<a href="https://colab.research.google.com/github/behraj/journals/blob/main/Cross_Validation_%26_C3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TAI-2023-Experiments

## Hold-out Cross-val

### MNIST - Batches 1

In [ ]:
## Model 1

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
# Load the MNIST dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Flatten the input images
x_train = x_train.reshape(-1, 784)
x_test = x_test.reshape(-1, 784)

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Convert the labels to one-hot encoding
num_classes = 10
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Define the model architecture
model = Sequential([
    Dense(64, activation='relu', input_shape=(784,)),
    Dense(64, activation='relu'),
    Dense(num_classes, activation='softmax')
])

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Perform hold-out cross-validation
# num_folds = 5
validation_scores = []

# for fold in range(num_folds):
#     # Split the data into train and validation sets
#     x_train_fold, x_val_fold, y_train_fold, y_val_fold = train_test_split(x_train, y_train, test_size=0.2, random_state=fold)

    # Train the model on the train set
model.fit(x_train, y_train, batch_size=128, epochs=10, verbose=1)

    # Evaluate the model on the validation set
_, val_accuracy = model.evaluate(x_test, y_test, verbose=0)
validation_scores.append(val_accuracy)

# Compute the average validation score
average_validation_score = np.mean(validation_scores)
print("Average Validation Score:", average_validation_score)

# Evaluate the model on the test set
_, test_accuracy = model.evaluate(x_test, y_test, verbose=0)
print("Test Accuracy:", test_accuracy)

Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
11490434/11490434 [==============================] - 2s 0us/step
Epoch 1/10
469/469 [==============================] - 7s 3ms/step - loss: 0.3885 - accuracy: 0.8912
Epoch 2/10
469/469 [==============================] - 2s 3ms/step - loss: 0.1608 - accuracy: 0.9536
Epoch 3/10
469/469 [==============================] - 2s 3ms/step - loss: 0.1163 - accuracy: 0.9657
Epoch 4/10
469/469 [==============================] - 2s 4ms/step - loss: 0.0915 - accuracy: 0.9728
Epoch 5/10
469/469 [==============================] - 2s 5ms/step - loss: 0.0757 - accuracy: 0.9773
Epoch 6/10
469/469 [==============================] - 2s 4ms/step - loss: 0.0645 - accuracy: 0.9803
Epoch 7/10
469/469 [==============================] - 2s 3ms/step - loss: 0.0563 - accuracy: 0.9831
Epoch 8/10
469/469 [==============================] - 2s 3ms/step - loss: 0.0489 - accuracy: 0.9851
Epoch 9/10
469/469 [==============================] - 2s 3ms/step - loss: 0.0420 - accuracy: 0.9870
Epoch 10/10
469/469 [==============================] - 2s 4ms/step - loss: 0.0378 - accuracy: 0.9882
Average Validation Score: 0.9753000140190125
Test Accuracy: 0.9753000140190125

In [ ]:
## Model 2

In [ ]:
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

# Load the Fashion MNIST dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Flatten the input images
x_train = x_train.reshape(-1, 784)
x_test = x_test.reshape(-1, 784)

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Convert the labels to one-hot encoding
num_classes = 10
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the data into train and test sets
test_size = 0.2
x_train, x_test, y_train, y_test = train_test_split(x_train, y_train, test_size=test_size, random_state=42)

# Define the model architecture
model = Sequential([
    Dense(64, activation='relu', input_shape=(784,)),
    Dense(32, activation='relu'),
    Dense(num_classes, activation='softmax')
])

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on the train set
model.fit(x_train, y_train, batch_size=128, epochs=10, verbose=1)

# Evaluate the model on the test set
_, test_accuracy = model.evaluate(x_test, y_test, verbose=0)
print("Test Accuracy:", test_accuracy)

Epoch 1/10
375/375 [==============================] - 2s 3ms/step - loss: 0.4587 - accuracy: 0.8727
Epoch 2/10
375/375 [==============================] - 1s 4ms/step - loss: 0.1992 - accuracy: 0.9432
Epoch 3/10
375/375 [==============================] - 2s 4ms/step - loss: 0.1525 - accuracy: 0.9553
Epoch 4/10
375/375 [==============================] - 1s 3ms/step - loss: 0.1215 - accuracy: 0.9651
Epoch 5/10
375/375 [==============================] - 1s 3ms/step - loss: 0.1030 - accuracy: 0.9690
Epoch 6/10
375/375 [==============================] - 1s 3ms/step - loss: 0.0872 - accuracy: 0.9736
Epoch 7/10
375/375 [==============================] - 1s 3ms/step - loss: 0.0746 - accuracy: 0.9777
Epoch 8/10
375/375 [==============================] - 1s 3ms/step - loss: 0.0654 - accuracy: 0.9800
Epoch 9/10
375/375 [==============================] - 1s 3ms/step - loss: 0.0566 - accuracy: 0.9831
Epoch 10/10
375/375 [==============================] - 1s 3ms/step - loss: 0.0494 - accuracy: 0.9856
Test Accuracy: 0.9705833196640015

### Fashion MNIST - Batches 1

In [ ]:
import numpy as np
from tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

# Load the Fashion MNIST dataset
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

# Define the model architecture
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(10)])
model.compile(optimizer='adam',
                   loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                   metrics=['accuracy'])
# model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on the train set
model.fit(x_train, y_train, batch_size=128, epochs=10, verbose=1)

# Evaluate the model on the test set
_, test_accuracy = model.evaluate(x_test, y_test, verbose=0)
print("Test Accuracy:", test_accuracy)

Epoch 1/10
469/469 [==============================] - 2s 3ms/step - loss: 6.3382 - accuracy: 0.7112
Epoch 2/10
469/469 [==============================] - 1s 3ms/step - loss: 0.8351 - accuracy: 0.7365
Epoch 3/10
469/469 [==============================] - 1s 3ms/step - loss: 0.6562 - accuracy: 0.7671
Epoch 4/10
469/469 [==============================] - 2s 4ms/step - loss: 0.5864 - accuracy: 0.7882
Epoch 5/10
469/469 [==============================] - 2s 4ms/step - loss: 0.5375 - accuracy: 0.8001
Epoch 6/10
469/469 [==============================] - 1s 3ms/step - loss: 0.4944 - accuracy: 0.8184
Epoch 7/10
469/469 [==============================] - 1s 3ms/step - loss: 0.4703 - accuracy: 0.8268
Epoch 8/10
469/469 [==============================] - 1s 3ms/step - loss: 0.4409 - accuracy: 0.8360
Epoch 9/10
469/469 [==============================] - 1s 3ms/step - loss: 0.4226 - accuracy: 0.8442
Epoch 10/10
469/469 [==============================] - 1s 3ms/step - loss: 0.4159 - accuracy: 0.8468
Test Accuracy: 0.8238999843597412



```
# This is formatted as code
```

### Kuzushiji-MNIST - Batches 1

In [ ]:
import numpy as np
import tensorflow as tf
# from tensorflow.keras.datasets import kmnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam
import tensorflow_datasets as tfds
import numpy as np
from sklearn.model_selection import train_test_split
# # Load the CIFAR-10 dataset
# (x_train, y_train), (x_test, y_test) = kmnist.load_data()


dataset = tfds.load('kmnist')
train_o, test_o = dataset['train'], dataset['test']

train_numpy = np.vstack(tfds.as_numpy(train_o))
test_numpy = np.vstack(tfds.as_numpy(test_o))

train_x = np.array(list(map(lambda x: x[0]['image'], train_numpy)))
train_y = np.array(list(map(lambda x: x[0]['label'], train_numpy)))

test_x = np.array(list(map(lambda x: x[0]['image'], test_numpy)))
test_y = np.array(list(map(lambda x: x[0]['label'], test_numpy)))

train = np.concatenate((train_x,test_x), axis = 0)
test = np.concatenate((train_y,test_y),axis = 0)

print("it is whole train size ****:\t", train_x.shape)

x_train, x_test, y_train, y_test = train_x, test_x, train_y, test_y


num_classes = 10

# Define the model architecture
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(num_classes)])
model.compile(optimizer='adam',
                   loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                   metrics=['accuracy'])
# model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on the train set
model.fit(x_train, y_train, batch_size=128, epochs=10, verbose=1)

# Evaluate the model on the test set
_, test_accuracy = model.evaluate(x_test, y_test, verbose=0)
print("Test Accuracy:", test_accuracy)

<ipython-input-29-39d9fa2706a2>:17: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  train_numpy = np.vstack(tfds.as_numpy(train_o))
<ipython-input-29-39d9fa2706a2>:18: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  test_numpy = np.vstack(tfds.as_numpy(test_o))

it is whole train size ****:	 (60000, 28, 28, 1)
Epoch 1/10
469/469 [==============================] - 2s 3ms/step - loss: 5.6400 - accuracy: 0.6520
Epoch 2/10
469/469 [==============================] - 1s 3ms/step - loss: 0.9007 - accuracy: 0.7600
Epoch 3/10
469/469 [==============================] - 2s 4ms/step - loss: 0.6415 - accuracy: 0.8173
Epoch 4/10
469/469 [==============================] - 2s 5ms/step - loss: 0.5169 - accuracy: 0.8516
Epoch 5/10
469/469 [==============================] - 2s 4ms/step - loss: 0.4355 - accuracy: 0.8752
Epoch 6/10
469/469 [==============================] - 1s 3ms/step - loss: 0.3860 - accuracy: 0.8885
Epoch 7/10
469/469 [==============================] - 1s 3ms/step - loss: 0.3608 - accuracy: 0.8973
Epoch 8/10
469/469 [==============================] - 1s 3ms/step - loss: 0.3276 - accuracy: 0.9048
Epoch 9/10
469/469 [==============================] - 1s 3ms/step - loss: 0.3126 - accuracy: 0.9107
Epoch 10/10
469/469 [==============================] - 2s 4ms/step - loss: 0.2841 - accuracy: 0.9180
Test Accuracy: 0.7713000178337097

### PermutedMNIST - Batches 1

In [ ]:
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

# Load the Fashion MNIST dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()
# Flatten the input images
x_train = x_train.reshape(-1, 784)
x_test = x_test.reshape(-1, 784)

In [ ]:
# Permute the pixel order in the training and test set
permuted_indices = np.random.permutation(784)
x_train_permuted = x_train[:, permuted_indices]
x_test_permuted = x_test[:, permuted_indices]

In [ ]:
num_classes = 10

# Define the model architecture
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(784,)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(num_classes)])
model.compile(optimizer='adam',
                   loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                   metrics=['accuracy'])
# model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on the train set
model.fit(x_train, y_train, batch_size=128, epochs=10, verbose=1)

# Evaluate the model on the test set
_, test_accuracy = model.evaluate(x_test, y_test, verbose=0)
print("Test Accuracy:", test_accuracy)

Epoch 1/10
469/469 [==============================] - 3s 4ms/step - loss: 5.3501 - accuracy: 0.8676
Epoch 2/10
469/469 [==============================] - 2s 3ms/step - loss: 0.7817 - accuracy: 0.9155
Epoch 3/10
469/469 [==============================] - 1s 3ms/step - loss: 0.3793 - accuracy: 0.9294
Epoch 4/10
469/469 [==============================] - 1s 3ms/step - loss: 0.2504 - accuracy: 0.9431
Epoch 5/10
469/469 [==============================] - 1s 3ms/step - loss: 0.1964 - accuracy: 0.9520
Epoch 6/10
469/469 [==============================] - 1s 3ms/step - loss: 0.1635 - accuracy: 0.9588
Epoch 7/10
469/469 [==============================] - 1s 3ms/step - loss: 0.1430 - accuracy: 0.9629
Epoch 8/10
469/469 [==============================] - 1s 3ms/step - loss: 0.1349 - accuracy: 0.9636
Epoch 9/10
469/469 [==============================] - 2s 4ms/step - loss: 0.1281 - accuracy: 0.9661
Epoch 10/10
469/469 [==============================] - 2s 4ms/step - loss: 0.1268 - accuracy: 0.9658
Test Accuracy: 0.9516000151634216

## CV

### MNIST-C

In [ ]:
import numpy as np
import tensorflow as tf
import tensorflow_datasets as tfds
from sklearn.model_selection import KFold
from keras.models import Sequential
from keras.layers import Dense, Flatten
import tensorflow_datasets as tfds
from sklearn.model_selection import train_test_split
# # Load the MNIST-C dataset
# dataset = tfds.load('mnist_corrupted', split='train')
# data = list(dataset.as_numpy_iterator())
# images = np.array([example['image'] for example in data])
# labels = np.array([example['label'] for example in data])


# Load MNIST-C dataset
dataset, info = tfds.load('mnist_corrupted', split='train+test', with_info=True)

# Extract x and y from the dataset
data = list(dataset)
x_data = [item['image'] for item in data]
y_data = [item['label'] for item in data]

# Convert x_data and y_data to numpy arrays
x_data = np.array(x_data)
y_data = np.array(y_data)

# Normalize pixel values to range [0, 1]
x_data = x_data.astype('float32') / 255.0

# Split the data into training and test sets
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=42)

# Flatten the images for logistic regression (assuming images are 28x28)
# x_train = x_train.reshape(x_train.shape[0], -1)
# x_test = x_test.reshape(x_test.shape[0], -1)


num_classes = 10

Downloading and preparing dataset 235.23 MiB (download: 235.23 MiB, generated: Unknown size, total: 235.23 MiB) to /root/tensorflow_datasets/mnist_corrupted/identity/1.0.0...

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

Generating splits...:   0%|          | 0/2 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/60000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/mnist_corrupted/identity/1.0.0.incomplete0D7PAH/mnist_corrupted-train.tfre…

Generating test examples...:   0%|          | 0/10000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/mnist_corrupted/identity/1.0.0.incomplete0D7PAH/mnist_corrupted-test.tfrec…

Dataset mnist_corrupted downloaded and prepared to /root/tensorflow_datasets/mnist_corrupted/identity/1.0.0. Subsequent calls will reuse this data.

In [ ]:
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(14000, 784) (14000, 784) (56000,) (14000,)

#### Holdout-CV

In [ ]:
import tensorflow as tf
# Define the model architecture
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(784,)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(num_classes)])
model.compile(optimizer='adam',
                   loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                   metrics=['accuracy'])
# model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on the train set
model.fit(x_train, y_train, batch_size=128, epochs=10, verbose=1)

# Evaluate the model on the test set
_, test_accuracy = model.evaluate(x_test, y_test, verbose=0)
print("Test Accuracy:", test_accuracy)

Epoch 1/10
438/438 [==============================] - 8s 4ms/step - loss: 0.3699 - accuracy: 0.8984
Epoch 2/10
438/438 [==============================] - 2s 4ms/step - loss: 0.1719 - accuracy: 0.9509
Epoch 3/10
438/438 [==============================] - 2s 4ms/step - loss: 0.1246 - accuracy: 0.9639
Epoch 4/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0969 - accuracy: 0.9722
Epoch 5/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0780 - accuracy: 0.9773
Epoch 6/10
438/438 [==============================] - 2s 5ms/step - loss: 0.0652 - accuracy: 0.9812
Epoch 7/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0539 - accuracy: 0.9846
Epoch 8/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0459 - accuracy: 0.9869
Epoch 9/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0401 - accuracy: 0.9885
Epoch 10/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0339 - accuracy: 0.9904
Test Accuracy: 0.9770714044570923

#### MNIST-C Batches 20

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.optimizers import Adam


# Normalize the input data
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

# Convert the labels to one-hot encoding
num_classes = 10
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training set into 20 batches
num_batches = 20
x_train_batches = np.array_split(x_train, num_batches)
y_train_batches = np.array_split(y_train, num_batches)

# Initialize the list to store test accuracies
accuracies = []

# Define the model architecture
model = Sequential([
    Flatten(input_shape=(28, 28, 1)),
    Dense(128, activation='relu'),
    Dense(num_classes, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch
epochs = 10
for i in range(num_batches):
    x_train_batch = x_train_batches[i]
    y_train_batch = y_train_batches[i]
    model.fit(x_train_batch, y_train_batch, batch_size=128, epochs=epochs, verbose=1)

    # Evaluate the model on the test set
    test_loss, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy (Batch {}): {:.2f}%".format(i+1, test_accuracy*100))
    accuracies.append(test_accuracy)

# Print the batch accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Batch-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
22/22 [==============================] - 7s 5ms/step - loss: 2.2953 - accuracy: 0.2139
Epoch 2/10
22/22 [==============================] - 0s 5ms/step - loss: 2.2774 - accuracy: 0.2864
Epoch 3/10
22/22 [==============================] - 0s 5ms/step - loss: 2.2529 - accuracy: 0.3679
Epoch 4/10
22/22 [==============================] - 0s 5ms/step - loss: 2.2205 - accuracy: 0.3850
Epoch 5/10
22/22 [==============================] - 0s 4ms/step - loss: 2.1794 - accuracy: 0.4550
Epoch 6/10
22/22 [==============================] - 0s 6ms/step - loss: 2.1300 - accuracy: 0.4686
Epoch 7/10
22/22 [==============================] - 0s 8ms/step - loss: 2.0717 - accuracy: 0.5293
Epoch 8/10
22/22 [==============================] - 0s 6ms/step - loss: 2.0070 - accuracy: 0.5446
Epoch 9/10
22/22 [==============================] - 0s 9ms/step - loss: 1.9371 - accuracy: 0.5479
Epoch 10/10
22/22 [==============================] - 0s 6ms/step - loss: 1.8638 - accuracy: 0.5861
438/438 [==============================] - 2s 3ms/step - loss: 1.8333 - accuracy: 0.6037
Test Accuracy (Batch 1): 60.37%
Epoch 1/10
22/22 [==============================] - 0s 4ms/step - loss: 1.7922 - accuracy: 0.6229
Epoch 2/10
22/22 [==============================] - 0s 4ms/step - loss: 1.7145 - accuracy: 0.6275
Epoch 3/10
22/22 [==============================] - 0s 4ms/step - loss: 1.6403 - accuracy: 0.6379
Epoch 4/10
22/22 [==============================] - 0s 4ms/step - loss: 1.5679 - accuracy: 0.6575
Epoch 5/10
22/22 [==============================] - 0s 4ms/step - loss: 1.5001 - accuracy: 0.6839
Epoch 6/10
22/22 [==============================] - 0s 4ms/step - loss: 1.4352 - accuracy: 0.6857
Epoch 7/10
22/22 [==============================] - 0s 4ms/step - loss: 1.3740 - accuracy: 0.7021
Epoch 8/10
22/22 [==============================] - 0s 4ms/step - loss: 1.3171 - accuracy: 0.7264
Epoch 9/10
22/22 [==============================] - 0s 4ms/step - loss: 1.2635 - accuracy: 0.7257
Epoch 10/10
22/22 [==============================] - 0s 4ms/step - loss: 1.2135 - accuracy: 0.7407
438/438 [==============================] - 2s 3ms/step - loss: 1.2044 - accuracy: 0.7319
Test Accuracy (Batch 2): 73.19%
Epoch 1/10
22/22 [==============================] - 0s 5ms/step - loss: 1.1713 - accuracy: 0.7296
Epoch 2/10
22/22 [==============================] - 0s 4ms/step - loss: 1.1282 - accuracy: 0.7482
Epoch 3/10
22/22 [==============================] - 0s 6ms/step - loss: 1.0884 - accuracy: 0.7611
Epoch 4/10
22/22 [==============================] - 0s 5ms/step - loss: 1.0515 - accuracy: 0.7711
Epoch 5/10
22/22 [==============================] - 0s 5ms/step - loss: 1.0172 - accuracy: 0.7782
Epoch 6/10
22/22 [==============================] - 0s 5ms/step - loss: 0.9862 - accuracy: 0.7839
Epoch 7/10
22/22 [==============================] - 0s 5ms/step - loss: 0.9560 - accuracy: 0.7900
Epoch 8/10
22/22 [==============================] - 0s 4ms/step - loss: 0.9281 - accuracy: 0.7904
Epoch 9/10
22/22 [==============================] - 0s 4ms/step - loss: 0.9020 - accuracy: 0.8014
Epoch 10/10
22/22 [==============================] - 0s 5ms/step - loss: 0.8776 - accuracy: 0.8036
438/438 [==============================] - 2s 4ms/step - loss: 0.8824 - accuracy: 0.8034
Test Accuracy (Batch 3): 80.34%
Epoch 1/10
22/22 [==============================] - 0s 5ms/step - loss: 0.8677 - accuracy: 0.8104
Epoch 2/10
22/22 [==============================] - 0s 4ms/step - loss: 0.8442 - accuracy: 0.8104
Epoch 3/10
22/22 [==============================] - 0s 4ms/step - loss: 0.8221 - accuracy: 0.8093
Epoch 4/10
22/22 [==============================] - 0s 4ms/step - loss: 0.8013 - accuracy: 0.8221
Epoch 5/10
22/22 [==============================] - 0s 5ms/step - loss: 0.7813 - accuracy: 0.8225
Epoch 6/10
22/22 [==============================] - 0s 4ms/step - loss: 0.7628 - accuracy: 0.8264
Epoch 7/10
22/22 [==============================] - 0s 5ms/step - loss: 0.7459 - accuracy: 0.8325
Epoch 8/10
22/22 [==============================] - 0s 4ms/step - loss: 0.7289 - accuracy: 0.8329
Epoch 9/10
22/22 [==============================] - 0s 5ms/step - loss: 0.7138 - accuracy: 0.8361
Epoch 10/10
22/22 [==============================] - 0s 5ms/step - loss: 0.6985 - accuracy: 0.8396
438/438 [==============================] - 2s 4ms/step - loss: 0.7062 - accuracy: 0.8386
Test Accuracy (Batch 4): 83.86%
Epoch 1/10
22/22 [==============================] - 0s 5ms/step - loss: 0.6853 - accuracy: 0.8346
Epoch 2/10
22/22 [==============================] - 0s 4ms/step - loss: 0.6712 - accuracy: 0.8436
Epoch 3/10
22/22 [==============================] - 0s 4ms/step - loss: 0.6579 - accuracy: 0.8404
Epoch 4/10
22/22 [==============================] - 0s 5ms/step - loss: 0.6456 - accuracy: 0.8468
Epoch 5/10
22/22 [==============================] - 0s 5ms/step - loss: 0.6335 - accuracy: 0.8507
Epoch 6/10
22/22 [==============================] - 0s 4ms/step - loss: 0.6223 - accuracy: 0.8539
Epoch 7/10
22/22 [==============================] - 0s 5ms/step - loss: 0.6127 - accuracy: 0.8532
Epoch 8/10
22/22 [==============================] - 0s 4ms/step - loss: 0.6022 - accuracy: 0.8571
Epoch 9/10
22/22 [==============================] - 0s 5ms/step - loss: 0.5921 - accuracy: 0.8582
Epoch 10/10
22/22 [==============================] - 0s 6ms/step - loss: 0.5828 - accuracy: 0.8589
438/438 [==============================] - 2s 3ms/step - loss: 0.6015 - accuracy: 0.8558
Test Accuracy (Batch 5): 85.58%
Epoch 1/10
22/22 [==============================] - 0s 4ms/step - loss: 0.5828 - accuracy: 0.8604
Epoch 2/10
22/22 [==============================] - 0s 5ms/step - loss: 0.5726 - accuracy: 0.8604
Epoch 3/10
22/22 [==============================] - 0s 4ms/step - loss: 0.5629 - accuracy: 0.8639
Epoch 4/10
22/22 [==============================] - 0s 5ms/step - loss: 0.5541 - accuracy: 0.8664
Epoch 5/10
22/22 [==============================] - 0s 5ms/step - loss: 0.5459 - accuracy: 0.8686
Epoch 6/10
22/22 [==============================] - 0s 5ms/step - loss: 0.5382 - accuracy: 0.8729
Epoch 7/10
22/22 [==============================] - 0s 5ms/step - loss: 0.5311 - accuracy: 0.8729
Epoch 8/10
22/22 [==============================] - 0s 5ms/step - loss: 0.5231 - accuracy: 0.8786
Epoch 9/10
22/22 [==============================] - 0s 5ms/step - loss: 0.5166 - accuracy: 0.8764
Epoch 10/10
22/22 [==============================] - 0s 5ms/step - loss: 0.5094 - accuracy: 0.8782
438/438 [==============================] - 2s 4ms/step - loss: 0.5332 - accuracy: 0.8686
Test Accuracy (Batch 6): 86.86%
Epoch 1/10
22/22 [==============================] - 0s 12ms/step - loss: 0.5283 - accuracy: 0.8607
Epoch 2/10
22/22 [==============================] - 0s 9ms/step - loss: 0.5210 - accuracy: 0.8671
Epoch 3/10
22/22 [==============================] - 0s 7ms/step - loss: 0.5149 - accuracy: 0.8700
Epoch 4/10
22/22 [==============================] - 0s 7ms/step - loss: 0.5077 - accuracy: 0.8718
Epoch 5/10
22/22 [==============================] - 0s 8ms/step - loss: 0.5011 - accuracy: 0.8721
Epoch 6/10
22/22 [==============================] - 0s 7ms/step - loss: 0.4954 - accuracy: 0.8721
Epoch 7/10
22/22 [==============================] - 0s 7ms/step - loss: 0.4893 - accuracy: 0.8743
Epoch 8/10
22/22 [==============================] - 0s 6ms/step - loss: 0.4834 - accuracy: 0.8771
Epoch 9/10
22/22 [==============================] - 0s 6ms/step - loss: 0.4776 - accuracy: 0.8789
Epoch 10/10
22/22 [==============================] - 0s 7ms/step - loss: 0.4725 - accuracy: 0.8786
438/438 [==============================] - 2s 3ms/step - loss: 0.4849 - accuracy: 0.8788
Test Accuracy (Batch 7): 87.88%
Epoch 1/10
22/22 [==============================] - 0s 5ms/step - loss: 0.4783 - accuracy: 0.8807
Epoch 2/10
22/22 [==============================] - 0s 5ms/step - loss: 0.4716 - accuracy: 0.8836
Epoch 3/10
22/22 [==============================] - 0s 6ms/step - loss: 0.4649 - accuracy: 0.8839
Epoch 4/10
22/22 [==============================] - 0s 5ms/step - loss: 0.4588 - accuracy: 0.8843
Epoch 5/10
22/22 [==============================] - 0s 5ms/step - loss: 0.4538 - accuracy: 0.8846
Epoch 6/10
22/22 [==============================] - 0s 5ms/step - loss: 0.4486 - accuracy: 0.8864
Epoch 7/10
22/22 [==============================] - 0s 4ms/step - loss: 0.4433 - accuracy: 0.8857
Epoch 8/10
22/22 [==============================] - 0s 5ms/step - loss: 0.4388 - accuracy: 0.8889
Epoch 9/10
22/22 [==============================] - 0s 4ms/step - loss: 0.4344 - accuracy: 0.8879
Epoch 10/10
22/22 [==============================] - 0s 6ms/step - loss: 0.4312 - accuracy: 0.8889
438/438 [==============================] - 2s 3ms/step - loss: 0.4475 - accuracy: 0.8858
Test Accuracy (Batch 8): 88.58%
Epoch 1/10
22/22 [==============================] - 0s 5ms/step - loss: 0.4443 - accuracy: 0.8746
Epoch 2/10
22/22 [==============================] - 0s 5ms/step - loss: 0.4398 - accuracy: 0.8768
Epoch 3/10
22/22 [==============================] - 0s 5ms/step - loss: 0.4363 - accuracy: 0.8793
Epoch 4/10
22/22 [==============================] - 0s 5ms/step - loss: 0.4320 - accuracy: 0.8764
Epoch 5/10
22/22 [==============================] - 0s 5ms/step - loss: 0.4282 - accuracy: 0.8800
Epoch 6/10
22/22 [==============================] - 0s 4ms/step - loss: 0.4238 - accuracy: 0.8800
Epoch 7/10
22/22 [==============================] - 0s 4ms/step - loss: 0.4202 - accuracy: 0.8804
Epoch 8/10
22/22 [==============================] - 0s 4ms/step - loss: 0.4165 - accuracy: 0.8814
Epoch 9/10
22/22 [==============================] - 0s 5ms/step - loss: 0.4133 - accuracy: 0.8800
Epoch 10/10
22/22 [==============================] - 0s 5ms/step - loss: 0.4101 - accuracy: 0.8850
438/438 [==============================] - 2s 4ms/step - loss: 0.4212 - accuracy: 0.8891
Test Accuracy (Batch 9): 88.91%
Epoch 1/10
22/22 [==============================] - 0s 6ms/step - loss: 0.4309 - accuracy: 0.8829
Epoch 2/10
22/22 [==============================] - 0s 6ms/step - loss: 0.4267 - accuracy: 0.8882
Epoch 3/10
22/22 [==============================] - 0s 5ms/step - loss: 0.4218 - accuracy: 0.8900
Epoch 4/10
22/22 [==============================] - 0s 8ms/step - loss: 0.4184 - accuracy: 0.8914
Epoch 5/10
22/22 [==============================] - 0s 10ms/step - loss: 0.4145 - accuracy: 0.8900
Epoch 6/10
22/22 [==============================] - 0s 11ms/step - loss: 0.4102 - accuracy: 0.8918
Epoch 7/10
22/22 [==============================] - 0s 6ms/step - loss: 0.4063 - accuracy: 0.8921
Epoch 8/10
22/22 [==============================] - 0s 6ms/step - loss: 0.4037 - accuracy: 0.8932
Epoch 9/10
22/22 [==============================] - 0s 7ms/step - loss: 0.4006 - accuracy: 0.8939
Epoch 10/10
22/22 [==============================] - 0s 6ms/step - loss: 0.3964 - accuracy: 0.8946
438/438 [==============================] - 2s 4ms/step - loss: 0.3985 - accuracy: 0.8935
Test Accuracy (Batch 10): 89.35%
Epoch 1/10
22/22 [==============================] - 0s 5ms/step - loss: 0.4047 - accuracy: 0.8846
Epoch 2/10
22/22 [==============================] - 0s 6ms/step - loss: 0.4013 - accuracy: 0.8861
Epoch 3/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3978 - accuracy: 0.8896
Epoch 4/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3947 - accuracy: 0.8896
Epoch 5/10
22/22 [==============================] - 0s 6ms/step - loss: 0.3908 - accuracy: 0.8900
Epoch 6/10
22/22 [==============================] - 0s 6ms/step - loss: 0.3881 - accuracy: 0.8911
Epoch 7/10
22/22 [==============================] - 0s 4ms/step - loss: 0.3861 - accuracy: 0.8943
Epoch 8/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3827 - accuracy: 0.8907
Epoch 9/10
22/22 [==============================] - 0s 4ms/step - loss: 0.3803 - accuracy: 0.8936
Epoch 10/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3777 - accuracy: 0.8950
438/438 [==============================] - 2s 3ms/step - loss: 0.3839 - accuracy: 0.8972
Test Accuracy (Batch 11): 89.72%
Epoch 1/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3901 - accuracy: 0.8904
Epoch 2/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3860 - accuracy: 0.8968
Epoch 3/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3824 - accuracy: 0.8943
Epoch 4/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3798 - accuracy: 0.8979
Epoch 5/10
22/22 [==============================] - 0s 4ms/step - loss: 0.3770 - accuracy: 0.8957
Epoch 6/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3743 - accuracy: 0.8971
Epoch 7/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3715 - accuracy: 0.8968
Epoch 8/10
22/22 [==============================] - 0s 4ms/step - loss: 0.3690 - accuracy: 0.8982
Epoch 9/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3667 - accuracy: 0.9004
Epoch 10/10
22/22 [==============================] - 0s 4ms/step - loss: 0.3646 - accuracy: 0.8986
438/438 [==============================] - 2s 4ms/step - loss: 0.3694 - accuracy: 0.8998
Test Accuracy (Batch 12): 89.98%
Epoch 1/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3768 - accuracy: 0.8979
Epoch 2/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3750 - accuracy: 0.9000
Epoch 3/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3720 - accuracy: 0.9014
Epoch 4/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3695 - accuracy: 0.9014
Epoch 5/10
22/22 [==============================] - 0s 6ms/step - loss: 0.3672 - accuracy: 0.9029
Epoch 6/10
22/22 [==============================] - 0s 6ms/step - loss: 0.3646 - accuracy: 0.9029
Epoch 7/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3615 - accuracy: 0.9032
Epoch 8/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3590 - accuracy: 0.9007
Epoch 9/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3566 - accuracy: 0.9054
Epoch 10/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3549 - accuracy: 0.9036
438/438 [==============================] - 2s 4ms/step - loss: 0.3589 - accuracy: 0.9016
Test Accuracy (Batch 13): 90.16%
Epoch 1/10
22/22 [==============================] - 0s 6ms/step - loss: 0.3761 - accuracy: 0.8986
Epoch 2/10
22/22 [==============================] - 0s 7ms/step - loss: 0.3736 - accuracy: 0.9004
Epoch 3/10
22/22 [==============================] - 0s 7ms/step - loss: 0.3701 - accuracy: 0.9011
Epoch 4/10
22/22 [==============================] - 0s 6ms/step - loss: 0.3676 - accuracy: 0.9021
Epoch 5/10
22/22 [==============================] - 0s 7ms/step - loss: 0.3651 - accuracy: 0.9007
Epoch 6/10
22/22 [==============================] - 0s 6ms/step - loss: 0.3630 - accuracy: 0.9021
Epoch 7/10
22/22 [==============================] - 0s 8ms/step - loss: 0.3600 - accuracy: 0.9029
Epoch 8/10
22/22 [==============================] - 0s 8ms/step - loss: 0.3580 - accuracy: 0.9039
Epoch 9/10
22/22 [==============================] - 0s 8ms/step - loss: 0.3558 - accuracy: 0.9057
Epoch 10/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3537 - accuracy: 0.9050
438/438 [==============================] - 2s 5ms/step - loss: 0.3505 - accuracy: 0.9036
Test Accuracy (Batch 14): 90.36%
Epoch 1/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3602 - accuracy: 0.9032
Epoch 2/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3560 - accuracy: 0.9046
Epoch 3/10
22/22 [==============================] - 0s 6ms/step - loss: 0.3532 - accuracy: 0.9054
Epoch 4/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3502 - accuracy: 0.9057
Epoch 5/10
22/22 [==============================] - 0s 4ms/step - loss: 0.3474 - accuracy: 0.9054
Epoch 6/10
22/22 [==============================] - 0s 4ms/step - loss: 0.3449 - accuracy: 0.9064
Epoch 7/10
22/22 [==============================] - 0s 4ms/step - loss: 0.3437 - accuracy: 0.9075
Epoch 8/10
22/22 [==============================] - 0s 4ms/step - loss: 0.3405 - accuracy: 0.9079
Epoch 9/10
22/22 [==============================] - 0s 4ms/step - loss: 0.3384 - accuracy: 0.9100
Epoch 10/10
22/22 [==============================] - 0s 6ms/step - loss: 0.3366 - accuracy: 0.9086
438/438 [==============================] - 2s 4ms/step - loss: 0.3424 - accuracy: 0.9021
Test Accuracy (Batch 15): 90.21%
Epoch 1/10
22/22 [==============================] - 0s 6ms/step - loss: 0.3428 - accuracy: 0.9032
Epoch 2/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3396 - accuracy: 0.9046
Epoch 3/10
22/22 [==============================] - 0s 6ms/step - loss: 0.3372 - accuracy: 0.9029
Epoch 4/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3348 - accuracy: 0.9046
Epoch 5/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3320 - accuracy: 0.9050
Epoch 6/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3310 - accuracy: 0.9032
Epoch 7/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3282 - accuracy: 0.9061
Epoch 8/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3262 - accuracy: 0.9068
Epoch 9/10
22/22 [==============================] - 0s 6ms/step - loss: 0.3246 - accuracy: 0.9071
Epoch 10/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3222 - accuracy: 0.9107
438/438 [==============================] - 2s 3ms/step - loss: 0.3343 - accuracy: 0.9059
Test Accuracy (Batch 16): 90.59%
Epoch 1/10
22/22 [==============================] - 0s 7ms/step - loss: 0.3308 - accuracy: 0.9071
Epoch 2/10
22/22 [==============================] - 0s 6ms/step - loss: 0.3284 - accuracy: 0.9086
Epoch 3/10
22/22 [==============================] - 0s 6ms/step - loss: 0.3264 - accuracy: 0.9079
Epoch 4/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3244 - accuracy: 0.9118
Epoch 5/10
22/22 [==============================] - 0s 6ms/step - loss: 0.3220 - accuracy: 0.9096
Epoch 6/10
22/22 [==============================] - 0s 6ms/step - loss: 0.3201 - accuracy: 0.9118
Epoch 7/10
22/22 [==============================] - 0s 6ms/step - loss: 0.3184 - accuracy: 0.9143
Epoch 8/10
22/22 [==============================] - 0s 7ms/step - loss: 0.3168 - accuracy: 0.9111
Epoch 9/10
22/22 [==============================] - 0s 7ms/step - loss: 0.3144 - accuracy: 0.9139
Epoch 10/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3133 - accuracy: 0.9143
438/438 [==============================] - 2s 4ms/step - loss: 0.3289 - accuracy: 0.9081
Test Accuracy (Batch 17): 90.81%
Epoch 1/10
22/22 [==============================] - 0s 5ms/step - loss: 0.2943 - accuracy: 0.9164
Epoch 2/10
22/22 [==============================] - 0s 5ms/step - loss: 0.2923 - accuracy: 0.9171
Epoch 3/10
22/22 [==============================] - 0s 5ms/step - loss: 0.2901 - accuracy: 0.9179
Epoch 4/10
22/22 [==============================] - 0s 5ms/step - loss: 0.2878 - accuracy: 0.9179
Epoch 5/10
22/22 [==============================] - 0s 5ms/step - loss: 0.2857 - accuracy: 0.9193
Epoch 6/10
22/22 [==============================] - 0s 5ms/step - loss: 0.2842 - accuracy: 0.9193
Epoch 7/10
22/22 [==============================] - 0s 6ms/step - loss: 0.2817 - accuracy: 0.9204
Epoch 8/10
22/22 [==============================] - 0s 5ms/step - loss: 0.2801 - accuracy: 0.9200
Epoch 9/10
22/22 [==============================] - 0s 5ms/step - loss: 0.2785 - accuracy: 0.9204
Epoch 10/10
22/22 [==============================] - 0s 5ms/step - loss: 0.2764 - accuracy: 0.9218
438/438 [==============================] - 2s 4ms/step - loss: 0.3235 - accuracy: 0.9084
Test Accuracy (Batch 18): 90.84%
Epoch 1/10
22/22 [==============================] - 0s 5ms/step - loss: 0.3375 - accuracy: 0.9039
Epoch 2/10

#### Batches 10

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.optimizers import Adam

x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=42)
# Normalize the input data
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

# Convert the labels to one-hot encoding
num_classes = 10
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training set into 20 batches
num_batches = 10
x_train_batches = np.array_split(x_train, num_batches)
y_train_batches = np.array_split(y_train, num_batches)

# Initialize the list to store test accuracies
accuracies = []

# Define the model architecture
model = Sequential([
    Flatten(input_shape=(28, 28, 1)),
    Dense(128, activation='relu'),
    Dense(num_classes, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch
epochs = 10
for i in range(num_batches):
    x_train_batch = x_train_batches[i]
    y_train_batch = y_train_batches[i]
    model.fit(x_train_batch, y_train_batch, batch_size=128, epochs=epochs, verbose=1)

    # Evaluate the model on the test set
    test_loss, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy (Batch {}): {:.2f}%".format(i+1, test_accuracy*100))
    accuracies.append(test_accuracy)

# Print the batch accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Batch-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
44/44 [==============================] - 2s 5ms/step - loss: 2.2897 - accuracy: 0.2116
Epoch 2/10
44/44 [==============================] - 0s 4ms/step - loss: 2.2489 - accuracy: 0.3455
Epoch 3/10
44/44 [==============================] - 0s 4ms/step - loss: 2.1803 - accuracy: 0.4250
Epoch 4/10
44/44 [==============================] - 0s 4ms/step - loss: 2.0817 - accuracy: 0.4882
Epoch 5/10
44/44 [==============================] - 0s 4ms/step - loss: 1.9606 - accuracy: 0.5641
Epoch 6/10
44/44 [==============================] - 0s 5ms/step - loss: 1.8284 - accuracy: 0.5850
Epoch 7/10
44/44 [==============================] - 0s 5ms/step - loss: 1.6941 - accuracy: 0.6477
Epoch 8/10
44/44 [==============================] - 0s 5ms/step - loss: 1.5661 - accuracy: 0.6771
Epoch 9/10
44/44 [==============================] - 0s 5ms/step - loss: 1.4481 - accuracy: 0.7134
Epoch 10/10
44/44 [==============================] - 0s 4ms/step - loss: 1.3427 - accuracy: 0.7309
438/438 [==============================] - 2s 3ms/step - loss: 1.3034 - accuracy: 0.7359
Test Accuracy (Batch 1): 73.59%
Epoch 1/10
44/44 [==============================] - 0s 4ms/step - loss: 1.2465 - accuracy: 0.7302
Epoch 2/10
44/44 [==============================] - 0s 4ms/step - loss: 1.1637 - accuracy: 0.7443
Epoch 3/10
44/44 [==============================] - 0s 4ms/step - loss: 1.0910 - accuracy: 0.7664
Epoch 4/10
44/44 [==============================] - 0s 5ms/step - loss: 1.0279 - accuracy: 0.7757
Epoch 5/10
44/44 [==============================] - 0s 5ms/step - loss: 0.9718 - accuracy: 0.7921
Epoch 6/10
44/44 [==============================] - 0s 4ms/step - loss: 0.9218 - accuracy: 0.7987
Epoch 7/10
44/44 [==============================] - 0s 5ms/step - loss: 0.8768 - accuracy: 0.8079
Epoch 8/10
44/44 [==============================] - 0s 6ms/step - loss: 0.8366 - accuracy: 0.8182
Epoch 9/10
44/44 [==============================] - 0s 6ms/step - loss: 0.8006 - accuracy: 0.8241
Epoch 10/10
44/44 [==============================] - 0s 5ms/step - loss: 0.7678 - accuracy: 0.8300
438/438 [==============================] - 2s 4ms/step - loss: 0.7664 - accuracy: 0.8273
Test Accuracy (Batch 2): 82.73%
Epoch 1/10
44/44 [==============================] - 0s 4ms/step - loss: 0.7365 - accuracy: 0.8313
Epoch 2/10
44/44 [==============================] - 0s 4ms/step - loss: 0.7074 - accuracy: 0.8386
Epoch 3/10
44/44 [==============================] - 0s 5ms/step - loss: 0.6821 - accuracy: 0.8438
Epoch 4/10
44/44 [==============================] - 0s 4ms/step - loss: 0.6580 - accuracy: 0.8445
Epoch 5/10
44/44 [==============================] - 0s 5ms/step - loss: 0.6370 - accuracy: 0.8482
Epoch 6/10
44/44 [==============================] - 0s 4ms/step - loss: 0.6175 - accuracy: 0.8509
Epoch 7/10
44/44 [==============================] - 0s 4ms/step - loss: 0.5997 - accuracy: 0.8559
Epoch 8/10
44/44 [==============================] - 0s 5ms/step - loss: 0.5834 - accuracy: 0.8571
Epoch 9/10
44/44 [==============================] - 0s 4ms/step - loss: 0.5670 - accuracy: 0.8620
Epoch 10/10
44/44 [==============================] - 0s 4ms/step - loss: 0.5529 - accuracy: 0.8625
438/438 [==============================] - 2s 3ms/step - loss: 0.5684 - accuracy: 0.8591
Test Accuracy (Batch 3): 85.91%
Epoch 1/10
44/44 [==============================] - 0s 4ms/step - loss: 0.5594 - accuracy: 0.8582
Epoch 2/10
44/44 [==============================] - 0s 5ms/step - loss: 0.5452 - accuracy: 0.8646
Epoch 3/10
44/44 [==============================] - 0s 4ms/step - loss: 0.5320 - accuracy: 0.8682
Epoch 4/10
44/44 [==============================] - 0s 4ms/step - loss: 0.5198 - accuracy: 0.8698
Epoch 5/10
44/44 [==============================] - 0s 4ms/step - loss: 0.5082 - accuracy: 0.8741
Epoch 6/10
44/44 [==============================] - 0s 4ms/step - loss: 0.4977 - accuracy: 0.8732
Epoch 7/10
44/44 [==============================] - 0s 5ms/step - loss: 0.4875 - accuracy: 0.8780
Epoch 8/10
44/44 [==============================] - 0s 4ms/step - loss: 0.4778 - accuracy: 0.8773
Epoch 9/10
44/44 [==============================] - 0s 5ms/step - loss: 0.4692 - accuracy: 0.8823
Epoch 10/10
44/44 [==============================] - 0s 5ms/step - loss: 0.4610 - accuracy: 0.8811
438/438 [==============================] - 1s 3ms/step - loss: 0.4718 - accuracy: 0.8800
Test Accuracy (Batch 4): 88.00%
Epoch 1/10
44/44 [==============================] - 0s 7ms/step - loss: 0.4719 - accuracy: 0.8743
Epoch 2/10
44/44 [==============================] - 0s 6ms/step - loss: 0.4638 - accuracy: 0.8761
Epoch 3/10
44/44 [==============================] - 0s 6ms/step - loss: 0.4580 - accuracy: 0.8768
Epoch 4/10
44/44 [==============================] - 0s 6ms/step - loss: 0.4505 - accuracy: 0.8775
Epoch 5/10
44/44 [==============================] - 0s 6ms/step - loss: 0.4437 - accuracy: 0.8798
Epoch 6/10
44/44 [==============================] - 0s 8ms/step - loss: 0.4378 - accuracy: 0.8809
Epoch 7/10
44/44 [==============================] - 0s 6ms/step - loss: 0.4318 - accuracy: 0.8804
Epoch 8/10
44/44 [==============================] - 0s 7ms/step - loss: 0.4262 - accuracy: 0.8820
Epoch 9/10
44/44 [==============================] - 0s 4ms/step - loss: 0.4210 - accuracy: 0.8846
Epoch 10/10
44/44 [==============================] - 0s 5ms/step - loss: 0.4160 - accuracy: 0.8871
438/438 [==============================] - 1s 3ms/step - loss: 0.4181 - accuracy: 0.8896
Test Accuracy (Batch 5): 88.96%
Epoch 1/10
44/44 [==============================] - 0s 4ms/step - loss: 0.4212 - accuracy: 0.8846
Epoch 2/10
44/44 [==============================] - 0s 4ms/step - loss: 0.4157 - accuracy: 0.8877
Epoch 3/10
44/44 [==============================] - 0s 4ms/step - loss: 0.4105 - accuracy: 0.8870
Epoch 4/10
44/44 [==============================] - 0s 4ms/step - loss: 0.4063 - accuracy: 0.8882
Epoch 5/10
44/44 [==============================] - 0s 4ms/step - loss: 0.4021 - accuracy: 0.8902
Epoch 6/10
44/44 [==============================] - 0s 5ms/step - loss: 0.3977 - accuracy: 0.8929
Epoch 7/10
44/44 [==============================] - 0s 4ms/step - loss: 0.3937 - accuracy: 0.8929
Epoch 8/10
44/44 [==============================] - 0s 4ms/step - loss: 0.3905 - accuracy: 0.8923
Epoch 9/10
44/44 [==============================] - 0s 4ms/step - loss: 0.3873 - accuracy: 0.8927
Epoch 10/10
44/44 [==============================] - 0s 4ms/step - loss: 0.3826 - accuracy: 0.8964
438/438 [==============================] - 1s 3ms/step - loss: 0.3859 - accuracy: 0.8966
Test Accuracy (Batch 6): 89.66%
Epoch 1/10
44/44 [==============================] - 0s 4ms/step - loss: 0.3956 - accuracy: 0.8920
Epoch 2/10
44/44 [==============================] - 0s 4ms/step - loss: 0.3915 - accuracy: 0.8936
Epoch 3/10
44/44 [==============================] - 0s 4ms/step - loss: 0.3870 - accuracy: 0.8970
Epoch 4/10
44/44 [==============================] - 0s 4ms/step - loss: 0.3835 - accuracy: 0.8968
Epoch 5/10
44/44 [==============================] - 0s 5ms/step - loss: 0.3803 - accuracy: 0.8993
Epoch 6/10
44/44 [==============================] - 0s 5ms/step - loss: 0.3765 - accuracy: 0.8984
Epoch 7/10
44/44 [==============================] - 0s 5ms/step - loss: 0.3736 - accuracy: 0.8998
Epoch 8/10
44/44 [==============================] - 0s 7ms/step - loss: 0.3701 - accuracy: 0.9000
Epoch 9/10
44/44 [==============================] - 0s 6ms/step - loss: 0.3672 - accuracy: 0.9011
Epoch 10/10
44/44 [==============================] - 0s 7ms/step - loss: 0.3643 - accuracy: 0.9021
438/438 [==============================] - 2s 4ms/step - loss: 0.3630 - accuracy: 0.9019
Test Accuracy (Batch 7): 90.19%
Epoch 1/10
44/44 [==============================] - 0s 4ms/step - loss: 0.3660 - accuracy: 0.9002
Epoch 2/10
44/44 [==============================] - 0s 4ms/step - loss: 0.3620 - accuracy: 0.9013
Epoch 3/10
44/44 [==============================] - 0s 4ms/step - loss: 0.3585 - accuracy: 0.9013
Epoch 4/10
44/44 [==============================] - 0s 4ms/step - loss: 0.3550 - accuracy: 0.9034
Epoch 5/10
44/44 [==============================] - 0s 5ms/step - loss: 0.3518 - accuracy: 0.9046
Epoch 6/10
44/44 [==============================] - 0s 4ms/step - loss: 0.3493 - accuracy: 0.9045
Epoch 7/10
44/44 [==============================] - 0s 4ms/step - loss: 0.3474 - accuracy: 0.9059
Epoch 8/10
44/44 [==============================] - 0s 5ms/step - loss: 0.3435 - accuracy: 0.9055
Epoch 9/10
44/44 [==============================] - 0s 4ms/step - loss: 0.3415 - accuracy: 0.9070
Epoch 10/10
44/44 [==============================] - 0s 4ms/step - loss: 0.3396 - accuracy: 0.9070
438/438 [==============================] - 1s 3ms/step - loss: 0.3463 - accuracy: 0.9026
Test Accuracy (Batch 8): 90.26%
Epoch 1/10
44/44 [==============================] - 0s 4ms/step - loss: 0.3263 - accuracy: 0.9107
Epoch 2/10
44/44 [==============================] - 0s 4ms/step - loss: 0.3232 - accuracy: 0.9100
Epoch 3/10
44/44 [==============================] - 0s 5ms/step - loss: 0.3208 - accuracy: 0.9118
Epoch 4/10
44/44 [==============================] - 0s 4ms/step - loss: 0.3180 - accuracy: 0.9139
Epoch 5/10
44/44 [==============================] - 0s 5ms/step - loss: 0.3158 - accuracy: 0.9118
Epoch 6/10
44/44 [==============================] - 0s 4ms/step - loss: 0.3135 - accuracy: 0.9137
Epoch 7/10
44/44 [==============================] - 0s 4ms/step - loss: 0.3112 - accuracy: 0.9155
Epoch 8/10
44/44 [==============================] - 0s 4ms/step - loss: 0.3094 - accuracy: 0.9145
Epoch 9/10
44/44 [==============================] - 0s 4ms/step - loss: 0.3073 - accuracy: 0.9150
Epoch 10/10
44/44 [==============================] - 0s 4ms/step - loss: 0.3048 - accuracy: 0.9148
438/438 [==============================] - 1s 3ms/step - loss: 0.3325 - accuracy: 0.9052
Test Accuracy (Batch 9): 90.52%
Epoch 1/10
44/44 [==============================] - 0s 4ms/step - loss: 0.3321 - accuracy: 0.9089
Epoch 2/10
44/44 [==============================] - 0s 5ms/step - loss: 0.3288 - accuracy: 0.9112
Epoch 3/10
44/44 [==============================] - 0s 4ms/step - loss: 0.3265 - accuracy: 0.9093
Epoch 4/10
44/44 [==============================] - 0s 4ms/step - loss: 0.3235 - accuracy: 0.9121
Epoch 5/10
44/44 [==============================] - 0s 4ms/step - loss: 0.3216 - accuracy: 0.9104
Epoch 6/10
44/44 [==============================] - 0s 6ms/step - loss: 0.3190 - accuracy: 0.9121
Epoch 7/10
44/44 [==============================] - 0s 6ms/step - loss: 0.3165 - accuracy: 0.9111
Epoch 8/10
44/44 [==============================] - 0s 7ms/step - loss: 0.3148 - accuracy: 0.9127
Epoch 9/10
44/44 [==============================] - 0s 6ms/step - loss: 0.3124 - accuracy: 0.9141
Epoch 10/10
44/44 [==============================] - 0s 6ms/step - loss: 0.3107 - accuracy: 0.9137
438/438 [==============================] - 2s 4ms/step - loss: 0.3213 - accuracy: 0.9077
Test Accuracy (Batch 10): 90.77%
Batch-1: 73.59%
Batch-2: 82.73%
Batch-3: 85.91%
Batch-4: 88.00%
Batch-5: 88.96%
Batch-6: 89.66%
Batch-7: 90.19%
Batch-8: 90.26%
Batch-9: 90.52%
Batch-10: 90.77%

#### Batches 6

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.optimizers import Adam

x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=42)
# Normalize the input data
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

# Convert the labels to one-hot encoding
num_classes = 10
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training set into 20 batches
num_batches = 6
x_train_batches = np.array_split(x_train, num_batches)
y_train_batches = np.array_split(y_train, num_batches)

# Initialize the list to store test accuracies
accuracies = []

# Define the model architecture
model = Sequential([
    Flatten(input_shape=(28, 28, 1)),
    Dense(128, activation='relu'),
    Dense(num_classes, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch
epochs = 10
for i in range(num_batches):
    x_train_batch = x_train_batches[i]
    y_train_batch = y_train_batches[i]
    model.fit(x_train_batch, y_train_batch, batch_size=128, epochs=epochs, verbose=1)

    # Evaluate the model on the test set
    test_loss, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy (Batch {}): {:.2f}%".format(i+1, test_accuracy*100))
    accuracies.append(test_accuracy)

# Print the batch accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Batch-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
73/73 [==============================] - 2s 7ms/step - loss: 2.2761 - accuracy: 0.3332
Epoch 2/10
73/73 [==============================] - 0s 6ms/step - loss: 2.1724 - accuracy: 0.4496
Epoch 3/10
73/73 [==============================] - 0s 6ms/step - loss: 1.9826 - accuracy: 0.5318
Epoch 4/10
73/73 [==============================] - 0s 7ms/step - loss: 1.7448 - accuracy: 0.5910
Epoch 5/10
73/73 [==============================] - 0s 7ms/step - loss: 1.5146 - accuracy: 0.6639
Epoch 6/10
73/73 [==============================] - 0s 5ms/step - loss: 1.3218 - accuracy: 0.7194
Epoch 7/10
73/73 [==============================] - 0s 5ms/step - loss: 1.1679 - accuracy: 0.7476
Epoch 8/10
73/73 [==============================] - 0s 5ms/step - loss: 1.0466 - accuracy: 0.7808
Epoch 9/10
73/73 [==============================] - 0s 5ms/step - loss: 0.9486 - accuracy: 0.7964
Epoch 10/10
73/73 [==============================] - 0s 4ms/step - loss: 0.8686 - accuracy: 0.8120
438/438 [==============================] - 2s 4ms/step - loss: 0.8442 - accuracy: 0.8108
Test Accuracy (Batch 1): 81.08%
Epoch 1/10
73/73 [==============================] - 0s 5ms/step - loss: 0.8026 - accuracy: 0.8137
Epoch 2/10
73/73 [==============================] - 0s 6ms/step - loss: 0.7463 - accuracy: 0.8235
Epoch 3/10
73/73 [==============================] - 0s 5ms/step - loss: 0.6997 - accuracy: 0.8323
Epoch 4/10
73/73 [==============================] - 0s 5ms/step - loss: 0.6595 - accuracy: 0.8400
Epoch 5/10
73/73 [==============================] - 0s 5ms/step - loss: 0.6247 - accuracy: 0.8458
Epoch 6/10
73/73 [==============================] - 0s 5ms/step - loss: 0.5942 - accuracy: 0.8527
Epoch 7/10
73/73 [==============================] - 0s 5ms/step - loss: 0.5679 - accuracy: 0.8573
Epoch 8/10
73/73 [==============================] - 0s 5ms/step - loss: 0.5445 - accuracy: 0.8627
Epoch 9/10
73/73 [==============================] - 0s 5ms/step - loss: 0.5246 - accuracy: 0.8659
Epoch 10/10
73/73 [==============================] - 0s 5ms/step - loss: 0.5058 - accuracy: 0.8702
438/438 [==============================] - 2s 5ms/step - loss: 0.5141 - accuracy: 0.8704
Test Accuracy (Batch 2): 87.04%
Epoch 1/10
73/73 [==============================] - 0s 6ms/step - loss: 0.5059 - accuracy: 0.8716
Epoch 2/10
73/73 [==============================] - 0s 6ms/step - loss: 0.4892 - accuracy: 0.8770
Epoch 3/10
73/73 [==============================] - 0s 5ms/step - loss: 0.4744 - accuracy: 0.8769
Epoch 4/10
73/73 [==============================] - 0s 4ms/step - loss: 0.4606 - accuracy: 0.8818
Epoch 5/10
73/73 [==============================] - 0s 5ms/step - loss: 0.4486 - accuracy: 0.8832
Epoch 6/10
73/73 [==============================] - 0s 4ms/step - loss: 0.4375 - accuracy: 0.8857
Epoch 7/10
73/73 [==============================] - 0s 4ms/step - loss: 0.4275 - accuracy: 0.8871
Epoch 8/10
73/73 [==============================] - 0s 5ms/step - loss: 0.4180 - accuracy: 0.8875
Epoch 9/10
73/73 [==============================] - 0s 5ms/step - loss: 0.4097 - accuracy: 0.8906
Epoch 10/10
73/73 [==============================] - 0s 5ms/step - loss: 0.4008 - accuracy: 0.8917
438/438 [==============================] - 1s 3ms/step - loss: 0.4083 - accuracy: 0.8910
Test Accuracy (Batch 3): 89.10%
Epoch 1/10
73/73 [==============================] - 0s 4ms/step - loss: 0.4127 - accuracy: 0.8856
Epoch 2/10
73/73 [==============================] - 0s 4ms/step - loss: 0.4049 - accuracy: 0.8888
Epoch 3/10
73/73 [==============================] - 0s 5ms/step - loss: 0.3983 - accuracy: 0.8903
Epoch 4/10
73/73 [==============================] - 0s 4ms/step - loss: 0.3919 - accuracy: 0.8935
Epoch 5/10
73/73 [==============================] - 0s 5ms/step - loss: 0.3862 - accuracy: 0.8937
Epoch 6/10
73/73 [==============================] - 0s 4ms/step - loss: 0.3815 - accuracy: 0.8955
Epoch 7/10
73/73 [==============================] - 0s 4ms/step - loss: 0.3762 - accuracy: 0.8970
Epoch 8/10
73/73 [==============================] - 0s 5ms/step - loss: 0.3716 - accuracy: 0.8975
Epoch 9/10
73/73 [==============================] - 0s 5ms/step - loss: 0.3672 - accuracy: 0.8984
Epoch 10/10
73/73 [==============================] - 0s 5ms/step - loss: 0.3631 - accuracy: 0.9005
438/438 [==============================] - 2s 3ms/step - loss: 0.3632 - accuracy: 0.9011
Test Accuracy (Batch 4): 90.11%
Epoch 1/10
73/73 [==============================] - 0s 6ms/step - loss: 0.3681 - accuracy: 0.9009
Epoch 2/10
73/73 [==============================] - 0s 5ms/step - loss: 0.3637 - accuracy: 0.9008
Epoch 3/10
73/73 [==============================] - 0s 5ms/step - loss: 0.3582 - accuracy: 0.9020
Epoch 4/10
73/73 [==============================] - 0s 6ms/step - loss: 0.3541 - accuracy: 0.9040
Epoch 5/10
73/73 [==============================] - 0s 6ms/step - loss: 0.3504 - accuracy: 0.9042
Epoch 6/10
73/73 [==============================] - 0s 7ms/step - loss: 0.3460 - accuracy: 0.9061
Epoch 7/10
73/73 [==============================] - 0s 5ms/step - loss: 0.3428 - accuracy: 0.9060
Epoch 8/10
73/73 [==============================] - 0s 4ms/step - loss: 0.3390 - accuracy: 0.9095
Epoch 9/10
73/73 [==============================] - 0s 5ms/step - loss: 0.3355 - accuracy: 0.9097
Epoch 10/10
73/73 [==============================] - 0s 4ms/step - loss: 0.3323 - accuracy: 0.9083
438/438 [==============================] - 2s 4ms/step - loss: 0.3371 - accuracy: 0.9054
Test Accuracy (Batch 5): 90.54%
Epoch 1/10
73/73 [==============================] - 0s 4ms/step - loss: 0.3241 - accuracy: 0.9103
Epoch 2/10
73/73 [==============================] - 0s 4ms/step - loss: 0.3193 - accuracy: 0.9128
Epoch 3/10
73/73 [==============================] - 0s 4ms/step - loss: 0.3158 - accuracy: 0.9135
Epoch 4/10
73/73 [==============================] - 0s 5ms/step - loss: 0.3117 - accuracy: 0.9141
Epoch 5/10
73/73 [==============================] - 0s 5ms/step - loss: 0.3091 - accuracy: 0.9140
Epoch 6/10
73/73 [==============================] - 0s 5ms/step - loss: 0.3055 - accuracy: 0.9158
Epoch 7/10
73/73 [==============================] - 0s 4ms/step - loss: 0.3033 - accuracy: 0.9156
Epoch 8/10
73/73 [==============================] - 0s 4ms/step - loss: 0.3005 - accuracy: 0.9173
Epoch 9/10
73/73 [==============================] - 0s 5ms/step - loss: 0.2983 - accuracy: 0.9167
Epoch 10/10
73/73 [==============================] - 0s 5ms/step - loss: 0.2952 - accuracy: 0.9179
438/438 [==============================] - 1s 3ms/step - loss: 0.3183 - accuracy: 0.9092
Test Accuracy (Batch 6): 90.92%
Batch-1: 81.08%
Batch-2: 87.04%
Batch-3: 89.10%
Batch-4: 90.11%
Batch-5: 90.54%
Batch-6: 90.92%

#### Batches 5

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.optimizers import Adam

x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=42)
# Normalize the input data
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

# Convert the labels to one-hot encoding
num_classes = 10
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training set into 20 batches
num_batches = 5
x_train_batches = np.array_split(x_train, num_batches)
y_train_batches = np.array_split(y_train, num_batches)

# Initialize the list to store test accuracies
accuracies = []

# Define the model architecture
model = Sequential([
    Flatten(input_shape=(28, 28, 1)),
    Dense(128, activation='relu'),
    Dense(num_classes, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch
epochs = 10
for i in range(num_batches):
    x_train_batch = x_train_batches[i]
    y_train_batch = y_train_batches[i]
    model.fit(x_train_batch, y_train_batch, batch_size=128, epochs=epochs, verbose=1)

    # Evaluate the model on the test set
    test_loss, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy (Batch {}): {:.2f}%".format(i+1, test_accuracy*100))
    accuracies.append(test_accuracy)

# Print the batch accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Batch-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
88/88 [==============================] - 2s 5ms/step - loss: 2.2683 - accuracy: 0.3640
Epoch 2/10
88/88 [==============================] - 0s 6ms/step - loss: 2.1153 - accuracy: 0.5097
Epoch 3/10
88/88 [==============================] - 0s 4ms/step - loss: 1.8448 - accuracy: 0.5792
Epoch 4/10
88/88 [==============================] - 0s 5ms/step - loss: 1.5522 - accuracy: 0.6495
Epoch 5/10
88/88 [==============================] - 0s 5ms/step - loss: 1.3092 - accuracy: 0.7204
Epoch 6/10
88/88 [==============================] - 0s 5ms/step - loss: 1.1254 - accuracy: 0.7613
Epoch 7/10
88/88 [==============================] - 0s 5ms/step - loss: 0.9871 - accuracy: 0.7915
Epoch 8/10
88/88 [==============================] - 0s 5ms/step - loss: 0.8808 - accuracy: 0.8116
Epoch 9/10
88/88 [==============================] - 0s 4ms/step - loss: 0.7968 - accuracy: 0.8248
Epoch 10/10
88/88 [==============================] - 0s 4ms/step - loss: 0.7296 - accuracy: 0.8372
438/438 [==============================] - 2s 3ms/step - loss: 0.7114 - accuracy: 0.8346
Test Accuracy (Batch 1): 83.46%
Epoch 1/10
88/88 [==============================] - 0s 5ms/step - loss: 0.6765 - accuracy: 0.8401
Epoch 2/10
88/88 [==============================] - 0s 4ms/step - loss: 0.6296 - accuracy: 0.8510
Epoch 3/10
88/88 [==============================] - 0s 5ms/step - loss: 0.5914 - accuracy: 0.8581
Epoch 4/10
88/88 [==============================] - 0s 6ms/step - loss: 0.5582 - accuracy: 0.8647
Epoch 5/10
88/88 [==============================] - 0s 5ms/step - loss: 0.5301 - accuracy: 0.8699
Epoch 6/10
88/88 [==============================] - 0s 6ms/step - loss: 0.5061 - accuracy: 0.8766
Epoch 7/10
88/88 [==============================] - 0s 6ms/step - loss: 0.4851 - accuracy: 0.8779
Epoch 8/10
88/88 [==============================] - 0s 5ms/step - loss: 0.4668 - accuracy: 0.8840
Epoch 9/10
88/88 [==============================] - 0s 4ms/step - loss: 0.4504 - accuracy: 0.8849
Epoch 10/10
88/88 [==============================] - 0s 4ms/step - loss: 0.4359 - accuracy: 0.8873
438/438 [==============================] - 2s 4ms/step - loss: 0.4468 - accuracy: 0.8865
Test Accuracy (Batch 2): 88.65%
Epoch 1/10
88/88 [==============================] - 0s 5ms/step - loss: 0.4460 - accuracy: 0.8796
Epoch 2/10
88/88 [==============================] - 0s 4ms/step - loss: 0.4332 - accuracy: 0.8813
Epoch 3/10
88/88 [==============================] - 0s 5ms/step - loss: 0.4226 - accuracy: 0.8847
Epoch 4/10
88/88 [==============================] - 0s 5ms/step - loss: 0.4125 - accuracy: 0.8857
Epoch 5/10
88/88 [==============================] - 0s 5ms/step - loss: 0.4043 - accuracy: 0.8886
Epoch 6/10
88/88 [==============================] - 0s 5ms/step - loss: 0.3960 - accuracy: 0.8908
Epoch 7/10
88/88 [==============================] - 0s 5ms/step - loss: 0.3892 - accuracy: 0.8924
Epoch 8/10
88/88 [==============================] - 0s 5ms/step - loss: 0.3823 - accuracy: 0.8922
Epoch 9/10
88/88 [==============================] - 0s 5ms/step - loss: 0.3764 - accuracy: 0.8956
Epoch 10/10
88/88 [==============================] - 0s 5ms/step - loss: 0.3704 - accuracy: 0.8963
438/438 [==============================] - 1s 3ms/step - loss: 0.3714 - accuracy: 0.9001
Test Accuracy (Batch 3): 90.01%
Epoch 1/10
88/88 [==============================] - 1s 6ms/step - loss: 0.3770 - accuracy: 0.8971
Epoch 2/10
88/88 [==============================] - 1s 7ms/step - loss: 0.3713 - accuracy: 0.8988
Epoch 3/10
88/88 [==============================] - 0s 5ms/step - loss: 0.3662 - accuracy: 0.9006
Epoch 4/10
88/88 [==============================] - 0s 4ms/step - loss: 0.3616 - accuracy: 0.9016
Epoch 5/10
88/88 [==============================] - 0s 4ms/step - loss: 0.3557 - accuracy: 0.9035
Epoch 6/10
88/88 [==============================] - 0s 4ms/step - loss: 0.3518 - accuracy: 0.9046
Epoch 7/10
88/88 [==============================] - 0s 4ms/step - loss: 0.3480 - accuracy: 0.9055
Epoch 8/10
88/88 [==============================] - 0s 4ms/step - loss: 0.3435 - accuracy: 0.9064
Epoch 9/10
88/88 [==============================] - 0s 4ms/step - loss: 0.3400 - accuracy: 0.9079
Epoch 10/10
88/88 [==============================] - 0s 4ms/step - loss: 0.3359 - accuracy: 0.9084
438/438 [==============================] - 1s 3ms/step - loss: 0.3371 - accuracy: 0.9056
Test Accuracy (Batch 4): 90.56%
Epoch 1/10
88/88 [==============================] - 0s 4ms/step - loss: 0.3266 - accuracy: 0.9115
Epoch 2/10
88/88 [==============================] - 0s 4ms/step - loss: 0.3226 - accuracy: 0.9112
Epoch 3/10
88/88 [==============================] - 0s 4ms/step - loss: 0.3180 - accuracy: 0.9141
Epoch 4/10
88/88 [==============================] - 0s 4ms/step - loss: 0.3143 - accuracy: 0.9139
Epoch 5/10
88/88 [==============================] - 0s 4ms/step - loss: 0.3113 - accuracy: 0.9146
Epoch 6/10
88/88 [==============================] - 0s 4ms/step - loss: 0.3086 - accuracy: 0.9148
Epoch 7/10
88/88 [==============================] - 0s 4ms/step - loss: 0.3048 - accuracy: 0.9168
Epoch 8/10
88/88 [==============================] - 0s 4ms/step - loss: 0.3018 - accuracy: 0.9162
Epoch 9/10
88/88 [==============================] - 0s 4ms/step - loss: 0.2998 - accuracy: 0.9171
Epoch 10/10
88/88 [==============================] - 0s 4ms/step - loss: 0.2974 - accuracy: 0.9169
438/438 [==============================] - 2s 5ms/step - loss: 0.3168 - accuracy: 0.9100
Test Accuracy (Batch 5): 91.00%
Batch-1: 83.46%
Batch-2: 88.65%
Batch-3: 90.01%
Batch-4: 90.56%
Batch-5: 91.00%

#### Batches 4

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.optimizers import Adam

x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=42)
# Normalize the input data
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

# Convert the labels to one-hot encoding
num_classes = 10
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training set into 20 batches
num_batches = 4
x_train_batches = np.array_split(x_train, num_batches)
y_train_batches = np.array_split(y_train, num_batches)

# Initialize the list to store test accuracies
accuracies = []

# Define the model architecture
model = Sequential([
    Flatten(input_shape=(28, 28, 1)),
    Dense(128, activation='relu'),
    Dense(num_classes, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch
epochs = 10
for i in range(num_batches):
    x_train_batch = x_train_batches[i]
    y_train_batch = y_train_batches[i]
    model.fit(x_train_batch, y_train_batch, batch_size=128, epochs=epochs, verbose=1)

    # Evaluate the model on the test set
    test_loss, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy (Batch {}): {:.2f}%".format(i+1, test_accuracy*100))
    accuracies.append(test_accuracy)

# Print the batch accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Batch-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
110/110 [==============================] - 2s 4ms/step - loss: 2.2488 - accuracy: 0.3711
Epoch 2/10
110/110 [==============================] - 0s 4ms/step - loss: 2.0083 - accuracy: 0.5109
Epoch 3/10
110/110 [==============================] - 0s 4ms/step - loss: 1.6437 - accuracy: 0.6239
Epoch 4/10
110/110 [==============================] - 0s 4ms/step - loss: 1.3281 - accuracy: 0.7120
Epoch 5/10
110/110 [==============================] - 0s 4ms/step - loss: 1.1054 - accuracy: 0.7657
Epoch 6/10
110/110 [==============================] - 0s 4ms/step - loss: 0.9486 - accuracy: 0.7989
Epoch 7/10
110/110 [==============================] - 1s 6ms/step - loss: 0.8342 - accuracy: 0.8162
Epoch 8/10
110/110 [==============================] - 1s 7ms/step - loss: 0.7463 - accuracy: 0.8318
Epoch 9/10
110/110 [==============================] - 1s 6ms/step - loss: 0.6781 - accuracy: 0.8413
Epoch 10/10
110/110 [==============================] - 1s 5ms/step - loss: 0.6235 - accuracy: 0.8513
438/438 [==============================] - 2s 4ms/step - loss: 0.6113 - accuracy: 0.8538
Test Accuracy (Batch 1): 85.38%
Epoch 1/10
110/110 [==============================] - 1s 5ms/step - loss: 0.5884 - accuracy: 0.8561
Epoch 2/10
110/110 [==============================] - 0s 4ms/step - loss: 0.5503 - accuracy: 0.8641
Epoch 3/10
110/110 [==============================] - 0s 4ms/step - loss: 0.5184 - accuracy: 0.8699
Epoch 4/10
110/110 [==============================] - 0s 4ms/step - loss: 0.4912 - accuracy: 0.8757
Epoch 5/10
110/110 [==============================] - 0s 4ms/step - loss: 0.4689 - accuracy: 0.8800
Epoch 6/10
110/110 [==============================] - 0s 4ms/step - loss: 0.4493 - accuracy: 0.8833
Epoch 7/10
110/110 [==============================] - 0s 4ms/step - loss: 0.4328 - accuracy: 0.8848
Epoch 8/10
110/110 [==============================] - 0s 4ms/step - loss: 0.4182 - accuracy: 0.8886
Epoch 9/10
110/110 [==============================] - 0s 4ms/step - loss: 0.4050 - accuracy: 0.8909
Epoch 10/10
110/110 [==============================] - 1s 5ms/step - loss: 0.3937 - accuracy: 0.8939
438/438 [==============================] - 2s 3ms/step - loss: 0.4020 - accuracy: 0.8935
Test Accuracy (Batch 2): 89.35%
Epoch 1/10
110/110 [==============================] - 0s 4ms/step - loss: 0.4051 - accuracy: 0.8890
Epoch 2/10
110/110 [==============================] - 0s 4ms/step - loss: 0.3958 - accuracy: 0.8927
Epoch 3/10
110/110 [==============================] - 0s 4ms/step - loss: 0.3867 - accuracy: 0.8949
Epoch 4/10
110/110 [==============================] - 1s 6ms/step - loss: 0.3791 - accuracy: 0.8959
Epoch 5/10
110/110 [==============================] - 1s 6ms/step - loss: 0.3725 - accuracy: 0.8972
Epoch 6/10
110/110 [==============================] - 1s 6ms/step - loss: 0.3664 - accuracy: 0.9004
Epoch 7/10
110/110 [==============================] - 1s 6ms/step - loss: 0.3602 - accuracy: 0.9010
Epoch 8/10
110/110 [==============================] - 0s 4ms/step - loss: 0.3553 - accuracy: 0.9025
Epoch 9/10
110/110 [==============================] - 0s 4ms/step - loss: 0.3500 - accuracy: 0.9038
Epoch 10/10
110/110 [==============================] - 0s 4ms/step - loss: 0.3461 - accuracy: 0.9046
438/438 [==============================] - 1s 3ms/step - loss: 0.3438 - accuracy: 0.9044
Test Accuracy (Batch 3): 90.44%
Epoch 1/10
110/110 [==============================] - 0s 4ms/step - loss: 0.3349 - accuracy: 0.9093
Epoch 2/10
110/110 [==============================] - 0s 4ms/step - loss: 0.3290 - accuracy: 0.9094
Epoch 3/10
110/110 [==============================] - 0s 5ms/step - loss: 0.3252 - accuracy: 0.9093
Epoch 4/10
110/110 [==============================] - 1s 5ms/step - loss: 0.3204 - accuracy: 0.9110
Epoch 5/10
110/110 [==============================] - 1s 8ms/step - loss: 0.3168 - accuracy: 0.9107
Epoch 6/10
110/110 [==============================] - 1s 7ms/step - loss: 0.3129 - accuracy: 0.9141
Epoch 7/10
110/110 [==============================] - 0s 4ms/step - loss: 0.3093 - accuracy: 0.9144
Epoch 8/10
110/110 [==============================] - 0s 4ms/step - loss: 0.3057 - accuracy: 0.9162
Epoch 9/10
110/110 [==============================] - 0s 4ms/step - loss: 0.3030 - accuracy: 0.9163
Epoch 10/10
110/110 [==============================] - 0s 4ms/step - loss: 0.2994 - accuracy: 0.9173
438/438 [==============================] - 1s 3ms/step - loss: 0.3168 - accuracy: 0.9103
Test Accuracy (Batch 4): 91.03%
Batch-1: 85.38%
Batch-2: 89.35%
Batch-3: 90.44%
Batch-4: 91.03%

#### Batches 2

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.optimizers import Adam

x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=42)
# Normalize the input data
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

# Convert the labels to one-hot encoding
num_classes = 10
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training set into 20 batches
num_batches = 2
x_train_batches = np.array_split(x_train, num_batches)
y_train_batches = np.array_split(y_train, num_batches)

# Initialize the list to store test accuracies
accuracies = []

# Define the model architecture
model = Sequential([
    Flatten(input_shape=(28, 28, 1)),
    Dense(128, activation='relu'),
    Dense(num_classes, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch
epochs = 10
for i in range(num_batches):
    x_train_batch = x_train_batches[i]
    y_train_batch = y_train_batches[i]
    model.fit(x_train_batch, y_train_batch, batch_size=128, epochs=epochs, verbose=1)

    # Evaluate the model on the test set
    test_loss, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy (Batch {}): {:.2f}%".format(i+1, test_accuracy*100))
    accuracies.append(test_accuracy)

# Print the batch accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Batch-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
219/219 [==============================] - 2s 4ms/step - loss: 2.1522 - accuracy: 0.4145
Epoch 2/10
219/219 [==============================] - 1s 4ms/step - loss: 1.5548 - accuracy: 0.6655
Epoch 3/10
219/219 [==============================] - 1s 4ms/step - loss: 1.0726 - accuracy: 0.7683
Epoch 4/10
219/219 [==============================] - 1s 5ms/step - loss: 0.8193 - accuracy: 0.8136
Epoch 5/10
219/219 [==============================] - 1s 5ms/step - loss: 0.6744 - accuracy: 0.8398
Epoch 6/10
219/219 [==============================] - 1s 5ms/step - loss: 0.5826 - accuracy: 0.8556
Epoch 7/10
219/219 [==============================] - 1s 4ms/step - loss: 0.5196 - accuracy: 0.8696
Epoch 8/10
219/219 [==============================] - 1s 4ms/step - loss: 0.4745 - accuracy: 0.8776
Epoch 9/10
219/219 [==============================] - 1s 5ms/step - loss: 0.4414 - accuracy: 0.8839
Epoch 10/10
219/219 [==============================] - 1s 5ms/step - loss: 0.4160 - accuracy: 0.8884
438/438 [==============================] - 2s 3ms/step - loss: 0.4130 - accuracy: 0.8891
Test Accuracy (Batch 1): 88.91%
Epoch 1/10
219/219 [==============================] - 1s 4ms/step - loss: 0.4068 - accuracy: 0.8901
Epoch 2/10
219/219 [==============================] - 1s 4ms/step - loss: 0.3893 - accuracy: 0.8938
Epoch 3/10
219/219 [==============================] - 1s 4ms/step - loss: 0.3752 - accuracy: 0.8974
Epoch 4/10
219/219 [==============================] - 1s 4ms/step - loss: 0.3631 - accuracy: 0.9003
Epoch 5/10
219/219 [==============================] - 1s 4ms/step - loss: 0.3530 - accuracy: 0.9030
Epoch 6/10
219/219 [==============================] - 1s 4ms/step - loss: 0.3442 - accuracy: 0.9053
Epoch 7/10
219/219 [==============================] - 1s 6ms/step - loss: 0.3365 - accuracy: 0.9074
Epoch 8/10
219/219 [==============================] - 1s 5ms/step - loss: 0.3296 - accuracy: 0.9089
Epoch 9/10
219/219 [==============================] - 1s 4ms/step - loss: 0.3238 - accuracy: 0.9091
Epoch 10/10
219/219 [==============================] - 1s 4ms/step - loss: 0.3175 - accuracy: 0.9112
438/438 [==============================] - 2s 3ms/step - loss: 0.3223 - accuracy: 0.9085
Test Accuracy (Batch 2): 90.85%
Batch-1: 88.91%
Batch-2: 90.85%

### SVHN

In [ ]:
!wget http://ufldl.stanford.edu/housenumbers/train_32x32.mat
!wget http://ufldl.stanford.edu/housenumbers/test_32x32.mat

--2023-08-12 17:13:15--  http://ufldl.stanford.edu/housenumbers/train_32x32.mat
Resolving ufldl.stanford.edu (ufldl.stanford.edu)... 171.64.68.10
Connecting to ufldl.stanford.edu (ufldl.stanford.edu)|171.64.68.10|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 182040794 (174M) [text/plain]
Saving to: ‘train_32x32.mat.1’

train_32x32.mat.1   100%[===================>] 173.61M  83.4MB/s    in 2.1s

2023-08-12 17:13:17 (83.4 MB/s) - ‘train_32x32.mat.1’ saved [182040794/182040794]

--2023-08-12 17:13:17--  http://ufldl.stanford.edu/housenumbers/test_32x32.mat
Resolving ufldl.stanford.edu (ufldl.stanford.edu)... 171.64.68.10
Connecting to ufldl.stanford.edu (ufldl.stanford.edu)|171.64.68.10|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 64275384 (61M) [text/plain]
Saving to: ‘test_32x32.mat.1’

test_32x32.mat.1    100%[===================>]  61.30M  65.7MB/s    in 0.9s

2023-08-12 17:13:18 (65.7 MB/s) - ‘test_32x32.mat.1’ saved [64275384/64275384]

In [ ]:
import numpy as np
from tensorflow import keras
from sklearn.model_selection import KFold
import scipy.io as sio
from tensorflow.keras.utils import to_categorical
# Load the SVHN dataset
train_data = sio.loadmat("train_32x32.mat")
test_data = sio.loadmat("test_32x32.mat")

# Extract the images and labels from the downloaded data
train_images = np.transpose(train_data['X'], (3, 0, 1, 2))
train_labels = train_data['y']

test_images = np.transpose(test_data['X'], (3, 0, 1, 2))
test_labels = test_data['y']

# Change class labels to range from 0 to 9
train_labels[train_labels == 10] = 0
test_labels[test_labels == 10] = 0

# Perform one-hot encoding on the labels
num_classes = 10
train_labels = to_categorical(train_labels, num_classes)
test_labels = to_categorical(test_labels, num_classes)

# Print the shape of the loaded data
print("Train images shape:", train_images.shape)
print("Train labels shape:", train_labels.shape)
print("Test images shape:", test_images.shape)
print("Test labels shape:", test_labels.shape)

Train images shape: (73257, 32, 32, 3)
Train labels shape: (73257, 10)
Test images shape: (26032, 32, 32, 3)
Test labels shape: (26032, 10)

In [ ]:
x_train  = train_images
y_train = train_labels
x_test = test_images
y_test = test_labels
# Print the shape of the loaded data
print("Train images shape:", x_train.shape)
print("Train labels shape:", y_train.shape)
print("Test images shape:", x_test.shape)
print("Test labels shape:", y_test.shape)

Train images shape: (73257, 32, 32, 3)
Train labels shape: (73257, 10)
Test images shape: (26032, 32, 32, 3)
Test labels shape: (26032, 10)

##### Batches 20

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.optimizers import Adam

# x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=42)
# Normalize the input data
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

# Convert the labels to one-hot encoding
num_classes = 10
# y_train = tf.keras.utils.to_categorical(y_train, num_classes)
# y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training set into 20 batches
num_batches = 20
x_train_batches = np.array_split(x_train, num_batches)
y_train_batches = np.array_split(y_train, num_batches)

# Initialize the list to store test accuracies
accuracies = []

# Define the model architecture
model = Sequential([
    Flatten(input_shape=(32, 32, 3)),
    Dense(128, activation='relu'),
    Dense(num_classes, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch
epochs = 10
for i in range(num_batches):
    x_train_batch = x_train_batches[i]
    y_train_batch = y_train_batches[i]
    model.fit(x_train_batch, y_train_batch, batch_size=128, epochs=epochs, verbose=1)

    # Evaluate the model on the test set
    test_loss, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy (Batch {}): {:.2f}%".format(i+1, test_accuracy*100))
    accuracies.append(test_accuracy)

# Print the batch accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Batch-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
29/29 [==============================] - 2s 5ms/step - loss: 2.4852 - accuracy: 0.1406
Epoch 2/10
29/29 [==============================] - 0s 6ms/step - loss: 2.2938 - accuracy: 0.1709
Epoch 3/10
29/29 [==============================] - 0s 8ms/step - loss: 2.2523 - accuracy: 0.1908
Epoch 4/10
29/29 [==============================] - 0s 6ms/step - loss: 2.2664 - accuracy: 0.1848
Epoch 5/10
29/29 [==============================] - 0s 6ms/step - loss: 2.2526 - accuracy: 0.1985
Epoch 6/10
29/29 [==============================] - 0s 8ms/step - loss: 2.2319 - accuracy: 0.1963
Epoch 7/10
29/29 [==============================] - 0s 10ms/step - loss: 2.2246 - accuracy: 0.2056
Epoch 8/10
29/29 [==============================] - 0s 11ms/step - loss: 2.2561 - accuracy: 0.1840
Epoch 9/10
29/29 [==============================] - 0s 7ms/step - loss: 2.2076 - accuracy: 0.2034
Epoch 10/10
29/29 [==============================] - 0s 6ms/step - loss: 2.2090 - accuracy: 0.2088
814/814 [==============================] - 3s 3ms/step - loss: 2.3013 - accuracy: 0.1609
Test Accuracy (Batch 1): 16.09%
Epoch 1/10
29/29 [==============================] - 0s 5ms/step - loss: 2.3001 - accuracy: 0.1824
Epoch 2/10
29/29 [==============================] - 0s 5ms/step - loss: 2.2337 - accuracy: 0.2091
Epoch 3/10
29/29 [==============================] - 0s 4ms/step - loss: 2.2311 - accuracy: 0.2034
Epoch 4/10
29/29 [==============================] - 0s 4ms/step - loss: 2.2197 - accuracy: 0.2116
Epoch 5/10
29/29 [==============================] - 0s 5ms/step - loss: 2.2071 - accuracy: 0.2165
Epoch 6/10
29/29 [==============================] - 0s 5ms/step - loss: 2.1852 - accuracy: 0.2465
Epoch 7/10
29/29 [==============================] - 0s 5ms/step - loss: 2.1805 - accuracy: 0.2290
Epoch 8/10
29/29 [==============================] - 0s 5ms/step - loss: 2.1758 - accuracy: 0.2340
Epoch 9/10
29/29 [==============================] - 0s 5ms/step - loss: 2.1597 - accuracy: 0.2471
Epoch 10/10
29/29 [==============================] - 0s 4ms/step - loss: 2.1375 - accuracy: 0.2727
814/814 [==============================] - 3s 4ms/step - loss: 2.1910 - accuracy: 0.2563
Test Accuracy (Batch 2): 25.63%
Epoch 1/10
29/29 [==============================] - 0s 5ms/step - loss: 2.1621 - accuracy: 0.2492
Epoch 2/10
29/29 [==============================] - 0s 5ms/step - loss: 2.1400 - accuracy: 0.2492
Epoch 3/10
29/29 [==============================] - 0s 5ms/step - loss: 2.1102 - accuracy: 0.2711
Epoch 4/10
29/29 [==============================] - 0s 5ms/step - loss: 2.0871 - accuracy: 0.2755
Epoch 5/10
29/29 [==============================] - 0s 5ms/step - loss: 2.0457 - accuracy: 0.2946
Epoch 6/10
29/29 [==============================] - 0s 5ms/step - loss: 2.0128 - accuracy: 0.3224
Epoch 7/10
29/29 [==============================] - 0s 5ms/step - loss: 1.9942 - accuracy: 0.3134
Epoch 8/10
29/29 [==============================] - 0s 5ms/step - loss: 1.9857 - accuracy: 0.3093
Epoch 9/10
29/29 [==============================] - 0s 5ms/step - loss: 1.9409 - accuracy: 0.3251
Epoch 10/10
29/29 [==============================] - 0s 5ms/step - loss: 1.9090 - accuracy: 0.3549
814/814 [==============================] - 3s 4ms/step - loss: 1.9902 - accuracy: 0.3092
Test Accuracy (Batch 3): 30.92%
Epoch 1/10
29/29 [==============================] - 0s 11ms/step - loss: 1.9675 - accuracy: 0.3251
Epoch 2/10
29/29 [==============================] - 0s 7ms/step - loss: 1.9490 - accuracy: 0.3235
Epoch 3/10
29/29 [==============================] - 0s 6ms/step - loss: 1.9247 - accuracy: 0.3415
Epoch 4/10
29/29 [==============================] - 0s 9ms/step - loss: 1.8900 - accuracy: 0.3579
Epoch 5/10
29/29 [==============================] - 0s 7ms/step - loss: 1.8696 - accuracy: 0.3601
Epoch 6/10
29/29 [==============================] - 0s 4ms/step - loss: 1.8493 - accuracy: 0.3729
Epoch 7/10
29/29 [==============================] - 0s 5ms/step - loss: 1.8423 - accuracy: 0.3664
Epoch 8/10
29/29 [==============================] - 0s 5ms/step - loss: 1.7975 - accuracy: 0.4005
Epoch 9/10
29/29 [==============================] - 0s 5ms/step - loss: 1.7830 - accuracy: 0.3901
Epoch 10/10
29/29 [==============================] - 0s 5ms/step - loss: 1.7654 - accuracy: 0.4109
814/814 [==============================] - 3s 3ms/step - loss: 1.8066 - accuracy: 0.4079
Test Accuracy (Batch 4): 40.79%
Epoch 1/10
29/29 [==============================] - 0s 5ms/step - loss: 1.7867 - accuracy: 0.3928
Epoch 2/10
29/29 [==============================] - 0s 5ms/step - loss: 1.7543 - accuracy: 0.4076
Epoch 3/10
29/29 [==============================] - 0s 5ms/step - loss: 1.7246 - accuracy: 0.4221
Epoch 4/10
29/29 [==============================] - 0s 5ms/step - loss: 1.7031 - accuracy: 0.4409
Epoch 5/10
29/29 [==============================] - 0s 5ms/step - loss: 1.6701 - accuracy: 0.4518
Epoch 6/10
29/29 [==============================] - 0s 5ms/step - loss: 1.6569 - accuracy: 0.4545
Epoch 7/10
29/29 [==============================] - 0s 5ms/step - loss: 1.6612 - accuracy: 0.4488
Epoch 8/10
29/29 [==============================] - 0s 4ms/step - loss: 1.6186 - accuracy: 0.4663
Epoch 9/10
29/29 [==============================] - 0s 5ms/step - loss: 1.5853 - accuracy: 0.4813
Epoch 10/10
29/29 [==============================] - 0s 5ms/step - loss: 1.5620 - accuracy: 0.4966
814/814 [==============================] - 3s 4ms/step - loss: 1.6679 - accuracy: 0.4357
Test Accuracy (Batch 5): 43.57%
Epoch 1/10
29/29 [==============================] - 0s 6ms/step - loss: 1.6179 - accuracy: 0.4693
Epoch 2/10
29/29 [==============================] - 0s 6ms/step - loss: 1.6048 - accuracy: 0.4709
Epoch 3/10
29/29 [==============================] - 0s 5ms/step - loss: 1.5854 - accuracy: 0.4731
Epoch 4/10
29/29 [==============================] - 0s 5ms/step - loss: 1.5654 - accuracy: 0.4799
Epoch 5/10
29/29 [==============================] - 0s 8ms/step - loss: 1.5378 - accuracy: 0.4868
Epoch 6/10
29/29 [==============================] - 0s 6ms/step - loss: 1.5193 - accuracy: 0.5064
Epoch 7/10
29/29 [==============================] - 0s 5ms/step - loss: 1.5067 - accuracy: 0.5004
Epoch 8/10
29/29 [==============================] - 0s 5ms/step - loss: 1.4892 - accuracy: 0.5100
Epoch 9/10
29/29 [==============================] - 0s 5ms/step - loss: 1.4838 - accuracy: 0.5072
Epoch 10/10
29/29 [==============================] - 0s 5ms/step - loss: 1.4706 - accuracy: 0.5149
814/814 [==============================] - 3s 3ms/step - loss: 1.5492 - accuracy: 0.4896
Test Accuracy (Batch 6): 48.96%
Epoch 1/10
29/29 [==============================] - 0s 5ms/step - loss: 1.5008 - accuracy: 0.5061
Epoch 2/10
29/29 [==============================] - 0s 5ms/step - loss: 1.4863 - accuracy: 0.5124
Epoch 3/10
29/29 [==============================] - 0s 5ms/step - loss: 1.4533 - accuracy: 0.5299
Epoch 4/10
29/29 [==============================] - 0s 5ms/step - loss: 1.4480 - accuracy: 0.5253
Epoch 5/10
29/29 [==============================] - 0s 6ms/step - loss: 1.4384 - accuracy: 0.5324
Epoch 6/10
29/29 [==============================] - 0s 5ms/step - loss: 1.4185 - accuracy: 0.5430
Epoch 7/10
29/29 [==============================] - 0s 5ms/step - loss: 1.4052 - accuracy: 0.5389
Epoch 8/10
29/29 [==============================] - 0s 5ms/step - loss: 1.4059 - accuracy: 0.5408
Epoch 9/10
29/29 [==============================] - 0s 5ms/step - loss: 1.3771 - accuracy: 0.5575
Epoch 10/10
29/29 [==============================] - 0s 5ms/step - loss: 1.3767 - accuracy: 0.5465
814/814 [==============================] - 4s 4ms/step - loss: 1.4959 - accuracy: 0.5222
Test Accuracy (Batch 7): 52.22%
Epoch 1/10
29/29 [==============================] - 0s 5ms/step - loss: 1.4097 - accuracy: 0.5422
Epoch 2/10
29/29 [==============================] - 0s 4ms/step - loss: 1.3815 - accuracy: 0.5498
Epoch 3/10
29/29 [==============================] - 0s 5ms/step - loss: 1.3503 - accuracy: 0.5722
Epoch 4/10
29/29 [==============================] - 0s 5ms/step - loss: 1.3470 - accuracy: 0.5607
Epoch 5/10
29/29 [==============================] - 0s 5ms/step - loss: 1.3411 - accuracy: 0.5594
Epoch 6/10
29/29 [==============================] - 0s 5ms/step - loss: 1.3290 - accuracy: 0.5755
Epoch 7/10
29/29 [==============================] - 0s 5ms/step - loss: 1.3244 - accuracy: 0.5684
Epoch 8/10
29/29 [==============================] - 0s 5ms/step - loss: 1.3170 - accuracy: 0.5749
Epoch 9/10
29/29 [==============================] - 0s 5ms/step - loss: 1.2840 - accuracy: 0.5845
Epoch 10/10
29/29 [==============================] - 0s 5ms/step - loss: 1.3003 - accuracy: 0.5872
814/814 [==============================] - 3s 3ms/step - loss: 1.4707 - accuracy: 0.5259
Test Accuracy (Batch 8): 52.59%
Epoch 1/10
29/29 [==============================] - 0s 5ms/step - loss: 1.3963 - accuracy: 0.5528
Epoch 2/10
29/29 [==============================] - 0s 5ms/step - loss: 1.3885 - accuracy: 0.5506
Epoch 3/10
29/29 [==============================] - 0s 5ms/step - loss: 1.3706 - accuracy: 0.5580
Epoch 4/10
29/29 [==============================] - 0s 5ms/step - loss: 1.3732 - accuracy: 0.5556
Epoch 5/10
29/29 [==============================] - 0s 5ms/step - loss: 1.3451 - accuracy: 0.5665
Epoch 6/10
29/29 [==============================] - 0s 5ms/step - loss: 1.3451 - accuracy: 0.5657
Epoch 7/10
29/29 [==============================] - 0s 6ms/step - loss: 1.3160 - accuracy: 0.5779
Epoch 8/10
29/29 [==============================] - 0s 4ms/step - loss: 1.2966 - accuracy: 0.5864
Epoch 9/10
29/29 [==============================] - 0s 5ms/step - loss: 1.3126 - accuracy: 0.5804
Epoch 10/10
29/29 [==============================] - 0s 5ms/step - loss: 1.3138 - accuracy: 0.5782
814/814 [==============================] - 3s 4ms/step - loss: 1.4388 - accuracy: 0.5419
Test Accuracy (Batch 9): 54.19%
Epoch 1/10
29/29 [==============================] - 0s 5ms/step - loss: 1.2999 - accuracy: 0.5891
Epoch 2/10
29/29 [==============================] - 0s 5ms/step - loss: 1.2792 - accuracy: 0.5831
Epoch 3/10
29/29 [==============================] - 0s 5ms/step - loss: 1.2771 - accuracy: 0.5872
Epoch 4/10
29/29 [==============================] - 0s 4ms/step - loss: 1.2622 - accuracy: 0.5932
Epoch 5/10
29/29 [==============================] - 0s 6ms/step - loss: 1.2429 - accuracy: 0.5987
Epoch 6/10
29/29 [==============================] - 0s 5ms/step - loss: 1.2349 - accuracy: 0.5960
Epoch 7/10
29/29 [==============================] - 0s 6ms/step - loss: 1.2303 - accuracy: 0.6031
Epoch 8/10
29/29 [==============================] - 0s 5ms/step - loss: 1.2196 - accuracy: 0.6080
Epoch 9/10
29/29 [==============================] - 0s 5ms/step - loss: 1.2246 - accuracy: 0.6011
Epoch 10/10
29/29 [==============================] - 0s 5ms/step - loss: 1.2121 - accuracy: 0.5998
814/814 [==============================] - 3s 3ms/step - loss: 1.4362 - accuracy: 0.5544
Test Accuracy (Batch 10): 55.44%
Epoch 1/10
29/29 [==============================] - 0s 5ms/step - loss: 1.2677 - accuracy: 0.6003
Epoch 2/10
29/29 [==============================] - 0s 5ms/step - loss: 1.2619 - accuracy: 0.6020
Epoch 3/10
29/29 [==============================] - 0s 5ms/step - loss: 1.2429 - accuracy: 0.6112
Epoch 4/10
29/29 [==============================] - 0s 5ms/step - loss: 1.2194 - accuracy: 0.6132
Epoch 5/10
29/29 [==============================] - 0s 5ms/step - loss: 1.2205 - accuracy: 0.6170
Epoch 6/10
29/29 [==============================] - 0s 5ms/step - loss: 1.2053 - accuracy: 0.6121
Epoch 7/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1993 - accuracy: 0.6200
Epoch 8/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1919 - accuracy: 0.6181
Epoch 9/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1850 - accuracy: 0.6194
Epoch 10/10
29/29 [==============================] - 0s 6ms/step - loss: 1.1731 - accuracy: 0.6282
814/814 [==============================] - 3s 3ms/step - loss: 1.4769 - accuracy: 0.5534
Test Accuracy (Batch 11): 55.34%
Epoch 1/10
29/29 [==============================] - 0s 5ms/step - loss: 1.3002 - accuracy: 0.5932
Epoch 2/10
29/29 [==============================] - 0s 6ms/step - loss: 1.2533 - accuracy: 0.6200
Epoch 3/10
29/29 [==============================] - 0s 5ms/step - loss: 1.2378 - accuracy: 0.6252
Epoch 4/10
29/29 [==============================] - 0s 4ms/step - loss: 1.2342 - accuracy: 0.6260
Epoch 5/10
29/29 [==============================] - 0s 5ms/step - loss: 1.2035 - accuracy: 0.6358
Epoch 6/10
29/29 [==============================] - 0s 4ms/step - loss: 1.1952 - accuracy: 0.6336
Epoch 7/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1953 - accuracy: 0.6334
Epoch 8/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1935 - accuracy: 0.6257
Epoch 9/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1751 - accuracy: 0.6443
Epoch 10/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1884 - accuracy: 0.6385
814/814 [==============================] - 3s 3ms/step - loss: 1.3901 - accuracy: 0.5749
Test Accuracy (Batch 12): 57.49%
Epoch 1/10
29/29 [==============================] - 0s 4ms/step - loss: 1.2847 - accuracy: 0.5962
Epoch 2/10
29/29 [==============================] - 0s 4ms/step - loss: 1.2579 - accuracy: 0.6093
Epoch 3/10
29/29 [==============================] - 0s 5ms/step - loss: 1.2415 - accuracy: 0.6134
Epoch 4/10
29/29 [==============================] - 0s 5ms/step - loss: 1.2210 - accuracy: 0.6287
Epoch 5/10
29/29 [==============================] - 0s 4ms/step - loss: 1.2129 - accuracy: 0.6241
Epoch 6/10
29/29 [==============================] - 0s 5ms/step - loss: 1.2066 - accuracy: 0.6252
Epoch 7/10
29/29 [==============================] - 0s 5ms/step - loss: 1.2154 - accuracy: 0.6252
Epoch 8/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1959 - accuracy: 0.6339
Epoch 9/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1743 - accuracy: 0.6407
Epoch 10/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1594 - accuracy: 0.6413
814/814 [==============================] - 3s 3ms/step - loss: 1.3540 - accuracy: 0.5938
Test Accuracy (Batch 13): 59.38%
Epoch 1/10
29/29 [==============================] - 0s 5ms/step - loss: 1.2246 - accuracy: 0.6162
Epoch 2/10
29/29 [==============================] - 0s 5ms/step - loss: 1.2212 - accuracy: 0.6151
Epoch 3/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1958 - accuracy: 0.6205
Epoch 4/10
29/29 [==============================] - 0s 5ms/step - loss: 1.2038 - accuracy: 0.6123
Epoch 5/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1662 - accuracy: 0.6361
Epoch 6/10
29/29 [==============================] - 0s 6ms/step - loss: 1.1475 - accuracy: 0.6358
Epoch 7/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1366 - accuracy: 0.6383
Epoch 8/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1203 - accuracy: 0.6470
Epoch 9/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1109 - accuracy: 0.6443
Epoch 10/10
29/29 [==============================] - 0s 4ms/step - loss: 1.1125 - accuracy: 0.6538
814/814 [==============================] - 4s 4ms/step - loss: 1.3448 - accuracy: 0.5930
Test Accuracy (Batch 14): 59.30%
Epoch 1/10
29/29 [==============================] - 0s 4ms/step - loss: 1.2298 - accuracy: 0.6164
Epoch 2/10
29/29 [==============================] - 0s 5ms/step - loss: 1.2388 - accuracy: 0.6189
Epoch 3/10
29/29 [==============================] - 0s 5ms/step - loss: 1.2011 - accuracy: 0.6328
Epoch 4/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1858 - accuracy: 0.6369
Epoch 5/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1620 - accuracy: 0.6478
Epoch 6/10
29/29 [==============================] - 0s 4ms/step - loss: 1.1550 - accuracy: 0.6500
Epoch 7/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1483 - accuracy: 0.6552
Epoch 8/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1412 - accuracy: 0.6492
Epoch 9/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1312 - accuracy: 0.6590
Epoch 10/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1256 - accuracy: 0.6536
814/814 [==============================] - 3s 3ms/step - loss: 1.3231 - accuracy: 0.5988
Test Accuracy (Batch 15): 59.88%
Epoch 1/10
29/29 [==============================] - 0s 7ms/step - loss: 1.1766 - accuracy: 0.6383
Epoch 2/10
29/29 [==============================] - 0s 9ms/step - loss: 1.1767 - accuracy: 0.6339
Epoch 3/10
29/29 [==============================] - 0s 6ms/step - loss: 1.1316 - accuracy: 0.6473
Epoch 4/10
29/29 [==============================] - 0s 6ms/step - loss: 1.1446 - accuracy: 0.6454
Epoch 5/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1024 - accuracy: 0.6609
Epoch 6/10
29/29 [==============================] - 0s 9ms/step - loss: 1.1154 - accuracy: 0.6486
Epoch 7/10
29/29 [==============================] - 0s 7ms/step - loss: 1.0932 - accuracy: 0.6694
Epoch 8/10
29/29 [==============================] - 0s 5ms/step - loss: 1.0743 - accuracy: 0.6650
Epoch 9/10
29/29 [==============================] - 0s 5ms/step - loss: 1.0960 - accuracy: 0.6574
Epoch 10/10
29/29 [==============================] - 0s 6ms/step - loss: 1.0627 - accuracy: 0.6689
814/814 [==============================] - 3s 4ms/step - loss: 1.3336 - accuracy: 0.5920
Test Accuracy (Batch 16): 59.20%
Epoch 1/10
29/29 [==============================] - 0s 5ms/step - loss: 1.2125 - accuracy: 0.6383
Epoch 2/10
29/29 [==============================] - 0s 5ms/step - loss: 1.2065 - accuracy: 0.6410
Epoch 3/10
29/29 [==============================] - 0s 6ms/step - loss: 1.2091 - accuracy: 0.6350
Epoch 4/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1629 - accuracy: 0.6451
Epoch 5/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1579 - accuracy: 0.6484
Epoch 6/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1547 - accuracy: 0.6508
Epoch 7/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1876 - accuracy: 0.6347
Epoch 8/10
29/29 [==============================] - 0s 4ms/step - loss: 1.1535 - accuracy: 0.6416
Epoch 9/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1390 - accuracy: 0.6596
Epoch 10/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1283 - accuracy: 0.6552
814/814 [==============================] - 4s 4ms/step - loss: 1.3043 - accuracy: 0.6096
Test Accuracy (Batch 17): 60.96%
Epoch 1/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1711 - accuracy: 0.6466
Epoch 2/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1453 - accuracy: 0.6518
Epoch 3/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1722 - accuracy: 0.6398
Epoch 4/10
29/29 [==============================] - 0s 4ms/step - loss: 1.1547 - accuracy: 0.6434
Epoch 5/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1382 - accuracy: 0.6423
Epoch 6/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1293 - accuracy: 0.6480
Epoch 7/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1066 - accuracy: 0.6608
Epoch 8/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1064 - accuracy: 0.6603
Epoch 9/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1072 - accuracy: 0.6510
Epoch 10/10
29/29 [==============================] - 0s 5ms/step - loss: 1.0851 - accuracy: 0.6723
814/814 [==============================] - 3s 3ms/step - loss: 1.2920 - accuracy: 0.6073
Test Accuracy (Batch 18): 60.73%
Epoch 1/10
29/29 [==============================] - 0s 5ms/step - loss: 1.1541 - accuracy: 0.6494
Epoch 2/10

#### Batches 10

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.optimizers import Adam

# x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=42)
# Normalize the input data
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

# Convert the labels to one-hot encoding
num_classes = 10
# y_train = tf.keras.utils.to_categorical(y_train, num_classes)
# y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training set into 20 batches
num_batches = 10
x_train_batches = np.array_split(x_train, num_batches)
y_train_batches = np.array_split(y_train, num_batches)

# Initialize the list to store test accuracies
accuracies = []

# Define the model architecture
model = Sequential([
    Flatten(input_shape=(32, 32, 3)),
    Dense(128, activation='relu'),
    Dense(num_classes, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch
epochs = 10
for i in range(num_batches):
    x_train_batch = x_train_batches[i]
    y_train_batch = y_train_batches[i]
    model.fit(x_train_batch, y_train_batch, batch_size=128, epochs=epochs, verbose=1)

    # Evaluate the model on the test set
    test_loss, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy (Batch {}): {:.2f}%".format(i+1, test_accuracy*100))
    accuracies.append(test_accuracy)

# Print the batch accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Batch-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
58/58 [==============================] - 2s 8ms/step - loss: 2.2535 - accuracy: 0.1895
Epoch 2/10
58/58 [==============================] - 0s 7ms/step - loss: 2.2392 - accuracy: 0.1918
Epoch 3/10
58/58 [==============================] - 0s 7ms/step - loss: 2.2381 - accuracy: 0.1918
Epoch 4/10
58/58 [==============================] - 0s 6ms/step - loss: 2.2373 - accuracy: 0.1918
Epoch 5/10
58/58 [==============================] - 0s 5ms/step - loss: 2.2368 - accuracy: 0.1918
Epoch 6/10
58/58 [==============================] - 0s 5ms/step - loss: 2.2350 - accuracy: 0.1918
Epoch 7/10
58/58 [==============================] - 0s 5ms/step - loss: 2.2342 - accuracy: 0.1918
Epoch 8/10
58/58 [==============================] - 0s 5ms/step - loss: 2.2329 - accuracy: 0.1918
Epoch 9/10
58/58 [==============================] - 0s 5ms/step - loss: 2.2325 - accuracy: 0.1918
Epoch 10/10
58/58 [==============================] - 0s 5ms/step - loss: 2.2325 - accuracy: 0.1918
814/814 [==============================] - 3s 3ms/step - loss: 2.2253 - accuracy: 0.1959
Test Accuracy (Batch 1): 19.59%
Epoch 1/10
58/58 [==============================] - 0s 5ms/step - loss: 2.2323 - accuracy: 0.1927
Epoch 2/10
58/58 [==============================] - 0s 5ms/step - loss: 2.2306 - accuracy: 0.1908
Epoch 3/10
58/58 [==============================] - 0s 5ms/step - loss: 2.2299 - accuracy: 0.1912
Epoch 4/10
58/58 [==============================] - 0s 6ms/step - loss: 2.2288 - accuracy: 0.1912
Epoch 5/10
58/58 [==============================] - 0s 5ms/step - loss: 2.2276 - accuracy: 0.1922
Epoch 6/10
58/58 [==============================] - 0s 5ms/step - loss: 2.2268 - accuracy: 0.1916
Epoch 7/10
58/58 [==============================] - 0s 6ms/step - loss: 2.2265 - accuracy: 0.1914
Epoch 8/10
58/58 [==============================] - 0s 7ms/step - loss: 2.2255 - accuracy: 0.1936
Epoch 9/10
58/58 [==============================] - 0s 7ms/step - loss: 2.2244 - accuracy: 0.1912
Epoch 10/10
58/58 [==============================] - 0s 6ms/step - loss: 2.2239 - accuracy: 0.1945
814/814 [==============================] - 3s 3ms/step - loss: 2.2208 - accuracy: 0.1961
Test Accuracy (Batch 2): 19.61%
Epoch 1/10
58/58 [==============================] - 0s 5ms/step - loss: 2.2287 - accuracy: 0.1915
Epoch 2/10
58/58 [==============================] - 0s 5ms/step - loss: 2.2280 - accuracy: 0.1930
Epoch 3/10
58/58 [==============================] - 0s 5ms/step - loss: 2.2273 - accuracy: 0.1960
Epoch 4/10
58/58 [==============================] - 0s 5ms/step - loss: 2.2262 - accuracy: 0.1925
Epoch 5/10
58/58 [==============================] - 0s 5ms/step - loss: 2.2251 - accuracy: 0.1918
Epoch 6/10
58/58 [==============================] - 0s 5ms/step - loss: 2.2238 - accuracy: 0.1934
Epoch 7/10
58/58 [==============================] - 0s 5ms/step - loss: 2.2242 - accuracy: 0.1946
Epoch 8/10
58/58 [==============================] - 0s 6ms/step - loss: 2.2215 - accuracy: 0.1942
Epoch 9/10
58/58 [==============================] - 0s 5ms/step - loss: 2.2194 - accuracy: 0.1971
Epoch 10/10
58/58 [==============================] - 0s 5ms/step - loss: 2.2180 - accuracy: 0.1979
814/814 [==============================] - 3s 3ms/step - loss: 2.2159 - accuracy: 0.2030
Test Accuracy (Batch 3): 20.30%
Epoch 1/10
58/58 [==============================] - 0s 5ms/step - loss: 2.2251 - accuracy: 0.1966
Epoch 2/10
58/58 [==============================] - 0s 5ms/step - loss: 2.2220 - accuracy: 0.1938
Epoch 3/10
58/58 [==============================] - 0s 5ms/step - loss: 2.2194 - accuracy: 0.1993
Epoch 4/10
58/58 [==============================] - 0s 5ms/step - loss: 2.2169 - accuracy: 0.2020
Epoch 5/10
58/58 [==============================] - 0s 5ms/step - loss: 2.2144 - accuracy: 0.2042
Epoch 6/10
58/58 [==============================] - 0s 5ms/step - loss: 2.2117 - accuracy: 0.2078
Epoch 7/10
58/58 [==============================] - 0s 5ms/step - loss: 2.2079 - accuracy: 0.2080
Epoch 8/10
58/58 [==============================] - 0s 5ms/step - loss: 2.2033 - accuracy: 0.2116
Epoch 9/10
58/58 [==============================] - 0s 5ms/step - loss: 2.1989 - accuracy: 0.2166
Epoch 10/10
58/58 [==============================] - 0s 5ms/step - loss: 2.1938 - accuracy: 0.2203
814/814 [==============================] - 4s 5ms/step - loss: 2.1895 - accuracy: 0.2232
Test Accuracy (Batch 4): 22.32%
Epoch 1/10
58/58 [==============================] - 0s 4ms/step - loss: 2.1962 - accuracy: 0.2101
Epoch 2/10
58/58 [==============================] - 0s 5ms/step - loss: 2.1904 - accuracy: 0.2124
Epoch 3/10
58/58 [==============================] - 0s 5ms/step - loss: 2.1839 - accuracy: 0.2143
Epoch 4/10
58/58 [==============================] - 0s 5ms/step - loss: 2.1777 - accuracy: 0.2159
Epoch 5/10
58/58 [==============================] - 0s 5ms/step - loss: 2.1721 - accuracy: 0.2154
Epoch 6/10
58/58 [==============================] - 0s 5ms/step - loss: 2.1648 - accuracy: 0.2198
Epoch 7/10
58/58 [==============================] - 0s 6ms/step - loss: 2.1586 - accuracy: 0.2213
Epoch 8/10
58/58 [==============================] - 0s 6ms/step - loss: 2.1506 - accuracy: 0.2265
Epoch 9/10
58/58 [==============================] - 0s 5ms/step - loss: 2.1433 - accuracy: 0.2286
Epoch 10/10
58/58 [==============================] - 0s 5ms/step - loss: 2.1344 - accuracy: 0.2304
814/814 [==============================] - 4s 4ms/step - loss: 2.1316 - accuracy: 0.2402
Test Accuracy (Batch 5): 24.02%
Epoch 1/10
58/58 [==============================] - 0s 4ms/step - loss: 2.1318 - accuracy: 0.2389
Epoch 2/10
58/58 [==============================] - 0s 5ms/step - loss: 2.1214 - accuracy: 0.2439
Epoch 3/10
58/58 [==============================] - 0s 5ms/step - loss: 2.1116 - accuracy: 0.2437
Epoch 4/10
58/58 [==============================] - 0s 5ms/step - loss: 2.1020 - accuracy: 0.2469
Epoch 5/10
58/58 [==============================] - 0s 5ms/step - loss: 2.0903 - accuracy: 0.2502
Epoch 6/10
58/58 [==============================] - 0s 5ms/step - loss: 2.0806 - accuracy: 0.2536
Epoch 7/10
58/58 [==============================] - 0s 4ms/step - loss: 2.0693 - accuracy: 0.2595
Epoch 8/10
58/58 [==============================] - 0s 5ms/step - loss: 2.0583 - accuracy: 0.2637
Epoch 9/10
58/58 [==============================] - 0s 5ms/step - loss: 2.0476 - accuracy: 0.2675
Epoch 10/10
58/58 [==============================] - 0s 5ms/step - loss: 2.0364 - accuracy: 0.2715
814/814 [==============================] - 3s 4ms/step - loss: 2.0379 - accuracy: 0.2594
Test Accuracy (Batch 6): 25.94%
Epoch 1/10
58/58 [==============================] - 0s 6ms/step - loss: 2.0281 - accuracy: 0.2742
Epoch 2/10
58/58 [==============================] - 0s 5ms/step - loss: 2.0163 - accuracy: 0.2730
Epoch 3/10
58/58 [==============================] - 0s 5ms/step - loss: 2.0050 - accuracy: 0.2813
Epoch 4/10
58/58 [==============================] - 0s 5ms/step - loss: 1.9941 - accuracy: 0.2862
Epoch 5/10
58/58 [==============================] - 0s 5ms/step - loss: 1.9831 - accuracy: 0.2888
Epoch 6/10
58/58 [==============================] - 0s 5ms/step - loss: 1.9723 - accuracy: 0.2993
Epoch 7/10
58/58 [==============================] - 0s 5ms/step - loss: 1.9609 - accuracy: 0.3081
Epoch 8/10
58/58 [==============================] - 0s 5ms/step - loss: 1.9503 - accuracy: 0.3100
Epoch 9/10
58/58 [==============================] - 0s 5ms/step - loss: 1.9411 - accuracy: 0.3144
Epoch 10/10
58/58 [==============================] - 0s 4ms/step - loss: 1.9321 - accuracy: 0.3193
814/814 [==============================] - 3s 3ms/step - loss: 1.9424 - accuracy: 0.3257
Test Accuracy (Batch 7): 32.57%
Epoch 1/10
58/58 [==============================] - 0s 5ms/step - loss: 1.9250 - accuracy: 0.3301
Epoch 2/10
58/58 [==============================] - 0s 5ms/step - loss: 1.9130 - accuracy: 0.3369
Epoch 3/10
58/58 [==============================] - 0s 5ms/step - loss: 1.9013 - accuracy: 0.3418
Epoch 4/10
58/58 [==============================] - 0s 5ms/step - loss: 1.8916 - accuracy: 0.3485
Epoch 5/10
58/58 [==============================] - 0s 5ms/step - loss: 1.8813 - accuracy: 0.3502
Epoch 6/10
58/58 [==============================] - 0s 6ms/step - loss: 1.8708 - accuracy: 0.3528
Epoch 7/10
58/58 [==============================] - 0s 6ms/step - loss: 1.8626 - accuracy: 0.3595
Epoch 8/10
58/58 [==============================] - 0s 5ms/step - loss: 1.8521 - accuracy: 0.3672
Epoch 9/10
58/58 [==============================] - 0s 4ms/step - loss: 1.8434 - accuracy: 0.3750
Epoch 10/10
58/58 [==============================] - 0s 7ms/step - loss: 1.8367 - accuracy: 0.3670
814/814 [==============================] - 3s 3ms/step - loss: 1.8635 - accuracy: 0.3611
Test Accuracy (Batch 8): 36.11%
Epoch 1/10
58/58 [==============================] - 0s 5ms/step - loss: 1.8444 - accuracy: 0.3672
Epoch 2/10
58/58 [==============================] - 0s 5ms/step - loss: 1.8362 - accuracy: 0.3776
Epoch 3/10
58/58 [==============================] - 0s 5ms/step - loss: 1.8274 - accuracy: 0.3820
Epoch 4/10
58/58 [==============================] - 0s 5ms/step - loss: 1.8193 - accuracy: 0.3881
Epoch 5/10
58/58 [==============================] - 0s 5ms/step - loss: 1.8108 - accuracy: 0.3913
Epoch 6/10
58/58 [==============================] - 0s 5ms/step - loss: 1.8038 - accuracy: 0.3939
Epoch 7/10
58/58 [==============================] - 0s 5ms/step - loss: 1.7964 - accuracy: 0.3984
Epoch 8/10
58/58 [==============================] - 0s 5ms/step - loss: 1.7899 - accuracy: 0.3992
Epoch 9/10
58/58 [==============================] - 0s 5ms/step - loss: 1.7854 - accuracy: 0.4015
Epoch 10/10
58/58 [==============================] - 0s 5ms/step - loss: 1.7763 - accuracy: 0.4070
814/814 [==============================] - 3s 4ms/step - loss: 1.8042 - accuracy: 0.3956
Test Accuracy (Batch 9): 39.56%
Epoch 1/10
58/58 [==============================] - 0s 5ms/step - loss: 1.7770 - accuracy: 0.4059
Epoch 2/10
58/58 [==============================] - 0s 5ms/step - loss: 1.7700 - accuracy: 0.4101
Epoch 3/10
58/58 [==============================] - 0s 5ms/step - loss: 1.7620 - accuracy: 0.4111
Epoch 4/10
58/58 [==============================] - 0s 5ms/step - loss: 1.7552 - accuracy: 0.4167
Epoch 5/10
58/58 [==============================] - 0s 5ms/step - loss: 1.7481 - accuracy: 0.4122
Epoch 6/10
58/58 [==============================] - 0s 5ms/step - loss: 1.7402 - accuracy: 0.4205
Epoch 7/10
58/58 [==============================] - 0s 5ms/step - loss: 1.7333 - accuracy: 0.4285
Epoch 8/10
58/58 [==============================] - 0s 5ms/step - loss: 1.7274 - accuracy: 0.4243
Epoch 9/10
58/58 [==============================] - 0s 5ms/step - loss: 1.7217 - accuracy: 0.4321
Epoch 10/10
58/58 [==============================] - 0s 5ms/step - loss: 1.7139 - accuracy: 0.4352
814/814 [==============================] - 3s 3ms/step - loss: 1.7519 - accuracy: 0.4134
Test Accuracy (Batch 10): 41.34%
Batch-1: 19.59%
Batch-2: 19.61%
Batch-3: 20.30%
Batch-4: 22.32%
Batch-5: 24.02%
Batch-6: 25.94%
Batch-7: 32.57%
Batch-8: 36.11%
Batch-9: 39.56%
Batch-10: 41.34%

#### Batches 6

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.optimizers import Adam

# x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=42)
# Normalize the input data
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

# Convert the labels to one-hot encoding
num_classes = 10
# y_train = tf.keras.utils.to_categorical(y_train, num_classes)
# y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training set into 20 batches
num_batches = 6
x_train_batches = np.array_split(x_train, num_batches)
y_train_batches = np.array_split(y_train, num_batches)

# Initialize the list to store test accuracies
accuracies = []

# Define the model architecture
model = Sequential([
    Flatten(input_shape=(32, 32, 3)),
    Dense(128, activation='relu'),
    Dense(num_classes, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch
epochs = 10
for i in range(num_batches):
    x_train_batch = x_train_batches[i]
    y_train_batch = y_train_batches[i]
    model.fit(x_train_batch, y_train_batch, batch_size=128, epochs=epochs, verbose=1)

    # Evaluate the model on the test set
    test_loss, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy (Batch {}): {:.2f}%".format(i+1, test_accuracy*100))
    accuracies.append(test_accuracy)

# Print the batch accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Batch-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
96/96 [==============================] - 0s 5ms/step - loss: 2.2021 - accuracy: 0.1983
Epoch 3/10
96/96 [==============================] - 0s 5ms/step - loss: 2.1735 - accuracy: 0.2133
Epoch 4/10
96/96 [==============================] - 1s 6ms/step - loss: 2.1478 - accuracy: 0.2202
Epoch 5/10
96/96 [==============================] - 0s 5ms/step - loss: 2.1142 - accuracy: 0.2256
Epoch 6/10
96/96 [==============================] - 0s 5ms/step - loss: 2.0880 - accuracy: 0.2296
Epoch 7/10
96/96 [==============================] - 0s 5ms/step - loss: 2.0700 - accuracy: 0.2351
Epoch 8/10
96/96 [==============================] - 1s 5ms/step - loss: 2.0394 - accuracy: 0.2514
Epoch 9/10
96/96 [==============================] - 0s 5ms/step - loss: 2.0189 - accuracy: 0.2580
Epoch 10/10
96/96 [==============================] - 0s 5ms/step - loss: 1.9985 - accuracy: 0.2672
814/814 [==============================] - 3s 3ms/step - loss: 2.0147 - accuracy: 0.2505
Test Accuracy (Batch 2): 25.05%
Epoch 1/10
96/96 [==============================] - 0s 5ms/step - loss: 2.0077 - accuracy: 0.2636
Epoch 2/10
96/96 [==============================] - 0s 4ms/step - loss: 1.9859 - accuracy: 0.2849
Epoch 3/10
96/96 [==============================] - 0s 4ms/step - loss: 1.9747 - accuracy: 0.2867
Epoch 4/10
96/96 [==============================] - 0s 5ms/step - loss: 1.9631 - accuracy: 0.2978
Epoch 5/10
96/96 [==============================] - 0s 5ms/step - loss: 1.9568 - accuracy: 0.2912
Epoch 6/10
96/96 [==============================] - 0s 5ms/step - loss: 1.9469 - accuracy: 0.2994
Epoch 7/10
96/96 [==============================] - 0s 4ms/step - loss: 1.9353 - accuracy: 0.2998
Epoch 8/10
96/96 [==============================] - 0s 5ms/step - loss: 1.9269 - accuracy: 0.3060
Epoch 9/10
96/96 [==============================] - 0s 5ms/step - loss: 1.9266 - accuracy: 0.3044
Epoch 10/10
96/96 [==============================] - 0s 5ms/step - loss: 1.9142 - accuracy: 0.3028
814/814 [==============================] - 3s 3ms/step - loss: 1.9148 - accuracy: 0.3203
Test Accuracy (Batch 3): 32.03%
Epoch 1/10
96/96 [==============================] - 1s 6ms/step - loss: 1.9221 - accuracy: 0.3055
Epoch 2/10
96/96 [==============================] - 1s 6ms/step - loss: 1.9091 - accuracy: 0.3096
Epoch 3/10
96/96 [==============================] - 1s 6ms/step - loss: 1.9027 - accuracy: 0.3109
Epoch 4/10
96/96 [==============================] - 1s 6ms/step - loss: 1.8931 - accuracy: 0.3139
Epoch 5/10
96/96 [==============================] - 1s 7ms/step - loss: 1.8897 - accuracy: 0.3166
Epoch 6/10
96/96 [==============================] - 0s 5ms/step - loss: 1.8962 - accuracy: 0.3070
Epoch 7/10
96/96 [==============================] - 0s 4ms/step - loss: 1.8863 - accuracy: 0.3117
Epoch 8/10
96/96 [==============================] - 0s 5ms/step - loss: 1.8826 - accuracy: 0.3126
Epoch 9/10
96/96 [==============================] - 0s 5ms/step - loss: 1.8766 - accuracy: 0.3134
Epoch 10/10
96/96 [==============================] - 0s 5ms/step - loss: 1.8702 - accuracy: 0.3166
814/814 [==============================] - 3s 3ms/step - loss: 1.8765 - accuracy: 0.3221
Test Accuracy (Batch 4): 32.21%
Epoch 1/10
96/96 [==============================] - 0s 5ms/step - loss: 1.8696 - accuracy: 0.3230
Epoch 2/10
96/96 [==============================] - 1s 6ms/step - loss: 1.8605 - accuracy: 0.3215
Epoch 3/10
96/96 [==============================] - 0s 4ms/step - loss: 1.8557 - accuracy: 0.3224
Epoch 4/10
96/96 [==============================] - 0s 5ms/step - loss: 1.8434 - accuracy: 0.3284
Epoch 5/10
96/96 [==============================] - 1s 6ms/step - loss: 1.8655 - accuracy: 0.3147
Epoch 6/10
96/96 [==============================] - 0s 5ms/step - loss: 1.8451 - accuracy: 0.3281
Epoch 7/10
96/96 [==============================] - 1s 8ms/step - loss: 1.8411 - accuracy: 0.3303
Epoch 8/10
96/96 [==============================] - 1s 10ms/step - loss: 1.8362 - accuracy: 0.3307
Epoch 9/10
96/96 [==============================] - 1s 6ms/step - loss: 1.8302 - accuracy: 0.3277
Epoch 10/10
96/96 [==============================] - 1s 6ms/step - loss: 1.8391 - accuracy: 0.3270
814/814 [==============================] - 3s 4ms/step - loss: 1.8804 - accuracy: 0.3238
Test Accuracy (Batch 5): 32.38%
Epoch 1/10
96/96 [==============================] - 1s 6ms/step - loss: 1.8594 - accuracy: 0.3233
Epoch 2/10
96/96 [==============================] - 0s 5ms/step - loss: 1.8627 - accuracy: 0.3141
Epoch 3/10
96/96 [==============================] - 0s 4ms/step - loss: 1.8459 - accuracy: 0.3230
Epoch 4/10
96/96 [==============================] - 0s 5ms/step - loss: 1.8649 - accuracy: 0.3155
Epoch 5/10
96/96 [==============================] - 0s 5ms/step - loss: 1.8325 - accuracy: 0.3242
Epoch 6/10
96/96 [==============================] - 0s 5ms/step - loss: 1.8355 - accuracy: 0.3275
Epoch 7/10
96/96 [==============================] - 0s 5ms/step - loss: 1.8282 - accuracy: 0.3284
Epoch 8/10
96/96 [==============================] - 0s 5ms/step - loss: 1.8382 - accuracy: 0.3253
Epoch 9/10
96/96 [==============================] - 0s 5ms/step - loss: 1.8274 - accuracy: 0.3285
Epoch 10/10
96/96 [==============================] - 0s 5ms/step - loss: 1.8234 - accuracy: 0.3289
814/814 [==============================] - 3s 4ms/step - loss: 1.8876 - accuracy: 0.3253
Test Accuracy (Batch 6): 32.53%
Batch-1: 20.14%
Batch-2: 25.05%
Batch-3: 32.03%
Batch-4: 32.21%
Batch-5: 32.38%
Batch-6: 32.53%

#### Batches 5

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.optimizers import Adam

# x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=42)
# Normalize the input data
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

# Convert the labels to one-hot encoding
num_classes = 10
# y_train = tf.keras.utils.to_categorical(y_train, num_classes)
# y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training set into 20 batches
num_batches = 5
x_train_batches = np.array_split(x_train, num_batches)
y_train_batches = np.array_split(y_train, num_batches)

# Initialize the list to store test accuracies
accuracies = []

# Define the model architecture
model = Sequential([
    Flatten(input_shape=(32, 32, 3)),
    Dense(128, activation='relu'),
    Dense(num_classes, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch
epochs = 10
for i in range(num_batches):
    x_train_batch = x_train_batches[i]
    y_train_batch = y_train_batches[i]
    model.fit(x_train_batch, y_train_batch, batch_size=128, epochs=epochs, verbose=1)

    # Evaluate the model on the test set
    test_loss, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy (Batch {}): {:.2f}%".format(i+1, test_accuracy*100))
    accuracies.append(test_accuracy)

# Print the batch accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Batch-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
115/115 [==============================] - 2s 5ms/step - loss: 2.2466 - accuracy: 0.1895
Epoch 2/10
115/115 [==============================] - 1s 5ms/step - loss: 2.2369 - accuracy: 0.1913
Epoch 3/10
115/115 [==============================] - 1s 5ms/step - loss: 2.2360 - accuracy: 0.1913
Epoch 4/10
115/115 [==============================] - 1s 5ms/step - loss: 2.2341 - accuracy: 0.1913
Epoch 5/10
115/115 [==============================] - 1s 5ms/step - loss: 2.2328 - accuracy: 0.1913
Epoch 6/10
115/115 [==============================] - 1s 5ms/step - loss: 2.2312 - accuracy: 0.1913
Epoch 7/10
115/115 [==============================] - 1s 5ms/step - loss: 2.2297 - accuracy: 0.1913
Epoch 8/10
115/115 [==============================] - 1s 5ms/step - loss: 2.2281 - accuracy: 0.1913
Epoch 9/10
115/115 [==============================] - 1s 5ms/step - loss: 2.2258 - accuracy: 0.1913
Epoch 10/10
115/115 [==============================] - 1s 5ms/step - loss: 2.2231 - accuracy: 0.1915
814/814 [==============================] - 3s 4ms/step - loss: 2.2161 - accuracy: 0.1959
Test Accuracy (Batch 1): 19.59%
Epoch 1/10
115/115 [==============================] - 1s 5ms/step - loss: 2.2258 - accuracy: 0.1903
Epoch 2/10
115/115 [==============================] - 1s 5ms/step - loss: 2.2219 - accuracy: 0.1884
Epoch 3/10
115/115 [==============================] - 1s 5ms/step - loss: 2.2175 - accuracy: 0.1900
Epoch 4/10
115/115 [==============================] - 1s 5ms/step - loss: 2.2122 - accuracy: 0.1908
Epoch 5/10
115/115 [==============================] - 1s 5ms/step - loss: 2.2075 - accuracy: 0.1918
Epoch 6/10
115/115 [==============================] - 1s 5ms/step - loss: 2.2012 - accuracy: 0.1936
Epoch 7/10
115/115 [==============================] - 1s 8ms/step - loss: 2.1951 - accuracy: 0.1994
Epoch 8/10
115/115 [==============================] - 1s 6ms/step - loss: 2.1878 - accuracy: 0.2026
Epoch 9/10
115/115 [==============================] - 1s 7ms/step - loss: 2.1802 - accuracy: 0.2039
Epoch 10/10
115/115 [==============================] - 1s 5ms/step - loss: 2.1712 - accuracy: 0.2129
814/814 [==============================] - 3s 3ms/step - loss: 2.1682 - accuracy: 0.2161
Test Accuracy (Batch 2): 21.61%
Epoch 1/10
115/115 [==============================] - 1s 5ms/step - loss: 2.1669 - accuracy: 0.2155
Epoch 2/10
115/115 [==============================] - 1s 4ms/step - loss: 2.1549 - accuracy: 0.2219
Epoch 3/10
115/115 [==============================] - 1s 5ms/step - loss: 2.1412 - accuracy: 0.2278
Epoch 4/10
115/115 [==============================] - 1s 4ms/step - loss: 2.1274 - accuracy: 0.2315
Epoch 5/10
115/115 [==============================] - 1s 5ms/step - loss: 2.1126 - accuracy: 0.2377
Epoch 6/10
115/115 [==============================] - 1s 6ms/step - loss: 2.0975 - accuracy: 0.2407
Epoch 7/10
115/115 [==============================] - 1s 5ms/step - loss: 2.0821 - accuracy: 0.2441
Epoch 8/10
115/115 [==============================] - 1s 5ms/step - loss: 2.0676 - accuracy: 0.2514
Epoch 9/10
115/115 [==============================] - 1s 7ms/step - loss: 2.0514 - accuracy: 0.2580
Epoch 10/10
115/115 [==============================] - 1s 6ms/step - loss: 2.0360 - accuracy: 0.2689
814/814 [==============================] - 3s 3ms/step - loss: 2.0271 - accuracy: 0.2918
Test Accuracy (Batch 3): 29.18%
Epoch 1/10
115/115 [==============================] - 1s 6ms/step - loss: 2.0198 - accuracy: 0.2837
Epoch 2/10
115/115 [==============================] - 1s 6ms/step - loss: 2.0026 - accuracy: 0.2933
Epoch 3/10
115/115 [==============================] - 1s 8ms/step - loss: 1.9864 - accuracy: 0.3007
Epoch 4/10
115/115 [==============================] - 1s 6ms/step - loss: 1.9714 - accuracy: 0.3078
Epoch 5/10
115/115 [==============================] - 1s 5ms/step - loss: 1.9542 - accuracy: 0.3169
Epoch 6/10
115/115 [==============================] - 1s 5ms/step - loss: 1.9369 - accuracy: 0.3252
Epoch 7/10
115/115 [==============================] - 1s 5ms/step - loss: 1.9212 - accuracy: 0.3323
Epoch 8/10
115/115 [==============================] - 1s 5ms/step - loss: 1.9058 - accuracy: 0.3388
Epoch 9/10
115/115 [==============================] - 1s 5ms/step - loss: 1.8908 - accuracy: 0.3455
Epoch 10/10
115/115 [==============================] - 1s 5ms/step - loss: 1.8768 - accuracy: 0.3523
814/814 [==============================] - 3s 4ms/step - loss: 1.8792 - accuracy: 0.3548
Test Accuracy (Batch 4): 35.48%
Epoch 1/10
115/115 [==============================] - 1s 5ms/step - loss: 1.8770 - accuracy: 0.3533
Epoch 2/10
115/115 [==============================] - 1s 5ms/step - loss: 1.8615 - accuracy: 0.3596
Epoch 3/10
115/115 [==============================] - 1s 7ms/step - loss: 1.8496 - accuracy: 0.3657
Epoch 4/10
115/115 [==============================] - 1s 7ms/step - loss: 1.8331 - accuracy: 0.3747
Epoch 5/10
115/115 [==============================] - 1s 6ms/step - loss: 1.8213 - accuracy: 0.3774
Epoch 6/10
115/115 [==============================] - 1s 6ms/step - loss: 1.8080 - accuracy: 0.3884
Epoch 7/10
115/115 [==============================] - 1s 5ms/step - loss: 1.7972 - accuracy: 0.3914
Epoch 8/10
115/115 [==============================] - 1s 5ms/step - loss: 1.7840 - accuracy: 0.3976
Epoch 9/10
115/115 [==============================] - 1s 5ms/step - loss: 1.7714 - accuracy: 0.4015
Epoch 10/10
115/115 [==============================] - 1s 5ms/step - loss: 1.7596 - accuracy: 0.4055
814/814 [==============================] - 3s 4ms/step - loss: 1.7665 - accuracy: 0.3972
Test Accuracy (Batch 5): 39.72%
Batch-1: 19.59%
Batch-2: 21.61%
Batch-3: 29.18%
Batch-4: 35.48%
Batch-5: 39.72%

#### Batches 4

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.optimizers import Adam

# x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=42)
# Normalize the input data
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

# Convert the labels to one-hot encoding
num_classes = 10
# y_train = tf.keras.utils.to_categorical(y_train, num_classes)
# y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training set into 20 batches
num_batches = 4
x_train_batches = np.array_split(x_train, num_batches)
y_train_batches = np.array_split(y_train, num_batches)

# Initialize the list to store test accuracies
accuracies = []

# Define the model architecture
model = Sequential([
    Flatten(input_shape=(32, 32, 3)),
    Dense(128, activation='relu'),
    Dense(num_classes, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch
epochs = 10
for i in range(num_batches):
    x_train_batch = x_train_batches[i]
    y_train_batch = y_train_batches[i]
    model.fit(x_train_batch, y_train_batch, batch_size=128, epochs=epochs, verbose=1)

    # Evaluate the model on the test set
    test_loss, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy (Batch {}): {:.2f}%".format(i+1, test_accuracy*100))
    accuracies.append(test_accuracy)

# Print the batch accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Batch-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
144/144 [==============================] - 5s 9ms/step - loss: 2.3032 - accuracy: 0.1781
Epoch 2/10
144/144 [==============================] - 1s 7ms/step - loss: 2.2432 - accuracy: 0.1849
Epoch 3/10
144/144 [==============================] - 1s 7ms/step - loss: 2.2349 - accuracy: 0.1915
Epoch 4/10
144/144 [==============================] - 1s 7ms/step - loss: 2.2241 - accuracy: 0.1973
Epoch 5/10
144/144 [==============================] - 1s 6ms/step - loss: 2.2191 - accuracy: 0.1906
Epoch 6/10
144/144 [==============================] - 1s 6ms/step - loss: 2.1936 - accuracy: 0.1910
Epoch 7/10
144/144 [==============================] - 1s 6ms/step - loss: 2.1695 - accuracy: 0.1912
Epoch 8/10
144/144 [==============================] - 1s 6ms/step - loss: 2.1429 - accuracy: 0.2020
Epoch 9/10
144/144 [==============================] - 1s 5ms/step - loss: 2.1190 - accuracy: 0.2096
Epoch 10/10
144/144 [==============================] - 1s 6ms/step - loss: 2.1028 - accuracy: 0.2188
814/814 [==============================] - 4s 4ms/step - loss: 2.1031 - accuracy: 0.2379
Test Accuracy (Batch 1): 23.79%
Epoch 1/10
144/144 [==============================] - 1s 7ms/step - loss: 2.1024 - accuracy: 0.2249
Epoch 2/10
144/144 [==============================] - 1s 5ms/step - loss: 2.0883 - accuracy: 0.2335
Epoch 3/10
144/144 [==============================] - 1s 5ms/step - loss: 2.0769 - accuracy: 0.2385
Epoch 4/10
144/144 [==============================] - 1s 6ms/step - loss: 2.0719 - accuracy: 0.2398
Epoch 5/10
144/144 [==============================] - 1s 6ms/step - loss: 2.0638 - accuracy: 0.2444
Epoch 6/10
144/144 [==============================] - 1s 7ms/step - loss: 2.0582 - accuracy: 0.2468
Epoch 7/10
144/144 [==============================] - 1s 6ms/step - loss: 2.0513 - accuracy: 0.2485
Epoch 8/10
144/144 [==============================] - 1s 6ms/step - loss: 2.0485 - accuracy: 0.2507
Epoch 9/10
144/144 [==============================] - 1s 5ms/step - loss: 2.0427 - accuracy: 0.2522
Epoch 10/10
144/144 [==============================] - 1s 5ms/step - loss: 2.0371 - accuracy: 0.2549
814/814 [==============================] - 4s 4ms/step - loss: 2.0894 - accuracy: 0.2540
Test Accuracy (Batch 2): 25.40%
Epoch 1/10
144/144 [==============================] - 1s 6ms/step - loss: 2.0427 - accuracy: 0.2551
Epoch 2/10
144/144 [==============================] - 1s 6ms/step - loss: 2.0316 - accuracy: 0.2590
Epoch 3/10
144/144 [==============================] - 1s 5ms/step - loss: 2.0328 - accuracy: 0.2579
Epoch 4/10
144/144 [==============================] - 1s 6ms/step - loss: 2.0261 - accuracy: 0.2606
Epoch 5/10
144/144 [==============================] - 1s 6ms/step - loss: 2.0237 - accuracy: 0.2615
Epoch 6/10
144/144 [==============================] - 1s 6ms/step - loss: 2.0202 - accuracy: 0.2620
Epoch 7/10
144/144 [==============================] - 1s 7ms/step - loss: 2.0201 - accuracy: 0.2626
Epoch 8/10
144/144 [==============================] - 1s 8ms/step - loss: 2.0206 - accuracy: 0.2625
Epoch 9/10
144/144 [==============================] - 1s 6ms/step - loss: 2.0152 - accuracy: 0.2626
Epoch 10/10
144/144 [==============================] - 1s 5ms/step - loss: 2.0126 - accuracy: 0.2648
814/814 [==============================] - 4s 4ms/step - loss: 2.0548 - accuracy: 0.2664
Test Accuracy (Batch 3): 26.64%
Epoch 1/10
144/144 [==============================] - 1s 7ms/step - loss: 2.0330 - accuracy: 0.2590
Epoch 2/10
144/144 [==============================] - 1s 7ms/step - loss: 2.0248 - accuracy: 0.2631
Epoch 3/10
144/144 [==============================] - 1s 10ms/step - loss: 2.0232 - accuracy: 0.2640
Epoch 4/10
144/144 [==============================] - 1s 6ms/step - loss: 2.0222 - accuracy: 0.2618
Epoch 5/10
144/144 [==============================] - 1s 5ms/step - loss: 2.0240 - accuracy: 0.2623
Epoch 6/10
144/144 [==============================] - 1s 5ms/step - loss: 2.0217 - accuracy: 0.2625
Epoch 7/10
144/144 [==============================] - 1s 5ms/step - loss: 2.0213 - accuracy: 0.2619
Epoch 8/10
144/144 [==============================] - 1s 5ms/step - loss: 2.0184 - accuracy: 0.2630
Epoch 9/10
144/144 [==============================] - 1s 5ms/step - loss: 2.0198 - accuracy: 0.2644
Epoch 10/10
144/144 [==============================] - 1s 5ms/step - loss: 2.0189 - accuracy: 0.2640
814/814 [==============================] - 5s 7ms/step - loss: 2.0491 - accuracy: 0.2686
Test Accuracy (Batch 4): 26.86%
Batch-1: 23.79%
Batch-2: 25.40%
Batch-3: 26.64%
Batch-4: 26.86%

#### Batches 2

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.optimizers import Adam

# x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=42)
# Normalize the input data
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

# Convert the labels to one-hot encoding
num_classes = 10
# y_train = tf.keras.utils.to_categorical(y_train, num_classes)
# y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training set into 20 batches
num_batches = 2
x_train_batches = np.array_split(x_train, num_batches)
y_train_batches = np.array_split(y_train, num_batches)

# Initialize the list to store test accuracies
accuracies = []

# Define the model architecture
model = Sequential([
    Flatten(input_shape=(32, 32, 3)),
    Dense(128, activation='relu'),
    Dense(num_classes, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch
epochs = 10
for i in range(num_batches):
    x_train_batch = x_train_batches[i]
    y_train_batch = y_train_batches[i]
    model.fit(x_train_batch, y_train_batch, batch_size=128, epochs=epochs, verbose=1)

    # Evaluate the model on the test set
    test_loss, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy (Batch {}): {:.2f}%".format(i+1, test_accuracy*100))
    accuracies.append(test_accuracy)

# Print the batch accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Batch-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
287/287 [==============================] - 4s 5ms/step - loss: 2.2714 - accuracy: 0.1793
Epoch 2/10
287/287 [==============================] - 1s 5ms/step - loss: 2.2348 - accuracy: 0.1911
Epoch 3/10
287/287 [==============================] - 1s 5ms/step - loss: 2.2225 - accuracy: 0.1925
Epoch 4/10
287/287 [==============================] - 1s 5ms/step - loss: 2.2115 - accuracy: 0.1874
Epoch 5/10
287/287 [==============================] - 2s 6ms/step - loss: 2.1736 - accuracy: 0.2054
Epoch 6/10
287/287 [==============================] - 2s 6ms/step - loss: 2.0916 - accuracy: 0.2416
Epoch 7/10
287/287 [==============================] - 1s 5ms/step - loss: 2.0425 - accuracy: 0.2691
Epoch 8/10
287/287 [==============================] - 1s 5ms/step - loss: 2.0145 - accuracy: 0.2842
Epoch 9/10
287/287 [==============================] - 1s 5ms/step - loss: 1.9860 - accuracy: 0.3017
Epoch 10/10
287/287 [==============================] - 1s 5ms/step - loss: 1.9694 - accuracy: 0.3083
814/814 [==============================] - 3s 4ms/step - loss: 2.0196 - accuracy: 0.3061
Test Accuracy (Batch 1): 30.61%
Epoch 1/10
287/287 [==============================] - 1s 5ms/step - loss: 1.9646 - accuracy: 0.3111
Epoch 2/10
287/287 [==============================] - 1s 5ms/step - loss: 1.9545 - accuracy: 0.3146
Epoch 3/10
287/287 [==============================] - 2s 5ms/step - loss: 1.9439 - accuracy: 0.3191
Epoch 4/10
287/287 [==============================] - 2s 7ms/step - loss: 1.9373 - accuracy: 0.3206
Epoch 5/10
287/287 [==============================] - 1s 4ms/step - loss: 1.9301 - accuracy: 0.3245
Epoch 6/10
287/287 [==============================] - 1s 5ms/step - loss: 1.8760 - accuracy: 0.3575
Epoch 7/10
287/287 [==============================] - 1s 5ms/step - loss: 1.8623 - accuracy: 0.3581
Epoch 8/10
287/287 [==============================] - 1s 5ms/step - loss: 1.8514 - accuracy: 0.3637
Epoch 9/10
287/287 [==============================] - 1s 5ms/step - loss: 1.8432 - accuracy: 0.3645
Epoch 10/10
287/287 [==============================] - 2s 6ms/step - loss: 1.8448 - accuracy: 0.3625
814/814 [==============================] - 4s 5ms/step - loss: 1.9255 - accuracy: 0.3479
Test Accuracy (Batch 2): 34.79%
Batch-1: 30.61%
Batch-2: 34.79%

### Caltech101

#### Batches 20

In [ ]:
import tensorflow_datasets as tfds
import numpy as np
from skimage.transform import resize

# Load the Caltech 101 dataset
dataset_name = "caltech101"
builder = tfds.builder(dataset_name)

# Download and prepare the dataset
builder.download_and_prepare()

# Split the dataset into training and testing sets
train_dataset = builder.as_dataset(split="train")
test_dataset = builder.as_dataset(split="test")

# Iterate through the datasets to get features and labels
X_train = []
y_train = []
for example in tfds.as_numpy(train_dataset):
    X_train.append(example["image"])
    y_train.append(example["label"])

X_test = []
y_test = []
for example in tfds.as_numpy(test_dataset):
    X_test.append(example["image"])
    y_test.append(example["label"])

# Convert lists to numpy arrays
X_train = np.array(X_train)
y_train = np.array(y_train)
X_test = np.array(X_test)
y_test = np.array(y_test)

# Resize the image data to a common size
target_height, target_width, channels = 28, 28, 3
X_train_resized = np.array([resize(image, (target_height, target_width, channels)) for image in X_train])
X_test_resized = np.array([resize(image, (target_height, target_width, channels)) for image in X_test])

# Print the shape of the resized arrays
print("X_train resized shape:", X_train_resized.shape)
print("X_test resized shape:", X_test_resized.shape)

<ipython-input-1-d3b8c391cf7a>:30: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  X_train = np.array(X_train)
<ipython-input-1-d3b8c391cf7a>:32: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  X_test = np.array(X_test)

X_train resized shape: (3060, 28, 28, 3)
X_test resized shape: (6084, 28, 28, 3)

In [ ]:
print(y_train.shape,y_test.shape)

(3060,) (6084,)

In [ ]:
import tensorflow as tf
y_train = tf.keras.utils.to_categorical(y_train, num_classes=102)
y_test = tf.keras.utils.to_categorical(y_test, num_classes=102)

In [ ]:
print(y_train.shape,y_test.shape)

(3060, 102) (6084, 102)

In [ ]:
import tensorflow as tf
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras import layers
# x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=42)
# Normalize the input data
x_train = X_train_resized.astype('float32') / 255.0
x_test = X_test_resized.astype('float32') / 255.0

# Convert the labels to one-hot encoding
num_classes = 102
# y_train = tf.keras.utils.to_categorical(y_train, num_classes)
# y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training set into 20 batches
num_batches = 20
x_train_batches = np.array_split(x_train, num_batches)
y_train_batches = np.array_split(y_train, num_batches)

# Initialize the list to store test accuracies
accuracies = []

# Define the model architecture
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(28, 28, 3)),
    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu'),
    layers.Dropout(0.25),
    Dense(num_classes, activation='softmax')
])


model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch
epochs = 10
for i in range(num_batches):
    x_train_batch = x_train_batches[i]
    y_train_batch = y_train_batches[i]
    model.fit(x_train_batch, y_train_batch, batch_size=128, epochs=epochs, verbose=1)

    # Evaluate the model on the test set
    test_loss, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy (Batch {}): {:.2f}%".format(i+1, test_accuracy*100))
    accuracies.append(test_accuracy)

# Print the batch accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Batch-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
2/2 [==============================] - 11s 286ms/step - loss: 4.6248 - accuracy: 0.0131
Epoch 2/10
2/2 [==============================] - 0s 15ms/step - loss: 4.6200 - accuracy: 0.0523
Epoch 3/10
2/2 [==============================] - 0s 14ms/step - loss: 4.6038 - accuracy: 0.0392
Epoch 4/10
2/2 [==============================] - 0s 13ms/step - loss: 4.5609 - accuracy: 0.0327
Epoch 5/10
2/2 [==============================] - 0s 13ms/step - loss: 4.4787 - accuracy: 0.0392
Epoch 6/10
2/2 [==============================] - 0s 24ms/step - loss: 4.4132 - accuracy: 0.0392
Epoch 7/10
2/2 [==============================] - 0s 16ms/step - loss: 4.4143 - accuracy: 0.0392
Epoch 8/10
2/2 [==============================] - 0s 13ms/step - loss: 4.3795 - accuracy: 0.0327
Epoch 9/10
2/2 [==============================] - 0s 12ms/step - loss: 4.3626 - accuracy: 0.0261
Epoch 10/10
2/2 [==============================] - 0s 12ms/step - loss: 4.3424 - accuracy: 0.0327
191/191 [==============================] - 1s 5ms/step - loss: 4.9437 - accuracy: 0.0059
Test Accuracy (Batch 1): 0.59%
Epoch 1/10
2/2 [==============================] - 0s 12ms/step - loss: 4.9519 - accuracy: 0.0000e+00
Epoch 2/10
2/2 [==============================] - 0s 13ms/step - loss: 4.8346 - accuracy: 0.0131
Epoch 3/10
2/2 [==============================] - 0s 13ms/step - loss: 4.6954 - accuracy: 0.0000e+00
Epoch 4/10
2/2 [==============================] - 0s 12ms/step - loss: 4.6388 - accuracy: 0.0261
Epoch 5/10
2/2 [==============================] - 0s 13ms/step - loss: 4.6133 - accuracy: 0.0131
Epoch 6/10
2/2 [==============================] - 0s 11ms/step - loss: 4.6113 - accuracy: 0.0131
Epoch 7/10
2/2 [==============================] - 0s 13ms/step - loss: 4.6086 - accuracy: 0.0196
Epoch 8/10
2/2 [==============================] - 0s 14ms/step - loss: 4.6058 - accuracy: 0.0196
Epoch 9/10
2/2 [==============================] - 0s 13ms/step - loss: 4.6055 - accuracy: 0.0131
Epoch 10/10
2/2 [==============================] - 0s 12ms/step - loss: 4.6032 - accuracy: 0.0131
191/191 [==============================] - 1s 4ms/step - loss: 4.6202 - accuracy: 0.0115
Test Accuracy (Batch 2): 1.15%
Epoch 1/10
2/2 [==============================] - 0s 14ms/step - loss: 4.6276 - accuracy: 0.0131
Epoch 2/10
2/2 [==============================] - 0s 13ms/step - loss: 4.6238 - accuracy: 0.0131
Epoch 3/10
2/2 [==============================] - 0s 14ms/step - loss: 4.6247 - accuracy: 0.0131
Epoch 4/10
2/2 [==============================] - 0s 13ms/step - loss: 4.6220 - accuracy: 0.0131
Epoch 5/10
2/2 [==============================] - 0s 15ms/step - loss: 4.6205 - accuracy: 0.0131
Epoch 6/10
2/2 [==============================] - 0s 13ms/step - loss: 4.6177 - accuracy: 0.0131
Epoch 7/10
2/2 [==============================] - 0s 12ms/step - loss: 4.6158 - accuracy: 0.0131
Epoch 8/10
2/2 [==============================] - 0s 13ms/step - loss: 4.6102 - accuracy: 0.0196
Epoch 9/10
2/2 [==============================] - 0s 15ms/step - loss: 4.6080 - accuracy: 0.0131
Epoch 10/10
2/2 [==============================] - 0s 14ms/step - loss: 4.6052 - accuracy: 0.0131
191/191 [==============================] - 1s 5ms/step - loss: 4.5999 - accuracy: 0.0115
Test Accuracy (Batch 3): 1.15%
Epoch 1/10
2/2 [==============================] - 0s 16ms/step - loss: 4.6387 - accuracy: 0.0131
Epoch 2/10
2/2 [==============================] - 0s 15ms/step - loss: 4.6427 - accuracy: 0.0065
Epoch 3/10
2/2 [==============================] - 0s 15ms/step - loss: 4.6366 - accuracy: 0.0065
Epoch 4/10
2/2 [==============================] - 0s 15ms/step - loss: 4.6359 - accuracy: 0.0065
Epoch 5/10
2/2 [==============================] - 0s 15ms/step - loss: 4.6351 - accuracy: 0.0065
Epoch 6/10
2/2 [==============================] - 0s 26ms/step - loss: 4.6286 - accuracy: 0.0131
Epoch 7/10
2/2 [==============================] - 0s 12ms/step - loss: 4.6212 - accuracy: 0.0196
Epoch 8/10
2/2 [==============================] - 0s 15ms/step - loss: 4.6204 - accuracy: 0.0196
Epoch 9/10
2/2 [==============================] - 0s 13ms/step - loss: 4.6150 - accuracy: 0.0000e+00
Epoch 10/10
2/2 [==============================] - 0s 12ms/step - loss: 4.6098 - accuracy: 0.0131
191/191 [==============================] - 1s 6ms/step - loss: 4.5949 - accuracy: 0.0044
Test Accuracy (Batch 4): 0.44%
Epoch 1/10
2/2 [==============================] - 0s 17ms/step - loss: 4.6458 - accuracy: 0.0000e+00
Epoch 2/10
2/2 [==============================] - 0s 14ms/step - loss: 4.6430 - accuracy: 0.0000e+00
Epoch 3/10
2/2 [==============================] - 0s 12ms/step - loss: 4.6351 - accuracy: 0.0000e+00
Epoch 4/10
2/2 [==============================] - 0s 24ms/step - loss: 4.6362 - accuracy: 0.0000e+00
Epoch 5/10
2/2 [==============================] - 0s 16ms/step - loss: 4.6270 - accuracy: 0.0065
Epoch 6/10
2/2 [==============================] - 0s 22ms/step - loss: 4.6237 - accuracy: 0.0065
Epoch 7/10
2/2 [==============================] - 0s 18ms/step - loss: 4.6130 - accuracy: 0.0131
Epoch 8/10
2/2 [==============================] - 0s 20ms/step - loss: 4.6074 - accuracy: 0.0131
Epoch 9/10
2/2 [==============================] - 0s 15ms/step - loss: 4.5933 - accuracy: 0.0131
Epoch 10/10
2/2 [==============================] - 0s 15ms/step - loss: 4.5839 - accuracy: 0.0065
191/191 [==============================] - 1s 6ms/step - loss: 4.6235 - accuracy: 0.0153
Test Accuracy (Batch 5): 1.53%
Epoch 1/10
2/2 [==============================] - 0s 17ms/step - loss: 4.6282 - accuracy: 0.0131
Epoch 2/10
2/2 [==============================] - 0s 14ms/step - loss: 4.6267 - accuracy: 0.0131
Epoch 3/10
2/2 [==============================] - 0s 15ms/step - loss: 4.6246 - accuracy: 0.0131
Epoch 4/10
2/2 [==============================] - 0s 15ms/step - loss: 4.6118 - accuracy: 0.0196
Epoch 5/10
2/2 [==============================] - 0s 30ms/step - loss: 4.6000 - accuracy: 0.0196
Epoch 6/10
2/2 [==============================] - 0s 13ms/step - loss: 4.5898 - accuracy: 0.0196
Epoch 7/10
2/2 [==============================] - 0s 15ms/step - loss: 4.5755 - accuracy: 0.0196
Epoch 8/10
2/2 [==============================] - 0s 13ms/step - loss: 4.5400 - accuracy: 0.0196
Epoch 9/10
2/2 [==============================] - 0s 13ms/step - loss: 4.5248 - accuracy: 0.0065
Epoch 10/10
2/2 [==============================] - 0s 14ms/step - loss: 4.4888 - accuracy: 0.0261
191/191 [==============================] - 1s 4ms/step - loss: 4.7728 - accuracy: 0.0048
Test Accuracy (Batch 6): 0.48%
Epoch 1/10
2/2 [==============================] - 0s 15ms/step - loss: 4.7961 - accuracy: 0.0196
Epoch 2/10
2/2 [==============================] - 0s 15ms/step - loss: 4.7819 - accuracy: 0.0000e+00
Epoch 3/10
2/2 [==============================] - 0s 14ms/step - loss: 4.7387 - accuracy: 0.0196
Epoch 4/10
2/2 [==============================] - 0s 13ms/step - loss: 4.6963 - accuracy: 0.0065
Epoch 5/10
2/2 [==============================] - 0s 13ms/step - loss: 4.6583 - accuracy: 0.0065
Epoch 6/10
2/2 [==============================] - 0s 15ms/step - loss: 4.6316 - accuracy: 0.0131
Epoch 7/10
2/2 [==============================] - 0s 13ms/step - loss: 4.6180 - accuracy: 0.0065
Epoch 8/10
2/2 [==============================] - 0s 13ms/step - loss: 4.6141 - accuracy: 0.0131
Epoch 9/10
2/2 [==============================] - 0s 16ms/step - loss: 4.6076 - accuracy: 0.0131
Epoch 10/10
2/2 [==============================] - 0s 16ms/step - loss: 4.6004 - accuracy: 0.0065
191/191 [==============================] - 1s 5ms/step - loss: 4.6257 - accuracy: 0.0153
Test Accuracy (Batch 7): 1.53%
Epoch 1/10
2/2 [==============================] - 0s 17ms/step - loss: 4.6606 - accuracy: 0.0196
Epoch 2/10
2/2 [==============================] - 0s 13ms/step - loss: 4.6500 - accuracy: 0.0131
Epoch 3/10
2/2 [==============================] - 0s 14ms/step - loss: 4.6526 - accuracy: 0.0196
Epoch 4/10
2/2 [==============================] - 0s 13ms/step - loss: 4.6479 - accuracy: 0.0131
Epoch 5/10
2/2 [==============================] - 0s 14ms/step - loss: 4.6422 - accuracy: 0.0065
Epoch 6/10
2/2 [==============================] - 0s 13ms/step - loss: 4.6344 - accuracy: 0.0196
Epoch 7/10
2/2 [==============================] - 0s 13ms/step - loss: 4.6314 - accuracy: 0.0196
Epoch 8/10
2/2 [==============================] - 0s 18ms/step - loss: 4.6255 - accuracy: 0.0065
Epoch 9/10
2/2 [==============================] - 0s 17ms/step - loss: 4.6219 - accuracy: 0.0065
Epoch 10/10
2/2 [==============================] - 0s 14ms/step - loss: 4.6182 - accuracy: 0.0065
191/191 [==============================] - 1s 6ms/step - loss: 4.6190 - accuracy: 0.0044
Test Accuracy (Batch 8): 0.44%
Epoch 1/10
2/2 [==============================] - 0s 16ms/step - loss: 4.6340 - accuracy: 0.0000e+00
Epoch 2/10
2/2 [==============================] - 0s 12ms/step - loss: 4.6336 - accuracy: 0.0065
Epoch 3/10
2/2 [==============================] - 0s 12ms/step - loss: 4.6304 - accuracy: 0.0065
Epoch 4/10
2/2 [==============================] - 0s 11ms/step - loss: 4.6299 - accuracy: 0.0065
Epoch 5/10
2/2 [==============================] - 0s 12ms/step - loss: 4.6251 - accuracy: 0.0065
Epoch 6/10
2/2 [==============================] - 0s 12ms/step - loss: 4.6241 - accuracy: 0.0065
Epoch 7/10
2/2 [==============================] - 0s 13ms/step - loss: 4.6198 - accuracy: 0.0196
Epoch 8/10
2/2 [==============================] - 0s 12ms/step - loss: 4.6163 - accuracy: 0.0196
Epoch 9/10
2/2 [==============================] - 0s 12ms/step - loss: 4.6122 - accuracy: 0.0196
Epoch 10/10
2/2 [==============================] - 0s 12ms/step - loss: 4.6049 - accuracy: 0.0196
191/191 [==============================] - 1s 4ms/step - loss: 4.6190 - accuracy: 0.0071
Test Accuracy (Batch 9): 0.71%
Epoch 1/10
2/2 [==============================] - 0s 23ms/step - loss: 4.6287 - accuracy: 0.0131
Epoch 2/10
2/2 [==============================] - 0s 14ms/step - loss: 4.6309 - accuracy: 0.0131
Epoch 3/10
2/2 [==============================] - 0s 13ms/step - loss: 4.6236 - accuracy: 0.0065
Epoch 4/10
2/2 [==============================] - 0s 14ms/step - loss: 4.6229 - accuracy: 0.0131
Epoch 5/10
2/2 [==============================] - 0s 12ms/step - loss: 4.6192 - accuracy: 0.0131
Epoch 6/10
2/2 [==============================] - 0s 12ms/step - loss: 4.6127 - accuracy: 0.0065
Epoch 7/10
2/2 [==============================] - 0s 23ms/step - loss: 4.6075 - accuracy: 0.0131
Epoch 8/10
2/2 [==============================] - 0s 14ms/step - loss: 4.6012 - accuracy: 0.0196
Epoch 9/10
2/2 [==============================] - 0s 14ms/step - loss: 4.5925 - accuracy: 0.0196
Epoch 10/10
2/2 [==============================] - 0s 15ms/step - loss: 4.5828 - accuracy: 0.0065
191/191 [==============================] - 1s 5ms/step - loss: 4.6227 - accuracy: 0.0071
Test Accuracy (Batch 10): 0.71%
Epoch 1/10
2/2 [==============================] - 0s 22ms/step - loss: 4.6496 - accuracy: 0.0196
Epoch 2/10
2/2 [==============================] - 0s 17ms/step - loss: 4.6506 - accuracy: 0.0131
Epoch 3/10
2/2 [==============================] - 0s 11ms/step - loss: 4.6453 - accuracy: 0.0131
Epoch 4/10
2/2 [==============================] - 0s 18ms/step - loss: 4.6324 - accuracy: 0.0196
Epoch 5/10
2/2 [==============================] - 0s 18ms/step - loss: 4.6322 - accuracy: 0.0065
Epoch 6/10
2/2 [==============================] - 0s 18ms/step - loss: 4.6209 - accuracy: 0.0196
Epoch 7/10
2/2 [==============================] - 0s 10ms/step - loss: 4.6141 - accuracy: 0.0196
Epoch 8/10
2/2 [==============================] - 0s 14ms/step - loss: 4.5951 - accuracy: 0.0131
Epoch 9/10
2/2 [==============================] - 0s 11ms/step - loss: 4.5804 - accuracy: 0.0261
Epoch 10/10
2/2 [==============================] - 0s 17ms/step - loss: 4.5572 - accuracy: 0.0327
191/191 [==============================] - 1s 5ms/step - loss: 4.6205 - accuracy: 0.0085
Test Accuracy (Batch 11): 0.85%
Epoch 1/10
2/2 [==============================] - 0s 17ms/step - loss: 4.6912 - accuracy: 0.0065
Epoch 2/10
2/2 [==============================] - 0s 14ms/step - loss: 4.6832 - accuracy: 0.0131
Epoch 3/10
2/2 [==============================] - 0s 13ms/step - loss: 4.6651 - accuracy: 0.0131
Epoch 4/10
2/2 [==============================] - 0s 26ms/step - loss: 4.6626 - accuracy: 0.0131
Epoch 5/10
2/2 [==============================] - 0s 13ms/step - loss: 4.6439 - accuracy: 0.0131
Epoch 6/10
2/2 [==============================] - 0s 13ms/step - loss: 4.6362 - accuracy: 0.0131
Epoch 7/10
2/2 [==============================] - 0s 22ms/step - loss: 4.6311 - accuracy: 0.0131
Epoch 8/10
2/2 [==============================] - 0s 12ms/step - loss: 4.6186 - accuracy: 0.0131
Epoch 9/10
2/2 [==============================] - 0s 12ms/step - loss: 4.6115 - accuracy: 0.0131
Epoch 10/10
2/2 [==============================] - 0s 14ms/step - loss: 4.6028 - accuracy: 0.0131
191/191 [==============================] - 1s 5ms/step - loss: 4.6155 - accuracy: 0.0085
Test Accuracy (Batch 12): 0.85%
Epoch 1/10
2/2 [==============================] - 0s 16ms/step - loss: 4.6374 - accuracy: 0.0065
Epoch 2/10
2/2 [==============================] - 0s 15ms/step - loss: 4.6424 - accuracy: 0.0065
Epoch 3/10
2/2 [==============================] - 0s 18ms/step - loss: 4.6391 - accuracy: 0.0065
Epoch 4/10
2/2 [==============================] - 0s 25ms/step - loss: 4.6380 - accuracy: 0.0065
Epoch 5/10
2/2 [==============================] - 0s 16ms/step - loss: 4.6318 - accuracy: 0.0065
Epoch 6/10
2/2 [==============================] - 0s 15ms/step - loss: 4.6275 - accuracy: 0.0065
Epoch 7/10
2/2 [==============================] - 0s 16ms/step - loss: 4.6239 - accuracy: 0.0065
Epoch 8/10
2/2 [==============================] - 0s 16ms/step - loss: 4.6236 - accuracy: 0.0065
Epoch 9/10
2/2 [==============================] - 0s 13ms/step - loss: 4.6199 - accuracy: 0.0065
Epoch 10/10
2/2 [==============================] - 0s 16ms/step - loss: 4.6171 - accuracy: 0.0065
191/191 [==============================] - 1s 5ms/step - loss: 4.6160 - accuracy: 0.0085
Test Accuracy (Batch 13): 0.85%
Epoch 1/10
2/2 [==============================] - 0s 17ms/step - loss: 4.6398 - accuracy: 0.0065
Epoch 2/10
2/2 [==============================] - 0s 13ms/step - loss: 4.6393 - accuracy: 0.0065
Epoch 3/10
2/2 [==============================] - 0s 28ms/step - loss: 4.6375 - accuracy: 0.0065
Epoch 4/10
2/2 [==============================] - 0s 17ms/step - loss: 4.6333 - accuracy: 0.0065
Epoch 5/10
2/2 [==============================] - 0s 15ms/step - loss: 4.6327 - accuracy: 0.0000e+00
Epoch 6/10
2/2 [==============================] - 0s 14ms/step - loss: 4.6328 - accuracy: 0.0065
Epoch 7/10
2/2 [==============================] - 0s 13ms/step - loss: 4.6280 - accuracy: 0.0065
Epoch 8/10
2/2 [==============================] - 0s 17ms/step - loss: 4.6270 - accuracy: 0.0065
Epoch 9/10
2/2 [==============================] - 0s 15ms/step - loss: 4.6265 - accuracy: 0.0131
Epoch 10/10
2/2 [==============================] - 0s 13ms/step - loss: 4.6240 - accuracy: 0.0131
191/191 [==============================] - 1s 6ms/step - loss: 4.6189 - accuracy: 0.0048
Test Accuracy (Batch 14): 0.48%
Epoch 1/10
2/2 [==============================] - 0s 17ms/step - loss: 4.6382 - accuracy: 0.0000e+00
Epoch 2/10
2/2 [==============================] - 0s 14ms/step - loss: 4.6369 - accuracy: 0.0000e+00
Epoch 3/10
2/2 [==============================] - 0s 13ms/step - loss: 4.6381 - accuracy: 0.0000e+00
Epoch 4/10
2/2 [==============================] - 0s 23ms/step - loss: 4.6354 - accuracy: 0.0000e+00
Epoch 5/10
2/2 [==============================] - 0s 14ms/step - loss: 4.6359 - accuracy: 0.0000e+00
Epoch 6/10
2/2 [==============================] - 0s 24ms/step - loss: 4.6347 - accuracy: 0.0000e+00
Epoch 7/10
2/2 [==============================] - 0s 14ms/step - loss: 4.6328 - accuracy: 0.0000e+00
Epoch 8/10
2/2 [==============================] - 0s 21ms/step - loss: 4.6307 - accuracy: 0.0000e+00
Epoch 9/10
2/2 [==============================] - 0s 14ms/step - loss: 4.6295 - accuracy: 0.0000e+00
Epoch 10/10
2/2 [==============================] - 0s 14ms/step - loss: 4.6281 - accuracy: 0.0000e+00
191/191 [==============================] - 1s 5ms/step - loss: 4.6241 - accuracy: 0.0048
Test Accuracy (Batch 15): 0.48%
Epoch 1/10
2/2 [==============================] - 0s 14ms/step - loss: 4.6341 - accuracy: 0.0065
Epoch 2/10
2/2 [==============================] - 0s 21ms/step - loss: 4.6328 - accuracy: 0.0065
Epoch 3/10
2/2 [==============================] - 0s 12ms/step - loss: 4.6321 - accuracy: 0.0065
Epoch 4/10
2/2 [==============================] - 0s 25ms/step - loss: 4.6321 - accuracy: 0.0065
Epoch 5/10
2/2 [==============================] - 0s 13ms/step - loss: 4.6300 - accuracy: 0.0065
Epoch 6/10
2/2 [==============================] - 0s 12ms/step - loss: 4.6292 - accuracy: 0.0000e+00
Epoch 7/10
2/2 [==============================] - 0s 11ms/step - loss: 4.6275 - accuracy: 0.0196
Epoch 8/10
2/2 [==============================] - 0s 13ms/step - loss: 4.6272 - accuracy: 0.0000e+00
Epoch 9/10
2/2 [==============================] - 0s 17ms/step - loss: 4.6261 - accuracy: 0.0196
Epoch 10/10
2/2 [==============================] - 0s 17ms/step - loss: 4.6247 - accuracy: 0.0196
191/191 [==============================] - 1s 5ms/step - loss: 4.6283 - accuracy: 0.0039
Test Accuracy (Batch 16): 0.39%
Epoch 1/10
2/2 [==============================] - 0s 14ms/step - loss: 4.6304 - accuracy: 0.0065
Epoch 2/10
2/2 [==============================] - 0s 20ms/step - loss: 4.6296 - accuracy: 0.0131
Epoch 3/10
2/2 [==============================] - 0s 12ms/step - loss: 4.6297 - accuracy: 0.0131
Epoch 4/10
2/2 [==============================] - 0s 12ms/step - loss: 4.6277 - accuracy: 0.0196
Epoch 5/10
2/2 [==============================] - 0s 21ms/step - loss: 4.6294 - accuracy: 0.0131
Epoch 6/10
2/2 [==============================] - 0s 44ms/step - loss: 4.6277 - accuracy: 0.0131
Epoch 7/10
2/2 [==============================] - 0s 33ms/step - loss: 4.6272 - accuracy: 0.0000e+00
Epoch 8/10
2/2 [==============================] - 0s 37ms/step - loss: 4.6260 - accuracy: 0.0196
Epoch 9/10
2/2 [==============================] - 0s 31ms/step - loss: 4.6241 - accuracy: 0.0196
Epoch 10/10
2/2 [==============================] - 0s 24ms/step - loss: 4.6241 - accuracy: 0.0131
191/191 [==============================] - 1s 6ms/step - loss: 4.6285 - accuracy: 0.0039
Test Accuracy (Batch 17): 0.39%
Epoch 1/10
2/2 [==============================] - 0s 15ms/step - loss: 4.6308 - accuracy: 0.0065
Epoch 2/10
2/2 [==============================] - 0s 14ms/step - loss: 4.6308 - accuracy: 0.0131
Epoch 3/10
2/2 [==============================] - 0s 13ms/step - loss: 4.6303 - accuracy: 0.0131
Epoch 4/10
2/2 [==============================] - 0s 14ms/step - loss: 4.6306 - accuracy: 0.0131
Epoch 5/10
2/2 [==============================] - 0s 16ms/step - loss: 4.6301 - accuracy: 0.0261
Epoch 6/10
2/2 [==============================] - 0s 13ms/step - loss: 4.6282 - accuracy: 0.0196
Epoch 7/10
2/2 [==============================] - 0s 16ms/step - loss: 4.6270 - accuracy: 0.0261
Epoch 8/10
2/2 [==============================] - 0s 14ms/step - loss: 4.6274 - accuracy: 0.0196
Epoch 9/10
2/2 [==============================] - 0s 16ms/step - loss: 4.6263 - accuracy: 0.0261
Epoch 10/10
2/2 [==============================] - 0s 15ms/step - loss: 4.6240 - accuracy: 0.0196
191/191 [==============================] - 1s 5ms/step - loss: 4.6283 - accuracy: 0.0039
Test Accuracy (Batch 18): 0.39%
Epoch 1/10
2/2 [==============================] - 0s 17ms/step - loss: 4.6334 - accuracy: 0.0065
Epoch 2/10
2/2 [==============================] - 0s 14ms/step - loss: 4.6334 - accuracy: 0.0000e+00
Epoch 3/10

#### Batches 10

In [ ]:
import tensorflow as tf
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras import layers
# x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=42)
# Normalize the input data
x_train = X_train_resized.astype('float32') / 255.0
x_test = X_test_resized.astype('float32') / 255.0

# Convert the labels to one-hot encoding
num_classes = 102
# y_train = tf.keras.utils.to_categorical(y_train, num_classes)
# y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training set into 20 batches
num_batches = 10
x_train_batches = np.array_split(x_train, num_batches)
y_train_batches = np.array_split(y_train, num_batches)

# Initialize the list to store test accuracies
accuracies = []

# Define the model architecture
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(28, 28, 3)),
    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu'),
    layers.Dropout(0.25),
    Dense(num_classes, activation='softmax')
])


model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch
epochs = 10
for i in range(num_batches):
    x_train_batch = x_train_batches[i]
    y_train_batch = y_train_batches[i]
    model.fit(x_train_batch, y_train_batch, batch_size=128, epochs=epochs, verbose=1)

    # Evaluate the model on the test set
    test_loss, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy (Batch {}): {:.2f}%".format(i+1, test_accuracy*100))
    accuracies.append(test_accuracy)

# Print the batch accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Batch-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
3/3 [==============================] - 5s 199ms/step - loss: 4.6251 - accuracy: 0.0098
Epoch 2/10
3/3 [==============================] - 0s 12ms/step - loss: 4.6207 - accuracy: 0.0327
Epoch 3/10
3/3 [==============================] - 0s 12ms/step - loss: 4.6056 - accuracy: 0.0196
Epoch 4/10
3/3 [==============================] - 0s 12ms/step - loss: 4.5704 - accuracy: 0.0098
Epoch 5/10
3/3 [==============================] - 0s 12ms/step - loss: 4.5186 - accuracy: 0.0163
Epoch 6/10
3/3 [==============================] - 0s 13ms/step - loss: 4.5167 - accuracy: 0.0392
Epoch 7/10
3/3 [==============================] - 0s 14ms/step - loss: 4.5051 - accuracy: 0.0229
Epoch 8/10
3/3 [==============================] - 0s 12ms/step - loss: 4.5072 - accuracy: 0.0261
Epoch 9/10
3/3 [==============================] - 0s 13ms/step - loss: 4.4916 - accuracy: 0.0196
Epoch 10/10
3/3 [==============================] - 0s 12ms/step - loss: 4.5202 - accuracy: 0.0131
191/191 [==============================] - 1s 4ms/step - loss: 4.7125 - accuracy: 0.0090
Test Accuracy (Batch 1): 0.90%
Epoch 1/10
3/3 [==============================] - 0s 16ms/step - loss: 4.7924 - accuracy: 0.0131
Epoch 2/10
3/3 [==============================] - 0s 16ms/step - loss: 4.6673 - accuracy: 0.0033
Epoch 3/10
3/3 [==============================] - 0s 14ms/step - loss: 4.6316 - accuracy: 0.0196
Epoch 4/10
3/3 [==============================] - 0s 15ms/step - loss: 4.6228 - accuracy: 0.0131
Epoch 5/10
3/3 [==============================] - 0s 14ms/step - loss: 4.6212 - accuracy: 0.0196
Epoch 6/10
3/3 [==============================] - 0s 15ms/step - loss: 4.6203 - accuracy: 0.0196
Epoch 7/10
3/3 [==============================] - 0s 14ms/step - loss: 4.6200 - accuracy: 0.0065
Epoch 8/10
3/3 [==============================] - 0s 26ms/step - loss: 4.6177 - accuracy: 0.0163
Epoch 9/10
3/3 [==============================] - 0s 31ms/step - loss: 4.6160 - accuracy: 0.0163
Epoch 10/10
3/3 [==============================] - 0s 19ms/step - loss: 4.6125 - accuracy: 0.0098
191/191 [==============================] - 1s 5ms/step - loss: 4.6022 - accuracy: 6.5746e-04
Test Accuracy (Batch 2): 0.07%
Epoch 1/10
3/3 [==============================] - 0s 16ms/step - loss: 4.6356 - accuracy: 0.0098
Epoch 2/10
3/3 [==============================] - 0s 16ms/step - loss: 4.6342 - accuracy: 0.0033
Epoch 3/10
3/3 [==============================] - 0s 16ms/step - loss: 4.6316 - accuracy: 0.0131
Epoch 4/10
3/3 [==============================] - 0s 15ms/step - loss: 4.6265 - accuracy: 0.0163
Epoch 5/10
3/3 [==============================] - 0s 13ms/step - loss: 4.6217 - accuracy: 0.0131
Epoch 6/10
3/3 [==============================] - 0s 13ms/step - loss: 4.6163 - accuracy: 0.0131
Epoch 7/10
3/3 [==============================] - 0s 16ms/step - loss: 4.6127 - accuracy: 0.0131
Epoch 8/10
3/3 [==============================] - 0s 13ms/step - loss: 4.6055 - accuracy: 0.0261
Epoch 9/10
3/3 [==============================] - 0s 15ms/step - loss: 4.5896 - accuracy: 0.0196
Epoch 10/10
3/3 [==============================] - 0s 13ms/step - loss: 4.5722 - accuracy: 0.0163
191/191 [==============================] - 1s 4ms/step - loss: 4.6391 - accuracy: 0.0015
Test Accuracy (Batch 3): 0.15%
Epoch 1/10
3/3 [==============================] - 0s 15ms/step - loss: 4.6729 - accuracy: 0.0131
Epoch 2/10
3/3 [==============================] - 0s 15ms/step - loss: 4.6735 - accuracy: 0.0098
Epoch 3/10
3/3 [==============================] - 0s 17ms/step - loss: 4.6543 - accuracy: 0.0065
Epoch 4/10
3/3 [==============================] - 0s 14ms/step - loss: 4.6354 - accuracy: 0.0131
Epoch 5/10
3/3 [==============================] - 0s 13ms/step - loss: 4.6255 - accuracy: 0.0131
Epoch 6/10
3/3 [==============================] - 0s 13ms/step - loss: 4.6161 - accuracy: 0.0163
Epoch 7/10
3/3 [==============================] - 0s 13ms/step - loss: 4.6086 - accuracy: 0.0131
Epoch 8/10
3/3 [==============================] - 0s 14ms/step - loss: 4.5983 - accuracy: 0.0131
Epoch 9/10
3/3 [==============================] - 0s 16ms/step - loss: 4.5900 - accuracy: 0.0196
Epoch 10/10
3/3 [==============================] - 0s 12ms/step - loss: 4.5804 - accuracy: 0.0229
191/191 [==============================] - 1s 4ms/step - loss: 4.6284 - accuracy: 0.0044
Test Accuracy (Batch 4): 0.44%
Epoch 1/10
3/3 [==============================] - 0s 18ms/step - loss: 4.6771 - accuracy: 0.0000e+00
Epoch 2/10
3/3 [==============================] - 0s 18ms/step - loss: 4.6660 - accuracy: 0.0033
Epoch 3/10
3/3 [==============================] - 0s 16ms/step - loss: 4.6455 - accuracy: 0.0000e+00
Epoch 4/10
3/3 [==============================] - 0s 13ms/step - loss: 4.6336 - accuracy: 0.0065
Epoch 5/10
3/3 [==============================] - 0s 18ms/step - loss: 4.6195 - accuracy: 0.0294
Epoch 6/10
3/3 [==============================] - 0s 21ms/step - loss: 4.6048 - accuracy: 0.0163
Epoch 7/10
3/3 [==============================] - 0s 22ms/step - loss: 4.5973 - accuracy: 0.0196
Epoch 8/10
3/3 [==============================] - 0s 22ms/step - loss: 4.5810 - accuracy: 0.0261
Epoch 9/10
3/3 [==============================] - 0s 24ms/step - loss: 4.5667 - accuracy: 0.0196
Epoch 10/10
3/3 [==============================] - 0s 21ms/step - loss: 4.5477 - accuracy: 0.0229
191/191 [==============================] - 1s 5ms/step - loss: 4.6022 - accuracy: 0.0100
Test Accuracy (Batch 5): 1.00%
Epoch 1/10
3/3 [==============================] - 0s 16ms/step - loss: 4.6882 - accuracy: 0.0065
Epoch 2/10
3/3 [==============================] - 0s 18ms/step - loss: 4.6898 - accuracy: 0.0098
Epoch 3/10
3/3 [==============================] - 0s 17ms/step - loss: 4.6715 - accuracy: 0.0033
Epoch 4/10
3/3 [==============================] - 0s 15ms/step - loss: 4.6542 - accuracy: 0.0065
Epoch 5/10
3/3 [==============================] - 0s 14ms/step - loss: 4.6286 - accuracy: 0.0033
Epoch 6/10
3/3 [==============================] - 0s 15ms/step - loss: 4.6232 - accuracy: 0.0065
Epoch 7/10
3/3 [==============================] - 0s 13ms/step - loss: 4.6142 - accuracy: 0.0163
Epoch 8/10
3/3 [==============================] - 0s 15ms/step - loss: 4.6108 - accuracy: 0.0196
Epoch 9/10
3/3 [==============================] - 0s 15ms/step - loss: 4.6106 - accuracy: 0.0163
Epoch 10/10
3/3 [==============================] - 0s 14ms/step - loss: 4.6011 - accuracy: 0.0196
191/191 [==============================] - 1s 5ms/step - loss: 4.6034 - accuracy: 0.0028
Test Accuracy (Batch 6): 0.28%
Epoch 1/10
3/3 [==============================] - 0s 21ms/step - loss: 4.6442 - accuracy: 0.0098
Epoch 2/10
3/3 [==============================] - 0s 14ms/step - loss: 4.6434 - accuracy: 0.0098
Epoch 3/10
3/3 [==============================] - 0s 16ms/step - loss: 4.6383 - accuracy: 0.0098
Epoch 4/10
3/3 [==============================] - 0s 14ms/step - loss: 4.6355 - accuracy: 0.0098
Epoch 5/10
3/3 [==============================] - 0s 13ms/step - loss: 4.6314 - accuracy: 0.0065
Epoch 6/10
3/3 [==============================] - 0s 13ms/step - loss: 4.6286 - accuracy: 0.0131
Epoch 7/10
3/3 [==============================] - 0s 13ms/step - loss: 4.6256 - accuracy: 0.0163
Epoch 8/10
3/3 [==============================] - 0s 14ms/step - loss: 4.6225 - accuracy: 0.0098
Epoch 9/10
3/3 [==============================] - 0s 14ms/step - loss: 4.6216 - accuracy: 0.0065
Epoch 10/10
3/3 [==============================] - 0s 12ms/step - loss: 4.6185 - accuracy: 0.0163
191/191 [==============================] - 1s 4ms/step - loss: 4.6090 - accuracy: 0.0718
Test Accuracy (Batch 7): 7.18%
Epoch 1/10
3/3 [==============================] - 0s 13ms/step - loss: 4.6455 - accuracy: 0.0065
Epoch 2/10
3/3 [==============================] - 0s 14ms/step - loss: 4.6419 - accuracy: 0.0033
Epoch 3/10
3/3 [==============================] - 0s 14ms/step - loss: 4.6411 - accuracy: 0.0065
Epoch 4/10
3/3 [==============================] - 0s 13ms/step - loss: 4.6372 - accuracy: 0.0065
Epoch 5/10
3/3 [==============================] - 0s 14ms/step - loss: 4.6335 - accuracy: 0.0065
Epoch 6/10
3/3 [==============================] - 0s 14ms/step - loss: 4.6320 - accuracy: 0.0033
Epoch 7/10
3/3 [==============================] - 0s 15ms/step - loss: 4.6288 - accuracy: 0.0065
Epoch 8/10
3/3 [==============================] - 0s 16ms/step - loss: 4.6275 - accuracy: 0.0098
Epoch 9/10
3/3 [==============================] - 0s 12ms/step - loss: 4.6259 - accuracy: 0.0033
Epoch 10/10
3/3 [==============================] - 0s 12ms/step - loss: 4.6235 - accuracy: 0.0163
191/191 [==============================] - 1s 4ms/step - loss: 4.6210 - accuracy: 0.0044
Test Accuracy (Batch 8): 0.44%
Epoch 1/10
3/3 [==============================] - 0s 17ms/step - loss: 4.6297 - accuracy: 0.0065
Epoch 2/10
3/3 [==============================] - 0s 16ms/step - loss: 4.6292 - accuracy: 0.0033
Epoch 3/10
3/3 [==============================] - 0s 15ms/step - loss: 4.6286 - accuracy: 0.0033
Epoch 4/10
3/3 [==============================] - 0s 14ms/step - loss: 4.6277 - accuracy: 0.0033
Epoch 5/10
3/3 [==============================] - 0s 14ms/step - loss: 4.6278 - accuracy: 0.0065
Epoch 6/10
3/3 [==============================] - 0s 19ms/step - loss: 4.6270 - accuracy: 0.0065
Epoch 7/10
3/3 [==============================] - 0s 16ms/step - loss: 4.6258 - accuracy: 0.0065
Epoch 8/10
3/3 [==============================] - 0s 15ms/step - loss: 4.6247 - accuracy: 0.0131
Epoch 9/10
3/3 [==============================] - 0s 15ms/step - loss: 4.6237 - accuracy: 0.0196
Epoch 10/10
3/3 [==============================] - 0s 12ms/step - loss: 4.6236 - accuracy: 0.0131
191/191 [==============================] - 1s 5ms/step - loss: 4.6213 - accuracy: 0.0039
Test Accuracy (Batch 9): 0.39%
Epoch 1/10
3/3 [==============================] - 0s 15ms/step - loss: 4.6315 - accuracy: 0.0000e+00
Epoch 2/10
3/3 [==============================] - 0s 13ms/step - loss: 4.6312 - accuracy: 0.0000e+00
Epoch 3/10
3/3 [==============================] - 0s 13ms/step - loss: 4.6312 - accuracy: 0.0000e+00
Epoch 4/10
3/3 [==============================] - 0s 13ms/step - loss: 4.6309 - accuracy: 0.0000e+00
Epoch 5/10
3/3 [==============================] - 0s 12ms/step - loss: 4.6297 - accuracy: 0.0000e+00
Epoch 6/10
3/3 [==============================] - 0s 12ms/step - loss: 4.6286 - accuracy: 0.0000e+00
Epoch 7/10
3/3 [==============================] - 0s 15ms/step - loss: 4.6269 - accuracy: 0.0065
Epoch 8/10
3/3 [==============================] - 0s 15ms/step - loss: 4.6265 - accuracy: 0.0098
Epoch 9/10
3/3 [==============================] - 0s 15ms/step - loss: 4.6251 - accuracy: 0.0000e+00
Epoch 10/10
3/3 [==============================] - 0s 14ms/step - loss: 4.6240 - accuracy: 0.0098
191/191 [==============================] - 1s 4ms/step - loss: 4.6283 - accuracy: 0.0066
Test Accuracy (Batch 10): 0.66%
Batch-1: 0.90%
Batch-2: 0.07%
Batch-3: 0.15%
Batch-4: 0.44%
Batch-5: 1.00%
Batch-6: 0.28%
Batch-7: 7.18%
Batch-8: 0.44%
Batch-9: 0.39%
Batch-10: 0.66%

#### Batches 6

In [ ]:
import tensorflow as tf
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras import layers
# x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=42)
# Normalize the input data
x_train = X_train_resized.astype('float32') / 255.0
x_test = X_test_resized.astype('float32') / 255.0

# Convert the labels to one-hot encoding
num_classes = 102
# y_train = tf.keras.utils.to_categorical(y_train, num_classes)
# y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training set into 20 batches
num_batches = 6
x_train_batches = np.array_split(x_train, num_batches)
y_train_batches = np.array_split(y_train, num_batches)

# Initialize the list to store test accuracies
accuracies = []

# Define the model architecture
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(28, 28, 3)),
    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu'),
    layers.Dropout(0.25),
    Dense(num_classes, activation='softmax')
])


model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch
epochs = 10
for i in range(num_batches):
    x_train_batch = x_train_batches[i]
    y_train_batch = y_train_batches[i]
    model.fit(x_train_batch, y_train_batch, batch_size=128, epochs=epochs, verbose=1)

    # Evaluate the model on the test set
    test_loss, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy (Batch {}): {:.2f}%".format(i+1, test_accuracy*100))
    accuracies.append(test_accuracy)

# Print the batch accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Batch-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
4/4 [==============================] - 6s 161ms/step - loss: 4.6252 - accuracy: 0.0000e+00
Epoch 2/10
4/4 [==============================] - 0s 15ms/step - loss: 4.6167 - accuracy: 0.0137
Epoch 3/10
4/4 [==============================] - 0s 16ms/step - loss: 4.5953 - accuracy: 0.0196
Epoch 4/10
4/4 [==============================] - 0s 14ms/step - loss: 4.5759 - accuracy: 0.0216
Epoch 5/10
4/4 [==============================] - 0s 14ms/step - loss: 4.5652 - accuracy: 0.0196
Epoch 6/10
4/4 [==============================] - 0s 13ms/step - loss: 4.5506 - accuracy: 0.0196
Epoch 7/10
4/4 [==============================] - 0s 13ms/step - loss: 4.5579 - accuracy: 0.0118
Epoch 8/10
4/4 [==============================] - 0s 14ms/step - loss: 4.5646 - accuracy: 0.0137
Epoch 9/10
4/4 [==============================] - 0s 14ms/step - loss: 4.5539 - accuracy: 0.0216
Epoch 10/10
4/4 [==============================] - 0s 13ms/step - loss: 4.5476 - accuracy: 0.0216
191/191 [==============================] - 1s 5ms/step - loss: 4.5938 - accuracy: 0.0049
Test Accuracy (Batch 1): 0.49%
Epoch 1/10
4/4 [==============================] - 0s 19ms/step - loss: 4.7118 - accuracy: 0.0078
Epoch 2/10
4/4 [==============================] - 0s 19ms/step - loss: 4.6496 - accuracy: 0.0059
Epoch 3/10
4/4 [==============================] - 0s 20ms/step - loss: 4.6278 - accuracy: 0.0137
Epoch 4/10
4/4 [==============================] - 0s 16ms/step - loss: 4.6250 - accuracy: 0.0137
Epoch 5/10
4/4 [==============================] - 0s 17ms/step - loss: 4.6233 - accuracy: 0.0196
Epoch 6/10
4/4 [==============================] - 0s 16ms/step - loss: 4.6219 - accuracy: 0.0196
Epoch 7/10
4/4 [==============================] - 0s 15ms/step - loss: 4.6204 - accuracy: 0.0196
Epoch 8/10
4/4 [==============================] - 0s 15ms/step - loss: 4.6189 - accuracy: 0.0196
Epoch 9/10
4/4 [==============================] - 0s 13ms/step - loss: 4.6169 - accuracy: 0.0235
Epoch 10/10
4/4 [==============================] - 0s 13ms/step - loss: 4.6135 - accuracy: 0.0255
191/191 [==============================] - 1s 4ms/step - loss: 4.6282 - accuracy: 0.0153
Test Accuracy (Batch 2): 1.53%
Epoch 1/10
4/4 [==============================] - 0s 14ms/step - loss: 4.6323 - accuracy: 0.0078
Epoch 2/10
4/4 [==============================] - 0s 14ms/step - loss: 4.6310 - accuracy: 0.0059
Epoch 3/10
4/4 [==============================] - 0s 14ms/step - loss: 4.6288 - accuracy: 0.0059
Epoch 4/10
4/4 [==============================] - 0s 13ms/step - loss: 4.6252 - accuracy: 0.0078
Epoch 5/10
4/4 [==============================] - 0s 15ms/step - loss: 4.6201 - accuracy: 0.0078
Epoch 6/10
4/4 [==============================] - 0s 14ms/step - loss: 4.6081 - accuracy: 0.0118
Epoch 7/10
4/4 [==============================] - 0s 13ms/step - loss: 4.5940 - accuracy: 0.0118
Epoch 8/10
4/4 [==============================] - 0s 14ms/step - loss: 4.5697 - accuracy: 0.0176
Epoch 9/10
4/4 [==============================] - 0s 16ms/step - loss: 4.5509 - accuracy: 0.0137
Epoch 10/10
4/4 [==============================] - 0s 16ms/step - loss: 4.5528 - accuracy: 0.0137
191/191 [==============================] - 1s 6ms/step - loss: 4.5877 - accuracy: 0.0100
Test Accuracy (Batch 3): 1.00%
Epoch 1/10
4/4 [==============================] - 0s 24ms/step - loss: 4.7731 - accuracy: 0.0059
Epoch 2/10
4/4 [==============================] - 0s 25ms/step - loss: 4.6917 - accuracy: 0.0078
Epoch 3/10
4/4 [==============================] - 0s 22ms/step - loss: 4.6432 - accuracy: 0.0078
Epoch 4/10
4/4 [==============================] - 0s 21ms/step - loss: 4.6252 - accuracy: 0.0078
Epoch 5/10
4/4 [==============================] - 0s 22ms/step - loss: 4.6172 - accuracy: 0.0078
Epoch 6/10
4/4 [==============================] - 0s 24ms/step - loss: 4.6118 - accuracy: 0.0157
Epoch 7/10
4/4 [==============================] - 0s 29ms/step - loss: 4.6024 - accuracy: 0.0216
Epoch 8/10
4/4 [==============================] - 0s 28ms/step - loss: 4.5857 - accuracy: 0.0157
Epoch 9/10
4/4 [==============================] - 0s 24ms/step - loss: 4.5726 - accuracy: 0.0137
Epoch 10/10
4/4 [==============================] - 0s 16ms/step - loss: 4.5629 - accuracy: 0.0216
191/191 [==============================] - 1s 4ms/step - loss: 4.6782 - accuracy: 0.0085
Test Accuracy (Batch 4): 0.85%
Epoch 1/10
4/4 [==============================] - 0s 23ms/step - loss: 4.7385 - accuracy: 0.0059
Epoch 2/10
4/4 [==============================] - 0s 16ms/step - loss: 4.6743 - accuracy: 0.0157
Epoch 3/10
4/4 [==============================] - 0s 16ms/step - loss: 4.6356 - accuracy: 0.0196
Epoch 4/10
4/4 [==============================] - 0s 15ms/step - loss: 4.6156 - accuracy: 0.0196
Epoch 5/10
4/4 [==============================] - 0s 14ms/step - loss: 4.6047 - accuracy: 0.0137
Epoch 6/10
4/4 [==============================] - 0s 15ms/step - loss: 4.5976 - accuracy: 0.0157
Epoch 7/10
4/4 [==============================] - 0s 13ms/step - loss: 4.5841 - accuracy: 0.0196
Epoch 8/10
4/4 [==============================] - 0s 14ms/step - loss: 4.5727 - accuracy: 0.0137
Epoch 9/10
4/4 [==============================] - 0s 14ms/step - loss: 4.5596 - accuracy: 0.0157
Epoch 10/10
4/4 [==============================] - 0s 13ms/step - loss: 4.5518 - accuracy: 0.0216
191/191 [==============================] - 1s 4ms/step - loss: 4.7975 - accuracy: 0.0056
Test Accuracy (Batch 5): 0.56%
Epoch 1/10
4/4 [==============================] - 0s 16ms/step - loss: 4.7360 - accuracy: 0.0098
Epoch 2/10
4/4 [==============================] - 0s 16ms/step - loss: 4.6958 - accuracy: 0.0098
Epoch 3/10
4/4 [==============================] - 0s 14ms/step - loss: 4.6570 - accuracy: 0.0118
Epoch 4/10
4/4 [==============================] - 0s 14ms/step - loss: 4.6324 - accuracy: 0.0137
Epoch 5/10
4/4 [==============================] - 0s 14ms/step - loss: 4.6257 - accuracy: 0.0078
Epoch 6/10
4/4 [==============================] - 0s 13ms/step - loss: 4.6210 - accuracy: 0.0078
Epoch 7/10
4/4 [==============================] - 0s 15ms/step - loss: 4.6174 - accuracy: 0.0078
Epoch 8/10
4/4 [==============================] - 0s 14ms/step - loss: 4.6164 - accuracy: 0.0176
Epoch 9/10
4/4 [==============================] - 0s 17ms/step - loss: 4.6121 - accuracy: 0.0137
Epoch 10/10
4/4 [==============================] - 0s 13ms/step - loss: 4.6100 - accuracy: 0.0137
191/191 [==============================] - 1s 5ms/step - loss: 4.6573 - accuracy: 0.0061
Test Accuracy (Batch 6): 0.61%
Batch-1: 0.49%
Batch-2: 1.53%
Batch-3: 1.00%
Batch-4: 0.85%
Batch-5: 0.56%
Batch-6: 0.61%

#### Batches 5

In [ ]:
import tensorflow as tf
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras import layers
# x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=42)
# Normalize the input data
x_train = X_train_resized.astype('float32') / 255.0
x_test = X_test_resized.astype('float32') / 255.0

# Convert the labels to one-hot encoding
num_classes = 102
# y_train = tf.keras.utils.to_categorical(y_train, num_classes)
# y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training set into 20 batches
num_batches = 5
x_train_batches = np.array_split(x_train, num_batches)
y_train_batches = np.array_split(y_train, num_batches)

# Initialize the list to store test accuracies
accuracies = []

# Define the model architecture
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(28, 28, 3)),
    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu'),
    layers.Dropout(0.25),
    Dense(num_classes, activation='softmax')
])


model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch
epochs = 10
for i in range(num_batches):
    x_train_batch = x_train_batches[i]
    y_train_batch = y_train_batches[i]
    model.fit(x_train_batch, y_train_batch, batch_size=128, epochs=epochs, verbose=1)

    # Evaluate the model on the test set
    test_loss, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy (Batch {}): {:.2f}%".format(i+1, test_accuracy*100))
    accuracies.append(test_accuracy)

# Print the batch accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Batch-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
5/5 [==============================] - 5s 119ms/step - loss: 4.6260 - accuracy: 0.0098
Epoch 2/10
5/5 [==============================] - 0s 12ms/step - loss: 4.6178 - accuracy: 0.0098
Epoch 3/10
5/5 [==============================] - 0s 15ms/step - loss: 4.6015 - accuracy: 0.0278
Epoch 4/10
5/5 [==============================] - 0s 12ms/step - loss: 4.5921 - accuracy: 0.0131
Epoch 5/10
5/5 [==============================] - 0s 12ms/step - loss: 4.5876 - accuracy: 0.0180
Epoch 6/10
5/5 [==============================] - 0s 12ms/step - loss: 4.5880 - accuracy: 0.0229
Epoch 7/10
5/5 [==============================] - 0s 12ms/step - loss: 4.5754 - accuracy: 0.0196
Epoch 8/10
5/5 [==============================] - 0s 12ms/step - loss: 4.5818 - accuracy: 0.0147
Epoch 9/10
5/5 [==============================] - 0s 12ms/step - loss: 4.5802 - accuracy: 0.0131
Epoch 10/10
5/5 [==============================] - 0s 12ms/step - loss: 4.5741 - accuracy: 0.0147
191/191 [==============================] - 1s 4ms/step - loss: 4.5573 - accuracy: 0.1266
Test Accuracy (Batch 1): 12.66%
Epoch 1/10
5/5 [==============================] - 0s 18ms/step - loss: 4.6736 - accuracy: 0.0098
Epoch 2/10
5/5 [==============================] - 0s 19ms/step - loss: 4.6301 - accuracy: 0.0049
Epoch 3/10
5/5 [==============================] - 0s 16ms/step - loss: 4.6254 - accuracy: 0.0098
Epoch 4/10
5/5 [==============================] - 0s 15ms/step - loss: 4.6239 - accuracy: 0.0147
Epoch 5/10
5/5 [==============================] - 0s 16ms/step - loss: 4.6230 - accuracy: 0.0147
Epoch 6/10
5/5 [==============================] - 0s 15ms/step - loss: 4.6217 - accuracy: 0.0196
Epoch 7/10
5/5 [==============================] - 0s 13ms/step - loss: 4.6203 - accuracy: 0.0196
Epoch 8/10
5/5 [==============================] - 0s 12ms/step - loss: 4.6184 - accuracy: 0.0131
Epoch 9/10
5/5 [==============================] - 0s 13ms/step - loss: 4.6139 - accuracy: 0.0212
Epoch 10/10
5/5 [==============================] - 0s 13ms/step - loss: 4.6020 - accuracy: 0.0196
191/191 [==============================] - 1s 4ms/step - loss: 4.6225 - accuracy: 0.0153
Test Accuracy (Batch 2): 1.53%
Epoch 1/10
5/5 [==============================] - 0s 18ms/step - loss: 4.6619 - accuracy: 0.0082
Epoch 2/10
5/5 [==============================] - 0s 17ms/step - loss: 4.6347 - accuracy: 0.0049
Epoch 3/10
5/5 [==============================] - 0s 18ms/step - loss: 4.6257 - accuracy: 0.0082
Epoch 4/10
5/5 [==============================] - 0s 20ms/step - loss: 4.6212 - accuracy: 0.0114
Epoch 5/10
5/5 [==============================] - 0s 17ms/step - loss: 4.6154 - accuracy: 0.0098
Epoch 6/10
5/5 [==============================] - 0s 16ms/step - loss: 4.6044 - accuracy: 0.0065
Epoch 7/10
5/5 [==============================] - 0s 17ms/step - loss: 4.5824 - accuracy: 0.0196
Epoch 8/10
5/5 [==============================] - 0s 19ms/step - loss: 4.5759 - accuracy: 0.0147
Epoch 9/10
5/5 [==============================] - 0s 18ms/step - loss: 4.5753 - accuracy: 0.0180
Epoch 10/10
5/5 [==============================] - 0s 20ms/step - loss: 4.5694 - accuracy: 0.0245
191/191 [==============================] - 1s 5ms/step - loss: 4.6514 - accuracy: 0.0085
Test Accuracy (Batch 3): 0.85%
Epoch 1/10
5/5 [==============================] - 0s 17ms/step - loss: 4.6998 - accuracy: 0.0033
Epoch 2/10
5/5 [==============================] - 0s 16ms/step - loss: 4.6496 - accuracy: 0.0098
Epoch 3/10
5/5 [==============================] - 0s 16ms/step - loss: 4.6310 - accuracy: 0.0082
Epoch 4/10
5/5 [==============================] - 0s 17ms/step - loss: 4.6277 - accuracy: 0.0065
Epoch 5/10
5/5 [==============================] - 0s 14ms/step - loss: 4.6249 - accuracy: 0.0082
Epoch 6/10
5/5 [==============================] - 0s 15ms/step - loss: 4.6237 - accuracy: 0.0147
Epoch 7/10
5/5 [==============================] - 0s 13ms/step - loss: 4.6207 - accuracy: 0.0098
Epoch 8/10
5/5 [==============================] - 0s 14ms/step - loss: 4.6161 - accuracy: 0.0114
Epoch 9/10
5/5 [==============================] - 0s 12ms/step - loss: 4.6103 - accuracy: 0.0147
Epoch 10/10
5/5 [==============================] - 0s 12ms/step - loss: 4.6036 - accuracy: 0.0131
191/191 [==============================] - 1s 4ms/step - loss: 4.6565 - accuracy: 0.0061
Test Accuracy (Batch 4): 0.61%
Epoch 1/10
5/5 [==============================] - 0s 16ms/step - loss: 4.6390 - accuracy: 0.0082
Epoch 2/10
5/5 [==============================] - 0s 17ms/step - loss: 4.6376 - accuracy: 0.0147
Epoch 3/10
5/5 [==============================] - 0s 22ms/step - loss: 4.6313 - accuracy: 0.0147
Epoch 4/10
5/5 [==============================] - 0s 16ms/step - loss: 4.6263 - accuracy: 0.0147
Epoch 5/10
5/5 [==============================] - 0s 15ms/step - loss: 4.6247 - accuracy: 0.0163
Epoch 6/10
5/5 [==============================] - 0s 15ms/step - loss: 4.6197 - accuracy: 0.0131
Epoch 7/10
5/5 [==============================] - 0s 13ms/step - loss: 4.6185 - accuracy: 0.0163
Epoch 8/10
5/5 [==============================] - 0s 15ms/step - loss: 4.6123 - accuracy: 0.0180
Epoch 9/10
5/5 [==============================] - 0s 13ms/step - loss: 4.6105 - accuracy: 0.0163
Epoch 10/10
5/5 [==============================] - 0s 15ms/step - loss: 4.6071 - accuracy: 0.0163
191/191 [==============================] - 1s 4ms/step - loss: 4.6732 - accuracy: 0.0061
Test Accuracy (Batch 5): 0.61%
Batch-1: 12.66%
Batch-2: 1.53%
Batch-3: 0.85%
Batch-4: 0.61%
Batch-5: 0.61%

#### Batches 4

In [ ]:
import tensorflow as tf
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras import layers
# x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=42)
# Normalize the input data
x_train = X_train_resized.astype('float32') / 255.0
x_test = X_test_resized.astype('float32') / 255.0

# Convert the labels to one-hot encoding
num_classes = 102
# y_train = tf.keras.utils.to_categorical(y_train, num_classes)
# y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training set into 20 batches
num_batches = 4
x_train_batches = np.array_split(x_train, num_batches)
y_train_batches = np.array_split(y_train, num_batches)

# Initialize the list to store test accuracies
accuracies = []

# Define the model architecture
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(28, 28, 3)),
    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu'),
    layers.Dropout(0.25),
    Dense(num_classes, activation='softmax')
])


model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch
epochs = 10
for i in range(num_batches):
    x_train_batch = x_train_batches[i]
    y_train_batch = y_train_batches[i]
    model.fit(x_train_batch, y_train_batch, batch_size=128, epochs=epochs, verbose=1)

    # Evaluate the model on the test set
    test_loss, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy (Batch {}): {:.2f}%".format(i+1, test_accuracy*100))
    accuracies.append(test_accuracy)

# Print the batch accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Batch-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
6/6 [==============================] - 10s 98ms/step - loss: 4.6258 - accuracy: 0.0039
Epoch 2/10
6/6 [==============================] - 0s 12ms/step - loss: 4.6225 - accuracy: 0.0131
Epoch 3/10
6/6 [==============================] - 0s 14ms/step - loss: 4.6129 - accuracy: 0.0118
Epoch 4/10
6/6 [==============================] - 0s 13ms/step - loss: 4.6063 - accuracy: 0.0170
Epoch 5/10
6/6 [==============================] - 0s 14ms/step - loss: 4.5939 - accuracy: 0.0183
Epoch 6/10
6/6 [==============================] - 0s 14ms/step - loss: 4.5945 - accuracy: 0.0170
Epoch 7/10
6/6 [==============================] - 0s 13ms/step - loss: 4.5930 - accuracy: 0.0209
Epoch 8/10
6/6 [==============================] - 0s 13ms/step - loss: 4.5932 - accuracy: 0.0157
Epoch 9/10
6/6 [==============================] - 0s 13ms/step - loss: 4.5897 - accuracy: 0.0196
Epoch 10/10
6/6 [==============================] - 0s 13ms/step - loss: 4.5926 - accuracy: 0.0209
191/191 [==============================] - 1s 5ms/step - loss: 4.6282 - accuracy: 6.5746e-04
Test Accuracy (Batch 1): 0.07%
Epoch 1/10
6/6 [==============================] - 0s 13ms/step - loss: 4.6577 - accuracy: 0.0039
Epoch 2/10
6/6 [==============================] - 0s 15ms/step - loss: 4.6290 - accuracy: 0.0078
Epoch 3/10
6/6 [==============================] - 0s 13ms/step - loss: 4.6255 - accuracy: 0.0065
Epoch 4/10
6/6 [==============================] - 0s 14ms/step - loss: 4.6244 - accuracy: 0.0092
Epoch 5/10
6/6 [==============================] - 0s 12ms/step - loss: 4.6234 - accuracy: 0.0105
Epoch 6/10
6/6 [==============================] - 0s 13ms/step - loss: 4.6225 - accuracy: 0.0183
Epoch 7/10
6/6 [==============================] - 0s 13ms/step - loss: 4.6214 - accuracy: 0.0105
Epoch 8/10
6/6 [==============================] - 0s 14ms/step - loss: 4.6206 - accuracy: 0.0144
Epoch 9/10
6/6 [==============================] - 0s 13ms/step - loss: 4.6188 - accuracy: 0.0144
Epoch 10/10
6/6 [==============================] - 0s 13ms/step - loss: 4.6154 - accuracy: 0.0131
191/191 [==============================] - 1s 4ms/step - loss: 4.6054 - accuracy: 0.0666
Test Accuracy (Batch 2): 6.66%
Epoch 1/10
6/6 [==============================] - 0s 13ms/step - loss: 4.6416 - accuracy: 0.0026
Epoch 2/10
6/6 [==============================] - 0s 13ms/step - loss: 4.6344 - accuracy: 0.0131
Epoch 3/10
6/6 [==============================] - 0s 13ms/step - loss: 4.6274 - accuracy: 0.0092
Epoch 4/10
6/6 [==============================] - 0s 15ms/step - loss: 4.6226 - accuracy: 0.0118
Epoch 5/10
6/6 [==============================] - 0s 13ms/step - loss: 4.6151 - accuracy: 0.0157
Epoch 6/10
6/6 [==============================] - 0s 14ms/step - loss: 4.6045 - accuracy: 0.0118
Epoch 7/10
6/6 [==============================] - 0s 13ms/step - loss: 4.5948 - accuracy: 0.0105
Epoch 8/10
6/6 [==============================] - 0s 12ms/step - loss: 4.5943 - accuracy: 0.0183
Epoch 9/10
6/6 [==============================] - 0s 17ms/step - loss: 4.5892 - accuracy: 0.0144
Epoch 10/10
6/6 [==============================] - 0s 12ms/step - loss: 4.5899 - accuracy: 0.0170
191/191 [==============================] - 1s 4ms/step - loss: 4.6645 - accuracy: 0.0092
Test Accuracy (Batch 3): 0.92%
Epoch 1/10
6/6 [==============================] - 0s 15ms/step - loss: 4.6751 - accuracy: 0.0065
Epoch 2/10
6/6 [==============================] - 0s 14ms/step - loss: 4.6474 - accuracy: 0.0078
Epoch 3/10
6/6 [==============================] - 0s 12ms/step - loss: 4.6294 - accuracy: 0.0131
Epoch 4/10
6/6 [==============================] - 0s 14ms/step - loss: 4.6255 - accuracy: 0.0078
Epoch 5/10
6/6 [==============================] - 0s 14ms/step - loss: 4.6234 - accuracy: 0.0105
Epoch 6/10
6/6 [==============================] - 0s 14ms/step - loss: 4.6199 - accuracy: 0.0144
Epoch 7/10
6/6 [==============================] - 0s 15ms/step - loss: 4.6174 - accuracy: 0.0131
Epoch 8/10
6/6 [==============================] - 0s 13ms/step - loss: 4.6106 - accuracy: 0.0209
Epoch 9/10
6/6 [==============================] - 0s 12ms/step - loss: 4.6061 - accuracy: 0.0118
Epoch 10/10
6/6 [==============================] - 0s 13ms/step - loss: 4.5988 - accuracy: 0.0157
191/191 [==============================] - 1s 4ms/step - loss: 4.7251 - accuracy: 0.0061
Test Accuracy (Batch 4): 0.61%
Batch-1: 0.07%
Batch-2: 6.66%
Batch-3: 0.92%
Batch-4: 0.61%

#### Batches 2

In [ ]:
import tensorflow as tf
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras import layers
# x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=42)
# Normalize the input data
x_train = X_train_resized.astype('float32') / 255.0
x_test = X_test_resized.astype('float32') / 255.0

# Convert the labels to one-hot encoding
num_classes = 102
# y_train = tf.keras.utils.to_categorical(y_train, num_classes)
# y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training set into 20 batches
num_batches = 2
x_train_batches = np.array_split(x_train, num_batches)
y_train_batches = np.array_split(y_train, num_batches)

# Initialize the list to store test accuracies
accuracies = []

# Define the model architecture
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(28, 28, 3)),
    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu'),
    layers.Dropout(0.25),
    Dense(num_classes, activation='softmax')
])


model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch
epochs = 10
for i in range(num_batches):
    x_train_batch = x_train_batches[i]
    y_train_batch = y_train_batches[i]
    model.fit(x_train_batch, y_train_batch, batch_size=128, epochs=epochs, verbose=1)

    # Evaluate the model on the test set
    test_loss, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy (Batch {}): {:.2f}%".format(i+1, test_accuracy*100))
    accuracies.append(test_accuracy)

# Print the batch accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Batch-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
12/12 [==============================] - 5s 59ms/step - loss: 4.6261 - accuracy: 0.0098
Epoch 2/10
12/12 [==============================] - 0s 18ms/step - loss: 4.6237 - accuracy: 0.0137
Epoch 3/10
12/12 [==============================] - 0s 14ms/step - loss: 4.6208 - accuracy: 0.0111
Epoch 4/10
12/12 [==============================] - 0s 14ms/step - loss: 4.6189 - accuracy: 0.0137
Epoch 5/10
12/12 [==============================] - 0s 20ms/step - loss: 4.6154 - accuracy: 0.0131
Epoch 6/10
12/12 [==============================] - 0s 15ms/step - loss: 4.6124 - accuracy: 0.0137
Epoch 7/10
12/12 [==============================] - 0s 15ms/step - loss: 4.6140 - accuracy: 0.0137
Epoch 8/10
12/12 [==============================] - 0s 16ms/step - loss: 4.6114 - accuracy: 0.0085
Epoch 9/10
12/12 [==============================] - 0s 16ms/step - loss: 4.6110 - accuracy: 0.0098
Epoch 10/10
12/12 [==============================] - 0s 16ms/step - loss: 4.6123 - accuracy: 0.0085
191/191 [==============================] - 1s 5ms/step - loss: 4.6002 - accuracy: 0.0666
Test Accuracy (Batch 1): 6.66%
Epoch 1/10
12/12 [==============================] - 0s 17ms/step - loss: 4.6469 - accuracy: 0.0078
Epoch 2/10
12/12 [==============================] - 0s 15ms/step - loss: 4.6289 - accuracy: 0.0072
Epoch 3/10
12/12 [==============================] - 0s 13ms/step - loss: 4.6272 - accuracy: 0.0065
Epoch 4/10
12/12 [==============================] - 0s 13ms/step - loss: 4.6260 - accuracy: 0.0072
Epoch 5/10
12/12 [==============================] - 0s 13ms/step - loss: 4.6254 - accuracy: 0.0085
Epoch 6/10
12/12 [==============================] - 0s 12ms/step - loss: 4.6249 - accuracy: 0.0105
Epoch 7/10
12/12 [==============================] - 0s 12ms/step - loss: 4.6244 - accuracy: 0.0111
Epoch 8/10
12/12 [==============================] - 0s 12ms/step - loss: 4.6237 - accuracy: 0.0131
Epoch 9/10
12/12 [==============================] - 0s 13ms/step - loss: 4.6232 - accuracy: 0.0144
Epoch 10/10
12/12 [==============================] - 0s 13ms/step - loss: 4.6226 - accuracy: 0.0170
191/191 [==============================] - 1s 4ms/step - loss: 4.6313 - accuracy: 0.0056
Test Accuracy (Batch 2): 0.56%
Batch-1: 6.66%
Batch-2: 0.56%

### STL-10

In [ ]:
import tensorflow_datasets as tfds

# Load the STL-10 dataset
dataset_name = "stl10"
train_dataset, test_dataset = tfds.load(name=dataset_name, split=["train", "test"], as_supervised=True)

# Iterate through the datasets to get features and labels
X_train = []
y_train = []
for image, label in tfds.as_numpy(train_dataset):
    X_train.append(image)
    y_train.append(label)

X_test = []
y_test = []
for image, label in tfds.as_numpy(test_dataset):
    X_test.append(image)
    y_test.append(label)

# Convert lists to numpy arrays
import numpy as np
X_train = np.array(X_train)
y_train = np.array(y_train)
X_test = np.array(X_test)
y_test = np.array(y_test)

# Print the shape of the arrays
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

X_train shape: (5000, 96, 96, 3)
y_train shape: (5000,)
X_test shape: (8000, 96, 96, 3)
y_test shape: (8000,)

In [ ]:
import tensorflow as tf
y_train = tf.keras.utils.to_categorical(y_train, num_classes=10)
y_test = tf.keras.utils.to_categorical(y_test, num_classes=10)

#### Batches 20

In [ ]:
import tensorflow as tf
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras import layers
# x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=42)
# Normalize the input data
x_train = X_train.astype('float32') / 255.0
x_test = X_test.astype('float32') / 255.0

# Convert the labels to one-hot encoding
num_classes = 10
# y_train = tf.keras.utils.to_categorical(y_train, num_classes)
# y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training set into 20 batches
num_batches = 20
x_train_batches = np.array_split(x_train, num_batches)
y_train_batches = np.array_split(y_train, num_batches)

# Initialize the list to store test accuracies
accuracies = []

# Define the model architecture
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(96, 96, 3)),
    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu'),
    layers.Dropout(0.25),
    Dense(num_classes, activation='softmax')
])


model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch
epochs = 10
for i in range(num_batches):
    x_train_batch = x_train_batches[i]
    y_train_batch = y_train_batches[i]
    model.fit(x_train_batch, y_train_batch, batch_size=128, epochs=epochs, verbose=1)

    # Evaluate the model on the test set
    test_loss, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy (Batch {}): {:.2f}%".format(i+1, test_accuracy*100))
    accuracies.append(test_accuracy)

# Print the batch accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Batch-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
2/2 [==============================] - 16s 2s/step - loss: 3.5023 - accuracy: 0.1440
Epoch 2/10
2/2 [==============================] - 0s 91ms/step - loss: 3.3967 - accuracy: 0.1400
Epoch 3/10
2/2 [==============================] - 0s 94ms/step - loss: 2.4679 - accuracy: 0.1560
Epoch 4/10
2/2 [==============================] - 0s 91ms/step - loss: 2.3145 - accuracy: 0.1440
Epoch 5/10
2/2 [==============================] - 0s 90ms/step - loss: 2.2973 - accuracy: 0.1400
Epoch 6/10
2/2 [==============================] - 0s 91ms/step - loss: 2.2814 - accuracy: 0.2080
Epoch 7/10
2/2 [==============================] - 0s 94ms/step - loss: 2.2532 - accuracy: 0.2440
Epoch 8/10
2/2 [==============================] - 0s 92ms/step - loss: 2.2104 - accuracy: 0.2040
Epoch 9/10
2/2 [==============================] - 0s 91ms/step - loss: 2.1505 - accuracy: 0.2520
Epoch 10/10
2/2 [==============================] - 0s 89ms/step - loss: 2.0432 - accuracy: 0.3160
250/250 [==============================] - 2s 6ms/step - loss: 2.1808 - accuracy: 0.2058
Test Accuracy (Batch 1): 20.58%
Epoch 1/10
2/2 [==============================] - 0s 96ms/step - loss: 2.1696 - accuracy: 0.2360
Epoch 2/10
2/2 [==============================] - 0s 97ms/step - loss: 2.0220 - accuracy: 0.3040
Epoch 3/10
2/2 [==============================] - 0s 95ms/step - loss: 1.9624 - accuracy: 0.2800
Epoch 4/10
2/2 [==============================] - 0s 93ms/step - loss: 1.8500 - accuracy: 0.3280
Epoch 5/10
2/2 [==============================] - 0s 94ms/step - loss: 1.7512 - accuracy: 0.4000
Epoch 6/10
2/2 [==============================] - 0s 93ms/step - loss: 1.6760 - accuracy: 0.3920
Epoch 7/10
2/2 [==============================] - 0s 96ms/step - loss: 1.5443 - accuracy: 0.4080
Epoch 8/10
2/2 [==============================] - 0s 98ms/step - loss: 1.4316 - accuracy: 0.5200
Epoch 9/10
2/2 [==============================] - 0s 97ms/step - loss: 1.2577 - accuracy: 0.5520
Epoch 10/10
2/2 [==============================] - 0s 97ms/step - loss: 1.1582 - accuracy: 0.5960
250/250 [==============================] - 2s 7ms/step - loss: 1.9359 - accuracy: 0.3296
Test Accuracy (Batch 2): 32.96%
Epoch 1/10
2/2 [==============================] - 0s 91ms/step - loss: 2.0036 - accuracy: 0.2960
Epoch 2/10
2/2 [==============================] - 0s 89ms/step - loss: 1.8379 - accuracy: 0.3360
Epoch 3/10
2/2 [==============================] - 0s 91ms/step - loss: 1.6598 - accuracy: 0.3880
Epoch 4/10
2/2 [==============================] - 0s 92ms/step - loss: 1.5802 - accuracy: 0.4160
Epoch 5/10
2/2 [==============================] - 0s 93ms/step - loss: 1.5419 - accuracy: 0.4200
Epoch 6/10
2/2 [==============================] - 0s 92ms/step - loss: 1.4307 - accuracy: 0.4360
Epoch 7/10
2/2 [==============================] - 0s 96ms/step - loss: 1.3072 - accuracy: 0.5360
Epoch 8/10
2/2 [==============================] - 0s 93ms/step - loss: 1.2048 - accuracy: 0.5360
Epoch 9/10
2/2 [==============================] - 0s 95ms/step - loss: 1.0825 - accuracy: 0.6120
Epoch 10/10
2/2 [==============================] - 0s 92ms/step - loss: 1.0610 - accuracy: 0.5920
250/250 [==============================] - 2s 7ms/step - loss: 1.8355 - accuracy: 0.3598
Test Accuracy (Batch 3): 35.98%
Epoch 1/10
2/2 [==============================] - 0s 95ms/step - loss: 2.1050 - accuracy: 0.3160
Epoch 2/10
2/2 [==============================] - 0s 93ms/step - loss: 1.9055 - accuracy: 0.3120
Epoch 3/10
2/2 [==============================] - 0s 94ms/step - loss: 1.7636 - accuracy: 0.3480
Epoch 4/10
2/2 [==============================] - 0s 93ms/step - loss: 1.6812 - accuracy: 0.3680
Epoch 5/10
2/2 [==============================] - 0s 93ms/step - loss: 1.5867 - accuracy: 0.4280
Epoch 6/10
2/2 [==============================] - 0s 94ms/step - loss: 1.4939 - accuracy: 0.4760
Epoch 7/10
2/2 [==============================] - 0s 94ms/step - loss: 1.3223 - accuracy: 0.5240
Epoch 8/10
2/2 [==============================] - 0s 96ms/step - loss: 1.2060 - accuracy: 0.5360
Epoch 9/10
2/2 [==============================] - 0s 95ms/step - loss: 1.0960 - accuracy: 0.6160
Epoch 10/10
2/2 [==============================] - 0s 90ms/step - loss: 1.0262 - accuracy: 0.6200
250/250 [==============================] - 2s 7ms/step - loss: 1.8042 - accuracy: 0.3837
Test Accuracy (Batch 4): 38.37%
Epoch 1/10
2/2 [==============================] - 0s 97ms/step - loss: 1.9268 - accuracy: 0.3840
Epoch 2/10
2/2 [==============================] - 0s 92ms/step - loss: 1.6431 - accuracy: 0.4520
Epoch 3/10
2/2 [==============================] - 0s 94ms/step - loss: 1.5282 - accuracy: 0.4600
Epoch 4/10
2/2 [==============================] - 0s 94ms/step - loss: 1.4662 - accuracy: 0.4880
Epoch 5/10
2/2 [==============================] - 0s 93ms/step - loss: 1.3683 - accuracy: 0.5480
Epoch 6/10
2/2 [==============================] - 0s 92ms/step - loss: 1.3338 - accuracy: 0.5680
Epoch 7/10
2/2 [==============================] - 0s 91ms/step - loss: 1.1613 - accuracy: 0.6040
Epoch 8/10
2/2 [==============================] - 0s 96ms/step - loss: 1.0495 - accuracy: 0.6840
Epoch 9/10
2/2 [==============================] - 0s 93ms/step - loss: 0.9188 - accuracy: 0.6880
Epoch 10/10
2/2 [==============================] - 0s 94ms/step - loss: 0.8979 - accuracy: 0.6840
250/250 [==============================] - 2s 7ms/step - loss: 1.8812 - accuracy: 0.3889
Test Accuracy (Batch 5): 38.89%
Epoch 1/10
2/2 [==============================] - 0s 104ms/step - loss: 2.0471 - accuracy: 0.2920
Epoch 2/10
2/2 [==============================] - 0s 93ms/step - loss: 1.6727 - accuracy: 0.4080
Epoch 3/10
2/2 [==============================] - 0s 94ms/step - loss: 1.4892 - accuracy: 0.4680
Epoch 4/10
2/2 [==============================] - 0s 97ms/step - loss: 1.4812 - accuracy: 0.4680
Epoch 5/10
2/2 [==============================] - 0s 102ms/step - loss: 1.3963 - accuracy: 0.5280
Epoch 6/10
2/2 [==============================] - 0s 93ms/step - loss: 1.3262 - accuracy: 0.4960
Epoch 7/10
2/2 [==============================] - 0s 94ms/step - loss: 1.2195 - accuracy: 0.5840
Epoch 8/10
2/2 [==============================] - 0s 92ms/step - loss: 1.0679 - accuracy: 0.6400
Epoch 9/10
2/2 [==============================] - 0s 93ms/step - loss: 0.9496 - accuracy: 0.7000
Epoch 10/10
2/2 [==============================] - 0s 91ms/step - loss: 0.7930 - accuracy: 0.7560
250/250 [==============================] - 2s 7ms/step - loss: 1.6976 - accuracy: 0.4230
Test Accuracy (Batch 6): 42.30%
Epoch 1/10
2/2 [==============================] - 0s 94ms/step - loss: 1.9594 - accuracy: 0.3600
Epoch 2/10
2/2 [==============================] - 0s 94ms/step - loss: 1.7502 - accuracy: 0.3840
Epoch 3/10
2/2 [==============================] - 0s 92ms/step - loss: 1.4398 - accuracy: 0.4480
Epoch 4/10
2/2 [==============================] - 0s 92ms/step - loss: 1.3212 - accuracy: 0.5240
Epoch 5/10
2/2 [==============================] - 0s 92ms/step - loss: 1.2182 - accuracy: 0.5600
Epoch 6/10
2/2 [==============================] - 0s 96ms/step - loss: 1.0654 - accuracy: 0.6680
Epoch 7/10
2/2 [==============================] - 0s 94ms/step - loss: 0.9526 - accuracy: 0.7080
Epoch 8/10
2/2 [==============================] - 0s 93ms/step - loss: 0.7707 - accuracy: 0.7600
Epoch 9/10
2/2 [==============================] - 0s 95ms/step - loss: 0.5938 - accuracy: 0.7960
Epoch 10/10
2/2 [==============================] - 0s 90ms/step - loss: 0.5247 - accuracy: 0.8400
250/250 [==============================] - 2s 7ms/step - loss: 1.9599 - accuracy: 0.4142
Test Accuracy (Batch 7): 41.42%
Epoch 1/10
2/2 [==============================] - 0s 100ms/step - loss: 2.0530 - accuracy: 0.4040
Epoch 2/10
2/2 [==============================] - 0s 96ms/step - loss: 1.7283 - accuracy: 0.4480
Epoch 3/10
2/2 [==============================] - 0s 94ms/step - loss: 1.3952 - accuracy: 0.5120
Epoch 4/10
2/2 [==============================] - 0s 96ms/step - loss: 1.2766 - accuracy: 0.5560
Epoch 5/10
2/2 [==============================] - 0s 96ms/step - loss: 1.2284 - accuracy: 0.5720
Epoch 6/10
2/2 [==============================] - 0s 97ms/step - loss: 1.1505 - accuracy: 0.6480
Epoch 7/10
2/2 [==============================] - 0s 103ms/step - loss: 1.0201 - accuracy: 0.6840
Epoch 8/10
2/2 [==============================] - 0s 97ms/step - loss: 0.8842 - accuracy: 0.7200
Epoch 9/10
2/2 [==============================] - 0s 93ms/step - loss: 0.7200 - accuracy: 0.7880
Epoch 10/10
2/2 [==============================] - 0s 93ms/step - loss: 0.5902 - accuracy: 0.8200
250/250 [==============================] - 2s 6ms/step - loss: 1.8041 - accuracy: 0.4329
Test Accuracy (Batch 8): 43.29%
Epoch 1/10
2/2 [==============================] - 0s 94ms/step - loss: 2.0013 - accuracy: 0.3960
Epoch 2/10
2/2 [==============================] - 0s 95ms/step - loss: 1.6939 - accuracy: 0.4240
Epoch 3/10
2/2 [==============================] - 0s 93ms/step - loss: 1.4268 - accuracy: 0.4760
Epoch 4/10
2/2 [==============================] - 0s 92ms/step - loss: 1.3152 - accuracy: 0.4960
Epoch 5/10
2/2 [==============================] - 0s 93ms/step - loss: 1.0528 - accuracy: 0.6160
Epoch 6/10
2/2 [==============================] - 0s 94ms/step - loss: 0.9712 - accuracy: 0.7040
Epoch 7/10
2/2 [==============================] - 0s 94ms/step - loss: 0.8494 - accuracy: 0.7760
Epoch 8/10
2/2 [==============================] - 0s 93ms/step - loss: 0.6728 - accuracy: 0.8360
Epoch 9/10
2/2 [==============================] - 0s 96ms/step - loss: 0.5797 - accuracy: 0.8240
Epoch 10/10
2/2 [==============================] - 0s 91ms/step - loss: 0.4601 - accuracy: 0.8520
250/250 [==============================] - 2s 7ms/step - loss: 1.9356 - accuracy: 0.4111
Test Accuracy (Batch 9): 41.11%
Epoch 1/10
2/2 [==============================] - 0s 95ms/step - loss: 2.1183 - accuracy: 0.4000
Epoch 2/10
2/2 [==============================] - 0s 96ms/step - loss: 1.5435 - accuracy: 0.4200
Epoch 3/10
2/2 [==============================] - 0s 95ms/step - loss: 1.3654 - accuracy: 0.4920
Epoch 4/10
2/2 [==============================] - 0s 93ms/step - loss: 1.2494 - accuracy: 0.5160
Epoch 5/10
2/2 [==============================] - 0s 94ms/step - loss: 1.1105 - accuracy: 0.6480
Epoch 6/10
2/2 [==============================] - 0s 92ms/step - loss: 1.0065 - accuracy: 0.6800
Epoch 7/10
2/2 [==============================] - 0s 99ms/step - loss: 0.8523 - accuracy: 0.7720
Epoch 8/10
2/2 [==============================] - 0s 94ms/step - loss: 0.6873 - accuracy: 0.8160
Epoch 9/10
2/2 [==============================] - 0s 97ms/step - loss: 0.5440 - accuracy: 0.8440
Epoch 10/10
2/2 [==============================] - 0s 97ms/step - loss: 0.4517 - accuracy: 0.8440
250/250 [==============================] - 2s 7ms/step - loss: 1.7858 - accuracy: 0.4505
Test Accuracy (Batch 10): 45.05%
Epoch 1/10
2/2 [==============================] - 0s 97ms/step - loss: 1.9202 - accuracy: 0.4440
Epoch 2/10
2/2 [==============================] - 0s 96ms/step - loss: 1.5573 - accuracy: 0.4920
Epoch 3/10
2/2 [==============================] - 0s 94ms/step - loss: 1.3404 - accuracy: 0.5120
Epoch 4/10
2/2 [==============================] - 0s 95ms/step - loss: 1.1290 - accuracy: 0.6160
Epoch 5/10
2/2 [==============================] - 0s 96ms/step - loss: 1.0196 - accuracy: 0.6680
Epoch 6/10
2/2 [==============================] - 0s 94ms/step - loss: 0.8854 - accuracy: 0.7320
Epoch 7/10
2/2 [==============================] - 0s 94ms/step - loss: 0.6979 - accuracy: 0.8120
Epoch 8/10
2/2 [==============================] - 0s 94ms/step - loss: 0.6169 - accuracy: 0.8160
Epoch 9/10
2/2 [==============================] - 0s 96ms/step - loss: 0.4656 - accuracy: 0.8400
Epoch 10/10
2/2 [==============================] - 0s 92ms/step - loss: 0.3636 - accuracy: 0.8880
250/250 [==============================] - 2s 7ms/step - loss: 1.7781 - accuracy: 0.4596
Test Accuracy (Batch 11): 45.96%
Epoch 1/10
2/2 [==============================] - 0s 95ms/step - loss: 1.9228 - accuracy: 0.4160
Epoch 2/10
2/2 [==============================] - 0s 98ms/step - loss: 1.6068 - accuracy: 0.4880
Epoch 3/10
2/2 [==============================] - 0s 96ms/step - loss: 1.1992 - accuracy: 0.5360
Epoch 4/10
2/2 [==============================] - 0s 104ms/step - loss: 1.0918 - accuracy: 0.6120
Epoch 5/10
2/2 [==============================] - 0s 98ms/step - loss: 0.8625 - accuracy: 0.7160
Epoch 6/10
2/2 [==============================] - 0s 95ms/step - loss: 0.7556 - accuracy: 0.8120
Epoch 7/10
2/2 [==============================] - 0s 94ms/step - loss: 0.6101 - accuracy: 0.8760
Epoch 8/10
2/2 [==============================] - 0s 93ms/step - loss: 0.4855 - accuracy: 0.9080
Epoch 9/10
2/2 [==============================] - 0s 95ms/step - loss: 0.3600 - accuracy: 0.9400
Epoch 10/10
2/2 [==============================] - 0s 91ms/step - loss: 0.2722 - accuracy: 0.9320
250/250 [==============================] - 2s 7ms/step - loss: 1.8068 - accuracy: 0.4661
Test Accuracy (Batch 12): 46.61%
Epoch 1/10
2/2 [==============================] - 0s 96ms/step - loss: 1.8860 - accuracy: 0.4600
Epoch 2/10
2/2 [==============================] - 0s 97ms/step - loss: 1.4856 - accuracy: 0.4920
Epoch 3/10
2/2 [==============================] - 0s 93ms/step - loss: 1.2128 - accuracy: 0.5320
Epoch 4/10
2/2 [==============================] - 0s 99ms/step - loss: 0.9177 - accuracy: 0.6560
Epoch 5/10
2/2 [==============================] - 0s 95ms/step - loss: 0.7968 - accuracy: 0.7480
Epoch 6/10
2/2 [==============================] - 0s 95ms/step - loss: 0.6583 - accuracy: 0.8200
Epoch 7/10
2/2 [==============================] - 0s 96ms/step - loss: 0.5223 - accuracy: 0.8560
Epoch 8/10
2/2 [==============================] - 0s 94ms/step - loss: 0.3781 - accuracy: 0.8920
Epoch 9/10
2/2 [==============================] - 0s 97ms/step - loss: 0.2948 - accuracy: 0.9320
Epoch 10/10
2/2 [==============================] - 0s 93ms/step - loss: 0.2115 - accuracy: 0.9560
250/250 [==============================] - 2s 7ms/step - loss: 2.1034 - accuracy: 0.4459
Test Accuracy (Batch 13): 44.59%
Epoch 1/10
2/2 [==============================] - 0s 105ms/step - loss: 2.4057 - accuracy: 0.4040
Epoch 2/10
2/2 [==============================] - 0s 98ms/step - loss: 1.7580 - accuracy: 0.4120
Epoch 3/10
2/2 [==============================] - 0s 100ms/step - loss: 1.3883 - accuracy: 0.4920
Epoch 4/10
2/2 [==============================] - 0s 103ms/step - loss: 1.1541 - accuracy: 0.5520
Epoch 5/10
2/2 [==============================] - 0s 95ms/step - loss: 1.0490 - accuracy: 0.6200
Epoch 6/10
2/2 [==============================] - 0s 102ms/step - loss: 1.0220 - accuracy: 0.6640
Epoch 7/10
2/2 [==============================] - 0s 92ms/step - loss: 0.9243 - accuracy: 0.7280
Epoch 8/10
2/2 [==============================] - 0s 93ms/step - loss: 0.8450 - accuracy: 0.7720
Epoch 9/10
2/2 [==============================] - 0s 94ms/step - loss: 0.6937 - accuracy: 0.8120
Epoch 10/10
2/2 [==============================] - 0s 92ms/step - loss: 0.5443 - accuracy: 0.8640
250/250 [==============================] - 2s 7ms/step - loss: 1.6286 - accuracy: 0.4550
Test Accuracy (Batch 14): 45.50%
Epoch 1/10
2/2 [==============================] - 0s 95ms/step - loss: 1.6132 - accuracy: 0.4400
Epoch 2/10
2/2 [==============================] - 0s 93ms/step - loss: 1.3763 - accuracy: 0.5400
Epoch 3/10
2/2 [==============================] - 0s 97ms/step - loss: 1.1882 - accuracy: 0.5760
Epoch 4/10
2/2 [==============================] - 0s 95ms/step - loss: 0.9696 - accuracy: 0.6560
Epoch 5/10
2/2 [==============================] - 0s 92ms/step - loss: 0.7964 - accuracy: 0.6920
Epoch 6/10
2/2 [==============================] - 0s 96ms/step - loss: 0.6610 - accuracy: 0.7640
Epoch 7/10
2/2 [==============================] - 0s 93ms/step - loss: 0.5098 - accuracy: 0.8520
Epoch 8/10
2/2 [==============================] - 0s 98ms/step - loss: 0.4784 - accuracy: 0.8520
Epoch 9/10
2/2 [==============================] - 0s 95ms/step - loss: 0.3325 - accuracy: 0.9400
Epoch 10/10
2/2 [==============================] - 0s 94ms/step - loss: 0.2409 - accuracy: 0.9600
250/250 [==============================] - 2s 7ms/step - loss: 1.7182 - accuracy: 0.4793
Test Accuracy (Batch 15): 47.93%
Epoch 1/10
2/2 [==============================] - 0s 100ms/step - loss: 1.8931 - accuracy: 0.4320
Epoch 2/10
2/2 [==============================] - 0s 103ms/step - loss: 1.4491 - accuracy: 0.5040
Epoch 3/10
2/2 [==============================] - 0s 106ms/step - loss: 1.1594 - accuracy: 0.5800
Epoch 4/10
2/2 [==============================] - 0s 98ms/step - loss: 0.9493 - accuracy: 0.6880
Epoch 5/10
2/2 [==============================] - 0s 97ms/step - loss: 0.7570 - accuracy: 0.7360
Epoch 6/10
2/2 [==============================] - 0s 93ms/step - loss: 0.6211 - accuracy: 0.8240
Epoch 7/10
2/2 [==============================] - 0s 95ms/step - loss: 0.4600 - accuracy: 0.8800
Epoch 8/10
2/2 [==============================] - 0s 93ms/step - loss: 0.3408 - accuracy: 0.9200
Epoch 9/10
2/2 [==============================] - 0s 99ms/step - loss: 0.2387 - accuracy: 0.9440
Epoch 10/10
2/2 [==============================] - 0s 94ms/step - loss: 0.1592 - accuracy: 0.9560
250/250 [==============================] - 2s 7ms/step - loss: 2.0068 - accuracy: 0.4888
Test Accuracy (Batch 16): 48.88%
Epoch 1/10
2/2 [==============================] - 0s 95ms/step - loss: 2.3866 - accuracy: 0.4360
Epoch 2/10
2/2 [==============================] - 0s 98ms/step - loss: 1.6022 - accuracy: 0.5040
Epoch 3/10
2/2 [==============================] - 0s 95ms/step - loss: 1.1206 - accuracy: 0.5960
Epoch 4/10
2/2 [==============================] - 0s 98ms/step - loss: 0.9186 - accuracy: 0.6600
Epoch 5/10
2/2 [==============================] - 0s 95ms/step - loss: 0.8237 - accuracy: 0.7280
Epoch 6/10
2/2 [==============================] - 0s 99ms/step - loss: 0.7128 - accuracy: 0.8040
Epoch 7/10
2/2 [==============================] - 0s 94ms/step - loss: 0.5584 - accuracy: 0.8720
Epoch 8/10
2/2 [==============================] - 0s 98ms/step - loss: 0.4522 - accuracy: 0.9000
Epoch 9/10
2/2 [==============================] - 0s 98ms/step - loss: 0.3276 - accuracy: 0.9360
Epoch 10/10
2/2 [==============================] - 0s 96ms/step - loss: 0.2200 - accuracy: 0.9600
250/250 [==============================] - 2s 7ms/step - loss: 1.7209 - accuracy: 0.4930
Test Accuracy (Batch 17): 49.30%
Epoch 1/10
2/2 [==============================] - 0s 102ms/step - loss: 1.8780 - accuracy: 0.4640
Epoch 2/10
2/2 [==============================] - 0s 107ms/step - loss: 1.4308 - accuracy: 0.5200
Epoch 3/10
2/2 [==============================] - 0s 100ms/step - loss: 1.0627 - accuracy: 0.6120
Epoch 4/10
2/2 [==============================] - 0s 96ms/step - loss: 0.8961 - accuracy: 0.7120
Epoch 5/10
2/2 [==============================] - 0s 97ms/step - loss: 0.7300 - accuracy: 0.7800
Epoch 6/10
2/2 [==============================] - 0s 99ms/step - loss: 0.5716 - accuracy: 0.8480
Epoch 7/10
2/2 [==============================] - 0s 98ms/step - loss: 0.4035 - accuracy: 0.9280
Epoch 8/10
2/2 [==============================] - 0s 99ms/step - loss: 0.3177 - accuracy: 0.9280
Epoch 9/10
2/2 [==============================] - 0s 95ms/step - loss: 0.2303 - accuracy: 0.9440
Epoch 10/10
2/2 [==============================] - 0s 96ms/step - loss: 0.1557 - accuracy: 0.9600
250/250 [==============================] - 2s 7ms/step - loss: 1.9475 - accuracy: 0.4904
Test Accuracy (Batch 18): 49.04%
Epoch 1/10
2/2 [==============================] - 0s 97ms/step - loss: 2.4100 - accuracy: 0.3920
Epoch 2/10
2/2 [==============================] - 0s 96ms/step - loss: 1.8550 - accuracy: 0.4440
Epoch 3/10
2/2 [==============================] - 0s 98ms/step - loss: 1.3585 - accuracy: 0.5080
Epoch 4/10

#### Batches 10

In [ ]:
import tensorflow as tf
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras import layers
# x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=42)
# Normalize the input data
x_train = X_train.astype('float32') / 255.0
x_test = X_test.astype('float32') / 255.0

# Convert the labels to one-hot encoding
num_classes = 10
# y_train = tf.keras.utils.to_categorical(y_train, num_classes)
# y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training set into 20 batches
num_batches = 10
x_train_batches = np.array_split(x_train, num_batches)
y_train_batches = np.array_split(y_train, num_batches)

# Initialize the list to store test accuracies
accuracies = []

# Define the model architecture
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(96, 96, 3)),
    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu'),
    layers.Dropout(0.25),
    Dense(num_classes, activation='softmax')
])


model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch
epochs = 10
for i in range(num_batches):
    x_train_batch = x_train_batches[i]
    y_train_batch = y_train_batches[i]
    model.fit(x_train_batch, y_train_batch, batch_size=128, epochs=epochs, verbose=1)

    # Evaluate the model on the test set
    test_loss, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy (Batch {}): {:.2f}%".format(i+1, test_accuracy*100))
    accuracies.append(test_accuracy)

# Print the batch accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Batch-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
4/4 [==============================] - 20s 671ms/step - loss: 3.0803 - accuracy: 0.1120
Epoch 2/10
4/4 [==============================] - 0s 99ms/step - loss: 2.3435 - accuracy: 0.1060
Epoch 3/10
4/4 [==============================] - 0s 99ms/step - loss: 2.2753 - accuracy: 0.1600
Epoch 4/10
4/4 [==============================] - 0s 93ms/step - loss: 2.1915 - accuracy: 0.2140
Epoch 5/10
4/4 [==============================] - 0s 93ms/step - loss: 2.0007 - accuracy: 0.3140
Epoch 6/10
4/4 [==============================] - 0s 100ms/step - loss: 1.9744 - accuracy: 0.3180
Epoch 7/10
4/4 [==============================] - 0s 94ms/step - loss: 1.7705 - accuracy: 0.3780
Epoch 8/10
4/4 [==============================] - 0s 93ms/step - loss: 1.6547 - accuracy: 0.3760
Epoch 9/10
4/4 [==============================] - 0s 94ms/step - loss: 1.5756 - accuracy: 0.4340
Epoch 10/10
4/4 [==============================] - 0s 93ms/step - loss: 1.4948 - accuracy: 0.4540
250/250 [==============================] - 3s 8ms/step - loss: 1.8271 - accuracy: 0.3401
Test Accuracy (Batch 1): 34.01%
Epoch 1/10
4/4 [==============================] - 0s 98ms/step - loss: 1.9079 - accuracy: 0.3140
Epoch 2/10
4/4 [==============================] - 0s 99ms/step - loss: 1.7689 - accuracy: 0.3240
Epoch 3/10
4/4 [==============================] - 0s 101ms/step - loss: 1.6525 - accuracy: 0.3880
Epoch 4/10
4/4 [==============================] - 0s 104ms/step - loss: 1.5984 - accuracy: 0.4100
Epoch 5/10
4/4 [==============================] - 0s 103ms/step - loss: 1.4705 - accuracy: 0.4360
Epoch 6/10
4/4 [==============================] - 0s 103ms/step - loss: 1.3683 - accuracy: 0.5120
Epoch 7/10
4/4 [==============================] - 0s 102ms/step - loss: 1.2907 - accuracy: 0.4940
Epoch 8/10
4/4 [==============================] - 0s 99ms/step - loss: 1.1838 - accuracy: 0.5480
Epoch 9/10
4/4 [==============================] - 0s 93ms/step - loss: 1.0322 - accuracy: 0.6600
Epoch 10/10
4/4 [==============================] - 0s 93ms/step - loss: 0.9586 - accuracy: 0.6340
250/250 [==============================] - 2s 8ms/step - loss: 1.8653 - accuracy: 0.3886
Test Accuracy (Batch 2): 38.86%
Epoch 1/10
4/4 [==============================] - 0s 97ms/step - loss: 1.9061 - accuracy: 0.3620
Epoch 2/10
4/4 [==============================] - 0s 97ms/step - loss: 1.5891 - accuracy: 0.3940
Epoch 3/10
4/4 [==============================] - 0s 94ms/step - loss: 1.5542 - accuracy: 0.4440
Epoch 4/10
4/4 [==============================] - 0s 97ms/step - loss: 1.4559 - accuracy: 0.4800
Epoch 5/10
4/4 [==============================] - 0s 96ms/step - loss: 1.2971 - accuracy: 0.5240
Epoch 6/10
4/4 [==============================] - 0s 103ms/step - loss: 1.1387 - accuracy: 0.5940
Epoch 7/10
4/4 [==============================] - 0s 99ms/step - loss: 1.0175 - accuracy: 0.6160
Epoch 8/10
4/4 [==============================] - 0s 95ms/step - loss: 0.8810 - accuracy: 0.6920
Epoch 9/10
4/4 [==============================] - 0s 97ms/step - loss: 0.7213 - accuracy: 0.7760
Epoch 10/10
4/4 [==============================] - 0s 95ms/step - loss: 0.6045 - accuracy: 0.8080
250/250 [==============================] - 3s 13ms/step - loss: 1.8693 - accuracy: 0.4272
Test Accuracy (Batch 3): 42.72%
Epoch 1/10
4/4 [==============================] - 0s 98ms/step - loss: 1.9367 - accuracy: 0.4020
Epoch 2/10
4/4 [==============================] - 0s 95ms/step - loss: 1.4438 - accuracy: 0.4500
Epoch 3/10
4/4 [==============================] - 0s 99ms/step - loss: 1.4028 - accuracy: 0.5260
Epoch 4/10
4/4 [==============================] - 0s 95ms/step - loss: 1.1986 - accuracy: 0.5980
Epoch 5/10
4/4 [==============================] - 0s 97ms/step - loss: 0.9820 - accuracy: 0.6580
Epoch 6/10
4/4 [==============================] - 0s 103ms/step - loss: 0.8001 - accuracy: 0.7340
Epoch 7/10
4/4 [==============================] - 0s 95ms/step - loss: 0.6001 - accuracy: 0.8040
Epoch 8/10
4/4 [==============================] - 0s 97ms/step - loss: 0.4518 - accuracy: 0.8640
Epoch 9/10
4/4 [==============================] - 0s 96ms/step - loss: 0.3505 - accuracy: 0.9060
Epoch 10/10
4/4 [==============================] - 0s 95ms/step - loss: 0.2170 - accuracy: 0.9400
250/250 [==============================] - 2s 9ms/step - loss: 2.3098 - accuracy: 0.4313
Test Accuracy (Batch 4): 43.13%
Epoch 1/10
4/4 [==============================] - 1s 98ms/step - loss: 2.3196 - accuracy: 0.3380
Epoch 2/10
4/4 [==============================] - 0s 101ms/step - loss: 1.5062 - accuracy: 0.4320
Epoch 3/10
4/4 [==============================] - 0s 98ms/step - loss: 1.4474 - accuracy: 0.5040
Epoch 4/10
4/4 [==============================] - 0s 98ms/step - loss: 1.3202 - accuracy: 0.5520
Epoch 5/10
4/4 [==============================] - 0s 104ms/step - loss: 1.1219 - accuracy: 0.6080
Epoch 6/10
4/4 [==============================] - 0s 103ms/step - loss: 0.9028 - accuracy: 0.6920
Epoch 7/10
4/4 [==============================] - 0s 101ms/step - loss: 0.6687 - accuracy: 0.7720
Epoch 8/10
4/4 [==============================] - 0s 100ms/step - loss: 0.5504 - accuracy: 0.8180
Epoch 9/10
4/4 [==============================] - 0s 100ms/step - loss: 0.3965 - accuracy: 0.8700
Epoch 10/10
4/4 [==============================] - 0s 100ms/step - loss: 0.2729 - accuracy: 0.9100
250/250 [==============================] - 2s 8ms/step - loss: 2.0302 - accuracy: 0.4426
Test Accuracy (Batch 5): 44.26%
Epoch 1/10
4/4 [==============================] - 0s 102ms/step - loss: 2.1953 - accuracy: 0.3720
Epoch 2/10
4/4 [==============================] - 0s 99ms/step - loss: 1.3979 - accuracy: 0.4760
Epoch 3/10
4/4 [==============================] - 0s 98ms/step - loss: 1.2326 - accuracy: 0.5640
Epoch 4/10
4/4 [==============================] - 0s 100ms/step - loss: 1.0980 - accuracy: 0.6360
Epoch 5/10
4/4 [==============================] - 0s 99ms/step - loss: 0.8851 - accuracy: 0.7080
Epoch 6/10
4/4 [==============================] - 0s 98ms/step - loss: 0.6402 - accuracy: 0.7740
Epoch 7/10
4/4 [==============================] - 0s 106ms/step - loss: 0.4455 - accuracy: 0.8520
Epoch 8/10
4/4 [==============================] - 0s 100ms/step - loss: 0.3259 - accuracy: 0.8940
Epoch 9/10
4/4 [==============================] - 0s 98ms/step - loss: 0.2188 - accuracy: 0.9240
Epoch 10/10
4/4 [==============================] - 0s 96ms/step - loss: 0.1406 - accuracy: 0.9640
250/250 [==============================] - 2s 8ms/step - loss: 2.2114 - accuracy: 0.4619
Test Accuracy (Batch 6): 46.19%
Epoch 1/10
4/4 [==============================] - 0s 100ms/step - loss: 2.3426 - accuracy: 0.4180
Epoch 2/10
4/4 [==============================] - 0s 103ms/step - loss: 1.3846 - accuracy: 0.5060
Epoch 3/10
4/4 [==============================] - 0s 96ms/step - loss: 1.1512 - accuracy: 0.6400
Epoch 4/10
4/4 [==============================] - 0s 99ms/step - loss: 1.0122 - accuracy: 0.7060
Epoch 5/10
4/4 [==============================] - 0s 100ms/step - loss: 0.7956 - accuracy: 0.7760
Epoch 6/10
4/4 [==============================] - 0s 97ms/step - loss: 0.5929 - accuracy: 0.8060
Epoch 7/10
4/4 [==============================] - 0s 101ms/step - loss: 0.4086 - accuracy: 0.8840
Epoch 8/10
4/4 [==============================] - 0s 96ms/step - loss: 0.2830 - accuracy: 0.9000
Epoch 9/10
4/4 [==============================] - 0s 101ms/step - loss: 0.2125 - accuracy: 0.9240
Epoch 10/10
4/4 [==============================] - 0s 95ms/step - loss: 0.1685 - accuracy: 0.9480
250/250 [==============================] - 3s 11ms/step - loss: 2.1927 - accuracy: 0.4486
Test Accuracy (Batch 7): 44.86%
Epoch 1/10
4/4 [==============================] - 0s 108ms/step - loss: 2.1671 - accuracy: 0.4240
Epoch 2/10
4/4 [==============================] - 0s 102ms/step - loss: 1.2883 - accuracy: 0.5560
Epoch 3/10
4/4 [==============================] - 0s 98ms/step - loss: 1.0119 - accuracy: 0.6660
Epoch 4/10
4/4 [==============================] - 0s 97ms/step - loss: 0.8019 - accuracy: 0.7980
Epoch 5/10
4/4 [==============================] - 0s 100ms/step - loss: 0.5477 - accuracy: 0.8460
Epoch 6/10
4/4 [==============================] - 0s 106ms/step - loss: 0.3582 - accuracy: 0.8800
Epoch 7/10
4/4 [==============================] - 0s 99ms/step - loss: 0.2010 - accuracy: 0.9540
Epoch 8/10
4/4 [==============================] - 0s 99ms/step - loss: 0.1633 - accuracy: 0.9500
Epoch 9/10
4/4 [==============================] - 0s 99ms/step - loss: 0.1186 - accuracy: 0.9660
Epoch 10/10
4/4 [==============================] - 0s 97ms/step - loss: 0.0570 - accuracy: 0.9940
250/250 [==============================] - 2s 8ms/step - loss: 2.3866 - accuracy: 0.4720
Test Accuracy (Batch 8): 47.20%
Epoch 1/10
4/4 [==============================] - 0s 107ms/step - loss: 2.3583 - accuracy: 0.4340
Epoch 2/10
4/4 [==============================] - 0s 107ms/step - loss: 1.3238 - accuracy: 0.5040
Epoch 3/10
4/4 [==============================] - 0s 102ms/step - loss: 1.1747 - accuracy: 0.6040
Epoch 4/10
4/4 [==============================] - 0s 99ms/step - loss: 0.9808 - accuracy: 0.6920
Epoch 5/10
4/4 [==============================] - 0s 98ms/step - loss: 0.7894 - accuracy: 0.7660
Epoch 6/10
4/4 [==============================] - 0s 99ms/step - loss: 0.5927 - accuracy: 0.8040
Epoch 7/10
4/4 [==============================] - 0s 100ms/step - loss: 0.4244 - accuracy: 0.8580
Epoch 8/10
4/4 [==============================] - 0s 99ms/step - loss: 0.3017 - accuracy: 0.9080
Epoch 9/10
4/4 [==============================] - 0s 98ms/step - loss: 0.2100 - accuracy: 0.9420
Epoch 10/10
4/4 [==============================] - 0s 95ms/step - loss: 0.1625 - accuracy: 0.9540
250/250 [==============================] - 2s 8ms/step - loss: 2.0370 - accuracy: 0.4921
Test Accuracy (Batch 9): 49.21%
Epoch 1/10
4/4 [==============================] - 0s 102ms/step - loss: 2.1295 - accuracy: 0.4920
Epoch 2/10
4/4 [==============================] - 0s 100ms/step - loss: 1.2517 - accuracy: 0.5740
Epoch 3/10
4/4 [==============================] - 0s 102ms/step - loss: 1.0172 - accuracy: 0.6620
Epoch 4/10
4/4 [==============================] - 0s 106ms/step - loss: 0.8813 - accuracy: 0.7580
Epoch 5/10
4/4 [==============================] - 0s 101ms/step - loss: 0.6916 - accuracy: 0.8320
Epoch 6/10
4/4 [==============================] - 0s 101ms/step - loss: 0.5008 - accuracy: 0.8780
Epoch 7/10
4/4 [==============================] - 0s 101ms/step - loss: 0.3551 - accuracy: 0.9040
Epoch 8/10
4/4 [==============================] - 0s 103ms/step - loss: 0.2354 - accuracy: 0.9300
Epoch 9/10
4/4 [==============================] - 0s 104ms/step - loss: 0.1606 - accuracy: 0.9540
Epoch 10/10
4/4 [==============================] - 0s 98ms/step - loss: 0.1159 - accuracy: 0.9680
250/250 [==============================] - 2s 7ms/step - loss: 2.1456 - accuracy: 0.4940
Test Accuracy (Batch 10): 49.40%
Batch-1: 34.01%
Batch-2: 38.86%
Batch-3: 42.72%
Batch-4: 43.13%
Batch-5: 44.26%
Batch-6: 46.19%
Batch-7: 44.86%
Batch-8: 47.20%
Batch-9: 49.21%
Batch-10: 49.40%

#### Batches 6

In [ ]:
import tensorflow as tf
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras import layers
# x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=42)
# Normalize the input data
x_train = X_train.astype('float32') / 255.0
x_test = X_test.astype('float32') / 255.0

# Convert the labels to one-hot encoding
num_classes = 10
# y_train = tf.keras.utils.to_categorical(y_train, num_classes)
# y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training set into 20 batches
num_batches = 6
x_train_batches = np.array_split(x_train, num_batches)
y_train_batches = np.array_split(y_train, num_batches)

# Initialize the list to store test accuracies
accuracies = []

# Define the model architecture
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(96, 96, 3)),
    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu'),
    layers.Dropout(0.25),
    Dense(num_classes, activation='softmax')
])


model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch
epochs = 10
for i in range(num_batches):
    x_train_batch = x_train_batches[i]
    y_train_batch = y_train_batches[i]
    model.fit(x_train_batch, y_train_batch, batch_size=128, epochs=epochs, verbose=1)

    # Evaluate the model on the test set
    test_loss, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy (Batch {}): {:.2f}%".format(i+1, test_accuracy*100))
    accuracies.append(test_accuracy)

# Print the batch accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Batch-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
7/7 [==============================] - 5s 300ms/step - loss: 2.6190 - accuracy: 0.1067
Epoch 2/10
7/7 [==============================] - 1s 90ms/step - loss: 2.2705 - accuracy: 0.1283
Epoch 3/10
7/7 [==============================] - 1s 91ms/step - loss: 2.1605 - accuracy: 0.2110
Epoch 4/10
7/7 [==============================] - 1s 90ms/step - loss: 1.9941 - accuracy: 0.2662
Epoch 5/10
7/7 [==============================] - 1s 89ms/step - loss: 1.9315 - accuracy: 0.2854
Epoch 6/10
7/7 [==============================] - 1s 90ms/step - loss: 1.7861 - accuracy: 0.3501
Epoch 7/10
7/7 [==============================] - 1s 90ms/step - loss: 1.6577 - accuracy: 0.4089
Epoch 8/10
7/7 [==============================] - 1s 90ms/step - loss: 1.5264 - accuracy: 0.4376
Epoch 9/10
7/7 [==============================] - 1s 90ms/step - loss: 1.4330 - accuracy: 0.4868
Epoch 10/10
7/7 [==============================] - 1s 92ms/step - loss: 1.2836 - accuracy: 0.5372
250/250 [==============================] - 2s 7ms/step - loss: 1.6417 - accuracy: 0.4013
Test Accuracy (Batch 1): 40.13%
Epoch 1/10
7/7 [==============================] - 1s 91ms/step - loss: 1.6389 - accuracy: 0.3789
Epoch 2/10
7/7 [==============================] - 1s 90ms/step - loss: 1.5070 - accuracy: 0.4508
Epoch 3/10
7/7 [==============================] - 1s 91ms/step - loss: 1.3794 - accuracy: 0.4868
Epoch 4/10
7/7 [==============================] - 1s 92ms/step - loss: 1.2717 - accuracy: 0.5528
Epoch 5/10
7/7 [==============================] - 1s 92ms/step - loss: 1.1061 - accuracy: 0.5959
Epoch 6/10
7/7 [==============================] - 1s 92ms/step - loss: 0.9732 - accuracy: 0.6679
Epoch 7/10
7/7 [==============================] - 1s 92ms/step - loss: 0.8069 - accuracy: 0.7110
Epoch 8/10
7/7 [==============================] - 1s 91ms/step - loss: 0.6602 - accuracy: 0.7614
Epoch 9/10
7/7 [==============================] - 1s 92ms/step - loss: 0.4872 - accuracy: 0.8693
Epoch 10/10
7/7 [==============================] - 1s 95ms/step - loss: 0.3822 - accuracy: 0.8801
250/250 [==============================] - 2s 7ms/step - loss: 2.5204 - accuracy: 0.4326
Test Accuracy (Batch 2): 43.26%
Epoch 1/10
7/7 [==============================] - 2s 272ms/step - loss: 2.1761 - accuracy: 0.3577
Epoch 2/10
7/7 [==============================] - 1s 91ms/step - loss: 1.7119 - accuracy: 0.4022
Epoch 3/10
7/7 [==============================] - 1s 91ms/step - loss: 1.5302 - accuracy: 0.4658
Epoch 4/10
7/7 [==============================] - 1s 92ms/step - loss: 1.3564 - accuracy: 0.5294
Epoch 5/10
7/7 [==============================] - 1s 91ms/step - loss: 1.2002 - accuracy: 0.5918
Epoch 6/10
7/7 [==============================] - 1s 93ms/step - loss: 1.0177 - accuracy: 0.6495
Epoch 7/10
7/7 [==============================] - 1s 93ms/step - loss: 0.8223 - accuracy: 0.7239
Epoch 8/10
7/7 [==============================] - 1s 92ms/step - loss: 0.6433 - accuracy: 0.7803
Epoch 9/10
7/7 [==============================] - 1s 93ms/step - loss: 0.4631 - accuracy: 0.8379
Epoch 10/10
7/7 [==============================] - 1s 93ms/step - loss: 0.3475 - accuracy: 0.8932
250/250 [==============================] - 2s 7ms/step - loss: 2.1348 - accuracy: 0.4485
Test Accuracy (Batch 3): 44.85%
Epoch 1/10
7/7 [==============================] - 1s 93ms/step - loss: 2.0177 - accuracy: 0.3962
Epoch 2/10
7/7 [==============================] - 1s 92ms/step - loss: 1.3591 - accuracy: 0.4922
Epoch 3/10
7/7 [==============================] - 1s 93ms/step - loss: 1.1934 - accuracy: 0.5834
Epoch 4/10
7/7 [==============================] - 1s 93ms/step - loss: 0.9950 - accuracy: 0.6567
Epoch 5/10
7/7 [==============================] - 1s 92ms/step - loss: 0.8571 - accuracy: 0.7011
Epoch 6/10
7/7 [==============================] - 1s 93ms/step - loss: 0.5988 - accuracy: 0.8091
Epoch 7/10
7/7 [==============================] - 1s 97ms/step - loss: 0.4334 - accuracy: 0.8547
Epoch 8/10
7/7 [==============================] - 1s 97ms/step - loss: 0.2486 - accuracy: 0.9292
Epoch 9/10
7/7 [==============================] - 1s 94ms/step - loss: 0.1875 - accuracy: 0.9328
Epoch 10/10
7/7 [==============================] - 1s 93ms/step - loss: 0.1408 - accuracy: 0.9592
250/250 [==============================] - 2s 7ms/step - loss: 2.5516 - accuracy: 0.4459
Test Accuracy (Batch 4): 44.59%
Epoch 1/10
7/7 [==============================] - 1s 93ms/step - loss: 2.3750 - accuracy: 0.4190
Epoch 2/10
7/7 [==============================] - 1s 94ms/step - loss: 1.4615 - accuracy: 0.4682
Epoch 3/10
7/7 [==============================] - 1s 94ms/step - loss: 1.2736 - accuracy: 0.5774
Epoch 4/10
7/7 [==============================] - 1s 93ms/step - loss: 1.0462 - accuracy: 0.6303
Epoch 5/10
7/7 [==============================] - 1s 93ms/step - loss: 0.7932 - accuracy: 0.7047
Epoch 6/10
7/7 [==============================] - 1s 94ms/step - loss: 0.6312 - accuracy: 0.7827
Epoch 7/10
7/7 [==============================] - 1s 94ms/step - loss: 0.4507 - accuracy: 0.8475
Epoch 8/10
7/7 [==============================] - 1s 95ms/step - loss: 0.3445 - accuracy: 0.8800
Epoch 9/10
7/7 [==============================] - 1s 96ms/step - loss: 0.2651 - accuracy: 0.9148
Epoch 10/10
7/7 [==============================] - 1s 96ms/step - loss: 0.1493 - accuracy: 0.9664
250/250 [==============================] - 2s 7ms/step - loss: 2.1593 - accuracy: 0.4737
Test Accuracy (Batch 5): 47.37%
Epoch 1/10
7/7 [==============================] - 1s 93ms/step - loss: 2.0719 - accuracy: 0.4646
Epoch 2/10
7/7 [==============================] - 1s 93ms/step - loss: 1.2688 - accuracy: 0.5438
Epoch 3/10
7/7 [==============================] - 1s 91ms/step - loss: 1.0838 - accuracy: 0.6543
Epoch 4/10
7/7 [==============================] - 1s 93ms/step - loss: 0.7725 - accuracy: 0.7323
Epoch 5/10
7/7 [==============================] - 1s 94ms/step - loss: 0.5201 - accuracy: 0.8319
Epoch 6/10
7/7 [==============================] - 1s 95ms/step - loss: 0.3323 - accuracy: 0.8860
Epoch 7/10
7/7 [==============================] - 1s 94ms/step - loss: 0.2013 - accuracy: 0.9400
Epoch 8/10
7/7 [==============================] - 1s 94ms/step - loss: 0.1112 - accuracy: 0.9712
Epoch 9/10
7/7 [==============================] - 1s 93ms/step - loss: 0.0745 - accuracy: 0.9808
Epoch 10/10
7/7 [==============================] - 1s 95ms/step - loss: 0.0586 - accuracy: 0.9844
250/250 [==============================] - 2s 7ms/step - loss: 2.6894 - accuracy: 0.4895
Test Accuracy (Batch 6): 48.95%
Batch-1: 40.13%
Batch-2: 43.26%
Batch-3: 44.85%
Batch-4: 44.59%
Batch-5: 47.37%
Batch-6: 48.95%

#### Batches 5

In [ ]:
import tensorflow as tf
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras import layers
# x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=42)
# Normalize the input data
x_train = X_train.astype('float32') / 255.0
x_test = X_test.astype('float32') / 255.0

# Convert the labels to one-hot encoding
num_classes = 10
# y_train = tf.keras.utils.to_categorical(y_train, num_classes)
# y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training set into 20 batches
num_batches = 5
x_train_batches = np.array_split(x_train, num_batches)
y_train_batches = np.array_split(y_train, num_batches)

# Initialize the list to store test accuracies
accuracies = []

# Define the model architecture
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(96, 96, 3)),
    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu'),
    layers.Dropout(0.25),
    Dense(num_classes, activation='softmax')
])


model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch
epochs = 10
for i in range(num_batches):
    x_train_batch = x_train_batches[i]
    y_train_batch = y_train_batches[i]
    model.fit(x_train_batch, y_train_batch, batch_size=128, epochs=epochs, verbose=1)

    # Evaluate the model on the test set
    test_loss, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy (Batch {}): {:.2f}%".format(i+1, test_accuracy*100))
    accuracies.append(test_accuracy)

# Print the batch accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Batch-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
8/8 [==============================] - 19s 361ms/step - loss: 3.6558 - accuracy: 0.1020
Epoch 2/10
8/8 [==============================] - 1s 104ms/step - loss: 2.2933 - accuracy: 0.1310
Epoch 3/10
8/8 [==============================] - 1s 111ms/step - loss: 2.2625 - accuracy: 0.1310
Epoch 4/10
8/8 [==============================] - 1s 109ms/step - loss: 2.1538 - accuracy: 0.2030
Epoch 5/10
8/8 [==============================] - 1s 111ms/step - loss: 2.0013 - accuracy: 0.2360
Epoch 6/10
8/8 [==============================] - 1s 102ms/step - loss: 1.8661 - accuracy: 0.3010
Epoch 7/10
8/8 [==============================] - 1s 105ms/step - loss: 1.7962 - accuracy: 0.3390
Epoch 8/10
8/8 [==============================] - 1s 99ms/step - loss: 1.6456 - accuracy: 0.3990
Epoch 9/10
8/8 [==============================] - 1s 100ms/step - loss: 1.6208 - accuracy: 0.4000
Epoch 10/10
8/8 [==============================] - 1s 101ms/step - loss: 1.5326 - accuracy: 0.4500
250/250 [==============================] - 3s 9ms/step - loss: 1.6791 - accuracy: 0.3719
Test Accuracy (Batch 1): 37.19%
Epoch 1/10
8/8 [==============================] - 1s 107ms/step - loss: 1.7185 - accuracy: 0.3690
Epoch 2/10
8/8 [==============================] - 1s 106ms/step - loss: 1.5877 - accuracy: 0.4360
Epoch 3/10
8/8 [==============================] - 1s 108ms/step - loss: 1.4945 - accuracy: 0.4510
Epoch 4/10
8/8 [==============================] - 1s 102ms/step - loss: 1.4071 - accuracy: 0.4890
Epoch 5/10
8/8 [==============================] - 1s 101ms/step - loss: 1.3115 - accuracy: 0.5310
Epoch 6/10
8/8 [==============================] - 1s 103ms/step - loss: 1.2451 - accuracy: 0.5640
Epoch 7/10
8/8 [==============================] - 1s 102ms/step - loss: 1.1323 - accuracy: 0.5930
Epoch 8/10
8/8 [==============================] - 1s 103ms/step - loss: 0.9608 - accuracy: 0.6550
Epoch 9/10
8/8 [==============================] - 1s 103ms/step - loss: 0.8534 - accuracy: 0.6960
Epoch 10/10
8/8 [==============================] - 1s 100ms/step - loss: 0.6848 - accuracy: 0.7690
250/250 [==============================] - 2s 8ms/step - loss: 1.8973 - accuracy: 0.4370
Test Accuracy (Batch 2): 43.70%
Epoch 1/10
8/8 [==============================] - 1s 101ms/step - loss: 1.8528 - accuracy: 0.3950
Epoch 2/10
8/8 [==============================] - 1s 103ms/step - loss: 1.5784 - accuracy: 0.4220
Epoch 3/10
8/8 [==============================] - 1s 106ms/step - loss: 1.4319 - accuracy: 0.4690
Epoch 4/10
8/8 [==============================] - 1s 101ms/step - loss: 1.3386 - accuracy: 0.5140
Epoch 5/10
8/8 [==============================] - 1s 104ms/step - loss: 1.2010 - accuracy: 0.5470
Epoch 6/10
8/8 [==============================] - 1s 107ms/step - loss: 1.0934 - accuracy: 0.6070
Epoch 7/10
8/8 [==============================] - 1s 109ms/step - loss: 0.9312 - accuracy: 0.6790
Epoch 8/10
8/8 [==============================] - 1s 108ms/step - loss: 0.7338 - accuracy: 0.7480
Epoch 9/10
8/8 [==============================] - 1s 102ms/step - loss: 0.6449 - accuracy: 0.7750
Epoch 10/10
8/8 [==============================] - 1s 107ms/step - loss: 0.4948 - accuracy: 0.8330
250/250 [==============================] - 2s 8ms/step - loss: 1.8646 - accuracy: 0.4647
Test Accuracy (Batch 3): 46.47%
Epoch 1/10
8/8 [==============================] - 1s 103ms/step - loss: 1.7151 - accuracy: 0.4360
Epoch 2/10
8/8 [==============================] - 1s 101ms/step - loss: 1.4114 - accuracy: 0.4710
Epoch 3/10
8/8 [==============================] - 1s 103ms/step - loss: 1.2454 - accuracy: 0.5170
Epoch 4/10
8/8 [==============================] - 1s 107ms/step - loss: 1.0454 - accuracy: 0.6070
Epoch 5/10
8/8 [==============================] - 1s 104ms/step - loss: 0.9165 - accuracy: 0.6840
Epoch 6/10
8/8 [==============================] - 1s 106ms/step - loss: 0.7555 - accuracy: 0.7230
Epoch 7/10
8/8 [==============================] - 1s 111ms/step - loss: 0.6452 - accuracy: 0.7680
Epoch 8/10
8/8 [==============================] - 1s 112ms/step - loss: 0.5366 - accuracy: 0.8120
Epoch 9/10
8/8 [==============================] - 1s 107ms/step - loss: 0.3973 - accuracy: 0.8760
Epoch 10/10
8/8 [==============================] - 1s 103ms/step - loss: 0.3079 - accuracy: 0.9080
250/250 [==============================] - 2s 8ms/step - loss: 2.0105 - accuracy: 0.4869
Test Accuracy (Batch 4): 48.69%
Epoch 1/10
8/8 [==============================] - 1s 104ms/step - loss: 1.8759 - accuracy: 0.4470
Epoch 2/10
8/8 [==============================] - 1s 102ms/step - loss: 1.3754 - accuracy: 0.5240
Epoch 3/10
8/8 [==============================] - 1s 101ms/step - loss: 1.1824 - accuracy: 0.5830
Epoch 4/10
8/8 [==============================] - 1s 104ms/step - loss: 0.9745 - accuracy: 0.6430
Epoch 5/10
8/8 [==============================] - 1s 109ms/step - loss: 0.7832 - accuracy: 0.7240
Epoch 6/10
8/8 [==============================] - 1s 107ms/step - loss: 0.6345 - accuracy: 0.7860
Epoch 7/10
8/8 [==============================] - 1s 107ms/step - loss: 0.4663 - accuracy: 0.8430
Epoch 8/10
8/8 [==============================] - 1s 105ms/step - loss: 0.3398 - accuracy: 0.8820
Epoch 9/10
8/8 [==============================] - 1s 102ms/step - loss: 0.2569 - accuracy: 0.9200
Epoch 10/10
8/8 [==============================] - 1s 101ms/step - loss: 0.1934 - accuracy: 0.9400
250/250 [==============================] - 2s 7ms/step - loss: 2.2119 - accuracy: 0.4940
Test Accuracy (Batch 5): 49.40%
Batch-1: 37.19%
Batch-2: 43.70%
Batch-3: 46.47%
Batch-4: 48.69%
Batch-5: 49.40%

#### Batches 4

In [ ]:
import tensorflow as tf
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras import layers
# x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=42)
# Normalize the input data
x_train = X_train.astype('float32') / 255.0
x_test = X_test.astype('float32') / 255.0

# Convert the labels to one-hot encoding
num_classes = 10
# y_train = tf.keras.utils.to_categorical(y_train, num_classes)
# y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training set into 20 batches
num_batches = 4
x_train_batches = np.array_split(x_train, num_batches)
y_train_batches = np.array_split(y_train, num_batches)

# Initialize the list to store test accuracies
accuracies = []

# Define the model architecture
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(96, 96, 3)),
    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu'),
    layers.Dropout(0.25),
    Dense(num_classes, activation='softmax')
])


model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch
epochs = 10
for i in range(num_batches):
    x_train_batch = x_train_batches[i]
    y_train_batch = y_train_batches[i]
    model.fit(x_train_batch, y_train_batch, batch_size=128, epochs=epochs, verbose=1)

    # Evaluate the model on the test set
    test_loss, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy (Batch {}): {:.2f}%".format(i+1, test_accuracy*100))
    accuracies.append(test_accuracy)

# Print the batch accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Batch-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
10/10 [==============================] - 6s 283ms/step - loss: 2.8121 - accuracy: 0.1160
Epoch 2/10
10/10 [==============================] - 1s 101ms/step - loss: 2.2747 - accuracy: 0.1648
Epoch 3/10
10/10 [==============================] - 1s 99ms/step - loss: 2.1162 - accuracy: 0.2440
Epoch 4/10
10/10 [==============================] - 1s 101ms/step - loss: 1.9510 - accuracy: 0.2888
Epoch 5/10
10/10 [==============================] - 1s 101ms/step - loss: 1.8742 - accuracy: 0.2968
Epoch 6/10
10/10 [==============================] - 1s 104ms/step - loss: 1.7030 - accuracy: 0.3616
Epoch 7/10
10/10 [==============================] - 1s 102ms/step - loss: 1.5736 - accuracy: 0.4160
Epoch 8/10
10/10 [==============================] - 1s 101ms/step - loss: 1.5062 - accuracy: 0.4424
Epoch 9/10
10/10 [==============================] - 1s 100ms/step - loss: 1.4459 - accuracy: 0.4672
Epoch 10/10
10/10 [==============================] - 1s 99ms/step - loss: 1.2548 - accuracy: 0.5424
250/250 [==============================] - 3s 8ms/step - loss: 1.6398 - accuracy: 0.4232
Test Accuracy (Batch 1): 42.32%
Epoch 1/10
10/10 [==============================] - 1s 99ms/step - loss: 1.6655 - accuracy: 0.3840
Epoch 2/10
10/10 [==============================] - 1s 102ms/step - loss: 1.5665 - accuracy: 0.4176
Epoch 3/10
10/10 [==============================] - 1s 104ms/step - loss: 1.3946 - accuracy: 0.4872
Epoch 4/10
10/10 [==============================] - 1s 102ms/step - loss: 1.2356 - accuracy: 0.5480
Epoch 5/10
10/10 [==============================] - 1s 103ms/step - loss: 1.0542 - accuracy: 0.6384
Epoch 6/10
10/10 [==============================] - 1s 102ms/step - loss: 0.8851 - accuracy: 0.6864
Epoch 7/10
10/10 [==============================] - 1s 103ms/step - loss: 0.6787 - accuracy: 0.7632
Epoch 8/10
10/10 [==============================] - 1s 110ms/step - loss: 0.4937 - accuracy: 0.8288
Epoch 9/10
10/10 [==============================] - 1s 110ms/step - loss: 0.3694 - accuracy: 0.8872
Epoch 10/10
10/10 [==============================] - 1s 111ms/step - loss: 0.2502 - accuracy: 0.9160
250/250 [==============================] - 2s 8ms/step - loss: 2.6970 - accuracy: 0.4308
Test Accuracy (Batch 2): 43.08%
Epoch 1/10
10/10 [==============================] - 1s 101ms/step - loss: 2.0046 - accuracy: 0.3672
Epoch 2/10
10/10 [==============================] - 1s 101ms/step - loss: 1.5983 - accuracy: 0.4240
Epoch 3/10
10/10 [==============================] - 1s 99ms/step - loss: 1.3471 - accuracy: 0.4840
Epoch 4/10
10/10 [==============================] - 1s 100ms/step - loss: 1.1628 - accuracy: 0.5672
Epoch 5/10
10/10 [==============================] - 1s 100ms/step - loss: 1.0127 - accuracy: 0.6280
Epoch 6/10
10/10 [==============================] - 1s 101ms/step - loss: 0.8290 - accuracy: 0.7080
Epoch 7/10
10/10 [==============================] - 1s 106ms/step - loss: 0.6719 - accuracy: 0.7712
Epoch 8/10
10/10 [==============================] - 1s 105ms/step - loss: 0.5608 - accuracy: 0.8168
Epoch 9/10
10/10 [==============================] - 1s 104ms/step - loss: 0.4055 - accuracy: 0.8664
Epoch 10/10
10/10 [==============================] - 1s 103ms/step - loss: 0.3126 - accuracy: 0.8912
250/250 [==============================] - 2s 8ms/step - loss: 1.9748 - accuracy: 0.4834
Test Accuracy (Batch 3): 48.34%
Epoch 1/10
10/10 [==============================] - 1s 102ms/step - loss: 1.7909 - accuracy: 0.4392
Epoch 2/10
10/10 [==============================] - 1s 102ms/step - loss: 1.3232 - accuracy: 0.5248
Epoch 3/10
10/10 [==============================] - 1s 101ms/step - loss: 1.0408 - accuracy: 0.6528
Epoch 4/10
10/10 [==============================] - 1s 100ms/step - loss: 0.7913 - accuracy: 0.7240
Epoch 5/10
10/10 [==============================] - 1s 103ms/step - loss: 0.5942 - accuracy: 0.8000
Epoch 6/10
10/10 [==============================] - 1s 102ms/step - loss: 0.4147 - accuracy: 0.8680
Epoch 7/10
10/10 [==============================] - 1s 123ms/step - loss: 0.2660 - accuracy: 0.9136
Epoch 8/10
10/10 [==============================] - 1s 115ms/step - loss: 0.1936 - accuracy: 0.9440
Epoch 9/10
10/10 [==============================] - 1s 103ms/step - loss: 0.1329 - accuracy: 0.9576
Epoch 10/10
10/10 [==============================] - 1s 110ms/step - loss: 0.0996 - accuracy: 0.9664
250/250 [==============================] - 4s 15ms/step - loss: 2.4241 - accuracy: 0.4889
Test Accuracy (Batch 4): 48.89%
Batch-1: 42.32%
Batch-2: 43.08%
Batch-3: 48.34%
Batch-4: 48.89%

#### Batches 2

In [ ]:
import tensorflow as tf
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras import layers
# x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=42)
# Normalize the input data
x_train = X_train.astype('float32') / 255.0
x_test = X_test.astype('float32') / 255.0

# Convert the labels to one-hot encoding
num_classes = 10
# y_train = tf.keras.utils.to_categorical(y_train, num_classes)
# y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training set into 20 batches
num_batches = 2
x_train_batches = np.array_split(x_train, num_batches)
y_train_batches = np.array_split(y_train, num_batches)

# Initialize the list to store test accuracies
accuracies = []

# Define the model architecture
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(96, 96, 3)),
    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu'),
    layers.Dropout(0.25),
    Dense(num_classes, activation='softmax')
])


model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch
epochs = 10
for i in range(num_batches):
    x_train_batch = x_train_batches[i]
    y_train_batch = y_train_batches[i]
    model.fit(x_train_batch, y_train_batch, batch_size=128, epochs=epochs, verbose=1)

    # Evaluate the model on the test set
    test_loss, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy (Batch {}): {:.2f}%".format(i+1, test_accuracy*100))
    accuracies.append(test_accuracy)

# Print the batch accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Batch-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
20/20 [==============================] - 7s 164ms/step - loss: 2.4496 - accuracy: 0.1244
Epoch 2/10
20/20 [==============================] - 2s 100ms/step - loss: 2.0030 - accuracy: 0.2680
Epoch 3/10
20/20 [==============================] - 2s 108ms/step - loss: 1.7143 - accuracy: 0.3788
Epoch 4/10
20/20 [==============================] - 2s 100ms/step - loss: 1.4882 - accuracy: 0.4732
Epoch 5/10
20/20 [==============================] - 2s 101ms/step - loss: 1.3103 - accuracy: 0.5256
Epoch 6/10
20/20 [==============================] - 2s 102ms/step - loss: 1.1111 - accuracy: 0.6000
Epoch 7/10
20/20 [==============================] - 2s 103ms/step - loss: 0.9699 - accuracy: 0.6580
Epoch 8/10
20/20 [==============================] - 2s 103ms/step - loss: 0.7609 - accuracy: 0.7360
Epoch 9/10
20/20 [==============================] - 2s 110ms/step - loss: 0.6099 - accuracy: 0.7784
Epoch 10/10
20/20 [==============================] - 2s 103ms/step - loss: 0.4449 - accuracy: 0.8532
250/250 [==============================] - 2s 8ms/step - loss: 2.1915 - accuracy: 0.4633
Test Accuracy (Batch 1): 46.33%
Epoch 1/10
20/20 [==============================] - 2s 104ms/step - loss: 1.6983 - accuracy: 0.4136
Epoch 2/10
20/20 [==============================] - 2s 101ms/step - loss: 1.3290 - accuracy: 0.5124
Epoch 3/10
20/20 [==============================] - 2s 106ms/step - loss: 1.0870 - accuracy: 0.6052
Epoch 4/10
20/20 [==============================] - 2s 101ms/step - loss: 0.8320 - accuracy: 0.6956
Epoch 5/10
20/20 [==============================] - 2s 102ms/step - loss: 0.6363 - accuracy: 0.7772
Epoch 6/10
20/20 [==============================] - 2s 100ms/step - loss: 0.4423 - accuracy: 0.8480
Epoch 7/10
20/20 [==============================] - 2s 100ms/step - loss: 0.3181 - accuracy: 0.8936
Epoch 8/10
20/20 [==============================] - 2s 101ms/step - loss: 0.2208 - accuracy: 0.9312
Epoch 9/10
20/20 [==============================] - 2s 105ms/step - loss: 0.1673 - accuracy: 0.9496
Epoch 10/10
20/20 [==============================] - 2s 102ms/step - loss: 0.1435 - accuracy: 0.9516
250/250 [==============================] - 2s 8ms/step - loss: 2.1172 - accuracy: 0.5119
Test Accuracy (Batch 2): 51.19%
Batch-1: 46.33%
Batch-2: 51.19%

## C3

### MNIST-C

#### Batches 20

In [ ]:
# Split the data into training and test sets
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=42)

In [ ]:
import tensorflow as tf
x_train = x_train.reshape(-1, 28 * 28) / 255.0
x_train.shape

(56000, 784)

In [ ]:
x_train.shape

(56000, 784)

In [ ]:
x_test = x_test.reshape(-1, 28 * 28) / 255.0
x_test.shape

(14000, 784)

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.regularizers import Regularizer
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import KFold
from tensorflow.keras import backend as K
# Normalize the input data
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0
# x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=42)
# Convert the labels to one-hot encoding
num_classes = 10
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training set into 20 batches
num_batches = 20
x_train_batches = np.array_split(x_train, num_batches)
y_train_batches = np.array_split(y_train, num_batches)
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    f_accum = []
    for i in range(len(model.weights)):
        f_accum.append(np.zeros(K.int_shape(model.weights[i])))
    f_accum = np.array(f_accum)
    for _ in range(num_samples):
        idx = np.random.randint(0, x.shape[0])
        with tf.GradientTape() as tape:
            model_output = model(x[idx:idx+1])
        grads = tape.gradient(model_output, model.weights)
        for i in range(len(grads)):
            f_accum[i] += tf.square(grads[i])
    f_accum /= num_samples
    return f_accum

# Define the CrlB regularizer
class CrlBRegularizer(Regularizer):
    def __init__(self, fisher, prior_weights, lambda_=0.1):
        self.fisher = fisher
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i in range(len(self.fisher)):
            regularization += self.lambda_ * tf.reduce_sum(self.fisher[i] * tf.square(x - self.prior_weights[i]))
        return regularization



# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []


model = Sequential([
    Flatten(input_shape=(784,)),
    Dense(128, activation='relu'),
    Dense(num_classes, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
        # Train the model on each batch
epochs = 100
for i in range(num_batches):
    x_train_batch = x_train_batches[i]
    y_train_batch = y_train_batches[i]

    model.fit(x_train_batch, y_train_batch, batch_size=128, epochs=epochs, verbose=1)
    model.save_weights('FashionMNIST_A.h5')

# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_batch[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]

# Task B: Fashion MNIST with CrlB regularization
    model_CrlBB = Sequential([
        Dense(128, activation='relu', input_shape=(784,), kernel_regularizer=CrlBRegularizer(fisher_info[0], model.weights[0])),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBRegularizer(fisher_info[1], model.weights[1]))
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model_CrlBB = model_CrlBB
        model_CrlBB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model_CrlBB.load_weights('FashionMNIST_A.h5')
        model_CrlBB.fit( x_train_batch, y_train_batch, batch_size=128,epochs=epochs,  validation_data=(x_test, y_test))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test, y_test)[1]
    B_CrlB_acc = 100 * model_CrlBB.evaluate(x_test, y_test)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlB method Accuracy: %.2f%%" % B_CrlB_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/100
22/22 [==============================] - 1s 9ms/step - loss: 2.3024 - accuracy: 0.1068
Epoch 2/100
22/22 [==============================] - 0s 11ms/step - loss: 2.3011 - accuracy: 0.1129
Epoch 3/100
22/22 [==============================] - 0s 11ms/step - loss: 2.3001 - accuracy: 0.1129
Epoch 4/100
22/22 [==============================] - 0s 10ms/step - loss: 2.2995 - accuracy: 0.1129
Epoch 5/100
22/22 [==============================] - 0s 10ms/step - loss: 2.2991 - accuracy: 0.1129
Epoch 6/100
22/22 [==============================] - 0s 8ms/step - loss: 2.2989 - accuracy: 0.1186
Epoch 7/100
22/22 [==============================] - 0s 9ms/step - loss: 2.2986 - accuracy: 0.1132
Epoch 8/100
22/22 [==============================] - 0s 9ms/step - loss: 2.2986 - accuracy: 0.1086
Epoch 9/100
22/22 [==============================] - 0s 8ms/step - loss: 2.2986 - accuracy: 0.1132
Epoch 10/100
22/22 [==============================] - 0s 7ms/step - loss: 2.2985 - accuracy: 0.1132
Epoch 11/100
22/22 [==============================] - 0s 9ms/step - loss: 2.2984 - accuracy: 0.1096
Epoch 12/100
22/22 [==============================] - 0s 10ms/step - loss: 2.2984 - accuracy: 0.1107
Epoch 13/100
22/22 [==============================] - 0s 12ms/step - loss: 2.2986 - accuracy: 0.1136
Epoch 14/100
22/22 [==============================] - 0s 9ms/step - loss: 2.2985 - accuracy: 0.1132
Epoch 15/100
22/22 [==============================] - 0s 9ms/step - loss: 2.2985 - accuracy: 0.1075
Epoch 16/100
22/22 [==============================] - 0s 10ms/step - loss: 2.2984 - accuracy: 0.1150
Epoch 17/100
22/22 [==============================] - 0s 9ms/step - loss: 2.2984 - accuracy: 0.1075
Epoch 18/100
22/22 [==============================] - 0s 12ms/step - loss: 2.2985 - accuracy: 0.1132
Epoch 19/100
22/22 [==============================] - 0s 14ms/step - loss: 2.2984 - accuracy: 0.1132
Epoch 20/100
22/22 [==============================] - 0s 15ms/step - loss: 2.2984 - accuracy: 0.1079
Epoch 21/100
22/22 [==============================] - 0s 15ms/step - loss: 2.2984 - accuracy: 0.1082
Epoch 22/100
22/22 [==============================] - 0s 15ms/step - loss: 2.2984 - accuracy: 0.1164
Epoch 23/100
22/22 [==============================] - 0s 13ms/step - loss: 2.2984 - accuracy: 0.1182
Epoch 24/100
22/22 [==============================] - 0s 11ms/step - loss: 2.2984 - accuracy: 0.1132
Epoch 25/100
22/22 [==============================] - 0s 10ms/step - loss: 2.2984 - accuracy: 0.1075
Epoch 26/100
22/22 [==============================] - 0s 11ms/step - loss: 2.2983 - accuracy: 0.1175
Epoch 27/100
22/22 [==============================] - 0s 9ms/step - loss: 2.2984 - accuracy: 0.1132
Epoch 28/100
22/22 [==============================] - 0s 9ms/step - loss: 2.2984 - accuracy: 0.1154
Epoch 29/100
22/22 [==============================] - 0s 10ms/step - loss: 2.2983 - accuracy: 0.1132
Epoch 30/100
22/22 [==============================] - 0s 10ms/step - loss: 2.2983 - accuracy: 0.1093
Epoch 31/100
22/22 [==============================] - 0s 9ms/step - loss: 2.2983 - accuracy: 0.1136
Epoch 32/100
22/22 [==============================] - 0s 8ms/step - loss: 2.2983 - accuracy: 0.1132
Epoch 33/100
22/22 [==============================] - 0s 8ms/step - loss: 2.2983 - accuracy: 0.1132
Epoch 34/100
22/22 [==============================] - 0s 10ms/step - loss: 2.2983 - accuracy: 0.1079
Epoch 35/100
22/22 [==============================] - 0s 10ms/step - loss: 2.2983 - accuracy: 0.1157
Epoch 36/100
22/22 [==============================] - 0s 16ms/step - loss: 2.2983 - accuracy: 0.1132
Epoch 37/100
22/22 [==============================] - 0s 16ms/step - loss: 2.2983 - accuracy: 0.1132
Epoch 38/100
22/22 [==============================] - 0s 16ms/step - loss: 2.2982 - accuracy: 0.1168
Epoch 39/100
22/22 [==============================] - 0s 13ms/step - loss: 2.2983 - accuracy: 0.1125
Epoch 40/100
22/22 [==============================] - 0s 9ms/step - loss: 2.2982 - accuracy: 0.1150
Epoch 41/100
22/22 [==============================] - 0s 10ms/step - loss: 2.2982 - accuracy: 0.1129
Epoch 42/100
22/22 [==============================] - 0s 9ms/step - loss: 2.2981 - accuracy: 0.1129
Epoch 43/100
22/22 [==============================] - 0s 9ms/step - loss: 2.2982 - accuracy: 0.1129
Epoch 44/100
22/22 [==============================] - 0s 8ms/step - loss: 2.2982 - accuracy: 0.1121
Epoch 45/100
22/22 [==============================] - 0s 8ms/step - loss: 2.2982 - accuracy: 0.1425
Epoch 46/100
22/22 [==============================] - 0s 8ms/step - loss: 2.2981 - accuracy: 0.1132
Epoch 47/100
22/22 [==============================] - 0s 11ms/step - loss: 2.2981 - accuracy: 0.1132
Epoch 48/100
22/22 [==============================] - 0s 9ms/step - loss: 2.2980 - accuracy: 0.1132
Epoch 49/100
22/22 [==============================] - 0s 9ms/step - loss: 2.2981 - accuracy: 0.1132
Epoch 50/100
22/22 [==============================] - 0s 7ms/step - loss: 2.2981 - accuracy: 0.1129
Epoch 51/100
22/22 [==============================] - 0s 9ms/step - loss: 2.2980 - accuracy: 0.1443
Epoch 52/100
22/22 [==============================] - 0s 10ms/step - loss: 2.2980 - accuracy: 0.1650
Epoch 53/100
22/22 [==============================] - 0s 10ms/step - loss: 2.2980 - accuracy: 0.1132
Epoch 54/100
22/22 [==============================] - 0s 11ms/step - loss: 2.2980 - accuracy: 0.1354
Epoch 55/100
22/22 [==============================] - 0s 10ms/step - loss: 2.2980 - accuracy: 0.1132
Epoch 56/100
22/22 [==============================] - 0s 11ms/step - loss: 2.2980 - accuracy: 0.1136
Epoch 57/100
22/22 [==============================] - 0s 9ms/step - loss: 2.2979 - accuracy: 0.1325
Epoch 58/100
22/22 [==============================] - 0s 9ms/step - loss: 2.2979 - accuracy: 0.1132
Epoch 59/100
22/22 [==============================] - 0s 9ms/step - loss: 2.2980 - accuracy: 0.1132
Epoch 60/100
22/22 [==============================] - 0s 9ms/step - loss: 2.2979 - accuracy: 0.1379
Epoch 61/100
22/22 [==============================] - 0s 10ms/step - loss: 2.2979 - accuracy: 0.1132
Epoch 62/100
22/22 [==============================] - 0s 9ms/step - loss: 2.2979 - accuracy: 0.1132
Epoch 63/100
22/22 [==============================] - 0s 9ms/step - loss: 2.2979 - accuracy: 0.1164
Epoch 64/100
22/22 [==============================] - 0s 8ms/step - loss: 2.2978 - accuracy: 0.1157
Epoch 65/100
22/22 [==============================] - 0s 11ms/step - loss: 2.2979 - accuracy: 0.1086
Epoch 66/100
22/22 [==============================] - 0s 7ms/step - loss: 2.2977 - accuracy: 0.1143
Epoch 67/100
22/22 [==============================] - 0s 8ms/step - loss: 2.2977 - accuracy: 0.1186
Epoch 68/100
22/22 [==============================] - 0s 7ms/step - loss: 2.2977 - accuracy: 0.1136
Epoch 69/100
22/22 [==============================] - 0s 8ms/step - loss: 2.2977 - accuracy: 0.1132
Epoch 70/100
22/22 [==============================] - 0s 8ms/step - loss: 2.2976 - accuracy: 0.1132
Epoch 71/100
22/22 [==============================] - 0s 9ms/step - loss: 2.2976 - accuracy: 0.1132
Epoch 72/100
22/22 [==============================] - 0s 6ms/step - loss: 2.2977 - accuracy: 0.1136
Epoch 73/100
22/22 [==============================] - 0s 7ms/step - loss: 2.2976 - accuracy: 0.1136
Epoch 74/100
22/22 [==============================] - 0s 8ms/step - loss: 2.2975 - accuracy: 0.1136
Epoch 75/100
22/22 [==============================] - 0s 6ms/step - loss: 2.2975 - accuracy: 0.1207
Epoch 76/100
22/22 [==============================] - 0s 12ms/step - loss: 2.2974 - accuracy: 0.1168
Epoch 77/100
22/22 [==============================] - 0s 13ms/step - loss: 2.2975 - accuracy: 0.1104
Epoch 78/100
22/22 [==============================] - 0s 13ms/step - loss: 2.2974 - accuracy: 0.1400
Epoch 79/100
22/22 [==============================] - 0s 11ms/step - loss: 2.2973 - accuracy: 0.1232
Epoch 80/100
22/22 [==============================] - 0s 12ms/step - loss: 2.2974 - accuracy: 0.1157
Epoch 81/100
22/22 [==============================] - 0s 10ms/step - loss: 2.2973 - accuracy: 0.1139
Epoch 82/100
22/22 [==============================] - 0s 9ms/step - loss: 2.2973 - accuracy: 0.1221
Epoch 83/100
22/22 [==============================] - 0s 10ms/step - loss: 2.2972 - accuracy: 0.1393
Epoch 84/100
22/22 [==============================] - 0s 11ms/step - loss: 2.2972 - accuracy: 0.1250
Epoch 85/100
22/22 [==============================] - 0s 13ms/step - loss: 2.2972 - accuracy: 0.1500
Epoch 86/100
22/22 [==============================] - 0s 14ms/step - loss: 2.2972 - accuracy: 0.1132
Epoch 87/100
22/22 [==============================] - 0s 14ms/step - loss: 2.2971 - accuracy: 0.1132
Epoch 88/100
22/22 [==============================] - 0s 14ms/step - loss: 2.2970 - accuracy: 0.1132
Epoch 89/100
22/22 [==============================] - 0s 10ms/step - loss: 2.2971 - accuracy: 0.1207
Epoch 90/100
22/22 [==============================] - 0s 9ms/step - loss: 2.2970 - accuracy: 0.1632
Epoch 91/100
22/22 [==============================] - 0s 10ms/step - loss: 2.2970 - accuracy: 0.1196
Epoch 92/100
22/22 [==============================] - 0s 9ms/step - loss: 2.2968 - accuracy: 0.1211
Epoch 93/100
22/22 [==============================] - 0s 8ms/step - loss: 2.2969 - accuracy: 0.1386
Epoch 94/100
22/22 [==============================] - 0s 7ms/step - loss: 2.2968 - accuracy: 0.1379
Epoch 95/100
22/22 [==============================] - 0s 6ms/step - loss: 2.2968 - accuracy: 0.1193
Epoch 96/100
22/22 [==============================] - 0s 9ms/step - loss: 2.2966 - accuracy: 0.1132
Epoch 97/100
22/22 [==============================] - 0s 9ms/step - loss: 2.2967 - accuracy: 0.1132
Epoch 98/100
22/22 [==============================] - 0s 10ms/step - loss: 2.2966 - accuracy: 0.1300
Epoch 99/100
22/22 [==============================] - 0s 10ms/step - loss: 2.2965 - accuracy: 0.1511
Epoch 100/100
22/22 [==============================] - 0s 10ms/step - loss: 2.2964 - accuracy: 0.1568
Epoch 1/100
22/22 [==============================] - 209s 2s/step - loss: 2.2968 - accuracy: 0.1161 - val_loss: 2.3032 - val_accuracy: 0.1122
Epoch 2/100
22/22 [==============================] - 12s 587ms/step - loss: 2.2965 - accuracy: 0.1132 - val_loss: 2.3031 - val_accuracy: 0.1122
Epoch 3/100
22/22 [==============================] - 7s 351ms/step - loss: 2.2964 - accuracy: 0.1179 - val_loss: 2.3026 - val_accuracy: 0.1039
Epoch 4/100
22/22 [==============================] - 7s 309ms/step - loss: 2.2962 - accuracy: 0.1568 - val_loss: 2.3027 - val_accuracy: 0.1122
Epoch 5/100
22/22 [==============================] - 12s 588ms/step - loss: 2.2964 - accuracy: 0.1179 - val_loss: 2.3028 - val_accuracy: 0.1122
Epoch 6/100
22/22 [==============================] - 8s 364ms/step - loss: 2.2962 - accuracy: 0.1132 - val_loss: 2.3024 - val_accuracy: 0.1122
Epoch 7/100
22/22 [==============================] - 8s 356ms/step - loss: 2.2961 - accuracy: 0.1839 - val_loss: 2.3021 - val_accuracy: 0.1914
Epoch 8/100
22/22 [==============================] - 13s 594ms/step - loss: 2.2961 - accuracy: 0.2064 - val_loss: 2.3027 - val_accuracy: 0.1807
Epoch 9/100
22/22 [==============================] - 7s 328ms/step - loss: 2.2960 - accuracy: 0.1189 - val_loss: 2.3026 - val_accuracy: 0.1122
Epoch 10/100
22/22 [==============================] - 7s 338ms/step - loss: 2.2959 - accuracy: 0.1443 - val_loss: 2.3021 - val_accuracy: 0.1039
Epoch 11/100
22/22 [==============================] - 7s 327ms/step - loss: 2.2959 - accuracy: 0.1843 - val_loss: 2.3021 - val_accuracy: 0.2029
Epoch 12/100
22/22 [==============================] - 7s 338ms/step - loss: 2.2959 - accuracy: 0.1561 - val_loss: 2.3017 - val_accuracy: 0.1209
Epoch 13/100
22/22 [==============================] - 8s 363ms/step - loss: 2.2957 - accuracy: 0.1139 - val_loss: 2.3022 - val_accuracy: 0.1122
Epoch 14/100
22/22 [==============================] - 7s 352ms/step - loss: 2.2956 - accuracy: 0.1136 - val_loss: 2.3021 - val_accuracy: 0.1164
Epoch 15/100
22/22 [==============================] - 7s 334ms/step - loss: 2.2956 - accuracy: 0.1146 - val_loss: 2.3020 - val_accuracy: 0.1122
Epoch 16/100
22/22 [==============================] - 12s 585ms/step - loss: 2.2955 - accuracy: 0.1239 - val_loss: 2.3020 - val_accuracy: 0.1039
Epoch 17/100
22/22 [==============================] - 13s 593ms/step - loss: 2.2954 - accuracy: 0.1454 - val_loss: 2.3019 - val_accuracy: 0.2123
Epoch 18/100
22/22 [==============================] - 7s 349ms/step - loss: 2.2953 - accuracy: 0.1661 - val_loss: 2.3015 - val_accuracy: 0.1124
Epoch 19/100
22/22 [==============================] - 7s 349ms/step - loss: 2.2953 - accuracy: 0.1132 - val_loss: 2.3015 - val_accuracy: 0.1122
Epoch 20/100
22/22 [==============================] - 13s 593ms/step - loss: 2.2952 - accuracy: 0.1846 - val_loss: 2.3016 - val_accuracy: 0.2121
Epoch 21/100
22/22 [==============================] - 7s 348ms/step - loss: 2.2951 - accuracy: 0.1693 - val_loss: 2.3015 - val_accuracy: 0.1871
Epoch 22/100
22/22 [==============================] - 8s 357ms/step - loss: 2.2949 - accuracy: 0.1836 - val_loss: 2.3014 - val_accuracy: 0.1184
Epoch 23/100
22/22 [==============================] - 7s 343ms/step - loss: 2.2950 - accuracy: 0.1136 - val_loss: 2.3012 - val_accuracy: 0.1122
Epoch 24/100
22/22 [==============================] - 7s 330ms/step - loss: 2.2949 - accuracy: 0.1289 - val_loss: 2.3011 - val_accuracy: 0.1341
Epoch 25/100
22/22 [==============================] - 8s 373ms/step - loss: 2.2949 - accuracy: 0.1754 - val_loss: 2.3008 - val_accuracy: 0.1842
Epoch 26/100
22/22 [==============================] - 7s 348ms/step - loss: 2.2947 - accuracy: 0.1511 - val_loss: 2.3014 - val_accuracy: 0.1122
Epoch 27/100
22/22 [==============================] - 8s 357ms/step - loss: 2.2947 - accuracy: 0.1550 - val_loss: 2.3010 - val_accuracy: 0.2110
Epoch 28/100
22/22 [==============================] - 7s 345ms/step - loss: 2.2948 - accuracy: 0.1504 - val_loss: 2.3008 - val_accuracy: 0.1125
Epoch 29/100
22/22 [==============================] - 6s 294ms/step - loss: 2.2948 - accuracy: 0.1236 - val_loss: 2.3006 - val_accuracy: 0.1039
Epoch 30/100
22/22 [==============================] - 7s 344ms/step - loss: 2.2945 - accuracy: 0.1121 - val_loss: 2.3012 - val_accuracy: 0.1122
Epoch 31/100
22/22 [==============================] - 6s 294ms/step - loss: 2.2943 - accuracy: 0.1664 - val_loss: 2.3004 - val_accuracy: 0.1761
Epoch 32/100
22/22 [==============================] - 7s 342ms/step - loss: 2.2940 - accuracy: 0.1471 - val_loss: 2.3003 - val_accuracy: 0.1039
Epoch 33/100
22/22 [==============================] - 7s 341ms/step - loss: 2.2940 - accuracy: 0.1736 - val_loss: 2.3002 - val_accuracy: 0.1977
Epoch 34/100
22/22 [==============================] - 7s 329ms/step - loss: 2.2939 - accuracy: 0.2164 - val_loss: 2.3004 - val_accuracy: 0.2119
Epoch 35/100
22/22 [==============================] - 7s 329ms/step - loss: 2.2937 - accuracy: 0.1850 - val_loss: 2.3000 - val_accuracy: 0.1044
Epoch 36/100
22/22 [==============================] - 7s 319ms/step - loss: 2.2936 - accuracy: 0.1686 - val_loss: 2.2997 - val_accuracy: 0.2117
Epoch 37/100
22/22 [==============================] - 7s 339ms/step - loss: 2.2935 - accuracy: 0.1357 - val_loss: 2.2997 - val_accuracy: 0.1122
Epoch 38/100
22/22 [==============================] - 8s 362ms/step - loss: 2.2933 - accuracy: 0.1193 - val_loss: 2.2999 - val_accuracy: 0.1282
Epoch 39/100
22/22 [==============================] - 7s 346ms/step - loss: 2.2933 - accuracy: 0.1711 - val_loss: 2.2995 - val_accuracy: 0.2079
Epoch 40/100
22/22 [==============================] - 7s 312ms/step - loss: 2.2933 - accuracy: 0.1496 - val_loss: 2.2995 - val_accuracy: 0.1331
Epoch 41/100
22/22 [==============================] - 13s 597ms/step - loss: 2.2931 - accuracy: 0.1593 - val_loss: 2.2989 - val_accuracy: 0.2080
Epoch 42/100
22/22 [==============================] - 12s 588ms/step - loss: 2.2929 - accuracy: 0.1854 - val_loss: 2.2998 - val_accuracy: 0.2014
Epoch 43/100
22/22 [==============================] - 8s 355ms/step - loss: 2.2928 - accuracy: 0.1779 - val_loss: 2.2990 - val_accuracy: 0.1127
Epoch 44/100
22/22 [==============================] - 7s 346ms/step - loss: 2.2925 - accuracy: 0.1146 - val_loss: 2.2988 - val_accuracy: 0.1416
Epoch 45/100
22/22 [==============================] - 7s 341ms/step - loss: 2.2925 - accuracy: 0.1629 - val_loss: 2.2991 - val_accuracy: 0.1044
Epoch 46/100
22/22 [==============================] - 7s 336ms/step - loss: 2.2923 - accuracy: 0.1382 - val_loss: 2.2987 - val_accuracy: 0.1241
Epoch 47/100
22/22 [==============================] - 8s 372ms/step - loss: 2.2924 - accuracy: 0.1529 - val_loss: 2.2987 - val_accuracy: 0.2051
Epoch 48/100
22/22 [==============================] - 7s 336ms/step - loss: 2.2921 - accuracy: 0.1932 - val_loss: 2.2977 - val_accuracy: 0.1756
Epoch 49/100
22/22 [==============================] - 8s 368ms/step - loss: 2.2917 - accuracy: 0.1389 - val_loss: 2.2983 - val_accuracy: 0.1189
Epoch 50/100
22/22 [==============================] - 7s 341ms/step - loss: 2.2919 - accuracy: 0.1318 - val_loss: 2.2978 - val_accuracy: 0.1522
Epoch 51/100
22/22 [==============================] - 8s 353ms/step - loss: 2.2916 - accuracy: 0.1614 - val_loss: 2.2975 - val_accuracy: 0.2058
Epoch 52/100
22/22 [==============================] - 7s 339ms/step - loss: 2.2918 - accuracy: 0.2139 - val_loss: 2.2983 - val_accuracy: 0.2015
Epoch 53/100
22/22 [==============================] - 7s 344ms/step - loss: 2.2911 - accuracy: 0.1886 - val_loss: 2.2967 - val_accuracy: 0.1651
Epoch 54/100
22/22 [==============================] - 8s 368ms/step - loss: 2.2910 - accuracy: 0.1668 - val_loss: 2.2973 - val_accuracy: 0.1931
Epoch 55/100
22/22 [==============================] - 7s 308ms/step - loss: 2.2909 - accuracy: 0.1400 - val_loss: 2.2970 - val_accuracy: 0.1628
Epoch 56/100
22/22 [==============================] - 7s 348ms/step - loss: 2.2906 - accuracy: 0.1721 - val_loss: 2.2972 - val_accuracy: 0.1947
Epoch 57/100
22/22 [==============================] - 7s 330ms/step - loss: 2.2905 - accuracy: 0.1368 - val_loss: 2.2968 - val_accuracy: 0.1126
Epoch 58/100
22/22 [==============================] - 8s 360ms/step - loss: 2.2903 - accuracy: 0.1714 - val_loss: 2.2965 - val_accuracy: 0.2100
Epoch 59/100
22/22 [==============================] - 13s 590ms/step - loss: 2.2902 - accuracy: 0.1989 - val_loss: 2.2959 - val_accuracy: 0.2207
Epoch 60/100
22/22 [==============================] - 7s 343ms/step - loss: 2.2897 - accuracy: 0.1900 - val_loss: 2.2958 - val_accuracy: 0.1294
Epoch 61/100
22/22 [==============================] - 7s 341ms/step - loss: 2.2898 - accuracy: 0.1371 - val_loss: 2.2956 - val_accuracy: 0.1581
Epoch 62/100
22/22 [==============================] - 7s 348ms/step - loss: 2.2895 - accuracy: 0.2004 - val_loss: 2.2961 - val_accuracy: 0.1955
Epoch 63/100
22/22 [==============================] - 7s 343ms/step - loss: 2.2893 - accuracy: 0.1575 - val_loss: 2.2956 - val_accuracy: 0.1883
Epoch 64/100
22/22 [==============================] - 7s 342ms/step - loss: 2.2891 - accuracy: 0.1804 - val_loss: 2.2949 - val_accuracy: 0.1946
Epoch 65/100
22/22 [==============================] - 7s 348ms/step - loss: 2.2891 - accuracy: 0.1496 - val_loss: 2.2949 - val_accuracy: 0.2096
Epoch 66/100
22/22 [==============================] - 8s 375ms/step - loss: 2.2886 - accuracy: 0.2014 - val_loss: 2.2947 - val_accuracy: 0.2036
Epoch 67/100
22/22 [==============================] - 7s 325ms/step - loss: 2.2886 - accuracy: 0.1782 - val_loss: 2.2948 - val_accuracy: 0.1876
Epoch 68/100
22/22 [==============================] - 7s 347ms/step - loss: 2.2881 - accuracy: 0.1804 - val_loss: 2.2940 - val_accuracy: 0.1551
Epoch 69/100
22/22 [==============================] - 12s 580ms/step - loss: 2.2879 - accuracy: 0.1925 - val_loss: 2.2940 - val_accuracy: 0.1670
Epoch 70/100

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar100
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam

# Load the CIFAR-100 dataset
(x_train, y_train), (x_test, y_test) = cifar100.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 0.1  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = x_train + tf.random.normal(shape=x_train.shape, mean=0.0, stddev=corruption_level, dtype=tf.float32)
corrupted_data = tf.clip_by_value(corrupted_data, 0.0, 1.0)

# Convert the labels to one-hot encoding
num_classes = 100
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 10 batches
n_batches = 20
batch_size = x_train.shape[0] // n_batches

# Define the model architecture
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)))
model.add(Conv2D(32, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch separately
for i in range(n_batches):
    start_index = i * batch_size
    end_index = (i + 1) * batch_size
    x_batch = corrupted_data[start_index:end_index]
    y_batch = y_train[start_index:end_index]

    # Train the model on the current batch
    model.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)

#

---

#### Batches 10

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.regularizers import Regularizer
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import KFold
from tensorflow.keras import backend as K
# Normalize the input data
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0
# x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=42)
# Convert the labels to one-hot encoding
num_classes = 10
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training set into 20 batches
num_batches = 10
x_train_batches = np.array_split(x_train, num_batches)
y_train_batches = np.array_split(y_train, num_batches)
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    f_accum = []
    for i in range(len(model.weights)):
        f_accum.append(np.zeros(K.int_shape(model.weights[i])))
    f_accum = np.array(f_accum)
    for _ in range(num_samples):
        idx = np.random.randint(0, x.shape[0])
        with tf.GradientTape() as tape:
            model_output = model(x[idx:idx+1])
        grads = tape.gradient(model_output, model.weights)
        for i in range(len(grads)):
            f_accum[i] += tf.square(grads[i])
    f_accum /= num_samples
    return f_accum

# Define the CrlB regularizer
class CrlBRegularizer(Regularizer):
    def __init__(self, fisher, prior_weights, lambda_=0.1):
        self.fisher = fisher
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i in range(len(self.fisher)):
            regularization += self.lambda_ * tf.reduce_sum(self.fisher[i] * tf.square(x - self.prior_weights[i]))
        return regularization



# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []


model = Sequential([
    Flatten(input_shape=(784,)),
    Dense(128, activation='relu'),
    Dense(num_classes, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
        # Train the model on each batch
epochs = 100
for i in range(num_batches):
    x_train_batch = x_train_batches[i]
    y_train_batch = y_train_batches[i]

    model.fit(x_train_batch, y_train_batch, batch_size=128, epochs=epochs, verbose=1)
    model.save_weights('FashionMNIST_A.h5')

# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_batch[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]

# Task B: Fashion MNIST with CrlB regularization
    model_CrlBB = Sequential([
        Dense(128, activation='relu', input_shape=(784,), kernel_regularizer=CrlBRegularizer(fisher_info[0], model.weights[0])),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBRegularizer(fisher_info[1], model.weights[1]))
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model_CrlBB = model_CrlBB
        model_CrlBB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model_CrlBB.load_weights('FashionMNIST_A.h5')
        model_CrlBB.fit( x_train_batch, y_train_batch, batch_size=128,epochs=epochs,  validation_data=(x_test, y_test))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test, y_test)[1]
    B_CrlB_acc = 100 * model_CrlBB.evaluate(x_test, y_test)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlB method Accuracy: %.2f%%" % B_CrlB_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/100
44/44 [==============================] - 6s 3ms/step - loss: 2.3021 - accuracy: 0.1070
Epoch 2/100
44/44 [==============================] - 0s 3ms/step - loss: 2.3011 - accuracy: 0.1146
Epoch 3/100
44/44 [==============================] - 0s 3ms/step - loss: 2.3009 - accuracy: 0.1146
Epoch 4/100
44/44 [==============================] - 0s 3ms/step - loss: 2.3006 - accuracy: 0.1146
Epoch 5/100
44/44 [==============================] - 0s 4ms/step - loss: 2.3007 - accuracy: 0.1146
Epoch 6/100
44/44 [==============================] - 0s 4ms/step - loss: 2.3006 - accuracy: 0.1146
Epoch 7/100
44/44 [==============================] - 0s 4ms/step - loss: 2.3005 - accuracy: 0.1146
Epoch 8/100
44/44 [==============================] - 0s 3ms/step - loss: 2.3006 - accuracy: 0.1146
Epoch 9/100
44/44 [==============================] - 0s 3ms/step - loss: 2.3005 - accuracy: 0.1146
Epoch 10/100
44/44 [==============================] - 0s 3ms/step - loss: 2.3005 - accuracy: 0.1146
Epoch 11/100
44/44 [==============================] - 0s 3ms/step - loss: 2.3004 - accuracy: 0.1146
Epoch 12/100
44/44 [==============================] - 0s 3ms/step - loss: 2.3004 - accuracy: 0.1146
Epoch 13/100
44/44 [==============================] - 0s 3ms/step - loss: 2.3005 - accuracy: 0.1146
Epoch 14/100
44/44 [==============================] - 0s 3ms/step - loss: 2.3004 - accuracy: 0.1146
Epoch 15/100
44/44 [==============================] - 0s 3ms/step - loss: 2.3004 - accuracy: 0.1146
Epoch 16/100
44/44 [==============================] - 0s 3ms/step - loss: 2.3004 - accuracy: 0.1146
Epoch 17/100
44/44 [==============================] - 0s 3ms/step - loss: 2.3003 - accuracy: 0.1146
Epoch 18/100
44/44 [==============================] - 0s 3ms/step - loss: 2.3003 - accuracy: 0.1146
Epoch 19/100
44/44 [==============================] - 0s 3ms/step - loss: 2.3003 - accuracy: 0.1146
Epoch 20/100
44/44 [==============================] - 0s 3ms/step - loss: 2.3002 - accuracy: 0.1146
Epoch 21/100
44/44 [==============================] - 0s 3ms/step - loss: 2.3002 - accuracy: 0.1146
Epoch 22/100
44/44 [==============================] - 0s 3ms/step - loss: 2.3002 - accuracy: 0.1146
Epoch 23/100
44/44 [==============================] - 0s 3ms/step - loss: 2.3001 - accuracy: 0.1146
Epoch 24/100
44/44 [==============================] - 0s 3ms/step - loss: 2.3002 - accuracy: 0.1146
Epoch 25/100
44/44 [==============================] - 0s 3ms/step - loss: 2.3001 - accuracy: 0.1146
Epoch 26/100
44/44 [==============================] - 0s 3ms/step - loss: 2.3001 - accuracy: 0.1146
Epoch 27/100
44/44 [==============================] - 0s 3ms/step - loss: 2.3000 - accuracy: 0.1146
Epoch 28/100
44/44 [==============================] - 0s 3ms/step - loss: 2.3000 - accuracy: 0.1146
Epoch 29/100
44/44 [==============================] - 0s 3ms/step - loss: 2.3000 - accuracy: 0.1146
Epoch 30/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2999 - accuracy: 0.1146
Epoch 31/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2999 - accuracy: 0.1146
Epoch 32/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2999 - accuracy: 0.1146
Epoch 33/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2998 - accuracy: 0.1146
Epoch 34/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2997 - accuracy: 0.1146
Epoch 35/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2996 - accuracy: 0.1146
Epoch 36/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2996 - accuracy: 0.1146
Epoch 37/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2996 - accuracy: 0.1146
Epoch 38/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2996 - accuracy: 0.1146
Epoch 39/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2995 - accuracy: 0.1146
Epoch 40/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2993 - accuracy: 0.1146
Epoch 41/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2993 - accuracy: 0.1146
Epoch 42/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2993 - accuracy: 0.1146
Epoch 43/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2992 - accuracy: 0.1146
Epoch 44/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2991 - accuracy: 0.1146
Epoch 45/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2991 - accuracy: 0.1146
Epoch 46/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2990 - accuracy: 0.1146
Epoch 47/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2988 - accuracy: 0.1146
Epoch 48/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2988 - accuracy: 0.1146
Epoch 49/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2986 - accuracy: 0.1146
Epoch 50/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2986 - accuracy: 0.1146
Epoch 51/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2983 - accuracy: 0.1146
Epoch 52/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2982 - accuracy: 0.1146
Epoch 53/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2981 - accuracy: 0.1146
Epoch 54/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2979 - accuracy: 0.1146
Epoch 55/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2978 - accuracy: 0.1180
Epoch 56/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2976 - accuracy: 0.1146
Epoch 57/100
44/44 [==============================] - 0s 5ms/step - loss: 2.2975 - accuracy: 0.1146
Epoch 58/100
44/44 [==============================] - 0s 4ms/step - loss: 2.2973 - accuracy: 0.1146
Epoch 59/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2970 - accuracy: 0.1146
Epoch 60/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2969 - accuracy: 0.1146
Epoch 61/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2966 - accuracy: 0.1146
Epoch 62/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2965 - accuracy: 0.1146
Epoch 63/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2962 - accuracy: 0.1146
Epoch 64/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2959 - accuracy: 0.1146
Epoch 65/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2958 - accuracy: 0.1363
Epoch 66/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2953 - accuracy: 0.1146
Epoch 67/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2951 - accuracy: 0.1146
Epoch 68/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2948 - accuracy: 0.1146
Epoch 69/100
44/44 [==============================] - 0s 4ms/step - loss: 2.2944 - accuracy: 0.1146
Epoch 70/100
44/44 [==============================] - 0s 3ms/step - loss: 2.2942 - accuracy: 0.1146
Epoch 71/100
44/44 [==============================] - 0s 4ms/step - loss: 2.2937 - accuracy: 0.1146
Epoch 72/100
44/44 [==============================] - 0s 5ms/step - loss: 2.2935 - accuracy: 0.1148
Epoch 73/100
44/44 [==============================] - 0s 4ms/step - loss: 2.2931 - accuracy: 0.1146
Epoch 74/100
44/44 [==============================] - 0s 5ms/step - loss: 2.2927 - accuracy: 0.1411
Epoch 75/100
44/44 [==============================] - 0s 5ms/step - loss: 2.2922 - accuracy: 0.1146
Epoch 76/100
44/44 [==============================] - 0s 4ms/step - loss: 2.2918 - accuracy: 0.1146
Epoch 77/100
44/44 [==============================] - 0s 7ms/step - loss: 2.2914 - accuracy: 0.1146
Epoch 78/100
44/44 [==============================] - 0s 8ms/step - loss: 2.2908 - accuracy: 0.1163
Epoch 79/100
44/44 [==============================] - 0s 7ms/step - loss: 2.2905 - accuracy: 0.1155
Epoch 80/100
44/44 [==============================] - 0s 6ms/step - loss: 2.2899 - accuracy: 0.1280
Epoch 81/100
44/44 [==============================] - 0s 9ms/step - loss: 2.2894 - accuracy: 0.1146
Epoch 82/100
44/44 [==============================] - 0s 7ms/step - loss: 2.2886 - accuracy: 0.1146
Epoch 83/100
44/44 [==============================] - 0s 6ms/step - loss: 2.2880 - accuracy: 0.1352
Epoch 84/100
44/44 [==============================] - 0s 5ms/step - loss: 2.2876 - accuracy: 0.1155
Epoch 85/100
44/44 [==============================] - 0s 5ms/step - loss: 2.2870 - accuracy: 0.1486
Epoch 86/100
44/44 [==============================] - 0s 5ms/step - loss: 2.2860 - accuracy: 0.1279
Epoch 87/100
44/44 [==============================] - 0s 5ms/step - loss: 2.2853 - accuracy: 0.1291
Epoch 88/100
44/44 [==============================] - 0s 5ms/step - loss: 2.2847 - accuracy: 0.1230
Epoch 89/100
44/44 [==============================] - 0s 5ms/step - loss: 2.2840 - accuracy: 0.1316
Epoch 90/100
44/44 [==============================] - 0s 6ms/step - loss: 2.2834 - accuracy: 0.1284
Epoch 91/100
44/44 [==============================] - 0s 5ms/step - loss: 2.2821 - accuracy: 0.1250
Epoch 92/100
44/44 [==============================] - 0s 5ms/step - loss: 2.2814 - accuracy: 0.1314
Epoch 93/100
44/44 [==============================] - 0s 6ms/step - loss: 2.2805 - accuracy: 0.1187
Epoch 94/100
44/44 [==============================] - 0s 5ms/step - loss: 2.2798 - accuracy: 0.1418
Epoch 95/100
44/44 [==============================] - 0s 6ms/step - loss: 2.2788 - accuracy: 0.1375
Epoch 96/100
44/44 [==============================] - 0s 5ms/step - loss: 2.2779 - accuracy: 0.1534
Epoch 97/100
44/44 [==============================] - 0s 4ms/step - loss: 2.2770 - accuracy: 0.1386
Epoch 98/100
44/44 [==============================] - 0s 5ms/step - loss: 2.2758 - accuracy: 0.1252
Epoch 99/100
44/44 [==============================] - 0s 5ms/step - loss: 2.2750 - accuracy: 0.1755
Epoch 100/100
44/44 [==============================] - 0s 4ms/step - loss: 2.2734 - accuracy: 0.1357
Epoch 1/100
44/44 [==============================] - 101s 517ms/step - loss: 2.2742 - accuracy: 0.1612 - val_loss: 2.2739 - val_accuracy: 0.1554
Epoch 2/100
44/44 [==============================] - 1s 24ms/step - loss: 2.2718 - accuracy: 0.1298 - val_loss: 2.2729 - val_accuracy: 0.2043
Epoch 3/100
44/44 [==============================] - 1s 23ms/step - loss: 2.2710 - accuracy: 0.1673 - val_loss: 2.2718 - val_accuracy: 0.1536
Epoch 4/100
44/44 [==============================] - 1s 24ms/step - loss: 2.2698 - accuracy: 0.1787 - val_loss: 2.2709 - val_accuracy: 0.2389
Epoch 5/100
44/44 [==============================] - 1s 22ms/step - loss: 2.2688 - accuracy: 0.1670 - val_loss: 2.2702 - val_accuracy: 0.1383
Epoch 6/100
44/44 [==============================] - 1s 22ms/step - loss: 2.2673 - accuracy: 0.2057 - val_loss: 2.2698 - val_accuracy: 0.1198
Epoch 7/100
44/44 [==============================] - 1s 21ms/step - loss: 2.2661 - accuracy: 0.1614 - val_loss: 2.2680 - val_accuracy: 0.2724
Epoch 8/100
44/44 [==============================] - 1s 21ms/step - loss: 2.2651 - accuracy: 0.1941 - val_loss: 2.2663 - val_accuracy: 0.1691
Epoch 9/100
44/44 [==============================] - 1s 22ms/step - loss: 2.2643 - accuracy: 0.1964 - val_loss: 2.2654 - val_accuracy: 0.1625
Epoch 10/100
44/44 [==============================] - 1s 22ms/step - loss: 2.2635 - accuracy: 0.1554 - val_loss: 2.2647 - val_accuracy: 0.1372
Epoch 11/100
44/44 [==============================] - 1s 30ms/step - loss: 2.2615 - accuracy: 0.1998 - val_loss: 2.2630 - val_accuracy: 0.1885
Epoch 12/100
44/44 [==============================] - 1s 30ms/step - loss: 2.2603 - accuracy: 0.1795 - val_loss: 2.2617 - val_accuracy: 0.2290
Epoch 13/100
44/44 [==============================] - 1s 22ms/step - loss: 2.2586 - accuracy: 0.2202 - val_loss: 2.2601 - val_accuracy: 0.1884
Epoch 14/100
44/44 [==============================] - 1s 22ms/step - loss: 2.2574 - accuracy: 0.1852 - val_loss: 2.2601 - val_accuracy: 0.2194
Epoch 15/100
44/44 [==============================] - 1s 23ms/step - loss: 2.2566 - accuracy: 0.2114 - val_loss: 2.2575 - val_accuracy: 0.1789
Epoch 16/100
44/44 [==============================] - 1s 22ms/step - loss: 2.2546 - accuracy: 0.1766 - val_loss: 2.2592 - val_accuracy: 0.2259
Epoch 17/100
44/44 [==============================] - 1s 22ms/step - loss: 2.2535 - accuracy: 0.2138 - val_loss: 2.2550 - val_accuracy: 0.2086
Epoch 18/100
44/44 [==============================] - 1s 22ms/step - loss: 2.2521 - accuracy: 0.2030 - val_loss: 2.2541 - val_accuracy: 0.1475
Epoch 19/100
44/44 [==============================] - 1s 21ms/step - loss: 2.2499 - accuracy: 0.2188 - val_loss: 2.2518 - val_accuracy: 0.2357
Epoch 20/100
44/44 [==============================] - 1s 22ms/step - loss: 2.2493 - accuracy: 0.2245 - val_loss: 2.2519 - val_accuracy: 0.1734
Epoch 21/100
44/44 [==============================] - 1s 23ms/step - loss: 2.2472 - accuracy: 0.2177 - val_loss: 2.2486 - val_accuracy: 0.2494
Epoch 22/100
44/44 [==============================] - 1s 22ms/step - loss: 2.2459 - accuracy: 0.2132 - val_loss: 2.2478 - val_accuracy: 0.2344
Epoch 23/100
44/44 [==============================] - 2s 39ms/step - loss: 2.2441 - accuracy: 0.2329 - val_loss: 2.2454 - val_accuracy: 0.2179
Epoch 24/100
44/44 [==============================] - 1s 27ms/step - loss: 2.2426 - accuracy: 0.2121 - val_loss: 2.2460 - val_accuracy: 0.1930
Epoch 25/100
44/44 [==============================] - 1s 23ms/step - loss: 2.2412 - accuracy: 0.2396 - val_loss: 2.2423 - val_accuracy: 0.2249
Epoch 26/100
44/44 [==============================] - 2s 39ms/step - loss: 2.2392 - accuracy: 0.2105 - val_loss: 2.2429 - val_accuracy: 0.2892
Epoch 27/100
44/44 [==============================] - 1s 23ms/step - loss: 2.2377 - accuracy: 0.2257 - val_loss: 2.2413 - val_accuracy: 0.2481
Epoch 28/100
44/44 [==============================] - 1s 23ms/step - loss: 2.2359 - accuracy: 0.2463 - val_loss: 2.2372 - val_accuracy: 0.2821
Epoch 29/100
44/44 [==============================] - 1s 22ms/step - loss: 2.2341 - accuracy: 0.2143 - val_loss: 2.2362 - val_accuracy: 0.2975
Epoch 30/100
44/44 [==============================] - 1s 23ms/step - loss: 2.2326 - accuracy: 0.2596 - val_loss: 2.2370 - val_accuracy: 0.1829
Epoch 31/100
44/44 [==============================] - 1s 22ms/step - loss: 2.2304 - accuracy: 0.2157 - val_loss: 2.2319 - val_accuracy: 0.2671
Epoch 32/100
44/44 [==============================] - 1s 22ms/step - loss: 2.2280 - accuracy: 0.2516 - val_loss: 2.2306 - val_accuracy: 0.2779
Epoch 33/100
44/44 [==============================] - 1s 22ms/step - loss: 2.2270 - accuracy: 0.2370 - val_loss: 2.2295 - val_accuracy: 0.2921
Epoch 34/100
44/44 [==============================] - 1s 32ms/step - loss: 2.2256 - accuracy: 0.2395 - val_loss: 2.2266 - val_accuracy: 0.2234
Epoch 35/100
44/44 [==============================] - 1s 30ms/step - loss: 2.2225 - accuracy: 0.2252 - val_loss: 2.2261 - val_accuracy: 0.2906
Epoch 36/100
44/44 [==============================] - 1s 23ms/step - loss: 2.2207 - accuracy: 0.2652 - val_loss: 2.2226 - val_accuracy: 0.2629
Epoch 37/100
44/44 [==============================] - 1s 22ms/step - loss: 2.2190 - accuracy: 0.2493 - val_loss: 2.2207 - val_accuracy: 0.2569
Epoch 38/100
44/44 [==============================] - 1s 23ms/step - loss: 2.2174 - accuracy: 0.2541 - val_loss: 2.2185 - val_accuracy: 0.2135
Epoch 39/100
44/44 [==============================] - 1s 22ms/step - loss: 2.2148 - accuracy: 0.2520 - val_loss: 2.2166 - val_accuracy: 0.2655
Epoch 40/100
44/44 [==============================] - 1s 22ms/step - loss: 2.2130 - accuracy: 0.2480 - val_loss: 2.2160 - val_accuracy: 0.2441
Epoch 41/100
44/44 [==============================] - 1s 23ms/step - loss: 2.2107 - accuracy: 0.2384 - val_loss: 2.2127 - val_accuracy: 0.2339
Epoch 42/100
44/44 [==============================] - 1s 23ms/step - loss: 2.2083 - accuracy: 0.2727 - val_loss: 2.2106 - val_accuracy: 0.2028
Epoch 43/100
44/44 [==============================] - 1s 23ms/step - loss: 2.2062 - accuracy: 0.2471 - val_loss: 2.2089 - val_accuracy: 0.2587
Epoch 44/100
44/44 [==============================] - 1s 22ms/step - loss: 2.2049 - accuracy: 0.2682 - val_loss: 2.2069 - val_accuracy: 0.2193
Epoch 45/100
44/44 [==============================] - 2s 37ms/step - loss: 2.2032 - accuracy: 0.2380 - val_loss: 2.2039 - val_accuracy: 0.2649
Epoch 46/100
44/44 [==============================] - 1s 33ms/step - loss: 2.2014 - accuracy: 0.2591 - val_loss: 2.2015 - val_accuracy: 0.2674
Epoch 47/100
44/44 [==============================] - 1s 25ms/step - loss: 2.1978 - accuracy: 0.2680 - val_loss: 2.2043 - val_accuracy: 0.1694
Epoch 48/100
44/44 [==============================] - 1s 22ms/step - loss: 2.1966 - accuracy: 0.2570 - val_loss: 2.1979 - val_accuracy: 0.2084
Epoch 49/100
44/44 [==============================] - 1s 22ms/step - loss: 2.1932 - accuracy: 0.2596 - val_loss: 2.1951 - val_accuracy: 0.2883
Epoch 50/100
44/44 [==============================] - 1s 23ms/step - loss: 2.1915 - accuracy: 0.2580 - val_loss: 2.1928 - val_accuracy: 0.2802
Epoch 51/100
44/44 [==============================] - 1s 23ms/step - loss: 2.1890 - accuracy: 0.2800 - val_loss: 2.1904 - val_accuracy: 0.2381
Epoch 52/100
44/44 [==============================] - 1s 22ms/step - loss: 2.1862 - accuracy: 0.2637 - val_loss: 2.1887 - val_accuracy: 0.2787
Epoch 53/100
44/44 [==============================] - 1s 23ms/step - loss: 2.1840 - accuracy: 0.2575 - val_loss: 2.1874 - val_accuracy: 0.2949
Epoch 54/100
44/44 [==============================] - 1s 22ms/step - loss: 2.1828 - accuracy: 0.2759 - val_loss: 2.1853 - val_accuracy: 0.2909
Epoch 55/100
44/44 [==============================] - 1s 23ms/step - loss: 2.1795 - accuracy: 0.2705 - val_loss: 2.1823 - val_accuracy: 0.2578
Epoch 56/100
44/44 [==============================] - 1s 23ms/step - loss: 2.1773 - accuracy: 0.2741 - val_loss: 2.1788 - val_accuracy: 0.2571
Epoch 57/100
44/44 [==============================] - 2s 40ms/step - loss: 2.1750 - accuracy: 0.2796 - val_loss: 2.1763 - val_accuracy: 0.2541
Epoch 58/100
44/44 [==============================] - 2s 42ms/step - loss: 2.1722 - accuracy: 0.2680 - val_loss: 2.1739 - val_accuracy: 0.2716
Epoch 59/100
44/44 [==============================] - 1s 23ms/step - loss: 2.1706 - accuracy: 0.2770 - val_loss: 2.1722 - val_accuracy: 0.2754
Epoch 60/100
44/44 [==============================] - 2s 38ms/step - loss: 2.1671 - accuracy: 0.2700 - val_loss: 2.1709 - val_accuracy: 0.3026
Epoch 61/100
44/44 [==============================] - 1s 23ms/step - loss: 2.1649 - accuracy: 0.2920 - val_loss: 2.1668 - val_accuracy: 0.2815
Epoch 62/100
44/44 [==============================] - 1s 21ms/step - loss: 2.1623 - accuracy: 0.2700 - val_loss: 2.1650 - val_accuracy: 0.2741
Epoch 63/100
44/44 [==============================] - 1s 23ms/step - loss: 2.1601 - accuracy: 0.2727 - val_loss: 2.1648 - val_accuracy: 0.2537
Epoch 64/100
44/44 [==============================] - 1s 22ms/step - loss: 2.1582 - accuracy: 0.2925 - val_loss: 2.1591 - val_accuracy: 0.2736
Epoch 65/100
44/44 [==============================] - 1s 23ms/step - loss: 2.1553 - accuracy: 0.2836 - val_loss: 2.1592 - val_accuracy: 0.2865
Epoch 66/100
44/44 [==============================] - 1s 22ms/step - loss: 2.1520 - accuracy: 0.2707 - val_loss: 2.1559 - val_accuracy: 0.2713
Epoch 67/100
44/44 [==============================] - 2s 38ms/step - loss: 2.1494 - accuracy: 0.2839 - val_loss: 2.1514 - val_accuracy: 0.2767
Epoch 68/100
44/44 [==============================] - 2s 47ms/step - loss: 2.1476 - accuracy: 0.2830 - val_loss: 2.1494 - val_accuracy: 0.2976
Epoch 69/100
44/44 [==============================] - 1s 15ms/step - loss: 2.1455 - accuracy: 0.2914 - val_loss: 2.1466 - val_accuracy: 0.2862
Epoch 70/100
44/44 [==============================] - 1s 14ms/step - loss: 2.1421 - accuracy: 0.2871 - val_loss: 2.1475 - val_accuracy: 0.2942

#### Batches 6

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.regularizers import Regularizer
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import KFold
from tensorflow.keras import backend as K
# Normalize the input data
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0
# x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=42)
# Convert the labels to one-hot encoding
num_classes = 10
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training set into 20 batches
num_batches = 6
x_train_batches = np.array_split(x_train, num_batches)
y_train_batches = np.array_split(y_train, num_batches)
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    f_accum = []
    for i in range(len(model.weights)):
        f_accum.append(np.zeros(K.int_shape(model.weights[i])))
    f_accum = np.array(f_accum)
    for _ in range(num_samples):
        idx = np.random.randint(0, x.shape[0])
        with tf.GradientTape() as tape:
            model_output = model(x[idx:idx+1])
        grads = tape.gradient(model_output, model.weights)
        for i in range(len(grads)):
            f_accum[i] += tf.square(grads[i])
    f_accum /= num_samples
    return f_accum

# Define the CrlB regularizer
class CrlBRegularizer(Regularizer):
    def __init__(self, fisher, prior_weights, lambda_=0.1):
        self.fisher = fisher
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i in range(len(self.fisher)):
            regularization += self.lambda_ * tf.reduce_sum(self.fisher[i] * tf.square(x - self.prior_weights[i]))
        return regularization



# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []


model = Sequential([
    Flatten(input_shape=(784,)),
    Dense(128, activation='relu'),
    Dense(num_classes, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
        # Train the model on each batch
epochs = 100
for i in range(num_batches):
    x_train_batch = x_train_batches[i]
    y_train_batch = y_train_batches[i]

    model.fit(x_train_batch, y_train_batch, batch_size=128, epochs=epochs, verbose=1)
    model.save_weights('FashionMNIST_A.h5')

# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_batch[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]

# Task B: Fashion MNIST with CrlB regularization
    model_CrlBB = Sequential([
        Dense(128, activation='relu', input_shape=(784,), kernel_regularizer=CrlBRegularizer(fisher_info[0], model.weights[0])),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBRegularizer(fisher_info[1], model.weights[1]))
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model_CrlBB = model_CrlBB
        model_CrlBB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model_CrlBB.load_weights('FashionMNIST_A.h5')
        model_CrlBB.fit( x_train_batch, y_train_batch, batch_size=128,epochs=epochs,  validation_data=(x_test, y_test))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test, y_test)[1]
    B_CrlB_acc = 100 * model_CrlBB.evaluate(x_test, y_test)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlB method Accuracy: %.2f%%" % B_CrlB_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/100
73/73 [==============================] - 2s 4ms/step - loss: 2.3014 - accuracy: 0.1175
Epoch 2/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2999 - accuracy: 0.1176
Epoch 3/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2997 - accuracy: 0.1176
Epoch 4/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2998 - accuracy: 0.1176
Epoch 5/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2998 - accuracy: 0.1176
Epoch 6/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2997 - accuracy: 0.1176
Epoch 7/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2996 - accuracy: 0.1176
Epoch 8/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2997 - accuracy: 0.1176
Epoch 9/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2996 - accuracy: 0.1176
Epoch 10/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2996 - accuracy: 0.1176
Epoch 11/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2996 - accuracy: 0.1176
Epoch 12/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2995 - accuracy: 0.1176
Epoch 13/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2995 - accuracy: 0.1176
Epoch 14/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2994 - accuracy: 0.1176
Epoch 15/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2994 - accuracy: 0.1176
Epoch 16/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2993 - accuracy: 0.1176
Epoch 17/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2992 - accuracy: 0.1176
Epoch 18/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2992 - accuracy: 0.1176
Epoch 19/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2990 - accuracy: 0.1176
Epoch 20/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2989 - accuracy: 0.1176
Epoch 21/100
73/73 [==============================] - 0s 6ms/step - loss: 2.2989 - accuracy: 0.1176
Epoch 22/100
73/73 [==============================] - 0s 6ms/step - loss: 2.2988 - accuracy: 0.1176
Epoch 23/100
73/73 [==============================] - 1s 7ms/step - loss: 2.2987 - accuracy: 0.1176
Epoch 24/100
73/73 [==============================] - 1s 9ms/step - loss: 2.2985 - accuracy: 0.1176
Epoch 25/100
73/73 [==============================] - 0s 6ms/step - loss: 2.2985 - accuracy: 0.1176
Epoch 26/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2984 - accuracy: 0.1176
Epoch 27/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2983 - accuracy: 0.1176
Epoch 28/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2980 - accuracy: 0.1176
Epoch 29/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2980 - accuracy: 0.1176
Epoch 30/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2977 - accuracy: 0.1176
Epoch 31/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2975 - accuracy: 0.1176
Epoch 32/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2974 - accuracy: 0.1176
Epoch 33/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2972 - accuracy: 0.1176
Epoch 34/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2971 - accuracy: 0.1176
Epoch 35/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2965 - accuracy: 0.1176
Epoch 36/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2963 - accuracy: 0.1176
Epoch 37/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2960 - accuracy: 0.1176
Epoch 38/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2956 - accuracy: 0.1176
Epoch 39/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2953 - accuracy: 0.1176
Epoch 40/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2949 - accuracy: 0.1176
Epoch 41/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2944 - accuracy: 0.1176
Epoch 42/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2939 - accuracy: 0.1176
Epoch 43/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2934 - accuracy: 0.1176
Epoch 44/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2929 - accuracy: 0.1190
Epoch 45/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2921 - accuracy: 0.1176
Epoch 46/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2917 - accuracy: 0.1324
Epoch 47/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2911 - accuracy: 0.1188
Epoch 48/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2902 - accuracy: 0.1176
Epoch 49/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2894 - accuracy: 0.1183
Epoch 50/100
73/73 [==============================] - 0s 6ms/step - loss: 2.2886 - accuracy: 0.1232
Epoch 51/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2877 - accuracy: 0.1186
Epoch 52/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2865 - accuracy: 0.1304
Epoch 53/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2859 - accuracy: 0.1203
Epoch 54/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2844 - accuracy: 0.1286
Epoch 55/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2830 - accuracy: 0.1338
Epoch 56/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2819 - accuracy: 0.1283
Epoch 57/100
73/73 [==============================] - 0s 6ms/step - loss: 2.2810 - accuracy: 0.1451
Epoch 58/100
73/73 [==============================] - 0s 7ms/step - loss: 2.2792 - accuracy: 0.1437
Epoch 59/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2782 - accuracy: 0.1363
Epoch 60/100
73/73 [==============================] - 0s 6ms/step - loss: 2.2765 - accuracy: 0.1414
Epoch 61/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2750 - accuracy: 0.1527
Epoch 62/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2735 - accuracy: 0.1525
Epoch 63/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2715 - accuracy: 0.1600
Epoch 64/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2696 - accuracy: 0.1540
Epoch 65/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2678 - accuracy: 0.1852
Epoch 66/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2665 - accuracy: 0.1647
Epoch 67/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2641 - accuracy: 0.1730
Epoch 68/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2620 - accuracy: 0.1883
Epoch 69/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2593 - accuracy: 0.1978
Epoch 70/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2573 - accuracy: 0.1759
Epoch 71/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2548 - accuracy: 0.2133
Epoch 72/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2521 - accuracy: 0.1910
Epoch 73/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2492 - accuracy: 0.2082
Epoch 74/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2470 - accuracy: 0.2104
Epoch 75/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2441 - accuracy: 0.2010
Epoch 76/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2412 - accuracy: 0.2193
Epoch 77/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2382 - accuracy: 0.2296
Epoch 78/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2351 - accuracy: 0.2193
Epoch 79/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2321 - accuracy: 0.2384
Epoch 80/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2292 - accuracy: 0.2156
Epoch 81/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2252 - accuracy: 0.2296
Epoch 82/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2232 - accuracy: 0.2312
Epoch 83/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2194 - accuracy: 0.2312
Epoch 84/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2164 - accuracy: 0.2301
Epoch 85/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2126 - accuracy: 0.2363
Epoch 86/100
73/73 [==============================] - 0s 4ms/step - loss: 2.2089 - accuracy: 0.2496
Epoch 87/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2057 - accuracy: 0.2382
Epoch 88/100
73/73 [==============================] - 0s 5ms/step - loss: 2.2018 - accuracy: 0.2387
Epoch 89/100
73/73 [==============================] - 0s 4ms/step - loss: 2.1973 - accuracy: 0.2547
Epoch 90/100
73/73 [==============================] - 0s 5ms/step - loss: 2.1936 - accuracy: 0.2573
Epoch 91/100
73/73 [==============================] - 0s 5ms/step - loss: 2.1901 - accuracy: 0.2430
Epoch 92/100
73/73 [==============================] - 0s 5ms/step - loss: 2.1872 - accuracy: 0.2475
Epoch 93/100
73/73 [==============================] - 0s 6ms/step - loss: 2.1821 - accuracy: 0.2675
Epoch 94/100
73/73 [==============================] - 0s 5ms/step - loss: 2.1780 - accuracy: 0.2547
Epoch 95/100
73/73 [==============================] - 0s 5ms/step - loss: 2.1753 - accuracy: 0.2622
Epoch 96/100
73/73 [==============================] - 0s 5ms/step - loss: 2.1704 - accuracy: 0.2521
Epoch 97/100
73/73 [==============================] - 0s 6ms/step - loss: 2.1661 - accuracy: 0.2726
Epoch 98/100
73/73 [==============================] - 0s 6ms/step - loss: 2.1619 - accuracy: 0.2698
Epoch 99/100
73/73 [==============================] - 0s 4ms/step - loss: 2.1577 - accuracy: 0.2768
Epoch 100/100
73/73 [==============================] - 0s 5ms/step - loss: 2.1532 - accuracy: 0.2663
Epoch 1/100
73/73 [==============================] - 98s 300ms/step - loss: 2.1499 - accuracy: 0.2721 - val_loss: 2.1556 - val_accuracy: 0.2555
Epoch 2/100
73/73 [==============================] - 1s 17ms/step - loss: 2.1450 - accuracy: 0.2767 - val_loss: 2.1502 - val_accuracy: 0.2834
Epoch 3/100
73/73 [==============================] - 1s 17ms/step - loss: 2.1421 - accuracy: 0.2827 - val_loss: 2.1466 - val_accuracy: 0.2846
Epoch 4/100
73/73 [==============================] - 1s 17ms/step - loss: 2.1378 - accuracy: 0.2898 - val_loss: 2.1449 - val_accuracy: 0.2621
Epoch 5/100
73/73 [==============================] - 1s 16ms/step - loss: 2.1341 - accuracy: 0.2879 - val_loss: 2.1393 - val_accuracy: 0.2921
Epoch 6/100
73/73 [==============================] - 2s 23ms/step - loss: 2.1302 - accuracy: 0.2923 - val_loss: 2.1401 - val_accuracy: 0.2681
Epoch 7/100
73/73 [==============================] - 2s 28ms/step - loss: 2.1263 - accuracy: 0.2895 - val_loss: 2.1319 - val_accuracy: 0.2971
Epoch 8/100
73/73 [==============================] - 1s 17ms/step - loss: 2.1223 - accuracy: 0.2898 - val_loss: 2.1302 - val_accuracy: 0.2903
Epoch 9/100
73/73 [==============================] - 1s 16ms/step - loss: 2.1193 - accuracy: 0.2851 - val_loss: 2.1326 - val_accuracy: 0.2543
Epoch 10/100
73/73 [==============================] - 1s 16ms/step - loss: 2.1151 - accuracy: 0.3045 - val_loss: 2.1200 - val_accuracy: 0.2859
Epoch 11/100
73/73 [==============================] - 1s 16ms/step - loss: 2.1099 - accuracy: 0.3064 - val_loss: 2.1161 - val_accuracy: 0.2889
Epoch 12/100
73/73 [==============================] - 1s 16ms/step - loss: 2.1059 - accuracy: 0.3000 - val_loss: 2.1113 - val_accuracy: 0.2901
Epoch 13/100
73/73 [==============================] - 1s 17ms/step - loss: 2.1027 - accuracy: 0.3099 - val_loss: 2.1079 - val_accuracy: 0.2954
Epoch 14/100
73/73 [==============================] - 1s 17ms/step - loss: 2.0982 - accuracy: 0.3024 - val_loss: 2.1084 - val_accuracy: 0.2930
Epoch 15/100
73/73 [==============================] - 2s 22ms/step - loss: 2.0943 - accuracy: 0.3105 - val_loss: 2.1009 - val_accuracy: 0.2761
Epoch 16/100
73/73 [==============================] - 2s 21ms/step - loss: 2.0891 - accuracy: 0.3167 - val_loss: 2.0963 - val_accuracy: 0.2826
Epoch 17/100
73/73 [==============================] - 2s 27ms/step - loss: 2.0858 - accuracy: 0.3061 - val_loss: 2.0924 - val_accuracy: 0.2950
Epoch 18/100
73/73 [==============================] - 1s 17ms/step - loss: 2.0811 - accuracy: 0.3165 - val_loss: 2.0884 - val_accuracy: 0.3167
Epoch 19/100
73/73 [==============================] - 1s 16ms/step - loss: 2.0774 - accuracy: 0.3279 - val_loss: 2.0830 - val_accuracy: 0.3143
Epoch 20/100
73/73 [==============================] - 1s 17ms/step - loss: 2.0721 - accuracy: 0.3222 - val_loss: 2.0779 - val_accuracy: 0.3306
Epoch 21/100
73/73 [==============================] - 1s 17ms/step - loss: 2.0674 - accuracy: 0.3348 - val_loss: 2.0740 - val_accuracy: 0.3198
Epoch 22/100
73/73 [==============================] - 1s 17ms/step - loss: 2.0629 - accuracy: 0.3253 - val_loss: 2.0702 - val_accuracy: 0.3372
Epoch 23/100
73/73 [==============================] - 2s 25ms/step - loss: 2.0597 - accuracy: 0.3327 - val_loss: 2.0707 - val_accuracy: 0.2922
Epoch 24/100
73/73 [==============================] - 2s 32ms/step - loss: 2.0537 - accuracy: 0.3368 - val_loss: 2.0646 - val_accuracy: 0.3192
Epoch 25/100
73/73 [==============================] - 1s 16ms/step - loss: 2.0510 - accuracy: 0.3241 - val_loss: 2.0597 - val_accuracy: 0.3279
Epoch 26/100
73/73 [==============================] - 1s 17ms/step - loss: 2.0459 - accuracy: 0.3393 - val_loss: 2.0533 - val_accuracy: 0.3346
Epoch 27/100
73/73 [==============================] - 1s 17ms/step - loss: 2.0417 - accuracy: 0.3368 - val_loss: 2.0512 - val_accuracy: 0.3519
Epoch 28/100
73/73 [==============================] - 1s 16ms/step - loss: 2.0368 - accuracy: 0.3482 - val_loss: 2.0433 - val_accuracy: 0.3369
Epoch 29/100
73/73 [==============================] - 1s 17ms/step - loss: 2.0318 - accuracy: 0.3406 - val_loss: 2.0441 - val_accuracy: 0.2946
Epoch 30/100
73/73 [==============================] - 1s 16ms/step - loss: 2.0267 - accuracy: 0.3537 - val_loss: 2.0426 - val_accuracy: 0.3246
Epoch 31/100
73/73 [==============================] - 1s 17ms/step - loss: 2.0240 - accuracy: 0.3509 - val_loss: 2.0319 - val_accuracy: 0.3506
Epoch 32/100
73/73 [==============================] - 1s 17ms/step - loss: 2.0187 - accuracy: 0.3559 - val_loss: 2.0266 - val_accuracy: 0.3562
Epoch 33/100
73/73 [==============================] - 2s 27ms/step - loss: 2.0134 - accuracy: 0.3514 - val_loss: 2.0227 - val_accuracy: 0.3562
Epoch 34/100
73/73 [==============================] - 1s 19ms/step - loss: 2.0089 - accuracy: 0.3628 - val_loss: 2.0186 - val_accuracy: 0.3442
Epoch 35/100
73/73 [==============================] - 2s 26ms/step - loss: 2.0038 - accuracy: 0.3560 - val_loss: 2.0129 - val_accuracy: 0.3666
Epoch 36/100
73/73 [==============================] - 1s 17ms/step - loss: 1.9995 - accuracy: 0.3636 - val_loss: 2.0079 - val_accuracy: 0.3549
Epoch 37/100
73/73 [==============================] - 1s 16ms/step - loss: 1.9945 - accuracy: 0.3634 - val_loss: 2.0076 - val_accuracy: 0.3446
Epoch 38/100
73/73 [==============================] - 1s 19ms/step - loss: 1.9914 - accuracy: 0.3662 - val_loss: 2.0009 - val_accuracy: 0.3533
Epoch 39/100
73/73 [==============================] - 1s 17ms/step - loss: 1.9856 - accuracy: 0.3695 - val_loss: 1.9939 - val_accuracy: 0.3637
Epoch 40/100
73/73 [==============================] - 1s 17ms/step - loss: 1.9817 - accuracy: 0.3750 - val_loss: 1.9921 - val_accuracy: 0.3540
Epoch 41/100
73/73 [==============================] - 1s 20ms/step - loss: 1.9782 - accuracy: 0.3620 - val_loss: 1.9862 - val_accuracy: 0.3693
Epoch 42/100
73/73 [==============================] - 2s 29ms/step - loss: 1.9726 - accuracy: 0.3702 - val_loss: 1.9837 - val_accuracy: 0.3686
Epoch 43/100
73/73 [==============================] - 2s 26ms/step - loss: 1.9667 - accuracy: 0.3799 - val_loss: 1.9774 - val_accuracy: 0.3744
Epoch 44/100
73/73 [==============================] - 1s 17ms/step - loss: 1.9634 - accuracy: 0.3772 - val_loss: 1.9717 - val_accuracy: 0.3677
Epoch 45/100
73/73 [==============================] - 1s 17ms/step - loss: 1.9579 - accuracy: 0.3872 - val_loss: 1.9669 - val_accuracy: 0.3746
Epoch 46/100
73/73 [==============================] - 1s 17ms/step - loss: 1.9534 - accuracy: 0.3824 - val_loss: 1.9625 - val_accuracy: 0.3656
Epoch 47/100
73/73 [==============================] - 1s 16ms/step - loss: 1.9486 - accuracy: 0.3845 - val_loss: 1.9587 - val_accuracy: 0.3744
Epoch 48/100
73/73 [==============================] - 1s 17ms/step - loss: 1.9447 - accuracy: 0.3845 - val_loss: 1.9558 - val_accuracy: 0.3890
Epoch 49/100
73/73 [==============================] - 1s 17ms/step - loss: 1.9402 - accuracy: 0.3906 - val_loss: 1.9484 - val_accuracy: 0.3760
Epoch 50/100
73/73 [==============================] - 1s 21ms/step - loss: 1.9347 - accuracy: 0.3934 - val_loss: 1.9439 - val_accuracy: 0.3862
Epoch 51/100
73/73 [==============================] - 2s 21ms/step - loss: 1.9313 - accuracy: 0.3875 - val_loss: 1.9434 - val_accuracy: 0.3796
Epoch 52/100
73/73 [==============================] - 1s 17ms/step - loss: 1.9263 - accuracy: 0.3918 - val_loss: 1.9396 - val_accuracy: 0.3707
Epoch 53/100
73/73 [==============================] - 1s 17ms/step - loss: 1.9219 - accuracy: 0.4011 - val_loss: 1.9348 - val_accuracy: 0.3749
Epoch 54/100
73/73 [==============================] - 1s 17ms/step - loss: 1.9167 - accuracy: 0.3994 - val_loss: 1.9255 - val_accuracy: 0.3909
Epoch 55/100
73/73 [==============================] - 1s 17ms/step - loss: 1.9110 - accuracy: 0.4136 - val_loss: 1.9222 - val_accuracy: 0.3793
Epoch 56/100
73/73 [==============================] - 1s 17ms/step - loss: 1.9072 - accuracy: 0.4041 - val_loss: 1.9210 - val_accuracy: 0.3877
Epoch 57/100
73/73 [==============================] - 1s 17ms/step - loss: 1.9029 - accuracy: 0.4050 - val_loss: 1.9128 - val_accuracy: 0.4039
Epoch 58/100
73/73 [==============================] - 1s 17ms/step - loss: 1.8974 - accuracy: 0.4095 - val_loss: 1.9097 - val_accuracy: 0.3994
Epoch 59/100
73/73 [==============================] - 2s 26ms/step - loss: 1.8930 - accuracy: 0.4050 - val_loss: 1.9061 - val_accuracy: 0.3882
Epoch 60/100
73/73 [==============================] - 2s 30ms/step - loss: 1.8883 - accuracy: 0.4189 - val_loss: 1.8990 - val_accuracy: 0.4043
Epoch 61/100
73/73 [==============================] - 2s 26ms/step - loss: 1.8866 - accuracy: 0.4131 - val_loss: 1.8988 - val_accuracy: 0.4120
Epoch 62/100
73/73 [==============================] - 1s 17ms/step - loss: 1.8788 - accuracy: 0.4255 - val_loss: 1.8918 - val_accuracy: 0.3907
Epoch 63/100
73/73 [==============================] - 1s 17ms/step - loss: 1.8763 - accuracy: 0.4124 - val_loss: 1.8845 - val_accuracy: 0.4169
Epoch 64/100
73/73 [==============================] - 1s 17ms/step - loss: 1.8695 - accuracy: 0.4349 - val_loss: 1.8846 - val_accuracy: 0.3982
Epoch 65/100
73/73 [==============================] - 1s 17ms/step - loss: 1.8649 - accuracy: 0.4203 - val_loss: 1.8756 - val_accuracy: 0.4261
Epoch 66/100
73/73 [==============================] - 1s 17ms/step - loss: 1.8615 - accuracy: 0.4210 - val_loss: 1.8712 - val_accuracy: 0.4161
Epoch 67/100
73/73 [==============================] - 1s 17ms/step - loss: 1.8571 - accuracy: 0.4261 - val_loss: 1.8671 - val_accuracy: 0.4474
Epoch 68/100
73/73 [==============================] - 2s 27ms/step - loss: 1.8526 - accuracy: 0.4294 - val_loss: 1.8628 - val_accuracy: 0.4261
Epoch 69/100
73/73 [==============================] - 1s 20ms/step - loss: 1.8469 - accuracy: 0.4358 - val_loss: 1.8581 - val_accuracy: 0.4389
Epoch 70/100
73/73 [==============================] - 1s 17ms/step - loss: 1.8427 - accuracy: 0.4454 - val_loss: 1.8544 - val_accuracy: 0.4041

#### Batches 5

### CIFAR10 - Batches 1

In [ ]:
import numpy as np
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split

# Load the CIFAR-10 dataset
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Convert the labels to one-hot encoding
num_classes = 10
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Flatten the input images
x_train = x_train.reshape(-1, 32 , 32 , 3)
x_test = x_test.reshape(-1, 32 ,32 , 3)

# Split the data into train and test sets
test_size = 0.2
x_train, x_test, y_train, y_test = train_test_split(x_train, y_train, test_size=test_size, random_state=42)

# Define the model architecture
model = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32 ,32 , 3)),
        Conv2D(32, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        Flatten(),
        Dense(512, activation='relu'),
        Dense(num_classes, activation='softmax')
        ])

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on the train set
model.fit(x_train, y_train, batch_size=128, epochs=10, verbose=1)

# Evaluate the model on the test set
_, test_accuracy = model.evaluate(x_test, y_test, verbose=0)
print("Test Accuracy:", test_accuracy)

Epoch 1/10
313/313 [==============================] - 239s 760ms/step - loss: 1.4822 - accuracy: 0.4660
Epoch 2/10
313/313 [==============================] - 233s 745ms/step - loss: 1.0422 - accuracy: 0.6328
Epoch 3/10
313/313 [==============================] - 226s 722ms/step - loss: 0.8470 - accuracy: 0.7051
Epoch 4/10
313/313 [==============================] - 225s 721ms/step - loss: 0.6903 - accuracy: 0.7588
Epoch 5/10
313/313 [==============================] - 225s 718ms/step - loss: 0.5536 - accuracy: 0.8052
Epoch 6/10
313/313 [==============================] - 224s 716ms/step - loss: 0.4156 - accuracy: 0.8551
Epoch 7/10
313/313 [==============================] - 226s 721ms/step - loss: 0.2898 - accuracy: 0.8988
Epoch 8/10
313/313 [==============================] - 226s 723ms/step - loss: 0.1805 - accuracy: 0.9381
Epoch 9/10
313/313 [==============================] - 226s 723ms/step - loss: 0.1158 - accuracy: 0.9609
Epoch 10/10
313/313 [==============================] - 227s 725ms/step - loss: 0.0844 - accuracy: 0.9717
Test Accuracy: 0.734000027179718

### CIFAR10 - Batches 20

In [ ]:
import numpy as np
from tensorflow.keras.datasets import cifar10
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

# Load the CIFAR-10 dataset
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Split the training set into 20 batches
num_batches = 20
x_train_batches = np.array_split(x_train, num_batches)
y_train_batches = np.array_split(y_train, num_batches)

# Perform hold-out cross-validation
validation_scores = []

for i in range(num_batches):
    # Create the validation set for this fold
    x_train_fold = x_train_batches[:i]
    y_train_fold = y_train_batches[:i]
    x_val_fold = x_train_batches[i]
    y_val_fold = y_train_batches[i]

    # Train and evaluate your model on this fold
    # ...
    # Replace this with your model training and evaluation code

    # Compute and store the validation score
    validation_score = 0.0  # Replace with the actual validation score
    validation_scores.append(validation_score)

    # Compute the average validation score
    average_validation_score = np.mean(validation_scores)
    print("Average Validation Score:", average_validation_score)

    # Normalize the input data
    # x_train_fold = x_train_fold.astype('float32') / 255.
    # x_val_fold = x_val_fold.astype('float32') / 255.

    # Convert the labels to one-hot encoding
    num_classes = 10
    # y_train_fold = tf.keras.utils.to_categorical(y_train_fold, num_classes)
    # y_val_fold = tf.keras.utils.to_categorical(y_val_fold, num_classes)

# Define the model architecture
    model = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32 ,32 , 3)),
        Conv2D(32, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        Flatten(),
        Dense(512, activation='relu'),
        Dense(num_classes, activation='softmax')
        ])

# Compile the model
    model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on the train set
    model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, verbose=1)

# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test, verbose=0)
    print("Test Accuracy:", test_accuracy)

Downloading data from https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
170498071/170498071 [==============================] - 3s 0us/step
Average Validation Score: 0.0
Epoch 1/10
372/372 [==============================] - 16s 12ms/step - loss: 1.4493 - accuracy: 0.4798 - val_loss: 1.1430 - val_accuracy: 0.5896
Epoch 2/10
372/372 [==============================] - 4s 11ms/step - loss: 0.9872 - accuracy: 0.6530 - val_loss: 0.9146 - val_accuracy: 0.6804
Epoch 3/10
372/372 [==============================] - 4s 10ms/step - loss: 0.7844 - accuracy: 0.7271 - val_loss: 0.8731 - val_accuracy: 0.6880
Epoch 4/10
372/372 [==============================] - 4s 10ms/step - loss: 0.6339 - accuracy: 0.7795 - val_loss: 0.7365 - val_accuracy: 0.7452
Epoch 5/10
372/372 [==============================] - 4s 11ms/step - loss: 0.5006 - accuracy: 0.8237 - val_loss: 0.7172 - val_accuracy: 0.7572
Epoch 6/10
372/372 [==============================] - 4s 10ms/step - loss: 0.3633 - accuracy: 0.8736 - val_loss: 0.7845 - val_accuracy: 0.7612
Epoch 7/10
372/372 [==============================] - 4s 10ms/step - loss: 0.2480 - accuracy: 0.9137 - val_loss: 0.8957 - val_accuracy: 0.7528
Epoch 8/10
372/372 [==============================] - 4s 11ms/step - loss: 0.1586 - accuracy: 0.9456 - val_loss: 1.1085 - val_accuracy: 0.7516
Epoch 9/10
372/372 [==============================] - 4s 11ms/step - loss: 0.1073 - accuracy: 0.9635 - val_loss: 1.1612 - val_accuracy: 0.7524
Epoch 10/10
372/372 [==============================] - 4s 11ms/step - loss: 0.0725 - accuracy: 0.9750 - val_loss: 1.3139 - val_accuracy: 0.7476
79/79 [==============================] - 1s 4ms/step - loss: 1.3139 - accuracy: 0.7476
Average accuracy: 0.72260000705719
Average Validation Score: 0.24920000632603964
Epoch 1/10
372/372 [==============================] - 6s 12ms/step - loss: 1.4449 - accuracy: 0.4775 - val_loss: 1.1562 - val_accuracy: 0.5924
Epoch 2/10
372/372 [==============================] - 4s 11ms/step - loss: 0.9534 - accuracy: 0.6649 - val_loss: 0.8684 - val_accuracy: 0.7016
Epoch 3/10
372/372 [==============================] - 4s 11ms/step - loss: 0.7615 - accuracy: 0.7346 - val_loss: 0.7925 - val_accuracy: 0.7236
Epoch 4/10
372/372 [==============================] - 4s 11ms/step - loss: 0.6256 - accuracy: 0.7811 - val_loss: 0.7539 - val_accuracy: 0.7324
Epoch 5/10
372/372 [==============================] - 4s 11ms/step - loss: 0.4922 - accuracy: 0.8274 - val_loss: 0.7159 - val_accuracy: 0.7568
Epoch 6/10
372/372 [==============================] - 4s 10ms/step - loss: 0.3622 - accuracy: 0.8733 - val_loss: 0.8111 - val_accuracy: 0.7464
Epoch 7/10
372/372 [==============================] - 4s 11ms/step - loss: 0.2520 - accuracy: 0.9125 - val_loss: 0.8572 - val_accuracy: 0.7592
Epoch 8/10
372/372 [==============================] - 4s 11ms/step - loss: 0.1580 - accuracy: 0.9459 - val_loss: 0.9723 - val_accuracy: 0.7412
Epoch 9/10
372/372 [==============================] - 4s 11ms/step - loss: 0.1045 - accuracy: 0.9635 - val_loss: 1.1159 - val_accuracy: 0.7576
Epoch 10/10
372/372 [==============================] - 4s 11ms/step - loss: 0.0845 - accuracy: 0.9709 - val_loss: 1.3414 - val_accuracy: 0.7288
79/79 [==============================] - 0s 3ms/step - loss: 1.3414 - accuracy: 0.7288
Average accuracy: 0.7239999949932099
Average Validation Score: 0.2952800035476685
Epoch 1/10
372/372 [==============================] - 7s 12ms/step - loss: 1.4723 - accuracy: 0.4682 - val_loss: 1.1396 - val_accuracy: 0.5856
Epoch 2/10
372/372 [==============================] - 4s 10ms/step - loss: 1.0083 - accuracy: 0.6442 - val_loss: 0.9494 - val_accuracy: 0.6604
Epoch 3/10
372/372 [==============================] - 4s 11ms/step - loss: 0.7999 - accuracy: 0.7194 - val_loss: 0.8322 - val_accuracy: 0.7016
Epoch 4/10
372/372 [==============================] - 4s 11ms/step - loss: 0.6498 - accuracy: 0.7716 - val_loss: 0.9136 - val_accuracy: 0.6816
Epoch 5/10
372/372 [==============================] - 4s 11ms/step - loss: 0.5167 - accuracy: 0.8205 - val_loss: 0.7572 - val_accuracy: 0.7420
Epoch 6/10
372/372 [==============================] - 4s 11ms/step - loss: 0.3884 - accuracy: 0.8653 - val_loss: 0.7667 - val_accuracy: 0.7488
Epoch 7/10
372/372 [==============================] - 4s 11ms/step - loss: 0.2624 - accuracy: 0.9076 - val_loss: 0.8699 - val_accuracy: 0.7488
Epoch 8/10
372/372 [==============================] - 4s 11ms/step - loss: 0.1707 - accuracy: 0.9423 - val_loss: 1.0233 - val_accuracy: 0.7380
Epoch 9/10
372/372 [==============================] - 4s 11ms/step - loss: 0.1189 - accuracy: 0.9590 - val_loss: 1.1664 - val_accuracy: 0.7464
Epoch 10/10
372/372 [==============================] - 4s 11ms/step - loss: 0.0801 - accuracy: 0.9723 - val_loss: 1.3127 - val_accuracy: 0.7572
79/79 [==============================] - 0s 3ms/step - loss: 1.3127 - accuracy: 0.7572
Average accuracy: 0.7110399901866913
Average Validation Score: 0.3190857172012329
Epoch 1/10
372/372 [==============================] - 7s 11ms/step - loss: 1.4632 - accuracy: 0.4719 - val_loss: 1.1669 - val_accuracy: 0.5804
Epoch 2/10
372/372 [==============================] - 4s 11ms/step - loss: 0.9972 - accuracy: 0.6500 - val_loss: 0.9517 - val_accuracy: 0.6620
Epoch 3/10
372/372 [==============================] - 4s 11ms/step - loss: 0.7785 - accuracy: 0.7304 - val_loss: 0.8768 - val_accuracy: 0.6912
Epoch 4/10
372/372 [==============================] - 4s 11ms/step - loss: 0.6368 - accuracy: 0.7787 - val_loss: 0.7964 - val_accuracy: 0.7244
Epoch 5/10
372/372 [==============================] - 4s 11ms/step - loss: 0.5059 - accuracy: 0.8223 - val_loss: 0.7567 - val_accuracy: 0.7388
Epoch 6/10
372/372 [==============================] - 4s 11ms/step - loss: 0.3631 - accuracy: 0.8754 - val_loss: 0.9129 - val_accuracy: 0.7264
Epoch 7/10
372/372 [==============================] - 4s 11ms/step - loss: 0.2480 - accuracy: 0.9140 - val_loss: 0.9140 - val_accuracy: 0.7460
Epoch 8/10
372/372 [==============================] - 4s 10ms/step - loss: 0.1513 - accuracy: 0.9481 - val_loss: 1.0641 - val_accuracy: 0.7424
Epoch 9/10
372/372 [==============================] - 4s 11ms/step - loss: 0.1023 - accuracy: 0.9645 - val_loss: 1.2787 - val_accuracy: 0.7292
Epoch 10/10
372/372 [==============================] - 4s 11ms/step - loss: 0.0743 - accuracy: 0.9745 - val_loss: 1.3515 - val_accuracy: 0.7424
79/79 [==============================] - 0s 3ms/step - loss: 1.3515 - accuracy: 0.7424
Average accuracy: 0.7083199977874756
Average Validation Score: 0.3306666678852505
Epoch 1/10
372/372 [==============================] - 7s 12ms/step - loss: 1.4542 - accuracy: 0.4752 - val_loss: 1.1302 - val_accuracy: 0.6140
Epoch 2/10
372/372 [==============================] - 4s 11ms/step - loss: 0.9989 - accuracy: 0.6480 - val_loss: 0.9190 - val_accuracy: 0.6700
Epoch 3/10
372/372 [==============================] - 4s 11ms/step - loss: 0.7904 - accuracy: 0.7239 - val_loss: 0.8490 - val_accuracy: 0.7100
Epoch 4/10
372/372 [==============================] - 4s 11ms/step - loss: 0.6447 - accuracy: 0.7755 - val_loss: 0.7869 - val_accuracy: 0.7180
Epoch 5/10
372/372 [==============================] - 4s 11ms/step - loss: 0.5023 - accuracy: 0.8253 - val_loss: 0.7649 - val_accuracy: 0.7348
Epoch 6/10
372/372 [==============================] - 4s 10ms/step - loss: 0.3655 - accuracy: 0.8723 - val_loss: 0.7884 - val_accuracy: 0.7464
Epoch 7/10
372/372 [==============================] - 4s 11ms/step - loss: 0.2393 - accuracy: 0.9180 - val_loss: 0.8706 - val_accuracy: 0.7444
Epoch 8/10
372/372 [==============================] - 4s 11ms/step - loss: 0.1462 - accuracy: 0.9504 - val_loss: 1.0497 - val_accuracy: 0.7396
Epoch 9/10
372/372 [==============================] - 4s 11ms/step - loss: 0.0926 - accuracy: 0.9683 - val_loss: 1.1287 - val_accuracy: 0.7504
Epoch 10/10
372/372 [==============================] - 4s 11ms/step - loss: 0.0739 - accuracy: 0.9739 - val_loss: 1.3093 - val_accuracy: 0.7420
79/79 [==============================] - 0s 3ms/step - loss: 1.3093 - accuracy: 0.7420
Average accuracy: 0.7169600009918213
Average Validation Score: 0.33799999952316284
Epoch 1/10
372/372 [==============================] - 6s 11ms/step - loss: 1.4443 - accuracy: 0.4813 - val_loss: 1.1914 - val_accuracy: 0.5752
Epoch 2/10
372/372 [==============================] - 4s 11ms/step - loss: 0.9840 - accuracy: 0.6543 - val_loss: 0.9263 - val_accuracy: 0.6648
Epoch 3/10
372/372 [==============================] - 4s 11ms/step - loss: 0.7888 - accuracy: 0.7253 - val_loss: 0.8411 - val_accuracy: 0.7096
Epoch 4/10
372/372 [==============================] - 4s 11ms/step - loss: 0.6459 - accuracy: 0.7724 - val_loss: 0.8433 - val_accuracy: 0.7076
Epoch 5/10
372/372 [==============================] - 4s 11ms/step - loss: 0.5062 - accuracy: 0.8238 - val_loss: 0.7603 - val_accuracy: 0.7388
Epoch 6/10
372/372 [==============================] - 4s 11ms/step - loss: 0.3679 - accuracy: 0.8729 - val_loss: 0.8335 - val_accuracy: 0.7456
Epoch 7/10
372/372 [==============================] - 4s 11ms/step - loss: 0.2514 - accuracy: 0.9131 - val_loss: 0.8912 - val_accuracy: 0.7336
Epoch 8/10
372/372 [==============================] - 4s 11ms/step - loss: 0.1541 - accuracy: 0.9465 - val_loss: 1.0478 - val_accuracy: 0.7448
Epoch 9/10
372/372 [==============================] - 4s 11ms/step - loss: 0.0991 - accuracy: 0.9671 - val_loss: 1.2712 - val_accuracy: 0.7280
Epoch 10/10
372/372 [==============================] - 4s 11ms/step - loss: 0.0735 - accuracy: 0.9742 - val_loss: 1.3021 - val_accuracy: 0.7444
79/79 [==============================] - 0s 3ms/step - loss: 1.3021 - accuracy: 0.7444
Average accuracy: 0.7092399954795837
Average Validation Score: 0.3432615399360657
Epoch 1/10
372/372 [==============================] - 6s 12ms/step - loss: 1.4360 - accuracy: 0.4832 - val_loss: 1.1496 - val_accuracy: 0.5984
Epoch 2/10
372/372 [==============================] - 4s 11ms/step - loss: 0.9712 - accuracy: 0.6610 - val_loss: 1.0037 - val_accuracy: 0.6588
Epoch 3/10
372/372 [==============================] - 4s 11ms/step - loss: 0.7848 - accuracy: 0.7252 - val_loss: 0.8060 - val_accuracy: 0.7256
Epoch 4/10
372/372 [==============================] - 4s 11ms/step - loss: 0.6301 - accuracy: 0.7792 - val_loss: 0.7772 - val_accuracy: 0.7360
Epoch 5/10
372/372 [==============================] - 4s 11ms/step - loss: 0.4804 - accuracy: 0.8316 - val_loss: 0.7688 - val_accuracy: 0.7476
Epoch 6/10
372/372 [==============================] - 4s 11ms/step - loss: 0.3546 - accuracy: 0.8763 - val_loss: 0.8365 - val_accuracy: 0.7516
Epoch 7/10
372/372 [==============================] - 4s 11ms/step - loss: 0.2260 - accuracy: 0.9216 - val_loss: 0.9910 - val_accuracy: 0.7408
Epoch 8/10
372/372 [==============================] - 4s 11ms/step - loss: 0.1348 - accuracy: 0.9536 - val_loss: 1.1342 - val_accuracy: 0.7372
Epoch 9/10
372/372 [==============================] - 4s 11ms/step - loss: 0.0945 - accuracy: 0.9681 - val_loss: 1.1641 - val_accuracy: 0.7608
Epoch 10/10
372/372 [==============================] - 4s 11ms/step - loss: 0.0673 - accuracy: 0.9771 - val_loss: 1.3065 - val_accuracy: 0.7548
79/79 [==============================] - 0s 3ms/step - loss: 1.3065 - accuracy: 0.7548
Average accuracy: 0.7211600124835968
Average Validation Score: 0.34781333605448406
Epoch 1/10
372/372 [==============================] - 6s 12ms/step - loss: 1.4341 - accuracy: 0.4840 - val_loss: 1.2267 - val_accuracy: 0.5720
Epoch 2/10
372/372 [==============================] - 4s 11ms/step - loss: 0.9815 - accuracy: 0.6530 - val_loss: 0.9736 - val_accuracy: 0.6608
Epoch 3/10
372/372 [==============================] - 4s 11ms/step - loss: 0.7888 - accuracy: 0.7222 - val_loss: 0.8769 - val_accuracy: 0.6992
Epoch 4/10
372/372 [==============================] - 4s 11ms/step - loss: 0.6351 - accuracy: 0.7758 - val_loss: 0.8076 - val_accuracy: 0.7288
Epoch 5/10
372/372 [==============================] - 4s 11ms/step - loss: 0.4978 - accuracy: 0.8256 - val_loss: 0.8320 - val_accuracy: 0.7304
Epoch 6/10
372/372 [==============================] - 4s 11ms/step - loss: 0.3570 - accuracy: 0.8760 - val_loss: 0.9317 - val_accuracy: 0.7216
Epoch 7/10
372/372 [==============================] - 4s 11ms/step - loss: 0.2279 - accuracy: 0.9217 - val_loss: 1.0017 - val_accuracy: 0.7556
Epoch 8/10
372/372 [==============================] - 4s 11ms/step - loss: 0.1448 - accuracy: 0.9507 - val_loss: 1.2245 - val_accuracy: 0.7160
Epoch 9/10
372/372 [==============================] - 4s 11ms/step - loss: 0.1096 - accuracy: 0.9628 - val_loss: 1.3173 - val_accuracy: 0.7452
Epoch 10/10
372/372 [==============================] - 4s 11ms/step - loss: 0.0679 - accuracy: 0.9772 - val_loss: 1.3642 - val_accuracy: 0.7368

### CIFAR10 - Batches 10

In [ ]:
import numpy as np
from tensorflow.keras.datasets import cifar10
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers

# Load the CIFAR-10 dataset
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Check if the number of batches is greater than the size of the training set
num_batches = 10
if num_batches > len(x_train):
    num_batches = len(x_train)

# Split the training set into batches
x_train_batches = np.array_split(x_train[:num_batches], num_batches)
y_train_batches = np.array_split(y_train[:num_batches], num_batches)

# Perform hold-out cross-validation
validation_scores = []

for i in range(num_batches):
    # Create the validation set for this fold
    x_train_fold = np.concatenate(x_train_batches[:i] + x_train_batches[i+1:])
    y_train_fold = np.concatenate(y_train_batches[:i] + y_train_batches[i+1:])
    x_val_fold = x_train_batches[i]
    y_val_fold = y_train_batches[i]

    # Define the model architecture
    model = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        Conv2D(32, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        Flatten(),
        Dense(512, activation='relu'),
        Dense(10, activation='softmax')
    ])

    # Compile the model
    model.compile(optimizer=Adam(), loss='sparse_categorical_crossentropy', metrics=['accuracy'])

    # Train the model on the train set
    model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, verbose=1)

    # Evaluate the model on the validation set
    _, validation_accuracy = model.evaluate(x_val_fold, y_val_fold, verbose=0)
    validation_scores.append(validation_accuracy)

    # Compute the average validation score
    average_validation_score = np.mean(validation_scores)
    print("Average Validation Score:", average_validation_score)

# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test, verbose=0)
    print("Test Accuracy:", test_accuracy)

Epoch 1/10
1/1 [==============================] - 5s 5s/step - loss: 18.8070 - accuracy: 0.1111
Epoch 2/10
1/1 [==============================] - 0s 16ms/step - loss: 32.3658 - accuracy: 0.3333
Epoch 3/10
1/1 [==============================] - 0s 12ms/step - loss: 43.6343 - accuracy: 0.3333
Epoch 4/10
1/1 [==============================] - 0s 14ms/step - loss: 45.4323 - accuracy: 0.2222
Epoch 5/10
1/1 [==============================] - 0s 12ms/step - loss: 30.5602 - accuracy: 0.3333
Epoch 6/10
1/1 [==============================] - 0s 12ms/step - loss: 16.8691 - accuracy: 0.4444
Epoch 7/10
1/1 [==============================] - 0s 13ms/step - loss: 7.4005 - accuracy: 0.4444
Epoch 8/10
1/1 [==============================] - 0s 14ms/step - loss: 1.4737 - accuracy: 0.6667
Epoch 9/10
1/1 [==============================] - 0s 12ms/step - loss: 0.3392 - accuracy: 0.8889
Epoch 10/10
1/1 [==============================] - 0s 13ms/step - loss: 0.4544 - accuracy: 0.7778
Average Validation Score: 0.0
Test Accuracy: 0.13609999418258667
Epoch 1/10
1/1 [==============================] - 2s 2s/step - loss: 50.3945 - accuracy: 0.1111
Epoch 2/10
1/1 [==============================] - 0s 11ms/step - loss: 65.5112 - accuracy: 0.3333
Epoch 3/10
1/1 [==============================] - 0s 12ms/step - loss: 58.9234 - accuracy: 0.3333
Epoch 4/10
1/1 [==============================] - 0s 12ms/step - loss: 50.4117 - accuracy: 0.2222
Epoch 5/10
1/1 [==============================] - 0s 11ms/step - loss: 30.4853 - accuracy: 0.3333
Epoch 6/10
1/1 [==============================] - 0s 11ms/step - loss: 14.9758 - accuracy: 0.3333
Epoch 7/10
1/1 [==============================] - 0s 11ms/step - loss: 6.1087 - accuracy: 0.5556
Epoch 8/10
1/1 [==============================] - 0s 12ms/step - loss: 2.8971 - accuracy: 0.6667
Epoch 9/10
1/1 [==============================] - 0s 11ms/step - loss: 1.6851 - accuracy: 0.5556
Epoch 10/10
1/1 [==============================] - 0s 10ms/step - loss: 0.9186 - accuracy: 0.6667
Average Validation Score: 0.5
Test Accuracy: 0.13279999792575836
Epoch 1/10
1/1 [==============================] - 2s 2s/step - loss: 27.8518 - accuracy: 0.0000e+00
Epoch 2/10
1/1 [==============================] - 0s 13ms/step - loss: 30.2147 - accuracy: 0.2222
Epoch 3/10
1/1 [==============================] - 0s 11ms/step - loss: 51.2884 - accuracy: 0.1111
Epoch 4/10
1/1 [==============================] - 0s 12ms/step - loss: 29.2579 - accuracy: 0.2222
Epoch 5/10
1/1 [==============================] - 0s 12ms/step - loss: 27.4661 - accuracy: 0.3333
Epoch 6/10
1/1 [==============================] - 0s 11ms/step - loss: 19.5593 - accuracy: 0.3333
Epoch 7/10
1/1 [==============================] - 0s 13ms/step - loss: 9.3127 - accuracy: 0.4444
Epoch 8/10
1/1 [==============================] - 0s 13ms/step - loss: 3.9448 - accuracy: 0.3333
Epoch 9/10
1/1 [==============================] - 0s 11ms/step - loss: 3.6684 - accuracy: 0.4444
Epoch 10/10
1/1 [==============================] - 0s 11ms/step - loss: 1.8507 - accuracy: 0.5556
Average Validation Score: 0.3333333333333333
Test Accuracy: 0.10419999808073044
Epoch 1/10
1/1 [==============================] - 3s 3s/step - loss: 14.7611 - accuracy: 0.3333
Epoch 2/10
1/1 [==============================] - 0s 16ms/step - loss: 158.7684 - accuracy: 0.2222
Epoch 3/10
1/1 [==============================] - 0s 13ms/step - loss: 119.7604 - accuracy: 0.2222
Epoch 4/10
1/1 [==============================] - 0s 15ms/step - loss: 32.1201 - accuracy: 0.2222
Epoch 5/10
1/1 [==============================] - 0s 12ms/step - loss: 13.0260 - accuracy: 0.3333
Epoch 6/10
1/1 [==============================] - 0s 14ms/step - loss: 4.8009 - accuracy: 0.5556
Epoch 7/10
1/1 [==============================] - 0s 11ms/step - loss: 4.7463 - accuracy: 0.3333
Epoch 8/10
1/1 [==============================] - 0s 12ms/step - loss: 2.9313 - accuracy: 0.4444
Epoch 9/10
1/1 [==============================] - 0s 15ms/step - loss: 0.2760 - accuracy: 0.7778
Epoch 10/10
1/1 [==============================] - 0s 11ms/step - loss: 0.4226 - accuracy: 0.8889
Average Validation Score: 0.25
Test Accuracy: 0.09839999675750732
Epoch 1/10
1/1 [==============================] - 2s 2s/step - loss: 8.4234 - accuracy: 0.0000e+00
Epoch 2/10
1/1 [==============================] - 0s 13ms/step - loss: 40.9003 - accuracy: 0.3333
Epoch 3/10
1/1 [==============================] - 0s 13ms/step - loss: 51.3794 - accuracy: 0.1111
Epoch 4/10
1/1 [==============================] - 0s 11ms/step - loss: 28.1103 - accuracy: 0.2222
Epoch 5/10
1/1 [==============================] - 0s 10ms/step - loss: 18.5258 - accuracy: 0.3333
Epoch 6/10
1/1 [==============================] - 0s 10ms/step - loss: 9.8759 - accuracy: 0.3333
Epoch 7/10
1/1 [==============================] - 0s 11ms/step - loss: 2.6454 - accuracy: 0.6667
Epoch 8/10
1/1 [==============================] - 0s 10ms/step - loss: 0.9377 - accuracy: 0.6667
Epoch 9/10
1/1 [==============================] - 0s 11ms/step - loss: 0.8743 - accuracy: 0.7778
Epoch 10/10
1/1 [==============================] - 0s 11ms/step - loss: 0.6261 - accuracy: 0.7778
Average Validation Score: 0.2
Test Accuracy: 0.1306000053882599
Epoch 1/10
1/1 [==============================] - 2s 2s/step - loss: 11.2954 - accuracy: 0.2222
Epoch 2/10
1/1 [==============================] - 0s 12ms/step - loss: 41.9052 - accuracy: 0.3333
Epoch 3/10
1/1 [==============================] - 0s 11ms/step - loss: 44.6794 - accuracy: 0.3333
Epoch 4/10
1/1 [==============================] - 0s 12ms/step - loss: 36.6487 - accuracy: 0.4444
Epoch 5/10
1/1 [==============================] - 0s 11ms/step - loss: 25.2715 - accuracy: 0.3333
Epoch 6/10
1/1 [==============================] - 0s 12ms/step - loss: 15.7559 - accuracy: 0.4444
Epoch 7/10
1/1 [==============================] - 0s 11ms/step - loss: 6.7068 - accuracy: 0.4444
Epoch 8/10
1/1 [==============================] - 0s 11ms/step - loss: 2.2986 - accuracy: 0.6667
Epoch 9/10
1/1 [==============================] - 0s 11ms/step - loss: 0.6579 - accuracy: 0.7778
Epoch 10/10
1/1 [==============================] - 0s 12ms/step - loss: 0.3458 - accuracy: 1.0000
Average Validation Score: 0.16666666666666666
Test Accuracy: 0.1266999989748001
Epoch 1/10
1/1 [==============================] - 3s 3s/step - loss: 36.9509 - accuracy: 0.0000e+00
Epoch 2/10
1/1 [==============================] - 0s 12ms/step - loss: 24.2104 - accuracy: 0.1111
Epoch 3/10
1/1 [==============================] - 0s 11ms/step - loss: 51.6872 - accuracy: 0.2222
Epoch 4/10
1/1 [==============================] - 0s 17ms/step - loss: 58.8604 - accuracy: 0.3333
Epoch 5/10
1/1 [==============================] - 0s 11ms/step - loss: 50.2175 - accuracy: 0.2222
Epoch 6/10
1/1 [==============================] - 0s 12ms/step - loss: 33.9825 - accuracy: 0.2222
Epoch 7/10
1/1 [==============================] - 0s 11ms/step - loss: 14.5251 - accuracy: 0.4444
Epoch 8/10
1/1 [==============================] - 0s 11ms/step - loss: 6.7853 - accuracy: 0.5556
Epoch 9/10
1/1 [==============================] - 0s 11ms/step - loss: 3.8594 - accuracy: 0.5556
Epoch 10/10
1/1 [==============================] - 0s 12ms/step - loss: 2.2629 - accuracy: 0.6667
Average Validation Score: 0.14285714285714285
Test Accuracy: 0.10509999841451645
Epoch 1/10
1/1 [==============================] - 2s 2s/step - loss: 12.9124 - accuracy: 0.1111
Epoch 2/10
1/1 [==============================] - 0s 13ms/step - loss: 71.4745 - accuracy: 0.2222
Epoch 3/10
1/1 [==============================] - 0s 13ms/step - loss: 81.2008 - accuracy: 0.2222
Epoch 4/10
1/1 [==============================] - 0s 12ms/step - loss: 50.4831 - accuracy: 0.2222
Epoch 5/10
1/1 [==============================] - 0s 11ms/step - loss: 27.2549 - accuracy: 0.3333
Epoch 6/10
1/1 [==============================] - 0s 11ms/step - loss: 15.4843 - accuracy: 0.2222
Epoch 7/10
1/1 [==============================] - 0s 12ms/step - loss: 6.9499 - accuracy: 0.5556
Epoch 8/10
1/1 [==============================] - 0s 12ms/step - loss: 3.4878 - accuracy: 0.5556
Epoch 9/10
1/1 [==============================] - 0s 12ms/step - loss: 2.0217 - accuracy: 0.5556
Epoch 10/10
1/1 [==============================] - 0s 11ms/step - loss: 1.2979 - accuracy: 0.8889
Average Validation Score: 0.125
Test Accuracy: 0.13779999315738678
Epoch 1/10
1/1 [==============================] - 2s 2s/step - loss: 23.4087 - accuracy: 0.0000e+00
Epoch 2/10
1/1 [==============================] - 0s 12ms/step - loss: 8.4790 - accuracy: 0.4444
Epoch 3/10
1/1 [==============================] - 0s 12ms/step - loss: 26.8837 - accuracy: 0.2222
Epoch 4/10
1/1 [==============================] - 0s 13ms/step - loss: 25.2693 - accuracy: 0.3333
Epoch 5/10
1/1 [==============================] - 0s 12ms/step - loss: 13.9149 - accuracy: 0.4444
Epoch 6/10
1/1 [==============================] - 0s 13ms/step - loss: 6.0587 - accuracy: 0.4444
Epoch 7/10
1/1 [==============================] - 0s 12ms/step - loss: 2.9273 - accuracy: 0.7778
Epoch 8/10
1/1 [==============================] - 0s 11ms/step - loss: 2.5103 - accuracy: 0.6667
Epoch 9/10
1/1 [==============================] - 0s 10ms/step - loss: 0.9060 - accuracy: 0.7778
Epoch 10/10
1/1 [==============================] - 0s 11ms/step - loss: 0.3553 - accuracy: 0.8889
Average Validation Score: 0.1111111111111111
Test Accuracy: 0.131400004029274
Epoch 1/10
1/1 [==============================] - 2s 2s/step - loss: 24.3564 - accuracy: 0.1111
Epoch 2/10
1/1 [==============================] - 0s 13ms/step - loss: 48.4906 - accuracy: 0.4444
Epoch 3/10
1/1 [==============================] - 0s 12ms/step - loss: 65.2156 - accuracy: 0.2222
Epoch 4/10
1/1 [==============================] - 0s 12ms/step - loss: 50.3197 - accuracy: 0.3333
Epoch 5/10
1/1 [==============================] - 0s 12ms/step - loss: 31.8112 - accuracy: 0.1111
Epoch 6/10
1/1 [==============================] - 0s 12ms/step - loss: 13.5694 - accuracy: 0.4444
Epoch 7/10
1/1 [==============================] - 0s 10ms/step - loss: 6.2953 - accuracy: 0.4444
Epoch 8/10
1/1 [==============================] - 0s 11ms/step - loss: 2.2642 - accuracy: 0.5556
Epoch 9/10
1/1 [==============================] - 0s 10ms/step - loss: 1.1053 - accuracy: 0.5556
Epoch 10/10
1/1 [==============================] - 0s 10ms/step - loss: 0.6324 - accuracy: 0.7778
Average Validation Score: 0.1
Test Accuracy: 0.14079999923706055

### MNIST - Batches 20

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
import numpy as np

# Load the MNIST dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Convert the labels to one-hot encoding
num_classes = 10
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 20 batches
num_batches = 20
batch_size = len(x_train) // num_batches

x_train_batches = np.array_split(x_train, num_batches)
y_train_batches = np.array_split(y_train, num_batches)

# Define the CrlB regularizer
class CrlBRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization

# Define the original MNIST model
model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(num_classes, activation='softmax')
])

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the original model on Task A
model.fit(x_train_batches[0], y_train_batches[0], batch_size=batch_size, epochs=10, validation_data=(x_test, y_test))

# Save the weights of the original model for later use
prior_weights = model.get_weights()

# Compute the Fisher Information matrix
def compute_fisher(model, x, num_samples=200):
    fisher_matrix = []
    for i in range(len(model.trainable_weights)):
        fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

    for _ in range(num_samples):
        idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
        with tf.GradientTape() as tape:
            logits = model(x[idx:idx+1])
        gradients = tape.gradient(logits, model.trainable_weights)
        for i in range(len(fisher_matrix)):
            fisher_matrix[i] += tf.square(gradients[i])

    fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
    return fisher_matrix

# Compute the Fisher Information matrix for each batch
fisher_matrices = []
for i in range(num_batches):
    fisher_matrix = compute_fisher(model, x_train_batches[i])
    fisher_matrices.append(fisher_matrix)

# Define the new model with CrlB regularization
model_CrlB = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu', kernel_regularizer=CrlBRegularizer(model, fisher_matrices[0], prior_weights, lambda_=0.1)),
    Dense(num_classes, activation='softmax', kernel_regularizer=CrlBRegularizer(model, fisher_matrices[0], prior_weights, lambda_=0.1))
])

# Compile the model with CrlB regularization
model_CrlB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on Task B with CrlB regularization for each batch
for i in range(num_batches):
    model_CrlB.fit(x_train_batches[i], y_train_batches[i], batch_size=batch_size, epochs=10, validation_data=(x_test, y_test))

Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
11490434/11490434 [==============================] - 0s 0us/step
Epoch 1/10
1/1 [==============================] - 3s 3s/step - loss: 2.3140 - accuracy: 0.1203 - val_loss: 2.1684 - val_accuracy: 0.2441
Epoch 2/10
1/1 [==============================] - 0s 70ms/step - loss: 2.1585 - accuracy: 0.2590 - val_loss: 2.0320 - val_accuracy: 0.4173
Epoch 3/10
1/1 [==============================] - 0s 101ms/step - loss: 2.0179 - accuracy: 0.4357 - val_loss: 1.9055 - val_accuracy: 0.5302
Epoch 4/10
1/1 [==============================] - 0s 103ms/step - loss: 1.8875 - accuracy: 0.5550 - val_loss: 1.7859 - val_accuracy: 0.6057
Epoch 5/10
1/1 [==============================] - 0s 71ms/step - loss: 1.7637 - accuracy: 0.6297 - val_loss: 1.6713 - val_accuracy: 0.6592
Epoch 6/10
1/1 [==============================] - 0s 100ms/step - loss: 1.6452 - accuracy: 0.6867 - val_loss: 1.5614 - val_accuracy: 0.6938
Epoch 7/10
1/1 [==============================] - 0s 101ms/step - loss: 1.5316 - accuracy: 0.7267 - val_loss: 1.4565 - val_accuracy: 0.7170
Epoch 8/10
1/1 [==============================] - 0s 69ms/step - loss: 1.4230 - accuracy: 0.7540 - val_loss: 1.3572 - val_accuracy: 0.7400
Epoch 9/10
1/1 [==============================] - 0s 98ms/step - loss: 1.3207 - accuracy: 0.7710 - val_loss: 1.2645 - val_accuracy: 0.7540
Epoch 10/10
1/1 [==============================] - 0s 98ms/step - loss: 1.2256 - accuracy: 0.7863 - val_loss: 1.1792 - val_accuracy: 0.7670
Epoch 1/10
1/1 [==============================] - 2s 2s/step - loss: 2.4552 - accuracy: 0.0807 - val_loss: 2.2754 - val_accuracy: 0.1195
Epoch 2/10
1/1 [==============================] - 0s 132ms/step - loss: 2.2683 - accuracy: 0.1203 - val_loss: 2.1318 - val_accuracy: 0.2102
Epoch 3/10
1/1 [==============================] - 0s 129ms/step - loss: 2.1163 - accuracy: 0.2180 - val_loss: 2.0091 - val_accuracy: 0.4054
Epoch 4/10
1/1 [==============================] - 0s 137ms/step - loss: 1.9858 - accuracy: 0.4233 - val_loss: 1.8983 - val_accuracy: 0.5417
Epoch 5/10
1/1 [==============================] - 0s 93ms/step - loss: 1.8681 - accuracy: 0.5843 - val_loss: 1.7935 - val_accuracy: 0.6047
Epoch 6/10
1/1 [==============================] - 0s 104ms/step - loss: 1.7568 - accuracy: 0.6617 - val_loss: 1.6912 - val_accuracy: 0.6469
Epoch 7/10
1/1 [==============================] - 0s 116ms/step - loss: 1.6490 - accuracy: 0.6937 - val_loss: 1.5904 - val_accuracy: 0.6790
Epoch 8/10
1/1 [==============================] - 0s 98ms/step - loss: 1.5434 - accuracy: 0.7223 - val_loss: 1.4916 - val_accuracy: 0.7056
Epoch 9/10
1/1 [==============================] - 0s 88ms/step - loss: 1.4407 - accuracy: 0.7443 - val_loss: 1.3959 - val_accuracy: 0.7274
Epoch 10/10
1/1 [==============================] - 0s 82ms/step - loss: 1.3421 - accuracy: 0.7617 - val_loss: 1.3048 - val_accuracy: 0.7447
Epoch 1/10
1/1 [==============================] - 0s 153ms/step - loss: 1.2833 - accuracy: 0.7513 - val_loss: 1.2187 - val_accuracy: 0.7645
Epoch 2/10
1/1 [==============================] - 0s 103ms/step - loss: 1.1970 - accuracy: 0.7703 - val_loss: 1.1388 - val_accuracy: 0.7832
Epoch 3/10
1/1 [==============================] - 0s 104ms/step - loss: 1.1162 - accuracy: 0.7837 - val_loss: 1.0660 - val_accuracy: 0.7959
Epoch 4/10
1/1 [==============================] - 0s 78ms/step - loss: 1.0419 - accuracy: 0.8000 - val_loss: 1.0005 - val_accuracy: 0.8052
Epoch 5/10
1/1 [==============================] - 0s 102ms/step - loss: 0.9742 - accuracy: 0.8113 - val_loss: 0.9417 - val_accuracy: 0.8091
Epoch 6/10
1/1 [==============================] - 0s 71ms/step - loss: 0.9130 - accuracy: 0.8230 - val_loss: 0.8886 - val_accuracy: 0.8157
Epoch 7/10
1/1 [==============================] - 0s 97ms/step - loss: 0.8573 - accuracy: 0.8283 - val_loss: 0.8403 - val_accuracy: 0.8195
Epoch 8/10
1/1 [==============================] - 0s 71ms/step - loss: 0.8066 - accuracy: 0.8333 - val_loss: 0.7963 - val_accuracy: 0.8242
Epoch 9/10
1/1 [==============================] - 0s 98ms/step - loss: 0.7606 - accuracy: 0.8390 - val_loss: 0.7563 - val_accuracy: 0.8295
Epoch 10/10
1/1 [==============================] - 0s 66ms/step - loss: 0.7189 - accuracy: 0.8460 - val_loss: 0.7199 - val_accuracy: 0.8338
Epoch 1/10
1/1 [==============================] - 0s 174ms/step - loss: 0.7576 - accuracy: 0.8160 - val_loss: 0.6864 - val_accuracy: 0.8425
Epoch 2/10
1/1 [==============================] - 0s 100ms/step - loss: 0.7235 - accuracy: 0.8233 - val_loss: 0.6568 - val_accuracy: 0.8469
Epoch 3/10
1/1 [==============================] - 0s 101ms/step - loss: 0.6921 - accuracy: 0.8283 - val_loss: 0.6314 - val_accuracy: 0.8511
Epoch 4/10
1/1 [==============================] - 0s 65ms/step - loss: 0.6643 - accuracy: 0.8323 - val_loss: 0.6098 - val_accuracy: 0.8528
Epoch 5/10
1/1 [==============================] - 0s 64ms/step - loss: 0.6399 - accuracy: 0.8363 - val_loss: 0.5906 - val_accuracy: 0.8562
Epoch 6/10
1/1 [==============================] - 0s 101ms/step - loss: 0.6178 - accuracy: 0.8437 - val_loss: 0.5728 - val_accuracy: 0.8588
Epoch 7/10
1/1 [==============================] - 0s 101ms/step - loss: 0.5973 - accuracy: 0.8493 - val_loss: 0.5557 - val_accuracy: 0.8610
Epoch 8/10
1/1 [==============================] - 0s 99ms/step - loss: 0.5776 - accuracy: 0.8527 - val_loss: 0.5395 - val_accuracy: 0.8622
Epoch 9/10
1/1 [==============================] - 0s 100ms/step - loss: 0.5589 - accuracy: 0.8560 - val_loss: 0.5244 - val_accuracy: 0.8666
Epoch 10/10
1/1 [==============================] - 0s 100ms/step - loss: 0.5415 - accuracy: 0.8567 - val_loss: 0.5106 - val_accuracy: 0.8688
Epoch 1/10
1/1 [==============================] - 0s 125ms/step - loss: 0.4817 - accuracy: 0.8793 - val_loss: 0.4978 - val_accuracy: 0.8704
Epoch 2/10
1/1 [==============================] - 0s 105ms/step - loss: 0.4685 - accuracy: 0.8803 - val_loss: 0.4866 - val_accuracy: 0.8715
Epoch 3/10
1/1 [==============================] - 0s 102ms/step - loss: 0.4557 - accuracy: 0.8837 - val_loss: 0.4770 - val_accuracy: 0.8737
Epoch 4/10
1/1 [==============================] - 0s 102ms/step - loss: 0.4437 - accuracy: 0.8850 - val_loss: 0.4688 - val_accuracy: 0.8752
Epoch 5/10
1/1 [==============================] - 0s 72ms/step - loss: 0.4326 - accuracy: 0.8867 - val_loss: 0.4618 - val_accuracy: 0.8769
Epoch 6/10
1/1 [==============================] - 0s 103ms/step - loss: 0.4222 - accuracy: 0.8910 - val_loss: 0.4554 - val_accuracy: 0.8778
Epoch 7/10
1/1 [==============================] - 0s 105ms/step - loss: 0.4123 - accuracy: 0.8943 - val_loss: 0.4494 - val_accuracy: 0.8793
Epoch 8/10
1/1 [==============================] - 0s 110ms/step - loss: 0.4026 - accuracy: 0.8967 - val_loss: 0.4435 - val_accuracy: 0.8801
Epoch 9/10
1/1 [==============================] - 0s 64ms/step - loss: 0.3931 - accuracy: 0.8990 - val_loss: 0.4377 - val_accuracy: 0.8813
Epoch 10/10
1/1 [==============================] - 0s 99ms/step - loss: 0.3839 - accuracy: 0.9020 - val_loss: 0.4320 - val_accuracy: 0.8828
Epoch 1/10
1/1 [==============================] - 0s 169ms/step - loss: 0.5260 - accuracy: 0.8487 - val_loss: 0.4252 - val_accuracy: 0.8840
Epoch 2/10
1/1 [==============================] - 0s 103ms/step - loss: 0.5174 - accuracy: 0.8483 - val_loss: 0.4185 - val_accuracy: 0.8851
Epoch 3/10
1/1 [==============================] - 0s 66ms/step - loss: 0.5072 - accuracy: 0.8510 - val_loss: 0.4127 - val_accuracy: 0.8860
Epoch 4/10
1/1 [==============================] - 0s 98ms/step - loss: 0.4970 - accuracy: 0.8540 - val_loss: 0.4076 - val_accuracy: 0.8867
Epoch 5/10
1/1 [==============================] - 0s 101ms/step - loss: 0.4871 - accuracy: 0.8537 - val_loss: 0.4025 - val_accuracy: 0.8890
Epoch 6/10
1/1 [==============================] - 0s 103ms/step - loss: 0.4772 - accuracy: 0.8557 - val_loss: 0.3971 - val_accuracy: 0.8911
Epoch 7/10
1/1 [==============================] - 0s 106ms/step - loss: 0.4671 - accuracy: 0.8583 - val_loss: 0.3915 - val_accuracy: 0.8924
Epoch 8/10
1/1 [==============================] - 0s 64ms/step - loss: 0.4570 - accuracy: 0.8640 - val_loss: 0.3862 - val_accuracy: 0.8953
Epoch 9/10
1/1 [==============================] - 0s 98ms/step - loss: 0.4473 - accuracy: 0.8673 - val_loss: 0.3818 - val_accuracy: 0.8963
Epoch 10/10
1/1 [==============================] - 0s 98ms/step - loss: 0.4384 - accuracy: 0.8710 - val_loss: 0.3782 - val_accuracy: 0.8967
Epoch 1/10
1/1 [==============================] - 0s 142ms/step - loss: 0.4239 - accuracy: 0.8797 - val_loss: 0.3749 - val_accuracy: 0.8981
Epoch 2/10
1/1 [==============================] - 0s 102ms/step - loss: 0.4190 - accuracy: 0.8830 - val_loss: 0.3720 - val_accuracy: 0.8993
Epoch 3/10
1/1 [==============================] - 0s 103ms/step - loss: 0.4135 - accuracy: 0.8833 - val_loss: 0.3692 - val_accuracy: 0.8994
Epoch 4/10
1/1 [==============================] - 0s 108ms/step - loss: 0.4076 - accuracy: 0.8867 - val_loss: 0.3664 - val_accuracy: 0.9002
Epoch 5/10
1/1 [==============================] - 0s 100ms/step - loss: 0.4014 - accuracy: 0.8870 - val_loss: 0.3634 - val_accuracy: 0.9011
Epoch 6/10
1/1 [==============================] - 0s 67ms/step - loss: 0.3950 - accuracy: 0.8887 - val_loss: 0.3603 - val_accuracy: 0.9020
Epoch 7/10
1/1 [==============================] - 0s 106ms/step - loss: 0.3885 - accuracy: 0.8913 - val_loss: 0.3570 - val_accuracy: 0.9024
Epoch 8/10
1/1 [==============================] - 0s 74ms/step - loss: 0.3820 - accuracy: 0.8943 - val_loss: 0.3536 - val_accuracy: 0.9034
Epoch 9/10
1/1 [==============================] - 0s 102ms/step - loss: 0.3755 - accuracy: 0.8957 - val_loss: 0.3502 - val_accuracy: 0.9051
Epoch 10/10
1/1 [==============================] - 0s 98ms/step - loss: 0.3692 - accuracy: 0.8977 - val_loss: 0.3468 - val_accuracy: 0.9061
Epoch 1/10
1/1 [==============================] - 0s 149ms/step - loss: 0.3445 - accuracy: 0.9077 - val_loss: 0.3430 - val_accuracy: 0.9072
Epoch 2/10
1/1 [==============================] - 0s 101ms/step - loss: 0.3403 - accuracy: 0.9117 - val_loss: 0.3393 - val_accuracy: 0.9093
Epoch 3/10
1/1 [==============================] - 0s 108ms/step - loss: 0.3354 - accuracy: 0.9123 - val_loss: 0.3359 - val_accuracy: 0.9103
Epoch 4/10
1/1 [==============================] - 0s 65ms/step - loss: 0.3301 - accuracy: 0.9173 - val_loss: 0.3330 - val_accuracy: 0.9111
Epoch 5/10
1/1 [==============================] - 0s 68ms/step - loss: 0.3246 - accuracy: 0.9177 - val_loss: 0.3304 - val_accuracy: 0.9116
Epoch 6/10
1/1 [==============================] - 0s 99ms/step - loss: 0.3192 - accuracy: 0.9193 - val_loss: 0.3283 - val_accuracy: 0.9113
Epoch 7/10
1/1 [==============================] - 0s 101ms/step - loss: 0.3139 - accuracy: 0.9193 - val_loss: 0.3265 - val_accuracy: 0.9106
Epoch 8/10
1/1 [==============================] - 0s 101ms/step - loss: 0.3088 - accuracy: 0.9210 - val_loss: 0.3252 - val_accuracy: 0.9101
Epoch 9/10
1/1 [==============================] - 0s 101ms/step - loss: 0.3040 - accuracy: 0.9213 - val_loss: 0.3241 - val_accuracy: 0.9099
Epoch 10/10
1/1 [==============================] - 0s 100ms/step - loss: 0.2993 - accuracy: 0.9223 - val_loss: 0.3231 - val_accuracy: 0.9097
Epoch 1/10
1/1 [==============================] - 0s 134ms/step - loss: 0.3301 - accuracy: 0.9097 - val_loss: 0.3214 - val_accuracy: 0.9097
Epoch 2/10
1/1 [==============================] - 0s 75ms/step - loss: 0.3272 - accuracy: 0.9100 - val_loss: 0.3195 - val_accuracy: 0.9109
Epoch 3/10
1/1 [==============================] - 0s 66ms/step - loss: 0.3231 - accuracy: 0.9100 - val_loss: 0.3175 - val_accuracy: 0.9105
Epoch 4/10
1/1 [==============================] - 0s 100ms/step - loss: 0.3185 - accuracy: 0.9123 - val_loss: 0.3156 - val_accuracy: 0.9117
Epoch 5/10
1/1 [==============================] - 0s 100ms/step - loss: 0.3136 - accuracy: 0.9153 - val_loss: 0.3138 - val_accuracy: 0.9121
Epoch 6/10
1/1 [==============================] - 0s 102ms/step - loss: 0.3087 - accuracy: 0.9163 - val_loss: 0.3121 - val_accuracy: 0.9127
Epoch 7/10
1/1 [==============================] - 0s 69ms/step - loss: 0.3037 - accuracy: 0.9177 - val_loss: 0.3104 - val_accuracy: 0.9140
Epoch 8/10
1/1 [==============================] - 0s 71ms/step - loss: 0.2987 - accuracy: 0.9187 - val_loss: 0.3087 - val_accuracy: 0.9145
Epoch 9/10
1/1 [==============================] - 0s 63ms/step - loss: 0.2936 - accuracy: 0.9210 - val_loss: 0.3072 - val_accuracy: 0.9158
Epoch 10/10
1/1 [==============================] - 0s 100ms/step - loss: 0.2886 - accuracy: 0.9223 - val_loss: 0.3057 - val_accuracy: 0.9164
Epoch 1/10
1/1 [==============================] - 0s 162ms/step - loss: 0.3307 - accuracy: 0.9077 - val_loss: 0.3040 - val_accuracy: 0.9176
Epoch 2/10
1/1 [==============================] - 0s 109ms/step - loss: 0.3262 - accuracy: 0.9100 - val_loss: 0.3030 - val_accuracy: 0.9178
Epoch 3/10
1/1 [==============================] - 0s 102ms/step - loss: 0.3211 - accuracy: 0.9120 - val_loss: 0.3030 - val_accuracy: 0.9166
Epoch 4/10
1/1 [==============================] - 0s 64ms/step - loss: 0.3166 - accuracy: 0.9143 - val_loss: 0.3035 - val_accuracy: 0.9175
Epoch 5/10
1/1 [==============================] - 0s 101ms/step - loss: 0.3127 - accuracy: 0.9150 - val_loss: 0.3036 - val_accuracy: 0.9166
Epoch 6/10
1/1 [==============================] - 0s 72ms/step - loss: 0.3087 - accuracy: 0.9157 - val_loss: 0.3026 - val_accuracy: 0.9163
Epoch 7/10
1/1 [==============================] - 0s 101ms/step - loss: 0.3042 - accuracy: 0.9160 - val_loss: 0.3007 - val_accuracy: 0.9172
Epoch 8/10
1/1 [==============================] - 0s 100ms/step - loss: 0.2993 - accuracy: 0.9187 - val_loss: 0.2984 - val_accuracy: 0.9168
Epoch 9/10
1/1 [==============================] - 0s 98ms/step - loss: 0.2944 - accuracy: 0.9200 - val_loss: 0.2962 - val_accuracy: 0.9179
Epoch 10/10
1/1 [==============================] - 0s 67ms/step - loss: 0.2898 - accuracy: 0.9223 - val_loss: 0.2946 - val_accuracy: 0.9180
Epoch 1/10
1/1 [==============================] - 0s 142ms/step - loss: 0.3144 - accuracy: 0.9133 - val_loss: 0.2928 - val_accuracy: 0.9190
Epoch 2/10
1/1 [==============================] - 0s 62ms/step - loss: 0.3115 - accuracy: 0.9127 - val_loss: 0.2913 - val_accuracy: 0.9190
Epoch 3/10
1/1 [==============================] - 0s 98ms/step - loss: 0.3082 - accuracy: 0.9143 - val_loss: 0.2901 - val_accuracy: 0.9187
Epoch 4/10
1/1 [==============================] - 0s 94ms/step - loss: 0.3045 - accuracy: 0.9150 - val_loss: 0.2891 - val_accuracy: 0.9193
Epoch 5/10
1/1 [==============================] - 0s 113ms/step - loss: 0.3005 - accuracy: 0.9183 - val_loss: 0.2880 - val_accuracy: 0.9194
Epoch 6/10
1/1 [==============================] - 0s 86ms/step - loss: 0.2962 - accuracy: 0.9180 - val_loss: 0.2868 - val_accuracy: 0.9189
Epoch 7/10
1/1 [==============================] - 0s 92ms/step - loss: 0.2915 - accuracy: 0.9193 - val_loss: 0.2855 - val_accuracy: 0.9197
Epoch 8/10
1/1 [==============================] - 0s 111ms/step - loss: 0.2868 - accuracy: 0.9203 - val_loss: 0.2843 - val_accuracy: 0.9208
Epoch 9/10
1/1 [==============================] - 0s 92ms/step - loss: 0.2822 - accuracy: 0.9220 - val_loss: 0.2831 - val_accuracy: 0.9209
Epoch 10/10
1/1 [==============================] - 0s 96ms/step - loss: 0.2778 - accuracy: 0.9237 - val_loss: 0.2821 - val_accuracy: 0.9208
Epoch 1/10
1/1 [==============================] - 0s 197ms/step - loss: 0.3464 - accuracy: 0.8970 - val_loss: 0.2803 - val_accuracy: 0.9227
Epoch 2/10
1/1 [==============================] - 0s 79ms/step - loss: 0.3437 - accuracy: 0.8980 - val_loss: 0.2784 - val_accuracy: 0.9226
Epoch 3/10
1/1 [==============================] - 0s 88ms/step - loss: 0.3398 - accuracy: 0.8997 - val_loss: 0.2769 - val_accuracy: 0.9228
Epoch 4/10
1/1 [==============================] - 0s 75ms/step - loss: 0.3356 - accuracy: 0.9020 - val_loss: 0.2756 - val_accuracy: 0.9230
Epoch 5/10
1/1 [==============================] - 0s 75ms/step - loss: 0.3311 - accuracy: 0.9033 - val_loss: 0.2743 - val_accuracy: 0.9232
Epoch 6/10
1/1 [==============================] - 0s 97ms/step - loss: 0.3261 - accuracy: 0.9053 - val_loss: 0.2728 - val_accuracy: 0.9239
Epoch 7/10
1/1 [==============================] - 0s 113ms/step - loss: 0.3208 - accuracy: 0.9080 - val_loss: 0.2712 - val_accuracy: 0.9247
Epoch 8/10
1/1 [==============================] - 0s 117ms/step - loss: 0.3152 - accuracy: 0.9097 - val_loss: 0.2699 - val_accuracy: 0.9239
Epoch 9/10
1/1 [==============================] - 0s 117ms/step - loss: 0.3098 - accuracy: 0.9107 - val_loss: 0.2690 - val_accuracy: 0.9244
Epoch 10/10
1/1 [==============================] - 0s 110ms/step - loss: 0.3047 - accuracy: 0.9120 - val_loss: 0.2683 - val_accuracy: 0.9248
Epoch 1/10
1/1 [==============================] - 0s 140ms/step - loss: 0.2581 - accuracy: 0.9237 - val_loss: 0.2673 - val_accuracy: 0.9252
Epoch 2/10
1/1 [==============================] - 0s 64ms/step - loss: 0.2564 - accuracy: 0.9247 - val_loss: 0.2660 - val_accuracy: 0.9256
Epoch 3/10
1/1 [==============================] - 0s 63ms/step - loss: 0.2532 - accuracy: 0.9270 - val_loss: 0.2650 - val_accuracy: 0.9259
Epoch 4/10
1/1 [==============================] - 0s 66ms/step - loss: 0.2494 - accuracy: 0.9283 - val_loss: 0.2646 - val_accuracy: 0.9260
Epoch 5/10
1/1 [==============================] - 0s 69ms/step - loss: 0.2455 - accuracy: 0.9327 - val_loss: 0.2650 - val_accuracy: 0.9270
Epoch 6/10
1/1 [==============================] - 0s 66ms/step - loss: 0.2421 - accuracy: 0.9337 - val_loss: 0.2657 - val_accuracy: 0.9260
Epoch 7/10
1/1 [==============================] - 0s 99ms/step - loss: 0.2390 - accuracy: 0.9357 - val_loss: 0.2663 - val_accuracy: 0.9256
Epoch 8/10
1/1 [==============================] - 0s 109ms/step - loss: 0.2361 - accuracy: 0.9353 - val_loss: 0.2664 - val_accuracy: 0.9265
Epoch 9/10
1/1 [==============================] - 0s 99ms/step - loss: 0.2328 - accuracy: 0.9370 - val_loss: 0.2658 - val_accuracy: 0.9271
Epoch 10/10
1/1 [==============================] - 0s 67ms/step - loss: 0.2293 - accuracy: 0.9377 - val_loss: 0.2647 - val_accuracy: 0.9269
Epoch 1/10
1/1 [==============================] - 0s 126ms/step - loss: 0.2998 - accuracy: 0.9133 - val_loss: 0.2627 - val_accuracy: 0.9273
Epoch 2/10
1/1 [==============================] - 0s 101ms/step - loss: 0.2960 - accuracy: 0.9147 - val_loss: 0.2609 - val_accuracy: 0.9277
Epoch 3/10
1/1 [==============================] - 0s 65ms/step - loss: 0.2916 - accuracy: 0.9143 - val_loss: 0.2599 - val_accuracy: 0.9279
Epoch 4/10
1/1 [==============================] - 0s 66ms/step - loss: 0.2874 - accuracy: 0.9150 - val_loss: 0.2595 - val_accuracy: 0.9284
Epoch 5/10
1/1 [==============================] - 0s 102ms/step - loss: 0.2835 - accuracy: 0.9177 - val_loss: 0.2588 - val_accuracy: 0.9291
Epoch 6/10
1/1 [==============================] - 0s 66ms/step - loss: 0.2793 - accuracy: 0.9180 - val_loss: 0.2573 - val_accuracy: 0.9280
Epoch 7/10
1/1 [==============================] - 0s 104ms/step - loss: 0.2745 - accuracy: 0.9203 - val_loss: 0.2552 - val_accuracy: 0.9280
Epoch 8/10
1/1 [==============================] - 0s 67ms/step - loss: 0.2694 - accuracy: 0.9197 - val_loss: 0.2532 - val_accuracy: 0.9281
Epoch 9/10
1/1 [==============================] - 0s 101ms/step - loss: 0.2644 - accuracy: 0.9230 - val_loss: 0.2518 - val_accuracy: 0.9284
Epoch 10/10
1/1 [==============================] - 0s 99ms/step - loss: 0.2599 - accuracy: 0.9237 - val_loss: 0.2512 - val_accuracy: 0.9291
Epoch 1/10
1/1 [==============================] - 0s 166ms/step - loss: 0.2719 - accuracy: 0.9210 - val_loss: 0.2510 - val_accuracy: 0.9288
Epoch 2/10
1/1 [==============================] - 0s 100ms/step - loss: 0.2696 - accuracy: 0.9210 - val_loss: 0.2516 - val_accuracy: 0.9293
Epoch 3/10

### SVHN

In [ ]:
!wget http://ufldl.stanford.edu/housenumbers/train_32x32.mat
!wget http://ufldl.stanford.edu/housenumbers/test_32x32.mat

--2023-08-01 14:19:15--  http://ufldl.stanford.edu/housenumbers/train_32x32.mat
Resolving ufldl.stanford.edu (ufldl.stanford.edu)... 171.64.68.10
Connecting to ufldl.stanford.edu (ufldl.stanford.edu)|171.64.68.10|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 182040794 (174M) [text/plain]
Saving to: ‘train_32x32.mat’

train_32x32.mat     100%[===================>] 173.61M  42.0MB/s    in 6.9s

2023-08-01 14:19:22 (25.2 MB/s) - ‘train_32x32.mat’ saved [182040794/182040794]

--2023-08-01 14:19:22--  http://ufldl.stanford.edu/housenumbers/test_32x32.mat
Resolving ufldl.stanford.edu (ufldl.stanford.edu)... 171.64.68.10
Connecting to ufldl.stanford.edu (ufldl.stanford.edu)|171.64.68.10|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 64275384 (61M) [text/plain]
Saving to: ‘test_32x32.mat’

test_32x32.mat      100%[===================>]  61.30M  19.2MB/s    in 4.2s

2023-08-01 14:19:26 (14.7 MB/s) - ‘test_32x32.mat’ saved [64275384/64275384]

In [ ]:
import numpy as np
from tensorflow import keras
from sklearn.model_selection import KFold
import scipy.io as sio
from tensorflow.keras.utils import to_categorical
# Define the model architecture
def create_model():
    model = keras.Sequential([
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(64, activation='relu'),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])

    return model


# Load the SVHN dataset
train_data = sio.loadmat("train_32x32.mat")
test_data = sio.loadmat("test_32x32.mat")

# Extract the images and labels from the downloaded data
train_images = np.transpose(train_data['X'], (3, 0, 1, 2))
train_labels = train_data['y']

test_images = np.transpose(test_data['X'], (3, 0, 1, 2))
test_labels = test_data['y']

# Change class labels to range from 0 to 9
train_labels[train_labels == 10] = 0
test_labels[test_labels == 10] = 0

# Perform one-hot encoding on the labels
num_classes = 10
train_labels = to_categorical(train_labels, num_classes)
test_labels = to_categorical(test_labels, num_classes)

# Print the shape of the loaded data
print("Train images shape:", train_images.shape)
print("Train labels shape:", train_labels.shape)
print("Test images shape:", test_images.shape)
print("Test labels shape:", test_labels.shape)

# Concatenate the entire dataset
x = np.concatenate((train_images, test_images), axis=0)
y = np.concatenate((train_labels, test_labels), axis=0)
# Split the data into training and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
print(x.shape, y.shape)
# Define the number of folds for cross-validation
# k = 2
# kf = KFold(n_splits=k, shuffle=True, random_state=42)

# train_images = x
# train_labels = y
accuracies = []

# Perform k-fold cross-validation
# for train_idx, val_idx in kf.split(train_images):
    # Create a new instance of the model for each fold
model = create_model()

    # Train the model on the current fold
model.fit(x_train, y_train, epochs=5, batch_size=32, verbose=1)

    # Evaluate the model on the validation fold
_, accuracy = model.evaluate(x_test, y_test, verbose=0)

    # Append the accuracy to the list of accuracies
accuracies.append(accuracy)

# Compute the mean and standard deviation of the accuracies
mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)

# Print the results
print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)
# i = 0
# float2 = "{0:.2f}"
# for score in accuracies:
#     percent = score * 100
#     print("Fold-{}: {}%".format(i+1, float2.format(percent)))
#     i = i + 1

Train images shape: (73257, 32, 32, 3)
Train labels shape: (73257, 10)
Test images shape: (26032, 32, 32, 3)
Test labels shape: (26032, 10)
(99289, 32, 32, 3) (99289, 10)
Epoch 1/5
2483/2483 [==============================] - 22s 6ms/step - loss: 1.3062 - accuracy: 0.6357
Epoch 2/5
2483/2483 [==============================] - 13s 5ms/step - loss: 0.6410 - accuracy: 0.8141
Epoch 3/5
2483/2483 [==============================] - 13s 5ms/step - loss: 0.5598 - accuracy: 0.8385
Epoch 4/5
2483/2483 [==============================] - 13s 5ms/step - loss: 0.5164 - accuracy: 0.8497
Epoch 5/5
2483/2483 [==============================] - 14s 5ms/step - loss: 0.4839 - accuracy: 0.8580
Mean accuracy: 0.8509416580200195
Standard deviation: 0.0

### Caltec101

In [ ]:
import tensorflow_datasets as tfds
import numpy as np
from skimage.transform import resize

# Load the Caltech 101 dataset
dataset_name = "caltech101"
builder = tfds.builder(dataset_name)

# Download and prepare the dataset
builder.download_and_prepare()

# Split the dataset into training and testing sets
train_dataset = builder.as_dataset(split="train")
test_dataset = builder.as_dataset(split="test")

# Iterate through the datasets to get features and labels
X_train = []
y_train = []
for example in tfds.as_numpy(train_dataset):
    X_train.append(example["image"])
    y_train.append(example["label"])

X_test = []
y_test = []
for example in tfds.as_numpy(test_dataset):
    X_test.append(example["image"])
    y_test.append(example["label"])

# Convert lists to numpy arrays
X_train = np.array(X_train)
y_train = np.array(y_train)
X_test = np.array(X_test)
y_test = np.array(y_test)

# Resize the image data to a common size
target_height, target_width, channels = 28, 28, 3
X_train_resized = np.array([resize(image, (target_height, target_width, channels)) for image in X_train])
X_test_resized = np.array([resize(image, (target_height, target_width, channels)) for image in X_test])

# Print the shape of the resized arrays
print("X_train resized shape:", X_train_resized.shape)
print("X_test resized shape:", X_test_resized.shape)

Downloading and preparing dataset 125.64 MiB (download: 125.64 MiB, generated: 132.86 MiB, total: 258.50 MiB) to /root/tensorflow_datasets/caltech101/3.0.1...

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

Generating splits...:   0%|          | 0/2 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/3060 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/caltech101/3.0.1.incomplete452ODY/caltech101-train.tfrecord*...:   0%|    …

Generating test examples...:   0%|          | 0/6084 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/caltech101/3.0.1.incomplete452ODY/caltech101-test.tfrecord*...:   0%|     …

Dataset caltech101 downloaded and prepared to /root/tensorflow_datasets/caltech101/3.0.1. Subsequent calls will reuse this data.

<ipython-input-1-d3b8c391cf7a>:30: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  X_train = np.array(X_train)
<ipython-input-1-d3b8c391cf7a>:32: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  X_test = np.array(X_test)

X_train resized shape: (3060, 28, 28, 3)
X_test resized shape: (6084, 28, 28, 3)

In [ ]:
import tensorflow as tf
y_train = tf.keras.utils.to_categorical(y_train, num_classes=102)
y_test = tf.keras.utils.to_categorical(y_test, num_classes=102)

In [ ]:
import tensorflow as tf
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras import layers
# Define the model architecture
num_classes = 102
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(28, 28, 3)),
    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu'),
    layers.Dropout(0.25),
    Dense(num_classes, activation='softmax')
])

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the original model on Task A
model.fit(X_train_resized, y_train, batch_size=128, epochs=100, validation_data=(X_test_resized, y_test))


# Evaluate the model on the test set
_, test_accuracy = model.evaluate(X_test_resized, y_test, verbose=0)
print("Test Accuracy:", test_accuracy)

Epoch 1/100
24/24 [==============================] - 5s 51ms/step - loss: 4.6232 - accuracy: 0.0118 - val_loss: 4.5921 - val_accuracy: 0.0192
Epoch 2/100
24/24 [==============================] - 1s 28ms/step - loss: 4.5197 - accuracy: 0.0304 - val_loss: 4.4317 - val_accuracy: 0.0398
Epoch 3/100
24/24 [==============================] - 1s 25ms/step - loss: 4.2669 - accuracy: 0.0748 - val_loss: 3.7993 - val_accuracy: 0.2076
Epoch 4/100
24/24 [==============================] - 1s 24ms/step - loss: 3.8467 - accuracy: 0.1529 - val_loss: 3.3418 - val_accuracy: 0.2717
Epoch 5/100
24/24 [==============================] - 1s 24ms/step - loss: 3.3977 - accuracy: 0.2284 - val_loss: 3.2361 - val_accuracy: 0.3036
Epoch 6/100
24/24 [==============================] - 1s 27ms/step - loss: 3.0177 - accuracy: 0.2928 - val_loss: 2.7079 - val_accuracy: 0.4086
Epoch 7/100
24/24 [==============================] - 1s 28ms/step - loss: 2.6132 - accuracy: 0.3703 - val_loss: 2.7205 - val_accuracy: 0.4177
Epoch 8/100
24/24 [==============================] - 1s 27ms/step - loss: 2.2211 - accuracy: 0.4435 - val_loss: 2.5102 - val_accuracy: 0.4633
Epoch 9/100
24/24 [==============================] - 1s 29ms/step - loss: 1.8408 - accuracy: 0.5216 - val_loss: 2.5158 - val_accuracy: 0.4691
Epoch 10/100
24/24 [==============================] - 1s 29ms/step - loss: 1.5168 - accuracy: 0.5915 - val_loss: 2.4409 - val_accuracy: 0.5005
Epoch 11/100
24/24 [==============================] - 1s 31ms/step - loss: 1.1959 - accuracy: 0.6748 - val_loss: 2.5813 - val_accuracy: 0.4910
Epoch 12/100
24/24 [==============================] - 1s 33ms/step - loss: 0.9459 - accuracy: 0.7422 - val_loss: 2.6512 - val_accuracy: 0.5171
Epoch 13/100
24/24 [==============================] - 1s 28ms/step - loss: 0.7922 - accuracy: 0.7794 - val_loss: 2.8220 - val_accuracy: 0.5105
Epoch 14/100
24/24 [==============================] - 1s 28ms/step - loss: 0.5913 - accuracy: 0.8281 - val_loss: 3.0007 - val_accuracy: 0.5062
Epoch 15/100
24/24 [==============================] - 1s 24ms/step - loss: 0.5201 - accuracy: 0.8461 - val_loss: 3.0489 - val_accuracy: 0.5002
Epoch 16/100
24/24 [==============================] - 1s 27ms/step - loss: 0.4413 - accuracy: 0.8781 - val_loss: 3.0481 - val_accuracy: 0.5220
Epoch 17/100
24/24 [==============================] - 1s 25ms/step - loss: 0.3182 - accuracy: 0.9098 - val_loss: 3.3205 - val_accuracy: 0.5141
Epoch 18/100
24/24 [==============================] - 1s 25ms/step - loss: 0.2591 - accuracy: 0.9235 - val_loss: 3.2775 - val_accuracy: 0.5279
Epoch 19/100
24/24 [==============================] - 1s 24ms/step - loss: 0.2475 - accuracy: 0.9350 - val_loss: 3.3210 - val_accuracy: 0.5191
Epoch 20/100
24/24 [==============================] - 1s 27ms/step - loss: 0.2634 - accuracy: 0.9268 - val_loss: 3.4602 - val_accuracy: 0.5099
Epoch 21/100
24/24 [==============================] - 1s 28ms/step - loss: 0.2421 - accuracy: 0.9248 - val_loss: 3.3791 - val_accuracy: 0.5108
Epoch 22/100
24/24 [==============================] - 1s 27ms/step - loss: 0.1793 - accuracy: 0.9467 - val_loss: 3.3411 - val_accuracy: 0.5370
Epoch 23/100
24/24 [==============================] - 1s 28ms/step - loss: 0.1408 - accuracy: 0.9598 - val_loss: 3.5888 - val_accuracy: 0.5294
Epoch 24/100
24/24 [==============================] - 1s 25ms/step - loss: 0.1450 - accuracy: 0.9539 - val_loss: 3.7254 - val_accuracy: 0.5199
Epoch 25/100
24/24 [==============================] - 1s 24ms/step - loss: 0.1514 - accuracy: 0.9542 - val_loss: 3.6506 - val_accuracy: 0.5243
Epoch 26/100
24/24 [==============================] - 1s 24ms/step - loss: 0.1157 - accuracy: 0.9641 - val_loss: 3.7298 - val_accuracy: 0.5271
Epoch 27/100
24/24 [==============================] - 1s 28ms/step - loss: 0.1319 - accuracy: 0.9598 - val_loss: 3.6174 - val_accuracy: 0.5314
Epoch 28/100
24/24 [==============================] - 1s 28ms/step - loss: 0.0930 - accuracy: 0.9722 - val_loss: 3.8575 - val_accuracy: 0.5312
Epoch 29/100
24/24 [==============================] - 1s 30ms/step - loss: 0.0815 - accuracy: 0.9709 - val_loss: 3.8743 - val_accuracy: 0.5266
Epoch 30/100
24/24 [==============================] - 1s 30ms/step - loss: 0.0976 - accuracy: 0.9680 - val_loss: 3.8923 - val_accuracy: 0.5281
Epoch 31/100
24/24 [==============================] - 1s 35ms/step - loss: 0.0858 - accuracy: 0.9739 - val_loss: 3.8692 - val_accuracy: 0.5317
Epoch 32/100
24/24 [==============================] - 1s 26ms/step - loss: 0.0840 - accuracy: 0.9755 - val_loss: 3.9836 - val_accuracy: 0.5274
Epoch 33/100
24/24 [==============================] - 1s 27ms/step - loss: 0.0952 - accuracy: 0.9722 - val_loss: 3.9218 - val_accuracy: 0.5261
Epoch 34/100
24/24 [==============================] - 1s 24ms/step - loss: 0.0612 - accuracy: 0.9797 - val_loss: 4.1396 - val_accuracy: 0.5204
Epoch 35/100
24/24 [==============================] - 1s 25ms/step - loss: 0.0987 - accuracy: 0.9683 - val_loss: 3.9446 - val_accuracy: 0.5309
Epoch 36/100
24/24 [==============================] - 1s 27ms/step - loss: 0.0856 - accuracy: 0.9768 - val_loss: 3.8654 - val_accuracy: 0.5135
Epoch 37/100
24/24 [==============================] - 1s 28ms/step - loss: 0.0841 - accuracy: 0.9765 - val_loss: 3.7011 - val_accuracy: 0.5422
Epoch 38/100
24/24 [==============================] - 1s 26ms/step - loss: 0.0625 - accuracy: 0.9820 - val_loss: 3.9173 - val_accuracy: 0.5312
Epoch 39/100
24/24 [==============================] - 1s 28ms/step - loss: 0.0565 - accuracy: 0.9827 - val_loss: 4.0591 - val_accuracy: 0.5325
Epoch 40/100
24/24 [==============================] - 1s 28ms/step - loss: 0.0516 - accuracy: 0.9866 - val_loss: 4.2487 - val_accuracy: 0.5197
Epoch 41/100
24/24 [==============================] - 1s 27ms/step - loss: 0.0507 - accuracy: 0.9837 - val_loss: 4.2029 - val_accuracy: 0.5281
Epoch 42/100
24/24 [==============================] - 1s 28ms/step - loss: 0.0718 - accuracy: 0.9794 - val_loss: 3.9269 - val_accuracy: 0.5255
Epoch 43/100
24/24 [==============================] - 1s 28ms/step - loss: 0.0841 - accuracy: 0.9765 - val_loss: 3.7872 - val_accuracy: 0.5273
Epoch 44/100
24/24 [==============================] - 1s 27ms/step - loss: 0.0710 - accuracy: 0.9791 - val_loss: 4.1154 - val_accuracy: 0.5242
Epoch 45/100
24/24 [==============================] - 1s 29ms/step - loss: 0.0731 - accuracy: 0.9771 - val_loss: 4.0178 - val_accuracy: 0.5291
Epoch 46/100
24/24 [==============================] - 1s 28ms/step - loss: 0.0581 - accuracy: 0.9814 - val_loss: 3.9594 - val_accuracy: 0.5228
Epoch 47/100
24/24 [==============================] - 1s 28ms/step - loss: 0.0489 - accuracy: 0.9853 - val_loss: 4.0160 - val_accuracy: 0.5350
Epoch 48/100
24/24 [==============================] - 1s 33ms/step - loss: 0.0489 - accuracy: 0.9846 - val_loss: 4.2718 - val_accuracy: 0.5225
Epoch 49/100
24/24 [==============================] - 1s 34ms/step - loss: 0.0573 - accuracy: 0.9833 - val_loss: 4.3018 - val_accuracy: 0.5370
Epoch 50/100
24/24 [==============================] - 1s 36ms/step - loss: 0.0527 - accuracy: 0.9863 - val_loss: 4.0835 - val_accuracy: 0.5373
Epoch 51/100
24/24 [==============================] - 1s 30ms/step - loss: 0.0483 - accuracy: 0.9856 - val_loss: 4.1546 - val_accuracy: 0.5360
Epoch 52/100
24/24 [==============================] - 1s 24ms/step - loss: 0.0434 - accuracy: 0.9886 - val_loss: 4.1787 - val_accuracy: 0.5329
Epoch 53/100
24/24 [==============================] - 1s 27ms/step - loss: 0.0491 - accuracy: 0.9850 - val_loss: 4.3024 - val_accuracy: 0.5347
Epoch 54/100
24/24 [==============================] - 1s 24ms/step - loss: 0.0633 - accuracy: 0.9814 - val_loss: 4.2002 - val_accuracy: 0.5312
Epoch 55/100
24/24 [==============================] - 1s 27ms/step - loss: 0.0466 - accuracy: 0.9866 - val_loss: 4.2358 - val_accuracy: 0.5317
Epoch 56/100
24/24 [==============================] - 1s 28ms/step - loss: 0.0442 - accuracy: 0.9859 - val_loss: 4.1006 - val_accuracy: 0.5322
Epoch 57/100
24/24 [==============================] - 1s 25ms/step - loss: 0.0387 - accuracy: 0.9895 - val_loss: 4.1804 - val_accuracy: 0.5376
Epoch 58/100
24/24 [==============================] - 1s 27ms/step - loss: 0.0491 - accuracy: 0.9876 - val_loss: 4.3283 - val_accuracy: 0.5375
Epoch 59/100
24/24 [==============================] - 1s 27ms/step - loss: 0.0514 - accuracy: 0.9840 - val_loss: 4.0608 - val_accuracy: 0.5391
Epoch 60/100
24/24 [==============================] - 1s 25ms/step - loss: 0.0471 - accuracy: 0.9850 - val_loss: 4.2235 - val_accuracy: 0.5251
Epoch 61/100
24/24 [==============================] - 1s 27ms/step - loss: 0.0504 - accuracy: 0.9846 - val_loss: 4.4099 - val_accuracy: 0.5212
Epoch 62/100
24/24 [==============================] - 1s 25ms/step - loss: 0.0534 - accuracy: 0.9843 - val_loss: 4.3093 - val_accuracy: 0.5345
Epoch 63/100
24/24 [==============================] - 1s 25ms/step - loss: 0.0402 - accuracy: 0.9859 - val_loss: 4.3894 - val_accuracy: 0.5141
Epoch 64/100
24/24 [==============================] - 1s 24ms/step - loss: 0.0404 - accuracy: 0.9873 - val_loss: 4.4301 - val_accuracy: 0.5255
Epoch 65/100
24/24 [==============================] - 1s 24ms/step - loss: 0.0504 - accuracy: 0.9859 - val_loss: 4.2385 - val_accuracy: 0.5273
Epoch 66/100
24/24 [==============================] - 1s 24ms/step - loss: 0.0500 - accuracy: 0.9846 - val_loss: 4.3739 - val_accuracy: 0.5263
Epoch 67/100
24/24 [==============================] - 1s 27ms/step - loss: 0.0552 - accuracy: 0.9846 - val_loss: 4.5712 - val_accuracy: 0.5046
Epoch 68/100
24/24 [==============================] - 1s 33ms/step - loss: 0.0463 - accuracy: 0.9850 - val_loss: 4.3443 - val_accuracy: 0.5302
Epoch 69/100
24/24 [==============================] - 1s 34ms/step - loss: 0.0373 - accuracy: 0.9902 - val_loss: 4.5181 - val_accuracy: 0.5265
Epoch 70/100
24/24 [==============================] - 1s 32ms/step - loss: 0.0511 - accuracy: 0.9853 - val_loss: 4.4115 - val_accuracy: 0.5322
Epoch 71/100
24/24 [==============================] - 1s 26ms/step - loss: 0.0490 - accuracy: 0.9840 - val_loss: 4.4785 - val_accuracy: 0.5192
Epoch 72/100
24/24 [==============================] - 1s 28ms/step - loss: 0.0558 - accuracy: 0.9840 - val_loss: 4.0283 - val_accuracy: 0.5478
Epoch 73/100
24/24 [==============================] - 1s 25ms/step - loss: 0.0562 - accuracy: 0.9856 - val_loss: 4.4965 - val_accuracy: 0.5376
Epoch 74/100
24/24 [==============================] - 1s 28ms/step - loss: 0.0558 - accuracy: 0.9824 - val_loss: 4.2354 - val_accuracy: 0.5276
Epoch 75/100
24/24 [==============================] - 1s 25ms/step - loss: 0.0443 - accuracy: 0.9840 - val_loss: 4.4003 - val_accuracy: 0.5309
Epoch 76/100
24/24 [==============================] - 1s 28ms/step - loss: 0.0491 - accuracy: 0.9840 - val_loss: 4.6925 - val_accuracy: 0.5309
Epoch 77/100
24/24 [==============================] - 1s 25ms/step - loss: 0.0888 - accuracy: 0.9768 - val_loss: 4.1334 - val_accuracy: 0.5368
Epoch 78/100
24/24 [==============================] - 1s 24ms/step - loss: 0.0556 - accuracy: 0.9850 - val_loss: 4.0956 - val_accuracy: 0.5314
Epoch 79/100
24/24 [==============================] - 1s 28ms/step - loss: 0.0412 - accuracy: 0.9879 - val_loss: 4.2450 - val_accuracy: 0.5339
Epoch 80/100
24/24 [==============================] - 1s 28ms/step - loss: 0.0448 - accuracy: 0.9843 - val_loss: 4.1444 - val_accuracy: 0.5260
Epoch 81/100
24/24 [==============================] - 1s 28ms/step - loss: 0.0352 - accuracy: 0.9892 - val_loss: 4.4117 - val_accuracy: 0.5339
Epoch 82/100
24/24 [==============================] - 1s 28ms/step - loss: 0.0381 - accuracy: 0.9889 - val_loss: 4.4606 - val_accuracy: 0.5329
Epoch 83/100
24/24 [==============================] - 1s 25ms/step - loss: 0.0289 - accuracy: 0.9918 - val_loss: 4.4640 - val_accuracy: 0.5444
Epoch 84/100
24/24 [==============================] - 1s 29ms/step - loss: 0.0268 - accuracy: 0.9915 - val_loss: 4.5347 - val_accuracy: 0.5375
Epoch 85/100
24/24 [==============================] - 1s 28ms/step - loss: 0.0252 - accuracy: 0.9918 - val_loss: 4.6121 - val_accuracy: 0.5365
Epoch 86/100
24/24 [==============================] - 1s 25ms/step - loss: 0.0199 - accuracy: 0.9935 - val_loss: 4.7659 - val_accuracy: 0.5431
Epoch 87/100
24/24 [==============================] - 1s 37ms/step - loss: 0.0256 - accuracy: 0.9938 - val_loss: 4.4976 - val_accuracy: 0.5393
Epoch 88/100
24/24 [==============================] - 1s 35ms/step - loss: 0.0216 - accuracy: 0.9935 - val_loss: 4.4631 - val_accuracy: 0.5391
Epoch 89/100
24/24 [==============================] - 1s 31ms/step - loss: 0.0284 - accuracy: 0.9922 - val_loss: 4.5085 - val_accuracy: 0.5398
Epoch 90/100
24/24 [==============================] - 1s 30ms/step - loss: 0.0337 - accuracy: 0.9892 - val_loss: 4.4866 - val_accuracy: 0.5391
Epoch 91/100
24/24 [==============================] - 1s 25ms/step - loss: 0.0341 - accuracy: 0.9895 - val_loss: 4.4886 - val_accuracy: 0.5406
Epoch 92/100
24/24 [==============================] - 1s 27ms/step - loss: 0.0257 - accuracy: 0.9915 - val_loss: 4.6267 - val_accuracy: 0.5117
Epoch 93/100
24/24 [==============================] - 1s 28ms/step - loss: 0.0387 - accuracy: 0.9863 - val_loss: 4.4025 - val_accuracy: 0.5335
Epoch 94/100
24/24 [==============================] - 1s 25ms/step - loss: 0.0211 - accuracy: 0.9912 - val_loss: 4.7446 - val_accuracy: 0.5273
Epoch 95/100
24/24 [==============================] - 1s 27ms/step - loss: 0.0328 - accuracy: 0.9886 - val_loss: 4.7130 - val_accuracy: 0.5386
Epoch 96/100
24/24 [==============================] - 1s 25ms/step - loss: 0.0303 - accuracy: 0.9915 - val_loss: 4.6356 - val_accuracy: 0.5347
Epoch 97/100
24/24 [==============================] - 1s 24ms/step - loss: 0.0252 - accuracy: 0.9925 - val_loss: 4.5219 - val_accuracy: 0.5360
Epoch 98/100
24/24 [==============================] - 1s 28ms/step - loss: 0.0371 - accuracy: 0.9899 - val_loss: 4.7211 - val_accuracy: 0.5350
Epoch 99/100
24/24 [==============================] - 1s 27ms/step - loss: 0.0313 - accuracy: 0.9938 - val_loss: 4.9153 - val_accuracy: 0.5253
Epoch 100/100
24/24 [==============================] - 1s 29ms/step - loss: 0.0332 - accuracy: 0.9895 - val_loss: 4.8303 - val_accuracy: 0.5204
Test Accuracy: 0.5203813314437866

### Caltech-C3

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPool2D,Dense,Flatten,Dropout,Input, AveragePooling2D, Activation,Conv2D, MaxPooling2D, BatchNormalization,Concatenate
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
from tensorflow.keras import regularizers, optimizers
from tensorflow.keras.preprocessing.image import ImageDataGenerator

from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers
from tensorflow.keras.regularizers import Regularizer

# Perform hold-out cross-validation
validation_scores = []

# Define the CrlBo regularizer
class CrlBoRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# # Number of K-folds
# K = 2

# # Initialize the KFold object
# kf = KFold(n_splits=K, shuffle=True, random_state=42)
# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []
num_classes = 102
# # Perform K-fold cross-validation
# for train_index, test_index in kf.split(x, y):
#     x_train_fold, x_test_fold = x[train_index], x[test_index]
#     y_train_fold, y_test_fold = y[train_index], y[test_index]

# Task A: Original SVHN model
model = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(28, 28, 3)),
        Conv2D(32, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu'),
        layers.Dropout(0.25),
        Dense(num_classes, activation='softmax')
    ])
with tf.device('/device:GPU:0'):  # Specify the GPU device to use
    model = model
    model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    model.fit(X_train_resized, y_train, batch_size=128, epochs=100, validation_data=(X_test_resized, y_test))
    model.save_weights('FashionMNIST_A.h5')
    prior_weights = model.get_weights()
# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(X_train_resized[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    fisher_matrix = []
    for i in range(len(model.trainable_weights)):
        fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

    for _ in range(num_samples):
        idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
        with tf.GradientTape() as tape:
            logits = model(x[idx:idx+1])
        gradients = tape.gradient(logits, model.trainable_weights)
        for i in range(len(fisher_matrix)):
            fisher_matrix[i] += tf.square(gradients[i])

    fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
    return fisher_matrix

fisher_matrix = compute_fisher(model, X_train_resized)
# for train_index, test_index in kf.split(x, y):
#     x_train_fold, x_test_fold = x[train_index], x[test_index]
#     y_train_fold, y_test_fold = y[train_index], y[test_index]
# Task B: Fashion SVHN with CrlBo regularization
model_CrlBoB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(28, 28, 3),
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])
with tf.device('/device:GPU:0'):  # Specify the GPU device to use
    model_CrlBoB = model_CrlBoB
    model_CrlBoB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    model_CrlBoB.load_weights('FashionMNIST_A.h5')
    model_CrlBoB.fit(X_train_resized, y_train, batch_size=128, epochs=100, validation_data=(X_test_resized, y_test))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(X_test_resized, y_test)[1]
    B_CrlBo_acc = 100 * model_CrlBoB.evaluate(X_test_resized, y_test)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(X_test_resized, y_test)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlBo method Accuracy: %.2f%%" % B_CrlBo_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/100
24/24 [==============================] - 7s 89ms/step - loss: 4.6304 - accuracy: 0.0082 - val_loss: 4.6246 - val_accuracy: 0.0054
Epoch 2/100
24/24 [==============================] - 1s 41ms/step - loss: 4.5765 - accuracy: 0.0206 - val_loss: 4.5365 - val_accuracy: 0.0054
Epoch 3/100
24/24 [==============================] - 1s 30ms/step - loss: 4.3972 - accuracy: 0.0503 - val_loss: 4.3131 - val_accuracy: 0.0493
Epoch 4/100
24/24 [==============================] - 1s 24ms/step - loss: 4.0659 - accuracy: 0.1167 - val_loss: 3.9190 - val_accuracy: 0.1854
Epoch 5/100
24/24 [==============================] - 1s 27ms/step - loss: 3.6344 - accuracy: 0.1859 - val_loss: 3.3190 - val_accuracy: 0.3212
Epoch 6/100
24/24 [==============================] - 1s 25ms/step - loss: 3.1896 - accuracy: 0.2657 - val_loss: 3.0300 - val_accuracy: 0.3489
Epoch 7/100
24/24 [==============================] - 1s 28ms/step - loss: 2.7872 - accuracy: 0.3346 - val_loss: 2.7961 - val_accuracy: 0.4127
Epoch 8/100
24/24 [==============================] - 1s 23ms/step - loss: 2.4421 - accuracy: 0.4049 - val_loss: 2.6368 - val_accuracy: 0.4320
Epoch 9/100
24/24 [==============================] - 1s 24ms/step - loss: 2.0812 - accuracy: 0.4814 - val_loss: 2.6668 - val_accuracy: 0.4440
Epoch 10/100
24/24 [==============================] - 1s 27ms/step - loss: 1.7300 - accuracy: 0.5435 - val_loss: 2.5015 - val_accuracy: 0.4898
Epoch 11/100
24/24 [==============================] - 1s 27ms/step - loss: 1.4368 - accuracy: 0.6212 - val_loss: 2.5752 - val_accuracy: 0.4910
Epoch 12/100
24/24 [==============================] - 1s 27ms/step - loss: 1.1464 - accuracy: 0.6892 - val_loss: 2.5863 - val_accuracy: 0.4796
Epoch 13/100
24/24 [==============================] - 1s 23ms/step - loss: 0.9439 - accuracy: 0.7356 - val_loss: 2.7401 - val_accuracy: 0.4895
Epoch 14/100
24/24 [==============================] - 1s 29ms/step - loss: 0.7425 - accuracy: 0.7853 - val_loss: 2.9062 - val_accuracy: 0.4903
Epoch 15/100
24/24 [==============================] - 1s 33ms/step - loss: 0.6141 - accuracy: 0.8284 - val_loss: 3.0568 - val_accuracy: 0.4852
Epoch 16/100
24/24 [==============================] - 1s 28ms/step - loss: 0.5131 - accuracy: 0.8493 - val_loss: 3.1323 - val_accuracy: 0.5051
Epoch 17/100
24/24 [==============================] - 1s 27ms/step - loss: 0.4396 - accuracy: 0.8696 - val_loss: 3.1385 - val_accuracy: 0.5081
Epoch 18/100
24/24 [==============================] - 1s 26ms/step - loss: 0.3740 - accuracy: 0.8863 - val_loss: 3.2430 - val_accuracy: 0.5120
Epoch 19/100
24/24 [==============================] - 1s 32ms/step - loss: 0.2882 - accuracy: 0.9193 - val_loss: 3.4394 - val_accuracy: 0.5005
Epoch 20/100
24/24 [==============================] - 1s 33ms/step - loss: 0.3174 - accuracy: 0.9082 - val_loss: 3.2614 - val_accuracy: 0.5117
Epoch 21/100
24/24 [==============================] - 1s 32ms/step - loss: 0.2301 - accuracy: 0.9337 - val_loss: 3.5444 - val_accuracy: 0.5094
Epoch 22/100
24/24 [==============================] - 1s 23ms/step - loss: 0.2112 - accuracy: 0.9373 - val_loss: 3.6769 - val_accuracy: 0.4921
Epoch 23/100
24/24 [==============================] - 1s 28ms/step - loss: 0.1850 - accuracy: 0.9451 - val_loss: 3.5585 - val_accuracy: 0.5069
Epoch 24/100
24/24 [==============================] - 1s 28ms/step - loss: 0.1816 - accuracy: 0.9415 - val_loss: 3.6802 - val_accuracy: 0.5025
Epoch 25/100
24/24 [==============================] - 1s 27ms/step - loss: 0.1766 - accuracy: 0.9458 - val_loss: 3.7077 - val_accuracy: 0.5181
Epoch 26/100
24/24 [==============================] - 1s 28ms/step - loss: 0.1664 - accuracy: 0.9575 - val_loss: 3.4637 - val_accuracy: 0.5265
Epoch 27/100
24/24 [==============================] - 1s 27ms/step - loss: 0.1406 - accuracy: 0.9611 - val_loss: 3.7565 - val_accuracy: 0.5187
Epoch 28/100
24/24 [==============================] - 1s 28ms/step - loss: 0.1495 - accuracy: 0.9585 - val_loss: 3.7300 - val_accuracy: 0.5176
Epoch 29/100
24/24 [==============================] - 1s 23ms/step - loss: 0.1158 - accuracy: 0.9650 - val_loss: 3.9104 - val_accuracy: 0.5076
Epoch 30/100
24/24 [==============================] - 1s 24ms/step - loss: 0.1150 - accuracy: 0.9644 - val_loss: 3.8605 - val_accuracy: 0.5125
Epoch 31/100
24/24 [==============================] - 1s 25ms/step - loss: 0.0952 - accuracy: 0.9683 - val_loss: 3.9122 - val_accuracy: 0.5202
Epoch 32/100
24/24 [==============================] - 1s 28ms/step - loss: 0.0994 - accuracy: 0.9680 - val_loss: 3.9989 - val_accuracy: 0.5228
Epoch 33/100
24/24 [==============================] - 1s 27ms/step - loss: 0.1031 - accuracy: 0.9703 - val_loss: 3.8845 - val_accuracy: 0.5225
Epoch 34/100
24/24 [==============================] - 1s 23ms/step - loss: 0.0973 - accuracy: 0.9716 - val_loss: 4.0767 - val_accuracy: 0.5271
Epoch 35/100
24/24 [==============================] - 1s 23ms/step - loss: 0.0925 - accuracy: 0.9712 - val_loss: 4.1350 - val_accuracy: 0.5092
Epoch 36/100
24/24 [==============================] - 1s 26ms/step - loss: 0.1242 - accuracy: 0.9624 - val_loss: 3.9097 - val_accuracy: 0.5123
Epoch 37/100
24/24 [==============================] - 1s 28ms/step - loss: 0.1064 - accuracy: 0.9725 - val_loss: 3.8029 - val_accuracy: 0.5247
Epoch 38/100
24/24 [==============================] - 1s 30ms/step - loss: 0.0881 - accuracy: 0.9739 - val_loss: 3.9284 - val_accuracy: 0.5184
Epoch 39/100
24/24 [==============================] - 1s 31ms/step - loss: 0.0765 - accuracy: 0.9732 - val_loss: 4.0426 - val_accuracy: 0.5178
Epoch 40/100
24/24 [==============================] - 1s 35ms/step - loss: 0.0910 - accuracy: 0.9755 - val_loss: 4.0411 - val_accuracy: 0.5289
Epoch 41/100
24/24 [==============================] - 1s 30ms/step - loss: 0.0680 - accuracy: 0.9797 - val_loss: 4.0225 - val_accuracy: 0.5151
Epoch 42/100
24/24 [==============================] - 1s 27ms/step - loss: 0.0581 - accuracy: 0.9837 - val_loss: 3.9939 - val_accuracy: 0.5207
Epoch 43/100
24/24 [==============================] - 1s 27ms/step - loss: 0.0715 - accuracy: 0.9771 - val_loss: 4.0685 - val_accuracy: 0.5095
Epoch 44/100
24/24 [==============================] - 1s 24ms/step - loss: 0.0693 - accuracy: 0.9804 - val_loss: 4.0461 - val_accuracy: 0.5163
Epoch 45/100
24/24 [==============================] - 1s 23ms/step - loss: 0.0535 - accuracy: 0.9820 - val_loss: 4.0043 - val_accuracy: 0.5271
Epoch 46/100
24/24 [==============================] - 1s 23ms/step - loss: 0.0560 - accuracy: 0.9843 - val_loss: 4.2790 - val_accuracy: 0.5274
Epoch 47/100
24/24 [==============================] - 1s 27ms/step - loss: 0.0571 - accuracy: 0.9840 - val_loss: 4.2698 - val_accuracy: 0.5207
Epoch 48/100
24/24 [==============================] - 1s 26ms/step - loss: 0.0650 - accuracy: 0.9810 - val_loss: 3.9617 - val_accuracy: 0.5294
Epoch 49/100
24/24 [==============================] - 1s 23ms/step - loss: 0.0644 - accuracy: 0.9820 - val_loss: 4.3196 - val_accuracy: 0.5235
Epoch 50/100
24/24 [==============================] - 1s 26ms/step - loss: 0.0642 - accuracy: 0.9810 - val_loss: 4.1905 - val_accuracy: 0.5156
Epoch 51/100
24/24 [==============================] - 1s 27ms/step - loss: 0.0750 - accuracy: 0.9788 - val_loss: 4.2768 - val_accuracy: 0.5077
Epoch 52/100
24/24 [==============================] - 1s 27ms/step - loss: 0.0529 - accuracy: 0.9843 - val_loss: 4.2305 - val_accuracy: 0.5210
Epoch 53/100
24/24 [==============================] - 1s 27ms/step - loss: 0.0569 - accuracy: 0.9840 - val_loss: 4.2391 - val_accuracy: 0.5215
Epoch 54/100
24/24 [==============================] - 1s 25ms/step - loss: 0.0456 - accuracy: 0.9886 - val_loss: 4.0798 - val_accuracy: 0.5348
Epoch 55/100
24/24 [==============================] - 1s 27ms/step - loss: 0.0448 - accuracy: 0.9882 - val_loss: 4.1429 - val_accuracy: 0.5334
Epoch 56/100
24/24 [==============================] - 1s 27ms/step - loss: 0.0462 - accuracy: 0.9843 - val_loss: 4.2561 - val_accuracy: 0.5159
Epoch 57/100
24/24 [==============================] - 1s 27ms/step - loss: 0.0552 - accuracy: 0.9817 - val_loss: 4.2968 - val_accuracy: 0.5163
Epoch 58/100
24/24 [==============================] - 1s 47ms/step - loss: 0.0433 - accuracy: 0.9853 - val_loss: 4.3315 - val_accuracy: 0.5210
Epoch 59/100
24/24 [==============================] - 1s 42ms/step - loss: 0.0474 - accuracy: 0.9869 - val_loss: 4.5316 - val_accuracy: 0.5230
Epoch 60/100
24/24 [==============================] - 1s 36ms/step - loss: 0.0428 - accuracy: 0.9856 - val_loss: 4.4257 - val_accuracy: 0.5251
Epoch 61/100
24/24 [==============================] - 1s 34ms/step - loss: 0.0507 - accuracy: 0.9850 - val_loss: 4.6782 - val_accuracy: 0.5225
Epoch 62/100
24/24 [==============================] - 1s 45ms/step - loss: 0.0540 - accuracy: 0.9866 - val_loss: 4.2862 - val_accuracy: 0.5033
Epoch 63/100
24/24 [==============================] - 1s 28ms/step - loss: 0.0448 - accuracy: 0.9859 - val_loss: 4.4823 - val_accuracy: 0.5240
Epoch 64/100
24/24 [==============================] - 1s 28ms/step - loss: 0.0414 - accuracy: 0.9882 - val_loss: 4.2722 - val_accuracy: 0.5329
Epoch 65/100
24/24 [==============================] - 1s 28ms/step - loss: 0.0434 - accuracy: 0.9863 - val_loss: 4.4985 - val_accuracy: 0.5243
Epoch 66/100
24/24 [==============================] - 1s 24ms/step - loss: 0.0456 - accuracy: 0.9869 - val_loss: 4.6255 - val_accuracy: 0.5076
Epoch 67/100
24/24 [==============================] - 1s 23ms/step - loss: 0.0574 - accuracy: 0.9830 - val_loss: 4.5358 - val_accuracy: 0.5005
Epoch 68/100
24/24 [==============================] - 1s 23ms/step - loss: 0.0572 - accuracy: 0.9856 - val_loss: 4.4176 - val_accuracy: 0.5044
Epoch 69/100
24/24 [==============================] - 1s 27ms/step - loss: 0.0608 - accuracy: 0.9827 - val_loss: 4.2593 - val_accuracy: 0.5202
Epoch 70/100
24/24 [==============================] - 1s 24ms/step - loss: 0.0352 - accuracy: 0.9889 - val_loss: 4.3532 - val_accuracy: 0.5194
Epoch 71/100
24/24 [==============================] - 1s 25ms/step - loss: 0.0424 - accuracy: 0.9886 - val_loss: 4.5017 - val_accuracy: 0.5150
Epoch 72/100
24/24 [==============================] - 1s 27ms/step - loss: 0.0452 - accuracy: 0.9869 - val_loss: 4.5308 - val_accuracy: 0.5192
Epoch 73/100
24/24 [==============================] - 1s 27ms/step - loss: 0.0496 - accuracy: 0.9827 - val_loss: 4.7580 - val_accuracy: 0.5230
Epoch 74/100
24/24 [==============================] - 1s 25ms/step - loss: 0.0399 - accuracy: 0.9892 - val_loss: 4.6623 - val_accuracy: 0.5178
Epoch 75/100
24/24 [==============================] - 1s 25ms/step - loss: 0.0488 - accuracy: 0.9837 - val_loss: 4.3055 - val_accuracy: 0.5263
Epoch 76/100
24/24 [==============================] - 1s 24ms/step - loss: 0.0414 - accuracy: 0.9879 - val_loss: 4.3427 - val_accuracy: 0.5222
Epoch 77/100
24/24 [==============================] - 1s 28ms/step - loss: 0.0432 - accuracy: 0.9895 - val_loss: 4.2848 - val_accuracy: 0.5194
Epoch 78/100
24/24 [==============================] - 1s 34ms/step - loss: 0.0426 - accuracy: 0.9876 - val_loss: 4.6423 - val_accuracy: 0.5260
Epoch 79/100
24/24 [==============================] - 1s 29ms/step - loss: 0.0330 - accuracy: 0.9908 - val_loss: 4.5540 - val_accuracy: 0.5283
Epoch 80/100
24/24 [==============================] - 1s 32ms/step - loss: 0.0387 - accuracy: 0.9905 - val_loss: 4.5650 - val_accuracy: 0.5201
Epoch 81/100
24/24 [==============================] - 1s 24ms/step - loss: 0.0343 - accuracy: 0.9892 - val_loss: 4.8738 - val_accuracy: 0.5130
Epoch 82/100
24/24 [==============================] - 1s 25ms/step - loss: 0.0430 - accuracy: 0.9843 - val_loss: 4.4928 - val_accuracy: 0.5284
Epoch 83/100
24/24 [==============================] - 1s 28ms/step - loss: 0.0550 - accuracy: 0.9827 - val_loss: 4.6540 - val_accuracy: 0.5097
Epoch 84/100
24/24 [==============================] - 1s 28ms/step - loss: 0.0393 - accuracy: 0.9886 - val_loss: 4.5938 - val_accuracy: 0.5179
Epoch 85/100
24/24 [==============================] - 1s 28ms/step - loss: 0.0398 - accuracy: 0.9886 - val_loss: 4.6776 - val_accuracy: 0.5222
Epoch 86/100
24/24 [==============================] - 1s 27ms/step - loss: 0.0311 - accuracy: 0.9905 - val_loss: 4.6983 - val_accuracy: 0.5092
Epoch 87/100
24/24 [==============================] - 1s 28ms/step - loss: 0.0325 - accuracy: 0.9876 - val_loss: 4.8607 - val_accuracy: 0.5155
Epoch 88/100
24/24 [==============================] - 1s 26ms/step - loss: 0.0320 - accuracy: 0.9879 - val_loss: 4.8878 - val_accuracy: 0.5127
Epoch 89/100
24/24 [==============================] - 1s 24ms/step - loss: 0.0345 - accuracy: 0.9876 - val_loss: 5.0024 - val_accuracy: 0.5131
Epoch 90/100
24/24 [==============================] - 1s 28ms/step - loss: 0.0389 - accuracy: 0.9879 - val_loss: 5.0098 - val_accuracy: 0.5153
Epoch 91/100
24/24 [==============================] - 1s 27ms/step - loss: 0.0596 - accuracy: 0.9837 - val_loss: 4.5217 - val_accuracy: 0.5266
Epoch 92/100
24/24 [==============================] - 1s 28ms/step - loss: 0.0367 - accuracy: 0.9886 - val_loss: 4.4445 - val_accuracy: 0.5345
Epoch 93/100
24/24 [==============================] - 1s 27ms/step - loss: 0.0348 - accuracy: 0.9876 - val_loss: 4.6491 - val_accuracy: 0.5251
Epoch 94/100
24/24 [==============================] - 1s 25ms/step - loss: 0.0254 - accuracy: 0.9931 - val_loss: 4.7026 - val_accuracy: 0.5261
Epoch 95/100
24/24 [==============================] - 1s 27ms/step - loss: 0.0310 - accuracy: 0.9902 - val_loss: 4.9880 - val_accuracy: 0.5284
Epoch 96/100
24/24 [==============================] - 1s 27ms/step - loss: 0.0376 - accuracy: 0.9886 - val_loss: 5.1683 - val_accuracy: 0.5263
Epoch 97/100
24/24 [==============================] - 1s 46ms/step - loss: 0.0443 - accuracy: 0.9863 - val_loss: 4.8883 - val_accuracy: 0.5140
Epoch 98/100
24/24 [==============================] - 1s 32ms/step - loss: 0.0485 - accuracy: 0.9859 - val_loss: 4.5644 - val_accuracy: 0.5201
Epoch 99/100
24/24 [==============================] - 1s 34ms/step - loss: 0.0344 - accuracy: 0.9899 - val_loss: 4.6257 - val_accuracy: 0.5184
Epoch 100/100
24/24 [==============================] - 1s 28ms/step - loss: 0.0303 - accuracy: 0.9925 - val_loss: 4.8976 - val_accuracy: 0.5105
Epoch 1/100
24/24 [==============================] - 12s 118ms/step - loss: 0.0162 - accuracy: 0.9954 - val_loss: 6.1309 - val_accuracy: 0.5025
Epoch 2/100
24/24 [==============================] - 1s 44ms/step - loss: 0.0095 - accuracy: 0.9964 - val_loss: 6.7989 - val_accuracy: 0.5000
Epoch 3/100
24/24 [==============================] - 1s 44ms/step - loss: 0.0109 - accuracy: 0.9961 - val_loss: 6.4903 - val_accuracy: 0.4970
Epoch 4/100
24/24 [==============================] - 1s 47ms/step - loss: 0.0189 - accuracy: 0.9951 - val_loss: 6.1738 - val_accuracy: 0.4854
Epoch 5/100
24/24 [==============================] - 1s 43ms/step - loss: 0.0115 - accuracy: 0.9971 - val_loss: 5.9923 - val_accuracy: 0.5127
Epoch 6/100
24/24 [==============================] - 1s 44ms/step - loss: 0.0158 - accuracy: 0.9954 - val_loss: 6.0682 - val_accuracy: 0.5067
Epoch 7/100
24/24 [==============================] - 1s 32ms/step - loss: 0.0176 - accuracy: 0.9941 - val_loss: 5.9338 - val_accuracy: 0.5049
Epoch 8/100
24/24 [==============================] - 1s 44ms/step - loss: 0.0259 - accuracy: 0.9925 - val_loss: 6.0276 - val_accuracy: 0.5176
Epoch 9/100
24/24 [==============================] - 1s 49ms/step - loss: 0.0198 - accuracy: 0.9948 - val_loss: 5.8431 - val_accuracy: 0.5020
Epoch 10/100
24/24 [==============================] - 1s 44ms/step - loss: 0.0284 - accuracy: 0.9935 - val_loss: 5.7510 - val_accuracy: 0.5107
Epoch 11/100
24/24 [==============================] - 1s 34ms/step - loss: 0.0350 - accuracy: 0.9922 - val_loss: 6.0874 - val_accuracy: 0.4949
Epoch 12/100
24/24 [==============================] - 1s 33ms/step - loss: 0.0495 - accuracy: 0.9889 - val_loss: 6.2926 - val_accuracy: 0.4859
Epoch 13/100
24/24 [==============================] - 1s 30ms/step - loss: 0.0289 - accuracy: 0.9918 - val_loss: 6.1431 - val_accuracy: 0.4819
Epoch 14/100
24/24 [==============================] - 1s 45ms/step - loss: 0.0241 - accuracy: 0.9938 - val_loss: 5.8738 - val_accuracy: 0.5015
Epoch 15/100
24/24 [==============================] - 1s 30ms/step - loss: 0.0181 - accuracy: 0.9951 - val_loss: 5.9854 - val_accuracy: 0.4892
Epoch 16/100
24/24 [==============================] - 1s 45ms/step - loss: 0.0103 - accuracy: 0.9974 - val_loss: 6.1128 - val_accuracy: 0.5046
Epoch 17/100
24/24 [==============================] - 1s 44ms/step - loss: 0.0188 - accuracy: 0.9958 - val_loss: 6.1093 - val_accuracy: 0.5071
Epoch 18/100
24/24 [==============================] - 1s 45ms/step - loss: 0.0168 - accuracy: 0.9958 - val_loss: 6.0214 - val_accuracy: 0.4942
Epoch 19/100
24/24 [==============================] - 1s 44ms/step - loss: 0.0115 - accuracy: 0.9971 - val_loss: 5.8870 - val_accuracy: 0.5136
Epoch 20/100
24/24 [==============================] - 1s 44ms/step - loss: 0.0057 - accuracy: 0.9990 - val_loss: 6.2684 - val_accuracy: 0.5163
Epoch 21/100
24/24 [==============================] - 1s 44ms/step - loss: 0.0082 - accuracy: 0.9980 - val_loss: 6.2274 - val_accuracy: 0.5184
Epoch 22/100
24/24 [==============================] - 1s 50ms/step - loss: 0.0094 - accuracy: 0.9961 - val_loss: 6.4056 - val_accuracy: 0.5084
Epoch 23/100
24/24 [==============================] - 1s 50ms/step - loss: 0.0126 - accuracy: 0.9977 - val_loss: 6.2256 - val_accuracy: 0.5058
Epoch 24/100
24/24 [==============================] - 1s 32ms/step - loss: 0.0152 - accuracy: 0.9964 - val_loss: 5.8884 - val_accuracy: 0.5148
Epoch 25/100
24/24 [==============================] - 1s 31ms/step - loss: 0.0170 - accuracy: 0.9944 - val_loss: 6.1009 - val_accuracy: 0.5128
Epoch 26/100
24/24 [==============================] - 1s 44ms/step - loss: 0.0228 - accuracy: 0.9944 - val_loss: 5.7009 - val_accuracy: 0.5110
Epoch 27/100
24/24 [==============================] - 1s 43ms/step - loss: 0.0209 - accuracy: 0.9938 - val_loss: 5.8143 - val_accuracy: 0.5072
Epoch 28/100
24/24 [==============================] - 1s 45ms/step - loss: 0.0090 - accuracy: 0.9967 - val_loss: 5.6177 - val_accuracy: 0.5128
Epoch 29/100
24/24 [==============================] - 1s 32ms/step - loss: 0.0098 - accuracy: 0.9967 - val_loss: 5.4665 - val_accuracy: 0.5135
Epoch 30/100
24/24 [==============================] - 1s 43ms/step - loss: 0.0182 - accuracy: 0.9954 - val_loss: 5.9597 - val_accuracy: 0.4924
Epoch 31/100
24/24 [==============================] - 1s 32ms/step - loss: 0.0328 - accuracy: 0.9908 - val_loss: 5.5534 - val_accuracy: 0.5094
Epoch 32/100
24/24 [==============================] - 1s 44ms/step - loss: 0.0246 - accuracy: 0.9925 - val_loss: 5.4075 - val_accuracy: 0.4952
Epoch 33/100
24/24 [==============================] - 1s 45ms/step - loss: 0.0305 - accuracy: 0.9938 - val_loss: 6.3120 - val_accuracy: 0.4842
Epoch 34/100
24/24 [==============================] - 1s 31ms/step - loss: 0.0237 - accuracy: 0.9951 - val_loss: 5.8444 - val_accuracy: 0.5159
Epoch 35/100
24/24 [==============================] - 1s 39ms/step - loss: 0.0603 - accuracy: 0.9895 - val_loss: 5.5666 - val_accuracy: 0.4778
Epoch 36/100
24/24 [==============================] - 1s 40ms/step - loss: 0.0241 - accuracy: 0.9925 - val_loss: 5.3079 - val_accuracy: 0.5146
Epoch 37/100
24/24 [==============================] - 1s 52ms/step - loss: 0.0192 - accuracy: 0.9948 - val_loss: 4.9493 - val_accuracy: 0.4995
Epoch 38/100
24/24 [==============================] - 1s 36ms/step - loss: 0.0143 - accuracy: 0.9967 - val_loss: 5.2433 - val_accuracy: 0.5061
Epoch 39/100
24/24 [==============================] - 1s 45ms/step - loss: 0.0105 - accuracy: 0.9967 - val_loss: 5.3601 - val_accuracy: 0.5153
Epoch 40/100

### STL-10 -CV

In [ ]:
import tensorflow_datasets as tfds

# Load the STL-10 dataset
dataset_name = "stl10"
train_dataset, test_dataset = tfds.load(name=dataset_name, split=["train", "test"], as_supervised=True)

# Iterate through the datasets to get features and labels
X_train = []
y_train = []
for image, label in tfds.as_numpy(train_dataset):
    X_train.append(image)
    y_train.append(label)

X_test = []
y_test = []
for image, label in tfds.as_numpy(test_dataset):
    X_test.append(image)
    y_test.append(label)

# Convert lists to numpy arrays
import numpy as np
X_train = np.array(X_train)
y_train = np.array(y_train)
X_test = np.array(X_test)
y_test = np.array(y_test)

# Print the shape of the arrays
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

Downloading and preparing dataset 2.46 GiB (download: 2.46 GiB, generated: 1.86 GiB, total: 4.32 GiB) to /root/tensorflow_datasets/stl10/1.0.0...

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

Generating splits...:   0%|          | 0/3 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/5000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/stl10/1.0.0.incompleteV796Q8/stl10-train.tfrecord*...:   0%|          | 0/…

Generating test examples...:   0%|          | 0/8000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/stl10/1.0.0.incompleteV796Q8/stl10-test.tfrecord*...:   0%|          | 0/8…

Generating unlabelled examples...:   0%|          | 0/100000 [00:00<?, ? examples/s]

In [ ]:
import tensorflow as tf
y_train = tf.keras.utils.to_categorical(y_train, num_classes=10)
y_test = tf.keras.utils.to_categorical(y_test, num_classes=10)

In [ ]:
import tensorflow as tf
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras import layers
# Define the model architecture
num_classes = 10
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(96, 96, 3)),
    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu'),
    layers.Dropout(0.25),
    Dense(num_classes, activation='softmax')
])

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the original model on Task A
model.fit(X_train, y_train, batch_size=128, epochs=100, validation_data=(X_test, y_test))


# Evaluate the model on the test set
_, test_accuracy = model.evaluate(X_test, y_test, verbose=0)
print("Test Accuracy:", test_accuracy)

Epoch 1/100
40/40 [==============================] - 24s 172ms/step - loss: 103.6232 - accuracy: 0.1372 - val_loss: 2.1230 - val_accuracy: 0.1991
Epoch 2/100
40/40 [==============================] - 5s 120ms/step - loss: 2.0501 - accuracy: 0.2208 - val_loss: 1.9282 - val_accuracy: 0.2705
Epoch 3/100
40/40 [==============================] - 5s 118ms/step - loss: 1.9553 - accuracy: 0.2596 - val_loss: 1.8972 - val_accuracy: 0.2900
Epoch 4/100
40/40 [==============================] - 5s 126ms/step - loss: 1.8409 - accuracy: 0.3092 - val_loss: 1.7781 - val_accuracy: 0.3415
Epoch 5/100
40/40 [==============================] - 5s 123ms/step - loss: 1.7227 - accuracy: 0.3536 - val_loss: 1.8383 - val_accuracy: 0.3350
Epoch 6/100
40/40 [==============================] - 5s 123ms/step - loss: 1.5974 - accuracy: 0.4086 - val_loss: 1.7190 - val_accuracy: 0.3614
Epoch 7/100
40/40 [==============================] - 5s 125ms/step - loss: 1.4919 - accuracy: 0.4494 - val_loss: 1.6607 - val_accuracy: 0.3945
Epoch 8/100
40/40 [==============================] - 5s 123ms/step - loss: 1.3463 - accuracy: 0.5072 - val_loss: 1.7439 - val_accuracy: 0.3891
Epoch 9/100
40/40 [==============================] - 5s 124ms/step - loss: 1.2351 - accuracy: 0.5474 - val_loss: 1.7205 - val_accuracy: 0.3970
Epoch 10/100
40/40 [==============================] - 5s 123ms/step - loss: 1.0803 - accuracy: 0.6100 - val_loss: 1.8516 - val_accuracy: 0.4044
Epoch 11/100
40/40 [==============================] - 5s 124ms/step - loss: 0.9942 - accuracy: 0.6420 - val_loss: 1.8347 - val_accuracy: 0.4085
Epoch 12/100
40/40 [==============================] - 5s 125ms/step - loss: 0.8790 - accuracy: 0.6744 - val_loss: 1.9408 - val_accuracy: 0.4135
Epoch 13/100
40/40 [==============================] - 5s 122ms/step - loss: 0.7776 - accuracy: 0.7174 - val_loss: 2.0436 - val_accuracy: 0.4029
Epoch 14/100
40/40 [==============================] - 5s 126ms/step - loss: 0.7091 - accuracy: 0.7506 - val_loss: 2.1620 - val_accuracy: 0.4041
Epoch 15/100
40/40 [==============================] - 5s 129ms/step - loss: 0.6486 - accuracy: 0.7652 - val_loss: 2.1860 - val_accuracy: 0.4055
Epoch 16/100
40/40 [==============================] - 5s 125ms/step - loss: 0.6141 - accuracy: 0.7854 - val_loss: 2.2492 - val_accuracy: 0.4110
Epoch 17/100
40/40 [==============================] - 5s 128ms/step - loss: 0.5073 - accuracy: 0.8266 - val_loss: 2.5144 - val_accuracy: 0.4141
Epoch 18/100
40/40 [==============================] - 5s 124ms/step - loss: 0.4579 - accuracy: 0.8402 - val_loss: 2.5200 - val_accuracy: 0.4106
Epoch 19/100
40/40 [==============================] - 5s 126ms/step - loss: 0.4149 - accuracy: 0.8534 - val_loss: 2.7405 - val_accuracy: 0.4106
Epoch 20/100
40/40 [==============================] - 5s 128ms/step - loss: 0.4059 - accuracy: 0.8644 - val_loss: 2.6067 - val_accuracy: 0.4069
Epoch 21/100
40/40 [==============================] - 5s 123ms/step - loss: 0.3885 - accuracy: 0.8696 - val_loss: 2.7139 - val_accuracy: 0.4092
Epoch 22/100
40/40 [==============================] - 5s 125ms/step - loss: 0.3086 - accuracy: 0.8958 - val_loss: 2.8254 - val_accuracy: 0.4099
Epoch 23/100
40/40 [==============================] - 5s 123ms/step - loss: 0.3038 - accuracy: 0.9014 - val_loss: 2.8286 - val_accuracy: 0.4145
Epoch 24/100
40/40 [==============================] - 5s 125ms/step - loss: 0.2613 - accuracy: 0.9156 - val_loss: 2.7749 - val_accuracy: 0.4209
Epoch 25/100
40/40 [==============================] - 5s 128ms/step - loss: 0.2605 - accuracy: 0.9166 - val_loss: 2.7206 - val_accuracy: 0.4249
Epoch 26/100
40/40 [==============================] - 5s 127ms/step - loss: 0.2222 - accuracy: 0.9278 - val_loss: 2.9104 - val_accuracy: 0.4271
Epoch 27/100
40/40 [==============================] - 5s 123ms/step - loss: 0.2270 - accuracy: 0.9228 - val_loss: 2.9229 - val_accuracy: 0.4116
Epoch 28/100
40/40 [==============================] - 5s 129ms/step - loss: 0.2209 - accuracy: 0.9332 - val_loss: 3.1109 - val_accuracy: 0.4157
Epoch 29/100
40/40 [==============================] - 5s 128ms/step - loss: 0.2060 - accuracy: 0.9306 - val_loss: 3.0838 - val_accuracy: 0.4199
Epoch 30/100
40/40 [==============================] - 5s 128ms/step - loss: 0.2011 - accuracy: 0.9384 - val_loss: 2.8829 - val_accuracy: 0.4139
Epoch 31/100
40/40 [==============================] - 5s 128ms/step - loss: 0.1746 - accuracy: 0.9456 - val_loss: 3.2275 - val_accuracy: 0.4050
Epoch 32/100
40/40 [==============================] - 5s 130ms/step - loss: 0.1918 - accuracy: 0.9398 - val_loss: 3.1096 - val_accuracy: 0.4108
Epoch 33/100
40/40 [==============================] - 5s 131ms/step - loss: 0.2907 - accuracy: 0.9052 - val_loss: 2.7614 - val_accuracy: 0.4075
Epoch 34/100
40/40 [==============================] - 5s 127ms/step - loss: 0.1997 - accuracy: 0.9386 - val_loss: 3.3659 - val_accuracy: 0.4047
Epoch 35/100
40/40 [==============================] - 5s 130ms/step - loss: 0.1536 - accuracy: 0.9482 - val_loss: 3.3648 - val_accuracy: 0.4173
Epoch 36/100
40/40 [==============================] - 5s 128ms/step - loss: 0.1875 - accuracy: 0.9418 - val_loss: 3.2216 - val_accuracy: 0.4195
Epoch 37/100
40/40 [==============================] - 5s 127ms/step - loss: 0.2058 - accuracy: 0.9388 - val_loss: 3.1829 - val_accuracy: 0.4134
Epoch 38/100
40/40 [==============================] - 5s 131ms/step - loss: 0.1690 - accuracy: 0.9450 - val_loss: 3.1129 - val_accuracy: 0.4184
Epoch 39/100
40/40 [==============================] - 5s 126ms/step - loss: 0.1319 - accuracy: 0.9600 - val_loss: 3.0883 - val_accuracy: 0.4223
Epoch 40/100
40/40 [==============================] - 5s 127ms/step - loss: 0.0995 - accuracy: 0.9698 - val_loss: 3.2952 - val_accuracy: 0.4231
Epoch 41/100
40/40 [==============================] - 5s 129ms/step - loss: 0.1204 - accuracy: 0.9616 - val_loss: 3.5449 - val_accuracy: 0.4245
Epoch 42/100
40/40 [==============================] - 5s 127ms/step - loss: 0.1496 - accuracy: 0.9536 - val_loss: 2.9638 - val_accuracy: 0.4236
Epoch 43/100
40/40 [==============================] - 5s 128ms/step - loss: 0.1906 - accuracy: 0.9394 - val_loss: 3.3845 - val_accuracy: 0.4271
Epoch 44/100
40/40 [==============================] - 5s 128ms/step - loss: 0.1206 - accuracy: 0.9616 - val_loss: 3.4524 - val_accuracy: 0.4274
Epoch 45/100
40/40 [==============================] - 5s 127ms/step - loss: 0.1151 - accuracy: 0.9660 - val_loss: 3.1101 - val_accuracy: 0.4294
Epoch 46/100
40/40 [==============================] - 5s 127ms/step - loss: 0.0866 - accuracy: 0.9738 - val_loss: 3.2255 - val_accuracy: 0.4264
Epoch 47/100
40/40 [==============================] - 5s 128ms/step - loss: 0.1149 - accuracy: 0.9642 - val_loss: 3.5844 - val_accuracy: 0.4180
Epoch 48/100
40/40 [==============================] - 5s 128ms/step - loss: 0.0998 - accuracy: 0.9700 - val_loss: 3.3206 - val_accuracy: 0.4218
Epoch 49/100
40/40 [==============================] - 5s 126ms/step - loss: 0.1041 - accuracy: 0.9684 - val_loss: 3.1053 - val_accuracy: 0.4272
Epoch 50/100
40/40 [==============================] - 5s 128ms/step - loss: 0.0968 - accuracy: 0.9696 - val_loss: 3.5616 - val_accuracy: 0.4285
Epoch 51/100
40/40 [==============================] - 5s 130ms/step - loss: 0.1102 - accuracy: 0.9680 - val_loss: 3.1316 - val_accuracy: 0.4198
Epoch 52/100
40/40 [==============================] - 5s 129ms/step - loss: 0.0865 - accuracy: 0.9750 - val_loss: 3.5754 - val_accuracy: 0.4264
Epoch 53/100
40/40 [==============================] - 5s 128ms/step - loss: 0.0770 - accuracy: 0.9748 - val_loss: 3.4265 - val_accuracy: 0.4257
Epoch 54/100
40/40 [==============================] - 5s 126ms/step - loss: 0.0742 - accuracy: 0.9776 - val_loss: 3.3398 - val_accuracy: 0.4184
Epoch 55/100
40/40 [==============================] - 5s 123ms/step - loss: 0.2118 - accuracy: 0.9386 - val_loss: 3.2491 - val_accuracy: 0.4099
Epoch 56/100
40/40 [==============================] - 5s 127ms/step - loss: 0.0832 - accuracy: 0.9728 - val_loss: 3.3849 - val_accuracy: 0.4157
Epoch 57/100
40/40 [==============================] - 5s 124ms/step - loss: 0.0793 - accuracy: 0.9766 - val_loss: 3.3854 - val_accuracy: 0.4201
Epoch 58/100
40/40 [==============================] - 5s 128ms/step - loss: 0.0775 - accuracy: 0.9746 - val_loss: 3.1963 - val_accuracy: 0.4189
Epoch 59/100
40/40 [==============================] - 5s 125ms/step - loss: 0.0814 - accuracy: 0.9752 - val_loss: 3.3347 - val_accuracy: 0.4207
Epoch 60/100
40/40 [==============================] - 5s 126ms/step - loss: 0.1455 - accuracy: 0.9600 - val_loss: 3.3054 - val_accuracy: 0.4238
Epoch 61/100
40/40 [==============================] - 5s 126ms/step - loss: 0.0862 - accuracy: 0.9742 - val_loss: 3.3539 - val_accuracy: 0.4219
Epoch 62/100
40/40 [==============================] - 5s 127ms/step - loss: 0.0671 - accuracy: 0.9794 - val_loss: 3.8425 - val_accuracy: 0.4260
Epoch 63/100
40/40 [==============================] - 5s 128ms/step - loss: 0.0830 - accuracy: 0.9766 - val_loss: 3.7416 - val_accuracy: 0.4241
Epoch 64/100
40/40 [==============================] - 5s 128ms/step - loss: 0.0679 - accuracy: 0.9802 - val_loss: 3.6739 - val_accuracy: 0.4251
Epoch 65/100
40/40 [==============================] - 5s 128ms/step - loss: 0.0741 - accuracy: 0.9774 - val_loss: 3.9267 - val_accuracy: 0.4214
Epoch 66/100
40/40 [==============================] - 5s 129ms/step - loss: 0.0628 - accuracy: 0.9820 - val_loss: 3.8071 - val_accuracy: 0.4309
Epoch 67/100
40/40 [==============================] - 5s 126ms/step - loss: 0.0562 - accuracy: 0.9834 - val_loss: 3.8177 - val_accuracy: 0.4151
Epoch 68/100
40/40 [==============================] - 5s 126ms/step - loss: 0.1594 - accuracy: 0.9538 - val_loss: 3.6746 - val_accuracy: 0.4245
Epoch 69/100
40/40 [==============================] - 5s 128ms/step - loss: 0.0659 - accuracy: 0.9800 - val_loss: 3.3806 - val_accuracy: 0.4229
Epoch 70/100
40/40 [==============================] - 5s 127ms/step - loss: 0.0671 - accuracy: 0.9784 - val_loss: 3.6322 - val_accuracy: 0.4229
Epoch 71/100
40/40 [==============================] - 5s 130ms/step - loss: 0.0594 - accuracy: 0.9816 - val_loss: 3.8047 - val_accuracy: 0.4304
Epoch 72/100
40/40 [==============================] - 5s 127ms/step - loss: 0.0693 - accuracy: 0.9798 - val_loss: 3.5145 - val_accuracy: 0.4269
Epoch 73/100
40/40 [==============================] - 5s 125ms/step - loss: 0.0839 - accuracy: 0.9786 - val_loss: 3.3577 - val_accuracy: 0.4223
Epoch 74/100
40/40 [==============================] - 5s 129ms/step - loss: 0.0796 - accuracy: 0.9748 - val_loss: 3.5145 - val_accuracy: 0.4214
Epoch 75/100
40/40 [==============================] - 5s 129ms/step - loss: 0.0594 - accuracy: 0.9824 - val_loss: 3.4690 - val_accuracy: 0.4301
Epoch 76/100
40/40 [==============================] - 5s 128ms/step - loss: 0.1232 - accuracy: 0.9674 - val_loss: 3.4077 - val_accuracy: 0.4141
Epoch 77/100
40/40 [==============================] - 5s 125ms/step - loss: 0.0664 - accuracy: 0.9774 - val_loss: 3.7442 - val_accuracy: 0.4195
Epoch 78/100
40/40 [==============================] - 5s 127ms/step - loss: 0.0555 - accuracy: 0.9834 - val_loss: 3.2759 - val_accuracy: 0.4314
Epoch 79/100
40/40 [==============================] - 5s 126ms/step - loss: 0.0566 - accuracy: 0.9828 - val_loss: 3.7378 - val_accuracy: 0.4297
Epoch 80/100
40/40 [==============================] - 5s 126ms/step - loss: 0.0635 - accuracy: 0.9814 - val_loss: 3.2709 - val_accuracy: 0.4283
Epoch 81/100
40/40 [==============================] - 5s 129ms/step - loss: 0.0503 - accuracy: 0.9838 - val_loss: 3.5071 - val_accuracy: 0.4341
Epoch 82/100
40/40 [==============================] - 5s 126ms/step - loss: 0.0632 - accuracy: 0.9826 - val_loss: 3.7184 - val_accuracy: 0.4260
Epoch 83/100
40/40 [==============================] - 5s 127ms/step - loss: 0.0406 - accuracy: 0.9870 - val_loss: 3.9425 - val_accuracy: 0.4246
Epoch 84/100
40/40 [==============================] - 5s 132ms/step - loss: 0.0977 - accuracy: 0.9692 - val_loss: 3.3708 - val_accuracy: 0.4306
Epoch 85/100
40/40 [==============================] - 5s 128ms/step - loss: 0.0352 - accuracy: 0.9892 - val_loss: 3.7310 - val_accuracy: 0.4329
Epoch 86/100
40/40 [==============================] - 5s 127ms/step - loss: 0.0387 - accuracy: 0.9878 - val_loss: 4.2299 - val_accuracy: 0.4361
Epoch 87/100
40/40 [==============================] - 5s 129ms/step - loss: 0.0504 - accuracy: 0.9846 - val_loss: 3.9027 - val_accuracy: 0.4338
Epoch 88/100
40/40 [==============================] - 5s 127ms/step - loss: 0.0591 - accuracy: 0.9832 - val_loss: 3.8461 - val_accuracy: 0.4330
Epoch 89/100
40/40 [==============================] - 5s 127ms/step - loss: 0.0546 - accuracy: 0.9818 - val_loss: 3.6755 - val_accuracy: 0.4260
Epoch 90/100
40/40 [==============================] - 5s 127ms/step - loss: 0.0575 - accuracy: 0.9834 - val_loss: 3.6981 - val_accuracy: 0.4317
Epoch 91/100
40/40 [==============================] - 6s 162ms/step - loss: 0.0532 - accuracy: 0.9842 - val_loss: 3.6179 - val_accuracy: 0.4271
Epoch 92/100
40/40 [==============================] - 5s 130ms/step - loss: 0.1145 - accuracy: 0.9642 - val_loss: 3.5691 - val_accuracy: 0.4246
Epoch 93/100
40/40 [==============================] - 5s 128ms/step - loss: 0.0618 - accuracy: 0.9810 - val_loss: 4.3074 - val_accuracy: 0.4210
Epoch 94/100
40/40 [==============================] - 5s 130ms/step - loss: 0.0630 - accuracy: 0.9818 - val_loss: 3.6548 - val_accuracy: 0.4295
Epoch 95/100
40/40 [==============================] - 5s 129ms/step - loss: 0.0404 - accuracy: 0.9862 - val_loss: 4.0760 - val_accuracy: 0.4351
Epoch 96/100
40/40 [==============================] - 5s 129ms/step - loss: 0.0447 - accuracy: 0.9852 - val_loss: 3.8985 - val_accuracy: 0.4251
Epoch 97/100
40/40 [==============================] - 5s 128ms/step - loss: 0.0408 - accuracy: 0.9886 - val_loss: 3.6008 - val_accuracy: 0.4243
Epoch 98/100
40/40 [==============================] - 5s 128ms/step - loss: 0.0373 - accuracy: 0.9882 - val_loss: 3.9460 - val_accuracy: 0.4321
Epoch 99/100
40/40 [==============================] - 5s 129ms/step - loss: 0.0375 - accuracy: 0.9894 - val_loss: 4.0658 - val_accuracy: 0.4294
Epoch 100/100
40/40 [==============================] - 5s 128ms/step - loss: 0.0473 - accuracy: 0.9870 - val_loss: 3.7146 - val_accuracy: 0.4364
Test Accuracy: 0.4363749921321869

### STL-10 C3

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPool2D,Dense,Flatten,Dropout,Input, AveragePooling2D, Activation,Conv2D, MaxPooling2D, BatchNormalization,Concatenate
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
from tensorflow.keras import regularizers, optimizers
from tensorflow.keras.preprocessing.image import ImageDataGenerator

from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers
from tensorflow.keras.regularizers import Regularizer

# Perform hold-out cross-validation
validation_scores = []

# Define the CrlBo regularizer
class CrlBoRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization



# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []
num_classes = 10
# Perform K-fold cross-validation


# Task A: Original STL-10 model
model = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(96, 96, 3)),

        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same'),

        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu'),
        layers.Dropout(0.25),
        Dense(num_classes, activation='softmax')
    ])
with tf.device('/device:GPU:0'):  # Specify the GPU device to use
  model = model
  model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
  model.fit(X_train, y_train, batch_size=32, epochs=10, validation_data=(X_test,y_test))
  model.save_weights('FashionMNIST_A.h5')
  prior_weights = model.get_weights()
# Compute Fisher Information for Task A
with tf.GradientTape() as tape:
  model_output = model(X_train[:1])
  grads = tape.gradient(model_output, model.weights)
  fisher_info = [tf.square(g).numpy() for g in grads]
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    fisher_matrix = []
    for i in range(len(model.trainable_weights)):
        fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

    for _ in range(num_samples):
        idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
        with tf.GradientTape() as tape:
            logits = model(x[idx:idx+1])
        gradients = tape.gradient(logits, model.trainable_weights)
        for i in range(len(fisher_matrix)):
            fisher_matrix[i] += tf.square(gradients[i])

    fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
    return fisher_matrix

fisher_matrix = compute_fisher(model, X_train)

# Task B: Fashion MNIST with CrlBo regularization
model_CrlBoB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(96, 96, 3),
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),

        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),

        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])
with tf.device('/device:GPU:0'):  # Specify the GPU device to use
  model_CrlBoB = model_CrlBoB
  model_CrlBoB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
  model_CrlBoB.load_weights('FashionMNIST_A.h5')
  model_CrlBoB.fit( X_train, y_train, batch_size=32, epochs=10, validation_data=(X_test, y_test))

# Evaluate performance
  A_original_acc = 100 * model.evaluate(X_test, y_test)[1]
  B_CrlBo_acc = 100 * model_CrlBoB.evaluate(X_test, y_test)[1]
# Train the model on each batch



# Evaluate the model on the test set
  _, test_accuracy = model.evaluate(X_test, y_test)
  print("Test Accuracy:", test_accuracy)

  print("Task A Original Accuracy: %.2f%%" % A_original_acc)
  print("Task B CrlBo method Accuracy: %.2f%%" % B_CrlBo_acc)


    # Append the test accuracy of Task B to accuracies list
  accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
157/157 [==============================] - 16s 26ms/step - loss: 61.9413 - accuracy: 0.1810 - val_loss: 2.1540 - val_accuracy: 0.1727
Epoch 2/10
157/157 [==============================] - 3s 20ms/step - loss: 2.0243 - accuracy: 0.2230 - val_loss: 2.0410 - val_accuracy: 0.1925
Epoch 3/10
157/157 [==============================] - 3s 20ms/step - loss: 1.9193 - accuracy: 0.2712 - val_loss: 1.9848 - val_accuracy: 0.2218
Epoch 4/10
157/157 [==============================] - 3s 20ms/step - loss: 1.8032 - accuracy: 0.3222 - val_loss: 1.9939 - val_accuracy: 0.2292
Epoch 5/10
157/157 [==============================] - 4s 23ms/step - loss: 1.6853 - accuracy: 0.3766 - val_loss: 1.9643 - val_accuracy: 0.2700
Epoch 6/10
157/157 [==============================] - 4s 22ms/step - loss: 1.5499 - accuracy: 0.4250 - val_loss: 2.0417 - val_accuracy: 0.2682
Epoch 7/10
157/157 [==============================] - 3s 20ms/step - loss: 1.3880 - accuracy: 0.4904 - val_loss: 2.2312 - val_accuracy: 0.2599
Epoch 8/10
157/157 [==============================] - 3s 21ms/step - loss: 1.2251 - accuracy: 0.5530 - val_loss: 2.2617 - val_accuracy: 0.3040
Epoch 9/10
157/157 [==============================] - 4s 23ms/step - loss: 1.1160 - accuracy: 0.6018 - val_loss: 2.3708 - val_accuracy: 0.3183
Epoch 10/10
157/157 [==============================] - 3s 19ms/step - loss: 0.9413 - accuracy: 0.6692 - val_loss: 2.3562 - val_accuracy: 0.3524
Epoch 1/10
157/157 [==============================] - 37s 126ms/step - loss: 0.9493 - accuracy: 0.6830 - val_loss: 2.5258 - val_accuracy: 0.3446
Epoch 2/10
157/157 [==============================] - 9s 56ms/step - loss: 0.7775 - accuracy: 0.7416 - val_loss: 2.6591 - val_accuracy: 0.3725
Epoch 3/10
157/157 [==============================] - 7s 43ms/step - loss: 0.6020 - accuracy: 0.7964 - val_loss: 2.9282 - val_accuracy: 0.3755
Epoch 4/10
157/157 [==============================] - 7s 43ms/step - loss: 0.4379 - accuracy: 0.8570 - val_loss: 3.2883 - val_accuracy: 0.4108
Epoch 5/10
157/157 [==============================] - 7s 43ms/step - loss: 0.4896 - accuracy: 0.8524 - val_loss: 3.2817 - val_accuracy: 0.3909
Epoch 6/10
157/157 [==============================] - 9s 56ms/step - loss: 0.3646 - accuracy: 0.8874 - val_loss: 3.4221 - val_accuracy: 0.3759
Epoch 7/10
157/157 [==============================] - 9s 58ms/step - loss: 0.2593 - accuracy: 0.9196 - val_loss: 3.8489 - val_accuracy: 0.3889
Epoch 8/10
157/157 [==============================] - 9s 57ms/step - loss: 0.2802 - accuracy: 0.9144 - val_loss: 4.4966 - val_accuracy: 0.3899
Epoch 9/10
157/157 [==============================] - 7s 43ms/step - loss: 0.2381 - accuracy: 0.9352 - val_loss: 4.2310 - val_accuracy: 0.4019
Epoch 10/10
157/157 [==============================] - 9s 57ms/step - loss: 0.2005 - accuracy: 0.9450 - val_loss: 4.6126 - val_accuracy: 0.4008
250/250 [==============================] - 1s 4ms/step - loss: 2.3562 - accuracy: 0.3524
250/250 [==============================] - 3s 13ms/step - loss: 4.6126 - accuracy: 0.4008
250/250 [==============================] - 1s 4ms/step - loss: 2.3562 - accuracy: 0.3524
Test Accuracy: 0.35237500071525574
Task A Original Accuracy: 35.24%
Task B CrlBo method Accuracy: 40.08%
Fold-1: 35.24%

### CIFAR100

In [ ]:
import numpy as np
# from tensorflow.keras.datasets import cifar100
import numpy as np
# Importing the necessary libraries, which we may or may not use. Its always good idea to import them befor (if you remember) else we can do it at any point of time no problem.
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPool2D,Dense,Flatten,Dropout,Input, AveragePooling2D, Activation,Conv2D, MaxPooling2D, BatchNormalization,Concatenate
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
from tensorflow.keras import regularizers, optimizers
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.datasets import cifar100
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers

# Load the CIFAR-10 dataset
(x_train, y_train), (x_test, y_test) = cifar100.load_data()

# Convert the labels to one-hot encoding
num_classes = 100
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 20 batches
num_batches = 20
batch_size = len(x_train) // num_batches

x_train_batches = np.array_split(x_train, num_batches)
y_train_batches = np.array_split(y_train, num_batches)


validation_scores = []
# Define the CrlB regularizer
class CrlBRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization



# Define the model architecture
model = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        Conv2D(32, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu'),
        layers.Dropout(0.25),
        Dense(num_classes, activation='softmax')
])

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the original model on Task A
model.fit(x_train_batches[0], y_train_batches[0], batch_size=batch_size, epochs=10, validation_data=(x_test, y_test))

# Save the weights of the original model for later use
prior_weights = model.get_weights()
# Compute the Fisher Information matrix
def compute_fisher(model, x, num_samples=200):
    fisher_matrix = []
    for i in range(len(model.trainable_weights)):
        fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

    for _ in range(num_samples):
        idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
        with tf.GradientTape() as tape:
            logits = model(x[idx:idx+1])
        gradients = tape.gradient(logits, model.trainable_weights)
        for i in range(len(fisher_matrix)):
            fisher_matrix[i] += tf.square(gradients[i])

    fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
    return fisher_matrix
# Compute the Fisher Information matrix for each batch
fisher_matrices = []
for i in range(num_batches):
    fisher_matrix = compute_fisher(model, x_train_batches[i])
    fisher_matrices.append(fisher_matrix)

# Define the new model with CrlB regularization
model_CrlB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3),
               kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
])
# Train the model on Task B with CrlB regularization for each batch
for i in range(num_batches):
    history = model_CrlB.fit(x_train_batches[i], y_train_batches[i], batch_size=batch_size, epochs=10, validation_data=(x_test, y_test))
    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)

    average_accuracy = sum(history.history['val_accuracy']) / len(history.history['val_accuracy'])
    print("Average accuracy:", average_accuracy)

Downloading data from https://www.cs.toronto.edu/~kriz/cifar-100-python.tar.gz
169001437/169001437 [==============================] - 13s 0us/step
Epoch 1/10
1/1 [==============================] - 12s 12s/step - loss: 57.5048 - accuracy: 0.0096 - val_loss: 27.6356 - val_accuracy: 0.0102
Epoch 2/10
1/1 [==============================] - 0s 340ms/step - loss: 53.0729 - accuracy: 0.0112 - val_loss: 12.6364 - val_accuracy: 0.0086
Epoch 3/10
1/1 [==============================] - 0s 352ms/step - loss: 27.1564 - accuracy: 0.0056 - val_loss: 6.3315 - val_accuracy: 0.0077
Epoch 4/10
1/1 [==============================] - 0s 332ms/step - loss: 12.7522 - accuracy: 0.0132 - val_loss: 5.1681 - val_accuracy: 0.0091
Epoch 5/10
1/1 [==============================] - 0s 346ms/step - loss: 7.7238 - accuracy: 0.0072 - val_loss: 4.7922 - val_accuracy: 0.0114
Epoch 6/10
1/1 [==============================] - 0s 331ms/step - loss: 5.7362 - accuracy: 0.0092 - val_loss: 4.6617 - val_accuracy: 0.0107
Epoch 7/10
1/1 [==============================] - 0s 348ms/step - loss: 5.0042 - accuracy: 0.0128 - val_loss: 4.6214 - val_accuracy: 0.0105
Epoch 8/10
1/1 [==============================] - 0s 344ms/step - loss: 4.7400 - accuracy: 0.0128 - val_loss: 4.6093 - val_accuracy: 0.0122
Epoch 9/10
1/1 [==============================] - 0s 350ms/step - loss: 4.6622 - accuracy: 0.0116 - val_loss: 4.6065 - val_accuracy: 0.0128
Epoch 10/10
1/1 [==============================] - 0s 346ms/step - loss: 4.6284 - accuracy: 0.0096 - val_loss: 4.6063 - val_accuracy: 0.0118

RuntimeError: ignored

### CIFAR10-*C*

#### Batches 1

In [ ]:
import numpy as np
import keras
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
# Load the CIFAR-10 dataset
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 3  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = np.copy(x_train).astype('float64')
if corruption_name == "speckle_noise":
    noise = np.random.randn(*corrupted_data.shape) * corruption_level
    corrupted_data += noise
    corrupted_data = np.clip(corrupted_data, 0., 255.)
    corrupted_data = corrupted_data.astype('uint8')
num_classes=10
# Convert labels to one-hot vectors
y_train_onehot = keras.utils.to_categorical(y_train, num_classes=10)
y_test_onehot = keras.utils.to_categorical(y_test, num_classes=10)
# Define the model architecture
model = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32 ,32 , 3)),
        Conv2D(32, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        Flatten(),
        Dense(512, activation='relu'),
        Dense(num_classes, activation='softmax')
        ])

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on the train set
model.fit(corrupted_data, y_train_onehot, batch_size=128, epochs=10, verbose=1)

# Evaluate the model on the test set
_, test_accuracy = model.evaluate(x_test, y_test_onehot, verbose=0)
print("Test Accuracy:", test_accuracy)

Epoch 1/10
391/391 [==============================] - 16s 11ms/step - loss: 2.2342 - accuracy: 0.4291
Epoch 2/10
391/391 [==============================] - 4s 10ms/step - loss: 1.2137 - accuracy: 0.5699
Epoch 3/10
391/391 [==============================] - 4s 10ms/step - loss: 1.0176 - accuracy: 0.6427
Epoch 4/10
391/391 [==============================] - 4s 10ms/step - loss: 0.8297 - accuracy: 0.7115
Epoch 5/10
391/391 [==============================] - 4s 10ms/step - loss: 0.6566 - accuracy: 0.7713
Epoch 6/10
391/391 [==============================] - 4s 11ms/step - loss: 0.4826 - accuracy: 0.8317
Epoch 7/10
391/391 [==============================] - 4s 10ms/step - loss: 0.3432 - accuracy: 0.8809
Epoch 8/10
391/391 [==============================] - 4s 10ms/step - loss: 0.2568 - accuracy: 0.9110
Epoch 9/10
391/391 [==============================] - 4s 11ms/step - loss: 0.1970 - accuracy: 0.9331
Epoch 10/10
391/391 [==============================] - 4s 10ms/step - loss: 0.1653 - accuracy: 0.9439
Test Accuracy: 0.6398000121116638

#### Batches 20

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

# Load the CIFAR-10 dataset
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 3  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = np.copy(x_train).astype('float64')
if corruption_name == "speckle_noise":
    noise = np.random.randn(*corrupted_data.shape) * corruption_level
    corrupted_data += noise
    corrupted_data = np.clip(corrupted_data, 0., 255.)
    corrupted_data = corrupted_data.astype('uint8')

# Convert the labels to one-hot encoding
num_classes = 10
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 20 batches
n_batches = 20
# batch_size = len(x_train) // num_batches
batch_size = corrupted_data.shape[0] // n_batches

# x_train_batches = np.array_split(corrupted_data, num_batches)
# y_train_batches = np.array_split(y_train, num_batches)

# Define the model architecture
model = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32 ,32 , 3)),
        Conv2D(32, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        Flatten(),
        Dense(512, activation='relu'),
        Dense(num_classes, activation='softmax')
        ])

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
# Train the model on the train set
for i in range(n_batches):
    start_index = i * batch_size
    end_index = (i + 1) * batch_size
    X_batch = corrupted_data[start_index:end_index]
    y_batch = y_train[start_index:end_index]
    # Train the model on the current batch
    model.fit(X_batch, y_batch, epochs=10, batch_size=32, verbose=1)
    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)

Epoch 1/10
79/79 [==============================] - 11s 13ms/step - loss: 2.3281 - accuracy: 0.0932
Epoch 2/10
79/79 [==============================] - 1s 7ms/step - loss: 2.3024 - accuracy: 0.1044
Epoch 3/10
79/79 [==============================] - 1s 7ms/step - loss: 2.3026 - accuracy: 0.1168
Epoch 4/10
79/79 [==============================] - 1s 8ms/step - loss: 2.2965 - accuracy: 0.1212
Epoch 5/10
79/79 [==============================] - 1s 8ms/step - loss: 2.2536 - accuracy: 0.1628
Epoch 6/10
79/79 [==============================] - 1s 7ms/step - loss: 2.1691 - accuracy: 0.2040
Epoch 7/10
79/79 [==============================] - 1s 8ms/step - loss: 2.1131 - accuracy: 0.2184
Epoch 8/10
79/79 [==============================] - 1s 7ms/step - loss: 1.9729 - accuracy: 0.2972
Epoch 9/10
79/79 [==============================] - 1s 7ms/step - loss: 1.6991 - accuracy: 0.4156
Epoch 10/10
79/79 [==============================] - 1s 7ms/step - loss: 1.2132 - accuracy: 0.5944
313/313 [==============================] - 2s 5ms/step - loss: 2.1869 - accuracy: 0.1934
Test Accuracy: 0.19339999556541443
Epoch 1/10
79/79 [==============================] - 0s 6ms/step - loss: 2.3111 - accuracy: 0.1500
Epoch 2/10
79/79 [==============================] - 0s 5ms/step - loss: 2.1918 - accuracy: 0.1852
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 2.0954 - accuracy: 0.2436
Epoch 4/10
79/79 [==============================] - 0s 5ms/step - loss: 1.8397 - accuracy: 0.3660
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 1.3177 - accuracy: 0.5644
Epoch 6/10
79/79 [==============================] - 0s 5ms/step - loss: 0.5411 - accuracy: 0.8376
Epoch 7/10
79/79 [==============================] - 0s 5ms/step - loss: 0.2466 - accuracy: 0.9276
Epoch 8/10
79/79 [==============================] - 0s 5ms/step - loss: 0.1240 - accuracy: 0.9652
Epoch 9/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0133 - accuracy: 0.9988
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0024 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 2.4345 - accuracy: 0.2250
Test Accuracy: 0.22499999403953552
Epoch 1/10
79/79 [==============================] - 0s 5ms/step - loss: 2.4871 - accuracy: 0.1216
Epoch 2/10
79/79 [==============================] - 0s 5ms/step - loss: 2.2295 - accuracy: 0.1592
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 2.1755 - accuracy: 0.2020
Epoch 4/10
79/79 [==============================] - 0s 5ms/step - loss: 2.0505 - accuracy: 0.2660
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 1.8510 - accuracy: 0.3612
Epoch 6/10
79/79 [==============================] - 0s 5ms/step - loss: 1.5185 - accuracy: 0.4892
Epoch 7/10
79/79 [==============================] - 0s 5ms/step - loss: 0.9104 - accuracy: 0.7088
Epoch 8/10
79/79 [==============================] - 0s 5ms/step - loss: 0.2714 - accuracy: 0.9256
Epoch 9/10
79/79 [==============================] - 0s 6ms/step - loss: 0.1258 - accuracy: 0.9740
Epoch 10/10
79/79 [==============================] - 1s 7ms/step - loss: 0.0121 - accuracy: 0.9992
313/313 [==============================] - 1s 4ms/step - loss: 2.6579 - accuracy: 0.2018
Test Accuracy: 0.20180000364780426
Epoch 1/10
79/79 [==============================] - 1s 6ms/step - loss: 2.5200 - accuracy: 0.1272
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 2.2320 - accuracy: 0.1680
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 2.1914 - accuracy: 0.1928
Epoch 4/10
79/79 [==============================] - 0s 5ms/step - loss: 2.0651 - accuracy: 0.2580
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 1.8522 - accuracy: 0.3548
Epoch 6/10
79/79 [==============================] - 0s 5ms/step - loss: 1.4527 - accuracy: 0.5092
Epoch 7/10
79/79 [==============================] - 0s 5ms/step - loss: 0.8567 - accuracy: 0.7360
Epoch 8/10
79/79 [==============================] - 0s 5ms/step - loss: 0.2594 - accuracy: 0.9380
Epoch 9/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0574 - accuracy: 0.9928
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0106 - accuracy: 0.9996
313/313 [==============================] - 1s 3ms/step - loss: 2.9292 - accuracy: 0.1868
Test Accuracy: 0.1868000030517578
Epoch 1/10
79/79 [==============================] - 0s 6ms/step - loss: 2.5067 - accuracy: 0.1108
Epoch 2/10
79/79 [==============================] - 0s 5ms/step - loss: 2.2572 - accuracy: 0.1548
Epoch 3/10
79/79 [==============================] - 0s 6ms/step - loss: 2.1946 - accuracy: 0.1756
Epoch 4/10
79/79 [==============================] - 0s 6ms/step - loss: 2.1243 - accuracy: 0.2208
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 2.0457 - accuracy: 0.2560
Epoch 6/10
79/79 [==============================] - 0s 5ms/step - loss: 1.9207 - accuracy: 0.3176
Epoch 7/10
79/79 [==============================] - 1s 7ms/step - loss: 1.7004 - accuracy: 0.4008
Epoch 8/10
79/79 [==============================] - 1s 7ms/step - loss: 1.3579 - accuracy: 0.5432
Epoch 9/10
79/79 [==============================] - 1s 7ms/step - loss: 0.9448 - accuracy: 0.7032
Epoch 10/10
79/79 [==============================] - 1s 7ms/step - loss: 0.5010 - accuracy: 0.8600
313/313 [==============================] - 1s 3ms/step - loss: 3.2535 - accuracy: 0.1637
Test Accuracy: 0.16369999945163727
Epoch 1/10
79/79 [==============================] - 0s 6ms/step - loss: 2.4382 - accuracy: 0.1096
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 2.2947 - accuracy: 0.1160
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 2.2770 - accuracy: 0.1220
Epoch 4/10
79/79 [==============================] - 0s 5ms/step - loss: 2.2536 - accuracy: 0.1400
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 2.2335 - accuracy: 0.1392
Epoch 6/10
79/79 [==============================] - 0s 5ms/step - loss: 2.2067 - accuracy: 0.1596
Epoch 7/10
79/79 [==============================] - 0s 5ms/step - loss: 2.2090 - accuracy: 0.1484
Epoch 8/10
79/79 [==============================] - 0s 5ms/step - loss: 2.1546 - accuracy: 0.1804
Epoch 9/10
79/79 [==============================] - 0s 5ms/step - loss: 2.1130 - accuracy: 0.1956
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 2.0828 - accuracy: 0.2088
313/313 [==============================] - 1s 3ms/step - loss: 2.5069 - accuracy: 0.1668
Test Accuracy: 0.16680000722408295
Epoch 1/10
79/79 [==============================] - 1s 7ms/step - loss: 2.3402 - accuracy: 0.0984
Epoch 2/10
79/79 [==============================] - 1s 7ms/step - loss: 2.3051 - accuracy: 0.1036
Epoch 3/10
79/79 [==============================] - 1s 7ms/step - loss: 2.3026 - accuracy: 0.1084
Epoch 4/10
79/79 [==============================] - 1s 8ms/step - loss: 2.2968 - accuracy: 0.1056
Epoch 5/10
79/79 [==============================] - 1s 7ms/step - loss: 2.2891 - accuracy: 0.1000
Epoch 6/10
79/79 [==============================] - 1s 7ms/step - loss: 2.2773 - accuracy: 0.1060
Epoch 7/10
79/79 [==============================] - 1s 8ms/step - loss: 2.2562 - accuracy: 0.1240
Epoch 8/10
79/79 [==============================] - 1s 8ms/step - loss: 2.2440 - accuracy: 0.1220
Epoch 9/10
79/79 [==============================] - 1s 7ms/step - loss: 2.2330 - accuracy: 0.1448
Epoch 10/10
79/79 [==============================] - 1s 7ms/step - loss: 2.2108 - accuracy: 0.1524
313/313 [==============================] - 1s 4ms/step - loss: 2.4134 - accuracy: 0.1605
Test Accuracy: 0.16050000488758087
Epoch 1/10
79/79 [==============================] - 1s 6ms/step - loss: 2.3120 - accuracy: 0.1012
Epoch 2/10
79/79 [==============================] - 0s 5ms/step - loss: 2.3024 - accuracy: 0.1092
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 2.3027 - accuracy: 0.1108
Epoch 4/10
79/79 [==============================] - 0s 5ms/step - loss: 2.2979 - accuracy: 0.1028
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 2.2952 - accuracy: 0.1060
Epoch 6/10
79/79 [==============================] - 0s 5ms/step - loss: 2.2920 - accuracy: 0.1148
Epoch 7/10
79/79 [==============================] - 0s 5ms/step - loss: 2.2875 - accuracy: 0.1092
Epoch 8/10
79/79 [==============================] - 0s 5ms/step - loss: 2.2821 - accuracy: 0.1144
Epoch 9/10
79/79 [==============================] - 1s 6ms/step - loss: 2.2708 - accuracy: 0.1224
Epoch 10/10
79/79 [==============================] - 1s 10ms/step - loss: 2.2435 - accuracy: 0.1312
313/313 [==============================] - 2s 5ms/step - loss: 2.3061 - accuracy: 0.1492
Test Accuracy: 0.14920000731945038
Epoch 1/10
79/79 [==============================] - 1s 10ms/step - loss: 2.3108 - accuracy: 0.0956
Epoch 2/10
79/79 [==============================] - 1s 9ms/step - loss: 2.3028 - accuracy: 0.0980
Epoch 3/10
79/79 [==============================] - 1s 9ms/step - loss: 2.3017 - accuracy: 0.1064
Epoch 4/10
79/79 [==============================] - 1s 9ms/step - loss: 2.2992 - accuracy: 0.1056
Epoch 5/10
79/79 [==============================] - 1s 9ms/step - loss: 2.2929 - accuracy: 0.1176
Epoch 6/10
79/79 [==============================] - 1s 9ms/step - loss: 2.2833 - accuracy: 0.1124
Epoch 7/10
79/79 [==============================] - 1s 9ms/step - loss: 2.2681 - accuracy: 0.1220
Epoch 8/10
79/79 [==============================] - 1s 9ms/step - loss: 2.2387 - accuracy: 0.1340
Epoch 9/10
79/79 [==============================] - 1s 10ms/step - loss: 2.2117 - accuracy: 0.1516
Epoch 10/10
79/79 [==============================] - 1s 9ms/step - loss: 2.1487 - accuracy: 0.1652
313/313 [==============================] - 3s 8ms/step - loss: 2.2925 - accuracy: 0.1659
Test Accuracy: 0.16590000689029694
Epoch 1/10
79/79 [==============================] - 1s 10ms/step - loss: 2.3167 - accuracy: 0.0896
Epoch 2/10
79/79 [==============================] - 1s 8ms/step - loss: 2.3044 - accuracy: 0.0988
Epoch 3/10
79/79 [==============================] - 1s 9ms/step - loss: 2.3042 - accuracy: 0.0972
Epoch 4/10
79/79 [==============================] - 1s 9ms/step - loss: 2.3049 - accuracy: 0.0932
Epoch 5/10
79/79 [==============================] - 1s 9ms/step - loss: 2.3043 - accuracy: 0.0980
Epoch 6/10
79/79 [==============================] - 1s 9ms/step - loss: 2.3049 - accuracy: 0.0952
Epoch 7/10
79/79 [==============================] - 1s 8ms/step - loss: 2.3048 - accuracy: 0.0916
Epoch 8/10
79/79 [==============================] - 1s 8ms/step - loss: 2.3042 - accuracy: 0.0896
Epoch 9/10
79/79 [==============================] - 1s 10ms/step - loss: 2.3047 - accuracy: 0.0968
Epoch 10/10
79/79 [==============================] - 1s 8ms/step - loss: 2.3047 - accuracy: 0.0936
313/313 [==============================] - 2s 7ms/step - loss: 2.3037 - accuracy: 0.1025
Test Accuracy: 0.10249999910593033
Epoch 1/10
79/79 [==============================] - 1s 12ms/step - loss: 2.3056 - accuracy: 0.0916
Epoch 2/10
79/79 [==============================] - 1s 9ms/step - loss: 2.3036 - accuracy: 0.0996
Epoch 3/10
79/79 [==============================] - 1s 7ms/step - loss: 2.3033 - accuracy: 0.1024
Epoch 4/10
79/79 [==============================] - 0s 5ms/step - loss: 2.3036 - accuracy: 0.1072
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 2.3042 - accuracy: 0.1056
Epoch 6/10
79/79 [==============================] - 0s 6ms/step - loss: 2.3042 - accuracy: 0.0964
Epoch 7/10
79/79 [==============================] - 0s 5ms/step - loss: 2.3036 - accuracy: 0.1032
Epoch 8/10
79/79 [==============================] - 0s 5ms/step - loss: 2.3038 - accuracy: 0.1036
Epoch 9/10
79/79 [==============================] - 0s 6ms/step - loss: 2.3040 - accuracy: 0.1080
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 2.3043 - accuracy: 0.1044
313/313 [==============================] - 1s 3ms/step - loss: 2.3033 - accuracy: 0.0998
Test Accuracy: 0.0997999981045723
Epoch 1/10
79/79 [==============================] - 0s 6ms/step - loss: 2.3050 - accuracy: 0.0968
Epoch 2/10
79/79 [==============================] - 0s 5ms/step - loss: 2.3031 - accuracy: 0.0992
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 2.3029 - accuracy: 0.1028
Epoch 4/10
79/79 [==============================] - 1s 6ms/step - loss: 2.3025 - accuracy: 0.1048
Epoch 5/10
79/79 [==============================] - 1s 7ms/step - loss: 2.3025 - accuracy: 0.1016
Epoch 6/10
79/79 [==============================] - 1s 7ms/step - loss: 2.3023 - accuracy: 0.1060
Epoch 7/10
79/79 [==============================] - 1s 7ms/step - loss: 2.3032 - accuracy: 0.1020
Epoch 8/10
79/79 [==============================] - 1s 7ms/step - loss: 2.3039 - accuracy: 0.0952
Epoch 9/10
79/79 [==============================] - 1s 6ms/step - loss: 2.3025 - accuracy: 0.1028
Epoch 10/10
79/79 [==============================] - 0s 6ms/step - loss: 2.3027 - accuracy: 0.1064
313/313 [==============================] - 1s 3ms/step - loss: 2.3047 - accuracy: 0.0981
Test Accuracy: 0.09809999912977219
Epoch 1/10
79/79 [==============================] - 0s 6ms/step - loss: 2.3065 - accuracy: 0.1000
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 2.3028 - accuracy: 0.0984
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 2.3024 - accuracy: 0.1100
Epoch 4/10
79/79 [==============================] - 0s 5ms/step - loss: 2.3025 - accuracy: 0.1116
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 2.3031 - accuracy: 0.1128
Epoch 6/10
79/79 [==============================] - 0s 5ms/step - loss: 2.3024 - accuracy: 0.1080
Epoch 7/10
79/79 [==============================] - 0s 5ms/step - loss: 2.3021 - accuracy: 0.1016
Epoch 8/10
79/79 [==============================] - 0s 5ms/step - loss: 2.3031 - accuracy: 0.1128
Epoch 9/10
79/79 [==============================] - 0s 5ms/step - loss: 2.3027 - accuracy: 0.1032
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 2.3023 - accuracy: 0.1024
313/313 [==============================] - 1s 3ms/step - loss: 2.3038 - accuracy: 0.1002
Test Accuracy: 0.10019999742507935
Epoch 1/10
79/79 [==============================] - 0s 6ms/step - loss: 2.3046 - accuracy: 0.0960
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 2.3032 - accuracy: 0.1024
Epoch 3/10
79/79 [==============================] - 1s 8ms/step - loss: 2.3036 - accuracy: 0.1040
Epoch 4/10
79/79 [==============================] - 1s 7ms/step - loss: 2.3030 - accuracy: 0.1080
Epoch 5/10
79/79 [==============================] - 1s 7ms/step - loss: 2.3032 - accuracy: 0.0988
Epoch 6/10
79/79 [==============================] - 1s 7ms/step - loss: 2.3031 - accuracy: 0.1060
Epoch 7/10
79/79 [==============================] - 1s 7ms/step - loss: 2.3026 - accuracy: 0.1088
Epoch 8/10
79/79 [==============================] - 0s 5ms/step - loss: 2.3029 - accuracy: 0.0956
Epoch 9/10
79/79 [==============================] - 0s 6ms/step - loss: 2.3032 - accuracy: 0.1080
Epoch 10/10
79/79 [==============================] - 0s 6ms/step - loss: 2.3030 - accuracy: 0.0996
313/313 [==============================] - 1s 4ms/step - loss: 2.3042 - accuracy: 0.1002
Test Accuracy: 0.10019999742507935
Epoch 1/10
79/79 [==============================] - 1s 10ms/step - loss: 2.3046 - accuracy: 0.0940
Epoch 2/10
79/79 [==============================] - 1s 9ms/step - loss: 2.3036 - accuracy: 0.1056
Epoch 3/10
79/79 [==============================] - 1s 11ms/step - loss: 2.3027 - accuracy: 0.1112
Epoch 4/10
79/79 [==============================] - 1s 9ms/step - loss: 2.3033 - accuracy: 0.1112
Epoch 5/10
79/79 [==============================] - 1s 8ms/step - loss: 2.3033 - accuracy: 0.1112
Epoch 6/10
79/79 [==============================] - 1s 7ms/step - loss: 2.3034 - accuracy: 0.1084
Epoch 7/10
79/79 [==============================] - 0s 6ms/step - loss: 2.3033 - accuracy: 0.1044
Epoch 8/10
79/79 [==============================] - 0s 6ms/step - loss: 2.3028 - accuracy: 0.1112
Epoch 9/10
79/79 [==============================] - 0s 6ms/step - loss: 2.3026 - accuracy: 0.1112
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 2.3031 - accuracy: 0.1112
313/313 [==============================] - 1s 4ms/step - loss: 2.3033 - accuracy: 0.1000
Test Accuracy: 0.10000000149011612
Epoch 1/10
79/79 [==============================] - 1s 7ms/step - loss: 2.3046 - accuracy: 0.1000
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 2.3034 - accuracy: 0.1056
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 2.3037 - accuracy: 0.1012
Epoch 4/10
79/79 [==============================] - 0s 5ms/step - loss: 2.3031 - accuracy: 0.0996
Epoch 5/10
79/79 [==============================] - 0s 6ms/step - loss: 2.3030 - accuracy: 0.0964
Epoch 6/10
79/79 [==============================] - 0s 6ms/step - loss: 2.3032 - accuracy: 0.0944
Epoch 7/10
79/79 [==============================] - 1s 7ms/step - loss: 2.3036 - accuracy: 0.0912
Epoch 8/10
79/79 [==============================] - 1s 7ms/step - loss: 2.3033 - accuracy: 0.0908
Epoch 9/10
79/79 [==============================] - 1s 7ms/step - loss: 2.3034 - accuracy: 0.1000
Epoch 10/10
79/79 [==============================] - 1s 8ms/step - loss: 2.3031 - accuracy: 0.1036
313/313 [==============================] - 1s 4ms/step - loss: 2.3031 - accuracy: 0.0997
Test Accuracy: 0.09969999641180038
Epoch 1/10
79/79 [==============================] - 1s 6ms/step - loss: 2.3041 - accuracy: 0.1012
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 2.3027 - accuracy: 0.1032
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 2.3026 - accuracy: 0.1044
Epoch 4/10
79/79 [==============================] - 0s 5ms/step - loss: 2.3023 - accuracy: 0.0976
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 2.3024 - accuracy: 0.1064
Epoch 6/10
79/79 [==============================] - 0s 5ms/step - loss: 2.3027 - accuracy: 0.1064
Epoch 7/10
79/79 [==============================] - 0s 5ms/step - loss: 2.3025 - accuracy: 0.0956
Epoch 8/10
79/79 [==============================] - 0s 5ms/step - loss: 2.3026 - accuracy: 0.1056
Epoch 9/10
79/79 [==============================] - 0s 5ms/step - loss: 2.3027 - accuracy: 0.0932
Epoch 10/10
79/79 [==============================] - 0s 6ms/step - loss: 2.3022 - accuracy: 0.1060
313/313 [==============================] - 1s 3ms/step - loss: 2.3035 - accuracy: 0.1022
Test Accuracy: 0.10220000147819519
Epoch 1/10
79/79 [==============================] - 0s 6ms/step - loss: 2.3050 - accuracy: 0.1040
Epoch 2/10
79/79 [==============================] - 0s 5ms/step - loss: 2.3016 - accuracy: 0.1040
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 2.3015 - accuracy: 0.1068
Epoch 4/10
79/79 [==============================] - 0s 6ms/step - loss: 2.3019 - accuracy: 0.1000
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 2.3012 - accuracy: 0.1036
Epoch 6/10
79/79 [==============================] - 1s 6ms/step - loss: 2.3013 - accuracy: 0.1064
Epoch 7/10
79/79 [==============================] - 1s 7ms/step - loss: 2.3010 - accuracy: 0.1024
Epoch 8/10
79/79 [==============================] - 1s 7ms/step - loss: 2.3013 - accuracy: 0.1084
Epoch 9/10
79/79 [==============================] - 1s 7ms/step - loss: 2.3015 - accuracy: 0.1076
Epoch 10/10
79/79 [==============================] - 1s 7ms/step - loss: 2.3010 - accuracy: 0.1056
313/313 [==============================] - 1s 3ms/step - loss: 2.3042 - accuracy: 0.1000
Test Accuracy: 0.10000000149011612
Epoch 1/10
79/79 [==============================] - 0s 6ms/step - loss: 2.3039 - accuracy: 0.1076

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam

# Load the CIFAR-100 dataset
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 0.1  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = x_train + tf.random.normal(shape=x_train.shape, mean=0.0, stddev=corruption_level, dtype=tf.float32)
corrupted_data = tf.clip_by_value(corrupted_data, 0.0, 1.0)

# Convert the labels to one-hot encoding
num_classes = 10
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 2 batches
n_batches = 20
batch_size = x_train.shape[0] // n_batches

# Define the model architecture
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)))
model.add(Conv2D(32, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch separately
for i in range(n_batches):
    start_index = i * batch_size
    end_index = (i + 1) * batch_size
    x_batch = corrupted_data[start_index:end_index]
    y_batch = y_train[start_index:end_index]

    # Train the model on the current batch
    model.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)

Epoch 1/10
79/79 [==============================] - 10s 15ms/step - loss: 1.9730 - accuracy: 0.2664
Epoch 2/10
79/79 [==============================] - 1s 9ms/step - loss: 1.6952 - accuracy: 0.3856
Epoch 3/10
79/79 [==============================] - 1s 8ms/step - loss: 1.5446 - accuracy: 0.4396
Epoch 4/10
79/79 [==============================] - 1s 8ms/step - loss: 1.4160 - accuracy: 0.4912
Epoch 5/10
79/79 [==============================] - 1s 11ms/step - loss: 1.3007 - accuracy: 0.5160
Epoch 6/10
79/79 [==============================] - 1s 12ms/step - loss: 1.1089 - accuracy: 0.5984
Epoch 7/10
79/79 [==============================] - 1s 13ms/step - loss: 0.8715 - accuracy: 0.6968
Epoch 8/10
79/79 [==============================] - 1s 10ms/step - loss: 0.6841 - accuracy: 0.7564
Epoch 9/10
79/79 [==============================] - 1s 8ms/step - loss: 0.4672 - accuracy: 0.8400
Epoch 10/10
79/79 [==============================] - 1s 10ms/step - loss: 0.2665 - accuracy: 0.9076
313/313 [==============================] - 2s 5ms/step - loss: 2.6595 - accuracy: 0.4594
Test Accuracy: 0.4593999981880188
Epoch 1/10
79/79 [==============================] - 1s 12ms/step - loss: 1.6609 - accuracy: 0.4352
Epoch 2/10
79/79 [==============================] - 1s 10ms/step - loss: 1.1950 - accuracy: 0.5628
Epoch 3/10
79/79 [==============================] - 1s 8ms/step - loss: 0.8496 - accuracy: 0.7036
Epoch 4/10
79/79 [==============================] - 1s 7ms/step - loss: 0.5395 - accuracy: 0.8228
Epoch 5/10
79/79 [==============================] - 1s 8ms/step - loss: 0.2388 - accuracy: 0.9248
Epoch 6/10
79/79 [==============================] - 1s 8ms/step - loss: 0.0827 - accuracy: 0.9796
Epoch 7/10
79/79 [==============================] - 1s 7ms/step - loss: 0.0416 - accuracy: 0.9864
Epoch 8/10
79/79 [==============================] - 1s 7ms/step - loss: 0.0322 - accuracy: 0.9912
Epoch 9/10
79/79 [==============================] - 1s 6ms/step - loss: 0.0476 - accuracy: 0.9860
Epoch 10/10
79/79 [==============================] - 0s 6ms/step - loss: 0.1406 - accuracy: 0.9548
313/313 [==============================] - 3s 9ms/step - loss: 3.0857 - accuracy: 0.4883
Test Accuracy: 0.48829999566078186
Epoch 1/10
79/79 [==============================] - 1s 10ms/step - loss: 1.6512 - accuracy: 0.4420
Epoch 2/10
79/79 [==============================] - 1s 12ms/step - loss: 1.0180 - accuracy: 0.6348
Epoch 3/10
79/79 [==============================] - 1s 11ms/step - loss: 0.5790 - accuracy: 0.7940
Epoch 4/10
79/79 [==============================] - 1s 10ms/step - loss: 0.2001 - accuracy: 0.9376
Epoch 5/10
79/79 [==============================] - 1s 12ms/step - loss: 0.1217 - accuracy: 0.9660
Epoch 6/10
79/79 [==============================] - 1s 10ms/step - loss: 0.0412 - accuracy: 0.9908
Epoch 7/10
79/79 [==============================] - 1s 11ms/step - loss: 0.0058 - accuracy: 1.0000
Epoch 8/10
79/79 [==============================] - 1s 9ms/step - loss: 0.0034 - accuracy: 0.9996
Epoch 9/10
79/79 [==============================] - 1s 8ms/step - loss: 0.0039 - accuracy: 0.9988
Epoch 10/10
79/79 [==============================] - 1s 10ms/step - loss: 0.0316 - accuracy: 0.9896
313/313 [==============================] - 1s 3ms/step - loss: 3.1088 - accuracy: 0.5209
Test Accuracy: 0.5209000110626221
Epoch 1/10
79/79 [==============================] - 0s 6ms/step - loss: 1.7148 - accuracy: 0.4520
Epoch 2/10
79/79 [==============================] - 0s 5ms/step - loss: 0.9548 - accuracy: 0.6744
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 0.4386 - accuracy: 0.8596
Epoch 4/10
79/79 [==============================] - 0s 5ms/step - loss: 0.1129 - accuracy: 0.9676
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 0.1027 - accuracy: 0.9680
Epoch 6/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0234 - accuracy: 0.9952
Epoch 7/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0105 - accuracy: 0.9996
Epoch 8/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0015 - accuracy: 1.0000
Epoch 9/10
79/79 [==============================] - 0s 5ms/step - loss: 5.8338e-04 - accuracy: 1.0000
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 4.1715e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 3.0977 - accuracy: 0.5335
Test Accuracy: 0.5335000157356262
Epoch 1/10
79/79 [==============================] - 0s 6ms/step - loss: 1.7133 - accuracy: 0.4584
Epoch 2/10
79/79 [==============================] - 0s 5ms/step - loss: 0.9220 - accuracy: 0.6868
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 0.3784 - accuracy: 0.8772
Epoch 4/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0715 - accuracy: 0.9840
Epoch 5/10
79/79 [==============================] - 0s 6ms/step - loss: 0.0179 - accuracy: 0.9964
Epoch 6/10
79/79 [==============================] - 1s 8ms/step - loss: 0.0091 - accuracy: 0.9980
Epoch 7/10
79/79 [==============================] - 1s 8ms/step - loss: 0.0049 - accuracy: 0.9988
Epoch 8/10
79/79 [==============================] - 1s 7ms/step - loss: 0.0099 - accuracy: 0.9984
Epoch 9/10
79/79 [==============================] - 1s 7ms/step - loss: 0.0025 - accuracy: 0.9996
Epoch 10/10
79/79 [==============================] - 1s 7ms/step - loss: 6.5565e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 3.1652 - accuracy: 0.5517
Test Accuracy: 0.5516999959945679
Epoch 1/10
79/79 [==============================] - 0s 6ms/step - loss: 1.6966 - accuracy: 0.4508
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 0.8986 - accuracy: 0.6920
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 0.3678 - accuracy: 0.8848
Epoch 4/10
79/79 [==============================] - 0s 6ms/step - loss: 0.0901 - accuracy: 0.9796
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0155 - accuracy: 0.9972
Epoch 6/10
79/79 [==============================] - 0s 6ms/step - loss: 0.0034 - accuracy: 1.0000
Epoch 7/10
79/79 [==============================] - 0s 6ms/step - loss: 0.0012 - accuracy: 1.0000
Epoch 8/10
79/79 [==============================] - 0s 5ms/step - loss: 6.5563e-04 - accuracy: 1.0000
Epoch 9/10
79/79 [==============================] - 0s 6ms/step - loss: 5.0186e-04 - accuracy: 1.0000
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 3.9122e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 3.0735 - accuracy: 0.5496
Test Accuracy: 0.5496000051498413
Epoch 1/10
79/79 [==============================] - 0s 6ms/step - loss: 1.6627 - accuracy: 0.4748
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 0.8535 - accuracy: 0.7120
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 0.3426 - accuracy: 0.8904
Epoch 4/10
79/79 [==============================] - 1s 7ms/step - loss: 0.0836 - accuracy: 0.9792
Epoch 5/10
79/79 [==============================] - 1s 8ms/step - loss: 0.0151 - accuracy: 0.9976
Epoch 6/10
79/79 [==============================] - 1s 8ms/step - loss: 0.0019 - accuracy: 1.0000
Epoch 7/10
79/79 [==============================] - 1s 8ms/step - loss: 8.9404e-04 - accuracy: 1.0000
Epoch 8/10
79/79 [==============================] - 1s 8ms/step - loss: 6.2866e-04 - accuracy: 1.0000
Epoch 9/10
79/79 [==============================] - 0s 6ms/step - loss: 4.8358e-04 - accuracy: 1.0000
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 3.8893e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 3.0031 - accuracy: 0.5649
Test Accuracy: 0.5648999810218811
Epoch 1/10
79/79 [==============================] - 0s 6ms/step - loss: 1.6641 - accuracy: 0.4692
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 0.8602 - accuracy: 0.6976
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 0.3271 - accuracy: 0.8996
Epoch 4/10
79/79 [==============================] - 0s 6ms/step - loss: 0.1069 - accuracy: 0.9712
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0177 - accuracy: 0.9976
Epoch 6/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0032 - accuracy: 1.0000
Epoch 7/10
79/79 [==============================] - 0s 6ms/step - loss: 0.0012 - accuracy: 1.0000
Epoch 8/10
79/79 [==============================] - 0s 6ms/step - loss: 7.0865e-04 - accuracy: 1.0000
Epoch 9/10
79/79 [==============================] - 0s 5ms/step - loss: 5.3153e-04 - accuracy: 1.0000
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 4.1369e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 4ms/step - loss: 2.9161 - accuracy: 0.5657
Test Accuracy: 0.5656999945640564
Epoch 1/10
79/79 [==============================] - 1s 7ms/step - loss: 1.6410 - accuracy: 0.4736
Epoch 2/10
79/79 [==============================] - 1s 7ms/step - loss: 0.8160 - accuracy: 0.7128
Epoch 3/10
79/79 [==============================] - 1s 7ms/step - loss: 0.2859 - accuracy: 0.9144
Epoch 4/10
79/79 [==============================] - 1s 7ms/step - loss: 0.0665 - accuracy: 0.9848
Epoch 5/10
79/79 [==============================] - 1s 7ms/step - loss: 0.0142 - accuracy: 0.9976
Epoch 6/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0022 - accuracy: 1.0000
Epoch 7/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0010 - accuracy: 1.0000
Epoch 8/10
79/79 [==============================] - 0s 5ms/step - loss: 7.2524e-04 - accuracy: 1.0000
Epoch 9/10
79/79 [==============================] - 0s 5ms/step - loss: 5.5334e-04 - accuracy: 1.0000
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 4.4266e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 2.7781 - accuracy: 0.5754
Test Accuracy: 0.5753999948501587
Epoch 1/10
79/79 [==============================] - 0s 6ms/step - loss: 1.5312 - accuracy: 0.5056
Epoch 2/10
79/79 [==============================] - 0s 5ms/step - loss: 0.7005 - accuracy: 0.7600
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 0.2170 - accuracy: 0.9356
Epoch 4/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0360 - accuracy: 0.9928
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0058 - accuracy: 0.9996
Epoch 6/10
79/79 [==============================] - 0s 6ms/step - loss: 0.0015 - accuracy: 1.0000
Epoch 7/10
79/79 [==============================] - 0s 5ms/step - loss: 7.7247e-04 - accuracy: 1.0000
Epoch 8/10
79/79 [==============================] - 0s 5ms/step - loss: 5.7550e-04 - accuracy: 1.0000
Epoch 9/10
79/79 [==============================] - 0s 6ms/step - loss: 4.5405e-04 - accuracy: 1.0000
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 3.7349e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 4ms/step - loss: 2.8585 - accuracy: 0.5696
Test Accuracy: 0.569599986076355
Epoch 1/10
79/79 [==============================] - 1s 7ms/step - loss: 1.5760 - accuracy: 0.5064
Epoch 2/10
79/79 [==============================] - 1s 8ms/step - loss: 0.7102 - accuracy: 0.7716
Epoch 3/10
79/79 [==============================] - 1s 8ms/step - loss: 0.2276 - accuracy: 0.9316
Epoch 4/10
79/79 [==============================] - 1s 7ms/step - loss: 0.0368 - accuracy: 0.9916
Epoch 5/10
79/79 [==============================] - 0s 6ms/step - loss: 0.0225 - accuracy: 0.9948
Epoch 6/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0030 - accuracy: 0.9996
Epoch 7/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0010 - accuracy: 1.0000
Epoch 8/10
79/79 [==============================] - 0s 5ms/step - loss: 7.1808e-04 - accuracy: 1.0000
Epoch 9/10
79/79 [==============================] - 0s 5ms/step - loss: 5.4881e-04 - accuracy: 1.0000
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 4.3993e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 2.7931 - accuracy: 0.5752
Test Accuracy: 0.5752000212669373
Epoch 1/10
79/79 [==============================] - 1s 8ms/step - loss: 1.4980 - accuracy: 0.5112
Epoch 2/10
79/79 [==============================] - 1s 7ms/step - loss: 0.7036 - accuracy: 0.7612
Epoch 3/10
79/79 [==============================] - 1s 8ms/step - loss: 0.2078 - accuracy: 0.9456
Epoch 4/10
79/79 [==============================] - 1s 7ms/step - loss: 0.0283 - accuracy: 0.9960
Epoch 5/10
79/79 [==============================] - 1s 8ms/step - loss: 0.0037 - accuracy: 1.0000
Epoch 6/10
79/79 [==============================] - 1s 6ms/step - loss: 0.0013 - accuracy: 1.0000
Epoch 7/10
79/79 [==============================] - 0s 5ms/step - loss: 8.1158e-04 - accuracy: 1.0000
Epoch 8/10
79/79 [==============================] - 0s 5ms/step - loss: 5.9301e-04 - accuracy: 1.0000
Epoch 9/10
79/79 [==============================] - 0s 5ms/step - loss: 4.5695e-04 - accuracy: 1.0000
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 3.6596e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 4ms/step - loss: 2.6469 - accuracy: 0.5929
Test Accuracy: 0.5928999781608582
Epoch 1/10
79/79 [==============================] - 1s 7ms/step - loss: 1.5626 - accuracy: 0.5056
Epoch 2/10
79/79 [==============================] - 1s 7ms/step - loss: 0.7720 - accuracy: 0.7456
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 0.2531 - accuracy: 0.9196
Epoch 4/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0317 - accuracy: 0.9940
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0087 - accuracy: 0.9988
Epoch 6/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0018 - accuracy: 1.0000
Epoch 7/10
79/79 [==============================] - 0s 5ms/step - loss: 9.4104e-04 - accuracy: 1.0000
Epoch 8/10
79/79 [==============================] - 0s 6ms/step - loss: 6.6134e-04 - accuracy: 1.0000
Epoch 9/10
79/79 [==============================] - 0s 5ms/step - loss: 5.0550e-04 - accuracy: 1.0000
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 3.9822e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 2.7107 - accuracy: 0.5816
Test Accuracy: 0.58160001039505
Epoch 1/10
79/79 [==============================] - 0s 6ms/step - loss: 1.5713 - accuracy: 0.5076
Epoch 2/10
79/79 [==============================] - 0s 5ms/step - loss: 0.7054 - accuracy: 0.7536
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 0.2285 - accuracy: 0.9300
Epoch 4/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0348 - accuracy: 0.9928
Epoch 5/10
79/79 [==============================] - 0s 6ms/step - loss: 0.0054 - accuracy: 0.9996
Epoch 6/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0018 - accuracy: 1.0000
Epoch 7/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0012 - accuracy: 1.0000
Epoch 8/10
79/79 [==============================] - 0s 5ms/step - loss: 8.2169e-04 - accuracy: 1.0000
Epoch 9/10
79/79 [==============================] - 0s 5ms/step - loss: 5.2807e-04 - accuracy: 1.0000
Epoch 10/10
79/79 [==============================] - 1s 7ms/step - loss: 2.9850e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 4ms/step - loss: 2.6391 - accuracy: 0.6022
Test Accuracy: 0.6021999716758728
Epoch 1/10
79/79 [==============================] - 1s 8ms/step - loss: 1.4898 - accuracy: 0.5264
Epoch 2/10
79/79 [==============================] - 1s 9ms/step - loss: 0.6591 - accuracy: 0.7748
Epoch 3/10
79/79 [==============================] - 0s 6ms/step - loss: 0.2018 - accuracy: 0.9424
Epoch 4/10
79/79 [==============================] - 0s 6ms/step - loss: 0.0421 - accuracy: 0.9916
Epoch 5/10
79/79 [==============================] - 0s 6ms/step - loss: 0.0076 - accuracy: 1.0000
Epoch 6/10
79/79 [==============================] - 0s 6ms/step - loss: 0.0020 - accuracy: 1.0000
Epoch 7/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0012 - accuracy: 1.0000
Epoch 8/10
79/79 [==============================] - 0s 6ms/step - loss: 8.3721e-04 - accuracy: 1.0000
Epoch 9/10
79/79 [==============================] - 0s 5ms/step - loss: 6.5239e-04 - accuracy: 1.0000
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 5.3000e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 2.5890 - accuracy: 0.5966
Test Accuracy: 0.5965999960899353
Epoch 1/10
79/79 [==============================] - 0s 5ms/step - loss: 1.4609 - accuracy: 0.5324
Epoch 2/10
79/79 [==============================] - 0s 5ms/step - loss: 0.6463 - accuracy: 0.7836
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 0.1916 - accuracy: 0.9412
Epoch 4/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0302 - accuracy: 0.9928
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0050 - accuracy: 1.0000
Epoch 6/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0019 - accuracy: 1.0000
Epoch 7/10
79/79 [==============================] - 1s 6ms/step - loss: 0.0012 - accuracy: 1.0000
Epoch 8/10
79/79 [==============================] - 1s 7ms/step - loss: 9.2303e-04 - accuracy: 1.0000
Epoch 9/10
79/79 [==============================] - 1s 7ms/step - loss: 7.2679e-04 - accuracy: 1.0000
Epoch 10/10
79/79 [==============================] - 1s 6ms/step - loss: 5.8937e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 2.4354 - accuracy: 0.6053
Test Accuracy: 0.6053000092506409
Epoch 1/10
79/79 [==============================] - 0s 6ms/step - loss: 1.5146 - accuracy: 0.4984
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 0.7267 - accuracy: 0.7520
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 0.2252 - accuracy: 0.9360
Epoch 4/10
79/79 [==============================] - 0s 6ms/step - loss: 0.0615 - accuracy: 0.9852
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0071 - accuracy: 0.9996
Epoch 6/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0020 - accuracy: 1.0000
Epoch 7/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0012 - accuracy: 1.0000
Epoch 8/10
79/79 [==============================] - 0s 5ms/step - loss: 8.8082e-04 - accuracy: 1.0000
Epoch 9/10
79/79 [==============================] - 0s 5ms/step - loss: 6.9400e-04 - accuracy: 1.0000
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 5.6453e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 2.4706 - accuracy: 0.6083
Test Accuracy: 0.608299970626831
Epoch 1/10
79/79 [==============================] - 0s 6ms/step - loss: 1.4476 - accuracy: 0.5360
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 0.6170 - accuracy: 0.7984
Epoch 3/10
79/79 [==============================] - 0s 6ms/step - loss: 0.1460 - accuracy: 0.9616
Epoch 4/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0215 - accuracy: 0.9984
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0044 - accuracy: 0.9996
Epoch 6/10
79/79 [==============================] - 1s 7ms/step - loss: 0.0022 - accuracy: 1.0000
Epoch 7/10
79/79 [==============================] - 1s 7ms/step - loss: 0.0015 - accuracy: 1.0000
Epoch 8/10
79/79 [==============================] - 1s 7ms/step - loss: 0.0011 - accuracy: 1.0000
Epoch 9/10
79/79 [==============================] - 1s 7ms/step - loss: 8.5811e-04 - accuracy: 1.0000
Epoch 10/10
79/79 [==============================] - 1s 7ms/step - loss: 6.9802e-04 - accuracy: 1.0000

#### Batches *10*

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

# Load the CIFAR-10 dataset
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 3  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = np.copy(x_train).astype('float64')
if corruption_name == "speckle_noise":
    noise = np.random.randn(*corrupted_data.shape) * corruption_level
    corrupted_data += noise
    corrupted_data = np.clip(corrupted_data, 0., 255.)
    corrupted_data = corrupted_data.astype('uint8')

# Convert the labels to one-hot encoding
num_classes = 10
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 20 batches
n_batches = 10
# batch_size = len(x_train) // num_batches
batch_size = corrupted_data.shape[0] // n_batches

# x_train_batches = np.array_split(corrupted_data, num_batches)
# y_train_batches = np.array_split(y_train, num_batches)

# Define the model architecture
model = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32 ,32 , 3)),
        Conv2D(32, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        Flatten(),
        Dense(512, activation='relu'),
        Dense(num_classes, activation='softmax')
        ])

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
# Train the model on the train set
for i in range(n_batches):
    start_index = i * batch_size
    end_index = (i + 1) * batch_size
    X_batch = corrupted_data[start_index:end_index]
    y_batch = y_train[start_index:end_index]
    # Train the model on the current batch
    model.fit(X_batch, y_batch, epochs=10, batch_size=32, verbose=1)
    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)

Epoch 1/10
157/157 [==============================] - 6s 7ms/step - loss: 2.3180 - accuracy: 0.0944
Epoch 2/10
157/157 [==============================] - 1s 5ms/step - loss: 2.3027 - accuracy: 0.1026
Epoch 3/10
157/157 [==============================] - 1s 5ms/step - loss: 2.3018 - accuracy: 0.0998
Epoch 4/10
157/157 [==============================] - 1s 5ms/step - loss: 2.3015 - accuracy: 0.1120
Epoch 5/10
157/157 [==============================] - 1s 5ms/step - loss: 2.2967 - accuracy: 0.1174
Epoch 6/10
157/157 [==============================] - 1s 5ms/step - loss: 2.2667 - accuracy: 0.1432
Epoch 7/10
157/157 [==============================] - 1s 5ms/step - loss: 2.2060 - accuracy: 0.1852
Epoch 8/10
157/157 [==============================] - 1s 5ms/step - loss: 2.1221 - accuracy: 0.2164
Epoch 9/10
157/157 [==============================] - 1s 5ms/step - loss: 2.0048 - accuracy: 0.2872
Epoch 10/10
157/157 [==============================] - 1s 8ms/step - loss: 1.7833 - accuracy: 0.3704
313/313 [==============================] - 2s 4ms/step - loss: 2.1263 - accuracy: 0.2285
Test Accuracy: 0.22849999368190765
Epoch 1/10
157/157 [==============================] - 1s 6ms/step - loss: 2.2270 - accuracy: 0.1690
Epoch 2/10
157/157 [==============================] - 1s 5ms/step - loss: 2.1368 - accuracy: 0.2122
Epoch 3/10
157/157 [==============================] - 1s 5ms/step - loss: 1.9948 - accuracy: 0.2872
Epoch 4/10
157/157 [==============================] - 1s 5ms/step - loss: 1.6936 - accuracy: 0.4100
Epoch 5/10
157/157 [==============================] - 1s 5ms/step - loss: 1.1423 - accuracy: 0.6194
Epoch 6/10
157/157 [==============================] - 1s 5ms/step - loss: 0.4459 - accuracy: 0.8666
Epoch 7/10
157/157 [==============================] - 1s 5ms/step - loss: 0.1119 - accuracy: 0.9720
Epoch 8/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0176 - accuracy: 0.9980
Epoch 9/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0027 - accuracy: 1.0000
Epoch 10/10
157/157 [==============================] - 1s 5ms/step - loss: 9.1398e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 2.5831 - accuracy: 0.2266
Test Accuracy: 0.22660000622272491
Epoch 1/10
157/157 [==============================] - 1s 6ms/step - loss: 2.4178 - accuracy: 0.1180
Epoch 2/10
157/157 [==============================] - 1s 5ms/step - loss: 2.2537 - accuracy: 0.1418
Epoch 3/10
157/157 [==============================] - 1s 5ms/step - loss: 2.2176 - accuracy: 0.1772
Epoch 4/10
157/157 [==============================] - 1s 5ms/step - loss: 2.1420 - accuracy: 0.2238
Epoch 5/10
157/157 [==============================] - 1s 5ms/step - loss: 1.9972 - accuracy: 0.2852
Epoch 6/10
157/157 [==============================] - 1s 5ms/step - loss: 1.7039 - accuracy: 0.4154
Epoch 7/10
157/157 [==============================] - 1s 5ms/step - loss: 1.1891 - accuracy: 0.6018
Epoch 8/10
157/157 [==============================] - 1s 5ms/step - loss: 0.5930 - accuracy: 0.8164
Epoch 9/10
157/157 [==============================] - 1s 5ms/step - loss: 0.1815 - accuracy: 0.9542
Epoch 10/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0304 - accuracy: 0.9958
313/313 [==============================] - 1s 5ms/step - loss: 2.7506 - accuracy: 0.1764
Test Accuracy: 0.17640000581741333
Epoch 1/10
157/157 [==============================] - 1s 6ms/step - loss: 2.4595 - accuracy: 0.1134
Epoch 2/10
157/157 [==============================] - 1s 5ms/step - loss: 2.2537 - accuracy: 0.1566
Epoch 3/10
157/157 [==============================] - 1s 5ms/step - loss: 2.1831 - accuracy: 0.1926
Epoch 4/10
157/157 [==============================] - 1s 5ms/step - loss: 2.0587 - accuracy: 0.2672
Epoch 5/10
157/157 [==============================] - 1s 5ms/step - loss: 1.8702 - accuracy: 0.3520
Epoch 6/10
157/157 [==============================] - 1s 5ms/step - loss: 1.5290 - accuracy: 0.4834
Epoch 7/10
157/157 [==============================] - 1s 5ms/step - loss: 1.0681 - accuracy: 0.6538
Epoch 8/10
157/157 [==============================] - 1s 5ms/step - loss: 0.5148 - accuracy: 0.8568
Epoch 9/10
157/157 [==============================] - 1s 5ms/step - loss: 0.1391 - accuracy: 0.9740
Epoch 10/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0200 - accuracy: 0.9996
313/313 [==============================] - 1s 4ms/step - loss: 2.8658 - accuracy: 0.2029
Test Accuracy: 0.2029000073671341
Epoch 1/10
157/157 [==============================] - 1s 6ms/step - loss: 2.4477 - accuracy: 0.1170
Epoch 2/10
157/157 [==============================] - 1s 5ms/step - loss: 2.2915 - accuracy: 0.1114
Epoch 3/10
157/157 [==============================] - 1s 5ms/step - loss: 2.2771 - accuracy: 0.1310
Epoch 4/10
157/157 [==============================] - 1s 5ms/step - loss: 2.2586 - accuracy: 0.1382
Epoch 5/10
157/157 [==============================] - 1s 5ms/step - loss: 2.2260 - accuracy: 0.1604
Epoch 6/10
157/157 [==============================] - 1s 5ms/step - loss: 2.1820 - accuracy: 0.1754
Epoch 7/10
157/157 [==============================] - 1s 5ms/step - loss: 2.1067 - accuracy: 0.2146
Epoch 8/10
157/157 [==============================] - 1s 5ms/step - loss: 2.0308 - accuracy: 0.2534
Epoch 9/10
157/157 [==============================] - 1s 5ms/step - loss: 1.9136 - accuracy: 0.3024
Epoch 10/10
157/157 [==============================] - 1s 5ms/step - loss: 1.7664 - accuracy: 0.3690
313/313 [==============================] - 1s 4ms/step - loss: 2.2081 - accuracy: 0.1850
Test Accuracy: 0.1850000023841858
Epoch 1/10
157/157 [==============================] - 1s 7ms/step - loss: 2.3469 - accuracy: 0.1124
Epoch 2/10
157/157 [==============================] - 1s 7ms/step - loss: 2.2900 - accuracy: 0.1294
Epoch 3/10
157/157 [==============================] - 1s 5ms/step - loss: 2.2745 - accuracy: 0.1304
Epoch 4/10
157/157 [==============================] - 1s 5ms/step - loss: 2.2377 - accuracy: 0.1472
Epoch 5/10
157/157 [==============================] - 1s 5ms/step - loss: 2.1892 - accuracy: 0.1812
Epoch 6/10
157/157 [==============================] - 1s 5ms/step - loss: 2.1503 - accuracy: 0.1844
Epoch 7/10
157/157 [==============================] - 1s 5ms/step - loss: 2.0816 - accuracy: 0.2326
Epoch 8/10
157/157 [==============================] - 1s 5ms/step - loss: 2.0094 - accuracy: 0.2602
Epoch 9/10
157/157 [==============================] - 1s 5ms/step - loss: 1.9180 - accuracy: 0.3016
Epoch 10/10
157/157 [==============================] - 1s 8ms/step - loss: 1.7886 - accuracy: 0.3512
313/313 [==============================] - 1s 3ms/step - loss: 2.4556 - accuracy: 0.1843
Test Accuracy: 0.1843000054359436
Epoch 1/10
157/157 [==============================] - 1s 7ms/step - loss: 2.3327 - accuracy: 0.1114
Epoch 2/10
157/157 [==============================] - 1s 7ms/step - loss: 2.2885 - accuracy: 0.1246
Epoch 3/10
157/157 [==============================] - 1s 5ms/step - loss: 2.2776 - accuracy: 0.1404
Epoch 4/10
157/157 [==============================] - 1s 5ms/step - loss: 2.2633 - accuracy: 0.1330
Epoch 5/10
157/157 [==============================] - 1s 5ms/step - loss: 2.2389 - accuracy: 0.1492
Epoch 6/10
157/157 [==============================] - 1s 5ms/step - loss: 2.2121 - accuracy: 0.1584
Epoch 7/10
157/157 [==============================] - 1s 5ms/step - loss: 2.1669 - accuracy: 0.1746
Epoch 8/10
157/157 [==============================] - 1s 5ms/step - loss: 2.1320 - accuracy: 0.1928
Epoch 9/10
157/157 [==============================] - 1s 5ms/step - loss: 2.0769 - accuracy: 0.2112
Epoch 10/10
157/157 [==============================] - 1s 5ms/step - loss: 2.0267 - accuracy: 0.2274
313/313 [==============================] - 1s 3ms/step - loss: 2.2373 - accuracy: 0.1533
Test Accuracy: 0.15330000221729279
Epoch 1/10
157/157 [==============================] - 1s 5ms/step - loss: 2.3260 - accuracy: 0.1048
Epoch 2/10
157/157 [==============================] - 1s 5ms/step - loss: 2.2856 - accuracy: 0.1174
Epoch 3/10
157/157 [==============================] - 1s 7ms/step - loss: 2.2766 - accuracy: 0.1158
Epoch 4/10
157/157 [==============================] - 1s 8ms/step - loss: 2.2442 - accuracy: 0.1396
Epoch 5/10
157/157 [==============================] - 1s 8ms/step - loss: 2.2115 - accuracy: 0.1482
Epoch 6/10
157/157 [==============================] - 1s 8ms/step - loss: 2.1778 - accuracy: 0.1602
Epoch 7/10
157/157 [==============================] - 1s 5ms/step - loss: 2.1591 - accuracy: 0.1712
Epoch 8/10
157/157 [==============================] - 1s 5ms/step - loss: 2.1244 - accuracy: 0.1780
Epoch 9/10
157/157 [==============================] - 1s 5ms/step - loss: 2.0875 - accuracy: 0.1970
Epoch 10/10
157/157 [==============================] - 1s 5ms/step - loss: 2.0462 - accuracy: 0.2100
313/313 [==============================] - 1s 4ms/step - loss: 2.2980 - accuracy: 0.1397
Test Accuracy: 0.1396999955177307
Epoch 1/10
157/157 [==============================] - 1s 6ms/step - loss: 2.3145 - accuracy: 0.1020
Epoch 2/10
157/157 [==============================] - 1s 5ms/step - loss: 2.3026 - accuracy: 0.0980
Epoch 3/10
157/157 [==============================] - 1s 5ms/step - loss: 2.2969 - accuracy: 0.0998
Epoch 4/10
157/157 [==============================] - 1s 5ms/step - loss: 2.2928 - accuracy: 0.1126
Epoch 5/10
157/157 [==============================] - 1s 7ms/step - loss: 2.2947 - accuracy: 0.1110
Epoch 6/10
157/157 [==============================] - 1s 7ms/step - loss: 2.2899 - accuracy: 0.1010
Epoch 7/10
157/157 [==============================] - 1s 6ms/step - loss: 2.2805 - accuracy: 0.1140
Epoch 8/10
157/157 [==============================] - 1s 5ms/step - loss: 2.2705 - accuracy: 0.1210
Epoch 9/10
157/157 [==============================] - 1s 5ms/step - loss: 2.2564 - accuracy: 0.1240
Epoch 10/10
157/157 [==============================] - 1s 5ms/step - loss: 2.2390 - accuracy: 0.1342
313/313 [==============================] - 1s 3ms/step - loss: 2.3645 - accuracy: 0.1222
Test Accuracy: 0.12219999730587006
Epoch 1/10
157/157 [==============================] - 1s 6ms/step - loss: 2.3049 - accuracy: 0.1070
Epoch 2/10
157/157 [==============================] - 1s 5ms/step - loss: 2.3046 - accuracy: 0.0924
Epoch 3/10
157/157 [==============================] - 1s 5ms/step - loss: 2.2982 - accuracy: 0.1068
Epoch 4/10
157/157 [==============================] - 1s 5ms/step - loss: 2.2920 - accuracy: 0.1076
Epoch 5/10
157/157 [==============================] - 1s 5ms/step - loss: 2.2851 - accuracy: 0.1110
Epoch 6/10
157/157 [==============================] - 1s 5ms/step - loss: 2.2848 - accuracy: 0.1062
Epoch 7/10
157/157 [==============================] - 1s 7ms/step - loss: 2.2818 - accuracy: 0.1104
Epoch 8/10
157/157 [==============================] - 1s 7ms/step - loss: 2.2768 - accuracy: 0.1220
Epoch 9/10
157/157 [==============================] - 1s 7ms/step - loss: 2.2618 - accuracy: 0.1258
Epoch 10/10
157/157 [==============================] - 1s 5ms/step - loss: 2.2471 - accuracy: 0.1380
313/313 [==============================] - 1s 4ms/step - loss: 2.2145 - accuracy: 0.1747
Test Accuracy: 0.17470000684261322

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam

# Load the CIFAR-100 dataset
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 0.1  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = x_train + tf.random.normal(shape=x_train.shape, mean=0.0, stddev=corruption_level, dtype=tf.float32)
corrupted_data = tf.clip_by_value(corrupted_data, 0.0, 1.0)

# Convert the labels to one-hot encoding
num_classes = 10
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 2 batches
n_batches = 10
batch_size = x_train.shape[0] // n_batches

# Define the model architecture
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)))
model.add(Conv2D(32, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch separately
for i in range(n_batches):
    start_index = i * batch_size
    end_index = (i + 1) * batch_size
    x_batch = corrupted_data[start_index:end_index]
    y_batch = y_train[start_index:end_index]

    # Train the model on the current batch
    model.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)

Epoch 1/10
157/157 [==============================] - 10s 12ms/step - loss: 2.0125 - accuracy: 0.2510
Epoch 2/10
157/157 [==============================] - 2s 11ms/step - loss: 1.6661 - accuracy: 0.3944
Epoch 3/10
157/157 [==============================] - 2s 10ms/step - loss: 1.4772 - accuracy: 0.4650
Epoch 4/10
157/157 [==============================] - 1s 9ms/step - loss: 1.3025 - accuracy: 0.5234
Epoch 5/10
157/157 [==============================] - 1s 8ms/step - loss: 1.1220 - accuracy: 0.5964
Epoch 6/10
157/157 [==============================] - 1s 8ms/step - loss: 0.8825 - accuracy: 0.6892
Epoch 7/10
157/157 [==============================] - 1s 9ms/step - loss: 0.6529 - accuracy: 0.7690
Epoch 8/10
157/157 [==============================] - 1s 9ms/step - loss: 0.3891 - accuracy: 0.8678
Epoch 9/10
157/157 [==============================] - 2s 14ms/step - loss: 0.2531 - accuracy: 0.9118
Epoch 10/10
157/157 [==============================] - 2s 13ms/step - loss: 0.1535 - accuracy: 0.9494
313/313 [==============================] - 2s 5ms/step - loss: 2.5355 - accuracy: 0.5076
Test Accuracy: 0.5076000094413757
Epoch 1/10
157/157 [==============================] - 1s 7ms/step - loss: 1.4544 - accuracy: 0.5076
Epoch 2/10
157/157 [==============================] - 1s 7ms/step - loss: 0.9918 - accuracy: 0.6508
Epoch 3/10
157/157 [==============================] - 1s 7ms/step - loss: 0.6255 - accuracy: 0.7906
Epoch 4/10
157/157 [==============================] - 1s 7ms/step - loss: 0.2938 - accuracy: 0.9048
Epoch 5/10
157/157 [==============================] - 1s 7ms/step - loss: 0.1247 - accuracy: 0.9598
Epoch 6/10
157/157 [==============================] - 1s 7ms/step - loss: 0.0731 - accuracy: 0.9808
Epoch 7/10
157/157 [==============================] - 1s 7ms/step - loss: 0.0308 - accuracy: 0.9914
Epoch 8/10
157/157 [==============================] - 2s 10ms/step - loss: 0.0193 - accuracy: 0.9952
Epoch 9/10
157/157 [==============================] - 2s 10ms/step - loss: 0.0651 - accuracy: 0.9818
Epoch 10/10
157/157 [==============================] - 1s 7ms/step - loss: 0.0804 - accuracy: 0.9740
313/313 [==============================] - 1s 4ms/step - loss: 2.9404 - accuracy: 0.5465
Test Accuracy: 0.546500027179718
Epoch 1/10
157/157 [==============================] - 1s 6ms/step - loss: 1.4221 - accuracy: 0.5234
Epoch 2/10
157/157 [==============================] - 1s 5ms/step - loss: 0.8121 - accuracy: 0.7116
Epoch 3/10
157/157 [==============================] - 1s 5ms/step - loss: 0.3700 - accuracy: 0.8752
Epoch 4/10
157/157 [==============================] - 1s 5ms/step - loss: 0.1274 - accuracy: 0.9632
Epoch 5/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0782 - accuracy: 0.9754
Epoch 6/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0458 - accuracy: 0.9868
Epoch 7/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0125 - accuracy: 0.9974
Epoch 8/10
157/157 [==============================] - 1s 7ms/step - loss: 0.0045 - accuracy: 0.9994
Epoch 9/10
157/157 [==============================] - 1s 7ms/step - loss: 7.9680e-04 - accuracy: 1.0000
Epoch 10/10
157/157 [==============================] - 1s 6ms/step - loss: 2.8862e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 3.0158 - accuracy: 0.5884
Test Accuracy: 0.5884000062942505
Epoch 1/10
157/157 [==============================] - 1s 5ms/step - loss: 1.4746 - accuracy: 0.5128
Epoch 2/10
157/157 [==============================] - 1s 5ms/step - loss: 0.7813 - accuracy: 0.7304
Epoch 3/10
157/157 [==============================] - 1s 5ms/step - loss: 0.3152 - accuracy: 0.8932
Epoch 4/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0781 - accuracy: 0.9788
Epoch 5/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0235 - accuracy: 0.9950
Epoch 6/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0049 - accuracy: 0.9996
Epoch 7/10
157/157 [==============================] - 1s 5ms/step - loss: 7.5726e-04 - accuracy: 1.0000
Epoch 8/10
157/157 [==============================] - 1s 5ms/step - loss: 3.9216e-04 - accuracy: 1.0000
Epoch 9/10
157/157 [==============================] - 1s 5ms/step - loss: 2.7774e-04 - accuracy: 1.0000
Epoch 10/10
157/157 [==============================] - 1s 6ms/step - loss: 2.1347e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 4ms/step - loss: 3.0003 - accuracy: 0.5982
Test Accuracy: 0.5982000231742859
Epoch 1/10
157/157 [==============================] - 1s 6ms/step - loss: 1.4784 - accuracy: 0.5024
Epoch 2/10
157/157 [==============================] - 1s 5ms/step - loss: 0.7943 - accuracy: 0.7282
Epoch 3/10
157/157 [==============================] - 1s 5ms/step - loss: 0.3438 - accuracy: 0.8878
Epoch 4/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0944 - accuracy: 0.9736
Epoch 5/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0344 - accuracy: 0.9912
Epoch 6/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0089 - accuracy: 0.9982
Epoch 7/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0016 - accuracy: 1.0000
Epoch 8/10
157/157 [==============================] - 1s 5ms/step - loss: 4.8540e-04 - accuracy: 1.0000
Epoch 9/10
157/157 [==============================] - 1s 5ms/step - loss: 3.2530e-04 - accuracy: 1.0000
Epoch 10/10
157/157 [==============================] - 1s 5ms/step - loss: 2.4489e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 4ms/step - loss: 2.9695 - accuracy: 0.6011
Test Accuracy: 0.6011000275611877
Epoch 1/10
157/157 [==============================] - 1s 7ms/step - loss: 1.4002 - accuracy: 0.5450
Epoch 2/10
157/157 [==============================] - 1s 5ms/step - loss: 0.7044 - accuracy: 0.7610
Epoch 3/10
157/157 [==============================] - 1s 5ms/step - loss: 0.2570 - accuracy: 0.9150
Epoch 4/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0637 - accuracy: 0.9832
Epoch 5/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0164 - accuracy: 0.9970
Epoch 6/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0023 - accuracy: 0.9998
Epoch 7/10
157/157 [==============================] - 1s 5ms/step - loss: 8.4337e-04 - accuracy: 1.0000
Epoch 8/10
157/157 [==============================] - 1s 5ms/step - loss: 4.5904e-04 - accuracy: 1.0000
Epoch 9/10
157/157 [==============================] - 1s 5ms/step - loss: 3.3620e-04 - accuracy: 1.0000
Epoch 10/10
157/157 [==============================] - 1s 5ms/step - loss: 2.6144e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 2.7112 - accuracy: 0.6212
Test Accuracy: 0.6212000250816345
Epoch 1/10
157/157 [==============================] - 1s 5ms/step - loss: 1.3771 - accuracy: 0.5450
Epoch 2/10
157/157 [==============================] - 1s 7ms/step - loss: 0.6628 - accuracy: 0.7780
Epoch 3/10
157/157 [==============================] - 1s 7ms/step - loss: 0.1941 - accuracy: 0.9396
Epoch 4/10
157/157 [==============================] - 1s 6ms/step - loss: 0.0335 - accuracy: 0.9940
Epoch 5/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0058 - accuracy: 0.9996
Epoch 6/10
157/157 [==============================] - 1s 5ms/step - loss: 9.8444e-04 - accuracy: 1.0000
Epoch 7/10
157/157 [==============================] - 1s 5ms/step - loss: 5.8435e-04 - accuracy: 1.0000
Epoch 8/10
157/157 [==============================] - 1s 5ms/step - loss: 4.1424e-04 - accuracy: 1.0000
Epoch 9/10
157/157 [==============================] - 1s 5ms/step - loss: 3.1402e-04 - accuracy: 1.0000
Epoch 10/10
157/157 [==============================] - 1s 5ms/step - loss: 2.4886e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 2.5952 - accuracy: 0.6260
Test Accuracy: 0.6259999871253967
Epoch 1/10
157/157 [==============================] - 1s 5ms/step - loss: 1.3670 - accuracy: 0.5508
Epoch 2/10
157/157 [==============================] - 1s 5ms/step - loss: 0.6581 - accuracy: 0.7822
Epoch 3/10
157/157 [==============================] - 1s 5ms/step - loss: 0.2118 - accuracy: 0.9392
Epoch 4/10
157/157 [==============================] - 1s 6ms/step - loss: 0.0396 - accuracy: 0.9918
Epoch 5/10
157/157 [==============================] - 1s 7ms/step - loss: 0.0091 - accuracy: 0.9988
Epoch 6/10
157/157 [==============================] - 1s 7ms/step - loss: 0.0016 - accuracy: 1.0000
Epoch 7/10
157/157 [==============================] - 1s 5ms/step - loss: 6.1480e-04 - accuracy: 1.0000
Epoch 8/10
157/157 [==============================] - 1s 5ms/step - loss: 4.1676e-04 - accuracy: 1.0000
Epoch 9/10
157/157 [==============================] - 1s 5ms/step - loss: 3.1416e-04 - accuracy: 1.0000
Epoch 10/10
157/157 [==============================] - 1s 5ms/step - loss: 2.4729e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 2.5218 - accuracy: 0.6347
Test Accuracy: 0.6347000002861023
Epoch 1/10
157/157 [==============================] - 1s 6ms/step - loss: 1.3638 - accuracy: 0.5446
Epoch 2/10
157/157 [==============================] - 1s 5ms/step - loss: 0.6697 - accuracy: 0.7744
Epoch 3/10
157/157 [==============================] - 1s 5ms/step - loss: 0.2162 - accuracy: 0.9328
Epoch 4/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0350 - accuracy: 0.9924
Epoch 5/10
157/157 [==============================] - 1s 6ms/step - loss: 0.0061 - accuracy: 0.9996
Epoch 6/10
157/157 [==============================] - 1s 7ms/step - loss: 0.0012 - accuracy: 1.0000
Epoch 7/10
157/157 [==============================] - 1s 7ms/step - loss: 6.4037e-04 - accuracy: 1.0000
Epoch 8/10
157/157 [==============================] - 1s 5ms/step - loss: 4.6064e-04 - accuracy: 1.0000
Epoch 9/10
157/157 [==============================] - 1s 5ms/step - loss: 3.5204e-04 - accuracy: 1.0000
Epoch 10/10
157/157 [==============================] - 1s 5ms/step - loss: 2.8056e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 2.5989 - accuracy: 0.6376
Test Accuracy: 0.6376000046730042
Epoch 1/10
157/157 [==============================] - 1s 6ms/step - loss: 1.2942 - accuracy: 0.5852
Epoch 2/10
157/157 [==============================] - 1s 5ms/step - loss: 0.5602 - accuracy: 0.8076
Epoch 3/10
157/157 [==============================] - 1s 5ms/step - loss: 0.1630 - accuracy: 0.9538
Epoch 4/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0261 - accuracy: 0.9964
Epoch 5/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0037 - accuracy: 0.9998
Epoch 6/10
157/157 [==============================] - 2s 10ms/step - loss: 0.0012 - accuracy: 1.0000
Epoch 7/10
157/157 [==============================] - 1s 7ms/step - loss: 7.5035e-04 - accuracy: 1.0000
Epoch 8/10
157/157 [==============================] - 1s 7ms/step - loss: 5.3438e-04 - accuracy: 1.0000
Epoch 9/10
157/157 [==============================] - 1s 5ms/step - loss: 4.0642e-04 - accuracy: 1.0000
Epoch 10/10
157/157 [==============================] - 1s 5ms/step - loss: 3.2025e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 2.4718 - accuracy: 0.6447
Test Accuracy: 0.6446999907493591

#### Batches 6

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

# Load the CIFAR-10 dataset
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 3  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = np.copy(x_train).astype('float64')
if corruption_name == "speckle_noise":
    noise = np.random.randn(*corrupted_data.shape) * corruption_level
    corrupted_data += noise
    corrupted_data = np.clip(corrupted_data, 0., 255.)
    corrupted_data = corrupted_data.astype('uint8')

# Convert the labels to one-hot encoding
num_classes = 10
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 20 batches
n_batches = 6
# batch_size = len(x_train) // num_batches
batch_size = corrupted_data.shape[0] // n_batches

# x_train_batches = np.array_split(corrupted_data, num_batches)
# y_train_batches = np.array_split(y_train, num_batches)

# Define the model architecture
model = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32 ,32 , 3)),
        Conv2D(32, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        Flatten(),
        Dense(512, activation='relu'),
        Dense(num_classes, activation='softmax')
        ])

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
# Train the model on the train set
for i in range(n_batches):
    start_index = i * batch_size
    end_index = (i + 1) * batch_size
    X_batch = corrupted_data[start_index:end_index]
    y_batch = y_train[start_index:end_index]
    # Train the model on the current batch
    model.fit(X_batch, y_batch, epochs=10, batch_size=32, verbose=1)
    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)

Epoch 1/10
261/261 [==============================] - 6s 6ms/step - loss: 2.3156 - accuracy: 0.0980
Epoch 2/10
261/261 [==============================] - 2s 7ms/step - loss: 2.3027 - accuracy: 0.0992
Epoch 3/10
261/261 [==============================] - 3s 10ms/step - loss: 2.3030 - accuracy: 0.1002
Epoch 4/10
261/261 [==============================] - 2s 9ms/step - loss: 2.3026 - accuracy: 0.0994
Epoch 5/10
261/261 [==============================] - 2s 9ms/step - loss: 2.3026 - accuracy: 0.0994
Epoch 6/10
261/261 [==============================] - 2s 9ms/step - loss: 2.3006 - accuracy: 0.1084
Epoch 7/10
261/261 [==============================] - 2s 9ms/step - loss: 2.2817 - accuracy: 0.1336
Epoch 8/10
261/261 [==============================] - 3s 10ms/step - loss: 2.2206 - accuracy: 0.1716
Epoch 9/10
261/261 [==============================] - 2s 10ms/step - loss: 2.1612 - accuracy: 0.2022
Epoch 10/10
261/261 [==============================] - 2s 9ms/step - loss: 2.0991 - accuracy: 0.2327
313/313 [==============================] - 1s 4ms/step - loss: 2.1947 - accuracy: 0.1831
Test Accuracy: 0.18310000002384186
Epoch 1/10
261/261 [==============================] - 2s 9ms/step - loss: 2.2068 - accuracy: 0.1780
Epoch 2/10
261/261 [==============================] - 2s 7ms/step - loss: 2.1422 - accuracy: 0.2047
Epoch 3/10
261/261 [==============================] - 1s 5ms/step - loss: 2.0762 - accuracy: 0.2450
Epoch 4/10
261/261 [==============================] - 1s 5ms/step - loss: 1.9236 - accuracy: 0.3125
Epoch 5/10
261/261 [==============================] - 1s 5ms/step - loss: 1.5873 - accuracy: 0.4413
Epoch 6/10
261/261 [==============================] - 1s 5ms/step - loss: 0.9830 - accuracy: 0.6726
Epoch 7/10
261/261 [==============================] - 1s 5ms/step - loss: 0.3752 - accuracy: 0.8850
Epoch 8/10
261/261 [==============================] - 1s 5ms/step - loss: 0.0994 - accuracy: 0.9773
Epoch 9/10
261/261 [==============================] - 1s 5ms/step - loss: 0.0296 - accuracy: 0.9951
Epoch 10/10
261/261 [==============================] - 2s 7ms/step - loss: 0.0069 - accuracy: 0.9995
313/313 [==============================] - 1s 4ms/step - loss: 3.4490 - accuracy: 0.2507
Test Accuracy: 0.2506999969482422
Epoch 1/10
261/261 [==============================] - 1s 5ms/step - loss: 2.3681 - accuracy: 0.1438
Epoch 2/10
261/261 [==============================] - 1s 5ms/step - loss: 2.1669 - accuracy: 0.2039
Epoch 3/10
261/261 [==============================] - 1s 5ms/step - loss: 2.0391 - accuracy: 0.2611
Epoch 4/10
261/261 [==============================] - 1s 5ms/step - loss: 1.8182 - accuracy: 0.3647
Epoch 5/10
261/261 [==============================] - 1s 5ms/step - loss: 1.4236 - accuracy: 0.5110
Epoch 6/10
261/261 [==============================] - 1s 5ms/step - loss: 0.8829 - accuracy: 0.7089
Epoch 7/10
261/261 [==============================] - 1s 6ms/step - loss: 0.4132 - accuracy: 0.8754
Epoch 8/10
261/261 [==============================] - 2s 7ms/step - loss: 0.1689 - accuracy: 0.9581
Epoch 9/10
261/261 [==============================] - 1s 5ms/step - loss: 0.0534 - accuracy: 0.9906
Epoch 10/10
261/261 [==============================] - 1s 5ms/step - loss: 0.0200 - accuracy: 0.9970
313/313 [==============================] - 1s 3ms/step - loss: 4.6647 - accuracy: 0.2395
Test Accuracy: 0.2395000010728836
Epoch 1/10
261/261 [==============================] - 1s 5ms/step - loss: 2.4115 - accuracy: 0.1314
Epoch 2/10
261/261 [==============================] - 1s 5ms/step - loss: 2.2165 - accuracy: 0.1817
Epoch 3/10
261/261 [==============================] - 1s 5ms/step - loss: 2.1523 - accuracy: 0.2090
Epoch 4/10
261/261 [==============================] - 1s 5ms/step - loss: 2.0401 - accuracy: 0.2639
Epoch 5/10
261/261 [==============================] - 2s 7ms/step - loss: 1.8563 - accuracy: 0.3384
Epoch 6/10
261/261 [==============================] - 2s 6ms/step - loss: 1.5660 - accuracy: 0.4582
Epoch 7/10
261/261 [==============================] - 1s 5ms/step - loss: 1.1927 - accuracy: 0.5904
Epoch 8/10
261/261 [==============================] - 1s 5ms/step - loss: 0.8125 - accuracy: 0.7353
Epoch 9/10
261/261 [==============================] - 1s 5ms/step - loss: 0.4717 - accuracy: 0.8583
Epoch 10/10
261/261 [==============================] - 1s 5ms/step - loss: 0.2503 - accuracy: 0.9288
313/313 [==============================] - 1s 4ms/step - loss: 5.8364 - accuracy: 0.2072
Test Accuracy: 0.20720000565052032
Epoch 1/10
261/261 [==============================] - 1s 6ms/step - loss: 2.3590 - accuracy: 0.1060
Epoch 2/10
261/261 [==============================] - 1s 5ms/step - loss: 2.3005 - accuracy: 0.1039
Epoch 3/10
261/261 [==============================] - 1s 5ms/step - loss: 2.2994 - accuracy: 0.1020
Epoch 4/10
261/261 [==============================] - 1s 5ms/step - loss: 2.2910 - accuracy: 0.1174
Epoch 5/10
261/261 [==============================] - 1s 5ms/step - loss: 2.2718 - accuracy: 0.1331
Epoch 6/10
261/261 [==============================] - 2s 6ms/step - loss: 2.2484 - accuracy: 0.1435
Epoch 7/10
261/261 [==============================] - 2s 8ms/step - loss: 2.2032 - accuracy: 0.1705
Epoch 8/10
261/261 [==============================] - 2s 8ms/step - loss: 2.1426 - accuracy: 0.1957
Epoch 9/10
261/261 [==============================] - 1s 5ms/step - loss: 2.0799 - accuracy: 0.2341
Epoch 10/10
261/261 [==============================] - 1s 5ms/step - loss: 1.9894 - accuracy: 0.2670
313/313 [==============================] - 1s 4ms/step - loss: 4.5682 - accuracy: 0.2092
Test Accuracy: 0.20919999480247498
Epoch 1/10
261/261 [==============================] - 2s 7ms/step - loss: 2.2204 - accuracy: 0.1661
Epoch 2/10
261/261 [==============================] - 2s 6ms/step - loss: 2.1678 - accuracy: 0.1876
Epoch 3/10
261/261 [==============================] - 1s 5ms/step - loss: 2.1106 - accuracy: 0.2216
Epoch 4/10
261/261 [==============================] - 1s 5ms/step - loss: 2.0301 - accuracy: 0.2502
Epoch 5/10
261/261 [==============================] - 1s 5ms/step - loss: 1.9055 - accuracy: 0.3036
Epoch 6/10
261/261 [==============================] - 1s 5ms/step - loss: 1.7370 - accuracy: 0.3673
Epoch 7/10
261/261 [==============================] - 1s 5ms/step - loss: 1.5328 - accuracy: 0.4416
Epoch 8/10
261/261 [==============================] - 2s 6ms/step - loss: 1.3032 - accuracy: 0.5308
Epoch 9/10
261/261 [==============================] - 2s 7ms/step - loss: 1.0685 - accuracy: 0.6209
Epoch 10/10
261/261 [==============================] - 2s 7ms/step - loss: 0.8471 - accuracy: 0.6977
313/313 [==============================] - 1s 3ms/step - loss: 10.0355 - accuracy: 0.2114
Test Accuracy: 0.21140000224113464

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam

# Load the CIFAR-100 dataset
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 0.1  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = x_train + tf.random.normal(shape=x_train.shape, mean=0.0, stddev=corruption_level, dtype=tf.float32)
corrupted_data = tf.clip_by_value(corrupted_data, 0.0, 1.0)

# Convert the labels to one-hot encoding
num_classes = 10
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 2 batches
n_batches = 6
batch_size = x_train.shape[0] // n_batches

# Define the model architecture
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)))
model.add(Conv2D(32, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch separately
for i in range(n_batches):
    start_index = i * batch_size
    end_index = (i + 1) * batch_size
    x_batch = corrupted_data[start_index:end_index]
    y_batch = y_train[start_index:end_index]

    # Train the model on the current batch
    model.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)

Epoch 1/10
261/261 [==============================] - 7s 7ms/step - loss: 1.8184 - accuracy: 0.3329
Epoch 2/10
261/261 [==============================] - 1s 5ms/step - loss: 1.4928 - accuracy: 0.4561
Epoch 3/10
261/261 [==============================] - 1s 5ms/step - loss: 1.2833 - accuracy: 0.5386
Epoch 4/10
261/261 [==============================] - 1s 5ms/step - loss: 1.0582 - accuracy: 0.6191
Epoch 5/10
261/261 [==============================] - 1s 5ms/step - loss: 0.8496 - accuracy: 0.6946
Epoch 6/10
261/261 [==============================] - 1s 5ms/step - loss: 0.5770 - accuracy: 0.7962
Epoch 7/10
261/261 [==============================] - 1s 5ms/step - loss: 0.3378 - accuracy: 0.8813
Epoch 8/10
261/261 [==============================] - 1s 5ms/step - loss: 0.1746 - accuracy: 0.9406
Epoch 9/10
261/261 [==============================] - 2s 7ms/step - loss: 0.1152 - accuracy: 0.9615
Epoch 10/10
261/261 [==============================] - 1s 6ms/step - loss: 0.0824 - accuracy: 0.9744
313/313 [==============================] - 1s 4ms/step - loss: 2.8589 - accuracy: 0.5316
Test Accuracy: 0.5315999984741211
Epoch 1/10
261/261 [==============================] - 1s 5ms/step - loss: 1.3539 - accuracy: 0.5440
Epoch 2/10
261/261 [==============================] - 1s 5ms/step - loss: 0.8417 - accuracy: 0.7043
Epoch 3/10
261/261 [==============================] - 1s 5ms/step - loss: 0.4426 - accuracy: 0.8513
Epoch 4/10
261/261 [==============================] - 2s 7ms/step - loss: 0.1734 - accuracy: 0.9460
Epoch 5/10
261/261 [==============================] - 2s 7ms/step - loss: 0.0755 - accuracy: 0.9761
Epoch 6/10
261/261 [==============================] - 1s 5ms/step - loss: 0.0471 - accuracy: 0.9858
Epoch 7/10
261/261 [==============================] - 1s 5ms/step - loss: 0.0565 - accuracy: 0.9816
Epoch 8/10
261/261 [==============================] - 2s 6ms/step - loss: 0.0624 - accuracy: 0.9789
Epoch 9/10
261/261 [==============================] - 2s 8ms/step - loss: 0.0681 - accuracy: 0.9778
Epoch 10/10
261/261 [==============================] - 2s 8ms/step - loss: 0.0439 - accuracy: 0.9855
313/313 [==============================] - 2s 7ms/step - loss: 2.8636 - accuracy: 0.5774
Test Accuracy: 0.5774000287055969
Epoch 1/10
261/261 [==============================] - 2s 9ms/step - loss: 1.2723 - accuracy: 0.5621
Epoch 2/10
261/261 [==============================] - 2s 8ms/step - loss: 0.7352 - accuracy: 0.7467
Epoch 3/10
261/261 [==============================] - 2s 8ms/step - loss: 0.3125 - accuracy: 0.8939
Epoch 4/10
261/261 [==============================] - 2s 9ms/step - loss: 0.1010 - accuracy: 0.9693
Epoch 5/10
261/261 [==============================] - 2s 8ms/step - loss: 0.0277 - accuracy: 0.9926
Epoch 6/10
261/261 [==============================] - 3s 12ms/step - loss: 0.0588 - accuracy: 0.9806
Epoch 7/10
261/261 [==============================] - 2s 9ms/step - loss: 0.0677 - accuracy: 0.9779
Epoch 8/10
261/261 [==============================] - 2s 8ms/step - loss: 0.0386 - accuracy: 0.9882
Epoch 9/10
261/261 [==============================] - 2s 7ms/step - loss: 0.0566 - accuracy: 0.9826
Epoch 10/10
261/261 [==============================] - 2s 6ms/step - loss: 0.0402 - accuracy: 0.9869
313/313 [==============================] - 1s 4ms/step - loss: 2.8237 - accuracy: 0.6021
Test Accuracy: 0.6021000146865845
Epoch 1/10
261/261 [==============================] - 3s 10ms/step - loss: 1.3289 - accuracy: 0.5565
Epoch 2/10
261/261 [==============================] - 2s 7ms/step - loss: 0.6854 - accuracy: 0.7635
Epoch 3/10
261/261 [==============================] - 2s 6ms/step - loss: 0.2737 - accuracy: 0.9120
Epoch 4/10
261/261 [==============================] - 2s 6ms/step - loss: 0.0545 - accuracy: 0.9866
Epoch 5/10
261/261 [==============================] - 2s 6ms/step - loss: 0.0145 - accuracy: 0.9968
Epoch 6/10
261/261 [==============================] - 1s 5ms/step - loss: 0.0141 - accuracy: 0.9970
Epoch 7/10
261/261 [==============================] - 1s 5ms/step - loss: 0.0190 - accuracy: 0.9940
Epoch 8/10
261/261 [==============================] - 2s 6ms/step - loss: 0.1100 - accuracy: 0.9660
Epoch 9/10
261/261 [==============================] - 2s 6ms/step - loss: 0.0606 - accuracy: 0.9814
Epoch 10/10
261/261 [==============================] - 1s 5ms/step - loss: 0.0477 - accuracy: 0.9852
313/313 [==============================] - 1s 3ms/step - loss: 2.7220 - accuracy: 0.6029
Test Accuracy: 0.6029000282287598
Epoch 1/10
261/261 [==============================] - 1s 5ms/step - loss: 1.3229 - accuracy: 0.5650
Epoch 2/10
261/261 [==============================] - 1s 5ms/step - loss: 0.6625 - accuracy: 0.7749
Epoch 3/10
261/261 [==============================] - 2s 7ms/step - loss: 0.2253 - accuracy: 0.9282
Epoch 4/10
261/261 [==============================] - 1s 6ms/step - loss: 0.0432 - accuracy: 0.9909
Epoch 5/10
261/261 [==============================] - 1s 5ms/step - loss: 0.0105 - accuracy: 0.9986
Epoch 6/10
261/261 [==============================] - 1s 5ms/step - loss: 0.0016 - accuracy: 0.9999
Epoch 7/10
261/261 [==============================] - 1s 5ms/step - loss: 7.8432e-04 - accuracy: 0.9999
Epoch 8/10
261/261 [==============================] - 1s 5ms/step - loss: 3.3533e-04 - accuracy: 1.0000
Epoch 9/10
261/261 [==============================] - 1s 5ms/step - loss: 2.3894e-04 - accuracy: 1.0000
Epoch 10/10
261/261 [==============================] - 1s 5ms/step - loss: 1.8106e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 2.8871 - accuracy: 0.6420
Test Accuracy: 0.6420000195503235
Epoch 1/10
261/261 [==============================] - 2s 7ms/step - loss: 1.3080 - accuracy: 0.5646
Epoch 2/10
261/261 [==============================] - 1s 5ms/step - loss: 0.6287 - accuracy: 0.7850
Epoch 3/10
261/261 [==============================] - 1s 5ms/step - loss: 0.2088 - accuracy: 0.9365
Epoch 4/10
261/261 [==============================] - 1s 5ms/step - loss: 0.0418 - accuracy: 0.9900
Epoch 5/10
261/261 [==============================] - 1s 5ms/step - loss: 0.0086 - accuracy: 0.9989
Epoch 6/10
261/261 [==============================] - 1s 5ms/step - loss: 0.0011 - accuracy: 1.0000
Epoch 7/10
261/261 [==============================] - 1s 5ms/step - loss: 4.5984e-04 - accuracy: 1.0000
Epoch 8/10
261/261 [==============================] - 1s 5ms/step - loss: 2.7280e-04 - accuracy: 1.0000
Epoch 9/10
261/261 [==============================] - 2s 6ms/step - loss: 1.8160e-04 - accuracy: 1.0000
Epoch 10/10
261/261 [==============================] - 2s 7ms/step - loss: 1.2965e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 2.9304 - accuracy: 0.6494
Test Accuracy: 0.649399995803833

#### Batches 5

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam

# Load the CIFAR-100 dataset
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 0.1  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = x_train + tf.random.normal(shape=x_train.shape, mean=0.0, stddev=corruption_level, dtype=tf.float32)
corrupted_data = tf.clip_by_value(corrupted_data, 0.0, 1.0)

# Convert the labels to one-hot encoding
num_classes = 10
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 2 batches
n_batches = 5
batch_size = x_train.shape[0] // n_batches

# Define the model architecture
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)))
model.add(Conv2D(32, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch separately
for i in range(n_batches):
    start_index = i * batch_size
    end_index = (i + 1) * batch_size
    x_batch = corrupted_data[start_index:end_index]
    y_batch = y_train[start_index:end_index]

    # Train the model on the current batch
    model.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)

Epoch 1/10
313/313 [==============================] - 12s 11ms/step - loss: 1.7666 - accuracy: 0.3446
Epoch 2/10
313/313 [==============================] - 3s 8ms/step - loss: 1.4114 - accuracy: 0.4917
Epoch 3/10
313/313 [==============================] - 3s 11ms/step - loss: 1.2006 - accuracy: 0.5702
Epoch 4/10
313/313 [==============================] - 3s 8ms/step - loss: 1.0027 - accuracy: 0.6384
Epoch 5/10
313/313 [==============================] - 3s 9ms/step - loss: 0.7817 - accuracy: 0.7184
Epoch 6/10
313/313 [==============================] - 3s 9ms/step - loss: 0.5422 - accuracy: 0.8071
Epoch 7/10
313/313 [==============================] - 4s 11ms/step - loss: 0.3233 - accuracy: 0.8913
Epoch 8/10
313/313 [==============================] - 3s 11ms/step - loss: 0.1709 - accuracy: 0.9416
Epoch 9/10
313/313 [==============================] - 2s 7ms/step - loss: 0.1110 - accuracy: 0.9653
Epoch 10/10
313/313 [==============================] - 2s 7ms/step - loss: 0.1104 - accuracy: 0.9619
313/313 [==============================] - 2s 4ms/step - loss: 2.2205 - accuracy: 0.5804
Test Accuracy: 0.5803999900817871
Epoch 1/10
313/313 [==============================] - 2s 7ms/step - loss: 1.2146 - accuracy: 0.5853
Epoch 2/10
313/313 [==============================] - 2s 7ms/step - loss: 0.8017 - accuracy: 0.7210
Epoch 3/10
313/313 [==============================] - 2s 5ms/step - loss: 0.4688 - accuracy: 0.8389
Epoch 4/10
313/313 [==============================] - 2s 5ms/step - loss: 0.1971 - accuracy: 0.9359
Epoch 5/10
313/313 [==============================] - 2s 5ms/step - loss: 0.0933 - accuracy: 0.9717
Epoch 6/10
313/313 [==============================] - 2s 5ms/step - loss: 0.0679 - accuracy: 0.9793
Epoch 7/10
313/313 [==============================] - 2s 5ms/step - loss: 0.0662 - accuracy: 0.9781
Epoch 8/10
313/313 [==============================] - 2s 5ms/step - loss: 0.0621 - accuracy: 0.9799
Epoch 9/10
313/313 [==============================] - 2s 6ms/step - loss: 0.0521 - accuracy: 0.9851
Epoch 10/10
313/313 [==============================] - 2s 6ms/step - loss: 0.0373 - accuracy: 0.9879
313/313 [==============================] - 1s 3ms/step - loss: 2.6236 - accuracy: 0.6203
Test Accuracy: 0.6202999949455261
Epoch 1/10
313/313 [==============================] - 2s 5ms/step - loss: 1.2050 - accuracy: 0.5930
Epoch 2/10
313/313 [==============================] - 2s 5ms/step - loss: 0.6671 - accuracy: 0.7687
Epoch 3/10
313/313 [==============================] - 2s 5ms/step - loss: 0.2849 - accuracy: 0.9078
Epoch 4/10
313/313 [==============================] - 2s 7ms/step - loss: 0.0864 - accuracy: 0.9736
Epoch 5/10
313/313 [==============================] - 2s 5ms/step - loss: 0.0483 - accuracy: 0.9858
Epoch 6/10
313/313 [==============================] - 2s 5ms/step - loss: 0.0304 - accuracy: 0.9912
Epoch 7/10
313/313 [==============================] - 2s 5ms/step - loss: 0.0492 - accuracy: 0.9842
Epoch 8/10
313/313 [==============================] - 2s 5ms/step - loss: 0.0644 - accuracy: 0.9792
Epoch 9/10
313/313 [==============================] - 2s 5ms/step - loss: 0.0513 - accuracy: 0.9841
Epoch 10/10
313/313 [==============================] - 2s 5ms/step - loss: 0.0382 - accuracy: 0.9882
313/313 [==============================] - 1s 3ms/step - loss: 2.4697 - accuracy: 0.6188
Test Accuracy: 0.6187999844551086
Epoch 1/10
313/313 [==============================] - 2s 5ms/step - loss: 1.2135 - accuracy: 0.5952
Epoch 2/10
313/313 [==============================] - 2s 5ms/step - loss: 0.6450 - accuracy: 0.7841
Epoch 3/10
313/313 [==============================] - 2s 5ms/step - loss: 0.2411 - accuracy: 0.9225
Epoch 4/10
313/313 [==============================] - 2s 5ms/step - loss: 0.0513 - accuracy: 0.9874
Epoch 5/10
313/313 [==============================] - 2s 7ms/step - loss: 0.0106 - accuracy: 0.9981
Epoch 6/10
313/313 [==============================] - 2s 5ms/step - loss: 0.0120 - accuracy: 0.9967
Epoch 7/10
313/313 [==============================] - 2s 5ms/step - loss: 0.0976 - accuracy: 0.9703
Epoch 8/10
313/313 [==============================] - 2s 5ms/step - loss: 0.0434 - accuracy: 0.9868
Epoch 9/10
313/313 [==============================] - 2s 5ms/step - loss: 0.0572 - accuracy: 0.9829
Epoch 10/10
313/313 [==============================] - 2s 7ms/step - loss: 0.0387 - accuracy: 0.9880
313/313 [==============================] - 1s 3ms/step - loss: 2.8450 - accuracy: 0.6076
Test Accuracy: 0.6075999736785889
Epoch 1/10
313/313 [==============================] - 2s 7ms/step - loss: 1.2139 - accuracy: 0.5979
Epoch 2/10
313/313 [==============================] - 2s 6ms/step - loss: 0.5894 - accuracy: 0.7954
Epoch 3/10
313/313 [==============================] - 3s 8ms/step - loss: 0.1877 - accuracy: 0.9425
Epoch 4/10
313/313 [==============================] - 3s 9ms/step - loss: 0.0330 - accuracy: 0.9931
Epoch 5/10
313/313 [==============================] - 2s 8ms/step - loss: 0.0049 - accuracy: 0.9997
Epoch 6/10
313/313 [==============================] - 3s 11ms/step - loss: 0.0034 - accuracy: 0.9994
Epoch 7/10
313/313 [==============================] - 3s 9ms/step - loss: 5.8685e-04 - accuracy: 1.0000
Epoch 8/10
313/313 [==============================] - 3s 8ms/step - loss: 3.1957e-04 - accuracy: 1.0000
Epoch 9/10
313/313 [==============================] - 2s 8ms/step - loss: 2.2072e-04 - accuracy: 1.0000
Epoch 10/10
313/313 [==============================] - 2s 6ms/step - loss: 1.6311e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 4ms/step - loss: 2.6221 - accuracy: 0.6748
Test Accuracy: 0.6747999787330627

#### Batches 4

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam

# Load the CIFAR-100 dataset
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 0.1  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = x_train + tf.random.normal(shape=x_train.shape, mean=0.0, stddev=corruption_level, dtype=tf.float32)
corrupted_data = tf.clip_by_value(corrupted_data, 0.0, 1.0)

# Convert the labels to one-hot encoding
num_classes = 10
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 2 batches
n_batches = 4
batch_size = x_train.shape[0] // n_batches

# Define the model architecture
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)))
model.add(Conv2D(32, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch separately
for i in range(n_batches):
    start_index = i * batch_size
    end_index = (i + 1) * batch_size
    x_batch = corrupted_data[start_index:end_index]
    y_batch = y_train[start_index:end_index]

    # Train the model on the current batch
    model.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)

Epoch 1/10
391/391 [==============================] - 12s 8ms/step - loss: 1.7780 - accuracy: 0.3434
Epoch 2/10
391/391 [==============================] - 3s 7ms/step - loss: 1.3822 - accuracy: 0.5006
Epoch 3/10
391/391 [==============================] - 3s 7ms/step - loss: 1.1562 - accuracy: 0.5836
Epoch 4/10
391/391 [==============================] - 3s 8ms/step - loss: 0.9542 - accuracy: 0.6573
Epoch 5/10
391/391 [==============================] - 2s 6ms/step - loss: 0.7532 - accuracy: 0.7330
Epoch 6/10
391/391 [==============================] - 2s 5ms/step - loss: 0.5152 - accuracy: 0.8200
Epoch 7/10
391/391 [==============================] - 2s 5ms/step - loss: 0.3023 - accuracy: 0.8966
Epoch 8/10
391/391 [==============================] - 2s 5ms/step - loss: 0.1522 - accuracy: 0.9485
Epoch 9/10
391/391 [==============================] - 2s 5ms/step - loss: 0.1244 - accuracy: 0.9589
Epoch 10/10
391/391 [==============================] - 3s 6ms/step - loss: 0.1123 - accuracy: 0.9617
313/313 [==============================] - 1s 4ms/step - loss: 2.3492 - accuracy: 0.5768
Test Accuracy: 0.5767999887466431
Epoch 1/10
391/391 [==============================] - 2s 5ms/step - loss: 1.2172 - accuracy: 0.5841
Epoch 2/10
391/391 [==============================] - 2s 5ms/step - loss: 0.8318 - accuracy: 0.7058
Epoch 3/10
391/391 [==============================] - 2s 5ms/step - loss: 0.5444 - accuracy: 0.8123
Epoch 4/10
391/391 [==============================] - 2s 5ms/step - loss: 0.2569 - accuracy: 0.9128
Epoch 5/10
391/391 [==============================] - 2s 6ms/step - loss: 0.1274 - accuracy: 0.9582
Epoch 6/10
391/391 [==============================] - 2s 6ms/step - loss: 0.1030 - accuracy: 0.9641
Epoch 7/10
391/391 [==============================] - 2s 5ms/step - loss: 0.0688 - accuracy: 0.9770
Epoch 8/10
391/391 [==============================] - 2s 5ms/step - loss: 0.0617 - accuracy: 0.9775
Epoch 9/10
391/391 [==============================] - 2s 5ms/step - loss: 0.0713 - accuracy: 0.9778
Epoch 10/10
391/391 [==============================] - 2s 5ms/step - loss: 0.0366 - accuracy: 0.9874
313/313 [==============================] - 1s 4ms/step - loss: 2.7623 - accuracy: 0.6206
Test Accuracy: 0.6205999851226807
Epoch 1/10
391/391 [==============================] - 2s 6ms/step - loss: 1.2173 - accuracy: 0.5975
Epoch 2/10
391/391 [==============================] - 2s 5ms/step - loss: 0.7187 - accuracy: 0.7532
Epoch 3/10
391/391 [==============================] - 2s 5ms/step - loss: 0.3730 - accuracy: 0.8753
Epoch 4/10
391/391 [==============================] - 2s 5ms/step - loss: 0.1319 - accuracy: 0.9602
Epoch 5/10
391/391 [==============================] - 2s 5ms/step - loss: 0.0794 - accuracy: 0.9750
Epoch 6/10
391/391 [==============================] - 3s 6ms/step - loss: 0.0465 - accuracy: 0.9870
Epoch 7/10
391/391 [==============================] - 2s 6ms/step - loss: 0.0427 - accuracy: 0.9869
Epoch 8/10
391/391 [==============================] - 2s 5ms/step - loss: 0.0645 - accuracy: 0.9794
Epoch 9/10
391/391 [==============================] - 2s 5ms/step - loss: 0.0616 - accuracy: 0.9815
Epoch 10/10
391/391 [==============================] - 2s 5ms/step - loss: 0.0510 - accuracy: 0.9834
313/313 [==============================] - 1s 3ms/step - loss: 2.7068 - accuracy: 0.6313
Test Accuracy: 0.6312999725341797
Epoch 1/10
391/391 [==============================] - 2s 5ms/step - loss: 1.1941 - accuracy: 0.6027
Epoch 2/10
391/391 [==============================] - 2s 5ms/step - loss: 0.6648 - accuracy: 0.7722
Epoch 3/10
391/391 [==============================] - 2s 6ms/step - loss: 0.2960 - accuracy: 0.9032
Epoch 4/10
391/391 [==============================] - 2s 6ms/step - loss: 0.0796 - accuracy: 0.9778
Epoch 5/10
391/391 [==============================] - 2s 6ms/step - loss: 0.0210 - accuracy: 0.9954
Epoch 6/10
391/391 [==============================] - 2s 5ms/step - loss: 0.0718 - accuracy: 0.9788
Epoch 7/10
391/391 [==============================] - 2s 5ms/step - loss: 0.0657 - accuracy: 0.9802
Epoch 8/10
391/391 [==============================] - 2s 5ms/step - loss: 0.0322 - accuracy: 0.9910
Epoch 9/10
391/391 [==============================] - 3s 7ms/step - loss: 0.0243 - accuracy: 0.9929
Epoch 10/10
391/391 [==============================] - 2s 5ms/step - loss: 0.0483 - accuracy: 0.9851
313/313 [==============================] - 1s 4ms/step - loss: 2.8208 - accuracy: 0.6263
Test Accuracy: 0.6262999773025513

#### Batches 2

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam

# Load the CIFAR-100 dataset
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 0.1  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = x_train + tf.random.normal(shape=x_train.shape, mean=0.0, stddev=corruption_level, dtype=tf.float32)
corrupted_data = tf.clip_by_value(corrupted_data, 0.0, 1.0)

# Convert the labels to one-hot encoding
num_classes = 10
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 2 batches
n_batches = 2
batch_size = x_train.shape[0] // n_batches

# Define the model architecture
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)))
model.add(Conv2D(32, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch separately
for i in range(n_batches):
    start_index = i * batch_size
    end_index = (i + 1) * batch_size
    x_batch = corrupted_data[start_index:end_index]
    y_batch = y_train[start_index:end_index]

    # Train the model on the current batch
    model.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)

Downloading data from https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
170498071/170498071 [==============================] - 6s 0us/step
Epoch 1/10
782/782 [==============================] - 21s 7ms/step - loss: 1.5942 - accuracy: 0.4190
Epoch 2/10
782/782 [==============================] - 6s 8ms/step - loss: 1.1514 - accuracy: 0.5888
Epoch 3/10
782/782 [==============================] - 4s 5ms/step - loss: 0.9151 - accuracy: 0.6760
Epoch 4/10
782/782 [==============================] - 4s 5ms/step - loss: 0.6956 - accuracy: 0.7536
Epoch 5/10
782/782 [==============================] - 5s 6ms/step - loss: 0.4604 - accuracy: 0.8383
Epoch 6/10
782/782 [==============================] - 4s 5ms/step - loss: 0.2638 - accuracy: 0.9091
Epoch 7/10
782/782 [==============================] - 4s 5ms/step - loss: 0.1691 - accuracy: 0.9409
Epoch 8/10
782/782 [==============================] - 5s 6ms/step - loss: 0.1261 - accuracy: 0.9577
Epoch 9/10
782/782 [==============================] - 4s 5ms/step - loss: 0.0920 - accuracy: 0.9681
Epoch 10/10
782/782 [==============================] - 4s 5ms/step - loss: 0.0930 - accuracy: 0.9690
313/313 [==============================] - 2s 4ms/step - loss: 2.2884 - accuracy: 0.6326
Test Accuracy: 0.6326000094413757
Epoch 1/10
782/782 [==============================] - 4s 5ms/step - loss: 1.0470 - accuracy: 0.6414
Epoch 2/10
782/782 [==============================] - 4s 5ms/step - loss: 0.6812 - accuracy: 0.7654
Epoch 3/10
782/782 [==============================] - 5s 6ms/step - loss: 0.3883 - accuracy: 0.8655
Epoch 4/10
782/782 [==============================] - 4s 5ms/step - loss: 0.1758 - accuracy: 0.9415
Epoch 5/10
782/782 [==============================] - 4s 5ms/step - loss: 0.1085 - accuracy: 0.9636
Epoch 6/10
782/782 [==============================] - 4s 6ms/step - loss: 0.0918 - accuracy: 0.9700
Epoch 7/10
782/782 [==============================] - 4s 5ms/step - loss: 0.0641 - accuracy: 0.9790
Epoch 8/10
782/782 [==============================] - 4s 6ms/step - loss: 0.0713 - accuracy: 0.9774
Epoch 9/10
782/782 [==============================] - 4s 6ms/step - loss: 0.0644 - accuracy: 0.9789
Epoch 10/10
782/782 [==============================] - 4s 5ms/step - loss: 0.0586 - accuracy: 0.9818
313/313 [==============================] - 1s 3ms/step - loss: 2.5061 - accuracy: 0.6556
Test Accuracy: 0.6556000113487244

#### Batches 1

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam

# Load the CIFAR-100 dataset
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 0.1  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = x_train + tf.random.normal(shape=x_train.shape, mean=0.0, stddev=corruption_level, dtype=tf.float32)
corrupted_data = tf.clip_by_value(corrupted_data, 0.0, 1.0)

# Convert the labels to one-hot encoding
num_classes = 10
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 2 batches
n_batches = 1
batch_size = x_train.shape[0] // n_batches

# Define the model architecture
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)))
model.add(Conv2D(32, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch separately
for i in range(n_batches):
    start_index = i * batch_size
    end_index = (i + 1) * batch_size
    x_batch = corrupted_data[start_index:end_index]
    y_batch = y_train[start_index:end_index]

    # Train the model on the current batch
    model.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)

Epoch 1/10
1563/1563 [==============================] - 22s 10ms/step - loss: 1.4073 - accuracy: 0.4888
Epoch 2/10
1563/1563 [==============================] - 12s 8ms/step - loss: 0.9788 - accuracy: 0.6532
Epoch 3/10
1563/1563 [==============================] - 10s 6ms/step - loss: 0.7656 - accuracy: 0.7316
Epoch 4/10
1563/1563 [==============================] - 9s 6ms/step - loss: 0.5736 - accuracy: 0.7998
Epoch 5/10
1563/1563 [==============================] - 8s 5ms/step - loss: 0.3928 - accuracy: 0.8613
Epoch 6/10
1563/1563 [==============================] - 8s 5ms/step - loss: 0.2538 - accuracy: 0.9101
Epoch 7/10
1563/1563 [==============================] - 8s 5ms/step - loss: 0.1701 - accuracy: 0.9422
Epoch 8/10
1563/1563 [==============================] - 8s 5ms/step - loss: 0.1504 - accuracy: 0.9486
Epoch 9/10
1563/1563 [==============================] - 8s 5ms/step - loss: 0.1203 - accuracy: 0.9581
Epoch 10/10
1563/1563 [==============================] - 8s 5ms/step - loss: 0.1066 - accuracy: 0.9643
313/313 [==============================] - 1s 3ms/step - loss: 2.0650 - accuracy: 0.6855
Test Accuracy: 0.6855000257492065

### CIFAR100-C

#### Batches 1

In [ ]:
import numpy as np
import keras
from tensorflow.keras.datasets import cifar100
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
# Load the CIFAR-100 dataset
(x_train, y_train), (x_test, y_test) = cifar100.load_data()

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 3  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = np.copy(x_train).astype('float64')
if corruption_name == "speckle_noise":
    noise = np.random.randn(*corrupted_data.shape) * corruption_level
    corrupted_data += noise
    corrupted_data = np.clip(corrupted_data, 0., 255.)
    corrupted_data = corrupted_data.astype('uint8')
num_classes=100
# Convert labels to one-hot vectors
y_train_onehot = keras.utils.to_categorical(y_train, num_classes=100)
y_test_onehot = keras.utils.to_categorical(y_test, num_classes=100)
# Define the model architecture
model = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32 ,32 , 3)),
        Conv2D(32, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        Flatten(),
        Dense(512, activation='relu'),
        Dense(num_classes, activation='softmax')
        ])

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on the train set
model.fit(corrupted_data, y_train_onehot, batch_size=128, epochs=10, verbose=1)

# Evaluate the model on the test set
_, test_accuracy = model.evaluate(x_test, y_test_onehot, verbose=0)
print("Test Accuracy:", test_accuracy)

Epoch 1/10
391/391 [==============================] - 6s 10ms/step - loss: 4.6081 - accuracy: 0.0821
Epoch 2/10
391/391 [==============================] - 4s 11ms/step - loss: 3.3121 - accuracy: 0.2119
Epoch 3/10
391/391 [==============================] - 4s 11ms/step - loss: 2.8485 - accuracy: 0.2990
Epoch 4/10
391/391 [==============================] - 4s 11ms/step - loss: 2.4292 - accuracy: 0.3856
Epoch 5/10
391/391 [==============================] - 4s 11ms/step - loss: 1.9869 - accuracy: 0.4855
Epoch 6/10
391/391 [==============================] - 4s 10ms/step - loss: 1.5096 - accuracy: 0.5916
Epoch 7/10
391/391 [==============================] - 4s 10ms/step - loss: 1.0580 - accuracy: 0.7043
Epoch 8/10
391/391 [==============================] - 4s 11ms/step - loss: 0.7121 - accuracy: 0.7901
Epoch 9/10
391/391 [==============================] - 4s 10ms/step - loss: 0.5346 - accuracy: 0.8390
Epoch 10/10
391/391 [==============================] - 4s 10ms/step - loss: 0.4429 - accuracy: 0.8666
Test Accuracy: 0.28870001435279846

#### Batches 20

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar100
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam

# Load the CIFAR-100 dataset
(x_train, y_train), (x_test, y_test) = cifar100.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 0.1  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = x_train + tf.random.normal(shape=x_train.shape, mean=0.0, stddev=corruption_level, dtype=tf.float32)
corrupted_data = tf.clip_by_value(corrupted_data, 0.0, 1.0)

# Convert the labels to one-hot encoding
num_classes = 100
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 10 batches
n_batches = 20
batch_size = x_train.shape[0] // n_batches

# Define the model architecture
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)))
model.add(Conv2D(32, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch separately
for i in range(n_batches):
    start_index = i * batch_size
    end_index = (i + 1) * batch_size
    x_batch = corrupted_data[start_index:end_index]
    y_batch = y_train[start_index:end_index]

    # Train the model on the current batch
    model.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)

Epoch 1/10
79/79 [==============================] - 9s 15ms/step - loss: 4.5793 - accuracy: 0.0156
Epoch 2/10
79/79 [==============================] - 1s 10ms/step - loss: 4.3618 - accuracy: 0.0400
Epoch 3/10
79/79 [==============================] - 1s 15ms/step - loss: 4.0510 - accuracy: 0.0736
Epoch 4/10
79/79 [==============================] - 1s 12ms/step - loss: 3.7813 - accuracy: 0.1100
Epoch 5/10
79/79 [==============================] - 1s 13ms/step - loss: 3.3974 - accuracy: 0.1728
Epoch 6/10
79/79 [==============================] - 1s 10ms/step - loss: 2.8680 - accuracy: 0.2716
Epoch 7/10
79/79 [==============================] - 1s 10ms/step - loss: 2.1284 - accuracy: 0.4392
Epoch 8/10
79/79 [==============================] - 1s 8ms/step - loss: 1.2502 - accuracy: 0.6548
Epoch 9/10
79/79 [==============================] - 1s 9ms/step - loss: 0.6033 - accuracy: 0.8452
Epoch 10/10
79/79 [==============================] - 1s 9ms/step - loss: 0.3289 - accuracy: 0.9076
313/313 [==============================] - 3s 7ms/step - loss: 8.8115 - accuracy: 0.1150
Test Accuracy: 0.11500000208616257
Epoch 1/10
79/79 [==============================] - 1s 8ms/step - loss: 4.2541 - accuracy: 0.0884
Epoch 2/10
79/79 [==============================] - 1s 8ms/step - loss: 3.1959 - accuracy: 0.2276
Epoch 3/10
79/79 [==============================] - 1s 7ms/step - loss: 2.0062 - accuracy: 0.4760
Epoch 4/10
79/79 [==============================] - 1s 7ms/step - loss: 0.8007 - accuracy: 0.7920
Epoch 5/10
79/79 [==============================] - 1s 8ms/step - loss: 0.3021 - accuracy: 0.9176
Epoch 6/10
79/79 [==============================] - 0s 6ms/step - loss: 0.1557 - accuracy: 0.9552
Epoch 7/10
79/79 [==============================] - 0s 6ms/step - loss: 0.1043 - accuracy: 0.9736
Epoch 8/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0833 - accuracy: 0.9764
Epoch 9/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0249 - accuracy: 0.9936
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0457 - accuracy: 0.9904
313/313 [==============================] - 1s 3ms/step - loss: 9.1688 - accuracy: 0.1411
Test Accuracy: 0.14110000431537628
Epoch 1/10
79/79 [==============================] - 0s 6ms/step - loss: 4.2957 - accuracy: 0.0880
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 3.2440 - accuracy: 0.2388
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 2.1013 - accuracy: 0.4684
Epoch 4/10
79/79 [==============================] - 1s 7ms/step - loss: 0.8630 - accuracy: 0.7680
Epoch 5/10
79/79 [==============================] - 1s 7ms/step - loss: 0.3009 - accuracy: 0.9168
Epoch 6/10
79/79 [==============================] - 1s 7ms/step - loss: 0.0940 - accuracy: 0.9788
Epoch 7/10
79/79 [==============================] - 1s 7ms/step - loss: 0.0577 - accuracy: 0.9840
Epoch 8/10
79/79 [==============================] - 1s 8ms/step - loss: 0.0172 - accuracy: 0.9956
Epoch 9/10
79/79 [==============================] - 1s 9ms/step - loss: 0.0126 - accuracy: 0.9968
Epoch 10/10
79/79 [==============================] - 1s 8ms/step - loss: 0.0208 - accuracy: 0.9960
313/313 [==============================] - 1s 4ms/step - loss: 8.4823 - accuracy: 0.1637
Test Accuracy: 0.16369999945163727
Epoch 1/10
79/79 [==============================] - 1s 6ms/step - loss: 4.2402 - accuracy: 0.0928
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 2.9360 - accuracy: 0.2980
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 1.5332 - accuracy: 0.6012
Epoch 4/10
79/79 [==============================] - 0s 5ms/step - loss: 0.4739 - accuracy: 0.8768
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 0.1282 - accuracy: 0.9676
Epoch 6/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0912 - accuracy: 0.9804
Epoch 7/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0310 - accuracy: 0.9920
Epoch 8/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0093 - accuracy: 0.9972
Epoch 9/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0070 - accuracy: 0.9980
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0039 - accuracy: 0.9988
313/313 [==============================] - 1s 5ms/step - loss: 8.9189 - accuracy: 0.1596
Test Accuracy: 0.15960000455379486
Epoch 1/10
79/79 [==============================] - 1s 7ms/step - loss: 4.1865 - accuracy: 0.1064
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 2.8691 - accuracy: 0.3004
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 1.4613 - accuracy: 0.6256
Epoch 4/10
79/79 [==============================] - 0s 5ms/step - loss: 0.3729 - accuracy: 0.9044
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 0.1319 - accuracy: 0.9668
Epoch 6/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0456 - accuracy: 0.9880
Epoch 7/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0117 - accuracy: 0.9964
Epoch 8/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0037 - accuracy: 0.9996
Epoch 9/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0013 - accuracy: 1.0000
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 8.1577e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 8.6480 - accuracy: 0.1710
Test Accuracy: 0.17100000381469727
Epoch 1/10
79/79 [==============================] - 0s 6ms/step - loss: 4.1786 - accuracy: 0.1220
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 2.7512 - accuracy: 0.3312
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 1.3495 - accuracy: 0.6476
Epoch 4/10
79/79 [==============================] - 0s 5ms/step - loss: 0.3282 - accuracy: 0.9220
Epoch 5/10
79/79 [==============================] - 0s 6ms/step - loss: 0.0677 - accuracy: 0.9824
Epoch 6/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0166 - accuracy: 0.9972
Epoch 7/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0049 - accuracy: 0.9992
Epoch 8/10
79/79 [==============================] - 1s 7ms/step - loss: 0.0012 - accuracy: 1.0000
Epoch 9/10
79/79 [==============================] - 1s 7ms/step - loss: 7.9767e-04 - accuracy: 1.0000
Epoch 10/10
79/79 [==============================] - 1s 7ms/step - loss: 6.1245e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 8.4437 - accuracy: 0.1906
Test Accuracy: 0.19059999287128448
Epoch 1/10
79/79 [==============================] - 1s 6ms/step - loss: 4.1194 - accuracy: 0.1184
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 2.5828 - accuracy: 0.3668
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 1.0940 - accuracy: 0.7040
Epoch 4/10
79/79 [==============================] - 0s 5ms/step - loss: 0.2739 - accuracy: 0.9320
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0474 - accuracy: 0.9900
Epoch 6/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0121 - accuracy: 0.9968
Epoch 7/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0111 - accuracy: 0.9980
Epoch 8/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0013 - accuracy: 1.0000
Epoch 9/10
79/79 [==============================] - 0s 5ms/step - loss: 8.2664e-04 - accuracy: 1.0000
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 6.2965e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 7.9984 - accuracy: 0.1857
Test Accuracy: 0.18569999933242798
Epoch 1/10
79/79 [==============================] - 0s 6ms/step - loss: 4.0196 - accuracy: 0.1428
Epoch 2/10
79/79 [==============================] - 0s 5ms/step - loss: 2.4980 - accuracy: 0.3840
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 0.9818 - accuracy: 0.7468
Epoch 4/10
79/79 [==============================] - 0s 6ms/step - loss: 0.1569 - accuracy: 0.9616
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0212 - accuracy: 0.9976
Epoch 6/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0184 - accuracy: 0.9968
Epoch 7/10
79/79 [==============================] - 1s 7ms/step - loss: 0.0016 - accuracy: 1.0000
Epoch 8/10
79/79 [==============================] - 1s 7ms/step - loss: 8.6281e-04 - accuracy: 1.0000
Epoch 9/10
79/79 [==============================] - 1s 7ms/step - loss: 6.5137e-04 - accuracy: 1.0000
Epoch 10/10
79/79 [==============================] - 1s 7ms/step - loss: 5.2389e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 8.1572 - accuracy: 0.1980
Test Accuracy: 0.1979999989271164
Epoch 1/10
79/79 [==============================] - 0s 6ms/step - loss: 4.2639 - accuracy: 0.1052
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 2.7905 - accuracy: 0.3296
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 1.0703 - accuracy: 0.7348
Epoch 4/10
79/79 [==============================] - 0s 5ms/step - loss: 0.1812 - accuracy: 0.9576
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0297 - accuracy: 0.9940
Epoch 6/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0057 - accuracy: 0.9992
Epoch 7/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0019 - accuracy: 1.0000
Epoch 8/10
79/79 [==============================] - 0s 6ms/step - loss: 8.2083e-04 - accuracy: 1.0000
Epoch 9/10
79/79 [==============================] - 0s 6ms/step - loss: 6.9068e-04 - accuracy: 1.0000
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 5.1207e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 7.8995 - accuracy: 0.1967
Test Accuracy: 0.19670000672340393
Epoch 1/10
79/79 [==============================] - 0s 6ms/step - loss: 4.0986 - accuracy: 0.1212
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 2.4982 - accuracy: 0.3892
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 0.8835 - accuracy: 0.7700
Epoch 4/10
79/79 [==============================] - 0s 5ms/step - loss: 0.1437 - accuracy: 0.9652
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0202 - accuracy: 0.9956
Epoch 6/10
79/79 [==============================] - 0s 6ms/step - loss: 0.0063 - accuracy: 0.9988
Epoch 7/10
79/79 [==============================] - 1s 7ms/step - loss: 0.0106 - accuracy: 0.9988
Epoch 8/10
79/79 [==============================] - 1s 7ms/step - loss: 0.0036 - accuracy: 0.9992
Epoch 9/10
79/79 [==============================] - 1s 7ms/step - loss: 9.9594e-04 - accuracy: 1.0000
Epoch 10/10
79/79 [==============================] - 1s 7ms/step - loss: 6.8659e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 7.5795 - accuracy: 0.2075
Test Accuracy: 0.20749999582767487
Epoch 1/10
79/79 [==============================] - 0s 6ms/step - loss: 4.1010 - accuracy: 0.1344
Epoch 2/10
79/79 [==============================] - 0s 5ms/step - loss: 2.6738 - accuracy: 0.3476
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 1.1149 - accuracy: 0.7088
Epoch 4/10
79/79 [==============================] - 0s 5ms/step - loss: 0.1716 - accuracy: 0.9560
Epoch 5/10
79/79 [==============================] - 0s 6ms/step - loss: 0.0151 - accuracy: 0.9988
Epoch 6/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0044 - accuracy: 0.9996
Epoch 7/10
79/79 [==============================] - 0s 6ms/step - loss: 0.0016 - accuracy: 1.0000
Epoch 8/10
79/79 [==============================] - 0s 5ms/step - loss: 9.9474e-04 - accuracy: 1.0000
Epoch 9/10
79/79 [==============================] - 0s 5ms/step - loss: 7.7459e-04 - accuracy: 1.0000
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 6.3545e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 7.2173 - accuracy: 0.2169
Test Accuracy: 0.21690000593662262
Epoch 1/10
79/79 [==============================] - 0s 6ms/step - loss: 3.9391 - accuracy: 0.1464
Epoch 2/10
79/79 [==============================] - 0s 5ms/step - loss: 2.3370 - accuracy: 0.4236
Epoch 3/10
79/79 [==============================] - 0s 6ms/step - loss: 0.8952 - accuracy: 0.7688
Epoch 4/10
79/79 [==============================] - 0s 5ms/step - loss: 0.1148 - accuracy: 0.9768
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0160 - accuracy: 0.9972
Epoch 6/10
79/79 [==============================] - 1s 7ms/step - loss: 0.0053 - accuracy: 0.9992
Epoch 7/10
79/79 [==============================] - 1s 7ms/step - loss: 0.0024 - accuracy: 1.0000
Epoch 8/10
79/79 [==============================] - 1s 7ms/step - loss: 0.0013 - accuracy: 1.0000
Epoch 9/10
79/79 [==============================] - 1s 7ms/step - loss: 9.7848e-04 - accuracy: 1.0000
Epoch 10/10
79/79 [==============================] - 1s 7ms/step - loss: 7.9449e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 4ms/step - loss: 7.1200 - accuracy: 0.2170
Test Accuracy: 0.21699999272823334
Epoch 1/10
79/79 [==============================] - 0s 6ms/step - loss: 3.9134 - accuracy: 0.1616
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 2.1817 - accuracy: 0.4504
Epoch 3/10
79/79 [==============================] - 0s 6ms/step - loss: 0.6403 - accuracy: 0.8320
Epoch 4/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0779 - accuracy: 0.9876
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0108 - accuracy: 0.9992
Epoch 6/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0028 - accuracy: 1.0000
Epoch 7/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0016 - accuracy: 1.0000
Epoch 8/10
79/79 [==============================] - 0s 6ms/step - loss: 0.0012 - accuracy: 1.0000
Epoch 9/10
79/79 [==============================] - 0s 5ms/step - loss: 9.5803e-04 - accuracy: 1.0000
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 7.9289e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 7.0064 - accuracy: 0.2174
Test Accuracy: 0.21739999949932098
Epoch 1/10
79/79 [==============================] - 0s 6ms/step - loss: 3.9399 - accuracy: 0.1436
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 2.4328 - accuracy: 0.3972
Epoch 3/10
79/79 [==============================] - 0s 6ms/step - loss: 0.8902 - accuracy: 0.7744
Epoch 4/10
79/79 [==============================] - 0s 6ms/step - loss: 0.1181 - accuracy: 0.9768
Epoch 5/10
79/79 [==============================] - 1s 7ms/step - loss: 0.0119 - accuracy: 0.9992
Epoch 6/10
79/79 [==============================] - 1s 7ms/step - loss: 0.0030 - accuracy: 0.9996
Epoch 7/10
79/79 [==============================] - 1s 8ms/step - loss: 0.0014 - accuracy: 1.0000
Epoch 8/10
79/79 [==============================] - 1s 7ms/step - loss: 8.1873e-04 - accuracy: 1.0000
Epoch 9/10
79/79 [==============================] - 0s 6ms/step - loss: 5.4325e-04 - accuracy: 1.0000
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 3.9094e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 7.6312 - accuracy: 0.2148
Test Accuracy: 0.21480000019073486
Epoch 1/10
79/79 [==============================] - 0s 6ms/step - loss: 3.9072 - accuracy: 0.1608
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 2.3039 - accuracy: 0.4276
Epoch 3/10
79/79 [==============================] - 1s 8ms/step - loss: 0.8080 - accuracy: 0.7944
Epoch 4/10
79/79 [==============================] - 1s 9ms/step - loss: 0.0992 - accuracy: 0.9828
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0252 - accuracy: 0.9984
Epoch 6/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0040 - accuracy: 1.0000
Epoch 7/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0020 - accuracy: 1.0000
Epoch 8/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0015 - accuracy: 1.0000
Epoch 9/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0012 - accuracy: 1.0000
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 9.5905e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 6.9959 - accuracy: 0.2194
Test Accuracy: 0.21940000355243683
Epoch 1/10
79/79 [==============================] - 0s 6ms/step - loss: 4.0279 - accuracy: 0.1500
Epoch 2/10
79/79 [==============================] - 1s 7ms/step - loss: 2.3828 - accuracy: 0.4172
Epoch 3/10
79/79 [==============================] - 1s 7ms/step - loss: 0.7991 - accuracy: 0.7928
Epoch 4/10
79/79 [==============================] - 1s 7ms/step - loss: 0.1029 - accuracy: 0.9804
Epoch 5/10
79/79 [==============================] - 1s 7ms/step - loss: 0.0185 - accuracy: 0.9980
Epoch 6/10
79/79 [==============================] - 1s 7ms/step - loss: 0.0035 - accuracy: 1.0000
Epoch 7/10
79/79 [==============================] - 0s 6ms/step - loss: 0.0016 - accuracy: 1.0000
Epoch 8/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0011 - accuracy: 1.0000
Epoch 9/10
79/79 [==============================] - 0s 5ms/step - loss: 8.3798e-04 - accuracy: 1.0000
Epoch 10/10
79/79 [==============================] - 0s 6ms/step - loss: 6.4147e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 4ms/step - loss: 7.2905 - accuracy: 0.2231
Test Accuracy: 0.22310000658035278
Epoch 1/10
79/79 [==============================] - 1s 7ms/step - loss: 3.9528 - accuracy: 0.1496
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 2.3532 - accuracy: 0.4160
Epoch 3/10
79/79 [==============================] - 1s 7ms/step - loss: 0.8473 - accuracy: 0.7844
Epoch 4/10
79/79 [==============================] - 1s 7ms/step - loss: 0.1101 - accuracy: 0.9800
Epoch 5/10
79/79 [==============================] - 1s 7ms/step - loss: 0.0166 - accuracy: 0.9968
Epoch 6/10
79/79 [==============================] - 1s 7ms/step - loss: 0.0049 - accuracy: 1.0000
Epoch 7/10
79/79 [==============================] - 1s 8ms/step - loss: 0.0022 - accuracy: 1.0000
Epoch 8/10
79/79 [==============================] - 1s 6ms/step - loss: 0.0016 - accuracy: 1.0000
Epoch 9/10
79/79 [==============================] - 0s 6ms/step - loss: 0.0013 - accuracy: 1.0000
Epoch 10/10
79/79 [==============================] - 0s 6ms/step - loss: 0.0010 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 6.9899 - accuracy: 0.2219
Test Accuracy: 0.22190000116825104
Epoch 1/10
79/79 [==============================] - 1s 7ms/step - loss: 3.8998 - accuracy: 0.1496
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 2.1493 - accuracy: 0.4700
Epoch 3/10
79/79 [==============================] - 0s 6ms/step - loss: 0.6528 - accuracy: 0.8352
Epoch 4/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0762 - accuracy: 0.9892
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0082 - accuracy: 1.0000
Epoch 6/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0031 - accuracy: 1.0000
Epoch 7/10
79/79 [==============================] - 0s 6ms/step - loss: 0.0019 - accuracy: 1.0000
Epoch 8/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0014 - accuracy: 1.0000
Epoch 9/10
79/79 [==============================] - 0s 5ms/step - loss: 0.0012 - accuracy: 1.0000
Epoch 10/10
79/79 [==============================] - 0s 6ms/step - loss: 9.6189e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 4ms/step - loss: 6.9305 - accuracy: 0.2296

#### Batches 10

------------------------------------------

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar100
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam

# Load the CIFAR-100 dataset
(x_train, y_train), (x_test, y_test) = cifar100.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 0.1  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = x_train + tf.random.normal(shape=x_train.shape, mean=0.0, stddev=corruption_level, dtype=tf.float32)
corrupted_data = tf.clip_by_value(corrupted_data, 0.0, 1.0)

# Convert the labels to one-hot encoding
num_classes = 100
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 10 batches
n_batches = 10
batch_size = x_train.shape[0] // n_batches

# Define the model architecture
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)))
model.add(Conv2D(32, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch separately
for i in range(n_batches):
    start_index = i * batch_size
    end_index = (i + 1) * batch_size
    x_batch = corrupted_data[start_index:end_index]
    y_batch = y_train[start_index:end_index]

    # Train the model on the current batch
    model.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)

Epoch 1/10
157/157 [==============================] - 7s 7ms/step - loss: 4.5774 - accuracy: 0.0168
Epoch 2/10
157/157 [==============================] - 1s 5ms/step - loss: 4.1644 - accuracy: 0.0658
Epoch 3/10
157/157 [==============================] - 1s 5ms/step - loss: 3.7016 - accuracy: 0.1320
Epoch 4/10
157/157 [==============================] - 1s 5ms/step - loss: 3.1663 - accuracy: 0.2172
Epoch 5/10
157/157 [==============================] - 1s 5ms/step - loss: 2.4849 - accuracy: 0.3650
Epoch 6/10
157/157 [==============================] - 1s 5ms/step - loss: 1.6176 - accuracy: 0.5576
Epoch 7/10
157/157 [==============================] - 1s 5ms/step - loss: 0.7919 - accuracy: 0.7818
Epoch 8/10
157/157 [==============================] - 1s 5ms/step - loss: 0.2957 - accuracy: 0.9168
Epoch 9/10
157/157 [==============================] - 1s 7ms/step - loss: 0.1571 - accuracy: 0.9548
Epoch 10/10
157/157 [==============================] - 1s 9ms/step - loss: 0.1416 - accuracy: 0.9560
313/313 [==============================] - 3s 8ms/step - loss: 8.5263 - accuracy: 0.1558
Test Accuracy: 0.155799999833107
Epoch 1/10
157/157 [==============================] - 1s 9ms/step - loss: 3.8161 - accuracy: 0.1506
Epoch 2/10
157/157 [==============================] - 1s 9ms/step - loss: 2.7659 - accuracy: 0.3172
Epoch 3/10
157/157 [==============================] - 2s 10ms/step - loss: 1.6027 - accuracy: 0.5804
Epoch 4/10
157/157 [==============================] - 1s 9ms/step - loss: 0.4670 - accuracy: 0.8696
Epoch 5/10
157/157 [==============================] - 1s 9ms/step - loss: 0.1496 - accuracy: 0.9626
Epoch 6/10
157/157 [==============================] - 2s 10ms/step - loss: 0.0407 - accuracy: 0.9896
Epoch 7/10
157/157 [==============================] - 2s 14ms/step - loss: 0.0237 - accuracy: 0.9948
Epoch 8/10
157/157 [==============================] - 2s 10ms/step - loss: 0.0248 - accuracy: 0.9938
Epoch 9/10
157/157 [==============================] - 1s 9ms/step - loss: 0.0816 - accuracy: 0.9754
Epoch 10/10
157/157 [==============================] - 1s 8ms/step - loss: 0.0508 - accuracy: 0.9866
313/313 [==============================] - 1s 4ms/step - loss: 8.4791 - accuracy: 0.1764
Test Accuracy: 0.17640000581741333
Epoch 1/10
157/157 [==============================] - 1s 8ms/step - loss: 3.9685 - accuracy: 0.1242
Epoch 2/10
157/157 [==============================] - 1s 7ms/step - loss: 2.6607 - accuracy: 0.3494
Epoch 3/10
157/157 [==============================] - 1s 6ms/step - loss: 1.1484 - accuracy: 0.7046
Epoch 4/10
157/157 [==============================] - 1s 5ms/step - loss: 0.2214 - accuracy: 0.9396
Epoch 5/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0646 - accuracy: 0.9848
Epoch 6/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0197 - accuracy: 0.9960
Epoch 7/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0061 - accuracy: 0.9984
Epoch 8/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0033 - accuracy: 0.9996
Epoch 9/10
157/157 [==============================] - 1s 5ms/step - loss: 3.9550e-04 - accuracy: 1.0000
Epoch 10/10
157/157 [==============================] - 1s 5ms/step - loss: 2.2715e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 8.9191 - accuracy: 0.1984
Test Accuracy: 0.19840000569820404
Epoch 1/10
157/157 [==============================] - 1s 5ms/step - loss: 3.8615 - accuracy: 0.1536
Epoch 2/10
157/157 [==============================] - 1s 6ms/step - loss: 2.5054 - accuracy: 0.3770
Epoch 3/10
157/157 [==============================] - 1s 7ms/step - loss: 0.9403 - accuracy: 0.7448
Epoch 4/10
157/157 [==============================] - 1s 7ms/step - loss: 0.1383 - accuracy: 0.9660
Epoch 5/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0257 - accuracy: 0.9950
Epoch 6/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0025 - accuracy: 0.9996
Epoch 7/10
157/157 [==============================] - 1s 5ms/step - loss: 8.6151e-04 - accuracy: 1.0000
Epoch 8/10
157/157 [==============================] - 1s 5ms/step - loss: 4.3023e-04 - accuracy: 1.0000
Epoch 9/10
157/157 [==============================] - 1s 5ms/step - loss: 3.0278e-04 - accuracy: 1.0000
Epoch 10/10
157/157 [==============================] - 1s 5ms/step - loss: 2.3849e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 8.3513 - accuracy: 0.2196
Test Accuracy: 0.21960000693798065
Epoch 1/10
157/157 [==============================] - 1s 6ms/step - loss: 3.6998 - accuracy: 0.1728
Epoch 2/10
157/157 [==============================] - 1s 6ms/step - loss: 2.2736 - accuracy: 0.4268
Epoch 3/10
157/157 [==============================] - 1s 5ms/step - loss: 0.6894 - accuracy: 0.8148
Epoch 4/10
157/157 [==============================] - 1s 6ms/step - loss: 0.0958 - accuracy: 0.9758
Epoch 5/10
157/157 [==============================] - 1s 7ms/step - loss: 0.0198 - accuracy: 0.9950
Epoch 6/10
157/157 [==============================] - 1s 7ms/step - loss: 0.0031 - accuracy: 0.9994
Epoch 7/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0020 - accuracy: 0.9996
Epoch 8/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0013 - accuracy: 0.9996
Epoch 9/10
157/157 [==============================] - 1s 5ms/step - loss: 3.2368e-04 - accuracy: 1.0000
Epoch 10/10
157/157 [==============================] - 1s 6ms/step - loss: 2.1333e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 8.1311 - accuracy: 0.2360
Test Accuracy: 0.23600000143051147
Epoch 1/10
157/157 [==============================] - 1s 6ms/step - loss: 3.6566 - accuracy: 0.1742
Epoch 2/10
157/157 [==============================] - 1s 5ms/step - loss: 2.2649 - accuracy: 0.4230
Epoch 3/10
157/157 [==============================] - 1s 5ms/step - loss: 0.7738 - accuracy: 0.7944
Epoch 4/10
157/157 [==============================] - 1s 5ms/step - loss: 0.1130 - accuracy: 0.9708
Epoch 5/10
157/157 [==============================] - 1s 6ms/step - loss: 0.0338 - accuracy: 0.9938
Epoch 6/10
157/157 [==============================] - 1s 8ms/step - loss: 0.0084 - accuracy: 0.9984
Epoch 7/10
157/157 [==============================] - 1s 7ms/step - loss: 0.0016 - accuracy: 1.0000
Epoch 8/10
157/157 [==============================] - 1s 5ms/step - loss: 5.8815e-04 - accuracy: 1.0000
Epoch 9/10
157/157 [==============================] - 1s 6ms/step - loss: 3.9893e-04 - accuracy: 1.0000
Epoch 10/10
157/157 [==============================] - 1s 5ms/step - loss: 3.0567e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 7.5341 - accuracy: 0.2411
Test Accuracy: 0.2410999983549118
Epoch 1/10
157/157 [==============================] - 1s 6ms/step - loss: 3.5780 - accuracy: 0.1924
Epoch 2/10
157/157 [==============================] - 1s 5ms/step - loss: 2.0835 - accuracy: 0.4726
Epoch 3/10
157/157 [==============================] - 1s 5ms/step - loss: 0.6259 - accuracy: 0.8358
Epoch 4/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0799 - accuracy: 0.9820
Epoch 5/10
157/157 [==============================] - 1s 7ms/step - loss: 0.0159 - accuracy: 0.9970
Epoch 6/10
157/157 [==============================] - 1s 8ms/step - loss: 0.0050 - accuracy: 0.9996
Epoch 7/10
157/157 [==============================] - 2s 11ms/step - loss: 0.0054 - accuracy: 0.9996
Epoch 8/10
157/157 [==============================] - 1s 8ms/step - loss: 7.9961e-04 - accuracy: 1.0000
Epoch 9/10
157/157 [==============================] - 1s 7ms/step - loss: 4.9153e-04 - accuracy: 1.0000
Epoch 10/10
157/157 [==============================] - 1s 5ms/step - loss: 3.7858e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 4ms/step - loss: 7.1939 - accuracy: 0.2515
Test Accuracy: 0.2515000104904175
Epoch 1/10
157/157 [==============================] - 1s 6ms/step - loss: 3.5377 - accuracy: 0.1990
Epoch 2/10
157/157 [==============================] - 1s 5ms/step - loss: 2.0052 - accuracy: 0.4906
Epoch 3/10
157/157 [==============================] - 1s 5ms/step - loss: 0.5467 - accuracy: 0.8568
Epoch 4/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0548 - accuracy: 0.9894
Epoch 5/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0161 - accuracy: 0.9970
Epoch 6/10
157/157 [==============================] - 1s 6ms/step - loss: 0.0085 - accuracy: 0.9984
Epoch 7/10
157/157 [==============================] - 1s 6ms/step - loss: 0.0020 - accuracy: 0.9996
Epoch 8/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0012 - accuracy: 0.9998
Epoch 9/10
157/157 [==============================] - 1s 7ms/step - loss: 4.9611e-04 - accuracy: 1.0000
Epoch 10/10
157/157 [==============================] - 1s 7ms/step - loss: 3.8382e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 7.0781 - accuracy: 0.2545
Test Accuracy: 0.25450000166893005
Epoch 1/10
157/157 [==============================] - 1s 6ms/step - loss: 3.5105 - accuracy: 0.2098
Epoch 2/10
157/157 [==============================] - 1s 5ms/step - loss: 1.8814 - accuracy: 0.5090
Epoch 3/10
157/157 [==============================] - 1s 6ms/step - loss: 0.4326 - accuracy: 0.8934
Epoch 4/10
157/157 [==============================] - 1s 6ms/step - loss: 0.0412 - accuracy: 0.9926
Epoch 5/10
157/157 [==============================] - 1s 6ms/step - loss: 0.0051 - accuracy: 0.9998
Epoch 6/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0016 - accuracy: 1.0000
Epoch 7/10
157/157 [==============================] - 1s 6ms/step - loss: 9.3480e-04 - accuracy: 1.0000
Epoch 8/10
157/157 [==============================] - 1s 5ms/step - loss: 6.9128e-04 - accuracy: 1.0000
Epoch 9/10
157/157 [==============================] - 1s 5ms/step - loss: 5.4056e-04 - accuracy: 1.0000
Epoch 10/10
157/157 [==============================] - 1s 5ms/step - loss: 4.3608e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 5ms/step - loss: 6.8227 - accuracy: 0.2665
Test Accuracy: 0.26649999618530273
Epoch 1/10
157/157 [==============================] - 1s 7ms/step - loss: 3.4715 - accuracy: 0.2116
Epoch 2/10
157/157 [==============================] - 1s 6ms/step - loss: 1.8461 - accuracy: 0.5244
Epoch 3/10
157/157 [==============================] - 1s 5ms/step - loss: 0.4376 - accuracy: 0.8820
Epoch 4/10
157/157 [==============================] - 1s 5ms/step - loss: 0.0358 - accuracy: 0.9950
Epoch 5/10
157/157 [==============================] - 1s 6ms/step - loss: 0.0043 - accuracy: 1.0000
Epoch 6/10
157/157 [==============================] - 1s 6ms/step - loss: 0.0017 - accuracy: 1.0000
Epoch 7/10
157/157 [==============================] - 1s 6ms/step - loss: 0.0011 - accuracy: 1.0000
Epoch 8/10
157/157 [==============================] - 1s 5ms/step - loss: 8.2638e-04 - accuracy: 1.0000
Epoch 9/10
157/157 [==============================] - 1s 5ms/step - loss: 6.5080e-04 - accuracy: 1.0000
Epoch 10/10
157/157 [==============================] - 1s 5ms/step - loss: 5.2639e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 4ms/step - loss: 6.5772 - accuracy: 0.2705
Test Accuracy: 0.2705000042915344

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar100
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam

# Load the CIFAR-100 dataset
(x_train, y_train), (x_test, y_test) = cifar100.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 0.1  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = tf.image.random_noise(x_train, var=corruption_level)
corrupted_data = tf.clip_by_value(corrupted_data, 0.0, 1.0)

# Convert the labels to one-hot encoding
num_classes = 100
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 10 batches
n_batches = 10
batch_size = x_train.shape[0] // n_batches

# Define the model architecture
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)))
model.add(Conv2D(32, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch separately
for i in range(n_batches):
    start_index = i * batch_size
    end_index = (i + 1) * batch_size
    x_batch = corrupted_data[start_index:end_index]
    y_batch = y_train[start_index:end_index]

    # Train the model on the current batch
    model.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)

#### Batches 6

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar100
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam

# Load the CIFAR-100 dataset
(x_train, y_train), (x_test, y_test) = cifar100.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 0.1  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = x_train + tf.random.normal(shape=x_train.shape, mean=0.0, stddev=corruption_level, dtype=tf.float32)
corrupted_data = tf.clip_by_value(corrupted_data, 0.0, 1.0)

# Convert the labels to one-hot encoding
num_classes = 100
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 10 batches
n_batches = 6
batch_size = x_train.shape[0] // n_batches

# Define the model architecture
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)))
model.add(Conv2D(32, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch separately
for i in range(n_batches):
    start_index = i * batch_size
    end_index = (i + 1) * batch_size
    x_batch = corrupted_data[start_index:end_index]
    y_batch = y_train[start_index:end_index]

    # Train the model on the current batch
    model.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)

Epoch 1/10
261/261 [==============================] - 16s 12ms/step - loss: 4.4480 - accuracy: 0.0282
Epoch 2/10
261/261 [==============================] - 2s 6ms/step - loss: 3.8732 - accuracy: 0.0980
Epoch 3/10
261/261 [==============================] - 1s 5ms/step - loss: 3.4047 - accuracy: 0.1840
Epoch 4/10
261/261 [==============================] - 1s 5ms/step - loss: 2.8984 - accuracy: 0.2722
Epoch 5/10
261/261 [==============================] - 2s 7ms/step - loss: 2.3092 - accuracy: 0.3923
Epoch 6/10
261/261 [==============================] - 2s 6ms/step - loss: 1.5955 - accuracy: 0.5712
Epoch 7/10
261/261 [==============================] - 1s 5ms/step - loss: 0.9057 - accuracy: 0.7441
Epoch 8/10
261/261 [==============================] - 1s 5ms/step - loss: 0.4503 - accuracy: 0.8729
Epoch 9/10
261/261 [==============================] - 1s 5ms/step - loss: 0.2528 - accuracy: 0.9290
Epoch 10/10
261/261 [==============================] - 1s 5ms/step - loss: 0.1880 - accuracy: 0.9452
313/313 [==============================] - 1s 3ms/step - loss: 8.6898 - accuracy: 0.1819
Test Accuracy: 0.1818999946117401
Epoch 1/10
261/261 [==============================] - 1s 5ms/step - loss: 3.6881 - accuracy: 0.1739
Epoch 2/10
261/261 [==============================] - 2s 6ms/step - loss: 2.7222 - accuracy: 0.3288
Epoch 3/10
261/261 [==============================] - 2s 7ms/step - loss: 1.8681 - accuracy: 0.5157
Epoch 4/10
261/261 [==============================] - 1s 5ms/step - loss: 0.9378 - accuracy: 0.7451
Epoch 5/10
261/261 [==============================] - 1s 5ms/step - loss: 0.3102 - accuracy: 0.9162
Epoch 6/10
261/261 [==============================] - 1s 5ms/step - loss: 0.1194 - accuracy: 0.9663
Epoch 7/10
261/261 [==============================] - 1s 5ms/step - loss: 0.0689 - accuracy: 0.9820
Epoch 8/10
261/261 [==============================] - 1s 5ms/step - loss: 0.0731 - accuracy: 0.9782
Epoch 9/10
261/261 [==============================] - 1s 5ms/step - loss: 0.0707 - accuracy: 0.9794
Epoch 10/10
261/261 [==============================] - 1s 5ms/step - loss: 0.0920 - accuracy: 0.9719
313/313 [==============================] - 1s 4ms/step - loss: 8.8090 - accuracy: 0.1996
Test Accuracy: 0.1995999962091446
Epoch 1/10
261/261 [==============================] - 1s 6ms/step - loss: 3.6364 - accuracy: 0.1812
Epoch 2/10
261/261 [==============================] - 1s 5ms/step - loss: 2.4975 - accuracy: 0.3771
Epoch 3/10
261/261 [==============================] - 2s 6ms/step - loss: 1.4150 - accuracy: 0.6295
Epoch 4/10
261/261 [==============================] - 2s 7ms/step - loss: 0.4120 - accuracy: 0.8913
Epoch 5/10
261/261 [==============================] - 1s 5ms/step - loss: 0.0867 - accuracy: 0.9792
Epoch 6/10
261/261 [==============================] - 1s 5ms/step - loss: 0.0270 - accuracy: 0.9936
Epoch 7/10
261/261 [==============================] - 1s 5ms/step - loss: 0.0113 - accuracy: 0.9975
Epoch 8/10
261/261 [==============================] - 1s 5ms/step - loss: 0.0040 - accuracy: 0.9993
Epoch 9/10
261/261 [==============================] - 1s 5ms/step - loss: 0.0378 - accuracy: 0.9892
Epoch 10/10
261/261 [==============================] - 1s 5ms/step - loss: 0.1097 - accuracy: 0.9690
313/313 [==============================] - 1s 4ms/step - loss: 7.9097 - accuracy: 0.2121
Test Accuracy: 0.21209999918937683
Epoch 1/10
261/261 [==============================] - 1s 6ms/step - loss: 3.4830 - accuracy: 0.2082
Epoch 2/10
261/261 [==============================] - 1s 5ms/step - loss: 2.2394 - accuracy: 0.4301
Epoch 3/10
261/261 [==============================] - 1s 5ms/step - loss: 1.0268 - accuracy: 0.7197
Epoch 4/10
261/261 [==============================] - 2s 6ms/step - loss: 0.2169 - accuracy: 0.9448
Epoch 5/10
261/261 [==============================] - 2s 7ms/step - loss: 0.0395 - accuracy: 0.9914
Epoch 6/10
261/261 [==============================] - 1s 5ms/step - loss: 0.0110 - accuracy: 0.9981
Epoch 7/10
261/261 [==============================] - 1s 5ms/step - loss: 0.0068 - accuracy: 0.9982
Epoch 8/10
261/261 [==============================] - 1s 5ms/step - loss: 0.0056 - accuracy: 0.9987
Epoch 9/10
261/261 [==============================] - 1s 5ms/step - loss: 0.0224 - accuracy: 0.9941
Epoch 10/10
261/261 [==============================] - 1s 5ms/step - loss: 0.1259 - accuracy: 0.9628
313/313 [==============================] - 1s 4ms/step - loss: 7.3715 - accuracy: 0.2196
Test Accuracy: 0.21960000693798065
Epoch 1/10
261/261 [==============================] - 1s 6ms/step - loss: 3.4719 - accuracy: 0.2051
Epoch 2/10
261/261 [==============================] - 1s 5ms/step - loss: 2.1709 - accuracy: 0.4438
Epoch 3/10
261/261 [==============================] - 1s 5ms/step - loss: 0.9350 - accuracy: 0.7562
Epoch 4/10
261/261 [==============================] - 1s 5ms/step - loss: 0.1765 - accuracy: 0.9584
Epoch 5/10
261/261 [==============================] - 1s 5ms/step - loss: 0.0233 - accuracy: 0.9966
Epoch 6/10
261/261 [==============================] - 2s 7ms/step - loss: 0.0085 - accuracy: 0.9990
Epoch 7/10
261/261 [==============================] - 1s 6ms/step - loss: 0.0019 - accuracy: 0.9998
Epoch 8/10
261/261 [==============================] - 1s 5ms/step - loss: 7.2363e-04 - accuracy: 1.0000
Epoch 9/10
261/261 [==============================] - 1s 5ms/step - loss: 5.0329e-04 - accuracy: 1.0000
Epoch 10/10
261/261 [==============================] - 1s 5ms/step - loss: 3.8085e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 4ms/step - loss: 7.9711 - accuracy: 0.2563
Test Accuracy: 0.2563000023365021
Epoch 1/10
261/261 [==============================] - 2s 6ms/step - loss: 3.4832 - accuracy: 0.2084
Epoch 2/10
261/261 [==============================] - 2s 7ms/step - loss: 2.0988 - accuracy: 0.4674
Epoch 3/10
261/261 [==============================] - 1s 5ms/step - loss: 0.8031 - accuracy: 0.7893
Epoch 4/10
261/261 [==============================] - 1s 5ms/step - loss: 0.1258 - accuracy: 0.9708
Epoch 5/10
261/261 [==============================] - 1s 5ms/step - loss: 0.0175 - accuracy: 0.9968
Epoch 6/10
261/261 [==============================] - 1s 6ms/step - loss: 0.0040 - accuracy: 0.9995
Epoch 7/10
261/261 [==============================] - 2s 7ms/step - loss: 0.0031 - accuracy: 0.9993
Epoch 8/10
261/261 [==============================] - 2s 6ms/step - loss: 0.0013 - accuracy: 1.0000
Epoch 9/10
261/261 [==============================] - 1s 5ms/step - loss: 6.4724e-04 - accuracy: 1.0000
Epoch 10/10
261/261 [==============================] - 1s 5ms/step - loss: 3.8246e-04 - accuracy: 1.0000
313/313 [==============================] - 1s 3ms/step - loss: 7.7106 - accuracy: 0.2716
Test Accuracy: 0.27160000801086426

#### Batches 5

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar100
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam

# Load the CIFAR-100 dataset
(x_train, y_train), (x_test, y_test) = cifar100.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 0.1  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = x_train + tf.random.normal(shape=x_train.shape, mean=0.0, stddev=corruption_level, dtype=tf.float32)
corrupted_data = tf.clip_by_value(corrupted_data, 0.0, 1.0)

# Convert the labels to one-hot encoding
num_classes = 100
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 10 batches
n_batches = 5
batch_size = x_train.shape[0] // n_batches

# Define the model architecture
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)))
model.add(Conv2D(32, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch separately
for i in range(n_batches):
    start_index = i * batch_size
    end_index = (i + 1) * batch_size
    x_batch = corrupted_data[start_index:end_index]
    y_batch = y_train[start_index:end_index]

    # Train the model on the current batch
    model.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)

Epoch 1/10
313/313 [==============================] - 13s 12ms/step - loss: 4.3589 - accuracy: 0.0396
Epoch 2/10
313/313 [==============================] - 3s 11ms/step - loss: 3.8415 - accuracy: 0.1086
Epoch 3/10
313/313 [==============================] - 3s 11ms/step - loss: 3.3629 - accuracy: 0.1927
Epoch 4/10
313/313 [==============================] - 4s 13ms/step - loss: 2.8228 - accuracy: 0.2944
Epoch 5/10
313/313 [==============================] - 3s 11ms/step - loss: 2.2116 - accuracy: 0.4230
Epoch 6/10
313/313 [==============================] - 3s 10ms/step - loss: 1.4525 - accuracy: 0.6057
Epoch 7/10
313/313 [==============================] - 3s 10ms/step - loss: 0.7403 - accuracy: 0.7899
Epoch 8/10
313/313 [==============================] - 4s 13ms/step - loss: 0.3833 - accuracy: 0.8880
Epoch 9/10
313/313 [==============================] - 3s 11ms/step - loss: 0.2153 - accuracy: 0.9331
Epoch 10/10
313/313 [==============================] - 3s 9ms/step - loss: 0.1954 - accuracy: 0.9446
313/313 [==============================] - 1s 4ms/step - loss: 7.7971 - accuracy: 0.2000
Test Accuracy: 0.20000000298023224
Epoch 1/10
313/313 [==============================] - 2s 5ms/step - loss: 3.4888 - accuracy: 0.2001
Epoch 2/10
313/313 [==============================] - 2s 5ms/step - loss: 2.6122 - accuracy: 0.3496
Epoch 3/10
313/313 [==============================] - 2s 5ms/step - loss: 1.7784 - accuracy: 0.5336
Epoch 4/10
313/313 [==============================] - 2s 5ms/step - loss: 0.8140 - accuracy: 0.7777
Epoch 5/10
313/313 [==============================] - 2s 6ms/step - loss: 0.2238 - accuracy: 0.9370
Epoch 6/10
313/313 [==============================] - 2s 7ms/step - loss: 0.1014 - accuracy: 0.9702
Epoch 7/10
313/313 [==============================] - 2s 5ms/step - loss: 0.1089 - accuracy: 0.9681
Epoch 8/10
313/313 [==============================] - 2s 5ms/step - loss: 0.1025 - accuracy: 0.9699
Epoch 9/10
313/313 [==============================] - 2s 5ms/step - loss: 0.1005 - accuracy: 0.9687
Epoch 10/10
313/313 [==============================] - 2s 5ms/step - loss: 0.0844 - accuracy: 0.9736
313/313 [==============================] - 1s 4ms/step - loss: 8.8641 - accuracy: 0.2325
Test Accuracy: 0.23250000178813934
Epoch 1/10
313/313 [==============================] - 2s 7ms/step - loss: 3.4781 - accuracy: 0.2101
Epoch 2/10
313/313 [==============================] - 2s 5ms/step - loss: 2.4010 - accuracy: 0.3938
Epoch 3/10
313/313 [==============================] - 2s 5ms/step - loss: 1.4167 - accuracy: 0.6259
Epoch 4/10
313/313 [==============================] - 2s 5ms/step - loss: 0.4831 - accuracy: 0.8679
Epoch 5/10
313/313 [==============================] - 2s 5ms/step - loss: 0.1090 - accuracy: 0.9735
Epoch 6/10
313/313 [==============================] - 2s 5ms/step - loss: 0.0354 - accuracy: 0.9921
Epoch 7/10
313/313 [==============================] - 2s 5ms/step - loss: 0.0202 - accuracy: 0.9954
Epoch 8/10
313/313 [==============================] - 3s 10ms/step - loss: 0.0577 - accuracy: 0.9831
Epoch 9/10
313/313 [==============================] - 2s 5ms/step - loss: 0.1323 - accuracy: 0.9591
Epoch 10/10
313/313 [==============================] - 2s 5ms/step - loss: 0.1052 - accuracy: 0.9687
313/313 [==============================] - 1s 3ms/step - loss: 7.8948 - accuracy: 0.2324
Test Accuracy: 0.23240000009536743
Epoch 1/10
313/313 [==============================] - 2s 5ms/step - loss: 3.4269 - accuracy: 0.2163
Epoch 2/10
313/313 [==============================] - 2s 5ms/step - loss: 2.2909 - accuracy: 0.4201
Epoch 3/10
313/313 [==============================] - 2s 6ms/step - loss: 1.2043 - accuracy: 0.6809
Epoch 4/10
313/313 [==============================] - 2s 7ms/step - loss: 0.3138 - accuracy: 0.9158
Epoch 5/10
313/313 [==============================] - 2s 5ms/step - loss: 0.0546 - accuracy: 0.9876
Epoch 6/10
313/313 [==============================] - 2s 5ms/step - loss: 0.0226 - accuracy: 0.9954
Epoch 7/10
313/313 [==============================] - 2s 5ms/step - loss: 0.0179 - accuracy: 0.9973
Epoch 8/10
313/313 [==============================] - 2s 5ms/step - loss: 0.0071 - accuracy: 0.9986
Epoch 9/10
313/313 [==============================] - 2s 5ms/step - loss: 0.0020 - accuracy: 0.9998
Epoch 10/10
313/313 [==============================] - 2s 7ms/step - loss: 3.7322e-04 - accuracy: 1.0000
313/313 [==============================] - 2s 5ms/step - loss: 8.2985 - accuracy: 0.2678
Test Accuracy: 0.2678000032901764
Epoch 1/10
313/313 [==============================] - 2s 6ms/step - loss: 3.4050 - accuracy: 0.2136
Epoch 2/10
313/313 [==============================] - 2s 5ms/step - loss: 2.1626 - accuracy: 0.4479
Epoch 3/10
313/313 [==============================] - 2s 5ms/step - loss: 0.9867 - accuracy: 0.7332
Epoch 4/10
313/313 [==============================] - 2s 5ms/step - loss: 0.2126 - accuracy: 0.9432
Epoch 5/10
313/313 [==============================] - 2s 5ms/step - loss: 0.0300 - accuracy: 0.9945
Epoch 6/10
313/313 [==============================] - 2s 5ms/step - loss: 0.0102 - accuracy: 0.9984
Epoch 7/10
313/313 [==============================] - 2s 6ms/step - loss: 0.0224 - accuracy: 0.9953
Epoch 8/10
313/313 [==============================] - 2s 6ms/step - loss: 0.0206 - accuracy: 0.9953
Epoch 9/10
313/313 [==============================] - 2s 5ms/step - loss: 0.0087 - accuracy: 0.9979
Epoch 10/10
313/313 [==============================] - 2s 5ms/step - loss: 0.0113 - accuracy: 0.9976
313/313 [==============================] - 1s 4ms/step - loss: 8.1687 - accuracy: 0.2612
Test Accuracy: 0.2612000107765198

#### Batches 4

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar100
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam

# Load the CIFAR-100 dataset
(x_train, y_train), (x_test, y_test) = cifar100.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 0.1  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = x_train + tf.random.normal(shape=x_train.shape, mean=0.0, stddev=corruption_level, dtype=tf.float32)
corrupted_data = tf.clip_by_value(corrupted_data, 0.0, 1.0)

# Convert the labels to one-hot encoding
num_classes = 100
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 10 batches
n_batches = 4
batch_size = x_train.shape[0] // n_batches

# Define the model architecture
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)))
model.add(Conv2D(32, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch separately
for i in range(n_batches):
    start_index = i * batch_size
    end_index = (i + 1) * batch_size
    x_batch = corrupted_data[start_index:end_index]
    y_batch = y_train[start_index:end_index]

    # Train the model on the current batch
    model.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)

Epoch 1/10
391/391 [==============================] - 14s 10ms/step - loss: 4.3097 - accuracy: 0.0416
Epoch 2/10
391/391 [==============================] - 4s 10ms/step - loss: 3.7274 - accuracy: 0.1269
Epoch 3/10
391/391 [==============================] - 4s 9ms/step - loss: 3.2420 - accuracy: 0.2102
Epoch 4/10
391/391 [==============================] - 3s 8ms/step - loss: 2.7270 - accuracy: 0.3155
Epoch 5/10
391/391 [==============================] - 3s 9ms/step - loss: 2.1621 - accuracy: 0.4282
Epoch 6/10
391/391 [==============================] - 3s 9ms/step - loss: 1.4881 - accuracy: 0.5911
Epoch 7/10
391/391 [==============================] - 3s 7ms/step - loss: 0.8467 - accuracy: 0.7556
Epoch 8/10
391/391 [==============================] - 3s 7ms/step - loss: 0.4323 - accuracy: 0.8720
Epoch 9/10
391/391 [==============================] - 2s 5ms/step - loss: 0.2835 - accuracy: 0.9157
Epoch 10/10
391/391 [==============================] - 3s 7ms/step - loss: 0.2051 - accuracy: 0.9388
313/313 [==============================] - 3s 7ms/step - loss: 8.0369 - accuracy: 0.1970
Test Accuracy: 0.19699999690055847
Epoch 1/10
391/391 [==============================] - 3s 9ms/step - loss: 3.4161 - accuracy: 0.2133
Epoch 2/10
391/391 [==============================] - 4s 11ms/step - loss: 2.5978 - accuracy: 0.3523
Epoch 3/10
391/391 [==============================] - 3s 8ms/step - loss: 1.8387 - accuracy: 0.5218
Epoch 4/10
391/391 [==============================] - 3s 8ms/step - loss: 0.9108 - accuracy: 0.7532
Epoch 5/10
391/391 [==============================] - 2s 5ms/step - loss: 0.2984 - accuracy: 0.9176
Epoch 6/10
391/391 [==============================] - 2s 6ms/step - loss: 0.1203 - accuracy: 0.9668
Epoch 7/10
391/391 [==============================] - 3s 6ms/step - loss: 0.0944 - accuracy: 0.9746
Epoch 8/10
391/391 [==============================] - 2s 5ms/step - loss: 0.1149 - accuracy: 0.9658
Epoch 9/10
391/391 [==============================] - 2s 5ms/step - loss: 0.1229 - accuracy: 0.9630
Epoch 10/10
391/391 [==============================] - 2s 5ms/step - loss: 0.1003 - accuracy: 0.9700
313/313 [==============================] - 1s 4ms/step - loss: 8.3391 - accuracy: 0.2341
Test Accuracy: 0.23409999907016754
Epoch 1/10
391/391 [==============================] - 3s 7ms/step - loss: 3.3431 - accuracy: 0.2297
Epoch 2/10
391/391 [==============================] - 2s 5ms/step - loss: 2.3503 - accuracy: 0.4049
Epoch 3/10
391/391 [==============================] - 2s 5ms/step - loss: 1.4404 - accuracy: 0.6159
Epoch 4/10
391/391 [==============================] - 2s 5ms/step - loss: 0.5192 - accuracy: 0.8593
Epoch 5/10
391/391 [==============================] - 2s 5ms/step - loss: 0.1135 - accuracy: 0.9714
Epoch 6/10
391/391 [==============================] - 2s 6ms/step - loss: 0.0415 - accuracy: 0.9898
Epoch 7/10
391/391 [==============================] - 2s 6ms/step - loss: 0.0404 - accuracy: 0.9902
Epoch 8/10
391/391 [==============================] - 2s 5ms/step - loss: 0.0592 - accuracy: 0.9831
Epoch 9/10
391/391 [==============================] - 2s 5ms/step - loss: 0.1147 - accuracy: 0.9654
Epoch 10/10
391/391 [==============================] - 2s 5ms/step - loss: 0.1016 - accuracy: 0.9689
313/313 [==============================] - 1s 3ms/step - loss: 8.1033 - accuracy: 0.2383
Test Accuracy: 0.23829999566078186
Epoch 1/10
391/391 [==============================] - 3s 7ms/step - loss: 3.4064 - accuracy: 0.2192
Epoch 2/10
391/391 [==============================] - 2s 6ms/step - loss: 2.3189 - accuracy: 0.4103
Epoch 3/10
391/391 [==============================] - 2s 5ms/step - loss: 1.2694 - accuracy: 0.6606
Epoch 4/10
391/391 [==============================] - 2s 5ms/step - loss: 0.3545 - accuracy: 0.9061
Epoch 5/10
391/391 [==============================] - 2s 6ms/step - loss: 0.0576 - accuracy: 0.9885
Epoch 6/10
391/391 [==============================] - 2s 6ms/step - loss: 0.0209 - accuracy: 0.9952
Epoch 7/10
391/391 [==============================] - 3s 7ms/step - loss: 0.0074 - accuracy: 0.9983
Epoch 8/10
391/391 [==============================] - 2s 5ms/step - loss: 0.0197 - accuracy: 0.9953
Epoch 9/10
391/391 [==============================] - 2s 5ms/step - loss: 0.1168 - accuracy: 0.9655
Epoch 10/10
391/391 [==============================] - 2s 5ms/step - loss: 0.1231 - accuracy: 0.9642
313/313 [==============================] - 1s 4ms/step - loss: 7.4714 - accuracy: 0.2451
Test Accuracy: 0.2451000064611435

#### Batches 2

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar100
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam

# Load the CIFAR-100 dataset
(x_train, y_train), (x_test, y_test) = cifar100.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 0.1  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = x_train + tf.random.normal(shape=x_train.shape, mean=0.0, stddev=corruption_level, dtype=tf.float32)
corrupted_data = tf.clip_by_value(corrupted_data, 0.0, 1.0)

# Convert the labels to one-hot encoding
num_classes = 100
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 10 batches
n_batches = 2
batch_size = x_train.shape[0] // n_batches

# Define the model architecture
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)))
model.add(Conv2D(32, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch separately
for i in range(n_batches):
    start_index = i * batch_size
    end_index = (i + 1) * batch_size
    x_batch = corrupted_data[start_index:end_index]
    y_batch = y_train[start_index:end_index]

    # Train the model on the current batch
    model.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)

Epoch 1/10
782/782 [==============================] - 12s 7ms/step - loss: 4.0332 - accuracy: 0.0825
Epoch 2/10
782/782 [==============================] - 4s 5ms/step - loss: 3.2602 - accuracy: 0.2115
Epoch 3/10
782/782 [==============================] - 5s 6ms/step - loss: 2.7807 - accuracy: 0.3068
Epoch 4/10
782/782 [==============================] - 5s 7ms/step - loss: 2.3196 - accuracy: 0.3985
Epoch 5/10
782/782 [==============================] - 4s 5ms/step - loss: 1.8203 - accuracy: 0.5122
Epoch 6/10
782/782 [==============================] - 4s 5ms/step - loss: 1.2889 - accuracy: 0.6404
Epoch 7/10
782/782 [==============================] - 5s 6ms/step - loss: 0.8160 - accuracy: 0.7631
Epoch 8/10
782/782 [==============================] - 4s 5ms/step - loss: 0.4842 - accuracy: 0.8562
Epoch 9/10
782/782 [==============================] - 4s 5ms/step - loss: 0.3423 - accuracy: 0.8944
Epoch 10/10
782/782 [==============================] - 5s 6ms/step - loss: 0.2636 - accuracy: 0.9159
313/313 [==============================] - 1s 3ms/step - loss: 7.0169 - accuracy: 0.2535
Test Accuracy: 0.2535000145435333
Epoch 1/10
782/782 [==============================] - 4s 5ms/step - loss: 3.0683 - accuracy: 0.2736
Epoch 2/10
782/782 [==============================] - 5s 6ms/step - loss: 2.4138 - accuracy: 0.3888
Epoch 3/10
782/782 [==============================] - 4s 5ms/step - loss: 1.8868 - accuracy: 0.5076
Epoch 4/10
782/782 [==============================] - 4s 5ms/step - loss: 1.2220 - accuracy: 0.6678
Epoch 5/10
782/782 [==============================] - 5s 6ms/step - loss: 0.6120 - accuracy: 0.8240
Epoch 6/10
782/782 [==============================] - 5s 6ms/step - loss: 0.3009 - accuracy: 0.9098
Epoch 7/10
782/782 [==============================] - 4s 5ms/step - loss: 0.1980 - accuracy: 0.9398
Epoch 8/10
782/782 [==============================] - 5s 6ms/step - loss: 0.1787 - accuracy: 0.9416
Epoch 9/10
782/782 [==============================] - 4s 5ms/step - loss: 0.1426 - accuracy: 0.9550
Epoch 10/10
782/782 [==============================] - 4s 5ms/step - loss: 0.1428 - accuracy: 0.9556
313/313 [==============================] - 1s 4ms/step - loss: 7.6319 - accuracy: 0.2751
Test Accuracy: 0.2750999927520752

#### Batches 1

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar100
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam

# Load the CIFAR-100 dataset
(x_train, y_train), (x_test, y_test) = cifar100.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 0.1  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = x_train + tf.random.normal(shape=x_train.shape, mean=0.0, stddev=corruption_level, dtype=tf.float32)
corrupted_data = tf.clip_by_value(corrupted_data, 0.0, 1.0)

# Convert the labels to one-hot encoding
num_classes = 100
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 10 batches
n_batches = 1
batch_size = x_train.shape[0] // n_batches

# Define the model architecture
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)))
model.add(Conv2D(32, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on each batch separately
for i in range(n_batches):
    start_index = i * batch_size
    end_index = (i + 1) * batch_size
    x_batch = corrupted_data[start_index:end_index]
    y_batch = y_train[start_index:end_index]

    # Train the model on the current batch
    model.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)

Epoch 1/10
1563/1563 [==============================] - 30s 12ms/step - loss: 3.5865 - accuracy: 0.1579
Epoch 2/10
1563/1563 [==============================] - 16s 10ms/step - loss: 2.7420 - accuracy: 0.3128
Epoch 3/10
1563/1563 [==============================] - 13s 8ms/step - loss: 2.2784 - accuracy: 0.4127
Epoch 4/10
1563/1563 [==============================] - 10s 6ms/step - loss: 1.8638 - accuracy: 0.5035
Epoch 5/10
1563/1563 [==============================] - 9s 6ms/step - loss: 1.4456 - accuracy: 0.6015
Epoch 6/10
1563/1563 [==============================] - 8s 5ms/step - loss: 1.0504 - accuracy: 0.7000
Epoch 7/10
1563/1563 [==============================] - 9s 6ms/step - loss: 0.7180 - accuracy: 0.7876
Epoch 8/10
1563/1563 [==============================] - 9s 6ms/step - loss: 0.5122 - accuracy: 0.8408
Epoch 9/10
1563/1563 [==============================] - 8s 5ms/step - loss: 0.3924 - accuracy: 0.8773
Epoch 10/10
1563/1563 [==============================] - 9s 6ms/step - loss: 0.3234 - accuracy: 0.8981
313/313 [==============================] - 1s 4ms/step - loss: 6.0262 - accuracy: 0.3242
Test Accuracy: 0.32420000433921814

## C3

### CIFAR10-C

#### Batches 1

In [ ]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras import layers
# Load the CIFAR-10 dataset
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 3  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = np.copy(x_train).astype('float64')
if corruption_name == "speckle_noise":
    noise = np.random.randn(*corrupted_data.shape) * corruption_level
    corrupted_data += noise
    corrupted_data = np.clip(corrupted_data, 0., 255.)
    corrupted_data = corrupted_data.astype('uint8')
num_classes=10
# Convert labels to one-hot vectors
y_train_onehot = keras.utils.to_categorical(y_train, num_classes=10)
y_test_onehot = keras.utils.to_categorical(y_test, num_classes=10)

# Define the CrlB regularizer
class CrlBRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Define the original CIFAR-10 model
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu'),
    layers.Dropout(0.25),
    Dense(num_classes, activation='softmax')
])

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the original model on Task A
model.fit(corrupted_data, y_train_onehot, batch_size=128, epochs=10, validation_data=(x_test, y_test_onehot))

# Save the weights of the original model for later use
prior_weights = model.get_weights()

# Compute the Fisher Information matrix
def compute_fisher(model, x, num_samples=30):
    fisher_matrix = []
    for i in range(len(model.trainable_weights)):
        fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

    for _ in range(num_samples):
        idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
        with tf.GradientTape() as tape:
            logits = model(x[idx:idx+1])
        gradients = tape.gradient(logits, model.trainable_weights)
        for i in range(len(fisher_matrix)):
            fisher_matrix[i] += tf.square(gradients[i])

    fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
    return fisher_matrix

fisher_matrix = compute_fisher(model, corrupted_data)

# Define the new model with CrlB regularization
model_CrlB = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3),
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
    Conv2D(32, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
    Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
    Dense(num_classes, activation='softmax', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
])

# Compile the model with CrlB regularization
model_CrlB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on Task B with CrlB regularization
history = model_CrlB.fit(corrupted_data, y_train_onehot, batch_size=128, epochs=10, validation_data=(x_test, y_test_onehot))
print(history)
# Evaluate the model on the test set
_, test_accuracy = model.evaluate(x_test, y_test_onehot, verbose=0)
print("Test Accuracy:", test_accuracy)

Epoch 1/10
391/391 [==============================] - 8s 15ms/step - loss: 2.7226 - accuracy: 0.3232 - val_loss: 1.3912 - val_accuracy: 0.4967
Epoch 2/10
391/391 [==============================] - 5s 13ms/step - loss: 1.3611 - accuracy: 0.5122 - val_loss: 1.1421 - val_accuracy: 0.5974
Epoch 3/10
391/391 [==============================] - 5s 14ms/step - loss: 1.1666 - accuracy: 0.5864 - val_loss: 1.0450 - val_accuracy: 0.6403
Epoch 4/10
391/391 [==============================] - 5s 13ms/step - loss: 1.0556 - accuracy: 0.6281 - val_loss: 0.9335 - val_accuracy: 0.6749
Epoch 5/10
391/391 [==============================] - 6s 14ms/step - loss: 0.9578 - accuracy: 0.6608 - val_loss: 0.8999 - val_accuracy: 0.6919
Epoch 6/10
391/391 [==============================] - 5s 13ms/step - loss: 0.8848 - accuracy: 0.6890 - val_loss: 0.8297 - val_accuracy: 0.7167
Epoch 7/10
391/391 [==============================] - 5s 13ms/step - loss: 0.8288 - accuracy: 0.7088 - val_loss: 0.8764 - val_accuracy: 0.6917
Epoch 8/10
391/391 [==============================] - 5s 14ms/step - loss: 0.7791 - accuracy: 0.7249 - val_loss: 0.8122 - val_accuracy: 0.7169
Epoch 9/10
391/391 [==============================] - 5s 13ms/step - loss: 0.7252 - accuracy: 0.7447 - val_loss: 0.7801 - val_accuracy: 0.7338
Epoch 10/10
391/391 [==============================] - 5s 14ms/step - loss: 0.6773 - accuracy: 0.7594 - val_loss: 0.7738 - val_accuracy: 0.7328
Epoch 1/10
391/391 [==============================] - 13s 20ms/step - loss: 2.9279 - accuracy: 0.2897 - val_loss: 1.4455 - val_accuracy: 0.4709
Epoch 2/10
391/391 [==============================] - 6s 16ms/step - loss: 1.3928 - accuracy: 0.4968 - val_loss: 1.2025 - val_accuracy: 0.5620
Epoch 3/10
391/391 [==============================] - 6s 16ms/step - loss: 1.1819 - accuracy: 0.5828 - val_loss: 1.1085 - val_accuracy: 0.6124
Epoch 4/10
391/391 [==============================] - 6s 16ms/step - loss: 1.0315 - accuracy: 0.6362 - val_loss: 0.9378 - val_accuracy: 0.6719
Epoch 5/10
391/391 [==============================] - 7s 18ms/step - loss: 0.9222 - accuracy: 0.6761 - val_loss: 0.9486 - val_accuracy: 0.6694
Epoch 6/10
391/391 [==============================] - 6s 16ms/step - loss: 0.8320 - accuracy: 0.7107 - val_loss: 0.8377 - val_accuracy: 0.7093
Epoch 7/10
391/391 [==============================] - 6s 17ms/step - loss: 0.7457 - accuracy: 0.7385 - val_loss: 0.8634 - val_accuracy: 0.7053
Epoch 8/10
391/391 [==============================] - 6s 16ms/step - loss: 0.6787 - accuracy: 0.7616 - val_loss: 0.7919 - val_accuracy: 0.7290
Epoch 9/10
391/391 [==============================] - 7s 18ms/step - loss: 0.6211 - accuracy: 0.7826 - val_loss: 0.8460 - val_accuracy: 0.7181
Epoch 10/10
391/391 [==============================] - 6s 16ms/step - loss: 0.5680 - accuracy: 0.8000 - val_loss: 0.7765 - val_accuracy: 0.7374
<keras.callbacks.History object at 0x7fe46198b250>
Test Accuracy: 0.7328000068664551

#### Batches 20

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers

# Load the CIFAR-100 dataset
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 0.1  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = x_train + tf.random.normal(shape=x_train.shape, mean=0.0, stddev=corruption_level, dtype=tf.float32)
corrupted_data = tf.clip_by_value(corrupted_data, 0.0, 1.0)

# Convert the labels to one-hot encoding
num_classes = 10
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 2 batches
n_batches = 20
batch_size = x_train.shape[0] // n_batches

# Define the CrlB regularizer
class CrlBRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Define the original CIFAR-10 model
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu'),
    layers.Dropout(0.25),
    Dense(num_classes, activation='softmax')
])

# Compile the model
# model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the original model on Task A
# model.fit(corrupted_data, y_train_onehot, batch_size=128, epochs=10, validation_data=(x_test, y_test_onehot))

# Train the model on each batch separately
for i in range(n_batches):
    start_index = i * batch_size
    end_index = (i + 1) * batch_size
    x_batch = corrupted_data[start_index:end_index]
    y_batch = y_train[start_index:end_index]
    model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    # Train the model on the current batch
    model.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    # _, test_accuracy = model.evaluate(x_test, y_test)
    # print("Test Accuracy:", test_accuracy)
# Save the weights of the original model for later use
    prior_weights = model.get_weights()

# Compute the Fisher Information matrix
    def compute_fisher(model, x, num_samples=30):
        fisher_matrix = []
        for i in range(len(model.trainable_weights)):
            fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

        for _ in range(num_samples):
            idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
            with tf.GradientTape() as tape:
                logits = model(x[idx:idx+1])
            gradients = tape.gradient(logits, model.trainable_weights)
            for i in range(len(fisher_matrix)):
                fisher_matrix[i] += tf.square(gradients[i])

        fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
        return fisher_matrix

    fisher_matrix = compute_fisher(model, corrupted_data)

# Define the new model with CrlB regularization
    model_CrlB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3),
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])

# Compile the model with CrlB regularization
    model_CrlB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on Task B with CrlB regularization
# history = model_CrlB.fit(corrupted_data, y_train_onehot, batch_size=128, epochs=10, validation_data=(x_test, y_test_onehot))
# print(history)
# Train the model on each batch separately
# for i in range(n_batches):
#     start_index = i * batch_size
#     end_index = (i + 1) * batch_size
#     x_batch = corrupted_data[start_index:end_index]
#     y_batch = y_train[start_index:end_index]

    # Train the model on the current batch
    model_CrlB.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)
# # Evaluate the model on the test set
# _, test_accuracy = model.evaluate(x_test, y_test_onehot, verbose=0)
# print("Test Accuracy:", test_accuracy)

Epoch 1/10
79/79 [==============================] - 9s 11ms/step - loss: 2.1424 - accuracy: 0.2064
Epoch 2/10
79/79 [==============================] - 1s 7ms/step - loss: 1.9303 - accuracy: 0.2800
Epoch 3/10
79/79 [==============================] - 1s 6ms/step - loss: 1.7390 - accuracy: 0.3564
Epoch 4/10
79/79 [==============================] - 1s 7ms/step - loss: 1.6283 - accuracy: 0.3992
Epoch 5/10
79/79 [==============================] - 1s 7ms/step - loss: 1.4865 - accuracy: 0.4588
Epoch 6/10
79/79 [==============================] - 1s 7ms/step - loss: 1.3311 - accuracy: 0.5136
Epoch 7/10
79/79 [==============================] - 1s 7ms/step - loss: 1.2191 - accuracy: 0.5588
Epoch 8/10
79/79 [==============================] - 1s 6ms/step - loss: 1.1528 - accuracy: 0.5836
Epoch 9/10
79/79 [==============================] - 0s 6ms/step - loss: 1.0179 - accuracy: 0.6416
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 0.8919 - accuracy: 0.6772
Epoch 1/10
79/79 [==============================] - 6s 10ms/step - loss: 2.1746 - accuracy: 0.1888
Epoch 2/10
79/79 [==============================] - 1s 8ms/step - loss: 1.8712 - accuracy: 0.3088
Epoch 3/10
79/79 [==============================] - 1s 8ms/step - loss: 1.6764 - accuracy: 0.3804
Epoch 4/10
79/79 [==============================] - 1s 8ms/step - loss: 1.5807 - accuracy: 0.4236
Epoch 5/10
79/79 [==============================] - 1s 8ms/step - loss: 1.4817 - accuracy: 0.4616
Epoch 6/10
79/79 [==============================] - 1s 8ms/step - loss: 1.3514 - accuracy: 0.5124
Epoch 7/10
79/79 [==============================] - 1s 8ms/step - loss: 1.2175 - accuracy: 0.5640
Epoch 8/10
79/79 [==============================] - 1s 7ms/step - loss: 1.0967 - accuracy: 0.5992
Epoch 9/10
79/79 [==============================] - 1s 8ms/step - loss: 0.9762 - accuracy: 0.6480
Epoch 10/10
79/79 [==============================] - 1s 8ms/step - loss: 0.8032 - accuracy: 0.7184
313/313 [==============================] - 1s 3ms/step - loss: 1.7018 - accuracy: 0.4649
Test Accuracy: 0.4648999869823456
Epoch 1/10
79/79 [==============================] - 3s 8ms/step - loss: 1.4996 - accuracy: 0.4588
Epoch 2/10
79/79 [==============================] - 1s 7ms/step - loss: 1.3098 - accuracy: 0.5280
Epoch 3/10
79/79 [==============================] - 1s 7ms/step - loss: 1.1612 - accuracy: 0.5760
Epoch 4/10
79/79 [==============================] - 1s 7ms/step - loss: 1.0053 - accuracy: 0.6344
Epoch 5/10
79/79 [==============================] - 0s 6ms/step - loss: 0.8217 - accuracy: 0.7088
Epoch 6/10
79/79 [==============================] - 0s 6ms/step - loss: 0.6737 - accuracy: 0.7592
Epoch 7/10
79/79 [==============================] - 0s 5ms/step - loss: 0.5134 - accuracy: 0.8112
Epoch 8/10
79/79 [==============================] - 0s 6ms/step - loss: 0.4428 - accuracy: 0.8444
Epoch 9/10
79/79 [==============================] - 0s 5ms/step - loss: 0.3450 - accuracy: 0.8792
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 0.2982 - accuracy: 0.9004
Epoch 1/10
79/79 [==============================] - 5s 8ms/step - loss: 2.1696 - accuracy: 0.1904
Epoch 2/10
79/79 [==============================] - 1s 7ms/step - loss: 1.9577 - accuracy: 0.2824
Epoch 3/10
79/79 [==============================] - 1s 8ms/step - loss: 1.8248 - accuracy: 0.3316
Epoch 4/10
79/79 [==============================] - 1s 9ms/step - loss: 1.6360 - accuracy: 0.3992
Epoch 5/10
79/79 [==============================] - 1s 9ms/step - loss: 1.5418 - accuracy: 0.4304
Epoch 6/10
79/79 [==============================] - 1s 9ms/step - loss: 1.3706 - accuracy: 0.4932
Epoch 7/10
79/79 [==============================] - 1s 9ms/step - loss: 1.2274 - accuracy: 0.5520
Epoch 8/10
79/79 [==============================] - 1s 8ms/step - loss: 1.0348 - accuracy: 0.6200
Epoch 9/10
79/79 [==============================] - 1s 8ms/step - loss: 0.8291 - accuracy: 0.7116
Epoch 10/10
79/79 [==============================] - 1s 8ms/step - loss: 0.6838 - accuracy: 0.7524
313/313 [==============================] - 1s 3ms/step - loss: 2.0535 - accuracy: 0.5015
Test Accuracy: 0.5015000104904175
Epoch 1/10
79/79 [==============================] - 3s 7ms/step - loss: 1.5458 - accuracy: 0.4824
Epoch 2/10
79/79 [==============================] - 0s 5ms/step - loss: 1.2097 - accuracy: 0.5748
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 1.0136 - accuracy: 0.6296
Epoch 4/10
79/79 [==============================] - 0s 6ms/step - loss: 0.8039 - accuracy: 0.7168
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 0.6161 - accuracy: 0.7804
Epoch 6/10
79/79 [==============================] - 0s 6ms/step - loss: 0.4785 - accuracy: 0.8260
Epoch 7/10
79/79 [==============================] - 0s 5ms/step - loss: 0.3633 - accuracy: 0.8788
Epoch 8/10
79/79 [==============================] - 0s 5ms/step - loss: 0.2897 - accuracy: 0.9032
Epoch 9/10
79/79 [==============================] - 0s 5ms/step - loss: 0.2210 - accuracy: 0.9228
Epoch 10/10
79/79 [==============================] - 0s 6ms/step - loss: 0.2079 - accuracy: 0.9256
Epoch 1/10
79/79 [==============================] - 6s 8ms/step - loss: 2.1346 - accuracy: 0.2088
Epoch 2/10
79/79 [==============================] - 1s 7ms/step - loss: 1.9146 - accuracy: 0.3036
Epoch 3/10
79/79 [==============================] - 1s 7ms/step - loss: 1.7633 - accuracy: 0.3516
Epoch 4/10
79/79 [==============================] - 1s 7ms/step - loss: 1.6182 - accuracy: 0.3992
Epoch 5/10
79/79 [==============================] - 1s 7ms/step - loss: 1.4783 - accuracy: 0.4552
Epoch 6/10
79/79 [==============================] - 1s 7ms/step - loss: 1.3403 - accuracy: 0.5148
Epoch 7/10
79/79 [==============================] - 1s 7ms/step - loss: 1.2212 - accuracy: 0.5564
Epoch 8/10
79/79 [==============================] - 1s 7ms/step - loss: 1.0420 - accuracy: 0.6240
Epoch 9/10
79/79 [==============================] - 1s 8ms/step - loss: 0.8887 - accuracy: 0.6748
Epoch 10/10
79/79 [==============================] - 1s 7ms/step - loss: 0.7683 - accuracy: 0.7220
313/313 [==============================] - 1s 4ms/step - loss: 2.0358 - accuracy: 0.5436
Test Accuracy: 0.5436000227928162
Epoch 1/10
79/79 [==============================] - 3s 7ms/step - loss: 1.5830 - accuracy: 0.4780
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 1.1528 - accuracy: 0.5948
Epoch 3/10
79/79 [==============================] - 0s 6ms/step - loss: 0.8950 - accuracy: 0.6784
Epoch 4/10
79/79 [==============================] - 0s 5ms/step - loss: 0.7276 - accuracy: 0.7468
Epoch 5/10
79/79 [==============================] - 0s 6ms/step - loss: 0.5311 - accuracy: 0.8176
Epoch 6/10
79/79 [==============================] - 0s 5ms/step - loss: 0.3823 - accuracy: 0.8588
Epoch 7/10
79/79 [==============================] - 0s 5ms/step - loss: 0.3289 - accuracy: 0.8816
Epoch 8/10
79/79 [==============================] - 0s 6ms/step - loss: 0.2426 - accuracy: 0.9192
Epoch 9/10
79/79 [==============================] - 0s 6ms/step - loss: 0.1577 - accuracy: 0.9444
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 0.1568 - accuracy: 0.9504
Epoch 1/10
79/79 [==============================] - 7s 8ms/step - loss: 2.1790 - accuracy: 0.1800
Epoch 2/10
79/79 [==============================] - 1s 8ms/step - loss: 1.8928 - accuracy: 0.2972
Epoch 3/10
79/79 [==============================] - 1s 7ms/step - loss: 1.7123 - accuracy: 0.3732
Epoch 4/10
79/79 [==============================] - 1s 8ms/step - loss: 1.6146 - accuracy: 0.4088
Epoch 5/10
79/79 [==============================] - 1s 7ms/step - loss: 1.4357 - accuracy: 0.4804
Epoch 6/10
79/79 [==============================] - 1s 8ms/step - loss: 1.3346 - accuracy: 0.5104
Epoch 7/10
79/79 [==============================] - 1s 11ms/step - loss: 1.1667 - accuracy: 0.5796
Epoch 8/10
79/79 [==============================] - 1s 8ms/step - loss: 1.0018 - accuracy: 0.6380
Epoch 9/10
79/79 [==============================] - 1s 7ms/step - loss: 0.7750 - accuracy: 0.7264
Epoch 10/10
79/79 [==============================] - 1s 7ms/step - loss: 0.6440 - accuracy: 0.7748
313/313 [==============================] - 1s 3ms/step - loss: 1.9331 - accuracy: 0.5570
Test Accuracy: 0.5569999814033508
Epoch 1/10
79/79 [==============================] - 3s 7ms/step - loss: 1.6131 - accuracy: 0.4648
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 1.1429 - accuracy: 0.6100
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 0.9142 - accuracy: 0.6812
Epoch 4/10
79/79 [==============================] - 0s 5ms/step - loss: 0.7287 - accuracy: 0.7548
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 0.5705 - accuracy: 0.8056
Epoch 6/10
79/79 [==============================] - 0s 6ms/step - loss: 0.3952 - accuracy: 0.8636
Epoch 7/10
79/79 [==============================] - 0s 6ms/step - loss: 0.3341 - accuracy: 0.8820
Epoch 8/10
79/79 [==============================] - 0s 6ms/step - loss: 0.2076 - accuracy: 0.9352
Epoch 9/10
79/79 [==============================] - 0s 6ms/step - loss: 0.2112 - accuracy: 0.9300
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 0.1600 - accuracy: 0.9436
Epoch 1/10
79/79 [==============================] - 5s 10ms/step - loss: 2.1930 - accuracy: 0.1800
Epoch 2/10
79/79 [==============================] - 1s 9ms/step - loss: 1.9689 - accuracy: 0.2848
Epoch 3/10
79/79 [==============================] - 1s 9ms/step - loss: 1.7591 - accuracy: 0.3628
Epoch 4/10
79/79 [==============================] - 1s 7ms/step - loss: 1.5961 - accuracy: 0.4232
Epoch 5/10
79/79 [==============================] - 1s 8ms/step - loss: 1.4945 - accuracy: 0.4616
Epoch 6/10
79/79 [==============================] - 1s 8ms/step - loss: 1.3590 - accuracy: 0.4984
Epoch 7/10
79/79 [==============================] - 1s 8ms/step - loss: 1.2637 - accuracy: 0.5368
Epoch 8/10
79/79 [==============================] - 1s 8ms/step - loss: 1.1094 - accuracy: 0.5952
Epoch 9/10
79/79 [==============================] - 1s 8ms/step - loss: 0.9601 - accuracy: 0.6612
Epoch 10/10
79/79 [==============================] - 1s 8ms/step - loss: 0.7957 - accuracy: 0.7188
313/313 [==============================] - 1s 3ms/step - loss: 1.8845 - accuracy: 0.5699
Test Accuracy: 0.5698999762535095
Epoch 1/10
79/79 [==============================] - 3s 7ms/step - loss: 1.6103 - accuracy: 0.4720
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 1.1714 - accuracy: 0.5832
Epoch 3/10
79/79 [==============================] - 0s 6ms/step - loss: 0.9222 - accuracy: 0.6800
Epoch 4/10
79/79 [==============================] - 0s 5ms/step - loss: 0.6926 - accuracy: 0.7552
Epoch 5/10
79/79 [==============================] - 1s 6ms/step - loss: 0.5209 - accuracy: 0.8216
Epoch 6/10
79/79 [==============================] - 1s 7ms/step - loss: 0.3781 - accuracy: 0.8768
Epoch 7/10
79/79 [==============================] - 1s 7ms/step - loss: 0.2761 - accuracy: 0.9088
Epoch 8/10
79/79 [==============================] - 1s 7ms/step - loss: 0.2584 - accuracy: 0.9052
Epoch 9/10
79/79 [==============================] - 1s 7ms/step - loss: 0.1783 - accuracy: 0.9392
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 0.1389 - accuracy: 0.9496
Epoch 1/10
79/79 [==============================] - 5s 8ms/step - loss: 2.2003 - accuracy: 0.1748
Epoch 2/10
79/79 [==============================] - 1s 8ms/step - loss: 1.9061 - accuracy: 0.3104
Epoch 3/10
79/79 [==============================] - 1s 8ms/step - loss: 1.7708 - accuracy: 0.3552
Epoch 4/10
79/79 [==============================] - 1s 7ms/step - loss: 1.6368 - accuracy: 0.4092
Epoch 5/10
79/79 [==============================] - 1s 8ms/step - loss: 1.5472 - accuracy: 0.4388
Epoch 6/10
79/79 [==============================] - 1s 8ms/step - loss: 1.4273 - accuracy: 0.4908
Epoch 7/10
79/79 [==============================] - 1s 9ms/step - loss: 1.3082 - accuracy: 0.5268
Epoch 8/10
79/79 [==============================] - 1s 10ms/step - loss: 1.1605 - accuracy: 0.5728
Epoch 9/10
79/79 [==============================] - 1s 10ms/step - loss: 1.0407 - accuracy: 0.6332
Epoch 10/10
79/79 [==============================] - 1s 8ms/step - loss: 0.8403 - accuracy: 0.6892
313/313 [==============================] - 1s 3ms/step - loss: 1.9304 - accuracy: 0.5781
Test Accuracy: 0.5781000256538391
Epoch 1/10
79/79 [==============================] - 3s 7ms/step - loss: 1.5810 - accuracy: 0.4992
Epoch 2/10
79/79 [==============================] - 0s 5ms/step - loss: 1.1218 - accuracy: 0.6124
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 0.8574 - accuracy: 0.6996
Epoch 4/10
79/79 [==============================] - 0s 6ms/step - loss: 0.6800 - accuracy: 0.7664
Epoch 5/10
79/79 [==============================] - 0s 6ms/step - loss: 0.4954 - accuracy: 0.8280
Epoch 6/10
79/79 [==============================] - 0s 5ms/step - loss: 0.3791 - accuracy: 0.8632
Epoch 7/10
79/79 [==============================] - 0s 5ms/step - loss: 0.2773 - accuracy: 0.8992
Epoch 8/10
79/79 [==============================] - 0s 6ms/step - loss: 0.2472 - accuracy: 0.9164
Epoch 9/10
79/79 [==============================] - 0s 5ms/step - loss: 0.1661 - accuracy: 0.9444
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 0.1877 - accuracy: 0.9404
Epoch 1/10
79/79 [==============================] - 6s 9ms/step - loss: 2.1877 - accuracy: 0.1676
Epoch 2/10
79/79 [==============================] - 1s 8ms/step - loss: 1.9194 - accuracy: 0.2860
Epoch 3/10
79/79 [==============================] - 1s 8ms/step - loss: 1.7461 - accuracy: 0.3796
Epoch 4/10
79/79 [==============================] - 1s 8ms/step - loss: 1.6260 - accuracy: 0.4212
Epoch 5/10
79/79 [==============================] - 1s 8ms/step - loss: 1.4677 - accuracy: 0.4728
Epoch 6/10
79/79 [==============================] - 1s 8ms/step - loss: 1.3189 - accuracy: 0.5264
Epoch 7/10
79/79 [==============================] - 1s 7ms/step - loss: 1.1928 - accuracy: 0.5740
Epoch 8/10
79/79 [==============================] - 1s 8ms/step - loss: 1.0121 - accuracy: 0.6368
Epoch 9/10
79/79 [==============================] - 1s 8ms/step - loss: 0.8648 - accuracy: 0.6856
Epoch 10/10
79/79 [==============================] - 1s 8ms/step - loss: 0.7083 - accuracy: 0.7448
313/313 [==============================] - 1s 3ms/step - loss: 1.7416 - accuracy: 0.5878
Test Accuracy: 0.5878000259399414
Epoch 1/10
79/79 [==============================] - 3s 7ms/step - loss: 1.5669 - accuracy: 0.4984
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 1.1107 - accuracy: 0.6168
Epoch 3/10
79/79 [==============================] - 0s 6ms/step - loss: 0.8650 - accuracy: 0.6952
Epoch 4/10
79/79 [==============================] - 0s 5ms/step - loss: 0.6845 - accuracy: 0.7608
Epoch 5/10
79/79 [==============================] - 0s 6ms/step - loss: 0.5127 - accuracy: 0.8180
Epoch 6/10
79/79 [==============================] - 0s 5ms/step - loss: 0.3713 - accuracy: 0.8748
Epoch 7/10
79/79 [==============================] - 0s 6ms/step - loss: 0.2850 - accuracy: 0.9068
Epoch 8/10
79/79 [==============================] - 0s 6ms/step - loss: 0.2035 - accuracy: 0.9344
Epoch 9/10
79/79 [==============================] - 0s 5ms/step - loss: 0.1498 - accuracy: 0.9500
Epoch 10/10
79/79 [==============================] - 0s 6ms/step - loss: 0.1241 - accuracy: 0.9604
Epoch 1/10
79/79 [==============================] - 5s 9ms/step - loss: 2.2554 - accuracy: 0.1388
Epoch 2/10
79/79 [==============================] - 1s 8ms/step - loss: 1.9643 - accuracy: 0.2796
Epoch 3/10
79/79 [==============================] - 1s 8ms/step - loss: 1.7608 - accuracy: 0.3696
Epoch 4/10
79/79 [==============================] - 1s 8ms/step - loss: 1.6532 - accuracy: 0.4156
Epoch 5/10
79/79 [==============================] - 1s 8ms/step - loss: 1.5255 - accuracy: 0.4612
Epoch 6/10
79/79 [==============================] - 1s 10ms/step - loss: 1.4013 - accuracy: 0.5008
Epoch 7/10
79/79 [==============================] - 1s 9ms/step - loss: 1.2963 - accuracy: 0.5468
Epoch 8/10
79/79 [==============================] - 1s 9ms/step - loss: 1.1404 - accuracy: 0.5940
Epoch 9/10
79/79 [==============================] - 1s 8ms/step - loss: 1.0038 - accuracy: 0.6476
Epoch 10/10
79/79 [==============================] - 1s 8ms/step - loss: 0.8216 - accuracy: 0.7160
313/313 [==============================] - 1s 3ms/step - loss: 1.8211 - accuracy: 0.6072
Test Accuracy: 0.607200026512146
Epoch 1/10
79/79 [==============================] - 3s 7ms/step - loss: 1.5098 - accuracy: 0.5112
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 1.0903 - accuracy: 0.6184
Epoch 3/10
79/79 [==============================] - 0s 6ms/step - loss: 0.8433 - accuracy: 0.6984
Epoch 4/10
79/79 [==============================] - 0s 6ms/step - loss: 0.6426 - accuracy: 0.7740
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 0.4716 - accuracy: 0.8316
Epoch 6/10
79/79 [==============================] - 0s 6ms/step - loss: 0.3461 - accuracy: 0.8772
Epoch 7/10
79/79 [==============================] - 0s 6ms/step - loss: 0.2851 - accuracy: 0.8980
Epoch 8/10
79/79 [==============================] - 0s 6ms/step - loss: 0.2327 - accuracy: 0.9212
Epoch 9/10
79/79 [==============================] - 0s 6ms/step - loss: 0.1894 - accuracy: 0.9328
Epoch 10/10
79/79 [==============================] - 0s 6ms/step - loss: 0.1750 - accuracy: 0.9376
Epoch 1/10
79/79 [==============================] - 6s 9ms/step - loss: 2.2464 - accuracy: 0.1492
Epoch 2/10
79/79 [==============================] - 1s 8ms/step - loss: 1.9344 - accuracy: 0.2780
Epoch 3/10
79/79 [==============================] - 1s 8ms/step - loss: 1.7152 - accuracy: 0.3880
Epoch 4/10
79/79 [==============================] - 1s 9ms/step - loss: 1.6012 - accuracy: 0.4320
Epoch 5/10
79/79 [==============================] - 1s 9ms/step - loss: 1.4546 - accuracy: 0.4664
Epoch 6/10
79/79 [==============================] - 1s 9ms/step - loss: 1.3583 - accuracy: 0.5116
Epoch 7/10
79/79 [==============================] - 1s 8ms/step - loss: 1.2107 - accuracy: 0.5680
Epoch 8/10
79/79 [==============================] - 1s 7ms/step - loss: 1.1056 - accuracy: 0.5988
Epoch 9/10
79/79 [==============================] - 1s 8ms/step - loss: 0.9283 - accuracy: 0.6648
Epoch 10/10
79/79 [==============================] - 1s 8ms/step - loss: 0.7443 - accuracy: 0.7424
313/313 [==============================] - 1s 3ms/step - loss: 1.5644 - accuracy: 0.6109
Test Accuracy: 0.6108999848365784
Epoch 1/10
79/79 [==============================] - 3s 7ms/step - loss: 1.4866 - accuracy: 0.5132
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 1.0620 - accuracy: 0.6280
Epoch 3/10
79/79 [==============================] - 0s 6ms/step - loss: 0.8281 - accuracy: 0.7168
Epoch 4/10
79/79 [==============================] - 0s 6ms/step - loss: 0.6378 - accuracy: 0.7860
Epoch 5/10
79/79 [==============================] - 0s 6ms/step - loss: 0.4684 - accuracy: 0.8392
Epoch 6/10
79/79 [==============================] - 0s 6ms/step - loss: 0.3929 - accuracy: 0.8648
Epoch 7/10
79/79 [==============================] - 0s 5ms/step - loss: 0.2748 - accuracy: 0.9032
Epoch 8/10
79/79 [==============================] - 0s 6ms/step - loss: 0.2619 - accuracy: 0.9080
Epoch 9/10
79/79 [==============================] - 1s 6ms/step - loss: 0.1648 - accuracy: 0.9444
Epoch 10/10
79/79 [==============================] - 1s 7ms/step - loss: 0.1743 - accuracy: 0.9460
Epoch 1/10
79/79 [==============================] - 6s 9ms/step - loss: 2.1836 - accuracy: 0.1692
Epoch 2/10
79/79 [==============================] - 1s 8ms/step - loss: 1.9396 - accuracy: 0.3000
Epoch 3/10

#### Batches 10

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers

# Load the CIFAR-100 dataset
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 0.1  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = x_train + tf.random.normal(shape=x_train.shape, mean=0.0, stddev=corruption_level, dtype=tf.float32)
corrupted_data = tf.clip_by_value(corrupted_data, 0.0, 1.0)

# Convert the labels to one-hot encoding
num_classes = 10
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 2 batches
n_batches = 10
batch_size = x_train.shape[0] // n_batches

# Define the CrlB regularizer
class CrlBRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Define the original CIFAR-10 model
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu'),
    layers.Dropout(0.25),
    Dense(num_classes, activation='softmax')
])

# Compile the model
# model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the original model on Task A
# model.fit(corrupted_data, y_train_onehot, batch_size=128, epochs=10, validation_data=(x_test, y_test_onehot))

# Train the model on each batch separately
for i in range(n_batches):
    start_index = i * batch_size
    end_index = (i + 1) * batch_size
    x_batch = corrupted_data[start_index:end_index]
    y_batch = y_train[start_index:end_index]
    model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    # Train the model on the current batch
    model.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    # _, test_accuracy = model.evaluate(x_test, y_test)
    # print("Test Accuracy:", test_accuracy)
# Save the weights of the original model for later use
    prior_weights = model.get_weights()

# Compute the Fisher Information matrix
    def compute_fisher(model, x, num_samples=30):
        fisher_matrix = []
        for i in range(len(model.trainable_weights)):
            fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

        for _ in range(num_samples):
            idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
            with tf.GradientTape() as tape:
                logits = model(x[idx:idx+1])
            gradients = tape.gradient(logits, model.trainable_weights)
            for i in range(len(fisher_matrix)):
                fisher_matrix[i] += tf.square(gradients[i])

        fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
        return fisher_matrix

    fisher_matrix = compute_fisher(model, corrupted_data)

# Define the new model with CrlB regularization
    model_CrlB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3),
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])

# Compile the model with CrlB regularization
    model_CrlB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on Task B with CrlB regularization
# history = model_CrlB.fit(corrupted_data, y_train_onehot, batch_size=128, epochs=10, validation_data=(x_test, y_test_onehot))
# print(history)
# Train the model on each batch separately
# for i in range(n_batches):
#     start_index = i * batch_size
#     end_index = (i + 1) * batch_size
#     x_batch = corrupted_data[start_index:end_index]
#     y_batch = y_train[start_index:end_index]

    # Train the model on the current batch
    model_CrlB.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)
# # Evaluate the model on the test set
# _, test_accuracy = model.evaluate(x_test, y_test_onehot, verbose=0)
# print("Test Accuracy:", test_accuracy)

Epoch 1/10
157/157 [==============================] - 4s 9ms/step - loss: 2.0841 - accuracy: 0.2184
Epoch 2/10
157/157 [==============================] - 1s 6ms/step - loss: 1.7463 - accuracy: 0.3722
Epoch 3/10
157/157 [==============================] - 1s 5ms/step - loss: 1.5815 - accuracy: 0.4310
Epoch 4/10
157/157 [==============================] - 1s 6ms/step - loss: 1.4462 - accuracy: 0.4692
Epoch 5/10
157/157 [==============================] - 1s 5ms/step - loss: 1.3155 - accuracy: 0.5180
Epoch 6/10
157/157 [==============================] - 1s 7ms/step - loss: 1.1890 - accuracy: 0.5698
Epoch 7/10
157/157 [==============================] - 1s 7ms/step - loss: 1.0744 - accuracy: 0.6128
Epoch 8/10
157/157 [==============================] - 1s 6ms/step - loss: 0.9476 - accuracy: 0.6600
Epoch 9/10
157/157 [==============================] - 1s 6ms/step - loss: 0.7970 - accuracy: 0.7084
Epoch 10/10
157/157 [==============================] - 1s 6ms/step - loss: 0.6900 - accuracy: 0.7578
Epoch 1/10
157/157 [==============================] - 8s 13ms/step - loss: 2.0572 - accuracy: 0.2362
Epoch 2/10
157/157 [==============================] - 2s 15ms/step - loss: 1.7057 - accuracy: 0.3832
Epoch 3/10
157/157 [==============================] - 2s 12ms/step - loss: 1.5196 - accuracy: 0.4544
Epoch 4/10
157/157 [==============================] - 2s 15ms/step - loss: 1.3616 - accuracy: 0.5078
Epoch 5/10
157/157 [==============================] - 2s 14ms/step - loss: 1.2069 - accuracy: 0.5586
Epoch 6/10
157/157 [==============================] - 2s 12ms/step - loss: 1.0532 - accuracy: 0.6202
Epoch 7/10
157/157 [==============================] - 2s 12ms/step - loss: 0.9004 - accuracy: 0.6694
Epoch 8/10
157/157 [==============================] - 2s 10ms/step - loss: 0.7129 - accuracy: 0.7498
Epoch 9/10
157/157 [==============================] - 2s 13ms/step - loss: 0.5818 - accuracy: 0.7902
Epoch 10/10
157/157 [==============================] - 2s 15ms/step - loss: 0.4327 - accuracy: 0.8444
313/313 [==============================] - 2s 4ms/step - loss: 1.4985 - accuracy: 0.5272
Test Accuracy: 0.5271999835968018
Epoch 1/10
157/157 [==============================] - 5s 7ms/step - loss: 1.3984 - accuracy: 0.5072
Epoch 2/10
157/157 [==============================] - 1s 7ms/step - loss: 1.1557 - accuracy: 0.5816
Epoch 3/10
157/157 [==============================] - 1s 7ms/step - loss: 1.0086 - accuracy: 0.6366
Epoch 4/10
157/157 [==============================] - 1s 7ms/step - loss: 0.8582 - accuracy: 0.6904
Epoch 5/10
157/157 [==============================] - 1s 8ms/step - loss: 0.6818 - accuracy: 0.7630
Epoch 6/10
157/157 [==============================] - 2s 10ms/step - loss: 0.5287 - accuracy: 0.8116
Epoch 7/10
157/157 [==============================] - 1s 7ms/step - loss: 0.4535 - accuracy: 0.8402
Epoch 8/10
157/157 [==============================] - 1s 7ms/step - loss: 0.3615 - accuracy: 0.8746
Epoch 9/10
157/157 [==============================] - 1s 7ms/step - loss: 0.3029 - accuracy: 0.8982
Epoch 10/10
157/157 [==============================] - 1s 7ms/step - loss: 0.2441 - accuracy: 0.9174
Epoch 1/10
157/157 [==============================] - 9s 8ms/step - loss: 2.0164 - accuracy: 0.2570
Epoch 2/10
157/157 [==============================] - 1s 8ms/step - loss: 1.6402 - accuracy: 0.3920
Epoch 3/10
157/157 [==============================] - 1s 8ms/step - loss: 1.5227 - accuracy: 0.4422
Epoch 4/10
157/157 [==============================] - 1s 8ms/step - loss: 1.3551 - accuracy: 0.5018
Epoch 5/10
157/157 [==============================] - 1s 8ms/step - loss: 1.2178 - accuracy: 0.5580
Epoch 6/10
157/157 [==============================] - 1s 8ms/step - loss: 1.0800 - accuracy: 0.6078
Epoch 7/10
157/157 [==============================] - 1s 8ms/step - loss: 0.9380 - accuracy: 0.6686
Epoch 8/10
157/157 [==============================] - 1s 9ms/step - loss: 0.7719 - accuracy: 0.7240
Epoch 9/10
157/157 [==============================] - 1s 9ms/step - loss: 0.6094 - accuracy: 0.7862
Epoch 10/10
157/157 [==============================] - 1s 8ms/step - loss: 0.4505 - accuracy: 0.8358
313/313 [==============================] - 1s 3ms/step - loss: 1.7977 - accuracy: 0.5573
Test Accuracy: 0.5572999715805054
Epoch 1/10
157/157 [==============================] - 4s 7ms/step - loss: 1.4354 - accuracy: 0.5150
Epoch 2/10
157/157 [==============================] - 1s 6ms/step - loss: 1.1013 - accuracy: 0.6100
Epoch 3/10
157/157 [==============================] - 1s 5ms/step - loss: 0.9182 - accuracy: 0.6788
Epoch 4/10
157/157 [==============================] - 1s 6ms/step - loss: 0.7289 - accuracy: 0.7490
Epoch 5/10
157/157 [==============================] - 1s 6ms/step - loss: 0.5826 - accuracy: 0.7958
Epoch 6/10
157/157 [==============================] - 1s 5ms/step - loss: 0.4425 - accuracy: 0.8440
Epoch 7/10
157/157 [==============================] - 1s 5ms/step - loss: 0.3229 - accuracy: 0.8834
Epoch 8/10
157/157 [==============================] - 1s 5ms/step - loss: 0.2745 - accuracy: 0.9068
Epoch 9/10
157/157 [==============================] - 1s 5ms/step - loss: 0.2384 - accuracy: 0.9168
Epoch 10/10
157/157 [==============================] - 1s 5ms/step - loss: 0.1993 - accuracy: 0.9350
Epoch 1/10
157/157 [==============================] - 10s 12ms/step - loss: 2.0756 - accuracy: 0.2382
Epoch 2/10
157/157 [==============================] - 2s 12ms/step - loss: 1.7486 - accuracy: 0.3608
Epoch 3/10
157/157 [==============================] - 2s 10ms/step - loss: 1.5958 - accuracy: 0.4200
Epoch 4/10
157/157 [==============================] - 2s 11ms/step - loss: 1.4607 - accuracy: 0.4772
Epoch 5/10
157/157 [==============================] - 2s 12ms/step - loss: 1.3482 - accuracy: 0.5168
Epoch 6/10
157/157 [==============================] - 2s 11ms/step - loss: 1.2010 - accuracy: 0.5682
Epoch 7/10
157/157 [==============================] - 1s 9ms/step - loss: 1.0407 - accuracy: 0.6242
Epoch 8/10
157/157 [==============================] - 2s 10ms/step - loss: 0.8772 - accuracy: 0.6890
Epoch 9/10
157/157 [==============================] - 2s 10ms/step - loss: 0.7069 - accuracy: 0.7474
Epoch 10/10
157/157 [==============================] - 1s 8ms/step - loss: 0.5350 - accuracy: 0.8096
313/313 [==============================] - 1s 3ms/step - loss: 1.6292 - accuracy: 0.5998
Test Accuracy: 0.5997999906539917
Epoch 1/10
157/157 [==============================] - 5s 8ms/step - loss: 1.3963 - accuracy: 0.5194
Epoch 2/10
157/157 [==============================] - 1s 6ms/step - loss: 1.0773 - accuracy: 0.6190
Epoch 3/10
157/157 [==============================] - 1s 6ms/step - loss: 0.8725 - accuracy: 0.6892
Epoch 4/10
157/157 [==============================] - 1s 5ms/step - loss: 0.6904 - accuracy: 0.7562
Epoch 5/10
157/157 [==============================] - 1s 5ms/step - loss: 0.5621 - accuracy: 0.8030
Epoch 6/10
157/157 [==============================] - 1s 6ms/step - loss: 0.4448 - accuracy: 0.8478
Epoch 7/10
157/157 [==============================] - 1s 5ms/step - loss: 0.3462 - accuracy: 0.8808
Epoch 8/10
157/157 [==============================] - 1s 5ms/step - loss: 0.2637 - accuracy: 0.9108
Epoch 9/10
157/157 [==============================] - 1s 5ms/step - loss: 0.2324 - accuracy: 0.9202
Epoch 10/10
157/157 [==============================] - 1s 5ms/step - loss: 0.1923 - accuracy: 0.9366
Epoch 1/10
157/157 [==============================] - 7s 8ms/step - loss: 2.1123 - accuracy: 0.2084
Epoch 2/10
157/157 [==============================] - 1s 8ms/step - loss: 1.7666 - accuracy: 0.3384
Epoch 3/10
157/157 [==============================] - 1s 8ms/step - loss: 1.5798 - accuracy: 0.4272
Epoch 4/10
157/157 [==============================] - 1s 8ms/step - loss: 1.4308 - accuracy: 0.4922
Epoch 5/10
157/157 [==============================] - 1s 8ms/step - loss: 1.2740 - accuracy: 0.5404
Epoch 6/10
157/157 [==============================] - 1s 8ms/step - loss: 1.1293 - accuracy: 0.6000
Epoch 7/10
157/157 [==============================] - 1s 9ms/step - loss: 0.9882 - accuracy: 0.6406
Epoch 8/10
157/157 [==============================] - 1s 9ms/step - loss: 0.8044 - accuracy: 0.7122
Epoch 9/10
157/157 [==============================] - 1s 8ms/step - loss: 0.6207 - accuracy: 0.7806
Epoch 10/10
157/157 [==============================] - 1s 8ms/step - loss: 0.4515 - accuracy: 0.8436
313/313 [==============================] - 1s 4ms/step - loss: 1.5796 - accuracy: 0.6170
Test Accuracy: 0.6169999837875366
Epoch 1/10
157/157 [==============================] - 3s 6ms/step - loss: 1.3436 - accuracy: 0.5536
Epoch 2/10
157/157 [==============================] - 1s 5ms/step - loss: 0.9972 - accuracy: 0.6566
Epoch 3/10
157/157 [==============================] - 1s 5ms/step - loss: 0.8015 - accuracy: 0.7228
Epoch 4/10
157/157 [==============================] - 1s 5ms/step - loss: 0.6562 - accuracy: 0.7638
Epoch 5/10
157/157 [==============================] - 1s 5ms/step - loss: 0.5085 - accuracy: 0.8196
Epoch 6/10
157/157 [==============================] - 1s 5ms/step - loss: 0.3961 - accuracy: 0.8620
Epoch 7/10
157/157 [==============================] - 1s 5ms/step - loss: 0.2807 - accuracy: 0.9004
Epoch 8/10
157/157 [==============================] - 1s 6ms/step - loss: 0.2488 - accuracy: 0.9130
Epoch 9/10
157/157 [==============================] - 1s 6ms/step - loss: 0.2119 - accuracy: 0.9264
Epoch 10/10
157/157 [==============================] - 1s 6ms/step - loss: 0.1884 - accuracy: 0.9388
Epoch 1/10
157/157 [==============================] - 6s 8ms/step - loss: 2.0447 - accuracy: 0.2542
Epoch 2/10
157/157 [==============================] - 1s 8ms/step - loss: 1.7196 - accuracy: 0.3712
Epoch 3/10
157/157 [==============================] - 1s 8ms/step - loss: 1.5223 - accuracy: 0.4450
Epoch 4/10
157/157 [==============================] - 1s 8ms/step - loss: 1.3678 - accuracy: 0.4996
Epoch 5/10
157/157 [==============================] - 1s 9ms/step - loss: 1.2318 - accuracy: 0.5526
Epoch 6/10
157/157 [==============================] - 2s 10ms/step - loss: 1.0794 - accuracy: 0.6136
Epoch 7/10
157/157 [==============================] - 1s 9ms/step - loss: 0.9403 - accuracy: 0.6620
Epoch 8/10
157/157 [==============================] - 1s 8ms/step - loss: 0.7666 - accuracy: 0.7290
Epoch 9/10
157/157 [==============================] - 1s 8ms/step - loss: 0.5898 - accuracy: 0.7880
Epoch 10/10
157/157 [==============================] - 1s 8ms/step - loss: 0.4362 - accuracy: 0.8402
313/313 [==============================] - 1s 4ms/step - loss: 1.6771 - accuracy: 0.6193
Test Accuracy: 0.6193000078201294
Epoch 1/10
157/157 [==============================] - 3s 6ms/step - loss: 1.3063 - accuracy: 0.5644
Epoch 2/10
157/157 [==============================] - 1s 6ms/step - loss: 0.9763 - accuracy: 0.6580
Epoch 3/10
157/157 [==============================] - 1s 6ms/step - loss: 0.7831 - accuracy: 0.7338
Epoch 4/10
157/157 [==============================] - 1s 6ms/step - loss: 0.6258 - accuracy: 0.7784
Epoch 5/10
157/157 [==============================] - 1s 6ms/step - loss: 0.5073 - accuracy: 0.8154
Epoch 6/10
157/157 [==============================] - 1s 6ms/step - loss: 0.4097 - accuracy: 0.8514
Epoch 7/10
157/157 [==============================] - 1s 6ms/step - loss: 0.3118 - accuracy: 0.8930
Epoch 8/10
157/157 [==============================] - 2s 11ms/step - loss: 0.2352 - accuracy: 0.9210
Epoch 9/10
157/157 [==============================] - 1s 8ms/step - loss: 0.2120 - accuracy: 0.9270
Epoch 10/10
157/157 [==============================] - 1s 6ms/step - loss: 0.1880 - accuracy: 0.9368
Epoch 1/10
157/157 [==============================] - 6s 8ms/step - loss: 2.0466 - accuracy: 0.2366
Epoch 2/10
157/157 [==============================] - 1s 8ms/step - loss: 1.7343 - accuracy: 0.3522
Epoch 3/10
157/157 [==============================] - 1s 8ms/step - loss: 1.5355 - accuracy: 0.4350
Epoch 4/10
157/157 [==============================] - 1s 8ms/step - loss: 1.3990 - accuracy: 0.4918
Epoch 5/10
157/157 [==============================] - 1s 8ms/step - loss: 1.2712 - accuracy: 0.5362
Epoch 6/10
157/157 [==============================] - 2s 12ms/step - loss: 1.1283 - accuracy: 0.5976
Epoch 7/10
157/157 [==============================] - 1s 8ms/step - loss: 0.9860 - accuracy: 0.6470
Epoch 8/10
157/157 [==============================] - 1s 8ms/step - loss: 0.8241 - accuracy: 0.7070
Epoch 9/10
157/157 [==============================] - 1s 8ms/step - loss: 0.6721 - accuracy: 0.7598
Epoch 10/10
157/157 [==============================] - 1s 8ms/step - loss: 0.5012 - accuracy: 0.8270
313/313 [==============================] - 1s 3ms/step - loss: 1.5112 - accuracy: 0.6341
Test Accuracy: 0.6341000199317932
Epoch 1/10
157/157 [==============================] - 3s 6ms/step - loss: 1.3204 - accuracy: 0.5584
Epoch 2/10
157/157 [==============================] - 1s 6ms/step - loss: 1.0147 - accuracy: 0.6428
Epoch 3/10
157/157 [==============================] - 1s 6ms/step - loss: 0.8236 - accuracy: 0.7098
Epoch 4/10
157/157 [==============================] - 1s 7ms/step - loss: 0.6851 - accuracy: 0.7578
Epoch 5/10
157/157 [==============================] - 1s 7ms/step - loss: 0.5143 - accuracy: 0.8200
Epoch 6/10
157/157 [==============================] - 1s 5ms/step - loss: 0.3892 - accuracy: 0.8574
Epoch 7/10
157/157 [==============================] - 1s 6ms/step - loss: 0.3474 - accuracy: 0.8786
Epoch 8/10
157/157 [==============================] - 1s 6ms/step - loss: 0.2845 - accuracy: 0.9014
Epoch 9/10
157/157 [==============================] - 1s 6ms/step - loss: 0.2237 - accuracy: 0.9220
Epoch 10/10
157/157 [==============================] - 1s 5ms/step - loss: 0.1867 - accuracy: 0.9376
Epoch 1/10
157/157 [==============================] - 7s 10ms/step - loss: 2.0797 - accuracy: 0.2328
Epoch 2/10
157/157 [==============================] - 1s 8ms/step - loss: 1.8060 - accuracy: 0.3474
Epoch 3/10
157/157 [==============================] - 1s 8ms/step - loss: 1.6017 - accuracy: 0.4144
Epoch 4/10
157/157 [==============================] - 1s 8ms/step - loss: 1.4668 - accuracy: 0.4724
Epoch 5/10
157/157 [==============================] - 1s 8ms/step - loss: 1.3433 - accuracy: 0.5204
Epoch 6/10
157/157 [==============================] - 1s 8ms/step - loss: 1.2316 - accuracy: 0.5546
Epoch 7/10
157/157 [==============================] - 1s 8ms/step - loss: 1.0912 - accuracy: 0.6174
Epoch 8/10
157/157 [==============================] - 1s 8ms/step - loss: 0.9112 - accuracy: 0.6738
Epoch 9/10
157/157 [==============================] - 1s 8ms/step - loss: 0.7564 - accuracy: 0.7310
Epoch 10/10
157/157 [==============================] - 1s 9ms/step - loss: 0.6016 - accuracy: 0.7882
313/313 [==============================] - 1s 4ms/step - loss: 1.3434 - accuracy: 0.6449
Test Accuracy: 0.6449000239372253
Epoch 1/10
157/157 [==============================] - 4s 6ms/step - loss: 1.3089 - accuracy: 0.5644
Epoch 2/10
157/157 [==============================] - 1s 6ms/step - loss: 1.0007 - accuracy: 0.6474
Epoch 3/10
157/157 [==============================] - 1s 6ms/step - loss: 0.8075 - accuracy: 0.7180
Epoch 4/10
157/157 [==============================] - 1s 6ms/step - loss: 0.6701 - accuracy: 0.7690
Epoch 5/10
157/157 [==============================] - 1s 6ms/step - loss: 0.5353 - accuracy: 0.8164
Epoch 6/10
157/157 [==============================] - 1s 6ms/step - loss: 0.4304 - accuracy: 0.8492
Epoch 7/10
157/157 [==============================] - 1s 6ms/step - loss: 0.3336 - accuracy: 0.8808
Epoch 8/10
157/157 [==============================] - 1s 7ms/step - loss: 0.2956 - accuracy: 0.8966
Epoch 9/10
157/157 [==============================] - 1s 7ms/step - loss: 0.2438 - accuracy: 0.9196
Epoch 10/10
157/157 [==============================] - 1s 6ms/step - loss: 0.1986 - accuracy: 0.9318
Epoch 1/10
157/157 [==============================] - 6s 8ms/step - loss: 2.0909 - accuracy: 0.2292
Epoch 2/10
157/157 [==============================] - 1s 8ms/step - loss: 1.7784 - accuracy: 0.3516
Epoch 3/10
157/157 [==============================] - 1s 8ms/step - loss: 1.5859 - accuracy: 0.4254
Epoch 4/10
157/157 [==============================] - 1s 9ms/step - loss: 1.4268 - accuracy: 0.4822
Epoch 5/10
157/157 [==============================] - 1s 9ms/step - loss: 1.2935 - accuracy: 0.5388
Epoch 6/10
157/157 [==============================] - 1s 8ms/step - loss: 1.1218 - accuracy: 0.5918
Epoch 7/10
157/157 [==============================] - 1s 8ms/step - loss: 0.9691 - accuracy: 0.6512
Epoch 8/10
157/157 [==============================] - 1s 8ms/step - loss: 0.8081 - accuracy: 0.7214
Epoch 9/10
157/157 [==============================] - 1s 8ms/step - loss: 0.6512 - accuracy: 0.7772
Epoch 10/10
157/157 [==============================] - 1s 8ms/step - loss: 0.4758 - accuracy: 0.8314
313/313 [==============================] - 1s 3ms/step - loss: 1.5191 - accuracy: 0.6370
Test Accuracy: 0.6370000243186951
Epoch 1/10
157/157 [==============================] - 3s 6ms/step - loss: 1.2824 - accuracy: 0.5696
Epoch 2/10
157/157 [==============================] - 1s 7ms/step - loss: 1.0071 - accuracy: 0.6496
Epoch 3/10
157/157 [==============================] - 1s 6ms/step - loss: 0.8298 - accuracy: 0.7136
Epoch 4/10
157/157 [==============================] - 1s 5ms/step - loss: 0.6840 - accuracy: 0.7632
Epoch 5/10
157/157 [==============================] - 1s 6ms/step - loss: 0.5456 - accuracy: 0.8048
Epoch 6/10
157/157 [==============================] - 1s 7ms/step - loss: 0.4270 - accuracy: 0.8500
Epoch 7/10
157/157 [==============================] - 1s 7ms/step - loss: 0.3537 - accuracy: 0.8776
Epoch 8/10
157/157 [==============================] - 1s 6ms/step - loss: 0.2827 - accuracy: 0.9042
Epoch 9/10
157/157 [==============================] - 1s 6ms/step - loss: 0.2368 - accuracy: 0.9180
Epoch 10/10
157/157 [==============================] - 1s 6ms/step - loss: 0.1774 - accuracy: 0.9378
Epoch 1/10
157/157 [==============================] - 6s 8ms/step - loss: 1.9739 - accuracy: 0.2720
Epoch 2/10
157/157 [==============================] - 1s 8ms/step - loss: 1.6648 - accuracy: 0.3926
Epoch 3/10
157/157 [==============================] - 2s 10ms/step - loss: 1.5301 - accuracy: 0.4462
Epoch 4/10
157/157 [==============================] - 1s 9ms/step - loss: 1.3700 - accuracy: 0.5102
Epoch 5/10
157/157 [==============================] - 1s 8ms/step - loss: 1.2330 - accuracy: 0.5604
Epoch 6/10
157/157 [==============================] - 1s 8ms/step - loss: 1.0380 - accuracy: 0.6258
Epoch 7/10
157/157 [==============================] - 1s 8ms/step - loss: 0.8984 - accuracy: 0.6742
Epoch 8/10
157/157 [==============================] - 1s 8ms/step - loss: 0.6853 - accuracy: 0.7622
Epoch 9/10
157/157 [==============================] - 2s 10ms/step - loss: 0.5219 - accuracy: 0.8128
Epoch 10/10
157/157 [==============================] - 1s 8ms/step - loss: 0.4106 - accuracy: 0.8492
313/313 [==============================] - 1s 3ms/step - loss: 1.3765 - accuracy: 0.6609
Test Accuracy: 0.6608999967575073
Epoch 1/10
157/157 [==============================] - 3s 6ms/step - loss: 1.2415 - accuracy: 0.5876
Epoch 2/10
157/157 [==============================] - 1s 5ms/step - loss: 0.9620 - accuracy: 0.6712
Epoch 3/10
157/157 [==============================] - 1s 6ms/step - loss: 0.7922 - accuracy: 0.7182
Epoch 4/10
157/157 [==============================] - 1s 6ms/step - loss: 0.6586 - accuracy: 0.7738
Epoch 5/10
157/157 [==============================] - 1s 7ms/step - loss: 0.5077 - accuracy: 0.8268
Epoch 6/10
157/157 [==============================] - 1s 6ms/step - loss: 0.4043 - accuracy: 0.8630
Epoch 7/10
157/157 [==============================] - 1s 6ms/step - loss: 0.3244 - accuracy: 0.8866
Epoch 8/10
157/157 [==============================] - 1s 6ms/step - loss: 0.2724 - accuracy: 0.9040
Epoch 9/10

#### Batches 6

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers

# Load the CIFAR-100 dataset
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 0.1  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = x_train + tf.random.normal(shape=x_train.shape, mean=0.0, stddev=corruption_level, dtype=tf.float32)
corrupted_data = tf.clip_by_value(corrupted_data, 0.0, 1.0)

# Convert the labels to one-hot encoding
num_classes = 10
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 2 batches
n_batches = 6
batch_size = x_train.shape[0] // n_batches

# Define the CrlB regularizer
class CrlBRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Define the original CIFAR-10 model
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu'),
    layers.Dropout(0.25),
    Dense(num_classes, activation='softmax')
])

# Compile the model
# model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the original model on Task A
# model.fit(corrupted_data, y_train_onehot, batch_size=128, epochs=10, validation_data=(x_test, y_test_onehot))

# Train the model on each batch separately
for i in range(n_batches):
    start_index = i * batch_size
    end_index = (i + 1) * batch_size
    x_batch = corrupted_data[start_index:end_index]
    y_batch = y_train[start_index:end_index]
    model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    # Train the model on the current batch
    model.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    # _, test_accuracy = model.evaluate(x_test, y_test)
    # print("Test Accuracy:", test_accuracy)
# Save the weights of the original model for later use
    prior_weights = model.get_weights()

# Compute the Fisher Information matrix
    def compute_fisher(model, x, num_samples=30):
        fisher_matrix = []
        for i in range(len(model.trainable_weights)):
            fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

        for _ in range(num_samples):
            idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
            with tf.GradientTape() as tape:
                logits = model(x[idx:idx+1])
            gradients = tape.gradient(logits, model.trainable_weights)
            for i in range(len(fisher_matrix)):
                fisher_matrix[i] += tf.square(gradients[i])

        fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
        return fisher_matrix

    fisher_matrix = compute_fisher(model, corrupted_data)

# Define the new model with CrlB regularization
    model_CrlB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3),
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])

# Compile the model with CrlB regularization
    model_CrlB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on Task B with CrlB regularization
# history = model_CrlB.fit(corrupted_data, y_train_onehot, batch_size=128, epochs=10, validation_data=(x_test, y_test_onehot))
# print(history)
# Train the model on each batch separately
# for i in range(n_batches):
#     start_index = i * batch_size
#     end_index = (i + 1) * batch_size
#     x_batch = corrupted_data[start_index:end_index]
#     y_batch = y_train[start_index:end_index]

    # Train the model on the current batch
    model_CrlB.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)
# # Evaluate the model on the test set
# _, test_accuracy = model.evaluate(x_test, y_test_onehot, verbose=0)
# print("Test Accuracy:", test_accuracy)

Epoch 1/10
261/261 [==============================] - 14s 14ms/step - loss: 1.9210 - accuracy: 0.2817
Epoch 2/10
261/261 [==============================] - 3s 10ms/step - loss: 1.5611 - accuracy: 0.4237
Epoch 3/10
261/261 [==============================] - 3s 11ms/step - loss: 1.3813 - accuracy: 0.4954
Epoch 4/10
261/261 [==============================] - 4s 16ms/step - loss: 1.2406 - accuracy: 0.5503
Epoch 5/10
261/261 [==============================] - 3s 10ms/step - loss: 1.1263 - accuracy: 0.5938
Epoch 6/10
261/261 [==============================] - 2s 9ms/step - loss: 0.9949 - accuracy: 0.6363
Epoch 7/10
261/261 [==============================] - 2s 9ms/step - loss: 0.8801 - accuracy: 0.6780
Epoch 8/10
261/261 [==============================] - 2s 9ms/step - loss: 0.7425 - accuracy: 0.7356
Epoch 9/10
261/261 [==============================] - 3s 12ms/step - loss: 0.6206 - accuracy: 0.7734
Epoch 10/10
261/261 [==============================] - 2s 8ms/step - loss: 0.5182 - accuracy: 0.8159
Epoch 1/10
261/261 [==============================] - 15s 11ms/step - loss: 1.9261 - accuracy: 0.2871
Epoch 2/10
261/261 [==============================] - 3s 11ms/step - loss: 1.5908 - accuracy: 0.4117
Epoch 3/10
261/261 [==============================] - 4s 15ms/step - loss: 1.4149 - accuracy: 0.4823
Epoch 4/10
261/261 [==============================] - 3s 12ms/step - loss: 1.2689 - accuracy: 0.5349
Epoch 5/10
261/261 [==============================] - 3s 10ms/step - loss: 1.1365 - accuracy: 0.5887
Epoch 6/10
261/261 [==============================] - 2s 9ms/step - loss: 0.9975 - accuracy: 0.6382
Epoch 7/10
261/261 [==============================] - 3s 10ms/step - loss: 0.8507 - accuracy: 0.6895
Epoch 8/10
261/261 [==============================] - 3s 11ms/step - loss: 0.7039 - accuracy: 0.7481
Epoch 9/10
261/261 [==============================] - 2s 9ms/step - loss: 0.5716 - accuracy: 0.7986
Epoch 10/10
261/261 [==============================] - 2s 9ms/step - loss: 0.4694 - accuracy: 0.8312
313/313 [==============================] - 2s 4ms/step - loss: 1.4048 - accuracy: 0.5843
Test Accuracy: 0.5842999815940857
Epoch 1/10
261/261 [==============================] - 7s 7ms/step - loss: 1.2838 - accuracy: 0.5573
Epoch 2/10
261/261 [==============================] - 2s 7ms/step - loss: 1.0519 - accuracy: 0.6276
Epoch 3/10
261/261 [==============================] - 2s 7ms/step - loss: 0.9028 - accuracy: 0.6819
Epoch 4/10
261/261 [==============================] - 2s 7ms/step - loss: 0.7435 - accuracy: 0.7367
Epoch 5/10
261/261 [==============================] - 2s 7ms/step - loss: 0.6208 - accuracy: 0.7767
Epoch 6/10
261/261 [==============================] - 2s 9ms/step - loss: 0.5019 - accuracy: 0.8235
Epoch 7/10
261/261 [==============================] - 1s 6ms/step - loss: 0.4070 - accuracy: 0.8538
Epoch 8/10
261/261 [==============================] - 1s 6ms/step - loss: 0.3335 - accuracy: 0.8812
Epoch 9/10
261/261 [==============================] - 1s 6ms/step - loss: 0.2826 - accuracy: 0.8994
Epoch 10/10
261/261 [==============================] - 1s 6ms/step - loss: 0.2455 - accuracy: 0.9148
Epoch 1/10
261/261 [==============================] - 8s 8ms/step - loss: 1.9758 - accuracy: 0.2622
Epoch 2/10
261/261 [==============================] - 2s 8ms/step - loss: 1.5560 - accuracy: 0.4367
Epoch 3/10
261/261 [==============================] - 2s 8ms/step - loss: 1.3605 - accuracy: 0.5177
Epoch 4/10
261/261 [==============================] - 2s 8ms/step - loss: 1.2017 - accuracy: 0.5751
Epoch 5/10
261/261 [==============================] - 2s 9ms/step - loss: 1.0243 - accuracy: 0.6370
Epoch 6/10
261/261 [==============================] - 2s 9ms/step - loss: 0.8590 - accuracy: 0.6959
Epoch 7/10
261/261 [==============================] - 2s 8ms/step - loss: 0.6801 - accuracy: 0.7564
Epoch 8/10
261/261 [==============================] - 2s 8ms/step - loss: 0.5114 - accuracy: 0.8213
Epoch 9/10
261/261 [==============================] - 2s 8ms/step - loss: 0.4049 - accuracy: 0.8579
Epoch 10/10
261/261 [==============================] - 2s 8ms/step - loss: 0.2909 - accuracy: 0.9011
313/313 [==============================] - 1s 3ms/step - loss: 1.6356 - accuracy: 0.6101
Test Accuracy: 0.6100999712944031
Epoch 1/10
261/261 [==============================] - 4s 7ms/step - loss: 1.2672 - accuracy: 0.5782
Epoch 2/10
261/261 [==============================] - 2s 6ms/step - loss: 0.9769 - accuracy: 0.6571
Epoch 3/10
261/261 [==============================] - 1s 5ms/step - loss: 0.8153 - accuracy: 0.7099
Epoch 4/10
261/261 [==============================] - 1s 6ms/step - loss: 0.6518 - accuracy: 0.7702
Epoch 5/10
261/261 [==============================] - 1s 6ms/step - loss: 0.5327 - accuracy: 0.8109
Epoch 6/10
261/261 [==============================] - 1s 6ms/step - loss: 0.4423 - accuracy: 0.8453
Epoch 7/10
261/261 [==============================] - 1s 6ms/step - loss: 0.3722 - accuracy: 0.8699
Epoch 8/10
261/261 [==============================] - 2s 7ms/step - loss: 0.2843 - accuracy: 0.9014
Epoch 9/10
261/261 [==============================] - 2s 6ms/step - loss: 0.2420 - accuracy: 0.9182
Epoch 10/10
261/261 [==============================] - 2s 7ms/step - loss: 0.2280 - accuracy: 0.9226
Epoch 1/10
261/261 [==============================] - 7s 8ms/step - loss: 1.9314 - accuracy: 0.2872
Epoch 2/10
261/261 [==============================] - 2s 8ms/step - loss: 1.5566 - accuracy: 0.4367
Epoch 3/10
261/261 [==============================] - 3s 10ms/step - loss: 1.3654 - accuracy: 0.5125
Epoch 4/10
261/261 [==============================] - 2s 8ms/step - loss: 1.2007 - accuracy: 0.5704
Epoch 5/10
261/261 [==============================] - 2s 8ms/step - loss: 1.0514 - accuracy: 0.6244
Epoch 6/10
261/261 [==============================] - 2s 8ms/step - loss: 0.9142 - accuracy: 0.6765
Epoch 7/10
261/261 [==============================] - 2s 8ms/step - loss: 0.7516 - accuracy: 0.7341
Epoch 8/10
261/261 [==============================] - 2s 9ms/step - loss: 0.5900 - accuracy: 0.7913
Epoch 9/10
261/261 [==============================] - 2s 9ms/step - loss: 0.4921 - accuracy: 0.8302
Epoch 10/10
261/261 [==============================] - 2s 8ms/step - loss: 0.3590 - accuracy: 0.8740
313/313 [==============================] - 1s 3ms/step - loss: 1.5209 - accuracy: 0.6325
Test Accuracy: 0.6324999928474426
Epoch 1/10
261/261 [==============================] - 4s 6ms/step - loss: 1.2261 - accuracy: 0.5873
Epoch 2/10
261/261 [==============================] - 1s 6ms/step - loss: 0.9379 - accuracy: 0.6738
Epoch 3/10
261/261 [==============================] - 2s 7ms/step - loss: 0.7690 - accuracy: 0.7270
Epoch 4/10
261/261 [==============================] - 2s 6ms/step - loss: 0.6342 - accuracy: 0.7761
Epoch 5/10
261/261 [==============================] - 1s 6ms/step - loss: 0.4967 - accuracy: 0.8279
Epoch 6/10
261/261 [==============================] - 1s 5ms/step - loss: 0.3947 - accuracy: 0.8609
Epoch 7/10
261/261 [==============================] - 2s 7ms/step - loss: 0.3305 - accuracy: 0.8818
Epoch 8/10
261/261 [==============================] - 1s 6ms/step - loss: 0.2819 - accuracy: 0.9045
Epoch 9/10
261/261 [==============================] - 1s 5ms/step - loss: 0.2367 - accuracy: 0.9194
Epoch 10/10
261/261 [==============================] - 1s 5ms/step - loss: 0.2108 - accuracy: 0.9267
Epoch 1/10
261/261 [==============================] - 7s 8ms/step - loss: 1.9497 - accuracy: 0.2887
Epoch 2/10
261/261 [==============================] - 2s 8ms/step - loss: 1.6079 - accuracy: 0.4164
Epoch 3/10
261/261 [==============================] - 2s 7ms/step - loss: 1.4005 - accuracy: 0.4971
Epoch 4/10
261/261 [==============================] - 2s 9ms/step - loss: 1.2373 - accuracy: 0.5537
Epoch 5/10
261/261 [==============================] - 2s 7ms/step - loss: 1.0960 - accuracy: 0.6076
Epoch 6/10
261/261 [==============================] - 2s 7ms/step - loss: 0.9285 - accuracy: 0.6679
Epoch 7/10
261/261 [==============================] - 2s 8ms/step - loss: 0.7802 - accuracy: 0.7255
Epoch 8/10
261/261 [==============================] - 2s 8ms/step - loss: 0.6188 - accuracy: 0.7820
Epoch 9/10
261/261 [==============================] - 2s 8ms/step - loss: 0.4884 - accuracy: 0.8315
Epoch 10/10
261/261 [==============================] - 2s 9ms/step - loss: 0.3831 - accuracy: 0.8698
313/313 [==============================] - 1s 3ms/step - loss: 1.5150 - accuracy: 0.6432
Test Accuracy: 0.6431999802589417
Epoch 1/10
261/261 [==============================] - 5s 6ms/step - loss: 1.2388 - accuracy: 0.5848
Epoch 2/10
261/261 [==============================] - 1s 6ms/step - loss: 0.9587 - accuracy: 0.6586
Epoch 3/10
261/261 [==============================] - 2s 7ms/step - loss: 0.7967 - accuracy: 0.7185
Epoch 4/10
261/261 [==============================] - 1s 6ms/step - loss: 0.6456 - accuracy: 0.7710
Epoch 5/10
261/261 [==============================] - 1s 6ms/step - loss: 0.5302 - accuracy: 0.8122
Epoch 6/10
261/261 [==============================] - 1s 6ms/step - loss: 0.4437 - accuracy: 0.8456
Epoch 7/10
261/261 [==============================] - 2s 6ms/step - loss: 0.3341 - accuracy: 0.8781
Epoch 8/10
261/261 [==============================] - 2s 7ms/step - loss: 0.2752 - accuracy: 0.9015
Epoch 9/10
261/261 [==============================] - 1s 6ms/step - loss: 0.2690 - accuracy: 0.9083
Epoch 10/10
261/261 [==============================] - 1s 6ms/step - loss: 0.2111 - accuracy: 0.9266
Epoch 1/10
261/261 [==============================] - 7s 8ms/step - loss: 1.9377 - accuracy: 0.2881
Epoch 2/10
261/261 [==============================] - 2s 8ms/step - loss: 1.6123 - accuracy: 0.4083
Epoch 3/10
261/261 [==============================] - 2s 8ms/step - loss: 1.4324 - accuracy: 0.4833
Epoch 4/10
261/261 [==============================] - 2s 8ms/step - loss: 1.2843 - accuracy: 0.5309
Epoch 5/10
261/261 [==============================] - 2s 8ms/step - loss: 1.1393 - accuracy: 0.5935
Epoch 6/10
261/261 [==============================] - 2s 9ms/step - loss: 0.9906 - accuracy: 0.6498
Epoch 7/10
261/261 [==============================] - 2s 8ms/step - loss: 0.8241 - accuracy: 0.7116
Epoch 8/10
261/261 [==============================] - 2s 8ms/step - loss: 0.6745 - accuracy: 0.7634
Epoch 9/10
261/261 [==============================] - 2s 8ms/step - loss: 0.5261 - accuracy: 0.8114
Epoch 10/10
261/261 [==============================] - 2s 8ms/step - loss: 0.4047 - accuracy: 0.8579
313/313 [==============================] - 1s 3ms/step - loss: 1.3659 - accuracy: 0.6740
Test Accuracy: 0.6740000247955322
Epoch 1/10
261/261 [==============================] - 4s 6ms/step - loss: 1.1855 - accuracy: 0.6034
Epoch 2/10
261/261 [==============================] - 1s 6ms/step - loss: 0.9012 - accuracy: 0.6859
Epoch 3/10
261/261 [==============================] - 2s 7ms/step - loss: 0.7729 - accuracy: 0.7246
Epoch 4/10
261/261 [==============================] - 2s 6ms/step - loss: 0.6213 - accuracy: 0.7791
Epoch 5/10
261/261 [==============================] - 1s 6ms/step - loss: 0.4965 - accuracy: 0.8265
Epoch 6/10
261/261 [==============================] - 2s 6ms/step - loss: 0.4146 - accuracy: 0.8523
Epoch 7/10
261/261 [==============================] - 1s 6ms/step - loss: 0.3312 - accuracy: 0.8862
Epoch 8/10
261/261 [==============================] - 1s 6ms/step - loss: 0.2753 - accuracy: 0.9032
Epoch 9/10
261/261 [==============================] - 1s 6ms/step - loss: 0.2379 - accuracy: 0.9198
Epoch 10/10
261/261 [==============================] - 2s 6ms/step - loss: 0.2063 - accuracy: 0.9282
Epoch 1/10
261/261 [==============================] - 7s 8ms/step - loss: 1.9379 - accuracy: 0.2868
Epoch 2/10
261/261 [==============================] - 2s 9ms/step - loss: 1.5623 - accuracy: 0.4319
Epoch 3/10
261/261 [==============================] - 2s 8ms/step - loss: 1.3855 - accuracy: 0.5002
Epoch 4/10
261/261 [==============================] - 2s 8ms/step - loss: 1.2067 - accuracy: 0.5685
Epoch 5/10
261/261 [==============================] - 2s 8ms/step - loss: 1.0726 - accuracy: 0.6135
Epoch 6/10
261/261 [==============================] - 2s 8ms/step - loss: 0.9249 - accuracy: 0.6717
Epoch 7/10
261/261 [==============================] - 2s 8ms/step - loss: 0.7451 - accuracy: 0.7339
Epoch 8/10
261/261 [==============================] - 2s 9ms/step - loss: 0.6084 - accuracy: 0.7839
Epoch 9/10
261/261 [==============================] - 2s 8ms/step - loss: 0.4465 - accuracy: 0.8402
Epoch 10/10
261/261 [==============================] - 2s 8ms/step - loss: 0.3552 - accuracy: 0.8723
313/313 [==============================] - 1s 3ms/step - loss: 1.3796 - accuracy: 0.6694
Test Accuracy: 0.6693999767303467

#### Batches 5

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers

# Load the CIFAR-100 dataset
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 0.1  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = x_train + tf.random.normal(shape=x_train.shape, mean=0.0, stddev=corruption_level, dtype=tf.float32)
corrupted_data = tf.clip_by_value(corrupted_data, 0.0, 1.0)

# Convert the labels to one-hot encoding
num_classes = 10
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 2 batches
n_batches = 5
batch_size = x_train.shape[0] // n_batches

# Define the CrlB regularizer
class CrlBRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Define the original CIFAR-10 model
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu'),
    layers.Dropout(0.25),
    Dense(num_classes, activation='softmax')
])

# Compile the model
# model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the original model on Task A
# model.fit(corrupted_data, y_train_onehot, batch_size=128, epochs=10, validation_data=(x_test, y_test_onehot))

# Train the model on each batch separately
for i in range(n_batches):
    start_index = i * batch_size
    end_index = (i + 1) * batch_size
    x_batch = corrupted_data[start_index:end_index]
    y_batch = y_train[start_index:end_index]
    model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    # Train the model on the current batch
    model.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    # _, test_accuracy = model.evaluate(x_test, y_test)
    # print("Test Accuracy:", test_accuracy)
# Save the weights of the original model for later use
    prior_weights = model.get_weights()

# Compute the Fisher Information matrix
    def compute_fisher(model, x, num_samples=30):
        fisher_matrix = []
        for i in range(len(model.trainable_weights)):
            fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

        for _ in range(num_samples):
            idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
            with tf.GradientTape() as tape:
                logits = model(x[idx:idx+1])
            gradients = tape.gradient(logits, model.trainable_weights)
            for i in range(len(fisher_matrix)):
                fisher_matrix[i] += tf.square(gradients[i])

        fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
        return fisher_matrix

    fisher_matrix = compute_fisher(model, corrupted_data)

# Define the new model with CrlB regularization
    model_CrlB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3),
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])

# Compile the model with CrlB regularization
    model_CrlB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on Task B with CrlB regularization
# history = model_CrlB.fit(corrupted_data, y_train_onehot, batch_size=128, epochs=10, validation_data=(x_test, y_test_onehot))
# print(history)
# Train the model on each batch separately
# for i in range(n_batches):
#     start_index = i * batch_size
#     end_index = (i + 1) * batch_size
#     x_batch = corrupted_data[start_index:end_index]
#     y_batch = y_train[start_index:end_index]

    # Train the model on the current batch
    model_CrlB.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)
# # Evaluate the model on the test set
# _, test_accuracy = model.evaluate(x_test, y_test_onehot, verbose=0)
# print("Test Accuracy:", test_accuracy)

Epoch 1/10
313/313 [==============================] - 4s 7ms/step - loss: 1.9016 - accuracy: 0.2986
Epoch 2/10
313/313 [==============================] - 2s 5ms/step - loss: 1.5535 - accuracy: 0.4273
Epoch 3/10
313/313 [==============================] - 2s 5ms/step - loss: 1.3819 - accuracy: 0.5080
Epoch 4/10
313/313 [==============================] - 2s 5ms/step - loss: 1.2369 - accuracy: 0.5522
Epoch 5/10
313/313 [==============================] - 2s 5ms/step - loss: 1.1227 - accuracy: 0.5940
Epoch 6/10
313/313 [==============================] - 2s 5ms/step - loss: 0.9944 - accuracy: 0.6398
Epoch 7/10
313/313 [==============================] - 2s 6ms/step - loss: 0.8949 - accuracy: 0.6816
Epoch 8/10
313/313 [==============================] - 2s 7ms/step - loss: 0.7694 - accuracy: 0.7234
Epoch 9/10
313/313 [==============================] - 2s 5ms/step - loss: 0.6681 - accuracy: 0.7640
Epoch 10/10
313/313 [==============================] - 2s 5ms/step - loss: 0.5734 - accuracy: 0.7890
Epoch 1/10
313/313 [==============================] - 8s 9ms/step - loss: 1.8736 - accuracy: 0.3091
Epoch 2/10
313/313 [==============================] - 2s 8ms/step - loss: 1.4918 - accuracy: 0.4531
Epoch 3/10
313/313 [==============================] - 2s 8ms/step - loss: 1.3171 - accuracy: 0.5244
Epoch 4/10
313/313 [==============================] - 2s 8ms/step - loss: 1.1569 - accuracy: 0.5811
Epoch 5/10
313/313 [==============================] - 3s 8ms/step - loss: 1.0211 - accuracy: 0.6362
Epoch 6/10
313/313 [==============================] - 3s 9ms/step - loss: 0.8585 - accuracy: 0.6950
Epoch 7/10
313/313 [==============================] - 2s 8ms/step - loss: 0.7071 - accuracy: 0.7477
Epoch 8/10
313/313 [==============================] - 2s 8ms/step - loss: 0.5337 - accuracy: 0.8073
Epoch 9/10
313/313 [==============================] - 2s 8ms/step - loss: 0.4267 - accuracy: 0.8497
Epoch 10/10
313/313 [==============================] - 3s 9ms/step - loss: 0.3290 - accuracy: 0.8863
313/313 [==============================] - 1s 3ms/step - loss: 1.3567 - accuracy: 0.5845
Test Accuracy: 0.5845000147819519
Epoch 1/10
313/313 [==============================] - 4s 6ms/step - loss: 1.2823 - accuracy: 0.5506
Epoch 2/10
313/313 [==============================] - 2s 6ms/step - loss: 1.0719 - accuracy: 0.6266
Epoch 3/10
313/313 [==============================] - 2s 7ms/step - loss: 0.9328 - accuracy: 0.6739
Epoch 4/10
313/313 [==============================] - 2s 6ms/step - loss: 0.7918 - accuracy: 0.7125
Epoch 5/10
313/313 [==============================] - 2s 6ms/step - loss: 0.6721 - accuracy: 0.7628
Epoch 6/10
313/313 [==============================] - 2s 6ms/step - loss: 0.5560 - accuracy: 0.8057
Epoch 7/10
313/313 [==============================] - 2s 6ms/step - loss: 0.4785 - accuracy: 0.8309
Epoch 8/10
313/313 [==============================] - 2s 6ms/step - loss: 0.3800 - accuracy: 0.8688
Epoch 9/10
313/313 [==============================] - 2s 6ms/step - loss: 0.3378 - accuracy: 0.8787
Epoch 10/10
313/313 [==============================] - 2s 7ms/step - loss: 0.2857 - accuracy: 0.9011
Epoch 1/10
313/313 [==============================] - 7s 8ms/step - loss: 1.9375 - accuracy: 0.2773
Epoch 2/10
313/313 [==============================] - 3s 8ms/step - loss: 1.5383 - accuracy: 0.4374
Epoch 3/10
313/313 [==============================] - 3s 8ms/step - loss: 1.3434 - accuracy: 0.5126
Epoch 4/10
313/313 [==============================] - 2s 8ms/step - loss: 1.1827 - accuracy: 0.5784
Epoch 5/10
313/313 [==============================] - 2s 8ms/step - loss: 1.0329 - accuracy: 0.6333
Epoch 6/10
313/313 [==============================] - 2s 8ms/step - loss: 0.8811 - accuracy: 0.6885
Epoch 7/10
313/313 [==============================] - 3s 8ms/step - loss: 0.7157 - accuracy: 0.7466
Epoch 8/10
313/313 [==============================] - 3s 8ms/step - loss: 0.5732 - accuracy: 0.8000
Epoch 9/10
313/313 [==============================] - 2s 8ms/step - loss: 0.4242 - accuracy: 0.8508
Epoch 10/10
313/313 [==============================] - 2s 7ms/step - loss: 0.3439 - accuracy: 0.8806
313/313 [==============================] - 2s 4ms/step - loss: 1.4196 - accuracy: 0.6338
Test Accuracy: 0.6338000297546387
Epoch 1/10
313/313 [==============================] - 4s 6ms/step - loss: 1.2326 - accuracy: 0.5832
Epoch 2/10
313/313 [==============================] - 2s 6ms/step - loss: 0.9904 - accuracy: 0.6482
Epoch 3/10
313/313 [==============================] - 2s 5ms/step - loss: 0.8521 - accuracy: 0.6985
Epoch 4/10
313/313 [==============================] - 2s 6ms/step - loss: 0.7182 - accuracy: 0.7473
Epoch 5/10
313/313 [==============================] - 2s 7ms/step - loss: 0.5893 - accuracy: 0.7948
Epoch 6/10
313/313 [==============================] - 2s 6ms/step - loss: 0.4994 - accuracy: 0.8284
Epoch 7/10
313/313 [==============================] - 2s 6ms/step - loss: 0.4042 - accuracy: 0.8549
Epoch 8/10
313/313 [==============================] - 2s 6ms/step - loss: 0.3376 - accuracy: 0.8817
Epoch 9/10
313/313 [==============================] - 2s 5ms/step - loss: 0.2955 - accuracy: 0.8935
Epoch 10/10
313/313 [==============================] - 2s 6ms/step - loss: 0.2629 - accuracy: 0.9076
Epoch 1/10
313/313 [==============================] - 8s 8ms/step - loss: 1.8790 - accuracy: 0.3052
Epoch 2/10
313/313 [==============================] - 2s 8ms/step - loss: 1.5232 - accuracy: 0.4414
Epoch 3/10
313/313 [==============================] - 3s 8ms/step - loss: 1.3513 - accuracy: 0.5074
Epoch 4/10
313/313 [==============================] - 3s 8ms/step - loss: 1.2149 - accuracy: 0.5631
Epoch 5/10
313/313 [==============================] - 2s 7ms/step - loss: 1.0839 - accuracy: 0.6080
Epoch 6/10
313/313 [==============================] - 2s 7ms/step - loss: 0.9611 - accuracy: 0.6592
Epoch 7/10
313/313 [==============================] - 2s 7ms/step - loss: 0.8326 - accuracy: 0.7024
Epoch 8/10
313/313 [==============================] - 3s 8ms/step - loss: 0.7012 - accuracy: 0.7485
Epoch 9/10
313/313 [==============================] - 3s 8ms/step - loss: 0.5662 - accuracy: 0.7977
Epoch 10/10
313/313 [==============================] - 2s 7ms/step - loss: 0.4645 - accuracy: 0.8323
313/313 [==============================] - 1s 3ms/step - loss: 1.4667 - accuracy: 0.6435
Test Accuracy: 0.6434999704360962
Epoch 1/10
313/313 [==============================] - 5s 6ms/step - loss: 1.2325 - accuracy: 0.5883
Epoch 2/10
313/313 [==============================] - 2s 5ms/step - loss: 0.9797 - accuracy: 0.6583
Epoch 3/10
313/313 [==============================] - 2s 5ms/step - loss: 0.8284 - accuracy: 0.7101
Epoch 4/10
313/313 [==============================] - 2s 5ms/step - loss: 0.7124 - accuracy: 0.7511
Epoch 5/10
313/313 [==============================] - 2s 5ms/step - loss: 0.5710 - accuracy: 0.7973
Epoch 6/10
313/313 [==============================] - 2s 5ms/step - loss: 0.4857 - accuracy: 0.8294
Epoch 7/10
313/313 [==============================] - 2s 7ms/step - loss: 0.3844 - accuracy: 0.8636
Epoch 8/10
313/313 [==============================] - 2s 6ms/step - loss: 0.3426 - accuracy: 0.8797
Epoch 9/10
313/313 [==============================] - 2s 5ms/step - loss: 0.2951 - accuracy: 0.8971
Epoch 10/10
313/313 [==============================] - 2s 5ms/step - loss: 0.2455 - accuracy: 0.9144
Epoch 1/10
313/313 [==============================] - 8s 8ms/step - loss: 1.8809 - accuracy: 0.3062
Epoch 2/10
313/313 [==============================] - 2s 8ms/step - loss: 1.5596 - accuracy: 0.4304
Epoch 3/10
313/313 [==============================] - 2s 8ms/step - loss: 1.3791 - accuracy: 0.5035
Epoch 4/10
313/313 [==============================] - 2s 8ms/step - loss: 1.2242 - accuracy: 0.5621
Epoch 5/10
313/313 [==============================] - 3s 9ms/step - loss: 1.0893 - accuracy: 0.6086
Epoch 6/10
313/313 [==============================] - 2s 8ms/step - loss: 0.9467 - accuracy: 0.6562
Epoch 7/10
313/313 [==============================] - 2s 8ms/step - loss: 0.7981 - accuracy: 0.7147
Epoch 8/10
313/313 [==============================] - 2s 8ms/step - loss: 0.6654 - accuracy: 0.7626
Epoch 9/10
313/313 [==============================] - 2s 8ms/step - loss: 0.5481 - accuracy: 0.8062
Epoch 10/10
313/313 [==============================] - 3s 9ms/step - loss: 0.4253 - accuracy: 0.8487
313/313 [==============================] - 1s 3ms/step - loss: 1.2898 - accuracy: 0.6658
Test Accuracy: 0.6657999753952026
Epoch 1/10
313/313 [==============================] - 4s 6ms/step - loss: 1.1770 - accuracy: 0.6012
Epoch 2/10
313/313 [==============================] - 2s 5ms/step - loss: 0.9665 - accuracy: 0.6610
Epoch 3/10
313/313 [==============================] - 2s 7ms/step - loss: 0.8171 - accuracy: 0.7127
Epoch 4/10
313/313 [==============================] - 2s 6ms/step - loss: 0.6736 - accuracy: 0.7614
Epoch 5/10
313/313 [==============================] - 2s 5ms/step - loss: 0.5660 - accuracy: 0.8032
Epoch 6/10
313/313 [==============================] - 2s 5ms/step - loss: 0.4711 - accuracy: 0.8329
Epoch 7/10
313/313 [==============================] - 2s 5ms/step - loss: 0.3756 - accuracy: 0.8674
Epoch 8/10
313/313 [==============================] - 2s 5ms/step - loss: 0.3271 - accuracy: 0.8905
Epoch 9/10
313/313 [==============================] - 2s 5ms/step - loss: 0.2644 - accuracy: 0.9064
Epoch 10/10
313/313 [==============================] - 2s 7ms/step - loss: 0.2421 - accuracy: 0.9156
Epoch 1/10
313/313 [==============================] - 7s 8ms/step - loss: 1.9763 - accuracy: 0.2603
Epoch 2/10
313/313 [==============================] - 3s 8ms/step - loss: 1.5497 - accuracy: 0.4322
Epoch 3/10
313/313 [==============================] - 3s 9ms/step - loss: 1.3353 - accuracy: 0.5185
Epoch 4/10
313/313 [==============================] - 2s 8ms/step - loss: 1.1763 - accuracy: 0.5766
Epoch 5/10
313/313 [==============================] - 2s 8ms/step - loss: 1.0340 - accuracy: 0.6296
Epoch 6/10
313/313 [==============================] - 2s 8ms/step - loss: 0.8685 - accuracy: 0.6897
Epoch 7/10
313/313 [==============================] - 3s 8ms/step - loss: 0.7191 - accuracy: 0.7406
Epoch 8/10
313/313 [==============================] - 3s 8ms/step - loss: 0.5572 - accuracy: 0.7982
Epoch 9/10
313/313 [==============================] - 2s 8ms/step - loss: 0.4343 - accuracy: 0.8472
Epoch 10/10
313/313 [==============================] - 2s 8ms/step - loss: 0.3228 - accuracy: 0.8853
313/313 [==============================] - 1s 3ms/step - loss: 1.2741 - accuracy: 0.6623
Test Accuracy: 0.6622999906539917

#### Batches 4

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers

# Load the CIFAR-100 dataset
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 0.1  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = x_train + tf.random.normal(shape=x_train.shape, mean=0.0, stddev=corruption_level, dtype=tf.float32)
corrupted_data = tf.clip_by_value(corrupted_data, 0.0, 1.0)

# Convert the labels to one-hot encoding
num_classes = 10
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 2 batches
n_batches = 4
batch_size = x_train.shape[0] // n_batches

# Define the CrlB regularizer
class CrlBRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Define the original CIFAR-10 model
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu'),
    layers.Dropout(0.25),
    Dense(num_classes, activation='softmax')
])

# Compile the model
# model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the original model on Task A
# model.fit(corrupted_data, y_train_onehot, batch_size=128, epochs=10, validation_data=(x_test, y_test_onehot))

# Train the model on each batch separately
for i in range(n_batches):
    start_index = i * batch_size
    end_index = (i + 1) * batch_size
    x_batch = corrupted_data[start_index:end_index]
    y_batch = y_train[start_index:end_index]
    model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    # Train the model on the current batch
    model.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    # _, test_accuracy = model.evaluate(x_test, y_test)
    # print("Test Accuracy:", test_accuracy)
# Save the weights of the original model for later use
    prior_weights = model.get_weights()

# Compute the Fisher Information matrix
    def compute_fisher(model, x, num_samples=30):
        fisher_matrix = []
        for i in range(len(model.trainable_weights)):
            fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

        for _ in range(num_samples):
            idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
            with tf.GradientTape() as tape:
                logits = model(x[idx:idx+1])
            gradients = tape.gradient(logits, model.trainable_weights)
            for i in range(len(fisher_matrix)):
                fisher_matrix[i] += tf.square(gradients[i])

        fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
        return fisher_matrix

    fisher_matrix = compute_fisher(model, corrupted_data)

# Define the new model with CrlB regularization
    model_CrlB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3),
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])

# Compile the model with CrlB regularization
    model_CrlB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on Task B with CrlB regularization
# history = model_CrlB.fit(corrupted_data, y_train_onehot, batch_size=128, epochs=10, validation_data=(x_test, y_test_onehot))
# print(history)
# Train the model on each batch separately
# for i in range(n_batches):
#     start_index = i * batch_size
#     end_index = (i + 1) * batch_size
#     x_batch = corrupted_data[start_index:end_index]
#     y_batch = y_train[start_index:end_index]

    # Train the model on the current batch
    model_CrlB.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)
# # Evaluate the model on the test set
# _, test_accuracy = model.evaluate(x_test, y_test_onehot, verbose=0)
# print("Test Accuracy:", test_accuracy)

Downloading data from https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
170498071/170498071 [==============================] - 2s 0us/step
Epoch 1/10
391/391 [==============================] - 21s 10ms/step - loss: 1.8680 - accuracy: 0.3167
Epoch 2/10
391/391 [==============================] - 3s 8ms/step - loss: 1.5072 - accuracy: 0.4468
Epoch 3/10
391/391 [==============================] - 3s 7ms/step - loss: 1.3383 - accuracy: 0.5180
Epoch 4/10
391/391 [==============================] - 3s 7ms/step - loss: 1.2121 - accuracy: 0.5647
Epoch 5/10
391/391 [==============================] - 3s 8ms/step - loss: 1.0881 - accuracy: 0.6106
Epoch 6/10
391/391 [==============================] - 3s 8ms/step - loss: 0.9740 - accuracy: 0.6526
Epoch 7/10
391/391 [==============================] - 3s 7ms/step - loss: 0.8574 - accuracy: 0.6932
Epoch 8/10
391/391 [==============================] - 3s 7ms/step - loss: 0.7417 - accuracy: 0.7348
Epoch 9/10
391/391 [==============================] - 3s 7ms/step - loss: 0.6348 - accuracy: 0.7734
Epoch 10/10
391/391 [==============================] - 3s 9ms/step - loss: 0.5423 - accuracy: 0.8090
Epoch 1/10
391/391 [==============================] - 9s 9ms/step - loss: 1.8910 - accuracy: 0.3088
Epoch 2/10
391/391 [==============================] - 3s 9ms/step - loss: 1.5061 - accuracy: 0.4523
Epoch 3/10
391/391 [==============================] - 3s 8ms/step - loss: 1.3006 - accuracy: 0.5322
Epoch 4/10
391/391 [==============================] - 3s 8ms/step - loss: 1.1355 - accuracy: 0.5902
Epoch 5/10
391/391 [==============================] - 3s 8ms/step - loss: 0.9799 - accuracy: 0.6509
Epoch 6/10
391/391 [==============================] - 4s 9ms/step - loss: 0.8165 - accuracy: 0.7046
Epoch 7/10
391/391 [==============================] - 3s 8ms/step - loss: 0.6422 - accuracy: 0.7714
Epoch 8/10
391/391 [==============================] - 3s 8ms/step - loss: 0.5174 - accuracy: 0.8174
Epoch 9/10
391/391 [==============================] - 4s 9ms/step - loss: 0.4097 - accuracy: 0.8520
Epoch 10/10
391/391 [==============================] - 3s 8ms/step - loss: 0.3242 - accuracy: 0.8902
313/313 [==============================] - 1s 3ms/step - loss: 1.2853 - accuracy: 0.6097
Test Accuracy: 0.6097000241279602
Epoch 1/10
391/391 [==============================] - 5s 6ms/step - loss: 1.2110 - accuracy: 0.5754
Epoch 2/10
391/391 [==============================] - 3s 7ms/step - loss: 1.0134 - accuracy: 0.6431
Epoch 3/10
391/391 [==============================] - 2s 6ms/step - loss: 0.8692 - accuracy: 0.6975
Epoch 4/10
391/391 [==============================] - 2s 5ms/step - loss: 0.7388 - accuracy: 0.7399
Epoch 5/10
391/391 [==============================] - 2s 6ms/step - loss: 0.6231 - accuracy: 0.7769
Epoch 6/10
391/391 [==============================] - 2s 6ms/step - loss: 0.5163 - accuracy: 0.8146
Epoch 7/10
391/391 [==============================] - 2s 6ms/step - loss: 0.4332 - accuracy: 0.8486
Epoch 8/10
391/391 [==============================] - 3s 6ms/step - loss: 0.3619 - accuracy: 0.8706
Epoch 9/10
391/391 [==============================] - 2s 6ms/step - loss: 0.3173 - accuracy: 0.8884
Epoch 10/10
391/391 [==============================] - 2s 6ms/step - loss: 0.2873 - accuracy: 0.8993
Epoch 1/10
391/391 [==============================] - 9s 8ms/step - loss: 1.8229 - accuracy: 0.3330
Epoch 2/10
391/391 [==============================] - 3s 8ms/step - loss: 1.4666 - accuracy: 0.4704
Epoch 3/10
391/391 [==============================] - 3s 8ms/step - loss: 1.2827 - accuracy: 0.5398
Epoch 4/10
391/391 [==============================] - 4s 9ms/step - loss: 1.1344 - accuracy: 0.5921
Epoch 5/10
391/391 [==============================] - 3s 8ms/step - loss: 1.0053 - accuracy: 0.6436
Epoch 6/10
391/391 [==============================] - 3s 8ms/step - loss: 0.8405 - accuracy: 0.7008
Epoch 7/10
391/391 [==============================] - 3s 8ms/step - loss: 0.6999 - accuracy: 0.7500
Epoch 8/10
391/391 [==============================] - 4s 9ms/step - loss: 0.5583 - accuracy: 0.8035
Epoch 9/10
391/391 [==============================] - 3s 8ms/step - loss: 0.4250 - accuracy: 0.8493
Epoch 10/10
391/391 [==============================] - 3s 8ms/step - loss: 0.3291 - accuracy: 0.8822
313/313 [==============================] - 1s 3ms/step - loss: 1.3642 - accuracy: 0.6448
Test Accuracy: 0.6448000073432922
Epoch 1/10
391/391 [==============================] - 5s 7ms/step - loss: 1.1854 - accuracy: 0.5959
Epoch 2/10
391/391 [==============================] - 2s 6ms/step - loss: 0.9533 - accuracy: 0.6669
Epoch 3/10
391/391 [==============================] - 2s 6ms/step - loss: 0.7929 - accuracy: 0.7181
Epoch 4/10
391/391 [==============================] - 2s 6ms/step - loss: 0.6747 - accuracy: 0.7579
Epoch 5/10
391/391 [==============================] - 2s 6ms/step - loss: 0.5700 - accuracy: 0.7994
Epoch 6/10
391/391 [==============================] - 3s 8ms/step - loss: 0.4641 - accuracy: 0.8356
Epoch 7/10
391/391 [==============================] - 2s 6ms/step - loss: 0.3983 - accuracy: 0.8634
Epoch 8/10
391/391 [==============================] - 2s 6ms/step - loss: 0.3432 - accuracy: 0.8757
Epoch 9/10
391/391 [==============================] - 2s 6ms/step - loss: 0.3050 - accuracy: 0.8944
Epoch 10/10
391/391 [==============================] - 3s 7ms/step - loss: 0.2615 - accuracy: 0.9118
Epoch 1/10
391/391 [==============================] - 9s 9ms/step - loss: 1.8510 - accuracy: 0.3189
Epoch 2/10
391/391 [==============================] - 3s 8ms/step - loss: 1.5059 - accuracy: 0.4490
Epoch 3/10
391/391 [==============================] - 3s 8ms/step - loss: 1.3406 - accuracy: 0.5191
Epoch 4/10
391/391 [==============================] - 3s 8ms/step - loss: 1.1846 - accuracy: 0.5720
Epoch 5/10
391/391 [==============================] - 4s 9ms/step - loss: 1.0615 - accuracy: 0.6225
Epoch 6/10
391/391 [==============================] - 3s 8ms/step - loss: 0.9151 - accuracy: 0.6765
Epoch 7/10
391/391 [==============================] - 3s 8ms/step - loss: 0.7798 - accuracy: 0.7220
Epoch 8/10
391/391 [==============================] - 3s 8ms/step - loss: 0.6436 - accuracy: 0.7724
Epoch 9/10
391/391 [==============================] - 4s 9ms/step - loss: 0.5261 - accuracy: 0.8166
Epoch 10/10
391/391 [==============================] - 3s 8ms/step - loss: 0.4254 - accuracy: 0.8490
313/313 [==============================] - 1s 4ms/step - loss: 1.2933 - accuracy: 0.6688
Test Accuracy: 0.6687999963760376
Epoch 1/10
391/391 [==============================] - 5s 6ms/step - loss: 1.1359 - accuracy: 0.6171
Epoch 2/10
391/391 [==============================] - 2s 6ms/step - loss: 0.9024 - accuracy: 0.6867
Epoch 3/10
391/391 [==============================] - 2s 6ms/step - loss: 0.7621 - accuracy: 0.7299
Epoch 4/10
391/391 [==============================] - 3s 7ms/step - loss: 0.6448 - accuracy: 0.7753
Epoch 5/10
391/391 [==============================] - 2s 6ms/step - loss: 0.5380 - accuracy: 0.8134
Epoch 6/10
391/391 [==============================] - 2s 6ms/step - loss: 0.4528 - accuracy: 0.8383
Epoch 7/10
391/391 [==============================] - 2s 6ms/step - loss: 0.3795 - accuracy: 0.8684
Epoch 8/10
391/391 [==============================] - 2s 6ms/step - loss: 0.3236 - accuracy: 0.8867
Epoch 9/10
391/391 [==============================] - 3s 7ms/step - loss: 0.2795 - accuracy: 0.8998
Epoch 10/10
391/391 [==============================] - 2s 6ms/step - loss: 0.2589 - accuracy: 0.9089
Epoch 1/10
391/391 [==============================] - 9s 8ms/step - loss: 1.8184 - accuracy: 0.3333
Epoch 2/10
391/391 [==============================] - 3s 8ms/step - loss: 1.4608 - accuracy: 0.4709
Epoch 3/10
391/391 [==============================] - 3s 9ms/step - loss: 1.2928 - accuracy: 0.5410
Epoch 4/10
391/391 [==============================] - 4s 9ms/step - loss: 1.1555 - accuracy: 0.5838
Epoch 5/10
391/391 [==============================] - 3s 8ms/step - loss: 0.9977 - accuracy: 0.6425
Epoch 6/10
391/391 [==============================] - 3s 8ms/step - loss: 0.8720 - accuracy: 0.6879
Epoch 7/10
391/391 [==============================] - 4s 9ms/step - loss: 0.7371 - accuracy: 0.7352
Epoch 8/10
391/391 [==============================] - 3s 9ms/step - loss: 0.6047 - accuracy: 0.7845
Epoch 9/10
391/391 [==============================] - 3s 8ms/step - loss: 0.4826 - accuracy: 0.8288
Epoch 10/10
391/391 [==============================] - 3s 8ms/step - loss: 0.3780 - accuracy: 0.8679
313/313 [==============================] - 1s 4ms/step - loss: 1.2680 - accuracy: 0.6838
Test Accuracy: 0.6837999820709229

#### Batches 2

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers

# Load the CIFAR-100 dataset
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 0.1  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = x_train + tf.random.normal(shape=x_train.shape, mean=0.0, stddev=corruption_level, dtype=tf.float32)
corrupted_data = tf.clip_by_value(corrupted_data, 0.0, 1.0)

# Convert the labels to one-hot encoding
num_classes = 10
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 2 batches
n_batches = 2
batch_size = x_train.shape[0] // n_batches

# Define the CrlB regularizer
class CrlBRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Define the original CIFAR-10 model
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu'),
    layers.Dropout(0.25),
    Dense(num_classes, activation='softmax')
])

# Compile the model
# model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the original model on Task A
# model.fit(corrupted_data, y_train_onehot, batch_size=128, epochs=10, validation_data=(x_test, y_test_onehot))

# Train the model on each batch separately
for i in range(n_batches):
    start_index = i * batch_size
    end_index = (i + 1) * batch_size
    x_batch = corrupted_data[start_index:end_index]
    y_batch = y_train[start_index:end_index]
    model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    # Train the model on the current batch
    model.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    # _, test_accuracy = model.evaluate(x_test, y_test)
    # print("Test Accuracy:", test_accuracy)
# Save the weights of the original model for later use
    prior_weights = model.get_weights()

# Compute the Fisher Information matrix
    def compute_fisher(model, x, num_samples=30):
        fisher_matrix = []
        for i in range(len(model.trainable_weights)):
            fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

        for _ in range(num_samples):
            idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
            with tf.GradientTape() as tape:
                logits = model(x[idx:idx+1])
            gradients = tape.gradient(logits, model.trainable_weights)
            for i in range(len(fisher_matrix)):
                fisher_matrix[i] += tf.square(gradients[i])

        fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
        return fisher_matrix

    fisher_matrix = compute_fisher(model, corrupted_data)

# Define the new model with CrlB regularization
    model_CrlB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3),
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])

# Compile the model with CrlB regularization
    model_CrlB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on Task B with CrlB regularization
# history = model_CrlB.fit(corrupted_data, y_train_onehot, batch_size=128, epochs=10, validation_data=(x_test, y_test_onehot))
# print(history)
# Train the model on each batch separately
# for i in range(n_batches):
#     start_index = i * batch_size
#     end_index = (i + 1) * batch_size
#     x_batch = corrupted_data[start_index:end_index]
#     y_batch = y_train[start_index:end_index]

    # Train the model on the current batch
    model_CrlB.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)
# # Evaluate the model on the test set
# _, test_accuracy = model.evaluate(x_test, y_test_onehot, verbose=0)
# print("Test Accuracy:", test_accuracy)

Epoch 1/10
782/782 [==============================] - 10s 6ms/step - loss: 1.7219 - accuracy: 0.3712
Epoch 2/10
782/782 [==============================] - 4s 5ms/step - loss: 1.3343 - accuracy: 0.5191
Epoch 3/10
782/782 [==============================] - 5s 6ms/step - loss: 1.1634 - accuracy: 0.5783
Epoch 4/10
782/782 [==============================] - 4s 5ms/step - loss: 1.0515 - accuracy: 0.6257
Epoch 5/10
782/782 [==============================] - 4s 5ms/step - loss: 0.9434 - accuracy: 0.6634
Epoch 6/10
782/782 [==============================] - 5s 6ms/step - loss: 0.8581 - accuracy: 0.6914
Epoch 7/10
782/782 [==============================] - 4s 5ms/step - loss: 0.7674 - accuracy: 0.7276
Epoch 8/10
782/782 [==============================] - 4s 6ms/step - loss: 0.6945 - accuracy: 0.7502
Epoch 9/10
782/782 [==============================] - 4s 6ms/step - loss: 0.6251 - accuracy: 0.7776
Epoch 10/10
782/782 [==============================] - 4s 5ms/step - loss: 0.5511 - accuracy: 0.8003
Epoch 1/10
782/782 [==============================] - 11s 7ms/step - loss: 1.6837 - accuracy: 0.3858
Epoch 2/10
782/782 [==============================] - 6s 8ms/step - loss: 1.3090 - accuracy: 0.5270
Epoch 3/10
782/782 [==============================] - 6s 7ms/step - loss: 1.1333 - accuracy: 0.5949
Epoch 4/10
782/782 [==============================] - 6s 8ms/step - loss: 0.9944 - accuracy: 0.6412
Epoch 5/10
782/782 [==============================] - 6s 8ms/step - loss: 0.8732 - accuracy: 0.6845
Epoch 6/10
782/782 [==============================] - 6s 8ms/step - loss: 0.7707 - accuracy: 0.7269
Epoch 7/10
782/782 [==============================] - 6s 8ms/step - loss: 0.6466 - accuracy: 0.7710
Epoch 8/10
782/782 [==============================] - 6s 8ms/step - loss: 0.5474 - accuracy: 0.8059
Epoch 9/10
782/782 [==============================] - 6s 7ms/step - loss: 0.4623 - accuracy: 0.8346
Epoch 10/10
782/782 [==============================] - 6s 8ms/step - loss: 0.3912 - accuracy: 0.8612
313/313 [==============================] - 2s 6ms/step - loss: 1.1197 - accuracy: 0.6559
Test Accuracy: 0.6559000015258789
Epoch 1/10
782/782 [==============================] - 6s 5ms/step - loss: 1.0779 - accuracy: 0.6260
Epoch 2/10
782/782 [==============================] - 4s 6ms/step - loss: 0.9132 - accuracy: 0.6809
Epoch 3/10
782/782 [==============================] - 4s 6ms/step - loss: 0.8274 - accuracy: 0.7096
Epoch 4/10
782/782 [==============================] - 4s 5ms/step - loss: 0.7226 - accuracy: 0.7443
Epoch 5/10
782/782 [==============================] - 5s 6ms/step - loss: 0.6347 - accuracy: 0.7744
Epoch 6/10
782/782 [==============================] - 4s 5ms/step - loss: 0.5639 - accuracy: 0.8012
Epoch 7/10
782/782 [==============================] - 4s 5ms/step - loss: 0.4878 - accuracy: 0.8281
Epoch 8/10
782/782 [==============================] - 5s 6ms/step - loss: 0.4481 - accuracy: 0.8433
Epoch 9/10
782/782 [==============================] - 4s 5ms/step - loss: 0.4058 - accuracy: 0.8559
Epoch 10/10
782/782 [==============================] - 4s 5ms/step - loss: 0.3718 - accuracy: 0.8667
Epoch 1/10
782/782 [==============================] - 11s 8ms/step - loss: 1.6448 - accuracy: 0.3955
Epoch 2/10
782/782 [==============================] - 6s 8ms/step - loss: 1.2551 - accuracy: 0.5498
Epoch 3/10
782/782 [==============================] - 6s 7ms/step - loss: 1.0645 - accuracy: 0.6205
Epoch 4/10
782/782 [==============================] - 6s 8ms/step - loss: 0.9203 - accuracy: 0.6724
Epoch 5/10
782/782 [==============================] - 6s 7ms/step - loss: 0.7816 - accuracy: 0.7205
Epoch 6/10
782/782 [==============================] - 6s 8ms/step - loss: 0.6544 - accuracy: 0.7686
Epoch 7/10
782/782 [==============================] - 6s 8ms/step - loss: 0.5284 - accuracy: 0.8104
Epoch 8/10
782/782 [==============================] - 6s 8ms/step - loss: 0.4383 - accuracy: 0.8450
Epoch 9/10
782/782 [==============================] - 6s 7ms/step - loss: 0.3622 - accuracy: 0.8720
Epoch 10/10
782/782 [==============================] - 6s 8ms/step - loss: 0.3019 - accuracy: 0.8923
313/313 [==============================] - 1s 3ms/step - loss: 1.1422 - accuracy: 0.6869
Test Accuracy: 0.6869000196456909

#### Batches 1

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers

# Load the CIFAR-100 dataset
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 0.1  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = x_train + tf.random.normal(shape=x_train.shape, mean=0.0, stddev=corruption_level, dtype=tf.float32)
corrupted_data = tf.clip_by_value(corrupted_data, 0.0, 1.0)

# Convert the labels to one-hot encoding
num_classes = 10
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 2 batches
n_batches = 1
batch_size = x_train.shape[0] // n_batches

# Define the CrlB regularizer
class CrlBRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Define the original CIFAR-10 model
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu'),
    layers.Dropout(0.25),
    Dense(num_classes, activation='softmax')
])

# Compile the model
# model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the original model on Task A
# model.fit(corrupted_data, y_train_onehot, batch_size=128, epochs=10, validation_data=(x_test, y_test_onehot))

# Train the model on each batch separately
for i in range(n_batches):
    start_index = i * batch_size
    end_index = (i + 1) * batch_size
    x_batch = corrupted_data[start_index:end_index]
    y_batch = y_train[start_index:end_index]
    model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    # Train the model on the current batch
    model.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    # _, test_accuracy = model.evaluate(x_test, y_test)
    # print("Test Accuracy:", test_accuracy)
# Save the weights of the original model for later use
    prior_weights = model.get_weights()

# Compute the Fisher Information matrix
    def compute_fisher(model, x, num_samples=30):
        fisher_matrix = []
        for i in range(len(model.trainable_weights)):
            fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

        for _ in range(num_samples):
            idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
            with tf.GradientTape() as tape:
                logits = model(x[idx:idx+1])
            gradients = tape.gradient(logits, model.trainable_weights)
            for i in range(len(fisher_matrix)):
                fisher_matrix[i] += tf.square(gradients[i])

        fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
        return fisher_matrix

    fisher_matrix = compute_fisher(model, corrupted_data)

# Define the new model with CrlB regularization
    model_CrlB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3),
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])

# Compile the model with CrlB regularization
    model_CrlB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on Task B with CrlB regularization
# history = model_CrlB.fit(corrupted_data, y_train_onehot, batch_size=128, epochs=10, validation_data=(x_test, y_test_onehot))
# print(history)
# Train the model on each batch separately
# for i in range(n_batches):
#     start_index = i * batch_size
#     end_index = (i + 1) * batch_size
#     x_batch = corrupted_data[start_index:end_index]
#     y_batch = y_train[start_index:end_index]

    # Train the model on the current batch
    model_CrlB.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)
# # Evaluate the model on the test set
# _, test_accuracy = model.evaluate(x_test, y_test_onehot, verbose=0)
# print("Test Accuracy:", test_accuracy)

Epoch 1/10
1563/1563 [==============================] - 15s 7ms/step - loss: 1.4971 - accuracy: 0.4572
Epoch 2/10
1563/1563 [==============================] - 11s 7ms/step - loss: 1.1325 - accuracy: 0.5948
Epoch 3/10
1563/1563 [==============================] - 10s 6ms/step - loss: 0.9783 - accuracy: 0.6537
Epoch 4/10
1563/1563 [==============================] - 9s 6ms/step - loss: 0.8758 - accuracy: 0.6895
Epoch 5/10
1563/1563 [==============================] - 9s 6ms/step - loss: 0.7971 - accuracy: 0.7198
Epoch 6/10
1563/1563 [==============================] - 9s 6ms/step - loss: 0.7290 - accuracy: 0.7432
Epoch 7/10
1563/1563 [==============================] - 9s 6ms/step - loss: 0.6713 - accuracy: 0.7621
Epoch 8/10
1563/1563 [==============================] - 9s 6ms/step - loss: 0.6210 - accuracy: 0.7806
Epoch 9/10
1563/1563 [==============================] - 9s 6ms/step - loss: 0.5799 - accuracy: 0.7939
Epoch 10/10
1563/1563 [==============================] - 9s 6ms/step - loss: 0.5464 - accuracy: 0.8066
Epoch 1/10
1563/1563 [==============================] - 18s 8ms/step - loss: 1.4852 - accuracy: 0.4586
Epoch 2/10
1563/1563 [==============================] - 12s 8ms/step - loss: 1.1063 - accuracy: 0.6060
Epoch 3/10
1563/1563 [==============================] - 12s 8ms/step - loss: 0.9461 - accuracy: 0.6652
Epoch 4/10
1563/1563 [==============================] - 13s 8ms/step - loss: 0.8230 - accuracy: 0.7078
Epoch 5/10
1563/1563 [==============================] - 12s 8ms/step - loss: 0.7233 - accuracy: 0.7445
Epoch 6/10
1563/1563 [==============================] - 12s 8ms/step - loss: 0.6320 - accuracy: 0.7754
Epoch 7/10
1563/1563 [==============================] - 12s 8ms/step - loss: 0.5545 - accuracy: 0.8036
Epoch 8/10
1563/1563 [==============================] - 12s 8ms/step - loss: 0.4862 - accuracy: 0.8283
Epoch 9/10
1563/1563 [==============================] - 12s 8ms/step - loss: 0.4337 - accuracy: 0.8463
Epoch 10/10
1563/1563 [==============================] - 12s 8ms/step - loss: 0.3914 - accuracy: 0.8621
313/313 [==============================] - 1s 3ms/step - loss: 0.8748 - accuracy: 0.7133
Test Accuracy: 0.7132999897003174

# C3 foldwise

## Folds 2

### MNIST

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.regularizers import Regularizer
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import KFold
from tensorflow.keras import backend as K
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    f_accum = []
    for i in range(len(model.weights)):
        f_accum.append(np.zeros(K.int_shape(model.weights[i])))
    f_accum = np.array(f_accum)
    for _ in range(num_samples):
        idx = np.random.randint(0, x.shape[0])
        with tf.GradientTape() as tape:
            model_output = model(x[idx:idx+1])
        grads = tape.gradient(model_output, model.weights)
        for i in range(len(grads)):
            f_accum[i] += tf.square(grads[i])
    f_accum /= num_samples
    return f_accum

# Define the CrlB regularizer
class CrlBRegularizer(Regularizer):
    def __init__(self, fisher, prior_weights, lambda_=0.1):
        self.fisher = fisher
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i in range(len(self.fisher)):
            regularization += self.lambda_ * tf.reduce_sum(self.fisher[i] * tf.square(x - self.prior_weights[i]))
        return regularization

# Load the MNIST dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.reshape(-1, 28 * 28) / 255.0
x_test = x_test.reshape(-1, 28 * 28) / 255.0
y_train_onehot = tf.keras.utils.to_categorical(y_train, num_classes=10)
y_test_onehot = tf.keras.utils.to_categorical(y_test, num_classes=10)

# Number of K-folds
K = 2

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)

# Initialize the list to store test accuracies
accuracies = []

# Perform K-fold cross-validation
for train_index, test_index in kf.split(x_train, y_train_onehot):
    x_train_fold, x_test_fold = x_train[train_index], x_train[test_index]
    y_train_fold, y_test_fold = y_train_onehot[train_index], y_train_onehot[test_index]

# Task A: Original Fashion MNIST model
    model = Sequential([
    Dense(128, activation='relu', input_shape=(784,)),
    Dense(10, activation='softmax')
])
    model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
    model.save_weights('FashionMNIST_A.h5')

# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]

# Task B: Fashion MNIST with CrlB regularization
    model_CrlBB = Sequential([
        Dense(128, activation='relu', input_shape=(784,), kernel_regularizer=CrlBRegularizer(fisher_info[0], model.weights[0])),
        Dense(10, activation='softmax', kernel_regularizer=CrlBRegularizer(fisher_info[1], model.weights[1]))
    ])
    model_CrlBB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    model_CrlBB.load_weights('FashionMNIST_A.h5')
    model_CrlBB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlB_acc = 100 * model_CrlBB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlB method Accuracy: %.2f%%" % B_CrlB_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
235/235 [==============================] - 5s 13ms/step - loss: 0.4979 - accuracy: 0.8630 - val_loss: 0.2857 - val_accuracy: 0.9223
Epoch 2/10
235/235 [==============================] - 3s 12ms/step - loss: 0.2335 - accuracy: 0.9341 - val_loss: 0.2223 - val_accuracy: 0.9359
Epoch 3/10
235/235 [==============================] - 3s 12ms/step - loss: 0.1765 - accuracy: 0.9497 - val_loss: 0.1895 - val_accuracy: 0.9474
Epoch 4/10
235/235 [==============================] - 2s 8ms/step - loss: 0.1425 - accuracy: 0.9592 - val_loss: 0.1593 - val_accuracy: 0.9543
Epoch 5/10
235/235 [==============================] - 2s 10ms/step - loss: 0.1172 - accuracy: 0.9666 - val_loss: 0.1451 - val_accuracy: 0.9585
Epoch 6/10
235/235 [==============================] - 2s 9ms/step - loss: 0.0970 - accuracy: 0.9734 - val_loss: 0.1375 - val_accuracy: 0.9604
Epoch 7/10
235/235 [==============================] - 2s 8ms/step - loss: 0.0809 - accuracy: 0.9781 - val_loss: 0.1295 - val_accuracy: 0.9631
Epoch 8/10
235/235 [==============================] - 3s 12ms/step - loss: 0.0696 - accuracy: 0.9810 - val_loss: 0.1243 - val_accuracy: 0.9647
Epoch 9/10
235/235 [==============================] - 2s 10ms/step - loss: 0.0587 - accuracy: 0.9847 - val_loss: 0.1181 - val_accuracy: 0.9662
Epoch 10/10
235/235 [==============================] - 2s 8ms/step - loss: 0.0508 - accuracy: 0.9857 - val_loss: 0.1139 - val_accuracy: 0.9666
Epoch 1/10
235/235 [==============================] - 101s 101ms/step - loss: 0.0461 - accuracy: 0.9875 - val_loss: 0.1116 - val_accuracy: 0.9678
Epoch 2/10
235/235 [==============================] - 4s 18ms/step - loss: 0.0389 - accuracy: 0.9895 - val_loss: 0.1129 - val_accuracy: 0.9678
Epoch 3/10
235/235 [==============================] - 3s 13ms/step - loss: 0.0300 - accuracy: 0.9931 - val_loss: 0.1139 - val_accuracy: 0.9673
Epoch 4/10
235/235 [==============================] - 3s 13ms/step - loss: 0.0258 - accuracy: 0.9943 - val_loss: 0.1095 - val_accuracy: 0.9698
Epoch 5/10
235/235 [==============================] - 3s 13ms/step - loss: 0.0218 - accuracy: 0.9954 - val_loss: 0.1154 - val_accuracy: 0.9666
Epoch 6/10
235/235 [==============================] - 4s 17ms/step - loss: 0.0178 - accuracy: 0.9971 - val_loss: 0.1105 - val_accuracy: 0.9693
Epoch 7/10
235/235 [==============================] - 4s 18ms/step - loss: 0.0159 - accuracy: 0.9974 - val_loss: 0.1208 - val_accuracy: 0.9668
Epoch 8/10
235/235 [==============================] - 4s 18ms/step - loss: 0.0128 - accuracy: 0.9984 - val_loss: 0.1091 - val_accuracy: 0.9708
Epoch 9/10
235/235 [==============================] - 4s 17ms/step - loss: 0.0104 - accuracy: 0.9987 - val_loss: 0.1136 - val_accuracy: 0.9704
Epoch 10/10
235/235 [==============================] - 3s 14ms/step - loss: 0.0087 - accuracy: 0.9992 - val_loss: 0.1131 - val_accuracy: 0.9703
938/938 [==============================] - 3s 3ms/step - loss: 0.1139 - accuracy: 0.9666
938/938 [==============================] - 7s 7ms/step - loss: 0.1131 - accuracy: 0.9703
938/938 [==============================] - 3s 4ms/step - loss: 0.1139 - accuracy: 0.9666
Test Accuracy: 0.9666000008583069
Task A Original Accuracy: 96.66%
Task B EWC method Accuracy: 97.03%
Epoch 1/10
235/235 [==============================] - 4s 12ms/step - loss: 0.4809 - accuracy: 0.8724 - val_loss: 0.2717 - val_accuracy: 0.9218
Epoch 2/10
235/235 [==============================] - 2s 7ms/step - loss: 0.2269 - accuracy: 0.9367 - val_loss: 0.2058 - val_accuracy: 0.9409
Epoch 3/10
235/235 [==============================] - 2s 10ms/step - loss: 0.1722 - accuracy: 0.9512 - val_loss: 0.1822 - val_accuracy: 0.9471
Epoch 4/10
235/235 [==============================] - 2s 10ms/step - loss: 0.1363 - accuracy: 0.9623 - val_loss: 0.1531 - val_accuracy: 0.9554
Epoch 5/10
235/235 [==============================] - 2s 10ms/step - loss: 0.1105 - accuracy: 0.9705 - val_loss: 0.1387 - val_accuracy: 0.9580
Epoch 6/10
235/235 [==============================] - 2s 7ms/step - loss: 0.0927 - accuracy: 0.9740 - val_loss: 0.1330 - val_accuracy: 0.9604
Epoch 7/10
235/235 [==============================] - 2s 10ms/step - loss: 0.0770 - accuracy: 0.9787 - val_loss: 0.1207 - val_accuracy: 0.9642
Epoch 8/10
235/235 [==============================] - 2s 7ms/step - loss: 0.0656 - accuracy: 0.9828 - val_loss: 0.1210 - val_accuracy: 0.9637
Epoch 9/10
235/235 [==============================] - 2s 10ms/step - loss: 0.0568 - accuracy: 0.9852 - val_loss: 0.1151 - val_accuracy: 0.9648
Epoch 10/10
235/235 [==============================] - 2s 10ms/step - loss: 0.0488 - accuracy: 0.9874 - val_loss: 0.1105 - val_accuracy: 0.9670
Epoch 1/10
235/235 [==============================] - 97s 74ms/step - loss: 0.0453 - accuracy: 0.9877 - val_loss: 0.1162 - val_accuracy: 0.9661
Epoch 2/10
235/235 [==============================] - 2s 11ms/step - loss: 0.0361 - accuracy: 0.9911 - val_loss: 0.1081 - val_accuracy: 0.9677
Epoch 3/10
235/235 [==============================] - 3s 13ms/step - loss: 0.0305 - accuracy: 0.9931 - val_loss: 0.1094 - val_accuracy: 0.9679
Epoch 4/10
235/235 [==============================] - 2s 10ms/step - loss: 0.0256 - accuracy: 0.9943 - val_loss: 0.1062 - val_accuracy: 0.9692
Epoch 5/10
235/235 [==============================] - 2s 8ms/step - loss: 0.0208 - accuracy: 0.9957 - val_loss: 0.1046 - val_accuracy: 0.9698
Epoch 6/10
235/235 [==============================] - 2s 10ms/step - loss: 0.0172 - accuracy: 0.9969 - val_loss: 0.1049 - val_accuracy: 0.9699
Epoch 7/10
235/235 [==============================] - 2s 10ms/step - loss: 0.0135 - accuracy: 0.9983 - val_loss: 0.1077 - val_accuracy: 0.9702
Epoch 8/10
235/235 [==============================] - 3s 11ms/step - loss: 0.0122 - accuracy: 0.9983 - val_loss: 0.1052 - val_accuracy: 0.9716
Epoch 9/10
235/235 [==============================] - 2s 9ms/step - loss: 0.0095 - accuracy: 0.9991 - val_loss: 0.1125 - val_accuracy: 0.9702
Epoch 10/10
235/235 [==============================] - 2s 8ms/step - loss: 0.0091 - accuracy: 0.9989 - val_loss: 0.1091 - val_accuracy: 0.9706
938/938 [==============================] - 2s 2ms/step - loss: 0.1105 - accuracy: 0.9670
938/938 [==============================] - 5s 5ms/step - loss: 0.1091 - accuracy: 0.9706
938/938 [==============================] - 2s 2ms/step - loss: 0.1105 - accuracy: 0.9670
Test Accuracy: 0.967033326625824
Task A Original Accuracy: 96.70%
Task B EWC method Accuracy: 97.06%
Fold-1: 96.66%
Fold-2: 96.70%

### PermutedMNIST

In [ ]:
import numpy as np
import keras
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

# Create a permutation index for the pixel positions
num_pixels = x_train.shape[1] * x_train.shape[2]
perm_index = np.random.permutation(num_pixels)

# Permute the pixels for training and test sets
x_train_permuted = x_train.reshape(-1, num_pixels)[:, perm_index].reshape(-1, x_train.shape[1], x_train.shape[2])
x_test_permuted = x_test.reshape(-1, num_pixels)[:, perm_index].reshape(-1, x_test.shape[1], x_test.shape[2])
x = np.concatenate((x_train_permuted, x_test_permuted), axis=0)
y = np.concatenate((y_train, y_test), axis=0)

In [ ]:
import tensorflow as tf
x = x.reshape(-1, 28 * 28) / 255.0
y = tf.keras.utils.to_categorical(y, num_classes=10)

In [ ]:
print(x.shape, y.shape, y_test.shape)

(70000, 784) (70000, 10) (10000,)

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.regularizers import Regularizer
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import KFold
from tensorflow.keras import backend as K
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    f_accum = []
    for i in range(len(model.weights)):
        f_accum.append(np.zeros(K.int_shape(model.weights[i])))
    f_accum = np.array(f_accum)
    for _ in range(num_samples):
        idx = np.random.randint(0, x.shape[0])
        with tf.GradientTape() as tape:
            model_output = model(x[idx:idx+1])
        grads = tape.gradient(model_output, model.weights)
        for i in range(len(grads)):
            f_accum[i] += tf.square(grads[i])
    f_accum /= num_samples
    return f_accum

# Define the CrlB regularizer
class CrlBRegularizer(Regularizer):
    def __init__(self, fisher, prior_weights, lambda_=0.1):
        self.fisher = fisher
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i in range(len(self.fisher)):
            regularization += self.lambda_ * tf.reduce_sum(self.fisher[i] * tf.square(x - self.prior_weights[i]))
        return regularization


# Number of K-folds
K = 2

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)
# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []

# Perform K-fold cross-validation
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]

# Task A: Original Fashion MNIST model
    model = Sequential([
    Dense(128, activation='relu', input_shape=(784,)),
    Dense(10, activation='softmax')
])
    model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
    model.save_weights('FashionMNIST_A.h5')

# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]

# Task B: Fashion MNIST with CrlB regularization
    model_CrlBB = Sequential([
        Dense(128, activation='relu', input_shape=(784,), kernel_regularizer=CrlBRegularizer(fisher_info[0], model.weights[0])),
        Dense(10, activation='softmax', kernel_regularizer=CrlBRegularizer(fisher_info[1], model.weights[1]))
    ])
    model_CrlBB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    model_CrlBB.load_weights('FashionMNIST_A.h5')
    model_CrlBB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlB_acc = 100 * model_CrlBB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlB method Accuracy: %.2f%%" % B_CrlB_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
274/274 [==============================] - 10s 11ms/step - loss: 0.4439 - accuracy: 0.8766 - val_loss: 0.2594 - val_accuracy: 0.9275
Epoch 2/10
274/274 [==============================] - 3s 10ms/step - loss: 0.2175 - accuracy: 0.9385 - val_loss: 0.1997 - val_accuracy: 0.9446
Epoch 3/10
274/274 [==============================] - 2s 7ms/step - loss: 0.1627 - accuracy: 0.9543 - val_loss: 0.1715 - val_accuracy: 0.9513
Epoch 4/10
274/274 [==============================] - 2s 9ms/step - loss: 0.1289 - accuracy: 0.9635 - val_loss: 0.1453 - val_accuracy: 0.9578
Epoch 5/10
274/274 [==============================] - 3s 11ms/step - loss: 0.1054 - accuracy: 0.9703 - val_loss: 0.1360 - val_accuracy: 0.9602
Epoch 6/10
274/274 [==============================] - 2s 9ms/step - loss: 0.0873 - accuracy: 0.9749 - val_loss: 0.1210 - val_accuracy: 0.9654
Epoch 7/10
274/274 [==============================] - 2s 9ms/step - loss: 0.0720 - accuracy: 0.9799 - val_loss: 0.1190 - val_accuracy: 0.9649
Epoch 8/10
274/274 [==============================] - 2s 7ms/step - loss: 0.0627 - accuracy: 0.9825 - val_loss: 0.1080 - val_accuracy: 0.9674
Epoch 9/10
274/274 [==============================] - 2s 7ms/step - loss: 0.0520 - accuracy: 0.9863 - val_loss: 0.1058 - val_accuracy: 0.9687
Epoch 10/10
274/274 [==============================] - 3s 10ms/step - loss: 0.0444 - accuracy: 0.9887 - val_loss: 0.1029 - val_accuracy: 0.9691
Epoch 1/10
274/274 [==============================] - 99s 82ms/step - loss: 0.0407 - accuracy: 0.9889 - val_loss: 0.1009 - val_accuracy: 0.9699
Epoch 2/10
274/274 [==============================] - 5s 17ms/step - loss: 0.0331 - accuracy: 0.9913 - val_loss: 0.1022 - val_accuracy: 0.9695
Epoch 3/10
274/274 [==============================] - 4s 16ms/step - loss: 0.0261 - accuracy: 0.9941 - val_loss: 0.1046 - val_accuracy: 0.9697
Epoch 4/10
274/274 [==============================] - 4s 15ms/step - loss: 0.0234 - accuracy: 0.9945 - val_loss: 0.0981 - val_accuracy: 0.9711
Epoch 5/10
274/274 [==============================] - 3s 13ms/step - loss: 0.0190 - accuracy: 0.9959 - val_loss: 0.1047 - val_accuracy: 0.9703
Epoch 6/10
274/274 [==============================] - 4s 13ms/step - loss: 0.0157 - accuracy: 0.9970 - val_loss: 0.1008 - val_accuracy: 0.9710
Epoch 7/10
274/274 [==============================] - 7s 26ms/step - loss: 0.0127 - accuracy: 0.9979 - val_loss: 0.0983 - val_accuracy: 0.9717
Epoch 8/10
274/274 [==============================] - 4s 13ms/step - loss: 0.0105 - accuracy: 0.9986 - val_loss: 0.0999 - val_accuracy: 0.9727
Epoch 9/10
274/274 [==============================] - 4s 13ms/step - loss: 0.0094 - accuracy: 0.9985 - val_loss: 0.1010 - val_accuracy: 0.9723
Epoch 10/10
274/274 [==============================] - 5s 18ms/step - loss: 0.0067 - accuracy: 0.9996 - val_loss: 0.1031 - val_accuracy: 0.9727
1094/1094 [==============================] - 4s 4ms/step - loss: 0.1029 - accuracy: 0.9691
1094/1094 [==============================] - 8s 7ms/step - loss: 0.1031 - accuracy: 0.9727
1094/1094 [==============================] - 4s 4ms/step - loss: 0.1029 - accuracy: 0.9691
Test Accuracy: 0.9690571427345276
Task A Original Accuracy: 96.91%
Task B EWC method Accuracy: 97.27%
Epoch 1/10
274/274 [==============================] - 5s 11ms/step - loss: 0.4450 - accuracy: 0.8802 - val_loss: 0.2551 - val_accuracy: 0.9276
Epoch 2/10
274/274 [==============================] - 2s 9ms/step - loss: 0.2103 - accuracy: 0.9405 - val_loss: 0.1876 - val_accuracy: 0.9467
Epoch 3/10
274/274 [==============================] - 3s 9ms/step - loss: 0.1561 - accuracy: 0.9557 - val_loss: 0.1609 - val_accuracy: 0.9522
Epoch 4/10
274/274 [==============================] - 2s 8ms/step - loss: 0.1242 - accuracy: 0.9641 - val_loss: 0.1501 - val_accuracy: 0.9565
Epoch 5/10
274/274 [==============================] - 3s 10ms/step - loss: 0.1020 - accuracy: 0.9715 - val_loss: 0.1230 - val_accuracy: 0.9637
Epoch 6/10
274/274 [==============================] - 2s 7ms/step - loss: 0.0849 - accuracy: 0.9761 - val_loss: 0.1182 - val_accuracy: 0.9647
Epoch 7/10
274/274 [==============================] - 2s 9ms/step - loss: 0.0718 - accuracy: 0.9803 - val_loss: 0.1098 - val_accuracy: 0.9672
Epoch 8/10
274/274 [==============================] - 2s 7ms/step - loss: 0.0619 - accuracy: 0.9833 - val_loss: 0.1130 - val_accuracy: 0.9654
Epoch 9/10
274/274 [==============================] - 2s 8ms/step - loss: 0.0522 - accuracy: 0.9857 - val_loss: 0.1000 - val_accuracy: 0.9704
Epoch 10/10
274/274 [==============================] - 3s 10ms/step - loss: 0.0434 - accuracy: 0.9887 - val_loss: 0.1010 - val_accuracy: 0.9699
Epoch 1/10
274/274 [==============================] - 112s 111ms/step - loss: 0.0411 - accuracy: 0.9887 - val_loss: 0.0989 - val_accuracy: 0.9707
Epoch 2/10
274/274 [==============================] - 10s 37ms/step - loss: 0.0331 - accuracy: 0.9914 - val_loss: 0.1032 - val_accuracy: 0.9693
Epoch 3/10
274/274 [==============================] - 9s 32ms/step - loss: 0.0273 - accuracy: 0.9937 - val_loss: 0.0961 - val_accuracy: 0.9717
Epoch 4/10
274/274 [==============================] - 9s 33ms/step - loss: 0.0233 - accuracy: 0.9947 - val_loss: 0.0984 - val_accuracy: 0.9725
Epoch 5/10
274/274 [==============================] - 9s 33ms/step - loss: 0.0201 - accuracy: 0.9959 - val_loss: 0.0980 - val_accuracy: 0.9724
Epoch 6/10
274/274 [==============================] - 10s 37ms/step - loss: 0.0158 - accuracy: 0.9973 - val_loss: 0.0994 - val_accuracy: 0.9726
Epoch 7/10
274/274 [==============================] - 8s 31ms/step - loss: 0.0138 - accuracy: 0.9981 - val_loss: 0.1002 - val_accuracy: 0.9726
Epoch 8/10
274/274 [==============================] - 11s 40ms/step - loss: 0.0111 - accuracy: 0.9985 - val_loss: 0.1049 - val_accuracy: 0.9714
Epoch 9/10
274/274 [==============================] - 9s 33ms/step - loss: 0.0102 - accuracy: 0.9985 - val_loss: 0.1014 - val_accuracy: 0.9735
Epoch 10/10
274/274 [==============================] - 10s 38ms/step - loss: 0.0080 - accuracy: 0.9991 - val_loss: 0.1052 - val_accuracy: 0.9730
1094/1094 [==============================] - 3s 2ms/step - loss: 0.1010 - accuracy: 0.9699
1094/1094 [==============================] - 15s 14ms/step - loss: 0.1052 - accuracy: 0.9730
1094/1094 [==============================] - 3s 2ms/step - loss: 0.1010 - accuracy: 0.9699
Test Accuracy: 0.9699142575263977
Task A Original Accuracy: 96.99%
Task B EWC method Accuracy: 97.30%
Fold-1: 96.91%
Fold-2: 96.99%

### FashionMNIST

In [ ]:
import numpy as np
import keras
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
(x_train, y_train), (x_test, y_test) = keras.datasets.fashion_mnist.load_data()
# Concatenate the entire dataset
x = np.concatenate((x_train, x_test), axis=0)
y = np.concatenate((y_train, y_test), axis=0)

In [ ]:
import tensorflow as tf
x = x.reshape(-1, 28 * 28) / 255.0
y = tf.keras.utils.to_categorical(y, num_classes=10)

In [ ]:
print(x.shape, y.shape, y_test.shape)

(70000, 784) (70000, 10) (10000,)

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.regularizers import Regularizer
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import KFold
from tensorflow.keras import backend as K
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    f_accum = []
    for i in range(len(model.weights)):
        f_accum.append(np.zeros(K.int_shape(model.weights[i])))
    f_accum = np.array(f_accum)
    for _ in range(num_samples):
        idx = np.random.randint(0, x.shape[0])
        with tf.GradientTape() as tape:
            model_output = model(x[idx:idx+1])
        grads = tape.gradient(model_output, model.weights)
        for i in range(len(grads)):
            f_accum[i] += tf.square(grads[i])
    f_accum /= num_samples
    return f_accum

# Define the CrlB regularizer
class CrlBRegularizer(Regularizer):
    def __init__(self, fisher, prior_weights, lambda_=0.1):
        self.fisher = fisher
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i in range(len(self.fisher)):
            regularization += self.lambda_ * tf.reduce_sum(self.fisher[i] * tf.square(x - self.prior_weights[i]))
        return regularization


# Number of K-folds
K = 2

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)
# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []

# Perform K-fold cross-validation
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]

# Task A: Original Fashion MNIST model
    model = Sequential([
    Dense(128, activation='relu', input_shape=(784,)),
    Dense(10, activation='softmax')
])
    model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
    model.save_weights('FashionMNIST_A.h5')

# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]

# Task B: Fashion MNIST with CrlB regularization
    model_CrlBB = Sequential([
        Dense(128, activation='relu', input_shape=(784,), kernel_regularizer=CrlBRegularizer(fisher_info[0], model.weights[0])),
        Dense(10, activation='softmax', kernel_regularizer=CrlBRegularizer(fisher_info[1], model.weights[1]))
    ])
    model_CrlBB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    model_CrlBB.load_weights('FashionMNIST_A.h5')
    model_CrlBB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlB_acc = 100 * model_CrlBB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlB method Accuracy: %.2f%%" % B_CrlB_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
274/274 [==============================] - 6s 11ms/step - loss: 0.6374 - accuracy: 0.7835 - val_loss: 0.5076 - val_accuracy: 0.8231
Epoch 2/10
274/274 [==============================] - 2s 8ms/step - loss: 0.4487 - accuracy: 0.8453 - val_loss: 0.4220 - val_accuracy: 0.8526
Epoch 3/10
274/274 [==============================] - 3s 10ms/step - loss: 0.4054 - accuracy: 0.8555 - val_loss: 0.4044 - val_accuracy: 0.8574
Epoch 4/10
274/274 [==============================] - 2s 8ms/step - loss: 0.3811 - accuracy: 0.8653 - val_loss: 0.3856 - val_accuracy: 0.8635
Epoch 5/10
274/274 [==============================] - 2s 9ms/step - loss: 0.3570 - accuracy: 0.8735 - val_loss: 0.3656 - val_accuracy: 0.8714
Epoch 6/10
274/274 [==============================] - 2s 9ms/step - loss: 0.3388 - accuracy: 0.8792 - val_loss: 0.3582 - val_accuracy: 0.8736
Epoch 7/10
274/274 [==============================] - 2s 9ms/step - loss: 0.3275 - accuracy: 0.8814 - val_loss: 0.3552 - val_accuracy: 0.8747
Epoch 8/10
274/274 [==============================] - 3s 10ms/step - loss: 0.3154 - accuracy: 0.8859 - val_loss: 0.3554 - val_accuracy: 0.8742
Epoch 9/10
274/274 [==============================] - 3s 11ms/step - loss: 0.3012 - accuracy: 0.8921 - val_loss: 0.3403 - val_accuracy: 0.8797
Epoch 10/10
274/274 [==============================] - 3s 10ms/step - loss: 0.2913 - accuracy: 0.8946 - val_loss: 0.3564 - val_accuracy: 0.8710
Epoch 1/10
274/274 [==============================] - 118s 140ms/step - loss: 0.2845 - accuracy: 0.8963 - val_loss: 0.3326 - val_accuracy: 0.8805
Epoch 2/10
274/274 [==============================] - 19s 70ms/step - loss: 0.2707 - accuracy: 0.9026 - val_loss: 0.3358 - val_accuracy: 0.8799
Epoch 3/10
274/274 [==============================] - 19s 69ms/step - loss: 0.2621 - accuracy: 0.9060 - val_loss: 0.3373 - val_accuracy: 0.8792
Epoch 4/10
274/274 [==============================] - 22s 79ms/step - loss: 0.2563 - accuracy: 0.9068 - val_loss: 0.3271 - val_accuracy: 0.8830
Epoch 5/10
274/274 [==============================] - 22s 80ms/step - loss: 0.2491 - accuracy: 0.9095 - val_loss: 0.3426 - val_accuracy: 0.8789
Epoch 6/10
274/274 [==============================] - 22s 80ms/step - loss: 0.2447 - accuracy: 0.9099 - val_loss: 0.3170 - val_accuracy: 0.8876
Epoch 7/10
274/274 [==============================] - 18s 66ms/step - loss: 0.2348 - accuracy: 0.9141 - val_loss: 0.3304 - val_accuracy: 0.8839
Epoch 8/10
274/274 [==============================] - 22s 81ms/step - loss: 0.2330 - accuracy: 0.9133 - val_loss: 0.3175 - val_accuracy: 0.8870
Epoch 9/10
274/274 [==============================] - 14s 51ms/step - loss: 0.2225 - accuracy: 0.9176 - val_loss: 0.3195 - val_accuracy: 0.8879
Epoch 10/10
274/274 [==============================] - 12s 43ms/step - loss: 0.2184 - accuracy: 0.9194 - val_loss: 0.3240 - val_accuracy: 0.8842
1094/1094 [==============================] - 3s 2ms/step - loss: 0.3564 - accuracy: 0.8710
1094/1094 [==============================] - 19s 18ms/step - loss: 0.3240 - accuracy: 0.8842
1094/1094 [==============================] - 3s 2ms/step - loss: 0.3564 - accuracy: 0.8710
Test Accuracy: 0.8709714412689209
Task A Original Accuracy: 87.10%
Task B EWC method Accuracy: 88.42%
Epoch 1/10
274/274 [==============================] - 3s 7ms/step - loss: 0.6120 - accuracy: 0.7900 - val_loss: 0.4583 - val_accuracy: 0.8428
Epoch 2/10
274/274 [==============================] - 1s 5ms/step - loss: 0.4419 - accuracy: 0.8464 - val_loss: 0.4343 - val_accuracy: 0.8495
Epoch 3/10
274/274 [==============================] - 1s 5ms/step - loss: 0.3970 - accuracy: 0.8605 - val_loss: 0.3999 - val_accuracy: 0.8598
Epoch 4/10
274/274 [==============================] - 1s 5ms/step - loss: 0.3746 - accuracy: 0.8683 - val_loss: 0.3836 - val_accuracy: 0.8626
Epoch 5/10
274/274 [==============================] - 1s 5ms/step - loss: 0.3515 - accuracy: 0.8757 - val_loss: 0.3658 - val_accuracy: 0.8691
Epoch 6/10
274/274 [==============================] - 1s 5ms/step - loss: 0.3378 - accuracy: 0.8787 - val_loss: 0.3598 - val_accuracy: 0.8701
Epoch 7/10
274/274 [==============================] - 2s 6ms/step - loss: 0.3216 - accuracy: 0.8858 - val_loss: 0.3764 - val_accuracy: 0.8665
Epoch 8/10
274/274 [==============================] - 2s 6ms/step - loss: 0.3103 - accuracy: 0.8887 - val_loss: 0.3765 - val_accuracy: 0.8649
Epoch 9/10
274/274 [==============================] - 1s 5ms/step - loss: 0.3007 - accuracy: 0.8929 - val_loss: 0.3522 - val_accuracy: 0.8743
Epoch 10/10
274/274 [==============================] - 1s 5ms/step - loss: 0.2864 - accuracy: 0.8963 - val_loss: 0.3627 - val_accuracy: 0.8701
Epoch 1/10
274/274 [==============================] - 62s 50ms/step - loss: 0.2843 - accuracy: 0.8978 - val_loss: 0.3657 - val_accuracy: 0.8720
Epoch 2/10
274/274 [==============================] - 2s 8ms/step - loss: 0.2715 - accuracy: 0.9023 - val_loss: 0.3455 - val_accuracy: 0.8770
Epoch 3/10
274/274 [==============================] - 3s 10ms/step - loss: 0.2663 - accuracy: 0.9037 - val_loss: 0.3267 - val_accuracy: 0.8836
Epoch 4/10
274/274 [==============================] - 3s 10ms/step - loss: 0.2564 - accuracy: 0.9068 - val_loss: 0.3382 - val_accuracy: 0.8793
Epoch 5/10
274/274 [==============================] - 3s 11ms/step - loss: 0.2464 - accuracy: 0.9097 - val_loss: 0.3252 - val_accuracy: 0.8852
Epoch 6/10
274/274 [==============================] - 3s 9ms/step - loss: 0.2423 - accuracy: 0.9118 - val_loss: 0.3328 - val_accuracy: 0.8803
Epoch 7/10
274/274 [==============================] - 2s 8ms/step - loss: 0.2406 - accuracy: 0.9122 - val_loss: 0.3300 - val_accuracy: 0.8830
Epoch 8/10
274/274 [==============================] - 2s 8ms/step - loss: 0.2290 - accuracy: 0.9176 - val_loss: 0.3432 - val_accuracy: 0.8785
Epoch 9/10
274/274 [==============================] - 3s 10ms/step - loss: 0.2251 - accuracy: 0.9171 - val_loss: 0.3426 - val_accuracy: 0.8806
Epoch 10/10
274/274 [==============================] - 3s 9ms/step - loss: 0.2172 - accuracy: 0.9211 - val_loss: 0.3361 - val_accuracy: 0.8830
1094/1094 [==============================] - 3s 2ms/step - loss: 0.3627 - accuracy: 0.8701
1094/1094 [==============================] - 5s 5ms/step - loss: 0.3361 - accuracy: 0.8830
1094/1094 [==============================] - 3s 2ms/step - loss: 0.3627 - accuracy: 0.8701
Test Accuracy: 0.8701428771018982
Task A Original Accuracy: 87.01%
Task B EWC method Accuracy: 88.30%
Fold-1: 87.10%
Fold-2: 87.01%

### Kuzushiji-MNIST

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import KFold
# from tensorflow.keras.datasets import kmnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam
import tensorflow_datasets as tfds

from sklearn.model_selection import train_test_split

# (x_train, y_train), (x_test, y_test) = kmnist.load_data()


dataset = tfds.load('kmnist')
train_o, test_o = dataset['train'], dataset['test']

train_numpy = np.vstack(tfds.as_numpy(train_o))
test_numpy = np.vstack(tfds.as_numpy(test_o))

train_x = np.array(list(map(lambda x: x[0]['image'], train_numpy)))
train_y = np.array(list(map(lambda x: x[0]['label'], train_numpy)))

test_x = np.array(list(map(lambda x: x[0]['image'], test_numpy)))
test_y = np.array(list(map(lambda x: x[0]['label'], test_numpy)))

train = np.concatenate((train_x,test_x), axis = 0)
test = np.concatenate((train_y,test_y),axis = 0)

print("it is whole train size ****:\t", train_x.shape)

x_train, x_test, y_train, y_test = train_x, test_x, train_y, test_y
# Concatenate the entire dataset
x = np.concatenate((x_train, x_test), axis=0)
y = np.concatenate((y_train, y_test), axis=0)

Downloading and preparing dataset 20.26 MiB (download: 20.26 MiB, generated: 31.76 MiB, total: 52.02 MiB) to /root/tensorflow_datasets/kmnist/3.0.1...

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

Generating splits...:   0%|          | 0/2 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/60000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/kmnist/3.0.1.incomplete189RXF/kmnist-train.tfrecord*...:   0%|          | …

Generating test examples...:   0%|          | 0/10000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/kmnist/3.0.1.incomplete189RXF/kmnist-test.tfrecord*...:   0%|          | 0…

Dataset kmnist downloaded and prepared to /root/tensorflow_datasets/kmnist/3.0.1. Subsequent calls will reuse this data.

<ipython-input-1-ae6edded5cbd>:19: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  train_numpy = np.vstack(tfds.as_numpy(train_o))
<ipython-input-1-ae6edded5cbd>:20: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  test_numpy = np.vstack(tfds.as_numpy(test_o))

it is whole train size ****:	 (60000, 28, 28, 1)

In [ ]:
import tensorflow as tf
x = x.reshape(-1, 28 * 28) / 255.0
y = tf.keras.utils.to_categorical(y, num_classes=10)

In [ ]:
print(x.shape, y.shape, y_test.shape)

(70000, 784) (70000, 10) (10000,)

In [ ]:
import tensorflow as tf

# Check if a GPU is available
if tf.test.is_gpu_available():
    print("GPU is available!")
else:
    print("No GPU found, using CPU.")

WARNING:tensorflow:From <ipython-input-4-7af0529a442a>:4: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.

GPU is available!

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.regularizers import Regularizer
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import KFold
from tensorflow.keras import backend as K
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    f_accum = []
    for i in range(len(model.weights)):
        f_accum.append(np.zeros(K.int_shape(model.weights[i])))
    f_accum = np.array(f_accum)
    for _ in range(num_samples):
        idx = np.random.randint(0, x.shape[0])
        with tf.GradientTape() as tape:
            model_output = model(x[idx:idx+1])
        grads = tape.gradient(model_output, model.weights)
        for i in range(len(grads)):
            f_accum[i] += tf.square(grads[i])
    f_accum /= num_samples
    return f_accum

# Define the CrlB regularizer
class CrlBRegularizer(Regularizer):
    def __init__(self, fisher, prior_weights, lambda_=0.1):
        self.fisher = fisher
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i in range(len(self.fisher)):
            regularization += self.lambda_ * tf.reduce_sum(self.fisher[i] * tf.square(x - self.prior_weights[i]))
        return regularization


# Number of K-folds
K = 2

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)
# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []

# Perform K-fold cross-validation
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]

# Task A: Original Fashion MNIST model
    model = Sequential([
    Dense(128, activation='relu', input_shape=(784,)),
    Dense(10, activation='softmax')
])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model = model
        model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
        model.save_weights('FashionMNIST_A.h5')

# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]

# Task B: Fashion MNIST with CrlB regularization
    model_CrlBB = Sequential([
        Dense(128, activation='relu', input_shape=(784,), kernel_regularizer=CrlBRegularizer(fisher_info[0], model.weights[0])),
        Dense(10, activation='softmax', kernel_regularizer=CrlBRegularizer(fisher_info[1], model.weights[1]))
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model_CrlBB = model_CrlBB
        model_CrlBB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model_CrlBB.load_weights('FashionMNIST_A.h5')
        model_CrlBB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlB_acc = 100 * model_CrlBB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlB method Accuracy: %.2f%%" % B_CrlB_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
274/274 [==============================] - 12s 14ms/step - loss: 0.6797 - accuracy: 0.7967 - val_loss: 0.4551 - val_accuracy: 0.8636
Epoch 2/10
274/274 [==============================] - 2s 8ms/step - loss: 0.3733 - accuracy: 0.8900 - val_loss: 0.3385 - val_accuracy: 0.8995
Epoch 3/10
274/274 [==============================] - 3s 10ms/step - loss: 0.2797 - accuracy: 0.9200 - val_loss: 0.2882 - val_accuracy: 0.9164
Epoch 4/10
274/274 [==============================] - 3s 11ms/step - loss: 0.2217 - accuracy: 0.9386 - val_loss: 0.2651 - val_accuracy: 0.9219
Epoch 5/10
274/274 [==============================] - 2s 9ms/step - loss: 0.1810 - accuracy: 0.9507 - val_loss: 0.2447 - val_accuracy: 0.9289
Epoch 6/10
274/274 [==============================] - 2s 8ms/step - loss: 0.1497 - accuracy: 0.9611 - val_loss: 0.2338 - val_accuracy: 0.9326
Epoch 7/10
274/274 [==============================] - 3s 10ms/step - loss: 0.1252 - accuracy: 0.9670 - val_loss: 0.2323 - val_accuracy: 0.9318
Epoch 8/10
274/274 [==============================] - 3s 10ms/step - loss: 0.1052 - accuracy: 0.9738 - val_loss: 0.2178 - val_accuracy: 0.9374
Epoch 9/10
274/274 [==============================] - 4s 13ms/step - loss: 0.0881 - accuracy: 0.9783 - val_loss: 0.2188 - val_accuracy: 0.9378
Epoch 10/10
274/274 [==============================] - 2s 8ms/step - loss: 0.0735 - accuracy: 0.9840 - val_loss: 0.2247 - val_accuracy: 0.9369
Epoch 1/10
274/274 [==============================] - 167s 187ms/step - loss: 0.0690 - accuracy: 0.9830 - val_loss: 0.2260 - val_accuracy: 0.9378
Epoch 2/10
274/274 [==============================] - 23s 86ms/step - loss: 0.0547 - accuracy: 0.9879 - val_loss: 0.2327 - val_accuracy: 0.9358
Epoch 3/10
274/274 [==============================] - 14s 53ms/step - loss: 0.0444 - accuracy: 0.9909 - val_loss: 0.2326 - val_accuracy: 0.9379
Epoch 4/10
274/274 [==============================] - 15s 53ms/step - loss: 0.0348 - accuracy: 0.9940 - val_loss: 0.2318 - val_accuracy: 0.9377
Epoch 5/10
274/274 [==============================] - 20s 72ms/step - loss: 0.0273 - accuracy: 0.9964 - val_loss: 0.2350 - val_accuracy: 0.9399
Epoch 6/10
274/274 [==============================] - 15s 55ms/step - loss: 0.0228 - accuracy: 0.9975 - val_loss: 0.2390 - val_accuracy: 0.9395
Epoch 7/10
274/274 [==============================] - 15s 53ms/step - loss: 0.0193 - accuracy: 0.9977 - val_loss: 0.2537 - val_accuracy: 0.9379
Epoch 8/10
274/274 [==============================] - 14s 52ms/step - loss: 0.0155 - accuracy: 0.9987 - val_loss: 0.2598 - val_accuracy: 0.9364
Epoch 9/10
274/274 [==============================] - 20s 71ms/step - loss: 0.0120 - accuracy: 0.9993 - val_loss: 0.2525 - val_accuracy: 0.9410
Epoch 10/10
274/274 [==============================] - 15s 53ms/step - loss: 0.0090 - accuracy: 0.9997 - val_loss: 0.2602 - val_accuracy: 0.9400
1094/1094 [==============================] - 3s 3ms/step - loss: 0.2247 - accuracy: 0.9369
1094/1094 [==============================] - 24s 22ms/step - loss: 0.2602 - accuracy: 0.9400
1094/1094 [==============================] - 5s 5ms/step - loss: 0.2247 - accuracy: 0.9369
Test Accuracy: 0.9368571639060974
Task A Original Accuracy: 93.69%
Task B EWC method Accuracy: 94.00%
Epoch 1/10
274/274 [==============================] - 3s 8ms/step - loss: 0.6541 - accuracy: 0.8033 - val_loss: 0.4281 - val_accuracy: 0.8752
Epoch 2/10
274/274 [==============================] - 3s 9ms/step - loss: 0.3524 - accuracy: 0.8964 - val_loss: 0.3464 - val_accuracy: 0.8979
Epoch 3/10
274/274 [==============================] - 3s 12ms/step - loss: 0.2682 - accuracy: 0.9223 - val_loss: 0.2974 - val_accuracy: 0.9125
Epoch 4/10
274/274 [==============================] - 2s 7ms/step - loss: 0.2129 - accuracy: 0.9399 - val_loss: 0.2645 - val_accuracy: 0.9226
Epoch 5/10
274/274 [==============================] - 2s 9ms/step - loss: 0.1750 - accuracy: 0.9506 - val_loss: 0.2457 - val_accuracy: 0.9271
Epoch 6/10
274/274 [==============================] - 2s 9ms/step - loss: 0.1446 - accuracy: 0.9609 - val_loss: 0.2314 - val_accuracy: 0.9315
Epoch 7/10
274/274 [==============================] - 2s 9ms/step - loss: 0.1229 - accuracy: 0.9670 - val_loss: 0.2290 - val_accuracy: 0.9321
Epoch 8/10
274/274 [==============================] - 3s 9ms/step - loss: 0.1023 - accuracy: 0.9733 - val_loss: 0.2363 - val_accuracy: 0.9304
Epoch 9/10
274/274 [==============================] - 2s 9ms/step - loss: 0.0852 - accuracy: 0.9791 - val_loss: 0.2259 - val_accuracy: 0.9335
Epoch 10/10
274/274 [==============================] - 2s 7ms/step - loss: 0.0717 - accuracy: 0.9838 - val_loss: 0.2215 - val_accuracy: 0.9356
Epoch 1/10
274/274 [==============================] - 81s 49ms/step - loss: 0.0668 - accuracy: 0.9840 - val_loss: 0.2274 - val_accuracy: 0.9354
Epoch 2/10
274/274 [==============================] - 3s 9ms/step - loss: 0.0524 - accuracy: 0.9880 - val_loss: 0.2342 - val_accuracy: 0.9342
Epoch 3/10
274/274 [==============================] - 2s 8ms/step - loss: 0.0409 - accuracy: 0.9921 - val_loss: 0.2367 - val_accuracy: 0.9351
Epoch 4/10
274/274 [==============================] - 2s 9ms/step - loss: 0.0336 - accuracy: 0.9943 - val_loss: 0.2336 - val_accuracy: 0.9370
Epoch 5/10
274/274 [==============================] - 3s 10ms/step - loss: 0.0283 - accuracy: 0.9956 - val_loss: 0.2386 - val_accuracy: 0.9378
Epoch 6/10
274/274 [==============================] - 3s 9ms/step - loss: 0.0218 - accuracy: 0.9974 - val_loss: 0.2405 - val_accuracy: 0.9377
Epoch 7/10
274/274 [==============================] - 2s 8ms/step - loss: 0.0182 - accuracy: 0.9982 - val_loss: 0.2400 - val_accuracy: 0.9387
Epoch 8/10
274/274 [==============================] - 3s 9ms/step - loss: 0.0136 - accuracy: 0.9992 - val_loss: 0.2504 - val_accuracy: 0.9380
Epoch 9/10
274/274 [==============================] - 3s 10ms/step - loss: 0.0117 - accuracy: 0.9992 - val_loss: 0.2481 - val_accuracy: 0.9401
Epoch 10/10
274/274 [==============================] - 3s 9ms/step - loss: 0.0091 - accuracy: 0.9997 - val_loss: 0.2573 - val_accuracy: 0.9396
1094/1094 [==============================] - 3s 2ms/step - loss: 0.2215 - accuracy: 0.9356
1094/1094 [==============================] - 4s 4ms/step - loss: 0.2573 - accuracy: 0.9396
1094/1094 [==============================] - 3s 3ms/step - loss: 0.2215 - accuracy: 0.9356
Test Accuracy: 0.9356285929679871
Task A Original Accuracy: 93.56%
Task B EWC method Accuracy: 93.96%
Fold-1: 93.69%
Fold-2: 93.56%

### MNIST-C

In [ ]:
import numpy as np
import tensorflow_datasets as tfds
from sklearn.model_selection import KFold
from keras.models import Sequential
from keras.layers import Dense, Flatten

# Load the MNIST-C dataset
dataset = tfds.load('mnist_corrupted', split='train')
data = list(dataset.as_numpy_iterator())
images = np.array([example['image'] for example in data])
labels = np.array([example['label'] for example in data])

Downloading and preparing dataset 235.23 MiB (download: 235.23 MiB, generated: Unknown size, total: 235.23 MiB) to /root/tensorflow_datasets/mnist_corrupted/identity/1.0.0...

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

Generating splits...:   0%|          | 0/2 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/60000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/mnist_corrupted/identity/1.0.0.incompleteT7J7EU/mnist_corrupted-train.tfre…

Generating test examples...:   0%|          | 0/10000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/mnist_corrupted/identity/1.0.0.incompleteT7J7EU/mnist_corrupted-test.tfrec…

Dataset mnist_corrupted downloaded and prepared to /root/tensorflow_datasets/mnist_corrupted/identity/1.0.0. Subsequent calls will reuse this data.

In [ ]:
print(images.shape, labels.shape)

(60000, 28, 28, 1) (60000,)

In [ ]:
import tensorflow as tf
x = images.reshape(-1, 28 * 28) / 255.0
y = tf.keras.utils.to_categorical(labels, num_classes=10)

In [ ]:
print(x.shape, y.shape)

(60000, 784) (60000, 10)

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.regularizers import Regularizer
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import KFold
from tensorflow.keras import backend as K
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    f_accum = []
    for i in range(len(model.weights)):
        f_accum.append(np.zeros(K.int_shape(model.weights[i])))
    f_accum = np.array(f_accum)
    for _ in range(num_samples):
        idx = np.random.randint(0, x.shape[0])
        with tf.GradientTape() as tape:
            model_output = model(x[idx:idx+1])
        grads = tape.gradient(model_output, model.weights)
        for i in range(len(grads)):
            f_accum[i] += tf.square(grads[i])
    f_accum /= num_samples
    return f_accum

# Define the CrlB regularizer
class CrlBRegularizer(Regularizer):
    def __init__(self, fisher, prior_weights, lambda_=0.1):
        self.fisher = fisher
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i in range(len(self.fisher)):
            regularization += self.lambda_ * tf.reduce_sum(self.fisher[i] * tf.square(x - self.prior_weights[i]))
        return regularization


# Number of K-folds
K = 2

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)
# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []

# Perform K-fold cross-validation
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]

# Task A: Original Fashion MNIST model
    model = Sequential([
    Dense(128, activation='relu', input_shape=(784,)),
    Dense(10, activation='softmax')
])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model = model
        model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
        model.save_weights('FashionMNIST_A.h5')

# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]

# Task B: Fashion MNIST with CrlB regularization
    model_CrlBB = Sequential([
        Dense(128, activation='relu', input_shape=(784,), kernel_regularizer=CrlBRegularizer(fisher_info[0], model.weights[0])),
        Dense(10, activation='softmax', kernel_regularizer=CrlBRegularizer(fisher_info[1], model.weights[1]))
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model_CrlBB = model_CrlBB
        model_CrlBB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model_CrlBB.load_weights('FashionMNIST_A.h5')
        model_CrlBB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlB_acc = 100 * model_CrlBB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlB method Accuracy: %.2f%%" % B_CrlB_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
235/235 [==============================] - 5s 14ms/step - loss: 0.4937 - accuracy: 0.8655 - val_loss: 0.2695 - val_accuracy: 0.9234
Epoch 2/10
235/235 [==============================] - 3s 13ms/step - loss: 0.2235 - accuracy: 0.9365 - val_loss: 0.2093 - val_accuracy: 0.9400
Epoch 3/10
235/235 [==============================] - 2s 8ms/step - loss: 0.1683 - accuracy: 0.9518 - val_loss: 0.1727 - val_accuracy: 0.9503
Epoch 4/10
235/235 [==============================] - 2s 7ms/step - loss: 0.1327 - accuracy: 0.9625 - val_loss: 0.1566 - val_accuracy: 0.9536
Epoch 5/10
235/235 [==============================] - 2s 10ms/step - loss: 0.1089 - accuracy: 0.9696 - val_loss: 0.1347 - val_accuracy: 0.9602
Epoch 6/10
235/235 [==============================] - 2s 8ms/step - loss: 0.0903 - accuracy: 0.9746 - val_loss: 0.1262 - val_accuracy: 0.9627
Epoch 7/10
235/235 [==============================] - 4s 18ms/step - loss: 0.0767 - accuracy: 0.9789 - val_loss: 0.1183 - val_accuracy: 0.9644
Epoch 8/10
235/235 [==============================] - 2s 10ms/step - loss: 0.0652 - accuracy: 0.9821 - val_loss: 0.1159 - val_accuracy: 0.9652
Epoch 9/10
235/235 [==============================] - 2s 8ms/step - loss: 0.0557 - accuracy: 0.9849 - val_loss: 0.1101 - val_accuracy: 0.9666
Epoch 10/10
235/235 [==============================] - 2s 8ms/step - loss: 0.0478 - accuracy: 0.9872 - val_loss: 0.1085 - val_accuracy: 0.9675
Epoch 1/10
235/235 [==============================] - 105s 96ms/step - loss: 0.0442 - accuracy: 0.9881 - val_loss: 0.1078 - val_accuracy: 0.9668
Epoch 2/10
235/235 [==============================] - 3s 12ms/step - loss: 0.0361 - accuracy: 0.9902 - val_loss: 0.1074 - val_accuracy: 0.9680
Epoch 3/10
235/235 [==============================] - 3s 12ms/step - loss: 0.0294 - accuracy: 0.9932 - val_loss: 0.1065 - val_accuracy: 0.9691
Epoch 4/10
235/235 [==============================] - 3s 12ms/step - loss: 0.0240 - accuracy: 0.9950 - val_loss: 0.1045 - val_accuracy: 0.9696
Epoch 5/10
235/235 [==============================] - 4s 15ms/step - loss: 0.0215 - accuracy: 0.9959 - val_loss: 0.1063 - val_accuracy: 0.9689
Epoch 6/10
235/235 [==============================] - 3s 12ms/step - loss: 0.0179 - accuracy: 0.9965 - val_loss: 0.1027 - val_accuracy: 0.9702
Epoch 7/10
235/235 [==============================] - 3s 12ms/step - loss: 0.0150 - accuracy: 0.9976 - val_loss: 0.1060 - val_accuracy: 0.9703
Epoch 8/10
235/235 [==============================] - 3s 12ms/step - loss: 0.0125 - accuracy: 0.9984 - val_loss: 0.1024 - val_accuracy: 0.9713
Epoch 9/10
235/235 [==============================] - 4s 16ms/step - loss: 0.0100 - accuracy: 0.9990 - val_loss: 0.1086 - val_accuracy: 0.9705
Epoch 10/10
235/235 [==============================] - 3s 12ms/step - loss: 0.0090 - accuracy: 0.9987 - val_loss: 0.1055 - val_accuracy: 0.9717
938/938 [==============================] - 3s 3ms/step - loss: 0.1085 - accuracy: 0.9675
938/938 [==============================] - 6s 7ms/step - loss: 0.1055 - accuracy: 0.9717
938/938 [==============================] - 3s 3ms/step - loss: 0.1085 - accuracy: 0.9675
Test Accuracy: 0.9674999713897705
Task A Original Accuracy: 96.75%
Task B EWC method Accuracy: 97.17%
Epoch 1/10
235/235 [==============================] - 3s 9ms/step - loss: 0.4864 - accuracy: 0.8674 - val_loss: 0.2736 - val_accuracy: 0.9224
Epoch 2/10
235/235 [==============================] - 2s 7ms/step - loss: 0.2221 - accuracy: 0.9380 - val_loss: 0.2055 - val_accuracy: 0.9394
Epoch 3/10
235/235 [==============================] - 2s 8ms/step - loss: 0.1674 - accuracy: 0.9529 - val_loss: 0.1793 - val_accuracy: 0.9484
Epoch 4/10
235/235 [==============================] - 3s 11ms/step - loss: 0.1351 - accuracy: 0.9627 - val_loss: 0.1606 - val_accuracy: 0.9543
Epoch 5/10
235/235 [==============================] - 2s 8ms/step - loss: 0.1098 - accuracy: 0.9701 - val_loss: 0.1397 - val_accuracy: 0.9593
Epoch 6/10
235/235 [==============================] - 2s 7ms/step - loss: 0.0918 - accuracy: 0.9757 - val_loss: 0.1306 - val_accuracy: 0.9618
Epoch 7/10
235/235 [==============================] - 2s 7ms/step - loss: 0.0772 - accuracy: 0.9792 - val_loss: 0.1254 - val_accuracy: 0.9622
Epoch 8/10
235/235 [==============================] - 2s 6ms/step - loss: 0.0646 - accuracy: 0.9834 - val_loss: 0.1187 - val_accuracy: 0.9652
Epoch 9/10
235/235 [==============================] - 2s 9ms/step - loss: 0.0559 - accuracy: 0.9853 - val_loss: 0.1187 - val_accuracy: 0.9639
Epoch 10/10
235/235 [==============================] - 3s 11ms/step - loss: 0.0465 - accuracy: 0.9887 - val_loss: 0.1105 - val_accuracy: 0.9670
Epoch 1/10
235/235 [==============================] - 104s 123ms/step - loss: 0.0441 - accuracy: 0.9889 - val_loss: 0.1159 - val_accuracy: 0.9654
Epoch 2/10
235/235 [==============================] - 8s 36ms/step - loss: 0.0355 - accuracy: 0.9908 - val_loss: 0.1110 - val_accuracy: 0.9666
Epoch 3/10
235/235 [==============================] - 10s 42ms/step - loss: 0.0285 - accuracy: 0.9937 - val_loss: 0.1090 - val_accuracy: 0.9683
Epoch 4/10
235/235 [==============================] - 8s 36ms/step - loss: 0.0239 - accuracy: 0.9949 - val_loss: 0.1085 - val_accuracy: 0.9678
Epoch 5/10
235/235 [==============================] - 9s 38ms/step - loss: 0.0203 - accuracy: 0.9965 - val_loss: 0.1057 - val_accuracy: 0.9699
Epoch 6/10
235/235 [==============================] - 10s 42ms/step - loss: 0.0170 - accuracy: 0.9970 - val_loss: 0.1102 - val_accuracy: 0.9691
Epoch 7/10
235/235 [==============================] - 8s 33ms/step - loss: 0.0146 - accuracy: 0.9974 - val_loss: 0.1114 - val_accuracy: 0.9686
Epoch 8/10
235/235 [==============================] - 9s 38ms/step - loss: 0.0121 - accuracy: 0.9981 - val_loss: 0.1103 - val_accuracy: 0.9704
Epoch 9/10
235/235 [==============================] - 10s 43ms/step - loss: 0.0111 - accuracy: 0.9986 - val_loss: 0.1088 - val_accuracy: 0.9705
Epoch 10/10
235/235 [==============================] - 10s 43ms/step - loss: 0.0080 - accuracy: 0.9990 - val_loss: 0.1090 - val_accuracy: 0.9706
938/938 [==============================] - 2s 2ms/step - loss: 0.1105 - accuracy: 0.9670
938/938 [==============================] - 10s 10ms/step - loss: 0.1090 - accuracy: 0.9706
938/938 [==============================] - 2s 2ms/step - loss: 0.1105 - accuracy: 0.9670
Test Accuracy: 0.967033326625824
Task A Original Accuracy: 96.70%
Task B EWC method Accuracy: 97.06%
Fold-1: 96.75%
Fold-2: 96.70%

### CIFAR10

In [ ]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import KFold
from tensorflow.keras.optimizers import Adam
from skimage.util import random_noise
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()

# Concatenate the entire dataset
x = np.concatenate((x_train, x_test), axis=0)
y = np.concatenate((y_train, y_test), axis=0)

Downloading data from https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
170498071/170498071 [==============================] - 13s 0us/step

In [ ]:
import tensorflow as tf
# x = x.reshape(-1, 28 * 28) / 255.0
y = tf.keras.utils.to_categorical(y, num_classes=10)

In [ ]:
y.shape

(60000, 10)

In [ ]:
import numpy as np
# from tensorflow.keras.datasets import cifar100
import numpy as np
# Importing the necessary libraries, which we may or may not use. Its always good idea to import them befor (if you remember) else we can do it at any point of time no problem.
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPool2D,Dense,Flatten,Dropout,Input, AveragePooling2D, Activation,Conv2D, MaxPooling2D, BatchNormalization,Concatenate
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
from tensorflow.keras import regularizers, optimizers
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.datasets import cifar100
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers
from tensorflow.keras.regularizers import Regularizer

# Perform hold-out cross-validation
validation_scores = []

# Define the CrlB regularizer
class CrlBRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    fisher_matrix = []
    for i in range(len(model.trainable_weights)):
        fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

    for _ in range(num_samples):
        idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
        with tf.GradientTape() as tape:
            logits = model(x[idx:idx+1])
        gradients = tape.gradient(logits, model.trainable_weights)
        for i in range(len(fisher_matrix)):
            fisher_matrix[i] += tf.square(gradients[i])

    fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
    return fisher_matrix

fisher_matrix = compute_fisher(model, x_train_fold)

# Number of K-folds
K = 2

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)
# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []
num_classes = 10
# Perform K-fold cross-validation
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]

# Task A: Original Fashion MNIST model
    model = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        Conv2D(32, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu'),
        layers.Dropout(0.25),
        Dense(num_classes, activation='softmax')
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model = model
        model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
        model.save_weights('FashionMNIST_A.h5')
        prior_weights = model.get_weights()
# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]

# Task B: Fashion MNIST with CrlB regularization
    model_CrlBB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3),
               kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model_CrlBB = model_CrlBB
        model_CrlBB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model_CrlBB.load_weights('FashionMNIST_A.h5')
        model_CrlBB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlB_acc = 100 * model_CrlBB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlB method Accuracy: %.2f%%" % B_CrlB_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
235/235 [==============================] - 10s 23ms/step - loss: 3.2069 - accuracy: 0.1149 - val_loss: 2.2470 - val_accuracy: 0.1582
Epoch 2/10
235/235 [==============================] - 5s 19ms/step - loss: 2.0885 - accuracy: 0.2216 - val_loss: 1.8031 - val_accuracy: 0.3309
Epoch 3/10
235/235 [==============================] - 5s 19ms/step - loss: 1.6465 - accuracy: 0.3943 - val_loss: 1.4512 - val_accuracy: 0.4936
Epoch 4/10
235/235 [==============================] - 4s 19ms/step - loss: 1.4235 - accuracy: 0.4880 - val_loss: 1.2641 - val_accuracy: 0.5465
Epoch 5/10
235/235 [==============================] - 5s 20ms/step - loss: 1.2864 - accuracy: 0.5424 - val_loss: 1.2007 - val_accuracy: 0.5635
Epoch 6/10
235/235 [==============================] - 4s 19ms/step - loss: 1.1635 - accuracy: 0.5884 - val_loss: 1.1747 - val_accuracy: 0.5828
Epoch 7/10
235/235 [==============================] - 5s 22ms/step - loss: 1.0754 - accuracy: 0.6222 - val_loss: 1.0184 - val_accuracy: 0.6464
Epoch 8/10
235/235 [==============================] - 5s 21ms/step - loss: 0.9943 - accuracy: 0.6509 - val_loss: 0.9784 - val_accuracy: 0.6605
Epoch 9/10
235/235 [==============================] - 4s 18ms/step - loss: 0.9040 - accuracy: 0.6781 - val_loss: 1.1089 - val_accuracy: 0.6317
Epoch 10/10
235/235 [==============================] - 5s 22ms/step - loss: 0.8563 - accuracy: 0.6995 - val_loss: 0.8882 - val_accuracy: 0.6915
Epoch 1/10
235/235 [==============================] - 16s 34ms/step - loss: 0.7602 - accuracy: 0.7320 - val_loss: 0.8703 - val_accuracy: 0.6954
Epoch 2/10
235/235 [==============================] - 7s 28ms/step - loss: 0.6632 - accuracy: 0.7669 - val_loss: 0.8761 - val_accuracy: 0.7002
Epoch 3/10
235/235 [==============================] - 6s 27ms/step - loss: 0.5792 - accuracy: 0.7980 - val_loss: 0.8632 - val_accuracy: 0.7120
Epoch 4/10
235/235 [==============================] - 7s 29ms/step - loss: 0.5075 - accuracy: 0.8221 - val_loss: 0.9022 - val_accuracy: 0.7039
Epoch 5/10
235/235 [==============================] - 6s 27ms/step - loss: 0.4358 - accuracy: 0.8465 - val_loss: 0.9295 - val_accuracy: 0.7056
Epoch 6/10
235/235 [==============================] - 6s 25ms/step - loss: 0.3978 - accuracy: 0.8619 - val_loss: 0.9528 - val_accuracy: 0.7069
Epoch 7/10
235/235 [==============================] - 6s 27ms/step - loss: 0.3568 - accuracy: 0.8755 - val_loss: 1.0546 - val_accuracy: 0.7031
Epoch 8/10
235/235 [==============================] - 6s 25ms/step - loss: 0.3169 - accuracy: 0.8889 - val_loss: 1.0437 - val_accuracy: 0.7009
Epoch 9/10
235/235 [==============================] - 6s 27ms/step - loss: 0.2904 - accuracy: 0.9017 - val_loss: 1.1044 - val_accuracy: 0.7061
Epoch 10/10
235/235 [==============================] - 7s 28ms/step - loss: 0.2569 - accuracy: 0.9131 - val_loss: 1.1003 - val_accuracy: 0.7040
938/938 [==============================] - 4s 4ms/step - loss: 0.8882 - accuracy: 0.6915
938/938 [==============================] - 6s 7ms/step - loss: 1.1003 - accuracy: 0.7040
938/938 [==============================] - 4s 5ms/step - loss: 0.8882 - accuracy: 0.6915
Test Accuracy: 0.6915000081062317
Task A Original Accuracy: 69.15%
Task B EWC method Accuracy: 70.40%
Epoch 1/10
235/235 [==============================] - 9s 24ms/step - loss: 3.1750 - accuracy: 0.2389 - val_loss: 1.5694 - val_accuracy: 0.4305
Epoch 2/10
235/235 [==============================] - 5s 22ms/step - loss: 1.5688 - accuracy: 0.4265 - val_loss: 1.3819 - val_accuracy: 0.5027
Epoch 3/10
235/235 [==============================] - 4s 18ms/step - loss: 1.4208 - accuracy: 0.4890 - val_loss: 1.3057 - val_accuracy: 0.5345
Epoch 4/10
235/235 [==============================] - 5s 19ms/step - loss: 1.2970 - accuracy: 0.5353 - val_loss: 1.1915 - val_accuracy: 0.5833
Epoch 5/10
235/235 [==============================] - 5s 21ms/step - loss: 1.1977 - accuracy: 0.5762 - val_loss: 1.1618 - val_accuracy: 0.5940
Epoch 6/10
235/235 [==============================] - 5s 19ms/step - loss: 1.1090 - accuracy: 0.6072 - val_loss: 1.0659 - val_accuracy: 0.6374
Epoch 7/10
235/235 [==============================] - 5s 20ms/step - loss: 1.0334 - accuracy: 0.6371 - val_loss: 0.9945 - val_accuracy: 0.6556
Epoch 8/10
235/235 [==============================] - 4s 18ms/step - loss: 0.9670 - accuracy: 0.6608 - val_loss: 0.9482 - val_accuracy: 0.6704
Epoch 9/10
235/235 [==============================] - 5s 19ms/step - loss: 0.9033 - accuracy: 0.6825 - val_loss: 0.9281 - val_accuracy: 0.6744
Epoch 10/10
235/235 [==============================] - 6s 25ms/step - loss: 0.8439 - accuracy: 0.7021 - val_loss: 0.9338 - val_accuracy: 0.6785
Epoch 1/10
235/235 [==============================] - 18s 43ms/step - loss: 0.7581 - accuracy: 0.7348 - val_loss: 0.8879 - val_accuracy: 0.6979
Epoch 2/10
235/235 [==============================] - 5s 22ms/step - loss: 0.6558 - accuracy: 0.7685 - val_loss: 0.9025 - val_accuracy: 0.6935
Epoch 3/10
235/235 [==============================] - 6s 25ms/step - loss: 0.5883 - accuracy: 0.7933 - val_loss: 0.9148 - val_accuracy: 0.6905
Epoch 4/10
235/235 [==============================] - 6s 27ms/step - loss: 0.5157 - accuracy: 0.8214 - val_loss: 0.9411 - val_accuracy: 0.7055
Epoch 5/10
235/235 [==============================] - 7s 29ms/step - loss: 0.4441 - accuracy: 0.8428 - val_loss: 1.0294 - val_accuracy: 0.6957
Epoch 6/10
235/235 [==============================] - 5s 23ms/step - loss: 0.3934 - accuracy: 0.8625 - val_loss: 1.0375 - val_accuracy: 0.7022
Epoch 7/10
235/235 [==============================] - 6s 25ms/step - loss: 0.3593 - accuracy: 0.8749 - val_loss: 1.1173 - val_accuracy: 0.6893
Epoch 8/10
235/235 [==============================] - 5s 23ms/step - loss: 0.3289 - accuracy: 0.8864 - val_loss: 1.1429 - val_accuracy: 0.6969
Epoch 9/10
235/235 [==============================] - 7s 28ms/step - loss: 0.2908 - accuracy: 0.8993 - val_loss: 1.1177 - val_accuracy: 0.6977
Epoch 10/10
235/235 [==============================] - 5s 23ms/step - loss: 0.2757 - accuracy: 0.9070 - val_loss: 1.1380 - val_accuracy: 0.7013
938/938 [==============================] - 3s 3ms/step - loss: 0.9338 - accuracy: 0.6785
938/938 [==============================] - 5s 5ms/step - loss: 1.1380 - accuracy: 0.7013
938/938 [==============================] - 3s 4ms/step - loss: 0.9338 - accuracy: 0.6785
Test Accuracy: 0.6784666776657104
Task A Original Accuracy: 67.85%
Task B EWC method Accuracy: 70.13%
Fold-1: 69.15%
Fold-2: 67.85%

### CIFAR10-C

In [ ]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import KFold
from tensorflow.keras.optimizers import Adam
from skimage.util import random_noise
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()

# Concatenate the entire dataset
x = np.concatenate((x_train, x_test), axis=0)
y = np.concatenate((y_train, y_test), axis=0)

# y_train = y
# Add speckle noise to the training images
x = random_noise(x, mode='speckle', var=0.1)

In [ ]:
import tensorflow as tf

In [ ]:

y = tf.keras.utils.to_categorical(y, num_classes=10)

In [ ]:
print(x.shape,y.shape)

(60000, 32, 32, 3) (60000, 10)

In [ ]:
import numpy as np
# from tensorflow.keras.datasets import cifar100
import numpy as np
# Importing the necessary libraries, which we may or may not use. Its always good idea to import them befor (if you remember) else we can do it at any point of time no problem.
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPool2D,Dense,Flatten,Dropout,Input, AveragePooling2D, Activation,Conv2D, MaxPooling2D, BatchNormalization,Concatenate
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
from tensorflow.keras import regularizers, optimizers
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.datasets import cifar100
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers
from tensorflow.keras.regularizers import Regularizer

# Perform hold-out cross-validation
validation_scores = []

# Define the CrlB regularizer
class CrlBRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Number of K-folds
K = 2

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)
# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []
num_classes = 10
# Perform K-fold cross-validation
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]

# Task A: Original Fashion MNIST model
    model = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        Conv2D(32, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu'),
        layers.Dropout(0.25),
        Dense(num_classes, activation='softmax')
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model = model
        model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
        model.save_weights('FashionMNIST_A.h5')
        prior_weights = model.get_weights()
# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    fisher_matrix = []
    for i in range(len(model.trainable_weights)):
        fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

    for _ in range(num_samples):
        idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
        with tf.GradientTape() as tape:
            logits = model(x[idx:idx+1])
        gradients = tape.gradient(logits, model.trainable_weights)
        for i in range(len(fisher_matrix)):
            fisher_matrix[i] += tf.square(gradients[i])

    fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
    return fisher_matrix

fisher_matrix = compute_fisher(model, x_train_fold)
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]
# Task B: Fashion MNIST with CrlB regularization
    model_CrlBB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3),
               kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model_CrlBB = model_CrlBB
        model_CrlBB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model_CrlBB.load_weights('FashionMNIST_A.h5')
        model_CrlBB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlB_acc = 100 * model_CrlBB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlB method Accuracy: %.2f%%" % B_CrlB_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
235/235 [==============================] - 27s 49ms/step - loss: 1.7572 - accuracy: 0.3576 - val_loss: 1.4404 - val_accuracy: 0.4763
Epoch 2/10
235/235 [==============================] - 6s 26ms/step - loss: 1.4074 - accuracy: 0.4913 - val_loss: 1.2808 - val_accuracy: 0.5426
Epoch 3/10
235/235 [==============================] - 6s 25ms/step - loss: 1.2502 - accuracy: 0.5532 - val_loss: 1.1775 - val_accuracy: 0.5771
Epoch 4/10
235/235 [==============================] - 6s 26ms/step - loss: 1.1216 - accuracy: 0.6010 - val_loss: 1.1139 - val_accuracy: 0.6044
Epoch 5/10
235/235 [==============================] - 7s 29ms/step - loss: 1.0181 - accuracy: 0.6406 - val_loss: 1.0516 - val_accuracy: 0.6324
Epoch 6/10
235/235 [==============================] - 6s 24ms/step - loss: 0.9255 - accuracy: 0.6732 - val_loss: 1.0711 - val_accuracy: 0.6305
Epoch 7/10
235/235 [==============================] - 5s 23ms/step - loss: 0.8378 - accuracy: 0.7010 - val_loss: 1.0159 - val_accuracy: 0.6484
Epoch 8/10
235/235 [==============================] - 6s 25ms/step - loss: 0.7561 - accuracy: 0.7323 - val_loss: 1.0308 - val_accuracy: 0.6462
Epoch 9/10
235/235 [==============================] - 6s 27ms/step - loss: 0.6832 - accuracy: 0.7589 - val_loss: 1.0191 - val_accuracy: 0.6597
Epoch 10/10
235/235 [==============================] - 6s 26ms/step - loss: 0.6108 - accuracy: 0.7835 - val_loss: 1.0267 - val_accuracy: 0.6612
Epoch 1/10
235/235 [==============================] - 15s 35ms/step - loss: 1.7306 - accuracy: 0.3631 - val_loss: 1.4551 - val_accuracy: 0.4698
Epoch 2/10
235/235 [==============================] - 6s 25ms/step - loss: 1.3697 - accuracy: 0.5052 - val_loss: 1.2392 - val_accuracy: 0.5565
Epoch 3/10
235/235 [==============================] - 5s 23ms/step - loss: 1.1831 - accuracy: 0.5783 - val_loss: 1.1272 - val_accuracy: 0.6031
Epoch 4/10
235/235 [==============================] - 7s 31ms/step - loss: 1.0615 - accuracy: 0.6220 - val_loss: 1.0523 - val_accuracy: 0.6243
Epoch 5/10
235/235 [==============================] - 6s 23ms/step - loss: 0.9600 - accuracy: 0.6609 - val_loss: 1.0451 - val_accuracy: 0.6336
Epoch 6/10
235/235 [==============================] - 6s 25ms/step - loss: 0.8565 - accuracy: 0.6946 - val_loss: 0.9641 - val_accuracy: 0.6606
Epoch 7/10
235/235 [==============================] - 5s 23ms/step - loss: 0.7702 - accuracy: 0.7262 - val_loss: 0.9553 - val_accuracy: 0.6720
Epoch 8/10
235/235 [==============================] - 7s 29ms/step - loss: 0.6900 - accuracy: 0.7548 - val_loss: 1.0367 - val_accuracy: 0.6544
Epoch 9/10
235/235 [==============================] - 6s 24ms/step - loss: 0.6120 - accuracy: 0.7807 - val_loss: 0.9849 - val_accuracy: 0.6774
Epoch 10/10
235/235 [==============================] - 6s 25ms/step - loss: 0.5349 - accuracy: 0.8104 - val_loss: 1.0434 - val_accuracy: 0.6648
Epoch 1/10
235/235 [==============================] - 25s 49ms/step - loss: 0.9877 - accuracy: 0.6565 - val_loss: 0.4896 - val_accuracy: 0.8532
Epoch 2/10
235/235 [==============================] - 7s 31ms/step - loss: 0.8070 - accuracy: 0.7191 - val_loss: 0.4744 - val_accuracy: 0.8523
Epoch 3/10
235/235 [==============================] - 8s 34ms/step - loss: 0.6745 - accuracy: 0.7647 - val_loss: 0.4620 - val_accuracy: 0.8421
Epoch 4/10
235/235 [==============================] - 7s 31ms/step - loss: 0.5476 - accuracy: 0.8080 - val_loss: 0.4623 - val_accuracy: 0.8403
Epoch 5/10
235/235 [==============================] - 7s 31ms/step - loss: 0.4341 - accuracy: 0.8506 - val_loss: 0.4608 - val_accuracy: 0.8366
Epoch 6/10
235/235 [==============================] - 7s 31ms/step - loss: 0.3356 - accuracy: 0.8819 - val_loss: 0.4986 - val_accuracy: 0.8282
Epoch 7/10
235/235 [==============================] - 7s 30ms/step - loss: 0.2632 - accuracy: 0.9081 - val_loss: 0.5632 - val_accuracy: 0.8117
Epoch 8/10
235/235 [==============================] - 7s 30ms/step - loss: 0.2206 - accuracy: 0.9224 - val_loss: 0.6455 - val_accuracy: 0.7969
Epoch 9/10
235/235 [==============================] - 7s 28ms/step - loss: 0.1828 - accuracy: 0.9370 - val_loss: 0.6109 - val_accuracy: 0.8133
Epoch 10/10
235/235 [==============================] - 6s 26ms/step - loss: 0.1484 - accuracy: 0.9490 - val_loss: 0.7617 - val_accuracy: 0.7897
938/938 [==============================] - 5s 5ms/step - loss: 0.3087 - accuracy: 0.9126
938/938 [==============================] - 6s 6ms/step - loss: 0.7617 - accuracy: 0.7897
938/938 [==============================] - 4s 4ms/step - loss: 0.3087 - accuracy: 0.9126
Test Accuracy: 0.9125666618347168
Task A Original Accuracy: 91.26%
Task B EWC method Accuracy: 78.97%
Epoch 1/10
235/235 [==============================] - 20s 45ms/step - loss: 0.3679 - accuracy: 0.8706 - val_loss: 1.1477 - val_accuracy: 0.6754
Epoch 2/10
235/235 [==============================] - 7s 30ms/step - loss: 0.2908 - accuracy: 0.8999 - val_loss: 1.2447 - val_accuracy: 0.6670
Epoch 3/10
235/235 [==============================] - 7s 31ms/step - loss: 0.2468 - accuracy: 0.9152 - val_loss: 1.3496 - val_accuracy: 0.6686
Epoch 4/10
235/235 [==============================] - 6s 24ms/step - loss: 0.1941 - accuracy: 0.9322 - val_loss: 1.4873 - val_accuracy: 0.6593
Epoch 5/10
235/235 [==============================] - 7s 30ms/step - loss: 0.1796 - accuracy: 0.9377 - val_loss: 1.4545 - val_accuracy: 0.6677
Epoch 6/10
235/235 [==============================] - 6s 27ms/step - loss: 0.1559 - accuracy: 0.9470 - val_loss: 1.5024 - val_accuracy: 0.6611
Epoch 7/10
235/235 [==============================] - 6s 26ms/step - loss: 0.1377 - accuracy: 0.9510 - val_loss: 1.6507 - val_accuracy: 0.6618
Epoch 8/10
235/235 [==============================] - 6s 28ms/step - loss: 0.1269 - accuracy: 0.9552 - val_loss: 1.6157 - val_accuracy: 0.6641
Epoch 9/10
235/235 [==============================] - 7s 30ms/step - loss: 0.1145 - accuracy: 0.9606 - val_loss: 1.7022 - val_accuracy: 0.6620
Epoch 10/10
235/235 [==============================] - 6s 25ms/step - loss: 0.1103 - accuracy: 0.9628 - val_loss: 1.7588 - val_accuracy: 0.6612
938/938 [==============================] - 4s 4ms/step - loss: 1.0434 - accuracy: 0.6648
938/938 [==============================] - 7s 7ms/step - loss: 1.7588 - accuracy: 0.6612
938/938 [==============================] - 4s 4ms/step - loss: 1.0434 - accuracy: 0.6648
Test Accuracy: 0.6648333072662354
Task A Original Accuracy: 66.48%
Task B EWC method Accuracy: 66.12%
Fold-1: 91.26%
Fold-2: 66.48%

### CIFAR100

In [ ]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import KFold
from tensorflow.keras.optimizers import Adam
from skimage.util import random_noise
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar100.load_data()

# Concatenate the entire dataset
x = np.concatenate((x_train, x_test), axis=0)
y = np.concatenate((y_train, y_test), axis=0)

Downloading data from https://www.cs.toronto.edu/~kriz/cifar-100-python.tar.gz
169001437/169001437 [==============================] - 13s 0us/step

In [ ]:
import tensorflow as tf

y = tf.keras.utils.to_categorical(y, num_classes=100)

In [ ]:
print(x.shape,y.shape)

(60000, 32, 32, 3) (60000, 100)

In [ ]:
import numpy as np

import numpy as np

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPool2D,Dense,Flatten,Dropout,Input, AveragePooling2D, Activation,Conv2D, MaxPooling2D, BatchNormalization,Concatenate
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
from tensorflow.keras import regularizers, optimizers
from tensorflow.keras.preprocessing.image import ImageDataGenerator

from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers
from tensorflow.keras.regularizers import Regularizer

# Perform hold-out cross-validation
validation_scores = []

# Define the CrlBo regularizer
class CrlBoRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Number of K-folds
K = 2

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)
# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []
num_classes = 100
# Perform K-fold cross-validation
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]

# Task A: Original Fashion MNIST model
    model = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        Conv2D(32, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu'),
        layers.Dropout(0.25),
        Dense(num_classes, activation='softmax')
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model = model
        model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
        model.save_weights('FashionMNIST_A.h5')
        prior_weights = model.get_weights()
# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    fisher_matrix = []
    for i in range(len(model.trainable_weights)):
        fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

    for _ in range(num_samples):
        idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
        with tf.GradientTape() as tape:
            logits = model(x[idx:idx+1])
        gradients = tape.gradient(logits, model.trainable_weights)
        for i in range(len(fisher_matrix)):
            fisher_matrix[i] += tf.square(gradients[i])

    fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
    return fisher_matrix

fisher_matrix = compute_fisher(model, x_train_fold)
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]
# Task B: Fashion MNIST with CrlBo regularization
    model_CrlBoB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3),
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model_CrlBoB = model_CrlBoB
        model_CrlBoB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model_CrlBoB.load_weights('FashionMNIST_A.h5')
        model_CrlBoB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlBo_acc = 100 * model_CrlBoB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlBo method Accuracy: %.2f%%" % B_CrlBo_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
235/235 [==============================] - 23s 25ms/step - loss: 5.1336 - accuracy: 0.0287 - val_loss: 4.1498 - val_accuracy: 0.0695
Epoch 2/10
235/235 [==============================] - 4s 19ms/step - loss: 3.9538 - accuracy: 0.0968 - val_loss: 3.7113 - val_accuracy: 0.1431
Epoch 3/10
235/235 [==============================] - 4s 17ms/step - loss: 3.5857 - accuracy: 0.1561 - val_loss: 3.3511 - val_accuracy: 0.2074
Epoch 4/10
235/235 [==============================] - 5s 19ms/step - loss: 3.3154 - accuracy: 0.2065 - val_loss: 3.2235 - val_accuracy: 0.2403
Epoch 5/10
235/235 [==============================] - 5s 20ms/step - loss: 3.0878 - accuracy: 0.2490 - val_loss: 3.0488 - val_accuracy: 0.2577
Epoch 6/10
235/235 [==============================] - 4s 19ms/step - loss: 2.8871 - accuracy: 0.2854 - val_loss: 2.9028 - val_accuracy: 0.2920
Epoch 7/10
235/235 [==============================] - 5s 22ms/step - loss: 2.7087 - accuracy: 0.3202 - val_loss: 2.8236 - val_accuracy: 0.3054
Epoch 8/10
235/235 [==============================] - 5s 19ms/step - loss: 2.5254 - accuracy: 0.3545 - val_loss: 2.7811 - val_accuracy: 0.3149
Epoch 9/10
235/235 [==============================] - 5s 19ms/step - loss: 2.3676 - accuracy: 0.3887 - val_loss: 2.7248 - val_accuracy: 0.3278
Epoch 10/10
235/235 [==============================] - 5s 21ms/step - loss: 2.2128 - accuracy: 0.4223 - val_loss: 2.7594 - val_accuracy: 0.3285
Epoch 1/10
235/235 [==============================] - 11s 33ms/step - loss: 5.6961 - accuracy: 0.0283 - val_loss: 4.2521 - val_accuracy: 0.0610
Epoch 2/10
235/235 [==============================] - 5s 19ms/step - loss: 4.1250 - accuracy: 0.0736 - val_loss: 3.9251 - val_accuracy: 0.1167
Epoch 3/10
235/235 [==============================] - 5s 19ms/step - loss: 3.7774 - accuracy: 0.1283 - val_loss: 3.5461 - val_accuracy: 0.1740
Epoch 4/10
235/235 [==============================] - 5s 21ms/step - loss: 3.5410 - accuracy: 0.1658 - val_loss: 3.3993 - val_accuracy: 0.1993
Epoch 5/10
235/235 [==============================] - 5s 20ms/step - loss: 3.3286 - accuracy: 0.2033 - val_loss: 3.2415 - val_accuracy: 0.2316
Epoch 6/10
235/235 [==============================] - 5s 23ms/step - loss: 3.1278 - accuracy: 0.2388 - val_loss: 3.0424 - val_accuracy: 0.2633
Epoch 7/10
235/235 [==============================] - 4s 19ms/step - loss: 2.9533 - accuracy: 0.2734 - val_loss: 2.9764 - val_accuracy: 0.2830
Epoch 8/10
235/235 [==============================] - 5s 20ms/step - loss: 2.7424 - accuracy: 0.3113 - val_loss: 2.9298 - val_accuracy: 0.2848
Epoch 9/10
235/235 [==============================] - 5s 21ms/step - loss: 2.5975 - accuracy: 0.3390 - val_loss: 2.8565 - val_accuracy: 0.3062
Epoch 10/10
235/235 [==============================] - 4s 19ms/step - loss: 2.4513 - accuracy: 0.3701 - val_loss: 2.7360 - val_accuracy: 0.3263
Epoch 1/10
235/235 [==============================] - 18s 41ms/step - loss: 2.8074 - accuracy: 0.3058 - val_loss: 2.1289 - val_accuracy: 0.4505
Epoch 2/10
235/235 [==============================] - 6s 27ms/step - loss: 2.4062 - accuracy: 0.3822 - val_loss: 2.1131 - val_accuracy: 0.4488
Epoch 3/10
235/235 [==============================] - 7s 29ms/step - loss: 2.0671 - accuracy: 0.4574 - val_loss: 2.1968 - val_accuracy: 0.4268
Epoch 4/10
235/235 [==============================] - 6s 27ms/step - loss: 1.7616 - accuracy: 0.5216 - val_loss: 2.2058 - val_accuracy: 0.4342
Epoch 5/10
235/235 [==============================] - 6s 26ms/step - loss: 1.4408 - accuracy: 0.5969 - val_loss: 2.3327 - val_accuracy: 0.4255
Epoch 6/10
235/235 [==============================] - 6s 27ms/step - loss: 1.1806 - accuracy: 0.6622 - val_loss: 2.5202 - val_accuracy: 0.4140
Epoch 7/10
235/235 [==============================] - 6s 25ms/step - loss: 0.9780 - accuracy: 0.7121 - val_loss: 2.6898 - val_accuracy: 0.3987
Epoch 8/10
235/235 [==============================] - 6s 27ms/step - loss: 0.8340 - accuracy: 0.7525 - val_loss: 2.9137 - val_accuracy: 0.3970
Epoch 9/10
235/235 [==============================] - 7s 29ms/step - loss: 0.7036 - accuracy: 0.7879 - val_loss: 3.1544 - val_accuracy: 0.3952
Epoch 10/10
235/235 [==============================] - 5s 22ms/step - loss: 0.6058 - accuracy: 0.8174 - val_loss: 3.3581 - val_accuracy: 0.3868
938/938 [==============================] - 5s 5ms/step - loss: 1.8745 - accuracy: 0.5519
938/938 [==============================] - 6s 6ms/step - loss: 3.3581 - accuracy: 0.3868
938/938 [==============================] - 4s 4ms/step - loss: 1.8745 - accuracy: 0.5519
Test Accuracy: 0.5519333481788635
Task A Original Accuracy: 55.19%
Task B CrlBo method Accuracy: 38.68%
Epoch 1/10
235/235 [==============================] - 18s 39ms/step - loss: 2.0971 - accuracy: 0.4486 - val_loss: 2.7460 - val_accuracy: 0.3278
Epoch 2/10
235/235 [==============================] - 5s 23ms/step - loss: 1.8005 - accuracy: 0.5159 - val_loss: 2.7936 - val_accuracy: 0.3379
Epoch 3/10
235/235 [==============================] - 6s 26ms/step - loss: 1.5453 - accuracy: 0.5740 - val_loss: 2.9341 - val_accuracy: 0.3329
Epoch 4/10
235/235 [==============================] - 6s 24ms/step - loss: 1.3152 - accuracy: 0.6281 - val_loss: 3.1271 - val_accuracy: 0.3278
Epoch 5/10
235/235 [==============================] - 6s 27ms/step - loss: 1.1170 - accuracy: 0.6825 - val_loss: 3.2962 - val_accuracy: 0.3214
Epoch 6/10
235/235 [==============================] - 7s 29ms/step - loss: 0.9451 - accuracy: 0.7256 - val_loss: 3.5586 - val_accuracy: 0.3268
Epoch 7/10
235/235 [==============================] - 6s 27ms/step - loss: 0.8105 - accuracy: 0.7589 - val_loss: 3.5424 - val_accuracy: 0.3258
Epoch 8/10
235/235 [==============================] - 6s 24ms/step - loss: 0.7308 - accuracy: 0.7832 - val_loss: 3.8429 - val_accuracy: 0.3247
Epoch 9/10
235/235 [==============================] - 6s 27ms/step - loss: 0.6441 - accuracy: 0.8092 - val_loss: 3.9271 - val_accuracy: 0.3221
Epoch 10/10
235/235 [==============================] - 7s 30ms/step - loss: 0.5957 - accuracy: 0.8205 - val_loss: 4.2028 - val_accuracy: 0.3221
938/938 [==============================] - 4s 4ms/step - loss: 2.7360 - accuracy: 0.3263
938/938 [==============================] - 6s 7ms/step - loss: 4.2028 - accuracy: 0.3221
938/938 [==============================] - 4s 4ms/step - loss: 2.7360 - accuracy: 0.3263
Test Accuracy: 0.3262999951839447
Task A Original Accuracy: 32.63%
Task B CrlBo method Accuracy: 32.21%
Fold-1: 55.19%
Fold-2: 32.63%

### CIFAR100-C

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from skimage.util import random_noise
from sklearn.model_selection import KFold
from tensorflow.keras.optimizers import Adam

(x_train, y_train), (x_test, y_test) = keras.datasets.cifar100.load_data()
# Add speckle noise to the training images
x_train = random_noise(x_train, mode='speckle', var=0.1)
# Concatenate the entire dataset
x = np.concatenate((x_train, x_test), axis=0)
y = np.concatenate((y_train, y_test), axis=0)

# y_train = y

# x = random_noise(x, mode='speckle', var=0.1)

y = tf.keras.utils.to_categorical(y, num_classes=100)
print(x.shape,y.shape)

(60000, 32, 32, 3) (60000, 100)

In [ ]:
import numpy as np

import numpy as np

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPool2D,Dense,Flatten,Dropout,Input, AveragePooling2D, Activation,Conv2D, MaxPooling2D, BatchNormalization,Concatenate
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
from tensorflow.keras import regularizers, optimizers
from tensorflow.keras.preprocessing.image import ImageDataGenerator

from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers
from tensorflow.keras.regularizers import Regularizer

# Perform hold-out cross-validation
validation_scores = []

# Define the CrlBo regularizer
class CrlBoRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Number of K-folds
K = 2

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)
# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []
num_classes = 100
# Perform K-fold cross-validation
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]

# Task A: Original Fashion MNIST model
    model = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        Conv2D(32, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu'),
        layers.Dropout(0.25),
        Dense(num_classes, activation='softmax')
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model = model
        model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
        model.save_weights('FashionMNIST_A.h5')
        prior_weights = model.get_weights()
# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    fisher_matrix = []
    for i in range(len(model.trainable_weights)):
        fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

    for _ in range(num_samples):
        idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
        with tf.GradientTape() as tape:
            logits = model(x[idx:idx+1])
        gradients = tape.gradient(logits, model.trainable_weights)
        for i in range(len(fisher_matrix)):
            fisher_matrix[i] += tf.square(gradients[i])

    fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
    return fisher_matrix

fisher_matrix = compute_fisher(model, x_train_fold)
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]
# Task B: Fashion MNIST with CrlBo regularization
    model_CrlBoB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3),
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model_CrlBoB = model_CrlBoB
        model_CrlBoB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model_CrlBoB.load_weights('FashionMNIST_A.h5')
        model_CrlBoB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlBo_acc = 100 * model_CrlBoB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlBo method Accuracy: %.2f%%" % B_CrlBo_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
235/235 [==============================] - 33s 39ms/step - loss: 4.7626 - accuracy: 0.0131 - val_loss: 4.4320 - val_accuracy: 0.0229
Epoch 2/10
235/235 [==============================] - 7s 31ms/step - loss: 4.2811 - accuracy: 0.0418 - val_loss: 4.0788 - val_accuracy: 0.0711
Epoch 3/10
235/235 [==============================] - 6s 26ms/step - loss: 3.9634 - accuracy: 0.0884 - val_loss: 3.8318 - val_accuracy: 0.1133
Epoch 4/10
235/235 [==============================] - 5s 23ms/step - loss: 3.7730 - accuracy: 0.1185 - val_loss: 3.7132 - val_accuracy: 0.1290
Epoch 5/10
235/235 [==============================] - 6s 26ms/step - loss: 3.6166 - accuracy: 0.1424 - val_loss: 3.5545 - val_accuracy: 0.1613
Epoch 6/10
235/235 [==============================] - 6s 24ms/step - loss: 3.4710 - accuracy: 0.1703 - val_loss: 3.4562 - val_accuracy: 0.1794
Epoch 7/10
235/235 [==============================] - 7s 29ms/step - loss: 3.3407 - accuracy: 0.1926 - val_loss: 3.3737 - val_accuracy: 0.1945
Epoch 8/10
235/235 [==============================] - 6s 24ms/step - loss: 3.2125 - accuracy: 0.2215 - val_loss: 3.3429 - val_accuracy: 0.2003
Epoch 9/10
235/235 [==============================] - 7s 30ms/step - loss: 3.0874 - accuracy: 0.2399 - val_loss: 3.3096 - val_accuracy: 0.2130
Epoch 10/10
235/235 [==============================] - 6s 25ms/step - loss: 2.9561 - accuracy: 0.2673 - val_loss: 3.2681 - val_accuracy: 0.2252
Epoch 1/10
235/235 [==============================] - 15s 40ms/step - loss: 4.7624 - accuracy: 0.0118 - val_loss: 4.5526 - val_accuracy: 0.0235
Epoch 2/10
235/235 [==============================] - 6s 24ms/step - loss: 4.3556 - accuracy: 0.0402 - val_loss: 4.1341 - val_accuracy: 0.0596
Epoch 3/10
235/235 [==============================] - 6s 26ms/step - loss: 4.0553 - accuracy: 0.0776 - val_loss: 3.8849 - val_accuracy: 0.1083
Epoch 4/10
235/235 [==============================] - 5s 23ms/step - loss: 3.8280 - accuracy: 0.1124 - val_loss: 3.7182 - val_accuracy: 0.1307
Epoch 5/10
235/235 [==============================] - 6s 24ms/step - loss: 3.6543 - accuracy: 0.1453 - val_loss: 3.5374 - val_accuracy: 0.1700
Epoch 6/10
235/235 [==============================] - 6s 24ms/step - loss: 3.4809 - accuracy: 0.1706 - val_loss: 3.4700 - val_accuracy: 0.1823
Epoch 7/10
235/235 [==============================] - 5s 23ms/step - loss: 3.3367 - accuracy: 0.1987 - val_loss: 3.3636 - val_accuracy: 0.1968
Epoch 8/10
235/235 [==============================] - 6s 27ms/step - loss: 3.1837 - accuracy: 0.2247 - val_loss: 3.3083 - val_accuracy: 0.2138
Epoch 9/10
235/235 [==============================] - 5s 23ms/step - loss: 3.0253 - accuracy: 0.2555 - val_loss: 3.2622 - val_accuracy: 0.2212
Epoch 10/10
235/235 [==============================] - 6s 26ms/step - loss: 2.8968 - accuracy: 0.2781 - val_loss: 3.2594 - val_accuracy: 0.2276
Epoch 1/10
235/235 [==============================] - 25s 53ms/step - loss: 3.2216 - accuracy: 0.2278 - val_loss: 2.7291 - val_accuracy: 0.3231
Epoch 2/10
235/235 [==============================] - 7s 30ms/step - loss: 2.9330 - accuracy: 0.2776 - val_loss: 2.7322 - val_accuracy: 0.3237
Epoch 3/10
235/235 [==============================] - 6s 24ms/step - loss: 2.6776 - accuracy: 0.3283 - val_loss: 2.6704 - val_accuracy: 0.3262
Epoch 4/10
235/235 [==============================] - 7s 28ms/step - loss: 2.4080 - accuracy: 0.3841 - val_loss: 2.6366 - val_accuracy: 0.3369
Epoch 5/10
235/235 [==============================] - 6s 24ms/step - loss: 2.1264 - accuracy: 0.4445 - val_loss: 2.7487 - val_accuracy: 0.3265
Epoch 6/10
235/235 [==============================] - 6s 25ms/step - loss: 1.8788 - accuracy: 0.4995 - val_loss: 2.8433 - val_accuracy: 0.3191
Epoch 7/10
235/235 [==============================] - 7s 28ms/step - loss: 1.6167 - accuracy: 0.5572 - val_loss: 3.0277 - val_accuracy: 0.3076
Epoch 8/10
235/235 [==============================] - 7s 28ms/step - loss: 1.4147 - accuracy: 0.6097 - val_loss: 3.1581 - val_accuracy: 0.3046
Epoch 9/10
235/235 [==============================] - 7s 31ms/step - loss: 1.2025 - accuracy: 0.6590 - val_loss: 3.3910 - val_accuracy: 0.2942
Epoch 10/10
235/235 [==============================] - 6s 26ms/step - loss: 1.0257 - accuracy: 0.7015 - val_loss: 3.6846 - val_accuracy: 0.2950
938/938 [==============================] - 7s 7ms/step - loss: 2.4749 - accuracy: 0.3929
938/938 [==============================] - 7s 7ms/step - loss: 3.6846 - accuracy: 0.2950
938/938 [==============================] - 5s 5ms/step - loss: 2.4749 - accuracy: 0.3929
Test Accuracy: 0.39286667108535767
Task A Original Accuracy: 39.29%
Task B CrlBo method Accuracy: 29.50%
Epoch 1/10
235/235 [==============================] - 14s 31ms/step - loss: 2.5713 - accuracy: 0.3468 - val_loss: 3.2819 - val_accuracy: 0.2427
Epoch 2/10
235/235 [==============================] - 6s 27ms/step - loss: 2.3343 - accuracy: 0.3994 - val_loss: 3.3719 - val_accuracy: 0.2463
Epoch 3/10
235/235 [==============================] - 6s 26ms/step - loss: 2.1473 - accuracy: 0.4375 - val_loss: 3.4848 - val_accuracy: 0.2495
Epoch 4/10
235/235 [==============================] - 6s 27ms/step - loss: 1.9472 - accuracy: 0.4814 - val_loss: 3.5215 - val_accuracy: 0.2522
Epoch 5/10
235/235 [==============================] - 5s 21ms/step - loss: 1.7714 - accuracy: 0.5238 - val_loss: 3.6543 - val_accuracy: 0.2502
Epoch 6/10
235/235 [==============================] - 6s 27ms/step - loss: 1.5830 - accuracy: 0.5624 - val_loss: 3.8379 - val_accuracy: 0.2511
Epoch 7/10
235/235 [==============================] - 6s 26ms/step - loss: 1.4093 - accuracy: 0.6064 - val_loss: 4.0103 - val_accuracy: 0.2457
Epoch 8/10
235/235 [==============================] - 5s 21ms/step - loss: 1.2444 - accuracy: 0.6492 - val_loss: 4.2460 - val_accuracy: 0.2444
Epoch 9/10
235/235 [==============================] - 5s 21ms/step - loss: 1.0947 - accuracy: 0.6871 - val_loss: 4.3897 - val_accuracy: 0.2395
Epoch 10/10
235/235 [==============================] - 5s 22ms/step - loss: 0.9496 - accuracy: 0.7252 - val_loss: 4.7104 - val_accuracy: 0.2405
938/938 [==============================] - 3s 3ms/step - loss: 3.2594 - accuracy: 0.2276
938/938 [==============================] - 5s 5ms/step - loss: 4.7104 - accuracy: 0.2405
938/938 [==============================] - 3s 3ms/step - loss: 3.2594 - accuracy: 0.2276
Test Accuracy: 0.22763332724571228
Task A Original Accuracy: 22.76%
Task B CrlBo method Accuracy: 24.05%
Fold-1: 39.29%
Fold-2: 22.76%

### STL-10

In [ ]:
import tensorflow_datasets as tfds

# Load the STL-10 dataset
dataset_name = "stl10"
train_dataset, test_dataset = tfds.load(name=dataset_name, split=["train", "test"], as_supervised=True)

# Iterate through the datasets to get features and labels
X_train = []
y_train = []
for image, label in tfds.as_numpy(train_dataset):
    X_train.append(image)
    y_train.append(label)

X_test = []
y_test = []
for image, label in tfds.as_numpy(test_dataset):
    X_test.append(image)
    y_test.append(label)

# Convert lists to numpy arrays
import numpy as np
X_train = np.array(X_train)
y_train = np.array(y_train)
X_test = np.array(X_test)
y_test = np.array(y_test)

# Print the shape of the arrays
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

X_train shape: (5000, 96, 96, 3)
y_train shape: (5000,)
X_test shape: (8000, 96, 96, 3)
y_test shape: (8000,)

In [ ]:
import tensorflow as tf
y_train = tf.keras.utils.to_categorical(y_train, num_classes=10)
y_test = tf.keras.utils.to_categorical(y_test, num_classes=10)

In [ ]:
x = np.concatenate((X_train,X_test), axis=0)
x.shape

(13000, 96, 96, 3)

In [ ]:
y = np.concatenate((y_train,y_test),axis=0)
y.shape

(13000, 10)

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPool2D,Dense,Flatten,Dropout,Input, AveragePooling2D, Activation,Conv2D, MaxPooling2D, BatchNormalization,Concatenate
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
from tensorflow.keras import regularizers, optimizers
from tensorflow.keras.preprocessing.image import ImageDataGenerator

from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers
from tensorflow.keras.regularizers import Regularizer

# Perform hold-out cross-validation
validation_scores = []

# Define the CrlBo regularizer
class CrlBoRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Number of K-folds
K = 2

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)
# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []
num_classes = 10
# Perform K-fold cross-validation
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]

# Task A: Original STL-10 model
    model = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(96, 96, 3)),
        Conv2D(32, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu'),
        layers.Dropout(0.25),
        Dense(num_classes, activation='softmax')
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model = model
        model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
        model.save_weights('FashionMNIST_A.h5')
        prior_weights = model.get_weights()
# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    fisher_matrix = []
    for i in range(len(model.trainable_weights)):
        fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

    for _ in range(num_samples):
        idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
        with tf.GradientTape() as tape:
            logits = model(x[idx:idx+1])
        gradients = tape.gradient(logits, model.trainable_weights)
        for i in range(len(fisher_matrix)):
            fisher_matrix[i] += tf.square(gradients[i])

    fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
    return fisher_matrix

fisher_matrix = compute_fisher(model, x_train_fold)
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]
# Task B: Fashion MNIST with CrlBo regularization
    model_CrlBoB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(96, 96, 3),
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model_CrlBoB = model_CrlBoB
        model_CrlBoB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model_CrlBoB.load_weights('FashionMNIST_A.h5')
        model_CrlBoB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlBo_acc = 100 * model_CrlBoB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlBo method Accuracy: %.2f%%" % B_CrlBo_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/100
51/51 [==============================] - 29s 160ms/step - loss: 47.9097 - accuracy: 0.1386 - val_loss: 2.0850 - val_accuracy: 0.1963
Epoch 2/100
51/51 [==============================] - 6s 110ms/step - loss: 1.9881 - accuracy: 0.2365 - val_loss: 1.9347 - val_accuracy: 0.2732
Epoch 3/100
51/51 [==============================] - 6s 117ms/step - loss: 1.8166 - accuracy: 0.3178 - val_loss: 1.7525 - val_accuracy: 0.3294
Epoch 4/100
51/51 [==============================] - 6s 119ms/step - loss: 1.6502 - accuracy: 0.3883 - val_loss: 1.6385 - val_accuracy: 0.3755
Epoch 5/100
51/51 [==============================] - 6s 121ms/step - loss: 1.5488 - accuracy: 0.4251 - val_loss: 1.5757 - val_accuracy: 0.4117
Epoch 6/100
51/51 [==============================] - 6s 121ms/step - loss: 1.4470 - accuracy: 0.4722 - val_loss: 1.6082 - val_accuracy: 0.3957
Epoch 7/100
51/51 [==============================] - 6s 121ms/step - loss: 1.3712 - accuracy: 0.4998 - val_loss: 1.5801 - val_accuracy: 0.4043
Epoch 8/100
51/51 [==============================] - 6s 121ms/step - loss: 1.2529 - accuracy: 0.5355 - val_loss: 1.5587 - val_accuracy: 0.4294
Epoch 9/100
51/51 [==============================] - 6s 120ms/step - loss: 1.1361 - accuracy: 0.5872 - val_loss: 1.5591 - val_accuracy: 0.4422
Epoch 10/100
51/51 [==============================] - 6s 124ms/step - loss: 1.0192 - accuracy: 0.6297 - val_loss: 1.6633 - val_accuracy: 0.4534
Epoch 11/100
51/51 [==============================] - 6s 121ms/step - loss: 0.9227 - accuracy: 0.6635 - val_loss: 1.6158 - val_accuracy: 0.4503
Epoch 12/100
51/51 [==============================] - 6s 117ms/step - loss: 0.8074 - accuracy: 0.7114 - val_loss: 1.7733 - val_accuracy: 0.4518
Epoch 13/100
51/51 [==============================] - 6s 113ms/step - loss: 0.7515 - accuracy: 0.7328 - val_loss: 1.7100 - val_accuracy: 0.4651
Epoch 14/100
51/51 [==============================] - 6s 122ms/step - loss: 0.6493 - accuracy: 0.7685 - val_loss: 1.8723 - val_accuracy: 0.4671
Epoch 15/100
51/51 [==============================] - 6s 121ms/step - loss: 0.5911 - accuracy: 0.7935 - val_loss: 1.9129 - val_accuracy: 0.4631
Epoch 16/100
51/51 [==============================] - 6s 123ms/step - loss: 0.5155 - accuracy: 0.8223 - val_loss: 1.9744 - val_accuracy: 0.4637
Epoch 17/100
51/51 [==============================] - 6s 113ms/step - loss: 0.4707 - accuracy: 0.8318 - val_loss: 2.0829 - val_accuracy: 0.4665
Epoch 18/100
51/51 [==============================] - 6s 112ms/step - loss: 0.4122 - accuracy: 0.8585 - val_loss: 2.2359 - val_accuracy: 0.4783
Epoch 19/100
51/51 [==============================] - 6s 114ms/step - loss: 0.3659 - accuracy: 0.8754 - val_loss: 2.3376 - val_accuracy: 0.4694
Epoch 20/100
51/51 [==============================] - 6s 112ms/step - loss: 0.3503 - accuracy: 0.8828 - val_loss: 2.3407 - val_accuracy: 0.4628
Epoch 21/100
51/51 [==============================] - 6s 114ms/step - loss: 0.2987 - accuracy: 0.8985 - val_loss: 2.4306 - val_accuracy: 0.4680
Epoch 22/100
51/51 [==============================] - 6s 112ms/step - loss: 0.2928 - accuracy: 0.8983 - val_loss: 2.4495 - val_accuracy: 0.4680
Epoch 23/100
51/51 [==============================] - 6s 123ms/step - loss: 0.2887 - accuracy: 0.9054 - val_loss: 2.3726 - val_accuracy: 0.4680
Epoch 24/100
51/51 [==============================] - 6s 111ms/step - loss: 0.2330 - accuracy: 0.9245 - val_loss: 2.6937 - val_accuracy: 0.4732
Epoch 25/100
51/51 [==============================] - 6s 121ms/step - loss: 0.2442 - accuracy: 0.9211 - val_loss: 2.4081 - val_accuracy: 0.4660
Epoch 26/100
51/51 [==============================] - 6s 121ms/step - loss: 0.2137 - accuracy: 0.9266 - val_loss: 2.5706 - val_accuracy: 0.4708
Epoch 27/100
51/51 [==============================] - 6s 116ms/step - loss: 0.2028 - accuracy: 0.9369 - val_loss: 2.6156 - val_accuracy: 0.4718
Epoch 28/100
51/51 [==============================] - 6s 121ms/step - loss: 0.1942 - accuracy: 0.9375 - val_loss: 2.8402 - val_accuracy: 0.4600
Epoch 29/100
51/51 [==============================] - 6s 123ms/step - loss: 0.2005 - accuracy: 0.9351 - val_loss: 2.6792 - val_accuracy: 0.4677
Epoch 30/100
51/51 [==============================] - 6s 122ms/step - loss: 0.1785 - accuracy: 0.9435 - val_loss: 2.9307 - val_accuracy: 0.4672
Epoch 31/100
51/51 [==============================] - 6s 121ms/step - loss: 0.1637 - accuracy: 0.9468 - val_loss: 3.0119 - val_accuracy: 0.4523
Epoch 32/100
51/51 [==============================] - 6s 113ms/step - loss: 0.1818 - accuracy: 0.9417 - val_loss: 2.6578 - val_accuracy: 0.4669
Epoch 33/100
51/51 [==============================] - 6s 113ms/step - loss: 0.1598 - accuracy: 0.9469 - val_loss: 2.7960 - val_accuracy: 0.4745
Epoch 34/100
51/51 [==============================] - 6s 114ms/step - loss: 0.1598 - accuracy: 0.9520 - val_loss: 2.8764 - val_accuracy: 0.4740
Epoch 35/100
51/51 [==============================] - 6s 121ms/step - loss: 0.1313 - accuracy: 0.9572 - val_loss: 2.7937 - val_accuracy: 0.4638
Epoch 36/100
51/51 [==============================] - 6s 121ms/step - loss: 0.1443 - accuracy: 0.9545 - val_loss: 2.8968 - val_accuracy: 0.4755
Epoch 37/100
51/51 [==============================] - 6s 113ms/step - loss: 0.1246 - accuracy: 0.9608 - val_loss: 2.7789 - val_accuracy: 0.4743
Epoch 38/100
51/51 [==============================] - 6s 116ms/step - loss: 0.1386 - accuracy: 0.9560 - val_loss: 2.8796 - val_accuracy: 0.4812
Epoch 39/100
51/51 [==============================] - 6s 120ms/step - loss: 0.1155 - accuracy: 0.9620 - val_loss: 2.9300 - val_accuracy: 0.4849
Epoch 40/100
51/51 [==============================] - 6s 122ms/step - loss: 0.1053 - accuracy: 0.9688 - val_loss: 2.8750 - val_accuracy: 0.4723
Epoch 41/100
51/51 [==============================] - 6s 113ms/step - loss: 0.1240 - accuracy: 0.9611 - val_loss: 3.2376 - val_accuracy: 0.4714
Epoch 42/100
51/51 [==============================] - 6s 123ms/step - loss: 0.1151 - accuracy: 0.9638 - val_loss: 2.8464 - val_accuracy: 0.4731
Epoch 43/100
51/51 [==============================] - 6s 112ms/step - loss: 0.1006 - accuracy: 0.9680 - val_loss: 3.1969 - val_accuracy: 0.4675
Epoch 44/100
51/51 [==============================] - 6s 122ms/step - loss: 0.1138 - accuracy: 0.9625 - val_loss: 3.1544 - val_accuracy: 0.4700
Epoch 45/100
51/51 [==============================] - 6s 120ms/step - loss: 0.1190 - accuracy: 0.9652 - val_loss: 2.9990 - val_accuracy: 0.4742
Epoch 46/100
51/51 [==============================] - 6s 116ms/step - loss: 0.0931 - accuracy: 0.9703 - val_loss: 3.0351 - val_accuracy: 0.4757
Epoch 47/100
51/51 [==============================] - 6s 123ms/step - loss: 0.0902 - accuracy: 0.9714 - val_loss: 2.9988 - val_accuracy: 0.4777
Epoch 48/100
51/51 [==============================] - 6s 121ms/step - loss: 0.1098 - accuracy: 0.9671 - val_loss: 3.1974 - val_accuracy: 0.4717
Epoch 49/100
51/51 [==============================] - 6s 114ms/step - loss: 0.0944 - accuracy: 0.9746 - val_loss: 3.2826 - val_accuracy: 0.4742
Epoch 50/100
51/51 [==============================] - 6s 114ms/step - loss: 0.1074 - accuracy: 0.9700 - val_loss: 3.1020 - val_accuracy: 0.4732
Epoch 51/100
51/51 [==============================] - 6s 114ms/step - loss: 0.0940 - accuracy: 0.9694 - val_loss: 3.1503 - val_accuracy: 0.4734
Epoch 52/100
51/51 [==============================] - 6s 120ms/step - loss: 0.0833 - accuracy: 0.9725 - val_loss: 3.3503 - val_accuracy: 0.4706
Epoch 53/100
51/51 [==============================] - 6s 122ms/step - loss: 0.0841 - accuracy: 0.9734 - val_loss: 3.1851 - val_accuracy: 0.4800
Epoch 54/100
51/51 [==============================] - 6s 121ms/step - loss: 0.0838 - accuracy: 0.9740 - val_loss: 3.0409 - val_accuracy: 0.4682
Epoch 55/100
51/51 [==============================] - 6s 122ms/step - loss: 0.0988 - accuracy: 0.9738 - val_loss: 3.1728 - val_accuracy: 0.4705
Epoch 56/100
51/51 [==============================] - 6s 123ms/step - loss: 0.1041 - accuracy: 0.9688 - val_loss: 3.1460 - val_accuracy: 0.4718
Epoch 57/100
51/51 [==============================] - 6s 121ms/step - loss: 0.0819 - accuracy: 0.9751 - val_loss: 3.1149 - val_accuracy: 0.4751
Epoch 58/100
51/51 [==============================] - 6s 112ms/step - loss: 0.0657 - accuracy: 0.9785 - val_loss: 3.2763 - val_accuracy: 0.4671
Epoch 59/100
51/51 [==============================] - 6s 115ms/step - loss: 0.0700 - accuracy: 0.9778 - val_loss: 3.4660 - val_accuracy: 0.4782
Epoch 60/100
51/51 [==============================] - 6s 112ms/step - loss: 0.0882 - accuracy: 0.9737 - val_loss: 3.3214 - val_accuracy: 0.4817
Epoch 61/100
51/51 [==============================] - 6s 116ms/step - loss: 0.0723 - accuracy: 0.9792 - val_loss: 3.2604 - val_accuracy: 0.4723
Epoch 62/100
51/51 [==============================] - 6s 120ms/step - loss: 0.0830 - accuracy: 0.9746 - val_loss: 3.4934 - val_accuracy: 0.4772
Epoch 63/100
51/51 [==============================] - 6s 115ms/step - loss: 0.0668 - accuracy: 0.9788 - val_loss: 3.5051 - val_accuracy: 0.4708
Epoch 64/100
51/51 [==============================] - 6s 115ms/step - loss: 0.0660 - accuracy: 0.9782 - val_loss: 3.3450 - val_accuracy: 0.4732
Epoch 65/100
51/51 [==============================] - 6s 113ms/step - loss: 0.1006 - accuracy: 0.9718 - val_loss: 3.3956 - val_accuracy: 0.4646
Epoch 66/100
51/51 [==============================] - 6s 112ms/step - loss: 0.0646 - accuracy: 0.9774 - val_loss: 3.2968 - val_accuracy: 0.4726
Epoch 67/100
51/51 [==============================] - 6s 116ms/step - loss: 0.0981 - accuracy: 0.9723 - val_loss: 3.1528 - val_accuracy: 0.4738
Epoch 68/100
51/51 [==============================] - 6s 125ms/step - loss: 0.0703 - accuracy: 0.9782 - val_loss: 3.1303 - val_accuracy: 0.4788
Epoch 69/100
51/51 [==============================] - 6s 120ms/step - loss: 0.0660 - accuracy: 0.9817 - val_loss: 3.1066 - val_accuracy: 0.4755
Epoch 70/100
51/51 [==============================] - 6s 113ms/step - loss: 0.0595 - accuracy: 0.9832 - val_loss: 3.5390 - val_accuracy: 0.4745
Epoch 71/100
51/51 [==============================] - 6s 120ms/step - loss: 0.0731 - accuracy: 0.9792 - val_loss: 3.4266 - val_accuracy: 0.4592
Epoch 72/100
51/51 [==============================] - 6s 123ms/step - loss: 0.0708 - accuracy: 0.9802 - val_loss: 3.1997 - val_accuracy: 0.4774
Epoch 73/100
51/51 [==============================] - 6s 121ms/step - loss: 0.0667 - accuracy: 0.9788 - val_loss: 3.4622 - val_accuracy: 0.4729
Epoch 74/100
51/51 [==============================] - 6s 123ms/step - loss: 0.0658 - accuracy: 0.9788 - val_loss: 3.5296 - val_accuracy: 0.4614
Epoch 75/100
51/51 [==============================] - 6s 113ms/step - loss: 0.0506 - accuracy: 0.9842 - val_loss: 3.3680 - val_accuracy: 0.4743
Epoch 76/100
51/51 [==============================] - 6s 114ms/step - loss: 0.0615 - accuracy: 0.9815 - val_loss: 3.4760 - val_accuracy: 0.4715
Epoch 77/100
51/51 [==============================] - 6s 121ms/step - loss: 0.0692 - accuracy: 0.9778 - val_loss: 3.2651 - val_accuracy: 0.4620
Epoch 78/100
51/51 [==============================] - 6s 123ms/step - loss: 0.0732 - accuracy: 0.9778 - val_loss: 3.0940 - val_accuracy: 0.4705
Epoch 79/100
51/51 [==============================] - 6s 112ms/step - loss: 0.0679 - accuracy: 0.9782 - val_loss: 3.3604 - val_accuracy: 0.4611
Epoch 80/100
51/51 [==============================] - 6s 116ms/step - loss: 0.0516 - accuracy: 0.9842 - val_loss: 3.5494 - val_accuracy: 0.4749
Epoch 81/100
51/51 [==============================] - 6s 113ms/step - loss: 0.0496 - accuracy: 0.9854 - val_loss: 3.7101 - val_accuracy: 0.4640
Epoch 82/100
51/51 [==============================] - 6s 115ms/step - loss: 0.0643 - accuracy: 0.9814 - val_loss: 3.4255 - val_accuracy: 0.4788
Epoch 83/100
51/51 [==============================] - 6s 120ms/step - loss: 0.0618 - accuracy: 0.9812 - val_loss: 3.3023 - val_accuracy: 0.4646
Epoch 84/100
51/51 [==============================] - 6s 119ms/step - loss: 0.0543 - accuracy: 0.9837 - val_loss: 3.4608 - val_accuracy: 0.4745
Epoch 85/100
51/51 [==============================] - 6s 118ms/step - loss: 0.0554 - accuracy: 0.9838 - val_loss: 3.5717 - val_accuracy: 0.4758
Epoch 86/100
51/51 [==============================] - 6s 109ms/step - loss: 0.0475 - accuracy: 0.9862 - val_loss: 3.5036 - val_accuracy: 0.4651
Epoch 87/100
51/51 [==============================] - 6s 119ms/step - loss: 0.0557 - accuracy: 0.9848 - val_loss: 3.7376 - val_accuracy: 0.4765
Epoch 88/100
51/51 [==============================] - 6s 118ms/step - loss: 0.0569 - accuracy: 0.9835 - val_loss: 3.5927 - val_accuracy: 0.4789
Epoch 89/100
51/51 [==============================] - 6s 111ms/step - loss: 0.0604 - accuracy: 0.9832 - val_loss: 3.5693 - val_accuracy: 0.4674
Epoch 90/100
51/51 [==============================] - 6s 118ms/step - loss: 0.0453 - accuracy: 0.9858 - val_loss: 3.4690 - val_accuracy: 0.4812
Epoch 91/100
51/51 [==============================] - 6s 110ms/step - loss: 0.0547 - accuracy: 0.9846 - val_loss: 3.6817 - val_accuracy: 0.4697
Epoch 92/100
51/51 [==============================] - 6s 109ms/step - loss: 0.0514 - accuracy: 0.9834 - val_loss: 3.8410 - val_accuracy: 0.4723
Epoch 93/100
51/51 [==============================] - 6s 119ms/step - loss: 0.0511 - accuracy: 0.9829 - val_loss: 3.6839 - val_accuracy: 0.4751
Epoch 94/100
51/51 [==============================] - 6s 109ms/step - loss: 0.0441 - accuracy: 0.9878 - val_loss: 3.5574 - val_accuracy: 0.4755
Epoch 95/100
51/51 [==============================] - 6s 118ms/step - loss: 0.0687 - accuracy: 0.9800 - val_loss: 3.3220 - val_accuracy: 0.4625
Epoch 96/100
51/51 [==============================] - 6s 117ms/step - loss: 0.0571 - accuracy: 0.9828 - val_loss: 3.0719 - val_accuracy: 0.4705
Epoch 97/100
51/51 [==============================] - 6s 118ms/step - loss: 0.0509 - accuracy: 0.9845 - val_loss: 3.5358 - val_accuracy: 0.4692
Epoch 98/100
51/51 [==============================] - 6s 109ms/step - loss: 0.0523 - accuracy: 0.9855 - val_loss: 3.5186 - val_accuracy: 0.4708
Epoch 99/100
51/51 [==============================] - 6s 109ms/step - loss: 0.0558 - accuracy: 0.9843 - val_loss: 4.0200 - val_accuracy: 0.4657
Epoch 100/100
51/51 [==============================] - 6s 118ms/step - loss: 0.0450 - accuracy: 0.9854 - val_loss: 3.6270 - val_accuracy: 0.4694
Epoch 1/100
51/51 [==============================] - 9s 128ms/step - loss: 40.5501 - accuracy: 0.1254 - val_loss: 2.1865 - val_accuracy: 0.1629
Epoch 2/100
51/51 [==============================] - 5s 108ms/step - loss: 2.1514 - accuracy: 0.1694 - val_loss: 2.0939 - val_accuracy: 0.1822
Epoch 3/100
51/51 [==============================] - 5s 108ms/step - loss: 2.0609 - accuracy: 0.1918 - val_loss: 1.9982 - val_accuracy: 0.2088
Epoch 4/100
51/51 [==============================] - 6s 109ms/step - loss: 1.9449 - accuracy: 0.2309 - val_loss: 1.8291 - val_accuracy: 0.3011
Epoch 5/100
51/51 [==============================] - 6s 109ms/step - loss: 1.8049 - accuracy: 0.3011 - val_loss: 1.9567 - val_accuracy: 0.2357
Epoch 6/100
51/51 [==============================] - 6s 110ms/step - loss: 1.6790 - accuracy: 0.3551 - val_loss: 1.6376 - val_accuracy: 0.3548
Epoch 7/100
51/51 [==============================] - 6s 118ms/step - loss: 1.5238 - accuracy: 0.4143 - val_loss: 1.5992 - val_accuracy: 0.3912
Epoch 8/100
51/51 [==============================] - 6s 118ms/step - loss: 1.4475 - accuracy: 0.4503 - val_loss: 1.5375 - val_accuracy: 0.4223
Epoch 9/100
51/51 [==============================] - 6s 118ms/step - loss: 1.3315 - accuracy: 0.4971 - val_loss: 1.5833 - val_accuracy: 0.4111
Epoch 10/100
51/51 [==============================] - 6s 117ms/step - loss: 1.2470 - accuracy: 0.5303 - val_loss: 1.5295 - val_accuracy: 0.4298
Epoch 11/100
51/51 [==============================] - 6s 117ms/step - loss: 1.1107 - accuracy: 0.5877 - val_loss: 1.5406 - val_accuracy: 0.4454
Epoch 12/100
51/51 [==============================] - 6s 117ms/step - loss: 0.9737 - accuracy: 0.6454 - val_loss: 1.5510 - val_accuracy: 0.4598
Epoch 13/100
51/51 [==============================] - 5s 108ms/step - loss: 0.8568 - accuracy: 0.6925 - val_loss: 1.5873 - val_accuracy: 0.4532
Epoch 14/100
51/51 [==============================] - 5s 108ms/step - loss: 0.7056 - accuracy: 0.7406 - val_loss: 1.6268 - val_accuracy: 0.4754
Epoch 15/100
51/51 [==============================] - 6s 118ms/step - loss: 0.6080 - accuracy: 0.7866 - val_loss: 1.7290 - val_accuracy: 0.4732
Epoch 16/100
51/51 [==============================] - 6s 117ms/step - loss: 0.4948 - accuracy: 0.8269 - val_loss: 1.8123 - val_accuracy: 0.4780
Epoch 17/100
51/51 [==============================] - 6s 118ms/step - loss: 0.4074 - accuracy: 0.8580 - val_loss: 1.9211 - val_accuracy: 0.4805
Epoch 18/100
51/51 [==============================] - 6s 109ms/step - loss: 0.3415 - accuracy: 0.8806 - val_loss: 2.0764 - val_accuracy: 0.4754
Epoch 19/100
51/51 [==============================] - 6s 118ms/step - loss: 0.2978 - accuracy: 0.8971 - val_loss: 2.1294 - val_accuracy: 0.4800
Epoch 20/100
51/51 [==============================] - 6s 109ms/step - loss: 0.2681 - accuracy: 0.9125 - val_loss: 2.1611 - val_accuracy: 0.4780
Epoch 21/100
51/51 [==============================] - 6s 119ms/step - loss: 0.2586 - accuracy: 0.9169 - val_loss: 2.1423 - val_accuracy: 0.4726
Epoch 22/100
51/51 [==============================] - 6s 109ms/step - loss: 0.2137 - accuracy: 0.9280 - val_loss: 2.3362 - val_accuracy: 0.4915
Epoch 23/100
51/51 [==============================] - 6s 118ms/step - loss: 0.1819 - accuracy: 0.9403 - val_loss: 2.3119 - val_accuracy: 0.4840
Epoch 24/100
51/51 [==============================] - 6s 109ms/step - loss: 0.1573 - accuracy: 0.9475 - val_loss: 2.3010 - val_accuracy: 0.4811
Epoch 25/100
51/51 [==============================] - 6s 119ms/step - loss: 0.1385 - accuracy: 0.9551 - val_loss: 2.3349 - val_accuracy: 0.4780
Epoch 26/100
51/51 [==============================] - 6s 109ms/step - loss: 0.1322 - accuracy: 0.9586 - val_loss: 2.3144 - val_accuracy: 0.4775
Epoch 27/100
51/51 [==============================] - 6s 110ms/step - loss: 0.1152 - accuracy: 0.9631 - val_loss: 2.5507 - val_accuracy: 0.4845
Epoch 28/100
51/51 [==============================] - 6s 118ms/step - loss: 0.1185 - accuracy: 0.9618 - val_loss: 2.6821 - val_accuracy: 0.4935
Epoch 29/100
51/51 [==============================] - 6s 117ms/step - loss: 0.1041 - accuracy: 0.9672 - val_loss: 2.5714 - val_accuracy: 0.4849
Epoch 30/100
51/51 [==============================] - 6s 110ms/step - loss: 0.1137 - accuracy: 0.9637 - val_loss: 2.6488 - val_accuracy: 0.4865
Epoch 31/100
51/51 [==============================] - 6s 117ms/step - loss: 0.1383 - accuracy: 0.9571 - val_loss: 2.4546 - val_accuracy: 0.4946
Epoch 32/100
51/51 [==============================] - 6s 109ms/step - loss: 0.0962 - accuracy: 0.9694 - val_loss: 2.5830 - val_accuracy: 0.4855
Epoch 33/100
51/51 [==============================] - 6s 117ms/step - loss: 0.0944 - accuracy: 0.9720 - val_loss: 2.5829 - val_accuracy: 0.4806
Epoch 34/100
51/51 [==============================] - 6s 110ms/step - loss: 0.0819 - accuracy: 0.9742 - val_loss: 2.6160 - val_accuracy: 0.4969
Epoch 35/100
51/51 [==============================] - 6s 117ms/step - loss: 0.0683 - accuracy: 0.9789 - val_loss: 2.7030 - val_accuracy: 0.4903
Epoch 36/100
51/51 [==============================] - 6s 118ms/step - loss: 0.0736 - accuracy: 0.9783 - val_loss: 2.6384 - val_accuracy: 0.4846
Epoch 37/100
51/51 [==============================] - 6s 117ms/step - loss: 0.0748 - accuracy: 0.9765 - val_loss: 2.7612 - val_accuracy: 0.4937
Epoch 38/100
51/51 [==============================] - 6s 110ms/step - loss: 0.0778 - accuracy: 0.9768 - val_loss: 2.7219 - val_accuracy: 0.4929
Epoch 39/100

### SVHN

In [ ]:
!wget http://ufldl.stanford.edu/housenumbers/train_32x32.mat
!wget http://ufldl.stanford.edu/housenumbers/test_32x32.mat

--2023-08-10 17:42:40--  http://ufldl.stanford.edu/housenumbers/train_32x32.mat
Resolving ufldl.stanford.edu (ufldl.stanford.edu)... 171.64.68.10
Connecting to ufldl.stanford.edu (ufldl.stanford.edu)|171.64.68.10|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 182040794 (174M) [text/plain]
Saving to: ‘train_32x32.mat’

train_32x32.mat     100%[===================>] 173.61M  53.4MB/s    in 4.1s

2023-08-10 17:42:44 (42.6 MB/s) - ‘train_32x32.mat’ saved [182040794/182040794]

--2023-08-10 17:42:44--  http://ufldl.stanford.edu/housenumbers/test_32x32.mat
Resolving ufldl.stanford.edu (ufldl.stanford.edu)... 171.64.68.10
Connecting to ufldl.stanford.edu (ufldl.stanford.edu)|171.64.68.10|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 64275384 (61M) [text/plain]
Saving to: ‘test_32x32.mat’

test_32x32.mat      100%[===================>]  61.30M  28.0MB/s    in 2.2s

2023-08-10 17:42:46 (28.0 MB/s) - ‘test_32x32.mat’ saved [64275384/64275384]

In [ ]:
import numpy as np
from tensorflow import keras
from sklearn.model_selection import KFold
import scipy.io as sio
from tensorflow.keras.utils import to_categorical
# Load the SVHN dataset
train_data = sio.loadmat("train_32x32.mat")
test_data = sio.loadmat("test_32x32.mat")

# Extract the images and labels from the downloaded data
train_images = np.transpose(train_data['X'], (3, 0, 1, 2))
train_labels = train_data['y']

test_images = np.transpose(test_data['X'], (3, 0, 1, 2))
test_labels = test_data['y']

# Change class labels to range from 0 to 9
train_labels[train_labels == 10] = 0
test_labels[test_labels == 10] = 0

# Perform one-hot encoding on the labels
num_classes = 10
train_labels = to_categorical(train_labels, num_classes)
test_labels = to_categorical(test_labels, num_classes)

# Print the shape of the loaded data
print("Train images shape:", train_images.shape)
print("Train labels shape:", train_labels.shape)
print("Test images shape:", test_images.shape)
print("Test labels shape:", test_labels.shape)

Train images shape: (73257, 32, 32, 3)
Train labels shape: (73257, 10)
Test images shape: (26032, 32, 32, 3)
Test labels shape: (26032, 10)

In [ ]:
x_train  = train_images
y_train = train_labels
x_test = test_images
y_test = test_labels
# Print the shape of the loaded data
print("Train images shape:", x_train.shape)
print("Train labels shape:", y_train.shape)
print("Test images shape:", x_test.shape)
print("Test labels shape:", y_test.shape)

Train images shape: (73257, 32, 32, 3)
Train labels shape: (73257, 10)
Test images shape: (26032, 32, 32, 3)
Test labels shape: (26032, 10)

In [ ]:
x = np.concatenate((x_train,x_test),axis = 0)
y = np.concatenate((y_train,y_test),axis = 0)
print(x.shape,y.shape)

(99289, 32, 32, 3) (99289, 10)

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPool2D,Dense,Flatten,Dropout,Input, AveragePooling2D, Activation,Conv2D, MaxPooling2D, BatchNormalization,Concatenate
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
from tensorflow.keras import regularizers, optimizers
from tensorflow.keras.preprocessing.image import ImageDataGenerator

from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers
from tensorflow.keras.regularizers import Regularizer

# Perform hold-out cross-validation
validation_scores = []

# Define the CrlBo regularizer
class CrlBoRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Number of K-folds
K = 2

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)
# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []
num_classes = 10
# Perform K-fold cross-validation
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]

# Task A: Original SVHN model
    model = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        Conv2D(32, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu'),
        layers.Dropout(0.25),
        Dense(num_classes, activation='softmax')
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model = model
        model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
        model.save_weights('FashionMNIST_A.h5')
        prior_weights = model.get_weights()
# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    fisher_matrix = []
    for i in range(len(model.trainable_weights)):
        fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

    for _ in range(num_samples):
        idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
        with tf.GradientTape() as tape:
            logits = model(x[idx:idx+1])
        gradients = tape.gradient(logits, model.trainable_weights)
        for i in range(len(fisher_matrix)):
            fisher_matrix[i] += tf.square(gradients[i])

    fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
    return fisher_matrix

fisher_matrix = compute_fisher(model, x_train_fold)
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]
# Task B: Fashion SVHN with CrlBo regularization
    model_CrlBoB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3),
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model_CrlBoB = model_CrlBoB
        model_CrlBoB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model_CrlBoB.load_weights('FashionMNIST_A.h5')
        model_CrlBoB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlBo_acc = 100 * model_CrlBoB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlBo method Accuracy: %.2f%%" % B_CrlBo_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
388/388 [==============================] - 15s 30ms/step - loss: 2.1276 - accuracy: 0.4794 - val_loss: 0.6824 - val_accuracy: 0.8112
Epoch 2/10
388/388 [==============================] - 8s 20ms/step - loss: 0.7415 - accuracy: 0.7760 - val_loss: 0.5085 - val_accuracy: 0.8526
Epoch 3/10
388/388 [==============================] - 8s 21ms/step - loss: 0.5872 - accuracy: 0.8230 - val_loss: 0.4447 - val_accuracy: 0.8726
Epoch 4/10
388/388 [==============================] - 7s 19ms/step - loss: 0.4963 - accuracy: 0.8487 - val_loss: 0.3967 - val_accuracy: 0.8935
Epoch 5/10
388/388 [==============================] - 8s 21ms/step - loss: 0.4367 - accuracy: 0.8657 - val_loss: 0.3470 - val_accuracy: 0.9018
Epoch 6/10
388/388 [==============================] - 7s 18ms/step - loss: 0.3943 - accuracy: 0.8813 - val_loss: 0.3263 - val_accuracy: 0.9083
Epoch 7/10
388/388 [==============================] - 9s 22ms/step - loss: 0.3602 - accuracy: 0.8901 - val_loss: 0.3049 - val_accuracy: 0.9152
Epoch 8/10
388/388 [==============================] - 8s 20ms/step - loss: 0.3352 - accuracy: 0.8971 - val_loss: 0.3141 - val_accuracy: 0.9122
Epoch 9/10
388/388 [==============================] - 7s 18ms/step - loss: 0.3097 - accuracy: 0.9061 - val_loss: 0.2976 - val_accuracy: 0.9186
Epoch 10/10
388/388 [==============================] - 8s 20ms/step - loss: 0.2910 - accuracy: 0.9105 - val_loss: 0.2907 - val_accuracy: 0.9197
Epoch 1/10
388/388 [==============================] - 14s 25ms/step - loss: 1.9871 - accuracy: 0.4855 - val_loss: 0.7643 - val_accuracy: 0.7745
Epoch 2/10
388/388 [==============================] - 7s 19ms/step - loss: 0.8605 - accuracy: 0.7286 - val_loss: 0.5911 - val_accuracy: 0.8262
Epoch 3/10
388/388 [==============================] - 8s 20ms/step - loss: 0.6862 - accuracy: 0.7866 - val_loss: 0.5156 - val_accuracy: 0.8603
Epoch 4/10
388/388 [==============================] - 8s 19ms/step - loss: 0.5592 - accuracy: 0.8274 - val_loss: 0.4106 - val_accuracy: 0.8819
Epoch 5/10
388/388 [==============================] - 7s 19ms/step - loss: 0.4698 - accuracy: 0.8556 - val_loss: 0.3926 - val_accuracy: 0.8869
Epoch 6/10
388/388 [==============================] - 7s 19ms/step - loss: 0.4174 - accuracy: 0.8727 - val_loss: 0.3504 - val_accuracy: 0.8997
Epoch 7/10
388/388 [==============================] - 8s 22ms/step - loss: 0.3820 - accuracy: 0.8820 - val_loss: 0.3477 - val_accuracy: 0.9032
Epoch 8/10
388/388 [==============================] - 8s 20ms/step - loss: 0.3437 - accuracy: 0.8941 - val_loss: 0.3229 - val_accuracy: 0.9095
Epoch 9/10
388/388 [==============================] - 8s 21ms/step - loss: 0.3254 - accuracy: 0.9013 - val_loss: 0.3076 - val_accuracy: 0.9158
Epoch 10/10
388/388 [==============================] - 12s 30ms/step - loss: 0.2979 - accuracy: 0.9074 - val_loss: 0.3199 - val_accuracy: 0.9148
Epoch 1/10
388/388 [==============================] - 32s 46ms/step - loss: 0.3890 - accuracy: 0.8868 - val_loss: 0.2127 - val_accuracy: 0.9398
Epoch 2/10
388/388 [==============================] - 11s 28ms/step - loss: 0.3102 - accuracy: 0.9082 - val_loss: 0.2017 - val_accuracy: 0.9416
Epoch 3/10
388/388 [==============================] - 11s 27ms/step - loss: 0.2699 - accuracy: 0.9194 - val_loss: 0.2142 - val_accuracy: 0.9377
Epoch 4/10
388/388 [==============================] - 13s 33ms/step - loss: 0.2282 - accuracy: 0.9308 - val_loss: 0.2082 - val_accuracy: 0.9402
Epoch 5/10
388/388 [==============================] - 11s 27ms/step - loss: 0.1973 - accuracy: 0.9386 - val_loss: 0.2188 - val_accuracy: 0.9369
Epoch 6/10
388/388 [==============================] - 11s 28ms/step - loss: 0.1757 - accuracy: 0.9454 - val_loss: 0.2477 - val_accuracy: 0.9314
Epoch 7/10
388/388 [==============================] - 13s 34ms/step - loss: 0.1569 - accuracy: 0.9515 - val_loss: 0.2383 - val_accuracy: 0.9378
Epoch 8/10
388/388 [==============================] - 11s 28ms/step - loss: 0.1468 - accuracy: 0.9540 - val_loss: 0.2550 - val_accuracy: 0.9310
Epoch 9/10
388/388 [==============================] - 13s 34ms/step - loss: 0.1285 - accuracy: 0.9596 - val_loss: 0.2588 - val_accuracy: 0.9350
Epoch 10/10
388/388 [==============================] - 13s 34ms/step - loss: 0.1077 - accuracy: 0.9655 - val_loss: 0.2723 - val_accuracy: 0.9351
1552/1552 [==============================] - 9s 6ms/step - loss: 0.1508 - accuracy: 0.9604
1552/1552 [==============================] - 13s 8ms/step - loss: 0.2723 - accuracy: 0.9351
1552/1552 [==============================] - 9s 5ms/step - loss: 0.1508 - accuracy: 0.9604
Test Accuracy: 0.9603988528251648
Task A Original Accuracy: 96.04%
Task B CrlBo method Accuracy: 93.51%
Epoch 1/10
388/388 [==============================] - 28s 40ms/step - loss: 0.2622 - accuracy: 0.9193 - val_loss: 0.3480 - val_accuracy: 0.9127
Epoch 2/10
388/388 [==============================] - 11s 28ms/step - loss: 0.2213 - accuracy: 0.9315 - val_loss: 0.3209 - val_accuracy: 0.9175
Epoch 3/10
388/388 [==============================] - 11s 28ms/step - loss: 0.1934 - accuracy: 0.9408 - val_loss: 0.3429 - val_accuracy: 0.9115
Epoch 4/10
388/388 [==============================] - 11s 29ms/step - loss: 0.1817 - accuracy: 0.9425 - val_loss: 0.3322 - val_accuracy: 0.9134
Epoch 5/10
388/388 [==============================] - 13s 32ms/step - loss: 0.1547 - accuracy: 0.9510 - val_loss: 0.3644 - val_accuracy: 0.9163
Epoch 6/10
388/388 [==============================] - 13s 33ms/step - loss: 0.1439 - accuracy: 0.9546 - val_loss: 0.3478 - val_accuracy: 0.9177
Epoch 7/10
388/388 [==============================] - 11s 29ms/step - loss: 0.1284 - accuracy: 0.9598 - val_loss: 0.3933 - val_accuracy: 0.9149
Epoch 8/10
388/388 [==============================] - 11s 27ms/step - loss: 0.1212 - accuracy: 0.9614 - val_loss: 0.3958 - val_accuracy: 0.9142
Epoch 9/10
388/388 [==============================] - 11s 28ms/step - loss: 0.1131 - accuracy: 0.9644 - val_loss: 0.4099 - val_accuracy: 0.9139
Epoch 10/10
388/388 [==============================] - 13s 34ms/step - loss: 0.1043 - accuracy: 0.9672 - val_loss: 0.4140 - val_accuracy: 0.9155
1552/1552 [==============================] - 7s 5ms/step - loss: 0.3199 - accuracy: 0.9148
1552/1552 [==============================] - 13s 8ms/step - loss: 0.4140 - accuracy: 0.9155
1552/1552 [==============================] - 7s 5ms/step - loss: 0.3199 - accuracy: 0.9148
Test Accuracy: 0.914773166179657
Task A Original Accuracy: 91.48%
Task B CrlBo method Accuracy: 91.55%
Fold-1: 96.04%
Fold-2: 91.48%

### Caltech101

In [ ]:
import tensorflow_datasets as tfds
import numpy as np
from skimage.transform import resize

# Load the Caltech 101 dataset
dataset_name = "caltech101"
builder = tfds.builder(dataset_name)

# Download and prepare the dataset
builder.download_and_prepare()

# Split the dataset into training and testing sets
train_dataset = builder.as_dataset(split="train")
test_dataset = builder.as_dataset(split="test")

# Iterate through the datasets to get features and labels
X_train = []
y_train = []
for example in tfds.as_numpy(train_dataset):
    X_train.append(example["image"])
    y_train.append(example["label"])

X_test = []
y_test = []
for example in tfds.as_numpy(test_dataset):
    X_test.append(example["image"])
    y_test.append(example["label"])

# Convert lists to numpy arrays
X_train = np.array(X_train)
y_train = np.array(y_train)
X_test = np.array(X_test)
y_test = np.array(y_test)

# Resize the image data to a common size
target_height, target_width, channels = 28, 28, 3
X_train_resized = np.array([resize(image, (target_height, target_width, channels)) for image in X_train])
X_test_resized = np.array([resize(image, (target_height, target_width, channels)) for image in X_test])

# Print the shape of the resized arrays
print("X_train resized shape:", X_train_resized.shape)
print("X_test resized shape:", X_test_resized.shape)

Downloading and preparing dataset 125.64 MiB (download: 125.64 MiB, generated: 132.86 MiB, total: 258.50 MiB) to /root/tensorflow_datasets/caltech101/3.0.1...

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

Generating splits...:   0%|          | 0/2 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/3060 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/caltech101/3.0.1.incompleteRFM208/caltech101-train.tfrecord*...:   0%|    …

Generating test examples...:   0%|          | 0/6084 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/caltech101/3.0.1.incompleteRFM208/caltech101-test.tfrecord*...:   0%|     …

Dataset caltech101 downloaded and prepared to /root/tensorflow_datasets/caltech101/3.0.1. Subsequent calls will reuse this data.

<ipython-input-1-d3b8c391cf7a>:30: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  X_train = np.array(X_train)
<ipython-input-1-d3b8c391cf7a>:32: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  X_test = np.array(X_test)

X_train resized shape: (3060, 28, 28, 3)
X_test resized shape: (6084, 28, 28, 3)

In [ ]:
x = np.concatenate((X_train_resized,X_test_resized), axis=0)
x.shape

(9144, 28, 28, 3)

In [ ]:
y = np.concatenate((y_train,y_test),axis=0)
y.shape

(9144,)

In [ ]:
import tensorflow as tf
y = tf.keras.utils.to_categorical(y, num_classes=102)
# y_test = tf.keras.utils.to_categorical(y_test, num_classes=102)
y.shape

(9144, 102)

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPool2D,Dense,Flatten,Dropout,Input, AveragePooling2D, Activation,Conv2D, MaxPooling2D, BatchNormalization,Concatenate
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
from tensorflow.keras import regularizers, optimizers
from tensorflow.keras.preprocessing.image import ImageDataGenerator

from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers
from tensorflow.keras.regularizers import Regularizer

# Perform hold-out cross-validation
validation_scores = []

# Define the CrlBo regularizer
class CrlBoRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Number of K-folds
K = 2

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)
# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []
num_classes = 102
# Perform K-fold cross-validation
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]

# Task A: Original SVHN model
    model = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(28, 28, 3)),
        Conv2D(32, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu'),
        layers.Dropout(0.25),
        Dense(num_classes, activation='softmax')
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model = model
        model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
        model.save_weights('FashionMNIST_A.h5')
        prior_weights = model.get_weights()
# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    fisher_matrix = []
    for i in range(len(model.trainable_weights)):
        fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

    for _ in range(num_samples):
        idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
        with tf.GradientTape() as tape:
            logits = model(x[idx:idx+1])
        gradients = tape.gradient(logits, model.trainable_weights)
        for i in range(len(fisher_matrix)):
            fisher_matrix[i] += tf.square(gradients[i])

    fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
    return fisher_matrix

fisher_matrix = compute_fisher(model, x_train_fold)
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]
# Task B: Fashion SVHN with CrlBo regularization
    model_CrlBoB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(28, 28, 3),
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model_CrlBoB = model_CrlBoB
        model_CrlBoB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model_CrlBoB.load_weights('FashionMNIST_A.h5')
        model_CrlBoB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlBo_acc = 100 * model_CrlBoB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlBo method Accuracy: %.2f%%" % B_CrlBo_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
36/36 [==============================] - 20s 44ms/step - loss: 4.1190 - accuracy: 0.1352 - val_loss: 3.8010 - val_accuracy: 0.2135
Epoch 2/10
36/36 [==============================] - 1s 24ms/step - loss: 3.5491 - accuracy: 0.2515 - val_loss: 3.3522 - val_accuracy: 0.2811
Epoch 3/10
36/36 [==============================] - 1s 18ms/step - loss: 3.0727 - accuracy: 0.3351 - val_loss: 2.9287 - val_accuracy: 0.3723
Epoch 4/10
36/36 [==============================] - 1s 21ms/step - loss: 2.6296 - accuracy: 0.4103 - val_loss: 2.6477 - val_accuracy: 0.4326
Epoch 5/10
36/36 [==============================] - 1s 19ms/step - loss: 2.2561 - accuracy: 0.4735 - val_loss: 2.5136 - val_accuracy: 0.4608
Epoch 6/10
36/36 [==============================] - 1s 20ms/step - loss: 1.9202 - accuracy: 0.5376 - val_loss: 2.3478 - val_accuracy: 0.4818
Epoch 7/10
36/36 [==============================] - 1s 26ms/step - loss: 1.6277 - accuracy: 0.5923 - val_loss: 2.3041 - val_accuracy: 0.4985
Epoch 8/10
36/36 [==============================] - 1s 22ms/step - loss: 1.3302 - accuracy: 0.6568 - val_loss: 2.2632 - val_accuracy: 0.5133
Epoch 9/10
36/36 [==============================] - 1s 27ms/step - loss: 1.1079 - accuracy: 0.6958 - val_loss: 2.3694 - val_accuracy: 0.5225
Epoch 10/10
36/36 [==============================] - 1s 25ms/step - loss: 0.8917 - accuracy: 0.7476 - val_loss: 2.4411 - val_accuracy: 0.5236
Epoch 1/10
36/36 [==============================] - 5s 36ms/step - loss: 4.1820 - accuracy: 0.1203 - val_loss: 3.9699 - val_accuracy: 0.1866
Epoch 2/10
36/36 [==============================] - 1s 21ms/step - loss: 3.6539 - accuracy: 0.2428 - val_loss: 3.3430 - val_accuracy: 0.3056
Epoch 3/10
36/36 [==============================] - 1s 20ms/step - loss: 3.1192 - accuracy: 0.3349 - val_loss: 2.8336 - val_accuracy: 0.3968
Epoch 4/10
36/36 [==============================] - 1s 23ms/step - loss: 2.6128 - accuracy: 0.4178 - val_loss: 2.5634 - val_accuracy: 0.4377
Epoch 5/10
36/36 [==============================] - 1s 23ms/step - loss: 2.1977 - accuracy: 0.4923 - val_loss: 2.3939 - val_accuracy: 0.4657
Epoch 6/10
36/36 [==============================] - 1s 19ms/step - loss: 1.8377 - accuracy: 0.5490 - val_loss: 2.2459 - val_accuracy: 0.5024
Epoch 7/10
36/36 [==============================] - 1s 25ms/step - loss: 1.5053 - accuracy: 0.6203 - val_loss: 2.2331 - val_accuracy: 0.5140
Epoch 8/10
36/36 [==============================] - 1s 37ms/step - loss: 1.2240 - accuracy: 0.6765 - val_loss: 2.2771 - val_accuracy: 0.5271
Epoch 9/10
36/36 [==============================] - 1s 30ms/step - loss: 0.9642 - accuracy: 0.7347 - val_loss: 2.3453 - val_accuracy: 0.5304
Epoch 10/10
36/36 [==============================] - 1s 30ms/step - loss: 0.7427 - accuracy: 0.7951 - val_loss: 2.4353 - val_accuracy: 0.5348
Epoch 1/10
36/36 [==============================] - 12s 119ms/step - loss: 2.1518 - accuracy: 0.5197 - val_loss: 0.7978 - val_accuracy: 0.8539
Epoch 2/10
36/36 [==============================] - 1s 27ms/step - loss: 1.4772 - accuracy: 0.6465 - val_loss: 0.6279 - val_accuracy: 0.8624
Epoch 3/10
36/36 [==============================] - 1s 27ms/step - loss: 1.0141 - accuracy: 0.7382 - val_loss: 0.5490 - val_accuracy: 0.8559
Epoch 4/10
36/36 [==============================] - 1s 27ms/step - loss: 0.6356 - accuracy: 0.8316 - val_loss: 0.6232 - val_accuracy: 0.8255
Epoch 5/10
36/36 [==============================] - 1s 24ms/step - loss: 0.3817 - accuracy: 0.8867 - val_loss: 0.6962 - val_accuracy: 0.8069
Epoch 6/10
36/36 [==============================] - 1s 26ms/step - loss: 0.2096 - accuracy: 0.9399 - val_loss: 0.7592 - val_accuracy: 0.8007
Epoch 7/10
36/36 [==============================] - 1s 23ms/step - loss: 0.1470 - accuracy: 0.9606 - val_loss: 0.8370 - val_accuracy: 0.7883
Epoch 8/10
36/36 [==============================] - 1s 25ms/step - loss: 0.1046 - accuracy: 0.9681 - val_loss: 0.8728 - val_accuracy: 0.7944
Epoch 9/10
36/36 [==============================] - 1s 25ms/step - loss: 0.0690 - accuracy: 0.9810 - val_loss: 0.9875 - val_accuracy: 0.7808
Epoch 10/10
36/36 [==============================] - 1s 25ms/step - loss: 0.0833 - accuracy: 0.9792 - val_loss: 1.0436 - val_accuracy: 0.7701
143/143 [==============================] - 1s 5ms/step - loss: 0.2621 - accuracy: 0.9479
143/143 [==============================] - 1s 9ms/step - loss: 1.0436 - accuracy: 0.7701
143/143 [==============================] - 1s 7ms/step - loss: 0.2621 - accuracy: 0.9479
Test Accuracy: 0.9479439854621887
Task A Original Accuracy: 94.79%
Task B CrlBo method Accuracy: 77.01%
Epoch 1/10
36/36 [==============================] - 12s 121ms/step - loss: 0.4171 - accuracy: 0.8821 - val_loss: 3.0743 - val_accuracy: 0.5297
Epoch 2/10
36/36 [==============================] - 1s 27ms/step - loss: 0.1885 - accuracy: 0.9431 - val_loss: 3.3499 - val_accuracy: 0.5337
Epoch 3/10
36/36 [==============================] - 1s 26ms/step - loss: 0.1378 - accuracy: 0.9584 - val_loss: 3.6363 - val_accuracy: 0.5271
Epoch 4/10
36/36 [==============================] - 1s 27ms/step - loss: 0.1253 - accuracy: 0.9650 - val_loss: 3.7606 - val_accuracy: 0.5346
Epoch 5/10
36/36 [==============================] - 1s 25ms/step - loss: 0.0825 - accuracy: 0.9766 - val_loss: 4.0671 - val_accuracy: 0.5381
Epoch 6/10
36/36 [==============================] - 1s 25ms/step - loss: 0.0620 - accuracy: 0.9814 - val_loss: 4.4611 - val_accuracy: 0.5293
Epoch 7/10
36/36 [==============================] - 1s 25ms/step - loss: 0.0827 - accuracy: 0.9766 - val_loss: 4.1811 - val_accuracy: 0.5330
Epoch 8/10
36/36 [==============================] - 1s 26ms/step - loss: 0.0669 - accuracy: 0.9799 - val_loss: 4.3902 - val_accuracy: 0.5311
Epoch 9/10
36/36 [==============================] - 1s 24ms/step - loss: 0.0488 - accuracy: 0.9862 - val_loss: 4.6250 - val_accuracy: 0.5302
Epoch 10/10
36/36 [==============================] - 1s 26ms/step - loss: 0.0654 - accuracy: 0.9808 - val_loss: 4.5595 - val_accuracy: 0.5265
143/143 [==============================] - 1s 5ms/step - loss: 2.4353 - accuracy: 0.5348
143/143 [==============================] - 1s 7ms/step - loss: 4.5595 - accuracy: 0.5265
143/143 [==============================] - 1s 4ms/step - loss: 2.4353 - accuracy: 0.5348
Test Accuracy: 0.5347769260406494
Task A Original Accuracy: 53.48%
Task B CrlBo method Accuracy: 52.65%
Fold-1: 94.79%
Fold-2: 53.48%

## Folds 5

### MNIST

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.regularizers import Regularizer
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import KFold
from tensorflow.keras import backend as K
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    f_accum = []
    for i in range(len(model.weights)):
        f_accum.append(np.zeros(K.int_shape(model.weights[i])))
    f_accum = np.array(f_accum)
    for _ in range(num_samples):
        idx = np.random.randint(0, x.shape[0])
        with tf.GradientTape() as tape:
            model_output = model(x[idx:idx+1])
        grads = tape.gradient(model_output, model.weights)
        for i in range(len(grads)):
            f_accum[i] += tf.square(grads[i])
    f_accum /= num_samples
    return f_accum

# Define the CrlB regularizer
class CrlBRegularizer(Regularizer):
    def __init__(self, fisher, prior_weights, lambda_=0.1):
        self.fisher = fisher
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i in range(len(self.fisher)):
            regularization += self.lambda_ * tf.reduce_sum(self.fisher[i] * tf.square(x - self.prior_weights[i]))
        return regularization

# Load the MNIST dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.reshape(-1, 28 * 28) / 255.0
x_test = x_test.reshape(-1, 28 * 28) / 255.0
y_train_onehot = tf.keras.utils.to_categorical(y_train, num_classes=10)
y_test_onehot = tf.keras.utils.to_categorical(y_test, num_classes=10)

# Number of K-folds
K = 5

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)

# Initialize the list to store test accuracies
accuracies = []

# Perform K-fold cross-validation
for train_index, test_index in kf.split(x_train, y_train_onehot):
    x_train_fold, x_test_fold = x_train[train_index], x_train[test_index]
    y_train_fold, y_test_fold = y_train_onehot[train_index], y_train_onehot[test_index]

# Task A: Original Fashion MNIST model
    model = Sequential([
    Dense(128, activation='relu', input_shape=(784,)),
    Dense(10, activation='softmax')
])
    model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
    model.save_weights('FashionMNIST_A.h5')

# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]

# Task B: Fashion MNIST with CrlB regularization
    model_CrlBB = Sequential([
        Dense(128, activation='relu', input_shape=(784,), kernel_regularizer=CrlBRegularizer(fisher_info[0], model.weights[0])),
        Dense(10, activation='softmax', kernel_regularizer=CrlBRegularizer(fisher_info[1], model.weights[1]))
    ])
    model_CrlBB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    model_CrlBB.load_weights('FashionMNIST_A.h5')
    model_CrlBB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlB_acc = 100 * model_CrlBB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlB method Accuracy: %.2f%%" % B_CrlB_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
11490434/11490434 [==============================] - 2s 0us/step
Epoch 1/10
375/375 [==============================] - 9s 9ms/step - loss: 0.3963 - accuracy: 0.8930 - val_loss: 0.2125 - val_accuracy: 0.9420
Epoch 2/10
375/375 [==============================] - 2s 5ms/step - loss: 0.1769 - accuracy: 0.9503 - val_loss: 0.1568 - val_accuracy: 0.9566
Epoch 3/10
375/375 [==============================] - 2s 5ms/step - loss: 0.1307 - accuracy: 0.9633 - val_loss: 0.1345 - val_accuracy: 0.9612
Epoch 4/10
375/375 [==============================] - 2s 5ms/step - loss: 0.1034 - accuracy: 0.9711 - val_loss: 0.1125 - val_accuracy: 0.9672
Epoch 5/10
375/375 [==============================] - 2s 5ms/step - loss: 0.0847 - accuracy: 0.9759 - val_loss: 0.1099 - val_accuracy: 0.9668
Epoch 6/10
375/375 [==============================] - 2s 4ms/step - loss: 0.0697 - accuracy: 0.9805 - val_loss: 0.0942 - val_accuracy: 0.9720
Epoch 7/10
375/375 [==============================] - 2s 6ms/step - loss: 0.0582 - accuracy: 0.9835 - val_loss: 0.0912 - val_accuracy: 0.9742
Epoch 8/10
375/375 [==============================] - 3s 7ms/step - loss: 0.0496 - accuracy: 0.9862 - val_loss: 0.0892 - val_accuracy: 0.9747
Epoch 9/10
375/375 [==============================] - 2s 5ms/step - loss: 0.0420 - accuracy: 0.9887 - val_loss: 0.0851 - val_accuracy: 0.9746
Epoch 10/10
375/375 [==============================] - 2s 5ms/step - loss: 0.0357 - accuracy: 0.9905 - val_loss: 0.0865 - val_accuracy: 0.9750
Epoch 1/10
375/375 [==============================] - 105s 80ms/step - loss: 0.0331 - accuracy: 0.9912 - val_loss: 0.0835 - val_accuracy: 0.9761
Epoch 2/10
375/375 [==============================] - 14s 36ms/step - loss: 0.0265 - accuracy: 0.9934 - val_loss: 0.0843 - val_accuracy: 0.9758
Epoch 3/10
375/375 [==============================] - 14s 38ms/step - loss: 0.0216 - accuracy: 0.9947 - val_loss: 0.0833 - val_accuracy: 0.9758
Epoch 4/10
375/375 [==============================] - 12s 33ms/step - loss: 0.0180 - accuracy: 0.9960 - val_loss: 0.0874 - val_accuracy: 0.9763
Epoch 5/10
375/375 [==============================] - 12s 33ms/step - loss: 0.0157 - accuracy: 0.9966 - val_loss: 0.0844 - val_accuracy: 0.9768
Epoch 6/10
375/375 [==============================] - 12s 32ms/step - loss: 0.0135 - accuracy: 0.9972 - val_loss: 0.0852 - val_accuracy: 0.9776
Epoch 7/10
375/375 [==============================] - 12s 31ms/step - loss: 0.0108 - accuracy: 0.9978 - val_loss: 0.0855 - val_accuracy: 0.9767
Epoch 8/10
375/375 [==============================] - 13s 36ms/step - loss: 0.0091 - accuracy: 0.9985 - val_loss: 0.0902 - val_accuracy: 0.9749
Epoch 9/10
375/375 [==============================] - 13s 34ms/step - loss: 0.0079 - accuracy: 0.9987 - val_loss: 0.0889 - val_accuracy: 0.9772
Epoch 10/10
375/375 [==============================] - 13s 34ms/step - loss: 0.0061 - accuracy: 0.9993 - val_loss: 0.0934 - val_accuracy: 0.9760
375/375 [==============================] - 2s 4ms/step - loss: 0.0865 - accuracy: 0.9750
375/375 [==============================] - 7s 19ms/step - loss: 0.0934 - accuracy: 0.9760
375/375 [==============================] - 2s 5ms/step - loss: 0.0865 - accuracy: 0.9750
Test Accuracy: 0.9750000238418579
Task A Original Accuracy: 97.50%
Task B EWC method Accuracy: 97.60%
Epoch 1/10
375/375 [==============================] - 3s 5ms/step - loss: 0.4024 - accuracy: 0.8890 - val_loss: 0.2308 - val_accuracy: 0.9337
Epoch 2/10
375/375 [==============================] - 2s 5ms/step - loss: 0.1895 - accuracy: 0.9457 - val_loss: 0.1649 - val_accuracy: 0.9531
Epoch 3/10
375/375 [==============================] - 2s 5ms/step - loss: 0.1407 - accuracy: 0.9594 - val_loss: 0.1391 - val_accuracy: 0.9597
Epoch 4/10
375/375 [==============================] - 2s 5ms/step - loss: 0.1098 - accuracy: 0.9679 - val_loss: 0.1253 - val_accuracy: 0.9627
Epoch 5/10
375/375 [==============================] - 2s 6ms/step - loss: 0.0892 - accuracy: 0.9743 - val_loss: 0.1081 - val_accuracy: 0.9674
Epoch 6/10
375/375 [==============================] - 2s 5ms/step - loss: 0.0731 - accuracy: 0.9791 - val_loss: 0.1019 - val_accuracy: 0.9702
Epoch 7/10
375/375 [==============================] - 2s 5ms/step - loss: 0.0601 - accuracy: 0.9826 - val_loss: 0.0946 - val_accuracy: 0.9712
Epoch 8/10
375/375 [==============================] - 2s 5ms/step - loss: 0.0512 - accuracy: 0.9854 - val_loss: 0.0903 - val_accuracy: 0.9730
Epoch 9/10
375/375 [==============================] - 2s 5ms/step - loss: 0.0437 - accuracy: 0.9879 - val_loss: 0.0887 - val_accuracy: 0.9720
Epoch 10/10
375/375 [==============================] - 2s 5ms/step - loss: 0.0366 - accuracy: 0.9900 - val_loss: 0.0895 - val_accuracy: 0.9731
Epoch 1/10
375/375 [==============================] - 68s 44ms/step - loss: 0.0338 - accuracy: 0.9905 - val_loss: 0.0907 - val_accuracy: 0.9732
Epoch 2/10
375/375 [==============================] - 6s 16ms/step - loss: 0.0266 - accuracy: 0.9933 - val_loss: 0.0864 - val_accuracy: 0.9733
Epoch 3/10
375/375 [==============================] - 6s 17ms/step - loss: 0.0221 - accuracy: 0.9945 - val_loss: 0.0882 - val_accuracy: 0.9746
Epoch 4/10
375/375 [==============================] - 6s 16ms/step - loss: 0.0186 - accuracy: 0.9954 - val_loss: 0.0888 - val_accuracy: 0.9741
Epoch 5/10
375/375 [==============================] - 6s 16ms/step - loss: 0.0150 - accuracy: 0.9970 - val_loss: 0.0911 - val_accuracy: 0.9734
Epoch 6/10
375/375 [==============================] - 6s 16ms/step - loss: 0.0130 - accuracy: 0.9971 - val_loss: 0.0951 - val_accuracy: 0.9737
Epoch 7/10
375/375 [==============================] - 6s 17ms/step - loss: 0.0106 - accuracy: 0.9982 - val_loss: 0.0927 - val_accuracy: 0.9748
Epoch 8/10
375/375 [==============================] - 6s 16ms/step - loss: 0.0086 - accuracy: 0.9987 - val_loss: 0.0919 - val_accuracy: 0.9750
Epoch 9/10
375/375 [==============================] - 7s 19ms/step - loss: 0.0074 - accuracy: 0.9989 - val_loss: 0.0958 - val_accuracy: 0.9753
Epoch 10/10
375/375 [==============================] - 6s 17ms/step - loss: 0.0069 - accuracy: 0.9990 - val_loss: 0.0942 - val_accuracy: 0.9768
375/375 [==============================] - 1s 3ms/step - loss: 0.0895 - accuracy: 0.9731
375/375 [==============================] - 5s 12ms/step - loss: 0.0942 - accuracy: 0.9768
375/375 [==============================] - 1s 3ms/step - loss: 0.0895 - accuracy: 0.9731
Test Accuracy: 0.9730833172798157
Task A Original Accuracy: 97.31%
Task B EWC method Accuracy: 97.68%
Epoch 1/10
375/375 [==============================] - 2s 4ms/step - loss: 0.3946 - accuracy: 0.8916 - val_loss: 0.2280 - val_accuracy: 0.9341
Epoch 2/10
375/375 [==============================] - 1s 3ms/step - loss: 0.1782 - accuracy: 0.9487 - val_loss: 0.1613 - val_accuracy: 0.9532
Epoch 3/10
375/375 [==============================] - 1s 4ms/step - loss: 0.1278 - accuracy: 0.9633 - val_loss: 0.1357 - val_accuracy: 0.9601
Epoch 4/10
375/375 [==============================] - 1s 4ms/step - loss: 0.1008 - accuracy: 0.9712 - val_loss: 0.1183 - val_accuracy: 0.9656
Epoch 5/10
375/375 [==============================] - 2s 4ms/step - loss: 0.0815 - accuracy: 0.9764 - val_loss: 0.1094 - val_accuracy: 0.9686
Epoch 6/10
375/375 [==============================] - 2s 5ms/step - loss: 0.0669 - accuracy: 0.9808 - val_loss: 0.1042 - val_accuracy: 0.9698
Epoch 7/10
375/375 [==============================] - 1s 3ms/step - loss: 0.0566 - accuracy: 0.9839 - val_loss: 0.0988 - val_accuracy: 0.9698
Epoch 8/10
375/375 [==============================] - 1s 3ms/step - loss: 0.0470 - accuracy: 0.9866 - val_loss: 0.0945 - val_accuracy: 0.9719
Epoch 9/10
375/375 [==============================] - 1s 4ms/step - loss: 0.0395 - accuracy: 0.9896 - val_loss: 0.0907 - val_accuracy: 0.9728
Epoch 10/10
375/375 [==============================] - 1s 4ms/step - loss: 0.0335 - accuracy: 0.9912 - val_loss: 0.0956 - val_accuracy: 0.9709
Epoch 1/10
375/375 [==============================] - 60s 36ms/step - loss: 0.0310 - accuracy: 0.9914 - val_loss: 0.0857 - val_accuracy: 0.9751
Epoch 2/10
375/375 [==============================] - 2s 5ms/step - loss: 0.0250 - accuracy: 0.9934 - val_loss: 0.0866 - val_accuracy: 0.9743
Epoch 3/10
375/375 [==============================] - 3s 8ms/step - loss: 0.0206 - accuracy: 0.9951 - val_loss: 0.0887 - val_accuracy: 0.9747
Epoch 4/10
375/375 [==============================] - 3s 8ms/step - loss: 0.0167 - accuracy: 0.9962 - val_loss: 0.0901 - val_accuracy: 0.9748
Epoch 5/10
375/375 [==============================] - 2s 5ms/step - loss: 0.0140 - accuracy: 0.9975 - val_loss: 0.0947 - val_accuracy: 0.9750
Epoch 6/10
375/375 [==============================] - 2s 5ms/step - loss: 0.0118 - accuracy: 0.9979 - val_loss: 0.0872 - val_accuracy: 0.9761
Epoch 7/10
375/375 [==============================] - 2s 5ms/step - loss: 0.0091 - accuracy: 0.9987 - val_loss: 0.0902 - val_accuracy: 0.9747
Epoch 8/10
375/375 [==============================] - 2s 5ms/step - loss: 0.0086 - accuracy: 0.9985 - val_loss: 0.0961 - val_accuracy: 0.9733
Epoch 9/10
375/375 [==============================] - 3s 7ms/step - loss: 0.0067 - accuracy: 0.9991 - val_loss: 0.0970 - val_accuracy: 0.9760
Epoch 10/10
375/375 [==============================] - 2s 6ms/step - loss: 0.0056 - accuracy: 0.9994 - val_loss: 0.1007 - val_accuracy: 0.9745
375/375 [==============================] - 1s 2ms/step - loss: 0.0956 - accuracy: 0.9709
375/375 [==============================] - 2s 6ms/step - loss: 0.1007 - accuracy: 0.9745
375/375 [==============================] - 1s 3ms/step - loss: 0.0956 - accuracy: 0.9709
Test Accuracy: 0.9709166884422302
Task A Original Accuracy: 97.09%
Task B EWC method Accuracy: 97.45%
Epoch 1/10
375/375 [==============================] - 2s 4ms/step - loss: 0.3980 - accuracy: 0.8922 - val_loss: 0.2305 - val_accuracy: 0.9368
Epoch 2/10
375/375 [==============================] - 1s 3ms/step - loss: 0.1827 - accuracy: 0.9477 - val_loss: 0.1665 - val_accuracy: 0.9515
Epoch 3/10
375/375 [==============================] - 1s 4ms/step - loss: 0.1319 - accuracy: 0.9624 - val_loss: 0.1402 - val_accuracy: 0.9582
Epoch 4/10
375/375 [==============================] - 1s 3ms/step - loss: 0.1023 - accuracy: 0.9708 - val_loss: 0.1189 - val_accuracy: 0.9656
Epoch 5/10
375/375 [==============================] - 1s 3ms/step - loss: 0.0826 - accuracy: 0.9762 - val_loss: 0.1101 - val_accuracy: 0.9674
Epoch 6/10
375/375 [==============================] - 1s 3ms/step - loss: 0.0696 - accuracy: 0.9797 - val_loss: 0.1058 - val_accuracy: 0.9681
Epoch 7/10
375/375 [==============================] - 2s 5ms/step - loss: 0.0578 - accuracy: 0.9837 - val_loss: 0.0968 - val_accuracy: 0.9724
Epoch 8/10
375/375 [==============================] - 2s 4ms/step - loss: 0.0488 - accuracy: 0.9862 - val_loss: 0.0941 - val_accuracy: 0.9730
Epoch 9/10
375/375 [==============================] - 1s 3ms/step - loss: 0.0416 - accuracy: 0.9886 - val_loss: 0.0932 - val_accuracy: 0.9739
Epoch 10/10
375/375 [==============================] - 1s 3ms/step - loss: 0.0351 - accuracy: 0.9905 - val_loss: 0.0902 - val_accuracy: 0.9732
Epoch 1/10
375/375 [==============================] - 62s 37ms/step - loss: 0.0323 - accuracy: 0.9914 - val_loss: 0.0927 - val_accuracy: 0.9728
Epoch 2/10
375/375 [==============================] - 3s 7ms/step - loss: 0.0253 - accuracy: 0.9937 - val_loss: 0.0960 - val_accuracy: 0.9732
Epoch 3/10
375/375 [==============================] - 2s 5ms/step - loss: 0.0216 - accuracy: 0.9950 - val_loss: 0.0936 - val_accuracy: 0.9728
Epoch 4/10
375/375 [==============================] - 2s 5ms/step - loss: 0.0185 - accuracy: 0.9956 - val_loss: 0.0923 - val_accuracy: 0.9742
Epoch 5/10
375/375 [==============================] - 2s 5ms/step - loss: 0.0145 - accuracy: 0.9971 - val_loss: 0.0904 - val_accuracy: 0.9763
Epoch 6/10
375/375 [==============================] - 2s 5ms/step - loss: 0.0117 - accuracy: 0.9980 - val_loss: 0.0970 - val_accuracy: 0.9741
Epoch 7/10
375/375 [==============================] - 3s 8ms/step - loss: 0.0110 - accuracy: 0.9978 - val_loss: 0.0969 - val_accuracy: 0.9744
Epoch 8/10
375/375 [==============================] - 2s 6ms/step - loss: 0.0087 - accuracy: 0.9985 - val_loss: 0.0986 - val_accuracy: 0.9739
Epoch 9/10
375/375 [==============================] - 2s 5ms/step - loss: 0.0072 - accuracy: 0.9990 - val_loss: 0.0987 - val_accuracy: 0.9762
Epoch 10/10
375/375 [==============================] - 2s 6ms/step - loss: 0.0064 - accuracy: 0.9992 - val_loss: 0.1050 - val_accuracy: 0.9750
375/375 [==============================] - 1s 3ms/step - loss: 0.0902 - accuracy: 0.9732
375/375 [==============================] - 2s 4ms/step - loss: 0.1050 - accuracy: 0.9750
375/375 [==============================] - 1s 3ms/step - loss: 0.0902 - accuracy: 0.9732
Test Accuracy: 0.9732499718666077
Task A Original Accuracy: 97.32%
Task B EWC method Accuracy: 97.50%
Epoch 1/10
375/375 [==============================] - 2s 4ms/step - loss: 0.3973 - accuracy: 0.8913 - val_loss: 0.2294 - val_accuracy: 0.9350
Epoch 2/10
375/375 [==============================] - 1s 3ms/step - loss: 0.1894 - accuracy: 0.9471 - val_loss: 0.1700 - val_accuracy: 0.9492
Epoch 3/10
375/375 [==============================] - 1s 4ms/step - loss: 0.1415 - accuracy: 0.9610 - val_loss: 0.1465 - val_accuracy: 0.9551
Epoch 4/10
375/375 [==============================] - 2s 5ms/step - loss: 0.1126 - accuracy: 0.9680 - val_loss: 0.1280 - val_accuracy: 0.9622
Epoch 5/10
375/375 [==============================] - 1s 4ms/step - loss: 0.0905 - accuracy: 0.9744 - val_loss: 0.1114 - val_accuracy: 0.9662
Epoch 6/10
375/375 [==============================] - 1s 3ms/step - loss: 0.0750 - accuracy: 0.9781 - val_loss: 0.1053 - val_accuracy: 0.9667
Epoch 7/10
375/375 [==============================] - 1s 3ms/step - loss: 0.0625 - accuracy: 0.9823 - val_loss: 0.0960 - val_accuracy: 0.9683
Epoch 8/10
375/375 [==============================] - 1s 3ms/step - loss: 0.0530 - accuracy: 0.9856 - val_loss: 0.0944 - val_accuracy: 0.9700
Epoch 9/10
375/375 [==============================] - 1s 4ms/step - loss: 0.0457 - accuracy: 0.9875 - val_loss: 0.0928 - val_accuracy: 0.9713
Epoch 10/10
375/375 [==============================] - 1s 4ms/step - loss: 0.0386 - accuracy: 0.9895 - val_loss: 0.0920 - val_accuracy: 0.9722
Epoch 1/10
375/375 [==============================] - 61s 36ms/step - loss: 0.0352 - accuracy: 0.9901 - val_loss: 0.0861 - val_accuracy: 0.9735
Epoch 2/10
375/375 [==============================] - 3s 7ms/step - loss: 0.0284 - accuracy: 0.9926 - val_loss: 0.0885 - val_accuracy: 0.9723
Epoch 3/10
375/375 [==============================] - 3s 8ms/step - loss: 0.0240 - accuracy: 0.9938 - val_loss: 0.0866 - val_accuracy: 0.9732
Epoch 4/10
375/375 [==============================] - 2s 6ms/step - loss: 0.0195 - accuracy: 0.9958 - val_loss: 0.0833 - val_accuracy: 0.9758
Epoch 5/10
375/375 [==============================] - 2s 6ms/step - loss: 0.0168 - accuracy: 0.9964 - val_loss: 0.0850 - val_accuracy: 0.9732
Epoch 6/10
375/375 [==============================] - 2s 6ms/step - loss: 0.0145 - accuracy: 0.9971 - val_loss: 0.0834 - val_accuracy: 0.9749
Epoch 7/10
375/375 [==============================] - 2s 6ms/step - loss: 0.0117 - accuracy: 0.9979 - val_loss: 0.0861 - val_accuracy: 0.9754
Epoch 8/10
375/375 [==============================] - 3s 8ms/step - loss: 0.0096 - accuracy: 0.9986 - val_loss: 0.0868 - val_accuracy: 0.9756
Epoch 9/10
375/375 [==============================] - 2s 6ms/step - loss: 0.0093 - accuracy: 0.9983 - val_loss: 0.0882 - val_accuracy: 0.9759
Epoch 10/10
375/375 [==============================] - 2s 5ms/step - loss: 0.0071 - accuracy: 0.9990 - val_loss: 0.0912 - val_accuracy: 0.9754
375/375 [==============================] - 1s 3ms/step - loss: 0.0920 - accuracy: 0.9722
375/375 [==============================] - 2s 4ms/step - loss: 0.0912 - accuracy: 0.9754
375/375 [==============================] - 1s 3ms/step - loss: 0.0920 - accuracy: 0.9722
Test Accuracy: 0.9721666574478149
Task A Original Accuracy: 97.22%
Task B EWC method Accuracy: 97.54%
Fold-1: 97.50%
Fold-2: 97.31%
Fold-3: 97.09%
Fold-4: 97.32%
Fold-5: 97.22%

### PermutedMNIST

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.regularizers import Regularizer
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import KFold
from tensorflow.keras import backend as K
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    f_accum = []
    for i in range(len(model.weights)):
        f_accum.append(np.zeros(K.int_shape(model.weights[i])))
    f_accum = np.array(f_accum)
    for _ in range(num_samples):
        idx = np.random.randint(0, x.shape[0])
        with tf.GradientTape() as tape:
            model_output = model(x[idx:idx+1])
        grads = tape.gradient(model_output, model.weights)
        for i in range(len(grads)):
            f_accum[i] += tf.square(grads[i])
    f_accum /= num_samples
    return f_accum

# Define the CrlB regularizer
class CrlBRegularizer(Regularizer):
    def __init__(self, fisher, prior_weights, lambda_=0.1):
        self.fisher = fisher
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i in range(len(self.fisher)):
            regularization += self.lambda_ * tf.reduce_sum(self.fisher[i] * tf.square(x - self.prior_weights[i]))
        return regularization


# Number of K-folds
K = 5

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)
# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []

# Perform K-fold cross-validation
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]

# Task A: Original Fashion MNIST model
    model = Sequential([
    Dense(128, activation='relu', input_shape=(784,)),
    Dense(10, activation='softmax')
])
    model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
    model.save_weights('FashionMNIST_A.h5')

# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]

# Task B: Fashion MNIST with CrlB regularization
    model_CrlBB = Sequential([
        Dense(128, activation='relu', input_shape=(784,), kernel_regularizer=CrlBRegularizer(fisher_info[0], model.weights[0])),
        Dense(10, activation='softmax', kernel_regularizer=CrlBRegularizer(fisher_info[1], model.weights[1]))
    ])
    model_CrlBB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    model_CrlBB.load_weights('FashionMNIST_A.h5')
    model_CrlBB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlB_acc = 100 * model_CrlBB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlB method Accuracy: %.2f%%" % B_CrlB_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
438/438 [==============================] - 10s 6ms/step - loss: 0.3610 - accuracy: 0.9013 - val_loss: 0.2092 - val_accuracy: 0.9406
Epoch 2/10
438/438 [==============================] - 2s 5ms/step - loss: 0.1655 - accuracy: 0.9525 - val_loss: 0.1508 - val_accuracy: 0.9571
Epoch 3/10
438/438 [==============================] - 3s 7ms/step - loss: 0.1191 - accuracy: 0.9654 - val_loss: 0.1279 - val_accuracy: 0.9626
Epoch 4/10
438/438 [==============================] - 2s 5ms/step - loss: 0.0926 - accuracy: 0.9724 - val_loss: 0.1106 - val_accuracy: 0.9688
Epoch 5/10
438/438 [==============================] - 2s 5ms/step - loss: 0.0743 - accuracy: 0.9781 - val_loss: 0.1033 - val_accuracy: 0.9688
Epoch 6/10
438/438 [==============================] - 2s 5ms/step - loss: 0.0624 - accuracy: 0.9812 - val_loss: 0.0964 - val_accuracy: 0.9722
Epoch 7/10
438/438 [==============================] - 2s 5ms/step - loss: 0.0522 - accuracy: 0.9850 - val_loss: 0.0978 - val_accuracy: 0.9723
Epoch 8/10
438/438 [==============================] - 3s 6ms/step - loss: 0.0443 - accuracy: 0.9874 - val_loss: 0.0897 - val_accuracy: 0.9731
Epoch 9/10
438/438 [==============================] - 3s 6ms/step - loss: 0.0366 - accuracy: 0.9895 - val_loss: 0.0875 - val_accuracy: 0.9749
Epoch 10/10
438/438 [==============================] - 2s 5ms/step - loss: 0.0322 - accuracy: 0.9907 - val_loss: 0.0860 - val_accuracy: 0.9751
Epoch 1/10
438/438 [==============================] - 101s 55ms/step - loss: 0.0289 - accuracy: 0.9922 - val_loss: 0.0917 - val_accuracy: 0.9737
Epoch 2/10
438/438 [==============================] - 4s 9ms/step - loss: 0.0243 - accuracy: 0.9932 - val_loss: 0.0869 - val_accuracy: 0.9751
Epoch 3/10
438/438 [==============================] - 5s 11ms/step - loss: 0.0200 - accuracy: 0.9951 - val_loss: 0.0851 - val_accuracy: 0.9757
Epoch 4/10
438/438 [==============================] - 4s 9ms/step - loss: 0.0167 - accuracy: 0.9958 - val_loss: 0.0852 - val_accuracy: 0.9769
Epoch 5/10
438/438 [==============================] - 4s 9ms/step - loss: 0.0139 - accuracy: 0.9969 - val_loss: 0.0877 - val_accuracy: 0.9766
Epoch 6/10
438/438 [==============================] - 5s 11ms/step - loss: 0.0116 - accuracy: 0.9976 - val_loss: 0.0932 - val_accuracy: 0.9746
Epoch 7/10
438/438 [==============================] - 4s 9ms/step - loss: 0.0105 - accuracy: 0.9977 - val_loss: 0.0859 - val_accuracy: 0.9774
Epoch 8/10
438/438 [==============================] - 4s 8ms/step - loss: 0.0083 - accuracy: 0.9984 - val_loss: 0.0883 - val_accuracy: 0.9770
Epoch 9/10
438/438 [==============================] - 5s 11ms/step - loss: 0.0081 - accuracy: 0.9985 - val_loss: 0.0919 - val_accuracy: 0.9770
Epoch 10/10
438/438 [==============================] - 4s 9ms/step - loss: 0.0066 - accuracy: 0.9988 - val_loss: 0.0919 - val_accuracy: 0.9774
438/438 [==============================] - 1s 3ms/step - loss: 0.0860 - accuracy: 0.9751
438/438 [==============================] - 3s 6ms/step - loss: 0.0919 - accuracy: 0.9774
438/438 [==============================] - 1s 3ms/step - loss: 0.0860 - accuracy: 0.9751
Test Accuracy: 0.9751428365707397
Task A Original Accuracy: 97.51%
Task B EWC method Accuracy: 97.74%
Epoch 1/10
438/438 [==============================] - 5s 8ms/step - loss: 0.3643 - accuracy: 0.9003 - val_loss: 0.2074 - val_accuracy: 0.9396
Epoch 2/10
438/438 [==============================] - 2s 6ms/step - loss: 0.1699 - accuracy: 0.9505 - val_loss: 0.1485 - val_accuracy: 0.9568
Epoch 3/10
438/438 [==============================] - 2s 5ms/step - loss: 0.1224 - accuracy: 0.9643 - val_loss: 0.1242 - val_accuracy: 0.9634
Epoch 4/10
438/438 [==============================] - 2s 5ms/step - loss: 0.0959 - accuracy: 0.9718 - val_loss: 0.1060 - val_accuracy: 0.9676
Epoch 5/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0777 - accuracy: 0.9773 - val_loss: 0.0943 - val_accuracy: 0.9716
Epoch 6/10
438/438 [==============================] - 2s 5ms/step - loss: 0.0642 - accuracy: 0.9816 - val_loss: 0.0921 - val_accuracy: 0.9710
Epoch 7/10
438/438 [==============================] - 2s 5ms/step - loss: 0.0545 - accuracy: 0.9839 - val_loss: 0.0852 - val_accuracy: 0.9739
Epoch 8/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0450 - accuracy: 0.9871 - val_loss: 0.0829 - val_accuracy: 0.9742
Epoch 9/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0385 - accuracy: 0.9892 - val_loss: 0.0801 - val_accuracy: 0.9752
Epoch 10/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0327 - accuracy: 0.9912 - val_loss: 0.0791 - val_accuracy: 0.9756
Epoch 1/10
438/438 [==============================] - 73s 50ms/step - loss: 0.0315 - accuracy: 0.9902 - val_loss: 0.0809 - val_accuracy: 0.9743
Epoch 2/10
438/438 [==============================] - 10s 24ms/step - loss: 0.0244 - accuracy: 0.9933 - val_loss: 0.0785 - val_accuracy: 0.9752
Epoch 3/10
438/438 [==============================] - 9s 21ms/step - loss: 0.0197 - accuracy: 0.9951 - val_loss: 0.0762 - val_accuracy: 0.9781
Epoch 4/10
438/438 [==============================] - 10s 23ms/step - loss: 0.0170 - accuracy: 0.9958 - val_loss: 0.0820 - val_accuracy: 0.9751
Epoch 5/10
438/438 [==============================] - 10s 22ms/step - loss: 0.0143 - accuracy: 0.9966 - val_loss: 0.0760 - val_accuracy: 0.9777
Epoch 6/10
438/438 [==============================] - 10s 23ms/step - loss: 0.0124 - accuracy: 0.9973 - val_loss: 0.0739 - val_accuracy: 0.9789
Epoch 7/10
438/438 [==============================] - 10s 24ms/step - loss: 0.0100 - accuracy: 0.9978 - val_loss: 0.0760 - val_accuracy: 0.9776
Epoch 8/10
438/438 [==============================] - 9s 21ms/step - loss: 0.0086 - accuracy: 0.9984 - val_loss: 0.0789 - val_accuracy: 0.9787
Epoch 9/10
438/438 [==============================] - 10s 23ms/step - loss: 0.0067 - accuracy: 0.9990 - val_loss: 0.0845 - val_accuracy: 0.9773
Epoch 10/10
438/438 [==============================] - 10s 22ms/step - loss: 0.0065 - accuracy: 0.9990 - val_loss: 0.0843 - val_accuracy: 0.9762
438/438 [==============================] - 1s 2ms/step - loss: 0.0791 - accuracy: 0.9756
438/438 [==============================] - 5s 12ms/step - loss: 0.0843 - accuracy: 0.9762
438/438 [==============================] - 1s 2ms/step - loss: 0.0791 - accuracy: 0.9756
Test Accuracy: 0.9755714535713196
Task A Original Accuracy: 97.56%
Task B EWC method Accuracy: 97.62%
Epoch 1/10
438/438 [==============================] - 3s 5ms/step - loss: 0.3734 - accuracy: 0.8955 - val_loss: 0.2076 - val_accuracy: 0.9423
Epoch 2/10
438/438 [==============================] - 2s 4ms/step - loss: 0.1701 - accuracy: 0.9532 - val_loss: 0.1492 - val_accuracy: 0.9576
Epoch 3/10
438/438 [==============================] - 2s 4ms/step - loss: 0.1229 - accuracy: 0.9646 - val_loss: 0.1324 - val_accuracy: 0.9606
Epoch 4/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0956 - accuracy: 0.9736 - val_loss: 0.1062 - val_accuracy: 0.9683
Epoch 5/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0761 - accuracy: 0.9782 - val_loss: 0.0970 - val_accuracy: 0.9706
Epoch 6/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0635 - accuracy: 0.9821 - val_loss: 0.0916 - val_accuracy: 0.9719
Epoch 7/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0529 - accuracy: 0.9850 - val_loss: 0.0864 - val_accuracy: 0.9726
Epoch 8/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0444 - accuracy: 0.9875 - val_loss: 0.0804 - val_accuracy: 0.9756
Epoch 9/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0376 - accuracy: 0.9900 - val_loss: 0.0815 - val_accuracy: 0.9741
Epoch 10/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0322 - accuracy: 0.9912 - val_loss: 0.0788 - val_accuracy: 0.9768
Epoch 1/10
438/438 [==============================] - 63s 33ms/step - loss: 0.0292 - accuracy: 0.9916 - val_loss: 0.0801 - val_accuracy: 0.9765
Epoch 2/10
438/438 [==============================] - 3s 8ms/step - loss: 0.0234 - accuracy: 0.9938 - val_loss: 0.0801 - val_accuracy: 0.9761
Epoch 3/10
438/438 [==============================] - 2s 6ms/step - loss: 0.0196 - accuracy: 0.9952 - val_loss: 0.0832 - val_accuracy: 0.9759
Epoch 4/10
438/438 [==============================] - 2s 6ms/step - loss: 0.0163 - accuracy: 0.9960 - val_loss: 0.0795 - val_accuracy: 0.9765
Epoch 5/10
438/438 [==============================] - 2s 6ms/step - loss: 0.0137 - accuracy: 0.9969 - val_loss: 0.0816 - val_accuracy: 0.9754
Epoch 6/10
438/438 [==============================] - 3s 6ms/step - loss: 0.0111 - accuracy: 0.9977 - val_loss: 0.0792 - val_accuracy: 0.9780
Epoch 7/10
438/438 [==============================] - 3s 7ms/step - loss: 0.0104 - accuracy: 0.9977 - val_loss: 0.0778 - val_accuracy: 0.9788
Epoch 8/10
438/438 [==============================] - 2s 6ms/step - loss: 0.0083 - accuracy: 0.9984 - val_loss: 0.0856 - val_accuracy: 0.9772
Epoch 9/10
438/438 [==============================] - 2s 6ms/step - loss: 0.0061 - accuracy: 0.9992 - val_loss: 0.0844 - val_accuracy: 0.9767
Epoch 10/10
438/438 [==============================] - 3s 6ms/step - loss: 0.0056 - accuracy: 0.9991 - val_loss: 0.0852 - val_accuracy: 0.9773
438/438 [==============================] - 1s 3ms/step - loss: 0.0788 - accuracy: 0.9768
438/438 [==============================] - 2s 4ms/step - loss: 0.0852 - accuracy: 0.9773
438/438 [==============================] - 1s 2ms/step - loss: 0.0788 - accuracy: 0.9768
Test Accuracy: 0.9767857193946838
Task A Original Accuracy: 97.68%
Task B EWC method Accuracy: 97.73%
Epoch 1/10
438/438 [==============================] - 3s 4ms/step - loss: 0.3726 - accuracy: 0.8976 - val_loss: 0.2086 - val_accuracy: 0.9438
Epoch 2/10
438/438 [==============================] - 2s 4ms/step - loss: 0.1705 - accuracy: 0.9506 - val_loss: 0.1559 - val_accuracy: 0.9545
Epoch 3/10
438/438 [==============================] - 2s 5ms/step - loss: 0.1200 - accuracy: 0.9656 - val_loss: 0.1282 - val_accuracy: 0.9631
Epoch 4/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0929 - accuracy: 0.9726 - val_loss: 0.1145 - val_accuracy: 0.9666
Epoch 5/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0747 - accuracy: 0.9784 - val_loss: 0.1031 - val_accuracy: 0.9689
Epoch 6/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0608 - accuracy: 0.9825 - val_loss: 0.0961 - val_accuracy: 0.9709
Epoch 7/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0513 - accuracy: 0.9851 - val_loss: 0.0914 - val_accuracy: 0.9740
Epoch 8/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0421 - accuracy: 0.9880 - val_loss: 0.0847 - val_accuracy: 0.9739
Epoch 9/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0361 - accuracy: 0.9901 - val_loss: 0.0879 - val_accuracy: 0.9751
Epoch 10/10
438/438 [==============================] - 2s 5ms/step - loss: 0.0299 - accuracy: 0.9918 - val_loss: 0.0842 - val_accuracy: 0.9760
Epoch 1/10
438/438 [==============================] - 63s 32ms/step - loss: 0.0273 - accuracy: 0.9922 - val_loss: 0.0820 - val_accuracy: 0.9761
Epoch 2/10
438/438 [==============================] - 3s 6ms/step - loss: 0.0225 - accuracy: 0.9938 - val_loss: 0.0879 - val_accuracy: 0.9755
Epoch 3/10
438/438 [==============================] - 3s 6ms/step - loss: 0.0187 - accuracy: 0.9953 - val_loss: 0.0912 - val_accuracy: 0.9760
Epoch 4/10
438/438 [==============================] - 3s 8ms/step - loss: 0.0148 - accuracy: 0.9967 - val_loss: 0.0900 - val_accuracy: 0.9751
Epoch 5/10
438/438 [==============================] - 2s 6ms/step - loss: 0.0128 - accuracy: 0.9974 - val_loss: 0.0893 - val_accuracy: 0.9758
Epoch 6/10
438/438 [==============================] - 2s 6ms/step - loss: 0.0106 - accuracy: 0.9979 - val_loss: 0.0876 - val_accuracy: 0.9766
Epoch 7/10
438/438 [==============================] - 2s 6ms/step - loss: 0.0089 - accuracy: 0.9983 - val_loss: 0.1017 - val_accuracy: 0.9744
Epoch 8/10
438/438 [==============================] - 4s 8ms/step - loss: 0.0075 - accuracy: 0.9988 - val_loss: 0.0922 - val_accuracy: 0.9759
Epoch 9/10
438/438 [==============================] - 2s 6ms/step - loss: 0.0062 - accuracy: 0.9992 - val_loss: 0.0900 - val_accuracy: 0.9774
Epoch 10/10
438/438 [==============================] - 2s 6ms/step - loss: 0.0055 - accuracy: 0.9992 - val_loss: 0.0943 - val_accuracy: 0.9766
438/438 [==============================] - 1s 2ms/step - loss: 0.0842 - accuracy: 0.9760
438/438 [==============================] - 2s 5ms/step - loss: 0.0943 - accuracy: 0.9766
438/438 [==============================] - 2s 3ms/step - loss: 0.0842 - accuracy: 0.9760
Test Accuracy: 0.9760000109672546
Task A Original Accuracy: 97.60%
Task B EWC method Accuracy: 97.66%
Epoch 1/10
438/438 [==============================] - 3s 4ms/step - loss: 0.3629 - accuracy: 0.9004 - val_loss: 0.2106 - val_accuracy: 0.9381
Epoch 2/10
438/438 [==============================] - 2s 4ms/step - loss: 0.1703 - accuracy: 0.9513 - val_loss: 0.1471 - val_accuracy: 0.9566
Epoch 3/10
438/438 [==============================] - 2s 4ms/step - loss: 0.1227 - accuracy: 0.9651 - val_loss: 0.1282 - val_accuracy: 0.9597
Epoch 4/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0961 - accuracy: 0.9726 - val_loss: 0.1098 - val_accuracy: 0.9657
Epoch 5/10
438/438 [==============================] - 2s 5ms/step - loss: 0.0771 - accuracy: 0.9776 - val_loss: 0.0937 - val_accuracy: 0.9715
Epoch 6/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0637 - accuracy: 0.9819 - val_loss: 0.0916 - val_accuracy: 0.9708
Epoch 7/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0545 - accuracy: 0.9846 - val_loss: 0.0876 - val_accuracy: 0.9723
Epoch 8/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0466 - accuracy: 0.9869 - val_loss: 0.0869 - val_accuracy: 0.9727
Epoch 9/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0393 - accuracy: 0.9890 - val_loss: 0.0777 - val_accuracy: 0.9761
Epoch 10/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0330 - accuracy: 0.9912 - val_loss: 0.0808 - val_accuracy: 0.9756
Epoch 1/10
438/438 [==============================] - 64s 34ms/step - loss: 0.0303 - accuracy: 0.9920 - val_loss: 0.0815 - val_accuracy: 0.9749
Epoch 2/10
438/438 [==============================] - 3s 7ms/step - loss: 0.0254 - accuracy: 0.9933 - val_loss: 0.0785 - val_accuracy: 0.9764
Epoch 3/10
438/438 [==============================] - 3s 6ms/step - loss: 0.0210 - accuracy: 0.9944 - val_loss: 0.0790 - val_accuracy: 0.9769
Epoch 4/10
438/438 [==============================] - 3s 6ms/step - loss: 0.0180 - accuracy: 0.9957 - val_loss: 0.0772 - val_accuracy: 0.9759
Epoch 5/10
438/438 [==============================] - 3s 6ms/step - loss: 0.0149 - accuracy: 0.9966 - val_loss: 0.0786 - val_accuracy: 0.9767
Epoch 6/10
438/438 [==============================] - 3s 8ms/step - loss: 0.0119 - accuracy: 0.9973 - val_loss: 0.0786 - val_accuracy: 0.9774
Epoch 7/10
438/438 [==============================] - 3s 6ms/step - loss: 0.0117 - accuracy: 0.9974 - val_loss: 0.0772 - val_accuracy: 0.9776
Epoch 8/10
438/438 [==============================] - 3s 6ms/step - loss: 0.0085 - accuracy: 0.9985 - val_loss: 0.0791 - val_accuracy: 0.9781
Epoch 9/10
438/438 [==============================] - 3s 6ms/step - loss: 0.0066 - accuracy: 0.9991 - val_loss: 0.0792 - val_accuracy: 0.9774
Epoch 10/10
438/438 [==============================] - 3s 7ms/step - loss: 0.0072 - accuracy: 0.9987 - val_loss: 0.0821 - val_accuracy: 0.9781
438/438 [==============================] - 1s 2ms/step - loss: 0.0808 - accuracy: 0.9756
438/438 [==============================] - 2s 4ms/step - loss: 0.0821 - accuracy: 0.9781
438/438 [==============================] - 1s 2ms/step - loss: 0.0808 - accuracy: 0.9756
Test Accuracy: 0.9755714535713196
Task A Original Accuracy: 97.56%
Task B EWC method Accuracy: 97.81%
Fold-1: 97.51%
Fold-2: 97.56%
Fold-3: 97.68%
Fold-4: 97.60%
Fold-5: 97.56%

### FashionMNIST

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.regularizers import Regularizer
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import KFold
from tensorflow.keras import backend as K
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    f_accum = []
    for i in range(len(model.weights)):
        f_accum.append(np.zeros(K.int_shape(model.weights[i])))
    f_accum = np.array(f_accum)
    for _ in range(num_samples):
        idx = np.random.randint(0, x.shape[0])
        with tf.GradientTape() as tape:
            model_output = model(x[idx:idx+1])
        grads = tape.gradient(model_output, model.weights)
        for i in range(len(grads)):
            f_accum[i] += tf.square(grads[i])
    f_accum /= num_samples
    return f_accum

# Define the CrlB regularizer
class CrlBRegularizer(Regularizer):
    def __init__(self, fisher, prior_weights, lambda_=0.1):
        self.fisher = fisher
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i in range(len(self.fisher)):
            regularization += self.lambda_ * tf.reduce_sum(self.fisher[i] * tf.square(x - self.prior_weights[i]))
        return regularization


# Number of K-folds
K = 5

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)
# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []

# Perform K-fold cross-validation
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]

# Task A: Original Fashion MNIST model
    model = Sequential([
    Dense(128, activation='relu', input_shape=(784,)),
    Dense(10, activation='softmax')
])
    model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
    model.save_weights('FashionMNIST_A.h5')

# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]

# Task B: Fashion MNIST with CrlB regularization
    model_CrlBB = Sequential([
        Dense(128, activation='relu', input_shape=(784,), kernel_regularizer=CrlBRegularizer(fisher_info[0], model.weights[0])),
        Dense(10, activation='softmax', kernel_regularizer=CrlBRegularizer(fisher_info[1], model.weights[1]))
    ])
    model_CrlBB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    model_CrlBB.load_weights('FashionMNIST_A.h5')
    model_CrlBB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlB_acc = 100 * model_CrlBB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlB method Accuracy: %.2f%%" % B_CrlB_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
438/438 [==============================] - 9s 8ms/step - loss: 0.5709 - accuracy: 0.8051 - val_loss: 0.4455 - val_accuracy: 0.8450
Epoch 2/10
438/438 [==============================] - 3s 6ms/step - loss: 0.4234 - accuracy: 0.8514 - val_loss: 0.4166 - val_accuracy: 0.8554
Epoch 3/10
438/438 [==============================] - 4s 8ms/step - loss: 0.3760 - accuracy: 0.8667 - val_loss: 0.3890 - val_accuracy: 0.8625
Epoch 4/10
438/438 [==============================] - 3s 7ms/step - loss: 0.3508 - accuracy: 0.8745 - val_loss: 0.3553 - val_accuracy: 0.8757
Epoch 5/10
438/438 [==============================] - 3s 7ms/step - loss: 0.3335 - accuracy: 0.8802 - val_loss: 0.3455 - val_accuracy: 0.8783
Epoch 6/10
438/438 [==============================] - 3s 6ms/step - loss: 0.3128 - accuracy: 0.8868 - val_loss: 0.3287 - val_accuracy: 0.8859
Epoch 7/10
438/438 [==============================] - 3s 6ms/step - loss: 0.3022 - accuracy: 0.8904 - val_loss: 0.3293 - val_accuracy: 0.8829
Epoch 8/10
438/438 [==============================] - 4s 8ms/step - loss: 0.2915 - accuracy: 0.8929 - val_loss: 0.3305 - val_accuracy: 0.8812
Epoch 9/10
438/438 [==============================] - 3s 6ms/step - loss: 0.2786 - accuracy: 0.8979 - val_loss: 0.3267 - val_accuracy: 0.8815
Epoch 10/10
438/438 [==============================] - 3s 7ms/step - loss: 0.2677 - accuracy: 0.9013 - val_loss: 0.3177 - val_accuracy: 0.8881
Epoch 1/10
438/438 [==============================] - 103s 52ms/step - loss: 0.2658 - accuracy: 0.9023 - val_loss: 0.3307 - val_accuracy: 0.8834
Epoch 2/10
438/438 [==============================] - 4s 10ms/step - loss: 0.2561 - accuracy: 0.9068 - val_loss: 0.3008 - val_accuracy: 0.8914
Epoch 3/10
438/438 [==============================] - 4s 8ms/step - loss: 0.2475 - accuracy: 0.9093 - val_loss: 0.3189 - val_accuracy: 0.8864
Epoch 4/10
438/438 [==============================] - 4s 9ms/step - loss: 0.2417 - accuracy: 0.9104 - val_loss: 0.3120 - val_accuracy: 0.8906
Epoch 5/10
438/438 [==============================] - 5s 10ms/step - loss: 0.2332 - accuracy: 0.9142 - val_loss: 0.3146 - val_accuracy: 0.8890
Epoch 6/10
438/438 [==============================] - 4s 9ms/step - loss: 0.2295 - accuracy: 0.9153 - val_loss: 0.2932 - val_accuracy: 0.8969
Epoch 7/10
438/438 [==============================] - 4s 8ms/step - loss: 0.2227 - accuracy: 0.9170 - val_loss: 0.3085 - val_accuracy: 0.8916
Epoch 8/10
438/438 [==============================] - 4s 10ms/step - loss: 0.2183 - accuracy: 0.9186 - val_loss: 0.2984 - val_accuracy: 0.8964
Epoch 9/10
438/438 [==============================] - 4s 9ms/step - loss: 0.2117 - accuracy: 0.9213 - val_loss: 0.3103 - val_accuracy: 0.8942
Epoch 10/10
438/438 [==============================] - 4s 9ms/step - loss: 0.2057 - accuracy: 0.9240 - val_loss: 0.3009 - val_accuracy: 0.8956
438/438 [==============================] - 2s 5ms/step - loss: 0.3177 - accuracy: 0.8881
438/438 [==============================] - 3s 6ms/step - loss: 0.3009 - accuracy: 0.8956
438/438 [==============================] - 1s 3ms/step - loss: 0.3177 - accuracy: 0.8881
Test Accuracy: 0.8881428837776184
Task A Original Accuracy: 88.81%
Task B EWC method Accuracy: 89.56%
Epoch 1/10
438/438 [==============================] - 5s 8ms/step - loss: 0.5757 - accuracy: 0.8039 - val_loss: 0.4492 - val_accuracy: 0.8413
Epoch 2/10
438/438 [==============================] - 3s 6ms/step - loss: 0.4150 - accuracy: 0.8544 - val_loss: 0.4082 - val_accuracy: 0.8547
Epoch 3/10
438/438 [==============================] - 2s 5ms/step - loss: 0.3712 - accuracy: 0.8686 - val_loss: 0.3691 - val_accuracy: 0.8662
Epoch 4/10
438/438 [==============================] - 2s 5ms/step - loss: 0.3490 - accuracy: 0.8763 - val_loss: 0.3508 - val_accuracy: 0.8739
Epoch 5/10
438/438 [==============================] - 2s 5ms/step - loss: 0.3272 - accuracy: 0.8829 - val_loss: 0.3415 - val_accuracy: 0.8757
Epoch 6/10
438/438 [==============================] - 3s 7ms/step - loss: 0.3116 - accuracy: 0.8873 - val_loss: 0.3647 - val_accuracy: 0.8626
Epoch 7/10
438/438 [==============================] - 2s 5ms/step - loss: 0.2978 - accuracy: 0.8916 - val_loss: 0.3343 - val_accuracy: 0.8759
Epoch 8/10
438/438 [==============================] - 2s 5ms/step - loss: 0.2838 - accuracy: 0.8971 - val_loss: 0.3207 - val_accuracy: 0.8823
Epoch 9/10
438/438 [==============================] - 2s 5ms/step - loss: 0.2787 - accuracy: 0.8986 - val_loss: 0.3191 - val_accuracy: 0.8834
Epoch 10/10
438/438 [==============================] - 2s 5ms/step - loss: 0.2650 - accuracy: 0.9024 - val_loss: 0.3112 - val_accuracy: 0.8851
Epoch 1/10
438/438 [==============================] - 104s 54ms/step - loss: 0.2581 - accuracy: 0.9060 - val_loss: 0.3060 - val_accuracy: 0.8881
Epoch 2/10
438/438 [==============================] - 4s 9ms/step - loss: 0.2481 - accuracy: 0.9097 - val_loss: 0.3070 - val_accuracy: 0.8877
Epoch 3/10
438/438 [==============================] - 4s 9ms/step - loss: 0.2436 - accuracy: 0.9111 - val_loss: 0.3114 - val_accuracy: 0.8865
Epoch 4/10
438/438 [==============================] - 5s 12ms/step - loss: 0.2384 - accuracy: 0.9127 - val_loss: 0.3093 - val_accuracy: 0.8871
Epoch 5/10
438/438 [==============================] - 4s 9ms/step - loss: 0.2277 - accuracy: 0.9160 - val_loss: 0.3206 - val_accuracy: 0.8835
Epoch 6/10
438/438 [==============================] - 4s 9ms/step - loss: 0.2222 - accuracy: 0.9186 - val_loss: 0.3147 - val_accuracy: 0.8889
Epoch 7/10
438/438 [==============================] - 5s 10ms/step - loss: 0.2168 - accuracy: 0.9204 - val_loss: 0.3152 - val_accuracy: 0.8881
Epoch 8/10
438/438 [==============================] - 4s 9ms/step - loss: 0.2132 - accuracy: 0.9223 - val_loss: 0.3032 - val_accuracy: 0.8890
Epoch 9/10
438/438 [==============================] - 4s 10ms/step - loss: 0.2064 - accuracy: 0.9249 - val_loss: 0.3109 - val_accuracy: 0.8894
Epoch 10/10
438/438 [==============================] - 5s 11ms/step - loss: 0.1993 - accuracy: 0.9270 - val_loss: 0.3092 - val_accuracy: 0.8896
438/438 [==============================] - 2s 3ms/step - loss: 0.3112 - accuracy: 0.8851
438/438 [==============================] - 3s 6ms/step - loss: 0.3092 - accuracy: 0.8896
438/438 [==============================] - 1s 3ms/step - loss: 0.3112 - accuracy: 0.8851
Test Accuracy: 0.8850714564323425
Task A Original Accuracy: 88.51%
Task B EWC method Accuracy: 88.96%
Epoch 1/10
438/438 [==============================] - 5s 8ms/step - loss: 0.5649 - accuracy: 0.8057 - val_loss: 0.4553 - val_accuracy: 0.8419
Epoch 2/10
438/438 [==============================] - 2s 5ms/step - loss: 0.4093 - accuracy: 0.8572 - val_loss: 0.3848 - val_accuracy: 0.8671
Epoch 3/10
438/438 [==============================] - 2s 5ms/step - loss: 0.3744 - accuracy: 0.8675 - val_loss: 0.3860 - val_accuracy: 0.8643
Epoch 4/10
438/438 [==============================] - 2s 5ms/step - loss: 0.3427 - accuracy: 0.8784 - val_loss: 0.3504 - val_accuracy: 0.8786
Epoch 5/10
438/438 [==============================] - 2s 6ms/step - loss: 0.3246 - accuracy: 0.8827 - val_loss: 0.3352 - val_accuracy: 0.8816
Epoch 6/10
438/438 [==============================] - 3s 6ms/step - loss: 0.3093 - accuracy: 0.8878 - val_loss: 0.3287 - val_accuracy: 0.8849
Epoch 7/10
438/438 [==============================] - 2s 6ms/step - loss: 0.2939 - accuracy: 0.8935 - val_loss: 0.3288 - val_accuracy: 0.8840
Epoch 8/10
438/438 [==============================] - 2s 5ms/step - loss: 0.2831 - accuracy: 0.8969 - val_loss: 0.3520 - val_accuracy: 0.8707
Epoch 9/10
438/438 [==============================] - 2s 5ms/step - loss: 0.2743 - accuracy: 0.9001 - val_loss: 0.3254 - val_accuracy: 0.8861
Epoch 10/10
438/438 [==============================] - 3s 6ms/step - loss: 0.2653 - accuracy: 0.9024 - val_loss: 0.3197 - val_accuracy: 0.8871
Epoch 1/10
438/438 [==============================] - 65s 33ms/step - loss: 0.2585 - accuracy: 0.9056 - val_loss: 0.3204 - val_accuracy: 0.8874
Epoch 2/10
438/438 [==============================] - 3s 6ms/step - loss: 0.2509 - accuracy: 0.9069 - val_loss: 0.3124 - val_accuracy: 0.8909
Epoch 3/10
438/438 [==============================] - 3s 6ms/step - loss: 0.2389 - accuracy: 0.9124 - val_loss: 0.3134 - val_accuracy: 0.8891
Epoch 4/10
438/438 [==============================] - 3s 6ms/step - loss: 0.2350 - accuracy: 0.9137 - val_loss: 0.3317 - val_accuracy: 0.8822
Epoch 5/10
438/438 [==============================] - 3s 8ms/step - loss: 0.2284 - accuracy: 0.9164 - val_loss: 0.3396 - val_accuracy: 0.8830
Epoch 6/10
438/438 [==============================] - 3s 6ms/step - loss: 0.2233 - accuracy: 0.9175 - val_loss: 0.3129 - val_accuracy: 0.8906
Epoch 7/10
438/438 [==============================] - 3s 6ms/step - loss: 0.2156 - accuracy: 0.9219 - val_loss: 0.3080 - val_accuracy: 0.8923
Epoch 8/10
438/438 [==============================] - 3s 6ms/step - loss: 0.2098 - accuracy: 0.9237 - val_loss: 0.3123 - val_accuracy: 0.8913
Epoch 9/10
438/438 [==============================] - 3s 7ms/step - loss: 0.2035 - accuracy: 0.9251 - val_loss: 0.3309 - val_accuracy: 0.8874
Epoch 10/10
438/438 [==============================] - 3s 7ms/step - loss: 0.1995 - accuracy: 0.9266 - val_loss: 0.3056 - val_accuracy: 0.8969
438/438 [==============================] - 1s 2ms/step - loss: 0.3197 - accuracy: 0.8871
438/438 [==============================] - 2s 4ms/step - loss: 0.3056 - accuracy: 0.8969
438/438 [==============================] - 1s 2ms/step - loss: 0.3197 - accuracy: 0.8871
Test Accuracy: 0.887071430683136
Task A Original Accuracy: 88.71%
Task B EWC method Accuracy: 89.69%
Epoch 1/10
438/438 [==============================] - 3s 4ms/step - loss: 0.5666 - accuracy: 0.8054 - val_loss: 0.4729 - val_accuracy: 0.8370
Epoch 2/10
438/438 [==============================] - 2s 5ms/step - loss: 0.4199 - accuracy: 0.8518 - val_loss: 0.4040 - val_accuracy: 0.8544
Epoch 3/10
438/438 [==============================] - 2s 4ms/step - loss: 0.3778 - accuracy: 0.8657 - val_loss: 0.3686 - val_accuracy: 0.8689
Epoch 4/10
438/438 [==============================] - 2s 4ms/step - loss: 0.3532 - accuracy: 0.8734 - val_loss: 0.3554 - val_accuracy: 0.8775
Epoch 5/10
438/438 [==============================] - 2s 5ms/step - loss: 0.3320 - accuracy: 0.8815 - val_loss: 0.3327 - val_accuracy: 0.8804
Epoch 6/10
438/438 [==============================] - 2s 4ms/step - loss: 0.3243 - accuracy: 0.8822 - val_loss: 0.3509 - val_accuracy: 0.8765
Epoch 7/10
438/438 [==============================] - 2s 4ms/step - loss: 0.3035 - accuracy: 0.8900 - val_loss: 0.3203 - val_accuracy: 0.8834
Epoch 8/10
438/438 [==============================] - 2s 5ms/step - loss: 0.2918 - accuracy: 0.8951 - val_loss: 0.3153 - val_accuracy: 0.8894
Epoch 9/10
438/438 [==============================] - 2s 4ms/step - loss: 0.2799 - accuracy: 0.8982 - val_loss: 0.3115 - val_accuracy: 0.8903
Epoch 10/10
438/438 [==============================] - 2s 4ms/step - loss: 0.2721 - accuracy: 0.8996 - val_loss: 0.3173 - val_accuracy: 0.8836
Epoch 1/10
438/438 [==============================] - 64s 33ms/step - loss: 0.2677 - accuracy: 0.9032 - val_loss: 0.3110 - val_accuracy: 0.8884
Epoch 2/10
438/438 [==============================] - 3s 7ms/step - loss: 0.2563 - accuracy: 0.9056 - val_loss: 0.3045 - val_accuracy: 0.8904
Epoch 3/10
438/438 [==============================] - 3s 7ms/step - loss: 0.2480 - accuracy: 0.9095 - val_loss: 0.3131 - val_accuracy: 0.8878
Epoch 4/10
438/438 [==============================] - 3s 6ms/step - loss: 0.2438 - accuracy: 0.9109 - val_loss: 0.3023 - val_accuracy: 0.8908
Epoch 5/10
438/438 [==============================] - 3s 6ms/step - loss: 0.2374 - accuracy: 0.9130 - val_loss: 0.2959 - val_accuracy: 0.8931
Epoch 6/10
438/438 [==============================] - 3s 6ms/step - loss: 0.2279 - accuracy: 0.9163 - val_loss: 0.2993 - val_accuracy: 0.8939
Epoch 7/10
438/438 [==============================] - 4s 8ms/step - loss: 0.2237 - accuracy: 0.9177 - val_loss: 0.3025 - val_accuracy: 0.8940
Epoch 8/10
438/438 [==============================] - 3s 6ms/step - loss: 0.2203 - accuracy: 0.9179 - val_loss: 0.2915 - val_accuracy: 0.8948
Epoch 9/10
438/438 [==============================] - 3s 6ms/step - loss: 0.2128 - accuracy: 0.9209 - val_loss: 0.2915 - val_accuracy: 0.8968
Epoch 10/10
438/438 [==============================] - 3s 6ms/step - loss: 0.2082 - accuracy: 0.9233 - val_loss: 0.3095 - val_accuracy: 0.8928
438/438 [==============================] - 1s 3ms/step - loss: 0.3173 - accuracy: 0.8836
438/438 [==============================] - 2s 4ms/step - loss: 0.3095 - accuracy: 0.8928
438/438 [==============================] - 1s 3ms/step - loss: 0.3173 - accuracy: 0.8836
Test Accuracy: 0.883642852306366
Task A Original Accuracy: 88.36%
Task B EWC method Accuracy: 89.28%
Epoch 1/10
438/438 [==============================] - 3s 4ms/step - loss: 0.5662 - accuracy: 0.8061 - val_loss: 0.4490 - val_accuracy: 0.8395
Epoch 2/10
438/438 [==============================] - 2s 4ms/step - loss: 0.4135 - accuracy: 0.8559 - val_loss: 0.3919 - val_accuracy: 0.8631
Epoch 3/10
438/438 [==============================] - 2s 5ms/step - loss: 0.3728 - accuracy: 0.8678 - val_loss: 0.3728 - val_accuracy: 0.8628
Epoch 4/10
438/438 [==============================] - 2s 4ms/step - loss: 0.3435 - accuracy: 0.8781 - val_loss: 0.3615 - val_accuracy: 0.8702
Epoch 5/10
438/438 [==============================] - 2s 4ms/step - loss: 0.3227 - accuracy: 0.8841 - val_loss: 0.3406 - val_accuracy: 0.8754
Epoch 6/10
438/438 [==============================] - 2s 4ms/step - loss: 0.3089 - accuracy: 0.8891 - val_loss: 0.3330 - val_accuracy: 0.8821
Epoch 7/10
438/438 [==============================] - 2s 4ms/step - loss: 0.2948 - accuracy: 0.8941 - val_loss: 0.3283 - val_accuracy: 0.8799
Epoch 8/10
438/438 [==============================] - 2s 4ms/step - loss: 0.2814 - accuracy: 0.8980 - val_loss: 0.3346 - val_accuracy: 0.8754
Epoch 9/10
438/438 [==============================] - 2s 4ms/step - loss: 0.2716 - accuracy: 0.9013 - val_loss: 0.3153 - val_accuracy: 0.8846
Epoch 10/10
438/438 [==============================] - 2s 5ms/step - loss: 0.2624 - accuracy: 0.9052 - val_loss: 0.3147 - val_accuracy: 0.8869
Epoch 1/10
438/438 [==============================] - 80s 65ms/step - loss: 0.2570 - accuracy: 0.9055 - val_loss: 0.3126 - val_accuracy: 0.8865
Epoch 2/10
438/438 [==============================] - 16s 37ms/step - loss: 0.2487 - accuracy: 0.9098 - val_loss: 0.3043 - val_accuracy: 0.8899
Epoch 3/10
438/438 [==============================] - 16s 37ms/step - loss: 0.2427 - accuracy: 0.9108 - val_loss: 0.3173 - val_accuracy: 0.8881
Epoch 4/10
438/438 [==============================] - 16s 37ms/step - loss: 0.2324 - accuracy: 0.9151 - val_loss: 0.3117 - val_accuracy: 0.8898
Epoch 5/10
438/438 [==============================] - 17s 39ms/step - loss: 0.2287 - accuracy: 0.9141 - val_loss: 0.3185 - val_accuracy: 0.8866
Epoch 6/10
438/438 [==============================] - 17s 38ms/step - loss: 0.2218 - accuracy: 0.9190 - val_loss: 0.3121 - val_accuracy: 0.8877
Epoch 7/10
438/438 [==============================] - 17s 38ms/step - loss: 0.2165 - accuracy: 0.9206 - val_loss: 0.3175 - val_accuracy: 0.8884
Epoch 8/10
438/438 [==============================] - 17s 39ms/step - loss: 0.2090 - accuracy: 0.9227 - val_loss: 0.3114 - val_accuracy: 0.8889
Epoch 9/10
438/438 [==============================] - 16s 37ms/step - loss: 0.2049 - accuracy: 0.9247 - val_loss: 0.3086 - val_accuracy: 0.8912
Epoch 10/10
438/438 [==============================] - 17s 38ms/step - loss: 0.1995 - accuracy: 0.9260 - val_loss: 0.3072 - val_accuracy: 0.8918
438/438 [==============================] - 1s 2ms/step - loss: 0.3147 - accuracy: 0.8869
438/438 [==============================] - 9s 20ms/step - loss: 0.3072 - accuracy: 0.8918
438/438 [==============================] - 1s 2ms/step - loss: 0.3147 - accuracy: 0.8869
Test Accuracy: 0.8868571519851685
Task A Original Accuracy: 88.69%
Task B EWC method Accuracy: 89.18%
Fold-1: 88.81%
Fold-2: 88.51%
Fold-3: 88.71%
Fold-4: 88.36%
Fold-5: 88.69%

### Kuzushiji-MNIST

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.regularizers import Regularizer
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import KFold
from tensorflow.keras import backend as K
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    f_accum = []
    for i in range(len(model.weights)):
        f_accum.append(np.zeros(K.int_shape(model.weights[i])))
    f_accum = np.array(f_accum)
    for _ in range(num_samples):
        idx = np.random.randint(0, x.shape[0])
        with tf.GradientTape() as tape:
            model_output = model(x[idx:idx+1])
        grads = tape.gradient(model_output, model.weights)
        for i in range(len(grads)):
            f_accum[i] += tf.square(grads[i])
    f_accum /= num_samples
    return f_accum

# Define the CrlB regularizer
class CrlBRegularizer(Regularizer):
    def __init__(self, fisher, prior_weights, lambda_=0.1):
        self.fisher = fisher
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i in range(len(self.fisher)):
            regularization += self.lambda_ * tf.reduce_sum(self.fisher[i] * tf.square(x - self.prior_weights[i]))
        return regularization


# Number of K-folds
K = 5

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)
# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []

# Perform K-fold cross-validation
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]

# Task A: Original Fashion MNIST model
    model = Sequential([
    Dense(128, activation='relu', input_shape=(784,)),
    Dense(10, activation='softmax')
])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model = model
        model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
        model.save_weights('FashionMNIST_A.h5')

# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]

# Task B: Fashion MNIST with CrlB regularization
    model_CrlBB = Sequential([
        Dense(128, activation='relu', input_shape=(784,), kernel_regularizer=CrlBRegularizer(fisher_info[0], model.weights[0])),
        Dense(10, activation='softmax', kernel_regularizer=CrlBRegularizer(fisher_info[1], model.weights[1]))
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model_CrlBB = model_CrlBB
        model_CrlBB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model_CrlBB.load_weights('FashionMNIST_A.h5')
        model_CrlBB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlB_acc = 100 * model_CrlBB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlB method Accuracy: %.2f%%" % B_CrlB_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
438/438 [==============================] - 3s 4ms/step - loss: 0.5731 - accuracy: 0.8286 - val_loss: 0.3619 - val_accuracy: 0.8940
Epoch 2/10
438/438 [==============================] - 2s 4ms/step - loss: 0.3000 - accuracy: 0.9140 - val_loss: 0.2812 - val_accuracy: 0.9196
Epoch 3/10
438/438 [==============================] - 2s 4ms/step - loss: 0.2211 - accuracy: 0.9378 - val_loss: 0.2379 - val_accuracy: 0.9304
Epoch 4/10
438/438 [==============================] - 3s 7ms/step - loss: 0.1736 - accuracy: 0.9507 - val_loss: 0.2119 - val_accuracy: 0.9385
Epoch 5/10
438/438 [==============================] - 3s 7ms/step - loss: 0.1414 - accuracy: 0.9603 - val_loss: 0.2058 - val_accuracy: 0.9401
Epoch 6/10
438/438 [==============================] - 3s 7ms/step - loss: 0.1173 - accuracy: 0.9674 - val_loss: 0.1939 - val_accuracy: 0.9455
Epoch 7/10
438/438 [==============================] - 4s 8ms/step - loss: 0.0975 - accuracy: 0.9738 - val_loss: 0.1903 - val_accuracy: 0.9462
Epoch 8/10
438/438 [==============================] - 3s 7ms/step - loss: 0.0829 - accuracy: 0.9784 - val_loss: 0.1844 - val_accuracy: 0.9479
Epoch 9/10
438/438 [==============================] - 3s 6ms/step - loss: 0.0690 - accuracy: 0.9830 - val_loss: 0.1877 - val_accuracy: 0.9483
Epoch 10/10
438/438 [==============================] - 3s 6ms/step - loss: 0.0583 - accuracy: 0.9856 - val_loss: 0.1844 - val_accuracy: 0.9507
Epoch 1/10
438/438 [==============================] - 122s 50ms/step - loss: 0.0539 - accuracy: 0.9864 - val_loss: 0.1987 - val_accuracy: 0.9479
Epoch 2/10
438/438 [==============================] - 4s 8ms/step - loss: 0.0412 - accuracy: 0.9907 - val_loss: 0.2054 - val_accuracy: 0.9464
Epoch 3/10
438/438 [==============================] - 5s 11ms/step - loss: 0.0343 - accuracy: 0.9923 - val_loss: 0.2032 - val_accuracy: 0.9479
Epoch 4/10
438/438 [==============================] - 4s 9ms/step - loss: 0.0281 - accuracy: 0.9944 - val_loss: 0.2229 - val_accuracy: 0.9446
Epoch 5/10
438/438 [==============================] - 4s 10ms/step - loss: 0.0234 - accuracy: 0.9958 - val_loss: 0.2114 - val_accuracy: 0.9515
Epoch 6/10
438/438 [==============================] - 5s 12ms/step - loss: 0.0187 - accuracy: 0.9971 - val_loss: 0.2178 - val_accuracy: 0.9495
Epoch 7/10
438/438 [==============================] - 4s 9ms/step - loss: 0.0155 - accuracy: 0.9976 - val_loss: 0.2181 - val_accuracy: 0.9494
Epoch 8/10
438/438 [==============================] - 4s 8ms/step - loss: 0.0138 - accuracy: 0.9981 - val_loss: 0.2305 - val_accuracy: 0.9490
Epoch 9/10
438/438 [==============================] - 5s 11ms/step - loss: 0.0118 - accuracy: 0.9984 - val_loss: 0.2323 - val_accuracy: 0.9504
Epoch 10/10
438/438 [==============================] - 4s 8ms/step - loss: 0.0091 - accuracy: 0.9990 - val_loss: 0.2407 - val_accuracy: 0.9490
438/438 [==============================] - 1s 3ms/step - loss: 0.1844 - accuracy: 0.9507
438/438 [==============================] - 3s 6ms/step - loss: 0.2407 - accuracy: 0.9490
438/438 [==============================] - 1s 3ms/step - loss: 0.1844 - accuracy: 0.9507
Test Accuracy: 0.9507142901420593
Task A Original Accuracy: 95.07%
Task B EWC method Accuracy: 94.90%
Epoch 1/10
438/438 [==============================] - 4s 6ms/step - loss: 0.5725 - accuracy: 0.8286 - val_loss: 0.3659 - val_accuracy: 0.8898
Epoch 2/10
438/438 [==============================] - 2s 5ms/step - loss: 0.3000 - accuracy: 0.9117 - val_loss: 0.2833 - val_accuracy: 0.9142
Epoch 3/10
438/438 [==============================] - 2s 5ms/step - loss: 0.2233 - accuracy: 0.9367 - val_loss: 0.2329 - val_accuracy: 0.9325
Epoch 4/10
438/438 [==============================] - 2s 5ms/step - loss: 0.1773 - accuracy: 0.9495 - val_loss: 0.2098 - val_accuracy: 0.9395
Epoch 5/10
438/438 [==============================] - 3s 7ms/step - loss: 0.1445 - accuracy: 0.9596 - val_loss: 0.2078 - val_accuracy: 0.9386
Epoch 6/10
438/438 [==============================] - 2s 5ms/step - loss: 0.1202 - accuracy: 0.9667 - val_loss: 0.1941 - val_accuracy: 0.9429
Epoch 7/10
438/438 [==============================] - 2s 5ms/step - loss: 0.1011 - accuracy: 0.9728 - val_loss: 0.1909 - val_accuracy: 0.9450
Epoch 8/10
438/438 [==============================] - 2s 5ms/step - loss: 0.0855 - accuracy: 0.9770 - val_loss: 0.1913 - val_accuracy: 0.9449
Epoch 9/10
438/438 [==============================] - 2s 5ms/step - loss: 0.0718 - accuracy: 0.9810 - val_loss: 0.1981 - val_accuracy: 0.9428
Epoch 10/10
438/438 [==============================] - 3s 6ms/step - loss: 0.0605 - accuracy: 0.9848 - val_loss: 0.1939 - val_accuracy: 0.9465
Epoch 1/10
438/438 [==============================] - 113s 81ms/step - loss: 0.0550 - accuracy: 0.9856 - val_loss: 0.1949 - val_accuracy: 0.9479
Epoch 2/10
438/438 [==============================] - 12s 27ms/step - loss: 0.0435 - accuracy: 0.9899 - val_loss: 0.2047 - val_accuracy: 0.9465
Epoch 3/10
438/438 [==============================] - 11s 24ms/step - loss: 0.0356 - accuracy: 0.9921 - val_loss: 0.2058 - val_accuracy: 0.9453
Epoch 4/10
438/438 [==============================] - 11s 24ms/step - loss: 0.0297 - accuracy: 0.9939 - val_loss: 0.2072 - val_accuracy: 0.9479
Epoch 5/10
438/438 [==============================] - 11s 25ms/step - loss: 0.0244 - accuracy: 0.9955 - val_loss: 0.2154 - val_accuracy: 0.9452
Epoch 6/10
438/438 [==============================] - 11s 25ms/step - loss: 0.0210 - accuracy: 0.9962 - val_loss: 0.2228 - val_accuracy: 0.9462
Epoch 7/10
438/438 [==============================] - 11s 25ms/step - loss: 0.0159 - accuracy: 0.9977 - val_loss: 0.2231 - val_accuracy: 0.9472
Epoch 8/10
438/438 [==============================] - 11s 26ms/step - loss: 0.0134 - accuracy: 0.9984 - val_loss: 0.2375 - val_accuracy: 0.9451
Epoch 9/10
438/438 [==============================] - 12s 28ms/step - loss: 0.0154 - accuracy: 0.9971 - val_loss: 0.2534 - val_accuracy: 0.9421
Epoch 10/10
438/438 [==============================] - 11s 24ms/step - loss: 0.0122 - accuracy: 0.9981 - val_loss: 0.2457 - val_accuracy: 0.9454
438/438 [==============================] - 1s 2ms/step - loss: 0.1939 - accuracy: 0.9465
438/438 [==============================] - 7s 15ms/step - loss: 0.2457 - accuracy: 0.9454
438/438 [==============================] - 1s 2ms/step - loss: 0.1939 - accuracy: 0.9465
Test Accuracy: 0.9465000033378601
Task A Original Accuracy: 94.65%
Task B EWC method Accuracy: 94.54%
Epoch 1/10
438/438 [==============================] - 3s 5ms/step - loss: 0.5812 - accuracy: 0.8258 - val_loss: 0.3702 - val_accuracy: 0.8919
Epoch 2/10
438/438 [==============================] - 1s 3ms/step - loss: 0.3034 - accuracy: 0.9117 - val_loss: 0.2817 - val_accuracy: 0.9164
Epoch 3/10
438/438 [==============================] - 2s 4ms/step - loss: 0.2281 - accuracy: 0.9348 - val_loss: 0.2365 - val_accuracy: 0.9293
Epoch 4/10
438/438 [==============================] - 2s 3ms/step - loss: 0.1819 - accuracy: 0.9484 - val_loss: 0.2146 - val_accuracy: 0.9363
Epoch 5/10
438/438 [==============================] - 2s 4ms/step - loss: 0.1497 - accuracy: 0.9581 - val_loss: 0.2017 - val_accuracy: 0.9412
Epoch 6/10
438/438 [==============================] - 2s 4ms/step - loss: 0.1249 - accuracy: 0.9657 - val_loss: 0.2019 - val_accuracy: 0.9405
Epoch 7/10
438/438 [==============================] - 2s 4ms/step - loss: 0.1059 - accuracy: 0.9704 - val_loss: 0.1947 - val_accuracy: 0.9426
Epoch 8/10
438/438 [==============================] - 2s 6ms/step - loss: 0.0889 - accuracy: 0.9764 - val_loss: 0.1913 - val_accuracy: 0.9459
Epoch 9/10
438/438 [==============================] - 1s 3ms/step - loss: 0.0750 - accuracy: 0.9800 - val_loss: 0.1898 - val_accuracy: 0.9461
Epoch 10/10
438/438 [==============================] - 2s 3ms/step - loss: 0.0636 - accuracy: 0.9844 - val_loss: 0.1842 - val_accuracy: 0.9476
Epoch 1/10
438/438 [==============================] - 61s 31ms/step - loss: 0.0592 - accuracy: 0.9846 - val_loss: 0.1944 - val_accuracy: 0.9470
Epoch 2/10
438/438 [==============================] - 2s 5ms/step - loss: 0.0470 - accuracy: 0.9888 - val_loss: 0.1933 - val_accuracy: 0.9469
Epoch 3/10
438/438 [==============================] - 3s 7ms/step - loss: 0.0393 - accuracy: 0.9907 - val_loss: 0.2011 - val_accuracy: 0.9469
Epoch 4/10
438/438 [==============================] - 2s 6ms/step - loss: 0.0317 - accuracy: 0.9933 - val_loss: 0.1958 - val_accuracy: 0.9484
Epoch 5/10
438/438 [==============================] - 2s 5ms/step - loss: 0.0263 - accuracy: 0.9951 - val_loss: 0.1996 - val_accuracy: 0.9486
Epoch 6/10
438/438 [==============================] - 2s 6ms/step - loss: 0.0219 - accuracy: 0.9958 - val_loss: 0.2202 - val_accuracy: 0.9448
Epoch 7/10
438/438 [==============================] - 3s 6ms/step - loss: 0.0201 - accuracy: 0.9963 - val_loss: 0.2185 - val_accuracy: 0.9471
Epoch 8/10
438/438 [==============================] - 3s 7ms/step - loss: 0.0152 - accuracy: 0.9977 - val_loss: 0.2270 - val_accuracy: 0.9459
Epoch 9/10
438/438 [==============================] - 3s 6ms/step - loss: 0.0124 - accuracy: 0.9984 - val_loss: 0.2262 - val_accuracy: 0.9475
Epoch 10/10
438/438 [==============================] - 3s 6ms/step - loss: 0.0123 - accuracy: 0.9980 - val_loss: 0.2451 - val_accuracy: 0.9431
438/438 [==============================] - 1s 2ms/step - loss: 0.1842 - accuracy: 0.9476
438/438 [==============================] - 2s 4ms/step - loss: 0.2451 - accuracy: 0.9431
438/438 [==============================] - 1s 3ms/step - loss: 0.1842 - accuracy: 0.9476
Test Accuracy: 0.9475714564323425
Task A Original Accuracy: 94.76%
Task B EWC method Accuracy: 94.31%
Epoch 1/10
438/438 [==============================] - 3s 4ms/step - loss: 0.5635 - accuracy: 0.8327 - val_loss: 0.3700 - val_accuracy: 0.8926
Epoch 2/10
438/438 [==============================] - 2s 3ms/step - loss: 0.2965 - accuracy: 0.9132 - val_loss: 0.2771 - val_accuracy: 0.9190
Epoch 3/10
438/438 [==============================] - 2s 4ms/step - loss: 0.2191 - accuracy: 0.9374 - val_loss: 0.2344 - val_accuracy: 0.9330
Epoch 4/10
438/438 [==============================] - 2s 4ms/step - loss: 0.1742 - accuracy: 0.9505 - val_loss: 0.2145 - val_accuracy: 0.9369
Epoch 5/10
438/438 [==============================] - 2s 3ms/step - loss: 0.1424 - accuracy: 0.9597 - val_loss: 0.1951 - val_accuracy: 0.9436
Epoch 6/10
438/438 [==============================] - 2s 5ms/step - loss: 0.1195 - accuracy: 0.9668 - val_loss: 0.1956 - val_accuracy: 0.9422
Epoch 7/10
438/438 [==============================] - 2s 4ms/step - loss: 0.1023 - accuracy: 0.9713 - val_loss: 0.1848 - val_accuracy: 0.9466
Epoch 8/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0852 - accuracy: 0.9768 - val_loss: 0.1831 - val_accuracy: 0.9464
Epoch 9/10
438/438 [==============================] - 2s 3ms/step - loss: 0.0738 - accuracy: 0.9807 - val_loss: 0.1901 - val_accuracy: 0.9436
Epoch 10/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0616 - accuracy: 0.9845 - val_loss: 0.1836 - val_accuracy: 0.9471
Epoch 1/10
438/438 [==============================] - 62s 32ms/step - loss: 0.0564 - accuracy: 0.9851 - val_loss: 0.1850 - val_accuracy: 0.9484
Epoch 2/10
438/438 [==============================] - 3s 6ms/step - loss: 0.0447 - accuracy: 0.9892 - val_loss: 0.1950 - val_accuracy: 0.9457
Epoch 3/10
438/438 [==============================] - 4s 8ms/step - loss: 0.0364 - accuracy: 0.9919 - val_loss: 0.1904 - val_accuracy: 0.9486
Epoch 4/10
438/438 [==============================] - 2s 6ms/step - loss: 0.0309 - accuracy: 0.9934 - val_loss: 0.1939 - val_accuracy: 0.9486
Epoch 5/10
438/438 [==============================] - 3s 6ms/step - loss: 0.0250 - accuracy: 0.9954 - val_loss: 0.2050 - val_accuracy: 0.9480
Epoch 6/10
438/438 [==============================] - 3s 6ms/step - loss: 0.0209 - accuracy: 0.9963 - val_loss: 0.2077 - val_accuracy: 0.9488
Epoch 7/10
438/438 [==============================] - 4s 9ms/step - loss: 0.0170 - accuracy: 0.9973 - val_loss: 0.2086 - val_accuracy: 0.9499
Epoch 8/10
438/438 [==============================] - 3s 6ms/step - loss: 0.0152 - accuracy: 0.9975 - val_loss: 0.2115 - val_accuracy: 0.9486
Epoch 9/10
438/438 [==============================] - 2s 6ms/step - loss: 0.0132 - accuracy: 0.9981 - val_loss: 0.2172 - val_accuracy: 0.9491
Epoch 10/10
438/438 [==============================] - 2s 6ms/step - loss: 0.0119 - accuracy: 0.9983 - val_loss: 0.2351 - val_accuracy: 0.9450
438/438 [==============================] - 1s 2ms/step - loss: 0.1836 - accuracy: 0.9471
438/438 [==============================] - 2s 5ms/step - loss: 0.2351 - accuracy: 0.9450
438/438 [==============================] - 1s 3ms/step - loss: 0.1836 - accuracy: 0.9471
Test Accuracy: 0.9471428394317627
Task A Original Accuracy: 94.71%
Task B EWC method Accuracy: 94.50%
Epoch 1/10
438/438 [==============================] - 3s 4ms/step - loss: 0.5703 - accuracy: 0.8296 - val_loss: 0.3757 - val_accuracy: 0.8906
Epoch 2/10
438/438 [==============================] - 2s 4ms/step - loss: 0.2990 - accuracy: 0.9128 - val_loss: 0.2802 - val_accuracy: 0.9201
Epoch 3/10
438/438 [==============================] - 2s 4ms/step - loss: 0.2237 - accuracy: 0.9365 - val_loss: 0.2426 - val_accuracy: 0.9297
Epoch 4/10
438/438 [==============================] - 2s 3ms/step - loss: 0.1777 - accuracy: 0.9502 - val_loss: 0.2217 - val_accuracy: 0.9340
Epoch 5/10
438/438 [==============================] - 2s 4ms/step - loss: 0.1442 - accuracy: 0.9597 - val_loss: 0.2032 - val_accuracy: 0.9413
Epoch 6/10
438/438 [==============================] - 2s 5ms/step - loss: 0.1197 - accuracy: 0.9664 - val_loss: 0.1976 - val_accuracy: 0.9426
Epoch 7/10
438/438 [==============================] - 2s 3ms/step - loss: 0.1005 - accuracy: 0.9728 - val_loss: 0.1942 - val_accuracy: 0.9443
Epoch 8/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0844 - accuracy: 0.9776 - val_loss: 0.1929 - val_accuracy: 0.9446
Epoch 9/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0705 - accuracy: 0.9818 - val_loss: 0.1902 - val_accuracy: 0.9464
Epoch 10/10
438/438 [==============================] - 2s 4ms/step - loss: 0.0591 - accuracy: 0.9855 - val_loss: 0.1831 - val_accuracy: 0.9472
Epoch 1/10
438/438 [==============================] - 73s 56ms/step - loss: 0.0539 - accuracy: 0.9859 - val_loss: 0.1929 - val_accuracy: 0.9471
Epoch 2/10
438/438 [==============================] - 11s 26ms/step - loss: 0.0424 - accuracy: 0.9897 - val_loss: 0.1931 - val_accuracy: 0.9481
Epoch 3/10
438/438 [==============================] - 11s 26ms/step - loss: 0.0350 - accuracy: 0.9923 - val_loss: 0.2022 - val_accuracy: 0.9473
Epoch 4/10
438/438 [==============================] - 11s 26ms/step - loss: 0.0281 - accuracy: 0.9944 - val_loss: 0.1959 - val_accuracy: 0.9496
Epoch 5/10
438/438 [==============================] - 11s 26ms/step - loss: 0.0223 - accuracy: 0.9958 - val_loss: 0.2018 - val_accuracy: 0.9491
Epoch 6/10
438/438 [==============================] - 12s 28ms/step - loss: 0.0192 - accuracy: 0.9965 - val_loss: 0.2074 - val_accuracy: 0.9491
Epoch 7/10
438/438 [==============================] - 12s 28ms/step - loss: 0.0149 - accuracy: 0.9979 - val_loss: 0.2091 - val_accuracy: 0.9514
Epoch 8/10
438/438 [==============================] - 11s 26ms/step - loss: 0.0136 - accuracy: 0.9978 - val_loss: 0.2146 - val_accuracy: 0.9501
Epoch 9/10
438/438 [==============================] - 12s 28ms/step - loss: 0.0124 - accuracy: 0.9983 - val_loss: 0.2135 - val_accuracy: 0.9522
Epoch 10/10
438/438 [==============================] - 11s 26ms/step - loss: 0.0087 - accuracy: 0.9990 - val_loss: 0.2271 - val_accuracy: 0.9497
438/438 [==============================] - 1s 2ms/step - loss: 0.1831 - accuracy: 0.9472
438/438 [==============================] - 6s 14ms/step - loss: 0.2271 - accuracy: 0.9497
438/438 [==============================] - 1s 2ms/step - loss: 0.1831 - accuracy: 0.9472
Test Accuracy: 0.9472143054008484
Task A Original Accuracy: 94.72%
Task B EWC method Accuracy: 94.97%
Fold-1: 95.07%
Fold-2: 94.65%
Fold-3: 94.76%
Fold-4: 94.71%
Fold-5: 94.72%

### MNIST-C

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.regularizers import Regularizer
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import KFold
from tensorflow.keras import backend as K
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    f_accum = []
    for i in range(len(model.weights)):
        f_accum.append(np.zeros(K.int_shape(model.weights[i])))
    f_accum = np.array(f_accum)
    for _ in range(num_samples):
        idx = np.random.randint(0, x.shape[0])
        with tf.GradientTape() as tape:
            model_output = model(x[idx:idx+1])
        grads = tape.gradient(model_output, model.weights)
        for i in range(len(grads)):
            f_accum[i] += tf.square(grads[i])
    f_accum /= num_samples
    return f_accum

# Define the CrlB regularizer
class CrlBRegularizer(Regularizer):
    def __init__(self, fisher, prior_weights, lambda_=0.1):
        self.fisher = fisher
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i in range(len(self.fisher)):
            regularization += self.lambda_ * tf.reduce_sum(self.fisher[i] * tf.square(x - self.prior_weights[i]))
        return regularization


# Number of K-folds
K = 5

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)
# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []

# Perform K-fold cross-validation
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]

# Task A: Original Fashion MNIST model
    model = Sequential([
    Dense(128, activation='relu', input_shape=(784,)),
    Dense(10, activation='softmax')
])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model = model
        model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
        model.save_weights('FashionMNIST_A.h5')

# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]

# Task B: Fashion MNIST with CrlB regularization
    model_CrlBB = Sequential([
        Dense(128, activation='relu', input_shape=(784,), kernel_regularizer=CrlBRegularizer(fisher_info[0], model.weights[0])),
        Dense(10, activation='softmax', kernel_regularizer=CrlBRegularizer(fisher_info[1], model.weights[1]))
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model_CrlBB = model_CrlBB
        model_CrlBB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model_CrlBB.load_weights('FashionMNIST_A.h5')
        model_CrlBB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlB_acc = 100 * model_CrlBB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlB method Accuracy: %.2f%%" % B_CrlB_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
375/375 [==============================] - 3s 5ms/step - loss: 0.3963 - accuracy: 0.8910 - val_loss: 0.2286 - val_accuracy: 0.9360
Epoch 2/10
375/375 [==============================] - 3s 8ms/step - loss: 0.1851 - accuracy: 0.9473 - val_loss: 0.1663 - val_accuracy: 0.9538
Epoch 3/10
375/375 [==============================] - 2s 4ms/step - loss: 0.1340 - accuracy: 0.9614 - val_loss: 0.1401 - val_accuracy: 0.9607
Epoch 4/10
375/375 [==============================] - 2s 4ms/step - loss: 0.1055 - accuracy: 0.9689 - val_loss: 0.1202 - val_accuracy: 0.9659
Epoch 5/10
375/375 [==============================] - 2s 6ms/step - loss: 0.0844 - accuracy: 0.9754 - val_loss: 0.1131 - val_accuracy: 0.9678
Epoch 6/10
375/375 [==============================] - 2s 4ms/step - loss: 0.0708 - accuracy: 0.9793 - val_loss: 0.1023 - val_accuracy: 0.9724
Epoch 7/10
375/375 [==============================] - 2s 4ms/step - loss: 0.0604 - accuracy: 0.9819 - val_loss: 0.0947 - val_accuracy: 0.9736
Epoch 8/10
375/375 [==============================] - 2s 6ms/step - loss: 0.0506 - accuracy: 0.9860 - val_loss: 0.0942 - val_accuracy: 0.9728
Epoch 9/10
375/375 [==============================] - 2s 6ms/step - loss: 0.0428 - accuracy: 0.9879 - val_loss: 0.0889 - val_accuracy: 0.9742
Epoch 10/10
375/375 [==============================] - 2s 4ms/step - loss: 0.0369 - accuracy: 0.9898 - val_loss: 0.0942 - val_accuracy: 0.9732
Epoch 1/10
375/375 [==============================] - 130s 79ms/step - loss: 0.0344 - accuracy: 0.9901 - val_loss: 0.0846 - val_accuracy: 0.9758
Epoch 2/10
375/375 [==============================] - 9s 25ms/step - loss: 0.0275 - accuracy: 0.9927 - val_loss: 0.0884 - val_accuracy: 0.9751
Epoch 3/10
375/375 [==============================] - 10s 26ms/step - loss: 0.0233 - accuracy: 0.9939 - val_loss: 0.0859 - val_accuracy: 0.9760
Epoch 4/10
375/375 [==============================] - 9s 23ms/step - loss: 0.0186 - accuracy: 0.9959 - val_loss: 0.1053 - val_accuracy: 0.9712
Epoch 5/10
375/375 [==============================] - 10s 26ms/step - loss: 0.0176 - accuracy: 0.9956 - val_loss: 0.0889 - val_accuracy: 0.9755
Epoch 6/10
375/375 [==============================] - 10s 26ms/step - loss: 0.0137 - accuracy: 0.9973 - val_loss: 0.0893 - val_accuracy: 0.9759
Epoch 7/10
375/375 [==============================] - 9s 24ms/step - loss: 0.0110 - accuracy: 0.9981 - val_loss: 0.0887 - val_accuracy: 0.9763
Epoch 8/10
375/375 [==============================] - 9s 24ms/step - loss: 0.0093 - accuracy: 0.9985 - val_loss: 0.0899 - val_accuracy: 0.9763
Epoch 9/10
375/375 [==============================] - 10s 25ms/step - loss: 0.0086 - accuracy: 0.9986 - val_loss: 0.0930 - val_accuracy: 0.9776
Epoch 10/10
375/375 [==============================] - 10s 25ms/step - loss: 0.0073 - accuracy: 0.9989 - val_loss: 0.0947 - val_accuracy: 0.9764
375/375 [==============================] - 1s 4ms/step - loss: 0.0942 - accuracy: 0.9732
375/375 [==============================] - 6s 17ms/step - loss: 0.0947 - accuracy: 0.9764
375/375 [==============================] - 1s 3ms/step - loss: 0.0942 - accuracy: 0.9732
Test Accuracy: 0.9732499718666077
Task A Original Accuracy: 97.32%
Task B EWC method Accuracy: 97.64%
Epoch 1/10
375/375 [==============================] - 3s 5ms/step - loss: 0.3931 - accuracy: 0.8926 - val_loss: 0.2255 - val_accuracy: 0.9386
Epoch 2/10
375/375 [==============================] - 2s 5ms/step - loss: 0.1808 - accuracy: 0.9488 - val_loss: 0.1621 - val_accuracy: 0.9548
Epoch 3/10
375/375 [==============================] - 2s 5ms/step - loss: 0.1327 - accuracy: 0.9621 - val_loss: 0.1417 - val_accuracy: 0.9616
Epoch 4/10
375/375 [==============================] - 2s 4ms/step - loss: 0.1042 - accuracy: 0.9703 - val_loss: 0.1178 - val_accuracy: 0.9653
Epoch 5/10
375/375 [==============================] - 2s 5ms/step - loss: 0.0843 - accuracy: 0.9757 - val_loss: 0.1086 - val_accuracy: 0.9683
Epoch 6/10
375/375 [==============================] - 2s 5ms/step - loss: 0.0698 - accuracy: 0.9798 - val_loss: 0.1102 - val_accuracy: 0.9669
Epoch 7/10
375/375 [==============================] - 2s 4ms/step - loss: 0.0594 - accuracy: 0.9833 - val_loss: 0.1086 - val_accuracy: 0.9667
Epoch 8/10
375/375 [==============================] - 2s 5ms/step - loss: 0.0489 - accuracy: 0.9866 - val_loss: 0.0976 - val_accuracy: 0.9717
Epoch 9/10
375/375 [==============================] - 2s 6ms/step - loss: 0.0422 - accuracy: 0.9884 - val_loss: 0.0900 - val_accuracy: 0.9728
Epoch 10/10
375/375 [==============================] - 2s 5ms/step - loss: 0.0360 - accuracy: 0.9904 - val_loss: 0.0928 - val_accuracy: 0.9722
Epoch 1/10
375/375 [==============================] - 107s 81ms/step - loss: 0.0333 - accuracy: 0.9904 - val_loss: 0.0908 - val_accuracy: 0.9744
Epoch 2/10
375/375 [==============================] - 8s 23ms/step - loss: 0.0261 - accuracy: 0.9931 - val_loss: 0.0901 - val_accuracy: 0.9741
Epoch 3/10
375/375 [==============================] - 9s 24ms/step - loss: 0.0219 - accuracy: 0.9948 - val_loss: 0.0891 - val_accuracy: 0.9745
Epoch 4/10
375/375 [==============================] - 9s 24ms/step - loss: 0.0182 - accuracy: 0.9958 - val_loss: 0.0919 - val_accuracy: 0.9743
Epoch 5/10
375/375 [==============================] - 8s 22ms/step - loss: 0.0159 - accuracy: 0.9964 - val_loss: 0.0930 - val_accuracy: 0.9737
Epoch 6/10
375/375 [==============================] - 9s 23ms/step - loss: 0.0140 - accuracy: 0.9969 - val_loss: 0.0898 - val_accuracy: 0.9752
Epoch 7/10
375/375 [==============================] - 9s 23ms/step - loss: 0.0111 - accuracy: 0.9979 - val_loss: 0.0961 - val_accuracy: 0.9733
Epoch 8/10
375/375 [==============================] - 8s 21ms/step - loss: 0.0094 - accuracy: 0.9984 - val_loss: 0.0933 - val_accuracy: 0.9754
Epoch 9/10
375/375 [==============================] - 9s 24ms/step - loss: 0.0076 - accuracy: 0.9990 - val_loss: 0.0966 - val_accuracy: 0.9759
Epoch 10/10
375/375 [==============================] - 9s 23ms/step - loss: 0.0063 - accuracy: 0.9994 - val_loss: 0.1079 - val_accuracy: 0.9720
375/375 [==============================] - 1s 3ms/step - loss: 0.0928 - accuracy: 0.9722
375/375 [==============================] - 5s 13ms/step - loss: 0.1079 - accuracy: 0.9720
375/375 [==============================] - 1s 2ms/step - loss: 0.0928 - accuracy: 0.9722
Test Accuracy: 0.9722499847412109
Task A Original Accuracy: 97.22%
Task B EWC method Accuracy: 97.20%
Epoch 1/10
375/375 [==============================] - 3s 6ms/step - loss: 0.3847 - accuracy: 0.8948 - val_loss: 0.2290 - val_accuracy: 0.9349
Epoch 2/10
375/375 [==============================] - 1s 4ms/step - loss: 0.1883 - accuracy: 0.9465 - val_loss: 0.1697 - val_accuracy: 0.9502
Epoch 3/10
375/375 [==============================] - 1s 4ms/step - loss: 0.1375 - accuracy: 0.9611 - val_loss: 0.1412 - val_accuracy: 0.9579
Epoch 4/10
375/375 [==============================] - 1s 3ms/step - loss: 0.1080 - accuracy: 0.9692 - val_loss: 0.1234 - val_accuracy: 0.9623
Epoch 5/10
375/375 [==============================] - 1s 4ms/step - loss: 0.0885 - accuracy: 0.9755 - val_loss: 0.1091 - val_accuracy: 0.9679
Epoch 6/10
375/375 [==============================] - 1s 4ms/step - loss: 0.0733 - accuracy: 0.9799 - val_loss: 0.1038 - val_accuracy: 0.9692
Epoch 7/10
375/375 [==============================] - 1s 3ms/step - loss: 0.0617 - accuracy: 0.9829 - val_loss: 0.0988 - val_accuracy: 0.9702
Epoch 8/10
375/375 [==============================] - 1s 4ms/step - loss: 0.0518 - accuracy: 0.9860 - val_loss: 0.0993 - val_accuracy: 0.9704
Epoch 9/10
375/375 [==============================] - 2s 4ms/step - loss: 0.0438 - accuracy: 0.9880 - val_loss: 0.0963 - val_accuracy: 0.9712
Epoch 10/10
375/375 [==============================] - 2s 5ms/step - loss: 0.0377 - accuracy: 0.9902 - val_loss: 0.0895 - val_accuracy: 0.9732
Epoch 1/10
375/375 [==============================] - 66s 46ms/step - loss: 0.0351 - accuracy: 0.9904 - val_loss: 0.0909 - val_accuracy: 0.9732
Epoch 2/10
375/375 [==============================] - 7s 18ms/step - loss: 0.0279 - accuracy: 0.9927 - val_loss: 0.0885 - val_accuracy: 0.9737
Epoch 3/10
375/375 [==============================] - 6s 17ms/step - loss: 0.0231 - accuracy: 0.9947 - val_loss: 0.0937 - val_accuracy: 0.9724
Epoch 4/10
375/375 [==============================] - 7s 18ms/step - loss: 0.0192 - accuracy: 0.9955 - val_loss: 0.0929 - val_accuracy: 0.9728
Epoch 5/10
375/375 [==============================] - 6s 16ms/step - loss: 0.0161 - accuracy: 0.9971 - val_loss: 0.0934 - val_accuracy: 0.9742
Epoch 6/10
375/375 [==============================] - 7s 18ms/step - loss: 0.0144 - accuracy: 0.9969 - val_loss: 0.0933 - val_accuracy: 0.9737
Epoch 7/10
375/375 [==============================] - 7s 19ms/step - loss: 0.0122 - accuracy: 0.9977 - val_loss: 0.1008 - val_accuracy: 0.9722
Epoch 8/10
375/375 [==============================] - 6s 17ms/step - loss: 0.0100 - accuracy: 0.9982 - val_loss: 0.0996 - val_accuracy: 0.9732
Epoch 9/10
375/375 [==============================] - 6s 15ms/step - loss: 0.0083 - accuracy: 0.9987 - val_loss: 0.0986 - val_accuracy: 0.9737
Epoch 10/10
375/375 [==============================] - 6s 17ms/step - loss: 0.0075 - accuracy: 0.9988 - val_loss: 0.0988 - val_accuracy: 0.9743
375/375 [==============================] - 1s 2ms/step - loss: 0.0895 - accuracy: 0.9732
375/375 [==============================] - 4s 10ms/step - loss: 0.0988 - accuracy: 0.9743
375/375 [==============================] - 1s 3ms/step - loss: 0.0895 - accuracy: 0.9732
Test Accuracy: 0.9732499718666077
Task A Original Accuracy: 97.32%
Task B EWC method Accuracy: 97.43%
Epoch 1/10
375/375 [==============================] - 2s 4ms/step - loss: 0.4003 - accuracy: 0.8913 - val_loss: 0.2231 - val_accuracy: 0.9364
Epoch 2/10
375/375 [==============================] - 1s 4ms/step - loss: 0.1870 - accuracy: 0.9475 - val_loss: 0.1585 - val_accuracy: 0.9518
Epoch 3/10
375/375 [==============================] - 1s 4ms/step - loss: 0.1344 - accuracy: 0.9622 - val_loss: 0.1282 - val_accuracy: 0.9623
Epoch 4/10
375/375 [==============================] - 1s 3ms/step - loss: 0.1038 - accuracy: 0.9707 - val_loss: 0.1135 - val_accuracy: 0.9641
Epoch 5/10
375/375 [==============================] - 1s 3ms/step - loss: 0.0832 - accuracy: 0.9764 - val_loss: 0.0994 - val_accuracy: 0.9689
Epoch 6/10
375/375 [==============================] - 1s 4ms/step - loss: 0.0687 - accuracy: 0.9809 - val_loss: 0.0919 - val_accuracy: 0.9725
Epoch 7/10
375/375 [==============================] - 1s 3ms/step - loss: 0.0569 - accuracy: 0.9840 - val_loss: 0.0934 - val_accuracy: 0.9709
Epoch 8/10
375/375 [==============================] - 2s 4ms/step - loss: 0.0494 - accuracy: 0.9860 - val_loss: 0.0862 - val_accuracy: 0.9730
Epoch 9/10
375/375 [==============================] - 2s 4ms/step - loss: 0.0407 - accuracy: 0.9891 - val_loss: 0.0844 - val_accuracy: 0.9732
Epoch 10/10
375/375 [==============================] - 1s 3ms/step - loss: 0.0347 - accuracy: 0.9912 - val_loss: 0.0844 - val_accuracy: 0.9740
Epoch 1/10
375/375 [==============================] - 66s 46ms/step - loss: 0.0327 - accuracy: 0.9913 - val_loss: 0.0898 - val_accuracy: 0.9728
Epoch 2/10
375/375 [==============================] - 7s 18ms/step - loss: 0.0269 - accuracy: 0.9928 - val_loss: 0.0827 - val_accuracy: 0.9754
Epoch 3/10
375/375 [==============================] - 6s 15ms/step - loss: 0.0221 - accuracy: 0.9945 - val_loss: 0.0825 - val_accuracy: 0.9758
Epoch 4/10
375/375 [==============================] - 6s 17ms/step - loss: 0.0181 - accuracy: 0.9961 - val_loss: 0.0818 - val_accuracy: 0.9765
Epoch 5/10
375/375 [==============================] - 6s 15ms/step - loss: 0.0150 - accuracy: 0.9970 - val_loss: 0.0820 - val_accuracy: 0.9766
Epoch 6/10
375/375 [==============================] - 7s 19ms/step - loss: 0.0130 - accuracy: 0.9976 - val_loss: 0.0846 - val_accuracy: 0.9758
Epoch 7/10
375/375 [==============================] - 6s 15ms/step - loss: 0.0108 - accuracy: 0.9980 - val_loss: 0.0869 - val_accuracy: 0.9762
Epoch 8/10
375/375 [==============================] - 6s 17ms/step - loss: 0.0096 - accuracy: 0.9983 - val_loss: 0.0842 - val_accuracy: 0.9772
Epoch 9/10
375/375 [==============================] - 6s 15ms/step - loss: 0.0078 - accuracy: 0.9988 - val_loss: 0.0906 - val_accuracy: 0.9762
Epoch 10/10
375/375 [==============================] - 6s 17ms/step - loss: 0.0065 - accuracy: 0.9990 - val_loss: 0.0868 - val_accuracy: 0.9772
375/375 [==============================] - 1s 3ms/step - loss: 0.0844 - accuracy: 0.9740
375/375 [==============================] - 4s 10ms/step - loss: 0.0868 - accuracy: 0.9772
375/375 [==============================] - 1s 2ms/step - loss: 0.0844 - accuracy: 0.9740
Test Accuracy: 0.9739999771118164
Task A Original Accuracy: 97.40%
Task B EWC method Accuracy: 97.72%
Epoch 1/10
375/375 [==============================] - 2s 4ms/step - loss: 0.3995 - accuracy: 0.8912 - val_loss: 0.2376 - val_accuracy: 0.9348
Epoch 2/10
375/375 [==============================] - 1s 4ms/step - loss: 0.1865 - accuracy: 0.9472 - val_loss: 0.1780 - val_accuracy: 0.9484
Epoch 3/10
375/375 [==============================] - 2s 5ms/step - loss: 0.1358 - accuracy: 0.9617 - val_loss: 0.1432 - val_accuracy: 0.9582
Epoch 4/10
375/375 [==============================] - 1s 3ms/step - loss: 0.1064 - accuracy: 0.9701 - val_loss: 0.1206 - val_accuracy: 0.9657
Epoch 5/10
375/375 [==============================] - 1s 3ms/step - loss: 0.0856 - accuracy: 0.9763 - val_loss: 0.1100 - val_accuracy: 0.9679
Epoch 6/10
375/375 [==============================] - 1s 3ms/step - loss: 0.0717 - accuracy: 0.9799 - val_loss: 0.1049 - val_accuracy: 0.9691
Epoch 7/10
375/375 [==============================] - 1s 4ms/step - loss: 0.0610 - accuracy: 0.9827 - val_loss: 0.0979 - val_accuracy: 0.9710
Epoch 8/10
375/375 [==============================] - 1s 3ms/step - loss: 0.0508 - accuracy: 0.9856 - val_loss: 0.0917 - val_accuracy: 0.9731
Epoch 9/10
375/375 [==============================] - 1s 3ms/step - loss: 0.0428 - accuracy: 0.9884 - val_loss: 0.0892 - val_accuracy: 0.9748
Epoch 10/10
375/375 [==============================] - 1s 3ms/step - loss: 0.0371 - accuracy: 0.9896 - val_loss: 0.0887 - val_accuracy: 0.9744
Epoch 1/10
375/375 [==============================] - 62s 38ms/step - loss: 0.0338 - accuracy: 0.9906 - val_loss: 0.0901 - val_accuracy: 0.9742
Epoch 2/10
375/375 [==============================] - 2s 5ms/step - loss: 0.0272 - accuracy: 0.9927 - val_loss: 0.0854 - val_accuracy: 0.9759
Epoch 3/10
375/375 [==============================] - 2s 5ms/step - loss: 0.0240 - accuracy: 0.9938 - val_loss: 0.0867 - val_accuracy: 0.9742
Epoch 4/10
375/375 [==============================] - 3s 7ms/step - loss: 0.0190 - accuracy: 0.9960 - val_loss: 0.0861 - val_accuracy: 0.9764
Epoch 5/10
375/375 [==============================] - 2s 6ms/step - loss: 0.0162 - accuracy: 0.9965 - val_loss: 0.0875 - val_accuracy: 0.9750
Epoch 6/10
375/375 [==============================] - 2s 6ms/step - loss: 0.0142 - accuracy: 0.9970 - val_loss: 0.0858 - val_accuracy: 0.9770
Epoch 7/10
375/375 [==============================] - 2s 6ms/step - loss: 0.0105 - accuracy: 0.9983 - val_loss: 0.0886 - val_accuracy: 0.9758
Epoch 8/10
375/375 [==============================] - 2s 5ms/step - loss: 0.0095 - accuracy: 0.9986 - val_loss: 0.0837 - val_accuracy: 0.9773
Epoch 9/10
375/375 [==============================] - 2s 5ms/step - loss: 0.0090 - accuracy: 0.9984 - val_loss: 0.0897 - val_accuracy: 0.9762
Epoch 10/10
375/375 [==============================] - 3s 8ms/step - loss: 0.0074 - accuracy: 0.9988 - val_loss: 0.0851 - val_accuracy: 0.9770
375/375 [==============================] - 1s 2ms/step - loss: 0.0887 - accuracy: 0.9744
375/375 [==============================] - 2s 4ms/step - loss: 0.0851 - accuracy: 0.9770
375/375 [==============================] - 1s 2ms/step - loss: 0.0887 - accuracy: 0.9744
Test Accuracy: 0.9744166731834412
Task A Original Accuracy: 97.44%
Task B EWC method Accuracy: 97.70%
Fold-1: 97.32%
Fold-2: 97.22%
Fold-3: 97.32%
Fold-4: 97.40%
Fold-5: 97.44%

### CIFAR10

In [ ]:
import numpy as np
# from tensorflow.keras.datasets import cifar100
import numpy as np
# Importing the necessary libraries, which we may or may not use. Its always good idea to import them befor (if you remember) else we can do it at any point of time no problem.
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPool2D,Dense,Flatten,Dropout,Input, AveragePooling2D, Activation,Conv2D, MaxPooling2D, BatchNormalization,Concatenate
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
from tensorflow.keras import regularizers, optimizers
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.datasets import cifar100
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers
from tensorflow.keras.regularizers import Regularizer

# Perform hold-out cross-validation
validation_scores = []

# Define the CrlB regularizer
class CrlBRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    fisher_matrix = []
    for i in range(len(model.trainable_weights)):
        fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

    for _ in range(num_samples):
        idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
        with tf.GradientTape() as tape:
            logits = model(x[idx:idx+1])
        gradients = tape.gradient(logits, model.trainable_weights)
        for i in range(len(fisher_matrix)):
            fisher_matrix[i] += tf.square(gradients[i])

    fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
    return fisher_matrix

fisher_matrix = compute_fisher(model, x_train_fold)

# Number of K-folds
K = 5

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)
# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []
num_classes = 10
# Perform K-fold cross-validation
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]

# Task A: Original Fashion MNIST model
    model = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        Conv2D(32, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu'),
        layers.Dropout(0.25),
        Dense(num_classes, activation='softmax')
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model = model
        model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
        model.save_weights('FashionMNIST_A.h5')
        prior_weights = model.get_weights()
# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]

# Task B: Fashion MNIST with CrlB regularization
    model_CrlBB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3),
               kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model_CrlBB = model_CrlBB
        model_CrlBB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model_CrlBB.load_weights('FashionMNIST_A.h5')
        model_CrlBB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlB_acc = 100 * model_CrlBB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlB method Accuracy: %.2f%%" % B_CrlB_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
375/375 [==============================] - 11s 18ms/step - loss: 2.6488 - accuracy: 0.2945 - val_loss: 1.5123 - val_accuracy: 0.4449
Epoch 2/10
375/375 [==============================] - 6s 15ms/step - loss: 1.4596 - accuracy: 0.4728 - val_loss: 1.2492 - val_accuracy: 0.5500
Epoch 3/10
375/375 [==============================] - 8s 20ms/step - loss: 1.2416 - accuracy: 0.5558 - val_loss: 1.0705 - val_accuracy: 0.6184
Epoch 4/10
375/375 [==============================] - 6s 16ms/step - loss: 1.1125 - accuracy: 0.6081 - val_loss: 1.0117 - val_accuracy: 0.6442
Epoch 5/10
375/375 [==============================] - 6s 16ms/step - loss: 1.0049 - accuracy: 0.6470 - val_loss: 0.9657 - val_accuracy: 0.6637
Epoch 6/10
375/375 [==============================] - 6s 15ms/step - loss: 0.9272 - accuracy: 0.6754 - val_loss: 0.8988 - val_accuracy: 0.6830
Epoch 7/10
375/375 [==============================] - 6s 17ms/step - loss: 0.8576 - accuracy: 0.7015 - val_loss: 0.8792 - val_accuracy: 0.6956
Epoch 8/10
375/375 [==============================] - 5s 14ms/step - loss: 0.8025 - accuracy: 0.7155 - val_loss: 0.8009 - val_accuracy: 0.7210
Epoch 9/10
375/375 [==============================] - 6s 16ms/step - loss: 0.7498 - accuracy: 0.7371 - val_loss: 0.7970 - val_accuracy: 0.7242
Epoch 10/10
375/375 [==============================] - 6s 15ms/step - loss: 0.7043 - accuracy: 0.7524 - val_loss: 0.8079 - val_accuracy: 0.7227
Epoch 1/10
375/375 [==============================] - 18s 25ms/step - loss: 0.6213 - accuracy: 0.7809 - val_loss: 0.7571 - val_accuracy: 0.7469
Epoch 2/10
375/375 [==============================] - 7s 19ms/step - loss: 0.5481 - accuracy: 0.8063 - val_loss: 0.8192 - val_accuracy: 0.7294
Epoch 3/10
375/375 [==============================] - 7s 19ms/step - loss: 0.4799 - accuracy: 0.8311 - val_loss: 0.8185 - val_accuracy: 0.7365
Epoch 4/10
375/375 [==============================] - 8s 21ms/step - loss: 0.4273 - accuracy: 0.8520 - val_loss: 0.8655 - val_accuracy: 0.7322
Epoch 5/10
375/375 [==============================] - 7s 18ms/step - loss: 0.3848 - accuracy: 0.8666 - val_loss: 0.8522 - val_accuracy: 0.7423
Epoch 6/10
375/375 [==============================] - 7s 19ms/step - loss: 0.3482 - accuracy: 0.8791 - val_loss: 0.8866 - val_accuracy: 0.7402
Epoch 7/10
375/375 [==============================] - 7s 17ms/step - loss: 0.3121 - accuracy: 0.8916 - val_loss: 0.8984 - val_accuracy: 0.7476
Epoch 8/10
375/375 [==============================] - 7s 19ms/step - loss: 0.2986 - accuracy: 0.8965 - val_loss: 0.9103 - val_accuracy: 0.7408
Epoch 9/10
375/375 [==============================] - 6s 17ms/step - loss: 0.2704 - accuracy: 0.9076 - val_loss: 0.9794 - val_accuracy: 0.7375
Epoch 10/10
375/375 [==============================] - 7s 19ms/step - loss: 0.2631 - accuracy: 0.9087 - val_loss: 1.0168 - val_accuracy: 0.7428
375/375 [==============================] - 2s 6ms/step - loss: 0.8079 - accuracy: 0.7227
375/375 [==============================] - 2s 6ms/step - loss: 1.0168 - accuracy: 0.7428
375/375 [==============================] - 1s 4ms/step - loss: 0.8079 - accuracy: 0.7227
Test Accuracy: 0.7226666808128357
Task A Original Accuracy: 72.27%
Task B EWC method Accuracy: 74.28%
Epoch 1/10
375/375 [==============================] - 11s 20ms/step - loss: 2.9806 - accuracy: 0.3062 - val_loss: 1.4606 - val_accuracy: 0.4774
Epoch 2/10
375/375 [==============================] - 6s 15ms/step - loss: 1.4782 - accuracy: 0.4668 - val_loss: 1.2345 - val_accuracy: 0.5594
Epoch 3/10
375/375 [==============================] - 6s 16ms/step - loss: 1.2823 - accuracy: 0.5435 - val_loss: 1.1225 - val_accuracy: 0.6168
Epoch 4/10
375/375 [==============================] - 5s 14ms/step - loss: 1.1396 - accuracy: 0.5987 - val_loss: 1.0631 - val_accuracy: 0.6376
Epoch 5/10
375/375 [==============================] - 6s 17ms/step - loss: 1.0337 - accuracy: 0.6342 - val_loss: 0.9578 - val_accuracy: 0.6643
Epoch 6/10
375/375 [==============================] - 6s 15ms/step - loss: 0.9501 - accuracy: 0.6642 - val_loss: 0.8852 - val_accuracy: 0.6919
Epoch 7/10
375/375 [==============================] - 7s 17ms/step - loss: 0.8910 - accuracy: 0.6877 - val_loss: 0.8437 - val_accuracy: 0.7076
Epoch 8/10
375/375 [==============================] - 5s 15ms/step - loss: 0.8352 - accuracy: 0.7088 - val_loss: 0.8068 - val_accuracy: 0.7168
Epoch 9/10
375/375 [==============================] - 6s 17ms/step - loss: 0.7795 - accuracy: 0.7257 - val_loss: 0.8108 - val_accuracy: 0.7175
Epoch 10/10
375/375 [==============================] - 6s 15ms/step - loss: 0.7349 - accuracy: 0.7427 - val_loss: 0.7920 - val_accuracy: 0.7218
Epoch 1/10
375/375 [==============================] - 17s 25ms/step - loss: 0.6626 - accuracy: 0.7678 - val_loss: 0.8285 - val_accuracy: 0.7128
Epoch 2/10
375/375 [==============================] - 6s 17ms/step - loss: 0.5937 - accuracy: 0.7943 - val_loss: 0.7837 - val_accuracy: 0.7328
Epoch 3/10
375/375 [==============================] - 7s 19ms/step - loss: 0.5306 - accuracy: 0.8148 - val_loss: 0.7786 - val_accuracy: 0.7369
Epoch 4/10
375/375 [==============================] - 7s 18ms/step - loss: 0.4711 - accuracy: 0.8360 - val_loss: 0.7920 - val_accuracy: 0.7398
Epoch 5/10
375/375 [==============================] - 7s 19ms/step - loss: 0.4302 - accuracy: 0.8518 - val_loss: 0.8105 - val_accuracy: 0.7400
Epoch 6/10
375/375 [==============================] - 7s 19ms/step - loss: 0.3867 - accuracy: 0.8643 - val_loss: 0.8567 - val_accuracy: 0.7333
Epoch 7/10
375/375 [==============================] - 7s 19ms/step - loss: 0.3422 - accuracy: 0.8807 - val_loss: 0.8782 - val_accuracy: 0.7399
Epoch 8/10
375/375 [==============================] - 7s 20ms/step - loss: 0.3319 - accuracy: 0.8844 - val_loss: 0.9011 - val_accuracy: 0.7387
Epoch 9/10
375/375 [==============================] - 7s 17ms/step - loss: 0.2951 - accuracy: 0.8983 - val_loss: 0.9013 - val_accuracy: 0.7502
Epoch 10/10
375/375 [==============================] - 8s 20ms/step - loss: 0.2727 - accuracy: 0.9087 - val_loss: 0.9560 - val_accuracy: 0.7429
375/375 [==============================] - 2s 4ms/step - loss: 0.7920 - accuracy: 0.7218
375/375 [==============================] - 2s 7ms/step - loss: 0.9560 - accuracy: 0.7429
375/375 [==============================] - 1s 4ms/step - loss: 0.7920 - accuracy: 0.7218
Test Accuracy: 0.721750020980835
Task A Original Accuracy: 72.18%
Task B EWC method Accuracy: 74.29%
Epoch 1/10
375/375 [==============================] - 10s 16ms/step - loss: 2.2837 - accuracy: 0.3041 - val_loss: 1.5257 - val_accuracy: 0.4489
Epoch 2/10
375/375 [==============================] - 6s 16ms/step - loss: 1.5296 - accuracy: 0.4455 - val_loss: 1.3535 - val_accuracy: 0.5263
Epoch 3/10
375/375 [==============================] - 5s 14ms/step - loss: 1.3676 - accuracy: 0.5074 - val_loss: 1.2623 - val_accuracy: 0.5727
Epoch 4/10
375/375 [==============================] - 6s 15ms/step - loss: 1.2418 - accuracy: 0.5580 - val_loss: 1.1430 - val_accuracy: 0.5981
Epoch 5/10
375/375 [==============================] - 6s 16ms/step - loss: 1.1463 - accuracy: 0.5934 - val_loss: 1.1080 - val_accuracy: 0.6127
Epoch 6/10
375/375 [==============================] - 6s 15ms/step - loss: 1.0407 - accuracy: 0.6330 - val_loss: 0.9821 - val_accuracy: 0.6589
Epoch 7/10
375/375 [==============================] - 6s 16ms/step - loss: 0.9649 - accuracy: 0.6609 - val_loss: 0.9217 - val_accuracy: 0.6737
Epoch 8/10
375/375 [==============================] - 5s 14ms/step - loss: 0.8915 - accuracy: 0.6837 - val_loss: 0.8796 - val_accuracy: 0.6967
Epoch 9/10
375/375 [==============================] - 6s 17ms/step - loss: 0.8289 - accuracy: 0.7084 - val_loss: 0.8549 - val_accuracy: 0.7061
Epoch 10/10
375/375 [==============================] - 5s 14ms/step - loss: 0.7709 - accuracy: 0.7305 - val_loss: 0.8371 - val_accuracy: 0.7165
Epoch 1/10
375/375 [==============================] - 16s 23ms/step - loss: 0.6626 - accuracy: 0.7674 - val_loss: 0.8294 - val_accuracy: 0.7174
Epoch 2/10
375/375 [==============================] - 6s 15ms/step - loss: 0.5948 - accuracy: 0.7923 - val_loss: 0.8584 - val_accuracy: 0.7089
Epoch 3/10
375/375 [==============================] - 6s 16ms/step - loss: 0.5265 - accuracy: 0.8148 - val_loss: 0.8516 - val_accuracy: 0.7222
Epoch 4/10
375/375 [==============================] - 6s 16ms/step - loss: 0.4687 - accuracy: 0.8373 - val_loss: 0.8729 - val_accuracy: 0.7194
Epoch 5/10
375/375 [==============================] - 6s 16ms/step - loss: 0.4255 - accuracy: 0.8515 - val_loss: 0.8955 - val_accuracy: 0.7197
Epoch 6/10
375/375 [==============================] - 6s 16ms/step - loss: 0.3739 - accuracy: 0.8684 - val_loss: 0.9177 - val_accuracy: 0.7247
Epoch 7/10
375/375 [==============================] - 6s 16ms/step - loss: 0.3522 - accuracy: 0.8787 - val_loss: 0.9370 - val_accuracy: 0.7269
Epoch 8/10
375/375 [==============================] - 6s 16ms/step - loss: 0.3255 - accuracy: 0.8859 - val_loss: 1.0103 - val_accuracy: 0.7198
Epoch 9/10
375/375 [==============================] - 6s 16ms/step - loss: 0.2959 - accuracy: 0.8982 - val_loss: 1.0179 - val_accuracy: 0.7258
Epoch 10/10
375/375 [==============================] - 6s 16ms/step - loss: 0.2885 - accuracy: 0.9008 - val_loss: 0.9905 - val_accuracy: 0.7274
375/375 [==============================] - 1s 3ms/step - loss: 0.8371 - accuracy: 0.7165
375/375 [==============================] - 2s 5ms/step - loss: 0.9905 - accuracy: 0.7274
375/375 [==============================] - 1s 3ms/step - loss: 0.8371 - accuracy: 0.7165
Test Accuracy: 0.7164999842643738
Task A Original Accuracy: 71.65%
Task B EWC method Accuracy: 72.74%
Epoch 1/10
375/375 [==============================] - 8s 14ms/step - loss: 2.6102 - accuracy: 0.3017 - val_loss: 1.4597 - val_accuracy: 0.4837
Epoch 2/10
375/375 [==============================] - 5s 13ms/step - loss: 1.4342 - accuracy: 0.4843 - val_loss: 1.2699 - val_accuracy: 0.5533
Epoch 3/10
375/375 [==============================] - 6s 16ms/step - loss: 1.2441 - accuracy: 0.5560 - val_loss: 1.1519 - val_accuracy: 0.5907
Epoch 4/10
375/375 [==============================] - 5s 13ms/step - loss: 1.1148 - accuracy: 0.6061 - val_loss: 0.9900 - val_accuracy: 0.6541
Epoch 5/10
375/375 [==============================] - 5s 14ms/step - loss: 1.0229 - accuracy: 0.6404 - val_loss: 0.9452 - val_accuracy: 0.6723
Epoch 6/10
375/375 [==============================] - 5s 14ms/step - loss: 0.9288 - accuracy: 0.6721 - val_loss: 0.8901 - val_accuracy: 0.6982
Epoch 7/10
375/375 [==============================] - 5s 13ms/step - loss: 0.8602 - accuracy: 0.6991 - val_loss: 0.8435 - val_accuracy: 0.7118
Epoch 8/10
375/375 [==============================] - 5s 13ms/step - loss: 0.7988 - accuracy: 0.7211 - val_loss: 0.8004 - val_accuracy: 0.7211
Epoch 9/10
375/375 [==============================] - 5s 13ms/step - loss: 0.7415 - accuracy: 0.7397 - val_loss: 0.8089 - val_accuracy: 0.7265
Epoch 10/10
375/375 [==============================] - 5s 14ms/step - loss: 0.6839 - accuracy: 0.7564 - val_loss: 0.7781 - val_accuracy: 0.7347
Epoch 1/10
375/375 [==============================] - 13s 21ms/step - loss: 0.5989 - accuracy: 0.7894 - val_loss: 0.7810 - val_accuracy: 0.7384
Epoch 2/10
375/375 [==============================] - 6s 16ms/step - loss: 0.5275 - accuracy: 0.8137 - val_loss: 0.7936 - val_accuracy: 0.7380
Epoch 3/10
375/375 [==============================] - 6s 17ms/step - loss: 0.4748 - accuracy: 0.8321 - val_loss: 0.7939 - val_accuracy: 0.7357
Epoch 4/10
375/375 [==============================] - 6s 16ms/step - loss: 0.4189 - accuracy: 0.8535 - val_loss: 0.8375 - val_accuracy: 0.7406
Epoch 5/10
375/375 [==============================] - 6s 16ms/step - loss: 0.3800 - accuracy: 0.8659 - val_loss: 0.8509 - val_accuracy: 0.7387
Epoch 6/10
375/375 [==============================] - 6s 16ms/step - loss: 0.3460 - accuracy: 0.8791 - val_loss: 0.9457 - val_accuracy: 0.7324
Epoch 7/10
375/375 [==============================] - 6s 17ms/step - loss: 0.3204 - accuracy: 0.8908 - val_loss: 0.9077 - val_accuracy: 0.7365
Epoch 8/10
375/375 [==============================] - 6s 16ms/step - loss: 0.2999 - accuracy: 0.8960 - val_loss: 1.0224 - val_accuracy: 0.7237
Epoch 9/10
375/375 [==============================] - 6s 16ms/step - loss: 0.2763 - accuracy: 0.9063 - val_loss: 1.0046 - val_accuracy: 0.7277
Epoch 10/10
375/375 [==============================] - 6s 16ms/step - loss: 0.2431 - accuracy: 0.9163 - val_loss: 0.9780 - val_accuracy: 0.7412
375/375 [==============================] - 1s 3ms/step - loss: 0.7781 - accuracy: 0.7347
375/375 [==============================] - 2s 5ms/step - loss: 0.9780 - accuracy: 0.7412
375/375 [==============================] - 1s 4ms/step - loss: 0.7781 - accuracy: 0.7347
Test Accuracy: 0.734666645526886
Task A Original Accuracy: 73.47%
Task B EWC method Accuracy: 74.12%
Epoch 1/10
375/375 [==============================] - 7s 14ms/step - loss: 2.5199 - accuracy: 0.3565 - val_loss: 1.4989 - val_accuracy: 0.4663
Epoch 2/10
375/375 [==============================] - 5s 14ms/step - loss: 1.4053 - accuracy: 0.4943 - val_loss: 1.1975 - val_accuracy: 0.5811
Epoch 3/10
375/375 [==============================] - 5s 13ms/step - loss: 1.2233 - accuracy: 0.5677 - val_loss: 1.1676 - val_accuracy: 0.5905
Epoch 4/10
375/375 [==============================] - 5s 13ms/step - loss: 1.0961 - accuracy: 0.6144 - val_loss: 1.0107 - val_accuracy: 0.6465
Epoch 5/10
375/375 [==============================] - 5s 14ms/step - loss: 0.9956 - accuracy: 0.6513 - val_loss: 0.9411 - val_accuracy: 0.6740
Epoch 6/10
375/375 [==============================] - 5s 13ms/step - loss: 0.9175 - accuracy: 0.6769 - val_loss: 0.8647 - val_accuracy: 0.7009
Epoch 7/10
375/375 [==============================] - 5s 14ms/step - loss: 0.8479 - accuracy: 0.7020 - val_loss: 0.8818 - val_accuracy: 0.6943
Epoch 8/10
375/375 [==============================] - 5s 13ms/step - loss: 0.7982 - accuracy: 0.7180 - val_loss: 0.8180 - val_accuracy: 0.7196
Epoch 9/10
375/375 [==============================] - 5s 14ms/step - loss: 0.7477 - accuracy: 0.7385 - val_loss: 0.8101 - val_accuracy: 0.7201
Epoch 10/10
375/375 [==============================] - 5s 13ms/step - loss: 0.7097 - accuracy: 0.7510 - val_loss: 0.8183 - val_accuracy: 0.7143
Epoch 1/10
375/375 [==============================] - 13s 21ms/step - loss: 0.6202 - accuracy: 0.7806 - val_loss: 0.7930 - val_accuracy: 0.7312
Epoch 2/10
375/375 [==============================] - 6s 16ms/step - loss: 0.5505 - accuracy: 0.8060 - val_loss: 0.8242 - val_accuracy: 0.7272
Epoch 3/10
375/375 [==============================] - 6s 17ms/step - loss: 0.4925 - accuracy: 0.8271 - val_loss: 0.8402 - val_accuracy: 0.7273
Epoch 4/10
375/375 [==============================] - 6s 16ms/step - loss: 0.4353 - accuracy: 0.8482 - val_loss: 0.8584 - val_accuracy: 0.7305
Epoch 5/10
375/375 [==============================] - 6s 16ms/step - loss: 0.4145 - accuracy: 0.8562 - val_loss: 0.8784 - val_accuracy: 0.7289
Epoch 6/10
375/375 [==============================] - 6s 16ms/step - loss: 0.3643 - accuracy: 0.8725 - val_loss: 0.8862 - val_accuracy: 0.7356
Epoch 7/10
375/375 [==============================] - 6s 17ms/step - loss: 0.3304 - accuracy: 0.8859 - val_loss: 0.9750 - val_accuracy: 0.7336
Epoch 8/10
375/375 [==============================] - 6s 16ms/step - loss: 0.3078 - accuracy: 0.8939 - val_loss: 0.9508 - val_accuracy: 0.7297
Epoch 9/10
375/375 [==============================] - 6s 17ms/step - loss: 0.2773 - accuracy: 0.9050 - val_loss: 1.0215 - val_accuracy: 0.7287
Epoch 10/10
375/375 [==============================] - 6s 17ms/step - loss: 0.2705 - accuracy: 0.9074 - val_loss: 1.0270 - val_accuracy: 0.7400
375/375 [==============================] - 1s 3ms/step - loss: 0.8183 - accuracy: 0.7143
375/375 [==============================] - 2s 5ms/step - loss: 1.0270 - accuracy: 0.7400
375/375 [==============================] - 2s 4ms/step - loss: 0.8183 - accuracy: 0.7143
Test Accuracy: 0.7142500281333923
Task A Original Accuracy: 71.43%
Task B EWC method Accuracy: 74.00%
Fold-1: 72.27%
Fold-2: 72.18%
Fold-3: 71.65%
Fold-4: 73.47%
Fold-5: 71.43%

### CIFAR10-C

In [ ]:
import numpy as np
# from tensorflow.keras.datasets import cifar100
import numpy as np
# Importing the necessary libraries, which we may or may not use. Its always good idea to import them befor (if you remember) else we can do it at any point of time no problem.
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPool2D,Dense,Flatten,Dropout,Input, AveragePooling2D, Activation,Conv2D, MaxPooling2D, BatchNormalization,Concatenate
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
from tensorflow.keras import regularizers, optimizers
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.datasets import cifar100
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers
from tensorflow.keras.regularizers import Regularizer

# Perform hold-out cross-validation
validation_scores = []

# Define the CrlB regularizer
class CrlBRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Number of K-folds
K = 5

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)
# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []
num_classes = 10
# Perform K-fold cross-validation
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]

# Task A: Original Fashion MNIST model
    model = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        Conv2D(32, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu'),
        layers.Dropout(0.25),
        Dense(num_classes, activation='softmax')
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model = model
        model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
        model.save_weights('FashionMNIST_A.h5')
        prior_weights = model.get_weights()
# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    fisher_matrix = []
    for i in range(len(model.trainable_weights)):
        fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

    for _ in range(num_samples):
        idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
        with tf.GradientTape() as tape:
            logits = model(x[idx:idx+1])
        gradients = tape.gradient(logits, model.trainable_weights)
        for i in range(len(fisher_matrix)):
            fisher_matrix[i] += tf.square(gradients[i])

    fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
    return fisher_matrix

fisher_matrix = compute_fisher(model, x_train_fold)
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]
# Task B: Fashion MNIST with CrlB regularization
    model_CrlBB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3),
               kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model_CrlBB = model_CrlBB
        model_CrlBB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model_CrlBB.load_weights('FashionMNIST_A.h5')
        model_CrlBB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlB_acc = 100 * model_CrlBB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlB method Accuracy: %.2f%%" % B_CrlB_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
375/375 [==============================] - 21s 26ms/step - loss: 1.6696 - accuracy: 0.3904 - val_loss: 1.3170 - val_accuracy: 0.5216
Epoch 2/10
375/375 [==============================] - 7s 20ms/step - loss: 1.2662 - accuracy: 0.5460 - val_loss: 1.1560 - val_accuracy: 0.5882
Epoch 3/10
375/375 [==============================] - 8s 21ms/step - loss: 1.0917 - accuracy: 0.6123 - val_loss: 1.0102 - val_accuracy: 0.6442
Epoch 4/10
375/375 [==============================] - 8s 21ms/step - loss: 0.9818 - accuracy: 0.6529 - val_loss: 0.9444 - val_accuracy: 0.6684
Epoch 5/10
375/375 [==============================] - 8s 21ms/step - loss: 0.8974 - accuracy: 0.6813 - val_loss: 0.9066 - val_accuracy: 0.6827
Epoch 6/10
375/375 [==============================] - 8s 21ms/step - loss: 0.8226 - accuracy: 0.7094 - val_loss: 0.8922 - val_accuracy: 0.6886
Epoch 7/10
375/375 [==============================] - 7s 19ms/step - loss: 0.7592 - accuracy: 0.7327 - val_loss: 0.8678 - val_accuracy: 0.7009
Epoch 8/10
375/375 [==============================] - 8s 21ms/step - loss: 0.6932 - accuracy: 0.7535 - val_loss: 0.8759 - val_accuracy: 0.7036
Epoch 9/10
375/375 [==============================] - 7s 19ms/step - loss: 0.6432 - accuracy: 0.7700 - val_loss: 0.8639 - val_accuracy: 0.7023
Epoch 10/10
375/375 [==============================] - 8s 20ms/step - loss: 0.5869 - accuracy: 0.7920 - val_loss: 0.9102 - val_accuracy: 0.7022
Epoch 1/10
375/375 [==============================] - 14s 21ms/step - loss: 1.6457 - accuracy: 0.3981 - val_loss: 1.3474 - val_accuracy: 0.5119
Epoch 2/10
375/375 [==============================] - 8s 21ms/step - loss: 1.2659 - accuracy: 0.5452 - val_loss: 1.1187 - val_accuracy: 0.6038
Epoch 3/10
375/375 [==============================] - 8s 21ms/step - loss: 1.0952 - accuracy: 0.6108 - val_loss: 1.0033 - val_accuracy: 0.6439
Epoch 4/10
375/375 [==============================] - 7s 20ms/step - loss: 0.9724 - accuracy: 0.6554 - val_loss: 0.9432 - val_accuracy: 0.6647
Epoch 5/10
375/375 [==============================] - 8s 20ms/step - loss: 0.8856 - accuracy: 0.6876 - val_loss: 0.8966 - val_accuracy: 0.6835
Epoch 6/10
375/375 [==============================] - 7s 19ms/step - loss: 0.8008 - accuracy: 0.7170 - val_loss: 0.8662 - val_accuracy: 0.6961
Epoch 7/10
375/375 [==============================] - 8s 22ms/step - loss: 0.7271 - accuracy: 0.7434 - val_loss: 0.8736 - val_accuracy: 0.6932
Epoch 8/10
375/375 [==============================] - 8s 21ms/step - loss: 0.6638 - accuracy: 0.7655 - val_loss: 0.8782 - val_accuracy: 0.6966
Epoch 9/10
375/375 [==============================] - 7s 19ms/step - loss: 0.5980 - accuracy: 0.7899 - val_loss: 0.8995 - val_accuracy: 0.6992
Epoch 10/10
375/375 [==============================] - 8s 21ms/step - loss: 0.5456 - accuracy: 0.8074 - val_loss: 0.9158 - val_accuracy: 0.6912
Epoch 1/10
375/375 [==============================] - 17s 24ms/step - loss: 1.6379 - accuracy: 0.4031 - val_loss: 1.3237 - val_accuracy: 0.5291
Epoch 2/10
375/375 [==============================] - 8s 21ms/step - loss: 1.2594 - accuracy: 0.5482 - val_loss: 1.1103 - val_accuracy: 0.6068
Epoch 3/10
375/375 [==============================] - 8s 22ms/step - loss: 1.1041 - accuracy: 0.6053 - val_loss: 1.0789 - val_accuracy: 0.6196
Epoch 4/10
375/375 [==============================] - 7s 20ms/step - loss: 0.9848 - accuracy: 0.6519 - val_loss: 0.9728 - val_accuracy: 0.6646
Epoch 5/10
375/375 [==============================] - 8s 21ms/step - loss: 0.8907 - accuracy: 0.6848 - val_loss: 0.9263 - val_accuracy: 0.6783
Epoch 6/10
375/375 [==============================] - 7s 20ms/step - loss: 0.8062 - accuracy: 0.7159 - val_loss: 0.9000 - val_accuracy: 0.6867
Epoch 7/10
375/375 [==============================] - 8s 21ms/step - loss: 0.7410 - accuracy: 0.7398 - val_loss: 0.9287 - val_accuracy: 0.6873
Epoch 8/10
375/375 [==============================] - 8s 21ms/step - loss: 0.6626 - accuracy: 0.7656 - val_loss: 0.8823 - val_accuracy: 0.7017
Epoch 9/10
375/375 [==============================] - 7s 20ms/step - loss: 0.6027 - accuracy: 0.7847 - val_loss: 0.8846 - val_accuracy: 0.7032
Epoch 10/10
375/375 [==============================] - 8s 21ms/step - loss: 0.5405 - accuracy: 0.8085 - val_loss: 0.9211 - val_accuracy: 0.7003
Epoch 1/10
375/375 [==============================] - 15s 23ms/step - loss: 1.6411 - accuracy: 0.4020 - val_loss: 1.3182 - val_accuracy: 0.5238
Epoch 2/10
375/375 [==============================] - 8s 20ms/step - loss: 1.2568 - accuracy: 0.5500 - val_loss: 1.2044 - val_accuracy: 0.5797
Epoch 3/10
375/375 [==============================] - 8s 21ms/step - loss: 1.1079 - accuracy: 0.6055 - val_loss: 1.0196 - val_accuracy: 0.6432
Epoch 4/10
375/375 [==============================] - 8s 21ms/step - loss: 1.0014 - accuracy: 0.6471 - val_loss: 0.9855 - val_accuracy: 0.6511
Epoch 5/10
375/375 [==============================] - 8s 21ms/step - loss: 0.9098 - accuracy: 0.6764 - val_loss: 0.9784 - val_accuracy: 0.6584
Epoch 6/10
375/375 [==============================] - 7s 18ms/step - loss: 0.8392 - accuracy: 0.7044 - val_loss: 0.9001 - val_accuracy: 0.6837
Epoch 7/10
375/375 [==============================] - 8s 20ms/step - loss: 0.7517 - accuracy: 0.7329 - val_loss: 0.8807 - val_accuracy: 0.6969
Epoch 8/10
375/375 [==============================] - 7s 19ms/step - loss: 0.6853 - accuracy: 0.7565 - val_loss: 0.9050 - val_accuracy: 0.6966
Epoch 9/10
375/375 [==============================] - 8s 21ms/step - loss: 0.6268 - accuracy: 0.7761 - val_loss: 0.8932 - val_accuracy: 0.6985
Epoch 10/10
375/375 [==============================] - 8s 21ms/step - loss: 0.5626 - accuracy: 0.7986 - val_loss: 0.9171 - val_accuracy: 0.7054
Epoch 1/10
375/375 [==============================] - 14s 24ms/step - loss: 1.6752 - accuracy: 0.3869 - val_loss: 1.3333 - val_accuracy: 0.5153
Epoch 2/10
375/375 [==============================] - 9s 23ms/step - loss: 1.2657 - accuracy: 0.5452 - val_loss: 1.1293 - val_accuracy: 0.5962
Epoch 3/10
375/375 [==============================] - 8s 22ms/step - loss: 1.0942 - accuracy: 0.6110 - val_loss: 1.0234 - val_accuracy: 0.6373
Epoch 4/10
375/375 [==============================] - 8s 22ms/step - loss: 0.9720 - accuracy: 0.6550 - val_loss: 0.9828 - val_accuracy: 0.6512
Epoch 5/10
375/375 [==============================] - 7s 20ms/step - loss: 0.8901 - accuracy: 0.6863 - val_loss: 0.9417 - val_accuracy: 0.6730
Epoch 6/10
375/375 [==============================] - 8s 21ms/step - loss: 0.8032 - accuracy: 0.7159 - val_loss: 0.9126 - val_accuracy: 0.6867
Epoch 7/10
375/375 [==============================] - 7s 19ms/step - loss: 0.7325 - accuracy: 0.7409 - val_loss: 0.9079 - val_accuracy: 0.6900
Epoch 8/10
375/375 [==============================] - 7s 19ms/step - loss: 0.6634 - accuracy: 0.7656 - val_loss: 0.8984 - val_accuracy: 0.6988
Epoch 9/10
375/375 [==============================] - 8s 21ms/step - loss: 0.6047 - accuracy: 0.7859 - val_loss: 0.9004 - val_accuracy: 0.6973
Epoch 10/10
375/375 [==============================] - 7s 19ms/step - loss: 0.5438 - accuracy: 0.8060 - val_loss: 0.9407 - val_accuracy: 0.6963
Epoch 1/10
375/375 [==============================] - 26s 36ms/step - loss: 0.5758 - accuracy: 0.8084 - val_loss: 0.3531 - val_accuracy: 0.8896
Epoch 2/10
375/375 [==============================] - 9s 23ms/step - loss: 0.4648 - accuracy: 0.8417 - val_loss: 0.3335 - val_accuracy: 0.8881
Epoch 3/10
375/375 [==============================] - 9s 25ms/step - loss: 0.3877 - accuracy: 0.8661 - val_loss: 0.3678 - val_accuracy: 0.8735
Epoch 4/10
375/375 [==============================] - 9s 24ms/step - loss: 0.3142 - accuracy: 0.8908 - val_loss: 0.3826 - val_accuracy: 0.8659
Epoch 5/10
375/375 [==============================] - 9s 24ms/step - loss: 0.2719 - accuracy: 0.9031 - val_loss: 0.4481 - val_accuracy: 0.8440
Epoch 6/10
375/375 [==============================] - 9s 24ms/step - loss: 0.2348 - accuracy: 0.9169 - val_loss: 0.4509 - val_accuracy: 0.8480
Epoch 7/10
375/375 [==============================] - 9s 25ms/step - loss: 0.2070 - accuracy: 0.9270 - val_loss: 0.4782 - val_accuracy: 0.8446
Epoch 8/10
375/375 [==============================] - 9s 24ms/step - loss: 0.1833 - accuracy: 0.9352 - val_loss: 0.5335 - val_accuracy: 0.8296
Epoch 9/10
375/375 [==============================] - 8s 23ms/step - loss: 0.1667 - accuracy: 0.9406 - val_loss: 0.5384 - val_accuracy: 0.8341
Epoch 10/10
375/375 [==============================] - 9s 23ms/step - loss: 0.1581 - accuracy: 0.9458 - val_loss: 0.5816 - val_accuracy: 0.8212
375/375 [==============================] - 2s 5ms/step - loss: 0.2981 - accuracy: 0.9124
375/375 [==============================] - 3s 8ms/step - loss: 0.5816 - accuracy: 0.8212
375/375 [==============================] - 2s 5ms/step - loss: 0.2981 - accuracy: 0.9124
Test Accuracy: 0.9124166369438171
Task A Original Accuracy: 91.24%
Task B EWC method Accuracy: 82.12%
Epoch 1/10
375/375 [==============================] - 25s 36ms/step - loss: 0.5755 - accuracy: 0.8083 - val_loss: 0.3324 - val_accuracy: 0.8921
Epoch 2/10
375/375 [==============================] - 9s 24ms/step - loss: 0.4657 - accuracy: 0.8416 - val_loss: 0.3234 - val_accuracy: 0.8921
Epoch 3/10
375/375 [==============================] - 9s 23ms/step - loss: 0.3827 - accuracy: 0.8679 - val_loss: 0.3405 - val_accuracy: 0.8789
Epoch 4/10
375/375 [==============================] - 9s 24ms/step - loss: 0.3202 - accuracy: 0.8886 - val_loss: 0.3692 - val_accuracy: 0.8698
Epoch 5/10
375/375 [==============================] - 9s 25ms/step - loss: 0.2652 - accuracy: 0.9081 - val_loss: 0.4056 - val_accuracy: 0.8587
Epoch 6/10
375/375 [==============================] - 9s 24ms/step - loss: 0.2292 - accuracy: 0.9194 - val_loss: 0.4699 - val_accuracy: 0.8434
Epoch 7/10
375/375 [==============================] - 9s 23ms/step - loss: 0.2009 - accuracy: 0.9298 - val_loss: 0.4724 - val_accuracy: 0.8413
Epoch 8/10
375/375 [==============================] - 8s 20ms/step - loss: 0.1813 - accuracy: 0.9361 - val_loss: 0.5151 - val_accuracy: 0.8333
Epoch 9/10
375/375 [==============================] - 7s 19ms/step - loss: 0.1615 - accuracy: 0.9441 - val_loss: 0.5705 - val_accuracy: 0.8257
Epoch 10/10
375/375 [==============================] - 8s 21ms/step - loss: 0.1523 - accuracy: 0.9478 - val_loss: 0.6111 - val_accuracy: 0.8194
375/375 [==============================] - 2s 4ms/step - loss: 0.2927 - accuracy: 0.9157
375/375 [==============================] - 4s 11ms/step - loss: 0.6111 - accuracy: 0.8194
375/375 [==============================] - 2s 5ms/step - loss: 0.2927 - accuracy: 0.9157
Test Accuracy: 0.9156666398048401
Task A Original Accuracy: 91.57%
Task B EWC method Accuracy: 81.94%
Epoch 1/10
375/375 [==============================] - 19s 27ms/step - loss: 0.5775 - accuracy: 0.8075 - val_loss: 0.3581 - val_accuracy: 0.8839
Epoch 2/10
375/375 [==============================] - 8s 22ms/step - loss: 0.4652 - accuracy: 0.8427 - val_loss: 0.3383 - val_accuracy: 0.8852
Epoch 3/10
375/375 [==============================] - 8s 20ms/step - loss: 0.3836 - accuracy: 0.8683 - val_loss: 0.3449 - val_accuracy: 0.8801
Epoch 4/10
375/375 [==============================] - 8s 20ms/step - loss: 0.3194 - accuracy: 0.8879 - val_loss: 0.3840 - val_accuracy: 0.8607
Epoch 5/10
375/375 [==============================] - 8s 21ms/step - loss: 0.2598 - accuracy: 0.9085 - val_loss: 0.4221 - val_accuracy: 0.8587
Epoch 6/10
375/375 [==============================] - 7s 18ms/step - loss: 0.2397 - accuracy: 0.9162 - val_loss: 0.4956 - val_accuracy: 0.8349
Epoch 7/10
375/375 [==============================] - 8s 20ms/step - loss: 0.1976 - accuracy: 0.9299 - val_loss: 0.4944 - val_accuracy: 0.8393
Epoch 8/10
375/375 [==============================] - 7s 19ms/step - loss: 0.1792 - accuracy: 0.9380 - val_loss: 0.5373 - val_accuracy: 0.8278
Epoch 9/10
375/375 [==============================] - 8s 20ms/step - loss: 0.1662 - accuracy: 0.9434 - val_loss: 0.5608 - val_accuracy: 0.8267
Epoch 10/10
375/375 [==============================] - 7s 19ms/step - loss: 0.1494 - accuracy: 0.9473 - val_loss: 0.6069 - val_accuracy: 0.8260
375/375 [==============================] - 2s 5ms/step - loss: 0.2972 - accuracy: 0.9117
375/375 [==============================] - 3s 7ms/step - loss: 0.6069 - accuracy: 0.8260
375/375 [==============================] - 2s 4ms/step - loss: 0.2972 - accuracy: 0.9117
Test Accuracy: 0.9116666913032532
Task A Original Accuracy: 91.17%
Task B EWC method Accuracy: 82.60%
Epoch 1/10
375/375 [==============================] - 20s 29ms/step - loss: 0.5742 - accuracy: 0.8111 - val_loss: 0.3300 - val_accuracy: 0.8987
Epoch 2/10
375/375 [==============================] - 7s 19ms/step - loss: 0.4630 - accuracy: 0.8426 - val_loss: 0.3314 - val_accuracy: 0.8914
Epoch 3/10
375/375 [==============================] - 8s 21ms/step - loss: 0.3902 - accuracy: 0.8643 - val_loss: 0.3376 - val_accuracy: 0.8865
Epoch 4/10
375/375 [==============================] - 8s 20ms/step - loss: 0.3229 - accuracy: 0.8858 - val_loss: 0.3678 - val_accuracy: 0.8708
Epoch 5/10
375/375 [==============================] - 7s 18ms/step - loss: 0.2706 - accuracy: 0.9062 - val_loss: 0.4115 - val_accuracy: 0.8572
Epoch 6/10
375/375 [==============================] - 8s 22ms/step - loss: 0.2335 - accuracy: 0.9186 - val_loss: 0.4488 - val_accuracy: 0.8457
Epoch 7/10
375/375 [==============================] - 9s 24ms/step - loss: 0.2009 - accuracy: 0.9305 - val_loss: 0.4858 - val_accuracy: 0.8429
Epoch 8/10
375/375 [==============================] - 7s 18ms/step - loss: 0.1885 - accuracy: 0.9331 - val_loss: 0.5094 - val_accuracy: 0.8407
Epoch 9/10
375/375 [==============================] - 8s 22ms/step - loss: 0.1627 - accuracy: 0.9436 - val_loss: 0.5510 - val_accuracy: 0.8314
Epoch 10/10
375/375 [==============================] - 8s 21ms/step - loss: 0.1493 - accuracy: 0.9480 - val_loss: 0.5808 - val_accuracy: 0.8271
375/375 [==============================] - 2s 6ms/step - loss: 0.2886 - accuracy: 0.9147
375/375 [==============================] - 3s 7ms/step - loss: 0.5808 - accuracy: 0.8271
375/375 [==============================] - 2s 5ms/step - loss: 0.2886 - accuracy: 0.9147
Test Accuracy: 0.9147499799728394
Task A Original Accuracy: 91.47%
Task B EWC method Accuracy: 82.71%
Epoch 1/10
375/375 [==============================] - 16s 24ms/step - loss: 0.4010 - accuracy: 0.8566 - val_loss: 1.0162 - val_accuracy: 0.6968
Epoch 2/10
375/375 [==============================] - 7s 18ms/step - loss: 0.3302 - accuracy: 0.8832 - val_loss: 1.0929 - val_accuracy: 0.6928
Epoch 3/10
375/375 [==============================] - 6s 16ms/step - loss: 0.2760 - accuracy: 0.9011 - val_loss: 1.2001 - val_accuracy: 0.6863
Epoch 4/10
375/375 [==============================] - 6s 17ms/step - loss: 0.2439 - accuracy: 0.9138 - val_loss: 1.2344 - val_accuracy: 0.6859
Epoch 5/10
375/375 [==============================] - 6s 16ms/step - loss: 0.2146 - accuracy: 0.9243 - val_loss: 1.3323 - val_accuracy: 0.6835
Epoch 6/10
375/375 [==============================] - 6s 17ms/step - loss: 0.2001 - accuracy: 0.9289 - val_loss: 1.3351 - val_accuracy: 0.6880
Epoch 7/10
375/375 [==============================] - 6s 16ms/step - loss: 0.1707 - accuracy: 0.9399 - val_loss: 1.4133 - val_accuracy: 0.6837
Epoch 8/10
375/375 [==============================] - 6s 17ms/step - loss: 0.1601 - accuracy: 0.9435 - val_loss: 1.4889 - val_accuracy: 0.6834
Epoch 9/10
375/375 [==============================] - 6s 16ms/step - loss: 0.1498 - accuracy: 0.9475 - val_loss: 1.4784 - val_accuracy: 0.6889
Epoch 10/10
375/375 [==============================] - 6s 17ms/step - loss: 0.1422 - accuracy: 0.9500 - val_loss: 1.5083 - val_accuracy: 0.6826
375/375 [==============================] - 1s 3ms/step - loss: 0.9407 - accuracy: 0.6963
375/375 [==============================] - 2s 6ms/step - loss: 1.5083 - accuracy: 0.6826
375/375 [==============================] - 1s 3ms/step - loss: 0.9407 - accuracy: 0.6963
Test Accuracy: 0.6963333487510681
Task A Original Accuracy: 69.63%
Task B EWC method Accuracy: 68.26%
Fold-1: 91.24%
Fold-2: 91.57%
Fold-3: 91.17%
Fold-4: 91.47%
Fold-5: 69.63%

### CIFAR100

In [ ]:
import numpy as np

import numpy as np

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPool2D,Dense,Flatten,Dropout,Input, AveragePooling2D, Activation,Conv2D, MaxPooling2D, BatchNormalization,Concatenate
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
from tensorflow.keras import regularizers, optimizers
from tensorflow.keras.preprocessing.image import ImageDataGenerator

from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers
from tensorflow.keras.regularizers import Regularizer

# Perform hold-out cross-validation
validation_scores = []

# Define the CrlBo regularizer
class CrlBoRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Number of K-folds
K = 5

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)
# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []
num_classes = 100
# Perform K-fold cross-validation
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]

# Task A: Original Fashion MNIST model
    model = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        Conv2D(32, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu'),
        layers.Dropout(0.25),
        Dense(num_classes, activation='softmax')
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model = model
        model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
        model.save_weights('FashionMNIST_A.h5')
        prior_weights = model.get_weights()
# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    fisher_matrix = []
    for i in range(len(model.trainable_weights)):
        fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

    for _ in range(num_samples):
        idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
        with tf.GradientTape() as tape:
            logits = model(x[idx:idx+1])
        gradients = tape.gradient(logits, model.trainable_weights)
        for i in range(len(fisher_matrix)):
            fisher_matrix[i] += tf.square(gradients[i])

    fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
    return fisher_matrix

fisher_matrix = compute_fisher(model, x_train_fold)
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]
# Task B: Fashion MNIST with CrlBo regularization
    model_CrlBoB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3),
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model_CrlBoB = model_CrlBoB
        model_CrlBoB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model_CrlBoB.load_weights('FashionMNIST_A.h5')
        model_CrlBoB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlBo_acc = 100 * model_CrlBoB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlBo method Accuracy: %.2f%%" % B_CrlBo_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
375/375 [==============================] - 16s 25ms/step - loss: 4.8089 - accuracy: 0.0317 - val_loss: 4.0706 - val_accuracy: 0.0841
Epoch 2/10
375/375 [==============================] - 7s 18ms/step - loss: 3.8391 - accuracy: 0.1177 - val_loss: 3.5197 - val_accuracy: 0.1748
Epoch 3/10
375/375 [==============================] - 8s 21ms/step - loss: 3.4499 - accuracy: 0.1808 - val_loss: 3.2168 - val_accuracy: 0.2332
Epoch 4/10
375/375 [==============================] - 7s 19ms/step - loss: 3.1733 - accuracy: 0.2333 - val_loss: 2.9920 - val_accuracy: 0.2748
Epoch 5/10
375/375 [==============================] - 8s 21ms/step - loss: 2.9570 - accuracy: 0.2728 - val_loss: 2.8678 - val_accuracy: 0.2962
Epoch 6/10
375/375 [==============================] - 7s 19ms/step - loss: 2.7621 - accuracy: 0.3095 - val_loss: 2.8313 - val_accuracy: 0.3063
Epoch 7/10
375/375 [==============================] - 7s 20ms/step - loss: 2.5951 - accuracy: 0.3412 - val_loss: 2.6610 - val_accuracy: 0.3343
Epoch 8/10
375/375 [==============================] - 7s 19ms/step - loss: 2.4371 - accuracy: 0.3709 - val_loss: 2.5890 - val_accuracy: 0.3528
Epoch 9/10
375/375 [==============================] - 6s 17ms/step - loss: 2.3027 - accuracy: 0.3989 - val_loss: 2.5362 - val_accuracy: 0.3567
Epoch 10/10
375/375 [==============================] - 7s 18ms/step - loss: 2.1772 - accuracy: 0.4254 - val_loss: 2.5129 - val_accuracy: 0.3685
Epoch 1/10
375/375 [==============================] - 11s 18ms/step - loss: 4.7612 - accuracy: 0.0585 - val_loss: 3.7964 - val_accuracy: 0.1428
Epoch 2/10
375/375 [==============================] - 6s 16ms/step - loss: 3.6513 - accuracy: 0.1514 - val_loss: 3.3772 - val_accuracy: 0.2087
Epoch 3/10
375/375 [==============================] - 6s 17ms/step - loss: 3.2826 - accuracy: 0.2151 - val_loss: 3.1163 - val_accuracy: 0.2531
Epoch 4/10
375/375 [==============================] - 6s 15ms/step - loss: 3.0192 - accuracy: 0.2621 - val_loss: 2.8813 - val_accuracy: 0.2988
Epoch 5/10
375/375 [==============================] - 8s 23ms/step - loss: 2.8095 - accuracy: 0.3003 - val_loss: 2.7370 - val_accuracy: 0.3267
Epoch 6/10
375/375 [==============================] - 7s 19ms/step - loss: 2.6365 - accuracy: 0.3331 - val_loss: 2.7425 - val_accuracy: 0.3282
Epoch 7/10
375/375 [==============================] - 6s 15ms/step - loss: 2.4787 - accuracy: 0.3648 - val_loss: 2.5791 - val_accuracy: 0.3549
Epoch 8/10
375/375 [==============================] - 6s 15ms/step - loss: 2.3458 - accuracy: 0.3936 - val_loss: 2.5260 - val_accuracy: 0.3679
Epoch 9/10
375/375 [==============================] - 6s 16ms/step - loss: 2.2182 - accuracy: 0.4209 - val_loss: 2.4903 - val_accuracy: 0.3778
Epoch 10/10
375/375 [==============================] - 6s 16ms/step - loss: 2.0843 - accuracy: 0.4473 - val_loss: 2.4700 - val_accuracy: 0.3855
Epoch 1/10
375/375 [==============================] - 11s 21ms/step - loss: 4.9035 - accuracy: 0.0350 - val_loss: 4.0552 - val_accuracy: 0.0882
Epoch 2/10
375/375 [==============================] - 7s 18ms/step - loss: 3.8842 - accuracy: 0.1059 - val_loss: 3.6152 - val_accuracy: 0.1626
Epoch 3/10
375/375 [==============================] - 7s 20ms/step - loss: 3.5461 - accuracy: 0.1623 - val_loss: 3.2919 - val_accuracy: 0.2147
Epoch 4/10
375/375 [==============================] - 7s 18ms/step - loss: 3.2627 - accuracy: 0.2121 - val_loss: 3.0792 - val_accuracy: 0.2531
Epoch 5/10
375/375 [==============================] - 8s 21ms/step - loss: 2.9882 - accuracy: 0.2632 - val_loss: 2.8636 - val_accuracy: 0.2975
Epoch 6/10
375/375 [==============================] - 6s 17ms/step - loss: 2.7466 - accuracy: 0.3099 - val_loss: 2.7081 - val_accuracy: 0.3300
Epoch 7/10
375/375 [==============================] - 8s 21ms/step - loss: 2.5508 - accuracy: 0.3531 - val_loss: 2.5808 - val_accuracy: 0.3576
Epoch 8/10
375/375 [==============================] - 7s 18ms/step - loss: 2.3832 - accuracy: 0.3835 - val_loss: 2.4410 - val_accuracy: 0.3835
Epoch 9/10
375/375 [==============================] - 8s 21ms/step - loss: 2.2153 - accuracy: 0.4199 - val_loss: 2.4109 - val_accuracy: 0.3900
Epoch 10/10
375/375 [==============================] - 7s 19ms/step - loss: 2.0695 - accuracy: 0.4503 - val_loss: 2.3738 - val_accuracy: 0.4020
Epoch 1/10
375/375 [==============================] - 14s 22ms/step - loss: 4.8897 - accuracy: 0.0561 - val_loss: 3.8123 - val_accuracy: 0.1232
Epoch 2/10
375/375 [==============================] - 8s 20ms/step - loss: 3.6785 - accuracy: 0.1442 - val_loss: 3.3887 - val_accuracy: 0.1998
Epoch 3/10
375/375 [==============================] - 7s 19ms/step - loss: 3.3411 - accuracy: 0.2034 - val_loss: 3.0667 - val_accuracy: 0.2644
Epoch 4/10
375/375 [==============================] - 7s 18ms/step - loss: 3.0362 - accuracy: 0.2576 - val_loss: 2.7991 - val_accuracy: 0.3103
Epoch 5/10
375/375 [==============================] - 8s 21ms/step - loss: 2.7996 - accuracy: 0.2977 - val_loss: 2.6730 - val_accuracy: 0.3321
Epoch 6/10
375/375 [==============================] - 7s 19ms/step - loss: 2.5873 - accuracy: 0.3447 - val_loss: 2.6311 - val_accuracy: 0.3358
Epoch 7/10
375/375 [==============================] - 7s 18ms/step - loss: 2.4377 - accuracy: 0.3722 - val_loss: 2.5563 - val_accuracy: 0.3604
Epoch 8/10
375/375 [==============================] - 7s 19ms/step - loss: 2.2742 - accuracy: 0.4075 - val_loss: 2.4337 - val_accuracy: 0.3799
Epoch 9/10
375/375 [==============================] - 7s 20ms/step - loss: 2.1433 - accuracy: 0.4327 - val_loss: 2.3655 - val_accuracy: 0.3944
Epoch 10/10
375/375 [==============================] - 7s 19ms/step - loss: 2.0015 - accuracy: 0.4648 - val_loss: 2.3591 - val_accuracy: 0.4043
Epoch 1/10
375/375 [==============================] - 13s 23ms/step - loss: 4.3919 - accuracy: 0.0760 - val_loss: 3.5613 - val_accuracy: 0.1652
Epoch 2/10
375/375 [==============================] - 7s 18ms/step - loss: 3.4276 - accuracy: 0.1856 - val_loss: 3.0938 - val_accuracy: 0.2538
Epoch 3/10
375/375 [==============================] - 8s 20ms/step - loss: 3.0442 - accuracy: 0.2571 - val_loss: 2.9036 - val_accuracy: 0.2838
Epoch 4/10
375/375 [==============================] - 7s 19ms/step - loss: 2.7773 - accuracy: 0.3077 - val_loss: 2.7105 - val_accuracy: 0.3265
Epoch 5/10
375/375 [==============================] - 8s 20ms/step - loss: 2.5712 - accuracy: 0.3447 - val_loss: 2.6036 - val_accuracy: 0.3396
Epoch 6/10
375/375 [==============================] - 8s 21ms/step - loss: 2.4028 - accuracy: 0.3827 - val_loss: 2.5124 - val_accuracy: 0.3613
Epoch 7/10
375/375 [==============================] - 8s 20ms/step - loss: 2.2570 - accuracy: 0.4129 - val_loss: 2.4713 - val_accuracy: 0.3771
Epoch 8/10
375/375 [==============================] - 7s 19ms/step - loss: 2.1017 - accuracy: 0.4456 - val_loss: 2.4250 - val_accuracy: 0.3870
Epoch 9/10
375/375 [==============================] - 7s 19ms/step - loss: 1.9544 - accuracy: 0.4750 - val_loss: 2.4276 - val_accuracy: 0.3988
Epoch 10/10
375/375 [==============================] - 8s 20ms/step - loss: 1.8451 - accuracy: 0.4995 - val_loss: 2.4619 - val_accuracy: 0.3916
Epoch 1/10
375/375 [==============================] - 26s 32ms/step - loss: 1.7869 - accuracy: 0.5311 - val_loss: 1.2956 - val_accuracy: 0.6503
Epoch 2/10
375/375 [==============================] - 9s 24ms/step - loss: 1.5282 - accuracy: 0.5856 - val_loss: 1.3760 - val_accuracy: 0.6214
Epoch 3/10
375/375 [==============================] - 8s 21ms/step - loss: 1.3165 - accuracy: 0.6327 - val_loss: 1.5139 - val_accuracy: 0.5848
Epoch 4/10
375/375 [==============================] - 8s 23ms/step - loss: 1.1254 - accuracy: 0.6745 - val_loss: 1.6148 - val_accuracy: 0.5626
Epoch 5/10
375/375 [==============================] - 9s 24ms/step - loss: 0.9904 - accuracy: 0.7107 - val_loss: 1.6557 - val_accuracy: 0.5667
Epoch 6/10
375/375 [==============================] - 8s 21ms/step - loss: 0.8669 - accuracy: 0.7434 - val_loss: 1.9223 - val_accuracy: 0.5250
Epoch 7/10
375/375 [==============================] - 9s 24ms/step - loss: 0.7767 - accuracy: 0.7675 - val_loss: 2.0593 - val_accuracy: 0.5182
Epoch 8/10
375/375 [==============================] - 9s 24ms/step - loss: 0.7058 - accuracy: 0.7866 - val_loss: 2.3281 - val_accuracy: 0.4888
Epoch 9/10
375/375 [==============================] - 8s 23ms/step - loss: 0.6421 - accuracy: 0.8063 - val_loss: 2.3215 - val_accuracy: 0.4941
Epoch 10/10
375/375 [==============================] - 9s 23ms/step - loss: 0.6101 - accuracy: 0.8159 - val_loss: 2.4167 - val_accuracy: 0.4978
375/375 [==============================] - 2s 4ms/step - loss: 1.2645 - accuracy: 0.6783
375/375 [==============================] - 3s 7ms/step - loss: 2.4167 - accuracy: 0.4978
375/375 [==============================] - 2s 4ms/step - loss: 1.2645 - accuracy: 0.6783
Test Accuracy: 0.6782500147819519
Task A Original Accuracy: 67.83%
Task B CrlBo method Accuracy: 49.78%
Epoch 1/10
375/375 [==============================] - 18s 25ms/step - loss: 1.7928 - accuracy: 0.5295 - val_loss: 1.3018 - val_accuracy: 0.6547
Epoch 2/10
375/375 [==============================] - 7s 18ms/step - loss: 1.5188 - accuracy: 0.5877 - val_loss: 1.4299 - val_accuracy: 0.5993
Epoch 3/10
375/375 [==============================] - 7s 18ms/step - loss: 1.3141 - accuracy: 0.6324 - val_loss: 1.4533 - val_accuracy: 0.5988
Epoch 4/10
375/375 [==============================] - 7s 18ms/step - loss: 1.1377 - accuracy: 0.6733 - val_loss: 1.6652 - val_accuracy: 0.5522
Epoch 5/10
375/375 [==============================] - 6s 16ms/step - loss: 0.9860 - accuracy: 0.7108 - val_loss: 1.7249 - val_accuracy: 0.5503
Epoch 6/10
375/375 [==============================] - 6s 16ms/step - loss: 0.8776 - accuracy: 0.7423 - val_loss: 1.8296 - val_accuracy: 0.5422
Epoch 7/10
375/375 [==============================] - 7s 18ms/step - loss: 0.8035 - accuracy: 0.7606 - val_loss: 1.9639 - val_accuracy: 0.5255
Epoch 8/10
375/375 [==============================] - 6s 16ms/step - loss: 0.7102 - accuracy: 0.7861 - val_loss: 2.1965 - val_accuracy: 0.5192
Epoch 9/10
375/375 [==============================] - 6s 16ms/step - loss: 0.6534 - accuracy: 0.8019 - val_loss: 2.2360 - val_accuracy: 0.5088
Epoch 10/10
375/375 [==============================] - 6s 16ms/step - loss: 0.6142 - accuracy: 0.8149 - val_loss: 2.4312 - val_accuracy: 0.4913
375/375 [==============================] - 1s 3ms/step - loss: 1.2475 - accuracy: 0.6812
375/375 [==============================] - 2s 6ms/step - loss: 2.4312 - accuracy: 0.4913
375/375 [==============================] - 1s 3ms/step - loss: 1.2475 - accuracy: 0.6812
Test Accuracy: 0.6812499761581421
Task A Original Accuracy: 68.12%
Task B CrlBo method Accuracy: 49.13%
Epoch 1/10
375/375 [==============================] - 13s 20ms/step - loss: 1.7873 - accuracy: 0.5304 - val_loss: 1.3417 - val_accuracy: 0.6340
Epoch 2/10
375/375 [==============================] - 6s 16ms/step - loss: 1.5378 - accuracy: 0.5825 - val_loss: 1.3819 - val_accuracy: 0.6166
Epoch 3/10
375/375 [==============================] - 6s 17ms/step - loss: 1.3088 - accuracy: 0.6325 - val_loss: 1.4970 - val_accuracy: 0.5899
Epoch 4/10
375/375 [==============================] - 6s 16ms/step - loss: 1.1442 - accuracy: 0.6726 - val_loss: 1.5786 - val_accuracy: 0.5678
Epoch 5/10
375/375 [==============================] - 6s 16ms/step - loss: 0.9977 - accuracy: 0.7082 - val_loss: 1.7456 - val_accuracy: 0.5467
Epoch 6/10
375/375 [==============================] - 6s 16ms/step - loss: 0.8645 - accuracy: 0.7433 - val_loss: 1.8823 - val_accuracy: 0.5319
Epoch 7/10
375/375 [==============================] - 6s 16ms/step - loss: 0.8031 - accuracy: 0.7605 - val_loss: 1.9867 - val_accuracy: 0.5173
Epoch 8/10
375/375 [==============================] - 6s 16ms/step - loss: 0.7094 - accuracy: 0.7850 - val_loss: 2.1875 - val_accuracy: 0.4996
Epoch 9/10
375/375 [==============================] - 6s 16ms/step - loss: 0.6626 - accuracy: 0.7996 - val_loss: 2.2964 - val_accuracy: 0.5033
Epoch 10/10
375/375 [==============================] - 6s 16ms/step - loss: 0.6147 - accuracy: 0.8117 - val_loss: 2.4006 - val_accuracy: 0.4978
375/375 [==============================] - 1s 3ms/step - loss: 1.2504 - accuracy: 0.6767
375/375 [==============================] - 2s 6ms/step - loss: 2.4006 - accuracy: 0.4978
375/375 [==============================] - 2s 4ms/step - loss: 1.2504 - accuracy: 0.6767
Test Accuracy: 0.6766666769981384
Task A Original Accuracy: 67.67%
Task B CrlBo method Accuracy: 49.78%
Epoch 1/10
375/375 [==============================] - 13s 22ms/step - loss: 1.7991 - accuracy: 0.5266 - val_loss: 1.3035 - val_accuracy: 0.6592
Epoch 2/10
375/375 [==============================] - 6s 16ms/step - loss: 1.5258 - accuracy: 0.5835 - val_loss: 1.3530 - val_accuracy: 0.6261
Epoch 3/10
375/375 [==============================] - 6s 16ms/step - loss: 1.3061 - accuracy: 0.6334 - val_loss: 1.4477 - val_accuracy: 0.5922
Epoch 4/10
375/375 [==============================] - 6s 16ms/step - loss: 1.1409 - accuracy: 0.6744 - val_loss: 1.5610 - val_accuracy: 0.5701
Epoch 5/10
375/375 [==============================] - 6s 16ms/step - loss: 0.9880 - accuracy: 0.7098 - val_loss: 1.7306 - val_accuracy: 0.5468
Epoch 6/10
375/375 [==============================] - 6s 16ms/step - loss: 0.8661 - accuracy: 0.7449 - val_loss: 1.9177 - val_accuracy: 0.5215
Epoch 7/10
375/375 [==============================] - 6s 16ms/step - loss: 0.7781 - accuracy: 0.7655 - val_loss: 2.0301 - val_accuracy: 0.5158
Epoch 8/10
375/375 [==============================] - 6s 16ms/step - loss: 0.7166 - accuracy: 0.7849 - val_loss: 2.1296 - val_accuracy: 0.5047
Epoch 9/10
375/375 [==============================] - 6s 16ms/step - loss: 0.6405 - accuracy: 0.8065 - val_loss: 2.2728 - val_accuracy: 0.4958
Epoch 10/10
375/375 [==============================] - 6s 16ms/step - loss: 0.5898 - accuracy: 0.8213 - val_loss: 2.3995 - val_accuracy: 0.4942
375/375 [==============================] - 1s 3ms/step - loss: 1.2550 - accuracy: 0.6788
375/375 [==============================] - 2s 6ms/step - loss: 2.3995 - accuracy: 0.4942
375/375 [==============================] - 2s 4ms/step - loss: 1.2550 - accuracy: 0.6788
Test Accuracy: 0.6788333058357239
Task A Original Accuracy: 67.88%
Task B CrlBo method Accuracy: 49.42%
Epoch 1/10
375/375 [==============================] - 13s 21ms/step - loss: 1.4608 - accuracy: 0.5915 - val_loss: 2.5669 - val_accuracy: 0.3941
Epoch 2/10
375/375 [==============================] - 6s 16ms/step - loss: 1.2551 - accuracy: 0.6440 - val_loss: 2.6783 - val_accuracy: 0.3982
Epoch 3/10
375/375 [==============================] - 6s 16ms/step - loss: 1.1027 - accuracy: 0.6814 - val_loss: 2.8195 - val_accuracy: 0.3873
Epoch 4/10
375/375 [==============================] - 6s 16ms/step - loss: 0.9710 - accuracy: 0.7158 - val_loss: 2.9499 - val_accuracy: 0.3811
Epoch 5/10
375/375 [==============================] - 6s 16ms/step - loss: 0.8772 - accuracy: 0.7389 - val_loss: 3.1140 - val_accuracy: 0.3785
Epoch 6/10
375/375 [==============================] - 6s 16ms/step - loss: 0.7793 - accuracy: 0.7660 - val_loss: 3.1576 - val_accuracy: 0.3793
Epoch 7/10
375/375 [==============================] - 6s 17ms/step - loss: 0.7307 - accuracy: 0.7807 - val_loss: 3.2885 - val_accuracy: 0.3825
Epoch 8/10
375/375 [==============================] - 6s 16ms/step - loss: 0.6508 - accuracy: 0.8018 - val_loss: 3.6468 - val_accuracy: 0.3709
Epoch 9/10
375/375 [==============================] - 6s 16ms/step - loss: 0.6100 - accuracy: 0.8157 - val_loss: 3.6952 - val_accuracy: 0.3742
Epoch 10/10
375/375 [==============================] - 6s 16ms/step - loss: 0.5777 - accuracy: 0.8231 - val_loss: 3.8006 - val_accuracy: 0.3752
375/375 [==============================] - 1s 3ms/step - loss: 2.4619 - accuracy: 0.3916
375/375 [==============================] - 2s 6ms/step - loss: 3.8006 - accuracy: 0.3752
375/375 [==============================] - 1s 3ms/step - loss: 2.4619 - accuracy: 0.3916
Test Accuracy: 0.39158332347869873
Task A Original Accuracy: 39.16%
Task B CrlBo method Accuracy: 37.52%
Fold-1: 67.83%
Fold-2: 68.12%
Fold-3: 67.67%
Fold-4: 67.88%
Fold-5: 39.16%

### CIFAR100-C

In [ ]:
import numpy as np
# from tensorflow.keras.datasets import cifar100
import numpy as np
# Importing the necessary libraries, which we may or may not use. Its always good idea to import them befor (if you remember) else we can do it at any point of time no problem.
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPool2D,Dense,Flatten,Dropout,Input, AveragePooling2D, Activation,Conv2D, MaxPooling2D, BatchNormalization,Concatenate
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
from tensorflow.keras import regularizers, optimizers
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.datasets import cifar100
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers
from tensorflow.keras.regularizers import Regularizer

# Perform hold-out cross-validation
validation_scores = []

# Define the CrlB regularizer
class CrlBRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Number of K-folds
K = 5

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)
# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []
num_classes = 100
# Perform K-fold cross-validation
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]

# Task A: Original Fashion MNIST model
    model = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        Conv2D(32, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same'),

        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu'),
        layers.Dropout(0.25),
        Dense(num_classes, activation='softmax')
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model = model
        model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model.fit(x_train_fold, y_train_fold, batch_size=32, epochs=10, validation_data=(x_test_fold, y_test_fold))
        model.save_weights('FashionMNIST_A.h5')
        prior_weights = model.get_weights()
# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]


# Compute the Fisher Information matrix
    def compute_fisher(model, x, num_samples=30):
        fisher_matrix = []
        for i in range(len(model.trainable_weights)):
            fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

        for _ in range(num_samples):
            idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
            with tf.GradientTape() as tape:
                logits = model(x[idx:idx+1])
            gradients = tape.gradient(logits, model.trainable_weights)
            for i in range(len(fisher_matrix)):
                fisher_matrix[i] += tf.square(gradients[i])

        fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
        return fisher_matrix

    fisher_matrix = compute_fisher(model, x_train_fold)

# Task B: Fashion MNIST with CrlB regularization
    model_CrlBB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3),
               kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),

        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model_CrlBB = model_CrlBB
        model_CrlBB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model_CrlBB.load_weights('FashionMNIST_A.h5')
        model_CrlBB.fit( x_train_fold, y_train_fold, batch_size=32, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlB_acc = 100 * model_CrlBB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlB method Accuracy: %.2f%%" % B_CrlB_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)
      # Print the fold accuracies
    for i, score in enumerate(accuracies):
        percent = score * 100
        print("Fold-{}: {:.2f}%".format(i+1, percent))
# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
1500/1500 [==============================] - 27s 7ms/step - loss: 4.3653 - accuracy: 0.0582 - val_loss: 3.8654 - val_accuracy: 0.1081
Epoch 2/10
1500/1500 [==============================] - 12s 8ms/step - loss: 3.7651 - accuracy: 0.1269 - val_loss: 3.6025 - val_accuracy: 0.1584
Epoch 3/10
1500/1500 [==============================] - 11s 7ms/step - loss: 3.5485 - accuracy: 0.1660 - val_loss: 3.4030 - val_accuracy: 0.1885
Epoch 4/10
1500/1500 [==============================] - 12s 8ms/step - loss: 3.3689 - accuracy: 0.1981 - val_loss: 3.3390 - val_accuracy: 0.2067
Epoch 5/10
1500/1500 [==============================] - 12s 8ms/step - loss: 3.2231 - accuracy: 0.2261 - val_loss: 3.1837 - val_accuracy: 0.2345
Epoch 6/10
1500/1500 [==============================] - 12s 8ms/step - loss: 3.0665 - accuracy: 0.2548 - val_loss: 3.1566 - val_accuracy: 0.2441
Epoch 7/10
1500/1500 [==============================] - 11s 7ms/step - loss: 2.9217 - accuracy: 0.2803 - val_loss: 3.0582 - val_accuracy: 0.2608
Epoch 8/10
1500/1500 [==============================] - 11s 7ms/step - loss: 2.7738 - accuracy: 0.3096 - val_loss: 3.0042 - val_accuracy: 0.2717
Epoch 9/10
1500/1500 [==============================] - 12s 8ms/step - loss: 2.6379 - accuracy: 0.3364 - val_loss: 3.0291 - val_accuracy: 0.2718
Epoch 10/10
1500/1500 [==============================] - 13s 8ms/step - loss: 2.5183 - accuracy: 0.3632 - val_loss: 2.9959 - val_accuracy: 0.2782
Epoch 1/10
1500/1500 [==============================] - 22s 11ms/step - loss: 2.1556 - accuracy: 0.4460 - val_loss: 3.0292 - val_accuracy: 0.2822
Epoch 2/10
1500/1500 [==============================] - 13s 9ms/step - loss: 1.9421 - accuracy: 0.4929 - val_loss: 3.2124 - val_accuracy: 0.2737
Epoch 3/10
1500/1500 [==============================] - 14s 10ms/step - loss: 1.7720 - accuracy: 0.5338 - val_loss: 3.3864 - val_accuracy: 0.2738
Epoch 4/10
1500/1500 [==============================] - 14s 9ms/step - loss: 1.6303 - accuracy: 0.5691 - val_loss: 3.4656 - val_accuracy: 0.2698
Epoch 5/10
1500/1500 [==============================] - 15s 10ms/step - loss: 1.4914 - accuracy: 0.6035 - val_loss: 3.5561 - val_accuracy: 0.2677
Epoch 6/10
1500/1500 [==============================] - 14s 9ms/step - loss: 1.3892 - accuracy: 0.6289 - val_loss: 3.7773 - val_accuracy: 0.2614
Epoch 7/10
1500/1500 [==============================] - 14s 10ms/step - loss: 1.3004 - accuracy: 0.6526 - val_loss: 3.9321 - val_accuracy: 0.2572
Epoch 8/10
1500/1500 [==============================] - 15s 10ms/step - loss: 1.2421 - accuracy: 0.6665 - val_loss: 4.0482 - val_accuracy: 0.2646
Epoch 9/10
1500/1500 [==============================] - 14s 10ms/step - loss: 1.1806 - accuracy: 0.6847 - val_loss: 4.2383 - val_accuracy: 0.2569
Epoch 10/10
1500/1500 [==============================] - 15s 10ms/step - loss: 1.1287 - accuracy: 0.6978 - val_loss: 4.2824 - val_accuracy: 0.2631
375/375 [==============================] - 1s 4ms/step - loss: 2.9959 - accuracy: 0.2782
375/375 [==============================] - 3s 7ms/step - loss: 4.2824 - accuracy: 0.2631
375/375 [==============================] - 1s 4ms/step - loss: 2.9959 - accuracy: 0.2782
Test Accuracy: 0.27816668152809143
Task A Original Accuracy: 27.82%
Task B CrlB method Accuracy: 26.31%
Fold-1: 27.82%
Epoch 1/10
1500/1500 [==============================] - 15s 8ms/step - loss: 4.4547 - accuracy: 0.0376 - val_loss: 3.9845 - val_accuracy: 0.0889
Epoch 2/10
1500/1500 [==============================] - 12s 8ms/step - loss: 3.8715 - accuracy: 0.1058 - val_loss: 3.7030 - val_accuracy: 0.1382
Epoch 3/10
1500/1500 [==============================] - 12s 8ms/step - loss: 3.6548 - accuracy: 0.1390 - val_loss: 3.5255 - val_accuracy: 0.1680
Epoch 4/10
1500/1500 [==============================] - 11s 8ms/step - loss: 3.5239 - accuracy: 0.1631 - val_loss: 3.4254 - val_accuracy: 0.1883
Epoch 5/10
1500/1500 [==============================] - 11s 8ms/step - loss: 3.4050 - accuracy: 0.1848 - val_loss: 3.3179 - val_accuracy: 0.2058
Epoch 6/10
1500/1500 [==============================] - 12s 8ms/step - loss: 3.3002 - accuracy: 0.2042 - val_loss: 3.2413 - val_accuracy: 0.2193
Epoch 7/10
1500/1500 [==============================] - 11s 8ms/step - loss: 3.2113 - accuracy: 0.2201 - val_loss: 3.2345 - val_accuracy: 0.2272
Epoch 8/10
1500/1500 [==============================] - 11s 7ms/step - loss: 3.1354 - accuracy: 0.2330 - val_loss: 3.1413 - val_accuracy: 0.2381
Epoch 9/10
1500/1500 [==============================] - 11s 7ms/step - loss: 3.0612 - accuracy: 0.2459 - val_loss: 3.1452 - val_accuracy: 0.2397
Epoch 10/10
1500/1500 [==============================] - 11s 7ms/step - loss: 2.9923 - accuracy: 0.2604 - val_loss: 3.1174 - val_accuracy: 0.2481
Epoch 1/10
1500/1500 [==============================] - 21s 10ms/step - loss: 2.7205 - accuracy: 0.3155 - val_loss: 3.0487 - val_accuracy: 0.2585
Epoch 2/10
1500/1500 [==============================] - 14s 9ms/step - loss: 2.5912 - accuracy: 0.3420 - val_loss: 3.0610 - val_accuracy: 0.2577
Epoch 3/10
1500/1500 [==============================] - 14s 9ms/step - loss: 2.4808 - accuracy: 0.3669 - val_loss: 3.0757 - val_accuracy: 0.2562
Epoch 4/10
1500/1500 [==============================] - 15s 10ms/step - loss: 2.3888 - accuracy: 0.3830 - val_loss: 3.1389 - val_accuracy: 0.2578
Epoch 5/10
1500/1500 [==============================] - 15s 10ms/step - loss: 2.2798 - accuracy: 0.4078 - val_loss: 3.1138 - val_accuracy: 0.2630
Epoch 6/10
1500/1500 [==============================] - 15s 10ms/step - loss: 2.1986 - accuracy: 0.4227 - val_loss: 3.1922 - val_accuracy: 0.2628
Epoch 7/10
1500/1500 [==============================] - 14s 9ms/step - loss: 2.1125 - accuracy: 0.4433 - val_loss: 3.1936 - val_accuracy: 0.2657
Epoch 8/10
1500/1500 [==============================] - 15s 10ms/step - loss: 2.0167 - accuracy: 0.4637 - val_loss: 3.2586 - val_accuracy: 0.2573
Epoch 9/10
1500/1500 [==============================] - 14s 9ms/step - loss: 1.9326 - accuracy: 0.4854 - val_loss: 3.2689 - val_accuracy: 0.2642
Epoch 10/10
1500/1500 [==============================] - 15s 10ms/step - loss: 1.8553 - accuracy: 0.5002 - val_loss: 3.3535 - val_accuracy: 0.2619
375/375 [==============================] - 1s 4ms/step - loss: 3.1174 - accuracy: 0.2481
375/375 [==============================] - 2s 6ms/step - loss: 3.3535 - accuracy: 0.2619
375/375 [==============================] - 1s 4ms/step - loss: 3.1174 - accuracy: 0.2481
Test Accuracy: 0.24808333814144135
Task A Original Accuracy: 24.81%
Task B CrlB method Accuracy: 26.19%
Fold-1: 27.82%
Fold-2: 24.81%
Epoch 1/10
1500/1500 [==============================] - 12s 6ms/step - loss: 4.5352 - accuracy: 0.0443 - val_loss: 3.9440 - val_accuracy: 0.0993
Epoch 2/10
1500/1500 [==============================] - 8s 5ms/step - loss: 3.8472 - accuracy: 0.1145 - val_loss: 3.6869 - val_accuracy: 0.1440
Epoch 3/10
1500/1500 [==============================] - 9s 6ms/step - loss: 3.6259 - accuracy: 0.1533 - val_loss: 3.5337 - val_accuracy: 0.1768
Epoch 4/10
1500/1500 [==============================] - 8s 5ms/step - loss: 3.4689 - accuracy: 0.1772 - val_loss: 3.3840 - val_accuracy: 0.2030
Epoch 5/10
1500/1500 [==============================] - 8s 5ms/step - loss: 3.3320 - accuracy: 0.2043 - val_loss: 3.2700 - val_accuracy: 0.2227
Epoch 6/10
1500/1500 [==============================] - 8s 5ms/step - loss: 3.2019 - accuracy: 0.2271 - val_loss: 3.1707 - val_accuracy: 0.2393
Epoch 7/10
1500/1500 [==============================] - 8s 5ms/step - loss: 3.0793 - accuracy: 0.2528 - val_loss: 3.1043 - val_accuracy: 0.2515
Epoch 8/10
1500/1500 [==============================] - 8s 6ms/step - loss: 2.9618 - accuracy: 0.2749 - val_loss: 3.0536 - val_accuracy: 0.2654
Epoch 9/10
1500/1500 [==============================] - 9s 6ms/step - loss: 2.8392 - accuracy: 0.3026 - val_loss: 3.0758 - val_accuracy: 0.2619
Epoch 10/10
1500/1500 [==============================] - 8s 5ms/step - loss: 2.7172 - accuracy: 0.3224 - val_loss: 3.0399 - val_accuracy: 0.2706
Epoch 1/10
1500/1500 [==============================] - 18s 9ms/step - loss: 2.3942 - accuracy: 0.3959 - val_loss: 3.0792 - val_accuracy: 0.2712
Epoch 2/10
1500/1500 [==============================] - 12s 8ms/step - loss: 2.2012 - accuracy: 0.4378 - val_loss: 3.1456 - val_accuracy: 0.2673
Epoch 3/10
1500/1500 [==============================] - 12s 8ms/step - loss: 2.0270 - accuracy: 0.4786 - val_loss: 3.2350 - val_accuracy: 0.2654
Epoch 4/10
1500/1500 [==============================] - 11s 7ms/step - loss: 1.8760 - accuracy: 0.5180 - val_loss: 3.3499 - val_accuracy: 0.2709
Epoch 5/10
1500/1500 [==============================] - 11s 7ms/step - loss: 1.7471 - accuracy: 0.5466 - val_loss: 3.4268 - val_accuracy: 0.2656
Epoch 6/10
1500/1500 [==============================] - 11s 7ms/step - loss: 1.6153 - accuracy: 0.5778 - val_loss: 3.5923 - val_accuracy: 0.2623
Epoch 7/10
1500/1500 [==============================] - 12s 8ms/step - loss: 1.5379 - accuracy: 0.6015 - val_loss: 3.6775 - val_accuracy: 0.2618
Epoch 8/10
1500/1500 [==============================] - 11s 7ms/step - loss: 1.4477 - accuracy: 0.6246 - val_loss: 3.8637 - val_accuracy: 0.2583
Epoch 9/10
1500/1500 [==============================] - 11s 7ms/step - loss: 1.4056 - accuracy: 0.6394 - val_loss: 3.9139 - val_accuracy: 0.2512
Epoch 10/10
1500/1500 [==============================] - 11s 7ms/step - loss: 1.3312 - accuracy: 0.6588 - val_loss: 4.1577 - val_accuracy: 0.2593

### SVHN

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPool2D,Dense,Flatten,Dropout,Input, AveragePooling2D, Activation,Conv2D, MaxPooling2D, BatchNormalization,Concatenate
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
from tensorflow.keras import regularizers, optimizers
from tensorflow.keras.preprocessing.image import ImageDataGenerator

from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers
from tensorflow.keras.regularizers import Regularizer

# Perform hold-out cross-validation
validation_scores = []

# Define the CrlBo regularizer
class CrlBoRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Number of K-folds
K = 5

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)
# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []
num_classes = 10
# Perform K-fold cross-validation
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]

# Task A: Original SVHN model
    model = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        Conv2D(32, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu'),
        layers.Dropout(0.25),
        Dense(num_classes, activation='softmax')
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model = model
        model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
        model.save_weights('FashionMNIST_A.h5')
        prior_weights = model.get_weights()
# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    fisher_matrix = []
    for i in range(len(model.trainable_weights)):
        fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

    for _ in range(num_samples):
        idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
        with tf.GradientTape() as tape:
            logits = model(x[idx:idx+1])
        gradients = tape.gradient(logits, model.trainable_weights)
        for i in range(len(fisher_matrix)):
            fisher_matrix[i] += tf.square(gradients[i])

    fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
    return fisher_matrix

fisher_matrix = compute_fisher(model, x_train_fold)
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]
# Task B: Fashion SVHN with CrlBo regularization
    model_CrlBoB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3),
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model_CrlBoB = model_CrlBoB
        model_CrlBoB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model_CrlBoB.load_weights('FashionMNIST_A.h5')
        model_CrlBoB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlBo_acc = 100 * model_CrlBoB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlBo method Accuracy: %.2f%%" % B_CrlBo_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
621/621 [==============================] - 20s 23ms/step - loss: 2.2109 - accuracy: 0.4465 - val_loss: 0.7688 - val_accuracy: 0.7743
Epoch 2/10
621/621 [==============================] - 12s 19ms/step - loss: 0.7338 - accuracy: 0.7732 - val_loss: 0.4641 - val_accuracy: 0.8683
Epoch 3/10
621/621 [==============================] - 12s 19ms/step - loss: 0.5344 - accuracy: 0.8360 - val_loss: 0.3578 - val_accuracy: 0.8995
Epoch 4/10
621/621 [==============================] - 12s 20ms/step - loss: 0.4469 - accuracy: 0.8649 - val_loss: 0.3235 - val_accuracy: 0.9076
Epoch 5/10
621/621 [==============================] - 12s 19ms/step - loss: 0.3901 - accuracy: 0.8821 - val_loss: 0.2992 - val_accuracy: 0.9163
Epoch 6/10
621/621 [==============================] - 12s 20ms/step - loss: 0.3521 - accuracy: 0.8952 - val_loss: 0.2772 - val_accuracy: 0.9229
Epoch 7/10
621/621 [==============================] - 13s 20ms/step - loss: 0.3219 - accuracy: 0.9029 - val_loss: 0.2647 - val_accuracy: 0.9243
Epoch 8/10
621/621 [==============================] - 12s 20ms/step - loss: 0.3031 - accuracy: 0.9085 - val_loss: 0.2697 - val_accuracy: 0.9253
Epoch 9/10
621/621 [==============================] - 12s 19ms/step - loss: 0.2817 - accuracy: 0.9158 - val_loss: 0.2590 - val_accuracy: 0.9277
Epoch 10/10
621/621 [==============================] - 12s 20ms/step - loss: 0.2714 - accuracy: 0.9181 - val_loss: 0.2791 - val_accuracy: 0.9200
Epoch 1/10
621/621 [==============================] - 18s 21ms/step - loss: 2.5764 - accuracy: 0.2154 - val_loss: 1.3330 - val_accuracy: 0.5752
Epoch 2/10
621/621 [==============================] - 12s 19ms/step - loss: 0.8822 - accuracy: 0.7254 - val_loss: 0.5101 - val_accuracy: 0.8501
Epoch 3/10
621/621 [==============================] - 12s 19ms/step - loss: 0.5562 - accuracy: 0.8308 - val_loss: 0.3673 - val_accuracy: 0.8970
Epoch 4/10
621/621 [==============================] - 11s 18ms/step - loss: 0.4549 - accuracy: 0.8634 - val_loss: 0.3219 - val_accuracy: 0.9095
Epoch 5/10
621/621 [==============================] - 12s 19ms/step - loss: 0.3997 - accuracy: 0.8791 - val_loss: 0.3123 - val_accuracy: 0.9124
Epoch 6/10
621/621 [==============================] - 12s 20ms/step - loss: 0.3632 - accuracy: 0.8915 - val_loss: 0.2907 - val_accuracy: 0.9179
Epoch 7/10
621/621 [==============================] - 12s 19ms/step - loss: 0.3294 - accuracy: 0.9006 - val_loss: 0.2759 - val_accuracy: 0.9218
Epoch 8/10
621/621 [==============================] - 12s 19ms/step - loss: 0.3024 - accuracy: 0.9086 - val_loss: 0.2639 - val_accuracy: 0.9273
Epoch 9/10
621/621 [==============================] - 12s 19ms/step - loss: 0.2797 - accuracy: 0.9165 - val_loss: 0.2592 - val_accuracy: 0.9270
Epoch 10/10
621/621 [==============================] - 13s 20ms/step - loss: 0.2614 - accuracy: 0.9211 - val_loss: 0.2505 - val_accuracy: 0.9326
Epoch 1/10
621/621 [==============================] - 18s 21ms/step - loss: 1.6399 - accuracy: 0.5531 - val_loss: 0.5399 - val_accuracy: 0.8501
Epoch 2/10
621/621 [==============================] - 12s 20ms/step - loss: 0.5746 - accuracy: 0.8274 - val_loss: 0.4037 - val_accuracy: 0.8849
Epoch 3/10
621/621 [==============================] - 12s 20ms/step - loss: 0.4460 - accuracy: 0.8670 - val_loss: 0.3227 - val_accuracy: 0.9090
Epoch 4/10
621/621 [==============================] - 12s 19ms/step - loss: 0.3772 - accuracy: 0.8877 - val_loss: 0.3085 - val_accuracy: 0.9107
Epoch 5/10
621/621 [==============================] - 12s 19ms/step - loss: 0.3346 - accuracy: 0.9008 - val_loss: 0.2727 - val_accuracy: 0.9216
Epoch 6/10
621/621 [==============================] - 12s 19ms/step - loss: 0.2985 - accuracy: 0.9116 - val_loss: 0.2783 - val_accuracy: 0.9217
Epoch 7/10
621/621 [==============================] - 12s 20ms/step - loss: 0.2785 - accuracy: 0.9170 - val_loss: 0.2631 - val_accuracy: 0.9278
Epoch 8/10
621/621 [==============================] - 13s 21ms/step - loss: 0.2588 - accuracy: 0.9215 - val_loss: 0.2501 - val_accuracy: 0.9327
Epoch 9/10
621/621 [==============================] - 12s 20ms/step - loss: 0.2337 - accuracy: 0.9301 - val_loss: 0.2762 - val_accuracy: 0.9238
Epoch 10/10
621/621 [==============================] - 12s 19ms/step - loss: 0.2179 - accuracy: 0.9325 - val_loss: 0.2841 - val_accuracy: 0.9266
Epoch 1/10
621/621 [==============================] - 18s 21ms/step - loss: 2.0020 - accuracy: 0.4974 - val_loss: 0.6749 - val_accuracy: 0.8034
Epoch 2/10
621/621 [==============================] - 12s 19ms/step - loss: 0.7066 - accuracy: 0.7824 - val_loss: 0.4505 - val_accuracy: 0.8690
Epoch 3/10
621/621 [==============================] - 12s 19ms/step - loss: 0.5315 - accuracy: 0.8389 - val_loss: 0.3803 - val_accuracy: 0.8904
Epoch 4/10
621/621 [==============================] - 12s 19ms/step - loss: 0.4497 - accuracy: 0.8641 - val_loss: 0.3653 - val_accuracy: 0.8961
Epoch 5/10
621/621 [==============================] - 12s 20ms/step - loss: 0.3954 - accuracy: 0.8807 - val_loss: 0.3121 - val_accuracy: 0.9146
Epoch 6/10
621/621 [==============================] - 11s 18ms/step - loss: 0.3568 - accuracy: 0.8930 - val_loss: 0.3240 - val_accuracy: 0.9138
Epoch 7/10
621/621 [==============================] - 13s 21ms/step - loss: 0.3285 - accuracy: 0.9007 - val_loss: 0.3066 - val_accuracy: 0.9199
Epoch 8/10
621/621 [==============================] - 12s 20ms/step - loss: 0.3025 - accuracy: 0.9087 - val_loss: 0.2970 - val_accuracy: 0.9211
Epoch 9/10
621/621 [==============================] - 12s 19ms/step - loss: 0.2830 - accuracy: 0.9137 - val_loss: 0.2833 - val_accuracy: 0.9271
Epoch 10/10
621/621 [==============================] - 12s 20ms/step - loss: 0.2625 - accuracy: 0.9199 - val_loss: 0.3000 - val_accuracy: 0.9199
Epoch 1/10
621/621 [==============================] - 19s 22ms/step - loss: 2.4446 - accuracy: 0.3465 - val_loss: 0.8407 - val_accuracy: 0.7444
Epoch 2/10
621/621 [==============================] - 12s 19ms/step - loss: 0.7723 - accuracy: 0.7602 - val_loss: 0.4740 - val_accuracy: 0.8625
Epoch 3/10
621/621 [==============================] - 12s 19ms/step - loss: 0.5230 - accuracy: 0.8419 - val_loss: 0.3807 - val_accuracy: 0.8871
Epoch 4/10
621/621 [==============================] - 13s 20ms/step - loss: 0.4262 - accuracy: 0.8722 - val_loss: 0.3212 - val_accuracy: 0.9077
Epoch 5/10
621/621 [==============================] - 12s 19ms/step - loss: 0.3698 - accuracy: 0.8883 - val_loss: 0.2950 - val_accuracy: 0.9153
Epoch 6/10
621/621 [==============================] - 13s 20ms/step - loss: 0.3348 - accuracy: 0.8988 - val_loss: 0.2843 - val_accuracy: 0.9201
Epoch 7/10
621/621 [==============================] - 12s 19ms/step - loss: 0.3043 - accuracy: 0.9072 - val_loss: 0.2728 - val_accuracy: 0.9239
Epoch 8/10
621/621 [==============================] - 12s 19ms/step - loss: 0.2782 - accuracy: 0.9159 - val_loss: 0.3065 - val_accuracy: 0.9163
Epoch 9/10
621/621 [==============================] - 13s 20ms/step - loss: 0.2580 - accuracy: 0.9210 - val_loss: 0.2680 - val_accuracy: 0.9252
Epoch 10/10
621/621 [==============================] - 13s 21ms/step - loss: 0.2377 - accuracy: 0.9272 - val_loss: 0.2607 - val_accuracy: 0.9291
Epoch 1/10
621/621 [==============================] - 30s 29ms/step - loss: 0.2358 - accuracy: 0.9314 - val_loss: 0.1315 - val_accuracy: 0.9640
Epoch 2/10
621/621 [==============================] - 15s 23ms/step - loss: 0.2033 - accuracy: 0.9389 - val_loss: 0.1563 - val_accuracy: 0.9544
Epoch 3/10
621/621 [==============================] - 14s 23ms/step - loss: 0.1773 - accuracy: 0.9455 - val_loss: 0.1690 - val_accuracy: 0.9532
Epoch 4/10
621/621 [==============================] - 14s 22ms/step - loss: 0.1524 - accuracy: 0.9525 - val_loss: 0.1700 - val_accuracy: 0.9528
Epoch 5/10
621/621 [==============================] - 14s 22ms/step - loss: 0.1380 - accuracy: 0.9574 - val_loss: 0.1986 - val_accuracy: 0.9466
Epoch 6/10
621/621 [==============================] - 14s 22ms/step - loss: 0.1253 - accuracy: 0.9603 - val_loss: 0.1917 - val_accuracy: 0.9501
Epoch 7/10
621/621 [==============================] - 14s 22ms/step - loss: 0.1183 - accuracy: 0.9626 - val_loss: 0.2299 - val_accuracy: 0.9404
Epoch 8/10
621/621 [==============================] - 16s 25ms/step - loss: 0.1082 - accuracy: 0.9659 - val_loss: 0.2258 - val_accuracy: 0.9458
Epoch 9/10
621/621 [==============================] - 14s 23ms/step - loss: 0.0974 - accuracy: 0.9693 - val_loss: 0.2249 - val_accuracy: 0.9462
Epoch 10/10
621/621 [==============================] - 14s 23ms/step - loss: 0.0938 - accuracy: 0.9705 - val_loss: 0.2388 - val_accuracy: 0.9436
621/621 [==============================] - 3s 5ms/step - loss: 0.1115 - accuracy: 0.9699
621/621 [==============================] - 6s 10ms/step - loss: 0.2388 - accuracy: 0.9436
621/621 [==============================] - 3s 4ms/step - loss: 0.1115 - accuracy: 0.9699
Test Accuracy: 0.9698861837387085
Task A Original Accuracy: 96.99%
Task B CrlBo method Accuracy: 94.36%
Epoch 1/10
621/621 [==============================] - 33s 28ms/step - loss: 0.2370 - accuracy: 0.9302 - val_loss: 0.1701 - val_accuracy: 0.9506
Epoch 2/10
621/621 [==============================] - 14s 23ms/step - loss: 0.1993 - accuracy: 0.9403 - val_loss: 0.1770 - val_accuracy: 0.9484
Epoch 3/10
621/621 [==============================] - 14s 23ms/step - loss: 0.1755 - accuracy: 0.9470 - val_loss: 0.1555 - val_accuracy: 0.9552
Epoch 4/10
621/621 [==============================] - 14s 23ms/step - loss: 0.1513 - accuracy: 0.9530 - val_loss: 0.1626 - val_accuracy: 0.9537
Epoch 5/10
621/621 [==============================] - 15s 24ms/step - loss: 0.1394 - accuracy: 0.9560 - val_loss: 0.1854 - val_accuracy: 0.9518
Epoch 6/10
621/621 [==============================] - 14s 22ms/step - loss: 0.1218 - accuracy: 0.9615 - val_loss: 0.2004 - val_accuracy: 0.9458
Epoch 7/10
621/621 [==============================] - 14s 23ms/step - loss: 0.1112 - accuracy: 0.9644 - val_loss: 0.2171 - val_accuracy: 0.9434
Epoch 8/10
621/621 [==============================] - 14s 23ms/step - loss: 0.1099 - accuracy: 0.9654 - val_loss: 0.2289 - val_accuracy: 0.9451
Epoch 9/10
621/621 [==============================] - 14s 23ms/step - loss: 0.0961 - accuracy: 0.9688 - val_loss: 0.2315 - val_accuracy: 0.9432
Epoch 10/10
621/621 [==============================] - 14s 23ms/step - loss: 0.0953 - accuracy: 0.9696 - val_loss: 0.2423 - val_accuracy: 0.9419
621/621 [==============================] - 3s 4ms/step - loss: 0.1110 - accuracy: 0.9704
621/621 [==============================] - 6s 9ms/step - loss: 0.2423 - accuracy: 0.9419
621/621 [==============================] - 4s 6ms/step - loss: 0.1110 - accuracy: 0.9704
Test Accuracy: 0.970440149307251
Task A Original Accuracy: 97.04%
Task B CrlBo method Accuracy: 94.19%
Epoch 1/10
621/621 [==============================] - 29s 28ms/step - loss: 0.2413 - accuracy: 0.9297 - val_loss: 0.1328 - val_accuracy: 0.9634
Epoch 2/10
621/621 [==============================] - 14s 22ms/step - loss: 0.1998 - accuracy: 0.9402 - val_loss: 0.1631 - val_accuracy: 0.9527
Epoch 3/10
621/621 [==============================] - 14s 23ms/step - loss: 0.1769 - accuracy: 0.9461 - val_loss: 0.1739 - val_accuracy: 0.9504
Epoch 4/10
621/621 [==============================] - 17s 27ms/step - loss: 0.1504 - accuracy: 0.9547 - val_loss: 0.1725 - val_accuracy: 0.9529
Epoch 5/10
621/621 [==============================] - 14s 22ms/step - loss: 0.1427 - accuracy: 0.9555 - val_loss: 0.1864 - val_accuracy: 0.9498
Epoch 6/10
621/621 [==============================] - 14s 23ms/step - loss: 0.1253 - accuracy: 0.9608 - val_loss: 0.2465 - val_accuracy: 0.9407
Epoch 7/10
621/621 [==============================] - 14s 22ms/step - loss: 0.1126 - accuracy: 0.9635 - val_loss: 0.2130 - val_accuracy: 0.9464
Epoch 8/10
621/621 [==============================] - 14s 22ms/step - loss: 0.1057 - accuracy: 0.9673 - val_loss: 0.2640 - val_accuracy: 0.9408
Epoch 9/10
621/621 [==============================] - 14s 22ms/step - loss: 0.1001 - accuracy: 0.9689 - val_loss: 0.2552 - val_accuracy: 0.9399
Epoch 10/10
621/621 [==============================] - 14s 23ms/step - loss: 0.0985 - accuracy: 0.9690 - val_loss: 0.2921 - val_accuracy: 0.9405
621/621 [==============================] - 4s 6ms/step - loss: 0.1157 - accuracy: 0.9684
621/621 [==============================] - 5s 8ms/step - loss: 0.2921 - accuracy: 0.9405
621/621 [==============================] - 4s 7ms/step - loss: 0.1157 - accuracy: 0.9684
Test Accuracy: 0.9683754444122314
Task A Original Accuracy: 96.84%
Task B CrlBo method Accuracy: 94.05%
Epoch 1/10
621/621 [==============================] - 30s 29ms/step - loss: 0.2331 - accuracy: 0.9310 - val_loss: 0.1628 - val_accuracy: 0.9550
Epoch 2/10
621/621 [==============================] - 16s 25ms/step - loss: 0.1944 - accuracy: 0.9419 - val_loss: 0.1840 - val_accuracy: 0.9492
Epoch 3/10
621/621 [==============================] - 14s 23ms/step - loss: 0.1686 - accuracy: 0.9475 - val_loss: 0.1787 - val_accuracy: 0.9517
Epoch 4/10
621/621 [==============================] - 14s 23ms/step - loss: 0.1520 - accuracy: 0.9538 - val_loss: 0.1950 - val_accuracy: 0.9495
Epoch 5/10
621/621 [==============================] - 15s 24ms/step - loss: 0.1350 - accuracy: 0.9578 - val_loss: 0.2416 - val_accuracy: 0.9391
Epoch 6/10
621/621 [==============================] - 15s 24ms/step - loss: 0.1205 - accuracy: 0.9630 - val_loss: 0.2171 - val_accuracy: 0.9441
Epoch 7/10
621/621 [==============================] - 15s 24ms/step - loss: 0.1144 - accuracy: 0.9643 - val_loss: 0.2388 - val_accuracy: 0.9430
Epoch 8/10
621/621 [==============================] - 14s 23ms/step - loss: 0.1045 - accuracy: 0.9674 - val_loss: 0.2539 - val_accuracy: 0.9415
Epoch 9/10
621/621 [==============================] - 14s 23ms/step - loss: 0.1036 - accuracy: 0.9677 - val_loss: 0.2863 - val_accuracy: 0.9347
Epoch 10/10
621/621 [==============================] - 15s 24ms/step - loss: 0.0920 - accuracy: 0.9712 - val_loss: 0.2952 - val_accuracy: 0.9396
621/621 [==============================] - 3s 5ms/step - loss: 0.1236 - accuracy: 0.9675
621/621 [==============================] - 6s 10ms/step - loss: 0.2952 - accuracy: 0.9396
621/621 [==============================] - 3s 5ms/step - loss: 0.1236 - accuracy: 0.9675
Test Accuracy: 0.9675194025039673
Task A Original Accuracy: 96.75%
Task B CrlBo method Accuracy: 93.96%
Epoch 1/10
621/621 [==============================] - 31s 29ms/step - loss: 0.2074 - accuracy: 0.9363 - val_loss: 0.2708 - val_accuracy: 0.9257
Epoch 2/10
621/621 [==============================] - 15s 24ms/step - loss: 0.1749 - accuracy: 0.9462 - val_loss: 0.2982 - val_accuracy: 0.9247
Epoch 3/10
621/621 [==============================] - 15s 24ms/step - loss: 0.1576 - accuracy: 0.9508 - val_loss: 0.2987 - val_accuracy: 0.9246
Epoch 4/10
621/621 [==============================] - 15s 24ms/step - loss: 0.1406 - accuracy: 0.9559 - val_loss: 0.3075 - val_accuracy: 0.9214
Epoch 5/10
621/621 [==============================] - 14s 23ms/step - loss: 0.1288 - accuracy: 0.9598 - val_loss: 0.3235 - val_accuracy: 0.9302
Epoch 6/10
621/621 [==============================] - 14s 23ms/step - loss: 0.1202 - accuracy: 0.9628 - val_loss: 0.3517 - val_accuracy: 0.9229
Epoch 7/10
621/621 [==============================] - 14s 23ms/step - loss: 0.1150 - accuracy: 0.9642 - val_loss: 0.3683 - val_accuracy: 0.9260
Epoch 8/10
621/621 [==============================] - 14s 23ms/step - loss: 0.1013 - accuracy: 0.9678 - val_loss: 0.3617 - val_accuracy: 0.9286
Epoch 9/10
621/621 [==============================] - 15s 24ms/step - loss: 0.1026 - accuracy: 0.9680 - val_loss: 0.3366 - val_accuracy: 0.9264
Epoch 10/10
621/621 [==============================] - 14s 23ms/step - loss: 0.0891 - accuracy: 0.9718 - val_loss: 0.3674 - val_accuracy: 0.9240
621/621 [==============================] - 4s 7ms/step - loss: 0.2607 - accuracy: 0.9291
621/621 [==============================] - 5s 8ms/step - loss: 0.3674 - accuracy: 0.9240
621/621 [==============================] - 3s 6ms/step - loss: 0.2607 - accuracy: 0.9291
Test Accuracy: 0.9290930032730103
Task A Original Accuracy: 92.91%
Task B CrlBo method Accuracy: 92.40%
Fold-1: 96.99%
Fold-2: 97.04%
Fold-3: 96.84%
Fold-4: 96.75%
Fold-5: 92.91%

### Caltech101

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPool2D,Dense,Flatten,Dropout,Input, AveragePooling2D, Activation,Conv2D, MaxPooling2D, BatchNormalization,Concatenate
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
from tensorflow.keras import regularizers, optimizers
from tensorflow.keras.preprocessing.image import ImageDataGenerator

from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers
from tensorflow.keras.regularizers import Regularizer

# Perform hold-out cross-validation
validation_scores = []

# Define the CrlBo regularizer
class CrlBoRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Number of K-folds
K = 5

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)
# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []
num_classes = 102
# Perform K-fold cross-validation
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]

# Task A: Original SVHN model
    model = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(28, 28, 3)),
        Conv2D(32, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu'),
        layers.Dropout(0.25),
        Dense(num_classes, activation='softmax')
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model = model
        model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
        model.save_weights('FashionMNIST_A.h5')
        prior_weights = model.get_weights()
# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    fisher_matrix = []
    for i in range(len(model.trainable_weights)):
        fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

    for _ in range(num_samples):
        idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
        with tf.GradientTape() as tape:
            logits = model(x[idx:idx+1])
        gradients = tape.gradient(logits, model.trainable_weights)
        for i in range(len(fisher_matrix)):
            fisher_matrix[i] += tf.square(gradients[i])

    fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
    return fisher_matrix

fisher_matrix = compute_fisher(model, x_train_fold)
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]
# Task B: Fashion SVHN with CrlBo regularization
    model_CrlBoB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(28, 28, 3),
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model_CrlBoB = model_CrlBoB
        model_CrlBoB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model_CrlBoB.load_weights('FashionMNIST_A.h5')
        model_CrlBoB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlBo_acc = 100 * model_CrlBoB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlBo method Accuracy: %.2f%%" % B_CrlBo_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
58/58 [==============================] - 9s 38ms/step - loss: 4.0957 - accuracy: 0.1379 - val_loss: 3.6003 - val_accuracy: 0.2346
Epoch 2/10
58/58 [==============================] - 1s 18ms/step - loss: 3.3070 - accuracy: 0.2992 - val_loss: 2.9275 - val_accuracy: 0.3751
Epoch 3/10
58/58 [==============================] - 1s 19ms/step - loss: 2.6694 - accuracy: 0.4090 - val_loss: 2.5163 - val_accuracy: 0.4467
Epoch 4/10
58/58 [==============================] - 1s 20ms/step - loss: 2.2469 - accuracy: 0.4751 - val_loss: 2.2807 - val_accuracy: 0.4800
Epoch 5/10
58/58 [==============================] - 1s 18ms/step - loss: 1.9156 - accuracy: 0.5373 - val_loss: 2.1094 - val_accuracy: 0.5145
Epoch 6/10
58/58 [==============================] - 1s 19ms/step - loss: 1.6497 - accuracy: 0.5896 - val_loss: 2.0950 - val_accuracy: 0.5189
Epoch 7/10
58/58 [==============================] - 1s 20ms/step - loss: 1.3956 - accuracy: 0.6373 - val_loss: 2.0253 - val_accuracy: 0.5424
Epoch 8/10
58/58 [==============================] - 2s 26ms/step - loss: 1.1870 - accuracy: 0.6863 - val_loss: 2.0131 - val_accuracy: 0.5615
Epoch 9/10
58/58 [==============================] - 1s 24ms/step - loss: 0.9650 - accuracy: 0.7360 - val_loss: 2.0333 - val_accuracy: 0.5631
Epoch 10/10
58/58 [==============================] - 1s 18ms/step - loss: 0.8018 - accuracy: 0.7729 - val_loss: 2.1154 - val_accuracy: 0.5653
Epoch 1/10
58/58 [==============================] - 9s 28ms/step - loss: 3.9152 - accuracy: 0.1862 - val_loss: 3.4631 - val_accuracy: 0.2734
Epoch 2/10
58/58 [==============================] - 1s 19ms/step - loss: 3.0879 - accuracy: 0.3418 - val_loss: 2.8133 - val_accuracy: 0.3887
Epoch 3/10
58/58 [==============================] - 1s 18ms/step - loss: 2.4615 - accuracy: 0.4472 - val_loss: 2.4563 - val_accuracy: 0.4571
Epoch 4/10
58/58 [==============================] - 1s 19ms/step - loss: 2.0652 - accuracy: 0.5199 - val_loss: 2.1600 - val_accuracy: 0.5090
Epoch 5/10
58/58 [==============================] - 1s 20ms/step - loss: 1.6797 - accuracy: 0.5911 - val_loss: 2.0569 - val_accuracy: 0.5254
Epoch 6/10
58/58 [==============================] - 1s 20ms/step - loss: 1.3974 - accuracy: 0.6465 - val_loss: 2.0165 - val_accuracy: 0.5489
Epoch 7/10
58/58 [==============================] - 1s 17ms/step - loss: 1.1438 - accuracy: 0.6954 - val_loss: 1.9916 - val_accuracy: 0.5577
Epoch 8/10
58/58 [==============================] - 1s 18ms/step - loss: 0.9219 - accuracy: 0.7502 - val_loss: 2.0622 - val_accuracy: 0.5610
Epoch 9/10
58/58 [==============================] - 1s 18ms/step - loss: 0.7114 - accuracy: 0.7955 - val_loss: 2.2673 - val_accuracy: 0.5566
Epoch 10/10
58/58 [==============================] - 1s 24ms/step - loss: 0.6288 - accuracy: 0.8179 - val_loss: 2.2060 - val_accuracy: 0.5703
Epoch 1/10
58/58 [==============================] - 7s 30ms/step - loss: 4.0311 - accuracy: 0.1541 - val_loss: 3.5792 - val_accuracy: 0.2482
Epoch 2/10
58/58 [==============================] - 1s 20ms/step - loss: 3.2536 - accuracy: 0.3035 - val_loss: 2.6926 - val_accuracy: 0.4106
Epoch 3/10
58/58 [==============================] - 1s 18ms/step - loss: 2.5815 - accuracy: 0.4170 - val_loss: 2.2933 - val_accuracy: 0.4986
Epoch 4/10
58/58 [==============================] - 1s 24ms/step - loss: 2.0885 - accuracy: 0.5066 - val_loss: 2.1529 - val_accuracy: 0.5090
Epoch 5/10
58/58 [==============================] - 2s 28ms/step - loss: 1.7944 - accuracy: 0.5617 - val_loss: 1.9479 - val_accuracy: 0.5533
Epoch 6/10
58/58 [==============================] - 1s 23ms/step - loss: 1.4924 - accuracy: 0.6253 - val_loss: 1.8621 - val_accuracy: 0.5757
Epoch 7/10
58/58 [==============================] - 1s 19ms/step - loss: 1.2351 - accuracy: 0.6797 - val_loss: 1.9039 - val_accuracy: 0.5845
Epoch 8/10
58/58 [==============================] - 1s 17ms/step - loss: 1.0243 - accuracy: 0.7176 - val_loss: 1.8690 - val_accuracy: 0.5938
Epoch 9/10
58/58 [==============================] - 1s 18ms/step - loss: 0.8074 - accuracy: 0.7713 - val_loss: 2.0340 - val_accuracy: 0.5965
Epoch 10/10
58/58 [==============================] - 1s 20ms/step - loss: 0.6275 - accuracy: 0.8163 - val_loss: 2.0918 - val_accuracy: 0.6020
Epoch 1/10
58/58 [==============================] - 9s 31ms/step - loss: 4.0580 - accuracy: 0.1520 - val_loss: 3.5491 - val_accuracy: 0.2788
Epoch 2/10
58/58 [==============================] - 1s 19ms/step - loss: 3.1691 - accuracy: 0.3337 - val_loss: 2.7437 - val_accuracy: 0.4101
Epoch 3/10
58/58 [==============================] - 1s 17ms/step - loss: 2.4917 - accuracy: 0.4428 - val_loss: 2.4088 - val_accuracy: 0.4675
Epoch 4/10
58/58 [==============================] - 1s 19ms/step - loss: 2.0696 - accuracy: 0.5136 - val_loss: 2.1478 - val_accuracy: 0.5052
Epoch 5/10
58/58 [==============================] - 1s 19ms/step - loss: 1.7573 - accuracy: 0.5713 - val_loss: 2.0854 - val_accuracy: 0.5287
Epoch 6/10
58/58 [==============================] - 1s 19ms/step - loss: 1.4572 - accuracy: 0.6284 - val_loss: 2.0232 - val_accuracy: 0.5495
Epoch 7/10
58/58 [==============================] - 1s 18ms/step - loss: 1.1790 - accuracy: 0.6889 - val_loss: 2.0837 - val_accuracy: 0.5566
Epoch 8/10
58/58 [==============================] - 1s 19ms/step - loss: 0.9438 - accuracy: 0.7461 - val_loss: 2.1000 - val_accuracy: 0.5610
Epoch 9/10
58/58 [==============================] - 2s 27ms/step - loss: 0.7407 - accuracy: 0.7954 - val_loss: 2.2402 - val_accuracy: 0.5642
Epoch 10/10
58/58 [==============================] - 2s 28ms/step - loss: 0.6264 - accuracy: 0.8212 - val_loss: 2.3012 - val_accuracy: 0.5730
Epoch 1/10
58/58 [==============================] - 8s 41ms/step - loss: 4.0450 - accuracy: 0.1514 - val_loss: 3.5715 - val_accuracy: 0.2407
Epoch 2/10
58/58 [==============================] - 1s 22ms/step - loss: 3.2130 - accuracy: 0.3140 - val_loss: 2.8881 - val_accuracy: 0.3818
Epoch 3/10
58/58 [==============================] - 2s 28ms/step - loss: 2.5832 - accuracy: 0.4233 - val_loss: 2.4176 - val_accuracy: 0.4475
Epoch 4/10
58/58 [==============================] - 1s 23ms/step - loss: 2.1469 - accuracy: 0.5010 - val_loss: 2.2213 - val_accuracy: 0.4973
Epoch 5/10
58/58 [==============================] - 1s 19ms/step - loss: 1.8341 - accuracy: 0.5504 - val_loss: 2.0415 - val_accuracy: 0.5383
Epoch 6/10
58/58 [==============================] - 1s 18ms/step - loss: 1.5615 - accuracy: 0.6132 - val_loss: 2.0273 - val_accuracy: 0.5454
Epoch 7/10
58/58 [==============================] - 1s 19ms/step - loss: 1.3152 - accuracy: 0.6642 - val_loss: 1.9608 - val_accuracy: 0.5656
Epoch 8/10
58/58 [==============================] - 1s 20ms/step - loss: 1.0960 - accuracy: 0.7063 - val_loss: 1.9827 - val_accuracy: 0.5646
Epoch 9/10
58/58 [==============================] - 1s 18ms/step - loss: 0.8991 - accuracy: 0.7537 - val_loss: 2.0242 - val_accuracy: 0.5722
Epoch 10/10
58/58 [==============================] - 1s 19ms/step - loss: 0.7277 - accuracy: 0.7890 - val_loss: 2.0937 - val_accuracy: 0.5766
Epoch 1/10
58/58 [==============================] - 18s 87ms/step - loss: 0.8828 - accuracy: 0.7993 - val_loss: 0.3676 - val_accuracy: 0.9185
Epoch 2/10
58/58 [==============================] - 1s 25ms/step - loss: 0.5385 - accuracy: 0.8692 - val_loss: 0.4707 - val_accuracy: 0.8660
Epoch 3/10
58/58 [==============================] - 1s 23ms/step - loss: 0.3440 - accuracy: 0.9059 - val_loss: 0.4226 - val_accuracy: 0.8770
Epoch 4/10
58/58 [==============================] - 1s 22ms/step - loss: 0.2225 - accuracy: 0.9390 - val_loss: 0.5293 - val_accuracy: 0.8431
Epoch 5/10
58/58 [==============================] - 1s 23ms/step - loss: 0.1550 - accuracy: 0.9537 - val_loss: 0.5282 - val_accuracy: 0.8546
Epoch 6/10
58/58 [==============================] - 1s 25ms/step - loss: 0.1287 - accuracy: 0.9613 - val_loss: 0.6422 - val_accuracy: 0.8311
Epoch 7/10
58/58 [==============================] - 1s 21ms/step - loss: 0.1099 - accuracy: 0.9688 - val_loss: 0.6401 - val_accuracy: 0.8393
Epoch 8/10
58/58 [==============================] - 2s 32ms/step - loss: 0.0921 - accuracy: 0.9729 - val_loss: 0.7027 - val_accuracy: 0.8207
Epoch 9/10
58/58 [==============================] - 2s 32ms/step - loss: 0.0812 - accuracy: 0.9758 - val_loss: 0.7009 - val_accuracy: 0.8245
Epoch 10/10
58/58 [==============================] - 1s 23ms/step - loss: 0.0681 - accuracy: 0.9811 - val_loss: 0.7653 - val_accuracy: 0.8103
58/58 [==============================] - 1s 8ms/step - loss: 0.2624 - accuracy: 0.9497
58/58 [==============================] - 1s 9ms/step - loss: 0.7653 - accuracy: 0.8103
58/58 [==============================] - 0s 5ms/step - loss: 0.2624 - accuracy: 0.9497
Test Accuracy: 0.9496992826461792
Task A Original Accuracy: 94.97%
Task B CrlBo method Accuracy: 81.03%
Epoch 1/10
58/58 [==============================] - 18s 78ms/step - loss: 0.8804 - accuracy: 0.7985 - val_loss: 0.3500 - val_accuracy: 0.9196
Epoch 2/10
58/58 [==============================] - 1s 25ms/step - loss: 0.5461 - accuracy: 0.8603 - val_loss: 0.3544 - val_accuracy: 0.9092
Epoch 3/10
58/58 [==============================] - 2s 32ms/step - loss: 0.3412 - accuracy: 0.9075 - val_loss: 0.4087 - val_accuracy: 0.8814
Epoch 4/10
58/58 [==============================] - 2s 31ms/step - loss: 0.2418 - accuracy: 0.9293 - val_loss: 0.4449 - val_accuracy: 0.8710
Epoch 5/10
58/58 [==============================] - 1s 22ms/step - loss: 0.1814 - accuracy: 0.9504 - val_loss: 0.5406 - val_accuracy: 0.8491
Epoch 6/10
58/58 [==============================] - 1s 23ms/step - loss: 0.1281 - accuracy: 0.9635 - val_loss: 0.5743 - val_accuracy: 0.8486
Epoch 7/10
58/58 [==============================] - 1s 24ms/step - loss: 0.1077 - accuracy: 0.9697 - val_loss: 0.6167 - val_accuracy: 0.8343
Epoch 8/10
58/58 [==============================] - 1s 25ms/step - loss: 0.1043 - accuracy: 0.9692 - val_loss: 0.6447 - val_accuracy: 0.8223
Epoch 9/10
58/58 [==============================] - 1s 22ms/step - loss: 0.0831 - accuracy: 0.9783 - val_loss: 0.7429 - val_accuracy: 0.8212
Epoch 10/10
58/58 [==============================] - 1s 23ms/step - loss: 0.0733 - accuracy: 0.9794 - val_loss: 0.7571 - val_accuracy: 0.8185
58/58 [==============================] - 0s 5ms/step - loss: 0.2428 - accuracy: 0.9508
58/58 [==============================] - 1s 8ms/step - loss: 0.7571 - accuracy: 0.8185
58/58 [==============================] - 0s 5ms/step - loss: 0.2428 - accuracy: 0.9508
Test Accuracy: 0.9507927894592285
Task A Original Accuracy: 95.08%
Task B CrlBo method Accuracy: 81.85%
Epoch 1/10
58/58 [==============================] - 17s 85ms/step - loss: 0.8901 - accuracy: 0.7982 - val_loss: 0.3583 - val_accuracy: 0.9142
Epoch 2/10
58/58 [==============================] - 2s 31ms/step - loss: 0.5294 - accuracy: 0.8694 - val_loss: 0.3753 - val_accuracy: 0.8950
Epoch 3/10
58/58 [==============================] - 2s 31ms/step - loss: 0.3202 - accuracy: 0.9129 - val_loss: 0.4104 - val_accuracy: 0.8808
Epoch 4/10
58/58 [==============================] - 1s 22ms/step - loss: 0.2120 - accuracy: 0.9377 - val_loss: 0.5306 - val_accuracy: 0.8442
Epoch 5/10
58/58 [==============================] - 1s 20ms/step - loss: 0.1988 - accuracy: 0.9419 - val_loss: 0.5567 - val_accuracy: 0.8496
Epoch 6/10
58/58 [==============================] - 1s 22ms/step - loss: 0.1576 - accuracy: 0.9545 - val_loss: 0.5668 - val_accuracy: 0.8469
Epoch 7/10
58/58 [==============================] - 1s 22ms/step - loss: 0.0872 - accuracy: 0.9751 - val_loss: 0.6146 - val_accuracy: 0.8403
Epoch 8/10
58/58 [==============================] - 1s 20ms/step - loss: 0.0699 - accuracy: 0.9807 - val_loss: 0.6488 - val_accuracy: 0.8283
Epoch 9/10
58/58 [==============================] - 1s 23ms/step - loss: 0.0891 - accuracy: 0.9725 - val_loss: 0.6587 - val_accuracy: 0.8387
Epoch 10/10
58/58 [==============================] - 1s 24ms/step - loss: 0.0910 - accuracy: 0.9743 - val_loss: 0.7397 - val_accuracy: 0.8256
58/58 [==============================] - 0s 5ms/step - loss: 0.2557 - accuracy: 0.9415
58/58 [==============================] - 1s 9ms/step - loss: 0.7397 - accuracy: 0.8256
58/58 [==============================] - 1s 10ms/step - loss: 0.2557 - accuracy: 0.9415
Test Accuracy: 0.9414981007575989
Task A Original Accuracy: 94.15%
Task B CrlBo method Accuracy: 82.56%
Epoch 1/10
58/58 [==============================] - 19s 69ms/step - loss: 0.8680 - accuracy: 0.8090 - val_loss: 0.3627 - val_accuracy: 0.9191
Epoch 2/10
58/58 [==============================] - 1s 22ms/step - loss: 0.5339 - accuracy: 0.8674 - val_loss: 0.3961 - val_accuracy: 0.8852
Epoch 3/10
58/58 [==============================] - 1s 23ms/step - loss: 0.3243 - accuracy: 0.9131 - val_loss: 0.4276 - val_accuracy: 0.8742
Epoch 4/10
58/58 [==============================] - 1s 22ms/step - loss: 0.2424 - accuracy: 0.9281 - val_loss: 0.4825 - val_accuracy: 0.8578
Epoch 5/10
58/58 [==============================] - 2s 27ms/step - loss: 0.1519 - accuracy: 0.9569 - val_loss: 0.5270 - val_accuracy: 0.8584
Epoch 6/10
58/58 [==============================] - 2s 28ms/step - loss: 0.1396 - accuracy: 0.9597 - val_loss: 0.6687 - val_accuracy: 0.8212
Epoch 7/10
58/58 [==============================] - 1s 25ms/step - loss: 0.1021 - accuracy: 0.9707 - val_loss: 0.6685 - val_accuracy: 0.8305
Epoch 8/10
58/58 [==============================] - 1s 21ms/step - loss: 0.0839 - accuracy: 0.9743 - val_loss: 0.7452 - val_accuracy: 0.8157
Epoch 9/10
58/58 [==============================] - 1s 22ms/step - loss: 0.1181 - accuracy: 0.9651 - val_loss: 0.7979 - val_accuracy: 0.8103
Epoch 10/10
58/58 [==============================] - 1s 22ms/step - loss: 0.0772 - accuracy: 0.9783 - val_loss: 0.7129 - val_accuracy: 0.8283
58/58 [==============================] - 1s 8ms/step - loss: 0.2489 - accuracy: 0.9464
58/58 [==============================] - 1s 11ms/step - loss: 0.7129 - accuracy: 0.8283
58/58 [==============================] - 0s 5ms/step - loss: 0.2489 - accuracy: 0.9464
Test Accuracy: 0.946418821811676
Task A Original Accuracy: 94.64%
Task B CrlBo method Accuracy: 82.83%
Epoch 1/10
58/58 [==============================] - 20s 86ms/step - loss: 0.3911 - accuracy: 0.8860 - val_loss: 2.5597 - val_accuracy: 0.5739
Epoch 2/10
58/58 [==============================] - 2s 30ms/step - loss: 0.2304 - accuracy: 0.9349 - val_loss: 2.9734 - val_accuracy: 0.5744
Epoch 3/10
58/58 [==============================] - 2s 30ms/step - loss: 0.1603 - accuracy: 0.9528 - val_loss: 3.0797 - val_accuracy: 0.5689
Epoch 4/10
58/58 [==============================] - 1s 24ms/step - loss: 0.1303 - accuracy: 0.9604 - val_loss: 3.2601 - val_accuracy: 0.5684
Epoch 5/10
58/58 [==============================] - 1s 22ms/step - loss: 0.1351 - accuracy: 0.9595 - val_loss: 3.2775 - val_accuracy: 0.5695
Epoch 6/10
58/58 [==============================] - 1s 23ms/step - loss: 0.1126 - accuracy: 0.9694 - val_loss: 3.5625 - val_accuracy: 0.5656
Epoch 7/10
58/58 [==============================] - 1s 21ms/step - loss: 0.1005 - accuracy: 0.9727 - val_loss: 3.6580 - val_accuracy: 0.5585
Epoch 8/10
58/58 [==============================] - 1s 23ms/step - loss: 0.0833 - accuracy: 0.9759 - val_loss: 3.7128 - val_accuracy: 0.5602
Epoch 9/10
58/58 [==============================] - 1s 24ms/step - loss: 0.0873 - accuracy: 0.9733 - val_loss: 3.6261 - val_accuracy: 0.5635
Epoch 10/10
58/58 [==============================] - 1s 22ms/step - loss: 0.0721 - accuracy: 0.9802 - val_loss: 3.7401 - val_accuracy: 0.5656
58/58 [==============================] - 1s 10ms/step - loss: 2.0937 - accuracy: 0.5766
58/58 [==============================] - 1s 8ms/step - loss: 3.7401 - accuracy: 0.5656
58/58 [==============================] - 0s 5ms/step - loss: 2.0937 - accuracy: 0.5766
Test Accuracy: 0.5765864253044128
Task A Original Accuracy: 57.66%
Task B CrlBo method Accuracy: 56.56%
Fold-1: 94.97%
Fold-2: 95.08%
Fold-3: 94.15%
Fold-4: 94.64%
Fold-5: 57.66%

## Folds 10

### MNIST

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.regularizers import Regularizer
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import KFold
from tensorflow.keras import backend as K
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    f_accum = []
    for i in range(len(model.weights)):
        f_accum.append(np.zeros(K.int_shape(model.weights[i])))
    f_accum = np.array(f_accum)
    for _ in range(num_samples):
        idx = np.random.randint(0, x.shape[0])
        with tf.GradientTape() as tape:
            model_output = model(x[idx:idx+1])
        grads = tape.gradient(model_output, model.weights)
        for i in range(len(grads)):
            f_accum[i] += tf.square(grads[i])
    f_accum /= num_samples
    return f_accum

# Define the CrlB regularizer
class CrlBRegularizer(Regularizer):
    def __init__(self, fisher, prior_weights, lambda_=0.1):
        self.fisher = fisher
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i in range(len(self.fisher)):
            regularization += self.lambda_ * tf.reduce_sum(self.fisher[i] * tf.square(x - self.prior_weights[i]))
        return regularization

# Load the MNIST dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.reshape(-1, 28 * 28) / 255.0
x_test = x_test.reshape(-1, 28 * 28) / 255.0
y_train_onehot = tf.keras.utils.to_categorical(y_train, num_classes=10)
y_test_onehot = tf.keras.utils.to_categorical(y_test, num_classes=10)

# Number of K-folds
K = 10

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)

# Initialize the list to store test accuracies
accuracies = []

# Perform K-fold cross-validation
for train_index, test_index in kf.split(x_train, y_train_onehot):
    x_train_fold, x_test_fold = x_train[train_index], x_train[test_index]
    y_train_fold, y_test_fold = y_train_onehot[train_index], y_train_onehot[test_index]

# Task A: Original Fashion MNIST model
    model = Sequential([
    Dense(128, activation='relu', input_shape=(784,)),
    Dense(10, activation='softmax')
])
    model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
    model.save_weights('FashionMNIST_A.h5')

# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]

# Task B: Fashion MNIST with CrlB regularization
    model_CrlBB = Sequential([
        Dense(128, activation='relu', input_shape=(784,), kernel_regularizer=CrlBRegularizer(fisher_info[0], model.weights[0])),
        Dense(10, activation='softmax', kernel_regularizer=CrlBRegularizer(fisher_info[1], model.weights[1]))
    ])
    model_CrlBB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    model_CrlBB.load_weights('FashionMNIST_A.h5')
    model_CrlBB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlB_acc = 100 * model_CrlBB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlB method Accuracy: %.2f%%" % B_CrlB_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
422/422 [==============================] - 3s 5ms/step - loss: 0.3787 - accuracy: 0.8959 - val_loss: 0.2098 - val_accuracy: 0.9420
Epoch 2/10
422/422 [==============================] - 2s 5ms/step - loss: 0.1788 - accuracy: 0.9497 - val_loss: 0.1499 - val_accuracy: 0.9587
Epoch 3/10
422/422 [==============================] - 2s 5ms/step - loss: 0.1313 - accuracy: 0.9624 - val_loss: 0.1221 - val_accuracy: 0.9662
Epoch 4/10
422/422 [==============================] - 3s 6ms/step - loss: 0.1024 - accuracy: 0.9703 - val_loss: 0.1029 - val_accuracy: 0.9705
Epoch 5/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0829 - accuracy: 0.9755 - val_loss: 0.0965 - val_accuracy: 0.9708
Epoch 6/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0688 - accuracy: 0.9803 - val_loss: 0.0851 - val_accuracy: 0.9752
Epoch 7/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0580 - accuracy: 0.9829 - val_loss: 0.0863 - val_accuracy: 0.9738
Epoch 8/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0490 - accuracy: 0.9861 - val_loss: 0.0780 - val_accuracy: 0.9757
Epoch 9/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0408 - accuracy: 0.9886 - val_loss: 0.0809 - val_accuracy: 0.9750
Epoch 10/10
422/422 [==============================] - 3s 7ms/step - loss: 0.0353 - accuracy: 0.9903 - val_loss: 0.0702 - val_accuracy: 0.9782
Epoch 1/10
422/422 [==============================] - 109s 75ms/step - loss: 0.0324 - accuracy: 0.9914 - val_loss: 0.0794 - val_accuracy: 0.9747
Epoch 2/10
422/422 [==============================] - 14s 32ms/step - loss: 0.0261 - accuracy: 0.9931 - val_loss: 0.0710 - val_accuracy: 0.9782
Epoch 3/10
422/422 [==============================] - 13s 30ms/step - loss: 0.0223 - accuracy: 0.9943 - val_loss: 0.0695 - val_accuracy: 0.9800
Epoch 4/10
422/422 [==============================] - 14s 32ms/step - loss: 0.0182 - accuracy: 0.9956 - val_loss: 0.0744 - val_accuracy: 0.9797
Epoch 5/10
422/422 [==============================] - 13s 31ms/step - loss: 0.0155 - accuracy: 0.9964 - val_loss: 0.0712 - val_accuracy: 0.9788
Epoch 6/10
422/422 [==============================] - 13s 30ms/step - loss: 0.0129 - accuracy: 0.9971 - val_loss: 0.0715 - val_accuracy: 0.9802
Epoch 7/10
422/422 [==============================] - 13s 30ms/step - loss: 0.0109 - accuracy: 0.9981 - val_loss: 0.0752 - val_accuracy: 0.9790
Epoch 8/10
422/422 [==============================] - 14s 32ms/step - loss: 0.0089 - accuracy: 0.9984 - val_loss: 0.0749 - val_accuracy: 0.9785
Epoch 9/10
422/422 [==============================] - 14s 32ms/step - loss: 0.0085 - accuracy: 0.9984 - val_loss: 0.0745 - val_accuracy: 0.9805
Epoch 10/10
422/422 [==============================] - 13s 30ms/step - loss: 0.0072 - accuracy: 0.9988 - val_loss: 0.0787 - val_accuracy: 0.9788
188/188 [==============================] - 0s 3ms/step - loss: 0.0702 - accuracy: 0.9782
188/188 [==============================] - 2s 12ms/step - loss: 0.0787 - accuracy: 0.9788
188/188 [==============================] - 0s 2ms/step - loss: 0.0702 - accuracy: 0.9782
Test Accuracy: 0.9781666398048401
Task A Original Accuracy: 97.82%
Task B EWC method Accuracy: 97.88%
Epoch 1/10
422/422 [==============================] - 3s 5ms/step - loss: 0.3808 - accuracy: 0.8944 - val_loss: 0.2167 - val_accuracy: 0.9407
Epoch 2/10
422/422 [==============================] - 2s 4ms/step - loss: 0.1751 - accuracy: 0.9495 - val_loss: 0.1604 - val_accuracy: 0.9558
Epoch 3/10
422/422 [==============================] - 2s 4ms/step - loss: 0.1276 - accuracy: 0.9639 - val_loss: 0.1294 - val_accuracy: 0.9625
Epoch 4/10
422/422 [==============================] - 1s 3ms/step - loss: 0.0991 - accuracy: 0.9720 - val_loss: 0.1197 - val_accuracy: 0.9653
Epoch 5/10
422/422 [==============================] - 1s 3ms/step - loss: 0.0802 - accuracy: 0.9775 - val_loss: 0.1029 - val_accuracy: 0.9673
Epoch 6/10
422/422 [==============================] - 1s 4ms/step - loss: 0.0667 - accuracy: 0.9810 - val_loss: 0.0902 - val_accuracy: 0.9725
Epoch 7/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0553 - accuracy: 0.9847 - val_loss: 0.0886 - val_accuracy: 0.9728
Epoch 8/10
422/422 [==============================] - 1s 3ms/step - loss: 0.0473 - accuracy: 0.9865 - val_loss: 0.0862 - val_accuracy: 0.9747
Epoch 9/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0398 - accuracy: 0.9891 - val_loss: 0.0858 - val_accuracy: 0.9742
Epoch 10/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0337 - accuracy: 0.9906 - val_loss: 0.0818 - val_accuracy: 0.9742
Epoch 1/10
422/422 [==============================] - 63s 34ms/step - loss: 0.0309 - accuracy: 0.9916 - val_loss: 0.0832 - val_accuracy: 0.9755
Epoch 2/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0244 - accuracy: 0.9937 - val_loss: 0.0820 - val_accuracy: 0.9765
Epoch 3/10
422/422 [==============================] - 3s 7ms/step - loss: 0.0198 - accuracy: 0.9955 - val_loss: 0.0821 - val_accuracy: 0.9750
Epoch 4/10
422/422 [==============================] - 3s 6ms/step - loss: 0.0168 - accuracy: 0.9962 - val_loss: 0.1024 - val_accuracy: 0.9727
Epoch 5/10
422/422 [==============================] - 3s 6ms/step - loss: 0.0146 - accuracy: 0.9966 - val_loss: 0.0937 - val_accuracy: 0.9740
Epoch 6/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0125 - accuracy: 0.9973 - val_loss: 0.0906 - val_accuracy: 0.9743
Epoch 7/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0100 - accuracy: 0.9983 - val_loss: 0.0879 - val_accuracy: 0.9758
Epoch 8/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0080 - accuracy: 0.9987 - val_loss: 0.0863 - val_accuracy: 0.9780
Epoch 9/10
422/422 [==============================] - 2s 6ms/step - loss: 0.0073 - accuracy: 0.9986 - val_loss: 0.0879 - val_accuracy: 0.9772
Epoch 10/10
422/422 [==============================] - 3s 7ms/step - loss: 0.0056 - accuracy: 0.9993 - val_loss: 0.0954 - val_accuracy: 0.9767
188/188 [==============================] - 0s 2ms/step - loss: 0.0818 - accuracy: 0.9742
188/188 [==============================] - 1s 4ms/step - loss: 0.0954 - accuracy: 0.9767
188/188 [==============================] - 1s 3ms/step - loss: 0.0818 - accuracy: 0.9742
Test Accuracy: 0.9741666913032532
Task A Original Accuracy: 97.42%
Task B EWC method Accuracy: 97.67%
Epoch 1/10
422/422 [==============================] - 2s 4ms/step - loss: 0.3772 - accuracy: 0.8947 - val_loss: 0.2101 - val_accuracy: 0.9425
Epoch 2/10
422/422 [==============================] - 1s 3ms/step - loss: 0.1742 - accuracy: 0.9502 - val_loss: 0.1645 - val_accuracy: 0.9525
Epoch 3/10
422/422 [==============================] - 1s 3ms/step - loss: 0.1260 - accuracy: 0.9642 - val_loss: 0.1293 - val_accuracy: 0.9622
Epoch 4/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0980 - accuracy: 0.9714 - val_loss: 0.1127 - val_accuracy: 0.9695
Epoch 5/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0787 - accuracy: 0.9777 - val_loss: 0.1145 - val_accuracy: 0.9667
Epoch 6/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0649 - accuracy: 0.9813 - val_loss: 0.0943 - val_accuracy: 0.9718
Epoch 7/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0546 - accuracy: 0.9841 - val_loss: 0.0915 - val_accuracy: 0.9732
Epoch 8/10
422/422 [==============================] - 1s 4ms/step - loss: 0.0458 - accuracy: 0.9863 - val_loss: 0.0975 - val_accuracy: 0.9713
Epoch 9/10
422/422 [==============================] - 1s 3ms/step - loss: 0.0392 - accuracy: 0.9884 - val_loss: 0.0899 - val_accuracy: 0.9735
Epoch 10/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0330 - accuracy: 0.9915 - val_loss: 0.0950 - val_accuracy: 0.9730
Epoch 1/10
422/422 [==============================] - 62s 32ms/step - loss: 0.0303 - accuracy: 0.9918 - val_loss: 0.0868 - val_accuracy: 0.9758
Epoch 2/10
422/422 [==============================] - 3s 7ms/step - loss: 0.0244 - accuracy: 0.9936 - val_loss: 0.0875 - val_accuracy: 0.9752
Epoch 3/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0206 - accuracy: 0.9949 - val_loss: 0.0877 - val_accuracy: 0.9752
Epoch 4/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0166 - accuracy: 0.9961 - val_loss: 0.0859 - val_accuracy: 0.9767
Epoch 5/10
422/422 [==============================] - 3s 8ms/step - loss: 0.0141 - accuracy: 0.9969 - val_loss: 0.0912 - val_accuracy: 0.9762
Epoch 6/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0120 - accuracy: 0.9975 - val_loss: 0.0838 - val_accuracy: 0.9770
Epoch 7/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0092 - accuracy: 0.9984 - val_loss: 0.0867 - val_accuracy: 0.9763
Epoch 8/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0077 - accuracy: 0.9989 - val_loss: 0.0907 - val_accuracy: 0.9762
Epoch 9/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0065 - accuracy: 0.9992 - val_loss: 0.0918 - val_accuracy: 0.9767
Epoch 10/10
422/422 [==============================] - 3s 7ms/step - loss: 0.0073 - accuracy: 0.9986 - val_loss: 0.0974 - val_accuracy: 0.9745
188/188 [==============================] - 0s 2ms/step - loss: 0.0950 - accuracy: 0.9730
188/188 [==============================] - 1s 4ms/step - loss: 0.0974 - accuracy: 0.9745
188/188 [==============================] - 0s 2ms/step - loss: 0.0950 - accuracy: 0.9730
Test Accuracy: 0.9729999899864197
Task A Original Accuracy: 97.30%
Task B EWC method Accuracy: 97.45%
Epoch 1/10
422/422 [==============================] - 2s 4ms/step - loss: 0.3697 - accuracy: 0.8988 - val_loss: 0.2142 - val_accuracy: 0.9382
Epoch 2/10
422/422 [==============================] - 2s 4ms/step - loss: 0.1722 - accuracy: 0.9514 - val_loss: 0.1472 - val_accuracy: 0.9577
Epoch 3/10
422/422 [==============================] - 2s 5ms/step - loss: 0.1241 - accuracy: 0.9647 - val_loss: 0.1189 - val_accuracy: 0.9665
Epoch 4/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0985 - accuracy: 0.9721 - val_loss: 0.1074 - val_accuracy: 0.9672
Epoch 5/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0794 - accuracy: 0.9772 - val_loss: 0.0967 - val_accuracy: 0.9713
Epoch 6/10
422/422 [==============================] - 1s 3ms/step - loss: 0.0651 - accuracy: 0.9811 - val_loss: 0.0866 - val_accuracy: 0.9745
Epoch 7/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0542 - accuracy: 0.9843 - val_loss: 0.0863 - val_accuracy: 0.9735
Epoch 8/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0456 - accuracy: 0.9871 - val_loss: 0.0816 - val_accuracy: 0.9758
Epoch 9/10
422/422 [==============================] - 1s 4ms/step - loss: 0.0389 - accuracy: 0.9893 - val_loss: 0.0810 - val_accuracy: 0.9757
Epoch 10/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0329 - accuracy: 0.9911 - val_loss: 0.0775 - val_accuracy: 0.9760
Epoch 1/10
422/422 [==============================] - 62s 32ms/step - loss: 0.0301 - accuracy: 0.9919 - val_loss: 0.0770 - val_accuracy: 0.9765
Epoch 2/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0244 - accuracy: 0.9939 - val_loss: 0.0764 - val_accuracy: 0.9792
Epoch 3/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0200 - accuracy: 0.9950 - val_loss: 0.0760 - val_accuracy: 0.9793
Epoch 4/10
422/422 [==============================] - 3s 7ms/step - loss: 0.0163 - accuracy: 0.9963 - val_loss: 0.0720 - val_accuracy: 0.9795
Epoch 5/10
422/422 [==============================] - 2s 6ms/step - loss: 0.0137 - accuracy: 0.9973 - val_loss: 0.0773 - val_accuracy: 0.9783
Epoch 6/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0109 - accuracy: 0.9980 - val_loss: 0.0796 - val_accuracy: 0.9798
Epoch 7/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0097 - accuracy: 0.9982 - val_loss: 0.0761 - val_accuracy: 0.9795
Epoch 8/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0080 - accuracy: 0.9987 - val_loss: 0.0799 - val_accuracy: 0.9785
Epoch 9/10
422/422 [==============================] - 3s 6ms/step - loss: 0.0074 - accuracy: 0.9987 - val_loss: 0.0827 - val_accuracy: 0.9792
Epoch 10/10
422/422 [==============================] - 3s 7ms/step - loss: 0.0064 - accuracy: 0.9990 - val_loss: 0.0815 - val_accuracy: 0.9793
188/188 [==============================] - 0s 2ms/step - loss: 0.0775 - accuracy: 0.9760
188/188 [==============================] - 1s 4ms/step - loss: 0.0815 - accuracy: 0.9793
188/188 [==============================] - 1s 3ms/step - loss: 0.0775 - accuracy: 0.9760
Test Accuracy: 0.9760000109672546
Task A Original Accuracy: 97.60%
Task B EWC method Accuracy: 97.93%
Epoch 1/10
422/422 [==============================] - 2s 4ms/step - loss: 0.3690 - accuracy: 0.8983 - val_loss: 0.2396 - val_accuracy: 0.9337
Epoch 2/10
422/422 [==============================] - 2s 4ms/step - loss: 0.1719 - accuracy: 0.9512 - val_loss: 0.1826 - val_accuracy: 0.9478
Epoch 3/10
422/422 [==============================] - 2s 4ms/step - loss: 0.1226 - accuracy: 0.9651 - val_loss: 0.1408 - val_accuracy: 0.9580
Epoch 4/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0945 - accuracy: 0.9731 - val_loss: 0.1271 - val_accuracy: 0.9618
Epoch 5/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0759 - accuracy: 0.9782 - val_loss: 0.1125 - val_accuracy: 0.9658
Epoch 6/10
422/422 [==============================] - 1s 3ms/step - loss: 0.0640 - accuracy: 0.9816 - val_loss: 0.1025 - val_accuracy: 0.9713
Epoch 7/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0524 - accuracy: 0.9854 - val_loss: 0.1016 - val_accuracy: 0.9707
Epoch 8/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0434 - accuracy: 0.9877 - val_loss: 0.1030 - val_accuracy: 0.9702
Epoch 9/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0375 - accuracy: 0.9892 - val_loss: 0.0943 - val_accuracy: 0.9735
Epoch 10/10
422/422 [==============================] - 1s 4ms/step - loss: 0.0323 - accuracy: 0.9913 - val_loss: 0.0924 - val_accuracy: 0.9738
Epoch 1/10
422/422 [==============================] - 70s 49ms/step - loss: 0.0298 - accuracy: 0.9918 - val_loss: 0.0924 - val_accuracy: 0.9728
Epoch 2/10
422/422 [==============================] - 9s 21ms/step - loss: 0.0236 - accuracy: 0.9940 - val_loss: 0.1005 - val_accuracy: 0.9723
Epoch 3/10
422/422 [==============================] - 8s 18ms/step - loss: 0.0201 - accuracy: 0.9950 - val_loss: 0.1009 - val_accuracy: 0.9728
Epoch 4/10
422/422 [==============================] - 9s 21ms/step - loss: 0.0161 - accuracy: 0.9964 - val_loss: 0.0964 - val_accuracy: 0.9752
Epoch 5/10
422/422 [==============================] - 9s 21ms/step - loss: 0.0135 - accuracy: 0.9970 - val_loss: 0.0931 - val_accuracy: 0.9768
Epoch 6/10
422/422 [==============================] - 8s 19ms/step - loss: 0.0116 - accuracy: 0.9975 - val_loss: 0.0994 - val_accuracy: 0.9740
Epoch 7/10
422/422 [==============================] - 9s 21ms/step - loss: 0.0090 - accuracy: 0.9986 - val_loss: 0.1022 - val_accuracy: 0.9745
Epoch 8/10
422/422 [==============================] - 9s 21ms/step - loss: 0.0087 - accuracy: 0.9984 - val_loss: 0.1024 - val_accuracy: 0.9767
Epoch 9/10
422/422 [==============================] - 8s 19ms/step - loss: 0.0063 - accuracy: 0.9991 - val_loss: 0.0991 - val_accuracy: 0.9780
Epoch 10/10
422/422 [==============================] - 9s 20ms/step - loss: 0.0060 - accuracy: 0.9992 - val_loss: 0.1041 - val_accuracy: 0.9758
188/188 [==============================] - 1s 3ms/step - loss: 0.0924 - accuracy: 0.9738
188/188 [==============================] - 2s 12ms/step - loss: 0.1041 - accuracy: 0.9758
188/188 [==============================] - 0s 3ms/step - loss: 0.0924 - accuracy: 0.9738
Test Accuracy: 0.9738333225250244
Task A Original Accuracy: 97.38%
Task B EWC method Accuracy: 97.58%
Epoch 1/10
422/422 [==============================] - 3s 4ms/step - loss: 0.3812 - accuracy: 0.8946 - val_loss: 0.2024 - val_accuracy: 0.9420
Epoch 2/10
422/422 [==============================] - 1s 3ms/step - loss: 0.1769 - accuracy: 0.9496 - val_loss: 0.1476 - val_accuracy: 0.9575
Epoch 3/10
422/422 [==============================] - 1s 4ms/step - loss: 0.1293 - accuracy: 0.9626 - val_loss: 0.1216 - val_accuracy: 0.9647
Epoch 4/10
422/422 [==============================] - 1s 3ms/step - loss: 0.1027 - accuracy: 0.9701 - val_loss: 0.1058 - val_accuracy: 0.9680
Epoch 5/10
422/422 [==============================] - 1s 3ms/step - loss: 0.0829 - accuracy: 0.9756 - val_loss: 0.0980 - val_accuracy: 0.9707
Epoch 6/10
422/422 [==============================] - 1s 3ms/step - loss: 0.0690 - accuracy: 0.9807 - val_loss: 0.0876 - val_accuracy: 0.9715
Epoch 7/10
422/422 [==============================] - 1s 3ms/step - loss: 0.0583 - accuracy: 0.9831 - val_loss: 0.0851 - val_accuracy: 0.9730
Epoch 8/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0496 - accuracy: 0.9862 - val_loss: 0.0827 - val_accuracy: 0.9748
Epoch 9/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0416 - accuracy: 0.9884 - val_loss: 0.0839 - val_accuracy: 0.9742
Epoch 10/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0357 - accuracy: 0.9904 - val_loss: 0.0791 - val_accuracy: 0.9765
Epoch 1/10
422/422 [==============================] - 68s 44ms/step - loss: 0.0323 - accuracy: 0.9911 - val_loss: 0.0837 - val_accuracy: 0.9735
Epoch 2/10
422/422 [==============================] - 8s 20ms/step - loss: 0.0257 - accuracy: 0.9937 - val_loss: 0.0812 - val_accuracy: 0.9748
Epoch 3/10
422/422 [==============================] - 8s 20ms/step - loss: 0.0218 - accuracy: 0.9940 - val_loss: 0.0866 - val_accuracy: 0.9738
Epoch 4/10
422/422 [==============================] - 8s 18ms/step - loss: 0.0183 - accuracy: 0.9957 - val_loss: 0.0772 - val_accuracy: 0.9765
Epoch 5/10
422/422 [==============================] - 8s 20ms/step - loss: 0.0159 - accuracy: 0.9962 - val_loss: 0.0822 - val_accuracy: 0.9763
Epoch 6/10
422/422 [==============================] - 8s 20ms/step - loss: 0.0128 - accuracy: 0.9973 - val_loss: 0.0781 - val_accuracy: 0.9770
Epoch 7/10
422/422 [==============================] - 8s 18ms/step - loss: 0.0116 - accuracy: 0.9974 - val_loss: 0.0826 - val_accuracy: 0.9750
Epoch 8/10
422/422 [==============================] - 9s 20ms/step - loss: 0.0095 - accuracy: 0.9982 - val_loss: 0.0839 - val_accuracy: 0.9770
Epoch 9/10
422/422 [==============================] - 9s 20ms/step - loss: 0.0078 - accuracy: 0.9989 - val_loss: 0.0831 - val_accuracy: 0.9767
Epoch 10/10
422/422 [==============================] - 8s 18ms/step - loss: 0.0061 - accuracy: 0.9991 - val_loss: 0.0829 - val_accuracy: 0.9762
188/188 [==============================] - 0s 2ms/step - loss: 0.0791 - accuracy: 0.9765
188/188 [==============================] - 2s 12ms/step - loss: 0.0829 - accuracy: 0.9762
188/188 [==============================] - 1s 3ms/step - loss: 0.0791 - accuracy: 0.9765
Test Accuracy: 0.9764999747276306
Task A Original Accuracy: 97.65%
Task B EWC method Accuracy: 97.62%
Epoch 1/10
422/422 [==============================] - 2s 4ms/step - loss: 0.3837 - accuracy: 0.8932 - val_loss: 0.2257 - val_accuracy: 0.9377
Epoch 2/10
422/422 [==============================] - 1s 3ms/step - loss: 0.1740 - accuracy: 0.9507 - val_loss: 0.1680 - val_accuracy: 0.9498
Epoch 3/10
422/422 [==============================] - 1s 3ms/step - loss: 0.1268 - accuracy: 0.9634 - val_loss: 0.1384 - val_accuracy: 0.9597
Epoch 4/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0995 - accuracy: 0.9713 - val_loss: 0.1201 - val_accuracy: 0.9638
Epoch 5/10

### PermutedMNIST

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.regularizers import Regularizer
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import KFold
from tensorflow.keras import backend as K
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    f_accum = []
    for i in range(len(model.weights)):
        f_accum.append(np.zeros(K.int_shape(model.weights[i])))
    f_accum = np.array(f_accum)
    for _ in range(num_samples):
        idx = np.random.randint(0, x.shape[0])
        with tf.GradientTape() as tape:
            model_output = model(x[idx:idx+1])
        grads = tape.gradient(model_output, model.weights)
        for i in range(len(grads)):
            f_accum[i] += tf.square(grads[i])
    f_accum /= num_samples
    return f_accum

# Define the CrlB regularizer
class CrlBRegularizer(Regularizer):
    def __init__(self, fisher, prior_weights, lambda_=0.1):
        self.fisher = fisher
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i in range(len(self.fisher)):
            regularization += self.lambda_ * tf.reduce_sum(self.fisher[i] * tf.square(x - self.prior_weights[i]))
        return regularization


# Number of K-folds
K = 10

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)
# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []

# Perform K-fold cross-validation
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]

# Task A: Original Fashion MNIST model
    model = Sequential([
    Dense(128, activation='relu', input_shape=(784,)),
    Dense(10, activation='softmax')
])
    model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
    model.save_weights('FashionMNIST_A.h5')

# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]

# Task B: Fashion MNIST with CrlB regularization
    model_CrlBB = Sequential([
        Dense(128, activation='relu', input_shape=(784,), kernel_regularizer=CrlBRegularizer(fisher_info[0], model.weights[0])),
        Dense(10, activation='softmax', kernel_regularizer=CrlBRegularizer(fisher_info[1], model.weights[1]))
    ])
    model_CrlBB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    model_CrlBB.load_weights('FashionMNIST_A.h5')
    model_CrlBB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlB_acc = 100 * model_CrlBB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlB method Accuracy: %.2f%%" % B_CrlB_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
493/493 [==============================] - 6s 6ms/step - loss: 1.7501 - accuracy: 0.6032 - val_loss: 1.1205 - val_accuracy: 0.7503
Epoch 2/10
493/493 [==============================] - 3s 6ms/step - loss: 0.8440 - accuracy: 0.8074 - val_loss: 0.6659 - val_accuracy: 0.8409
Epoch 3/10
493/493 [==============================] - 2s 5ms/step - loss: 0.5712 - accuracy: 0.8581 - val_loss: 0.5075 - val_accuracy: 0.8684
Epoch 4/10
493/493 [==============================] - 2s 5ms/step - loss: 0.4604 - accuracy: 0.8806 - val_loss: 0.4308 - val_accuracy: 0.8860
Epoch 5/10
493/493 [==============================] - 2s 5ms/step - loss: 0.4027 - accuracy: 0.8923 - val_loss: 0.3885 - val_accuracy: 0.8959
Epoch 6/10
493/493 [==============================] - 3s 6ms/step - loss: 0.3682 - accuracy: 0.8991 - val_loss: 0.3619 - val_accuracy: 0.9004
Epoch 7/10
493/493 [==============================] - 3s 6ms/step - loss: 0.3457 - accuracy: 0.9037 - val_loss: 0.3442 - val_accuracy: 0.9040
Epoch 8/10
493/493 [==============================] - 2s 5ms/step - loss: 0.3292 - accuracy: 0.9067 - val_loss: 0.3335 - val_accuracy: 0.9056
Epoch 9/10
493/493 [==============================] - 2s 5ms/step - loss: 0.3166 - accuracy: 0.9095 - val_loss: 0.3209 - val_accuracy: 0.9097
Epoch 10/10
493/493 [==============================] - 2s 5ms/step - loss: 0.3068 - accuracy: 0.9125 - val_loss: 0.3118 - val_accuracy: 0.9120
Epoch 1/10
493/493 [==============================] - 117s 73ms/step - loss: 0.2984 - accuracy: 0.9149 - val_loss: 0.3050 - val_accuracy: 0.9121
Epoch 2/10
493/493 [==============================] - 17s 34ms/step - loss: 0.2912 - accuracy: 0.9170 - val_loss: 0.2996 - val_accuracy: 0.9131
Epoch 3/10
493/493 [==============================] - 17s 34ms/step - loss: 0.2850 - accuracy: 0.9179 - val_loss: 0.2943 - val_accuracy: 0.9139
Epoch 4/10
493/493 [==============================] - 17s 35ms/step - loss: 0.2789 - accuracy: 0.9196 - val_loss: 0.2894 - val_accuracy: 0.9169
Epoch 5/10
493/493 [==============================] - 16s 33ms/step - loss: 0.2737 - accuracy: 0.9211 - val_loss: 0.2840 - val_accuracy: 0.9189
Epoch 6/10
493/493 [==============================] - 17s 35ms/step - loss: 0.2690 - accuracy: 0.9224 - val_loss: 0.2802 - val_accuracy: 0.9179
Epoch 7/10
493/493 [==============================] - 17s 35ms/step - loss: 0.2641 - accuracy: 0.9241 - val_loss: 0.2773 - val_accuracy: 0.9200
Epoch 8/10
493/493 [==============================] - 17s 35ms/step - loss: 0.2596 - accuracy: 0.9255 - val_loss: 0.2721 - val_accuracy: 0.9194
Epoch 9/10
493/493 [==============================] - 17s 34ms/step - loss: 0.2550 - accuracy: 0.9265 - val_loss: 0.2682 - val_accuracy: 0.9216
Epoch 10/10
493/493 [==============================] - 17s 35ms/step - loss: 0.2507 - accuracy: 0.9278 - val_loss: 0.2647 - val_accuracy: 0.9227
219/219 [==============================] - 1s 2ms/step - loss: 0.3118 - accuracy: 0.9120
219/219 [==============================] - 3s 13ms/step - loss: 0.2647 - accuracy: 0.9227
219/219 [==============================] - 1s 2ms/step - loss: 0.3118 - accuracy: 0.9120
Test Accuracy: 0.9120000004768372
Task A Original Accuracy: 91.20%
Task B EWC method Accuracy: 92.27%
Epoch 1/10
493/493 [==============================] - 3s 4ms/step - loss: 1.7928 - accuracy: 0.5690 - val_loss: 1.1742 - val_accuracy: 0.7583
Epoch 2/10
493/493 [==============================] - 2s 5ms/step - loss: 0.8847 - accuracy: 0.8036 - val_loss: 0.6830 - val_accuracy: 0.8403
Epoch 3/10
493/493 [==============================] - 2s 3ms/step - loss: 0.5933 - accuracy: 0.8554 - val_loss: 0.5129 - val_accuracy: 0.8739
Epoch 4/10
493/493 [==============================] - 2s 3ms/step - loss: 0.4743 - accuracy: 0.8776 - val_loss: 0.4351 - val_accuracy: 0.8861
Epoch 5/10
493/493 [==============================] - 2s 3ms/step - loss: 0.4122 - accuracy: 0.8904 - val_loss: 0.3869 - val_accuracy: 0.8986
Epoch 6/10
493/493 [==============================] - 2s 3ms/step - loss: 0.3751 - accuracy: 0.8979 - val_loss: 0.3588 - val_accuracy: 0.9030
Epoch 7/10
493/493 [==============================] - 2s 3ms/step - loss: 0.3506 - accuracy: 0.9023 - val_loss: 0.3405 - val_accuracy: 0.9061
Epoch 8/10
493/493 [==============================] - 2s 3ms/step - loss: 0.3332 - accuracy: 0.9059 - val_loss: 0.3255 - val_accuracy: 0.9124
Epoch 9/10
493/493 [==============================] - 2s 4ms/step - loss: 0.3205 - accuracy: 0.9088 - val_loss: 0.3153 - val_accuracy: 0.9129
Epoch 10/10
493/493 [==============================] - 2s 4ms/step - loss: 0.3099 - accuracy: 0.9116 - val_loss: 0.3056 - val_accuracy: 0.9157
Epoch 1/10
493/493 [==============================] - 75s 46ms/step - loss: 0.3013 - accuracy: 0.9132 - val_loss: 0.2982 - val_accuracy: 0.9160
Epoch 2/10
493/493 [==============================] - 11s 21ms/step - loss: 0.2936 - accuracy: 0.9151 - val_loss: 0.2927 - val_accuracy: 0.9190
Epoch 3/10
493/493 [==============================] - 10s 21ms/step - loss: 0.2870 - accuracy: 0.9168 - val_loss: 0.2865 - val_accuracy: 0.9206
Epoch 4/10
493/493 [==============================] - 10s 21ms/step - loss: 0.2806 - accuracy: 0.9182 - val_loss: 0.2825 - val_accuracy: 0.9216
Epoch 5/10
493/493 [==============================] - 10s 21ms/step - loss: 0.2749 - accuracy: 0.9203 - val_loss: 0.2772 - val_accuracy: 0.9226
Epoch 6/10
493/493 [==============================] - 10s 20ms/step - loss: 0.2696 - accuracy: 0.9218 - val_loss: 0.2711 - val_accuracy: 0.9234
Epoch 7/10
493/493 [==============================] - 10s 21ms/step - loss: 0.2645 - accuracy: 0.9233 - val_loss: 0.2666 - val_accuracy: 0.9256
Epoch 8/10
493/493 [==============================] - 12s 24ms/step - loss: 0.2593 - accuracy: 0.9251 - val_loss: 0.2640 - val_accuracy: 0.9274
Epoch 9/10
493/493 [==============================] - 11s 22ms/step - loss: 0.2543 - accuracy: 0.9269 - val_loss: 0.2586 - val_accuracy: 0.9264
Epoch 10/10
493/493 [==============================] - 10s 21ms/step - loss: 0.2495 - accuracy: 0.9283 - val_loss: 0.2542 - val_accuracy: 0.9289
219/219 [==============================] - 1s 2ms/step - loss: 0.3056 - accuracy: 0.9157
219/219 [==============================] - 3s 13ms/step - loss: 0.2542 - accuracy: 0.9289
219/219 [==============================] - 1s 2ms/step - loss: 0.3056 - accuracy: 0.9157
Test Accuracy: 0.9157142639160156
Task A Original Accuracy: 91.57%
Task B EWC method Accuracy: 92.89%
Epoch 1/10
493/493 [==============================] - 3s 4ms/step - loss: 1.7462 - accuracy: 0.5978 - val_loss: 1.1232 - val_accuracy: 0.7457
Epoch 2/10
493/493 [==============================] - 2s 4ms/step - loss: 0.8540 - accuracy: 0.8053 - val_loss: 0.6775 - val_accuracy: 0.8371
Epoch 3/10
493/493 [==============================] - 2s 3ms/step - loss: 0.5760 - accuracy: 0.8585 - val_loss: 0.5148 - val_accuracy: 0.8679
Epoch 4/10
493/493 [==============================] - 2s 3ms/step - loss: 0.4599 - accuracy: 0.8821 - val_loss: 0.4382 - val_accuracy: 0.8833
Epoch 5/10
493/493 [==============================] - 2s 3ms/step - loss: 0.4009 - accuracy: 0.8924 - val_loss: 0.3934 - val_accuracy: 0.8899
Epoch 6/10
493/493 [==============================] - 2s 3ms/step - loss: 0.3660 - accuracy: 0.8994 - val_loss: 0.3667 - val_accuracy: 0.8986
Epoch 7/10
493/493 [==============================] - 2s 3ms/step - loss: 0.3434 - accuracy: 0.9041 - val_loss: 0.3485 - val_accuracy: 0.9023
Epoch 8/10
493/493 [==============================] - 2s 4ms/step - loss: 0.3275 - accuracy: 0.9079 - val_loss: 0.3345 - val_accuracy: 0.9050
Epoch 9/10
493/493 [==============================] - 2s 4ms/step - loss: 0.3153 - accuracy: 0.9107 - val_loss: 0.3235 - val_accuracy: 0.9080
Epoch 10/10
493/493 [==============================] - 2s 3ms/step - loss: 0.3052 - accuracy: 0.9125 - val_loss: 0.3147 - val_accuracy: 0.9109
Epoch 1/10
493/493 [==============================] - 65s 31ms/step - loss: 0.2971 - accuracy: 0.9147 - val_loss: 0.3083 - val_accuracy: 0.9120
Epoch 2/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2902 - accuracy: 0.9168 - val_loss: 0.3017 - val_accuracy: 0.9143
Epoch 3/10
493/493 [==============================] - 3s 7ms/step - loss: 0.2838 - accuracy: 0.9181 - val_loss: 0.2959 - val_accuracy: 0.9154
Epoch 4/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2779 - accuracy: 0.9197 - val_loss: 0.2904 - val_accuracy: 0.9161
Epoch 5/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2727 - accuracy: 0.9212 - val_loss: 0.2849 - val_accuracy: 0.9191
Epoch 6/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2677 - accuracy: 0.9223 - val_loss: 0.2808 - val_accuracy: 0.9197
Epoch 7/10
493/493 [==============================] - 3s 6ms/step - loss: 0.2628 - accuracy: 0.9237 - val_loss: 0.2772 - val_accuracy: 0.9210
Epoch 8/10
493/493 [==============================] - 3s 6ms/step - loss: 0.2582 - accuracy: 0.9256 - val_loss: 0.2713 - val_accuracy: 0.9227
Epoch 9/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2535 - accuracy: 0.9268 - val_loss: 0.2672 - val_accuracy: 0.9243
Epoch 10/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2487 - accuracy: 0.9283 - val_loss: 0.2626 - val_accuracy: 0.9243
219/219 [==============================] - 1s 2ms/step - loss: 0.3147 - accuracy: 0.9109
219/219 [==============================] - 1s 4ms/step - loss: 0.2626 - accuracy: 0.9243
219/219 [==============================] - 1s 3ms/step - loss: 0.3147 - accuracy: 0.9109
Test Accuracy: 0.9108571410179138
Task A Original Accuracy: 91.09%
Task B EWC method Accuracy: 92.43%
Epoch 1/10
493/493 [==============================] - 3s 4ms/step - loss: 1.7959 - accuracy: 0.5906 - val_loss: 1.1848 - val_accuracy: 0.7434
Epoch 2/10
493/493 [==============================] - 2s 3ms/step - loss: 0.8943 - accuracy: 0.7985 - val_loss: 0.7129 - val_accuracy: 0.8277
Epoch 3/10
493/493 [==============================] - 2s 3ms/step - loss: 0.6012 - accuracy: 0.8520 - val_loss: 0.5341 - val_accuracy: 0.8640
Epoch 4/10
493/493 [==============================] - 2s 3ms/step - loss: 0.4792 - accuracy: 0.8766 - val_loss: 0.4491 - val_accuracy: 0.8819
Epoch 5/10
493/493 [==============================] - 2s 3ms/step - loss: 0.4158 - accuracy: 0.8887 - val_loss: 0.4021 - val_accuracy: 0.8909
Epoch 6/10
493/493 [==============================] - 2s 3ms/step - loss: 0.3780 - accuracy: 0.8970 - val_loss: 0.3715 - val_accuracy: 0.8973
Epoch 7/10
493/493 [==============================] - 2s 5ms/step - loss: 0.3532 - accuracy: 0.9017 - val_loss: 0.3512 - val_accuracy: 0.9013
Epoch 8/10
493/493 [==============================] - 2s 3ms/step - loss: 0.3356 - accuracy: 0.9061 - val_loss: 0.3353 - val_accuracy: 0.9069
Epoch 9/10
493/493 [==============================] - 2s 3ms/step - loss: 0.3221 - accuracy: 0.9090 - val_loss: 0.3247 - val_accuracy: 0.9087
Epoch 10/10
493/493 [==============================] - 2s 3ms/step - loss: 0.3110 - accuracy: 0.9113 - val_loss: 0.3150 - val_accuracy: 0.9130
Epoch 1/10
493/493 [==============================] - 64s 31ms/step - loss: 0.3018 - accuracy: 0.9134 - val_loss: 0.3075 - val_accuracy: 0.9127
Epoch 2/10
493/493 [==============================] - 3s 6ms/step - loss: 0.2936 - accuracy: 0.9162 - val_loss: 0.2973 - val_accuracy: 0.9166
Epoch 3/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2864 - accuracy: 0.9174 - val_loss: 0.2910 - val_accuracy: 0.9163
Epoch 4/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2799 - accuracy: 0.9198 - val_loss: 0.2853 - val_accuracy: 0.9173
Epoch 5/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2740 - accuracy: 0.9214 - val_loss: 0.2789 - val_accuracy: 0.9189
Epoch 6/10
493/493 [==============================] - 3s 7ms/step - loss: 0.2681 - accuracy: 0.9226 - val_loss: 0.2741 - val_accuracy: 0.9197
Epoch 7/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2622 - accuracy: 0.9249 - val_loss: 0.2676 - val_accuracy: 0.9209
Epoch 8/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2567 - accuracy: 0.9261 - val_loss: 0.2639 - val_accuracy: 0.9219
Epoch 9/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2515 - accuracy: 0.9269 - val_loss: 0.2592 - val_accuracy: 0.9224
Epoch 10/10
493/493 [==============================] - 3s 7ms/step - loss: 0.2461 - accuracy: 0.9290 - val_loss: 0.2525 - val_accuracy: 0.9251
219/219 [==============================] - 1s 2ms/step - loss: 0.3150 - accuracy: 0.9130
219/219 [==============================] - 1s 4ms/step - loss: 0.2525 - accuracy: 0.9251
219/219 [==============================] - 1s 2ms/step - loss: 0.3150 - accuracy: 0.9130
Test Accuracy: 0.9129999876022339
Task A Original Accuracy: 91.30%
Task B EWC method Accuracy: 92.51%
Epoch 1/10
493/493 [==============================] - 3s 4ms/step - loss: 1.7854 - accuracy: 0.6085 - val_loss: 1.1697 - val_accuracy: 0.7444
Epoch 2/10
493/493 [==============================] - 2s 3ms/step - loss: 0.8789 - accuracy: 0.8045 - val_loss: 0.6855 - val_accuracy: 0.8391
Epoch 3/10
493/493 [==============================] - 2s 3ms/step - loss: 0.5871 - accuracy: 0.8560 - val_loss: 0.5159 - val_accuracy: 0.8727
Epoch 4/10
493/493 [==============================] - 2s 4ms/step - loss: 0.4694 - accuracy: 0.8785 - val_loss: 0.4369 - val_accuracy: 0.8869
Epoch 5/10
493/493 [==============================] - 2s 4ms/step - loss: 0.4085 - accuracy: 0.8901 - val_loss: 0.3922 - val_accuracy: 0.8950
Epoch 6/10
493/493 [==============================] - 2s 3ms/step - loss: 0.3723 - accuracy: 0.8978 - val_loss: 0.3642 - val_accuracy: 0.9013
Epoch 7/10
493/493 [==============================] - 2s 3ms/step - loss: 0.3486 - accuracy: 0.9025 - val_loss: 0.3441 - val_accuracy: 0.9070
Epoch 8/10
493/493 [==============================] - 2s 3ms/step - loss: 0.3317 - accuracy: 0.9065 - val_loss: 0.3297 - val_accuracy: 0.9091
Epoch 9/10
493/493 [==============================] - 2s 3ms/step - loss: 0.3187 - accuracy: 0.9091 - val_loss: 0.3189 - val_accuracy: 0.9113
Epoch 10/10
493/493 [==============================] - 2s 3ms/step - loss: 0.3086 - accuracy: 0.9120 - val_loss: 0.3099 - val_accuracy: 0.9126
Epoch 1/10
493/493 [==============================] - 64s 29ms/step - loss: 0.2999 - accuracy: 0.9135 - val_loss: 0.3019 - val_accuracy: 0.9146
Epoch 2/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2921 - accuracy: 0.9161 - val_loss: 0.2942 - val_accuracy: 0.9160
Epoch 3/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2850 - accuracy: 0.9177 - val_loss: 0.2889 - val_accuracy: 0.9173
Epoch 4/10
493/493 [==============================] - 3s 7ms/step - loss: 0.2788 - accuracy: 0.9197 - val_loss: 0.2826 - val_accuracy: 0.9184
Epoch 5/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2729 - accuracy: 0.9207 - val_loss: 0.2764 - val_accuracy: 0.9201
Epoch 6/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2672 - accuracy: 0.9220 - val_loss: 0.2706 - val_accuracy: 0.9229
Epoch 7/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2620 - accuracy: 0.9237 - val_loss: 0.2667 - val_accuracy: 0.9220
Epoch 8/10
493/493 [==============================] - 4s 7ms/step - loss: 0.2565 - accuracy: 0.9254 - val_loss: 0.2619 - val_accuracy: 0.9240
Epoch 9/10
493/493 [==============================] - 3s 6ms/step - loss: 0.2513 - accuracy: 0.9270 - val_loss: 0.2560 - val_accuracy: 0.9261
Epoch 10/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2462 - accuracy: 0.9289 - val_loss: 0.2523 - val_accuracy: 0.9266
219/219 [==============================] - 1s 3ms/step - loss: 0.3099 - accuracy: 0.9126
219/219 [==============================] - 1s 4ms/step - loss: 0.2523 - accuracy: 0.9266
219/219 [==============================] - 1s 2ms/step - loss: 0.3099 - accuracy: 0.9126
Test Accuracy: 0.9125714302062988
Task A Original Accuracy: 91.26%
Task B EWC method Accuracy: 92.66%
Epoch 1/10
493/493 [==============================] - 3s 5ms/step - loss: 1.7859 - accuracy: 0.5824 - val_loss: 1.1699 - val_accuracy: 0.7339
Epoch 2/10
493/493 [==============================] - 2s 3ms/step - loss: 0.8760 - accuracy: 0.8058 - val_loss: 0.6904 - val_accuracy: 0.8247
Epoch 3/10
493/493 [==============================] - 2s 3ms/step - loss: 0.5890 - accuracy: 0.8552 - val_loss: 0.5255 - val_accuracy: 0.8613
Epoch 4/10
493/493 [==============================] - 2s 3ms/step - loss: 0.4722 - accuracy: 0.8780 - val_loss: 0.4418 - val_accuracy: 0.8819
Epoch 5/10
493/493 [==============================] - 2s 3ms/step - loss: 0.4109 - accuracy: 0.8910 - val_loss: 0.3968 - val_accuracy: 0.8904
Epoch 6/10
493/493 [==============================] - 2s 4ms/step - loss: 0.3746 - accuracy: 0.8979 - val_loss: 0.3661 - val_accuracy: 0.8951
Epoch 7/10
493/493 [==============================] - 2s 4ms/step - loss: 0.3508 - accuracy: 0.9022 - val_loss: 0.3461 - val_accuracy: 0.8989
Epoch 8/10
493/493 [==============================] - 2s 4ms/step - loss: 0.3339 - accuracy: 0.9060 - val_loss: 0.3328 - val_accuracy: 0.9036
Epoch 9/10
493/493 [==============================] - 2s 4ms/step - loss: 0.3208 - accuracy: 0.9089 - val_loss: 0.3224 - val_accuracy: 0.9053
Epoch 10/10
493/493 [==============================] - 2s 3ms/step - loss: 0.3108 - accuracy: 0.9120 - val_loss: 0.3113 - val_accuracy: 0.9057
Epoch 1/10
493/493 [==============================] - 65s 29ms/step - loss: 0.3022 - accuracy: 0.9137 - val_loss: 0.3023 - val_accuracy: 0.9099
Epoch 2/10
493/493 [==============================] - 4s 7ms/step - loss: 0.2945 - accuracy: 0.9156 - val_loss: 0.2963 - val_accuracy: 0.9113
Epoch 3/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2878 - accuracy: 0.9176 - val_loss: 0.2905 - val_accuracy: 0.9143
Epoch 4/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2817 - accuracy: 0.9194 - val_loss: 0.2845 - val_accuracy: 0.9166
Epoch 5/10
493/493 [==============================] - 3s 6ms/step - loss: 0.2760 - accuracy: 0.9205 - val_loss: 0.2807 - val_accuracy: 0.9161
Epoch 6/10
493/493 [==============================] - 3s 7ms/step - loss: 0.2706 - accuracy: 0.9222 - val_loss: 0.2756 - val_accuracy: 0.9176
Epoch 7/10
493/493 [==============================] - 3s 6ms/step - loss: 0.2653 - accuracy: 0.9236 - val_loss: 0.2685 - val_accuracy: 0.9213
Epoch 8/10
493/493 [==============================] - 3s 6ms/step - loss: 0.2602 - accuracy: 0.9253 - val_loss: 0.2651 - val_accuracy: 0.9220
Epoch 9/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2553 - accuracy: 0.9267 - val_loss: 0.2597 - val_accuracy: 0.9226
Epoch 10/10
493/493 [==============================] - 3s 6ms/step - loss: 0.2502 - accuracy: 0.9279 - val_loss: 0.2559 - val_accuracy: 0.9246
219/219 [==============================] - 1s 3ms/step - loss: 0.3113 - accuracy: 0.9057
219/219 [==============================] - 1s 4ms/step - loss: 0.2559 - accuracy: 0.9246
219/219 [==============================] - 1s 3ms/step - loss: 0.3113 - accuracy: 0.9057
Test Accuracy: 0.9057142734527588
Task A Original Accuracy: 90.57%
Task B EWC method Accuracy: 92.46%
Epoch 1/10
493/493 [==============================] - 3s 4ms/step - loss: 1.7947 - accuracy: 0.6022 - val_loss: 1.1717 - val_accuracy: 0.7557
Epoch 2/10
493/493 [==============================] - 2s 3ms/step - loss: 0.8801 - accuracy: 0.8077 - val_loss: 0.6736 - val_accuracy: 0.8397
Epoch 3/10
493/493 [==============================] - 2s 3ms/step - loss: 0.5875 - accuracy: 0.8557 - val_loss: 0.5019 - val_accuracy: 0.8754
Epoch 4/10
493/493 [==============================] - 2s 4ms/step - loss: 0.4708 - accuracy: 0.8785 - val_loss: 0.4233 - val_accuracy: 0.8909
Epoch 5/10

### FashionMNIST

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.regularizers import Regularizer
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import KFold
from tensorflow.keras import backend as K
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    f_accum = []
    for i in range(len(model.weights)):
        f_accum.append(np.zeros(K.int_shape(model.weights[i])))
    f_accum = np.array(f_accum)
    for _ in range(num_samples):
        idx = np.random.randint(0, x.shape[0])
        with tf.GradientTape() as tape:
            model_output = model(x[idx:idx+1])
        grads = tape.gradient(model_output, model.weights)
        for i in range(len(grads)):
            f_accum[i] += tf.square(grads[i])
    f_accum /= num_samples
    return f_accum

# Define the CrlB regularizer
class CrlBRegularizer(Regularizer):
    def __init__(self, fisher, prior_weights, lambda_=0.1):
        self.fisher = fisher
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i in range(len(self.fisher)):
            regularization += self.lambda_ * tf.reduce_sum(self.fisher[i] * tf.square(x - self.prior_weights[i]))
        return regularization


# Number of K-folds
K = 10

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)
# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []

# Perform K-fold cross-validation
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]

# Task A: Original Fashion MNIST model
    model = Sequential([
    Dense(128, activation='relu', input_shape=(784,)),
    Dense(10, activation='softmax')
])
    model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
    model.save_weights('FashionMNIST_A.h5')

# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]

# Task B: Fashion MNIST with CrlB regularization
    model_CrlBB = Sequential([
        Dense(128, activation='relu', input_shape=(784,), kernel_regularizer=CrlBRegularizer(fisher_info[0], model.weights[0])),
        Dense(10, activation='softmax', kernel_regularizer=CrlBRegularizer(fisher_info[1], model.weights[1]))
    ])
    model_CrlBB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    model_CrlBB.load_weights('FashionMNIST_A.h5')
    model_CrlBB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlB_acc = 100 * model_CrlBB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlB method Accuracy: %.2f%%" % B_CrlB_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
493/493 [==============================] - 4s 6ms/step - loss: 0.5438 - accuracy: 0.8137 - val_loss: 0.4183 - val_accuracy: 0.8501
Epoch 2/10
493/493 [==============================] - 3s 6ms/step - loss: 0.4053 - accuracy: 0.8575 - val_loss: 0.4131 - val_accuracy: 0.8527
Epoch 3/10
493/493 [==============================] - 2s 5ms/step - loss: 0.3677 - accuracy: 0.8696 - val_loss: 0.3610 - val_accuracy: 0.8677
Epoch 4/10
493/493 [==============================] - 2s 5ms/step - loss: 0.3397 - accuracy: 0.8784 - val_loss: 0.3394 - val_accuracy: 0.8801
Epoch 5/10
493/493 [==============================] - 2s 5ms/step - loss: 0.3223 - accuracy: 0.8837 - val_loss: 0.3243 - val_accuracy: 0.8816
Epoch 6/10
493/493 [==============================] - 3s 5ms/step - loss: 0.3098 - accuracy: 0.8882 - val_loss: 0.3260 - val_accuracy: 0.8819
Epoch 7/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2969 - accuracy: 0.8921 - val_loss: 0.3121 - val_accuracy: 0.8884
Epoch 8/10
493/493 [==============================] - 2s 5ms/step - loss: 0.2834 - accuracy: 0.8972 - val_loss: 0.3104 - val_accuracy: 0.8906
Epoch 9/10
493/493 [==============================] - 2s 5ms/step - loss: 0.2756 - accuracy: 0.8983 - val_loss: 0.3077 - val_accuracy: 0.8904
Epoch 10/10
493/493 [==============================] - 2s 4ms/step - loss: 0.2670 - accuracy: 0.9027 - val_loss: 0.3109 - val_accuracy: 0.8897
Epoch 1/10
493/493 [==============================] - 104s 48ms/step - loss: 0.2594 - accuracy: 0.9053 - val_loss: 0.2982 - val_accuracy: 0.8906
Epoch 2/10
493/493 [==============================] - 4s 8ms/step - loss: 0.2505 - accuracy: 0.9087 - val_loss: 0.3027 - val_accuracy: 0.8904
Epoch 3/10
493/493 [==============================] - 4s 8ms/step - loss: 0.2433 - accuracy: 0.9113 - val_loss: 0.2997 - val_accuracy: 0.8911
Epoch 4/10
493/493 [==============================] - 5s 10ms/step - loss: 0.2360 - accuracy: 0.9126 - val_loss: 0.2901 - val_accuracy: 0.8976
Epoch 5/10
493/493 [==============================] - 4s 8ms/step - loss: 0.2296 - accuracy: 0.9162 - val_loss: 0.3063 - val_accuracy: 0.8909
Epoch 6/10
493/493 [==============================] - 4s 8ms/step - loss: 0.2255 - accuracy: 0.9175 - val_loss: 0.3070 - val_accuracy: 0.8886
Epoch 7/10
493/493 [==============================] - 5s 9ms/step - loss: 0.2204 - accuracy: 0.9198 - val_loss: 0.2988 - val_accuracy: 0.8899
Epoch 8/10
493/493 [==============================] - 4s 8ms/step - loss: 0.2148 - accuracy: 0.9209 - val_loss: 0.2945 - val_accuracy: 0.8971
Epoch 9/10
493/493 [==============================] - 4s 8ms/step - loss: 0.2083 - accuracy: 0.9238 - val_loss: 0.3515 - val_accuracy: 0.8803
Epoch 10/10
493/493 [==============================] - 5s 10ms/step - loss: 0.2048 - accuracy: 0.9251 - val_loss: 0.2937 - val_accuracy: 0.8981
219/219 [==============================] - 1s 4ms/step - loss: 0.3109 - accuracy: 0.8897
219/219 [==============================] - 2s 7ms/step - loss: 0.2937 - accuracy: 0.8981
219/219 [==============================] - 1s 5ms/step - loss: 0.3109 - accuracy: 0.8897
Test Accuracy: 0.8897143006324768
Task A Original Accuracy: 88.97%
Task B EWC method Accuracy: 89.81%
Epoch 1/10
493/493 [==============================] - 4s 5ms/step - loss: 0.5506 - accuracy: 0.8095 - val_loss: 0.4479 - val_accuracy: 0.8456
Epoch 2/10
493/493 [==============================] - 2s 5ms/step - loss: 0.4062 - accuracy: 0.8573 - val_loss: 0.3838 - val_accuracy: 0.8681
Epoch 3/10
493/493 [==============================] - 2s 5ms/step - loss: 0.3630 - accuracy: 0.8720 - val_loss: 0.3636 - val_accuracy: 0.8696
Epoch 4/10
493/493 [==============================] - 3s 6ms/step - loss: 0.3350 - accuracy: 0.8807 - val_loss: 0.3486 - val_accuracy: 0.8777
Epoch 5/10
493/493 [==============================] - 2s 5ms/step - loss: 0.3177 - accuracy: 0.8858 - val_loss: 0.3354 - val_accuracy: 0.8819
Epoch 6/10
493/493 [==============================] - 2s 4ms/step - loss: 0.3046 - accuracy: 0.8906 - val_loss: 0.3248 - val_accuracy: 0.8833
Epoch 7/10
493/493 [==============================] - 2s 4ms/step - loss: 0.2901 - accuracy: 0.8940 - val_loss: 0.3234 - val_accuracy: 0.8880
Epoch 8/10
493/493 [==============================] - 2s 5ms/step - loss: 0.2800 - accuracy: 0.8975 - val_loss: 0.3210 - val_accuracy: 0.8856
Epoch 9/10
493/493 [==============================] - 3s 6ms/step - loss: 0.2708 - accuracy: 0.9014 - val_loss: 0.3330 - val_accuracy: 0.8860
Epoch 10/10
493/493 [==============================] - 2s 5ms/step - loss: 0.2635 - accuracy: 0.9032 - val_loss: 0.3121 - val_accuracy: 0.8931
Epoch 1/10
493/493 [==============================] - 82s 31ms/step - loss: 0.2564 - accuracy: 0.9054 - val_loss: 0.3188 - val_accuracy: 0.8920
Epoch 2/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2496 - accuracy: 0.9081 - val_loss: 0.3096 - val_accuracy: 0.8900
Epoch 3/10
493/493 [==============================] - 3s 6ms/step - loss: 0.2409 - accuracy: 0.9111 - val_loss: 0.3130 - val_accuracy: 0.8951
Epoch 4/10
493/493 [==============================] - 3s 6ms/step - loss: 0.2350 - accuracy: 0.9129 - val_loss: 0.3186 - val_accuracy: 0.8850
Epoch 5/10
493/493 [==============================] - 3s 7ms/step - loss: 0.2287 - accuracy: 0.9139 - val_loss: 0.3047 - val_accuracy: 0.8940
Epoch 6/10
493/493 [==============================] - 3s 6ms/step - loss: 0.2225 - accuracy: 0.9180 - val_loss: 0.3032 - val_accuracy: 0.8937
Epoch 7/10
493/493 [==============================] - 3s 6ms/step - loss: 0.2179 - accuracy: 0.9204 - val_loss: 0.2988 - val_accuracy: 0.8971
Epoch 8/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2148 - accuracy: 0.9206 - val_loss: 0.3068 - val_accuracy: 0.8947
Epoch 9/10
493/493 [==============================] - 3s 7ms/step - loss: 0.2039 - accuracy: 0.9255 - val_loss: 0.2999 - val_accuracy: 0.8986
Epoch 10/10
493/493 [==============================] - 3s 6ms/step - loss: 0.2017 - accuracy: 0.9257 - val_loss: 0.2981 - val_accuracy: 0.9010
219/219 [==============================] - 1s 2ms/step - loss: 0.3121 - accuracy: 0.8931
219/219 [==============================] - 1s 4ms/step - loss: 0.2981 - accuracy: 0.9010
219/219 [==============================] - 1s 2ms/step - loss: 0.3121 - accuracy: 0.8931
Test Accuracy: 0.8931428790092468
Task A Original Accuracy: 89.31%
Task B EWC method Accuracy: 90.10%
Epoch 1/10
493/493 [==============================] - 3s 4ms/step - loss: 0.5481 - accuracy: 0.8123 - val_loss: 0.4505 - val_accuracy: 0.8393
Epoch 2/10
493/493 [==============================] - 2s 3ms/step - loss: 0.4059 - accuracy: 0.8573 - val_loss: 0.3936 - val_accuracy: 0.8580
Epoch 3/10
493/493 [==============================] - 2s 4ms/step - loss: 0.3659 - accuracy: 0.8701 - val_loss: 0.3615 - val_accuracy: 0.8684
Epoch 4/10
493/493 [==============================] - 2s 4ms/step - loss: 0.3400 - accuracy: 0.8774 - val_loss: 0.4091 - val_accuracy: 0.8480
Epoch 5/10
493/493 [==============================] - 2s 3ms/step - loss: 0.3223 - accuracy: 0.8839 - val_loss: 0.3864 - val_accuracy: 0.8520
Epoch 6/10
493/493 [==============================] - 2s 3ms/step - loss: 0.3036 - accuracy: 0.8906 - val_loss: 0.3252 - val_accuracy: 0.8776
Epoch 7/10
493/493 [==============================] - 2s 3ms/step - loss: 0.2927 - accuracy: 0.8927 - val_loss: 0.3219 - val_accuracy: 0.8776
Epoch 8/10
493/493 [==============================] - 2s 3ms/step - loss: 0.2816 - accuracy: 0.8977 - val_loss: 0.3103 - val_accuracy: 0.8833
Epoch 9/10
493/493 [==============================] - 2s 3ms/step - loss: 0.2712 - accuracy: 0.9001 - val_loss: 0.3095 - val_accuracy: 0.8837
Epoch 10/10
493/493 [==============================] - 2s 5ms/step - loss: 0.2630 - accuracy: 0.9032 - val_loss: 0.2997 - val_accuracy: 0.8853
Epoch 1/10
493/493 [==============================] - 65s 29ms/step - loss: 0.2559 - accuracy: 0.9066 - val_loss: 0.3088 - val_accuracy: 0.8857
Epoch 2/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2457 - accuracy: 0.9099 - val_loss: 0.2962 - val_accuracy: 0.8873
Epoch 3/10
493/493 [==============================] - 4s 7ms/step - loss: 0.2411 - accuracy: 0.9120 - val_loss: 0.2978 - val_accuracy: 0.8879
Epoch 4/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2336 - accuracy: 0.9140 - val_loss: 0.3111 - val_accuracy: 0.8827
Epoch 5/10
493/493 [==============================] - 3s 6ms/step - loss: 0.2273 - accuracy: 0.9158 - val_loss: 0.3023 - val_accuracy: 0.8853
Epoch 6/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2216 - accuracy: 0.9185 - val_loss: 0.3145 - val_accuracy: 0.8826
Epoch 7/10
493/493 [==============================] - 4s 7ms/step - loss: 0.2159 - accuracy: 0.9212 - val_loss: 0.3088 - val_accuracy: 0.8876
Epoch 8/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2107 - accuracy: 0.9224 - val_loss: 0.3057 - val_accuracy: 0.8840
Epoch 9/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2072 - accuracy: 0.9235 - val_loss: 0.2962 - val_accuracy: 0.8900
Epoch 10/10
493/493 [==============================] - 3s 6ms/step - loss: 0.2014 - accuracy: 0.9259 - val_loss: 0.3143 - val_accuracy: 0.8857
219/219 [==============================] - 1s 3ms/step - loss: 0.2997 - accuracy: 0.8853
219/219 [==============================] - 1s 4ms/step - loss: 0.3143 - accuracy: 0.8857
219/219 [==============================] - 1s 3ms/step - loss: 0.2997 - accuracy: 0.8853
Test Accuracy: 0.8852857351303101
Task A Original Accuracy: 88.53%
Task B EWC method Accuracy: 88.57%
Epoch 1/10
493/493 [==============================] - 3s 4ms/step - loss: 0.5525 - accuracy: 0.8105 - val_loss: 0.4326 - val_accuracy: 0.8466
Epoch 2/10
493/493 [==============================] - 2s 3ms/step - loss: 0.4003 - accuracy: 0.8592 - val_loss: 0.4579 - val_accuracy: 0.8291
Epoch 3/10
493/493 [==============================] - 2s 4ms/step - loss: 0.3654 - accuracy: 0.8699 - val_loss: 0.3697 - val_accuracy: 0.8713
Epoch 4/10
493/493 [==============================] - 2s 3ms/step - loss: 0.3379 - accuracy: 0.8783 - val_loss: 0.3497 - val_accuracy: 0.8771
Epoch 5/10
493/493 [==============================] - 2s 3ms/step - loss: 0.3232 - accuracy: 0.8831 - val_loss: 0.3323 - val_accuracy: 0.8824
Epoch 6/10
493/493 [==============================] - 2s 4ms/step - loss: 0.3036 - accuracy: 0.8896 - val_loss: 0.3276 - val_accuracy: 0.8834
Epoch 7/10
493/493 [==============================] - 2s 4ms/step - loss: 0.2936 - accuracy: 0.8931 - val_loss: 0.3275 - val_accuracy: 0.8837
Epoch 8/10
493/493 [==============================] - 2s 3ms/step - loss: 0.2809 - accuracy: 0.8977 - val_loss: 0.3227 - val_accuracy: 0.8863
Epoch 9/10
493/493 [==============================] - 2s 3ms/step - loss: 0.2733 - accuracy: 0.9007 - val_loss: 0.3135 - val_accuracy: 0.8871
Epoch 10/10
493/493 [==============================] - 2s 4ms/step - loss: 0.2641 - accuracy: 0.9035 - val_loss: 0.3077 - val_accuracy: 0.8897
Epoch 1/10
493/493 [==============================] - 65s 29ms/step - loss: 0.2574 - accuracy: 0.9063 - val_loss: 0.3059 - val_accuracy: 0.8911
Epoch 2/10
493/493 [==============================] - 3s 7ms/step - loss: 0.2489 - accuracy: 0.9089 - val_loss: 0.3235 - val_accuracy: 0.8850
Epoch 3/10
493/493 [==============================] - 3s 6ms/step - loss: 0.2421 - accuracy: 0.9111 - val_loss: 0.3106 - val_accuracy: 0.8904
Epoch 4/10
493/493 [==============================] - 3s 6ms/step - loss: 0.2357 - accuracy: 0.9142 - val_loss: 0.2977 - val_accuracy: 0.8931
Epoch 5/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2276 - accuracy: 0.9163 - val_loss: 0.3509 - val_accuracy: 0.8826
Epoch 6/10
493/493 [==============================] - 4s 7ms/step - loss: 0.2225 - accuracy: 0.9181 - val_loss: 0.3107 - val_accuracy: 0.8903
Epoch 7/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2147 - accuracy: 0.9215 - val_loss: 0.3053 - val_accuracy: 0.8907
Epoch 8/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2103 - accuracy: 0.9221 - val_loss: 0.2896 - val_accuracy: 0.8957
Epoch 9/10
493/493 [==============================] - 3s 6ms/step - loss: 0.2051 - accuracy: 0.9250 - val_loss: 0.2948 - val_accuracy: 0.8989
Epoch 10/10
493/493 [==============================] - 4s 7ms/step - loss: 0.2015 - accuracy: 0.9266 - val_loss: 0.2873 - val_accuracy: 0.9031
219/219 [==============================] - 1s 3ms/step - loss: 0.3077 - accuracy: 0.8897
219/219 [==============================] - 1s 4ms/step - loss: 0.2873 - accuracy: 0.9031
219/219 [==============================] - 1s 3ms/step - loss: 0.3077 - accuracy: 0.8897
Test Accuracy: 0.8897143006324768
Task A Original Accuracy: 88.97%
Task B EWC method Accuracy: 90.31%
Epoch 1/10
493/493 [==============================] - 3s 4ms/step - loss: 0.5471 - accuracy: 0.8102 - val_loss: 0.4425 - val_accuracy: 0.8429
Epoch 2/10
493/493 [==============================] - 2s 3ms/step - loss: 0.4045 - accuracy: 0.8583 - val_loss: 0.3904 - val_accuracy: 0.8623
Epoch 3/10
493/493 [==============================] - 2s 3ms/step - loss: 0.3656 - accuracy: 0.8705 - val_loss: 0.3500 - val_accuracy: 0.8814
Epoch 4/10
493/493 [==============================] - 2s 3ms/step - loss: 0.3378 - accuracy: 0.8795 - val_loss: 0.3540 - val_accuracy: 0.8751
Epoch 5/10
493/493 [==============================] - 2s 3ms/step - loss: 0.3167 - accuracy: 0.8858 - val_loss: 0.3455 - val_accuracy: 0.8737
Epoch 6/10
493/493 [==============================] - 2s 3ms/step - loss: 0.3038 - accuracy: 0.8904 - val_loss: 0.3443 - val_accuracy: 0.8763
Epoch 7/10
493/493 [==============================] - 2s 5ms/step - loss: 0.2928 - accuracy: 0.8939 - val_loss: 0.3148 - val_accuracy: 0.8904
Epoch 8/10
493/493 [==============================] - 2s 4ms/step - loss: 0.2807 - accuracy: 0.8979 - val_loss: 0.3128 - val_accuracy: 0.8909
Epoch 9/10
493/493 [==============================] - 2s 3ms/step - loss: 0.2713 - accuracy: 0.9008 - val_loss: 0.3119 - val_accuracy: 0.8911
Epoch 10/10
493/493 [==============================] - 2s 3ms/step - loss: 0.2642 - accuracy: 0.9035 - val_loss: 0.3102 - val_accuracy: 0.8914
Epoch 1/10
493/493 [==============================] - 65s 30ms/step - loss: 0.2544 - accuracy: 0.9068 - val_loss: 0.3363 - val_accuracy: 0.8853
Epoch 2/10
493/493 [==============================] - 3s 6ms/step - loss: 0.2483 - accuracy: 0.9092 - val_loss: 0.3073 - val_accuracy: 0.8909
Epoch 3/10
493/493 [==============================] - 3s 6ms/step - loss: 0.2392 - accuracy: 0.9115 - val_loss: 0.3158 - val_accuracy: 0.8863
Epoch 4/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2337 - accuracy: 0.9142 - val_loss: 0.2983 - val_accuracy: 0.8977
Epoch 5/10
493/493 [==============================] - 3s 6ms/step - loss: 0.2270 - accuracy: 0.9162 - val_loss: 0.2935 - val_accuracy: 0.8974
Epoch 6/10
493/493 [==============================] - 3s 7ms/step - loss: 0.2222 - accuracy: 0.9170 - val_loss: 0.3043 - val_accuracy: 0.8954
Epoch 7/10
493/493 [==============================] - 3s 6ms/step - loss: 0.2150 - accuracy: 0.9215 - val_loss: 0.3033 - val_accuracy: 0.8994
Epoch 8/10
493/493 [==============================] - 3s 6ms/step - loss: 0.2098 - accuracy: 0.9225 - val_loss: 0.3015 - val_accuracy: 0.8934
Epoch 9/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2051 - accuracy: 0.9253 - val_loss: 0.3011 - val_accuracy: 0.8999
Epoch 10/10
493/493 [==============================] - 4s 7ms/step - loss: 0.2013 - accuracy: 0.9256 - val_loss: 0.3044 - val_accuracy: 0.8980
219/219 [==============================] - 1s 3ms/step - loss: 0.3102 - accuracy: 0.8914
219/219 [==============================] - 1s 4ms/step - loss: 0.3044 - accuracy: 0.8980
219/219 [==============================] - 1s 2ms/step - loss: 0.3102 - accuracy: 0.8914
Test Accuracy: 0.8914285898208618
Task A Original Accuracy: 89.14%
Task B EWC method Accuracy: 89.80%
Epoch 1/10
493/493 [==============================] - 3s 4ms/step - loss: 0.5582 - accuracy: 0.8072 - val_loss: 0.4351 - val_accuracy: 0.8510
Epoch 2/10
493/493 [==============================] - 2s 3ms/step - loss: 0.4036 - accuracy: 0.8573 - val_loss: 0.4213 - val_accuracy: 0.8476
Epoch 3/10
493/493 [==============================] - 2s 4ms/step - loss: 0.3632 - accuracy: 0.8709 - val_loss: 0.3727 - val_accuracy: 0.8670
Epoch 4/10
493/493 [==============================] - 2s 5ms/step - loss: 0.3392 - accuracy: 0.8785 - val_loss: 0.3463 - val_accuracy: 0.8761
Epoch 5/10
493/493 [==============================] - 2s 3ms/step - loss: 0.3204 - accuracy: 0.8851 - val_loss: 0.3430 - val_accuracy: 0.8793
Epoch 6/10
493/493 [==============================] - 2s 3ms/step - loss: 0.3013 - accuracy: 0.8905 - val_loss: 0.3473 - val_accuracy: 0.8761
Epoch 7/10
493/493 [==============================] - 2s 3ms/step - loss: 0.2910 - accuracy: 0.8935 - val_loss: 0.3315 - val_accuracy: 0.8800
Epoch 8/10
493/493 [==============================] - 2s 3ms/step - loss: 0.2794 - accuracy: 0.8973 - val_loss: 0.3281 - val_accuracy: 0.8797
Epoch 9/10
493/493 [==============================] - 2s 3ms/step - loss: 0.2699 - accuracy: 0.9006 - val_loss: 0.3128 - val_accuracy: 0.8859
Epoch 10/10
493/493 [==============================] - 2s 4ms/step - loss: 0.2607 - accuracy: 0.9038 - val_loss: 0.3205 - val_accuracy: 0.8854
Epoch 1/10
493/493 [==============================] - 65s 29ms/step - loss: 0.2533 - accuracy: 0.9070 - val_loss: 0.3087 - val_accuracy: 0.8893
Epoch 2/10
493/493 [==============================] - 3s 6ms/step - loss: 0.2455 - accuracy: 0.9097 - val_loss: 0.3285 - val_accuracy: 0.8827
Epoch 3/10
493/493 [==============================] - 4s 7ms/step - loss: 0.2377 - accuracy: 0.9127 - val_loss: 0.3206 - val_accuracy: 0.8841
Epoch 4/10
493/493 [==============================] - 3s 6ms/step - loss: 0.2306 - accuracy: 0.9149 - val_loss: 0.3176 - val_accuracy: 0.8866
Epoch 5/10
493/493 [==============================] - 3s 5ms/step - loss: 0.2272 - accuracy: 0.9161 - val_loss: 0.3069 - val_accuracy: 0.8927
Epoch 6/10
493/493 [==============================] - 3s 6ms/step - loss: 0.2200 - accuracy: 0.9187 - val_loss: 0.3195 - val_accuracy: 0.8879
Epoch 7/10
493/493 [==============================] - 3s 7ms/step - loss: 0.2133 - accuracy: 0.9219 - val_loss: 0.3261 - val_accuracy: 0.8846
Epoch 8/10
493/493 [==============================] - 3s 6ms/step - loss: 0.2085 - accuracy: 0.9241 - val_loss: 0.3116 - val_accuracy: 0.8913
Epoch 9/10
493/493 [==============================] - 3s 6ms/step - loss: 0.2025 - accuracy: 0.9260 - val_loss: 0.3326 - val_accuracy: 0.8846
Epoch 10/10
493/493 [==============================] - 3s 5ms/step - loss: 0.1998 - accuracy: 0.9278 - val_loss: 0.3249 - val_accuracy: 0.8927
219/219 [==============================] - 1s 2ms/step - loss: 0.3205 - accuracy: 0.8854
219/219 [==============================] - 1s 4ms/step - loss: 0.3249 - accuracy: 0.8927
219/219 [==============================] - 1s 4ms/step - loss: 0.3205 - accuracy: 0.8854
Test Accuracy: 0.8854285478591919
Task A Original Accuracy: 88.54%
Task B EWC method Accuracy: 89.27%
Epoch 1/10
493/493 [==============================] - 3s 4ms/step - loss: 0.5578 - accuracy: 0.8087 - val_loss: 0.4504 - val_accuracy: 0.8394
Epoch 2/10
493/493 [==============================] - 2s 3ms/step - loss: 0.4126 - accuracy: 0.8548 - val_loss: 0.3868 - val_accuracy: 0.8629
Epoch 3/10
493/493 [==============================] - 2s 3ms/step - loss: 0.3724 - accuracy: 0.8676 - val_loss: 0.3577 - val_accuracy: 0.8729
Epoch 4/10
493/493 [==============================] - 2s 4ms/step - loss: 0.3460 - accuracy: 0.8762 - val_loss: 0.3673 - val_accuracy: 0.8676
Epoch 5/10
493/493 [==============================] - 2s 3ms/step - loss: 0.3276 - accuracy: 0.8818 - val_loss: 0.3321 - val_accuracy: 0.8833

### Kuzushiji-MNIST

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.regularizers import Regularizer
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import KFold
from tensorflow.keras import backend as K
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    f_accum = []
    for i in range(len(model.weights)):
        f_accum.append(np.zeros(K.int_shape(model.weights[i])))
    f_accum = np.array(f_accum)
    for _ in range(num_samples):
        idx = np.random.randint(0, x.shape[0])
        with tf.GradientTape() as tape:
            model_output = model(x[idx:idx+1])
        grads = tape.gradient(model_output, model.weights)
        for i in range(len(grads)):
            f_accum[i] += tf.square(grads[i])
    f_accum /= num_samples
    return f_accum

# Define the CrlB regularizer
class CrlBRegularizer(Regularizer):
    def __init__(self, fisher, prior_weights, lambda_=0.1):
        self.fisher = fisher
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i in range(len(self.fisher)):
            regularization += self.lambda_ * tf.reduce_sum(self.fisher[i] * tf.square(x - self.prior_weights[i]))
        return regularization


# Number of K-folds
K = 10

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)
# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []

# Perform K-fold cross-validation
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]

# Task A: Original Fashion MNIST model
    model = Sequential([
    Dense(128, activation='relu', input_shape=(784,)),
    Dense(10, activation='softmax')
])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model = model
        model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
        model.save_weights('FashionMNIST_A.h5')

# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]

# Task B: Fashion MNIST with CrlB regularization
    model_CrlBB = Sequential([
        Dense(128, activation='relu', input_shape=(784,), kernel_regularizer=CrlBRegularizer(fisher_info[0], model.weights[0])),
        Dense(10, activation='softmax', kernel_regularizer=CrlBRegularizer(fisher_info[1], model.weights[1]))
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model_CrlBB = model_CrlBB
        model_CrlBB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model_CrlBB.load_weights('FashionMNIST_A.h5')
        model_CrlBB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlB_acc = 100 * model_CrlBB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlB method Accuracy: %.2f%%" % B_CrlB_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
493/493 [==============================] - 4s 5ms/step - loss: 0.5479 - accuracy: 0.8367 - val_loss: 0.3490 - val_accuracy: 0.8934
Epoch 2/10
493/493 [==============================] - 3s 6ms/step - loss: 0.2849 - accuracy: 0.9179 - val_loss: 0.2632 - val_accuracy: 0.9220
Epoch 3/10
493/493 [==============================] - 2s 5ms/step - loss: 0.2096 - accuracy: 0.9408 - val_loss: 0.2228 - val_accuracy: 0.9337
Epoch 4/10
493/493 [==============================] - 2s 4ms/step - loss: 0.1674 - accuracy: 0.9533 - val_loss: 0.1995 - val_accuracy: 0.9406
Epoch 5/10
493/493 [==============================] - 2s 5ms/step - loss: 0.1373 - accuracy: 0.9617 - val_loss: 0.1842 - val_accuracy: 0.9471
Epoch 6/10
493/493 [==============================] - 2s 4ms/step - loss: 0.1154 - accuracy: 0.9683 - val_loss: 0.1812 - val_accuracy: 0.9493
Epoch 7/10
493/493 [==============================] - 3s 6ms/step - loss: 0.0972 - accuracy: 0.9740 - val_loss: 0.1793 - val_accuracy: 0.9499
Epoch 8/10
493/493 [==============================] - 2s 5ms/step - loss: 0.0824 - accuracy: 0.9776 - val_loss: 0.1911 - val_accuracy: 0.9444
Epoch 9/10
493/493 [==============================] - 2s 5ms/step - loss: 0.0693 - accuracy: 0.9815 - val_loss: 0.1771 - val_accuracy: 0.9496
Epoch 10/10
493/493 [==============================] - 2s 5ms/step - loss: 0.0581 - accuracy: 0.9858 - val_loss: 0.1852 - val_accuracy: 0.9486
Epoch 1/10
493/493 [==============================] - 98s 48ms/step - loss: 0.0543 - accuracy: 0.9854 - val_loss: 0.1843 - val_accuracy: 0.9527
Epoch 2/10
493/493 [==============================] - 4s 7ms/step - loss: 0.0417 - accuracy: 0.9904 - val_loss: 0.2000 - val_accuracy: 0.9507
Epoch 3/10
493/493 [==============================] - 4s 9ms/step - loss: 0.0350 - accuracy: 0.9920 - val_loss: 0.1889 - val_accuracy: 0.9511
Epoch 4/10
493/493 [==============================] - 4s 8ms/step - loss: 0.0289 - accuracy: 0.9940 - val_loss: 0.1947 - val_accuracy: 0.9513
Epoch 5/10
493/493 [==============================] - 4s 7ms/step - loss: 0.0237 - accuracy: 0.9955 - val_loss: 0.2023 - val_accuracy: 0.9491
Epoch 6/10
493/493 [==============================] - 4s 8ms/step - loss: 0.0191 - accuracy: 0.9967 - val_loss: 0.2097 - val_accuracy: 0.9510
Epoch 7/10
493/493 [==============================] - 4s 8ms/step - loss: 0.0165 - accuracy: 0.9972 - val_loss: 0.2124 - val_accuracy: 0.9517
Epoch 8/10
493/493 [==============================] - 4s 8ms/step - loss: 0.0145 - accuracy: 0.9976 - val_loss: 0.2184 - val_accuracy: 0.9500
Epoch 9/10
493/493 [==============================] - 4s 8ms/step - loss: 0.0171 - accuracy: 0.9960 - val_loss: 0.2159 - val_accuracy: 0.9514
Epoch 10/10
493/493 [==============================] - 4s 9ms/step - loss: 0.0097 - accuracy: 0.9987 - val_loss: 0.2297 - val_accuracy: 0.9500
219/219 [==============================] - 1s 3ms/step - loss: 0.1852 - accuracy: 0.9486
219/219 [==============================] - 1s 6ms/step - loss: 0.2297 - accuracy: 0.9500
219/219 [==============================] - 1s 3ms/step - loss: 0.1852 - accuracy: 0.9486
Test Accuracy: 0.9485714435577393
Task A Original Accuracy: 94.86%
Task B EWC method Accuracy: 95.00%
Epoch 1/10
493/493 [==============================] - 5s 7ms/step - loss: 0.5426 - accuracy: 0.8381 - val_loss: 0.3580 - val_accuracy: 0.8943
Epoch 2/10
493/493 [==============================] - 2s 4ms/step - loss: 0.2779 - accuracy: 0.9199 - val_loss: 0.2679 - val_accuracy: 0.9244
Epoch 3/10
493/493 [==============================] - 2s 4ms/step - loss: 0.2015 - accuracy: 0.9436 - val_loss: 0.2271 - val_accuracy: 0.9351
Epoch 4/10
493/493 [==============================] - 2s 4ms/step - loss: 0.1601 - accuracy: 0.9542 - val_loss: 0.2100 - val_accuracy: 0.9434
Epoch 5/10
493/493 [==============================] - 2s 4ms/step - loss: 0.1304 - accuracy: 0.9637 - val_loss: 0.2017 - val_accuracy: 0.9444
Epoch 6/10
493/493 [==============================] - 3s 6ms/step - loss: 0.1093 - accuracy: 0.9702 - val_loss: 0.1955 - val_accuracy: 0.9456
Epoch 7/10
493/493 [==============================] - 2s 4ms/step - loss: 0.0924 - accuracy: 0.9747 - val_loss: 0.1951 - val_accuracy: 0.9471
Epoch 8/10
493/493 [==============================] - 2s 4ms/step - loss: 0.0775 - accuracy: 0.9795 - val_loss: 0.1885 - val_accuracy: 0.9489
Epoch 9/10
493/493 [==============================] - 2s 4ms/step - loss: 0.0650 - accuracy: 0.9829 - val_loss: 0.1984 - val_accuracy: 0.9481
Epoch 10/10
493/493 [==============================] - 2s 4ms/step - loss: 0.0556 - accuracy: 0.9859 - val_loss: 0.1934 - val_accuracy: 0.9469
Epoch 1/10
493/493 [==============================] - 60s 26ms/step - loss: 0.0510 - accuracy: 0.9868 - val_loss: 0.2096 - val_accuracy: 0.9444
Epoch 2/10
493/493 [==============================] - 3s 5ms/step - loss: 0.0396 - accuracy: 0.9902 - val_loss: 0.2137 - val_accuracy: 0.9494
Epoch 3/10
493/493 [==============================] - 3s 6ms/step - loss: 0.0327 - accuracy: 0.9924 - val_loss: 0.2082 - val_accuracy: 0.9470
Epoch 4/10
493/493 [==============================] - 3s 6ms/step - loss: 0.0286 - accuracy: 0.9940 - val_loss: 0.2173 - val_accuracy: 0.9463
Epoch 5/10
493/493 [==============================] - 3s 5ms/step - loss: 0.0229 - accuracy: 0.9954 - val_loss: 0.2259 - val_accuracy: 0.9464
Epoch 6/10
493/493 [==============================] - 3s 5ms/step - loss: 0.0186 - accuracy: 0.9968 - val_loss: 0.2281 - val_accuracy: 0.9460
Epoch 7/10
493/493 [==============================] - 3s 5ms/step - loss: 0.0150 - accuracy: 0.9977 - val_loss: 0.2387 - val_accuracy: 0.9481
Epoch 8/10
493/493 [==============================] - 3s 6ms/step - loss: 0.0158 - accuracy: 0.9973 - val_loss: 0.2560 - val_accuracy: 0.9456
Epoch 9/10
493/493 [==============================] - 3s 5ms/step - loss: 0.0119 - accuracy: 0.9981 - val_loss: 0.2482 - val_accuracy: 0.9449
Epoch 10/10
493/493 [==============================] - 3s 5ms/step - loss: 0.0113 - accuracy: 0.9982 - val_loss: 0.2716 - val_accuracy: 0.9434
219/219 [==============================] - 1s 2ms/step - loss: 0.1934 - accuracy: 0.9469
219/219 [==============================] - 1s 4ms/step - loss: 0.2716 - accuracy: 0.9434
219/219 [==============================] - 1s 2ms/step - loss: 0.1934 - accuracy: 0.9469
Test Accuracy: 0.9468571543693542
Task A Original Accuracy: 94.69%
Task B EWC method Accuracy: 94.34%
Epoch 1/10
493/493 [==============================] - 3s 4ms/step - loss: 0.5480 - accuracy: 0.8368 - val_loss: 0.3646 - val_accuracy: 0.8899
Epoch 2/10
493/493 [==============================] - 2s 3ms/step - loss: 0.2917 - accuracy: 0.9142 - val_loss: 0.2794 - val_accuracy: 0.9164
Epoch 3/10
493/493 [==============================] - 2s 4ms/step - loss: 0.2127 - accuracy: 0.9390 - val_loss: 0.2328 - val_accuracy: 0.9304
Epoch 4/10
493/493 [==============================] - 2s 4ms/step - loss: 0.1670 - accuracy: 0.9523 - val_loss: 0.2117 - val_accuracy: 0.9387
Epoch 5/10
493/493 [==============================] - 2s 3ms/step - loss: 0.1371 - accuracy: 0.9615 - val_loss: 0.2081 - val_accuracy: 0.9389
Epoch 6/10
493/493 [==============================] - 2s 3ms/step - loss: 0.1150 - accuracy: 0.9676 - val_loss: 0.1982 - val_accuracy: 0.9399
Epoch 7/10
493/493 [==============================] - 2s 4ms/step - loss: 0.0956 - accuracy: 0.9736 - val_loss: 0.1990 - val_accuracy: 0.9391
Epoch 8/10
493/493 [==============================] - 2s 3ms/step - loss: 0.0810 - accuracy: 0.9782 - val_loss: 0.1961 - val_accuracy: 0.9429
Epoch 9/10
493/493 [==============================] - 2s 3ms/step - loss: 0.0689 - accuracy: 0.9818 - val_loss: 0.1940 - val_accuracy: 0.9447
Epoch 10/10
493/493 [==============================] - 2s 3ms/step - loss: 0.0590 - accuracy: 0.9850 - val_loss: 0.1961 - val_accuracy: 0.9473
Epoch 1/10
493/493 [==============================] - 60s 29ms/step - loss: 0.0540 - accuracy: 0.9852 - val_loss: 0.2134 - val_accuracy: 0.9444
Epoch 2/10
493/493 [==============================] - 3s 5ms/step - loss: 0.0436 - accuracy: 0.9891 - val_loss: 0.1999 - val_accuracy: 0.9447
Epoch 3/10
493/493 [==============================] - 2s 5ms/step - loss: 0.0355 - accuracy: 0.9918 - val_loss: 0.2209 - val_accuracy: 0.9441
Epoch 4/10
493/493 [==============================] - 3s 5ms/step - loss: 0.0288 - accuracy: 0.9938 - val_loss: 0.2285 - val_accuracy: 0.9461
Epoch 5/10
493/493 [==============================] - 3s 5ms/step - loss: 0.0236 - accuracy: 0.9954 - val_loss: 0.2200 - val_accuracy: 0.9447
Epoch 6/10
493/493 [==============================] - 3s 6ms/step - loss: 0.0201 - accuracy: 0.9962 - val_loss: 0.2272 - val_accuracy: 0.9479
Epoch 7/10
493/493 [==============================] - 3s 5ms/step - loss: 0.0166 - accuracy: 0.9972 - val_loss: 0.2422 - val_accuracy: 0.9439
Epoch 8/10
493/493 [==============================] - 3s 5ms/step - loss: 0.0156 - accuracy: 0.9972 - val_loss: 0.2477 - val_accuracy: 0.9453
Epoch 9/10
493/493 [==============================] - 3s 5ms/step - loss: 0.0129 - accuracy: 0.9978 - val_loss: 0.2586 - val_accuracy: 0.9429
Epoch 10/10
493/493 [==============================] - 3s 6ms/step - loss: 0.0114 - accuracy: 0.9982 - val_loss: 0.2602 - val_accuracy: 0.9460
219/219 [==============================] - 1s 2ms/step - loss: 0.1961 - accuracy: 0.9473
219/219 [==============================] - 1s 4ms/step - loss: 0.2602 - accuracy: 0.9460
219/219 [==============================] - 1s 2ms/step - loss: 0.1961 - accuracy: 0.9473
Test Accuracy: 0.9472857117652893
Task A Original Accuracy: 94.73%
Task B EWC method Accuracy: 94.60%
Epoch 1/10
493/493 [==============================] - 3s 4ms/step - loss: 0.5426 - accuracy: 0.8397 - val_loss: 0.3470 - val_accuracy: 0.8964
Epoch 2/10
493/493 [==============================] - 2s 3ms/step - loss: 0.2859 - accuracy: 0.9165 - val_loss: 0.2680 - val_accuracy: 0.9193
Epoch 3/10
493/493 [==============================] - 2s 4ms/step - loss: 0.2121 - accuracy: 0.9396 - val_loss: 0.2293 - val_accuracy: 0.9336
Epoch 4/10
493/493 [==============================] - 2s 4ms/step - loss: 0.1676 - accuracy: 0.9527 - val_loss: 0.2044 - val_accuracy: 0.9419
Epoch 5/10
493/493 [==============================] - 2s 3ms/step - loss: 0.1370 - accuracy: 0.9617 - val_loss: 0.1890 - val_accuracy: 0.9453
Epoch 6/10
493/493 [==============================] - 2s 3ms/step - loss: 0.1141 - accuracy: 0.9678 - val_loss: 0.1887 - val_accuracy: 0.9441
Epoch 7/10
493/493 [==============================] - 2s 3ms/step - loss: 0.0959 - accuracy: 0.9741 - val_loss: 0.1818 - val_accuracy: 0.9486
Epoch 8/10
493/493 [==============================] - 2s 3ms/step - loss: 0.0799 - accuracy: 0.9790 - val_loss: 0.1841 - val_accuracy: 0.9493
Epoch 9/10
493/493 [==============================] - 2s 3ms/step - loss: 0.0666 - accuracy: 0.9829 - val_loss: 0.1960 - val_accuracy: 0.9450
Epoch 10/10
493/493 [==============================] - 2s 4ms/step - loss: 0.0569 - accuracy: 0.9856 - val_loss: 0.1879 - val_accuracy: 0.9481
Epoch 1/10
493/493 [==============================] - 71s 48ms/step - loss: 0.0517 - accuracy: 0.9864 - val_loss: 0.1895 - val_accuracy: 0.9497
Epoch 2/10
493/493 [==============================] - 11s 22ms/step - loss: 0.0401 - accuracy: 0.9904 - val_loss: 0.1978 - val_accuracy: 0.9490
Epoch 3/10
493/493 [==============================] - 12s 23ms/step - loss: 0.0339 - accuracy: 0.9924 - val_loss: 0.1987 - val_accuracy: 0.9473
Epoch 4/10
493/493 [==============================] - 11s 22ms/step - loss: 0.0275 - accuracy: 0.9940 - val_loss: 0.2061 - val_accuracy: 0.9497
Epoch 5/10
493/493 [==============================] - 12s 23ms/step - loss: 0.0219 - accuracy: 0.9959 - val_loss: 0.2126 - val_accuracy: 0.9484
Epoch 6/10
493/493 [==============================] - 12s 23ms/step - loss: 0.0192 - accuracy: 0.9966 - val_loss: 0.2166 - val_accuracy: 0.9489
Epoch 7/10
493/493 [==============================] - 12s 23ms/step - loss: 0.0157 - accuracy: 0.9974 - val_loss: 0.2197 - val_accuracy: 0.9476
Epoch 8/10
493/493 [==============================] - 11s 22ms/step - loss: 0.0124 - accuracy: 0.9983 - val_loss: 0.2350 - val_accuracy: 0.9461
Epoch 9/10
493/493 [==============================] - 11s 22ms/step - loss: 0.0119 - accuracy: 0.9983 - val_loss: 0.2329 - val_accuracy: 0.9461
Epoch 10/10
493/493 [==============================] - 11s 23ms/step - loss: 0.0133 - accuracy: 0.9972 - val_loss: 0.2512 - val_accuracy: 0.9479
219/219 [==============================] - 1s 2ms/step - loss: 0.1879 - accuracy: 0.9481
219/219 [==============================] - 3s 13ms/step - loss: 0.2512 - accuracy: 0.9479
219/219 [==============================] - 1s 2ms/step - loss: 0.1879 - accuracy: 0.9481
Test Accuracy: 0.9481428861618042
Task A Original Accuracy: 94.81%
Task B EWC method Accuracy: 94.79%
Epoch 1/10
493/493 [==============================] - 3s 4ms/step - loss: 0.5438 - accuracy: 0.8368 - val_loss: 0.3405 - val_accuracy: 0.9006
Epoch 2/10
493/493 [==============================] - 2s 3ms/step - loss: 0.2854 - accuracy: 0.9171 - val_loss: 0.2580 - val_accuracy: 0.9237
Epoch 3/10
493/493 [==============================] - 2s 3ms/step - loss: 0.2120 - accuracy: 0.9398 - val_loss: 0.2126 - val_accuracy: 0.9354
Epoch 4/10
493/493 [==============================] - 2s 3ms/step - loss: 0.1677 - accuracy: 0.9523 - val_loss: 0.2075 - val_accuracy: 0.9351
Epoch 5/10
493/493 [==============================] - 2s 3ms/step - loss: 0.1387 - accuracy: 0.9614 - val_loss: 0.1824 - val_accuracy: 0.9454
Epoch 6/10
493/493 [==============================] - 2s 3ms/step - loss: 0.1165 - accuracy: 0.9665 - val_loss: 0.1796 - val_accuracy: 0.9451
Epoch 7/10
493/493 [==============================] - 2s 3ms/step - loss: 0.0971 - accuracy: 0.9733 - val_loss: 0.1744 - val_accuracy: 0.9466
Epoch 8/10
493/493 [==============================] - 2s 4ms/step - loss: 0.0815 - accuracy: 0.9777 - val_loss: 0.1746 - val_accuracy: 0.9464
Epoch 9/10
493/493 [==============================] - 2s 3ms/step - loss: 0.0691 - accuracy: 0.9816 - val_loss: 0.1733 - val_accuracy: 0.9459
Epoch 10/10
493/493 [==============================] - 2s 3ms/step - loss: 0.0580 - accuracy: 0.9852 - val_loss: 0.1719 - val_accuracy: 0.9486
Epoch 1/10
493/493 [==============================] - 60s 28ms/step - loss: 0.0531 - accuracy: 0.9861 - val_loss: 0.1780 - val_accuracy: 0.9463
Epoch 2/10
493/493 [==============================] - 3s 5ms/step - loss: 0.0413 - accuracy: 0.9900 - val_loss: 0.1894 - val_accuracy: 0.9471
Epoch 3/10
493/493 [==============================] - 3s 5ms/step - loss: 0.0351 - accuracy: 0.9917 - val_loss: 0.1826 - val_accuracy: 0.9497
Epoch 4/10
493/493 [==============================] - 3s 5ms/step - loss: 0.0286 - accuracy: 0.9936 - val_loss: 0.1927 - val_accuracy: 0.9474
Epoch 5/10
493/493 [==============================] - 3s 5ms/step - loss: 0.0238 - accuracy: 0.9950 - val_loss: 0.1856 - val_accuracy: 0.9499
Epoch 6/10
493/493 [==============================] - 3s 6ms/step - loss: 0.0196 - accuracy: 0.9962 - val_loss: 0.2054 - val_accuracy: 0.9463
Epoch 7/10
493/493 [==============================] - 3s 5ms/step - loss: 0.0174 - accuracy: 0.9967 - val_loss: 0.2003 - val_accuracy: 0.9483
Epoch 8/10
493/493 [==============================] - 3s 5ms/step - loss: 0.0136 - accuracy: 0.9980 - val_loss: 0.2073 - val_accuracy: 0.9476
Epoch 9/10
493/493 [==============================] - 3s 5ms/step - loss: 0.0099 - accuracy: 0.9990 - val_loss: 0.2020 - val_accuracy: 0.9504
Epoch 10/10
493/493 [==============================] - 3s 6ms/step - loss: 0.0111 - accuracy: 0.9982 - val_loss: 0.2182 - val_accuracy: 0.9503
219/219 [==============================] - 1s 3ms/step - loss: 0.1719 - accuracy: 0.9486
219/219 [==============================] - 1s 4ms/step - loss: 0.2182 - accuracy: 0.9503
219/219 [==============================] - 1s 2ms/step - loss: 0.1719 - accuracy: 0.9486
Test Accuracy: 0.9485714435577393
Task A Original Accuracy: 94.86%
Task B EWC method Accuracy: 95.03%
Epoch 1/10
493/493 [==============================] - 3s 4ms/step - loss: 0.5456 - accuracy: 0.8357 - val_loss: 0.3632 - val_accuracy: 0.8893
Epoch 2/10
493/493 [==============================] - 2s 4ms/step - loss: 0.2864 - accuracy: 0.9161 - val_loss: 0.2650 - val_accuracy: 0.9191
Epoch 3/10
493/493 [==============================] - 2s 4ms/step - loss: 0.2128 - accuracy: 0.9376 - val_loss: 0.2252 - val_accuracy: 0.9327
Epoch 4/10
493/493 [==============================] - 2s 3ms/step - loss: 0.1672 - accuracy: 0.9526 - val_loss: 0.2145 - val_accuracy: 0.9339
Epoch 5/10
493/493 [==============================] - 2s 3ms/step - loss: 0.1366 - accuracy: 0.9620 - val_loss: 0.1962 - val_accuracy: 0.9427
Epoch 6/10
493/493 [==============================] - 2s 3ms/step - loss: 0.1123 - accuracy: 0.9688 - val_loss: 0.1940 - val_accuracy: 0.9427
Epoch 7/10
493/493 [==============================] - 2s 3ms/step - loss: 0.0944 - accuracy: 0.9738 - val_loss: 0.1903 - val_accuracy: 0.9451
Epoch 8/10
493/493 [==============================] - 2s 3ms/step - loss: 0.0786 - accuracy: 0.9786 - val_loss: 0.1879 - val_accuracy: 0.9477
Epoch 9/10
493/493 [==============================] - 2s 4ms/step - loss: 0.0667 - accuracy: 0.9821 - val_loss: 0.1918 - val_accuracy: 0.9473
Epoch 10/10
493/493 [==============================] - 2s 3ms/step - loss: 0.0564 - accuracy: 0.9851 - val_loss: 0.1894 - val_accuracy: 0.9480
Epoch 1/10
493/493 [==============================] - 70s 47ms/step - loss: 0.0500 - accuracy: 0.9868 - val_loss: 0.2102 - val_accuracy: 0.9436
Epoch 2/10
493/493 [==============================] - 12s 25ms/step - loss: 0.0415 - accuracy: 0.9894 - val_loss: 0.2061 - val_accuracy: 0.9480
Epoch 3/10
493/493 [==============================] - 12s 24ms/step - loss: 0.0325 - accuracy: 0.9926 - val_loss: 0.2082 - val_accuracy: 0.9474
Epoch 4/10
493/493 [==============================] - 12s 24ms/step - loss: 0.0266 - accuracy: 0.9946 - val_loss: 0.2073 - val_accuracy: 0.9474
Epoch 5/10
493/493 [==============================] - 12s 24ms/step - loss: 0.0213 - accuracy: 0.9959 - val_loss: 0.2142 - val_accuracy: 0.9469
Epoch 6/10
493/493 [==============================] - 12s 23ms/step - loss: 0.0185 - accuracy: 0.9966 - val_loss: 0.2243 - val_accuracy: 0.9474
Epoch 7/10
493/493 [==============================] - 12s 24ms/step - loss: 0.0156 - accuracy: 0.9973 - val_loss: 0.2437 - val_accuracy: 0.9457
Epoch 8/10
493/493 [==============================] - 12s 24ms/step - loss: 0.0134 - accuracy: 0.9980 - val_loss: 0.2453 - val_accuracy: 0.9454
Epoch 9/10
493/493 [==============================] - 12s 24ms/step - loss: 0.0119 - accuracy: 0.9981 - val_loss: 0.2417 - val_accuracy: 0.9474
Epoch 10/10
493/493 [==============================] - 12s 23ms/step - loss: 0.0109 - accuracy: 0.9982 - val_loss: 0.2568 - val_accuracy: 0.9459
219/219 [==============================] - 1s 3ms/step - loss: 0.1894 - accuracy: 0.9480
219/219 [==============================] - 3s 15ms/step - loss: 0.2568 - accuracy: 0.9459
219/219 [==============================] - 1s 2ms/step - loss: 0.1894 - accuracy: 0.9480
Test Accuracy: 0.9480000138282776
Task A Original Accuracy: 94.80%
Task B EWC method Accuracy: 94.59%
Epoch 1/10
493/493 [==============================] - 3s 4ms/step - loss: 0.5491 - accuracy: 0.8365 - val_loss: 0.3724 - val_accuracy: 0.8887
Epoch 2/10
493/493 [==============================] - 2s 3ms/step - loss: 0.2882 - accuracy: 0.9146 - val_loss: 0.2817 - val_accuracy: 0.9173
Epoch 3/10
493/493 [==============================] - 2s 3ms/step - loss: 0.2171 - accuracy: 0.9383 - val_loss: 0.2329 - val_accuracy: 0.9321
Epoch 4/10
493/493 [==============================] - 2s 4ms/step - loss: 0.1722 - accuracy: 0.9506 - val_loss: 0.2155 - val_accuracy: 0.9379
Epoch 5/10

### MNIST-C

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.regularizers import Regularizer
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import KFold
from tensorflow.keras import backend as K
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    f_accum = []
    for i in range(len(model.weights)):
        f_accum.append(np.zeros(K.int_shape(model.weights[i])))
    f_accum = np.array(f_accum)
    for _ in range(num_samples):
        idx = np.random.randint(0, x.shape[0])
        with tf.GradientTape() as tape:
            model_output = model(x[idx:idx+1])
        grads = tape.gradient(model_output, model.weights)
        for i in range(len(grads)):
            f_accum[i] += tf.square(grads[i])
    f_accum /= num_samples
    return f_accum

# Define the CrlB regularizer
class CrlBRegularizer(Regularizer):
    def __init__(self, fisher, prior_weights, lambda_=0.1):
        self.fisher = fisher
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i in range(len(self.fisher)):
            regularization += self.lambda_ * tf.reduce_sum(self.fisher[i] * tf.square(x - self.prior_weights[i]))
        return regularization


# Number of K-folds
K = 10

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)
# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []

# Perform K-fold cross-validation
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]

# Task A: Original Fashion MNIST model
    model = Sequential([
    Dense(128, activation='relu', input_shape=(784,)),
    Dense(10, activation='softmax')
])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model = model
        model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
        model.save_weights('FashionMNIST_A.h5')

# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]

# Task B: Fashion MNIST with CrlB regularization
    model_CrlBB = Sequential([
        Dense(128, activation='relu', input_shape=(784,), kernel_regularizer=CrlBRegularizer(fisher_info[0], model.weights[0])),
        Dense(10, activation='softmax', kernel_regularizer=CrlBRegularizer(fisher_info[1], model.weights[1]))
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model_CrlBB = model_CrlBB
        model_CrlBB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model_CrlBB.load_weights('FashionMNIST_A.h5')
        model_CrlBB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlB_acc = 100 * model_CrlBB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlB method Accuracy: %.2f%%" % B_CrlB_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
422/422 [==============================] - 5s 7ms/step - loss: 0.3732 - accuracy: 0.9003 - val_loss: 0.2105 - val_accuracy: 0.9390
Epoch 2/10
422/422 [==============================] - 2s 5ms/step - loss: 0.1738 - accuracy: 0.9510 - val_loss: 0.1533 - val_accuracy: 0.9585
Epoch 3/10
422/422 [==============================] - 2s 5ms/step - loss: 0.1257 - accuracy: 0.9637 - val_loss: 0.1248 - val_accuracy: 0.9663
Epoch 4/10
422/422 [==============================] - 3s 7ms/step - loss: 0.0975 - accuracy: 0.9711 - val_loss: 0.1101 - val_accuracy: 0.9685
Epoch 5/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0778 - accuracy: 0.9772 - val_loss: 0.0967 - val_accuracy: 0.9727
Epoch 6/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0635 - accuracy: 0.9819 - val_loss: 0.0881 - val_accuracy: 0.9752
Epoch 7/10
422/422 [==============================] - 2s 6ms/step - loss: 0.0535 - accuracy: 0.9845 - val_loss: 0.0911 - val_accuracy: 0.9737
Epoch 8/10
422/422 [==============================] - 3s 6ms/step - loss: 0.0453 - accuracy: 0.9872 - val_loss: 0.0820 - val_accuracy: 0.9753
Epoch 9/10
422/422 [==============================] - 3s 7ms/step - loss: 0.0382 - accuracy: 0.9898 - val_loss: 0.0802 - val_accuracy: 0.9775
Epoch 10/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0319 - accuracy: 0.9911 - val_loss: 0.0768 - val_accuracy: 0.9782
Epoch 1/10
422/422 [==============================] - 141s 70ms/step - loss: 0.0295 - accuracy: 0.9915 - val_loss: 0.0808 - val_accuracy: 0.9785
Epoch 2/10
422/422 [==============================] - 4s 9ms/step - loss: 0.0243 - accuracy: 0.9932 - val_loss: 0.0846 - val_accuracy: 0.9783
Epoch 3/10
422/422 [==============================] - 5s 12ms/step - loss: 0.0205 - accuracy: 0.9949 - val_loss: 0.0791 - val_accuracy: 0.9805
Epoch 4/10
422/422 [==============================] - 3s 8ms/step - loss: 0.0172 - accuracy: 0.9961 - val_loss: 0.0796 - val_accuracy: 0.9795
Epoch 5/10
422/422 [==============================] - 3s 8ms/step - loss: 0.0139 - accuracy: 0.9970 - val_loss: 0.0771 - val_accuracy: 0.9795
Epoch 6/10
422/422 [==============================] - 4s 10ms/step - loss: 0.0116 - accuracy: 0.9978 - val_loss: 0.0809 - val_accuracy: 0.9788
Epoch 7/10
422/422 [==============================] - 3s 8ms/step - loss: 0.0100 - accuracy: 0.9982 - val_loss: 0.0774 - val_accuracy: 0.9798
Epoch 8/10
422/422 [==============================] - 3s 8ms/step - loss: 0.0084 - accuracy: 0.9984 - val_loss: 0.0775 - val_accuracy: 0.9803
Epoch 9/10
422/422 [==============================] - 3s 8ms/step - loss: 0.0068 - accuracy: 0.9989 - val_loss: 0.0822 - val_accuracy: 0.9787
Epoch 10/10
422/422 [==============================] - 4s 9ms/step - loss: 0.0061 - accuracy: 0.9991 - val_loss: 0.0767 - val_accuracy: 0.9805
188/188 [==============================] - 1s 3ms/step - loss: 0.0768 - accuracy: 0.9782
188/188 [==============================] - 1s 6ms/step - loss: 0.0767 - accuracy: 0.9805
188/188 [==============================] - 1s 3ms/step - loss: 0.0768 - accuracy: 0.9782
Test Accuracy: 0.9781666398048401
Task A Original Accuracy: 97.82%
Task B EWC method Accuracy: 98.05%
Epoch 1/10
422/422 [==============================] - 4s 5ms/step - loss: 0.3618 - accuracy: 0.8991 - val_loss: 0.2148 - val_accuracy: 0.9418
Epoch 2/10
422/422 [==============================] - 2s 4ms/step - loss: 0.1711 - accuracy: 0.9519 - val_loss: 0.1560 - val_accuracy: 0.9568
Epoch 3/10
422/422 [==============================] - 2s 5ms/step - loss: 0.1251 - accuracy: 0.9644 - val_loss: 0.1286 - val_accuracy: 0.9640
Epoch 4/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0987 - accuracy: 0.9714 - val_loss: 0.1175 - val_accuracy: 0.9677
Epoch 5/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0789 - accuracy: 0.9769 - val_loss: 0.1034 - val_accuracy: 0.9690
Epoch 6/10
422/422 [==============================] - 3s 6ms/step - loss: 0.0653 - accuracy: 0.9813 - val_loss: 0.0919 - val_accuracy: 0.9737
Epoch 7/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0547 - accuracy: 0.9844 - val_loss: 0.0907 - val_accuracy: 0.9730
Epoch 8/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0472 - accuracy: 0.9865 - val_loss: 0.0839 - val_accuracy: 0.9752
Epoch 9/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0394 - accuracy: 0.9891 - val_loss: 0.0870 - val_accuracy: 0.9755
Epoch 10/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0337 - accuracy: 0.9909 - val_loss: 0.0830 - val_accuracy: 0.9753
Epoch 1/10
422/422 [==============================] - 108s 70ms/step - loss: 0.0306 - accuracy: 0.9920 - val_loss: 0.0812 - val_accuracy: 0.9765
Epoch 2/10
422/422 [==============================] - 10s 23ms/step - loss: 0.0251 - accuracy: 0.9935 - val_loss: 0.0804 - val_accuracy: 0.9763
Epoch 3/10
422/422 [==============================] - 9s 21ms/step - loss: 0.0211 - accuracy: 0.9945 - val_loss: 0.0857 - val_accuracy: 0.9770
Epoch 4/10
422/422 [==============================] - 11s 26ms/step - loss: 0.0171 - accuracy: 0.9957 - val_loss: 0.0821 - val_accuracy: 0.9780
Epoch 5/10
422/422 [==============================] - 10s 23ms/step - loss: 0.0143 - accuracy: 0.9968 - val_loss: 0.0855 - val_accuracy: 0.9770
Epoch 6/10
422/422 [==============================] - 10s 23ms/step - loss: 0.0122 - accuracy: 0.9976 - val_loss: 0.0849 - val_accuracy: 0.9777
Epoch 7/10
422/422 [==============================] - 11s 26ms/step - loss: 0.0105 - accuracy: 0.9980 - val_loss: 0.0877 - val_accuracy: 0.9763
Epoch 8/10
422/422 [==============================] - 9s 21ms/step - loss: 0.0090 - accuracy: 0.9983 - val_loss: 0.0904 - val_accuracy: 0.9773
Epoch 9/10
422/422 [==============================] - 10s 24ms/step - loss: 0.0074 - accuracy: 0.9988 - val_loss: 0.0903 - val_accuracy: 0.9783
Epoch 10/10
422/422 [==============================] - 11s 26ms/step - loss: 0.0057 - accuracy: 0.9993 - val_loss: 0.0896 - val_accuracy: 0.9773
188/188 [==============================] - 1s 3ms/step - loss: 0.0830 - accuracy: 0.9753
188/188 [==============================] - 3s 14ms/step - loss: 0.0896 - accuracy: 0.9773
188/188 [==============================] - 1s 5ms/step - loss: 0.0830 - accuracy: 0.9753
Test Accuracy: 0.9753333330154419
Task A Original Accuracy: 97.53%
Task B EWC method Accuracy: 97.73%
Epoch 1/10
422/422 [==============================] - 3s 5ms/step - loss: 0.3762 - accuracy: 0.8955 - val_loss: 0.2161 - val_accuracy: 0.9413
Epoch 2/10
422/422 [==============================] - 2s 4ms/step - loss: 0.1734 - accuracy: 0.9504 - val_loss: 0.1535 - val_accuracy: 0.9560
Epoch 3/10
422/422 [==============================] - 2s 4ms/step - loss: 0.1250 - accuracy: 0.9644 - val_loss: 0.1300 - val_accuracy: 0.9628
Epoch 4/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0964 - accuracy: 0.9723 - val_loss: 0.1095 - val_accuracy: 0.9668
Epoch 5/10
422/422 [==============================] - 3s 6ms/step - loss: 0.0778 - accuracy: 0.9775 - val_loss: 0.1007 - val_accuracy: 0.9695
Epoch 6/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0639 - accuracy: 0.9821 - val_loss: 0.0928 - val_accuracy: 0.9730
Epoch 7/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0530 - accuracy: 0.9852 - val_loss: 0.0846 - val_accuracy: 0.9745
Epoch 8/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0444 - accuracy: 0.9879 - val_loss: 0.0799 - val_accuracy: 0.9760
Epoch 9/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0371 - accuracy: 0.9902 - val_loss: 0.0815 - val_accuracy: 0.9758
Epoch 10/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0313 - accuracy: 0.9920 - val_loss: 0.0756 - val_accuracy: 0.9778
Epoch 1/10
422/422 [==============================] - 74s 33ms/step - loss: 0.0286 - accuracy: 0.9920 - val_loss: 0.0827 - val_accuracy: 0.9762
Epoch 2/10
422/422 [==============================] - 3s 7ms/step - loss: 0.0233 - accuracy: 0.9944 - val_loss: 0.0848 - val_accuracy: 0.9758
Epoch 3/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0198 - accuracy: 0.9953 - val_loss: 0.0871 - val_accuracy: 0.9767
Epoch 4/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0163 - accuracy: 0.9962 - val_loss: 0.0833 - val_accuracy: 0.9782
Epoch 5/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0133 - accuracy: 0.9974 - val_loss: 0.0882 - val_accuracy: 0.9782
Epoch 6/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0107 - accuracy: 0.9979 - val_loss: 0.0828 - val_accuracy: 0.9773
Epoch 7/10
422/422 [==============================] - 3s 7ms/step - loss: 0.0094 - accuracy: 0.9983 - val_loss: 0.0906 - val_accuracy: 0.9765
Epoch 8/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0086 - accuracy: 0.9983 - val_loss: 0.0907 - val_accuracy: 0.9767
Epoch 9/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0068 - accuracy: 0.9990 - val_loss: 0.0887 - val_accuracy: 0.9770
Epoch 10/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0050 - accuracy: 0.9994 - val_loss: 0.0849 - val_accuracy: 0.9797
188/188 [==============================] - 0s 2ms/step - loss: 0.0756 - accuracy: 0.9778
188/188 [==============================] - 1s 4ms/step - loss: 0.0849 - accuracy: 0.9797
188/188 [==============================] - 0s 3ms/step - loss: 0.0756 - accuracy: 0.9778
Test Accuracy: 0.9778333306312561
Task A Original Accuracy: 97.78%
Task B EWC method Accuracy: 97.97%
Epoch 1/10
422/422 [==============================] - 2s 4ms/step - loss: 0.3721 - accuracy: 0.8969 - val_loss: 0.2134 - val_accuracy: 0.9428
Epoch 2/10
422/422 [==============================] - 1s 3ms/step - loss: 0.1757 - accuracy: 0.9495 - val_loss: 0.1593 - val_accuracy: 0.9547
Epoch 3/10
422/422 [==============================] - 1s 3ms/step - loss: 0.1275 - accuracy: 0.9627 - val_loss: 0.1319 - val_accuracy: 0.9617
Epoch 4/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0977 - accuracy: 0.9715 - val_loss: 0.1166 - val_accuracy: 0.9670
Epoch 5/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0795 - accuracy: 0.9769 - val_loss: 0.1063 - val_accuracy: 0.9683
Epoch 6/10
422/422 [==============================] - 1s 3ms/step - loss: 0.0662 - accuracy: 0.9804 - val_loss: 0.0992 - val_accuracy: 0.9703
Epoch 7/10
422/422 [==============================] - 1s 3ms/step - loss: 0.0542 - accuracy: 0.9849 - val_loss: 0.0985 - val_accuracy: 0.9715
Epoch 8/10
422/422 [==============================] - 1s 3ms/step - loss: 0.0469 - accuracy: 0.9862 - val_loss: 0.0920 - val_accuracy: 0.9727
Epoch 9/10
422/422 [==============================] - 1s 3ms/step - loss: 0.0389 - accuracy: 0.9897 - val_loss: 0.0886 - val_accuracy: 0.9727
Epoch 10/10
422/422 [==============================] - 1s 3ms/step - loss: 0.0332 - accuracy: 0.9910 - val_loss: 0.0901 - val_accuracy: 0.9752
Epoch 1/10
422/422 [==============================] - 62s 32ms/step - loss: 0.0304 - accuracy: 0.9914 - val_loss: 0.0862 - val_accuracy: 0.9757
Epoch 2/10
422/422 [==============================] - 3s 6ms/step - loss: 0.0241 - accuracy: 0.9940 - val_loss: 0.0946 - val_accuracy: 0.9732
Epoch 3/10
422/422 [==============================] - 2s 6ms/step - loss: 0.0204 - accuracy: 0.9945 - val_loss: 0.0929 - val_accuracy: 0.9757
Epoch 4/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0175 - accuracy: 0.9957 - val_loss: 0.0927 - val_accuracy: 0.9743
Epoch 5/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0141 - accuracy: 0.9969 - val_loss: 0.0938 - val_accuracy: 0.9755
Epoch 6/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0129 - accuracy: 0.9971 - val_loss: 0.0923 - val_accuracy: 0.9758
Epoch 7/10
422/422 [==============================] - 2s 6ms/step - loss: 0.0106 - accuracy: 0.9976 - val_loss: 0.0998 - val_accuracy: 0.9762
Epoch 8/10
422/422 [==============================] - 3s 6ms/step - loss: 0.0090 - accuracy: 0.9981 - val_loss: 0.0989 - val_accuracy: 0.9748
Epoch 9/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0074 - accuracy: 0.9986 - val_loss: 0.1004 - val_accuracy: 0.9770
Epoch 10/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0064 - accuracy: 0.9990 - val_loss: 0.0986 - val_accuracy: 0.9760
188/188 [==============================] - 0s 2ms/step - loss: 0.0901 - accuracy: 0.9752
188/188 [==============================] - 1s 4ms/step - loss: 0.0986 - accuracy: 0.9760
188/188 [==============================] - 0s 2ms/step - loss: 0.0901 - accuracy: 0.9752
Test Accuracy: 0.9751666784286499
Task A Original Accuracy: 97.52%
Task B EWC method Accuracy: 97.60%
Epoch 1/10
422/422 [==============================] - 2s 4ms/step - loss: 0.3755 - accuracy: 0.8978 - val_loss: 0.2191 - val_accuracy: 0.9375
Epoch 2/10
422/422 [==============================] - 1s 3ms/step - loss: 0.1755 - accuracy: 0.9506 - val_loss: 0.1617 - val_accuracy: 0.9545
Epoch 3/10
422/422 [==============================] - 1s 3ms/step - loss: 0.1276 - accuracy: 0.9640 - val_loss: 0.1299 - val_accuracy: 0.9642
Epoch 4/10
422/422 [==============================] - 1s 3ms/step - loss: 0.0995 - accuracy: 0.9718 - val_loss: 0.1131 - val_accuracy: 0.9660
Epoch 5/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0803 - accuracy: 0.9769 - val_loss: 0.0987 - val_accuracy: 0.9700
Epoch 6/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0661 - accuracy: 0.9810 - val_loss: 0.0931 - val_accuracy: 0.9705
Epoch 7/10
422/422 [==============================] - 1s 3ms/step - loss: 0.0565 - accuracy: 0.9839 - val_loss: 0.0860 - val_accuracy: 0.9740
Epoch 8/10
422/422 [==============================] - 1s 3ms/step - loss: 0.0474 - accuracy: 0.9870 - val_loss: 0.0915 - val_accuracy: 0.9712
Epoch 9/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0407 - accuracy: 0.9886 - val_loss: 0.0820 - val_accuracy: 0.9755
Epoch 10/10
422/422 [==============================] - 1s 3ms/step - loss: 0.0340 - accuracy: 0.9908 - val_loss: 0.0818 - val_accuracy: 0.9753
Epoch 1/10
422/422 [==============================] - 62s 33ms/step - loss: 0.0321 - accuracy: 0.9911 - val_loss: 0.0820 - val_accuracy: 0.9750
Epoch 2/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0253 - accuracy: 0.9934 - val_loss: 0.0788 - val_accuracy: 0.9762
Epoch 3/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0213 - accuracy: 0.9946 - val_loss: 0.0792 - val_accuracy: 0.9750
Epoch 4/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0180 - accuracy: 0.9954 - val_loss: 0.0787 - val_accuracy: 0.9770
Epoch 5/10
422/422 [==============================] - 3s 7ms/step - loss: 0.0146 - accuracy: 0.9968 - val_loss: 0.0831 - val_accuracy: 0.9747
Epoch 6/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0124 - accuracy: 0.9974 - val_loss: 0.0812 - val_accuracy: 0.9758
Epoch 7/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0108 - accuracy: 0.9978 - val_loss: 0.0821 - val_accuracy: 0.9745
Epoch 8/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0084 - accuracy: 0.9987 - val_loss: 0.0810 - val_accuracy: 0.9770
Epoch 9/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0078 - accuracy: 0.9986 - val_loss: 0.0823 - val_accuracy: 0.9773
Epoch 10/10
422/422 [==============================] - 3s 6ms/step - loss: 0.0068 - accuracy: 0.9989 - val_loss: 0.0834 - val_accuracy: 0.9763
188/188 [==============================] - 1s 3ms/step - loss: 0.0818 - accuracy: 0.9753
188/188 [==============================] - 1s 5ms/step - loss: 0.0834 - accuracy: 0.9763
188/188 [==============================] - 0s 2ms/step - loss: 0.0818 - accuracy: 0.9753
Test Accuracy: 0.9753333330154419
Task A Original Accuracy: 97.53%
Task B EWC method Accuracy: 97.63%
Epoch 1/10
422/422 [==============================] - 2s 4ms/step - loss: 0.3762 - accuracy: 0.8985 - val_loss: 0.2207 - val_accuracy: 0.9368
Epoch 2/10
422/422 [==============================] - 1s 3ms/step - loss: 0.1730 - accuracy: 0.9507 - val_loss: 0.1617 - val_accuracy: 0.9547
Epoch 3/10
422/422 [==============================] - 1s 3ms/step - loss: 0.1254 - accuracy: 0.9636 - val_loss: 0.1333 - val_accuracy: 0.9625
Epoch 4/10
422/422 [==============================] - 1s 3ms/step - loss: 0.0967 - accuracy: 0.9720 - val_loss: 0.1151 - val_accuracy: 0.9682
Epoch 5/10
422/422 [==============================] - 2s 4ms/step - loss: 0.0766 - accuracy: 0.9780 - val_loss: 0.1060 - val_accuracy: 0.9718
Epoch 6/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0629 - accuracy: 0.9824 - val_loss: 0.1027 - val_accuracy: 0.9708
Epoch 7/10
422/422 [==============================] - 1s 3ms/step - loss: 0.0530 - accuracy: 0.9852 - val_loss: 0.1044 - val_accuracy: 0.9693
Epoch 8/10
422/422 [==============================] - 1s 3ms/step - loss: 0.0455 - accuracy: 0.9872 - val_loss: 0.0945 - val_accuracy: 0.9740
Epoch 9/10
422/422 [==============================] - 1s 3ms/step - loss: 0.0381 - accuracy: 0.9898 - val_loss: 0.0951 - val_accuracy: 0.9748
Epoch 10/10
422/422 [==============================] - 1s 3ms/step - loss: 0.0327 - accuracy: 0.9911 - val_loss: 0.0952 - val_accuracy: 0.9728
Epoch 1/10
422/422 [==============================] - 63s 32ms/step - loss: 0.0298 - accuracy: 0.9919 - val_loss: 0.0906 - val_accuracy: 0.9755
Epoch 2/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0237 - accuracy: 0.9937 - val_loss: 0.0982 - val_accuracy: 0.9733
Epoch 3/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0199 - accuracy: 0.9953 - val_loss: 0.0972 - val_accuracy: 0.9757
Epoch 4/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0167 - accuracy: 0.9961 - val_loss: 0.1023 - val_accuracy: 0.9750
Epoch 5/10
422/422 [==============================] - 3s 6ms/step - loss: 0.0140 - accuracy: 0.9970 - val_loss: 0.0936 - val_accuracy: 0.9753
Epoch 6/10
422/422 [==============================] - 3s 6ms/step - loss: 0.0115 - accuracy: 0.9975 - val_loss: 0.0992 - val_accuracy: 0.9762
Epoch 7/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0094 - accuracy: 0.9983 - val_loss: 0.1066 - val_accuracy: 0.9727
Epoch 8/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0078 - accuracy: 0.9988 - val_loss: 0.1023 - val_accuracy: 0.9762
Epoch 9/10
422/422 [==============================] - 2s 5ms/step - loss: 0.0069 - accuracy: 0.9990 - val_loss: 0.0991 - val_accuracy: 0.9755
Epoch 10/10
422/422 [==============================] - 2s 6ms/step - loss: 0.0063 - accuracy: 0.9990 - val_loss: 0.1085 - val_accuracy: 0.9753
188/188 [==============================] - 1s 3ms/step - loss: 0.0952 - accuracy: 0.9728
188/188 [==============================] - 1s 6ms/step - loss: 0.1085 - accuracy: 0.9753
188/188 [==============================] - 0s 2ms/step - loss: 0.0952 - accuracy: 0.9728
Test Accuracy: 0.9728333353996277
Task A Original Accuracy: 97.28%
Task B EWC method Accuracy: 97.53%
Epoch 1/10
422/422 [==============================] - 2s 4ms/step - loss: 0.3764 - accuracy: 0.8969 - val_loss: 0.2050 - val_accuracy: 0.9395
Epoch 2/10
422/422 [==============================] - 1s 3ms/step - loss: 0.1740 - accuracy: 0.9500 - val_loss: 0.1542 - val_accuracy: 0.9537
Epoch 3/10
422/422 [==============================] - 1s 3ms/step - loss: 0.1261 - accuracy: 0.9639 - val_loss: 0.1220 - val_accuracy: 0.9640
Epoch 4/10
422/422 [==============================] - 1s 3ms/step - loss: 0.0973 - accuracy: 0.9726 - val_loss: 0.1019 - val_accuracy: 0.9695
Epoch 5/10

### CIFAR10

In [ ]:
import numpy as np
# from tensorflow.keras.datasets import cifar100
import numpy as np
# Importing the necessary libraries, which we may or may not use. Its always good idea to import them befor (if you remember) else we can do it at any point of time no problem.
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPool2D,Dense,Flatten,Dropout,Input, AveragePooling2D, Activation,Conv2D, MaxPooling2D, BatchNormalization,Concatenate
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
from tensorflow.keras import regularizers, optimizers
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.datasets import cifar100
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers
from tensorflow.keras.regularizers import Regularizer

# Perform hold-out cross-validation
validation_scores = []

# Define the CrlB regularizer
class CrlBRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Number of K-folds
K = 10

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)
# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []
num_classes = 10
# Perform K-fold cross-validation
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]

# Task A: Original Fashion MNIST model
    model = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        Conv2D(32, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu'),
        layers.Dropout(0.25),
        Dense(num_classes, activation='softmax')
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model = model
        model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
        model.save_weights('FashionMNIST_A.h5')
        prior_weights = model.get_weights()
# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    fisher_matrix = []
    for i in range(len(model.trainable_weights)):
        fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

    for _ in range(num_samples):
        idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
        with tf.GradientTape() as tape:
            logits = model(x[idx:idx+1])
        gradients = tape.gradient(logits, model.trainable_weights)
        for i in range(len(fisher_matrix)):
            fisher_matrix[i] += tf.square(gradients[i])

    fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
    return fisher_matrix

fisher_matrix = compute_fisher(model, x_train_fold)
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]
# Task B: Fashion MNIST with CrlB regularization
    model_CrlBB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3),
               kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model_CrlBB = model_CrlBB
        model_CrlBB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model_CrlBB.load_weights('FashionMNIST_A.h5')
        model_CrlBB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlB_acc = 100 * model_CrlBB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlB method Accuracy: %.2f%%" % B_CrlB_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
422/422 [==============================] - 30s 23ms/step - loss: 2.9060 - accuracy: 0.2364 - val_loss: 1.6060 - val_accuracy: 0.4015
Epoch 2/10
422/422 [==============================] - 7s 17ms/step - loss: 1.5251 - accuracy: 0.4486 - val_loss: 1.2765 - val_accuracy: 0.5445
Epoch 3/10
422/422 [==============================] - 8s 20ms/step - loss: 1.2808 - accuracy: 0.5428 - val_loss: 1.1568 - val_accuracy: 0.5867
Epoch 4/10
422/422 [==============================] - 7s 17ms/step - loss: 1.1378 - accuracy: 0.5953 - val_loss: 1.0352 - val_accuracy: 0.6382
Epoch 5/10
422/422 [==============================] - 8s 19ms/step - loss: 1.0363 - accuracy: 0.6349 - val_loss: 1.0201 - val_accuracy: 0.6488
Epoch 6/10
422/422 [==============================] - 6s 14ms/step - loss: 0.9492 - accuracy: 0.6679 - val_loss: 0.8925 - val_accuracy: 0.6863
Epoch 7/10
422/422 [==============================] - 7s 16ms/step - loss: 0.8732 - accuracy: 0.6934 - val_loss: 0.8220 - val_accuracy: 0.7182
Epoch 8/10
422/422 [==============================] - 7s 16ms/step - loss: 0.8143 - accuracy: 0.7159 - val_loss: 0.8347 - val_accuracy: 0.7122
Epoch 9/10
422/422 [==============================] - 6s 15ms/step - loss: 0.7527 - accuracy: 0.7362 - val_loss: 0.8084 - val_accuracy: 0.7167
Epoch 10/10
422/422 [==============================] - 7s 18ms/step - loss: 0.7073 - accuracy: 0.7522 - val_loss: 0.7515 - val_accuracy: 0.7463
Epoch 1/10
422/422 [==============================] - 11s 18ms/step - loss: 2.8964 - accuracy: 0.2868 - val_loss: 1.4160 - val_accuracy: 0.4948
Epoch 2/10
422/422 [==============================] - 6s 14ms/step - loss: 1.3962 - accuracy: 0.4993 - val_loss: 1.1847 - val_accuracy: 0.5842
Epoch 3/10
422/422 [==============================] - 9s 22ms/step - loss: 1.1794 - accuracy: 0.5794 - val_loss: 1.0377 - val_accuracy: 0.6297
Epoch 4/10
422/422 [==============================] - 7s 18ms/step - loss: 1.0523 - accuracy: 0.6265 - val_loss: 0.9560 - val_accuracy: 0.6723
Epoch 5/10
422/422 [==============================] - 8s 20ms/step - loss: 0.9641 - accuracy: 0.6621 - val_loss: 0.8692 - val_accuracy: 0.6977
Epoch 6/10
422/422 [==============================] - 8s 19ms/step - loss: 0.8915 - accuracy: 0.6880 - val_loss: 0.8543 - val_accuracy: 0.7022
Epoch 7/10
422/422 [==============================] - 8s 19ms/step - loss: 0.8221 - accuracy: 0.7103 - val_loss: 0.8510 - val_accuracy: 0.7053
Epoch 8/10
422/422 [==============================] - 8s 20ms/step - loss: 0.7749 - accuracy: 0.7284 - val_loss: 0.7717 - val_accuracy: 0.7305
Epoch 9/10
422/422 [==============================] - 8s 20ms/step - loss: 0.7244 - accuracy: 0.7470 - val_loss: 0.7693 - val_accuracy: 0.7387
Epoch 10/10
422/422 [==============================] - 8s 18ms/step - loss: 0.6793 - accuracy: 0.7614 - val_loss: 0.7478 - val_accuracy: 0.7452
Epoch 1/10
422/422 [==============================] - 15s 21ms/step - loss: 2.9392 - accuracy: 0.2947 - val_loss: 1.4482 - val_accuracy: 0.4793
Epoch 2/10
422/422 [==============================] - 8s 18ms/step - loss: 1.4351 - accuracy: 0.4838 - val_loss: 1.2822 - val_accuracy: 0.5397
Epoch 3/10
422/422 [==============================] - 8s 19ms/step - loss: 1.2435 - accuracy: 0.5596 - val_loss: 1.0949 - val_accuracy: 0.6183
Epoch 4/10
422/422 [==============================] - 8s 19ms/step - loss: 1.1155 - accuracy: 0.6035 - val_loss: 1.0181 - val_accuracy: 0.6490
Epoch 5/10
422/422 [==============================] - 9s 21ms/step - loss: 1.0094 - accuracy: 0.6447 - val_loss: 0.8900 - val_accuracy: 0.6905
Epoch 6/10
422/422 [==============================] - 9s 21ms/step - loss: 0.9266 - accuracy: 0.6733 - val_loss: 0.8203 - val_accuracy: 0.7143
Epoch 7/10
422/422 [==============================] - 8s 20ms/step - loss: 0.8611 - accuracy: 0.6957 - val_loss: 0.8075 - val_accuracy: 0.7220
Epoch 8/10
422/422 [==============================] - 8s 18ms/step - loss: 0.7976 - accuracy: 0.7186 - val_loss: 0.8448 - val_accuracy: 0.7092
Epoch 9/10
422/422 [==============================] - 8s 20ms/step - loss: 0.7550 - accuracy: 0.7361 - val_loss: 0.7474 - val_accuracy: 0.7460
Epoch 10/10
422/422 [==============================] - 8s 18ms/step - loss: 0.7126 - accuracy: 0.7489 - val_loss: 0.7559 - val_accuracy: 0.7347
Epoch 1/10
422/422 [==============================] - 14s 23ms/step - loss: 2.5157 - accuracy: 0.2205 - val_loss: 1.6544 - val_accuracy: 0.4008
Epoch 2/10
422/422 [==============================] - 7s 17ms/step - loss: 1.5748 - accuracy: 0.4258 - val_loss: 1.3580 - val_accuracy: 0.5212
Epoch 3/10
422/422 [==============================] - 8s 19ms/step - loss: 1.3753 - accuracy: 0.5046 - val_loss: 1.2304 - val_accuracy: 0.5652
Epoch 4/10
422/422 [==============================] - 8s 19ms/step - loss: 1.2442 - accuracy: 0.5538 - val_loss: 1.0775 - val_accuracy: 0.6252
Epoch 5/10
422/422 [==============================] - 7s 17ms/step - loss: 1.1154 - accuracy: 0.6026 - val_loss: 0.9845 - val_accuracy: 0.6498
Epoch 6/10
422/422 [==============================] - 8s 20ms/step - loss: 1.0200 - accuracy: 0.6429 - val_loss: 0.9137 - val_accuracy: 0.6828
Epoch 7/10
422/422 [==============================] - 8s 19ms/step - loss: 0.9429 - accuracy: 0.6698 - val_loss: 0.8676 - val_accuracy: 0.6993
Epoch 8/10
422/422 [==============================] - 8s 19ms/step - loss: 0.8733 - accuracy: 0.6926 - val_loss: 0.8530 - val_accuracy: 0.7020
Epoch 9/10
422/422 [==============================] - 8s 20ms/step - loss: 0.8140 - accuracy: 0.7143 - val_loss: 0.8381 - val_accuracy: 0.7095
Epoch 10/10
422/422 [==============================] - 8s 18ms/step - loss: 0.7570 - accuracy: 0.7349 - val_loss: 0.7603 - val_accuracy: 0.7415
Epoch 1/10
422/422 [==============================] - 14s 21ms/step - loss: 2.5219 - accuracy: 0.2746 - val_loss: 1.5870 - val_accuracy: 0.4262
Epoch 2/10
422/422 [==============================] - 8s 18ms/step - loss: 1.5151 - accuracy: 0.4479 - val_loss: 1.3810 - val_accuracy: 0.5005
Epoch 3/10
422/422 [==============================] - 8s 19ms/step - loss: 1.3222 - accuracy: 0.5250 - val_loss: 1.2220 - val_accuracy: 0.5707
Epoch 4/10
422/422 [==============================] - 8s 18ms/step - loss: 1.1720 - accuracy: 0.5800 - val_loss: 1.0490 - val_accuracy: 0.6257
Epoch 5/10
422/422 [==============================] - 7s 18ms/step - loss: 1.0638 - accuracy: 0.6238 - val_loss: 0.9722 - val_accuracy: 0.6672
Epoch 6/10
422/422 [==============================] - 7s 16ms/step - loss: 0.9707 - accuracy: 0.6564 - val_loss: 0.8987 - val_accuracy: 0.6810
Epoch 7/10
422/422 [==============================] - 6s 14ms/step - loss: 0.9072 - accuracy: 0.6800 - val_loss: 0.8685 - val_accuracy: 0.7042
Epoch 8/10
422/422 [==============================] - 7s 16ms/step - loss: 0.8470 - accuracy: 0.7019 - val_loss: 0.8640 - val_accuracy: 0.7025
Epoch 9/10
422/422 [==============================] - 6s 14ms/step - loss: 0.7875 - accuracy: 0.7221 - val_loss: 0.8437 - val_accuracy: 0.7025
Epoch 10/10
422/422 [==============================] - 7s 16ms/step - loss: 0.7435 - accuracy: 0.7366 - val_loss: 0.7813 - val_accuracy: 0.7343
Epoch 1/10
422/422 [==============================] - 11s 17ms/step - loss: 2.8065 - accuracy: 0.3305 - val_loss: 1.5369 - val_accuracy: 0.4492
Epoch 2/10
422/422 [==============================] - 6s 15ms/step - loss: 1.4707 - accuracy: 0.4638 - val_loss: 1.2833 - val_accuracy: 0.5413
Epoch 3/10
422/422 [==============================] - 7s 17ms/step - loss: 1.2751 - accuracy: 0.5435 - val_loss: 1.0818 - val_accuracy: 0.6165
Epoch 4/10
422/422 [==============================] - 6s 15ms/step - loss: 1.1221 - accuracy: 0.6034 - val_loss: 1.0006 - val_accuracy: 0.6463
Epoch 5/10
422/422 [==============================] - 7s 17ms/step - loss: 1.0097 - accuracy: 0.6454 - val_loss: 0.9476 - val_accuracy: 0.6690
Epoch 6/10
422/422 [==============================] - 6s 14ms/step - loss: 0.9245 - accuracy: 0.6763 - val_loss: 0.8577 - val_accuracy: 0.7057
Epoch 7/10
422/422 [==============================] - 7s 16ms/step - loss: 0.8592 - accuracy: 0.6994 - val_loss: 0.8345 - val_accuracy: 0.7140
Epoch 8/10
422/422 [==============================] - 6s 14ms/step - loss: 0.7979 - accuracy: 0.7231 - val_loss: 0.7799 - val_accuracy: 0.7285
Epoch 9/10
422/422 [==============================] - 7s 16ms/step - loss: 0.7515 - accuracy: 0.7376 - val_loss: 0.7560 - val_accuracy: 0.7437
Epoch 10/10
422/422 [==============================] - 6s 15ms/step - loss: 0.7028 - accuracy: 0.7529 - val_loss: 0.7450 - val_accuracy: 0.7395
Epoch 1/10
422/422 [==============================] - 11s 16ms/step - loss: 2.3799 - accuracy: 0.3171 - val_loss: 1.4972 - val_accuracy: 0.4590
Epoch 2/10
422/422 [==============================] - 7s 16ms/step - loss: 1.4399 - accuracy: 0.4810 - val_loss: 1.3315 - val_accuracy: 0.5182
Epoch 3/10
422/422 [==============================] - 6s 15ms/step - loss: 1.2915 - accuracy: 0.5388 - val_loss: 1.1600 - val_accuracy: 0.5857
Epoch 4/10
422/422 [==============================] - 7s 17ms/step - loss: 1.1808 - accuracy: 0.5800 - val_loss: 1.1476 - val_accuracy: 0.5937
Epoch 5/10
422/422 [==============================] - 6s 15ms/step - loss: 1.0764 - accuracy: 0.6209 - val_loss: 0.9756 - val_accuracy: 0.6632
Epoch 6/10
422/422 [==============================] - 7s 16ms/step - loss: 0.9945 - accuracy: 0.6518 - val_loss: 0.9092 - val_accuracy: 0.6738
Epoch 7/10
422/422 [==============================] - 6s 15ms/step - loss: 0.9202 - accuracy: 0.6771 - val_loss: 0.9144 - val_accuracy: 0.6858
Epoch 8/10
422/422 [==============================] - 7s 16ms/step - loss: 0.8686 - accuracy: 0.6972 - val_loss: 0.8624 - val_accuracy: 0.6982
Epoch 9/10
422/422 [==============================] - 6s 15ms/step - loss: 0.7981 - accuracy: 0.7200 - val_loss: 0.8207 - val_accuracy: 0.7187
Epoch 10/10
422/422 [==============================] - 7s 17ms/step - loss: 0.7575 - accuracy: 0.7340 - val_loss: 0.7842 - val_accuracy: 0.7253
Epoch 1/10
422/422 [==============================] - 10s 17ms/step - loss: 2.8497 - accuracy: 0.2798 - val_loss: 1.5151 - val_accuracy: 0.4330
Epoch 2/10
422/422 [==============================] - 6s 13ms/step - loss: 1.4439 - accuracy: 0.4786 - val_loss: 1.3028 - val_accuracy: 0.5353
Epoch 3/10
422/422 [==============================] - 6s 14ms/step - loss: 1.2309 - accuracy: 0.5630 - val_loss: 1.0478 - val_accuracy: 0.6247
Epoch 4/10
422/422 [==============================] - 6s 13ms/step - loss: 1.0813 - accuracy: 0.6179 - val_loss: 0.9741 - val_accuracy: 0.6575
Epoch 5/10
422/422 [==============================] - 6s 14ms/step - loss: 0.9744 - accuracy: 0.6587 - val_loss: 0.8946 - val_accuracy: 0.6835
Epoch 6/10
422/422 [==============================] - 6s 13ms/step - loss: 0.8970 - accuracy: 0.6849 - val_loss: 0.8724 - val_accuracy: 0.7007
Epoch 7/10
422/422 [==============================] - 6s 13ms/step - loss: 0.8308 - accuracy: 0.7078 - val_loss: 0.7766 - val_accuracy: 0.7370
Epoch 8/10
422/422 [==============================] - 5s 13ms/step - loss: 0.7655 - accuracy: 0.7322 - val_loss: 0.8349 - val_accuracy: 0.7067
Epoch 9/10
422/422 [==============================] - 6s 14ms/step - loss: 0.7166 - accuracy: 0.7498 - val_loss: 0.7775 - val_accuracy: 0.7315
Epoch 10/10
422/422 [==============================] - 6s 13ms/step - loss: 0.6762 - accuracy: 0.7620 - val_loss: 0.7820 - val_accuracy: 0.7320
Epoch 1/10
422/422 [==============================] - 8s 14ms/step - loss: 2.8341 - accuracy: 0.2765 - val_loss: 1.5349 - val_accuracy: 0.4588
Epoch 2/10
422/422 [==============================] - 6s 13ms/step - loss: 1.4206 - accuracy: 0.4846 - val_loss: 1.1807 - val_accuracy: 0.5888
Epoch 3/10
422/422 [==============================] - 6s 13ms/step - loss: 1.2249 - accuracy: 0.5666 - val_loss: 1.0917 - val_accuracy: 0.6172
Epoch 4/10
422/422 [==============================] - 6s 14ms/step - loss: 1.0837 - accuracy: 0.6193 - val_loss: 0.9825 - val_accuracy: 0.6460
Epoch 5/10
422/422 [==============================] - 6s 14ms/step - loss: 0.9710 - accuracy: 0.6567 - val_loss: 0.8622 - val_accuracy: 0.6908
Epoch 6/10
422/422 [==============================] - 6s 14ms/step - loss: 0.8876 - accuracy: 0.6884 - val_loss: 0.8378 - val_accuracy: 0.7057
Epoch 7/10
422/422 [==============================] - 6s 14ms/step - loss: 0.8223 - accuracy: 0.7132 - val_loss: 0.8159 - val_accuracy: 0.7167
Epoch 8/10
422/422 [==============================] - 6s 13ms/step - loss: 0.7708 - accuracy: 0.7290 - val_loss: 0.7614 - val_accuracy: 0.7305
Epoch 9/10
422/422 [==============================] - 6s 13ms/step - loss: 0.7213 - accuracy: 0.7448 - val_loss: 0.7564 - val_accuracy: 0.7330
Epoch 10/10
422/422 [==============================] - 6s 14ms/step - loss: 0.6834 - accuracy: 0.7587 - val_loss: 0.7321 - val_accuracy: 0.7487
Epoch 1/10
422/422 [==============================] - 9s 15ms/step - loss: 2.9443 - accuracy: 0.2082 - val_loss: 1.5720 - val_accuracy: 0.4230
Epoch 2/10
422/422 [==============================] - 6s 14ms/step - loss: 1.4966 - accuracy: 0.4591 - val_loss: 1.3258 - val_accuracy: 0.5173
Epoch 3/10
422/422 [==============================] - 6s 14ms/step - loss: 1.2613 - accuracy: 0.5489 - val_loss: 1.0698 - val_accuracy: 0.6225
Epoch 4/10
422/422 [==============================] - 6s 13ms/step - loss: 1.0866 - accuracy: 0.6154 - val_loss: 0.9815 - val_accuracy: 0.6633
Epoch 5/10
422/422 [==============================] - 6s 14ms/step - loss: 0.9884 - accuracy: 0.6525 - val_loss: 0.9203 - val_accuracy: 0.6767
Epoch 6/10
422/422 [==============================] - 6s 13ms/step - loss: 0.9059 - accuracy: 0.6818 - val_loss: 0.8944 - val_accuracy: 0.6887
Epoch 7/10
422/422 [==============================] - 6s 14ms/step - loss: 0.8393 - accuracy: 0.7043 - val_loss: 0.8268 - val_accuracy: 0.7152
Epoch 8/10
422/422 [==============================] - 6s 14ms/step - loss: 0.7816 - accuracy: 0.7270 - val_loss: 0.7739 - val_accuracy: 0.7367
Epoch 9/10
422/422 [==============================] - 6s 13ms/step - loss: 0.7306 - accuracy: 0.7447 - val_loss: 0.7835 - val_accuracy: 0.7240
Epoch 10/10
422/422 [==============================] - 6s 13ms/step - loss: 0.6914 - accuracy: 0.7569 - val_loss: 0.7518 - val_accuracy: 0.7438
Epoch 1/10
422/422 [==============================] - 15s 21ms/step - loss: 0.6421 - accuracy: 0.7767 - val_loss: 0.5253 - val_accuracy: 0.8258
Epoch 2/10
422/422 [==============================] - 7s 16ms/step - loss: 0.5560 - accuracy: 0.8055 - val_loss: 0.5726 - val_accuracy: 0.7977
Epoch 3/10
422/422 [==============================] - 7s 16ms/step - loss: 0.4899 - accuracy: 0.8281 - val_loss: 0.5440 - val_accuracy: 0.8157
Epoch 4/10
422/422 [==============================] - 7s 16ms/step - loss: 0.4418 - accuracy: 0.8458 - val_loss: 0.5999 - val_accuracy: 0.7940
Epoch 5/10
422/422 [==============================] - 7s 16ms/step - loss: 0.4016 - accuracy: 0.8587 - val_loss: 0.5869 - val_accuracy: 0.8013
Epoch 6/10
422/422 [==============================] - 7s 17ms/step - loss: 0.3593 - accuracy: 0.8758 - val_loss: 0.6110 - val_accuracy: 0.7985
Epoch 7/10
422/422 [==============================] - 7s 16ms/step - loss: 0.3290 - accuracy: 0.8866 - val_loss: 0.6470 - val_accuracy: 0.7960
Epoch 8/10
422/422 [==============================] - 7s 16ms/step - loss: 0.3031 - accuracy: 0.8952 - val_loss: 0.6757 - val_accuracy: 0.7908
Epoch 9/10
422/422 [==============================] - 7s 16ms/step - loss: 0.2831 - accuracy: 0.9021 - val_loss: 0.7415 - val_accuracy: 0.7878
Epoch 10/10
422/422 [==============================] - 7s 16ms/step - loss: 0.2687 - accuracy: 0.9084 - val_loss: 0.7589 - val_accuracy: 0.7892
188/188 [==============================] - 1s 3ms/step - loss: 0.4502 - accuracy: 0.8572
188/188 [==============================] - 1s 5ms/step - loss: 0.7589 - accuracy: 0.7892
188/188 [==============================] - 1s 4ms/step - loss: 0.4502 - accuracy: 0.8572
Test Accuracy: 0.8571666479110718
Task A Original Accuracy: 85.72%
Task B EWC method Accuracy: 78.92%
Epoch 1/10
422/422 [==============================] - 13s 20ms/step - loss: 0.6419 - accuracy: 0.7780 - val_loss: 0.5927 - val_accuracy: 0.7902
Epoch 2/10
422/422 [==============================] - 7s 15ms/step - loss: 0.5693 - accuracy: 0.8016 - val_loss: 0.5259 - val_accuracy: 0.8175
Epoch 3/10
422/422 [==============================] - 7s 16ms/step - loss: 0.5004 - accuracy: 0.8238 - val_loss: 0.5513 - val_accuracy: 0.8152
Epoch 4/10
422/422 [==============================] - 7s 16ms/step - loss: 0.4492 - accuracy: 0.8419 - val_loss: 0.5812 - val_accuracy: 0.8000
Epoch 5/10
422/422 [==============================] - 7s 17ms/step - loss: 0.3900 - accuracy: 0.8643 - val_loss: 0.6165 - val_accuracy: 0.8005
Epoch 6/10
422/422 [==============================] - 7s 16ms/step - loss: 0.3670 - accuracy: 0.8724 - val_loss: 0.6579 - val_accuracy: 0.7872
Epoch 7/10
422/422 [==============================] - 7s 16ms/step - loss: 0.3217 - accuracy: 0.8872 - val_loss: 0.6557 - val_accuracy: 0.7973
Epoch 8/10
422/422 [==============================] - 7s 16ms/step - loss: 0.3072 - accuracy: 0.8950 - val_loss: 0.6951 - val_accuracy: 0.7897
Epoch 9/10
422/422 [==============================] - 6s 15ms/step - loss: 0.2848 - accuracy: 0.9025 - val_loss: 0.6825 - val_accuracy: 0.7952
Epoch 10/10
422/422 [==============================] - 7s 16ms/step - loss: 0.2581 - accuracy: 0.9113 - val_loss: 0.7881 - val_accuracy: 0.7763
188/188 [==============================] - 1s 3ms/step - loss: 0.4505 - accuracy: 0.8535
188/188 [==============================] - 1s 5ms/step - loss: 0.7881 - accuracy: 0.7763
188/188 [==============================] - 1s 3ms/step - loss: 0.4505 - accuracy: 0.8535
Test Accuracy: 0.8535000085830688
Task A Original Accuracy: 85.35%
Task B EWC method Accuracy: 77.63%
Epoch 1/10
422/422 [==============================] - 13s 20ms/step - loss: 0.6453 - accuracy: 0.7749 - val_loss: 0.5032 - val_accuracy: 0.8247
Epoch 2/10
422/422 [==============================] - 7s 16ms/step - loss: 0.5648 - accuracy: 0.8043 - val_loss: 0.4928 - val_accuracy: 0.8265
Epoch 3/10
422/422 [==============================] - 7s 15ms/step - loss: 0.5021 - accuracy: 0.8232 - val_loss: 0.5343 - val_accuracy: 0.8135
Epoch 4/10
422/422 [==============================] - 7s 16ms/step - loss: 0.4479 - accuracy: 0.8426 - val_loss: 0.5663 - val_accuracy: 0.8077
Epoch 5/10
422/422 [==============================] - 7s 15ms/step - loss: 0.3964 - accuracy: 0.8619 - val_loss: 0.5858 - val_accuracy: 0.8070
Epoch 6/10
422/422 [==============================] - 7s 16ms/step - loss: 0.3580 - accuracy: 0.8759 - val_loss: 0.6369 - val_accuracy: 0.7898
Epoch 7/10
422/422 [==============================] - 7s 15ms/step - loss: 0.3320 - accuracy: 0.8837 - val_loss: 0.6531 - val_accuracy: 0.7930
Epoch 8/10
422/422 [==============================] - 7s 16ms/step - loss: 0.2976 - accuracy: 0.8998 - val_loss: 0.6662 - val_accuracy: 0.7945
Epoch 9/10
422/422 [==============================] - 7s 15ms/step - loss: 0.2792 - accuracy: 0.9040 - val_loss: 0.7036 - val_accuracy: 0.7833
Epoch 10/10
422/422 [==============================] - 7s 16ms/step - loss: 0.2612 - accuracy: 0.9102 - val_loss: 0.7711 - val_accuracy: 0.7783
188/188 [==============================] - 1s 3ms/step - loss: 0.4478 - accuracy: 0.8545
188/188 [==============================] - 1s 5ms/step - loss: 0.7711 - accuracy: 0.7783
188/188 [==============================] - 1s 3ms/step - loss: 0.4478 - accuracy: 0.8545
Test Accuracy: 0.8544999957084656
Task A Original Accuracy: 85.45%
Task B EWC method Accuracy: 77.83%
Epoch 1/10
422/422 [==============================] - 14s 20ms/step - loss: 0.6438 - accuracy: 0.7754 - val_loss: 0.5180 - val_accuracy: 0.8302
Epoch 2/10

### CIFAR10-C

In [ ]:
import numpy as np
# from tensorflow.keras.datasets import cifar100
import numpy as np
# Importing the necessary libraries, which we may or may not use. Its always good idea to import them befor (if you remember) else we can do it at any point of time no problem.
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPool2D,Dense,Flatten,Dropout,Input, AveragePooling2D, Activation,Conv2D, MaxPooling2D, BatchNormalization,Concatenate
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
from tensorflow.keras import regularizers, optimizers
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.datasets import cifar100
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers
from tensorflow.keras.regularizers import Regularizer

# Perform hold-out cross-validation
validation_scores = []

# Define the CrlB regularizer
class CrlBRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Number of K-folds
K = 10

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)
# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []
num_classes = 10
# Perform K-fold cross-validation
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]

# Task A: Original Fashion MNIST model
    model = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        Conv2D(32, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu'),
        layers.Dropout(0.25),
        Dense(num_classes, activation='softmax')
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model = model
        model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
        model.save_weights('FashionMNIST_A.h5')
        prior_weights = model.get_weights()
# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]


# Compute the Fisher Information matrix
    def compute_fisher(model, x, num_samples=30):
        fisher_matrix = []
        for i in range(len(model.trainable_weights)):
            fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

        for _ in range(num_samples):
            idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
            with tf.GradientTape() as tape:
                logits = model(x[idx:idx+1])
            gradients = tape.gradient(logits, model.trainable_weights)
            for i in range(len(fisher_matrix)):
                fisher_matrix[i] += tf.square(gradients[i])

        fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
        return fisher_matrix

    fisher_matrix = compute_fisher(model, x_train_fold)

# Task B: Fashion MNIST with CrlB regularization
    model_CrlBB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3),
               kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model_CrlBB = model_CrlBB
        model_CrlBB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model_CrlBB.load_weights('FashionMNIST_A.h5')
        model_CrlBB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlB_acc = 100 * model_CrlBB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlB method Accuracy: %.2f%%" % B_CrlB_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)
      # Print the fold accuracies
    for i, score in enumerate(accuracies):
        percent = score * 100
        print("Fold-{}: {:.2f}%".format(i+1, percent))
# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
422/422 [==============================] - 40s 31ms/step - loss: 1.6380 - accuracy: 0.4031 - val_loss: 1.3426 - val_accuracy: 0.5197
Epoch 2/10
422/422 [==============================] - 11s 25ms/step - loss: 1.2688 - accuracy: 0.5447 - val_loss: 1.1369 - val_accuracy: 0.5937
Epoch 3/10
422/422 [==============================] - 10s 24ms/step - loss: 1.0976 - accuracy: 0.6108 - val_loss: 1.0126 - val_accuracy: 0.6402
Epoch 4/10
422/422 [==============================] - 10s 24ms/step - loss: 0.9843 - accuracy: 0.6520 - val_loss: 0.9454 - val_accuracy: 0.6633
Epoch 5/10
422/422 [==============================] - 8s 20ms/step - loss: 0.8907 - accuracy: 0.6856 - val_loss: 0.9067 - val_accuracy: 0.6870
Epoch 6/10
422/422 [==============================] - 9s 21ms/step - loss: 0.8102 - accuracy: 0.7146 - val_loss: 0.8555 - val_accuracy: 0.6967
Epoch 7/10
422/422 [==============================] - 8s 19ms/step - loss: 0.7405 - accuracy: 0.7384 - val_loss: 0.8749 - val_accuracy: 0.6998
Epoch 8/10
422/422 [==============================] - 8s 20ms/step - loss: 0.6763 - accuracy: 0.7626 - val_loss: 0.8931 - val_accuracy: 0.6995
Epoch 9/10
422/422 [==============================] - 6s 15ms/step - loss: 0.6212 - accuracy: 0.7785 - val_loss: 0.8628 - val_accuracy: 0.7080
Epoch 10/10
422/422 [==============================] - 7s 17ms/step - loss: 0.5661 - accuracy: 0.7986 - val_loss: 0.8582 - val_accuracy: 0.7113
Epoch 1/10
422/422 [==============================] - 20s 26ms/step - loss: 0.4329 - accuracy: 0.8460 - val_loss: 0.9197 - val_accuracy: 0.7043
Epoch 2/10
422/422 [==============================] - 8s 18ms/step - loss: 0.3586 - accuracy: 0.8723 - val_loss: 1.0493 - val_accuracy: 0.6980
Epoch 3/10
422/422 [==============================] - 9s 21ms/step - loss: 0.3117 - accuracy: 0.8882 - val_loss: 1.0499 - val_accuracy: 0.7005
Epoch 4/10
422/422 [==============================] - 9s 21ms/step - loss: 0.2748 - accuracy: 0.9017 - val_loss: 1.0681 - val_accuracy: 0.7017
Epoch 5/10
422/422 [==============================] - 8s 19ms/step - loss: 0.2411 - accuracy: 0.9147 - val_loss: 1.1348 - val_accuracy: 0.6953
Epoch 6/10
422/422 [==============================] - 9s 20ms/step - loss: 0.2132 - accuracy: 0.9256 - val_loss: 1.2184 - val_accuracy: 0.6933
Epoch 7/10
422/422 [==============================] - 8s 19ms/step - loss: 0.2003 - accuracy: 0.9291 - val_loss: 1.2171 - val_accuracy: 0.7027
Epoch 8/10
422/422 [==============================] - 8s 18ms/step - loss: 0.1790 - accuracy: 0.9386 - val_loss: 1.3363 - val_accuracy: 0.6933
Epoch 9/10
422/422 [==============================] - 8s 19ms/step - loss: 0.1699 - accuracy: 0.9407 - val_loss: 1.3822 - val_accuracy: 0.6952
Epoch 10/10
422/422 [==============================] - 8s 20ms/step - loss: 0.1586 - accuracy: 0.9449 - val_loss: 1.3511 - val_accuracy: 0.6938
188/188 [==============================] - 1s 4ms/step - loss: 0.8582 - accuracy: 0.7113
188/188 [==============================] - 1s 6ms/step - loss: 1.3511 - accuracy: 0.6938
188/188 [==============================] - 1s 4ms/step - loss: 0.8582 - accuracy: 0.7113
Test Accuracy: 0.7113333344459534
Task A Original Accuracy: 71.13%
Task B EWC method Accuracy: 69.38%
Fold-1: 71.13%
Epoch 1/10
422/422 [==============================] - 11s 18ms/step - loss: 1.6038 - accuracy: 0.4150 - val_loss: 1.2374 - val_accuracy: 0.5573
Epoch 2/10
422/422 [==============================] - 7s 17ms/step - loss: 1.1952 - accuracy: 0.5744 - val_loss: 1.0798 - val_accuracy: 0.6262
Epoch 3/10
422/422 [==============================] - 6s 15ms/step - loss: 1.0503 - accuracy: 0.6289 - val_loss: 0.9985 - val_accuracy: 0.6452
Epoch 4/10
422/422 [==============================] - 8s 18ms/step - loss: 0.9413 - accuracy: 0.6691 - val_loss: 0.9256 - val_accuracy: 0.6763
Epoch 5/10
422/422 [==============================] - 6s 15ms/step - loss: 0.8568 - accuracy: 0.6974 - val_loss: 0.9311 - val_accuracy: 0.6750
Epoch 6/10
422/422 [==============================] - 7s 17ms/step - loss: 0.7818 - accuracy: 0.7263 - val_loss: 0.8742 - val_accuracy: 0.6920
Epoch 7/10
422/422 [==============================] - 6s 15ms/step - loss: 0.7177 - accuracy: 0.7459 - val_loss: 0.8738 - val_accuracy: 0.6925
Epoch 8/10
422/422 [==============================] - 7s 17ms/step - loss: 0.6565 - accuracy: 0.7664 - val_loss: 0.8838 - val_accuracy: 0.6977
Epoch 9/10
422/422 [==============================] - 7s 15ms/step - loss: 0.5971 - accuracy: 0.7863 - val_loss: 0.8960 - val_accuracy: 0.7050
Epoch 10/10
422/422 [==============================] - 7s 18ms/step - loss: 0.5475 - accuracy: 0.8062 - val_loss: 0.9130 - val_accuracy: 0.6992
Epoch 1/10
422/422 [==============================] - 21s 28ms/step - loss: 0.4074 - accuracy: 0.8559 - val_loss: 0.9706 - val_accuracy: 0.7012
Epoch 2/10
422/422 [==============================] - 8s 18ms/step - loss: 0.3358 - accuracy: 0.8812 - val_loss: 1.0682 - val_accuracy: 0.7005
Epoch 3/10
422/422 [==============================] - 8s 20ms/step - loss: 0.2981 - accuracy: 0.8946 - val_loss: 1.1164 - val_accuracy: 0.6982
Epoch 4/10
422/422 [==============================] - 9s 20ms/step - loss: 0.2513 - accuracy: 0.9120 - val_loss: 1.1268 - val_accuracy: 0.7008
Epoch 5/10
422/422 [==============================] - 8s 18ms/step - loss: 0.2294 - accuracy: 0.9187 - val_loss: 1.2172 - val_accuracy: 0.6942
Epoch 6/10
422/422 [==============================] - 9s 20ms/step - loss: 0.2002 - accuracy: 0.9279 - val_loss: 1.3267 - val_accuracy: 0.7003
Epoch 7/10
422/422 [==============================] - 8s 20ms/step - loss: 0.1879 - accuracy: 0.9338 - val_loss: 1.3779 - val_accuracy: 0.6807
Epoch 8/10
422/422 [==============================] - 8s 18ms/step - loss: 0.1834 - accuracy: 0.9353 - val_loss: 1.3365 - val_accuracy: 0.6883
Epoch 9/10
422/422 [==============================] - 8s 20ms/step - loss: 0.1629 - accuracy: 0.9425 - val_loss: 1.4377 - val_accuracy: 0.6902
Epoch 10/10
422/422 [==============================] - 8s 18ms/step - loss: 0.1537 - accuracy: 0.9472 - val_loss: 1.3919 - val_accuracy: 0.6938
188/188 [==============================] - 1s 5ms/step - loss: 0.9130 - accuracy: 0.6992
188/188 [==============================] - 1s 7ms/step - loss: 1.3919 - accuracy: 0.6938
188/188 [==============================] - 1s 4ms/step - loss: 0.9130 - accuracy: 0.6992
Test Accuracy: 0.6991666555404663
Task A Original Accuracy: 69.92%
Task B EWC method Accuracy: 69.38%
Fold-1: 71.13%
Fold-2: 69.92%
Epoch 1/10
422/422 [==============================] - 10s 15ms/step - loss: 1.5919 - accuracy: 0.4204 - val_loss: 1.2945 - val_accuracy: 0.5253
Epoch 2/10
422/422 [==============================] - 6s 14ms/step - loss: 1.2186 - accuracy: 0.5642 - val_loss: 1.1040 - val_accuracy: 0.6072
Epoch 3/10
422/422 [==============================] - 6s 14ms/step - loss: 1.0694 - accuracy: 0.6220 - val_loss: 0.9616 - val_accuracy: 0.6643
Epoch 4/10
422/422 [==============================] - 6s 15ms/step - loss: 0.9582 - accuracy: 0.6606 - val_loss: 0.9106 - val_accuracy: 0.6865
Epoch 5/10
422/422 [==============================] - 6s 14ms/step - loss: 0.8749 - accuracy: 0.6890 - val_loss: 0.8907 - val_accuracy: 0.6873
Epoch 6/10
422/422 [==============================] - 6s 14ms/step - loss: 0.8070 - accuracy: 0.7143 - val_loss: 0.8719 - val_accuracy: 0.7020
Epoch 7/10
422/422 [==============================] - 6s 14ms/step - loss: 0.7328 - accuracy: 0.7415 - val_loss: 0.8283 - val_accuracy: 0.7118
Epoch 8/10
422/422 [==============================] - 6s 15ms/step - loss: 0.6704 - accuracy: 0.7642 - val_loss: 0.8396 - val_accuracy: 0.7155
Epoch 9/10
422/422 [==============================] - 6s 14ms/step - loss: 0.6109 - accuracy: 0.7820 - val_loss: 0.8503 - val_accuracy: 0.7168
Epoch 10/10
422/422 [==============================] - 6s 15ms/step - loss: 0.5639 - accuracy: 0.7995 - val_loss: 0.8924 - val_accuracy: 0.7130
Epoch 1/10
422/422 [==============================] - 14s 22ms/step - loss: 0.4243 - accuracy: 0.8485 - val_loss: 0.9253 - val_accuracy: 0.7167
Epoch 2/10
422/422 [==============================] - 7s 16ms/step - loss: 0.3440 - accuracy: 0.8772 - val_loss: 1.0334 - val_accuracy: 0.7100
Epoch 3/10
422/422 [==============================] - 7s 16ms/step - loss: 0.3023 - accuracy: 0.8917 - val_loss: 1.1308 - val_accuracy: 0.7000
Epoch 4/10
422/422 [==============================] - 7s 17ms/step - loss: 0.2638 - accuracy: 0.9063 - val_loss: 1.1030 - val_accuracy: 0.7058
Epoch 5/10
422/422 [==============================] - 7s 16ms/step - loss: 0.2345 - accuracy: 0.9173 - val_loss: 1.1454 - val_accuracy: 0.7058
Epoch 6/10
422/422 [==============================] - 7s 16ms/step - loss: 0.2118 - accuracy: 0.9263 - val_loss: 1.2067 - val_accuracy: 0.7042
Epoch 7/10
422/422 [==============================] - 7s 16ms/step - loss: 0.1888 - accuracy: 0.9339 - val_loss: 1.2700 - val_accuracy: 0.6987
Epoch 8/10
422/422 [==============================] - 7s 16ms/step - loss: 0.1729 - accuracy: 0.9406 - val_loss: 1.3583 - val_accuracy: 0.6880
Epoch 9/10
422/422 [==============================] - 7s 17ms/step - loss: 0.1637 - accuracy: 0.9429 - val_loss: 1.3535 - val_accuracy: 0.7043
Epoch 10/10
422/422 [==============================] - 7s 16ms/step - loss: 0.1509 - accuracy: 0.9478 - val_loss: 1.3760 - val_accuracy: 0.7050
188/188 [==============================] - 1s 3ms/step - loss: 0.8924 - accuracy: 0.7130
188/188 [==============================] - 1s 5ms/step - loss: 1.3760 - accuracy: 0.7050
188/188 [==============================] - 1s 3ms/step - loss: 0.8924 - accuracy: 0.7130
Test Accuracy: 0.7129999995231628
Task A Original Accuracy: 71.30%
Task B EWC method Accuracy: 70.50%
Fold-1: 71.13%
Fold-2: 69.92%
Fold-3: 71.30%
Epoch 1/10
422/422 [==============================] - 9s 15ms/step - loss: 1.6297 - accuracy: 0.4056 - val_loss: 1.3148 - val_accuracy: 0.5238
Epoch 2/10
422/422 [==============================] - 6s 15ms/step - loss: 1.2567 - accuracy: 0.5510 - val_loss: 1.0984 - val_accuracy: 0.6002
Epoch 3/10
422/422 [==============================] - 6s 14ms/step - loss: 1.0887 - accuracy: 0.6101 - val_loss: 1.0103 - val_accuracy: 0.6305
Epoch 4/10
422/422 [==============================] - 6s 15ms/step - loss: 0.9718 - accuracy: 0.6554 - val_loss: 0.9814 - val_accuracy: 0.6547
Epoch 5/10
422/422 [==============================] - 6s 15ms/step - loss: 0.8895 - accuracy: 0.6830 - val_loss: 0.8879 - val_accuracy: 0.6855
Epoch 6/10
422/422 [==============================] - 6s 15ms/step - loss: 0.8037 - accuracy: 0.7167 - val_loss: 0.9028 - val_accuracy: 0.6827
Epoch 7/10
422/422 [==============================] - 6s 14ms/step - loss: 0.7402 - accuracy: 0.7364 - val_loss: 0.8792 - val_accuracy: 0.6950
Epoch 8/10
422/422 [==============================] - 6s 14ms/step - loss: 0.6704 - accuracy: 0.7613 - val_loss: 0.8536 - val_accuracy: 0.7015
Epoch 9/10
422/422 [==============================] - 6s 15ms/step - loss: 0.6126 - accuracy: 0.7836 - val_loss: 0.8811 - val_accuracy: 0.7002
Epoch 10/10
422/422 [==============================] - 6s 14ms/step - loss: 0.5553 - accuracy: 0.8030 - val_loss: 0.8848 - val_accuracy: 0.7047
Epoch 1/10
422/422 [==============================] - 14s 20ms/step - loss: 0.4113 - accuracy: 0.8541 - val_loss: 0.9638 - val_accuracy: 0.7047
Epoch 2/10
422/422 [==============================] - 7s 17ms/step - loss: 0.3366 - accuracy: 0.8793 - val_loss: 1.0140 - val_accuracy: 0.6957
Epoch 3/10
422/422 [==============================] - 7s 16ms/step - loss: 0.2876 - accuracy: 0.8960 - val_loss: 1.1158 - val_accuracy: 0.6947
Epoch 4/10
422/422 [==============================] - 7s 17ms/step - loss: 0.2516 - accuracy: 0.9099 - val_loss: 1.1502 - val_accuracy: 0.6953
Epoch 5/10
422/422 [==============================] - 7s 16ms/step - loss: 0.2217 - accuracy: 0.9204 - val_loss: 1.2069 - val_accuracy: 0.6895
Epoch 6/10
422/422 [==============================] - 7s 16ms/step - loss: 0.1988 - accuracy: 0.9291 - val_loss: 1.2507 - val_accuracy: 0.6908
Epoch 7/10
422/422 [==============================] - 7s 17ms/step - loss: 0.1798 - accuracy: 0.9374 - val_loss: 1.3696 - val_accuracy: 0.6935
Epoch 8/10
422/422 [==============================] - 7s 16ms/step - loss: 0.1562 - accuracy: 0.9449 - val_loss: 1.4467 - val_accuracy: 0.6850
Epoch 9/10
422/422 [==============================] - 7s 16ms/step - loss: 0.1577 - accuracy: 0.9450 - val_loss: 1.4260 - val_accuracy: 0.6882
Epoch 10/10
422/422 [==============================] - 7s 17ms/step - loss: 0.1439 - accuracy: 0.9506 - val_loss: 1.5029 - val_accuracy: 0.6847
188/188 [==============================] - 1s 3ms/step - loss: 0.8848 - accuracy: 0.7047
188/188 [==============================] - 1s 5ms/step - loss: 1.5029 - accuracy: 0.6847
188/188 [==============================] - 1s 3ms/step - loss: 0.8848 - accuracy: 0.7047
Test Accuracy: 0.7046666741371155
Task A Original Accuracy: 70.47%
Task B EWC method Accuracy: 68.47%
Fold-1: 71.13%
Fold-2: 69.92%
Fold-3: 71.30%
Fold-4: 70.47%
Epoch 1/10
422/422 [==============================] - 9s 15ms/step - loss: 1.6018 - accuracy: 0.4134 - val_loss: 1.3027 - val_accuracy: 0.5278
Epoch 2/10
422/422 [==============================] - 6s 14ms/step - loss: 1.2161 - accuracy: 0.5642 - val_loss: 1.1184 - val_accuracy: 0.5995
Epoch 3/10
422/422 [==============================] - 6s 14ms/step - loss: 1.0553 - accuracy: 0.6244 - val_loss: 0.9987 - val_accuracy: 0.6453
Epoch 4/10
422/422 [==============================] - 6s 15ms/step - loss: 0.9332 - accuracy: 0.6708 - val_loss: 0.9533 - val_accuracy: 0.6707
Epoch 5/10
422/422 [==============================] - 6s 14ms/step - loss: 0.8473 - accuracy: 0.7004 - val_loss: 0.9109 - val_accuracy: 0.6803
Epoch 6/10
422/422 [==============================] - 6s 14ms/step - loss: 0.7729 - accuracy: 0.7269 - val_loss: 0.8870 - val_accuracy: 0.6960
Epoch 7/10
422/422 [==============================] - 6s 14ms/step - loss: 0.6905 - accuracy: 0.7570 - val_loss: 0.8770 - val_accuracy: 0.6958
Epoch 8/10
422/422 [==============================] - 6s 14ms/step - loss: 0.6389 - accuracy: 0.7733 - val_loss: 0.8851 - val_accuracy: 0.7087
Epoch 9/10
422/422 [==============================] - 6s 14ms/step - loss: 0.5756 - accuracy: 0.7967 - val_loss: 0.8844 - val_accuracy: 0.7102
Epoch 10/10
422/422 [==============================] - 6s 14ms/step - loss: 0.5198 - accuracy: 0.8141 - val_loss: 0.8742 - val_accuracy: 0.7075

### CIFAR100

In [ ]:
import numpy as np

import numpy as np

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPool2D,Dense,Flatten,Dropout,Input, AveragePooling2D, Activation,Conv2D, MaxPooling2D, BatchNormalization,Concatenate
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
from tensorflow.keras import regularizers, optimizers
from tensorflow.keras.preprocessing.image import ImageDataGenerator

from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers
from tensorflow.keras.regularizers import Regularizer

# Perform hold-out cross-validation
validation_scores = []

# Define the CrlBo regularizer
class CrlBoRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Number of K-folds
K = 10

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)
# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []
num_classes = 100
# Perform K-fold cross-validation
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]

# Task A: Original Fashion MNIST model
    model = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        Conv2D(32, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu'),
        layers.Dropout(0.25),
        Dense(num_classes, activation='softmax')
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model = model
        model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
        model.save_weights('FashionMNIST_A.h5')
        prior_weights = model.get_weights()
# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    fisher_matrix = []
    for i in range(len(model.trainable_weights)):
        fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

    for _ in range(num_samples):
        idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
        with tf.GradientTape() as tape:
            logits = model(x[idx:idx+1])
        gradients = tape.gradient(logits, model.trainable_weights)
        for i in range(len(fisher_matrix)):
            fisher_matrix[i] += tf.square(gradients[i])

    fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
    return fisher_matrix

fisher_matrix = compute_fisher(model, x_train_fold)
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]
# Task B: Fashion MNIST with CrlBo regularization
    model_CrlBoB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3),
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model_CrlBoB = model_CrlBoB
        model_CrlBoB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model_CrlBoB.load_weights('FashionMNIST_A.h5')
        model_CrlBoB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlBo_acc = 100 * model_CrlBoB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlBo method Accuracy: %.2f%%" % B_CrlBo_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
422/422 [==============================] - 17s 20ms/step - loss: 4.6989 - accuracy: 0.0557 - val_loss: 3.7396 - val_accuracy: 0.1487
Epoch 2/10
422/422 [==============================] - 9s 20ms/step - loss: 3.6261 - accuracy: 0.1580 - val_loss: 3.3517 - val_accuracy: 0.2170
Epoch 3/10
422/422 [==============================] - 8s 18ms/step - loss: 3.2800 - accuracy: 0.2179 - val_loss: 3.0769 - val_accuracy: 0.2683
Epoch 4/10
422/422 [==============================] - 7s 17ms/step - loss: 3.0307 - accuracy: 0.2622 - val_loss: 2.9393 - val_accuracy: 0.2970
Epoch 5/10
422/422 [==============================] - 8s 19ms/step - loss: 2.8378 - accuracy: 0.2973 - val_loss: 2.7915 - val_accuracy: 0.3123
Epoch 6/10
422/422 [==============================] - 8s 18ms/step - loss: 2.6755 - accuracy: 0.3269 - val_loss: 2.7068 - val_accuracy: 0.3278
Epoch 7/10
422/422 [==============================] - 8s 19ms/step - loss: 2.5345 - accuracy: 0.3563 - val_loss: 2.6461 - val_accuracy: 0.3368
Epoch 8/10
422/422 [==============================] - 8s 20ms/step - loss: 2.4048 - accuracy: 0.3826 - val_loss: 2.5804 - val_accuracy: 0.3532
Epoch 9/10
422/422 [==============================] - 7s 18ms/step - loss: 2.2669 - accuracy: 0.4112 - val_loss: 2.5326 - val_accuracy: 0.3647
Epoch 10/10
422/422 [==============================] - 8s 20ms/step - loss: 2.1591 - accuracy: 0.4332 - val_loss: 2.5165 - val_accuracy: 0.3712
Epoch 1/10
422/422 [==============================] - 15s 21ms/step - loss: 4.4786 - accuracy: 0.0836 - val_loss: 3.5125 - val_accuracy: 0.1805
Epoch 2/10
422/422 [==============================] - 9s 22ms/step - loss: 3.3979 - accuracy: 0.1924 - val_loss: 3.0837 - val_accuracy: 0.2537
Epoch 3/10
422/422 [==============================] - 8s 18ms/step - loss: 3.0123 - accuracy: 0.2626 - val_loss: 2.8797 - val_accuracy: 0.2950
Epoch 4/10
422/422 [==============================] - 8s 19ms/step - loss: 2.7549 - accuracy: 0.3088 - val_loss: 2.6104 - val_accuracy: 0.3525
Epoch 5/10
422/422 [==============================] - 8s 19ms/step - loss: 2.5525 - accuracy: 0.3516 - val_loss: 2.4876 - val_accuracy: 0.3737
Epoch 6/10
422/422 [==============================] - 8s 18ms/step - loss: 2.3929 - accuracy: 0.3799 - val_loss: 2.4453 - val_accuracy: 0.3788
Epoch 7/10
422/422 [==============================] - 8s 19ms/step - loss: 2.2458 - accuracy: 0.4132 - val_loss: 2.4191 - val_accuracy: 0.3887
Epoch 8/10
422/422 [==============================] - 8s 19ms/step - loss: 2.1003 - accuracy: 0.4428 - val_loss: 2.3063 - val_accuracy: 0.4097
Epoch 9/10
422/422 [==============================] - 7s 18ms/step - loss: 1.9951 - accuracy: 0.4665 - val_loss: 2.2944 - val_accuracy: 0.4167
Epoch 10/10
422/422 [==============================] - 8s 20ms/step - loss: 1.8804 - accuracy: 0.4882 - val_loss: 2.3278 - val_accuracy: 0.4162
Epoch 1/10
422/422 [==============================] - 14s 21ms/step - loss: 4.5719 - accuracy: 0.0649 - val_loss: 3.6973 - val_accuracy: 0.1578
Epoch 2/10
422/422 [==============================] - 8s 19ms/step - loss: 3.5349 - accuracy: 0.1695 - val_loss: 3.2556 - val_accuracy: 0.2313
Epoch 3/10
422/422 [==============================] - 7s 18ms/step - loss: 3.1609 - accuracy: 0.2349 - val_loss: 2.9263 - val_accuracy: 0.2875
Epoch 4/10
422/422 [==============================] - 8s 20ms/step - loss: 2.8562 - accuracy: 0.2913 - val_loss: 2.7231 - val_accuracy: 0.3208
Epoch 5/10
422/422 [==============================] - 9s 21ms/step - loss: 2.6187 - accuracy: 0.3408 - val_loss: 2.5026 - val_accuracy: 0.3608
Epoch 6/10
422/422 [==============================] - 8s 18ms/step - loss: 2.4195 - accuracy: 0.3800 - val_loss: 2.4449 - val_accuracy: 0.3738
Epoch 7/10
422/422 [==============================] - 8s 19ms/step - loss: 2.2587 - accuracy: 0.4125 - val_loss: 2.3895 - val_accuracy: 0.3860
Epoch 8/10
422/422 [==============================] - 8s 19ms/step - loss: 2.1164 - accuracy: 0.4414 - val_loss: 2.3275 - val_accuracy: 0.4000
Epoch 9/10
422/422 [==============================] - 9s 20ms/step - loss: 1.9961 - accuracy: 0.4669 - val_loss: 2.2632 - val_accuracy: 0.4252
Epoch 10/10
422/422 [==============================] - 8s 20ms/step - loss: 1.8729 - accuracy: 0.4928 - val_loss: 2.2775 - val_accuracy: 0.4243
Epoch 1/10
422/422 [==============================] - 15s 22ms/step - loss: 4.6770 - accuracy: 0.0448 - val_loss: 3.8794 - val_accuracy: 0.1135
Epoch 2/10
422/422 [==============================] - 7s 18ms/step - loss: 3.6938 - accuracy: 0.1399 - val_loss: 3.3393 - val_accuracy: 0.2195
Epoch 3/10
422/422 [==============================] - 8s 19ms/step - loss: 3.2545 - accuracy: 0.2175 - val_loss: 2.9961 - val_accuracy: 0.2680
Epoch 4/10
422/422 [==============================] - 7s 17ms/step - loss: 2.9322 - accuracy: 0.2771 - val_loss: 2.7347 - val_accuracy: 0.3233
Epoch 5/10
422/422 [==============================] - 8s 20ms/step - loss: 2.6888 - accuracy: 0.3234 - val_loss: 2.5854 - val_accuracy: 0.3592
Epoch 6/10
422/422 [==============================] - 9s 21ms/step - loss: 2.4743 - accuracy: 0.3680 - val_loss: 2.4932 - val_accuracy: 0.3698
Epoch 7/10
422/422 [==============================] - 7s 17ms/step - loss: 2.2999 - accuracy: 0.4034 - val_loss: 2.4216 - val_accuracy: 0.3895
Epoch 8/10
422/422 [==============================] - 8s 19ms/step - loss: 2.1554 - accuracy: 0.4320 - val_loss: 2.3357 - val_accuracy: 0.4033
Epoch 9/10
422/422 [==============================] - 7s 17ms/step - loss: 2.0112 - accuracy: 0.4625 - val_loss: 2.3702 - val_accuracy: 0.3950
Epoch 10/10
422/422 [==============================] - 6s 15ms/step - loss: 1.9130 - accuracy: 0.4864 - val_loss: 2.3825 - val_accuracy: 0.4002
Epoch 1/10
422/422 [==============================] - 11s 17ms/step - loss: 4.4933 - accuracy: 0.0655 - val_loss: 3.7002 - val_accuracy: 0.1513
Epoch 2/10
422/422 [==============================] - 6s 15ms/step - loss: 3.5441 - accuracy: 0.1633 - val_loss: 3.3057 - val_accuracy: 0.2240
Epoch 3/10
422/422 [==============================] - 6s 15ms/step - loss: 3.1841 - accuracy: 0.2291 - val_loss: 2.9197 - val_accuracy: 0.2908
Epoch 4/10
422/422 [==============================] - 7s 16ms/step - loss: 2.9164 - accuracy: 0.2798 - val_loss: 2.7379 - val_accuracy: 0.3180
Epoch 5/10
422/422 [==============================] - 6s 15ms/step - loss: 2.7126 - accuracy: 0.3174 - val_loss: 2.6274 - val_accuracy: 0.3505
Epoch 6/10
422/422 [==============================] - 7s 16ms/step - loss: 2.5433 - accuracy: 0.3521 - val_loss: 2.5355 - val_accuracy: 0.3682
Epoch 7/10
422/422 [==============================] - 6s 15ms/step - loss: 2.3960 - accuracy: 0.3806 - val_loss: 2.5174 - val_accuracy: 0.3657
Epoch 8/10
422/422 [==============================] - 7s 16ms/step - loss: 2.2459 - accuracy: 0.4130 - val_loss: 2.3618 - val_accuracy: 0.4072
Epoch 9/10
422/422 [==============================] - 6s 15ms/step - loss: 2.1339 - accuracy: 0.4342 - val_loss: 2.4351 - val_accuracy: 0.3940
Epoch 10/10
422/422 [==============================] - 8s 18ms/step - loss: 2.0089 - accuracy: 0.4615 - val_loss: 2.4161 - val_accuracy: 0.3995
Epoch 1/10
422/422 [==============================] - 12s 17ms/step - loss: 5.3012 - accuracy: 0.0201 - val_loss: 4.2868 - val_accuracy: 0.0625
Epoch 2/10
422/422 [==============================] - 6s 15ms/step - loss: 3.9586 - accuracy: 0.1010 - val_loss: 3.4970 - val_accuracy: 0.1818
Epoch 3/10
422/422 [==============================] - 7s 17ms/step - loss: 3.4857 - accuracy: 0.1726 - val_loss: 3.2296 - val_accuracy: 0.2185
Epoch 4/10
422/422 [==============================] - 6s 15ms/step - loss: 3.1716 - accuracy: 0.2289 - val_loss: 2.9613 - val_accuracy: 0.2858
Epoch 5/10
422/422 [==============================] - 7s 16ms/step - loss: 2.9379 - accuracy: 0.2736 - val_loss: 2.8619 - val_accuracy: 0.2962
Epoch 6/10
422/422 [==============================] - 6s 15ms/step - loss: 2.7536 - accuracy: 0.3121 - val_loss: 2.6668 - val_accuracy: 0.3358
Epoch 7/10
422/422 [==============================] - 7s 16ms/step - loss: 2.5848 - accuracy: 0.3433 - val_loss: 2.5949 - val_accuracy: 0.3450
Epoch 8/10
422/422 [==============================] - 7s 16ms/step - loss: 2.4428 - accuracy: 0.3731 - val_loss: 2.4562 - val_accuracy: 0.3723
Epoch 9/10
422/422 [==============================] - 7s 16ms/step - loss: 2.3046 - accuracy: 0.3998 - val_loss: 2.4252 - val_accuracy: 0.3895
Epoch 10/10
422/422 [==============================] - 6s 15ms/step - loss: 2.1677 - accuracy: 0.4301 - val_loss: 2.4202 - val_accuracy: 0.3902
Epoch 1/10
422/422 [==============================] - 10s 17ms/step - loss: 4.8617 - accuracy: 0.0367 - val_loss: 4.0467 - val_accuracy: 0.0932
Epoch 2/10
422/422 [==============================] - 6s 15ms/step - loss: 3.8420 - accuracy: 0.1179 - val_loss: 3.5448 - val_accuracy: 0.1820
Epoch 3/10
422/422 [==============================] - 7s 15ms/step - loss: 3.4489 - accuracy: 0.1835 - val_loss: 3.2499 - val_accuracy: 0.2413
Epoch 4/10
422/422 [==============================] - 6s 15ms/step - loss: 3.1585 - accuracy: 0.2326 - val_loss: 2.9847 - val_accuracy: 0.2643
Epoch 5/10
422/422 [==============================] - 7s 16ms/step - loss: 2.9245 - accuracy: 0.2773 - val_loss: 2.8225 - val_accuracy: 0.3030
Epoch 6/10
422/422 [==============================] - 6s 15ms/step - loss: 2.7397 - accuracy: 0.3126 - val_loss: 2.7317 - val_accuracy: 0.3188
Epoch 7/10
422/422 [==============================] - 7s 16ms/step - loss: 2.5796 - accuracy: 0.3427 - val_loss: 2.5508 - val_accuracy: 0.3568
Epoch 8/10
422/422 [==============================] - 6s 15ms/step - loss: 2.4218 - accuracy: 0.3802 - val_loss: 2.5590 - val_accuracy: 0.3572
Epoch 9/10
422/422 [==============================] - 7s 17ms/step - loss: 2.2952 - accuracy: 0.4016 - val_loss: 2.4333 - val_accuracy: 0.3738
Epoch 10/10
422/422 [==============================] - 7s 17ms/step - loss: 2.1699 - accuracy: 0.4286 - val_loss: 2.4324 - val_accuracy: 0.3812
Epoch 1/10
422/422 [==============================] - 11s 16ms/step - loss: 4.2678 - accuracy: 0.0804 - val_loss: 3.4961 - val_accuracy: 0.1813
Epoch 2/10
422/422 [==============================] - 7s 16ms/step - loss: 3.3910 - accuracy: 0.1941 - val_loss: 3.1175 - val_accuracy: 0.2540
Epoch 3/10
422/422 [==============================] - 6s 15ms/step - loss: 3.0173 - accuracy: 0.2616 - val_loss: 2.8347 - val_accuracy: 0.3033
Epoch 4/10
422/422 [==============================] - 7s 16ms/step - loss: 2.7397 - accuracy: 0.3135 - val_loss: 2.6740 - val_accuracy: 0.3392
Epoch 5/10
422/422 [==============================] - 6s 15ms/step - loss: 2.5449 - accuracy: 0.3539 - val_loss: 2.5307 - val_accuracy: 0.3595
Epoch 6/10
422/422 [==============================] - 7s 17ms/step - loss: 2.3685 - accuracy: 0.3874 - val_loss: 2.4454 - val_accuracy: 0.3817
Epoch 7/10
422/422 [==============================] - 6s 15ms/step - loss: 2.2126 - accuracy: 0.4194 - val_loss: 2.4158 - val_accuracy: 0.3825
Epoch 8/10
422/422 [==============================] - 7s 16ms/step - loss: 2.0843 - accuracy: 0.4477 - val_loss: 2.3160 - val_accuracy: 0.4123
Epoch 9/10
422/422 [==============================] - 6s 14ms/step - loss: 1.9540 - accuracy: 0.4739 - val_loss: 2.3734 - val_accuracy: 0.4037
Epoch 10/10
422/422 [==============================] - 7s 16ms/step - loss: 1.8498 - accuracy: 0.4983 - val_loss: 2.3552 - val_accuracy: 0.4077
Epoch 1/10
422/422 [==============================] - 12s 19ms/step - loss: 4.9011 - accuracy: 0.0566 - val_loss: 3.6929 - val_accuracy: 0.1488
Epoch 2/10
422/422 [==============================] - 6s 15ms/step - loss: 3.5480 - accuracy: 0.1666 - val_loss: 3.1209 - val_accuracy: 0.2473
Epoch 3/10
422/422 [==============================] - 8s 18ms/step - loss: 3.1062 - accuracy: 0.2458 - val_loss: 2.8409 - val_accuracy: 0.2982
Epoch 4/10
422/422 [==============================] - 8s 19ms/step - loss: 2.8366 - accuracy: 0.2945 - val_loss: 2.6638 - val_accuracy: 0.3258
Epoch 5/10
422/422 [==============================] - 6s 15ms/step - loss: 2.6201 - accuracy: 0.3376 - val_loss: 2.6165 - val_accuracy: 0.3432
Epoch 6/10
422/422 [==============================] - 7s 17ms/step - loss: 2.4477 - accuracy: 0.3741 - val_loss: 2.4936 - val_accuracy: 0.3697
Epoch 7/10
422/422 [==============================] - 6s 15ms/step - loss: 2.2966 - accuracy: 0.4030 - val_loss: 2.4972 - val_accuracy: 0.3713
Epoch 8/10
422/422 [==============================] - 7s 17ms/step - loss: 2.1739 - accuracy: 0.4283 - val_loss: 2.3756 - val_accuracy: 0.3950
Epoch 9/10
422/422 [==============================] - 6s 15ms/step - loss: 2.0328 - accuracy: 0.4620 - val_loss: 2.3215 - val_accuracy: 0.4048
Epoch 10/10
422/422 [==============================] - 7s 16ms/step - loss: 1.9206 - accuracy: 0.4823 - val_loss: 2.3542 - val_accuracy: 0.3980
Epoch 1/10
422/422 [==============================] - 11s 18ms/step - loss: 5.0713 - accuracy: 0.0277 - val_loss: 4.0604 - val_accuracy: 0.0847
Epoch 2/10
422/422 [==============================] - 6s 15ms/step - loss: 3.7843 - accuracy: 0.1279 - val_loss: 3.4170 - val_accuracy: 0.1958
Epoch 3/10
422/422 [==============================] - 7s 16ms/step - loss: 3.3255 - accuracy: 0.2047 - val_loss: 3.0800 - val_accuracy: 0.2547
Epoch 4/10
422/422 [==============================] - 6s 15ms/step - loss: 3.0316 - accuracy: 0.2588 - val_loss: 2.8572 - val_accuracy: 0.2933
Epoch 5/10
422/422 [==============================] - 7s 17ms/step - loss: 2.7781 - accuracy: 0.3067 - val_loss: 2.6700 - val_accuracy: 0.3310
Epoch 6/10
422/422 [==============================] - 6s 15ms/step - loss: 2.5741 - accuracy: 0.3469 - val_loss: 2.5346 - val_accuracy: 0.3622
Epoch 7/10
422/422 [==============================] - 7s 17ms/step - loss: 2.4192 - accuracy: 0.3774 - val_loss: 2.4651 - val_accuracy: 0.3742
Epoch 8/10
422/422 [==============================] - 6s 15ms/step - loss: 2.2736 - accuracy: 0.4096 - val_loss: 2.4712 - val_accuracy: 0.3753
Epoch 9/10
422/422 [==============================] - 6s 14ms/step - loss: 2.1341 - accuracy: 0.4419 - val_loss: 2.4437 - val_accuracy: 0.3890
Epoch 10/10
422/422 [==============================] - 6s 14ms/step - loss: 1.9947 - accuracy: 0.4666 - val_loss: 2.3949 - val_accuracy: 0.3928
Epoch 1/10
422/422 [==============================] - 14s 21ms/step - loss: 1.7813 - accuracy: 0.5220 - val_loss: 1.4702 - val_accuracy: 0.5918
Epoch 2/10
422/422 [==============================] - 7s 16ms/step - loss: 1.5324 - accuracy: 0.5783 - val_loss: 1.5546 - val_accuracy: 0.5712
Epoch 3/10
422/422 [==============================] - 7s 16ms/step - loss: 1.3401 - accuracy: 0.6202 - val_loss: 1.6857 - val_accuracy: 0.5442
Epoch 4/10
422/422 [==============================] - 7s 16ms/step - loss: 1.1529 - accuracy: 0.6660 - val_loss: 1.7850 - val_accuracy: 0.5258
Epoch 5/10
422/422 [==============================] - 7s 16ms/step - loss: 1.0217 - accuracy: 0.7018 - val_loss: 1.9579 - val_accuracy: 0.4988
Epoch 6/10
422/422 [==============================] - 7s 16ms/step - loss: 0.8859 - accuracy: 0.7354 - val_loss: 2.0973 - val_accuracy: 0.4950
Epoch 7/10
422/422 [==============================] - 7s 16ms/step - loss: 0.7964 - accuracy: 0.7598 - val_loss: 2.1605 - val_accuracy: 0.4795
Epoch 8/10
422/422 [==============================] - 7s 16ms/step - loss: 0.7274 - accuracy: 0.7812 - val_loss: 2.3044 - val_accuracy: 0.4867
Epoch 9/10
422/422 [==============================] - 7s 16ms/step - loss: 0.6651 - accuracy: 0.7949 - val_loss: 2.3736 - val_accuracy: 0.4795
Epoch 10/10
422/422 [==============================] - 7s 16ms/step - loss: 0.6288 - accuracy: 0.8071 - val_loss: 2.6179 - val_accuracy: 0.4675
188/188 [==============================] - 1s 3ms/step - loss: 1.4279 - accuracy: 0.6332
188/188 [==============================] - 1s 5ms/step - loss: 2.6179 - accuracy: 0.4675
188/188 [==============================] - 1s 3ms/step - loss: 1.4279 - accuracy: 0.6332
Test Accuracy: 0.6331666707992554
Task A Original Accuracy: 63.32%
Task B CrlBo method Accuracy: 46.75%
Epoch 1/10
422/422 [==============================] - 13s 19ms/step - loss: 1.7743 - accuracy: 0.5232 - val_loss: 1.4762 - val_accuracy: 0.6022
Epoch 2/10
422/422 [==============================] - 7s 16ms/step - loss: 1.5367 - accuracy: 0.5750 - val_loss: 1.5815 - val_accuracy: 0.5692
Epoch 3/10
422/422 [==============================] - 7s 16ms/step - loss: 1.3292 - accuracy: 0.6233 - val_loss: 1.6874 - val_accuracy: 0.5387
Epoch 4/10
422/422 [==============================] - 7s 16ms/step - loss: 1.1461 - accuracy: 0.6687 - val_loss: 1.7866 - val_accuracy: 0.5330
Epoch 5/10
422/422 [==============================] - 7s 16ms/step - loss: 1.0169 - accuracy: 0.7027 - val_loss: 1.9842 - val_accuracy: 0.5095
Epoch 6/10
422/422 [==============================] - 7s 17ms/step - loss: 0.8980 - accuracy: 0.7329 - val_loss: 2.0456 - val_accuracy: 0.5012
Epoch 7/10
422/422 [==============================] - 7s 16ms/step - loss: 0.8025 - accuracy: 0.7593 - val_loss: 2.1788 - val_accuracy: 0.4908
Epoch 8/10
422/422 [==============================] - 7s 16ms/step - loss: 0.7164 - accuracy: 0.7839 - val_loss: 2.3503 - val_accuracy: 0.4813
Epoch 9/10
422/422 [==============================] - 7s 15ms/step - loss: 0.6724 - accuracy: 0.7949 - val_loss: 2.4743 - val_accuracy: 0.4740
Epoch 10/10
422/422 [==============================] - 7s 16ms/step - loss: 0.6013 - accuracy: 0.8153 - val_loss: 2.6079 - val_accuracy: 0.4815
188/188 [==============================] - 1s 3ms/step - loss: 1.4217 - accuracy: 0.6375
188/188 [==============================] - 1s 5ms/step - loss: 2.6079 - accuracy: 0.4815
188/188 [==============================] - 1s 3ms/step - loss: 1.4217 - accuracy: 0.6375
Test Accuracy: 0.637499988079071
Task A Original Accuracy: 63.75%
Task B CrlBo method Accuracy: 48.15%
Epoch 1/10
422/422 [==============================] - 14s 21ms/step - loss: 1.7834 - accuracy: 0.5215 - val_loss: 1.4744 - val_accuracy: 0.5913
Epoch 2/10
422/422 [==============================] - 7s 16ms/step - loss: 1.5413 - accuracy: 0.5758 - val_loss: 1.5558 - val_accuracy: 0.5728
Epoch 3/10
422/422 [==============================] - 7s 16ms/step - loss: 1.3421 - accuracy: 0.6212 - val_loss: 1.6243 - val_accuracy: 0.5553
Epoch 4/10
422/422 [==============================] - 7s 16ms/step - loss: 1.1637 - accuracy: 0.6648 - val_loss: 1.7857 - val_accuracy: 0.5233
Epoch 5/10
422/422 [==============================] - 7s 16ms/step - loss: 1.0217 - accuracy: 0.7008 - val_loss: 1.8731 - val_accuracy: 0.5182
Epoch 6/10
422/422 [==============================] - 7s 16ms/step - loss: 0.8880 - accuracy: 0.7370 - val_loss: 2.1309 - val_accuracy: 0.4968
Epoch 7/10
422/422 [==============================] - 7s 17ms/step - loss: 0.8048 - accuracy: 0.7568 - val_loss: 2.1576 - val_accuracy: 0.5030
Epoch 8/10
422/422 [==============================] - 7s 16ms/step - loss: 0.7079 - accuracy: 0.7845 - val_loss: 2.3186 - val_accuracy: 0.4990
Epoch 9/10
422/422 [==============================] - 7s 17ms/step - loss: 0.6743 - accuracy: 0.7948 - val_loss: 2.4862 - val_accuracy: 0.4778
Epoch 10/10
422/422 [==============================] - 7s 16ms/step - loss: 0.6259 - accuracy: 0.8089 - val_loss: 2.5893 - val_accuracy: 0.4792
188/188 [==============================] - 1s 3ms/step - loss: 1.4035 - accuracy: 0.6387
188/188 [==============================] - 1s 5ms/step - loss: 2.5893 - accuracy: 0.4792
188/188 [==============================] - 1s 3ms/step - loss: 1.4035 - accuracy: 0.6387
Test Accuracy: 0.6386666893959045
Task A Original Accuracy: 63.87%
Task B CrlBo method Accuracy: 47.92%
Epoch 1/10
422/422 [==============================] - 14s 21ms/step - loss: 1.7884 - accuracy: 0.5216 - val_loss: 1.5214 - val_accuracy: 0.5737
Epoch 2/10

### CIFAR100-C

In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPool2D,Dense,Flatten,Dropout,Input, AveragePooling2D, Activation,Conv2D, MaxPooling2D, BatchNormalization,Concatenate
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
from tensorflow.keras import regularizers, optimizers
from tensorflow.keras.preprocessing.image import ImageDataGenerator

from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers
from tensorflow.keras.regularizers import Regularizer

# Perform hold-out cross-validation
validation_scores = []

# Define the CrlBo regularizer
class CrlBoRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Number of K-folds
K = 10

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)
# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []
num_classes = 100
# Perform K-fold cross-validation
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]

# Task A: Original Fashion MNIST model
    model = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        Conv2D(32, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu'),
        layers.Dropout(0.25),
        Dense(num_classes, activation='softmax')
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model = model
        model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
        model.save_weights('FashionMNIST_A.h5')
        prior_weights = model.get_weights()
# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    fisher_matrix = []
    for i in range(len(model.trainable_weights)):
        fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

    for _ in range(num_samples):
        idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
        with tf.GradientTape() as tape:
            logits = model(x[idx:idx+1])
        gradients = tape.gradient(logits, model.trainable_weights)
        for i in range(len(fisher_matrix)):
            fisher_matrix[i] += tf.square(gradients[i])

    fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
    return fisher_matrix

fisher_matrix = compute_fisher(model, x_train_fold)
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]
# Task B: Fashion MNIST with CrlBo regularization
    model_CrlBoB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3),
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),

        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model_CrlBoB = model_CrlBoB
        model_CrlBoB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model_CrlBoB.load_weights('FashionMNIST_A.h5')
        model_CrlBoB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlBo_acc = 100 * model_CrlBoB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlBo method Accuracy: %.2f%%" % B_CrlBo_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)
    for i, score in enumerate(accuracies):
        percent = score * 100
        print("Fold-{}: {:.2f}%".format(i+1, percent))
# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
422/422 [==============================] - 23s 17ms/step - loss: 4.6913 - accuracy: 0.0267 - val_loss: 4.0832 - val_accuracy: 0.0740
Epoch 2/10
422/422 [==============================] - 6s 13ms/step - loss: 3.9136 - accuracy: 0.1030 - val_loss: 3.6599 - val_accuracy: 0.1388
Epoch 3/10
422/422 [==============================] - 6s 13ms/step - loss: 3.6199 - accuracy: 0.1479 - val_loss: 3.4985 - val_accuracy: 0.1640
Epoch 4/10
422/422 [==============================] - 6s 14ms/step - loss: 3.4495 - accuracy: 0.1781 - val_loss: 3.3939 - val_accuracy: 0.1858
Epoch 5/10
422/422 [==============================] - 5s 13ms/step - loss: 3.3214 - accuracy: 0.2007 - val_loss: 3.2473 - val_accuracy: 0.2157
Epoch 6/10
422/422 [==============================] - 6s 14ms/step - loss: 3.2055 - accuracy: 0.2221 - val_loss: 3.1637 - val_accuracy: 0.2338
Epoch 7/10
422/422 [==============================] - 6s 15ms/step - loss: 3.0896 - accuracy: 0.2444 - val_loss: 3.0717 - val_accuracy: 0.2593
Epoch 8/10
422/422 [==============================] - 7s 17ms/step - loss: 2.9772 - accuracy: 0.2684 - val_loss: 3.0196 - val_accuracy: 0.2695
Epoch 9/10
422/422 [==============================] - 6s 15ms/step - loss: 2.8661 - accuracy: 0.2854 - val_loss: 2.9749 - val_accuracy: 0.2688
Epoch 10/10
422/422 [==============================] - 7s 17ms/step - loss: 2.7679 - accuracy: 0.3082 - val_loss: 2.9719 - val_accuracy: 0.2708
Epoch 1/10
422/422 [==============================] - 12s 16ms/step - loss: 4.8912 - accuracy: 0.0099 - val_loss: 4.5864 - val_accuracy: 0.0128
Epoch 2/10
422/422 [==============================] - 8s 19ms/step - loss: 4.1995 - accuracy: 0.0660 - val_loss: 3.8365 - val_accuracy: 0.1228
Epoch 3/10
422/422 [==============================] - 6s 14ms/step - loss: 3.7250 - accuracy: 0.1322 - val_loss: 3.5866 - val_accuracy: 0.1570
Epoch 4/10
422/422 [==============================] - 7s 17ms/step - loss: 3.5143 - accuracy: 0.1686 - val_loss: 3.4030 - val_accuracy: 0.2002
Epoch 5/10
422/422 [==============================] - 7s 16ms/step - loss: 3.3566 - accuracy: 0.1938 - val_loss: 3.2663 - val_accuracy: 0.2182
Epoch 6/10
422/422 [==============================] - 7s 17ms/step - loss: 3.2235 - accuracy: 0.2193 - val_loss: 3.1817 - val_accuracy: 0.2362
Epoch 7/10
422/422 [==============================] - 7s 17ms/step - loss: 3.1156 - accuracy: 0.2429 - val_loss: 3.1169 - val_accuracy: 0.2472
Epoch 8/10
422/422 [==============================] - 6s 15ms/step - loss: 3.0085 - accuracy: 0.2598 - val_loss: 3.0546 - val_accuracy: 0.2613
Epoch 9/10
422/422 [==============================] - 7s 16ms/step - loss: 2.9125 - accuracy: 0.2814 - val_loss: 3.0086 - val_accuracy: 0.2733
Epoch 10/10
422/422 [==============================] - 6s 15ms/step - loss: 2.8166 - accuracy: 0.2965 - val_loss: 2.9679 - val_accuracy: 0.2762
Epoch 1/10
422/422 [==============================] - 9s 14ms/step - loss: 4.6550 - accuracy: 0.0249 - val_loss: 4.1960 - val_accuracy: 0.0563
Epoch 2/10
422/422 [==============================] - 6s 15ms/step - loss: 3.9967 - accuracy: 0.0862 - val_loss: 3.7300 - val_accuracy: 0.1335
Epoch 3/10
422/422 [==============================] - 5s 13ms/step - loss: 3.6843 - accuracy: 0.1372 - val_loss: 3.5141 - val_accuracy: 0.1692
Epoch 4/10
422/422 [==============================] - 6s 14ms/step - loss: 3.5076 - accuracy: 0.1664 - val_loss: 3.4146 - val_accuracy: 0.1948
Epoch 5/10
422/422 [==============================] - 5s 13ms/step - loss: 3.3821 - accuracy: 0.1899 - val_loss: 3.3285 - val_accuracy: 0.2125
Epoch 6/10
422/422 [==============================] - 6s 15ms/step - loss: 3.2806 - accuracy: 0.2075 - val_loss: 3.2561 - val_accuracy: 0.2227
Epoch 7/10
422/422 [==============================] - 5s 13ms/step - loss: 3.1719 - accuracy: 0.2252 - val_loss: 3.1828 - val_accuracy: 0.2303
Epoch 8/10
422/422 [==============================] - 6s 13ms/step - loss: 3.0708 - accuracy: 0.2456 - val_loss: 3.0851 - val_accuracy: 0.2520
Epoch 9/10
422/422 [==============================] - 6s 13ms/step - loss: 2.9833 - accuracy: 0.2611 - val_loss: 3.0976 - val_accuracy: 0.2510
Epoch 10/10
422/422 [==============================] - 6s 14ms/step - loss: 2.8873 - accuracy: 0.2811 - val_loss: 3.0010 - val_accuracy: 0.2782
Epoch 1/10
422/422 [==============================] - 10s 16ms/step - loss: 4.7864 - accuracy: 0.0154 - val_loss: 4.3981 - val_accuracy: 0.0432
Epoch 2/10
422/422 [==============================] - 5s 13ms/step - loss: 4.1735 - accuracy: 0.0700 - val_loss: 3.9722 - val_accuracy: 0.1010
Epoch 3/10
422/422 [==============================] - 6s 15ms/step - loss: 3.8656 - accuracy: 0.1139 - val_loss: 3.7236 - val_accuracy: 0.1507
Epoch 4/10
422/422 [==============================] - 6s 13ms/step - loss: 3.6584 - accuracy: 0.1449 - val_loss: 3.5335 - val_accuracy: 0.1728
Epoch 5/10
422/422 [==============================] - 7s 15ms/step - loss: 3.4881 - accuracy: 0.1726 - val_loss: 3.3923 - val_accuracy: 0.1948
Epoch 6/10
422/422 [==============================] - 6s 13ms/step - loss: 3.3577 - accuracy: 0.1957 - val_loss: 3.3141 - val_accuracy: 0.2092
Epoch 7/10
422/422 [==============================] - 6s 13ms/step - loss: 3.2474 - accuracy: 0.2132 - val_loss: 3.2721 - val_accuracy: 0.2230
Epoch 8/10
422/422 [==============================] - 6s 14ms/step - loss: 3.1405 - accuracy: 0.2343 - val_loss: 3.1538 - val_accuracy: 0.2438
Epoch 9/10
422/422 [==============================] - 6s 13ms/step - loss: 3.0437 - accuracy: 0.2527 - val_loss: 3.1253 - val_accuracy: 0.2512
Epoch 10/10
422/422 [==============================] - 6s 14ms/step - loss: 2.9560 - accuracy: 0.2683 - val_loss: 3.0592 - val_accuracy: 0.2567
Epoch 1/10
422/422 [==============================] - 10s 16ms/step - loss: 4.7483 - accuracy: 0.0246 - val_loss: 4.1774 - val_accuracy: 0.0577
Epoch 2/10
422/422 [==============================] - 5s 13ms/step - loss: 4.0373 - accuracy: 0.0806 - val_loss: 3.8527 - val_accuracy: 0.1135
Epoch 3/10
422/422 [==============================] - 6s 14ms/step - loss: 3.7834 - accuracy: 0.1204 - val_loss: 3.6601 - val_accuracy: 0.1500
Epoch 4/10
422/422 [==============================] - 5s 13ms/step - loss: 3.6051 - accuracy: 0.1502 - val_loss: 3.5018 - val_accuracy: 0.1790
Epoch 5/10
422/422 [==============================] - 6s 15ms/step - loss: 3.4525 - accuracy: 0.1764 - val_loss: 3.3803 - val_accuracy: 0.2012
Epoch 6/10
422/422 [==============================] - 5s 13ms/step - loss: 3.3426 - accuracy: 0.1952 - val_loss: 3.2668 - val_accuracy: 0.2217
Epoch 7/10
422/422 [==============================] - 6s 14ms/step - loss: 3.2288 - accuracy: 0.2163 - val_loss: 3.1705 - val_accuracy: 0.2422
Epoch 8/10
422/422 [==============================] - 6s 15ms/step - loss: 3.1284 - accuracy: 0.2340 - val_loss: 3.1300 - val_accuracy: 0.2482
Epoch 9/10
422/422 [==============================] - 6s 14ms/step - loss: 3.0445 - accuracy: 0.2520 - val_loss: 3.1156 - val_accuracy: 0.2483
Epoch 10/10
422/422 [==============================] - 6s 13ms/step - loss: 2.9548 - accuracy: 0.2663 - val_loss: 3.0604 - val_accuracy: 0.2582
Epoch 1/10
422/422 [==============================] - 10s 16ms/step - loss: 4.6939 - accuracy: 0.0293 - val_loss: 4.0360 - val_accuracy: 0.0835
Epoch 2/10
422/422 [==============================] - 5s 13ms/step - loss: 3.8909 - accuracy: 0.1033 - val_loss: 3.6506 - val_accuracy: 0.1482
Epoch 3/10
422/422 [==============================] - 6s 15ms/step - loss: 3.6412 - accuracy: 0.1452 - val_loss: 3.4820 - val_accuracy: 0.1853
Epoch 4/10
422/422 [==============================] - 6s 13ms/step - loss: 3.4673 - accuracy: 0.1740 - val_loss: 3.3211 - val_accuracy: 0.2128
Epoch 5/10
422/422 [==============================] - 6s 14ms/step - loss: 3.3251 - accuracy: 0.1994 - val_loss: 3.1651 - val_accuracy: 0.2370
Epoch 6/10
422/422 [==============================] - 6s 13ms/step - loss: 3.2016 - accuracy: 0.2196 - val_loss: 3.1315 - val_accuracy: 0.2440
Epoch 7/10
422/422 [==============================] - 6s 15ms/step - loss: 3.0911 - accuracy: 0.2424 - val_loss: 3.0565 - val_accuracy: 0.2570
Epoch 8/10
422/422 [==============================] - 5s 13ms/step - loss: 2.9937 - accuracy: 0.2603 - val_loss: 2.9867 - val_accuracy: 0.2670
Epoch 9/10
422/422 [==============================] - 6s 14ms/step - loss: 2.8947 - accuracy: 0.2784 - val_loss: 2.9113 - val_accuracy: 0.2868
Epoch 10/10
422/422 [==============================] - 5s 13ms/step - loss: 2.8014 - accuracy: 0.2982 - val_loss: 2.9236 - val_accuracy: 0.2890
Epoch 1/10
422/422 [==============================] - 10s 16ms/step - loss: 4.7625 - accuracy: 0.0237 - val_loss: 4.1927 - val_accuracy: 0.0620
Epoch 2/10
422/422 [==============================] - 5s 13ms/step - loss: 3.9812 - accuracy: 0.0927 - val_loss: 3.7191 - val_accuracy: 0.1308
Epoch 3/10
422/422 [==============================] - 6s 14ms/step - loss: 3.6598 - accuracy: 0.1447 - val_loss: 3.4803 - val_accuracy: 0.1850
Epoch 4/10
422/422 [==============================] - 5s 13ms/step - loss: 3.4452 - accuracy: 0.1805 - val_loss: 3.3015 - val_accuracy: 0.2127
Epoch 5/10
422/422 [==============================] - 6s 14ms/step - loss: 3.2926 - accuracy: 0.2082 - val_loss: 3.1927 - val_accuracy: 0.2378
Epoch 6/10
422/422 [==============================] - 5s 13ms/step - loss: 3.1640 - accuracy: 0.2296 - val_loss: 3.0826 - val_accuracy: 0.2547
Epoch 7/10
422/422 [==============================] - 6s 13ms/step - loss: 3.0618 - accuracy: 0.2499 - val_loss: 3.0434 - val_accuracy: 0.2617
Epoch 8/10
422/422 [==============================] - 6s 13ms/step - loss: 2.9613 - accuracy: 0.2675 - val_loss: 2.9929 - val_accuracy: 0.2722
Epoch 9/10
422/422 [==============================] - 5s 12ms/step - loss: 2.8622 - accuracy: 0.2870 - val_loss: 2.9301 - val_accuracy: 0.2922
Epoch 10/10
422/422 [==============================] - 6s 15ms/step - loss: 2.7788 - accuracy: 0.3043 - val_loss: 2.9545 - val_accuracy: 0.2845
Epoch 1/10
422/422 [==============================] - 9s 13ms/step - loss: 4.8439 - accuracy: 0.0202 - val_loss: 4.2738 - val_accuracy: 0.0460
Epoch 2/10
422/422 [==============================] - 5s 12ms/step - loss: 4.0283 - accuracy: 0.0834 - val_loss: 3.8204 - val_accuracy: 0.1235
Epoch 3/10
422/422 [==============================] - 5s 12ms/step - loss: 3.7610 - accuracy: 0.1213 - val_loss: 3.6289 - val_accuracy: 0.1588
Epoch 4/10
422/422 [==============================] - 5s 12ms/step - loss: 3.5791 - accuracy: 0.1532 - val_loss: 3.4571 - val_accuracy: 0.1830
Epoch 5/10
422/422 [==============================] - 5s 12ms/step - loss: 3.4416 - accuracy: 0.1765 - val_loss: 3.3127 - val_accuracy: 0.2088
Epoch 6/10
422/422 [==============================] - 5s 12ms/step - loss: 3.3092 - accuracy: 0.1991 - val_loss: 3.2384 - val_accuracy: 0.2245
Epoch 7/10
422/422 [==============================] - 5s 12ms/step - loss: 3.1965 - accuracy: 0.2211 - val_loss: 3.1548 - val_accuracy: 0.2342
Epoch 8/10
422/422 [==============================] - 5s 12ms/step - loss: 3.0806 - accuracy: 0.2435 - val_loss: 3.0635 - val_accuracy: 0.2592
Epoch 9/10
422/422 [==============================] - 5s 11ms/step - loss: 2.9665 - accuracy: 0.2649 - val_loss: 2.9913 - val_accuracy: 0.2742
Epoch 10/10
422/422 [==============================] - 5s 12ms/step - loss: 2.8572 - accuracy: 0.2865 - val_loss: 2.9953 - val_accuracy: 0.2730

### SVHN

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPool2D,Dense,Flatten,Dropout,Input, AveragePooling2D, Activation,Conv2D, MaxPooling2D, BatchNormalization,Concatenate
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
from tensorflow.keras import regularizers, optimizers
from tensorflow.keras.preprocessing.image import ImageDataGenerator

from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers
from tensorflow.keras.regularizers import Regularizer

# Perform hold-out cross-validation
validation_scores = []

# Define the CrlBo regularizer
class CrlBoRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Number of K-folds
K = 10

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)
# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []
num_classes = 10
# Perform K-fold cross-validation
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]

# Task A: Original SVHN model
    model = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        Conv2D(32, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu'),
        layers.Dropout(0.25),
        Dense(num_classes, activation='softmax')
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model = model
        model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
        model.save_weights('FashionMNIST_A.h5')
        prior_weights = model.get_weights()
# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    fisher_matrix = []
    for i in range(len(model.trainable_weights)):
        fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

    for _ in range(num_samples):
        idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
        with tf.GradientTape() as tape:
            logits = model(x[idx:idx+1])
        gradients = tape.gradient(logits, model.trainable_weights)
        for i in range(len(fisher_matrix)):
            fisher_matrix[i] += tf.square(gradients[i])

    fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
    return fisher_matrix

fisher_matrix = compute_fisher(model, x_train_fold)
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]
# Task B: Fashion SVHN with CrlBo regularization
    model_CrlBoB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3),
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model_CrlBoB = model_CrlBoB
        model_CrlBoB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model_CrlBoB.load_weights('FashionMNIST_A.h5')
        model_CrlBoB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlBo_acc = 100 * model_CrlBoB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlBo method Accuracy: %.2f%%" % B_CrlBo_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
699/699 [==============================] - 27s 17ms/step - loss: 1.6507 - accuracy: 0.5513 - val_loss: 0.5166 - val_accuracy: 0.8497
Epoch 2/10
699/699 [==============================] - 11s 15ms/step - loss: 0.5727 - accuracy: 0.8261 - val_loss: 0.4051 - val_accuracy: 0.8864
Epoch 3/10
699/699 [==============================] - 11s 16ms/step - loss: 0.4497 - accuracy: 0.8660 - val_loss: 0.3346 - val_accuracy: 0.9055
Epoch 4/10
699/699 [==============================] - 11s 16ms/step - loss: 0.3843 - accuracy: 0.8854 - val_loss: 0.2924 - val_accuracy: 0.9189
Epoch 5/10
699/699 [==============================] - 11s 15ms/step - loss: 0.3416 - accuracy: 0.8987 - val_loss: 0.2886 - val_accuracy: 0.9192
Epoch 6/10
699/699 [==============================] - 11s 16ms/step - loss: 0.3206 - accuracy: 0.9037 - val_loss: 0.2725 - val_accuracy: 0.9251
Epoch 7/10
699/699 [==============================] - 10s 15ms/step - loss: 0.2946 - accuracy: 0.9109 - val_loss: 0.2602 - val_accuracy: 0.9307
Epoch 8/10
699/699 [==============================] - 11s 16ms/step - loss: 0.2740 - accuracy: 0.9182 - val_loss: 0.2592 - val_accuracy: 0.9311
Epoch 9/10
699/699 [==============================] - 12s 17ms/step - loss: 0.2557 - accuracy: 0.9224 - val_loss: 0.2781 - val_accuracy: 0.9289
Epoch 10/10
699/699 [==============================] - 11s 15ms/step - loss: 0.2419 - accuracy: 0.9258 - val_loss: 0.2564 - val_accuracy: 0.9310
Epoch 1/10
699/699 [==============================] - 15s 16ms/step - loss: 2.3433 - accuracy: 0.3667 - val_loss: 0.7140 - val_accuracy: 0.7896
Epoch 2/10
699/699 [==============================] - 11s 16ms/step - loss: 0.6956 - accuracy: 0.7881 - val_loss: 0.4494 - val_accuracy: 0.8715
Epoch 3/10
699/699 [==============================] - 11s 15ms/step - loss: 0.5280 - accuracy: 0.8390 - val_loss: 0.3656 - val_accuracy: 0.8970
Epoch 4/10
699/699 [==============================] - 11s 16ms/step - loss: 0.4438 - accuracy: 0.8674 - val_loss: 0.3342 - val_accuracy: 0.9062
Epoch 5/10
699/699 [==============================] - 10s 15ms/step - loss: 0.3906 - accuracy: 0.8825 - val_loss: 0.3140 - val_accuracy: 0.9141
Epoch 6/10
699/699 [==============================] - 11s 15ms/step - loss: 0.3552 - accuracy: 0.8930 - val_loss: 0.2803 - val_accuracy: 0.9211
Epoch 7/10
699/699 [==============================] - 11s 16ms/step - loss: 0.3221 - accuracy: 0.9036 - val_loss: 0.2893 - val_accuracy: 0.9160
Epoch 8/10
699/699 [==============================] - 11s 16ms/step - loss: 0.2887 - accuracy: 0.9137 - val_loss: 0.2584 - val_accuracy: 0.9293
Epoch 9/10
699/699 [==============================] - 11s 16ms/step - loss: 0.2694 - accuracy: 0.9190 - val_loss: 0.2437 - val_accuracy: 0.9339
Epoch 10/10
699/699 [==============================] - 10s 14ms/step - loss: 0.2524 - accuracy: 0.9230 - val_loss: 0.2605 - val_accuracy: 0.9305
Epoch 1/10
699/699 [==============================] - 12s 14ms/step - loss: 2.5116 - accuracy: 0.3858 - val_loss: 0.6950 - val_accuracy: 0.7940
Epoch 2/10
699/699 [==============================] - 10s 14ms/step - loss: 0.7263 - accuracy: 0.7774 - val_loss: 0.4620 - val_accuracy: 0.8670
Epoch 3/10
699/699 [==============================] - 9s 13ms/step - loss: 0.5467 - accuracy: 0.8357 - val_loss: 0.4199 - val_accuracy: 0.8734
Epoch 4/10
699/699 [==============================] - 9s 13ms/step - loss: 0.4593 - accuracy: 0.8621 - val_loss: 0.3532 - val_accuracy: 0.9020
Epoch 5/10
699/699 [==============================] - 9s 13ms/step - loss: 0.4002 - accuracy: 0.8794 - val_loss: 0.3262 - val_accuracy: 0.9048
Epoch 6/10
699/699 [==============================] - 10s 14ms/step - loss: 0.3584 - accuracy: 0.8937 - val_loss: 0.3186 - val_accuracy: 0.9123
Epoch 7/10
699/699 [==============================] - 9s 13ms/step - loss: 0.3279 - accuracy: 0.9029 - val_loss: 0.3015 - val_accuracy: 0.9192
Epoch 8/10
699/699 [==============================] - 10s 14ms/step - loss: 0.2975 - accuracy: 0.9099 - val_loss: 0.3028 - val_accuracy: 0.9159
Epoch 9/10
699/699 [==============================] - 9s 13ms/step - loss: 0.2791 - accuracy: 0.9155 - val_loss: 0.2835 - val_accuracy: 0.9240
Epoch 10/10
699/699 [==============================] - 9s 13ms/step - loss: 0.2658 - accuracy: 0.9198 - val_loss: 0.2661 - val_accuracy: 0.9298
Epoch 1/10
699/699 [==============================] - 12s 14ms/step - loss: 1.8822 - accuracy: 0.5633 - val_loss: 0.5934 - val_accuracy: 0.8269
Epoch 2/10
699/699 [==============================] - 9s 14ms/step - loss: 0.6121 - accuracy: 0.8167 - val_loss: 0.4203 - val_accuracy: 0.8792
Epoch 3/10
699/699 [==============================] - 9s 14ms/step - loss: 0.4663 - accuracy: 0.8624 - val_loss: 0.3044 - val_accuracy: 0.9141
Epoch 4/10
699/699 [==============================] - 10s 14ms/step - loss: 0.3894 - accuracy: 0.8853 - val_loss: 0.2901 - val_accuracy: 0.9194
Epoch 5/10
699/699 [==============================] - 10s 14ms/step - loss: 0.3438 - accuracy: 0.8979 - val_loss: 0.2764 - val_accuracy: 0.9218
Epoch 6/10
699/699 [==============================] - 10s 14ms/step - loss: 0.3078 - accuracy: 0.9086 - val_loss: 0.2539 - val_accuracy: 0.9278
Epoch 7/10
699/699 [==============================] - 10s 14ms/step - loss: 0.2900 - accuracy: 0.9144 - val_loss: 0.2578 - val_accuracy: 0.9289
Epoch 8/10
699/699 [==============================] - 10s 14ms/step - loss: 0.2666 - accuracy: 0.9192 - val_loss: 0.2554 - val_accuracy: 0.9307
Epoch 9/10
699/699 [==============================] - 10s 14ms/step - loss: 0.2466 - accuracy: 0.9256 - val_loss: 0.2758 - val_accuracy: 0.9214
Epoch 10/10
699/699 [==============================] - 10s 14ms/step - loss: 0.2345 - accuracy: 0.9288 - val_loss: 0.2400 - val_accuracy: 0.9337
Epoch 1/10
699/699 [==============================] - 12s 14ms/step - loss: 1.7268 - accuracy: 0.5614 - val_loss: 0.6464 - val_accuracy: 0.8088
Epoch 2/10
699/699 [==============================] - 10s 14ms/step - loss: 0.6825 - accuracy: 0.7864 - val_loss: 0.5216 - val_accuracy: 0.8517
Epoch 3/10
699/699 [==============================] - 9s 14ms/step - loss: 0.5550 - accuracy: 0.8266 - val_loss: 0.3864 - val_accuracy: 0.8811
Epoch 4/10
699/699 [==============================] - 10s 14ms/step - loss: 0.4719 - accuracy: 0.8557 - val_loss: 0.3461 - val_accuracy: 0.8955
Epoch 5/10
699/699 [==============================] - 10s 14ms/step - loss: 0.4128 - accuracy: 0.8743 - val_loss: 0.3188 - val_accuracy: 0.9051
Epoch 6/10
699/699 [==============================] - 10s 14ms/step - loss: 0.3656 - accuracy: 0.8885 - val_loss: 0.3108 - val_accuracy: 0.9071
Epoch 7/10
699/699 [==============================] - 10s 14ms/step - loss: 0.3339 - accuracy: 0.8998 - val_loss: 0.2952 - val_accuracy: 0.9125
Epoch 8/10
699/699 [==============================] - 10s 14ms/step - loss: 0.3126 - accuracy: 0.9053 - val_loss: 0.3051 - val_accuracy: 0.9105
Epoch 9/10
699/699 [==============================] - 10s 14ms/step - loss: 0.2958 - accuracy: 0.9102 - val_loss: 0.2609 - val_accuracy: 0.9260
Epoch 10/10
699/699 [==============================] - 10s 14ms/step - loss: 0.2757 - accuracy: 0.9163 - val_loss: 0.2513 - val_accuracy: 0.9274
Epoch 1/10
699/699 [==============================] - 12s 14ms/step - loss: 1.4775 - accuracy: 0.5948 - val_loss: 0.6251 - val_accuracy: 0.8217
Epoch 2/10
699/699 [==============================] - 9s 14ms/step - loss: 0.7165 - accuracy: 0.7771 - val_loss: 0.4742 - val_accuracy: 0.8631
Epoch 3/10
699/699 [==============================] - 10s 14ms/step - loss: 0.5556 - accuracy: 0.8296 - val_loss: 0.4011 - val_accuracy: 0.8814
Epoch 4/10
699/699 [==============================] - 9s 13ms/step - loss: 0.4676 - accuracy: 0.8557 - val_loss: 0.3686 - val_accuracy: 0.8943
Epoch 5/10
699/699 [==============================] - 9s 13ms/step - loss: 0.4075 - accuracy: 0.8761 - val_loss: 0.3324 - val_accuracy: 0.9083
Epoch 6/10
699/699 [==============================] - 9s 13ms/step - loss: 0.3696 - accuracy: 0.8868 - val_loss: 0.3305 - val_accuracy: 0.9054
Epoch 7/10
699/699 [==============================] - 9s 13ms/step - loss: 0.3323 - accuracy: 0.8982 - val_loss: 0.3087 - val_accuracy: 0.9094
Epoch 8/10
699/699 [==============================] - 9s 13ms/step - loss: 0.3059 - accuracy: 0.9069 - val_loss: 0.3074 - val_accuracy: 0.9143
Epoch 9/10
699/699 [==============================] - 9s 13ms/step - loss: 0.2822 - accuracy: 0.9143 - val_loss: 0.2906 - val_accuracy: 0.9192
Epoch 10/10
699/699 [==============================] - 9s 14ms/step - loss: 0.2643 - accuracy: 0.9193 - val_loss: 0.2820 - val_accuracy: 0.9238
Epoch 1/10
699/699 [==============================] - 12s 14ms/step - loss: 2.3350 - accuracy: 0.4283 - val_loss: 0.6471 - val_accuracy: 0.8125
Epoch 2/10
699/699 [==============================] - 10s 14ms/step - loss: 0.6285 - accuracy: 0.8079 - val_loss: 0.4329 - val_accuracy: 0.8784
Epoch 3/10
699/699 [==============================] - 10s 14ms/step - loss: 0.4759 - accuracy: 0.8570 - val_loss: 0.3825 - val_accuracy: 0.8919
Epoch 4/10
699/699 [==============================] - 9s 13ms/step - loss: 0.4002 - accuracy: 0.8792 - val_loss: 0.3368 - val_accuracy: 0.9078
Epoch 5/10
699/699 [==============================] - 9s 14ms/step - loss: 0.3534 - accuracy: 0.8941 - val_loss: 0.3073 - val_accuracy: 0.9169
Epoch 6/10
699/699 [==============================] - 9s 13ms/step - loss: 0.3174 - accuracy: 0.9057 - val_loss: 0.3031 - val_accuracy: 0.9196
Epoch 7/10
699/699 [==============================] - 9s 13ms/step - loss: 0.2952 - accuracy: 0.9114 - val_loss: 0.3095 - val_accuracy: 0.9175
Epoch 8/10
699/699 [==============================] - 9s 13ms/step - loss: 0.2768 - accuracy: 0.9164 - val_loss: 0.2806 - val_accuracy: 0.9283
Epoch 9/10
699/699 [==============================] - 10s 14ms/step - loss: 0.2581 - accuracy: 0.9216 - val_loss: 0.2963 - val_accuracy: 0.9241
Epoch 10/10
699/699 [==============================] - 9s 14ms/step - loss: 0.2412 - accuracy: 0.9273 - val_loss: 0.2906 - val_accuracy: 0.9258
Epoch 1/10
699/699 [==============================] - 12s 14ms/step - loss: 1.7949 - accuracy: 0.6019 - val_loss: 0.5943 - val_accuracy: 0.8311
Epoch 2/10
699/699 [==============================] - 10s 14ms/step - loss: 0.6248 - accuracy: 0.8108 - val_loss: 0.4368 - val_accuracy: 0.8732
Epoch 3/10
699/699 [==============================] - 10s 14ms/step - loss: 0.5076 - accuracy: 0.8486 - val_loss: 0.4440 - val_accuracy: 0.8718
Epoch 4/10
699/699 [==============================] - 9s 13ms/step - loss: 0.4248 - accuracy: 0.8731 - val_loss: 0.3519 - val_accuracy: 0.9001
Epoch 5/10
699/699 [==============================] - 10s 14ms/step - loss: 0.3776 - accuracy: 0.8883 - val_loss: 0.3239 - val_accuracy: 0.9102
Epoch 6/10
699/699 [==============================] - 10s 14ms/step - loss: 0.3353 - accuracy: 0.8993 - val_loss: 0.2834 - val_accuracy: 0.9201
Epoch 7/10
699/699 [==============================] - 9s 14ms/step - loss: 0.3120 - accuracy: 0.9065 - val_loss: 0.3027 - val_accuracy: 0.9167
Epoch 8/10
699/699 [==============================] - 10s 14ms/step - loss: 0.2910 - accuracy: 0.9122 - val_loss: 0.2704 - val_accuracy: 0.9258
Epoch 9/10
699/699 [==============================] - 9s 14ms/step - loss: 0.2705 - accuracy: 0.9183 - val_loss: 0.2810 - val_accuracy: 0.9282
Epoch 10/10
699/699 [==============================] - 10s 14ms/step - loss: 0.2541 - accuracy: 0.9220 - val_loss: 0.2930 - val_accuracy: 0.9263
Epoch 1/10
699/699 [==============================] - 12s 14ms/step - loss: 2.0173 - accuracy: 0.4497 - val_loss: 0.7120 - val_accuracy: 0.8029
Epoch 2/10
699/699 [==============================] - 10s 14ms/step - loss: 0.7748 - accuracy: 0.7627 - val_loss: 0.4876 - val_accuracy: 0.8570
Epoch 3/10
699/699 [==============================] - 10s 14ms/step - loss: 0.5477 - accuracy: 0.8362 - val_loss: 0.3727 - val_accuracy: 0.8924
Epoch 4/10
699/699 [==============================] - 9s 13ms/step - loss: 0.4535 - accuracy: 0.8637 - val_loss: 0.3135 - val_accuracy: 0.9118
Epoch 5/10
699/699 [==============================] - 10s 14ms/step - loss: 0.3960 - accuracy: 0.8802 - val_loss: 0.3774 - val_accuracy: 0.8903
Epoch 6/10
699/699 [==============================] - 10s 14ms/step - loss: 0.3594 - accuracy: 0.8925 - val_loss: 0.2848 - val_accuracy: 0.9175
Epoch 7/10
699/699 [==============================] - 10s 14ms/step - loss: 0.3205 - accuracy: 0.9032 - val_loss: 0.2889 - val_accuracy: 0.9155
Epoch 8/10
699/699 [==============================] - 9s 14ms/step - loss: 0.2987 - accuracy: 0.9109 - val_loss: 0.2705 - val_accuracy: 0.9232
Epoch 9/10
699/699 [==============================] - 9s 13ms/step - loss: 0.2730 - accuracy: 0.9178 - val_loss: 0.2557 - val_accuracy: 0.9280
Epoch 10/10
699/699 [==============================] - 10s 14ms/step - loss: 0.2501 - accuracy: 0.9244 - val_loss: 0.2591 - val_accuracy: 0.9259
Epoch 1/10
699/699 [==============================] - 12s 15ms/step - loss: 1.5980 - accuracy: 0.5979 - val_loss: 0.6440 - val_accuracy: 0.8038
Epoch 2/10
699/699 [==============================] - 10s 14ms/step - loss: 0.6568 - accuracy: 0.7979 - val_loss: 0.4436 - val_accuracy: 0.8743
Epoch 3/10
699/699 [==============================] - 10s 14ms/step - loss: 0.5414 - accuracy: 0.8353 - val_loss: 0.3966 - val_accuracy: 0.8851
Epoch 4/10
699/699 [==============================] - 9s 13ms/step - loss: 0.4622 - accuracy: 0.8599 - val_loss: 0.3665 - val_accuracy: 0.8943
Epoch 5/10
699/699 [==============================] - 10s 14ms/step - loss: 0.4096 - accuracy: 0.8765 - val_loss: 0.3330 - val_accuracy: 0.9033
Epoch 6/10
699/699 [==============================] - 9s 14ms/step - loss: 0.3665 - accuracy: 0.8888 - val_loss: 0.3110 - val_accuracy: 0.9133
Epoch 7/10
699/699 [==============================] - 10s 14ms/step - loss: 0.3360 - accuracy: 0.8991 - val_loss: 0.2887 - val_accuracy: 0.9188
Epoch 8/10
699/699 [==============================] - 10s 14ms/step - loss: 0.3064 - accuracy: 0.9070 - val_loss: 0.2762 - val_accuracy: 0.9198
Epoch 9/10
699/699 [==============================] - 9s 13ms/step - loss: 0.2887 - accuracy: 0.9126 - val_loss: 0.2730 - val_accuracy: 0.9263
Epoch 10/10
699/699 [==============================] - 10s 14ms/step - loss: 0.2716 - accuracy: 0.9172 - val_loss: 0.2711 - val_accuracy: 0.9256
Epoch 1/10
699/699 [==============================] - 20s 19ms/step - loss: 0.2416 - accuracy: 0.9278 - val_loss: 0.1678 - val_accuracy: 0.9544
Epoch 2/10
699/699 [==============================] - 11s 16ms/step - loss: 0.2108 - accuracy: 0.9357 - val_loss: 0.1717 - val_accuracy: 0.9540
Epoch 3/10
699/699 [==============================] - 11s 16ms/step - loss: 0.1900 - accuracy: 0.9424 - val_loss: 0.1922 - val_accuracy: 0.9460
Epoch 4/10
699/699 [==============================] - 11s 16ms/step - loss: 0.1759 - accuracy: 0.9456 - val_loss: 0.2026 - val_accuracy: 0.9412
Epoch 5/10
699/699 [==============================] - 11s 16ms/step - loss: 0.1565 - accuracy: 0.9509 - val_loss: 0.2011 - val_accuracy: 0.9446
Epoch 6/10
699/699 [==============================] - 11s 16ms/step - loss: 0.1493 - accuracy: 0.9529 - val_loss: 0.2050 - val_accuracy: 0.9446
Epoch 7/10
699/699 [==============================] - 11s 16ms/step - loss: 0.1383 - accuracy: 0.9566 - val_loss: 0.2050 - val_accuracy: 0.9461
Epoch 8/10
699/699 [==============================] - 11s 16ms/step - loss: 0.1293 - accuracy: 0.9587 - val_loss: 0.2228 - val_accuracy: 0.9422
Epoch 9/10
699/699 [==============================] - 11s 16ms/step - loss: 0.1218 - accuracy: 0.9615 - val_loss: 0.2550 - val_accuracy: 0.9360
Epoch 10/10
699/699 [==============================] - 11s 16ms/step - loss: 0.1110 - accuracy: 0.9646 - val_loss: 0.2668 - val_accuracy: 0.9353
311/311 [==============================] - 1s 3ms/step - loss: 0.1583 - accuracy: 0.9560
311/311 [==============================] - 2s 5ms/step - loss: 0.2668 - accuracy: 0.9353
311/311 [==============================] - 1s 3ms/step - loss: 0.1583 - accuracy: 0.9560
Test Accuracy: 0.9559875130653381
Task A Original Accuracy: 95.60%
Task B CrlBo method Accuracy: 93.53%
Epoch 1/10
699/699 [==============================] - 19s 19ms/step - loss: 0.2417 - accuracy: 0.9279 - val_loss: 0.1543 - val_accuracy: 0.9549
Epoch 2/10
699/699 [==============================] - 11s 16ms/step - loss: 0.2106 - accuracy: 0.9359 - val_loss: 0.1875 - val_accuracy: 0.9455
Epoch 3/10
699/699 [==============================] - 11s 16ms/step - loss: 0.1897 - accuracy: 0.9428 - val_loss: 0.1849 - val_accuracy: 0.9439
Epoch 4/10
699/699 [==============================] - 11s 16ms/step - loss: 0.1780 - accuracy: 0.9453 - val_loss: 0.1686 - val_accuracy: 0.9510
Epoch 5/10
699/699 [==============================] - 11s 16ms/step - loss: 0.1581 - accuracy: 0.9506 - val_loss: 0.2089 - val_accuracy: 0.9422
Epoch 6/10
699/699 [==============================] - 11s 16ms/step - loss: 0.1469 - accuracy: 0.9538 - val_loss: 0.2097 - val_accuracy: 0.9428
Epoch 7/10
699/699 [==============================] - 11s 16ms/step - loss: 0.1327 - accuracy: 0.9585 - val_loss: 0.2159 - val_accuracy: 0.9410
Epoch 8/10
699/699 [==============================] - 11s 16ms/step - loss: 0.1276 - accuracy: 0.9595 - val_loss: 0.2129 - val_accuracy: 0.9419
Epoch 9/10
699/699 [==============================] - 11s 16ms/step - loss: 0.1247 - accuracy: 0.9605 - val_loss: 0.2188 - val_accuracy: 0.9442
Epoch 10/10
699/699 [==============================] - 11s 16ms/step - loss: 0.1127 - accuracy: 0.9642 - val_loss: 0.2423 - val_accuracy: 0.9390
311/311 [==============================] - 1s 3ms/step - loss: 0.1467 - accuracy: 0.9585
311/311 [==============================] - 2s 7ms/step - loss: 0.2423 - accuracy: 0.9390
311/311 [==============================] - 1s 3ms/step - loss: 0.1467 - accuracy: 0.9585
Test Accuracy: 0.958505392074585
Task A Original Accuracy: 95.85%
Task B CrlBo method Accuracy: 93.90%
Epoch 1/10
699/699 [==============================] - 18s 19ms/step - loss: 0.2385 - accuracy: 0.9294 - val_loss: 0.1972 - val_accuracy: 0.9414
Epoch 2/10
699/699 [==============================] - 11s 16ms/step - loss: 0.2101 - accuracy: 0.9372 - val_loss: 0.1655 - val_accuracy: 0.9542
Epoch 3/10
699/699 [==============================] - 11s 16ms/step - loss: 0.1920 - accuracy: 0.9411 - val_loss: 0.1739 - val_accuracy: 0.9504
Epoch 4/10
699/699 [==============================] - 11s 16ms/step - loss: 0.1689 - accuracy: 0.9474 - val_loss: 0.1769 - val_accuracy: 0.9485
Epoch 5/10
699/699 [==============================] - 11s 16ms/step - loss: 0.1570 - accuracy: 0.9511 - val_loss: 0.1955 - val_accuracy: 0.9472
Epoch 6/10
699/699 [==============================] - 11s 16ms/step - loss: 0.1433 - accuracy: 0.9550 - val_loss: 0.1975 - val_accuracy: 0.9469
Epoch 7/10
699/699 [==============================] - 11s 16ms/step - loss: 0.1397 - accuracy: 0.9566 - val_loss: 0.2247 - val_accuracy: 0.9390
Epoch 8/10
699/699 [==============================] - 11s 16ms/step - loss: 0.1202 - accuracy: 0.9620 - val_loss: 0.2576 - val_accuracy: 0.9314
Epoch 9/10
699/699 [==============================] - 11s 16ms/step - loss: 0.1179 - accuracy: 0.9624 - val_loss: 0.2418 - val_accuracy: 0.9376
Epoch 10/10
699/699 [==============================] - 11s 16ms/step - loss: 0.1126 - accuracy: 0.9646 - val_loss: 0.2256 - val_accuracy: 0.9448
311/311 [==============================] - 1s 4ms/step - loss: 0.1502 - accuracy: 0.9599
311/311 [==============================] - 2s 5ms/step - loss: 0.2256 - accuracy: 0.9448
311/311 [==============================] - 1s 3ms/step - loss: 0.1502 - accuracy: 0.9599
Test Accuracy: 0.9599153995513916
Task A Original Accuracy: 95.99%
Task B CrlBo method Accuracy: 94.48%
Epoch 1/10
699/699 [==============================] - 19s 19ms/step - loss: 0.2406 - accuracy: 0.9286 - val_loss: 0.1633 - val_accuracy: 0.9530
Epoch 2/10

### Caltech101

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPool2D,Dense,Flatten,Dropout,Input, AveragePooling2D, Activation,Conv2D, MaxPooling2D, BatchNormalization,Concatenate
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
from tensorflow.keras import regularizers, optimizers
from tensorflow.keras.preprocessing.image import ImageDataGenerator

from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers
from tensorflow.keras.regularizers import Regularizer

# Perform hold-out cross-validation
validation_scores = []

# Define the CrlBo regularizer
class CrlBoRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Number of K-folds
K = 10

# Initialize the KFold object
kf = KFold(n_splits=K, shuffle=True, random_state=42)
# y_train_onehot = y
# Initialize the list to store test accuracies
accuracies = []
num_classes = 102
# Perform K-fold cross-validation
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]

# Task A: Original SVHN model
    model = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(28, 28, 3)),
        Conv2D(32, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        Conv2D(64, (3, 3), activation='relu', padding='same'),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu'),
        layers.Dropout(0.25),
        Dense(num_classes, activation='softmax')
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model = model
        model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model.fit(x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))
        model.save_weights('FashionMNIST_A.h5')
        prior_weights = model.get_weights()
# Compute Fisher Information for Task A
    with tf.GradientTape() as tape:
        model_output = model(x_train_fold[:1])
    grads = tape.gradient(model_output, model.weights)
    fisher_info = [tf.square(g).numpy() for g in grads]
# Define the Fisher Information computation function
def compute_fisher(model, x, num_samples=30):
    fisher_matrix = []
    for i in range(len(model.trainable_weights)):
        fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

    for _ in range(num_samples):
        idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
        with tf.GradientTape() as tape:
            logits = model(x[idx:idx+1])
        gradients = tape.gradient(logits, model.trainable_weights)
        for i in range(len(fisher_matrix)):
            fisher_matrix[i] += tf.square(gradients[i])

    fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
    return fisher_matrix

fisher_matrix = compute_fisher(model, x_train_fold)
for train_index, test_index in kf.split(x, y):
    x_train_fold, x_test_fold = x[train_index], x[test_index]
    y_train_fold, y_test_fold = y[train_index], y[test_index]
# Task B: Fashion SVHN with CrlBo regularization
    model_CrlBoB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(28, 28, 3),
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(64, (3, 3), activation='relu', padding='same',
               kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBoRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model_CrlBoB = model_CrlBoB
        model_CrlBoB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
        model_CrlBoB.load_weights('FashionMNIST_A.h5')
        model_CrlBoB.fit( x_train_fold, y_train_fold, batch_size=128, epochs=10, validation_data=(x_test_fold, y_test_fold))

# Evaluate performance
    A_original_acc = 100 * model.evaluate(x_test_fold, y_test_fold)[1]
    B_CrlBo_acc = 100 * model_CrlBoB.evaluate(x_test_fold, y_test_fold)[1]
# Train the model on each batch



# Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test_fold, y_test_fold)
    print("Test Accuracy:", test_accuracy)

    print("Task A Original Accuracy: %.2f%%" % A_original_acc)
    print("Task B CrlBo method Accuracy: %.2f%%" % B_CrlBo_acc)


    # Append the test accuracy of Task B to accuracies list
    accuracies.append(test_accuracy)

# Print the fold accuracies
for i, score in enumerate(accuracies):
    percent = score * 100
    print("Fold-{}: {:.2f}%".format(i+1, percent))

Epoch 1/10
65/65 [==============================] - 11s 28ms/step - loss: 3.9983 - accuracy: 0.1722 - val_loss: 3.4019 - val_accuracy: 0.3049
Epoch 2/10
65/65 [==============================] - 1s 14ms/step - loss: 3.0306 - accuracy: 0.3536 - val_loss: 2.5577 - val_accuracy: 0.4142
Epoch 3/10
65/65 [==============================] - 1s 15ms/step - loss: 2.3857 - accuracy: 0.4618 - val_loss: 2.2553 - val_accuracy: 0.4962
Epoch 4/10
65/65 [==============================] - 1s 14ms/step - loss: 1.9604 - accuracy: 0.5353 - val_loss: 2.0071 - val_accuracy: 0.5399
Epoch 5/10
65/65 [==============================] - 1s 14ms/step - loss: 1.6432 - accuracy: 0.5959 - val_loss: 1.9446 - val_accuracy: 0.5585
Epoch 6/10
65/65 [==============================] - 1s 14ms/step - loss: 1.3698 - accuracy: 0.6509 - val_loss: 1.8667 - val_accuracy: 0.5639
Epoch 7/10
65/65 [==============================] - 1s 19ms/step - loss: 1.1218 - accuracy: 0.7053 - val_loss: 1.9061 - val_accuracy: 0.5760
Epoch 8/10
65/65 [==============================] - 1s 18ms/step - loss: 0.9044 - accuracy: 0.7504 - val_loss: 1.9041 - val_accuracy: 0.5891
Epoch 9/10
65/65 [==============================] - 1s 18ms/step - loss: 0.7275 - accuracy: 0.7934 - val_loss: 2.0326 - val_accuracy: 0.5738
Epoch 10/10
65/65 [==============================] - 1s 14ms/step - loss: 0.6015 - accuracy: 0.8261 - val_loss: 2.0167 - val_accuracy: 0.5814
Epoch 1/10
65/65 [==============================] - 5s 20ms/step - loss: 3.9473 - accuracy: 0.1709 - val_loss: 3.5613 - val_accuracy: 0.2470
Epoch 2/10
65/65 [==============================] - 1s 18ms/step - loss: 3.0795 - accuracy: 0.3392 - val_loss: 2.7667 - val_accuracy: 0.3760
Epoch 3/10
65/65 [==============================] - 1s 21ms/step - loss: 2.4063 - accuracy: 0.4517 - val_loss: 2.4576 - val_accuracy: 0.4361
Epoch 4/10
65/65 [==============================] - 1s 17ms/step - loss: 1.9984 - accuracy: 0.5256 - val_loss: 2.1849 - val_accuracy: 0.5082
Epoch 5/10
65/65 [==============================] - 1s 14ms/step - loss: 1.6534 - accuracy: 0.5908 - val_loss: 2.0554 - val_accuracy: 0.5366
Epoch 6/10
65/65 [==============================] - 1s 13ms/step - loss: 1.3768 - accuracy: 0.6482 - val_loss: 1.9965 - val_accuracy: 0.5541
Epoch 7/10
65/65 [==============================] - 1s 15ms/step - loss: 1.1569 - accuracy: 0.6951 - val_loss: 2.0435 - val_accuracy: 0.5574
Epoch 8/10
65/65 [==============================] - 1s 14ms/step - loss: 0.9286 - accuracy: 0.7475 - val_loss: 2.0521 - val_accuracy: 0.5705
Epoch 9/10
65/65 [==============================] - 1s 15ms/step - loss: 0.7553 - accuracy: 0.7890 - val_loss: 2.0657 - val_accuracy: 0.5672
Epoch 10/10
65/65 [==============================] - 1s 14ms/step - loss: 0.6165 - accuracy: 0.8216 - val_loss: 2.2807 - val_accuracy: 0.5475
Epoch 1/10
65/65 [==============================] - 6s 30ms/step - loss: 4.0110 - accuracy: 0.1593 - val_loss: 3.5430 - val_accuracy: 0.2470
Epoch 2/10
65/65 [==============================] - 1s 15ms/step - loss: 3.1690 - accuracy: 0.3237 - val_loss: 2.7742 - val_accuracy: 0.3967
Epoch 3/10
65/65 [==============================] - 1s 16ms/step - loss: 2.5225 - accuracy: 0.4333 - val_loss: 2.3774 - val_accuracy: 0.4634
Epoch 4/10
65/65 [==============================] - 1s 14ms/step - loss: 2.1246 - accuracy: 0.5003 - val_loss: 2.2193 - val_accuracy: 0.4831
Epoch 5/10
65/65 [==============================] - 1s 14ms/step - loss: 1.7836 - accuracy: 0.5651 - val_loss: 1.9799 - val_accuracy: 0.5333
Epoch 6/10
65/65 [==============================] - 1s 14ms/step - loss: 1.5042 - accuracy: 0.6255 - val_loss: 1.9324 - val_accuracy: 0.5552
Epoch 7/10
65/65 [==============================] - 1s 15ms/step - loss: 1.2797 - accuracy: 0.6681 - val_loss: 1.8542 - val_accuracy: 0.5880
Epoch 8/10
65/65 [==============================] - 1s 15ms/step - loss: 1.0257 - accuracy: 0.7227 - val_loss: 1.8795 - val_accuracy: 0.5749
Epoch 9/10
65/65 [==============================] - 1s 15ms/step - loss: 0.8828 - accuracy: 0.7536 - val_loss: 1.8722 - val_accuracy: 0.5770
Epoch 10/10
65/65 [==============================] - 1s 14ms/step - loss: 0.6847 - accuracy: 0.8023 - val_loss: 1.9961 - val_accuracy: 0.5913
Epoch 1/10
65/65 [==============================] - 6s 22ms/step - loss: 3.9369 - accuracy: 0.1745 - val_loss: 3.4660 - val_accuracy: 0.2656
Epoch 2/10
65/65 [==============================] - 1s 15ms/step - loss: 3.0813 - accuracy: 0.3371 - val_loss: 2.7812 - val_accuracy: 0.3978
Epoch 3/10
65/65 [==============================] - 1s 14ms/step - loss: 2.4553 - accuracy: 0.4480 - val_loss: 2.3745 - val_accuracy: 0.4678
Epoch 4/10
65/65 [==============================] - 1s 15ms/step - loss: 2.0616 - accuracy: 0.5138 - val_loss: 2.1835 - val_accuracy: 0.4962
Epoch 5/10
65/65 [==============================] - 1s 15ms/step - loss: 1.7282 - accuracy: 0.5743 - val_loss: 2.0380 - val_accuracy: 0.5366
Epoch 6/10
65/65 [==============================] - 1s 15ms/step - loss: 1.4525 - accuracy: 0.6305 - val_loss: 1.9631 - val_accuracy: 0.5607
Epoch 7/10
65/65 [==============================] - 1s 15ms/step - loss: 1.2313 - accuracy: 0.6768 - val_loss: 1.9423 - val_accuracy: 0.5705
Epoch 8/10
65/65 [==============================] - 1s 14ms/step - loss: 1.0096 - accuracy: 0.7211 - val_loss: 2.1007 - val_accuracy: 0.5519
Epoch 9/10
65/65 [==============================] - 1s 19ms/step - loss: 0.8267 - accuracy: 0.7630 - val_loss: 2.0279 - val_accuracy: 0.5792
Epoch 10/10
65/65 [==============================] - 1s 19ms/step - loss: 0.6649 - accuracy: 0.8093 - val_loss: 2.0808 - val_accuracy: 0.5825
Epoch 1/10
65/65 [==============================] - 7s 36ms/step - loss: 3.9329 - accuracy: 0.1813 - val_loss: 3.4231 - val_accuracy: 0.2724
Epoch 2/10
65/65 [==============================] - 1s 14ms/step - loss: 3.1340 - accuracy: 0.3272 - val_loss: 2.6542 - val_accuracy: 0.4168
Epoch 3/10
65/65 [==============================] - 1s 15ms/step - loss: 2.5040 - accuracy: 0.4378 - val_loss: 2.2792 - val_accuracy: 0.4934
Epoch 4/10
65/65 [==============================] - 1s 16ms/step - loss: 2.0793 - accuracy: 0.5125 - val_loss: 2.0758 - val_accuracy: 0.5295
Epoch 5/10
65/65 [==============================] - 1s 21ms/step - loss: 1.7374 - accuracy: 0.5714 - val_loss: 1.9550 - val_accuracy: 0.5558
Epoch 6/10
65/65 [==============================] - 1s 20ms/step - loss: 1.4623 - accuracy: 0.6294 - val_loss: 1.9103 - val_accuracy: 0.5755
Epoch 7/10
65/65 [==============================] - 1s 14ms/step - loss: 1.2128 - accuracy: 0.6858 - val_loss: 1.8726 - val_accuracy: 0.5864
Epoch 8/10
65/65 [==============================] - 1s 16ms/step - loss: 1.0136 - accuracy: 0.7243 - val_loss: 2.0005 - val_accuracy: 0.5777
Epoch 9/10
65/65 [==============================] - 1s 14ms/step - loss: 0.8131 - accuracy: 0.7740 - val_loss: 1.9620 - val_accuracy: 0.5886
Epoch 10/10
65/65 [==============================] - 1s 15ms/step - loss: 0.6686 - accuracy: 0.8143 - val_loss: 1.9873 - val_accuracy: 0.5908
Epoch 1/10
65/65 [==============================] - 6s 21ms/step - loss: 3.9600 - accuracy: 0.1731 - val_loss: 3.3703 - val_accuracy: 0.2812
Epoch 2/10
65/65 [==============================] - 1s 15ms/step - loss: 3.0913 - accuracy: 0.3358 - val_loss: 2.5620 - val_accuracy: 0.4398
Epoch 3/10
65/65 [==============================] - 1s 14ms/step - loss: 2.4748 - accuracy: 0.4439 - val_loss: 2.1364 - val_accuracy: 0.5175
Epoch 4/10
65/65 [==============================] - 1s 16ms/step - loss: 2.0153 - accuracy: 0.5232 - val_loss: 1.9642 - val_accuracy: 0.5350
Epoch 5/10
65/65 [==============================] - 1s 15ms/step - loss: 1.6824 - accuracy: 0.5899 - val_loss: 1.8507 - val_accuracy: 0.5591
Epoch 6/10
65/65 [==============================] - 1s 16ms/step - loss: 1.4030 - accuracy: 0.6405 - val_loss: 1.7763 - val_accuracy: 0.5952
Epoch 7/10
65/65 [==============================] - 1s 15ms/step - loss: 1.1459 - accuracy: 0.6981 - val_loss: 1.7484 - val_accuracy: 0.6193
Epoch 8/10
65/65 [==============================] - 1s 20ms/step - loss: 0.9213 - accuracy: 0.7490 - val_loss: 1.7712 - val_accuracy: 0.6094
Epoch 9/10
65/65 [==============================] - 1s 20ms/step - loss: 0.7387 - accuracy: 0.7898 - val_loss: 1.8488 - val_accuracy: 0.6083
Epoch 10/10
65/65 [==============================] - 1s 17ms/step - loss: 0.5918 - accuracy: 0.8292 - val_loss: 1.9844 - val_accuracy: 0.6160
Epoch 1/10
65/65 [==============================] - 7s 21ms/step - loss: 3.9862 - accuracy: 0.1616 - val_loss: 3.4889 - val_accuracy: 0.2735
Epoch 2/10
65/65 [==============================] - 1s 15ms/step - loss: 3.1463 - accuracy: 0.3311 - val_loss: 2.7428 - val_accuracy: 0.4234
Epoch 3/10
65/65 [==============================] - 1s 16ms/step - loss: 2.5366 - accuracy: 0.4315 - val_loss: 2.4048 - val_accuracy: 0.4716
Epoch 4/10
65/65 [==============================] - 1s 15ms/step - loss: 2.1252 - accuracy: 0.5030 - val_loss: 2.1434 - val_accuracy: 0.5197
Epoch 5/10
65/65 [==============================] - 1s 16ms/step - loss: 1.7937 - accuracy: 0.5688 - val_loss: 2.0552 - val_accuracy: 0.5394
Epoch 6/10
65/65 [==============================] - 1s 15ms/step - loss: 1.5319 - accuracy: 0.6148 - val_loss: 1.9281 - val_accuracy: 0.5646
Epoch 7/10
65/65 [==============================] - 1s 16ms/step - loss: 1.2801 - accuracy: 0.6666 - val_loss: 1.8849 - val_accuracy: 0.5744
Epoch 8/10
65/65 [==============================] - 1s 15ms/step - loss: 1.0350 - accuracy: 0.7203 - val_loss: 1.9232 - val_accuracy: 0.5711
Epoch 9/10
65/65 [==============================] - 1s 19ms/step - loss: 0.8700 - accuracy: 0.7609 - val_loss: 1.9914 - val_accuracy: 0.5656
Epoch 10/10
65/65 [==============================] - 1s 21ms/step - loss: 0.6936 - accuracy: 0.8029 - val_loss: 2.0629 - val_accuracy: 0.5744
Epoch 1/10
65/65 [==============================] - 5s 22ms/step - loss: 3.9321 - accuracy: 0.1813 - val_loss: 3.2795 - val_accuracy: 0.3053
Epoch 2/10
65/65 [==============================] - 1s 15ms/step - loss: 3.0541 - accuracy: 0.3430 - val_loss: 2.6675 - val_accuracy: 0.4223
Epoch 3/10
65/65 [==============================] - 1s 16ms/step - loss: 2.4662 - accuracy: 0.4456 - val_loss: 2.3089 - val_accuracy: 0.4934
Epoch 4/10
65/65 [==============================] - 1s 15ms/step - loss: 2.0576 - accuracy: 0.5182 - val_loss: 2.1026 - val_accuracy: 0.5208
Epoch 5/10
65/65 [==============================] - 1s 16ms/step - loss: 1.7090 - accuracy: 0.5824 - val_loss: 2.0052 - val_accuracy: 0.5503
Epoch 6/10
65/65 [==============================] - 1s 19ms/step - loss: 1.4337 - accuracy: 0.6335 - val_loss: 2.0130 - val_accuracy: 0.5646
Epoch 7/10
65/65 [==============================] - 1s 20ms/step - loss: 1.1981 - accuracy: 0.6826 - val_loss: 1.9907 - val_accuracy: 0.5711
Epoch 8/10
65/65 [==============================] - 1s 17ms/step - loss: 0.9453 - accuracy: 0.7451 - val_loss: 2.0480 - val_accuracy: 0.5711
Epoch 9/10
65/65 [==============================] - 1s 15ms/step - loss: 0.7460 - accuracy: 0.7898 - val_loss: 2.1404 - val_accuracy: 0.5897
Epoch 10/10
65/65 [==============================] - 1s 16ms/step - loss: 0.6025 - accuracy: 0.8279 - val_loss: 2.2411 - val_accuracy: 0.5777
Epoch 1/10
65/65 [==============================] - 5s 22ms/step - loss: 3.9599 - accuracy: 0.1787 - val_loss: 3.5213 - val_accuracy: 0.2516
Epoch 2/10
65/65 [==============================] - 1s 15ms/step - loss: 3.0366 - accuracy: 0.3522 - val_loss: 2.7105 - val_accuracy: 0.3939
Epoch 3/10
65/65 [==============================] - 1s 18ms/step - loss: 2.4188 - accuracy: 0.4490 - val_loss: 2.3063 - val_accuracy: 0.4759
Epoch 4/10
65/65 [==============================] - 1s 20ms/step - loss: 1.9617 - accuracy: 0.5390 - val_loss: 2.0083 - val_accuracy: 0.5317
Epoch 5/10
65/65 [==============================] - 1s 20ms/step - loss: 1.6365 - accuracy: 0.5931 - val_loss: 1.9346 - val_accuracy: 0.5646
Epoch 6/10
65/65 [==============================] - 1s 16ms/step - loss: 1.3599 - accuracy: 0.6513 - val_loss: 1.8361 - val_accuracy: 0.5591
Epoch 7/10
65/65 [==============================] - 1s 15ms/step - loss: 1.1206 - accuracy: 0.7046 - val_loss: 1.8040 - val_accuracy: 0.5678
Epoch 8/10
65/65 [==============================] - 1s 16ms/step - loss: 0.8787 - accuracy: 0.7575 - val_loss: 1.8555 - val_accuracy: 0.5864
Epoch 9/10
65/65 [==============================] - 1s 15ms/step - loss: 0.7060 - accuracy: 0.7970 - val_loss: 1.9403 - val_accuracy: 0.5963
Epoch 10/10
65/65 [==============================] - 1s 15ms/step - loss: 0.5412 - accuracy: 0.8450 - val_loss: 2.0407 - val_accuracy: 0.5832
Epoch 1/10
65/65 [==============================] - 5s 21ms/step - loss: 4.0301 - accuracy: 0.1554 - val_loss: 3.6054 - val_accuracy: 0.2593
Epoch 2/10
65/65 [==============================] - 1s 16ms/step - loss: 3.1167 - accuracy: 0.3350 - val_loss: 2.6782 - val_accuracy: 0.4179
Epoch 3/10
65/65 [==============================] - 1s 14ms/step - loss: 2.4344 - accuracy: 0.4484 - val_loss: 2.2585 - val_accuracy: 0.5000
Epoch 4/10
65/65 [==============================] - 1s 16ms/step - loss: 1.9844 - accuracy: 0.5267 - val_loss: 2.0137 - val_accuracy: 0.5514
Epoch 5/10
65/65 [==============================] - 1s 14ms/step - loss: 1.6205 - accuracy: 0.5957 - val_loss: 1.9361 - val_accuracy: 0.5689
Epoch 6/10
65/65 [==============================] - 1s 17ms/step - loss: 1.3540 - accuracy: 0.6536 - val_loss: 2.0512 - val_accuracy: 0.5481
Epoch 7/10
65/65 [==============================] - 1s 20ms/step - loss: 1.1611 - accuracy: 0.6948 - val_loss: 1.8923 - val_accuracy: 0.5842
Epoch 8/10
65/65 [==============================] - 1s 19ms/step - loss: 0.9296 - accuracy: 0.7453 - val_loss: 1.9480 - val_accuracy: 0.5941
Epoch 9/10
65/65 [==============================] - 1s 16ms/step - loss: 0.7604 - accuracy: 0.7876 - val_loss: 1.9684 - val_accuracy: 0.6061
Epoch 10/10
65/65 [==============================] - 1s 14ms/step - loss: 0.6072 - accuracy: 0.8245 - val_loss: 2.0537 - val_accuracy: 0.6039
Epoch 1/10
65/65 [==============================] - 12s 59ms/step - loss: 0.5539 - accuracy: 0.8720 - val_loss: 0.2856 - val_accuracy: 0.9322
Epoch 2/10
65/65 [==============================] - 2s 26ms/step - loss: 0.2905 - accuracy: 0.9278 - val_loss: 0.2466 - val_accuracy: 0.9366
Epoch 3/10
65/65 [==============================] - 1s 19ms/step - loss: 0.1965 - accuracy: 0.9437 - val_loss: 0.3534 - val_accuracy: 0.8951
Epoch 4/10
65/65 [==============================] - 1s 19ms/step - loss: 0.1493 - accuracy: 0.9559 - val_loss: 0.3406 - val_accuracy: 0.9038
Epoch 5/10
65/65 [==============================] - 1s 17ms/step - loss: 0.1319 - accuracy: 0.9610 - val_loss: 0.4274 - val_accuracy: 0.8798
Epoch 6/10
65/65 [==============================] - 1s 20ms/step - loss: 0.1097 - accuracy: 0.9672 - val_loss: 0.4572 - val_accuracy: 0.8787
Epoch 7/10
65/65 [==============================] - 1s 19ms/step - loss: 0.1008 - accuracy: 0.9697 - val_loss: 0.4063 - val_accuracy: 0.8820
Epoch 8/10
65/65 [==============================] - 1s 18ms/step - loss: 0.0890 - accuracy: 0.9756 - val_loss: 0.4991 - val_accuracy: 0.8656
Epoch 9/10
65/65 [==============================] - 1s 18ms/step - loss: 0.0609 - accuracy: 0.9813 - val_loss: 0.5453 - val_accuracy: 0.8710
Epoch 10/10
65/65 [==============================] - 1s 18ms/step - loss: 0.0945 - accuracy: 0.9702 - val_loss: 0.6383 - val_accuracy: 0.8448
29/29 [==============================] - 0s 8ms/step - loss: 0.2138 - accuracy: 0.9585
29/29 [==============================] - 0s 8ms/step - loss: 0.6383 - accuracy: 0.8448
29/29 [==============================] - 0s 6ms/step - loss: 0.2138 - accuracy: 0.9585
Test Accuracy: 0.9584699273109436
Task A Original Accuracy: 95.85%
Task B CrlBo method Accuracy: 84.48%
Epoch 1/10
65/65 [==============================] - 13s 64ms/step - loss: 0.5572 - accuracy: 0.8680 - val_loss: 0.2781 - val_accuracy: 0.9333
Epoch 2/10
65/65 [==============================] - 2s 24ms/step - loss: 0.2888 - accuracy: 0.9266 - val_loss: 0.3322 - val_accuracy: 0.9049
Epoch 3/10
65/65 [==============================] - 1s 23ms/step - loss: 0.1955 - accuracy: 0.9456 - val_loss: 0.3646 - val_accuracy: 0.8896
Epoch 4/10
65/65 [==============================] - 1s 22ms/step - loss: 0.1486 - accuracy: 0.9560 - val_loss: 0.4327 - val_accuracy: 0.8809
Epoch 5/10
65/65 [==============================] - 1s 17ms/step - loss: 0.1252 - accuracy: 0.9621 - val_loss: 0.4427 - val_accuracy: 0.8852
Epoch 6/10
65/65 [==============================] - 1s 19ms/step - loss: 0.1109 - accuracy: 0.9667 - val_loss: 0.4717 - val_accuracy: 0.8874
Epoch 7/10
65/65 [==============================] - 1s 17ms/step - loss: 0.0930 - accuracy: 0.9738 - val_loss: 0.5013 - val_accuracy: 0.8710
Epoch 8/10
65/65 [==============================] - 1s 18ms/step - loss: 0.0916 - accuracy: 0.9741 - val_loss: 0.5169 - val_accuracy: 0.8634
Epoch 9/10
65/65 [==============================] - 1s 19ms/step - loss: 0.0670 - accuracy: 0.9799 - val_loss: 0.5843 - val_accuracy: 0.8557
Epoch 10/10
65/65 [==============================] - 1s 21ms/step - loss: 0.0676 - accuracy: 0.9807 - val_loss: 0.5797 - val_accuracy: 0.8612
29/29 [==============================] - 0s 6ms/step - loss: 0.2315 - accuracy: 0.9563
29/29 [==============================] - 0s 11ms/step - loss: 0.5797 - accuracy: 0.8612
29/29 [==============================] - 0s 9ms/step - loss: 0.2315 - accuracy: 0.9563
Test Accuracy: 0.9562841653823853
Task A Original Accuracy: 95.63%
Task B CrlBo method Accuracy: 86.12%
Epoch 1/10
65/65 [==============================] - 13s 73ms/step - loss: 0.5688 - accuracy: 0.8680 - val_loss: 0.2036 - val_accuracy: 0.9508
Epoch 2/10
65/65 [==============================] - 1s 18ms/step - loss: 0.2864 - accuracy: 0.9283 - val_loss: 0.2798 - val_accuracy: 0.9148
Epoch 3/10
65/65 [==============================] - 1s 18ms/step - loss: 0.2093 - accuracy: 0.9401 - val_loss: 0.2467 - val_accuracy: 0.9224
Epoch 4/10
65/65 [==============================] - 1s 16ms/step - loss: 0.1404 - accuracy: 0.9603 - val_loss: 0.3626 - val_accuracy: 0.8973
Epoch 5/10
65/65 [==============================] - 1s 18ms/step - loss: 0.1318 - accuracy: 0.9639 - val_loss: 0.4006 - val_accuracy: 0.8765
Epoch 6/10
65/65 [==============================] - 1s 19ms/step - loss: 0.1093 - accuracy: 0.9667 - val_loss: 0.4419 - val_accuracy: 0.8787
Epoch 7/10
65/65 [==============================] - 1s 17ms/step - loss: 0.0885 - accuracy: 0.9702 - val_loss: 0.4471 - val_accuracy: 0.8754
Epoch 8/10
65/65 [==============================] - 1s 19ms/step - loss: 0.0968 - accuracy: 0.9721 - val_loss: 0.5586 - val_accuracy: 0.8481
Epoch 9/10
65/65 [==============================] - 1s 18ms/step - loss: 0.0752 - accuracy: 0.9797 - val_loss: 0.5700 - val_accuracy: 0.8557
Epoch 10/10
65/65 [==============================] - 1s 20ms/step - loss: 0.0647 - accuracy: 0.9795 - val_loss: 0.5594 - val_accuracy: 0.8536
29/29 [==============================] - 0s 9ms/step - loss: 0.2039 - accuracy: 0.9639
29/29 [==============================] - 0s 13ms/step - loss: 0.5594 - accuracy: 0.8536
29/29 [==============================] - 0s 6ms/step - loss: 0.2039 - accuracy: 0.9639
Test Accuracy: 0.9639344215393066
Task A Original Accuracy: 96.39%
Task B CrlBo method Accuracy: 85.36%
Epoch 1/10
65/65 [==============================] - 11s 55ms/step - loss: 0.5434 - accuracy: 0.8737 - val_loss: 0.2563 - val_accuracy: 0.9443
Epoch 2/10
65/65 [==============================] - 2s 24ms/step - loss: 0.2948 - accuracy: 0.9226 - val_loss: 0.2244 - val_accuracy: 0.9410
Epoch 3/10
65/65 [==============================] - 1s 19ms/step - loss: 0.1832 - accuracy: 0.9467 - val_loss: 0.2932 - val_accuracy: 0.9169
Epoch 4/10

# C3 batchwise

### CIFAR100-C

#### Batches 1

In [ ]:
import tensorflow as tf
import keras
import numpy as np
from tensorflow.keras.datasets import cifar100
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras import layers
# Load the CIFAR-100 dataset
(x_train, y_train), (x_test, y_test) = cifar100.load_data()

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 3  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = np.copy(x_train).astype('float64')
if corruption_name == "speckle_noise":
    noise = np.random.randn(*corrupted_data.shape) * corruption_level
    corrupted_data += noise
    corrupted_data = np.clip(corrupted_data, 0., 255.)
    corrupted_data = corrupted_data.astype('uint8')
num_classes=100
# Convert labels to one-hot vectors
y_train_onehot = keras.utils.to_categorical(y_train, num_classes=100)
y_test_onehot = keras.utils.to_categorical(y_test, num_classes=100)

# Define the CrlB regularizer
class CrlBRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Define the original CIFAR-100 model
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu'),
    layers.Dropout(0.25),
    Dense(num_classes, activation='softmax')
])

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the original model on Task A
model.fit(corrupted_data, y_train_onehot, batch_size=128, epochs=10, validation_data=(x_test, y_test_onehot))

# Save the weights of the original model for later use
prior_weights = model.get_weights()

# Compute the Fisher Information matrix
def compute_fisher(model, x, num_samples=30):
    fisher_matrix = []
    for i in range(len(model.trainable_weights)):
        fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

    for _ in range(num_samples):
        idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
        with tf.GradientTape() as tape:
            logits = model(x[idx:idx+1])
        gradients = tape.gradient(logits, model.trainable_weights)
        for i in range(len(fisher_matrix)):
            fisher_matrix[i] += tf.square(gradients[i])

    fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
    return fisher_matrix

fisher_matrix = compute_fisher(model, corrupted_data)

# Define the new model with CrlB regularization
model_CrlB = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3),
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
    Conv2D(32, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
    Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
    Dense(num_classes, activation='softmax', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
])

# Compile the model with CrlB regularization
model_CrlB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on Task B with CrlB regularization
history = model_CrlB.fit(corrupted_data, y_train_onehot, batch_size=128, epochs=10, validation_data=(x_test, y_test_onehot))
print(history)
# Evaluate the model on the test set
_, test_accuracy = model.evaluate(x_test, y_test_onehot, verbose=0)
print("Test Accuracy:", test_accuracy)

Epoch 1/10
391/391 [==============================] - 11s 16ms/step - loss: 4.6691 - accuracy: 0.0440 - val_loss: 3.9149 - val_accuracy: 0.1128
Epoch 2/10
391/391 [==============================] - 5s 13ms/step - loss: 3.7245 - accuracy: 0.1339 - val_loss: 3.4417 - val_accuracy: 0.1963
Epoch 3/10
391/391 [==============================] - 5s 13ms/step - loss: 3.3516 - accuracy: 0.1988 - val_loss: 3.0563 - val_accuracy: 0.2588
Epoch 4/10
391/391 [==============================] - 5s 13ms/step - loss: 3.0301 - accuracy: 0.2567 - val_loss: 2.8662 - val_accuracy: 0.3026
Epoch 5/10
391/391 [==============================] - 5s 13ms/step - loss: 2.7919 - accuracy: 0.3026 - val_loss: 2.6838 - val_accuracy: 0.3393
Epoch 6/10
391/391 [==============================] - 5s 13ms/step - loss: 2.5887 - accuracy: 0.3431 - val_loss: 2.5632 - val_accuracy: 0.3551
Epoch 7/10
391/391 [==============================] - 6s 15ms/step - loss: 2.4258 - accuracy: 0.3760 - val_loss: 2.5022 - val_accuracy: 0.3655
Epoch 8/10
391/391 [==============================] - 6s 15ms/step - loss: 2.2875 - accuracy: 0.4053 - val_loss: 2.4109 - val_accuracy: 0.3893
Epoch 9/10
391/391 [==============================] - 5s 13ms/step - loss: 2.1424 - accuracy: 0.4353 - val_loss: 2.3698 - val_accuracy: 0.3970
Epoch 10/10
391/391 [==============================] - 5s 14ms/step - loss: 2.0089 - accuracy: 0.4639 - val_loss: 2.4057 - val_accuracy: 0.3944
Epoch 1/10
391/391 [==============================] - 13s 21ms/step - loss: 4.6270 - accuracy: 0.0439 - val_loss: 3.8729 - val_accuracy: 0.1177
Epoch 2/10
391/391 [==============================] - 6s 15ms/step - loss: 3.5798 - accuracy: 0.1652 - val_loss: 3.4145 - val_accuracy: 0.1996
Epoch 3/10
391/391 [==============================] - 6s 16ms/step - loss: 3.0946 - accuracy: 0.2497 - val_loss: 3.0012 - val_accuracy: 0.2732
Epoch 4/10
391/391 [==============================] - 6s 15ms/step - loss: 2.7817 - accuracy: 0.3105 - val_loss: 2.6963 - val_accuracy: 0.3323
Epoch 5/10
391/391 [==============================] - 6s 16ms/step - loss: 2.5211 - accuracy: 0.3604 - val_loss: 2.6201 - val_accuracy: 0.3569
Epoch 6/10
391/391 [==============================] - 6s 15ms/step - loss: 2.3166 - accuracy: 0.4017 - val_loss: 2.5718 - val_accuracy: 0.3556
Epoch 7/10
391/391 [==============================] - 6s 16ms/step - loss: 2.0951 - accuracy: 0.4491 - val_loss: 2.5277 - val_accuracy: 0.3795
Epoch 8/10
391/391 [==============================] - 6s 15ms/step - loss: 1.9062 - accuracy: 0.4904 - val_loss: 2.4742 - val_accuracy: 0.3842
Epoch 9/10
391/391 [==============================] - 6s 16ms/step - loss: 1.7205 - accuracy: 0.5312 - val_loss: 2.4849 - val_accuracy: 0.3920
Epoch 10/10
391/391 [==============================] - 6s 15ms/step - loss: 1.5440 - accuracy: 0.5706 - val_loss: 2.6477 - val_accuracy: 0.3860
<keras.callbacks.History object at 0x7f2d1cafa1d0>
Test Accuracy: 0.3944000005722046

#### Batches 20

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar100
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers

# Load the CIFAR-100 dataset
(x_train, y_train), (x_test, y_test) = cifar100.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 0.1  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = x_train + tf.random.normal(shape=x_train.shape, mean=0.0, stddev=corruption_level, dtype=tf.float32)
corrupted_data = tf.clip_by_value(corrupted_data, 0.0, 1.0)

# Convert the labels to one-hot encoding
num_classes = 100
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 2 batches
n_batches = 20
batch_size = x_train.shape[0] // n_batches

# Define the CrlB regularizer
class CrlBRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Define the original CIFAR-10 model
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu'),
    layers.Dropout(0.25),
    Dense(num_classes, activation='softmax')
])

# Compile the model
# model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the original model on Task A
# model.fit(corrupted_data, y_train_onehot, batch_size=128, epochs=10, validation_data=(x_test, y_test_onehot))

# Train the model on each batch separately
for i in range(n_batches):
    start_index = i * batch_size
    end_index = (i + 1) * batch_size
    x_batch = corrupted_data[start_index:end_index]
    y_batch = y_train[start_index:end_index]
    model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    # Train the model on the current batch
    model.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    # _, test_accuracy = model.evaluate(x_test, y_test)
    # print("Test Accuracy:", test_accuracy)
# Save the weights of the original model for later use
    prior_weights = model.get_weights()

# Compute the Fisher Information matrix
    def compute_fisher(model, x, num_samples=30):
        fisher_matrix = []
        for i in range(len(model.trainable_weights)):
            fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

        for _ in range(num_samples):
            idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
            with tf.GradientTape() as tape:
                logits = model(x[idx:idx+1])
            gradients = tape.gradient(logits, model.trainable_weights)
            for i in range(len(fisher_matrix)):
                fisher_matrix[i] += tf.square(gradients[i])

        fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
        return fisher_matrix

    fisher_matrix = compute_fisher(model, corrupted_data)

# Define the new model with CrlB regularization
    model_CrlB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3),
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])

# Compile the model with CrlB regularization
    model_CrlB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on Task B with CrlB regularization
# history = model_CrlB.fit(corrupted_data, y_train_onehot, batch_size=128, epochs=10, validation_data=(x_test, y_test_onehot))
# print(history)
# Train the model on each batch separately
# for i in range(n_batches):
#     start_index = i * batch_size
#     end_index = (i + 1) * batch_size
#     x_batch = corrupted_data[start_index:end_index]
#     y_batch = y_train[start_index:end_index]

    # Train the model on the current batch
    model_CrlB.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)
# # Evaluate the model on the test set
# _, test_accuracy = model.evaluate(x_test, y_test_onehot, verbose=0)
# print("Test Accuracy:", test_accuracy)

Downloading data from https://www.cs.toronto.edu/~kriz/cifar-100-python.tar.gz
169001437/169001437 [==============================] - 13s 0us/step
Epoch 1/10
79/79 [==============================] - 8s 9ms/step - loss: 4.6106 - accuracy: 0.0124
Epoch 2/10
79/79 [==============================] - 0s 5ms/step - loss: 4.5981 - accuracy: 0.0144
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 4.4941 - accuracy: 0.0232
Epoch 4/10
79/79 [==============================] - 0s 5ms/step - loss: 4.2950 - accuracy: 0.0384
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 4.1074 - accuracy: 0.0636
Epoch 6/10
79/79 [==============================] - 0s 6ms/step - loss: 3.9124 - accuracy: 0.0880
Epoch 7/10
79/79 [==============================] - 0s 5ms/step - loss: 3.7313 - accuracy: 0.1156
Epoch 8/10
79/79 [==============================] - 0s 5ms/step - loss: 3.4799 - accuracy: 0.1672
Epoch 9/10
79/79 [==============================] - 0s 6ms/step - loss: 3.1828 - accuracy: 0.2184
Epoch 10/10
79/79 [==============================] - 0s 6ms/step - loss: 2.8212 - accuracy: 0.2812
Epoch 1/10
79/79 [==============================] - 7s 9ms/step - loss: 4.5771 - accuracy: 0.0112
Epoch 2/10
79/79 [==============================] - 1s 8ms/step - loss: 4.3354 - accuracy: 0.0392
Epoch 3/10
79/79 [==============================] - 1s 8ms/step - loss: 4.1131 - accuracy: 0.0608
Epoch 4/10
79/79 [==============================] - 1s 8ms/step - loss: 3.9267 - accuracy: 0.0892
Epoch 5/10
79/79 [==============================] - 1s 8ms/step - loss: 3.6799 - accuracy: 0.1348
Epoch 6/10
79/79 [==============================] - 1s 8ms/step - loss: 3.3618 - accuracy: 0.1892
Epoch 7/10
79/79 [==============================] - 1s 8ms/step - loss: 2.9475 - accuracy: 0.2676
Epoch 8/10
79/79 [==============================] - 1s 8ms/step - loss: 2.4235 - accuracy: 0.3708
Epoch 9/10
79/79 [==============================] - 1s 7ms/step - loss: 1.7484 - accuracy: 0.5372
Epoch 10/10
79/79 [==============================] - 1s 8ms/step - loss: 1.1558 - accuracy: 0.6728
313/313 [==============================] - 1s 3ms/step - loss: 4.0395 - accuracy: 0.1195
Test Accuracy: 0.11949999630451202
Epoch 1/10
79/79 [==============================] - 3s 7ms/step - loss: 3.9528 - accuracy: 0.1004
Epoch 2/10
79/79 [==============================] - 1s 7ms/step - loss: 3.5208 - accuracy: 0.1636
Epoch 3/10
79/79 [==============================] - 1s 7ms/step - loss: 3.1164 - accuracy: 0.2416
Epoch 4/10
79/79 [==============================] - 1s 6ms/step - loss: 2.6403 - accuracy: 0.3284
Epoch 5/10
79/79 [==============================] - 1s 7ms/step - loss: 2.0553 - accuracy: 0.4548
Epoch 6/10
79/79 [==============================] - 0s 5ms/step - loss: 1.5420 - accuracy: 0.5940
Epoch 7/10
79/79 [==============================] - 0s 5ms/step - loss: 1.1424 - accuracy: 0.6856
Epoch 8/10
79/79 [==============================] - 0s 5ms/step - loss: 0.8068 - accuracy: 0.7716
Epoch 9/10
79/79 [==============================] - 0s 6ms/step - loss: 0.6556 - accuracy: 0.8168
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 0.5098 - accuracy: 0.8456
Epoch 1/10
79/79 [==============================] - 6s 8ms/step - loss: 4.5510 - accuracy: 0.0240
Epoch 2/10
79/79 [==============================] - 1s 7ms/step - loss: 4.3609 - accuracy: 0.0392
Epoch 3/10
79/79 [==============================] - 1s 7ms/step - loss: 4.1533 - accuracy: 0.0628
Epoch 4/10
79/79 [==============================] - 1s 8ms/step - loss: 3.9695 - accuracy: 0.0892
Epoch 5/10
79/79 [==============================] - 1s 7ms/step - loss: 3.7141 - accuracy: 0.1300
Epoch 6/10
79/79 [==============================] - 1s 8ms/step - loss: 3.4012 - accuracy: 0.1692
Epoch 7/10
79/79 [==============================] - 1s 7ms/step - loss: 2.9464 - accuracy: 0.2616
Epoch 8/10
79/79 [==============================] - 1s 7ms/step - loss: 2.4036 - accuracy: 0.3672
Epoch 9/10
79/79 [==============================] - 1s 8ms/step - loss: 1.7853 - accuracy: 0.5096
Epoch 10/10
79/79 [==============================] - 1s 8ms/step - loss: 1.2307 - accuracy: 0.6544
313/313 [==============================] - 1s 3ms/step - loss: 6.5005 - accuracy: 0.1416
Test Accuracy: 0.14159999787807465
Epoch 1/10
79/79 [==============================] - 3s 7ms/step - loss: 4.1291 - accuracy: 0.1104
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 3.3571 - accuracy: 0.1960
Epoch 3/10
79/79 [==============================] - 0s 6ms/step - loss: 2.8668 - accuracy: 0.2836
Epoch 4/10
79/79 [==============================] - 0s 6ms/step - loss: 2.3107 - accuracy: 0.3988
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 1.7177 - accuracy: 0.5332
Epoch 6/10
79/79 [==============================] - 0s 5ms/step - loss: 1.2358 - accuracy: 0.6532
Epoch 7/10
79/79 [==============================] - 0s 6ms/step - loss: 0.8386 - accuracy: 0.7540
Epoch 8/10
79/79 [==============================] - 0s 5ms/step - loss: 0.6140 - accuracy: 0.8192
Epoch 9/10
79/79 [==============================] - 0s 6ms/step - loss: 0.5011 - accuracy: 0.8472
Epoch 10/10
79/79 [==============================] - 0s 5ms/step - loss: 0.4069 - accuracy: 0.8844
Epoch 1/10
79/79 [==============================] - 6s 10ms/step - loss: 4.6080 - accuracy: 0.0100
Epoch 2/10
79/79 [==============================] - 1s 9ms/step - loss: 4.4821 - accuracy: 0.0320
Epoch 3/10
79/79 [==============================] - 1s 7ms/step - loss: 4.2625 - accuracy: 0.0424
Epoch 4/10
79/79 [==============================] - 1s 8ms/step - loss: 4.0810 - accuracy: 0.0688
Epoch 5/10
79/79 [==============================] - 1s 8ms/step - loss: 3.8255 - accuracy: 0.1052
Epoch 6/10
79/79 [==============================] - 1s 11ms/step - loss: 3.5183 - accuracy: 0.1592
Epoch 7/10
79/79 [==============================] - 1s 8ms/step - loss: 3.1028 - accuracy: 0.2324
Epoch 8/10
79/79 [==============================] - 1s 8ms/step - loss: 2.4850 - accuracy: 0.3644
Epoch 9/10
79/79 [==============================] - 1s 8ms/step - loss: 1.7953 - accuracy: 0.5108
Epoch 10/10
79/79 [==============================] - 1s 8ms/step - loss: 1.2171 - accuracy: 0.6652
313/313 [==============================] - 1s 3ms/step - loss: 6.6198 - accuracy: 0.1724
Test Accuracy: 0.17239999771118164
Epoch 1/10
79/79 [==============================] - 4s 7ms/step - loss: 4.1790 - accuracy: 0.1196
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 3.3073 - accuracy: 0.2056
Epoch 3/10
79/79 [==============================] - 0s 5ms/step - loss: 2.7964 - accuracy: 0.2916
Epoch 4/10
79/79 [==============================] - 0s 6ms/step - loss: 2.1822 - accuracy: 0.4356
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 1.5948 - accuracy: 0.5688
Epoch 6/10
79/79 [==============================] - 0s 6ms/step - loss: 1.1278 - accuracy: 0.6832
Epoch 7/10
79/79 [==============================] - 0s 6ms/step - loss: 0.7932 - accuracy: 0.7672
Epoch 8/10
79/79 [==============================] - 0s 6ms/step - loss: 0.5748 - accuracy: 0.8308
Epoch 9/10
79/79 [==============================] - 0s 5ms/step - loss: 0.4249 - accuracy: 0.8728
Epoch 10/10
79/79 [==============================] - 0s 6ms/step - loss: 0.3439 - accuracy: 0.8948
Epoch 1/10
79/79 [==============================] - 6s 10ms/step - loss: 4.6043 - accuracy: 0.0116
Epoch 2/10
79/79 [==============================] - 1s 9ms/step - loss: 4.4856 - accuracy: 0.0240
Epoch 3/10
79/79 [==============================] - 1s 10ms/step - loss: 4.2483 - accuracy: 0.0496
Epoch 4/10
79/79 [==============================] - 1s 8ms/step - loss: 4.0418 - accuracy: 0.0788
Epoch 5/10
79/79 [==============================] - 1s 8ms/step - loss: 3.8030 - accuracy: 0.1124
Epoch 6/10
79/79 [==============================] - 1s 8ms/step - loss: 3.4875 - accuracy: 0.1684
Epoch 7/10
79/79 [==============================] - 1s 8ms/step - loss: 3.0931 - accuracy: 0.2364
Epoch 8/10
79/79 [==============================] - 1s 7ms/step - loss: 2.5636 - accuracy: 0.3500
Epoch 9/10
79/79 [==============================] - 1s 7ms/step - loss: 1.9485 - accuracy: 0.4820
Epoch 10/10
79/79 [==============================] - 1s 8ms/step - loss: 1.4369 - accuracy: 0.6096
313/313 [==============================] - 1s 3ms/step - loss: 6.4957 - accuracy: 0.1816
Test Accuracy: 0.18160000443458557
Epoch 1/10
79/79 [==============================] - 3s 8ms/step - loss: 4.0652 - accuracy: 0.1156
Epoch 2/10
79/79 [==============================] - 1s 7ms/step - loss: 3.2023 - accuracy: 0.2412
Epoch 3/10
79/79 [==============================] - 0s 6ms/step - loss: 2.6358 - accuracy: 0.3400
Epoch 4/10
79/79 [==============================] - 0s 6ms/step - loss: 2.0167 - accuracy: 0.4768
Epoch 5/10
79/79 [==============================] - 0s 6ms/step - loss: 1.4251 - accuracy: 0.6144
Epoch 6/10
79/79 [==============================] - 0s 6ms/step - loss: 0.9839 - accuracy: 0.7200
Epoch 7/10
79/79 [==============================] - 0s 6ms/step - loss: 0.6906 - accuracy: 0.7952
Epoch 8/10
79/79 [==============================] - 0s 6ms/step - loss: 0.5175 - accuracy: 0.8436
Epoch 9/10
79/79 [==============================] - 0s 6ms/step - loss: 0.3697 - accuracy: 0.8896
Epoch 10/10
79/79 [==============================] - 0s 6ms/step - loss: 0.3518 - accuracy: 0.8944
Epoch 1/10
79/79 [==============================] - 5s 9ms/step - loss: 4.6060 - accuracy: 0.0096
Epoch 2/10
79/79 [==============================] - 1s 8ms/step - loss: 4.4423 - accuracy: 0.0280
Epoch 3/10
79/79 [==============================] - 1s 9ms/step - loss: 4.2056 - accuracy: 0.0476
Epoch 4/10
79/79 [==============================] - 1s 9ms/step - loss: 3.9969 - accuracy: 0.0752
Epoch 5/10
79/79 [==============================] - 1s 10ms/step - loss: 3.7727 - accuracy: 0.1104
Epoch 6/10
79/79 [==============================] - 1s 8ms/step - loss: 3.4604 - accuracy: 0.1608
Epoch 7/10
79/79 [==============================] - 1s 8ms/step - loss: 3.0724 - accuracy: 0.2408
Epoch 8/10
79/79 [==============================] - 1s 8ms/step - loss: 2.4517 - accuracy: 0.3572
Epoch 9/10
79/79 [==============================] - 1s 8ms/step - loss: 1.8523 - accuracy: 0.5028
Epoch 10/10
79/79 [==============================] - 1s 8ms/step - loss: 1.3165 - accuracy: 0.6440
313/313 [==============================] - 1s 3ms/step - loss: 6.4302 - accuracy: 0.1850
Test Accuracy: 0.1850000023841858
Epoch 1/10
79/79 [==============================] - 3s 7ms/step - loss: 4.1514 - accuracy: 0.1256
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 3.2672 - accuracy: 0.2304
Epoch 3/10
79/79 [==============================] - 0s 6ms/step - loss: 2.6751 - accuracy: 0.3360
Epoch 4/10
79/79 [==============================] - 0s 6ms/step - loss: 2.0140 - accuracy: 0.4792
Epoch 5/10
79/79 [==============================] - 0s 5ms/step - loss: 1.4265 - accuracy: 0.6116
Epoch 6/10
79/79 [==============================] - 0s 6ms/step - loss: 1.0174 - accuracy: 0.7132
Epoch 7/10
79/79 [==============================] - 0s 6ms/step - loss: 0.6900 - accuracy: 0.8008
Epoch 8/10
79/79 [==============================] - 1s 6ms/step - loss: 0.4739 - accuracy: 0.8572
Epoch 9/10
79/79 [==============================] - 1s 6ms/step - loss: 0.4072 - accuracy: 0.8784
Epoch 10/10
79/79 [==============================] - 1s 7ms/step - loss: 0.3153 - accuracy: 0.9048
Epoch 1/10
79/79 [==============================] - 6s 9ms/step - loss: 4.6081 - accuracy: 0.0128
Epoch 2/10
79/79 [==============================] - 1s 9ms/step - loss: 4.5352 - accuracy: 0.0216
Epoch 3/10
79/79 [==============================] - 1s 9ms/step - loss: 4.3666 - accuracy: 0.0380
Epoch 4/10
79/79 [==============================] - 1s 10ms/step - loss: 4.1848 - accuracy: 0.0520
Epoch 5/10
79/79 [==============================] - 1s 9ms/step - loss: 3.9831 - accuracy: 0.0892
Epoch 6/10
79/79 [==============================] - 1s 8ms/step - loss: 3.7266 - accuracy: 0.1368
Epoch 7/10
79/79 [==============================] - 1s 8ms/step - loss: 3.3557 - accuracy: 0.1980
Epoch 8/10
79/79 [==============================] - 1s 8ms/step - loss: 2.8359 - accuracy: 0.2988
Epoch 9/10
79/79 [==============================] - 1s 8ms/step - loss: 2.2246 - accuracy: 0.4352
Epoch 10/10
79/79 [==============================] - 1s 8ms/step - loss: 1.5529 - accuracy: 0.5852
313/313 [==============================] - 1s 3ms/step - loss: 5.6761 - accuracy: 0.1984
Test Accuracy: 0.19840000569820404
Epoch 1/10
79/79 [==============================] - 3s 7ms/step - loss: 4.1123 - accuracy: 0.1344
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 3.2208 - accuracy: 0.2268
Epoch 3/10
79/79 [==============================] - 0s 6ms/step - loss: 2.6756 - accuracy: 0.3300
Epoch 4/10
79/79 [==============================] - 0s 5ms/step - loss: 2.1010 - accuracy: 0.4484
Epoch 5/10
79/79 [==============================] - 0s 6ms/step - loss: 1.5606 - accuracy: 0.5844
Epoch 6/10
79/79 [==============================] - 1s 7ms/step - loss: 1.0591 - accuracy: 0.7104
Epoch 7/10
79/79 [==============================] - 1s 7ms/step - loss: 0.7668 - accuracy: 0.7844
Epoch 8/10
79/79 [==============================] - 1s 7ms/step - loss: 0.6003 - accuracy: 0.8240
Epoch 9/10
79/79 [==============================] - 1s 7ms/step - loss: 0.4715 - accuracy: 0.8568
Epoch 10/10
79/79 [==============================] - 1s 6ms/step - loss: 0.3465 - accuracy: 0.9000
Epoch 1/10
79/79 [==============================] - 6s 9ms/step - loss: 4.5796 - accuracy: 0.0128
Epoch 2/10
79/79 [==============================] - 1s 8ms/step - loss: 4.3753 - accuracy: 0.0372
Epoch 3/10
79/79 [==============================] - 1s 8ms/step - loss: 4.1846 - accuracy: 0.0488
Epoch 4/10
79/79 [==============================] - 1s 8ms/step - loss: 3.9980 - accuracy: 0.0836
Epoch 5/10
79/79 [==============================] - 1s 9ms/step - loss: 3.7563 - accuracy: 0.1216
Epoch 6/10
79/79 [==============================] - 1s 8ms/step - loss: 3.4627 - accuracy: 0.1732
Epoch 7/10
79/79 [==============================] - 1s 10ms/step - loss: 3.0819 - accuracy: 0.2404
Epoch 8/10
79/79 [==============================] - 1s 9ms/step - loss: 2.5582 - accuracy: 0.3432
Epoch 9/10
79/79 [==============================] - 1s 9ms/step - loss: 1.9298 - accuracy: 0.4956
Epoch 10/10
79/79 [==============================] - 1s 8ms/step - loss: 1.3889 - accuracy: 0.6280
313/313 [==============================] - 1s 3ms/step - loss: 5.8672 - accuracy: 0.2033
Test Accuracy: 0.20329999923706055
Epoch 1/10
79/79 [==============================] - 3s 7ms/step - loss: 4.1434 - accuracy: 0.1196
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 3.2930 - accuracy: 0.2188
Epoch 3/10
79/79 [==============================] - 0s 6ms/step - loss: 2.7363 - accuracy: 0.3176
Epoch 4/10
79/79 [==============================] - 0s 6ms/step - loss: 2.1560 - accuracy: 0.4420
Epoch 5/10
79/79 [==============================] - 0s 6ms/step - loss: 1.5651 - accuracy: 0.5740
Epoch 6/10
79/79 [==============================] - 0s 6ms/step - loss: 1.1369 - accuracy: 0.6832
Epoch 7/10
79/79 [==============================] - 0s 6ms/step - loss: 0.7489 - accuracy: 0.7824
Epoch 8/10
79/79 [==============================] - 0s 6ms/step - loss: 0.5761 - accuracy: 0.8276
Epoch 9/10
79/79 [==============================] - 0s 6ms/step - loss: 0.4321 - accuracy: 0.8696
Epoch 10/10
79/79 [==============================] - 0s 6ms/step - loss: 0.3218 - accuracy: 0.8996
Epoch 1/10
79/79 [==============================] - 5s 9ms/step - loss: 4.6086 - accuracy: 0.0128
Epoch 2/10
79/79 [==============================] - 1s 10ms/step - loss: 4.5654 - accuracy: 0.0164
Epoch 3/10
79/79 [==============================] - 1s 8ms/step - loss: 4.4210 - accuracy: 0.0288
Epoch 4/10
79/79 [==============================] - 1s 8ms/step - loss: 4.2062 - accuracy: 0.0456
Epoch 5/10
79/79 [==============================] - 1s 8ms/step - loss: 4.0018 - accuracy: 0.0832
Epoch 6/10
79/79 [==============================] - 1s 9ms/step - loss: 3.7183 - accuracy: 0.1296
Epoch 7/10
79/79 [==============================] - 1s 10ms/step - loss: 3.3689 - accuracy: 0.1864
Epoch 8/10
79/79 [==============================] - 1s 10ms/step - loss: 2.9057 - accuracy: 0.2776
Epoch 9/10
79/79 [==============================] - 1s 9ms/step - loss: 2.3640 - accuracy: 0.3900
Epoch 10/10
79/79 [==============================] - 1s 8ms/step - loss: 1.7547 - accuracy: 0.5328
313/313 [==============================] - 1s 3ms/step - loss: 5.6607 - accuracy: 0.2131
Test Accuracy: 0.21310000121593475
Epoch 1/10
79/79 [==============================] - 3s 7ms/step - loss: 4.0490 - accuracy: 0.1340
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 3.2432 - accuracy: 0.2272
Epoch 3/10
79/79 [==============================] - 0s 6ms/step - loss: 2.7420 - accuracy: 0.3224
Epoch 4/10
79/79 [==============================] - 0s 6ms/step - loss: 2.1643 - accuracy: 0.4308
Epoch 5/10
79/79 [==============================] - 0s 6ms/step - loss: 1.6245 - accuracy: 0.5620
Epoch 6/10
79/79 [==============================] - 0s 6ms/step - loss: 1.2263 - accuracy: 0.6472
Epoch 7/10
79/79 [==============================] - 1s 6ms/step - loss: 0.8481 - accuracy: 0.7512
Epoch 8/10
79/79 [==============================] - 1s 7ms/step - loss: 0.5937 - accuracy: 0.8340
Epoch 9/10
79/79 [==============================] - 1s 7ms/step - loss: 0.4772 - accuracy: 0.8512
Epoch 10/10
79/79 [==============================] - 1s 7ms/step - loss: 0.3428 - accuracy: 0.8924
Epoch 1/10
79/79 [==============================] - 5s 9ms/step - loss: 4.6018 - accuracy: 0.0132
Epoch 2/10
79/79 [==============================] - 1s 9ms/step - loss: 4.4980 - accuracy: 0.0308
Epoch 3/10
79/79 [==============================] - 1s 9ms/step - loss: 4.2079 - accuracy: 0.0536
Epoch 4/10
79/79 [==============================] - 1s 9ms/step - loss: 4.0157 - accuracy: 0.0768
Epoch 5/10
79/79 [==============================] - 1s 9ms/step - loss: 3.7491 - accuracy: 0.1244
Epoch 6/10
79/79 [==============================] - 1s 8ms/step - loss: 3.3685 - accuracy: 0.1844
Epoch 7/10
79/79 [==============================] - 1s 8ms/step - loss: 2.8801 - accuracy: 0.2784
Epoch 8/10
79/79 [==============================] - 1s 8ms/step - loss: 2.1364 - accuracy: 0.4428
Epoch 9/10
79/79 [==============================] - 1s 8ms/step - loss: 1.4369 - accuracy: 0.5996
Epoch 10/10
79/79 [==============================] - 1s 7ms/step - loss: 0.9156 - accuracy: 0.7508
313/313 [==============================] - 1s 3ms/step - loss: 5.5885 - accuracy: 0.2213
Test Accuracy: 0.22130000591278076
Epoch 1/10
79/79 [==============================] - 3s 7ms/step - loss: 4.1162 - accuracy: 0.1224
Epoch 2/10
79/79 [==============================] - 0s 6ms/step - loss: 3.3241 - accuracy: 0.2056
Epoch 3/10
79/79 [==============================] - 0s 6ms/step - loss: 2.7910 - accuracy: 0.3080
Epoch 4/10
79/79 [==============================] - 0s 6ms/step - loss: 2.2651 - accuracy: 0.4240
Epoch 5/10
79/79 [==============================] - 0s 6ms/step - loss: 1.7706 - accuracy: 0.5344
Epoch 6/10
79/79 [==============================] - 0s 6ms/step - loss: 1.2586 - accuracy: 0.6520
Epoch 7/10
79/79 [==============================] - 1s 7ms/step - loss: 0.8531 - accuracy: 0.7528
Epoch 8/10
79/79 [==============================] - 1s 7ms/step - loss: 0.5957 - accuracy: 0.8236
Epoch 9/10
79/79 [==============================] - 1s 7ms/step - loss: 0.4932 - accuracy: 0.8572
Epoch 10/10
79/79 [==============================] - 1s 7ms/step - loss: 0.3576 - accuracy: 0.8924
Epoch 1/10

#### Batches 10

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar100
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers

# Load the CIFAR-100 dataset
(x_train, y_train), (x_test, y_test) = cifar100.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 0.1  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = x_train + tf.random.normal(shape=x_train.shape, mean=0.0, stddev=corruption_level, dtype=tf.float32)
corrupted_data = tf.clip_by_value(corrupted_data, 0.0, 1.0)

# Convert the labels to one-hot encoding
num_classes = 100
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 2 batches
n_batches = 10
batch_size = x_train.shape[0] // n_batches

# Define the CrlB regularizer
class CrlBRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Define the original CIFAR-10 model
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu'),
    layers.Dropout(0.25),
    Dense(num_classes, activation='softmax')
])

# Compile the model
# model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the original model on Task A
# model.fit(corrupted_data, y_train_onehot, batch_size=128, epochs=10, validation_data=(x_test, y_test_onehot))

# Train the model on each batch separately
for i in range(n_batches):
    start_index = i * batch_size
    end_index = (i + 1) * batch_size
    x_batch = corrupted_data[start_index:end_index]
    y_batch = y_train[start_index:end_index]
    model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    # Train the model on the current batch
    model.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    # _, test_accuracy = model.evaluate(x_test, y_test)
    # print("Test Accuracy:", test_accuracy)
# Save the weights of the original model for later use
    prior_weights = model.get_weights()

# Compute the Fisher Information matrix
    def compute_fisher(model, x, num_samples=30):
        fisher_matrix = []
        for i in range(len(model.trainable_weights)):
            fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

        for _ in range(num_samples):
            idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
            with tf.GradientTape() as tape:
                logits = model(x[idx:idx+1])
            gradients = tape.gradient(logits, model.trainable_weights)
            for i in range(len(fisher_matrix)):
                fisher_matrix[i] += tf.square(gradients[i])

        fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
        return fisher_matrix

    fisher_matrix = compute_fisher(model, corrupted_data)

# Define the new model with CrlB regularization
    model_CrlB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3),
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])

# Compile the model with CrlB regularization
    model_CrlB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on Task B with CrlB regularization
# history = model_CrlB.fit(corrupted_data, y_train_onehot, batch_size=128, epochs=10, validation_data=(x_test, y_test_onehot))
# print(history)
# Train the model on each batch separately
# for i in range(n_batches):
#     start_index = i * batch_size
#     end_index = (i + 1) * batch_size
#     x_batch = corrupted_data[start_index:end_index]
#     y_batch = y_train[start_index:end_index]

    # Train the model on the current batch
    model_CrlB.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)
# # Evaluate the model on the test set
# _, test_accuracy = model.evaluate(x_test, y_test_onehot, verbose=0)
# print("Test Accuracy:", test_accuracy)

Epoch 1/10
157/157 [==============================] - 11s 8ms/step - loss: 4.5698 - accuracy: 0.0156
Epoch 2/10
157/157 [==============================] - 1s 7ms/step - loss: 4.4395 - accuracy: 0.0312
Epoch 3/10
157/157 [==============================] - 1s 6ms/step - loss: 4.2087 - accuracy: 0.0504
Epoch 4/10
157/157 [==============================] - 1s 6ms/step - loss: 3.9897 - accuracy: 0.0750
Epoch 5/10
157/157 [==============================] - 1s 6ms/step - loss: 3.7351 - accuracy: 0.1168
Epoch 6/10
157/157 [==============================] - 1s 9ms/step - loss: 3.4205 - accuracy: 0.1736
Epoch 7/10
157/157 [==============================] - 1s 9ms/step - loss: 3.0341 - accuracy: 0.2436
Epoch 8/10
157/157 [==============================] - 1s 7ms/step - loss: 2.5701 - accuracy: 0.3422
Epoch 9/10
157/157 [==============================] - 1s 6ms/step - loss: 2.0990 - accuracy: 0.4424
Epoch 10/10
157/157 [==============================] - 1s 7ms/step - loss: 1.6726 - accuracy: 0.5334
Epoch 1/10
157/157 [==============================] - 10s 10ms/step - loss: 4.5487 - accuracy: 0.0186
Epoch 2/10
157/157 [==============================] - 1s 9ms/step - loss: 4.2094 - accuracy: 0.0544
Epoch 3/10
157/157 [==============================] - 1s 9ms/step - loss: 3.9482 - accuracy: 0.0912
Epoch 4/10
157/157 [==============================] - 1s 9ms/step - loss: 3.6507 - accuracy: 0.1356
Epoch 5/10
157/157 [==============================] - 1s 9ms/step - loss: 3.2637 - accuracy: 0.1978
Epoch 6/10
157/157 [==============================] - 1s 9ms/step - loss: 2.7927 - accuracy: 0.2886
Epoch 7/10
157/157 [==============================] - 1s 9ms/step - loss: 2.2323 - accuracy: 0.4122
Epoch 8/10
157/157 [==============================] - 2s 12ms/step - loss: 1.6384 - accuracy: 0.5482
Epoch 9/10
157/157 [==============================] - 2s 10ms/step - loss: 1.1701 - accuracy: 0.6630
Epoch 10/10
157/157 [==============================] - 1s 9ms/step - loss: 0.7969 - accuracy: 0.7646
313/313 [==============================] - 1s 4ms/step - loss: 4.5169 - accuracy: 0.1627
Test Accuracy: 0.16269999742507935
Epoch 1/10
157/157 [==============================] - 3s 6ms/step - loss: 3.7874 - accuracy: 0.1398
Epoch 2/10
157/157 [==============================] - 1s 7ms/step - loss: 3.2386 - accuracy: 0.2162
Epoch 3/10
157/157 [==============================] - 1s 7ms/step - loss: 2.7830 - accuracy: 0.3010
Epoch 4/10
157/157 [==============================] - 1s 6ms/step - loss: 2.2673 - accuracy: 0.4084
Epoch 5/10
157/157 [==============================] - 1s 5ms/step - loss: 1.7347 - accuracy: 0.5300
Epoch 6/10
157/157 [==============================] - 1s 5ms/step - loss: 1.2551 - accuracy: 0.6518
Epoch 7/10
157/157 [==============================] - 1s 5ms/step - loss: 0.9593 - accuracy: 0.7270
Epoch 8/10
157/157 [==============================] - 1s 5ms/step - loss: 0.7370 - accuracy: 0.7870
Epoch 9/10
157/157 [==============================] - 1s 5ms/step - loss: 0.5429 - accuracy: 0.8404
Epoch 10/10
157/157 [==============================] - 1s 5ms/step - loss: 0.4370 - accuracy: 0.8702
Epoch 1/10
157/157 [==============================] - 7s 10ms/step - loss: 4.4986 - accuracy: 0.0218
Epoch 2/10
157/157 [==============================] - 1s 8ms/step - loss: 4.1477 - accuracy: 0.0536
Epoch 3/10
157/157 [==============================] - 1s 8ms/step - loss: 3.8392 - accuracy: 0.1020
Epoch 4/10
157/157 [==============================] - 1s 8ms/step - loss: 3.5171 - accuracy: 0.1534
Epoch 5/10
157/157 [==============================] - 1s 8ms/step - loss: 3.0911 - accuracy: 0.2348
Epoch 6/10
157/157 [==============================] - 1s 8ms/step - loss: 2.6509 - accuracy: 0.3276
Epoch 7/10
157/157 [==============================] - 1s 7ms/step - loss: 2.0562 - accuracy: 0.4508
Epoch 8/10
157/157 [==============================] - 1s 8ms/step - loss: 1.4703 - accuracy: 0.5922
Epoch 9/10
157/157 [==============================] - 1s 8ms/step - loss: 1.0326 - accuracy: 0.7046
Epoch 10/10
157/157 [==============================] - 1s 8ms/step - loss: 0.7187 - accuracy: 0.7902
313/313 [==============================] - 1s 4ms/step - loss: 5.9169 - accuracy: 0.2007
Test Accuracy: 0.20069999992847443
Epoch 1/10
157/157 [==============================] - 3s 6ms/step - loss: 3.8212 - accuracy: 0.1540
Epoch 2/10
157/157 [==============================] - 1s 5ms/step - loss: 3.1065 - accuracy: 0.2510
Epoch 3/10
157/157 [==============================] - 1s 5ms/step - loss: 2.5986 - accuracy: 0.3498
Epoch 4/10
157/157 [==============================] - 1s 5ms/step - loss: 2.0394 - accuracy: 0.4624
Epoch 5/10
157/157 [==============================] - 1s 6ms/step - loss: 1.4923 - accuracy: 0.5886
Epoch 6/10
157/157 [==============================] - 1s 6ms/step - loss: 1.0738 - accuracy: 0.6920
Epoch 7/10
157/157 [==============================] - 1s 6ms/step - loss: 0.7450 - accuracy: 0.7828
Epoch 8/10
157/157 [==============================] - 1s 6ms/step - loss: 0.5831 - accuracy: 0.8224
Epoch 9/10
157/157 [==============================] - 1s 6ms/step - loss: 0.4605 - accuracy: 0.8658
Epoch 10/10
157/157 [==============================] - 1s 7ms/step - loss: 0.3857 - accuracy: 0.8798
Epoch 1/10
157/157 [==============================] - 7s 8ms/step - loss: 4.5341 - accuracy: 0.0178
Epoch 2/10
157/157 [==============================] - 1s 8ms/step - loss: 4.1960 - accuracy: 0.0594
Epoch 3/10
157/157 [==============================] - 1s 8ms/step - loss: 3.9343 - accuracy: 0.0996
Epoch 4/10
157/157 [==============================] - 2s 10ms/step - loss: 3.6726 - accuracy: 0.1432
Epoch 5/10
157/157 [==============================] - 2s 10ms/step - loss: 3.3212 - accuracy: 0.2020
Epoch 6/10
157/157 [==============================] - 2s 10ms/step - loss: 2.8825 - accuracy: 0.2904
Epoch 7/10
157/157 [==============================] - 1s 8ms/step - loss: 2.3115 - accuracy: 0.3952
Epoch 8/10
157/157 [==============================] - 1s 8ms/step - loss: 1.7489 - accuracy: 0.5280
Epoch 9/10
157/157 [==============================] - 1s 8ms/step - loss: 1.2530 - accuracy: 0.6504
Epoch 10/10
157/157 [==============================] - 1s 8ms/step - loss: 0.8516 - accuracy: 0.7592
313/313 [==============================] - 1s 3ms/step - loss: 5.5682 - accuracy: 0.2208
Test Accuracy: 0.2207999974489212
Epoch 1/10
157/157 [==============================] - 3s 6ms/step - loss: 3.8523 - accuracy: 0.1456
Epoch 2/10
157/157 [==============================] - 1s 6ms/step - loss: 3.0648 - accuracy: 0.2598
Epoch 3/10
157/157 [==============================] - 1s 7ms/step - loss: 2.5723 - accuracy: 0.3468
Epoch 4/10
157/157 [==============================] - 1s 7ms/step - loss: 2.0033 - accuracy: 0.4840
Epoch 5/10
157/157 [==============================] - 1s 6ms/step - loss: 1.5064 - accuracy: 0.5838
Epoch 6/10
157/157 [==============================] - 1s 6ms/step - loss: 1.0513 - accuracy: 0.7052
Epoch 7/10
157/157 [==============================] - 1s 6ms/step - loss: 0.7474 - accuracy: 0.7840
Epoch 8/10
157/157 [==============================] - 1s 6ms/step - loss: 0.5497 - accuracy: 0.8320
Epoch 9/10
157/157 [==============================] - 1s 6ms/step - loss: 0.4478 - accuracy: 0.8596
Epoch 10/10
157/157 [==============================] - 1s 6ms/step - loss: 0.3811 - accuracy: 0.8884
Epoch 1/10
157/157 [==============================] - 6s 9ms/step - loss: 4.5490 - accuracy: 0.0144
Epoch 2/10
157/157 [==============================] - 1s 9ms/step - loss: 4.2231 - accuracy: 0.0542
Epoch 3/10
157/157 [==============================] - 1s 8ms/step - loss: 3.8486 - accuracy: 0.1124
Epoch 4/10
157/157 [==============================] - 1s 8ms/step - loss: 3.5023 - accuracy: 0.1658
Epoch 5/10
157/157 [==============================] - 1s 8ms/step - loss: 3.1171 - accuracy: 0.2384
Epoch 6/10
157/157 [==============================] - 1s 8ms/step - loss: 2.6097 - accuracy: 0.3252
Epoch 7/10
157/157 [==============================] - 1s 8ms/step - loss: 2.0602 - accuracy: 0.4518
Epoch 8/10
157/157 [==============================] - 1s 8ms/step - loss: 1.4968 - accuracy: 0.5922
Epoch 9/10
157/157 [==============================] - 1s 8ms/step - loss: 1.0482 - accuracy: 0.7050
Epoch 10/10
157/157 [==============================] - 1s 8ms/step - loss: 0.7759 - accuracy: 0.7810
313/313 [==============================] - 1s 3ms/step - loss: 5.4983 - accuracy: 0.2322
Test Accuracy: 0.2321999967098236
Epoch 1/10
157/157 [==============================] - 3s 6ms/step - loss: 3.8672 - accuracy: 0.1472
Epoch 2/10
157/157 [==============================] - 1s 6ms/step - loss: 3.1109 - accuracy: 0.2450
Epoch 3/10
157/157 [==============================] - 1s 7ms/step - loss: 2.5763 - accuracy: 0.3414
Epoch 4/10
157/157 [==============================] - 1s 7ms/step - loss: 2.0619 - accuracy: 0.4612
Epoch 5/10
157/157 [==============================] - 1s 6ms/step - loss: 1.5608 - accuracy: 0.5682
Epoch 6/10
157/157 [==============================] - 1s 5ms/step - loss: 1.1009 - accuracy: 0.6926
Epoch 7/10
157/157 [==============================] - 1s 6ms/step - loss: 0.8009 - accuracy: 0.7704
Epoch 8/10
157/157 [==============================] - 1s 5ms/step - loss: 0.6112 - accuracy: 0.8162
Epoch 9/10
157/157 [==============================] - 1s 6ms/step - loss: 0.4745 - accuracy: 0.8552
Epoch 10/10
157/157 [==============================] - 1s 5ms/step - loss: 0.3759 - accuracy: 0.8834
Epoch 1/10
157/157 [==============================] - 6s 9ms/step - loss: 4.5497 - accuracy: 0.0184
Epoch 2/10
157/157 [==============================] - 2s 10ms/step - loss: 4.2378 - accuracy: 0.0522
Epoch 3/10
157/157 [==============================] - 1s 8ms/step - loss: 3.9331 - accuracy: 0.1000
Epoch 4/10
157/157 [==============================] - 1s 8ms/step - loss: 3.6216 - accuracy: 0.1450
Epoch 5/10
157/157 [==============================] - 1s 8ms/step - loss: 3.2702 - accuracy: 0.2038
Epoch 6/10
157/157 [==============================] - 1s 8ms/step - loss: 2.8194 - accuracy: 0.2912
Epoch 7/10
157/157 [==============================] - 1s 8ms/step - loss: 2.2656 - accuracy: 0.4040
Epoch 8/10
157/157 [==============================] - 1s 8ms/step - loss: 1.6780 - accuracy: 0.5478
Epoch 9/10
157/157 [==============================] - 1s 8ms/step - loss: 1.1369 - accuracy: 0.6800
Epoch 10/10
157/157 [==============================] - 1s 8ms/step - loss: 0.8298 - accuracy: 0.7688
313/313 [==============================] - 1s 3ms/step - loss: 4.9618 - accuracy: 0.2489
Test Accuracy: 0.24889999628067017
Epoch 1/10
157/157 [==============================] - 3s 6ms/step - loss: 3.6955 - accuracy: 0.1692
Epoch 2/10
157/157 [==============================] - 1s 7ms/step - loss: 2.9863 - accuracy: 0.2686
Epoch 3/10
157/157 [==============================] - 1s 7ms/step - loss: 2.4704 - accuracy: 0.3684
Epoch 4/10
157/157 [==============================] - 1s 7ms/step - loss: 1.9801 - accuracy: 0.4802
Epoch 5/10
157/157 [==============================] - 1s 6ms/step - loss: 1.5005 - accuracy: 0.5772
Epoch 6/10
157/157 [==============================] - 1s 6ms/step - loss: 1.1319 - accuracy: 0.6686
Epoch 7/10
157/157 [==============================] - 1s 6ms/step - loss: 0.8200 - accuracy: 0.7574
Epoch 8/10
157/157 [==============================] - 1s 6ms/step - loss: 0.6116 - accuracy: 0.8122
Epoch 9/10
157/157 [==============================] - 1s 6ms/step - loss: 0.4997 - accuracy: 0.8480
Epoch 10/10
157/157 [==============================] - 1s 6ms/step - loss: 0.3897 - accuracy: 0.8784
Epoch 1/10
157/157 [==============================] - 7s 9ms/step - loss: 4.5769 - accuracy: 0.0178
Epoch 2/10
157/157 [==============================] - 1s 8ms/step - loss: 4.2417 - accuracy: 0.0518
Epoch 3/10
157/157 [==============================] - 1s 8ms/step - loss: 3.9321 - accuracy: 0.0936
Epoch 4/10
157/157 [==============================] - 1s 8ms/step - loss: 3.6288 - accuracy: 0.1380
Epoch 5/10
157/157 [==============================] - 1s 8ms/step - loss: 3.2642 - accuracy: 0.2016
Epoch 6/10
157/157 [==============================] - 1s 8ms/step - loss: 2.8456 - accuracy: 0.2918
Epoch 7/10
157/157 [==============================] - 1s 8ms/step - loss: 2.2647 - accuracy: 0.4064
Epoch 8/10
157/157 [==============================] - 1s 8ms/step - loss: 1.6532 - accuracy: 0.5484
Epoch 9/10
157/157 [==============================] - 1s 8ms/step - loss: 1.0825 - accuracy: 0.6880
Epoch 10/10
157/157 [==============================] - 2s 11ms/step - loss: 0.7824 - accuracy: 0.7754
313/313 [==============================] - 1s 3ms/step - loss: 4.8770 - accuracy: 0.2535
Test Accuracy: 0.2535000145435333
Epoch 1/10
157/157 [==============================] - 3s 6ms/step - loss: 3.7259 - accuracy: 0.1630
Epoch 2/10
157/157 [==============================] - 1s 6ms/step - loss: 3.0507 - accuracy: 0.2646
Epoch 3/10
157/157 [==============================] - 1s 6ms/step - loss: 2.5679 - accuracy: 0.3518
Epoch 4/10
157/157 [==============================] - 1s 6ms/step - loss: 2.1278 - accuracy: 0.4298
Epoch 5/10
157/157 [==============================] - 1s 6ms/step - loss: 1.6496 - accuracy: 0.5492
Epoch 6/10
157/157 [==============================] - 1s 6ms/step - loss: 1.2111 - accuracy: 0.6584
Epoch 7/10
157/157 [==============================] - 1s 7ms/step - loss: 0.9126 - accuracy: 0.7350
Epoch 8/10
157/157 [==============================] - 1s 8ms/step - loss: 0.6671 - accuracy: 0.7950
Epoch 9/10
157/157 [==============================] - 1s 6ms/step - loss: 0.5361 - accuracy: 0.8362
Epoch 10/10
157/157 [==============================] - 1s 6ms/step - loss: 0.4114 - accuracy: 0.8778
Epoch 1/10
157/157 [==============================] - 7s 8ms/step - loss: 4.5891 - accuracy: 0.0136
Epoch 2/10
157/157 [==============================] - 1s 8ms/step - loss: 4.2993 - accuracy: 0.0432
Epoch 3/10
157/157 [==============================] - 2s 10ms/step - loss: 3.9334 - accuracy: 0.0940
Epoch 4/10
157/157 [==============================] - 1s 9ms/step - loss: 3.6778 - accuracy: 0.1334
Epoch 5/10
157/157 [==============================] - 1s 8ms/step - loss: 3.3958 - accuracy: 0.1788
Epoch 6/10
157/157 [==============================] - 1s 8ms/step - loss: 3.0638 - accuracy: 0.2374
Epoch 7/10
157/157 [==============================] - 1s 8ms/step - loss: 2.6393 - accuracy: 0.3196
Epoch 8/10
157/157 [==============================] - 1s 8ms/step - loss: 2.1147 - accuracy: 0.4366
Epoch 9/10
157/157 [==============================] - 1s 8ms/step - loss: 1.5940 - accuracy: 0.5636
Epoch 10/10
157/157 [==============================] - 1s 8ms/step - loss: 1.1197 - accuracy: 0.6884
313/313 [==============================] - 1s 3ms/step - loss: 4.6114 - accuracy: 0.2708
Test Accuracy: 0.27079999446868896
Epoch 1/10
157/157 [==============================] - 3s 6ms/step - loss: 3.6353 - accuracy: 0.1852
Epoch 2/10
157/157 [==============================] - 1s 5ms/step - loss: 3.0134 - accuracy: 0.2708
Epoch 3/10
157/157 [==============================] - 1s 5ms/step - loss: 2.5355 - accuracy: 0.3534
Epoch 4/10
157/157 [==============================] - 1s 6ms/step - loss: 2.0838 - accuracy: 0.4564
Epoch 5/10
157/157 [==============================] - 1s 7ms/step - loss: 1.6451 - accuracy: 0.5558
Epoch 6/10
157/157 [==============================] - 1s 7ms/step - loss: 1.2567 - accuracy: 0.6410
Epoch 7/10
157/157 [==============================] - 1s 6ms/step - loss: 0.9536 - accuracy: 0.7300
Epoch 8/10
157/157 [==============================] - 1s 6ms/step - loss: 0.6830 - accuracy: 0.8004
Epoch 9/10
157/157 [==============================] - 1s 6ms/step - loss: 0.5346 - accuracy: 0.8404
Epoch 10/10
157/157 [==============================] - 1s 5ms/step - loss: 0.4245 - accuracy: 0.8626
Epoch 1/10
157/157 [==============================] - 6s 8ms/step - loss: 4.5486 - accuracy: 0.0142
Epoch 2/10
157/157 [==============================] - 2s 10ms/step - loss: 4.2502 - accuracy: 0.0390
Epoch 3/10
157/157 [==============================] - 1s 9ms/step - loss: 3.9773 - accuracy: 0.0790
Epoch 4/10
157/157 [==============================] - 1s 8ms/step - loss: 3.6855 - accuracy: 0.1292
Epoch 5/10
157/157 [==============================] - 1s 8ms/step - loss: 3.4036 - accuracy: 0.1758
Epoch 6/10
157/157 [==============================] - 1s 8ms/step - loss: 3.0569 - accuracy: 0.2418
Epoch 7/10
157/157 [==============================] - 1s 8ms/step - loss: 2.6206 - accuracy: 0.3332
Epoch 8/10
157/157 [==============================] - 1s 8ms/step - loss: 2.1116 - accuracy: 0.4392
Epoch 9/10
157/157 [==============================] - 1s 8ms/step - loss: 1.5796 - accuracy: 0.5694
Epoch 10/10
157/157 [==============================] - 1s 8ms/step - loss: 1.1191 - accuracy: 0.6810
313/313 [==============================] - 1s 3ms/step - loss: 4.6559 - accuracy: 0.2705
Test Accuracy: 0.2705000042915344
Epoch 1/10
157/157 [==============================] - 3s 6ms/step - loss: 3.6528 - accuracy: 0.1792
Epoch 2/10
157/157 [==============================] - 1s 6ms/step - loss: 3.0119 - accuracy: 0.2698
Epoch 3/10
157/157 [==============================] - 1s 6ms/step - loss: 2.5957 - accuracy: 0.3478
Epoch 4/10
157/157 [==============================] - 1s 6ms/step - loss: 2.1360 - accuracy: 0.4454
Epoch 5/10
157/157 [==============================] - 1s 7ms/step - loss: 1.6941 - accuracy: 0.5404
Epoch 6/10
157/157 [==============================] - 1s 6ms/step - loss: 1.3069 - accuracy: 0.6328
Epoch 7/10
157/157 [==============================] - 1s 6ms/step - loss: 0.9878 - accuracy: 0.7112
Epoch 8/10
157/157 [==============================] - 1s 6ms/step - loss: 0.7660 - accuracy: 0.7784
Epoch 9/10
157/157 [==============================] - 1s 6ms/step - loss: 0.5621 - accuracy: 0.8298
Epoch 10/10
157/157 [==============================] - 1s 6ms/step - loss: 0.4522 - accuracy: 0.8598
Epoch 1/10
157/157 [==============================] - 6s 10ms/step - loss: 4.4832 - accuracy: 0.0276
Epoch 2/10
157/157 [==============================] - 1s 9ms/step - loss: 4.0928 - accuracy: 0.0672
Epoch 3/10
157/157 [==============================] - 1s 8ms/step - loss: 3.7891 - accuracy: 0.1132
Epoch 4/10
157/157 [==============================] - 1s 8ms/step - loss: 3.5229 - accuracy: 0.1680
Epoch 5/10
157/157 [==============================] - 1s 8ms/step - loss: 3.1951 - accuracy: 0.2258
Epoch 6/10
157/157 [==============================] - 1s 8ms/step - loss: 2.7966 - accuracy: 0.2952
Epoch 7/10
157/157 [==============================] - 1s 8ms/step - loss: 2.3069 - accuracy: 0.4020
Epoch 8/10
157/157 [==============================] - 1s 8ms/step - loss: 1.7726 - accuracy: 0.5210
Epoch 9/10
157/157 [==============================] - 1s 8ms/step - loss: 1.2417 - accuracy: 0.6538
Epoch 10/10
157/157 [==============================] - 1s 8ms/step - loss: 0.8766 - accuracy: 0.7450
313/313 [==============================] - 1s 4ms/step - loss: 4.4491 - accuracy: 0.2685
Test Accuracy: 0.2685000002384186
Epoch 1/10
157/157 [==============================] - 3s 6ms/step - loss: 3.6478 - accuracy: 0.1818
Epoch 2/10
157/157 [==============================] - 1s 6ms/step - loss: 3.0562 - accuracy: 0.2632
Epoch 3/10
157/157 [==============================] - 1s 6ms/step - loss: 2.6464 - accuracy: 0.3342
Epoch 4/10
157/157 [==============================] - 1s 6ms/step - loss: 2.2175 - accuracy: 0.4178
Epoch 5/10
157/157 [==============================] - 1s 6ms/step - loss: 1.7807 - accuracy: 0.5184
Epoch 6/10
157/157 [==============================] - 1s 6ms/step - loss: 1.3572 - accuracy: 0.6214
Epoch 7/10
157/157 [==============================] - 1s 6ms/step - loss: 1.0354 - accuracy: 0.6996
Epoch 8/10
157/157 [==============================] - 1s 7ms/step - loss: 0.7592 - accuracy: 0.7772
Epoch 9/10

#### Batches 6

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar100
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers

# Load the CIFAR-100 dataset
(x_train, y_train), (x_test, y_test) = cifar100.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 0.1  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = x_train + tf.random.normal(shape=x_train.shape, mean=0.0, stddev=corruption_level, dtype=tf.float32)
corrupted_data = tf.clip_by_value(corrupted_data, 0.0, 1.0)

# Convert the labels to one-hot encoding
num_classes = 100
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 2 batches
n_batches = 6
batch_size = x_train.shape[0] // n_batches

# Define the CrlB regularizer
class CrlBRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Define the original CIFAR-10 model
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu'),
    layers.Dropout(0.25),
    Dense(num_classes, activation='softmax')
])

# Compile the model
# model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the original model on Task A
# model.fit(corrupted_data, y_train_onehot, batch_size=128, epochs=10, validation_data=(x_test, y_test_onehot))

# Train the model on each batch separately
for i in range(n_batches):
    start_index = i * batch_size
    end_index = (i + 1) * batch_size
    x_batch = corrupted_data[start_index:end_index]
    y_batch = y_train[start_index:end_index]
    model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    # Train the model on the current batch
    model.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    # _, test_accuracy = model.evaluate(x_test, y_test)
    # print("Test Accuracy:", test_accuracy)
# Save the weights of the original model for later use
    prior_weights = model.get_weights()

# Compute the Fisher Information matrix
    def compute_fisher(model, x, num_samples=30):
        fisher_matrix = []
        for i in range(len(model.trainable_weights)):
            fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

        for _ in range(num_samples):
            idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
            with tf.GradientTape() as tape:
                logits = model(x[idx:idx+1])
            gradients = tape.gradient(logits, model.trainable_weights)
            for i in range(len(fisher_matrix)):
                fisher_matrix[i] += tf.square(gradients[i])

        fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
        return fisher_matrix

    fisher_matrix = compute_fisher(model, corrupted_data)

# Define the new model with CrlB regularization
    model_CrlB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3),
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])

# Compile the model with CrlB regularization
    model_CrlB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on Task B with CrlB regularization
# history = model_CrlB.fit(corrupted_data, y_train_onehot, batch_size=128, epochs=10, validation_data=(x_test, y_test_onehot))
# print(history)
# Train the model on each batch separately
# for i in range(n_batches):
#     start_index = i * batch_size
#     end_index = (i + 1) * batch_size
#     x_batch = corrupted_data[start_index:end_index]
#     y_batch = y_train[start_index:end_index]

    # Train the model on the current batch
    model_CrlB.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)
# # Evaluate the model on the test set
# _, test_accuracy = model.evaluate(x_test, y_test_onehot, verbose=0)
# print("Test Accuracy:", test_accuracy)

Epoch 1/10
261/261 [==============================] - 4s 7ms/step - loss: 4.4316 - accuracy: 0.0250
Epoch 2/10
261/261 [==============================] - 1s 5ms/step - loss: 4.0712 - accuracy: 0.0625
Epoch 3/10
261/261 [==============================] - 1s 5ms/step - loss: 3.7959 - accuracy: 0.1140
Epoch 4/10
261/261 [==============================] - 1s 5ms/step - loss: 3.4969 - accuracy: 0.1667
Epoch 5/10
261/261 [==============================] - 1s 5ms/step - loss: 3.1769 - accuracy: 0.2272
Epoch 6/10
261/261 [==============================] - 1s 5ms/step - loss: 2.8076 - accuracy: 0.2916
Epoch 7/10
261/261 [==============================] - 2s 7ms/step - loss: 2.4786 - accuracy: 0.3594
Epoch 8/10
261/261 [==============================] - 2s 6ms/step - loss: 2.1183 - accuracy: 0.4401
Epoch 9/10
261/261 [==============================] - 1s 6ms/step - loss: 1.7884 - accuracy: 0.5040
Epoch 10/10
261/261 [==============================] - 1s 5ms/step - loss: 1.4883 - accuracy: 0.5862
Epoch 1/10
261/261 [==============================] - 7s 8ms/step - loss: 4.3937 - accuracy: 0.0323
Epoch 2/10
261/261 [==============================] - 2s 9ms/step - loss: 4.0324 - accuracy: 0.0781
Epoch 3/10
261/261 [==============================] - 2s 8ms/step - loss: 3.7088 - accuracy: 0.1241
Epoch 4/10
261/261 [==============================] - 2s 8ms/step - loss: 3.3852 - accuracy: 0.1850
Epoch 5/10
261/261 [==============================] - 2s 7ms/step - loss: 3.0120 - accuracy: 0.2544
Epoch 6/10
261/261 [==============================] - 2s 8ms/step - loss: 2.5999 - accuracy: 0.3402
Epoch 7/10
261/261 [==============================] - 2s 8ms/step - loss: 2.1508 - accuracy: 0.4242
Epoch 8/10
261/261 [==============================] - 2s 8ms/step - loss: 1.6588 - accuracy: 0.5397
Epoch 9/10
261/261 [==============================] - 2s 7ms/step - loss: 1.2304 - accuracy: 0.6484
Epoch 10/10
261/261 [==============================] - 2s 8ms/step - loss: 0.9466 - accuracy: 0.7241
313/313 [==============================] - 1s 3ms/step - loss: 4.0430 - accuracy: 0.2197
Test Accuracy: 0.21969999372959137
Epoch 1/10
261/261 [==============================] - 4s 6ms/step - loss: 3.4800 - accuracy: 0.1902
Epoch 2/10
261/261 [==============================] - 1s 5ms/step - loss: 2.9812 - accuracy: 0.2677
Epoch 3/10
261/261 [==============================] - 1s 6ms/step - loss: 2.5853 - accuracy: 0.3481
Epoch 4/10
261/261 [==============================] - 2s 6ms/step - loss: 2.1743 - accuracy: 0.4241
Epoch 5/10
261/261 [==============================] - 2s 7ms/step - loss: 1.7648 - accuracy: 0.5191
Epoch 6/10
261/261 [==============================] - 1s 5ms/step - loss: 1.4180 - accuracy: 0.6019
Epoch 7/10
261/261 [==============================] - 1s 5ms/step - loss: 1.1226 - accuracy: 0.6775
Epoch 8/10
261/261 [==============================] - 1s 5ms/step - loss: 0.9153 - accuracy: 0.7294
Epoch 9/10
261/261 [==============================] - 1s 6ms/step - loss: 0.7862 - accuracy: 0.7660
Epoch 10/10
261/261 [==============================] - 1s 5ms/step - loss: 0.6321 - accuracy: 0.8141
Epoch 1/10
261/261 [==============================] - 7s 8ms/step - loss: 4.4181 - accuracy: 0.0271
Epoch 2/10
261/261 [==============================] - 2s 8ms/step - loss: 4.0221 - accuracy: 0.0820
Epoch 3/10
261/261 [==============================] - 2s 7ms/step - loss: 3.6810 - accuracy: 0.1358
Epoch 4/10
261/261 [==============================] - 2s 8ms/step - loss: 3.2721 - accuracy: 0.2113
Epoch 5/10
261/261 [==============================] - 2s 9ms/step - loss: 2.8468 - accuracy: 0.2886
Epoch 6/10
261/261 [==============================] - 2s 8ms/step - loss: 2.3857 - accuracy: 0.3868
Epoch 7/10
261/261 [==============================] - 2s 8ms/step - loss: 1.8993 - accuracy: 0.4998
Epoch 8/10
261/261 [==============================] - 2s 8ms/step - loss: 1.4137 - accuracy: 0.6053
Epoch 9/10
261/261 [==============================] - 2s 8ms/step - loss: 1.0837 - accuracy: 0.6917
Epoch 10/10
261/261 [==============================] - 2s 8ms/step - loss: 0.8136 - accuracy: 0.7692
313/313 [==============================] - 1s 4ms/step - loss: 4.5870 - accuracy: 0.2551
Test Accuracy: 0.2551000118255615
Epoch 1/10
261/261 [==============================] - 4s 6ms/step - loss: 3.5191 - accuracy: 0.1902
Epoch 2/10
261/261 [==============================] - 1s 5ms/step - loss: 2.9127 - accuracy: 0.2827
Epoch 3/10
261/261 [==============================] - 1s 5ms/step - loss: 2.4751 - accuracy: 0.3711
Epoch 4/10
261/261 [==============================] - 1s 5ms/step - loss: 2.0505 - accuracy: 0.4590
Epoch 5/10
261/261 [==============================] - 1s 5ms/step - loss: 1.6228 - accuracy: 0.5555
Epoch 6/10
261/261 [==============================] - 1s 5ms/step - loss: 1.2607 - accuracy: 0.6433
Epoch 7/10
261/261 [==============================] - 2s 7ms/step - loss: 0.9941 - accuracy: 0.7133
Epoch 8/10
261/261 [==============================] - 2s 6ms/step - loss: 0.7729 - accuracy: 0.7712
Epoch 9/10
261/261 [==============================] - 1s 6ms/step - loss: 0.6396 - accuracy: 0.8073
Epoch 10/10
261/261 [==============================] - 1s 5ms/step - loss: 0.5320 - accuracy: 0.8374
Epoch 1/10
261/261 [==============================] - 8s 8ms/step - loss: 4.4558 - accuracy: 0.0265
Epoch 2/10
261/261 [==============================] - 2s 8ms/step - loss: 4.0027 - accuracy: 0.0806
Epoch 3/10
261/261 [==============================] - 2s 8ms/step - loss: 3.6703 - accuracy: 0.1398
Epoch 4/10
261/261 [==============================] - 2s 9ms/step - loss: 3.2983 - accuracy: 0.2015
Epoch 5/10
261/261 [==============================] - 2s 9ms/step - loss: 2.8813 - accuracy: 0.2765
Epoch 6/10
261/261 [==============================] - 2s 8ms/step - loss: 2.4383 - accuracy: 0.3708
Epoch 7/10
261/261 [==============================] - 2s 8ms/step - loss: 1.9649 - accuracy: 0.4750
Epoch 8/10
261/261 [==============================] - 2s 8ms/step - loss: 1.5221 - accuracy: 0.5808
Epoch 9/10
261/261 [==============================] - 2s 8ms/step - loss: 1.1216 - accuracy: 0.6789
Epoch 10/10
261/261 [==============================] - 2s 8ms/step - loss: 0.8419 - accuracy: 0.7540
313/313 [==============================] - 1s 3ms/step - loss: 4.3496 - accuracy: 0.2719
Test Accuracy: 0.2718999981880188
Epoch 1/10
261/261 [==============================] - 4s 6ms/step - loss: 3.4153 - accuracy: 0.2144
Epoch 2/10
261/261 [==============================] - 1s 5ms/step - loss: 2.8005 - accuracy: 0.3065
Epoch 3/10
261/261 [==============================] - 1s 5ms/step - loss: 2.3927 - accuracy: 0.3895
Epoch 4/10
261/261 [==============================] - 1s 5ms/step - loss: 1.9751 - accuracy: 0.4732
Epoch 5/10
261/261 [==============================] - 2s 6ms/step - loss: 1.5445 - accuracy: 0.5749
Epoch 6/10
261/261 [==============================] - 2s 7ms/step - loss: 1.2255 - accuracy: 0.6491
Epoch 7/10
261/261 [==============================] - 1s 6ms/step - loss: 0.9476 - accuracy: 0.7215
Epoch 8/10
261/261 [==============================] - 1s 6ms/step - loss: 0.7502 - accuracy: 0.7782
Epoch 9/10
261/261 [==============================] - 1s 6ms/step - loss: 0.6140 - accuracy: 0.8121
Epoch 10/10
261/261 [==============================] - 1s 6ms/step - loss: 0.5140 - accuracy: 0.8420
Epoch 1/10
261/261 [==============================] - 7s 8ms/step - loss: 4.4344 - accuracy: 0.0318
Epoch 2/10
261/261 [==============================] - 2s 8ms/step - loss: 3.9546 - accuracy: 0.0869
Epoch 3/10
261/261 [==============================] - 2s 8ms/step - loss: 3.6222 - accuracy: 0.1392
Epoch 4/10
261/261 [==============================] - 2s 9ms/step - loss: 3.2971 - accuracy: 0.2058
Epoch 5/10
261/261 [==============================] - 2s 8ms/step - loss: 2.9490 - accuracy: 0.2723
Epoch 6/10
261/261 [==============================] - 2s 8ms/step - loss: 2.5609 - accuracy: 0.3388
Epoch 7/10
261/261 [==============================] - 2s 8ms/step - loss: 2.1198 - accuracy: 0.4403
Epoch 8/10
261/261 [==============================] - 2s 8ms/step - loss: 1.6465 - accuracy: 0.5455
Epoch 9/10
261/261 [==============================] - 2s 8ms/step - loss: 1.2656 - accuracy: 0.6421
Epoch 10/10
261/261 [==============================] - 2s 9ms/step - loss: 0.9399 - accuracy: 0.7276
313/313 [==============================] - 1s 3ms/step - loss: 4.4898 - accuracy: 0.2872
Test Accuracy: 0.287200003862381
Epoch 1/10
261/261 [==============================] - 4s 6ms/step - loss: 3.4524 - accuracy: 0.2102
Epoch 2/10
261/261 [==============================] - 1s 6ms/step - loss: 2.8493 - accuracy: 0.2897
Epoch 3/10
261/261 [==============================] - 1s 6ms/step - loss: 2.4390 - accuracy: 0.3775
Epoch 4/10
261/261 [==============================] - 2s 6ms/step - loss: 2.0329 - accuracy: 0.4644
Epoch 5/10
261/261 [==============================] - 2s 7ms/step - loss: 1.6264 - accuracy: 0.5499
Epoch 6/10
261/261 [==============================] - 1s 6ms/step - loss: 1.2849 - accuracy: 0.6384
Epoch 7/10
261/261 [==============================] - 1s 6ms/step - loss: 1.0033 - accuracy: 0.7098
Epoch 8/10
261/261 [==============================] - 1s 6ms/step - loss: 0.7835 - accuracy: 0.7694
Epoch 9/10
261/261 [==============================] - 1s 6ms/step - loss: 0.6637 - accuracy: 0.7997
Epoch 10/10
261/261 [==============================] - 1s 6ms/step - loss: 0.5451 - accuracy: 0.8304
Epoch 1/10
261/261 [==============================] - 7s 8ms/step - loss: 4.4179 - accuracy: 0.0300
Epoch 2/10
261/261 [==============================] - 2s 8ms/step - loss: 3.9524 - accuracy: 0.0877
Epoch 3/10
261/261 [==============================] - 3s 10ms/step - loss: 3.5938 - accuracy: 0.1469
Epoch 4/10
261/261 [==============================] - 2s 8ms/step - loss: 3.2381 - accuracy: 0.2129
Epoch 5/10
261/261 [==============================] - 2s 8ms/step - loss: 2.8194 - accuracy: 0.2964
Epoch 6/10
261/261 [==============================] - 2s 8ms/step - loss: 2.3124 - accuracy: 0.3989
Epoch 7/10
261/261 [==============================] - 2s 8ms/step - loss: 1.7841 - accuracy: 0.5219
Epoch 8/10
261/261 [==============================] - 2s 8ms/step - loss: 1.3074 - accuracy: 0.6307
Epoch 9/10
261/261 [==============================] - 2s 9ms/step - loss: 0.9450 - accuracy: 0.7275
Epoch 10/10
261/261 [==============================] - 2s 8ms/step - loss: 0.6898 - accuracy: 0.7968
313/313 [==============================] - 1s 4ms/step - loss: 4.2838 - accuracy: 0.2859
Test Accuracy: 0.2858999967575073
Epoch 1/10
261/261 [==============================] - 4s 6ms/step - loss: 3.4604 - accuracy: 0.2130
Epoch 2/10
261/261 [==============================] - 1s 6ms/step - loss: 2.8484 - accuracy: 0.2961
Epoch 3/10
261/261 [==============================] - 1s 6ms/step - loss: 2.4408 - accuracy: 0.3744
Epoch 4/10
261/261 [==============================] - 1s 6ms/step - loss: 2.0410 - accuracy: 0.4548
Epoch 5/10
261/261 [==============================] - 1s 6ms/step - loss: 1.6613 - accuracy: 0.5423
Epoch 6/10
261/261 [==============================] - 2s 7ms/step - loss: 1.3195 - accuracy: 0.6318
Epoch 7/10
261/261 [==============================] - 2s 6ms/step - loss: 1.0183 - accuracy: 0.6997
Epoch 8/10
261/261 [==============================] - 1s 6ms/step - loss: 0.8164 - accuracy: 0.7562
Epoch 9/10
261/261 [==============================] - 2s 6ms/step - loss: 0.6692 - accuracy: 0.7955
Epoch 10/10
261/261 [==============================] - 1s 6ms/step - loss: 0.5303 - accuracy: 0.8418
Epoch 1/10
261/261 [==============================] - 8s 8ms/step - loss: 4.4981 - accuracy: 0.0223
Epoch 2/10
261/261 [==============================] - 2s 8ms/step - loss: 3.9967 - accuracy: 0.0896
Epoch 3/10
261/261 [==============================] - 2s 8ms/step - loss: 3.6248 - accuracy: 0.1427
Epoch 4/10
261/261 [==============================] - 2s 8ms/step - loss: 3.3103 - accuracy: 0.1984
Epoch 5/10
261/261 [==============================] - 2s 8ms/step - loss: 2.9499 - accuracy: 0.2665
Epoch 6/10
261/261 [==============================] - 2s 10ms/step - loss: 2.5457 - accuracy: 0.3454
Epoch 7/10
261/261 [==============================] - 2s 8ms/step - loss: 2.0893 - accuracy: 0.4417
Epoch 8/10
261/261 [==============================] - 2s 8ms/step - loss: 1.6368 - accuracy: 0.5484
Epoch 9/10
261/261 [==============================] - 2s 8ms/step - loss: 1.2272 - accuracy: 0.6581
Epoch 10/10
261/261 [==============================] - 2s 8ms/step - loss: 0.9300 - accuracy: 0.7348
313/313 [==============================] - 1s 3ms/step - loss: 4.2889 - accuracy: 0.2951
Test Accuracy: 0.29510000348091125

#### Batches 5

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar100
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers

# Load the CIFAR-100 dataset
(x_train, y_train), (x_test, y_test) = cifar100.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 0.1  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = x_train + tf.random.normal(shape=x_train.shape, mean=0.0, stddev=corruption_level, dtype=tf.float32)
corrupted_data = tf.clip_by_value(corrupted_data, 0.0, 1.0)

# Convert the labels to one-hot encoding
num_classes = 100
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 2 batches
n_batches = 5
batch_size = x_train.shape[0] // n_batches

# Define the CrlB regularizer
class CrlBRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Define the original CIFAR-10 model
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu'),
    layers.Dropout(0.25),
    Dense(num_classes, activation='softmax')
])

# Compile the model
# model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the original model on Task A
# model.fit(corrupted_data, y_train_onehot, batch_size=128, epochs=10, validation_data=(x_test, y_test_onehot))

# Train the model on each batch separately
for i in range(n_batches):
    start_index = i * batch_size
    end_index = (i + 1) * batch_size
    x_batch = corrupted_data[start_index:end_index]
    y_batch = y_train[start_index:end_index]
    model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    # Train the model on the current batch
    model.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    # _, test_accuracy = model.evaluate(x_test, y_test)
    # print("Test Accuracy:", test_accuracy)
# Save the weights of the original model for later use
    prior_weights = model.get_weights()

# Compute the Fisher Information matrix
    def compute_fisher(model, x, num_samples=30):
        fisher_matrix = []
        for i in range(len(model.trainable_weights)):
            fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

        for _ in range(num_samples):
            idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
            with tf.GradientTape() as tape:
                logits = model(x[idx:idx+1])
            gradients = tape.gradient(logits, model.trainable_weights)
            for i in range(len(fisher_matrix)):
                fisher_matrix[i] += tf.square(gradients[i])

        fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
        return fisher_matrix

    fisher_matrix = compute_fisher(model, corrupted_data)

# Define the new model with CrlB regularization
    model_CrlB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3),
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])

# Compile the model with CrlB regularization
    model_CrlB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on Task B with CrlB regularization
# history = model_CrlB.fit(corrupted_data, y_train_onehot, batch_size=128, epochs=10, validation_data=(x_test, y_test_onehot))
# print(history)
# Train the model on each batch separately
# for i in range(n_batches):
#     start_index = i * batch_size
#     end_index = (i + 1) * batch_size
#     x_batch = corrupted_data[start_index:end_index]
#     y_batch = y_train[start_index:end_index]

    # Train the model on the current batch
    model_CrlB.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)
# # Evaluate the model on the test set
# _, test_accuracy = model.evaluate(x_test, y_test_onehot, verbose=0)
# print("Test Accuracy:", test_accuracy)

Epoch 1/10
313/313 [==============================] - 5s 7ms/step - loss: 4.5234 - accuracy: 0.0176
Epoch 2/10
313/313 [==============================] - 2s 6ms/step - loss: 4.1218 - accuracy: 0.0629
Epoch 3/10
313/313 [==============================] - 2s 5ms/step - loss: 3.7856 - accuracy: 0.1174
Epoch 4/10
313/313 [==============================] - 2s 5ms/step - loss: 3.4622 - accuracy: 0.1713
Epoch 5/10
313/313 [==============================] - 2s 5ms/step - loss: 3.1845 - accuracy: 0.2172
Epoch 6/10
313/313 [==============================] - 2s 6ms/step - loss: 2.8854 - accuracy: 0.2747
Epoch 7/10
313/313 [==============================] - 2s 6ms/step - loss: 2.5887 - accuracy: 0.3363
Epoch 8/10
313/313 [==============================] - 2s 6ms/step - loss: 2.2668 - accuracy: 0.4051
Epoch 9/10
313/313 [==============================] - 2s 5ms/step - loss: 2.0087 - accuracy: 0.4640
Epoch 10/10
313/313 [==============================] - 2s 5ms/step - loss: 1.7300 - accuracy: 0.5232
Epoch 1/10
313/313 [==============================] - 8s 9ms/step - loss: 4.3480 - accuracy: 0.0383
Epoch 2/10
313/313 [==============================] - 2s 8ms/step - loss: 3.9164 - accuracy: 0.0951
Epoch 3/10
313/313 [==============================] - 2s 8ms/step - loss: 3.5710 - accuracy: 0.1515
Epoch 4/10
313/313 [==============================] - 2s 8ms/step - loss: 3.2102 - accuracy: 0.2172
Epoch 5/10
313/313 [==============================] - 3s 8ms/step - loss: 2.7928 - accuracy: 0.2926
Epoch 6/10
313/313 [==============================] - 3s 9ms/step - loss: 2.3545 - accuracy: 0.3878
Epoch 7/10
313/313 [==============================] - 2s 8ms/step - loss: 1.8786 - accuracy: 0.4907
Epoch 8/10
313/313 [==============================] - 3s 8ms/step - loss: 1.4159 - accuracy: 0.6034
Epoch 9/10
313/313 [==============================] - 2s 8ms/step - loss: 1.0383 - accuracy: 0.7016
Epoch 10/10
313/313 [==============================] - 3s 9ms/step - loss: 0.7545 - accuracy: 0.7775
313/313 [==============================] - 1s 3ms/step - loss: 3.6814 - accuracy: 0.2210
Test Accuracy: 0.22100000083446503
Epoch 1/10
313/313 [==============================] - 4s 6ms/step - loss: 3.4271 - accuracy: 0.1963
Epoch 2/10
313/313 [==============================] - 2s 6ms/step - loss: 3.0280 - accuracy: 0.2592
Epoch 3/10
313/313 [==============================] - 2s 5ms/step - loss: 2.6962 - accuracy: 0.3184
Epoch 4/10
313/313 [==============================] - 2s 6ms/step - loss: 2.3704 - accuracy: 0.3869
Epoch 5/10
313/313 [==============================] - 2s 7ms/step - loss: 2.0338 - accuracy: 0.4557
Epoch 6/10
313/313 [==============================] - 2s 5ms/step - loss: 1.7141 - accuracy: 0.5331
Epoch 7/10
313/313 [==============================] - 2s 6ms/step - loss: 1.4549 - accuracy: 0.5905
Epoch 8/10
313/313 [==============================] - 2s 6ms/step - loss: 1.2116 - accuracy: 0.6510
Epoch 9/10
313/313 [==============================] - 2s 6ms/step - loss: 1.0189 - accuracy: 0.7063
Epoch 10/10
313/313 [==============================] - 2s 5ms/step - loss: 0.8752 - accuracy: 0.7425
Epoch 1/10
313/313 [==============================] - 8s 8ms/step - loss: 4.3677 - accuracy: 0.0394
Epoch 2/10
313/313 [==============================] - 2s 8ms/step - loss: 3.8990 - accuracy: 0.1013
Epoch 3/10
313/313 [==============================] - 2s 8ms/step - loss: 3.4891 - accuracy: 0.1728
Epoch 4/10
313/313 [==============================] - 3s 9ms/step - loss: 3.0542 - accuracy: 0.2421
Epoch 5/10
313/313 [==============================] - 2s 8ms/step - loss: 2.5950 - accuracy: 0.3406
Epoch 6/10
313/313 [==============================] - 2s 8ms/step - loss: 2.1224 - accuracy: 0.4427
Epoch 7/10
313/313 [==============================] - 2s 8ms/step - loss: 1.6506 - accuracy: 0.5536
Epoch 8/10
313/313 [==============================] - 2s 8ms/step - loss: 1.2284 - accuracy: 0.6498
Epoch 9/10
313/313 [==============================] - 3s 9ms/step - loss: 0.8861 - accuracy: 0.7422
Epoch 10/10
313/313 [==============================] - 2s 8ms/step - loss: 0.7031 - accuracy: 0.7972
313/313 [==============================] - 1s 3ms/step - loss: 4.2494 - accuracy: 0.2538
Test Accuracy: 0.25380000472068787
Epoch 1/10
313/313 [==============================] - 4s 7ms/step - loss: 3.4352 - accuracy: 0.2008
Epoch 2/10
313/313 [==============================] - 2s 5ms/step - loss: 2.9149 - accuracy: 0.2815
Epoch 3/10
313/313 [==============================] - 2s 5ms/step - loss: 2.5490 - accuracy: 0.3493
Epoch 4/10
313/313 [==============================] - 2s 5ms/step - loss: 2.2241 - accuracy: 0.4100
Epoch 5/10
313/313 [==============================] - 2s 5ms/step - loss: 1.8662 - accuracy: 0.4930
Epoch 6/10
313/313 [==============================] - 2s 5ms/step - loss: 1.5493 - accuracy: 0.5680
Epoch 7/10
313/313 [==============================] - 2s 6ms/step - loss: 1.2717 - accuracy: 0.6370
Epoch 8/10
313/313 [==============================] - 2s 6ms/step - loss: 1.0663 - accuracy: 0.6868
Epoch 9/10
313/313 [==============================] - 2s 5ms/step - loss: 0.8749 - accuracy: 0.7395
Epoch 10/10
313/313 [==============================] - 2s 5ms/step - loss: 0.7601 - accuracy: 0.7650
Epoch 1/10
313/313 [==============================] - 9s 8ms/step - loss: 4.4088 - accuracy: 0.0302
Epoch 2/10
313/313 [==============================] - 2s 8ms/step - loss: 3.9397 - accuracy: 0.0890
Epoch 3/10
313/313 [==============================] - 2s 8ms/step - loss: 3.6488 - accuracy: 0.1393
Epoch 4/10
313/313 [==============================] - 2s 8ms/step - loss: 3.3188 - accuracy: 0.2022
Epoch 5/10
313/313 [==============================] - 3s 9ms/step - loss: 3.0032 - accuracy: 0.2581
Epoch 6/10
313/313 [==============================] - 3s 8ms/step - loss: 2.6879 - accuracy: 0.3168
Epoch 7/10
313/313 [==============================] - 2s 8ms/step - loss: 2.3172 - accuracy: 0.3927
Epoch 8/10
313/313 [==============================] - 2s 8ms/step - loss: 1.9655 - accuracy: 0.4752
Epoch 9/10
313/313 [==============================] - 2s 8ms/step - loss: 1.6217 - accuracy: 0.5530
Epoch 10/10
313/313 [==============================] - 3s 9ms/step - loss: 1.2792 - accuracy: 0.6353
313/313 [==============================] - 1s 3ms/step - loss: 4.0531 - accuracy: 0.2742
Test Accuracy: 0.2741999924182892
Epoch 1/10
313/313 [==============================] - 4s 6ms/step - loss: 3.3757 - accuracy: 0.2157
Epoch 2/10
313/313 [==============================] - 2s 6ms/step - loss: 2.8713 - accuracy: 0.2893
Epoch 3/10
313/313 [==============================] - 2s 5ms/step - loss: 2.5024 - accuracy: 0.3618
Epoch 4/10
313/313 [==============================] - 2s 6ms/step - loss: 2.1630 - accuracy: 0.4370
Epoch 5/10
313/313 [==============================] - 2s 7ms/step - loss: 1.8108 - accuracy: 0.5085
Epoch 6/10
313/313 [==============================] - 2s 6ms/step - loss: 1.4990 - accuracy: 0.5819
Epoch 7/10
313/313 [==============================] - 2s 5ms/step - loss: 1.2026 - accuracy: 0.6567
Epoch 8/10
313/313 [==============================] - 2s 6ms/step - loss: 1.0236 - accuracy: 0.7003
Epoch 9/10
313/313 [==============================] - 2s 5ms/step - loss: 0.8112 - accuracy: 0.7530
Epoch 10/10
313/313 [==============================] - 2s 6ms/step - loss: 0.7084 - accuracy: 0.7873
Epoch 1/10
313/313 [==============================] - 7s 8ms/step - loss: 4.3331 - accuracy: 0.0388
Epoch 2/10
313/313 [==============================] - 2s 8ms/step - loss: 3.8451 - accuracy: 0.1066
Epoch 3/10
313/313 [==============================] - 3s 9ms/step - loss: 3.4626 - accuracy: 0.1752
Epoch 4/10
313/313 [==============================] - 2s 8ms/step - loss: 3.0999 - accuracy: 0.2418
Epoch 5/10
313/313 [==============================] - 2s 7ms/step - loss: 2.7088 - accuracy: 0.3164
Epoch 6/10
313/313 [==============================] - 2s 8ms/step - loss: 2.2831 - accuracy: 0.4046
Epoch 7/10
313/313 [==============================] - 2s 8ms/step - loss: 1.8397 - accuracy: 0.5038
Epoch 8/10
313/313 [==============================] - 3s 9ms/step - loss: 1.4147 - accuracy: 0.6058
Epoch 9/10
313/313 [==============================] - 2s 8ms/step - loss: 1.0872 - accuracy: 0.6856
Epoch 10/10
313/313 [==============================] - 2s 8ms/step - loss: 0.8191 - accuracy: 0.7573
313/313 [==============================] - 1s 3ms/step - loss: 4.0963 - accuracy: 0.2895
Test Accuracy: 0.28949999809265137
Epoch 1/10
313/313 [==============================] - 5s 6ms/step - loss: 3.3796 - accuracy: 0.2257
Epoch 2/10
313/313 [==============================] - 2s 6ms/step - loss: 2.8512 - accuracy: 0.2994
Epoch 3/10
313/313 [==============================] - 2s 5ms/step - loss: 2.5247 - accuracy: 0.3562
Epoch 4/10
313/313 [==============================] - 2s 6ms/step - loss: 2.1824 - accuracy: 0.4254
Epoch 5/10
313/313 [==============================] - 2s 6ms/step - loss: 1.8612 - accuracy: 0.4966
Epoch 6/10
313/313 [==============================] - 2s 6ms/step - loss: 1.5395 - accuracy: 0.5698
Epoch 7/10
313/313 [==============================] - 2s 6ms/step - loss: 1.2532 - accuracy: 0.6402
Epoch 8/10
313/313 [==============================] - 2s 6ms/step - loss: 1.0205 - accuracy: 0.6996
Epoch 9/10
313/313 [==============================] - 2s 6ms/step - loss: 0.8554 - accuracy: 0.7434
Epoch 10/10
313/313 [==============================] - 2s 6ms/step - loss: 0.7322 - accuracy: 0.7747
Epoch 1/10
313/313 [==============================] - 8s 8ms/step - loss: 4.3682 - accuracy: 0.0367
Epoch 2/10
313/313 [==============================] - 2s 8ms/step - loss: 3.9230 - accuracy: 0.0972
Epoch 3/10
313/313 [==============================] - 2s 8ms/step - loss: 3.5559 - accuracy: 0.1527
Epoch 4/10
313/313 [==============================] - 2s 8ms/step - loss: 3.1974 - accuracy: 0.2159
Epoch 5/10
313/313 [==============================] - 3s 9ms/step - loss: 2.8251 - accuracy: 0.2899
Epoch 6/10
313/313 [==============================] - 2s 8ms/step - loss: 2.3989 - accuracy: 0.3830
Epoch 7/10
313/313 [==============================] - 2s 8ms/step - loss: 1.9440 - accuracy: 0.4815
Epoch 8/10
313/313 [==============================] - 2s 8ms/step - loss: 1.5326 - accuracy: 0.5772
Epoch 9/10
313/313 [==============================] - 2s 8ms/step - loss: 1.1628 - accuracy: 0.6669
Epoch 10/10
313/313 [==============================] - 3s 9ms/step - loss: 0.9224 - accuracy: 0.7385
313/313 [==============================] - 1s 3ms/step - loss: 4.0392 - accuracy: 0.2977
Test Accuracy: 0.2976999878883362

#### Batches 4

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar100
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers

# Load the CIFAR-100 dataset
(x_train, y_train), (x_test, y_test) = cifar100.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 0.1  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = x_train + tf.random.normal(shape=x_train.shape, mean=0.0, stddev=corruption_level, dtype=tf.float32)
corrupted_data = tf.clip_by_value(corrupted_data, 0.0, 1.0)

# Convert the labels to one-hot encoding
num_classes = 100
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 2 batches
n_batches = 4
batch_size = x_train.shape[0] // n_batches

# Define the CrlB regularizer
class CrlBRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Define the original CIFAR-10 model
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu'),
    layers.Dropout(0.25),
    Dense(num_classes, activation='softmax')
])

# Compile the model
# model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the original model on Task A
# model.fit(corrupted_data, y_train_onehot, batch_size=128, epochs=10, validation_data=(x_test, y_test_onehot))

# Train the model on each batch separately
for i in range(n_batches):
    start_index = i * batch_size
    end_index = (i + 1) * batch_size
    x_batch = corrupted_data[start_index:end_index]
    y_batch = y_train[start_index:end_index]
    model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    # Train the model on the current batch
    model.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    # _, test_accuracy = model.evaluate(x_test, y_test)
    # print("Test Accuracy:", test_accuracy)
# Save the weights of the original model for later use
    prior_weights = model.get_weights()

# Compute the Fisher Information matrix
    def compute_fisher(model, x, num_samples=30):
        fisher_matrix = []
        for i in range(len(model.trainable_weights)):
            fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

        for _ in range(num_samples):
            idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
            with tf.GradientTape() as tape:
                logits = model(x[idx:idx+1])
            gradients = tape.gradient(logits, model.trainable_weights)
            for i in range(len(fisher_matrix)):
                fisher_matrix[i] += tf.square(gradients[i])

        fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
        return fisher_matrix

    fisher_matrix = compute_fisher(model, corrupted_data)

# Define the new model with CrlB regularization
    model_CrlB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3),
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])

# Compile the model with CrlB regularization
    model_CrlB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on Task B with CrlB regularization
# history = model_CrlB.fit(corrupted_data, y_train_onehot, batch_size=128, epochs=10, validation_data=(x_test, y_test_onehot))
# print(history)
# Train the model on each batch separately
# for i in range(n_batches):
#     start_index = i * batch_size
#     end_index = (i + 1) * batch_size
#     x_batch = corrupted_data[start_index:end_index]
#     y_batch = y_train[start_index:end_index]

    # Train the model on the current batch
    model_CrlB.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)
# # Evaluate the model on the test set
# _, test_accuracy = model.evaluate(x_test, y_test_onehot, verbose=0)
# print("Test Accuracy:", test_accuracy)

Epoch 1/10
391/391 [==============================] - 5s 7ms/step - loss: 4.3582 - accuracy: 0.0366
Epoch 2/10
391/391 [==============================] - 2s 6ms/step - loss: 3.9217 - accuracy: 0.0918
Epoch 3/10
391/391 [==============================] - 2s 5ms/step - loss: 3.5915 - accuracy: 0.1494
Epoch 4/10
391/391 [==============================] - 2s 5ms/step - loss: 3.3023 - accuracy: 0.1985
Epoch 5/10
391/391 [==============================] - 2s 5ms/step - loss: 3.0149 - accuracy: 0.2549
Epoch 6/10
391/391 [==============================] - 2s 6ms/step - loss: 2.7548 - accuracy: 0.3042
Epoch 7/10
391/391 [==============================] - 2s 6ms/step - loss: 2.4974 - accuracy: 0.3473
Epoch 8/10
391/391 [==============================] - 2s 6ms/step - loss: 2.2347 - accuracy: 0.4135
Epoch 9/10
391/391 [==============================] - 2s 5ms/step - loss: 1.9645 - accuracy: 0.4666
Epoch 10/10
391/391 [==============================] - 2s 5ms/step - loss: 1.7206 - accuracy: 0.5219
Epoch 1/10
391/391 [==============================] - 9s 8ms/step - loss: 4.3296 - accuracy: 0.0380
Epoch 2/10
391/391 [==============================] - 3s 8ms/step - loss: 3.7439 - accuracy: 0.1218
Epoch 3/10
391/391 [==============================] - 3s 8ms/step - loss: 3.3169 - accuracy: 0.1981
Epoch 4/10
391/391 [==============================] - 3s 8ms/step - loss: 2.9110 - accuracy: 0.2718
Epoch 5/10
391/391 [==============================] - 3s 8ms/step - loss: 2.4914 - accuracy: 0.3590
Epoch 6/10
391/391 [==============================] - 3s 8ms/step - loss: 2.0711 - accuracy: 0.4446
Epoch 7/10
391/391 [==============================] - 3s 8ms/step - loss: 1.6301 - accuracy: 0.5484
Epoch 8/10
391/391 [==============================] - 3s 8ms/step - loss: 1.2351 - accuracy: 0.6502
Epoch 9/10
391/391 [==============================] - 3s 8ms/step - loss: 0.9253 - accuracy: 0.7301
Epoch 10/10
391/391 [==============================] - 3s 8ms/step - loss: 0.7350 - accuracy: 0.7787
313/313 [==============================] - 1s 3ms/step - loss: 3.4760 - accuracy: 0.2480
Test Accuracy: 0.24799999594688416
Epoch 1/10
391/391 [==============================] - 4s 6ms/step - loss: 3.3270 - accuracy: 0.2150
Epoch 2/10
391/391 [==============================] - 2s 6ms/step - loss: 2.9051 - accuracy: 0.2816
Epoch 3/10
391/391 [==============================] - 2s 6ms/step - loss: 2.5771 - accuracy: 0.3414
Epoch 4/10
391/391 [==============================] - 2s 5ms/step - loss: 2.2581 - accuracy: 0.4070
Epoch 5/10
391/391 [==============================] - 2s 5ms/step - loss: 1.9353 - accuracy: 0.4778
Epoch 6/10
391/391 [==============================] - 2s 5ms/step - loss: 1.6080 - accuracy: 0.5597
Epoch 7/10
391/391 [==============================] - 2s 5ms/step - loss: 1.3608 - accuracy: 0.6160
Epoch 8/10
391/391 [==============================] - 3s 7ms/step - loss: 1.1219 - accuracy: 0.6770
Epoch 9/10
391/391 [==============================] - 2s 6ms/step - loss: 0.9735 - accuracy: 0.7184
Epoch 10/10
391/391 [==============================] - 2s 5ms/step - loss: 0.8160 - accuracy: 0.7606
Epoch 1/10
391/391 [==============================] - 8s 9ms/step - loss: 4.3637 - accuracy: 0.0350
Epoch 2/10
391/391 [==============================] - 3s 8ms/step - loss: 3.8324 - accuracy: 0.1094
Epoch 3/10
391/391 [==============================] - 3s 8ms/step - loss: 3.4095 - accuracy: 0.1867
Epoch 4/10
391/391 [==============================] - 3s 8ms/step - loss: 3.0016 - accuracy: 0.2648
Epoch 5/10
391/391 [==============================] - 3s 9ms/step - loss: 2.5822 - accuracy: 0.3439
Epoch 6/10
391/391 [==============================] - 3s 8ms/step - loss: 2.1177 - accuracy: 0.4383
Epoch 7/10
391/391 [==============================] - 3s 7ms/step - loss: 1.6963 - accuracy: 0.5439
Epoch 8/10
391/391 [==============================] - 3s 8ms/step - loss: 1.2972 - accuracy: 0.6311
Epoch 9/10
391/391 [==============================] - 3s 9ms/step - loss: 1.0002 - accuracy: 0.7109
Epoch 10/10
391/391 [==============================] - 3s 8ms/step - loss: 0.7903 - accuracy: 0.7660
313/313 [==============================] - 1s 3ms/step - loss: 3.9550 - accuracy: 0.2822
Test Accuracy: 0.28220000863075256
Epoch 1/10
391/391 [==============================] - 4s 6ms/step - loss: 3.2828 - accuracy: 0.2306
Epoch 2/10
391/391 [==============================] - 2s 5ms/step - loss: 2.7785 - accuracy: 0.3072
Epoch 3/10
391/391 [==============================] - 3s 7ms/step - loss: 2.4240 - accuracy: 0.3806
Epoch 4/10
391/391 [==============================] - 2s 6ms/step - loss: 2.0764 - accuracy: 0.4537
Epoch 5/10
391/391 [==============================] - 2s 5ms/step - loss: 1.7403 - accuracy: 0.5266
Epoch 6/10
391/391 [==============================] - 2s 5ms/step - loss: 1.4404 - accuracy: 0.5904
Epoch 7/10
391/391 [==============================] - 2s 5ms/step - loss: 1.1807 - accuracy: 0.6614
Epoch 8/10
391/391 [==============================] - 2s 6ms/step - loss: 0.9778 - accuracy: 0.7093
Epoch 9/10
391/391 [==============================] - 3s 6ms/step - loss: 0.8258 - accuracy: 0.7538
Epoch 10/10
391/391 [==============================] - 2s 5ms/step - loss: 0.7064 - accuracy: 0.7882
Epoch 1/10
391/391 [==============================] - 8s 8ms/step - loss: 4.2668 - accuracy: 0.0466
Epoch 2/10
391/391 [==============================] - 3s 8ms/step - loss: 3.7527 - accuracy: 0.1217
Epoch 3/10
391/391 [==============================] - 3s 8ms/step - loss: 3.3193 - accuracy: 0.1974
Epoch 4/10
391/391 [==============================] - 3s 8ms/step - loss: 2.9600 - accuracy: 0.2618
Epoch 5/10
391/391 [==============================] - 3s 8ms/step - loss: 2.5955 - accuracy: 0.3338
Epoch 6/10
391/391 [==============================] - 3s 8ms/step - loss: 2.2513 - accuracy: 0.4038
Epoch 7/10
391/391 [==============================] - 3s 8ms/step - loss: 1.8538 - accuracy: 0.5006
Epoch 8/10
391/391 [==============================] - 3s 8ms/step - loss: 1.5255 - accuracy: 0.5745
Epoch 9/10
391/391 [==============================] - 3s 8ms/step - loss: 1.2038 - accuracy: 0.6529
Epoch 10/10
391/391 [==============================] - 3s 8ms/step - loss: 0.9424 - accuracy: 0.7228
313/313 [==============================] - 1s 4ms/step - loss: 3.9365 - accuracy: 0.2976
Test Accuracy: 0.29760000109672546
Epoch 1/10
391/391 [==============================] - 4s 6ms/step - loss: 3.3192 - accuracy: 0.2249
Epoch 2/10
391/391 [==============================] - 2s 5ms/step - loss: 2.7828 - accuracy: 0.3037
Epoch 3/10
391/391 [==============================] - 2s 5ms/step - loss: 2.4353 - accuracy: 0.3745
Epoch 4/10
391/391 [==============================] - 3s 7ms/step - loss: 2.0793 - accuracy: 0.4555
Epoch 5/10
391/391 [==============================] - 2s 5ms/step - loss: 1.7560 - accuracy: 0.5217
Epoch 6/10
391/391 [==============================] - 2s 6ms/step - loss: 1.4451 - accuracy: 0.5875
Epoch 7/10
391/391 [==============================] - 2s 5ms/step - loss: 1.2100 - accuracy: 0.6556
Epoch 8/10
391/391 [==============================] - 2s 5ms/step - loss: 0.9875 - accuracy: 0.7124
Epoch 9/10
391/391 [==============================] - 2s 6ms/step - loss: 0.8372 - accuracy: 0.7498
Epoch 10/10
391/391 [==============================] - 2s 6ms/step - loss: 0.7075 - accuracy: 0.7893
Epoch 1/10
391/391 [==============================] - 8s 8ms/step - loss: 4.3047 - accuracy: 0.0443
Epoch 2/10
391/391 [==============================] - 3s 9ms/step - loss: 3.7776 - accuracy: 0.1171
Epoch 3/10
391/391 [==============================] - 3s 8ms/step - loss: 3.3513 - accuracy: 0.1902
Epoch 4/10
391/391 [==============================] - 3s 8ms/step - loss: 2.9445 - accuracy: 0.2652
Epoch 5/10
391/391 [==============================] - 3s 8ms/step - loss: 2.5322 - accuracy: 0.3514
Epoch 6/10
391/391 [==============================] - 3s 8ms/step - loss: 2.0585 - accuracy: 0.4501
Epoch 7/10
391/391 [==============================] - 3s 8ms/step - loss: 1.5800 - accuracy: 0.5630
Epoch 8/10
391/391 [==============================] - 3s 8ms/step - loss: 1.1785 - accuracy: 0.6665
Epoch 9/10
391/391 [==============================] - 3s 8ms/step - loss: 0.9014 - accuracy: 0.7374
Epoch 10/10
391/391 [==============================] - 3s 9ms/step - loss: 0.6824 - accuracy: 0.7975
313/313 [==============================] - 2s 4ms/step - loss: 3.6702 - accuracy: 0.3196
Test Accuracy: 0.319599986076355

#### Batches 2

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar100
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers

# Load the CIFAR-100 dataset
(x_train, y_train), (x_test, y_test) = cifar100.load_data()

# Normalize the input data
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.

# Choose a corruption type and level
corruption_name = "speckle_noise"  # Choose a corruption type
corruption_level = 0.1  # Choose a corruption level

# Apply corruption to the training data
corrupted_data = x_train + tf.random.normal(shape=x_train.shape, mean=0.0, stddev=corruption_level, dtype=tf.float32)
corrupted_data = tf.clip_by_value(corrupted_data, 0.0, 1.0)

# Convert the labels to one-hot encoding
num_classes = 100
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

# Split the training data into 2 batches
n_batches = 2
batch_size = x_train.shape[0] // n_batches

# Define the CrlB regularizer
class CrlBRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Define the original CIFAR-10 model
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu'),
    layers.Dropout(0.25),
    Dense(num_classes, activation='softmax')
])

# Compile the model
# model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the original model on Task A
# model.fit(corrupted_data, y_train_onehot, batch_size=128, epochs=10, validation_data=(x_test, y_test_onehot))

# Train the model on each batch separately
for i in range(n_batches):
    start_index = i * batch_size
    end_index = (i + 1) * batch_size
    x_batch = corrupted_data[start_index:end_index]
    y_batch = y_train[start_index:end_index]
    model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
    # Train the model on the current batch
    model.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    # _, test_accuracy = model.evaluate(x_test, y_test)
    # print("Test Accuracy:", test_accuracy)
# Save the weights of the original model for later use
    prior_weights = model.get_weights()

# Compute the Fisher Information matrix
    def compute_fisher(model, x, num_samples=30):
        fisher_matrix = []
        for i in range(len(model.trainable_weights)):
            fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

        for _ in range(num_samples):
            idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
            with tf.GradientTape() as tape:
                logits = model(x[idx:idx+1])
            gradients = tape.gradient(logits, model.trainable_weights)
            for i in range(len(fisher_matrix)):
                fisher_matrix[i] += tf.square(gradients[i])

        fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
        return fisher_matrix

    fisher_matrix = compute_fisher(model, corrupted_data)

# Define the new model with CrlB regularization
    model_CrlB = Sequential([
        Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3),
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(32, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        MaxPooling2D((2, 2)),
        layers.Dropout(0.25),
        Flatten(),
        Dense(512, activation='relu', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
        Dense(num_classes, activation='softmax', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
    ])

# Compile the model with CrlB regularization
    model_CrlB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on Task B with CrlB regularization
# history = model_CrlB.fit(corrupted_data, y_train_onehot, batch_size=128, epochs=10, validation_data=(x_test, y_test_onehot))
# print(history)
# Train the model on each batch separately
# for i in range(n_batches):
#     start_index = i * batch_size
#     end_index = (i + 1) * batch_size
#     x_batch = corrupted_data[start_index:end_index]
#     y_batch = y_train[start_index:end_index]

    # Train the model on the current batch
    model_CrlB.fit(x_batch, y_batch, epochs=10, batch_size=32, verbose=1)

    # Evaluate the model on the test set
    _, test_accuracy = model.evaluate(x_test, y_test)
    print("Test Accuracy:", test_accuracy)
# # Evaluate the model on the test set
# _, test_accuracy = model.evaluate(x_test, y_test_onehot, verbose=0)
# print("Test Accuracy:", test_accuracy)

Epoch 1/10
782/782 [==============================] - 6s 6ms/step - loss: 4.1538 - accuracy: 0.0619
Epoch 2/10
782/782 [==============================] - 5s 6ms/step - loss: 3.6037 - accuracy: 0.1533
Epoch 3/10
782/782 [==============================] - 4s 5ms/step - loss: 3.2181 - accuracy: 0.2176
Epoch 4/10
782/782 [==============================] - 4s 5ms/step - loss: 2.9490 - accuracy: 0.2685
Epoch 5/10
782/782 [==============================] - 5s 6ms/step - loss: 2.7195 - accuracy: 0.3104
Epoch 6/10
782/782 [==============================] - 4s 5ms/step - loss: 2.5308 - accuracy: 0.3488
Epoch 7/10
782/782 [==============================] - 4s 6ms/step - loss: 2.3424 - accuracy: 0.3870
Epoch 8/10
782/782 [==============================] - 5s 6ms/step - loss: 2.1888 - accuracy: 0.4195
Epoch 9/10
782/782 [==============================] - 4s 5ms/step - loss: 2.0291 - accuracy: 0.4570
Epoch 10/10
782/782 [==============================] - 5s 6ms/step - loss: 1.8813 - accuracy: 0.4886
Epoch 1/10
782/782 [==============================] - 11s 8ms/step - loss: 4.1211 - accuracy: 0.0729
Epoch 2/10
782/782 [==============================] - 6s 8ms/step - loss: 3.3845 - accuracy: 0.1896
Epoch 3/10
782/782 [==============================] - 6s 8ms/step - loss: 2.9479 - accuracy: 0.2683
Epoch 4/10
782/782 [==============================] - 6s 8ms/step - loss: 2.5828 - accuracy: 0.3406
Epoch 5/10
782/782 [==============================] - 6s 8ms/step - loss: 2.2466 - accuracy: 0.4158
Epoch 6/10
782/782 [==============================] - 6s 8ms/step - loss: 1.9072 - accuracy: 0.4855
Epoch 7/10
782/782 [==============================] - 6s 8ms/step - loss: 1.5695 - accuracy: 0.5656
Epoch 8/10
782/782 [==============================] - 6s 8ms/step - loss: 1.2975 - accuracy: 0.6369
Epoch 9/10
782/782 [==============================] - 6s 8ms/step - loss: 1.0574 - accuracy: 0.6966
Epoch 10/10
782/782 [==============================] - 6s 8ms/step - loss: 0.8924 - accuracy: 0.7341
313/313 [==============================] - 1s 3ms/step - loss: 2.9497 - accuracy: 0.3125
Test Accuracy: 0.3125
Epoch 1/10
782/782 [==============================] - 7s 6ms/step - loss: 2.9926 - accuracy: 0.2720
Epoch 2/10
782/782 [==============================] - 4s 6ms/step - loss: 2.6851 - accuracy: 0.3268
Epoch 3/10
782/782 [==============================] - 5s 6ms/step - loss: 2.4614 - accuracy: 0.3687
Epoch 4/10
782/782 [==============================] - 4s 5ms/step - loss: 2.2646 - accuracy: 0.4096
Epoch 5/10
782/782 [==============================] - 4s 6ms/step - loss: 2.0695 - accuracy: 0.4495
Epoch 6/10
782/782 [==============================] - 5s 6ms/step - loss: 1.8791 - accuracy: 0.4906
Epoch 7/10
782/782 [==============================] - 4s 5ms/step - loss: 1.7367 - accuracy: 0.5219
Epoch 8/10
782/782 [==============================] - 4s 6ms/step - loss: 1.5781 - accuracy: 0.5585
Epoch 9/10
782/782 [==============================] - 4s 6ms/step - loss: 1.4328 - accuracy: 0.5937
Epoch 10/10
782/782 [==============================] - 4s 5ms/step - loss: 1.3320 - accuracy: 0.6195
Epoch 1/10
782/782 [==============================] - 11s 8ms/step - loss: 4.0916 - accuracy: 0.0723
Epoch 2/10
782/782 [==============================] - 6s 8ms/step - loss: 3.4066 - accuracy: 0.1824
Epoch 3/10
782/782 [==============================] - 6s 8ms/step - loss: 2.9820 - accuracy: 0.2608
Epoch 4/10
782/782 [==============================] - 6s 8ms/step - loss: 2.6697 - accuracy: 0.3243
Epoch 5/10
782/782 [==============================] - 6s 8ms/step - loss: 2.3856 - accuracy: 0.3825
Epoch 6/10
782/782 [==============================] - 6s 8ms/step - loss: 2.1251 - accuracy: 0.4374
Epoch 7/10
782/782 [==============================] - 6s 8ms/step - loss: 1.8662 - accuracy: 0.4963
Epoch 8/10
782/782 [==============================] - 6s 8ms/step - loss: 1.6116 - accuracy: 0.5546
Epoch 9/10
782/782 [==============================] - 6s 8ms/step - loss: 1.3965 - accuracy: 0.6037
Epoch 10/10
782/782 [==============================] - 7s 8ms/step - loss: 1.1989 - accuracy: 0.6545
313/313 [==============================] - 1s 3ms/step - loss: 3.0089 - accuracy: 0.3481
Test Accuracy: 0.3481000065803528

### SVHN

In [ ]:
!wget http://ufldl.stanford.edu/housenumbers/train_32x32.mat
!wget http://ufldl.stanford.edu/housenumbers/test_32x32.mat

--2023-08-03 08:22:27--  http://ufldl.stanford.edu/housenumbers/train_32x32.mat
Resolving ufldl.stanford.edu (ufldl.stanford.edu)... 171.64.68.10
Connecting to ufldl.stanford.edu (ufldl.stanford.edu)|171.64.68.10|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 182040794 (174M) [text/plain]
Saving to: ‘train_32x32.mat’

train_32x32.mat     100%[===================>] 173.61M  54.0MB/s    in 3.9s

2023-08-03 08:22:31 (44.2 MB/s) - ‘train_32x32.mat’ saved [182040794/182040794]

--2023-08-03 08:22:31--  http://ufldl.stanford.edu/housenumbers/test_32x32.mat
Resolving ufldl.stanford.edu (ufldl.stanford.edu)... 171.64.68.10
Connecting to ufldl.stanford.edu (ufldl.stanford.edu)|171.64.68.10|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 64275384 (61M) [text/plain]
Saving to: ‘test_32x32.mat’

test_32x32.mat      100%[===================>]  61.30M  31.7MB/s    in 1.9s

2023-08-03 08:22:33 (31.7 MB/s) - ‘test_32x32.mat’ saved [64275384/64275384]

In [ ]:
import numpy as np
from tensorflow import keras
from sklearn.model_selection import KFold
import scipy.io as sio
from tensorflow.keras.utils import to_categorical
# Load the SVHN dataset
train_data = sio.loadmat("train_32x32.mat")
test_data = sio.loadmat("test_32x32.mat")

# Extract the images and labels from the downloaded data
train_images = np.transpose(train_data['X'], (3, 0, 1, 2))
train_labels = train_data['y']

test_images = np.transpose(test_data['X'], (3, 0, 1, 2))
test_labels = test_data['y']

# Change class labels to range from 0 to 9
train_labels[train_labels == 10] = 0
test_labels[test_labels == 10] = 0

# Perform one-hot encoding on the labels
num_classes = 10
train_labels = to_categorical(train_labels, num_classes)
test_labels = to_categorical(test_labels, num_classes)

# Print the shape of the loaded data
print("Train images shape:", train_images.shape)
print("Train labels shape:", train_labels.shape)
print("Test images shape:", test_images.shape)
print("Test labels shape:", test_labels.shape)

Train images shape: (73257, 32, 32, 3)
Train labels shape: (73257, 10)
Test images shape: (26032, 32, 32, 3)
Test labels shape: (26032, 10)

In [ ]:
x_train  = train_images
y_train = train_labels
x_test = test_images
y_test = test_labels
# Print the shape of the loaded data
print("Train images shape:", x_train.shape)
print("Train labels shape:", y_train.shape)
print("Test images shape:", x_test.shape)
print("Test labels shape:", y_test.shape)

Train images shape: (73257, 32, 32, 3)
Train labels shape: (73257, 10)
Test images shape: (26032, 32, 32, 3)
Test labels shape: (26032, 10)

In [ ]:
import tensorflow as tf
import keras
import numpy as np
from tensorflow.keras.datasets import cifar100
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras import layers
# # Load the CIFAR-100 dataset
# (x_train, y_train), (x_test, y_test) = cifar100.load_data()

# Choose a corruption type and level
# corruption_name = "speckle_noise"  # Choose a corruption type
# corruption_level = 3  # Choose a corruption level

# Apply corruption to the training data
# corrupted_data = np.copy(x_train).astype('float64')
# if corruption_name == "speckle_noise":
#     noise = np.random.randn(*corrupted_data.shape) * corruption_level
#     corrupted_data += noise
#     corrupted_data = np.clip(corrupted_data, 0., 255.)
#     corrupted_data = corrupted_data.astype('uint8')
num_classes=10
# Convert labels to one-hot vectors
y_train_onehot = keras.utils.to_categorical(y_train, num_classes=10)
y_test_onehot = keras.utils.to_categorical(y_test, num_classes=10)

# Define the CrlB regularizer
class CrlBRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Define the original CIFAR-100 model
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu'),
    layers.Dropout(0.25),
    Dense(num_classes, activation='softmax')
])

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the original model on Task A
model.fit(x_train, y_train, batch_size=128, epochs=10, validation_data=(x_test, y_test))

# Save the weights of the original model for later use
prior_weights = model.get_weights()

# Compute the Fisher Information matrix
def compute_fisher(model, x, num_samples=30):
    fisher_matrix = []
    for i in range(len(model.trainable_weights)):
        fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

    for _ in range(num_samples):
        idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
        with tf.GradientTape() as tape:
            logits = model(x[idx:idx+1])
        gradients = tape.gradient(logits, model.trainable_weights)
        for i in range(len(fisher_matrix)):
            fisher_matrix[i] += tf.square(gradients[i])

    fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
    return fisher_matrix

fisher_matrix = compute_fisher(model, x_train)

# Define the new model with CrlB regularization
model_CrlB = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3),
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
    Conv2D(32, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
    Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
    Dense(num_classes, activation='softmax', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
])

# Compile the model with CrlB regularization
model_CrlB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on Task B with CrlB regularization
history = model_CrlB.fit(x_train, y_train, batch_size=128, epochs=10, validation_data=(x_test, y_test))
print(history)
# Evaluate the model on the test set
_, test_accuracy = model.evaluate(x_test, y_test, verbose=0)
print("Test Accuracy:", test_accuracy)

Epoch 1/10
573/573 [==============================] - 14s 18ms/step - loss: 2.3154 - accuracy: 0.4807 - val_loss: 0.7555 - val_accuracy: 0.7718
Epoch 2/10
573/573 [==============================] - 10s 17ms/step - loss: 0.7938 - accuracy: 0.7521 - val_loss: 0.5492 - val_accuracy: 0.8377
Epoch 3/10
573/573 [==============================] - 8s 15ms/step - loss: 0.6448 - accuracy: 0.7985 - val_loss: 0.4885 - val_accuracy: 0.8600
Epoch 4/10
573/573 [==============================] - 10s 17ms/step - loss: 0.5496 - accuracy: 0.8302 - val_loss: 0.4550 - val_accuracy: 0.8702
Epoch 5/10
573/573 [==============================] - 10s 17ms/step - loss: 0.4897 - accuracy: 0.8490 - val_loss: 0.3985 - val_accuracy: 0.8863
Epoch 6/10
573/573 [==============================] - 10s 17ms/step - loss: 0.4308 - accuracy: 0.8681 - val_loss: 0.3685 - val_accuracy: 0.8951
Epoch 7/10
573/573 [==============================] - 10s 17ms/step - loss: 0.3929 - accuracy: 0.8794 - val_loss: 0.3634 - val_accuracy: 0.8943
Epoch 8/10
573/573 [==============================] - 9s 16ms/step - loss: 0.3602 - accuracy: 0.8892 - val_loss: 0.3355 - val_accuracy: 0.9037
Epoch 9/10
573/573 [==============================] - 10s 17ms/step - loss: 0.3336 - accuracy: 0.8978 - val_loss: 0.3378 - val_accuracy: 0.9068
Epoch 10/10
573/573 [==============================] - 9s 17ms/step - loss: 0.3105 - accuracy: 0.9043 - val_loss: 0.3302 - val_accuracy: 0.9086
Epoch 1/10
573/573 [==============================] - 22s 25ms/step - loss: 1.9712 - accuracy: 0.4636 - val_loss: 0.6736 - val_accuracy: 0.8057
Epoch 2/10
573/573 [==============================] - 11s 18ms/step - loss: 0.6206 - accuracy: 0.8111 - val_loss: 0.4462 - val_accuracy: 0.8736
Epoch 3/10
573/573 [==============================] - 11s 19ms/step - loss: 0.4697 - accuracy: 0.8576 - val_loss: 0.3878 - val_accuracy: 0.8907
Epoch 4/10
573/573 [==============================] - 11s 19ms/step - loss: 0.4014 - accuracy: 0.8788 - val_loss: 0.3461 - val_accuracy: 0.9022
Epoch 5/10
573/573 [==============================] - 11s 19ms/step - loss: 0.3448 - accuracy: 0.8954 - val_loss: 0.3265 - val_accuracy: 0.9090
Epoch 6/10
573/573 [==============================] - 11s 19ms/step - loss: 0.3124 - accuracy: 0.9051 - val_loss: 0.3454 - val_accuracy: 0.9052
Epoch 7/10
573/573 [==============================] - 12s 21ms/step - loss: 0.2804 - accuracy: 0.9159 - val_loss: 0.2962 - val_accuracy: 0.9174
Epoch 8/10
573/573 [==============================] - 11s 19ms/step - loss: 0.2572 - accuracy: 0.9219 - val_loss: 0.3119 - val_accuracy: 0.9183
Epoch 9/10
573/573 [==============================] - 12s 20ms/step - loss: 0.2344 - accuracy: 0.9293 - val_loss: 0.3250 - val_accuracy: 0.9148
Epoch 10/10
573/573 [==============================] - 12s 20ms/step - loss: 0.2117 - accuracy: 0.9353 - val_loss: 0.3094 - val_accuracy: 0.9204
<keras.callbacks.History object at 0x7c3a6ea35450>
Test Accuracy: 0.9086124897003174

### MNIST-C

In [ ]:
import numpy as np
import tensorflow_datasets as tfds
from sklearn.model_selection import KFold
from keras.models import Sequential
from keras.layers import Dense, Flatten

# Load the MNIST-C dataset
dataset = tfds.load('mnist_corrupted', split='train')
data = list(dataset.as_numpy_iterator())
images = np.array([example['image'] for example in data])
labels = np.array([example['label'] for example in data])

Downloading and preparing dataset 235.23 MiB (download: 235.23 MiB, generated: Unknown size, total: 235.23 MiB) to /root/tensorflow_datasets/mnist_corrupted/identity/1.0.0...

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

Generating splits...:   0%|          | 0/2 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/60000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/mnist_corrupted/identity/1.0.0.incomplete3WD4J1/mnist_corrupted-train.tfre…

Generating test examples...:   0%|          | 0/10000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/mnist_corrupted/identity/1.0.0.incomplete3WD4J1/mnist_corrupted-test.tfrec…

Dataset mnist_corrupted downloaded and prepared to /root/tensorflow_datasets/mnist_corrupted/identity/1.0.0. Subsequent calls will reuse this data.

In [ ]:
import tensorflow_datasets as tfds
import numpy as np
from tensorflow.keras.utils import to_categorical

# Load MNIST-C dataset
dataset, info = tfds.load('mnist_corrupted', split='train+test', with_info=True)

# Extract x and y from the dataset
data = list(dataset)
x_data = np.array([item['image'] for item in data])
y_data = np.array([item['label'] for item in data])

# Normalize pixel values to range [0, 1]
x_data = x_data.astype('float32') / 255.0

# Convert integer labels to one-hot encoded vectors
y_data = to_categorical(y_data, num_classes=10)

# Split the data into training and test sets
x_train, x_test = x_data[:50000], x_data[50000:]
y_train, y_test = y_data[:50000], y_data[50000:]

In [ ]:
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(50000, 28, 28, 1) (50000, 10)
(20000, 28, 28, 1) (20000, 10)

In [ ]:
# from sklearn.model_selection import train_test_split
# # Split the data into train and test sets
# test_size = 0.2
# x_train, x_test, y_train, y_test = train_test_split(images, labels, test_size=test_size, random_state=42)

In [ ]:
import tensorflow as tf
import keras
import numpy as np
from tensorflow.keras.datasets import cifar100
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras import layers
# # Load the CIFAR-100 dataset
# (x_train, y_train), (x_test, y_test) = cifar100.load_data()

# Choose a corruption type and level
# corruption_name = "speckle_noise"  # Choose a corruption type
# corruption_level = 3  # Choose a corruption level

# Apply corruption to the training data
# corrupted_data = np.copy(x_train).astype('float64')
# if corruption_name == "speckle_noise":
#     noise = np.random.randn(*corrupted_data.shape) * corruption_level
#     corrupted_data += noise
#     corrupted_data = np.clip(corrupted_data, 0., 255.)
#     corrupted_data = corrupted_data.astype('uint8')
num_classes=10
# Convert labels to one-hot vectors
# y_train_onehot = keras.utils.to_categorical(y_train, num_classes=10)
# y_test_onehot = keras.utils.to_categorical(y_test, num_classes=10)

# Define the CrlB regularizer
class CrlBRegularizer(tf.keras.regularizers.Regularizer):
    def __init__(self, model, fisher_matrix, prior_weights, lambda_):
        self.model = model
        self.fisher_matrix = fisher_matrix
        self.prior_weights = prior_weights
        self.lambda_ = lambda_

    def __call__(self, x):
        regularization = 0.
        for i, weight in enumerate(self.model.trainable_weights):
            regularization += tf.reduce_sum(self.fisher_matrix[i] * tf.square(weight - self.prior_weights[i]))
        return self.lambda_ * regularization


# Define the original MNIST-C
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(28, 28, 1)),
    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu'),
    layers.Dropout(0.25),
    Dense(num_classes, activation='softmax')
])

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the original model on Task A
model.fit(x_train, y_train, batch_size=128, epochs=10, validation_data=(x_test, y_test))

# Save the weights of the original model for later use
prior_weights = model.get_weights()

# Compute the Fisher Information matrix
def compute_fisher(model, x, num_samples=30):
    fisher_matrix = []
    for i in range(len(model.trainable_weights)):
        fisher_matrix.append(tf.zeros_like(model.trainable_weights[i]))

    for _ in range(num_samples):
        idx = tf.random.uniform(shape=(), maxval=x.shape[0], dtype=tf.int32)
        with tf.GradientTape() as tape:
            logits = model(x[idx:idx+1])
        gradients = tape.gradient(logits, model.trainable_weights)
        for i in range(len(fisher_matrix)):
            fisher_matrix[i] += tf.square(gradients[i])

    fisher_matrix = [fisher / num_samples for fisher in fisher_matrix]
    return fisher_matrix

fisher_matrix = compute_fisher(model, x_train)

# Define the new model with CrlB regularization
model_CrlB = Sequential([
    Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(28, 28, 1),
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
    Conv2D(32, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
    Conv2D(64, (3, 3), activation='relu', padding='same',
           kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
    MaxPooling2D((2, 2)),
    layers.Dropout(0.25),
    Flatten(),
    Dense(512, activation='relu', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1)),
    Dense(num_classes, activation='softmax', kernel_regularizer=CrlBRegularizer(model, fisher_matrix, prior_weights, lambda_=0.1))
])

# Compile the model with CrlB regularization
model_CrlB.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model on Task B with CrlB regularization
history = model_CrlB.fit(x_train, y_train, batch_size=128, epochs=10, validation_data=(x_test, y_test))
print(history)
# Evaluate the model on the test set
_, test_accuracy = model.evaluate(x_test, y_test, verbose=0)
print("Test Accuracy:", test_accuracy)

Epoch 1/10
391/391 [==============================] - 12s 22ms/step - loss: 0.1994 - accuracy: 0.9369 - val_loss: 0.0614 - val_accuracy: 0.9809
Epoch 2/10
391/391 [==============================] - 6s 15ms/step - loss: 0.0579 - accuracy: 0.9821 - val_loss: 0.0409 - val_accuracy: 0.9870
Epoch 3/10
391/391 [==============================] - 6s 16ms/step - loss: 0.0390 - accuracy: 0.9881 - val_loss: 0.0348 - val_accuracy: 0.9890
Epoch 4/10
391/391 [==============================] - 6s 15ms/step - loss: 0.0320 - accuracy: 0.9895 - val_loss: 0.0318 - val_accuracy: 0.9902
Epoch 5/10
391/391 [==============================] - 6s 16ms/step - loss: 0.0263 - accuracy: 0.9916 - val_loss: 0.0357 - val_accuracy: 0.9895
Epoch 6/10
391/391 [==============================] - 5s 14ms/step - loss: 0.0216 - accuracy: 0.9929 - val_loss: 0.0311 - val_accuracy: 0.9905
Epoch 7/10
391/391 [==============================] - 6s 14ms/step - loss: 0.0202 - accuracy: 0.9931 - val_loss: 0.0266 - val_accuracy: 0.9913
Epoch 8/10
391/391 [==============================] - 6s 16ms/step - loss: 0.0178 - accuracy: 0.9939 - val_loss: 0.0294 - val_accuracy: 0.9913
Epoch 9/10
391/391 [==============================] - 5s 14ms/step - loss: 0.0145 - accuracy: 0.9953 - val_loss: 0.0239 - val_accuracy: 0.9927
Epoch 10/10
391/391 [==============================] - 6s 16ms/step - loss: 0.0154 - accuracy: 0.9949 - val_loss: 0.0245 - val_accuracy: 0.9927
Epoch 1/10
391/391 [==============================] - 20s 30ms/step - loss: 0.1900 - accuracy: 0.9402 - val_loss: 0.0577 - val_accuracy: 0.9812
Epoch 2/10
391/391 [==============================] - 8s 21ms/step - loss: 0.0513 - accuracy: 0.9837 - val_loss: 0.0379 - val_accuracy: 0.9880
Epoch 3/10
391/391 [==============================] - 10s 24ms/step - loss: 0.0362 - accuracy: 0.9886 - val_loss: 0.0312 - val_accuracy: 0.9900
Epoch 4/10
391/391 [==============================] - 9s 23ms/step - loss: 0.0283 - accuracy: 0.9909 - val_loss: 0.0313 - val_accuracy: 0.9899
Epoch 5/10
391/391 [==============================] - 8s 22ms/step - loss: 0.0229 - accuracy: 0.9922 - val_loss: 0.0291 - val_accuracy: 0.9905
Epoch 6/10
391/391 [==============================] - 7s 19ms/step - loss: 0.0183 - accuracy: 0.9942 - val_loss: 0.0276 - val_accuracy: 0.9918
Epoch 7/10
391/391 [==============================] - 7s 17ms/step - loss: 0.0175 - accuracy: 0.9943 - val_loss: 0.0288 - val_accuracy: 0.9920
Epoch 8/10
391/391 [==============================] - 7s 18ms/step - loss: 0.0139 - accuracy: 0.9953 - val_loss: 0.0308 - val_accuracy: 0.9919
Epoch 9/10
391/391 [==============================] - 7s 18ms/step - loss: 0.0138 - accuracy: 0.9955 - val_loss: 0.0258 - val_accuracy: 0.9919
Epoch 10/10
391/391 [==============================] - 7s 17ms/step - loss: 0.0115 - accuracy: 0.9959 - val_loss: 0.0313 - val_accuracy: 0.9917
<keras.callbacks.History object at 0x7f7fc40dcc40>
Test Accuracy: 0.9926999807357788

## IWCV

#### CIFAR10-C

In [ ]:
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical
from skimage.util import random_noise

# Load CIFAR-10 dataset
(X_train, y_train), (X_test, y_test) = cifar10.load_data()

# Normalize the pixel values
X_train = X_train / 255.0
X_test = X_test / 255.0

# Add speckle noise to the training images
X_train = random_noise(X_train, mode='speckle', var=0.1)

# Convert labels to one-hot encoded vectors
y_train = to_categorical(y_train, num_classes=10)
y_test = to_categorical(y_test, num_classes=10)

# Define the number of folds for cross-validation
n_splits = 5

# Initialize importance weights for each sample
sample_weights = np.ones(X_train.shape[0])

# Define the neural network architecture
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dense(10, activation='softmax'))

# Compile the model
model.compile(optimizer=Adam(learning_rate=0.001), loss='categorical_crossentropy', metrics=['accuracy'])

# Perform importance weighted cross-validation
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)
accuracies = []

for train_index, test_index in skf.split(X_train, np.argmax(y_train, axis=1)):
    X_train_fold, X_test_fold = X_train[train_index], X_train[test_index]
    y_train_fold, y_test_fold = y_train[train_index], y_train[test_index]
    weights_train_fold, weights_test_fold = sample_weights[train_index], sample_weights[test_index]

    y_test_fold = np.argmax(y_test_fold, axis=1)
    # Train the model with importance weights
    model.fit(X_train_fold, y_train_fold, epochs=10, batch_size=32, verbose=1, sample_weight=weights_train_fold)

    # Evaluate the model
    y_pred = model.predict(X_test_fold)
    accuracy = accuracy_score(y_test_fold, np.argmax(y_pred, axis=1))
    accuracies.append(accuracy)

    # Update importance weights based on model predictions
    weights_test_fold *= (1.0 / model.predict(X_test_fold)[np.arange(len(X_test_fold)), np.argmax(y_test_fold, axis=0)])

    # Normalize importance weights
    weights_test_fold /= np.mean(weights_test_fold)

    # Update overall importance weights
    sample_weights[test_index] = weights_test_fold

# Calculate and print the average accuracy across all folds
average_accuracy = np.mean(accuracies)
print(f"Average accuracy: {average_accuracy}")

Epoch 1/10
1250/1250 [==============================] - 14s 5ms/step - loss: 1.5468 - accuracy: 0.4408
Epoch 2/10
1250/1250 [==============================] - 7s 5ms/step - loss: 1.1917 - accuracy: 0.5806
Epoch 3/10
1250/1250 [==============================] - 6s 5ms/step - loss: 1.0647 - accuracy: 0.6288
Epoch 4/10
1250/1250 [==============================] - 7s 6ms/step - loss: 0.9708 - accuracy: 0.6597
Epoch 5/10
1250/1250 [==============================] - 6s 5ms/step - loss: 0.8952 - accuracy: 0.6866
Epoch 6/10
1250/1250 [==============================] - 7s 5ms/step - loss: 0.8178 - accuracy: 0.7135
Epoch 7/10
1250/1250 [==============================] - 6s 5ms/step - loss: 0.7487 - accuracy: 0.7364
Epoch 8/10
1250/1250 [==============================] - 5s 4ms/step - loss: 0.6843 - accuracy: 0.7590
Epoch 9/10
1250/1250 [==============================] - 5s 4ms/step - loss: 0.6228 - accuracy: 0.7806
Epoch 10/10
1250/1250 [==============================] - 5s 4ms/step - loss: 0.5625 - accuracy: 0.8026
313/313 [==============================] - 1s 2ms/step
313/313 [==============================] - 1s 2ms/step
Epoch 1/10
1250/1250 [==============================] - 5s 4ms/step - loss: 0.3806 - accuracy: 0.7709
Epoch 2/10
1250/1250 [==============================] - 5s 4ms/step - loss: 0.3321 - accuracy: 0.7861
Epoch 3/10
1250/1250 [==============================] - 4s 4ms/step - loss: 0.2877 - accuracy: 0.8004
Epoch 4/10
1250/1250 [==============================] - 4s 4ms/step - loss: 0.2457 - accuracy: 0.8137
Epoch 5/10
1250/1250 [==============================] - 5s 4ms/step - loss: 0.2054 - accuracy: 0.8283
Epoch 6/10
1250/1250 [==============================] - 4s 4ms/step - loss: 0.1753 - accuracy: 0.8373
Epoch 7/10
1250/1250 [==============================] - 5s 4ms/step - loss: 0.1585 - accuracy: 0.8411
Epoch 8/10
1250/1250 [==============================] - 5s 4ms/step - loss: 0.1292 - accuracy: 0.8530
Epoch 9/10
1250/1250 [==============================] - 4s 4ms/step - loss: 0.1160 - accuracy: 0.8558
Epoch 10/10
1250/1250 [==============================] - 6s 4ms/step - loss: 0.1079 - accuracy: 0.8591
313/313 [==============================] - 1s 2ms/step
313/313 [==============================] - 1s 2ms/step
Epoch 1/10
1250/1250 [==============================] - 5s 4ms/step - loss: 0.0748 - accuracy: 0.7922
Epoch 2/10
1250/1250 [==============================] - 5s 4ms/step - loss: 0.0738 - accuracy: 0.7937
Epoch 3/10
1250/1250 [==============================] - 5s 4ms/step - loss: 0.0650 - accuracy: 0.7940
Epoch 4/10
1250/1250 [==============================] - 5s 4ms/step - loss: 0.0665 - accuracy: 0.7918
Epoch 5/10
1250/1250 [==============================] - 5s 4ms/step - loss: 0.0483 - accuracy: 0.8003
Epoch 6/10
1250/1250 [==============================] - 5s 4ms/step - loss: 0.0632 - accuracy: 0.7909
Epoch 7/10
1250/1250 [==============================] - 5s 4ms/step - loss: 0.0546 - accuracy: 0.7930
Epoch 8/10
1250/1250 [==============================] - 4s 4ms/step - loss: 0.0529 - accuracy: 0.7923
Epoch 9/10
1250/1250 [==============================] - 5s 4ms/step - loss: 0.0545 - accuracy: 0.7899
Epoch 10/10
1250/1250 [==============================] - 4s 4ms/step - loss: 0.0449 - accuracy: 0.7944
313/313 [==============================] - 1s 2ms/step
313/313 [==============================] - 1s 2ms/step
Epoch 1/10
1250/1250 [==============================] - 5s 4ms/step - loss: 0.0566 - accuracy: 0.7310
Epoch 2/10
1250/1250 [==============================] - 4s 4ms/step - loss: 0.0189 - accuracy: 0.7499
Epoch 3/10
1250/1250 [==============================] - 5s 4ms/step - loss: 0.0410 - accuracy: 0.7307
Epoch 4/10
1250/1250 [==============================] - 4s 4ms/step - loss: 0.0329 - accuracy: 0.7308
Epoch 5/10
1250/1250 [==============================] - 4s 4ms/step - loss: 0.0249 - accuracy: 0.7308
Epoch 6/10
1250/1250 [==============================] - 5s 4ms/step - loss: 0.0307 - accuracy: 0.7239
Epoch 7/10
1250/1250 [==============================] - 5s 4ms/step - loss: 0.0243 - accuracy: 0.7243
Epoch 8/10
1250/1250 [==============================] - 5s 4ms/step - loss: 0.0282 - accuracy: 0.7219
Epoch 9/10
1250/1250 [==============================] - 5s 4ms/step - loss: 0.0222 - accuracy: 0.7237
Epoch 10/10
1250/1250 [==============================] - 5s 4ms/step - loss: 0.0233 - accuracy: 0.7186
313/313 [==============================] - 1s 2ms/step
313/313 [==============================] - 1s 2ms/step

<ipython-input-1-44c8c8726a40>:63: RuntimeWarning: divide by zero encountered in true_divide
  weights_test_fold *= (1.0 / model.predict(X_test_fold)[np.arange(len(X_test_fold)), np.argmax(y_test_fold, axis=0)])
<ipython-input-1-44c8c8726a40>:66: RuntimeWarning: invalid value encountered in true_divide
  weights_test_fold /= np.mean(weights_test_fold)

Epoch 1/10
1250/1250 [==============================] - 5s 4ms/step - loss: nan - accuracy: 0.1407
Epoch 2/10
1250/1250 [==============================] - 5s 4ms/step - loss: nan - accuracy: 0.1000
Epoch 3/10
1250/1250 [==============================] - 5s 4ms/step - loss: nan - accuracy: 0.1000
Epoch 4/10
1250/1250 [==============================] - 5s 4ms/step - loss: nan - accuracy: 0.1000
Epoch 5/10
1250/1250 [==============================] - 5s 4ms/step - loss: nan - accuracy: 0.1000
Epoch 6/10
1250/1250 [==============================] - 4s 4ms/step - loss: nan - accuracy: 0.1000
Epoch 7/10
1250/1250 [==============================] - 5s 4ms/step - loss: nan - accuracy: 0.1000
Epoch 8/10
1250/1250 [==============================] - 5s 4ms/step - loss: nan - accuracy: 0.1000
Epoch 9/10
1250/1250 [==============================] - 4s 4ms/step - loss: nan - accuracy: 0.1000
Epoch 10/10
1250/1250 [==============================] - 5s 4ms/step - loss: nan - accuracy: 0.1000
313/313 [==============================] - 1s 2ms/step
313/313 [==============================] - 1s 2ms/step
Average accuracy: 0.6014

#### CIFAR100-C

In [ ]:
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score
from tensorflow.keras.datasets import cifar100
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical
from skimage.util import random_noise

# Load CIFAR-100 dataset
(X_train, y_train), (X_test, y_test) = cifar100.load_data()

# Normalize the pixel values
X_train = X_train / 255.0
X_test = X_test / 255.0

# Add speckle noise to the training images
X_train = random_noise(X_train, mode='speckle', var=0.1)

# Convert labels to one-hot encoded vectors
y_train = to_categorical(y_train, num_classes=100)
y_test = to_categorical(y_test, num_classes=100)

# Define the number of folds for cross-validation
n_splits = 5

# Initialize importance weights for each sample
sample_weights = np.ones(X_train.shape[0])

# Define the neural network architecture
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dense(100, activation='softmax'))

# Compile the model
model.compile(optimizer=Adam(learning_rate=0.001), loss='categorical_crossentropy', metrics=['accuracy'])

# Perform importance-weighted cross-validation
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)
accuracies = []

for train_index, test_index in skf.split(X_train, np.argmax(y_train, axis=1)):
    X_train_fold, X_test_fold = X_train[train_index], X_train[test_index]
    y_train_fold, y_test_fold = y_train[train_index], y_train[test_index]
    weights_train_fold, weights_test_fold = sample_weights[train_index], sample_weights[test_index]

    # Train the model with importance weights
    model.fit(X_train_fold, y_train_fold, epochs=10, batch_size=32, verbose=1, sample_weight=weights_train_fold)

    # Evaluate the model
    y_pred = model.predict(X_test_fold)
    accuracy = accuracy_score(np.argmax(y_test_fold, axis=1), np.argmax(y_pred, axis=1))
    accuracies.append(accuracy)

    # Update importance weights based on model predictions
    # weights_test_fold *= (1.0 / model.predict(X_test_fold).flatten()).repeat(X_test_fold.shape[0])
    # weights_test_fold *= (1.0 / model.predict(X_test_fold)[np.arange(len(X_test_fold)), np.argmax(y_test_fold, axis=0)])
    weights_test_fold *= (1.0 / model.predict(X_test_fold))[np.arange(len(X_test_fold)), np.argmax(y_test_fold, axis=1)]

    # Normalize importance weights
    weights_test_fold /= np.mean(weights_test_fold)

    # Update overall importance weights
    sample_weights[test_index] = weights_test_fold

# Calculate and print the average accuracy across all folds
average_accuracy = np.mean(accuracies)
print(f"Average accuracy: {average_accuracy}")

Epoch 1/10
1250/1250 [==============================] - 13s 5ms/step - loss: 4.0743 - accuracy: 0.0789
Epoch 2/10
1250/1250 [==============================] - 7s 6ms/step - loss: 3.4351 - accuracy: 0.1786
Epoch 3/10
1250/1250 [==============================] - 6s 5ms/step - loss: 3.1609 - accuracy: 0.2284
Epoch 4/10
1250/1250 [==============================] - 7s 6ms/step - loss: 2.9874 - accuracy: 0.2620
Epoch 5/10
1250/1250 [==============================] - 7s 5ms/step - loss: 2.8562 - accuracy: 0.2880
Epoch 6/10
1250/1250 [==============================] - 5s 4ms/step - loss: 2.7562 - accuracy: 0.3059
Epoch 7/10
1250/1250 [==============================] - 5s 4ms/step - loss: 2.6632 - accuracy: 0.3238
Epoch 8/10
1250/1250 [==============================] - 5s 4ms/step - loss: 2.5855 - accuracy: 0.3393
Epoch 9/10
1250/1250 [==============================] - 5s 4ms/step - loss: 2.5183 - accuracy: 0.3534
Epoch 10/10
1250/1250 [==============================] - 5s 4ms/step - loss: 2.4504 - accuracy: 0.3650
313/313 [==============================] - 1s 2ms/step
313/313 [==============================] - 1s 2ms/step
Epoch 1/10
1250/1250 [==============================] - 5s 4ms/step - loss: 6.6145 - accuracy: 0.1736
Epoch 2/10
1250/1250 [==============================] - 5s 4ms/step - loss: 4.6683 - accuracy: 0.1102
Epoch 3/10
1250/1250 [==============================] - 5s 4ms/step - loss: 2.7940 - accuracy: 0.1954
Epoch 4/10
1250/1250 [==============================] - 5s 4ms/step - loss: 2.9399 - accuracy: 0.2218
Epoch 5/10
1250/1250 [==============================] - 5s 4ms/step - loss: 2.3238 - accuracy: 0.2518
Epoch 6/10
1250/1250 [==============================] - 5s 4ms/step - loss: 2.2630 - accuracy: 0.2857
Epoch 7/10
1250/1250 [==============================] - 5s 4ms/step - loss: 2.2083 - accuracy: 0.2742
Epoch 8/10
1250/1250 [==============================] - 5s 4ms/step - loss: 2.0133 - accuracy: 0.3104
Epoch 9/10
1250/1250 [==============================] - 5s 4ms/step - loss: 1.9359 - accuracy: 0.3265
Epoch 10/10
1250/1250 [==============================] - 5s 4ms/step - loss: 1.8500 - accuracy: 0.3458
313/313 [==============================] - 1s 2ms/step
313/313 [==============================] - 1s 2ms/step

<ipython-input-1-98a68a6d0e04>:64: RuntimeWarning: divide by zero encountered in true_divide
  weights_test_fold *= (1.0 / model.predict(X_test_fold))[np.arange(len(X_test_fold)), np.argmax(y_test_fold, axis=1)]

Epoch 1/10
1250/1250 [==============================] - 5s 4ms/step - loss: 7.1770 - accuracy: 0.1780
Epoch 2/10
1250/1250 [==============================] - 5s 4ms/step - loss: 2.1911 - accuracy: 0.1165
Epoch 3/10
1250/1250 [==============================] - 5s 4ms/step - loss: 1.5600 - accuracy: 0.2351
Epoch 4/10
1250/1250 [==============================] - 5s 4ms/step - loss: 1.3659 - accuracy: 0.2806
Epoch 5/10
1250/1250 [==============================] - 5s 4ms/step - loss: 1.2673 - accuracy: 0.3034
Epoch 6/10
1250/1250 [==============================] - 5s 4ms/step - loss: 1.1933 - accuracy: 0.3194
Epoch 7/10
1250/1250 [==============================] - 5s 4ms/step - loss: 1.1323 - accuracy: 0.3331
Epoch 8/10
1250/1250 [==============================] - 5s 4ms/step - loss: 1.0781 - accuracy: 0.3444
Epoch 9/10
1250/1250 [==============================] - 5s 4ms/step - loss: 1.0259 - accuracy: 0.3563
Epoch 10/10
1250/1250 [==============================] - 5s 4ms/step - loss: 0.9706 - accuracy: 0.3655
313/313 [==============================] - 1s 2ms/step
313/313 [==============================] - 1s 2ms/step
Epoch 1/10
1250/1250 [==============================] - 5s 4ms/step - loss: 5.8421 - accuracy: 0.0355
Epoch 2/10
1250/1250 [==============================] - 6s 5ms/step - loss: 3.8551 - accuracy: 0.0192
Epoch 3/10
1250/1250 [==============================] - 5s 4ms/step - loss: 3.6238 - accuracy: 0.0191
Epoch 4/10
1250/1250 [==============================] - 6s 5ms/step - loss: 5.3354 - accuracy: 0.0194
Epoch 5/10
1250/1250 [==============================] - 5s 4ms/step - loss: 2.9736 - accuracy: 0.0156
Epoch 6/10
1250/1250 [==============================] - 6s 4ms/step - loss: 2.8800 - accuracy: 0.0143
Epoch 7/10
1250/1250 [==============================] - 5s 4ms/step - loss: 2.8534 - accuracy: 0.0154
Epoch 8/10
1250/1250 [==============================] - 5s 4ms/step - loss: 2.8801 - accuracy: 0.0139
Epoch 9/10
1250/1250 [==============================] - 6s 5ms/step - loss: 2.7497 - accuracy: 0.0125
Epoch 10/10
1250/1250 [==============================] - 5s 4ms/step - loss: 2.5683 - accuracy: 0.0131
313/313 [==============================] - 1s 2ms/step
313/313 [==============================] - 1s 2ms/step

<ipython-input-1-98a68a6d0e04>:64: RuntimeWarning: divide by zero encountered in true_divide
  weights_test_fold *= (1.0 / model.predict(X_test_fold))[np.arange(len(X_test_fold)), np.argmax(y_test_fold, axis=1)]

Epoch 1/10
1250/1250 [==============================] - 5s 4ms/step - loss: 2.4986 - accuracy: 0.0116
Epoch 2/10
1250/1250 [==============================] - 5s 4ms/step - loss: 2.3014 - accuracy: 0.0110
Epoch 3/10
1250/1250 [==============================] - 5s 4ms/step - loss: 3.1424 - accuracy: 0.0106
Epoch 4/10
1250/1250 [==============================] - 5s 4ms/step - loss: 3.0620 - accuracy: 0.0103
Epoch 5/10
1250/1250 [==============================] - 5s 4ms/step - loss: 3.0106 - accuracy: 0.0107
Epoch 6/10
1250/1250 [==============================] - 5s 4ms/step - loss: 2.9567 - accuracy: 0.0105
Epoch 7/10
1250/1250 [==============================] - 5s 4ms/step - loss: 2.9058 - accuracy: 0.0105
Epoch 8/10
1250/1250 [==============================] - 5s 4ms/step - loss: 2.8513 - accuracy: 0.0102
Epoch 9/10
1250/1250 [==============================] - 4s 4ms/step - loss: 2.8003 - accuracy: 0.0100
Epoch 10/10
1250/1250 [==============================] - 5s 4ms/step - loss: 2.7543 - accuracy: 0.0100
313/313 [==============================] - 1s 2ms/step
313/313 [==============================] - 1s 2ms/step
Average accuracy: 0.1697

## **_____**



---

# For New journal Exp

## IW

### MNIST

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.losses import SparseCategoricalCrossentropy

# Load the dataset
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

# Normalize data
train_images, test_images = train_images / 255.0, test_images / 255.0

# importance weighting
importance_weights = np.where(train_labels == 5, 2.0, 1.0)

# neural network model
model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])


model.compile(optimizer='adam',
              loss=SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

# Train the model using importance weights
model.fit(train_images, train_labels, sample_weight=importance_weights, epochs=10)

# Evaluate the model on the test data
test_loss, test_accuracy = model.evaluate(test_images, test_labels)

# Print the average accuracy
print("Average Accuracy on Test Data:", test_accuracy)

Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
11490434/11490434 [==============================] - 1s 0us/step
Epoch 1/10

/usr/local/lib/python3.10/dist-packages/keras/backend.py:5612: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(

1875/1875 [==============================] - 17s 5ms/step - loss: 0.2897 - accuracy: 0.9226
Epoch 2/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1249 - accuracy: 0.9653
Epoch 3/10
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0859 - accuracy: 0.9758
Epoch 4/10
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0642 - accuracy: 0.9819
Epoch 5/10
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0496 - accuracy: 0.9855
Epoch 6/10
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0389 - accuracy: 0.9883
Epoch 7/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0310 - accuracy: 0.9907
Epoch 8/10
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0262 - accuracy: 0.9921
Epoch 9/10
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0206 - accuracy: 0.9941
Epoch 10/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0177 - accuracy: 0.9948
313/313 [==============================] - 1s 4ms/step - loss: 0.0829 - accuracy: 0.9774
Average Accuracy on Test Data: 0.977400004863739

### PerMutedMNIST

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.losses import SparseCategoricalCrossentropy

# Load the original MNIST dataset
(train_images_source, train_labels_source), (test_images_source, test_labels_source) = mnist.load_data()

# Normalize data
train_images_source, test_images_source = train_images_source / 255.0, test_images_source / 255.0

# Permuted MNIST: Permute the pixels in the images
permute_indices = np.random.permutation(28 * 28)
train_images_target = train_images_source.reshape((-1, 28 * 28))[:, permute_indices].reshape((-1, 28, 28))
test_images_target = test_images_source.reshape((-1, 28 * 28))[:, permute_indices].reshape((-1, 28, 28))

# Assign importance weights: Same weights for all samples in this example
importance_weights_source = np.ones(len(train_labels_source))
importance_weights_target = np.ones(len(train_labels_source))  # Same length as source since we don't have target labels

# Build a simple feedforward neural network model
model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

# Compile the model with the SparseCategoricalCrossentropy loss
model.compile(optimizer='adam',
              loss=SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

# Train the model on the source domain
model.fit(train_images_source, train_labels_source, sample_weight=importance_weights_source, epochs=10)

# Evaluate the model on the permuted MNIST target domain
test_loss, test_accuracy = model.evaluate(test_images_target, test_labels_source)

# Print the average accuracy on the permuted MNIST target domain
print("Average Accuracy on Permuted MNIST (Target Domain):", test_accuracy)

Epoch 1/10
1875/1875 [==============================] - 10s 5ms/step - loss: 0.2585 - accuracy: 0.9255
Epoch 2/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1133 - accuracy: 0.9664
Epoch 3/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0770 - accuracy: 0.9763
Epoch 4/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0585 - accuracy: 0.9821
Epoch 5/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0452 - accuracy: 0.9862
Epoch 6/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0362 - accuracy: 0.9889
Epoch 7/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0296 - accuracy: 0.9908
Epoch 8/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0230 - accuracy: 0.9929
Epoch 9/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0192 - accuracy: 0.9940
Epoch 10/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0162 - accuracy: 0.9950
313/313 [==============================] - 1s 4ms/step - loss: 8.6014 - accuracy: 0.1183
Average Accuracy on Permuted MNIST (Target Domain): 0.11829999834299088

## ERM

### MNIST

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.losses import SparseCategoricalCrossentropy

# Load the MNIST dataset
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

# Normalize the pixel values to be between 0 and 1
train_images, test_images = train_images / 255.0, test_images / 255.0

# Build a simple feedforward neural network model
model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

# Compile the model with the SparseCategoricalCrossentropy loss
model.compile(optimizer='adam',
              loss=SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

# Train the model
model.fit(train_images, train_labels, epochs=10)

# Evaluate the model on the test data
test_loss, test_accuracy = model.evaluate(test_images, test_labels)

# Print the test accuracy
print("Test Accuracy:", test_accuracy)

Epoch 1/10
1875/1875 [==============================] - 9s 4ms/step - loss: 0.2635 - accuracy: 0.9248
Epoch 2/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1163 - accuracy: 0.9659
Epoch 3/10
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0801 - accuracy: 0.9758
Epoch 4/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0589 - accuracy: 0.9819
Epoch 5/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0462 - accuracy: 0.9855
Epoch 6/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0360 - accuracy: 0.9889
Epoch 7/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0294 - accuracy: 0.9909
Epoch 8/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0223 - accuracy: 0.9932
Epoch 9/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0204 - accuracy: 0.9931
Epoch 10/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0160 - accuracy: 0.9951
313/313 [==============================] - 1s 4ms/step - loss: 0.0784 - accuracy: 0.9783
Test Accuracy: 0.9782999753952026

## DIW

### MNIST

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.losses import SparseCategoricalCrossentropy

# Load the MNIST dataset
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

# Normalize the pixel values to be between 0 and 1
train_images, test_images = train_images / 255.0, test_images / 255.0

# Build a simple feedforward neural network model
model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

# Compile the model with the SparseCategoricalCrossentropy loss
model.compile(optimizer='adam',
              loss=SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

# Initial sample weights (uniform, converted to float)
sample_weights = np.ones_like(train_labels, dtype=float)

# Training loop with dynamic importance weighting
for epoch in range(10):
    print(f"Epoch {epoch+1}")
    model.fit(train_images, train_labels, sample_weight=sample_weights, epochs=1, verbose=2)

    # Evaluate on training data
    train_loss, train_accuracy = model.evaluate(train_images, train_labels, verbose=0)
    print("Training Accuracy:", train_accuracy)

    # Predict on training data
    train_predictions = model.predict(train_images)
    # Identify misclassified samples
    misclassified = np.argmax(train_predictions, axis=1) != train_labels
    # Increase weights for misclassified samples
    sample_weights[misclassified] *= 1.5

# Evaluate the final model on the test data
test_loss, test_accuracy = model.evaluate(test_images, test_labels)

# Print the test accuracy
print("Test Accuracy:", test_accuracy)

Epoch 1
1875/1875 - 7s - loss: 0.2585 - accuracy: 0.9262 - 7s/epoch - 4ms/step
Training Accuracy: 0.9622499942779541
1875/1875 [==============================] - 6s 3ms/step
Epoch 2
1875/1875 - 7s - loss: 0.1551 - accuracy: 0.9646 - 7s/epoch - 4ms/step
Training Accuracy: 0.9763833284378052
1875/1875 [==============================] - 5s 3ms/step
Epoch 3
1875/1875 - 7s - loss: 0.1347 - accuracy: 0.9749 - 7s/epoch - 4ms/step
Training Accuracy: 0.9835333228111267
1875/1875 [==============================] - 8s 4ms/step
Epoch 4
1875/1875 - 6s - loss: 0.1253 - accuracy: 0.9798 - 6s/epoch - 3ms/step
Training Accuracy: 0.9844499826431274
1875/1875 [==============================] - 4s 2ms/step
Epoch 5
1875/1875 - 7s - loss: 0.1136 - accuracy: 0.9833 - 7s/epoch - 4ms/step
Training Accuracy: 0.9887333512306213
1875/1875 [==============================] - 5s 2ms/step
Epoch 6
1875/1875 - 6s - loss: 0.0994 - accuracy: 0.9861 - 6s/epoch - 3ms/step
Training Accuracy: 0.9924333095550537
1875/1875 [==============================] - 4s 2ms/step
Epoch 7
1875/1875 - 7s - loss: 0.0879 - accuracy: 0.9879 - 7s/epoch - 4ms/step
Training Accuracy: 0.9924499988555908
1875/1875 [==============================] - 5s 3ms/step
Epoch 8
1875/1875 - 6s - loss: 0.0761 - accuracy: 0.9902 - 6s/epoch - 3ms/step
Training Accuracy: 0.9921333193778992
1875/1875 [==============================] - 5s 2ms/step
Epoch 9
1875/1875 - 7s - loss: 0.0631 - accuracy: 0.9914 - 7s/epoch - 4ms/step
Training Accuracy: 0.9962000250816345
1875/1875 [==============================] - 8s 4ms/step
Epoch 10
1875/1875 - 7s - loss: 0.0512 - accuracy: 0.9935 - 7s/epoch - 4ms/step
Training Accuracy: 0.9953166842460632
1875/1875 [==============================] - 6s 3ms/step
313/313 [==============================] - 2s 4ms/step - loss: 0.0867 - accuracy: 0.9736
Test Accuracy: 0.9735999703407288

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Flatten, Dense, Lambda
from tensorflow.keras.losses import SparseCategoricalCrossentropy
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import backend as K
from sklearn.model_selection import train_test_split

# Load the original MNIST dataset
(train_images_source, train_labels_source), (test_images_source, test_labels_source) = mnist.load_data()

# Distributionally shifted MNIST (e.g., digit 5-9)
# Create this dataset with a similar structure to your specific distribution shift
# For simplicity, we'll use a random permutation here to simulate a shift
shift_indices = np.random.permutation(len(train_labels_source))
train_images_target = train_images_source[shift_indices]
train_labels_target = train_labels_source[shift_indices]

# Normalize the pixel values to be between 0 and 1
train_images_source, test_images_source = train_images_source / 255.0, test_images_source / 255.0
train_images_target = train_images_target / 255.0

# Define the domain discriminator model
disc_input = Input(shape=(28, 28))
disc_flatten = Flatten()(disc_input)
disc_hidden = Dense(128, activation='relu')(disc_flatten)
disc_output = Dense(1, activation='sigmoid')(disc_hidden)
discriminator = Model(inputs=disc_input, outputs=disc_output)

# Compile the discriminator
discriminator.compile(optimizer=Adam(learning_rate=0.0001),
                      loss='binary_crossentropy',
                      metrics=['accuracy'])

# Freeze the discriminator weights during generator training
discriminator.trainable = False

# Define the feature extractor (source and target data share this network)
feature_extractor = Model(inputs=disc_input, outputs=disc_hidden)

# Define the label predictor (for the source domain)
source_label_pred = Dense(10, activation='softmax')(disc_hidden)

# Define the domain predictor (adversarial model)
domain_pred = Dense(1, activation='sigmoid')(disc_hidden)

# Define the final domain adaptation model
domain_adaptation_model = Model(inputs=disc_input, outputs=[source_label_pred, domain_pred])

# Compile the domain adaptation model with multiple losses
domain_adaptation_model.compile(optimizer=Adam(learning_rate=0.0001),
                                loss=[SparseCategoricalCrossentropy(), 'binary_crossentropy'],
                                loss_weights=[1.0, 0.1],  # You can adjust the weight of the domain loss
                                metrics=['accuracy'])

# Training loop for domain adaptation
epochs = 10
for epoch in range(epochs):
    # Assuming source and target data are of the same size
    batch_size = 64
    num_batches = len(train_images_source) // batch_size
    for batch_index in range(num_batches):
        # Sample a batch of source data
        source_batch_images = train_images_source[batch_index * batch_size: (batch_index + 1) * batch_size]
        source_batch_labels = train_labels_source[batch_index * batch_size: (batch_index + 1) * batch_size]
        # Sample a batch of target data
        target_batch_images = train_images_target[batch_index * batch_size: (batch_index + 1) * batch_size]

        # Combine source and target data for the discriminator
        combined_images = np.concatenate((source_batch_images, target_batch_images))
        combined_labels = np.concatenate((np.zeros(len(source_batch_labels)), np.ones(len(target_batch_images))))

        # Train the discriminator for one batch
        disc_loss = discriminator.train_on_batch(combined_images, combined_labels)

        # Train the domain adaptation model for one batch
        da_loss = domain_adaptation_model.train_on_batch(source_batch_images, [source_batch_labels, np.zeros(batch_size)])

    # Validation (evaluate on the target domain validation set)
    val_loss = domain_adaptation_model.evaluate(test_images_source, [test_labels_source, np.ones(len(test_labels_source))], verbose=0)

    # Print metrics
    print(f"Epoch {epoch+1}/{epochs}")
    print(f"Discriminator Loss: {disc_loss[0]}, Domain Adaptation Loss: {da_loss[0]}, Validation Loss: {val_loss[0]}")
    print(f"Discriminator Accuracy: {disc_loss[1]}, Domain Adaptation Accuracy: {da_loss[1]}, Validation Accuracy: {val_loss[1]}")

Epoch 1/10
Discriminator Loss: 0.7115464210510254, Domain Adaptation Loss: 2.0865633487701416, Validation Loss: 2.1013448238372803
Discriminator Accuracy: 0.40625, Domain Adaptation Accuracy: 2.0630016326904297, Validation Accuracy: 1.946018934249878
Epoch 2/10
Discriminator Loss: 0.708702564239502, Domain Adaptation Loss: 1.9507725238800049, Validation Loss: 1.9939396381378174
Discriminator Accuracy: 0.3984375, Domain Adaptation Accuracy: 1.9361628293991089, Validation Accuracy: 1.788237452507019
Epoch 3/10
Discriminator Loss: 0.7062355875968933, Domain Adaptation Loss: 1.8864355087280273, Validation Loss: 1.9398771524429321
Discriminator Accuracy: 0.3828125, Domain Adaptation Accuracy: 1.8757834434509277, Validation Accuracy: 1.6988111734390259
Epoch 4/10
Discriminator Loss: 0.7054150104522705, Domain Adaptation Loss: 1.832003116607666, Validation Loss: 1.9150060415267944
Discriminator Accuracy: 0.34375, Domain Adaptation Accuracy: 1.82367742061615, Validation Accuracy: 1.6453092098236084

KeyboardInterrupt: ignored

### old setup - standardt test set

In [ ]:
import tensorflow as tf

# Check if a GPU is available
if tf.test.is_gpu_available():
    print("GPU is available!")
else:
    print("No GPU found, using CPU.")

# Your code using TensorFlow with GPU support goes here
# For example:
# with tf.device('/device:GPU:0'):
#     # Your GPU-accelerated TensorFlow code here

WARNING:tensorflow:From <ipython-input-1-b8cef8c36b10>:4: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.

GPU is available!

In [ ]:
import numpy as np
from tensorflow import keras
from sklearn.model_selection import KFold

(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

def create_model():
    model = keras.Sequential([
        keras.layers.Flatten(input_shape=(28, 28)),
        keras.layers.Dense(128, activation='relu'),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model

kfold = KFold(n_splits=2, shuffle=True, random_state=42)

accuracies = []
for train_idx, val_idx in kfold.split(x_train):
    model = create_model()
    model.fit(x_train[train_idx], y_train[train_idx], epochs=5, batch_size=32, verbose=0)
    _, accuracy = model.evaluate(x_test, y_test, verbose=0)
    accuracies.append(accuracy)

mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)

print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)

Mean accuracy: 0.9189999997615814
Standard deviation: 0.005099982023239136

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import KFold

# Check if a GPU is available
if tf.test.is_gpu_available():
    print("GPU is available!")
else:
    print("No GPU found, using CPU.")

# Rest of the code
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

def create_model():
    model = keras.Sequential([
        keras.layers.Flatten(input_shape=(28, 28)),
        keras.layers.Dense(128, activation='relu'),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model

kfold = KFold(n_splits=2, shuffle=True, random_state=42)

accuracies = []
for train_idx, val_idx in kfold.split(x_train):
    with tf.device('/device:GPU:0'):  # Specify the GPU device to use
        model = create_model()
        model.fit(x_train[train_idx], y_train[train_idx], epochs=5, batch_size=32, verbose=0)
        _, accuracy = model.evaluate(x_test, y_test, verbose=0)
        accuracies.append(accuracy)

mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)

print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)

WARNING:tensorflow:From <ipython-input-1-c6d7dc8d9c57>:7: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.

GPU is available!
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
11490434/11490434 [==============================] - 1s 0us/step
Mean accuracy: 0.921999990940094
Standard deviation: 0.004999995231628418

In [ ]:
import numpy as np
from tensorflow import keras
import numpy as np
from tensorflow import keras
from sklearn.model_selection import KFold
# Load the MNIST dataset
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

# Create a permutation index for the pixel positions
num_pixels = x_train.shape[1] * x_train.shape[2]
perm_index = np.random.permutation(num_pixels)

# Permute the pixels for training and test sets
x_train_permuted = x_train.reshape(-1, num_pixels)[:, perm_index].reshape(-1, x_train.shape[1], x_train.shape[2])
x_test_permuted = x_test.reshape(-1, num_pixels)[:, perm_index].reshape(-1, x_test.shape[1], x_test.shape[2])

# Save the PermutedMNIST data to numpy files
# np.save('permuted_mnist_train_data.npy', x_train_permuted)
# np.save('permuted_mnist_train_labels.npy', y_train)
# np.save('permuted_mnist_test_data.npy', x_test_permuted)
# np.save('permuted_mnist_test_labels.npy', y_test)

def create_model():
    model = keras.Sequential([
        keras.layers.Flatten(input_shape=(28, 28)),
        keras.layers.Dense(128, activation='relu'),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model

kfold = KFold(n_splits=2, shuffle=True, random_state=42)

accuracies = []
for train_idx, val_idx in kfold.split(x_train_permuted):
    model = create_model()
    model.fit(x_train_permuted[train_idx], y_train[train_idx], epochs=5, batch_size=32, verbose=0)
    _, accuracy = model.evaluate(x_test, y_test, verbose=0)
    accuracies.append(accuracy)

mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)

print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)

Mean accuracy: 0.9231333434581757
Standard deviation: 0.0017000138759613037

In [ ]:
import numpy as np
from tensorflow import keras
from sklearn.model_selection import KFold

(x_train, y_train), (x_test, y_test) = keras.datasets.fashion_mnist.load_data()

def create_model():
    model = keras.Sequential([
        keras.layers.Flatten(input_shape=(28, 28)),
        keras.layers.Dense(128, activation='relu'),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model

kfold = KFold(n_splits=2, shuffle=True, random_state=42)

accuracies = []
for train_idx, val_idx in kfold.split(x_train):
    model = create_model()
    model.fit(x_train[train_idx], y_train[train_idx], epochs=5, batch_size=32, verbose=0)
    _, accuracy = model.evaluate(x_train[val_idx], y_train[val_idx], verbose=0)
    accuracies.append(accuracy)

mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)

print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)

Mean accuracy: 0.7895500063896179
Standard deviation: 0.011816680431365967

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import KFold
# from tensorflow.keras.datasets import kmnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam
import tensorflow_datasets as tfds

from sklearn.model_selection import train_test_split

# (x_train, y_train), (x_test, y_test) = kmnist.load_data()


dataset = tfds.load('kmnist')
train_o, test_o = dataset['train'], dataset['test']

train_numpy = np.vstack(tfds.as_numpy(train_o))
test_numpy = np.vstack(tfds.as_numpy(test_o))

train_x = np.array(list(map(lambda x: x[0]['image'], train_numpy)))
train_y = np.array(list(map(lambda x: x[0]['label'], train_numpy)))

test_x = np.array(list(map(lambda x: x[0]['image'], test_numpy)))
test_y = np.array(list(map(lambda x: x[0]['label'], test_numpy)))

train = np.concatenate((train_x,test_x), axis = 0)
test = np.concatenate((train_y,test_y),axis = 0)

print("it is whole train size ****:\t", train_x.shape)

x_train, x_test, y_train, y_test = train_x, test_x, train_y, test_y

def create_model():
    model = keras.Sequential([
        keras.layers.Flatten(input_shape=(28, 28)),
        keras.layers.Dense(128, activation='relu'),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model

kfold = KFold(n_splits=2, shuffle=True, random_state=42)

accuracies = []
for train_idx, val_idx in kfold.split(x_train):
    model = create_model()
    model.fit(x_train[train_idx], y_train[train_idx], epochs=5, batch_size=32, verbose=0)
    _, accuracy = model.evaluate(x_train[val_idx], y_train[val_idx], verbose=0)
    accuracies.append(accuracy)

mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)

print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)

<ipython-input-2-7a6a0b05a433>:19: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  train_numpy = np.vstack(tfds.as_numpy(train_o))
<ipython-input-2-7a6a0b05a433>:20: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  test_numpy = np.vstack(tfds.as_numpy(test_o))

it is whole train size ****:	 (60000, 28, 28, 1)
Mean accuracy: 0.8354000151157379
Standard deviation: 0.004799991846084595

In [ ]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import KFold

(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()

def create_model():
    model = keras.Sequential([
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(64, activation='relu'),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model


kfold = KFold(n_splits=2, shuffle=True, random_state=42)

accuracies = []
for train_idx, val_idx in kfold.split(x_train):
    model = create_model()
    model.fit(x_train[train_idx], y_train[train_idx], epochs=5, batch_size=32, verbose=0)
    _, accuracy = model.evaluate(x_train[val_idx], y_train[val_idx], verbose=0)
    accuracies.append(accuracy)

mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)

print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)

Mean accuracy: 0.5669799745082855
Standard deviation: 0.004979997873306274

In [ ]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import KFold
from tensorflow.keras.optimizers import Adam
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar100.load_data()

def create_model():
    model = keras.Sequential([
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(100, activation='softmax')
    ])

    model.compile(optimizer=Adam(learning_rate=0.001),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model



kfold = KFold(n_splits=2, shuffle=True, random_state=42)

accuracies = []
for train_idx, val_idx in kfold.split(x_train):
    model = create_model()
    model.fit(x_train[train_idx], y_train[train_idx], epochs=5, batch_size=32, verbose=0)
    _, accuracy = model.evaluate(x_train[val_idx], y_train[val_idx], verbose=0)
    accuracies.append(accuracy)

mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)

print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)

Mean accuracy: 0.2423200011253357
Standard deviation: 0.01260000467300415

In [ ]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import KFold
from tensorflow.keras.optimizers import Adam
from skimage.util import random_noise
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()

# Add speckle noise to the training images
x_train = random_noise(x_train, mode='speckle', var=0.1)
def create_model():
    model = keras.Sequential([
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model



kfold = KFold(n_splits=2, shuffle=True, random_state=42)

accuracies = []
for train_idx, val_idx in kfold.split(x_train):
    model = create_model()
    model.fit(x_train[train_idx], y_train[train_idx], epochs=5, batch_size=32, validation_data=(x_train[val_idx], y_train[val_idx]),  verbose=0)
    _, accuracy = model.evaluate(x_test, y_test)
    accuracies.append(accuracy)

mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)

print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)

313/313 [==============================] - 2s 6ms/step - loss: 218.7366 - accuracy: 0.4837
313/313 [==============================] - 2s 3ms/step - loss: 227.9406 - accuracy: 0.4739
Mean accuracy: 0.4787999987602234
Standard deviation: 0.0049000084400177

In [ ]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import KFold
from tensorflow.keras.optimizers import Adam
from skimage.util import random_noise
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar100.load_data()

# Add speckle noise to the training images
x_train = random_noise(x_train, mode='speckle', var=0.1)
def create_model():
    model = keras.Sequential([
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(100, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model



kfold = KFold(n_splits=2, shuffle=True, random_state=42)

accuracies = []
for train_idx, val_idx in kfold.split(x_train):
    model = create_model()
    model.fit(x_train[train_idx], y_train[train_idx], epochs=5, batch_size=32, verbose=0)
    _, accuracy = model.evaluate(x_train[val_idx], y_train[val_idx], verbose=0)
    accuracies.append(accuracy)

mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)

print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)

In [ ]:
import numpy as np
from tensorflow import keras
from sklearn.model_selection import KFold

(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

def create_model():
    model = keras.Sequential([
        keras.layers.Flatten(input_shape=(28, 28)),
        keras.layers.Dense(128, activation='relu'),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model

kfold = KFold(n_splits=5, shuffle=True, random_state=42)

accuracies = []
for train_idx, val_idx in kfold.split(x_train):
    model = create_model()
    model.fit(x_train[train_idx], y_train[train_idx], epochs=5, batch_size=32, verbose=0)
    _, accuracy = model.evaluate(x_train[val_idx], y_train[val_idx], verbose=0)
    accuracies.append(accuracy)

mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)

print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)

Mean accuracy: 0.9323666572570801
Standard deviation: 0.0020225231685724503

### Leave one out cross val

#### CIFAR10

In [ ]:
import numpy as np
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import SparseCategoricalCrossentropy
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Load the CIFAR-10 dataset
(x_train, y_train), (_, _) = cifar10.load_data()

# Normalize pixel values to the range [0, 1]
x_train = x_train.astype('float32') / 255.0

# Define the number of classes in the CIFAR-10 dataset
num_classes = 10

# Perform Leave-One-Out Cross-Validation
fold_accuracy = []

for i in range(len(x_train)):
    # Split the data into training and validation sets
    x_train_fold, x_val_fold = np.delete(x_train, i, axis=0), x_train[i:i+1]
    y_train_fold, y_val_fold = np.delete(y_train, i, axis=0), y_train[i:i+1]

    # Convert labels to integer format (necessary for SparseCategoricalCrossentropy)
    y_train_fold = y_train_fold.reshape(-1)
    y_val_fold = y_val_fold.reshape(-1)

    # Define the model architecture
    model = Sequential()
    model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)))
    model.add(MaxPooling2D((2, 2)))
    model.add(Flatten())
    model.add(Dense(128, activation='relu'))
    model.add(Dense(num_classes, activation='softmax'))

    # Compile the model
    model.compile(optimizer=Adam(), loss=SparseCategoricalCrossentropy(), metrics=['accuracy'])

    # Train the model on the training data
    model.fit(x_train_fold, y_train_fold, epochs=10, batch_size=64, verbose=1)

    # Evaluate the model on the validation data
    val_pred = model.predict(x_val_fold)
    val_accuracy = accuracy_score(y_val_fold, val_pred)
    fold_accuracy.append(val_accuracy)

# Calculate and print the average accuracy across all folds
average_accuracy = np.mean(fold_accuracy)
print('Average accuracy:', average_accuracy)

Epoch 1/10
782/782 [==============================] - 6s 5ms/step - loss: 1.6202 - accuracy: 0.4140
Epoch 2/10
782/782 [==============================] - 5s 6ms/step - loss: 1.2826 - accuracy: 0.5471
Epoch 3/10
782/782 [==============================] - 5s 6ms/step - loss: 1.1648 - accuracy: 0.5930
Epoch 4/10
782/782 [==============================] - 4s 5ms/step - loss: 1.0853 - accuracy: 0.6204
Epoch 5/10
782/782 [==============================] - 5s 7ms/step - loss: 1.0257 - accuracy: 0.6428
Epoch 6/10
782/782 [==============================] - 4s 5ms/step - loss: 0.9758 - accuracy: 0.6612
Epoch 7/10
782/782 [==============================] - 4s 5ms/step - loss: 0.9366 - accuracy: 0.6754
Epoch 8/10
782/782 [==============================] - 4s 6ms/step - loss: 0.8956 - accuracy: 0.6903
Epoch 9/10
782/782 [==============================] - 5s 6ms/step - loss: 0.8659 - accuracy: 0.6993
Epoch 10/10
782/782 [==============================] - 4s 6ms/step - loss: 0.8377 - accuracy: 0.7093
1/1 [==============================] - 0s 167ms/step

ValueError: ignored

## K-Fold cross validation : (2)

### MNIST

In [ ]:
import numpy as np
from tensorflow import keras
from sklearn.model_selection import KFold

(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()
# Concatenate the entire dataset
x = np.concatenate((x_train, x_test), axis=0)
y = np.concatenate((y_train, y_test), axis=0)
def create_model():
    model = keras.Sequential([
        keras.layers.Flatten(input_shape=(28, 28)),
        keras.layers.Dense(128, activation='relu'),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model

kf= KFold(n_splits=2, shuffle=True, random_state=42)

fold_accuracy = []
for train_index, val_index in kf.split(x):
    # Split the data into training and validation sets
    x_train_fold, x_val_fold = x[train_index], x[val_index]
    y_train_fold, y_val_fold = y[train_index], y[val_index]
    model = create_model()
    model.fit(x_train_fold, y_train_fold, epochs=10, batch_size=64, verbose=1)
    # Evaluate the model on the validation data
    _, accuracy = model.evaluate(x_val_fold, y_val_fold, verbose=0)
    fold_accuracy.append(accuracy)

# mean_accuracy = np.mean(accuracies)
# std_accuracy = np.std(accuracies)

# print("Mean accuracy:", mean_accuracy)
# print("Standard deviation:", std_accuracy)
# Calculate and print the average accuracy across all folds
average_accuracy = np.mean(fold_accuracy)
print('Average accuracy:', average_accuracy)

Epoch 1/10
547/547 [==============================] - 6s 5ms/step - loss: 5.0108 - accuracy: 0.8641
Epoch 2/10
547/547 [==============================] - 4s 7ms/step - loss: 0.7772 - accuracy: 0.9027
Epoch 3/10
547/547 [==============================] - 4s 8ms/step - loss: 0.3858 - accuracy: 0.9210
Epoch 4/10
547/547 [==============================] - 3s 5ms/step - loss: 0.2721 - accuracy: 0.9361
Epoch 5/10
547/547 [==============================] - 3s 5ms/step - loss: 0.2307 - accuracy: 0.9436
Epoch 6/10
547/547 [==============================] - 3s 5ms/step - loss: 0.1982 - accuracy: 0.9495
Epoch 7/10
547/547 [==============================] - 3s 6ms/step - loss: 0.1919 - accuracy: 0.9519
Epoch 8/10
547/547 [==============================] - 4s 7ms/step - loss: 0.1933 - accuracy: 0.9519
Epoch 9/10
547/547 [==============================] - 3s 5ms/step - loss: 0.1827 - accuracy: 0.9543
Epoch 10/10
547/547 [==============================] - 3s 5ms/step - loss: 0.1741 - accuracy: 0.9579
Epoch 1/10
547/547 [==============================] - 4s 5ms/step - loss: 4.8772 - accuracy: 0.8494
Epoch 2/10
547/547 [==============================] - 3s 5ms/step - loss: 0.6432 - accuracy: 0.8937
Epoch 3/10
547/547 [==============================] - 3s 5ms/step - loss: 0.3767 - accuracy: 0.9188
Epoch 4/10
547/547 [==============================] - 4s 8ms/step - loss: 0.2696 - accuracy: 0.9352
Epoch 5/10
547/547 [==============================] - 3s 5ms/step - loss: 0.2297 - accuracy: 0.9415
Epoch 6/10
547/547 [==============================] - 3s 5ms/step - loss: 0.2096 - accuracy: 0.9461
Epoch 7/10
547/547 [==============================] - 3s 5ms/step - loss: 0.1978 - accuracy: 0.9499
Epoch 8/10
547/547 [==============================] - 3s 5ms/step - loss: 0.1744 - accuracy: 0.9549
Epoch 9/10
547/547 [==============================] - 3s 5ms/step - loss: 0.1874 - accuracy: 0.9546
Epoch 10/10
547/547 [==============================] - 3s 5ms/step - loss: 0.1573 - accuracy: 0.9592
Average accuracy: 0.9372857213020325

In [ ]:
i = 0
float2 = "{0:.2f}"
for score in accuracies:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Fold-1: 91.39%
Fold-2: 92.41%

### PermutedMNIST

In [ ]:

import numpy as np
from tensorflow import keras
import numpy as np
from tensorflow import keras
from sklearn.model_selection import KFold
# Load the MNIST dataset
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

# Create a permutation index for the pixel positions
num_pixels = x_train.shape[1] * x_train.shape[2]
perm_index = np.random.permutation(num_pixels)

# Permute the pixels for training and test sets
x_train_permuted = x_train.reshape(-1, num_pixels)[:, perm_index].reshape(-1, x_train.shape[1], x_train.shape[2])
x_test_permuted = x_test.reshape(-1, num_pixels)[:, perm_index].reshape(-1, x_test.shape[1], x_test.shape[2])
x = np.concatenate((x_train_permuted, x_test_permuted), axis=0)
y = np.concatenate((y_train, y_test), axis=0)
# Save the PermutedMNIST data to numpy files
# np.save('permuted_mnist_train_data.npy', x_train_permuted)
# np.save('permuted_mnist_train_labels.npy', y_train)
# np.save('permuted_mnist_test_data.npy', x_test_permuted)
# np.save('permuted_mnist_test_labels.npy', y_test)

def create_model():
    model = keras.Sequential([
        keras.layers.Flatten(input_shape=(28, 28)),
        keras.layers.Dense(128, activation='relu'),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model

kfold = KFold(n_splits=2, shuffle=True, random_state=42)

accuracies = []
for train_idx, val_idx in kfold.split(x):
    model = create_model()
    model.fit(x[train_idx], y[train_idx], epochs=5, batch_size=32, verbose=0)
    _, accuracy = model.evaluate(x[val_idx], y[val_idx], verbose=0)
    accuracies.append(accuracy)

mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)

print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)
i = 0
float2 = "{0:.2f}"
for score in accuracies:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
11490434/11490434 [==============================] - 2s 0us/step
Mean accuracy: 0.9239999949932098
Standard deviation: 0.000514298677444458
Fold-1: 92.45%
Fold-2: 92.35%

### Fashion-MNIST

In [ ]:
import numpy as np
from tensorflow import keras
from sklearn.model_selection import KFold

(x_train, y_train), (x_test, y_test) = keras.datasets.fashion_mnist.load_data()
# Concatenate the entire dataset
x = np.concatenate((x_train, x_test), axis=0)
y = np.concatenate((y_train, y_test), axis=0)
def create_model():
    model = keras.Sequential([
        keras.layers.Flatten(input_shape=(28, 28)),
        keras.layers.Dense(128, activation='relu'),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model

kf= KFold(n_splits=2, shuffle=True, random_state=42)

fold_accuracy = []
for train_index, val_index in kf.split(x):
    # Split the data into training and validation sets
    x_train_fold, x_val_fold = x[train_index], x[val_index]
    y_train_fold, y_val_fold = y[train_index], y[val_index]
    model = create_model()
    model.fit(x_train_fold, y_train_fold, epochs=10, batch_size=64, verbose=1)
    # Evaluate the model on the validation data
    _, accuracy = model.evaluate(x_val_fold, y_val_fold, verbose=0)
    fold_accuracy.append(accuracy)

# mean_accuracy = np.mean(accuracies)
# std_accuracy = np.std(accuracies)

# print("Mean accuracy:", mean_accuracy)
# print("Standard deviation:", std_accuracy)
# Calculate and print the average accuracy across all folds
average_accuracy = np.mean(fold_accuracy)
print('Average accuracy:', average_accuracy)
i = 0
float2 = "{0:.2f}"
for score in fold_accuracy:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Epoch 1/10
547/547 [==============================] - 4s 4ms/step - loss: 7.8074 - accuracy: 0.6964
Epoch 2/10
547/547 [==============================] - 2s 4ms/step - loss: 0.9091 - accuracy: 0.7044
Epoch 3/10
547/547 [==============================] - 2s 4ms/step - loss: 0.7232 - accuracy: 0.7396
Epoch 4/10
547/547 [==============================] - 2s 4ms/step - loss: 0.6450 - accuracy: 0.7680
Epoch 5/10
547/547 [==============================] - 3s 5ms/step - loss: 0.5833 - accuracy: 0.7850
Epoch 6/10
547/547 [==============================] - 2s 4ms/step - loss: 0.5430 - accuracy: 0.7994
Epoch 7/10
547/547 [==============================] - 2s 4ms/step - loss: 0.5373 - accuracy: 0.7982
Epoch 8/10
547/547 [==============================] - 2s 4ms/step - loss: 0.4933 - accuracy: 0.8242
Epoch 9/10
547/547 [==============================] - 2s 4ms/step - loss: 0.4644 - accuracy: 0.8335
Epoch 10/10
547/547 [==============================] - 2s 4ms/step - loss: 0.4423 - accuracy: 0.8397
Epoch 1/10
547/547 [==============================] - 4s 5ms/step - loss: 6.8589 - accuracy: 0.6895
Epoch 2/10
547/547 [==============================] - 2s 4ms/step - loss: 0.8472 - accuracy: 0.7191
Epoch 3/10
547/547 [==============================] - 2s 4ms/step - loss: 0.6962 - accuracy: 0.7507
Epoch 4/10
547/547 [==============================] - 2s 4ms/step - loss: 0.6044 - accuracy: 0.7820
Epoch 5/10
547/547 [==============================] - 2s 4ms/step - loss: 0.5471 - accuracy: 0.7989
Epoch 6/10
547/547 [==============================] - 3s 6ms/step - loss: 0.5168 - accuracy: 0.8102
Epoch 7/10
547/547 [==============================] - 2s 5ms/step - loss: 0.4994 - accuracy: 0.8200
Epoch 8/10
547/547 [==============================] - 2s 4ms/step - loss: 0.4684 - accuracy: 0.8304
Epoch 9/10
547/547 [==============================] - 2s 4ms/step - loss: 0.4549 - accuracy: 0.8408
Epoch 10/10
547/547 [==============================] - 2s 4ms/step - loss: 0.4376 - accuracy: 0.8435
Average accuracy: 0.8407428562641144
Fold-1: 83.94%
Fold-2: 84.21%

### Kuzushiji-MNIST

In [ ]:

import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import KFold
# from tensorflow.keras.datasets import kmnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam
import tensorflow_datasets as tfds

from sklearn.model_selection import train_test_split

# (x_train, y_train), (x_test, y_test) = kmnist.load_data()


dataset = tfds.load('kmnist')
train_o, test_o = dataset['train'], dataset['test']

train_numpy = np.vstack(tfds.as_numpy(train_o))
test_numpy = np.vstack(tfds.as_numpy(test_o))

train_x = np.array(list(map(lambda x: x[0]['image'], train_numpy)))
train_y = np.array(list(map(lambda x: x[0]['label'], train_numpy)))

test_x = np.array(list(map(lambda x: x[0]['image'], test_numpy)))
test_y = np.array(list(map(lambda x: x[0]['label'], test_numpy)))

train = np.concatenate((train_x,test_x), axis = 0)
test = np.concatenate((train_y,test_y),axis = 0)

print("it is whole train size ****:\t", train_x.shape)

x_train, x_test, y_train, y_test = train_x, test_x, train_y, test_y
# Concatenate the entire dataset
x = np.concatenate((x_train, x_test), axis=0)
y = np.concatenate((y_train, y_test), axis=0)
def create_model():
    model = keras.Sequential([
        keras.layers.Flatten(input_shape=(28, 28)),
        keras.layers.Dense(128, activation='relu'),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model

kfold = KFold(n_splits=2, shuffle=True, random_state=42)

accuracies = []
for train_idx, val_idx in kfold.split(x):
    model = create_model()
    model.fit(x[train_idx], y[train_idx], epochs=5, batch_size=32, verbose=0)
    _, accuracy = model.evaluate(x[val_idx], y[val_idx], verbose=0)
    accuracies.append(accuracy)

mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)

print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)
i = 0
float2 = "{0:.2f}"
for score in accuracies:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Downloading and preparing dataset 20.26 MiB (download: 20.26 MiB, generated: 31.76 MiB, total: 52.02 MiB) to /root/tensorflow_datasets/kmnist/3.0.1...

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

Generating splits...:   0%|          | 0/2 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/60000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/kmnist/3.0.1.incompleteOD01UU/kmnist-train.tfrecord*...:   0%|          | …

Generating test examples...:   0%|          | 0/10000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/kmnist/3.0.1.incompleteOD01UU/kmnist-test.tfrecord*...:   0%|          | 0…

Dataset kmnist downloaded and prepared to /root/tensorflow_datasets/kmnist/3.0.1. Subsequent calls will reuse this data.

<ipython-input-1-2df78913ad2f>:19: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  train_numpy = np.vstack(tfds.as_numpy(train_o))
<ipython-input-1-2df78913ad2f>:20: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  test_numpy = np.vstack(tfds.as_numpy(test_o))

it is whole train size ****:	 (60000, 28, 28, 1)
Mean accuracy: 0.8342285752296448
Standard deviation: 0.009285688400268555
Fold-1: 82.49%
Fold-2: 84.35%

### MNIST-C

In [ ]:
import numpy as np
import tensorflow_datasets as tfds
from sklearn.model_selection import KFold
from keras.models import Sequential
from keras.layers import Dense, Flatten

# Load the MNIST-C dataset
dataset = tfds.load('mnist_corrupted', split='train')
data = list(dataset.as_numpy_iterator())
images = np.array([example['image'] for example in data])
labels = np.array([example['label'] for example in data])

# Define the model architecture
model = Sequential()
model.add(Flatten(input_shape=(28, 28)))
model.add(Dense(128, activation='relu'))
model.add(Dense(10, activation='softmax'))
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Perform k-fold cross-validation
k = 2
kf = KFold(n_splits=k, shuffle=True)

accuracy_scores = []
for train_indices, val_indices in kf.split(images):
    train_images, train_labels = images[train_indices], labels[train_indices]
    val_images, val_labels = images[val_indices], labels[val_indices]

    # Preprocess and normalize the data if necessary

    # Train the model on the current fold
    model.fit(train_images, train_labels, epochs=5, batch_size=32, verbose=0)

    # Evaluate the model on the validation set
    _, accuracy = model.evaluate(val_images, val_labels, verbose=0)
    accuracy_scores.append(accuracy)

# Calculate and print the average accuracy across folds
average_accuracy = sum(accuracy_scores) / k
print("Average accuracy:", average_accuracy)
i = 0
float2 = "{0:.2f}"
for score in accuracy_scores:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Downloading and preparing dataset 235.23 MiB (download: 235.23 MiB, generated: Unknown size, total: 235.23 MiB) to /root/tensorflow_datasets/mnist_corrupted/identity/1.0.0...

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

Generating splits...:   0%|          | 0/2 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/60000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/mnist_corrupted/identity/1.0.0.incompleteNBPEQW/mnist_corrupted-train.tfre…

Generating test examples...:   0%|          | 0/10000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/mnist_corrupted/identity/1.0.0.incompleteNBPEQW/mnist_corrupted-test.tfrec…

Dataset mnist_corrupted downloaded and prepared to /root/tensorflow_datasets/mnist_corrupted/identity/1.0.0. Subsequent calls will reuse this data.
Average accuracy: 0.9361000061035156
Fold-1: 93.10%
Fold-2: 94.12%

### CIFAR10

In [ ]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import KFold

(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()
# Concatenate the entire dataset
x = np.concatenate((x_train, x_test), axis=0)
y = np.concatenate((y_train, y_test), axis=0)
def create_model():
    model = keras.Sequential([
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(64, activation='relu'),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model


kfold = KFold(n_splits=2, shuffle=True, random_state=42)

accuracies = []
for train_idx, val_idx in kfold.split(x):
    model = create_model()
    model.fit(x[train_idx], y[train_idx], epochs=5, batch_size=32, verbose=0)
    _, accuracy = model.evaluate(x[val_idx], y[val_idx], verbose=0)
    accuracies.append(accuracy)

mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)

print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)
i = 0
float2 = "{0:.2f}"
for score in accuracies:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Downloading data from https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
170498071/170498071 [==============================] - 2s 0us/step
Mean accuracy: 0.5810333490371704
Standard deviation: 0.007766664028167725
Fold-1: 57.33%
Fold-2: 58.88%

### CIFAR100

In [ ]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import KFold
from tensorflow.keras.optimizers import Adam
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar100.load_data()

# Concatenate the entire dataset
x = np.concatenate((x_train, x_test), axis=0)
y = np.concatenate((y_train, y_test), axis=0)

def create_model():
    model = keras.Sequential([
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(100, activation='softmax')
    ])

    model.compile(optimizer=Adam(learning_rate=0.001),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model



kfold = KFold(n_splits=2, shuffle=True, random_state=42)

accuracies = []
for train_idx, val_idx in kfold.split(x):
    model = create_model()
    model.fit(x[train_idx], y[train_idx], epochs=5, batch_size=32, verbose=0)
    _, accuracy = model.evaluate(x[val_idx], y[val_idx], verbose=0)
    accuracies.append(accuracy)

mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)

print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)

i = 0
float2 = "{0:.2f}"
for score in accuracies:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Downloading data from https://www.cs.toronto.edu/~kriz/cifar-100-python.tar.gz
169001437/169001437 [==============================] - 2s 0us/step
Mean accuracy: 0.26073333621025085
Standard deviation: 0.003166675567626953
Fold-1: 26.39%
Fold-2: 25.76%

### CIFAR10-C

In [ ]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import KFold
from tensorflow.keras.optimizers import Adam
from skimage.util import random_noise
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()

# Concatenate the entire dataset
x = np.concatenate((x_train, x_test), axis=0)
y = np.concatenate((y_train, y_test), axis=0)

y_train = y
# Add speckle noise to the training images
x_train = random_noise(x, mode='speckle', var=0.1)
def create_model():
    model = keras.Sequential([
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model



kfold = KFold(n_splits=2, shuffle=True, random_state=42)

accuracies = []
for train_idx, val_idx in kfold.split(x_train):
    model = create_model()
    model.fit(x_train[train_idx], y_train[train_idx], epochs=5,  verbose=0)
    _, accuracy = model.evaluate(x_train[val_idx], y_train[val_idx])
    accuracies.append(accuracy)

mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)

print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)
i = 0
float2 = "{0:.2f}"
for score in accuracies:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

938/938 [==============================] - 4s 4ms/step - loss: 1.0707 - accuracy: 0.6310
938/938 [==============================] - 3s 3ms/step - loss: 1.0172 - accuracy: 0.6493
Mean accuracy: 0.6401500105857849
Standard deviation: 0.009183347225189209
Fold-1: 63.10%
Fold-2: 64.93%

### CIFAR100-C

In [ ]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import KFold
from tensorflow.keras.optimizers import Adam
from skimage.util import random_noise
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar100.load_data()

# Concatenate the entire dataset
x = np.concatenate((x_train, x_test), axis=0)
y = np.concatenate((y_train, y_test), axis=0)

y_train = y
# Add speckle noise to the training images
x_train = random_noise(x, mode='speckle', var=0.1)
def create_model():
    model = keras.Sequential([
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(100, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model



kfold = KFold(n_splits=2, shuffle=True, random_state=42)

accuracies = []
for train_idx, val_idx in kfold.split(x_train):
    model = create_model()
    model.fit(x_train[train_idx], y_train[train_idx], epochs=5, batch_size=32, verbose=0)
    _, accuracy = model.evaluate(x_train[val_idx], y_train[val_idx], verbose=0)
    accuracies.append(accuracy)

mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)

print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)
i = 0
float2 = "{0:.2f}"
for score in accuracies:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Mean accuracy: 0.28191666305065155
Standard deviation: 0.0009499937295913696
Fold-1: 28.29%
Fold-2: 28.10%

### SVHN

In [ ]:
!wget http://ufldl.stanford.edu/housenumbers/train_32x32.mat
!wget http://ufldl.stanford.edu/housenumbers/test_32x32.mat

--2023-07-29 13:06:31--  http://ufldl.stanford.edu/housenumbers/train_32x32.mat
Resolving ufldl.stanford.edu (ufldl.stanford.edu)... 171.64.68.10
Connecting to ufldl.stanford.edu (ufldl.stanford.edu)|171.64.68.10|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 182040794 (174M) [text/plain]
Saving to: ‘train_32x32.mat’

train_32x32.mat     100%[===================>] 173.61M  18.9MB/s    in 8.9s

2023-07-29 13:06:40 (19.4 MB/s) - ‘train_32x32.mat’ saved [182040794/182040794]

--2023-07-29 13:06:40--  http://ufldl.stanford.edu/housenumbers/test_32x32.mat
Resolving ufldl.stanford.edu (ufldl.stanford.edu)... 171.64.68.10
Connecting to ufldl.stanford.edu (ufldl.stanford.edu)|171.64.68.10|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 64275384 (61M) [text/plain]
Saving to: ‘test_32x32.mat’

test_32x32.mat      100%[===================>]  61.30M  29.3MB/s    in 2.1s

2023-07-29 13:06:42 (29.3 MB/s) - ‘test_32x32.mat’ saved [64275384/64275384]

In [ ]:
import numpy as np
from tensorflow import keras
from sklearn.model_selection import KFold
import scipy.io as sio
from tensorflow.keras.utils import to_categorical
# Define the model architecture
def create_model():
    model = keras.Sequential([
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(64, activation='relu'),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])

    return model


# Load the SVHN dataset
train_data = sio.loadmat("train_32x32.mat")
test_data = sio.loadmat("test_32x32.mat")

# Extract the images and labels from the downloaded data
train_images = np.transpose(train_data['X'], (3, 0, 1, 2))
train_labels = train_data['y']

test_images = np.transpose(test_data['X'], (3, 0, 1, 2))
test_labels = test_data['y']

# Change class labels to range from 0 to 9
train_labels[train_labels == 10] = 0
test_labels[test_labels == 10] = 0

# Perform one-hot encoding on the labels
num_classes = 10
train_labels = to_categorical(train_labels, num_classes)
test_labels = to_categorical(test_labels, num_classes)

# Print the shape of the loaded data
print("Train images shape:", train_images.shape)
print("Train labels shape:", train_labels.shape)
print("Test images shape:", test_images.shape)
print("Test labels shape:", test_labels.shape)

# Concatenate the entire dataset
x = np.concatenate((train_images, test_images), axis=0)
y = np.concatenate((train_labels, test_labels), axis=0)
print(x.shape, y.shape)
# Define the number of folds for cross-validation
k = 2
kf = KFold(n_splits=k, shuffle=True, random_state=42)

train_images = x
train_labels = y
accuracies = []

# Perform k-fold cross-validation
for train_idx, val_idx in kf.split(train_images):
    # Create a new instance of the model for each fold
    model = create_model()

    # Train the model on the current fold
    model.fit(train_images[train_idx], train_labels[train_idx], epochs=5, batch_size=32, verbose=1)

    # Evaluate the model on the validation fold
    _, accuracy = model.evaluate(train_images[val_idx], train_labels[val_idx], verbose=0)

    # Append the accuracy to the list of accuracies
    accuracies.append(accuracy)

# Compute the mean and standard deviation of the accuracies
mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)

# Print the results
print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)
i = 0
float2 = "{0:.2f}"
for score in accuracies:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Train images shape: (73257, 32, 32, 3)
Train labels shape: (73257, 10)
Test images shape: (26032, 32, 32, 3)
Test labels shape: (26032, 10)
(99289, 32, 32, 3) (99289, 10)
Epoch 1/5
1552/1552 [==============================] - 26s 7ms/step - loss: 2.5434 - accuracy: 0.1851
Epoch 2/5
1552/1552 [==============================] - 10s 7ms/step - loss: 1.8137 - accuracy: 0.3543
Epoch 3/5
1552/1552 [==============================] - 10s 6ms/step - loss: 0.9429 - accuracy: 0.7094
Epoch 4/5
1552/1552 [==============================] - 11s 7ms/step - loss: 0.7361 - accuracy: 0.7806
Epoch 5/5
1552/1552 [==============================] - 11s 7ms/step - loss: 0.6597 - accuracy: 0.8058
Epoch 1/5
1552/1552 [==============================] - 14s 7ms/step - loss: 2.4523 - accuracy: 0.1894
Epoch 2/5
1552/1552 [==============================] - 11s 7ms/step - loss: 2.2321 - accuracy: 0.1910
Epoch 3/5
1552/1552 [==============================] - 10s 6ms/step - loss: 2.2320 - accuracy: 0.1910
Epoch 4/5
1552/1552 [==============================] - 10s 7ms/step - loss: 2.2320 - accuracy: 0.1910
Epoch 5/5
1552/1552 [==============================] - 11s 7ms/step - loss: 2.2320 - accuracy: 0.1910
Mean accuracy: 0.505782961845398
Standard deviation: 0.3148636221885681
Fold-1: 82.06%
Fold-2: 19.09%

### voc2012

In [ ]:
import tensorflow as tf
import tensorflow_datasets as tfds
import numpy as np
from sklearn.model_selection import KFold

# Check if GPU is available
if tf.config.list_physical_devices('GPU'):
    print("GPU is available.")
else:
    print("GPU is not available. Training on CPU.")

# Load VOC 2012 dataset from TFDS
def load_voc_dataset():
    train_data, info = tfds.load('voc/2012', split='train', as_supervised=True, with_info=True)
    test_data = tfds.load('voc/2012', split='test', as_supervised=True)
    val_data = tfds.load('voc/2012', split='validation', as_supervised=True)
    return train_data, test_data, val_data, info

# Define the model architecture
def create_model():
    model = tf.keras.models.Sequential([
        tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(None, None, 3)),
        tf.keras.layers.MaxPooling2D((2, 2)),
        tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
        tf.keras.layers.MaxPooling2D((2, 2)),
        tf.keras.layers.Conv2D(128, (3, 3), activation='relu'),
        tf.keras.layers.MaxPooling2D((2, 2)),
        tf.keras.layers.GlobalAveragePooling2D(),
        tf.keras.layers.Dense(512, activation='relu'),
        tf.keras.layers.Dense(20, activation='softmax')  # 20 classes in VOC 2012 dataset
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model

# Prepare the dataset for training
def preprocess_image(image, label):
    image = tf.image.resize(image, (224, 224))
    image = tf.cast(image, tf.float32) / 255.0
    label = tf.cast(label, tf.int32)
    return image, label

train_data, test_data, val_data, dataset_info = load_voc_dataset()
train_data = train_data.map(preprocess_image).prefetch(tf.data.AUTOTUNE)
test_data = test_data.map(preprocess_image).prefetch(tf.data.AUTOTUNE)
val_data = val_data.map(preprocess_image).prefetch(tf.data.AUTOTUNE)

# Combine train, test, and validation datasets
combined_data = train_data.concatenate(test_data).concatenate(val_data)

# Check for GPU support and set up the strategy
strategy = None
if tf.config.list_physical_devices('GPU'):
    strategy = tf.distribute.MirroredStrategy()
    print(f"Running on {strategy.num_replicas_in_sync} GPUs.")

# K-Fold Cross Validation
k = 5
num_samples = dataset_info.splits['train'].num_examples + dataset_info.splits['test'].num_examples + dataset_info.splits['validation'].num_examples
indices = np.arange(num_samples)
labels = np.array([label.numpy() for _, label in combined_data])

kfold = KFold(n_splits=k, shuffle=True, random_state=42)
fold_index = 0

for train_index, val_index in kfold.split(indices, labels):
    fold_index += 1
    print(f"Fold {fold_index}:")

    # Create TensorFlow datasets for training and validation
    train_dataset = combined_data.take(train_index[-1] + 1)
    val_dataset = combined_data.skip(train_index[-1] + 1).take(val_index[-1] - train_index[-1])

    # Create and train the model within the strategy's scope
    with strategy.scope():
        model = create_model()

    model.fit(train_dataset, validation_data=val_dataset, epochs=5)

GPU is available.
Downloading and preparing dataset 3.59 GiB (download: 3.59 GiB, generated: Unknown size, total: 3.59 GiB) to /root/tensorflow_datasets/voc/2012/4.0.0...

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

Shuffling /root/tensorflow_datasets/voc/2012/4.0.0.incomplete45VXEP/voc-test.tfrecord*...:   0%|          | 0/…

Generating train examples...:   0%|          | 0/5717 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/voc/2012/4.0.0.incomplete45VXEP/voc-train.tfrecord*...:   0%|          | 0…

Generating validation examples...:   0%|          | 0/5823 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/voc/2012/4.0.0.incomplete45VXEP/voc-validation.tfrecord*...:   0%|        …

Dataset voc downloaded and prepared to /root/tensorflow_datasets/voc/2012/4.0.0. Subsequent calls will reuse this data.

ValueError: ignored

### KddCup99

In [ ]:
import tensorflow as tf
import tensorflow_datasets as tfds
import numpy as np
from sklearn.model_selection import KFold
from tensorflow import keras
from tensorflow.keras import layers

# Load KDD Cup 1999 dataset from TensorFlow Datasets
(ds_train, ds_test), ds_info = tfds.load(
    'kddcup99',
    split=['train', 'test'],
    shuffle_files=True,
    as_supervised=True,
    with_info=True
)

# Combine the dataset
ds_combined = ds_train.concatenate(ds_test)

# Convert dataset to numpy arrays
x = []
y = []
for sample in ds_combined:
    features, label = sample
    x.append(features.numpy())
    y.append(label.numpy())
x = np.array(x)
y = np.array(y)

# Preprocess the data: One-hot encoding for categorical features
x = pd.get_dummies(pd.DataFrame(x, columns=ds_info.features['features'].keys())).to_numpy()

# Define the number of folds for cross-validation
num_folds = 5
kfold = KFold(n_splits=num_folds, shuffle=True)

# Define the model architecture
def create_model():
    model = keras.Sequential([
        layers.Dense(64, activation='relu', input_shape=(x.shape[1],)),
        layers.Dense(32, activation='relu'),
        layers.Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

# Perform k-fold cross-validation
accuracies = []

for fold, (train_idx, val_idx) in enumerate(kfold.split(x)):
    print(f"Fold: {fold + 1}")
    x_train_fold, x_val_fold = x[train_idx], x[val_idx]
    y_train_fold, y_val_fold = y[train_idx], y[val_idx]

    # Create and compile the model for each fold
    model = create_model()

    # Train the model
    model.fit(x_train_fold, y_train_fold, epochs=5, batch_size=32, verbose=1)

    # Evaluate the model on the validation set
    _, accuracy = model.evaluate(x_val_fold, y_val_fold, verbose=1)
    accuracies.append(accuracy)

# Calculate and print mean and standard deviation of accuracies
mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)
print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)
i = 0
float2 = "{0:.2f}"
for score in accuracies:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Downloading and preparing dataset 18.62 MiB (download: 18.62 MiB, generated: 5.25 GiB, total: 5.27 GiB) to /root/tensorflow_datasets/kddcup99/1.0.1...

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Generating splits...:   0%|          | 0/2 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/4898431 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/kddcup99/1.0.1.incompleteIJZ699/kddcup99-train.tfrecord*...:   0%|        …

Generating test examples...:   0%|          | 0/311029 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/kddcup99/1.0.1.incompleteIJZ699/kddcup99-test.tfrecord*...:   0%|         …

Dataset kddcup99 downloaded and prepared to /root/tensorflow_datasets/kddcup99/1.0.1. Subsequent calls will reuse this data.

ValueError: ignored

### COCO

In [ ]:
import tensorflow_datasets as tfds

# Get the list of available datasets
all_datasets = tfds.list_files()

# Print the list of datasets
print("Available datasets in TensorFlow Datasets:")
for dataset_name in all_datasets:
    print(dataset_name)

AttributeError: ignored

In [ ]:
import tensorflow_datasets as tfds
import numpy as np

# Load the COCO dataset
train_dataset, test_dataset = tfds.load('coco/2017', split=['train', 'validation'], shuffle_files=True, as_supervised=True)

# Initialize lists to store images and labels
train_images, train_labels = [], []
test_images, test_labels = [], []

# Load training data
for image, label in train_dataset:
    train_images.append(image.numpy())
    train_labels.append(label.numpy())

# Load test data
for image, label in test_dataset:
    test_images.append(image.numpy())
    test_labels.append(label.numpy())

# Convert lists to NumPy arrays
train_images = np.array(train_images)
train_labels = np.array(train_labels)
test_images = np.array(test_images)
test_labels = np.array(test_labels)

# Combine train and test data for k-fold cross-validation
combined_images = np.concatenate((train_images, test_images), axis=0)
combined_labels = np.concatenate((train_labels, test_labels), axis=0)

WARNING:absl:You use TensorFlow DType <dtype: 'int64'> in tfds.features This will soon be deprecated in favor of NumPy DTypes. In the meantime it was converted to int64.

Downloading and preparing dataset 25.20 GiB (download: 25.20 GiB, generated: Unknown size, total: 25.20 GiB) to /root/tensorflow_datasets/coco/2017/1.1.0...

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

KeyboardInterrupt: ignored

### COMPAS

In [ ]:
!wget https://raw.githubusercontent.com/propublica/compas-analysis/master/compas-scores-two-years.csv

--2023-07-18 18:49:23--  https://raw.githubusercontent.com/propublica/compas-analysis/master/compas-scores-two-years.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2546489 (2.4M) [text/plain]
Saving to: ‘compas-scores-two-years.csv’

compas-scores-two-y 100%[===================>]   2.43M  --.-KB/s    in 0.04s

2023-07-18 18:49:23 (55.0 MB/s) - ‘compas-scores-two-years.csv’ saved [2546489/2546489]

In [ ]:
import pandas as pd
df = pd.read_csv('compas-scores-two-years.csv')

In [ ]:
df.head(2)

,id,name,first,last,compas_screening_date,sex,dob,age,age_cat,race,...,v_decile_score,v_score_text,v_screening_date,in_custody,out_custody,priors_count.1,start,end,event,two_year_recid
0,1,miguel hernandez,miguel,hernandez,2013-08-14,Male,1947-04-18,69,Greater than 45,Other,...,1,Low,2013-08-14,2014-07-07,2014-07-14,0,0,327,0,0
1,3,kevon dixon,kevon,dixon,2013-01-27,Male,1982-01-22,34,25 - 45,African-American,...,1,Low,2013-01-27,2013-01-26,2013-02-05,0,9,159,1,1

In [ ]:
# Split the DataFrame into X and y variables
X = df.drop('two_year_recid', axis=1)  # Drop the 'selector' column to get features (X)
y = df['two_year_recid']  # Get the 'selector' column as the target variable (y)
print(X.head())
print(y.head())

   id                name   first         last compas_screening_date   sex  \
0   1    miguel hernandez  miguel    hernandez            2013-08-14  Male
1   3         kevon dixon   kevon        dixon            2013-01-27  Male
2   4            ed philo      ed        philo            2013-04-14  Male
3   5         marcu brown   marcu        brown            2013-01-13  Male
4   6  bouthy pierrelouis  bouthy  pierrelouis            2013-03-26  Male

          dob  age          age_cat              race  ...  \
0  1947-04-18   69  Greater than 45             Other  ...
1  1982-01-22   34          25 - 45  African-American  ...
2  1991-05-14   24     Less than 25  African-American  ...
3  1993-01-21   23     Less than 25  African-American  ...
4  1973-01-22   43          25 - 45             Other  ...

   v_type_of_assessment  v_decile_score  v_score_text  v_screening_date  \
0      Risk of Violence               1           Low        2013-08-14
1      Risk of Violence               1           Low        2013-01-27
2      Risk of Violence               3           Low        2013-04-14
3      Risk of Violence               6        Medium        2013-01-13
4      Risk of Violence               1           Low        2013-03-26

   in_custody  out_custody priors_count.1 start   end event
0  2014-07-07   2014-07-14              0     0   327     0
1  2013-01-26   2013-02-05              0     9   159     1
2  2013-06-16   2013-06-16              4     0    63     0
3         NaN          NaN              1     0  1174     0
4         NaN          NaN              2     0  1102     0

[5 rows x 52 columns]
0    0
1    1
2    1
3    0
4    0
Name: two_year_recid, dtype: int64

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml

# Load the dataset by ID
# dataset_id = 844  # ID of the "GermanCredit" dataset on OpenML
# dataset = openml.datasets.get_dataset(dataset_id)

# # Access the data and target variables
# X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# print(X.head(5))

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 2
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

Fold 1: Accuracy = 0.9914056002217909
Fold 2: Accuracy = 0.9861380648738564
Mean accuracy: 0.9887718325478236
Standard deviation: 0.00263376767396728

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Caltech 101

In [ ]:
import tensorflow_datasets as tfds
import numpy as np
from skimage.transform import resize

# Load the Caltech 101 dataset
dataset_name = "caltech101"
builder = tfds.builder(dataset_name)

# Download and prepare the dataset
builder.download_and_prepare()

# Split the dataset into training and testing sets
train_dataset = builder.as_dataset(split="train")
test_dataset = builder.as_dataset(split="test")

# Iterate through the datasets to get features and labels
X_train = []
y_train = []
for example in tfds.as_numpy(train_dataset):
    X_train.append(example["image"])
    y_train.append(example["label"])

X_test = []
y_test = []
for example in tfds.as_numpy(test_dataset):
    X_test.append(example["image"])
    y_test.append(example["label"])

# Convert lists to numpy arrays
X_train = np.array(X_train)
y_train = np.array(y_train)
X_test = np.array(X_test)
y_test = np.array(y_test)

# Resize the image data to a common size
target_height, target_width, channels = 28, 28, 3
X_train_resized = np.array([resize(image, (target_height, target_width, channels)) for image in X_train])
X_test_resized = np.array([resize(image, (target_height, target_width, channels)) for image in X_test])

# Print the shape of the resized arrays
print("X_train resized shape:", X_train_resized.shape)
print("X_test resized shape:", X_test_resized.shape)

<ipython-input-1-d3b8c391cf7a>:30: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  X_train = np.array(X_train)
<ipython-input-1-d3b8c391cf7a>:32: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  X_test = np.array(X_test)

X_train resized shape: (3060, 28, 28, 3)
X_test resized shape: (6084, 28, 28, 3)

In [ ]:
x = np.concatenate((X_train_resized,X_test_resized), axis=0)
x.shape

(9144, 28, 28, 3)

In [ ]:
y = np.concatenate((y_train,y_test),axis=0)
y.shape

(9144,)

In [ ]:
import tensorflow as tf
y = tf.keras.utils.to_categorical(y, num_classes=102)
# y_test = tf.keras.utils.to_categorical(y_test, num_classes=102)
y.shape

(9144, 102)

In [ ]:
# model.fit(X_train_resized, y_train, batch_size=128, epochs=100, validation_data=(X_test_resized, y_test))
import tensorflow as tf
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras import layers
from sklearn.model_selection import KFold
def create_model():
    model = keras.Sequential([
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(28, 28, 3)),  # Update input shape
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(64, activation='relu'),
        keras.layers.Dense(102, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])

    return model

# Define the number of folds for cross-validation
num_folds = 2
kf = KFold(n_splits=num_folds, shuffle=True)

fold_accuracy = []
for train_index, val_index in kf.split(x):
    # Split the data into training and validation sets
    x_train_fold, x_val_fold = x[train_index], x[val_index]
    y_train_fold, y_val_fold = y[train_index], y[val_index]
    with tf.device('/device:GPU:0'):
      model = create_model()
      model.fit(x_train_fold, y_train_fold, epochs=100, batch_size=64, verbose=1)
    # Evaluate the model on the validation data
      _, accuracy = model.evaluate(x_val_fold, y_val_fold, verbose=0)
      fold_accuracy.append(accuracy)


average_accuracy = np.mean(fold_accuracy)
print('Average accuracy:', average_accuracy)
i = 0
float2 = "{0:.2f}"
for score in fold_accuracy:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Epoch 1/100
72/72 [==============================] - 6s 12ms/step - loss: 4.0933 - accuracy: 0.1441
Epoch 2/100
72/72 [==============================] - 1s 8ms/step - loss: 3.5537 - accuracy: 0.2577
Epoch 3/100
72/72 [==============================] - 1s 10ms/step - loss: 3.1774 - accuracy: 0.3290
Epoch 4/100
72/72 [==============================] - 1s 12ms/step - loss: 2.8377 - accuracy: 0.3895
Epoch 5/100
72/72 [==============================] - 1s 15ms/step - loss: 2.5700 - accuracy: 0.4278
Epoch 6/100
72/72 [==============================] - 1s 14ms/step - loss: 2.3285 - accuracy: 0.4733
Epoch 7/100
72/72 [==============================] - 1s 10ms/step - loss: 2.1669 - accuracy: 0.4941
Epoch 8/100
72/72 [==============================] - 1s 8ms/step - loss: 1.9912 - accuracy: 0.5357
Epoch 9/100
72/72 [==============================] - 1s 9ms/step - loss: 1.8433 - accuracy: 0.5573
Epoch 10/100
72/72 [==============================] - 1s 7ms/step - loss: 1.6861 - accuracy: 0.5916
Epoch 11/100
72/72 [==============================] - 1s 8ms/step - loss: 1.5603 - accuracy: 0.6150
Epoch 12/100
72/72 [==============================] - 1s 8ms/step - loss: 1.4459 - accuracy: 0.6417
Epoch 13/100
72/72 [==============================] - 1s 8ms/step - loss: 1.3286 - accuracy: 0.6724
Epoch 14/100
72/72 [==============================] - 0s 7ms/step - loss: 1.2155 - accuracy: 0.6938
Epoch 15/100
72/72 [==============================] - 1s 7ms/step - loss: 1.1279 - accuracy: 0.7124
Epoch 16/100
72/72 [==============================] - 1s 7ms/step - loss: 1.0190 - accuracy: 0.7382
Epoch 17/100
72/72 [==============================] - 1s 7ms/step - loss: 0.9473 - accuracy: 0.7542
Epoch 18/100
72/72 [==============================] - 1s 7ms/step - loss: 0.8534 - accuracy: 0.7789
Epoch 19/100
72/72 [==============================] - 1s 7ms/step - loss: 0.7964 - accuracy: 0.7885
Epoch 20/100
72/72 [==============================] - 0s 6ms/step - loss: 0.6963 - accuracy: 0.8193
Epoch 21/100
72/72 [==============================] - 1s 8ms/step - loss: 0.6197 - accuracy: 0.8403
Epoch 22/100
72/72 [==============================] - 0s 6ms/step - loss: 0.5585 - accuracy: 0.8493
Epoch 23/100
72/72 [==============================] - 1s 7ms/step - loss: 0.4795 - accuracy: 0.8790
Epoch 24/100
72/72 [==============================] - 1s 7ms/step - loss: 0.4461 - accuracy: 0.8830
Epoch 25/100
72/72 [==============================] - 1s 10ms/step - loss: 0.3905 - accuracy: 0.8950
Epoch 26/100
72/72 [==============================] - 1s 9ms/step - loss: 0.3350 - accuracy: 0.9110
Epoch 27/100
72/72 [==============================] - 1s 10ms/step - loss: 0.2867 - accuracy: 0.9335
Epoch 28/100
72/72 [==============================] - 1s 9ms/step - loss: 0.2329 - accuracy: 0.9475
Epoch 29/100
72/72 [==============================] - 1s 7ms/step - loss: 0.2029 - accuracy: 0.9576
Epoch 30/100
72/72 [==============================] - 0s 6ms/step - loss: 0.1853 - accuracy: 0.9600
Epoch 31/100
72/72 [==============================] - 1s 7ms/step - loss: 0.1638 - accuracy: 0.9643
Epoch 32/100
72/72 [==============================] - 1s 9ms/step - loss: 0.1536 - accuracy: 0.9663
Epoch 33/100
72/72 [==============================] - 1s 8ms/step - loss: 0.1193 - accuracy: 0.9757
Epoch 34/100
72/72 [==============================] - 1s 7ms/step - loss: 0.1014 - accuracy: 0.9805
Epoch 35/100
72/72 [==============================] - 0s 7ms/step - loss: 0.0757 - accuracy: 0.9891
Epoch 36/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0659 - accuracy: 0.9928
Epoch 37/100
72/72 [==============================] - 0s 7ms/step - loss: 0.0600 - accuracy: 0.9926
Epoch 38/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0391 - accuracy: 0.9969
Epoch 39/100
72/72 [==============================] - 1s 8ms/step - loss: 0.0270 - accuracy: 0.9989
Epoch 40/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0260 - accuracy: 0.9989
Epoch 41/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0217 - accuracy: 0.9991
Epoch 42/100
72/72 [==============================] - 0s 7ms/step - loss: 0.0156 - accuracy: 0.9993
Epoch 43/100
72/72 [==============================] - 1s 8ms/step - loss: 0.0148 - accuracy: 0.9991
Epoch 44/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0147 - accuracy: 0.9991
Epoch 45/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0111 - accuracy: 0.9996
Epoch 46/100
72/72 [==============================] - 1s 7ms/step - loss: 0.1955 - accuracy: 0.9377
Epoch 47/100
72/72 [==============================] - 1s 8ms/step - loss: 0.4132 - accuracy: 0.8751
Epoch 48/100
72/72 [==============================] - 1s 10ms/step - loss: 0.2216 - accuracy: 0.9311
Epoch 49/100
72/72 [==============================] - 1s 9ms/step - loss: 0.1291 - accuracy: 0.9652
Epoch 50/100
72/72 [==============================] - 1s 9ms/step - loss: 0.0447 - accuracy: 0.9917
Epoch 51/100
72/72 [==============================] - 1s 10ms/step - loss: 0.0199 - accuracy: 0.9991
Epoch 52/100
72/72 [==============================] - 0s 6ms/step - loss: 0.0132 - accuracy: 0.9993
Epoch 53/100
72/72 [==============================] - 0s 7ms/step - loss: 0.0097 - accuracy: 0.9996
Epoch 54/100
72/72 [==============================] - 0s 7ms/step - loss: 0.0108 - accuracy: 0.9996
Epoch 55/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0068 - accuracy: 0.9998
Epoch 56/100
72/72 [==============================] - 0s 6ms/step - loss: 0.0077 - accuracy: 0.9998
Epoch 57/100
72/72 [==============================] - 0s 6ms/step - loss: 0.0063 - accuracy: 0.9998
Epoch 58/100
72/72 [==============================] - 0s 6ms/step - loss: 0.0065 - accuracy: 0.9996
Epoch 59/100
72/72 [==============================] - 0s 6ms/step - loss: 0.0039 - accuracy: 0.9996
Epoch 60/100
72/72 [==============================] - 0s 7ms/step - loss: 0.0084 - accuracy: 0.9996
Epoch 61/100
72/72 [==============================] - 0s 6ms/step - loss: 0.0056 - accuracy: 0.9998
Epoch 62/100
72/72 [==============================] - 0s 7ms/step - loss: 0.0051 - accuracy: 0.9998
Epoch 63/100
72/72 [==============================] - 0s 6ms/step - loss: 0.0078 - accuracy: 0.9993
Epoch 64/100
72/72 [==============================] - 0s 6ms/step - loss: 0.0086 - accuracy: 0.9996
Epoch 65/100
72/72 [==============================] - 0s 6ms/step - loss: 0.0087 - accuracy: 0.9991
Epoch 66/100
72/72 [==============================] - 0s 7ms/step - loss: 0.0071 - accuracy: 0.9996
Epoch 67/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0055 - accuracy: 0.9996
Epoch 68/100
72/72 [==============================] - 0s 7ms/step - loss: 0.0048 - accuracy: 0.9996
Epoch 69/100
72/72 [==============================] - 0s 7ms/step - loss: 0.0046 - accuracy: 0.9998
Epoch 70/100
72/72 [==============================] - 0s 6ms/step - loss: 0.0035 - accuracy: 0.9998
Epoch 71/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0107 - accuracy: 0.9993
Epoch 72/100
72/72 [==============================] - 1s 8ms/step - loss: 0.0087 - accuracy: 0.9996
Epoch 73/100
72/72 [==============================] - 1s 9ms/step - loss: 0.0049 - accuracy: 0.9998
Epoch 74/100
72/72 [==============================] - 1s 10ms/step - loss: 0.0206 - accuracy: 0.9956
Epoch 75/100
72/72 [==============================] - 1s 9ms/step - loss: 0.5290 - accuracy: 0.8500
Epoch 76/100
72/72 [==============================] - 1s 10ms/step - loss: 0.2537 - accuracy: 0.9256
Epoch 77/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0847 - accuracy: 0.9794
Epoch 78/100
72/72 [==============================] - 0s 6ms/step - loss: 0.0462 - accuracy: 0.9888
Epoch 79/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0183 - accuracy: 0.9974
Epoch 80/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0088 - accuracy: 0.9996
Epoch 81/100
72/72 [==============================] - 1s 8ms/step - loss: 0.0059 - accuracy: 0.9998
Epoch 82/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0046 - accuracy: 0.9998
Epoch 83/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0050 - accuracy: 0.9996
Epoch 84/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0056 - accuracy: 0.9996
Epoch 85/100
72/72 [==============================] - 1s 8ms/step - loss: 0.0042 - accuracy: 0.9998
Epoch 86/100
72/72 [==============================] - 0s 7ms/step - loss: 0.0040 - accuracy: 0.9998
Epoch 87/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0033 - accuracy: 0.9998
Epoch 88/100
72/72 [==============================] - 0s 7ms/step - loss: 0.0063 - accuracy: 0.9996
Epoch 89/100
72/72 [==============================] - 0s 7ms/step - loss: 0.0038 - accuracy: 0.9998
Epoch 90/100
72/72 [==============================] - 0s 6ms/step - loss: 0.0031 - accuracy: 0.9998
Epoch 91/100
72/72 [==============================] - 0s 6ms/step - loss: 0.0036 - accuracy: 0.9998
Epoch 92/100
72/72 [==============================] - 0s 7ms/step - loss: 0.0033 - accuracy: 0.9998
Epoch 93/100
72/72 [==============================] - 0s 6ms/step - loss: 0.0044 - accuracy: 0.9996
Epoch 94/100
72/72 [==============================] - 0s 7ms/step - loss: 0.0029 - accuracy: 0.9998
Epoch 95/100
72/72 [==============================] - 0s 7ms/step - loss: 0.0051 - accuracy: 0.9996
Epoch 96/100
72/72 [==============================] - 1s 11ms/step - loss: 0.0029 - accuracy: 0.9998
Epoch 97/100
72/72 [==============================] - 1s 9ms/step - loss: 0.0037 - accuracy: 0.9996
Epoch 98/100
72/72 [==============================] - 1s 10ms/step - loss: 0.0029 - accuracy: 0.9998
Epoch 99/100
72/72 [==============================] - 1s 9ms/step - loss: 0.0026 - accuracy: 0.9998
Epoch 100/100
72/72 [==============================] - 1s 8ms/step - loss: 0.0030 - accuracy: 0.9998
Epoch 1/100
72/72 [==============================] - 4s 7ms/step - loss: 4.1405 - accuracy: 0.1444
Epoch 2/100
72/72 [==============================] - 0s 6ms/step - loss: 3.5684 - accuracy: 0.2404
Epoch 3/100
72/72 [==============================] - 0s 7ms/step - loss: 3.2020 - accuracy: 0.3285
Epoch 4/100
72/72 [==============================] - 0s 7ms/step - loss: 2.8817 - accuracy: 0.3762
Epoch 5/100
72/72 [==============================] - 1s 7ms/step - loss: 2.6177 - accuracy: 0.4164
Epoch 6/100
72/72 [==============================] - 0s 7ms/step - loss: 2.4018 - accuracy: 0.4571
Epoch 7/100
72/72 [==============================] - 0s 7ms/step - loss: 2.2125 - accuracy: 0.4814
Epoch 8/100
72/72 [==============================] - 1s 7ms/step - loss: 2.0342 - accuracy: 0.5103
Epoch 9/100
72/72 [==============================] - 1s 7ms/step - loss: 1.8939 - accuracy: 0.5418
Epoch 10/100
72/72 [==============================] - 0s 6ms/step - loss: 1.7644 - accuracy: 0.5639
Epoch 11/100
72/72 [==============================] - 1s 10ms/step - loss: 1.6459 - accuracy: 0.5901
Epoch 12/100
72/72 [==============================] - 1s 9ms/step - loss: 1.5298 - accuracy: 0.6157
Epoch 13/100
72/72 [==============================] - 1s 9ms/step - loss: 1.4618 - accuracy: 0.6304
Epoch 14/100
72/72 [==============================] - 1s 10ms/step - loss: 1.3498 - accuracy: 0.6540
Epoch 15/100
72/72 [==============================] - 1s 7ms/step - loss: 1.2863 - accuracy: 0.6678
Epoch 16/100
72/72 [==============================] - 1s 7ms/step - loss: 1.1680 - accuracy: 0.6964
Epoch 17/100
72/72 [==============================] - 1s 7ms/step - loss: 1.0889 - accuracy: 0.7165
Epoch 18/100
72/72 [==============================] - 0s 7ms/step - loss: 1.0221 - accuracy: 0.7308
Epoch 19/100
72/72 [==============================] - 0s 6ms/step - loss: 0.9349 - accuracy: 0.7522
Epoch 20/100
72/72 [==============================] - 1s 7ms/step - loss: 0.8636 - accuracy: 0.7717
Epoch 21/100
72/72 [==============================] - 0s 6ms/step - loss: 0.8068 - accuracy: 0.7841
Epoch 22/100
72/72 [==============================] - 1s 7ms/step - loss: 0.7282 - accuracy: 0.8071
Epoch 23/100
72/72 [==============================] - 0s 6ms/step - loss: 0.6611 - accuracy: 0.8215
Epoch 24/100
72/72 [==============================] - 1s 7ms/step - loss: 0.6109 - accuracy: 0.8351
Epoch 25/100
72/72 [==============================] - 0s 6ms/step - loss: 0.5420 - accuracy: 0.8580
Epoch 26/100
72/72 [==============================] - 1s 8ms/step - loss: 0.4952 - accuracy: 0.8692
Epoch 27/100
72/72 [==============================] - 0s 6ms/step - loss: 0.4477 - accuracy: 0.8847
Epoch 28/100
72/72 [==============================] - 1s 7ms/step - loss: 0.4107 - accuracy: 0.8933
Epoch 29/100
72/72 [==============================] - 0s 6ms/step - loss: 0.3531 - accuracy: 0.9090
Epoch 30/100
72/72 [==============================] - 1s 7ms/step - loss: 0.3382 - accuracy: 0.9143
Epoch 31/100
72/72 [==============================] - 0s 7ms/step - loss: 0.2963 - accuracy: 0.9272
Epoch 32/100
72/72 [==============================] - 0s 7ms/step - loss: 0.2570 - accuracy: 0.9357
Epoch 33/100
72/72 [==============================] - 0s 6ms/step - loss: 0.2423 - accuracy: 0.9381
Epoch 34/100
72/72 [==============================] - 1s 7ms/step - loss: 0.2053 - accuracy: 0.9543
Epoch 35/100
72/72 [==============================] - 1s 9ms/step - loss: 0.1814 - accuracy: 0.9611
Epoch 36/100
72/72 [==============================] - 1s 9ms/step - loss: 0.1387 - accuracy: 0.9746
Epoch 37/100
72/72 [==============================] - 1s 10ms/step - loss: 0.1276 - accuracy: 0.9768
Epoch 38/100
72/72 [==============================] - 1s 12ms/step - loss: 0.0958 - accuracy: 0.9869
Epoch 39/100
72/72 [==============================] - 1s 10ms/step - loss: 0.0895 - accuracy: 0.9884
Epoch 40/100
72/72 [==============================] - 0s 6ms/step - loss: 0.0750 - accuracy: 0.9917
Epoch 41/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0628 - accuracy: 0.9937
Epoch 42/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0547 - accuracy: 0.9939
Epoch 43/100
72/72 [==============================] - 1s 8ms/step - loss: 0.0618 - accuracy: 0.9919
Epoch 44/100
72/72 [==============================] - 1s 7ms/step - loss: 0.1041 - accuracy: 0.9766
Epoch 45/100
72/72 [==============================] - 1s 7ms/step - loss: 0.1998 - accuracy: 0.9405
Epoch 46/100
72/72 [==============================] - 0s 6ms/step - loss: 0.1649 - accuracy: 0.9508
Epoch 47/100
72/72 [==============================] - 1s 7ms/step - loss: 0.1313 - accuracy: 0.9654
Epoch 48/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0720 - accuracy: 0.9862
Epoch 49/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0613 - accuracy: 0.9867
Epoch 50/100
72/72 [==============================] - 0s 7ms/step - loss: 0.0366 - accuracy: 0.9961
Epoch 51/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0207 - accuracy: 0.9991
Epoch 52/100
72/72 [==============================] - 0s 6ms/step - loss: 0.0136 - accuracy: 0.9993
Epoch 53/100
72/72 [==============================] - 1s 8ms/step - loss: 0.0123 - accuracy: 0.9996
Epoch 54/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0125 - accuracy: 0.9991
Epoch 55/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0123 - accuracy: 0.9993
Epoch 56/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0099 - accuracy: 0.9996
Epoch 57/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0081 - accuracy: 0.9998
Epoch 58/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0096 - accuracy: 0.9996
Epoch 59/100
72/72 [==============================] - 1s 11ms/step - loss: 0.0106 - accuracy: 0.9989
Epoch 60/100
72/72 [==============================] - 1s 11ms/step - loss: 0.0157 - accuracy: 0.9983
Epoch 61/100
72/72 [==============================] - 1s 9ms/step - loss: 0.0951 - accuracy: 0.9711
Epoch 62/100
72/72 [==============================] - 1s 11ms/step - loss: 0.3823 - accuracy: 0.8876
Epoch 63/100
72/72 [==============================] - 1s 8ms/step - loss: 0.1605 - accuracy: 0.9517
Epoch 64/100
72/72 [==============================] - 0s 6ms/step - loss: 0.0937 - accuracy: 0.9729
Epoch 65/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0668 - accuracy: 0.9845
Epoch 66/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0172 - accuracy: 0.9985
Epoch 67/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0093 - accuracy: 0.9996
Epoch 68/100
72/72 [==============================] - 0s 6ms/step - loss: 0.0071 - accuracy: 0.9998
Epoch 69/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0059 - accuracy: 0.9998
Epoch 70/100
72/72 [==============================] - 0s 7ms/step - loss: 0.0066 - accuracy: 0.9998
Epoch 71/100
72/72 [==============================] - 0s 7ms/step - loss: 0.0078 - accuracy: 0.9996
Epoch 72/100
72/72 [==============================] - 0s 7ms/step - loss: 0.0050 - accuracy: 0.9998
Epoch 73/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0064 - accuracy: 0.9996
Epoch 74/100
72/72 [==============================] - 0s 6ms/step - loss: 0.0049 - accuracy: 0.9996
Epoch 75/100
72/72 [==============================] - 0s 7ms/step - loss: 0.0060 - accuracy: 0.9996
Epoch 76/100
72/72 [==============================] - 0s 6ms/step - loss: 0.0057 - accuracy: 0.9996
Epoch 77/100
72/72 [==============================] - 1s 8ms/step - loss: 0.0038 - accuracy: 0.9998
Epoch 78/100
72/72 [==============================] - 0s 7ms/step - loss: 0.0058 - accuracy: 0.9996
Epoch 79/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0047 - accuracy: 0.9998
Epoch 80/100
72/72 [==============================] - 0s 7ms/step - loss: 0.0035 - accuracy: 0.9998
Epoch 81/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0053 - accuracy: 0.9991
Epoch 82/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0048 - accuracy: 0.9998
Epoch 83/100
72/72 [==============================] - 1s 11ms/step - loss: 0.0096 - accuracy: 0.9985
Epoch 84/100
72/72 [==============================] - 1s 9ms/step - loss: 0.1520 - accuracy: 0.9578
Epoch 85/100
72/72 [==============================] - 1s 14ms/step - loss: 0.4469 - accuracy: 0.8624
Epoch 86/100
72/72 [==============================] - 1s 10ms/step - loss: 0.2240 - accuracy: 0.9379
Epoch 87/100
72/72 [==============================] - 1s 8ms/step - loss: 0.0695 - accuracy: 0.9803
Epoch 88/100
72/72 [==============================] - 0s 6ms/step - loss: 0.0358 - accuracy: 0.9917
Epoch 89/100
72/72 [==============================] - 0s 7ms/step - loss: 0.0140 - accuracy: 0.9985
Epoch 90/100
72/72 [==============================] - 0s 7ms/step - loss: 0.0065 - accuracy: 0.9996
Epoch 91/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0045 - accuracy: 0.9998
Epoch 92/100
72/72 [==============================] - 1s 7ms/step - loss: 0.0048 - accuracy: 0.9996
Epoch 93/100
72/72 [==============================] - 0s 7ms/step - loss: 0.0035 - accuracy: 0.9998
Epoch 94/100
72/72 [==============================] - 0s 6ms/step - loss: 0.0037 - accuracy: 0.9998
Epoch 95/100
72/72 [==============================] - 0s 7ms/step - loss: 0.0050 - accuracy: 0.9996
Epoch 96/100
72/72 [==============================] - 1s 8ms/step - loss: 0.0032 - accuracy: 0.9998
Epoch 97/100
72/72 [==============================] - 0s 7ms/step - loss: 0.0036 - accuracy: 0.9996
Epoch 98/100
72/72 [==============================] - 0s 7ms/step - loss: 0.0037 - accuracy: 0.9996
Epoch 99/100
72/72 [==============================] - 0s 6ms/step - loss: 0.0025 - accuracy: 0.9998
Epoch 100/100

### STL-10

In [ ]:
import tensorflow_datasets as tfds

# Load the STL-10 dataset
dataset_name = "stl10"
train_dataset, test_dataset = tfds.load(name=dataset_name, split=["train", "test"], as_supervised=True)

# Iterate through the datasets to get features and labels
X_train = []
y_train = []
for image, label in tfds.as_numpy(train_dataset):
    X_train.append(image)
    y_train.append(label)

X_test = []
y_test = []
for image, label in tfds.as_numpy(test_dataset):
    X_test.append(image)
    y_test.append(label)

# Convert lists to numpy arrays
import numpy as np
X_train = np.array(X_train)
y_train = np.array(y_train)
X_test = np.array(X_test)
y_test = np.array(y_test)

# Print the shape of the arrays
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

Downloading and preparing dataset 2.46 GiB (download: 2.46 GiB, generated: 1.86 GiB, total: 4.32 GiB) to /root/tensorflow_datasets/stl10/1.0.0...

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

Generating splits...:   0%|          | 0/3 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/5000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/stl10/1.0.0.incomplete014JMI/stl10-train.tfrecord*...:   0%|          | 0/…

Generating test examples...:   0%|          | 0/8000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/stl10/1.0.0.incomplete014JMI/stl10-test.tfrecord*...:   0%|          | 0/8…

Generating unlabelled examples...:   0%|          | 0/100000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/stl10/1.0.0.incomplete014JMI/stl10-unlabelled.tfrecord*...:   0%|         …

Dataset stl10 downloaded and prepared to /root/tensorflow_datasets/stl10/1.0.0. Subsequent calls will reuse this data.
X_train shape: (5000, 96, 96, 3)
y_train shape: (5000,)
X_test shape: (8000, 96, 96, 3)
y_test shape: (8000,)

In [ ]:
import tensorflow as tf
y_train = tf.keras.utils.to_categorical(y_train, num_classes=10)
y_test = tf.keras.utils.to_categorical(y_test, num_classes=10)

In [ ]:
x = np.concatenate((X_train,X_test), axis=0)
x.shape

(13000, 96, 96, 3)

In [ ]:
y = np.concatenate((y_train,y_test),axis=0)
y.shape

(13000, 10)

In [ ]:
# import tensorflow as tf
# y = tf.keras.utils.to_categorical(y, num_classes=102)
# # y_test = tf.keras.utils.to_categorical(y_test, num_classes=102)
# y.shape

In [ ]:
# model.fit(X_train_resized, y_train, batch_size=128, epochs=100, validation_data=(X_test_resized, y_test))
import tensorflow as tf
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras import layers
from sklearn.model_selection import KFold
def create_model():
    model = keras.Sequential([
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(96, 96, 3)),  # Update input shape
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(64, activation='relu'),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])

    return model

# Define the number of folds for cross-validation
num_folds = 2
kf = KFold(n_splits=num_folds, shuffle=True)

fold_accuracy = []
for train_index, val_index in kf.split(x):
    # Split the data into training and validation sets
    x_train_fold, x_val_fold = x[train_index], x[val_index]
    y_train_fold, y_val_fold = y[train_index], y[val_index]
    with tf.device('/device:GPU:0'):
      model = create_model()
      model.fit(x_train_fold, y_train_fold, epochs=100, batch_size=64, verbose=1)
    # Evaluate the model on the validation data
      _, accuracy = model.evaluate(x_val_fold, y_val_fold, verbose=0)
      fold_accuracy.append(accuracy)


average_accuracy = np.mean(fold_accuracy)
print('Average accuracy:', average_accuracy)
i = 0
float2 = "{0:.2f}"
for score in fold_accuracy:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Epoch 1/100
102/102 [==============================] - 7s 26ms/step - loss: 15.4767 - accuracy: 0.2457
Epoch 2/100
102/102 [==============================] - 3s 27ms/step - loss: 1.5720 - accuracy: 0.4152
Epoch 3/100
102/102 [==============================] - 3s 25ms/step - loss: 1.2025 - accuracy: 0.5600
Epoch 4/100
102/102 [==============================] - 2s 24ms/step - loss: 0.9135 - accuracy: 0.6754
Epoch 5/100
102/102 [==============================] - 2s 22ms/step - loss: 0.6552 - accuracy: 0.7683
Epoch 6/100
102/102 [==============================] - 2s 21ms/step - loss: 0.4551 - accuracy: 0.8486
Epoch 7/100
102/102 [==============================] - 2s 22ms/step - loss: 0.3305 - accuracy: 0.8932
Epoch 8/100
102/102 [==============================] - 2s 22ms/step - loss: 0.2340 - accuracy: 0.9280
Epoch 9/100
102/102 [==============================] - 3s 28ms/step - loss: 0.1670 - accuracy: 0.9497
Epoch 10/100
102/102 [==============================] - 2s 23ms/step - loss: 0.1386 - accuracy: 0.9606
Epoch 11/100
102/102 [==============================] - 2s 22ms/step - loss: 0.1479 - accuracy: 0.9557
Epoch 12/100
102/102 [==============================] - 2s 22ms/step - loss: 0.1040 - accuracy: 0.9714
Epoch 13/100
102/102 [==============================] - 2s 22ms/step - loss: 0.0784 - accuracy: 0.9780
Epoch 14/100
102/102 [==============================] - 2s 24ms/step - loss: 0.1090 - accuracy: 0.9691
Epoch 15/100
102/102 [==============================] - 3s 25ms/step - loss: 0.0851 - accuracy: 0.9748
Epoch 16/100
102/102 [==============================] - 2s 22ms/step - loss: 0.0715 - accuracy: 0.9794
Epoch 17/100
102/102 [==============================] - 2s 21ms/step - loss: 0.0644 - accuracy: 0.9837
Epoch 18/100
102/102 [==============================] - 2s 21ms/step - loss: 0.0482 - accuracy: 0.9872
Epoch 19/100
102/102 [==============================] - 2s 23ms/step - loss: 0.0469 - accuracy: 0.9874
Epoch 20/100
102/102 [==============================] - 2s 23ms/step - loss: 0.0210 - accuracy: 0.9957
Epoch 21/100
102/102 [==============================] - 2s 24ms/step - loss: 0.0448 - accuracy: 0.9877
Epoch 22/100
102/102 [==============================] - 2s 21ms/step - loss: 0.0572 - accuracy: 0.9815
Epoch 23/100
102/102 [==============================] - 2s 21ms/step - loss: 0.0573 - accuracy: 0.9845
Epoch 24/100
102/102 [==============================] - 2s 21ms/step - loss: 0.0427 - accuracy: 0.9882
Epoch 25/100
102/102 [==============================] - 2s 21ms/step - loss: 0.0560 - accuracy: 0.9837
Epoch 26/100
102/102 [==============================] - 2s 24ms/step - loss: 0.0371 - accuracy: 0.9903
Epoch 27/100
102/102 [==============================] - 3s 25ms/step - loss: 0.0277 - accuracy: 0.9917
Epoch 28/100
102/102 [==============================] - 2s 23ms/step - loss: 0.0178 - accuracy: 0.9942
Epoch 29/100
102/102 [==============================] - 2s 21ms/step - loss: 0.0309 - accuracy: 0.9920
Epoch 30/100
102/102 [==============================] - 2s 21ms/step - loss: 0.0640 - accuracy: 0.9826
Epoch 31/100
102/102 [==============================] - 2s 21ms/step - loss: 0.1636 - accuracy: 0.9597
Epoch 32/100
102/102 [==============================] - 2s 24ms/step - loss: 0.1151 - accuracy: 0.9658
Epoch 33/100
102/102 [==============================] - 2s 24ms/step - loss: 0.0701 - accuracy: 0.9814
Epoch 34/100
102/102 [==============================] - 2s 22ms/step - loss: 0.0515 - accuracy: 0.9888
Epoch 35/100
102/102 [==============================] - 2s 22ms/step - loss: 0.0588 - accuracy: 0.9858
Epoch 36/100
102/102 [==============================] - 2s 24ms/step - loss: 0.0535 - accuracy: 0.9840
Epoch 37/100
102/102 [==============================] - 2s 21ms/step - loss: 0.0320 - accuracy: 0.9914
Epoch 38/100
102/102 [==============================] - 2s 24ms/step - loss: 0.0207 - accuracy: 0.9943
Epoch 39/100
102/102 [==============================] - 2s 24ms/step - loss: 0.0081 - accuracy: 0.9980
Epoch 40/100
102/102 [==============================] - 2s 22ms/step - loss: 0.0016 - accuracy: 0.9994
Epoch 41/100
102/102 [==============================] - 2s 21ms/step - loss: 6.6188e-04 - accuracy: 1.0000
Epoch 42/100
102/102 [==============================] - 2s 21ms/step - loss: 4.0209e-04 - accuracy: 1.0000
Epoch 43/100
102/102 [==============================] - 2s 22ms/step - loss: 3.2453e-04 - accuracy: 1.0000
Epoch 44/100
102/102 [==============================] - 3s 26ms/step - loss: 2.7521e-04 - accuracy: 1.0000
Epoch 45/100
102/102 [==============================] - 2s 23ms/step - loss: 2.4503e-04 - accuracy: 1.0000
Epoch 46/100
102/102 [==============================] - 2s 21ms/step - loss: 1.9825e-04 - accuracy: 1.0000
Epoch 47/100
102/102 [==============================] - 2s 21ms/step - loss: 1.6753e-04 - accuracy: 1.0000
Epoch 48/100
102/102 [==============================] - 2s 21ms/step - loss: 1.4732e-04 - accuracy: 1.0000
Epoch 49/100
102/102 [==============================] - 2s 23ms/step - loss: 1.3295e-04 - accuracy: 1.0000
Epoch 50/100
102/102 [==============================] - 3s 25ms/step - loss: 1.1911e-04 - accuracy: 1.0000
Epoch 51/100
102/102 [==============================] - 2s 22ms/step - loss: 1.1252e-04 - accuracy: 1.0000
Epoch 52/100
102/102 [==============================] - 2s 22ms/step - loss: 9.9973e-05 - accuracy: 1.0000
Epoch 53/100
102/102 [==============================] - 2s 22ms/step - loss: 9.0353e-05 - accuracy: 1.0000
Epoch 54/100
102/102 [==============================] - 2s 21ms/step - loss: 8.5101e-05 - accuracy: 1.0000
Epoch 55/100
102/102 [==============================] - 2s 22ms/step - loss: 7.7675e-05 - accuracy: 1.0000
Epoch 56/100
102/102 [==============================] - 3s 25ms/step - loss: 7.2726e-05 - accuracy: 1.0000
Epoch 57/100
102/102 [==============================] - 2s 22ms/step - loss: 6.6079e-05 - accuracy: 1.0000
Epoch 58/100
102/102 [==============================] - 2s 21ms/step - loss: 6.2054e-05 - accuracy: 1.0000
Epoch 59/100
102/102 [==============================] - 2s 20ms/step - loss: 5.7178e-05 - accuracy: 1.0000
Epoch 60/100
102/102 [==============================] - 2s 21ms/step - loss: 5.2641e-05 - accuracy: 1.0000
Epoch 61/100
102/102 [==============================] - 2s 24ms/step - loss: 4.9636e-05 - accuracy: 1.0000
Epoch 62/100
102/102 [==============================] - 3s 28ms/step - loss: 4.6051e-05 - accuracy: 1.0000
Epoch 63/100
102/102 [==============================] - 2s 22ms/step - loss: 4.2350e-05 - accuracy: 1.0000
Epoch 64/100
102/102 [==============================] - 2s 20ms/step - loss: 3.9495e-05 - accuracy: 1.0000
Epoch 65/100
102/102 [==============================] - 2s 21ms/step - loss: 3.6952e-05 - accuracy: 1.0000
Epoch 66/100
102/102 [==============================] - 2s 19ms/step - loss: 3.3889e-05 - accuracy: 1.0000
Epoch 67/100
102/102 [==============================] - 2s 20ms/step - loss: 3.1881e-05 - accuracy: 1.0000
Epoch 68/100
102/102 [==============================] - 3s 25ms/step - loss: 3.0020e-05 - accuracy: 1.0000
Epoch 69/100
102/102 [==============================] - 2s 23ms/step - loss: 2.8626e-05 - accuracy: 1.0000
Epoch 70/100
102/102 [==============================] - 2s 19ms/step - loss: 2.6250e-05 - accuracy: 1.0000
Epoch 71/100
102/102 [==============================] - 2s 17ms/step - loss: 2.4849e-05 - accuracy: 1.0000
Epoch 72/100
102/102 [==============================] - 2s 17ms/step - loss: 2.3434e-05 - accuracy: 1.0000
Epoch 73/100
102/102 [==============================] - 2s 15ms/step - loss: 2.1898e-05 - accuracy: 1.0000
Epoch 74/100
102/102 [==============================] - 2s 15ms/step - loss: 2.1013e-05 - accuracy: 1.0000
Epoch 75/100
102/102 [==============================] - 2s 16ms/step - loss: 1.9607e-05 - accuracy: 1.0000
Epoch 76/100
102/102 [==============================] - 2s 19ms/step - loss: 1.8494e-05 - accuracy: 1.0000
Epoch 77/100
102/102 [==============================] - 2s 22ms/step - loss: 1.7304e-05 - accuracy: 1.0000
Epoch 78/100
102/102 [==============================] - 2s 16ms/step - loss: 1.6194e-05 - accuracy: 1.0000
Epoch 79/100
102/102 [==============================] - 2s 16ms/step - loss: 1.5404e-05 - accuracy: 1.0000
Epoch 80/100
102/102 [==============================] - 2s 16ms/step - loss: 1.4299e-05 - accuracy: 1.0000
Epoch 81/100
102/102 [==============================] - 2s 15ms/step - loss: 1.3582e-05 - accuracy: 1.0000
Epoch 82/100
102/102 [==============================] - 2s 16ms/step - loss: 1.2687e-05 - accuracy: 1.0000
Epoch 83/100
102/102 [==============================] - 2s 15ms/step - loss: 1.1983e-05 - accuracy: 1.0000
Epoch 84/100
102/102 [==============================] - 2s 21ms/step - loss: 1.1262e-05 - accuracy: 1.0000
Epoch 85/100
102/102 [==============================] - 2s 20ms/step - loss: 1.0573e-05 - accuracy: 1.0000
Epoch 86/100
102/102 [==============================] - 2s 16ms/step - loss: 1.0056e-05 - accuracy: 1.0000
Epoch 87/100
102/102 [==============================] - 2s 16ms/step - loss: 9.4533e-06 - accuracy: 1.0000
Epoch 88/100
102/102 [==============================] - 2s 15ms/step - loss: 8.9104e-06 - accuracy: 1.0000
Epoch 89/100
102/102 [==============================] - 2s 15ms/step - loss: 8.4390e-06 - accuracy: 1.0000
Epoch 90/100
102/102 [==============================] - 2s 15ms/step - loss: 7.9682e-06 - accuracy: 1.0000
Epoch 91/100
102/102 [==============================] - 2s 15ms/step - loss: 7.5277e-06 - accuracy: 1.0000
Epoch 92/100
102/102 [==============================] - 2s 24ms/step - loss: 7.1646e-06 - accuracy: 1.0000
Epoch 93/100
102/102 [==============================] - 2s 18ms/step - loss: 6.7592e-06 - accuracy: 1.0000
Epoch 94/100
102/102 [==============================] - 2s 15ms/step - loss: 6.3922e-06 - accuracy: 1.0000
Epoch 95/100
102/102 [==============================] - 2s 15ms/step - loss: 6.0297e-06 - accuracy: 1.0000
Epoch 96/100
102/102 [==============================] - 2s 15ms/step - loss: 5.6706e-06 - accuracy: 1.0000
Epoch 97/100
102/102 [==============================] - 2s 15ms/step - loss: 5.3918e-06 - accuracy: 1.0000
Epoch 98/100
102/102 [==============================] - 2s 15ms/step - loss: 5.1029e-06 - accuracy: 1.0000
Epoch 99/100
102/102 [==============================] - 2s 17ms/step - loss: 4.8344e-06 - accuracy: 1.0000
Epoch 100/100
102/102 [==============================] - 2s 22ms/step - loss: 4.5887e-06 - accuracy: 1.0000
Epoch 1/100
102/102 [==============================] - 4s 17ms/step - loss: 17.0080 - accuracy: 0.2469
Epoch 2/100
102/102 [==============================] - 2s 16ms/step - loss: 1.4873 - accuracy: 0.4640
Epoch 3/100
102/102 [==============================] - 2s 15ms/step - loss: 0.9886 - accuracy: 0.6558
Epoch 4/100
102/102 [==============================] - 2s 20ms/step - loss: 0.5909 - accuracy: 0.7935
Epoch 5/100
102/102 [==============================] - 3s 26ms/step - loss: 0.3324 - accuracy: 0.8922
Epoch 6/100
102/102 [==============================] - 2s 16ms/step - loss: 0.1668 - accuracy: 0.9531
Epoch 7/100
102/102 [==============================] - 2s 15ms/step - loss: 0.1166 - accuracy: 0.9665
Epoch 8/100
102/102 [==============================] - 2s 15ms/step - loss: 0.1007 - accuracy: 0.9718
Epoch 9/100
102/102 [==============================] - 2s 15ms/step - loss: 0.0970 - accuracy: 0.9751
Epoch 10/100
102/102 [==============================] - 2s 15ms/step - loss: 0.0685 - accuracy: 0.9826
Epoch 11/100
102/102 [==============================] - 2s 17ms/step - loss: 0.0355 - accuracy: 0.9908
Epoch 12/100
102/102 [==============================] - 2s 22ms/step - loss: 0.0206 - accuracy: 0.9952
Epoch 13/100
102/102 [==============================] - 2s 17ms/step - loss: 0.0224 - accuracy: 0.9958
Epoch 14/100
102/102 [==============================] - 2s 16ms/step - loss: 0.0862 - accuracy: 0.9723
Epoch 15/100
102/102 [==============================] - 2s 16ms/step - loss: 0.1053 - accuracy: 0.9698
Epoch 16/100
102/102 [==============================] - 2s 16ms/step - loss: 0.1148 - accuracy: 0.9669
Epoch 17/100
102/102 [==============================] - 2s 15ms/step - loss: 0.0988 - accuracy: 0.9728
Epoch 18/100
102/102 [==============================] - 2s 15ms/step - loss: 0.0855 - accuracy: 0.9763
Epoch 19/100
102/102 [==============================] - 2s 20ms/step - loss: 0.0322 - accuracy: 0.9922
Epoch 20/100
102/102 [==============================] - 3s 26ms/step - loss: 0.0220 - accuracy: 0.9943
Epoch 21/100
102/102 [==============================] - 2s 16ms/step - loss: 0.0186 - accuracy: 0.9949
Epoch 22/100
102/102 [==============================] - 2s 16ms/step - loss: 0.0128 - accuracy: 0.9969
Epoch 23/100
102/102 [==============================] - 2s 16ms/step - loss: 0.0037 - accuracy: 0.9992
Epoch 24/100
102/102 [==============================] - 2s 16ms/step - loss: 0.0014 - accuracy: 0.9998
Epoch 25/100
102/102 [==============================] - 2s 16ms/step - loss: 0.0053 - accuracy: 0.9982
Epoch 26/100
102/102 [==============================] - 2s 16ms/step - loss: 8.2515e-04 - accuracy: 1.0000
Epoch 27/100
102/102 [==============================] - 2s 22ms/step - loss: 4.6848e-04 - accuracy: 1.0000
Epoch 28/100
102/102 [==============================] - 2s 18ms/step - loss: 2.4505e-04 - accuracy: 1.0000
Epoch 29/100
102/102 [==============================] - 2s 16ms/step - loss: 1.9531e-04 - accuracy: 1.0000
Epoch 30/100
102/102 [==============================] - 2s 16ms/step - loss: 1.6580e-04 - accuracy: 1.0000
Epoch 31/100
102/102 [==============================] - 2s 16ms/step - loss: 1.4385e-04 - accuracy: 1.0000
Epoch 32/100
102/102 [==============================] - 2s 16ms/step - loss: 1.2669e-04 - accuracy: 1.0000
Epoch 33/100
102/102 [==============================] - 2s 16ms/step - loss: 1.1349e-04 - accuracy: 1.0000
Epoch 34/100
102/102 [==============================] - 2s 19ms/step - loss: 1.0205e-04 - accuracy: 1.0000
Epoch 35/100
102/102 [==============================] - 3s 26ms/step - loss: 9.2677e-05 - accuracy: 1.0000
Epoch 36/100
102/102 [==============================] - 2s 15ms/step - loss: 8.4555e-05 - accuracy: 1.0000
Epoch 37/100
102/102 [==============================] - 2s 16ms/step - loss: 7.7213e-05 - accuracy: 1.0000
Epoch 38/100
102/102 [==============================] - 2s 15ms/step - loss: 7.1192e-05 - accuracy: 1.0000
Epoch 39/100
102/102 [==============================] - 2s 16ms/step - loss: 6.5730e-05 - accuracy: 1.0000
Epoch 40/100
102/102 [==============================] - 2s 16ms/step - loss: 6.0642e-05 - accuracy: 1.0000
Epoch 41/100
102/102 [==============================] - 2s 16ms/step - loss: 5.6205e-05 - accuracy: 1.0000
Epoch 42/100
102/102 [==============================] - 2s 23ms/step - loss: 5.2262e-05 - accuracy: 1.0000
Epoch 43/100
102/102 [==============================] - 2s 17ms/step - loss: 4.8620e-05 - accuracy: 1.0000
Epoch 44/100
102/102 [==============================] - 2s 15ms/step - loss: 4.5310e-05 - accuracy: 1.0000
Epoch 45/100
102/102 [==============================] - 2s 16ms/step - loss: 4.2339e-05 - accuracy: 1.0000
Epoch 46/100
102/102 [==============================] - 2s 16ms/step - loss: 3.9582e-05 - accuracy: 1.0000
Epoch 47/100
102/102 [==============================] - 2s 15ms/step - loss: 3.7002e-05 - accuracy: 1.0000
Epoch 48/100
102/102 [==============================] - 2s 16ms/step - loss: 3.4598e-05 - accuracy: 1.0000
Epoch 49/100
102/102 [==============================] - 2s 18ms/step - loss: 3.2515e-05 - accuracy: 1.0000
Epoch 50/100
102/102 [==============================] - 2s 22ms/step - loss: 3.0469e-05 - accuracy: 1.0000
Epoch 51/100
102/102 [==============================] - 2s 21ms/step - loss: 2.8597e-05 - accuracy: 1.0000
Epoch 52/100
102/102 [==============================] - 2s 18ms/step - loss: 2.6847e-05 - accuracy: 1.0000
Epoch 53/100
102/102 [==============================] - 2s 15ms/step - loss: 2.5268e-05 - accuracy: 1.0000
Epoch 54/100
102/102 [==============================] - 2s 15ms/step - loss: 2.3761e-05 - accuracy: 1.0000
Epoch 55/100
102/102 [==============================] - 2s 15ms/step - loss: 2.2302e-05 - accuracy: 1.0000
Epoch 56/100
102/102 [==============================] - 2s 15ms/step - loss: 2.1003e-05 - accuracy: 1.0000
Epoch 57/100
102/102 [==============================] - 2s 16ms/step - loss: 1.9793e-05 - accuracy: 1.0000
Epoch 58/100
102/102 [==============================] - 2s 24ms/step - loss: 1.8628e-05 - accuracy: 1.0000
Epoch 59/100
102/102 [==============================] - 2s 17ms/step - loss: 1.7585e-05 - accuracy: 1.0000
Epoch 60/100
102/102 [==============================] - 2s 15ms/step - loss: 1.6586e-05 - accuracy: 1.0000
Epoch 61/100
102/102 [==============================] - 2s 16ms/step - loss: 1.5634e-05 - accuracy: 1.0000
Epoch 62/100
102/102 [==============================] - 2s 15ms/step - loss: 1.4739e-05 - accuracy: 1.0000
Epoch 63/100
102/102 [==============================] - 2s 15ms/step - loss: 1.3928e-05 - accuracy: 1.0000
Epoch 64/100
102/102 [==============================] - 2s 16ms/step - loss: 1.3148e-05 - accuracy: 1.0000
Epoch 65/100
102/102 [==============================] - 2s 17ms/step - loss: 1.2444e-05 - accuracy: 1.0000
Epoch 66/100
102/102 [==============================] - 2s 22ms/step - loss: 1.1773e-05 - accuracy: 1.0000
Epoch 67/100
102/102 [==============================] - 2s 16ms/step - loss: 1.1135e-05 - accuracy: 1.0000
Epoch 68/100
102/102 [==============================] - 2s 16ms/step - loss: 1.0485e-05 - accuracy: 1.0000
Epoch 69/100
102/102 [==============================] - 2s 16ms/step - loss: 9.9418e-06 - accuracy: 1.0000
Epoch 70/100
102/102 [==============================] - 2s 16ms/step - loss: 9.4002e-06 - accuracy: 1.0000
Epoch 71/100
102/102 [==============================] - 2s 16ms/step - loss: 8.8670e-06 - accuracy: 1.0000
Epoch 72/100
102/102 [==============================] - 2s 16ms/step - loss: 8.3990e-06 - accuracy: 1.0000
Epoch 73/100
102/102 [==============================] - 2s 20ms/step - loss: 7.9361e-06 - accuracy: 1.0000
Epoch 74/100
102/102 [==============================] - 2s 20ms/step - loss: 7.5144e-06 - accuracy: 1.0000
Epoch 75/100
102/102 [==============================] - 2s 16ms/step - loss: 7.1149e-06 - accuracy: 1.0000
Epoch 76/100
102/102 [==============================] - 2s 17ms/step - loss: 6.7301e-06 - accuracy: 1.0000
Epoch 77/100
102/102 [==============================] - 2s 16ms/step - loss: 6.3831e-06 - accuracy: 1.0000
Epoch 78/100
102/102 [==============================] - 2s 15ms/step - loss: 6.0375e-06 - accuracy: 1.0000
Epoch 79/100
102/102 [==============================] - 2s 15ms/step - loss: 5.7042e-06 - accuracy: 1.0000
Epoch 80/100
102/102 [==============================] - 2s 16ms/step - loss: 5.4069e-06 - accuracy: 1.0000
Epoch 81/100
102/102 [==============================] - 2s 20ms/step - loss: 5.1219e-06 - accuracy: 1.0000
Epoch 82/100
102/102 [==============================] - 2s 18ms/step - loss: 4.8428e-06 - accuracy: 1.0000
Epoch 83/100
102/102 [==============================] - 2s 15ms/step - loss: 4.5867e-06 - accuracy: 1.0000
Epoch 84/100
102/102 [==============================] - 2s 15ms/step - loss: 4.3443e-06 - accuracy: 1.0000
Epoch 85/100
102/102 [==============================] - 2s 16ms/step - loss: 4.1240e-06 - accuracy: 1.0000
Epoch 86/100
102/102 [==============================] - 2s 15ms/step - loss: 3.8919e-06 - accuracy: 1.0000
Epoch 87/100
102/102 [==============================] - 2s 16ms/step - loss: 3.7025e-06 - accuracy: 1.0000
Epoch 88/100
102/102 [==============================] - 2s 17ms/step - loss: 3.4912e-06 - accuracy: 1.0000
Epoch 89/100
102/102 [==============================] - 2s 21ms/step - loss: 3.3003e-06 - accuracy: 1.0000
Epoch 90/100

### TinyImageNet

In [ ]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.utils import get_file
from tensorflow.keras.preprocessing.image import load_img, img_to_array
import os
import pandas as pd

# Download and extract the Tiny ImageNet dataset
url = "http://cs231n.stanford.edu/tiny-imagenet-200.zip"
zip_path = get_file("tiny-imagenet-200.zip", origin=url, extract=True)

# Set the path to the extracted dataset directory
dataset_dir = os.path.join(os.path.dirname(zip_path), "tiny-imagenet-200")

# Load the class labels
class_labels = pd.read_csv(os.path.join(dataset_dir, "wnids.txt"), header=None)
class_labels = class_labels[0].tolist()

# Load the class descriptions
class_desc = {}
with open(os.path.join(dataset_dir, "words.txt"), "r") as f:
    lines = f.readlines()
    for line in lines:
        parts = line.split("\t")
        class_desc[parts[0]] = parts[1]

# Create a dictionary to map class IDs to class descriptions
class_id_to_desc = {class_id: class_desc[class_id] for class_id in class_labels}

# Load the training data
X_train = []
y_train = []
for class_id in class_labels:
    class_dir = os.path.join(dataset_dir, "train", class_id, "images")
    for img_file in os.listdir(class_dir):
        img_path = os.path.join(class_dir, img_file)
        img = load_img(img_path, target_size=(64, 64))
        img_array = img_to_array(img)
        X_train.append(img_array)
        y_train.append(class_id)

X_train = np.array(X_train)
y_train = np.array(y_train)

# Print the shape of the training data
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)

Downloading data from http://cs231n.stanford.edu/tiny-imagenet-200.zip
248100043/248100043 [==============================] - 16s 0us/step
X_train shape: (100000, 64, 64, 3)
y_train shape: (100000,)

In [ ]:
# model.fit(X_train_resized, y_train, batch_size=128, epochs=100, validation_data=(X_test_resized, y_test))
import tensorflow as tf
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras import layers
from sklearn.model_selection import KFold
def create_model():
    model = keras.Sequential([
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(28, 28, 3)),  # Update input shape
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(64, activation='relu'),
        keras.layers.Dense(1, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])

    return model

# Define the number of folds for cross-validation
num_folds = 2
kf = KFold(n_splits=num_folds, shuffle=True)
x=X_train
fold_accuracy = []
for train_index, val_index in kf.split(x):
    # Split the data into training and validation sets
    x_train_fold, x_val_fold = x[train_index], x[val_index]
    y_train_fold, y_val_fold = y[train_index], y[val_index]
    with tf.device('/device:GPU:0'):
      model = create_model()
      model.fit(x_train_fold, y_train_fold, epochs=100, batch_size=64, verbose=1)
    # Evaluate the model on the validation data
      _, accuracy = model.evaluate(x_val_fold, y_val_fold, verbose=0)
      fold_accuracy.append(accuracy)


average_accuracy = np.mean(fold_accuracy)
print('Average accuracy:', average_accuracy)
i = 0
float2 = "{0:.2f}"
for score in fold_accuracy:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

## K-Fold cross validation : (5)

### MNIST

In [ ]:
import numpy as np
from tensorflow import keras
from sklearn.model_selection import KFold

(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()
# Concatenate the entire dataset
x = np.concatenate((x_train, x_test), axis=0)
y = np.concatenate((y_train, y_test), axis=0)
def create_model():
    model = keras.Sequential([
        keras.layers.Flatten(input_shape=(28, 28)),
        keras.layers.Dense(128, activation='relu'),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model

kf= KFold(n_splits=5, shuffle=True, random_state=42)

fold_accuracy = []
for train_index, val_index in kf.split(x):
    # Split the data into training and validation sets
    x_train_fold, x_val_fold = x[train_index], x[val_index]
    y_train_fold, y_val_fold = y[train_index], y[val_index]
    model = create_model()
    model.fit(x_train_fold, y_train_fold, epochs=10, batch_size=64, verbose=1)
    # Evaluate the model on the validation data
    _, accuracy = model.evaluate(x_val_fold, y_val_fold, verbose=0)
    fold_accuracy.append(accuracy)


average_accuracy = np.mean(fold_accuracy)
print('Average accuracy:', average_accuracy)
i = 0
float2 = "{0:.2f}"
for score in fold_accuracy:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
11490434/11490434 [==============================] - 0s 0us/step
Epoch 1/10
875/875 [==============================] - 9s 5ms/step - loss: 3.6378 - accuracy: 0.8596
Epoch 2/10
875/875 [==============================] - 3s 4ms/step - loss: 0.4427 - accuracy: 0.9049
Epoch 3/10
875/875 [==============================] - 3s 4ms/step - loss: 0.2839 - accuracy: 0.9284
Epoch 4/10
875/875 [==============================] - 4s 5ms/step - loss: 0.2231 - accuracy: 0.9416
Epoch 5/10
875/875 [==============================] - 3s 4ms/step - loss: 0.2062 - accuracy: 0.9468
Epoch 6/10
875/875 [==============================] - 3s 4ms/step - loss: 0.1938 - accuracy: 0.9493
Epoch 7/10
875/875 [==============================] - 3s 4ms/step - loss: 0.1723 - accuracy: 0.9532
Epoch 8/10
875/875 [==============================] - 4s 4ms/step - loss: 0.1746 - accuracy: 0.9546
Epoch 9/10
875/875 [==============================] - 3s 4ms/step - loss: 0.1613 - accuracy: 0.9578
Epoch 10/10
875/875 [==============================] - 3s 4ms/step - loss: 0.1476 - accuracy: 0.9604
Epoch 1/10
875/875 [==============================] - 6s 4ms/step - loss: 3.2474 - accuracy: 0.8633
Epoch 2/10
875/875 [==============================] - 3s 4ms/step - loss: 0.4169 - accuracy: 0.9106
Epoch 3/10
875/875 [==============================] - 3s 4ms/step - loss: 0.2578 - accuracy: 0.9346
Epoch 4/10
875/875 [==============================] - 4s 5ms/step - loss: 0.2118 - accuracy: 0.9419
Epoch 5/10
875/875 [==============================] - 3s 4ms/step - loss: 0.1968 - accuracy: 0.9455
Epoch 6/10
875/875 [==============================] - 3s 4ms/step - loss: 0.1811 - accuracy: 0.9514
Epoch 7/10
875/875 [==============================] - 3s 4ms/step - loss: 0.1692 - accuracy: 0.9537
Epoch 8/10
875/875 [==============================] - 4s 5ms/step - loss: 0.1612 - accuracy: 0.9562
Epoch 9/10
875/875 [==============================] - 3s 4ms/step - loss: 0.1619 - accuracy: 0.9575
Epoch 10/10
875/875 [==============================] - 3s 4ms/step - loss: 0.1491 - accuracy: 0.9597
Epoch 1/10
875/875 [==============================] - 5s 4ms/step - loss: 3.7268 - accuracy: 0.8782
Epoch 2/10
875/875 [==============================] - 3s 4ms/step - loss: 0.5070 - accuracy: 0.9145
Epoch 3/10
875/875 [==============================] - 3s 3ms/step - loss: 0.3067 - accuracy: 0.9304
Epoch 4/10
875/875 [==============================] - 3s 4ms/step - loss: 0.2345 - accuracy: 0.9437
Epoch 5/10
875/875 [==============================] - 4s 4ms/step - loss: 0.2097 - accuracy: 0.9476
Epoch 6/10
875/875 [==============================] - 3s 4ms/step - loss: 0.1986 - accuracy: 0.9498
Epoch 7/10
875/875 [==============================] - 3s 4ms/step - loss: 0.1785 - accuracy: 0.9547
Epoch 8/10
875/875 [==============================] - 4s 4ms/step - loss: 0.1711 - accuracy: 0.9578
Epoch 9/10
875/875 [==============================] - 3s 4ms/step - loss: 0.1641 - accuracy: 0.9586
Epoch 10/10
875/875 [==============================] - 3s 3ms/step - loss: 0.1546 - accuracy: 0.9613
Epoch 1/10
875/875 [==============================] - 4s 4ms/step - loss: 3.6457 - accuracy: 0.8696
Epoch 2/10
875/875 [==============================] - 3s 4ms/step - loss: 0.4764 - accuracy: 0.9078
Epoch 3/10
875/875 [==============================] - 4s 5ms/step - loss: 0.3072 - accuracy: 0.9300
Epoch 4/10
875/875 [==============================] - 2s 3ms/step - loss: 0.2433 - accuracy: 0.9378
Epoch 5/10
875/875 [==============================] - 2s 3ms/step - loss: 0.2211 - accuracy: 0.9451
Epoch 6/10
875/875 [==============================] - 2s 3ms/step - loss: 0.1895 - accuracy: 0.9514
Epoch 7/10
875/875 [==============================] - 2s 3ms/step - loss: 0.1788 - accuracy: 0.9541
Epoch 8/10
875/875 [==============================] - 3s 3ms/step - loss: 0.1656 - accuracy: 0.9566
Epoch 9/10
875/875 [==============================] - 2s 3ms/step - loss: 0.1567 - accuracy: 0.9580
Epoch 10/10
875/875 [==============================] - 2s 3ms/step - loss: 0.1376 - accuracy: 0.9632
Epoch 1/10
875/875 [==============================] - 3s 3ms/step - loss: 3.9836 - accuracy: 0.8681
Epoch 2/10
875/875 [==============================] - 3s 3ms/step - loss: 0.4974 - accuracy: 0.9079
Epoch 3/10
875/875 [==============================] - 2s 3ms/step - loss: 0.3190 - accuracy: 0.9308
Epoch 4/10
875/875 [==============================] - 2s 3ms/step - loss: 0.2381 - accuracy: 0.9420
Epoch 5/10
875/875 [==============================] - 2s 3ms/step - loss: 0.2113 - accuracy: 0.9477
Epoch 6/10
875/875 [==============================] - 2s 3ms/step - loss: 0.1948 - accuracy: 0.9516
Epoch 7/10
875/875 [==============================] - 3s 3ms/step - loss: 0.1744 - accuracy: 0.9550
Epoch 8/10
875/875 [==============================] - 2s 3ms/step - loss: 0.1671 - accuracy: 0.9567
Epoch 9/10
875/875 [==============================] - 2s 3ms/step - loss: 0.1577 - accuracy: 0.9600
Epoch 10/10
875/875 [==============================] - 2s 3ms/step - loss: 0.1587 - accuracy: 0.9601
Average accuracy: 0.9483285784721375
Fold-1: 94.71%
Fold-2: 94.38%
Fold-3: 95.05%
Fold-4: 95.16%
Fold-5: 94.86%

### PermutedMNIST

In [ ]:

import numpy as np
from tensorflow import keras
import numpy as np
from tensorflow import keras
from sklearn.model_selection import KFold
# Load the MNIST dataset
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

# Create a permutation index for the pixel positions
num_pixels = x_train.shape[1] * x_train.shape[2]
perm_index = np.random.permutation(num_pixels)

# Permute the pixels for training and test sets
x_train_permuted = x_train.reshape(-1, num_pixels)[:, perm_index].reshape(-1, x_train.shape[1], x_train.shape[2])
x_test_permuted = x_test.reshape(-1, num_pixels)[:, perm_index].reshape(-1, x_test.shape[1], x_test.shape[2])
x = np.concatenate((x_train_permuted, x_test_permuted), axis=0)
y = np.concatenate((y_train, y_test), axis=0)
# Save the PermutedMNIST data to numpy files
# np.save('permuted_mnist_train_data.npy', x_train_permuted)
# np.save('permuted_mnist_train_labels.npy', y_train)
# np.save('permuted_mnist_test_data.npy', x_test_permuted)
# np.save('permuted_mnist_test_labels.npy', y_test)

def create_model():
    model = keras.Sequential([
        keras.layers.Flatten(input_shape=(28, 28)),
        keras.layers.Dense(128, activation='relu'),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model

kfold = KFold(n_splits=5, shuffle=True, random_state=42)

accuracies = []
for train_idx, val_idx in kfold.split(x):
    model = create_model()
    model.fit(x[train_idx], y[train_idx], epochs=5, batch_size=32, verbose=0)
    _, accuracy = model.evaluate(x[val_idx], y[val_idx], verbose=0)
    accuracies.append(accuracy)

mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)

print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)
i = 0
float2 = "{0:.2f}"
for score in accuracies:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Mean accuracy: 0.9366571426391601
Standard deviation: 0.003071735406930268
Fold-1: 93.46%
Fold-2: 94.09%
Fold-3: 93.46%
Fold-4: 93.34%
Fold-5: 93.99%

### Fashion-MNIST

In [ ]:
import numpy as np
from tensorflow import keras
from sklearn.model_selection import KFold

(x_train, y_train), (x_test, y_test) = keras.datasets.fashion_mnist.load_data()
# Concatenate the entire dataset
x = np.concatenate((x_train, x_test), axis=0)
y = np.concatenate((y_train, y_test), axis=0)
def create_model():
    model = keras.Sequential([
        keras.layers.Flatten(input_shape=(28, 28)),
        keras.layers.Dense(128, activation='relu'),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model

kf= KFold(n_splits=5, shuffle=True, random_state=42)

fold_accuracy = []
for train_index, val_index in kf.split(x):
    # Split the data into training and validation sets
    x_train_fold, x_val_fold = x[train_index], x[val_index]
    y_train_fold, y_val_fold = y[train_index], y[val_index]
    model = create_model()
    model.fit(x_train_fold, y_train_fold, epochs=10, batch_size=64, verbose=1)
    # Evaluate the model on the validation data
    _, accuracy = model.evaluate(x_val_fold, y_val_fold, verbose=0)
    fold_accuracy.append(accuracy)

# mean_accuracy = np.mean(accuracies)
# std_accuracy = np.std(accuracies)

# print("Mean accuracy:", mean_accuracy)
# print("Standard deviation:", std_accuracy)
# Calculate and print the average accuracy across all folds
average_accuracy = np.mean(fold_accuracy)
print('Average accuracy:', average_accuracy)
i = 0
float2 = "{0:.2f}"
for score in fold_accuracy:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/train-labels-idx1-ubyte.gz
29515/29515 [==============================] - 0s 1us/step
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/train-images-idx3-ubyte.gz
26421880/26421880 [==============================] - 2s 0us/step
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/t10k-labels-idx1-ubyte.gz
5148/5148 [==============================] - 0s 0us/step
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/t10k-images-idx3-ubyte.gz
4422102/4422102 [==============================] - 1s 0us/step
Epoch 1/10
875/875 [==============================] - 3s 3ms/step - loss: 4.1377 - accuracy: 0.6953
Epoch 2/10
875/875 [==============================] - 3s 3ms/step - loss: 0.7232 - accuracy: 0.7524
Epoch 3/10
875/875 [==============================] - 2s 3ms/step - loss: 0.6073 - accuracy: 0.7873
Epoch 4/10
875/875 [==============================] - 2s 3ms/step - loss: 0.5400 - accuracy: 0.8077
Epoch 5/10
875/875 [==============================] - 2s 3ms/step - loss: 0.5102 - accuracy: 0.8181
Epoch 6/10
875/875 [==============================] - 3s 3ms/step - loss: 0.4754 - accuracy: 0.8306
Epoch 7/10
875/875 [==============================] - 3s 4ms/step - loss: 0.4590 - accuracy: 0.8362
Epoch 8/10
875/875 [==============================] - 2s 3ms/step - loss: 0.4468 - accuracy: 0.8408
Epoch 9/10
875/875 [==============================] - 3s 4ms/step - loss: 0.4373 - accuracy: 0.8436
Epoch 10/10
875/875 [==============================] - 3s 3ms/step - loss: 0.4244 - accuracy: 0.8476
Epoch 1/10
875/875 [==============================] - 3s 3ms/step - loss: 6.3534 - accuracy: 0.7309
Epoch 2/10
875/875 [==============================] - 2s 3ms/step - loss: 0.7152 - accuracy: 0.7752
Epoch 3/10
875/875 [==============================] - 2s 3ms/step - loss: 0.5775 - accuracy: 0.8015
Epoch 4/10
875/875 [==============================] - 2s 3ms/step - loss: 0.5220 - accuracy: 0.8175
Epoch 5/10
875/875 [==============================] - 3s 4ms/step - loss: 0.4911 - accuracy: 0.8308
Epoch 6/10
875/875 [==============================] - 2s 3ms/step - loss: 0.4729 - accuracy: 0.8361
Epoch 7/10
875/875 [==============================] - 2s 3ms/step - loss: 0.4615 - accuracy: 0.8413
Epoch 8/10
875/875 [==============================] - 2s 3ms/step - loss: 0.4467 - accuracy: 0.8444
Epoch 9/10
875/875 [==============================] - 2s 3ms/step - loss: 0.4408 - accuracy: 0.8455
Epoch 10/10
875/875 [==============================] - 3s 3ms/step - loss: 0.4292 - accuracy: 0.8502
Epoch 1/10
875/875 [==============================] - 3s 3ms/step - loss: 3.7987 - accuracy: 0.6955
Epoch 2/10
875/875 [==============================] - 3s 3ms/step - loss: 0.6658 - accuracy: 0.7713
Epoch 3/10
875/875 [==============================] - 3s 3ms/step - loss: 0.5649 - accuracy: 0.7970
Epoch 4/10
875/875 [==============================] - 2s 3ms/step - loss: 0.5194 - accuracy: 0.8145
Epoch 5/10
875/875 [==============================] - 2s 3ms/step - loss: 0.4959 - accuracy: 0.8228
Epoch 6/10
875/875 [==============================] - 2s 3ms/step - loss: 0.4854 - accuracy: 0.8294
Epoch 7/10
875/875 [==============================] - 3s 3ms/step - loss: 0.4689 - accuracy: 0.8370
Epoch 8/10
875/875 [==============================] - 3s 3ms/step - loss: 0.4517 - accuracy: 0.8420
Epoch 9/10
875/875 [==============================] - 2s 3ms/step - loss: 0.4436 - accuracy: 0.8464
Epoch 10/10
875/875 [==============================] - 3s 3ms/step - loss: 0.4419 - accuracy: 0.8448
Epoch 1/10
875/875 [==============================] - 3s 3ms/step - loss: 4.2735 - accuracy: 0.6814
Epoch 2/10
875/875 [==============================] - 2s 3ms/step - loss: 0.7428 - accuracy: 0.7157
Epoch 3/10
875/875 [==============================] - 2s 3ms/step - loss: 0.5891 - accuracy: 0.7779
Epoch 4/10
875/875 [==============================] - 2s 3ms/step - loss: 0.5237 - accuracy: 0.8017
Epoch 5/10
875/875 [==============================] - 3s 3ms/step - loss: 0.4901 - accuracy: 0.8215
Epoch 6/10
875/875 [==============================] - 2s 3ms/step - loss: 0.4773 - accuracy: 0.8276
Epoch 7/10
875/875 [==============================] - 2s 3ms/step - loss: 0.4726 - accuracy: 0.8290
Epoch 8/10
875/875 [==============================] - 2s 3ms/step - loss: 0.4634 - accuracy: 0.8320
Epoch 9/10
875/875 [==============================] - 2s 3ms/step - loss: 0.4569 - accuracy: 0.8363
Epoch 10/10
875/875 [==============================] - 3s 3ms/step - loss: 0.4510 - accuracy: 0.8370
Epoch 1/10
875/875 [==============================] - 3s 3ms/step - loss: 5.3866 - accuracy: 0.6870
Epoch 2/10
875/875 [==============================] - 3s 3ms/step - loss: 0.7668 - accuracy: 0.7243
Epoch 3/10
875/875 [==============================] - 2s 3ms/step - loss: 0.6121 - accuracy: 0.7828
Epoch 4/10
875/875 [==============================] - 2s 3ms/step - loss: 0.5353 - accuracy: 0.8151
Epoch 5/10
875/875 [==============================] - 2s 2ms/step - loss: 0.4931 - accuracy: 0.8287
Epoch 6/10
875/875 [==============================] - 2s 2ms/step - loss: 0.4761 - accuracy: 0.8325
Epoch 7/10
875/875 [==============================] - 3s 3ms/step - loss: 0.4572 - accuracy: 0.8391
Epoch 8/10
875/875 [==============================] - 2s 3ms/step - loss: 0.4455 - accuracy: 0.8413
Epoch 9/10
875/875 [==============================] - 2s 3ms/step - loss: 0.4424 - accuracy: 0.8439
Epoch 10/10
875/875 [==============================] - 2s 3ms/step - loss: 0.4267 - accuracy: 0.8459
Average accuracy: 0.8409000039100647
Fold-1: 84.12%
Fold-2: 83.84%
Fold-3: 84.33%
Fold-4: 83.48%
Fold-5: 84.68%

###  Kuzushiji-MNIST

In [ ]:

import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import KFold
# from tensorflow.keras.datasets import kmnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam
import tensorflow_datasets as tfds

from sklearn.model_selection import train_test_split

# (x_train, y_train), (x_test, y_test) = kmnist.load_data()


dataset = tfds.load('kmnist')
train_o, test_o = dataset['train'], dataset['test']

train_numpy = np.vstack(tfds.as_numpy(train_o))
test_numpy = np.vstack(tfds.as_numpy(test_o))

train_x = np.array(list(map(lambda x: x[0]['image'], train_numpy)))
train_y = np.array(list(map(lambda x: x[0]['label'], train_numpy)))

test_x = np.array(list(map(lambda x: x[0]['image'], test_numpy)))
test_y = np.array(list(map(lambda x: x[0]['label'], test_numpy)))

train = np.concatenate((train_x,test_x), axis = 0)
test = np.concatenate((train_y,test_y),axis = 0)

print("it is whole train size ****:\t", train_x.shape)

x_train, x_test, y_train, y_test = train_x, test_x, train_y, test_y
# Concatenate the entire dataset
x = np.concatenate((x_train, x_test), axis=0)
y = np.concatenate((y_train, y_test), axis=0)
def create_model():
    model = keras.Sequential([
        keras.layers.Flatten(input_shape=(28, 28)),
        keras.layers.Dense(128, activation='relu'),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model

kfold = KFold(n_splits=5, shuffle=True, random_state=42)

accuracies = []
for train_idx, val_idx in kfold.split(x):
    model = create_model()
    model.fit(x[train_idx], y[train_idx], epochs=5, batch_size=32, verbose=0)
    _, accuracy = model.evaluate(x[val_idx], y[val_idx], verbose=0)
    accuracies.append(accuracy)

mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)

print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)
i = 0
float2 = "{0:.2f}"
for score in accuracies:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Downloading and preparing dataset 20.26 MiB (download: 20.26 MiB, generated: 31.76 MiB, total: 52.02 MiB) to /root/tensorflow_datasets/kmnist/3.0.1...

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

Generating splits...:   0%|          | 0/2 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/60000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/kmnist/3.0.1.incompleteRUTDTR/kmnist-train.tfrecord*...:   0%|          | …

Generating test examples...:   0%|          | 0/10000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/kmnist/3.0.1.incompleteRUTDTR/kmnist-test.tfrecord*...:   0%|          | 0…

Dataset kmnist downloaded and prepared to /root/tensorflow_datasets/kmnist/3.0.1. Subsequent calls will reuse this data.

<ipython-input-3-9c2ecfc8c204>:19: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  train_numpy = np.vstack(tfds.as_numpy(train_o))
<ipython-input-3-9c2ecfc8c204>:20: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  test_numpy = np.vstack(tfds.as_numpy(test_o))

it is whole train size ****:	 (60000, 28, 28, 1)
Mean accuracy: 0.8584714293479919
Standard deviation: 0.009009242231909737
Fold-1: 86.80%
Fold-2: 84.26%
Fold-3: 86.63%
Fold-4: 85.80%
Fold-5: 85.75%

### MNIST-C

In [ ]:
import numpy as np
import tensorflow_datasets as tfds
from sklearn.model_selection import KFold
from keras.models import Sequential
from keras.layers import Dense, Flatten

# Load the MNIST-C dataset
dataset = tfds.load('mnist_corrupted', split='train')
data = list(dataset.as_numpy_iterator())
images = np.array([example['image'] for example in data])
labels = np.array([example['label'] for example in data])

# Define the model architecture
model = Sequential()
model.add(Flatten(input_shape=(28, 28)))
model.add(Dense(128, activation='relu'))
model.add(Dense(10, activation='softmax'))
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Perform k-fold cross-validation
k = 5
kf = KFold(n_splits=k, shuffle=True)

accuracy_scores = []
for train_indices, val_indices in kf.split(images):
    train_images, train_labels = images[train_indices], labels[train_indices]
    val_images, val_labels = images[val_indices], labels[val_indices]

    # Preprocess and normalize the data if necessary

    # Train the model on the current fold
    model.fit(train_images, train_labels, epochs=5, batch_size=32, verbose=0)

    # Evaluate the model on the validation set
    _, accuracy = model.evaluate(val_images, val_labels, verbose=0)
    accuracy_scores.append(accuracy)

# Calculate and print the average accuracy across folds
average_accuracy = sum(accuracy_scores) / k
print("Average accuracy:", average_accuracy)

Average accuracy: 0.9482166528701782

In [ ]:
i = 0
float2 = "{0:.2f}"
for score in accuracy_scores:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Fold-1: 93.04%
Fold-2: 94.43%
Fold-3: 94.56%
Fold-4: 96.17%
Fold-5: 95.90%

### CIFAR10

In [ ]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import KFold

(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()
# Concatenate the entire dataset
x = np.concatenate((x_train, x_test), axis=0)
y = np.concatenate((y_train, y_test), axis=0)
def create_model():
    model = keras.Sequential([
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(64, activation='relu'),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model


kfold = KFold(n_splits=5, shuffle=True, random_state=42)

accuracies = []
for train_idx, val_idx in kfold.split(x):
    model = create_model()
    model.fit(x[train_idx], y[train_idx], epochs=5, batch_size=32, verbose=0)
    _, accuracy = model.evaluate(x[val_idx], y[val_idx], verbose=0)
    accuracies.append(accuracy)

mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)

print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)
i = 0
float2 = "{0:.2f}"
for score in accuracies:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Downloading data from https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
170498071/170498071 [==============================] - 13s 0us/step
Mean accuracy: 0.6175000071525574
Standard deviation: 0.012563517279119038
Fold-1: 59.73%
Fold-2: 63.38%
Fold-3: 61.31%
Fold-4: 61.60%
Fold-5: 62.73%

### CIFAR100

In [ ]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import KFold
from tensorflow.keras.optimizers import Adam
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar100.load_data()

# Concatenate the entire dataset
x = np.concatenate((x_train, x_test), axis=0)
y = np.concatenate((y_train, y_test), axis=0)

def create_model():
    model = keras.Sequential([
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(100, activation='softmax')
    ])

    model.compile(optimizer=Adam(learning_rate=0.001),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model



kfold = KFold(n_splits=5, shuffle=True, random_state=42)

accuracies = []
for train_idx, val_idx in kfold.split(x):
    model = create_model()
    model.fit(x[train_idx], y[train_idx], epochs=5, batch_size=32, verbose=0)
    _, accuracy = model.evaluate(x[val_idx], y[val_idx], verbose=0)
    accuracies.append(accuracy)

mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)

print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)

i = 0
float2 = "{0:.2f}"
for score in accuracies:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Downloading data from https://www.cs.toronto.edu/~kriz/cifar-100-python.tar.gz
169001437/169001437 [==============================] - 13s 0us/step
Mean accuracy: 0.31543333530426027
Standard deviation: 0.012175269584863315
Fold-1: 29.80%
Fold-2: 31.32%
Fold-3: 31.91%
Fold-4: 33.55%
Fold-5: 31.14%

### CIFAR10-C

In [ ]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import KFold
from tensorflow.keras.optimizers import Adam
from skimage.util import random_noise
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()

# Concatenate the entire dataset
x = np.concatenate((x_train, x_test), axis=0)
y = np.concatenate((y_train, y_test), axis=0)

y_train = y
# Add speckle noise to the training images
x_train = random_noise(x, mode='speckle', var=0.1)
def create_model():
    model = keras.Sequential([
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model



kfold = KFold(n_splits=5, shuffle=True, random_state=42)

accuracies = []
for train_idx, val_idx in kfold.split(x_train):
    model = create_model()
    model.fit(x_train[train_idx], y_train[train_idx], epochs=5,  verbose=0)
    _, accuracy = model.evaluate(x_train[val_idx], y_train[val_idx])
    accuracies.append(accuracy)

mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)

print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)
i = 0
float2 = "{0:.2f}"
for score in accuracies:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

375/375 [==============================] - 2s 4ms/step - loss: 1.0259 - accuracy: 0.6491
375/375 [==============================] - 1s 3ms/step - loss: 0.9856 - accuracy: 0.6575
375/375 [==============================] - 1s 2ms/step - loss: 1.0346 - accuracy: 0.6504
375/375 [==============================] - 1s 3ms/step - loss: 0.9866 - accuracy: 0.6623
375/375 [==============================] - 2s 4ms/step - loss: 1.0060 - accuracy: 0.6513
Mean accuracy: 0.6541333317756652
Standard deviation: 0.005014588663903069
Fold-1: 64.91%
Fold-2: 65.75%
Fold-3: 65.04%
Fold-4: 66.23%
Fold-5: 65.13%

### CIFAR100-C

In [ ]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import KFold
from tensorflow.keras.optimizers import Adam
from skimage.util import random_noise
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar100.load_data()

# Concatenate the entire dataset
x = np.concatenate((x_train, x_test), axis=0)
y = np.concatenate((y_train, y_test), axis=0)

y_train = y
# Add speckle noise to the training images
x_train_noise = random_noise(x, mode='speckle', var=0.1)
def create_model():
    model = keras.Sequential([
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(100, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model



kfold = KFold(n_splits=5, shuffle=True, random_state=42)

accuracies = []
for train_idx, val_idx in kfold.split(x_train_noise):
    model = create_model()
    model.fit(x_train_noise[train_idx], y_train[train_idx], epochs=5, batch_size=32, verbose=0)
    _, accuracy = model.evaluate(x_train_noise[val_idx], y_train[val_idx], verbose=0)
    accuracies.append(accuracy)

mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)

print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)
i = 0
float2 = "{0:.2f}"
for score in accuracies:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Mean accuracy: 0.31978333592414854
Standard deviation: 0.0033617937164159054
Fold-1: 32.34%
Fold-2: 32.33%
Fold-3: 32.03%
Fold-4: 31.54%
Fold-5: 31.64%

In [ ]:
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar100.load_data()
x_train.shape

Downloading data from https://www.cs.toronto.edu/~kriz/cifar-100-python.tar.gz
169001437/169001437 [==============================] - 3s 0us/step

(50000, 32, 32, 3)

### SVHN

In [ ]:
!wget http://ufldl.stanford.edu/housenumbers/train_32x32.mat
!wget http://ufldl.stanford.edu/housenumbers/test_32x32.mat

--2023-07-14 13:11:32--  http://ufldl.stanford.edu/housenumbers/train_32x32.mat
Resolving ufldl.stanford.edu (ufldl.stanford.edu)... 171.64.68.10
Connecting to ufldl.stanford.edu (ufldl.stanford.edu)|171.64.68.10|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 182040794 (174M) [text/plain]
Saving to: ‘train_32x32.mat.4’

train_32x32.mat.4   100%[===================>] 173.61M  84.4MB/s    in 2.1s

2023-07-14 13:11:34 (84.4 MB/s) - ‘train_32x32.mat.4’ saved [182040794/182040794]

--2023-07-14 13:11:34--  http://ufldl.stanford.edu/housenumbers/test_32x32.mat
Resolving ufldl.stanford.edu (ufldl.stanford.edu)... 171.64.68.10
Connecting to ufldl.stanford.edu (ufldl.stanford.edu)|171.64.68.10|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 64275384 (61M) [text/plain]
Saving to: ‘test_32x32.mat.4’

test_32x32.mat.4    100%[===================>]  61.30M  64.0MB/s    in 1.0s

2023-07-14 13:11:35 (64.0 MB/s) - ‘test_32x32.mat.4’ saved [64275384/64275384]

In [ ]:
import numpy as np
from tensorflow import keras
from sklearn.model_selection import KFold
import scipy.io as sio
from tensorflow.keras.utils import to_categorical
# Define the model architecture
def create_model():
    model = keras.Sequential([
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(64, activation='relu'),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])

    return model


# Load the SVHN dataset
train_data = sio.loadmat("train_32x32.mat")
test_data = sio.loadmat("test_32x32.mat")

# Extract the images and labels from the downloaded data
train_images = np.transpose(train_data['X'], (3, 0, 1, 2))
train_labels = train_data['y']

test_images = np.transpose(test_data['X'], (3, 0, 1, 2))
test_labels = test_data['y']

# Change class labels to range from 0 to 9
train_labels[train_labels == 10] = 0
test_labels[test_labels == 10] = 0

# Perform one-hot encoding on the labels
num_classes = 10
train_labels = to_categorical(train_labels, num_classes)
test_labels = to_categorical(test_labels, num_classes)

# Print the shape of the loaded data
print("Train images shape:", train_images.shape)
print("Train labels shape:", train_labels.shape)
print("Test images shape:", test_images.shape)
print("Test labels shape:", test_labels.shape)

# Concatenate the entire dataset
x = np.concatenate((train_images, test_images), axis=0)
y = np.concatenate((train_labels, test_labels), axis=0)
print(x.shape, y.shape)
# Define the number of folds for cross-validation
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)

train_images = x
train_labels = y
accuracies = []

# Perform k-fold cross-validation
for train_idx, val_idx in kf.split(train_images):
    # Create a new instance of the model for each fold
    model = create_model()

    # Train the model on the current fold
    model.fit(train_images[train_idx], train_labels[train_idx], epochs=5, batch_size=32, verbose=1)

    # Evaluate the model on the validation fold
    _, accuracy = model.evaluate(train_images[val_idx], train_labels[val_idx], verbose=0)

    # Append the accuracy to the list of accuracies
    accuracies.append(accuracy)

# Compute the mean and standard deviation of the accuracies
mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)

# Print the results
print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)

Train images shape: (73257, 32, 32, 3)
Train labels shape: (73257, 10)
Test images shape: (26032, 32, 32, 3)
Test labels shape: (26032, 10)
(99289, 32, 32, 3) (99289, 10)
Epoch 1/5
2483/2483 [==============================] - 17s 6ms/step - loss: 2.4402 - accuracy: 0.1877
Epoch 2/5
2483/2483 [==============================] - 14s 6ms/step - loss: 2.1934 - accuracy: 0.1957
Epoch 3/5
2483/2483 [==============================] - 14s 6ms/step - loss: 1.3986 - accuracy: 0.5191
Epoch 4/5
2483/2483 [==============================] - 14s 6ms/step - loss: 0.7063 - accuracy: 0.7916
Epoch 5/5
2483/2483 [==============================] - 15s 6ms/step - loss: 0.6137 - accuracy: 0.8215
Epoch 1/5
2483/2483 [==============================] - 12s 4ms/step - loss: 1.2013 - accuracy: 0.6697
Epoch 2/5
2483/2483 [==============================] - 11s 4ms/step - loss: 0.6586 - accuracy: 0.8077
Epoch 3/5
2483/2483 [==============================] - 10s 4ms/step - loss: 0.5865 - accuracy: 0.8275
Epoch 4/5
2483/2483 [==============================] - 11s 4ms/step - loss: 0.5280 - accuracy: 0.8454
Epoch 5/5
2483/2483 [==============================] - 11s 4ms/step - loss: 0.4853 - accuracy: 0.8565
Epoch 1/5
2483/2483 [==============================] - 12s 4ms/step - loss: 1.1963 - accuracy: 0.6850
Epoch 2/5
2483/2483 [==============================] - 11s 4ms/step - loss: 0.6437 - accuracy: 0.8113
Epoch 3/5
2483/2483 [==============================] - 11s 4ms/step - loss: 0.5623 - accuracy: 0.8342
Epoch 4/5
2483/2483 [==============================] - 11s 4ms/step - loss: 0.5068 - accuracy: 0.8498
Epoch 5/5
2483/2483 [==============================] - 11s 4ms/step - loss: 0.4627 - accuracy: 0.8630
Epoch 1/5
2483/2483 [==============================] - 12s 4ms/step - loss: 1.3263 - accuracy: 0.6236
Epoch 2/5
2483/2483 [==============================] - 11s 4ms/step - loss: 0.7044 - accuracy: 0.7904
Epoch 3/5
2483/2483 [==============================] - 10s 4ms/step - loss: 0.6003 - accuracy: 0.8214
Epoch 4/5
2483/2483 [==============================] - 11s 4ms/step - loss: 0.5014 - accuracy: 0.8525
Epoch 5/5
2483/2483 [==============================] - 11s 4ms/step - loss: 0.4438 - accuracy: 0.8678
Epoch 1/5
2483/2483 [==============================] - 12s 4ms/step - loss: 1.3073 - accuracy: 0.6279
Epoch 2/5
2483/2483 [==============================] - 11s 4ms/step - loss: 0.6431 - accuracy: 0.8126
Epoch 3/5
2483/2483 [==============================] - 11s 4ms/step - loss: 0.5532 - accuracy: 0.8381
Epoch 4/5
2483/2483 [==============================] - 11s 4ms/step - loss: 0.4943 - accuracy: 0.8544
Epoch 5/5
2483/2483 [==============================] - 11s 4ms/step - loss: 0.4586 - accuracy: 0.8645
Mean accuracy: 0.8482712984085083
Standard deviation: 0.011335317852331021

In [ ]:
i = 0
float2 = "{0:.2f}"
for score in accuracies:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Fold-1: 83.04%
Fold-2: 84.17%
Fold-3: 84.96%
Fold-4: 86.23%
Fold-5: 85.73%

### CreditCard

In [ ]:
!wget -O creditfraud.zip https://www.dropbox.com/s/tl20yp9bcl56oxt/creditcardfraud.zip?dl=0

--2023-07-15 07:45:20--  https://www.dropbox.com/s/tl20yp9bcl56oxt/creditcardfraud.zip?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 162.125.1.18, 2620:100:6016:18::a27d:112
Connecting to www.dropbox.com (www.dropbox.com)|162.125.1.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /s/raw/tl20yp9bcl56oxt/creditcardfraud.zip [following]
--2023-07-15 07:45:20--  https://www.dropbox.com/s/raw/tl20yp9bcl56oxt/creditcardfraud.zip
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc9af04a7ca9f96c23075fbcd484.dl.dropboxusercontent.com/cd/0/inline/B_4T6DmTwFs6bNNCwA3RmX0J57Ft24Fic3gMRRetD8bCcIrXODic_7XiOf-B3sOuwQFjUkeuwc_probvA7mUURlkoaVqVDpLEEnGxn6bA2to2e6ZpGKKXdaFVM7dfUVssB5ojpMh_ORDby07FTz2MSsWlJRyHD_bjLp1irQxSerpuw/file# [following]
--2023-07-15 07:45:20--  https://uc9af04a7ca9f96c23075fbcd484.dl.dropboxusercontent.com/cd/0/inline/B_4T6DmTwFs6bNNCwA3RmX0J57Ft24Fic3gMRRetD8bCcIrXODic_7XiOf-B3sOuwQFjUkeuwc_probvA7mUURlkoaVqVDpLEEnGxn6bA2to2e6ZpGKKXdaFVM7dfUVssB5ojpMh_ORDby07FTz2MSsWlJRyHD_bjLp1irQxSerpuw/file
Resolving uc9af04a7ca9f96c23075fbcd484.dl.dropboxusercontent.com (uc9af04a7ca9f96c23075fbcd484.dl.dropboxusercontent.com)... 162.125.1.15, 2620:100:6016:15::a27d:10f
Connecting to uc9af04a7ca9f96c23075fbcd484.dl.dropboxusercontent.com (uc9af04a7ca9f96c23075fbcd484.dl.dropboxusercontent.com)|162.125.1.15|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /cd/0/inline2/B_6avAmJf_kf_z7tFgUy54YU8IFGvPPHb1mjixGY6ZR-Div1lAZCQa2nqs8C4F1WOYv45_6KjqMhwUOQo5yRrtSMk7Mp4hdaZJFRihHHPzMkDzIAnMY0sQPrK3I0LZqkP4ULU94ho5Mz20VnjSyMfx9N6qrCnW90QZnZBG-FhGdIfncBUgbdYa3IeQJnSTmuFOYKhHYBvRDY5WQ-2kPVnWcuY7593aiojOFGTj67t_ZQ0c2LTP5Ercof-qRYiExOp8l38s7FKnPnWrj5JewG-uP0WY6nb_K2M41VIwb7jxzltoWQtsDgUKU1AnK8U2QTeiD9qk0qzI3GDiEj65QeWHw2R1b0ETW5tk2ur4HJin19iCS39pKipGb7AIaa6Jln9v0d97ljcIZCCB8pt-CwpDPQdn6S6_9ODJix2DtvBWWE8g/file [following]
--2023-07-15 07:45:21--  https://uc9af04a7ca9f96c23075fbcd484.dl.dropboxusercontent.com/cd/0/inline2/B_6avAmJf_kf_z7tFgUy54YU8IFGvPPHb1mjixGY6ZR-Div1lAZCQa2nqs8C4F1WOYv45_6KjqMhwUOQo5yRrtSMk7Mp4hdaZJFRihHHPzMkDzIAnMY0sQPrK3I0LZqkP4ULU94ho5Mz20VnjSyMfx9N6qrCnW90QZnZBG-FhGdIfncBUgbdYa3IeQJnSTmuFOYKhHYBvRDY5WQ-2kPVnWcuY7593aiojOFGTj67t_ZQ0c2LTP5Ercof-qRYiExOp8l38s7FKnPnWrj5JewG-uP0WY6nb_K2M41VIwb7jxzltoWQtsDgUKU1AnK8U2QTeiD9qk0qzI3GDiEj65QeWHw2R1b0ETW5tk2ur4HJin19iCS39pKipGb7AIaa6Jln9v0d97ljcIZCCB8pt-CwpDPQdn6S6_9ODJix2DtvBWWE8g/file
Reusing existing connection to uc9af04a7ca9f96c23075fbcd484.dl.dropboxusercontent.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 69155672 (66M) [application/zip]
Saving to: ‘creditfraud.zip’

creditfraud.zip     100%[===================>]  65.95M   123MB/s    in 0.5s

2023-07-15 07:45:21 (123 MB/s) - ‘creditfraud.zip’ saved [69155672/69155672]

In [ ]:
!unzip creditfraud.zip

Archive:  creditfraud.zip
  inflating: creditcard.csv

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import Adam
from sklearn.model_selection import KFold
# Load the Credit Card Fraud Detection dataset
data = pd.read_csv('creditcard.csv')

# Split features and labels
features = data.drop('Class', axis=1)
labels = data['Class']

# Perform data preprocessing, such as scaling
scaler = StandardScaler()
features = scaler.fit_transform(features)



k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)



model = Sequential()
model.add(Dense(32, activation='relu', input_shape=(features.shape[1],)))

model.add(Dense(8, activation='relu'))

model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer=Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])

accuracy_scores = []

for train_indices, val_indices in kf.split(features):
    train_features, train_labels = features[train_indices], labels[train_indices]
    val_features, val_labels = features[val_indices], labels[val_indices]

    # Train the model on the current fold
    model.fit(train_features, train_labels, epochs=5, batch_size=32, verbose=0)

    # Evaluate the model on the validation set
    _, accuracy = model.evaluate(val_features, val_labels, verbose=0)
    accuracy_scores.append(accuracy)

# Calculate and print the average accuracy across folds
average_accuracy = sum(accuracy_scores) / k
print("Average accuracy:", average_accuracy)

i = 0
float2 = "{0:.2f}"
for score in accuracy_scores:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Average accuracy: 0.9994698166847229
Fold-1: 99.94%
Fold-2: 99.95%
Fold-3: 99.94%
Fold-4: 99.96%
Fold-5: 99.95%

### Caltech101

In [ ]:
# model.fit(X_train_resized, y_train, batch_size=128, epochs=100, validation_data=(X_test_resized, y_test))
import tensorflow as tf
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras import layers
from sklearn.model_selection import KFold
def create_model():
    model = keras.Sequential([
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(28, 28, 3)),  # Update input shape
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(64, activation='relu'),
        keras.layers.Dense(102, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])

    return model

# Define the number of folds for cross-validation
num_folds = 5
kf = KFold(n_splits=num_folds, shuffle=True)

fold_accuracy = []
for train_index, val_index in kf.split(x):
    # Split the data into training and validation sets
    x_train_fold, x_val_fold = x[train_index], x[val_index]
    y_train_fold, y_val_fold = y[train_index], y[val_index]
    with tf.device('/device:GPU:0'):
      model = create_model()
      model.fit(x_train_fold, y_train_fold, epochs=100, batch_size=64, verbose=1)
    # Evaluate the model on the validation data
      _, accuracy = model.evaluate(x_val_fold, y_val_fold, verbose=0)
      fold_accuracy.append(accuracy)


average_accuracy = np.mean(fold_accuracy)
print('Average accuracy:', average_accuracy)
i = 0
float2 = "{0:.2f}"
for score in fold_accuracy:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Epoch 1/100
115/115 [==============================] - 4s 7ms/step - loss: 3.9070 - accuracy: 0.1943
Epoch 2/100
115/115 [==============================] - 1s 6ms/step - loss: 3.2262 - accuracy: 0.3200
Epoch 3/100
115/115 [==============================] - 1s 6ms/step - loss: 2.7756 - accuracy: 0.3948
Epoch 4/100
115/115 [==============================] - 1s 6ms/step - loss: 2.4444 - accuracy: 0.4465
Epoch 5/100
115/115 [==============================] - 1s 6ms/step - loss: 2.1860 - accuracy: 0.4939
Epoch 6/100
115/115 [==============================] - 1s 6ms/step - loss: 1.9866 - accuracy: 0.5221
Epoch 7/100
115/115 [==============================] - 1s 6ms/step - loss: 1.7935 - accuracy: 0.5679
Epoch 8/100
115/115 [==============================] - 1s 6ms/step - loss: 1.6375 - accuracy: 0.6005
Epoch 9/100
115/115 [==============================] - 1s 6ms/step - loss: 1.5024 - accuracy: 0.6294
Epoch 10/100
115/115 [==============================] - 1s 6ms/step - loss: 1.3848 - accuracy: 0.6488
Epoch 11/100
115/115 [==============================] - 1s 6ms/step - loss: 1.2754 - accuracy: 0.6798
Epoch 12/100
115/115 [==============================] - 1s 6ms/step - loss: 1.1633 - accuracy: 0.7025
Epoch 13/100
115/115 [==============================] - 1s 8ms/step - loss: 1.0703 - accuracy: 0.7284
Epoch 14/100
115/115 [==============================] - 1s 9ms/step - loss: 0.9967 - accuracy: 0.7382
Epoch 15/100
115/115 [==============================] - 1s 8ms/step - loss: 0.9020 - accuracy: 0.7651
Epoch 16/100
115/115 [==============================] - 1s 6ms/step - loss: 0.8245 - accuracy: 0.7854
Epoch 17/100
115/115 [==============================] - 1s 5ms/step - loss: 0.7560 - accuracy: 0.7996
Epoch 18/100
115/115 [==============================] - 1s 6ms/step - loss: 0.6689 - accuracy: 0.8201
Epoch 19/100
115/115 [==============================] - 1s 5ms/step - loss: 0.6073 - accuracy: 0.8375
Epoch 20/100
115/115 [==============================] - 1s 6ms/step - loss: 0.5580 - accuracy: 0.8515
Epoch 21/100
115/115 [==============================] - 1s 6ms/step - loss: 0.4882 - accuracy: 0.8689
Epoch 22/100
115/115 [==============================] - 1s 5ms/step - loss: 0.4290 - accuracy: 0.8849
Epoch 23/100
115/115 [==============================] - 1s 6ms/step - loss: 0.3747 - accuracy: 0.9006
Epoch 24/100
115/115 [==============================] - 1s 6ms/step - loss: 0.3414 - accuracy: 0.9068
Epoch 25/100
115/115 [==============================] - 1s 6ms/step - loss: 0.2967 - accuracy: 0.9202
Epoch 26/100
115/115 [==============================] - 1s 6ms/step - loss: 0.2381 - accuracy: 0.9429
Epoch 27/100
115/115 [==============================] - 1s 6ms/step - loss: 0.2088 - accuracy: 0.9494
Epoch 28/100
115/115 [==============================] - 1s 5ms/step - loss: 0.1859 - accuracy: 0.9565
Epoch 29/100
115/115 [==============================] - 1s 6ms/step - loss: 0.1516 - accuracy: 0.9669
Epoch 30/100
115/115 [==============================] - 1s 9ms/step - loss: 0.1326 - accuracy: 0.9701
Epoch 31/100
115/115 [==============================] - 1s 8ms/step - loss: 0.1193 - accuracy: 0.9744
Epoch 32/100
115/115 [==============================] - 1s 9ms/step - loss: 0.1113 - accuracy: 0.9753
Epoch 33/100
115/115 [==============================] - 1s 8ms/step - loss: 0.0859 - accuracy: 0.9835
Epoch 34/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0684 - accuracy: 0.9895
Epoch 35/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0626 - accuracy: 0.9891
Epoch 36/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0588 - accuracy: 0.9900
Epoch 37/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0933 - accuracy: 0.9758
Epoch 38/100
115/115 [==============================] - 1s 6ms/step - loss: 0.1358 - accuracy: 0.9593
Epoch 39/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0753 - accuracy: 0.9826
Epoch 40/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0570 - accuracy: 0.9878
Epoch 41/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0477 - accuracy: 0.9907
Epoch 42/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0254 - accuracy: 0.9973
Epoch 43/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0378 - accuracy: 0.9938
Epoch 44/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0414 - accuracy: 0.9921
Epoch 45/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0292 - accuracy: 0.9963
Epoch 46/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0262 - accuracy: 0.9959
Epoch 47/100
115/115 [==============================] - 1s 7ms/step - loss: 0.1362 - accuracy: 0.9610
Epoch 48/100
115/115 [==============================] - 1s 8ms/step - loss: 0.1826 - accuracy: 0.9431
Epoch 49/100
115/115 [==============================] - 1s 7ms/step - loss: 0.0872 - accuracy: 0.9738
Epoch 50/100
115/115 [==============================] - 1s 7ms/step - loss: 0.0503 - accuracy: 0.9893
Epoch 51/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0194 - accuracy: 0.9974
Epoch 52/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0081 - accuracy: 0.9996
Epoch 53/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0069 - accuracy: 0.9995
Epoch 54/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0092 - accuracy: 0.9992
Epoch 55/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0039 - accuracy: 0.9996
Epoch 56/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0072 - accuracy: 0.9990
Epoch 57/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0055 - accuracy: 0.9995
Epoch 58/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0068 - accuracy: 0.9995
Epoch 59/100
115/115 [==============================] - 1s 5ms/step - loss: 0.0056 - accuracy: 0.9995
Epoch 60/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0067 - accuracy: 0.9995
Epoch 61/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0055 - accuracy: 0.9993
Epoch 62/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0048 - accuracy: 0.9995
Epoch 63/100
115/115 [==============================] - 1s 5ms/step - loss: 0.0075 - accuracy: 0.9990
Epoch 64/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0060 - accuracy: 0.9992
Epoch 65/100
115/115 [==============================] - 1s 9ms/step - loss: 0.3623 - accuracy: 0.8972
Epoch 66/100
115/115 [==============================] - 1s 7ms/step - loss: 0.2574 - accuracy: 0.9232
Epoch 67/100
115/115 [==============================] - 1s 10ms/step - loss: 0.0834 - accuracy: 0.9763
Epoch 68/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0231 - accuracy: 0.9958
Epoch 69/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0073 - accuracy: 0.9996
Epoch 70/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0045 - accuracy: 0.9997
Epoch 71/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0072 - accuracy: 0.9992
Epoch 72/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0050 - accuracy: 0.9993
Epoch 73/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0045 - accuracy: 0.9995
Epoch 74/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0053 - accuracy: 0.9995
Epoch 75/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0039 - accuracy: 0.9997
Epoch 76/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0035 - accuracy: 0.9995
Epoch 77/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0046 - accuracy: 0.9995
Epoch 78/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0031 - accuracy: 0.9996
Epoch 79/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0052 - accuracy: 0.9992
Epoch 80/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0038 - accuracy: 0.9995
Epoch 81/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0052 - accuracy: 0.9992
Epoch 82/100
115/115 [==============================] - 1s 7ms/step - loss: 0.0037 - accuracy: 0.9995
Epoch 83/100
115/115 [==============================] - 1s 11ms/step - loss: 0.0046 - accuracy: 0.9993
Epoch 84/100
115/115 [==============================] - 1s 9ms/step - loss: 0.0035 - accuracy: 0.9995
Epoch 85/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0040 - accuracy: 0.9995
Epoch 86/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0049 - accuracy: 0.9993
Epoch 87/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0041 - accuracy: 0.9993
Epoch 88/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0030 - accuracy: 0.9996
Epoch 89/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0026 - accuracy: 0.9996
Epoch 90/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0031 - accuracy: 0.9996
Epoch 91/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0038 - accuracy: 0.9993
Epoch 92/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0046 - accuracy: 0.9992
Epoch 93/100
115/115 [==============================] - 1s 6ms/step - loss: 0.4581 - accuracy: 0.8820
Epoch 94/100
115/115 [==============================] - 1s 6ms/step - loss: 0.2928 - accuracy: 0.9165
Epoch 95/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0706 - accuracy: 0.9810
Epoch 96/100
115/115 [==============================] - 1s 5ms/step - loss: 0.0213 - accuracy: 0.9960
Epoch 97/100
115/115 [==============================] - 1s 5ms/step - loss: 0.0091 - accuracy: 0.9986
Epoch 98/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0050 - accuracy: 0.9995
Epoch 99/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0041 - accuracy: 0.9995
Epoch 100/100
115/115 [==============================] - 1s 7ms/step - loss: 0.0031 - accuracy: 0.9993
Epoch 1/100
115/115 [==============================] - 3s 6ms/step - loss: 3.9751 - accuracy: 0.1794
Epoch 2/100
115/115 [==============================] - 1s 6ms/step - loss: 3.3578 - accuracy: 0.2931
Epoch 3/100
115/115 [==============================] - 1s 6ms/step - loss: 2.9852 - accuracy: 0.3684
Epoch 4/100
115/115 [==============================] - 1s 5ms/step - loss: 2.6965 - accuracy: 0.4057
Epoch 5/100
115/115 [==============================] - 1s 5ms/step - loss: 2.4550 - accuracy: 0.4510
Epoch 6/100
115/115 [==============================] - 1s 6ms/step - loss: 2.2570 - accuracy: 0.4802
Epoch 7/100
115/115 [==============================] - 1s 6ms/step - loss: 2.1075 - accuracy: 0.5051
Epoch 8/100
115/115 [==============================] - 1s 6ms/step - loss: 1.9790 - accuracy: 0.5353
Epoch 9/100
115/115 [==============================] - 1s 5ms/step - loss: 1.8579 - accuracy: 0.5526
Epoch 10/100
115/115 [==============================] - 1s 6ms/step - loss: 1.7442 - accuracy: 0.5765
Epoch 11/100
115/115 [==============================] - 1s 6ms/step - loss: 1.6484 - accuracy: 0.6029
Epoch 12/100
115/115 [==============================] - 1s 8ms/step - loss: 1.5689 - accuracy: 0.6126
Epoch 13/100
115/115 [==============================] - 1s 7ms/step - loss: 1.4815 - accuracy: 0.6325
Epoch 14/100
115/115 [==============================] - 1s 8ms/step - loss: 1.4078 - accuracy: 0.6425
Epoch 15/100
115/115 [==============================] - 1s 6ms/step - loss: 1.3435 - accuracy: 0.6599
Epoch 16/100
115/115 [==============================] - 1s 6ms/step - loss: 1.2563 - accuracy: 0.6801
Epoch 17/100
115/115 [==============================] - 1s 6ms/step - loss: 1.1972 - accuracy: 0.6928
Epoch 18/100
115/115 [==============================] - 1s 6ms/step - loss: 1.1296 - accuracy: 0.7069
Epoch 19/100
115/115 [==============================] - 1s 6ms/step - loss: 1.0760 - accuracy: 0.7161
Epoch 20/100
115/115 [==============================] - 1s 6ms/step - loss: 1.0020 - accuracy: 0.7404
Epoch 21/100
115/115 [==============================] - 1s 6ms/step - loss: 0.9485 - accuracy: 0.7512
Epoch 22/100
115/115 [==============================] - 1s 6ms/step - loss: 0.8833 - accuracy: 0.7660
Epoch 23/100
115/115 [==============================] - 1s 6ms/step - loss: 0.8410 - accuracy: 0.7744
Epoch 24/100
115/115 [==============================] - 1s 6ms/step - loss: 0.7912 - accuracy: 0.7888
Epoch 25/100
115/115 [==============================] - 1s 7ms/step - loss: 0.7408 - accuracy: 0.7977
Epoch 26/100
115/115 [==============================] - 1s 6ms/step - loss: 0.6806 - accuracy: 0.8213
Epoch 27/100
115/115 [==============================] - 1s 6ms/step - loss: 0.6529 - accuracy: 0.8290
Epoch 28/100
115/115 [==============================] - 1s 6ms/step - loss: 0.5997 - accuracy: 0.8417
Epoch 29/100
115/115 [==============================] - 1s 8ms/step - loss: 0.5343 - accuracy: 0.8599
Epoch 30/100
115/115 [==============================] - 1s 8ms/step - loss: 0.5035 - accuracy: 0.8643
Epoch 31/100
115/115 [==============================] - 1s 8ms/step - loss: 0.4617 - accuracy: 0.8775
Epoch 32/100
115/115 [==============================] - 1s 7ms/step - loss: 0.4231 - accuracy: 0.8895
Epoch 33/100
115/115 [==============================] - 1s 6ms/step - loss: 0.4051 - accuracy: 0.8945
Epoch 34/100
115/115 [==============================] - 1s 6ms/step - loss: 0.3615 - accuracy: 0.9058
Epoch 35/100
115/115 [==============================] - 1s 6ms/step - loss: 0.3312 - accuracy: 0.9120
Epoch 36/100
115/115 [==============================] - 1s 6ms/step - loss: 0.3114 - accuracy: 0.9176
Epoch 37/100
115/115 [==============================] - 1s 6ms/step - loss: 0.2944 - accuracy: 0.9221
Epoch 38/100
115/115 [==============================] - 1s 6ms/step - loss: 0.2484 - accuracy: 0.9352
Epoch 39/100
115/115 [==============================] - 1s 6ms/step - loss: 0.2155 - accuracy: 0.9501
Epoch 40/100
115/115 [==============================] - 1s 6ms/step - loss: 0.1939 - accuracy: 0.9557
Epoch 41/100
115/115 [==============================] - 1s 6ms/step - loss: 0.1942 - accuracy: 0.9515
Epoch 42/100
115/115 [==============================] - 1s 7ms/step - loss: 0.1908 - accuracy: 0.9496
Epoch 43/100
115/115 [==============================] - 1s 6ms/step - loss: 0.1698 - accuracy: 0.9584
Epoch 44/100
115/115 [==============================] - 1s 5ms/step - loss: 0.1276 - accuracy: 0.9751
Epoch 45/100
115/115 [==============================] - 1s 6ms/step - loss: 0.1242 - accuracy: 0.9728
Epoch 46/100
115/115 [==============================] - 1s 8ms/step - loss: 0.1113 - accuracy: 0.9761
Epoch 47/100
115/115 [==============================] - 1s 9ms/step - loss: 0.1100 - accuracy: 0.9762
Epoch 48/100
115/115 [==============================] - 1s 8ms/step - loss: 0.1038 - accuracy: 0.9769
Epoch 49/100
115/115 [==============================] - 1s 7ms/step - loss: 0.1414 - accuracy: 0.9606
Epoch 50/100
115/115 [==============================] - 1s 6ms/step - loss: 0.1330 - accuracy: 0.9613
Epoch 51/100
115/115 [==============================] - 1s 6ms/step - loss: 0.1189 - accuracy: 0.9686
Epoch 52/100
115/115 [==============================] - 1s 6ms/step - loss: 0.1232 - accuracy: 0.9679
Epoch 53/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0706 - accuracy: 0.9876
Epoch 54/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0419 - accuracy: 0.9947
Epoch 55/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0282 - accuracy: 0.9982
Epoch 56/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0220 - accuracy: 0.9990
Epoch 57/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0171 - accuracy: 0.9995
Epoch 58/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0132 - accuracy: 0.9999
Epoch 59/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0146 - accuracy: 0.9996
Epoch 60/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0115 - accuracy: 0.9997
Epoch 61/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0100 - accuracy: 0.9999
Epoch 62/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0088 - accuracy: 0.9999
Epoch 63/100
115/115 [==============================] - 1s 7ms/step - loss: 0.0100 - accuracy: 0.9997
Epoch 64/100
115/115 [==============================] - 1s 9ms/step - loss: 0.0070 - accuracy: 0.9999
Epoch 65/100
115/115 [==============================] - 1s 9ms/step - loss: 0.0083 - accuracy: 0.9999
Epoch 66/100
115/115 [==============================] - 1s 8ms/step - loss: 0.0094 - accuracy: 0.9997
Epoch 67/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0060 - accuracy: 0.9999
Epoch 68/100
115/115 [==============================] - 1s 6ms/step - loss: 0.5901 - accuracy: 0.8383
Epoch 69/100
115/115 [==============================] - 1s 6ms/step - loss: 0.3101 - accuracy: 0.9057
Epoch 70/100
115/115 [==============================] - 1s 6ms/step - loss: 0.1420 - accuracy: 0.9594
Epoch 71/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0625 - accuracy: 0.9841
Epoch 72/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0279 - accuracy: 0.9960
Epoch 73/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0131 - accuracy: 0.9996
Epoch 74/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0089 - accuracy: 0.9999
Epoch 75/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0074 - accuracy: 0.9997
Epoch 76/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0073 - accuracy: 0.9999
Epoch 77/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0070 - accuracy: 0.9997
Epoch 78/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0074 - accuracy: 0.9997
Epoch 79/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0066 - accuracy: 0.9997
Epoch 80/100
115/115 [==============================] - 1s 7ms/step - loss: 0.0060 - accuracy: 0.9997
Epoch 81/100
115/115 [==============================] - 1s 9ms/step - loss: 0.0045 - accuracy: 0.9999
Epoch 82/100
115/115 [==============================] - 1s 8ms/step - loss: 0.0043 - accuracy: 0.9997
Epoch 83/100
115/115 [==============================] - 1s 7ms/step - loss: 0.0044 - accuracy: 0.9999
Epoch 84/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0043 - accuracy: 0.9999
Epoch 85/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0034 - accuracy: 0.9999
Epoch 86/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0057 - accuracy: 0.9999
Epoch 87/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0044 - accuracy: 0.9999
Epoch 88/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0039 - accuracy: 0.9999
Epoch 89/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0054 - accuracy: 0.9997
Epoch 90/100
115/115 [==============================] - 1s 6ms/step - loss: 0.4483 - accuracy: 0.8893
Epoch 91/100
115/115 [==============================] - 1s 6ms/step - loss: 0.4209 - accuracy: 0.8786
Epoch 92/100
115/115 [==============================] - 1s 6ms/step - loss: 0.1125 - accuracy: 0.9687
Epoch 93/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0326 - accuracy: 0.9943
Epoch 94/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0113 - accuracy: 0.9999
Epoch 95/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0082 - accuracy: 0.9997
Epoch 96/100
115/115 [==============================] - 1s 6ms/step - loss: 0.0061 - accuracy: 0.9996
Epoch 97/100

### STL-10

In [ ]:
# model.fit(X_train_resized, y_train, batch_size=128, epochs=100, validation_data=(X_test_resized, y_test))
import tensorflow as tf
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras import layers
from sklearn.model_selection import KFold
def create_model():
    model = keras.Sequential([
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(96, 96, 3)),  # Update input shape
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(64, activation='relu'),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])

    return model

# Define the number of folds for cross-validation
num_folds = 5
kf = KFold(n_splits=num_folds, shuffle=True)

fold_accuracy = []
for train_index, val_index in kf.split(x):
    # Split the data into training and validation sets
    x_train_fold, x_val_fold = x[train_index], x[val_index]
    y_train_fold, y_val_fold = y[train_index], y[val_index]
    with tf.device('/device:GPU:0'):
      model = create_model()
      model.fit(x_train_fold, y_train_fold, epochs=100, batch_size=64, verbose=1)
    # Evaluate the model on the validation data
      _, accuracy = model.evaluate(x_val_fold, y_val_fold, verbose=0)
      fold_accuracy.append(accuracy)


average_accuracy = np.mean(fold_accuracy)
print('Average accuracy:', average_accuracy)
i = 0
float2 = "{0:.2f}"
for score in fold_accuracy:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Epoch 1/100
163/163 [==============================] - 14s 16ms/step - loss: 9.6589 - accuracy: 0.3256
Epoch 2/100
163/163 [==============================] - 2s 14ms/step - loss: 1.2792 - accuracy: 0.5311
Epoch 3/100
163/163 [==============================] - 2s 14ms/step - loss: 0.8609 - accuracy: 0.6944
Epoch 4/100
163/163 [==============================] - 3s 16ms/step - loss: 0.5262 - accuracy: 0.8182
Epoch 5/100
163/163 [==============================] - 2s 15ms/step - loss: 0.2952 - accuracy: 0.9075
Epoch 6/100
163/163 [==============================] - 2s 15ms/step - loss: 0.1752 - accuracy: 0.9467
Epoch 7/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0999 - accuracy: 0.9726
Epoch 8/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0503 - accuracy: 0.9874
Epoch 9/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0539 - accuracy: 0.9855
Epoch 10/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0647 - accuracy: 0.9810
Epoch 11/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0664 - accuracy: 0.9802
Epoch 12/100
163/163 [==============================] - 2s 14ms/step - loss: 0.1306 - accuracy: 0.9591
Epoch 13/100
163/163 [==============================] - 2s 14ms/step - loss: 0.1482 - accuracy: 0.9549
Epoch 14/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0921 - accuracy: 0.9714
Epoch 15/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0390 - accuracy: 0.9899
Epoch 16/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0528 - accuracy: 0.9838
Epoch 17/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0660 - accuracy: 0.9793
Epoch 18/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0547 - accuracy: 0.9841
Epoch 19/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0937 - accuracy: 0.9711
Epoch 20/100
163/163 [==============================] - 3s 15ms/step - loss: 0.0759 - accuracy: 0.9784
Epoch 21/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0773 - accuracy: 0.9755
Epoch 22/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0450 - accuracy: 0.9887
Epoch 23/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0424 - accuracy: 0.9887
Epoch 24/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0617 - accuracy: 0.9806
Epoch 25/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0824 - accuracy: 0.9757
Epoch 26/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0726 - accuracy: 0.9782
Epoch 27/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0866 - accuracy: 0.9771
Epoch 28/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0816 - accuracy: 0.9787
Epoch 29/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0567 - accuracy: 0.9844
Epoch 30/100
163/163 [==============================] - 3s 16ms/step - loss: 0.0446 - accuracy: 0.9878
Epoch 31/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0560 - accuracy: 0.9840
Epoch 32/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0487 - accuracy: 0.9872
Epoch 33/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0500 - accuracy: 0.9864
Epoch 34/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0330 - accuracy: 0.9899
Epoch 35/100
163/163 [==============================] - 3s 16ms/step - loss: 0.0739 - accuracy: 0.9827
Epoch 36/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0683 - accuracy: 0.9827
Epoch 37/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0323 - accuracy: 0.9919
Epoch 38/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0396 - accuracy: 0.9891
Epoch 39/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0403 - accuracy: 0.9896
Epoch 40/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0500 - accuracy: 0.9871
Epoch 41/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0583 - accuracy: 0.9852
Epoch 42/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0743 - accuracy: 0.9805
Epoch 43/100
163/163 [==============================] - 2s 14ms/step - loss: 0.1183 - accuracy: 0.9761
Epoch 44/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0461 - accuracy: 0.9880
Epoch 45/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0369 - accuracy: 0.9894
Epoch 46/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0685 - accuracy: 0.9850
Epoch 47/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0322 - accuracy: 0.9923
Epoch 48/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0491 - accuracy: 0.9887
Epoch 49/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0570 - accuracy: 0.9866
Epoch 50/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0593 - accuracy: 0.9859
Epoch 51/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0619 - accuracy: 0.9876
Epoch 52/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0627 - accuracy: 0.9884
Epoch 53/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0395 - accuracy: 0.9898
Epoch 54/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0916 - accuracy: 0.9816
Epoch 55/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0499 - accuracy: 0.9895
Epoch 56/100
163/163 [==============================] - 3s 16ms/step - loss: 0.0516 - accuracy: 0.9890
Epoch 57/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0277 - accuracy: 0.9932
Epoch 58/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0215 - accuracy: 0.9952
Epoch 59/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0354 - accuracy: 0.9928
Epoch 60/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0779 - accuracy: 0.9837
Epoch 61/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0331 - accuracy: 0.9922
Epoch 62/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0167 - accuracy: 0.9949
Epoch 63/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0467 - accuracy: 0.9897
Epoch 64/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0955 - accuracy: 0.9820
Epoch 65/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0879 - accuracy: 0.9848
Epoch 66/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0663 - accuracy: 0.9876
Epoch 67/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0449 - accuracy: 0.9896
Epoch 68/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0382 - accuracy: 0.9925
Epoch 69/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0149 - accuracy: 0.9962
Epoch 70/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0106 - accuracy: 0.9975
Epoch 71/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0232 - accuracy: 0.9950
Epoch 72/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0599 - accuracy: 0.9897
Epoch 73/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0951 - accuracy: 0.9828
Epoch 74/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0759 - accuracy: 0.9844
Epoch 75/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0247 - accuracy: 0.9943
Epoch 76/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0484 - accuracy: 0.9903
Epoch 77/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0583 - accuracy: 0.9898
Epoch 78/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0382 - accuracy: 0.9929
Epoch 79/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0151 - accuracy: 0.9959
Epoch 80/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0307 - accuracy: 0.9947
Epoch 81/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0338 - accuracy: 0.9934
Epoch 82/100
163/163 [==============================] - 3s 16ms/step - loss: 0.0299 - accuracy: 0.9939
Epoch 83/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0335 - accuracy: 0.9920
Epoch 84/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0375 - accuracy: 0.9936
Epoch 85/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0596 - accuracy: 0.9898
Epoch 86/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0396 - accuracy: 0.9919
Epoch 87/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0334 - accuracy: 0.9939
Epoch 88/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0187 - accuracy: 0.9949
Epoch 89/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0740 - accuracy: 0.9866
Epoch 90/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0516 - accuracy: 0.9912
Epoch 91/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0408 - accuracy: 0.9924
Epoch 92/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0334 - accuracy: 0.9943
Epoch 93/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0469 - accuracy: 0.9923
Epoch 94/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0499 - accuracy: 0.9916
Epoch 95/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0223 - accuracy: 0.9966
Epoch 96/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0209 - accuracy: 0.9959
Epoch 97/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0198 - accuracy: 0.9950
Epoch 98/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0480 - accuracy: 0.9933
Epoch 99/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0673 - accuracy: 0.9891
Epoch 100/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0335 - accuracy: 0.9948
Epoch 1/100
163/163 [==============================] - 4s 15ms/step - loss: 19.6183 - accuracy: 0.2656
Epoch 2/100
163/163 [==============================] - 2s 15ms/step - loss: 1.5421 - accuracy: 0.4402
Epoch 3/100
163/163 [==============================] - 2s 14ms/step - loss: 1.2003 - accuracy: 0.5606
Epoch 4/100
163/163 [==============================] - 2s 15ms/step - loss: 0.8982 - accuracy: 0.6775
Epoch 5/100
163/163 [==============================] - 2s 15ms/step - loss: 0.6366 - accuracy: 0.7746
Epoch 6/100
163/163 [==============================] - 2s 15ms/step - loss: 0.4867 - accuracy: 0.8336
Epoch 7/100
163/163 [==============================] - 2s 15ms/step - loss: 0.3622 - accuracy: 0.8775
Epoch 8/100
163/163 [==============================] - 2s 15ms/step - loss: 0.2574 - accuracy: 0.9185
Epoch 9/100
163/163 [==============================] - 3s 16ms/step - loss: 0.1913 - accuracy: 0.9400
Epoch 10/100
163/163 [==============================] - 2s 14ms/step - loss: 0.1448 - accuracy: 0.9556
Epoch 11/100
163/163 [==============================] - 2s 15ms/step - loss: 0.1176 - accuracy: 0.9671
Epoch 12/100
163/163 [==============================] - 3s 16ms/step - loss: 0.1331 - accuracy: 0.9596
Epoch 13/100
163/163 [==============================] - 2s 15ms/step - loss: 0.1392 - accuracy: 0.9565
Epoch 14/100
163/163 [==============================] - 2s 15ms/step - loss: 0.1176 - accuracy: 0.9647
Epoch 15/100
163/163 [==============================] - 2s 14ms/step - loss: 0.1103 - accuracy: 0.9675
Epoch 16/100
163/163 [==============================] - 2s 14ms/step - loss: 0.1083 - accuracy: 0.9694
Epoch 17/100
163/163 [==============================] - 3s 16ms/step - loss: 0.1219 - accuracy: 0.9649
Epoch 18/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0601 - accuracy: 0.9832
Epoch 19/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0341 - accuracy: 0.9903
Epoch 20/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0441 - accuracy: 0.9880
Epoch 21/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0508 - accuracy: 0.9849
Epoch 22/100
163/163 [==============================] - 3s 16ms/step - loss: 0.0926 - accuracy: 0.9746
Epoch 23/100
163/163 [==============================] - 2s 14ms/step - loss: 0.1203 - accuracy: 0.9669
Epoch 24/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0781 - accuracy: 0.9787
Epoch 25/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0576 - accuracy: 0.9843
Epoch 26/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0469 - accuracy: 0.9871
Epoch 27/100
163/163 [==============================] - 3s 15ms/step - loss: 0.0480 - accuracy: 0.9874
Epoch 28/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0895 - accuracy: 0.9749
Epoch 29/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0502 - accuracy: 0.9862
Epoch 30/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0594 - accuracy: 0.9836
Epoch 31/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0466 - accuracy: 0.9857
Epoch 32/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0624 - accuracy: 0.9833
Epoch 33/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0545 - accuracy: 0.9853
Epoch 34/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0624 - accuracy: 0.9848
Epoch 35/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0568 - accuracy: 0.9837
Epoch 36/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0438 - accuracy: 0.9880
Epoch 37/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0457 - accuracy: 0.9880
Epoch 38/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0292 - accuracy: 0.9927
Epoch 39/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0519 - accuracy: 0.9866
Epoch 40/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0605 - accuracy: 0.9838
Epoch 41/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0583 - accuracy: 0.9862
Epoch 42/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0787 - accuracy: 0.9805
Epoch 43/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0334 - accuracy: 0.9917
Epoch 44/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0191 - accuracy: 0.9965
Epoch 45/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0173 - accuracy: 0.9955
Epoch 46/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0342 - accuracy: 0.9908
Epoch 47/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0692 - accuracy: 0.9810
Epoch 48/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0938 - accuracy: 0.9778
Epoch 49/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0615 - accuracy: 0.9861
Epoch 50/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0694 - accuracy: 0.9826
Epoch 51/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0449 - accuracy: 0.9893
Epoch 52/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0772 - accuracy: 0.9848
Epoch 53/100
163/163 [==============================] - 3s 15ms/step - loss: 0.0953 - accuracy: 0.9813
Epoch 54/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0484 - accuracy: 0.9891
Epoch 55/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0240 - accuracy: 0.9935
Epoch 56/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0401 - accuracy: 0.9909
Epoch 57/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0145 - accuracy: 0.9963
Epoch 58/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0336 - accuracy: 0.9908
Epoch 59/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0173 - accuracy: 0.9959
Epoch 60/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0623 - accuracy: 0.9864
Epoch 61/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0315 - accuracy: 0.9922
Epoch 62/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0651 - accuracy: 0.9846
Epoch 63/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0776 - accuracy: 0.9844
Epoch 64/100
163/163 [==============================] - 2s 15ms/step - loss: 0.1175 - accuracy: 0.9803
Epoch 65/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0588 - accuracy: 0.9867
Epoch 66/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0249 - accuracy: 0.9938
Epoch 67/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0229 - accuracy: 0.9966
Epoch 68/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0524 - accuracy: 0.9891
Epoch 69/100
163/163 [==============================] - 3s 15ms/step - loss: 0.0171 - accuracy: 0.9951
Epoch 70/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0124 - accuracy: 0.9968
Epoch 71/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0062 - accuracy: 0.9983
Epoch 72/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0034 - accuracy: 0.9990
Epoch 73/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0166 - accuracy: 0.9963
Epoch 74/100
163/163 [==============================] - 3s 15ms/step - loss: 0.0445 - accuracy: 0.9900
Epoch 75/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0943 - accuracy: 0.9812
Epoch 76/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0971 - accuracy: 0.9834
Epoch 77/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0361 - accuracy: 0.9918
Epoch 78/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0422 - accuracy: 0.9921
Epoch 79/100
163/163 [==============================] - 3s 16ms/step - loss: 0.0653 - accuracy: 0.9857
Epoch 80/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0378 - accuracy: 0.9916
Epoch 81/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0598 - accuracy: 0.9876
Epoch 82/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0296 - accuracy: 0.9935
Epoch 83/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0301 - accuracy: 0.9944
Epoch 84/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0719 - accuracy: 0.9867
Epoch 85/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0577 - accuracy: 0.9881
Epoch 86/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0256 - accuracy: 0.9948
Epoch 87/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0128 - accuracy: 0.9967
Epoch 88/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0558 - accuracy: 0.9904
Epoch 89/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0345 - accuracy: 0.9947
Epoch 90/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0055 - accuracy: 0.9984
Epoch 91/100
163/163 [==============================] - 2s 14ms/step - loss: 0.0602 - accuracy: 0.9900
Epoch 92/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0511 - accuracy: 0.9917
Epoch 93/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0655 - accuracy: 0.9876
Epoch 94/100
163/163 [==============================] - 2s 15ms/step - loss: 0.0583 - accuracy: 0.9901
Epoch 95/100

## K-Fold cross validation : (10)

### MNIST

In [ ]:
import numpy as np
from tensorflow import keras
from sklearn.model_selection import KFold

(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()
# Concatenate the entire dataset
x = np.concatenate((x_train, x_test), axis=0)
y = np.concatenate((y_train, y_test), axis=0)
def create_model():
    model = keras.Sequential([
        keras.layers.Flatten(input_shape=(28, 28)),
        keras.layers.Dense(128, activation='relu'),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model

kf= KFold(n_splits=10, shuffle=True, random_state=42)

fold_accuracy = []
for train_index, val_index in kf.split(x):
    # Split the data into training and validation sets
    x_train_fold, x_val_fold = x[train_index], x[val_index]
    y_train_fold, y_val_fold = y[train_index], y[val_index]
    model = create_model()
    model.fit(x_train_fold, y_train_fold, epochs=10, batch_size=64, verbose=1)
    # Evaluate the model on the validation data
    _, accuracy = model.evaluate(x_val_fold, y_val_fold, verbose=0)
    fold_accuracy.append(accuracy)


average_accuracy = np.mean(fold_accuracy)
print('Average accuracy:', average_accuracy)
i = 0
float2 = "{0:.2f}"
for score in fold_accuracy:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
11490434/11490434 [==============================] - 0s 0us/step
Epoch 1/10
985/985 [==============================] - 8s 5ms/step - loss: 2.7133 - accuracy: 0.8463
Epoch 2/10
985/985 [==============================] - 4s 4ms/step - loss: 0.4016 - accuracy: 0.9051
Epoch 3/10
985/985 [==============================] - 4s 4ms/step - loss: 0.2768 - accuracy: 0.9308
Epoch 4/10
985/985 [==============================] - 6s 6ms/step - loss: 0.2226 - accuracy: 0.9408
Epoch 5/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1970 - accuracy: 0.9466
Epoch 6/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1850 - accuracy: 0.9511
Epoch 7/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1788 - accuracy: 0.9536
Epoch 8/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1682 - accuracy: 0.9572
Epoch 9/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1597 - accuracy: 0.9584
Epoch 10/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1427 - accuracy: 0.9621
Epoch 1/10
985/985 [==============================] - 6s 4ms/step - loss: 3.2709 - accuracy: 0.8712
Epoch 2/10
985/985 [==============================] - 5s 5ms/step - loss: 0.4033 - accuracy: 0.9139
Epoch 3/10
985/985 [==============================] - 4s 4ms/step - loss: 0.2584 - accuracy: 0.9353
Epoch 4/10
985/985 [==============================] - 4s 4ms/step - loss: 0.2153 - accuracy: 0.9436
Epoch 5/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1989 - accuracy: 0.9477
Epoch 6/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1831 - accuracy: 0.9516
Epoch 7/10
985/985 [==============================] - 6s 6ms/step - loss: 0.1754 - accuracy: 0.9540
Epoch 8/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1705 - accuracy: 0.9558
Epoch 9/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1457 - accuracy: 0.9609
Epoch 10/10
985/985 [==============================] - 5s 5ms/step - loss: 0.1471 - accuracy: 0.9622
Epoch 1/10
985/985 [==============================] - 6s 4ms/step - loss: 3.5492 - accuracy: 0.8791
Epoch 2/10
985/985 [==============================] - 5s 5ms/step - loss: 0.4770 - accuracy: 0.9117
Epoch 3/10
985/985 [==============================] - 4s 4ms/step - loss: 0.2773 - accuracy: 0.9339
Epoch 4/10
985/985 [==============================] - 5s 5ms/step - loss: 0.2206 - accuracy: 0.9436
Epoch 5/10
985/985 [==============================] - 6s 6ms/step - loss: 0.1981 - accuracy: 0.9482
Epoch 6/10
985/985 [==============================] - 4s 5ms/step - loss: 0.1815 - accuracy: 0.9516
Epoch 7/10
985/985 [==============================] - 5s 5ms/step - loss: 0.1729 - accuracy: 0.9553
Epoch 8/10
985/985 [==============================] - 5s 5ms/step - loss: 0.1614 - accuracy: 0.9581
Epoch 9/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1483 - accuracy: 0.9607
Epoch 10/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1514 - accuracy: 0.9613
Epoch 1/10
985/985 [==============================] - 6s 4ms/step - loss: 3.1751 - accuracy: 0.8717
Epoch 2/10
985/985 [==============================] - 4s 4ms/step - loss: 0.4305 - accuracy: 0.9114
Epoch 3/10
985/985 [==============================] - 4s 4ms/step - loss: 0.2840 - accuracy: 0.9329
Epoch 4/10
985/985 [==============================] - 4s 4ms/step - loss: 0.2207 - accuracy: 0.9456
Epoch 5/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1945 - accuracy: 0.9497
Epoch 6/10
985/985 [==============================] - 3s 4ms/step - loss: 0.1885 - accuracy: 0.9520
Epoch 7/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1741 - accuracy: 0.9553
Epoch 8/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1586 - accuracy: 0.9587
Epoch 9/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1582 - accuracy: 0.9586
Epoch 10/10
985/985 [==============================] - 5s 5ms/step - loss: 0.1485 - accuracy: 0.9610
Epoch 1/10
985/985 [==============================] - 5s 4ms/step - loss: 3.1334 - accuracy: 0.8653
Epoch 2/10
985/985 [==============================] - 4s 4ms/step - loss: 0.4476 - accuracy: 0.9061
Epoch 3/10
985/985 [==============================] - 4s 4ms/step - loss: 0.2822 - accuracy: 0.9312
Epoch 4/10
985/985 [==============================] - 4s 4ms/step - loss: 0.2252 - accuracy: 0.9416
Epoch 5/10
985/985 [==============================] - 5s 5ms/step - loss: 0.1971 - accuracy: 0.9483
Epoch 6/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1851 - accuracy: 0.9518
Epoch 7/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1722 - accuracy: 0.9547
Epoch 8/10
985/985 [==============================] - 5s 5ms/step - loss: 0.1615 - accuracy: 0.9584
Epoch 9/10
985/985 [==============================] - 5s 5ms/step - loss: 0.1562 - accuracy: 0.9599
Epoch 10/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1446 - accuracy: 0.9620
Epoch 1/10
985/985 [==============================] - 5s 4ms/step - loss: 2.7576 - accuracy: 0.8559
Epoch 2/10
985/985 [==============================] - 3s 4ms/step - loss: 0.3949 - accuracy: 0.9112
Epoch 3/10
985/985 [==============================] - 5s 5ms/step - loss: 0.2637 - accuracy: 0.9321
Epoch 4/10
985/985 [==============================] - 4s 4ms/step - loss: 0.2202 - accuracy: 0.9437
Epoch 5/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1927 - accuracy: 0.9497
Epoch 6/10
985/985 [==============================] - 5s 5ms/step - loss: 0.1744 - accuracy: 0.9538
Epoch 7/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1635 - accuracy: 0.9571
Epoch 8/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1548 - accuracy: 0.9593
Epoch 9/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1470 - accuracy: 0.9612
Epoch 10/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1426 - accuracy: 0.9632
Epoch 1/10
985/985 [==============================] - 5s 4ms/step - loss: 3.5589 - accuracy: 0.8780
Epoch 2/10
985/985 [==============================] - 4s 4ms/step - loss: 0.4509 - accuracy: 0.9147
Epoch 3/10
985/985 [==============================] - 4s 4ms/step - loss: 0.2815 - accuracy: 0.9338
Epoch 4/10
985/985 [==============================] - 4s 4ms/step - loss: 0.2225 - accuracy: 0.9446
Epoch 5/10
985/985 [==============================] - 4s 4ms/step - loss: 0.2044 - accuracy: 0.9474
Epoch 6/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1951 - accuracy: 0.9519
Epoch 7/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1656 - accuracy: 0.9565
Epoch 8/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1573 - accuracy: 0.9583
Epoch 9/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1533 - accuracy: 0.9607
Epoch 10/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1476 - accuracy: 0.9624
Epoch 1/10
985/985 [==============================] - 6s 5ms/step - loss: 3.4707 - accuracy: 0.8630
Epoch 2/10
985/985 [==============================] - 4s 4ms/step - loss: 0.4076 - accuracy: 0.9172
Epoch 3/10
985/985 [==============================] - 4s 4ms/step - loss: 0.2630 - accuracy: 0.9357
Epoch 4/10
985/985 [==============================] - 4s 4ms/step - loss: 0.2124 - accuracy: 0.9453
Epoch 5/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1921 - accuracy: 0.9494
Epoch 6/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1798 - accuracy: 0.9520
Epoch 7/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1758 - accuracy: 0.9556
Epoch 8/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1602 - accuracy: 0.9573
Epoch 9/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1503 - accuracy: 0.9606
Epoch 10/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1443 - accuracy: 0.9621
Epoch 1/10
985/985 [==============================] - 5s 4ms/step - loss: 3.2893 - accuracy: 0.8589
Epoch 2/10
985/985 [==============================] - 4s 4ms/step - loss: 0.4313 - accuracy: 0.9084
Epoch 3/10
985/985 [==============================] - 5s 5ms/step - loss: 0.2907 - accuracy: 0.9298
Epoch 4/10
985/985 [==============================] - 4s 4ms/step - loss: 0.2313 - accuracy: 0.9422
Epoch 5/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1925 - accuracy: 0.9497
Epoch 6/10
985/985 [==============================] - 5s 5ms/step - loss: 0.1730 - accuracy: 0.9537
Epoch 7/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1687 - accuracy: 0.9553
Epoch 8/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1677 - accuracy: 0.9552
Epoch 9/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1592 - accuracy: 0.9582
Epoch 10/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1451 - accuracy: 0.9616
Epoch 1/10
985/985 [==============================] - 5s 4ms/step - loss: 3.3139 - accuracy: 0.8737
Epoch 2/10
985/985 [==============================] - 4s 5ms/step - loss: 0.4339 - accuracy: 0.9136
Epoch 3/10
985/985 [==============================] - 4s 4ms/step - loss: 0.2937 - accuracy: 0.9316
Epoch 4/10
985/985 [==============================] - 4s 4ms/step - loss: 0.2344 - accuracy: 0.9402
Epoch 5/10
985/985 [==============================] - 5s 5ms/step - loss: 0.2121 - accuracy: 0.9454
Epoch 6/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1926 - accuracy: 0.9499
Epoch 7/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1795 - accuracy: 0.9536
Epoch 8/10
985/985 [==============================] - 5s 5ms/step - loss: 0.1651 - accuracy: 0.9567
Epoch 9/10
985/985 [==============================] - 4s 4ms/step - loss: 0.1625 - accuracy: 0.9588
Epoch 10/10
985/985 [==============================] - 3s 3ms/step - loss: 0.1464 - accuracy: 0.9625
Average accuracy: 0.9499714195728302
Fold-1: 95.04%
Fold-2: 95.17%
Fold-3: 94.86%
Fold-4: 94.07%
Fold-5: 95.33%
Fold-6: 95.41%
Fold-7: 95.33%
Fold-8: 94.54%
Fold-9: 94.66%
Fold-10: 95.56%

### PermutedMNIST

In [ ]:

import numpy as np
from tensorflow import keras
import numpy as np
from tensorflow import keras
from sklearn.model_selection import KFold
# Load the MNIST dataset
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

# Create a permutation index for the pixel positions
num_pixels = x_train.shape[1] * x_train.shape[2]
perm_index = np.random.permutation(num_pixels)

# Permute the pixels for training and test sets
x_train_permuted = x_train.reshape(-1, num_pixels)[:, perm_index].reshape(-1, x_train.shape[1], x_train.shape[2])
x_test_permuted = x_test.reshape(-1, num_pixels)[:, perm_index].reshape(-1, x_test.shape[1], x_test.shape[2])
x = np.concatenate((x_train_permuted, x_test_permuted), axis=0)
y = np.concatenate((y_train, y_test), axis=0)
# Save the PermutedMNIST data to numpy files
# np.save('permuted_mnist_train_data.npy', x_train_permuted)
# np.save('permuted_mnist_train_labels.npy', y_train)
# np.save('permuted_mnist_test_data.npy', x_test_permuted)
# np.save('permuted_mnist_test_labels.npy', y_test)

def create_model():
    model = keras.Sequential([
        keras.layers.Flatten(input_shape=(28, 28)),
        keras.layers.Dense(128, activation='relu'),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model

kfold = KFold(n_splits=10, shuffle=True, random_state=42)

accuracies = []
for train_idx, val_idx in kfold.split(x):
    model = create_model()
    model.fit(x[train_idx], y[train_idx], epochs=5, batch_size=32, verbose=0)
    _, accuracy = model.evaluate(x[val_idx], y[val_idx], verbose=0)
    accuracies.append(accuracy)

mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)

print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)
i = 0
float2 = "{0:.2f}"
for score in accuracies:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Mean accuracy: 0.9400857090950012
Standard deviation: 0.004260017703087816
Fold-1: 94.34%
Fold-2: 94.20%
Fold-3: 94.13%
Fold-4: 93.93%
Fold-5: 94.49%
Fold-6: 94.29%
Fold-7: 94.27%
Fold-8: 92.99%
Fold-9: 93.54%
Fold-10: 93.91%

### Fashion-MNIST

In [ ]:
import numpy as np
from tensorflow import keras
from sklearn.model_selection import KFold

(x_train, y_train), (x_test, y_test) = keras.datasets.fashion_mnist.load_data()
# Concatenate the entire dataset
x = np.concatenate((x_train, x_test), axis=0)
y = np.concatenate((y_train, y_test), axis=0)
def create_model():
    model = keras.Sequential([
        keras.layers.Flatten(input_shape=(28, 28)),
        keras.layers.Dense(128, activation='relu'),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model

kf= KFold(n_splits=10, shuffle=True, random_state=42)

fold_accuracy = []
for train_index, val_index in kf.split(x):
    # Split the data into training and validation sets
    x_train_fold, x_val_fold = x[train_index], x[val_index]
    y_train_fold, y_val_fold = y[train_index], y[val_index]
    model = create_model()
    model.fit(x_train_fold, y_train_fold, epochs=10, batch_size=64, verbose=1)
    # Evaluate the model on the validation data
    _, accuracy = model.evaluate(x_val_fold, y_val_fold, verbose=0)
    fold_accuracy.append(accuracy)

# mean_accuracy = np.mean(accuracies)
# std_accuracy = np.std(accuracies)

# print("Mean accuracy:", mean_accuracy)
# print("Standard deviation:", std_accuracy)
# Calculate and print the average accuracy across all folds
average_accuracy = np.mean(fold_accuracy)
print('Average accuracy:', average_accuracy)
i = 0
float2 = "{0:.2f}"
for score in fold_accuracy:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/train-labels-idx1-ubyte.gz
29515/29515 [==============================] - 0s 0us/step
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/train-images-idx3-ubyte.gz
26421880/26421880 [==============================] - 0s 0us/step
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/t10k-labels-idx1-ubyte.gz
5148/5148 [==============================] - 0s 0us/step
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/t10k-images-idx3-ubyte.gz
4422102/4422102 [==============================] - 0s 0us/step
Epoch 1/10
985/985 [==============================] - 3s 3ms/step - loss: 5.4715 - accuracy: 0.7035
Epoch 2/10
985/985 [==============================] - 3s 3ms/step - loss: 0.7723 - accuracy: 0.7291
Epoch 3/10
985/985 [==============================] - 3s 3ms/step - loss: 0.6267 - accuracy: 0.7589
Epoch 4/10
985/985 [==============================] - 3s 3ms/step - loss: 0.5681 - accuracy: 0.7879
Epoch 5/10
985/985 [==============================] - 3s 3ms/step - loss: 0.5249 - accuracy: 0.8161
Epoch 6/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4818 - accuracy: 0.8268
Epoch 7/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4687 - accuracy: 0.8332
Epoch 8/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4582 - accuracy: 0.8365
Epoch 9/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4536 - accuracy: 0.8383
Epoch 10/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4398 - accuracy: 0.8447
Epoch 1/10
985/985 [==============================] - 4s 3ms/step - loss: 4.4139 - accuracy: 0.7070
Epoch 2/10
985/985 [==============================] - 3s 3ms/step - loss: 0.6935 - accuracy: 0.7603
Epoch 3/10
985/985 [==============================] - 3s 3ms/step - loss: 0.5709 - accuracy: 0.7952
Epoch 4/10
985/985 [==============================] - 3s 3ms/step - loss: 0.5133 - accuracy: 0.8165
Epoch 5/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4853 - accuracy: 0.8281
Epoch 6/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4623 - accuracy: 0.8380
Epoch 7/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4538 - accuracy: 0.8397
Epoch 8/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4452 - accuracy: 0.8444
Epoch 9/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4310 - accuracy: 0.8500
Epoch 10/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4278 - accuracy: 0.8496
Epoch 1/10
985/985 [==============================] - 3s 3ms/step - loss: 3.6223 - accuracy: 0.7143
Epoch 2/10
985/985 [==============================] - 3s 3ms/step - loss: 0.6990 - accuracy: 0.7774
Epoch 3/10
985/985 [==============================] - 3s 3ms/step - loss: 0.5780 - accuracy: 0.8052
Epoch 4/10
985/985 [==============================] - 3s 3ms/step - loss: 0.5196 - accuracy: 0.8218
Epoch 5/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4774 - accuracy: 0.8323
Epoch 6/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4660 - accuracy: 0.8355
Epoch 7/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4544 - accuracy: 0.8393
Epoch 8/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4451 - accuracy: 0.8440
Epoch 9/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4379 - accuracy: 0.8470
Epoch 10/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4240 - accuracy: 0.8512
Epoch 1/10
985/985 [==============================] - 4s 3ms/step - loss: 4.7979 - accuracy: 0.6985
Epoch 2/10
985/985 [==============================] - 3s 3ms/step - loss: 0.7406 - accuracy: 0.7200
Epoch 3/10
985/985 [==============================] - 3s 3ms/step - loss: 0.6141 - accuracy: 0.7576
Epoch 4/10
985/985 [==============================] - 3s 3ms/step - loss: 0.5773 - accuracy: 0.7775
Epoch 5/10
985/985 [==============================] - 3s 3ms/step - loss: 0.5236 - accuracy: 0.8127
Epoch 6/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4969 - accuracy: 0.8253
Epoch 7/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4825 - accuracy: 0.8299
Epoch 8/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4649 - accuracy: 0.8356
Epoch 9/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4625 - accuracy: 0.8355
Epoch 10/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4604 - accuracy: 0.8370
Epoch 1/10
985/985 [==============================] - 3s 3ms/step - loss: 4.9582 - accuracy: 0.7001
Epoch 2/10
985/985 [==============================] - 3s 3ms/step - loss: 0.7577 - accuracy: 0.7241
Epoch 3/10
985/985 [==============================] - 3s 3ms/step - loss: 0.6326 - accuracy: 0.7614
Epoch 4/10
985/985 [==============================] - 3s 3ms/step - loss: 0.5765 - accuracy: 0.7830
Epoch 5/10
985/985 [==============================] - 3s 3ms/step - loss: 0.5435 - accuracy: 0.7953
Epoch 6/10
985/985 [==============================] - 3s 3ms/step - loss: 0.5318 - accuracy: 0.8009
Epoch 7/10
985/985 [==============================] - 3s 3ms/step - loss: 0.5053 - accuracy: 0.8121
Epoch 8/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4700 - accuracy: 0.8358
Epoch 9/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4438 - accuracy: 0.8435
Epoch 10/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4445 - accuracy: 0.8452
Epoch 1/10
985/985 [==============================] - 4s 3ms/step - loss: 4.9303 - accuracy: 0.6907
Epoch 2/10
985/985 [==============================] - 3s 3ms/step - loss: 0.7874 - accuracy: 0.7078
Epoch 3/10
985/985 [==============================] - 3s 3ms/step - loss: 0.6518 - accuracy: 0.7517
Epoch 4/10
985/985 [==============================] - 3s 3ms/step - loss: 0.5633 - accuracy: 0.7945
Epoch 5/10
985/985 [==============================] - 3s 3ms/step - loss: 0.5309 - accuracy: 0.8075
Epoch 6/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4976 - accuracy: 0.8229
Epoch 7/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4863 - accuracy: 0.8305
Epoch 8/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4746 - accuracy: 0.8358
Epoch 9/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4638 - accuracy: 0.8387
Epoch 10/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4584 - accuracy: 0.8405
Epoch 1/10
985/985 [==============================] - 3s 3ms/step - loss: 4.2260 - accuracy: 0.7028
Epoch 2/10
985/985 [==============================] - 3s 3ms/step - loss: 0.6968 - accuracy: 0.7630
Epoch 3/10
985/985 [==============================] - 3s 3ms/step - loss: 0.6069 - accuracy: 0.7832
Epoch 4/10
985/985 [==============================] - 3s 3ms/step - loss: 0.5450 - accuracy: 0.8042
Epoch 5/10
985/985 [==============================] - 3s 3ms/step - loss: 0.5073 - accuracy: 0.8202
Epoch 6/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4784 - accuracy: 0.8300
Epoch 7/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4598 - accuracy: 0.8376
Epoch 8/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4520 - accuracy: 0.8414
Epoch 9/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4424 - accuracy: 0.8447
Epoch 10/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4341 - accuracy: 0.8466
Epoch 1/10
985/985 [==============================] - 4s 3ms/step - loss: 4.6084 - accuracy: 0.6905
Epoch 2/10
985/985 [==============================] - 3s 3ms/step - loss: 0.7831 - accuracy: 0.7455
Epoch 3/10
985/985 [==============================] - 3s 3ms/step - loss: 0.6037 - accuracy: 0.7908
Epoch 4/10
985/985 [==============================] - 3s 3ms/step - loss: 0.5276 - accuracy: 0.8156
Epoch 5/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4999 - accuracy: 0.8259
Epoch 6/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4717 - accuracy: 0.8365
Epoch 7/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4535 - accuracy: 0.8425
Epoch 8/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4322 - accuracy: 0.8485
Epoch 9/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4344 - accuracy: 0.8481
Epoch 10/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4286 - accuracy: 0.8490
Epoch 1/10
985/985 [==============================] - 3s 3ms/step - loss: 3.7405 - accuracy: 0.6875
Epoch 2/10
985/985 [==============================] - 3s 3ms/step - loss: 0.7266 - accuracy: 0.7497
Epoch 3/10
985/985 [==============================] - 3s 3ms/step - loss: 0.6232 - accuracy: 0.7733
Epoch 4/10
985/985 [==============================] - 3s 3ms/step - loss: 0.5400 - accuracy: 0.8098
Epoch 5/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4875 - accuracy: 0.8298
Epoch 6/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4593 - accuracy: 0.8383
Epoch 7/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4434 - accuracy: 0.8408
Epoch 8/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4447 - accuracy: 0.8423
Epoch 9/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4298 - accuracy: 0.8476
Epoch 10/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4201 - accuracy: 0.8517
Epoch 1/10
985/985 [==============================] - 4s 3ms/step - loss: 3.7278 - accuracy: 0.7008
Epoch 2/10
985/985 [==============================] - 3s 3ms/step - loss: 0.6764 - accuracy: 0.7716
Epoch 3/10
985/985 [==============================] - 3s 3ms/step - loss: 0.5589 - accuracy: 0.7985
Epoch 4/10
985/985 [==============================] - 3s 3ms/step - loss: 0.5132 - accuracy: 0.8185
Epoch 5/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4916 - accuracy: 0.8281
Epoch 6/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4706 - accuracy: 0.8358
Epoch 7/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4606 - accuracy: 0.8391
Epoch 8/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4504 - accuracy: 0.8432
Epoch 9/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4389 - accuracy: 0.8469
Epoch 10/10
985/985 [==============================] - 3s 3ms/step - loss: 0.4395 - accuracy: 0.8466
Average accuracy: 0.8371857106685638
Fold-1: 83.97%
Fold-2: 84.37%
Fold-3: 84.26%
Fold-4: 83.49%
Fold-5: 82.61%
Fold-6: 83.10%
Fold-7: 84.23%
Fold-8: 84.31%
Fold-9: 83.69%
Fold-10: 83.16%

###  Kuzushiji-MNIST

In [ ]:

import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import KFold
# from tensorflow.keras.datasets import kmnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam
import tensorflow_datasets as tfds

from sklearn.model_selection import train_test_split

# (x_train, y_train), (x_test, y_test) = kmnist.load_data()


dataset = tfds.load('kmnist')
train_o, test_o = dataset['train'], dataset['test']

train_numpy = np.vstack(tfds.as_numpy(train_o))
test_numpy = np.vstack(tfds.as_numpy(test_o))

train_x = np.array(list(map(lambda x: x[0]['image'], train_numpy)))
train_y = np.array(list(map(lambda x: x[0]['label'], train_numpy)))

test_x = np.array(list(map(lambda x: x[0]['image'], test_numpy)))
test_y = np.array(list(map(lambda x: x[0]['label'], test_numpy)))

train = np.concatenate((train_x,test_x), axis = 0)
test = np.concatenate((train_y,test_y),axis = 0)

print("it is whole train size ****:\t", train_x.shape)

x_train, x_test, y_train, y_test = train_x, test_x, train_y, test_y
# Concatenate the entire dataset
x = np.concatenate((x_train, x_test), axis=0)
y = np.concatenate((y_train, y_test), axis=0)
def create_model():
    model = keras.Sequential([
        keras.layers.Flatten(input_shape=(28, 28)),
        keras.layers.Dense(128, activation='relu'),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model

kfold = KFold(n_splits=10, shuffle=True, random_state=42)

accuracies = []
for train_idx, val_idx in kfold.split(x):
    model = create_model()
    model.fit(x[train_idx], y[train_idx], epochs=5, batch_size=32, verbose=0)
    _, accuracy = model.evaluate(x[val_idx], y[val_idx], verbose=0)
    accuracies.append(accuracy)

mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)

print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)
i = 0
float2 = "{0:.2f}"
for score in accuracies:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Downloading and preparing dataset 20.26 MiB (download: 20.26 MiB, generated: 31.76 MiB, total: 52.02 MiB) to /root/tensorflow_datasets/kmnist/3.0.1...

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

Generating splits...:   0%|          | 0/2 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/60000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/kmnist/3.0.1.incompleteVUFQCX/kmnist-train.tfrecord*...:   0%|          | …

Generating test examples...:   0%|          | 0/10000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/kmnist/3.0.1.incompleteVUFQCX/kmnist-test.tfrecord*...:   0%|          | 0…

Dataset kmnist downloaded and prepared to /root/tensorflow_datasets/kmnist/3.0.1. Subsequent calls will reuse this data.

<ipython-input-8-30cc501b62cb>:19: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  train_numpy = np.vstack(tfds.as_numpy(train_o))
<ipython-input-8-30cc501b62cb>:20: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  test_numpy = np.vstack(tfds.as_numpy(test_o))

it is whole train size ****:	 (60000, 28, 28, 1)
Mean accuracy: 0.8595714271068573
Standard deviation: 0.005009785360976155
Fold-1: 85.46%
Fold-2: 86.61%
Fold-3: 85.66%
Fold-4: 85.33%
Fold-5: 86.20%
Fold-6: 86.34%
Fold-7: 86.60%
Fold-8: 85.16%
Fold-9: 86.24%
Fold-10: 85.97%

### MNIST-C

In [ ]:
import numpy as np
import tensorflow_datasets as tfds
from sklearn.model_selection import KFold
from keras.models import Sequential
from keras.layers import Dense, Flatten

# Load the MNIST-C dataset
dataset = tfds.load('mnist_corrupted', split='train')
data = list(dataset.as_numpy_iterator())
images = np.array([example['image'] for example in data])
labels = np.array([example['label'] for example in data])

# Define the model architecture
model = Sequential()
model.add(Flatten(input_shape=(28, 28)))
model.add(Dense(128, activation='relu'))
model.add(Dense(10, activation='softmax'))
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Perform k-fold cross-validation
k = 10
kf = KFold(n_splits=k, shuffle=True)

accuracy_scores = []
for train_indices, val_indices in kf.split(images):
    train_images, train_labels = images[train_indices], labels[train_indices]
    val_images, val_labels = images[val_indices], labels[val_indices]

    # Preprocess and normalize the data if necessary

    # Train the model on the current fold
    model.fit(train_images, train_labels, epochs=5, batch_size=32, verbose=0)

    # Evaluate the model on the validation set
    _, accuracy = model.evaluate(val_images, val_labels, verbose=0)
    accuracy_scores.append(accuracy)

# Calculate and print the average accuracy across folds
average_accuracy = sum(accuracy_scores) / k
print("Average accuracy:", average_accuracy)
i = 0
float2 = "{0:.2f}"
for score in accuracy_scores:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Downloading and preparing dataset 235.23 MiB (download: 235.23 MiB, generated: Unknown size, total: 235.23 MiB) to /root/tensorflow_datasets/mnist_corrupted/identity/1.0.0...

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

Generating splits...:   0%|          | 0/2 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/60000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/mnist_corrupted/identity/1.0.0.incompleteD7NWJP/mnist_corrupted-train.tfre…

Generating test examples...:   0%|          | 0/10000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/mnist_corrupted/identity/1.0.0.incompleteD7NWJP/mnist_corrupted-test.tfrec…

Dataset mnist_corrupted downloaded and prepared to /root/tensorflow_datasets/mnist_corrupted/identity/1.0.0. Subsequent calls will reuse this data.
Average accuracy: 0.9592499911785126
Fold-1: 94.10%
Fold-2: 95.23%
Fold-3: 95.05%
Fold-4: 95.65%
Fold-5: 96.23%
Fold-6: 96.62%
Fold-7: 95.83%
Fold-8: 96.73%
Fold-9: 96.98%
Fold-10: 96.82%

### CIFAR10

In [ ]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import KFold

(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()
# Concatenate the entire dataset
x = np.concatenate((x_train, x_test), axis=0)
y = np.concatenate((y_train, y_test), axis=0)
def create_model():
    model = keras.Sequential([
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(64, activation='relu'),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model


kfold = KFold(n_splits=10, shuffle=True, random_state=42)

accuracies = []
for train_idx, val_idx in kfold.split(x):
    model = create_model()
    model.fit(x[train_idx], y[train_idx], epochs=5, batch_size=32, verbose=0)
    _, accuracy = model.evaluate(x[val_idx], y[val_idx], verbose=0)
    accuracies.append(accuracy)

mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)

print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)
i = 0
float2 = "{0:.2f}"
for score in accuracies:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Downloading data from https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
170498071/170498071 [==============================] - 5s 0us/step
Mean accuracy: 0.644266664981842
Standard deviation: 0.01608262570836896
Fold-1: 65.68%
Fold-2: 64.93%
Fold-3: 66.40%
Fold-4: 60.52%
Fold-5: 64.37%
Fold-6: 65.00%
Fold-7: 65.33%
Fold-8: 65.42%
Fold-9: 63.63%
Fold-10: 62.98%

### CIFAR100

In [ ]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import KFold
from tensorflow.keras.optimizers import Adam
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar100.load_data()

# Concatenate the entire dataset
x = np.concatenate((x_train, x_test), axis=0)
y = np.concatenate((y_train, y_test), axis=0)

def create_model():
    model = keras.Sequential([
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(100, activation='softmax')
    ])

    model.compile(optimizer=Adam(learning_rate=0.001),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model



kfold = KFold(n_splits=10, shuffle=True, random_state=42)

accuracies = []
for train_idx, val_idx in kfold.split(x):
    model = create_model()
    model.fit(x[train_idx], y[train_idx], epochs=5, batch_size=32, verbose=0)
    _, accuracy = model.evaluate(x[val_idx], y[val_idx], verbose=0)
    accuracies.append(accuracy)

mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)

print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)

i = 0
float2 = "{0:.2f}"
for score in accuracies:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Downloading data from https://www.cs.toronto.edu/~kriz/cifar-100-python.tar.gz
169001437/169001437 [==============================] - 3s 0us/step
Mean accuracy: 0.3188333362340927
Standard deviation: 0.01297754427392042
Fold-1: 31.38%
Fold-2: 32.80%
Fold-3: 29.97%
Fold-4: 33.85%
Fold-5: 30.18%
Fold-6: 33.67%
Fold-7: 32.20%
Fold-8: 31.37%
Fold-9: 30.78%
Fold-10: 32.63%

### CIFAR10-C

In [ ]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import KFold
from tensorflow.keras.optimizers import Adam
from skimage.util import random_noise
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()

# Concatenate the entire dataset
x = np.concatenate((x_train, x_test), axis=0)
y = np.concatenate((y_train, y_test), axis=0)

y_train = y
# Add speckle noise to the training images
x_train = random_noise(x, mode='speckle', var=0.1)
def create_model():
    model = keras.Sequential([
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model



kfold = KFold(n_splits=10, shuffle=True, random_state=42)

accuracies = []
for train_idx, val_idx in kfold.split(x_train):
    model = create_model()
    model.fit(x_train[train_idx], y_train[train_idx], epochs=5,  verbose=0)
    _, accuracy = model.evaluate(x_train[val_idx], y_train[val_idx])
    accuracies.append(accuracy)

mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)

print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)
i = 0
float2 = "{0:.2f}"
for score in accuracies:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Downloading data from https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
170498071/170498071 [==============================] - 13s 0us/step
188/188 [==============================] - 1s 4ms/step - loss: 0.9558 - accuracy: 0.6662
188/188 [==============================] - 1s 3ms/step - loss: 1.0435 - accuracy: 0.6572
188/188 [==============================] - 1s 3ms/step - loss: 0.9456 - accuracy: 0.6757
188/188 [==============================] - 1s 3ms/step - loss: 0.9389 - accuracy: 0.6718
188/188 [==============================] - 1s 2ms/step - loss: 1.0127 - accuracy: 0.6565
188/188 [==============================] - 1s 3ms/step - loss: 0.9706 - accuracy: 0.6678
188/188 [==============================] - 1s 4ms/step - loss: 0.9868 - accuracy: 0.6608
188/188 [==============================] - 1s 3ms/step - loss: 0.9636 - accuracy: 0.6680
188/188 [==============================] - 1s 3ms/step - loss: 0.9573 - accuracy: 0.6768
188/188 [==============================] - 1s 3ms/step - loss: 1.0177 - accuracy: 0.6425
Mean accuracy: 0.6643333315849305
Standard deviation: 0.009857321910842163
Fold-1: 66.62%
Fold-2: 65.72%
Fold-3: 67.57%
Fold-4: 67.18%
Fold-5: 65.65%
Fold-6: 66.78%
Fold-7: 66.08%
Fold-8: 66.80%
Fold-9: 67.68%
Fold-10: 64.25%

### CIFAR100-C

In [ ]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import KFold
from tensorflow.keras.optimizers import Adam
from skimage.util import random_noise
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar100.load_data()

# Concatenate the entire dataset
x = np.concatenate((x_train, x_test), axis=0)
y = np.concatenate((y_train, y_test), axis=0)

y_train = y
# Add speckle noise to the training images
x_train_noise = random_noise(x, mode='speckle', var=0.1)
def create_model():
    model = keras.Sequential([
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(100, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model



kfold = KFold(n_splits=10, shuffle=True, random_state=42)

accuracies = []
for train_idx, val_idx in kfold.split(x_train_noise):
    model = create_model()
    model.fit(x_train_noise[train_idx], y_train[train_idx], epochs=5, batch_size=32, verbose=0)
    _, accuracy = model.evaluate(x_train_noise[val_idx], y_train[val_idx], verbose=0)
    accuracies.append(accuracy)

mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)

print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)
i = 0
float2 = "{0:.2f}"
for score in accuracies:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Mean accuracy: 0.326566669344902
Standard deviation: 0.0059382010320731815
Fold-1: 33.35%
Fold-2: 32.03%
Fold-3: 32.80%
Fold-4: 32.12%
Fold-5: 32.83%
Fold-6: 33.85%
Fold-7: 32.05%
Fold-8: 32.92%
Fold-9: 31.98%
Fold-10: 32.63%

### SVHN

In [ ]:
!wget http://ufldl.stanford.edu/housenumbers/train_32x32.mat
!wget http://ufldl.stanford.edu/housenumbers/test_32x32.mat

--2023-07-15 10:23:06--  http://ufldl.stanford.edu/housenumbers/train_32x32.mat
Resolving ufldl.stanford.edu (ufldl.stanford.edu)... 171.64.68.10
Connecting to ufldl.stanford.edu (ufldl.stanford.edu)|171.64.68.10|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 182040794 (174M) [text/plain]
Saving to: ‘train_32x32.mat’

train_32x32.mat     100%[===================>] 173.61M  17.1MB/s    in 13s

2023-07-15 10:23:20 (13.0 MB/s) - ‘train_32x32.mat’ saved [182040794/182040794]

--2023-07-15 10:23:20--  http://ufldl.stanford.edu/housenumbers/test_32x32.mat
Resolving ufldl.stanford.edu (ufldl.stanford.edu)... 171.64.68.10
Connecting to ufldl.stanford.edu (ufldl.stanford.edu)|171.64.68.10|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 64275384 (61M) [text/plain]
Saving to: ‘test_32x32.mat’

test_32x32.mat      100%[===================>]  61.30M  16.1MB/s    in 6.9s

2023-07-15 10:23:28 (8.90 MB/s) - ‘test_32x32.mat’ saved [64275384/64275384]

In [ ]:
import numpy as np
from tensorflow import keras
from sklearn.model_selection import KFold
import scipy.io as sio
from tensorflow.keras.utils import to_categorical
# Define the model architecture
def create_model():
    model = keras.Sequential([
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(32, 32, 3)),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(64, activation='relu'),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])

    return model


# Load the SVHN dataset
train_data = sio.loadmat("train_32x32.mat")
test_data = sio.loadmat("test_32x32.mat")

# Extract the images and labels from the downloaded data
train_images = np.transpose(train_data['X'], (3, 0, 1, 2))
train_labels = train_data['y']

test_images = np.transpose(test_data['X'], (3, 0, 1, 2))
test_labels = test_data['y']

# Change class labels to range from 0 to 9
train_labels[train_labels == 10] = 0
test_labels[test_labels == 10] = 0

# Perform one-hot encoding on the labels
num_classes = 10
train_labels = to_categorical(train_labels, num_classes)
test_labels = to_categorical(test_labels, num_classes)

# Print the shape of the loaded data
print("Train images shape:", train_images.shape)
print("Train labels shape:", train_labels.shape)
print("Test images shape:", test_images.shape)
print("Test labels shape:", test_labels.shape)

# Concatenate the entire dataset
x = np.concatenate((train_images, test_images), axis=0)
y = np.concatenate((train_labels, test_labels), axis=0)
print(x.shape, y.shape)
# Define the number of folds for cross-validation
k = 10
kf = KFold(n_splits=k, shuffle=True, random_state=42)

train_images = x
train_labels = y
accuracies = []

# Perform k-fold cross-validation
for train_idx, val_idx in kf.split(train_images):
    # Create a new instance of the model for each fold
    model = create_model()

    # Train the model on the current fold
    model.fit(train_images[train_idx], train_labels[train_idx], epochs=5, batch_size=32, verbose=1)

    # Evaluate the model on the validation fold
    _, accuracy = model.evaluate(train_images[val_idx], train_labels[val_idx], verbose=0)

    # Append the accuracy to the list of accuracies
    accuracies.append(accuracy)

# Compute the mean and standard deviation of the accuracies
mean_accuracy = np.mean(accuracies)
std_accuracy = np.std(accuracies)

# Print the results
print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_accuracy)
i = 0
float2 = "{0:.2f}"
for score in accuracies:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Train images shape: (73257, 32, 32, 3)
Train labels shape: (73257, 10)
Test images shape: (26032, 32, 32, 3)
Test labels shape: (26032, 10)
(99289, 32, 32, 3) (99289, 10)
Epoch 1/5
2793/2793 [==============================] - 13s 4ms/step - loss: 1.1835 - accuracy: 0.6885
Epoch 2/5
2793/2793 [==============================] - 12s 4ms/step - loss: 0.6032 - accuracy: 0.8260
Epoch 3/5
2793/2793 [==============================] - 12s 4ms/step - loss: 0.5258 - accuracy: 0.8485
Epoch 4/5
2793/2793 [==============================] - 12s 4ms/step - loss: 0.4729 - accuracy: 0.8619
Epoch 5/5
2793/2793 [==============================] - 12s 4ms/step - loss: 0.4294 - accuracy: 0.8744
Epoch 1/5
2793/2793 [==============================] - 13s 4ms/step - loss: 1.2101 - accuracy: 0.6752
Epoch 2/5
2793/2793 [==============================] - 12s 4ms/step - loss: 0.6631 - accuracy: 0.8080
Epoch 3/5
2793/2793 [==============================] - 12s 4ms/step - loss: 0.5963 - accuracy: 0.8250
Epoch 4/5
2793/2793 [==============================] - 11s 4ms/step - loss: 0.5427 - accuracy: 0.8413
Epoch 5/5
2793/2793 [==============================] - 12s 4ms/step - loss: 0.4872 - accuracy: 0.8570
Epoch 1/5
2793/2793 [==============================] - 13s 4ms/step - loss: 1.0788 - accuracy: 0.7110
Epoch 2/5
2793/2793 [==============================] - 12s 4ms/step - loss: 0.6222 - accuracy: 0.8211
Epoch 3/5
2793/2793 [==============================] - 12s 4ms/step - loss: 0.5573 - accuracy: 0.8388
Epoch 4/5
2793/2793 [==============================] - 12s 4ms/step - loss: 0.5166 - accuracy: 0.8489
Epoch 5/5
2793/2793 [==============================] - 12s 4ms/step - loss: 0.4811 - accuracy: 0.8593
Epoch 1/5
2793/2793 [==============================] - 14s 4ms/step - loss: 2.4071 - accuracy: 0.1897
Epoch 2/5
2793/2793 [==============================] - 12s 4ms/step - loss: 2.2336 - accuracy: 0.1909
Epoch 3/5
2793/2793 [==============================] - 11s 4ms/step - loss: 2.2335 - accuracy: 0.1909
Epoch 4/5
2793/2793 [==============================] - 12s 4ms/step - loss: 2.2336 - accuracy: 0.1909
Epoch 5/5
2793/2793 [==============================] - 11s 4ms/step - loss: 2.2335 - accuracy: 0.1909
Epoch 1/5
2793/2793 [==============================] - 13s 4ms/step - loss: 1.1536 - accuracy: 0.6779
Epoch 2/5
2793/2793 [==============================] - 11s 4ms/step - loss: 0.6203 - accuracy: 0.8204
Epoch 3/5
2793/2793 [==============================] - 12s 4ms/step - loss: 0.5503 - accuracy: 0.8404
Epoch 4/5
2793/2793 [==============================] - 12s 4ms/step - loss: 0.5127 - accuracy: 0.8520
Epoch 5/5
2793/2793 [==============================] - 12s 4ms/step - loss: 0.4837 - accuracy: 0.8598
Epoch 1/5
2793/2793 [==============================] - 13s 4ms/step - loss: 1.3377 - accuracy: 0.6172
Epoch 2/5
2793/2793 [==============================] - 12s 4ms/step - loss: 0.6631 - accuracy: 0.8110
Epoch 3/5
2793/2793 [==============================] - 11s 4ms/step - loss: 0.5455 - accuracy: 0.8420
Epoch 4/5
2793/2793 [==============================] - 11s 4ms/step - loss: 0.4781 - accuracy: 0.8602
Epoch 5/5
2793/2793 [==============================] - 11s 4ms/step - loss: 0.4364 - accuracy: 0.8716
Epoch 1/5
2793/2793 [==============================] - 13s 4ms/step - loss: 1.3281 - accuracy: 0.6765
Epoch 2/5
2793/2793 [==============================] - 12s 4ms/step - loss: 0.6624 - accuracy: 0.8050
Epoch 3/5
2793/2793 [==============================] - 12s 4ms/step - loss: 0.5813 - accuracy: 0.8286
Epoch 4/5
2793/2793 [==============================] - 12s 4ms/step - loss: 0.5282 - accuracy: 0.8442
Epoch 5/5
2793/2793 [==============================] - 12s 4ms/step - loss: 0.4833 - accuracy: 0.8572
Epoch 1/5
2793/2793 [==============================] - 13s 4ms/step - loss: 1.9327 - accuracy: 0.3505
Epoch 2/5
2793/2793 [==============================] - 12s 4ms/step - loss: 0.7612 - accuracy: 0.7743
Epoch 3/5
2793/2793 [==============================] - 12s 4ms/step - loss: 0.6045 - accuracy: 0.8256
Epoch 4/5
2793/2793 [==============================] - 12s 4ms/step - loss: 0.5476 - accuracy: 0.8423
Epoch 5/5
2793/2793 [==============================] - 11s 4ms/step - loss: 0.5121 - accuracy: 0.8527
Epoch 1/5
2793/2793 [==============================] - 13s 4ms/step - loss: 1.8402 - accuracy: 0.4820
Epoch 2/5
2793/2793 [==============================] - 11s 4ms/step - loss: 0.7874 - accuracy: 0.7648
Epoch 3/5
2793/2793 [==============================] - 11s 4ms/step - loss: 0.6191 - accuracy: 0.8167
Epoch 4/5
2793/2793 [==============================] - 12s 4ms/step - loss: 0.5302 - accuracy: 0.8444
Epoch 5/5
2793/2793 [==============================] - 12s 4ms/step - loss: 0.4824 - accuracy: 0.8589
Epoch 1/5
2793/2793 [==============================] - 13s 4ms/step - loss: 1.1682 - accuracy: 0.6923
Epoch 2/5
2793/2793 [==============================] - 11s 4ms/step - loss: 0.5969 - accuracy: 0.8281
Epoch 3/5
2793/2793 [==============================] - 12s 4ms/step - loss: 0.5282 - accuracy: 0.8466
Epoch 4/5
2793/2793 [==============================] - 12s 4ms/step - loss: 0.4809 - accuracy: 0.8598
Epoch 5/5
2793/2793 [==============================] - 11s 4ms/step - loss: 0.4446 - accuracy: 0.8691
Mean accuracy: 0.7912061795592308
Standard deviation: 0.20006005042206626
Fold-1: 87.31%
Fold-2: 86.49%
Fold-3: 84.67%
Fold-4: 19.16%
Fold-5: 85.55%
Fold-6: 86.45%
Fold-7: 85.81%
Fold-8: 84.37%
Fold-9: 85.18%
Fold-10: 86.21%

### CReditCArd

In [ ]:
!wget -O creditfraud.zip https://www.dropbox.com/s/tl20yp9bcl56oxt/creditcardfraud.zip?dl=0

--2023-07-15 11:04:04--  https://www.dropbox.com/s/tl20yp9bcl56oxt/creditcardfraud.zip?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 162.125.64.18, 2620:100:6025:18::a27d:4512
Connecting to www.dropbox.com (www.dropbox.com)|162.125.64.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /s/raw/tl20yp9bcl56oxt/creditcardfraud.zip [following]
--2023-07-15 11:04:06--  https://www.dropbox.com/s/raw/tl20yp9bcl56oxt/creditcardfraud.zip
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc5ea98b86dc9788c787eb63bed6.dl.dropboxusercontent.com/cd/0/inline/B_4GMrn1V1-5uQOFM7iWuN2ryCMyLBgCQWiBdaNbG5ay2B3HRnFWRLxHaunTgWCjFvZm05M4ytvyACvVS8VbhAcWxFfR4FkPx6VeKiL03cDKgTTzMhIhKYVE3D4ue0YsXoUrrU_aVIPyBFhY0iHk2Wu-lLDbV3AUMT_6VwduvtrGEg/file# [following]
--2023-07-15 11:04:06--  https://uc5ea98b86dc9788c787eb63bed6.dl.dropboxusercontent.com/cd/0/inline/B_4GMrn1V1-5uQOFM7iWuN2ryCMyLBgCQWiBdaNbG5ay2B3HRnFWRLxHaunTgWCjFvZm05M4ytvyACvVS8VbhAcWxFfR4FkPx6VeKiL03cDKgTTzMhIhKYVE3D4ue0YsXoUrrU_aVIPyBFhY0iHk2Wu-lLDbV3AUMT_6VwduvtrGEg/file
Resolving uc5ea98b86dc9788c787eb63bed6.dl.dropboxusercontent.com (uc5ea98b86dc9788c787eb63bed6.dl.dropboxusercontent.com)... 162.125.80.15, 2620:100:6031:15::a27d:510f
Connecting to uc5ea98b86dc9788c787eb63bed6.dl.dropboxusercontent.com (uc5ea98b86dc9788c787eb63bed6.dl.dropboxusercontent.com)|162.125.80.15|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /cd/0/inline2/B_7Z8CjJhloRwtw4bcIKynCeKEHbb0JFFDxo8Qw6bNovX6W0RboJgP8s3w-qgO3C7wnVwZ6CwMJ6bURRVoQtlwfuwG53wnU_jox2bu4xuo9rmvD6VRsyxC3PvitfOUl0ezR4tt-PpnH7wDyvvo80GBCxqw4EisWnbp8D6H19zRG2NhBwkOgAca1BRns08xJ5-eL9YiLG_2up-Ylnzl4HSHNwHeqB6H8cyBk6j0K4J2fByFHRAAwr0OSKn3LZKO4EJXjHY4n56XoalewJlXl4XzCXqQwJaCYhzmQttpw4odi8k0MQN-mciO2jIuHCBu4-B6NBV2bAUJRrAtRLm0GibSrUz3oXyQFSjj36fimc3z8uZkpJcnuCkSX3iiK6nQLCMNan0hlIdEm3ZfvdEg1OOxtk9GKylokcKFXbDp9PvN-bHA/file [following]
--2023-07-15 11:04:07--  https://uc5ea98b86dc9788c787eb63bed6.dl.dropboxusercontent.com/cd/0/inline2/B_7Z8CjJhloRwtw4bcIKynCeKEHbb0JFFDxo8Qw6bNovX6W0RboJgP8s3w-qgO3C7wnVwZ6CwMJ6bURRVoQtlwfuwG53wnU_jox2bu4xuo9rmvD6VRsyxC3PvitfOUl0ezR4tt-PpnH7wDyvvo80GBCxqw4EisWnbp8D6H19zRG2NhBwkOgAca1BRns08xJ5-eL9YiLG_2up-Ylnzl4HSHNwHeqB6H8cyBk6j0K4J2fByFHRAAwr0OSKn3LZKO4EJXjHY4n56XoalewJlXl4XzCXqQwJaCYhzmQttpw4odi8k0MQN-mciO2jIuHCBu4-B6NBV2bAUJRrAtRLm0GibSrUz3oXyQFSjj36fimc3z8uZkpJcnuCkSX3iiK6nQLCMNan0hlIdEm3ZfvdEg1OOxtk9GKylokcKFXbDp9PvN-bHA/file
Reusing existing connection to uc5ea98b86dc9788c787eb63bed6.dl.dropboxusercontent.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 69155672 (66M) [application/zip]
Saving to: ‘creditfraud.zip’

creditfraud.zip     100%[===================>]  65.95M  15.8MB/s    in 4.6s

2023-07-15 11:04:12 (14.3 MB/s) - ‘creditfraud.zip’ saved [69155672/69155672]

In [ ]:
!unzip creditfraud.zip

Archive:  creditfraud.zip
replace creditcard.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import Adam
from sklearn.model_selection import KFold
# Load the Credit Card Fraud Detection dataset
data = pd.read_csv('creditcard.csv')

# Split features and labels
features = data.drop('Class', axis=1)
labels = data['Class']

# Perform data preprocessing, such as scaling
scaler = StandardScaler()
features = scaler.fit_transform(features)



k = 10
kf = KFold(n_splits=k, shuffle=True, random_state=42)



model = Sequential()
model.add(Dense(32, activation='relu', input_shape=(features.shape[1],)))

# model.add(Dense(8, activation='relu'))

model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

accuracy_scores = []

for train_indices, val_indices in kf.split(features):
    train_features, train_labels = features[train_indices], labels[train_indices]
    val_features, val_labels = features[val_indices], labels[val_indices]

    # Train the model on the current fold
    model.fit(train_features, train_labels, epochs=5, batch_size=32, verbose=0)

    # Evaluate the model on the validation set
    _, accuracy = model.evaluate(val_features, val_labels, verbose=0)
    accuracy_scores.append(accuracy)

# Calculate and print the average accuracy across folds
average_accuracy = sum(accuracy_scores) / k
print("Average accuracy:", average_accuracy)

i = 0
float2 = "{0:.2f}"
for score in accuracy_scores:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Average accuracy: 0.9995505690574646
Fold-1: 99.94%
Fold-2: 99.96%
Fold-3: 99.96%
Fold-4: 99.96%
Fold-5: 99.95%
Fold-6: 99.94%
Fold-7: 99.96%
Fold-8: 99.96%
Fold-9: 99.95%
Fold-10: 99.97%

### Caltech101

In [ ]:
# model.fit(X_train_resized, y_train, batch_size=128, epochs=100, validation_data=(X_test_resized, y_test))
import tensorflow as tf
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras import layers
from sklearn.model_selection import KFold
def create_model():
    model = keras.Sequential([
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(28, 28, 3)),  # Update input shape
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(64, activation='relu'),
        keras.layers.Dense(102, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])

    return model

# Define the number of folds for cross-validation
num_folds = 10
kf = KFold(n_splits=num_folds, shuffle=True)

fold_accuracy = []
for train_index, val_index in kf.split(x):
    # Split the data into training and validation sets
    x_train_fold, x_val_fold = x[train_index], x[val_index]
    y_train_fold, y_val_fold = y[train_index], y[val_index]
    with tf.device('/device:GPU:0'):
      model = create_model()
      model.fit(x_train_fold, y_train_fold, epochs=100, batch_size=64, verbose=1)
    # Evaluate the model on the validation data
      _, accuracy = model.evaluate(x_val_fold, y_val_fold, verbose=0)
      fold_accuracy.append(accuracy)


average_accuracy = np.mean(fold_accuracy)
print('Average accuracy:', average_accuracy)
i = 0
float2 = "{0:.2f}"
for score in fold_accuracy:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Epoch 1/100
129/129 [==============================] - 6s 10ms/step - loss: 3.9035 - accuracy: 0.2016
Epoch 2/100
129/129 [==============================] - 1s 7ms/step - loss: 3.1825 - accuracy: 0.3320
Epoch 3/100
129/129 [==============================] - 1s 9ms/step - loss: 2.7421 - accuracy: 0.4069
Epoch 4/100
129/129 [==============================] - 1s 7ms/step - loss: 2.4274 - accuracy: 0.4556
Epoch 5/100
129/129 [==============================] - 1s 7ms/step - loss: 2.2074 - accuracy: 0.4913
Epoch 6/100
129/129 [==============================] - 1s 7ms/step - loss: 2.0278 - accuracy: 0.5273
Epoch 7/100
129/129 [==============================] - 1s 7ms/step - loss: 1.8745 - accuracy: 0.5534
Epoch 8/100
129/129 [==============================] - 1s 8ms/step - loss: 1.7506 - accuracy: 0.5714
Epoch 9/100
129/129 [==============================] - 1s 9ms/step - loss: 1.6196 - accuracy: 0.6023
Epoch 10/100
129/129 [==============================] - 1s 10ms/step - loss: 1.5084 - accuracy: 0.6201
Epoch 11/100
129/129 [==============================] - 1s 9ms/step - loss: 1.4286 - accuracy: 0.6407
Epoch 12/100
129/129 [==============================] - 1s 7ms/step - loss: 1.3298 - accuracy: 0.6620
Epoch 13/100
129/129 [==============================] - 1s 7ms/step - loss: 1.2429 - accuracy: 0.6825
Epoch 14/100
129/129 [==============================] - 1s 7ms/step - loss: 1.1613 - accuracy: 0.7025
Epoch 15/100
129/129 [==============================] - 1s 7ms/step - loss: 1.0805 - accuracy: 0.7199
Epoch 16/100
129/129 [==============================] - 1s 6ms/step - loss: 1.0236 - accuracy: 0.7305
Epoch 17/100
129/129 [==============================] - 1s 6ms/step - loss: 0.9502 - accuracy: 0.7493
Epoch 18/100
129/129 [==============================] - 1s 7ms/step - loss: 0.8805 - accuracy: 0.7685
Epoch 19/100
129/129 [==============================] - 1s 6ms/step - loss: 0.8221 - accuracy: 0.7817
Epoch 20/100
129/129 [==============================] - 1s 6ms/step - loss: 0.7612 - accuracy: 0.7965
Epoch 21/100
129/129 [==============================] - 1s 7ms/step - loss: 0.7152 - accuracy: 0.8075
Epoch 22/100
129/129 [==============================] - 1s 7ms/step - loss: 0.6494 - accuracy: 0.8236
Epoch 23/100
129/129 [==============================] - 1s 9ms/step - loss: 0.5993 - accuracy: 0.8359
Epoch 24/100
129/129 [==============================] - 1s 10ms/step - loss: 0.5487 - accuracy: 0.8532
Epoch 25/100
129/129 [==============================] - 1s 8ms/step - loss: 0.5055 - accuracy: 0.8630
Epoch 26/100
129/129 [==============================] - 1s 7ms/step - loss: 0.4795 - accuracy: 0.8639
Epoch 27/100
129/129 [==============================] - 1s 7ms/step - loss: 0.4298 - accuracy: 0.8832
Epoch 28/100
129/129 [==============================] - 1s 6ms/step - loss: 0.3754 - accuracy: 0.8997
Epoch 29/100
129/129 [==============================] - 1s 7ms/step - loss: 0.3487 - accuracy: 0.9078
Epoch 30/100
129/129 [==============================] - 1s 6ms/step - loss: 0.3033 - accuracy: 0.9205
Epoch 31/100
129/129 [==============================] - 1s 6ms/step - loss: 0.2916 - accuracy: 0.9213
Epoch 32/100
129/129 [==============================] - 1s 6ms/step - loss: 0.2333 - accuracy: 0.9423
Epoch 33/100
129/129 [==============================] - 1s 6ms/step - loss: 0.2346 - accuracy: 0.9380
Epoch 34/100
129/129 [==============================] - 1s 7ms/step - loss: 0.1904 - accuracy: 0.9513
Epoch 35/100
129/129 [==============================] - 1s 7ms/step - loss: 0.1771 - accuracy: 0.9590
Epoch 36/100
129/129 [==============================] - 1s 8ms/step - loss: 0.1535 - accuracy: 0.9637
Epoch 37/100
129/129 [==============================] - 1s 9ms/step - loss: 0.1509 - accuracy: 0.9615
Epoch 38/100
129/129 [==============================] - 1s 9ms/step - loss: 0.1226 - accuracy: 0.9728
Epoch 39/100
129/129 [==============================] - 1s 7ms/step - loss: 0.1009 - accuracy: 0.9786
Epoch 40/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0924 - accuracy: 0.9810
Epoch 41/100
129/129 [==============================] - 1s 6ms/step - loss: 0.1139 - accuracy: 0.9708
Epoch 42/100
129/129 [==============================] - 1s 7ms/step - loss: 0.1267 - accuracy: 0.9661
Epoch 43/100
129/129 [==============================] - 1s 7ms/step - loss: 0.1317 - accuracy: 0.9620
Epoch 44/100
129/129 [==============================] - 1s 7ms/step - loss: 0.0867 - accuracy: 0.9799
Epoch 45/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0821 - accuracy: 0.9804
Epoch 46/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0798 - accuracy: 0.9826
Epoch 47/100
129/129 [==============================] - 1s 7ms/step - loss: 0.0522 - accuracy: 0.9904
Epoch 48/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0453 - accuracy: 0.9911
Epoch 49/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0444 - accuracy: 0.9910
Epoch 50/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0630 - accuracy: 0.9847
Epoch 51/100
129/129 [==============================] - 1s 11ms/step - loss: 0.1824 - accuracy: 0.9420
Epoch 52/100
129/129 [==============================] - 1s 11ms/step - loss: 0.1192 - accuracy: 0.9629
Epoch 53/100
129/129 [==============================] - 1s 8ms/step - loss: 0.0382 - accuracy: 0.9937
Epoch 54/100
129/129 [==============================] - 1s 7ms/step - loss: 0.0166 - accuracy: 0.9989
Epoch 55/100
129/129 [==============================] - 1s 7ms/step - loss: 0.0112 - accuracy: 0.9994
Epoch 56/100
129/129 [==============================] - 1s 7ms/step - loss: 0.0083 - accuracy: 0.9994
Epoch 57/100
129/129 [==============================] - 1s 7ms/step - loss: 0.0092 - accuracy: 0.9993
Epoch 58/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0081 - accuracy: 0.9993
Epoch 59/100
129/129 [==============================] - 1s 7ms/step - loss: 0.0072 - accuracy: 0.9994
Epoch 60/100
129/129 [==============================] - 1s 7ms/step - loss: 0.0082 - accuracy: 0.9994
Epoch 61/100
129/129 [==============================] - 1s 7ms/step - loss: 0.0050 - accuracy: 0.9998
Epoch 62/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0069 - accuracy: 0.9993
Epoch 63/100
129/129 [==============================] - 1s 7ms/step - loss: 0.0086 - accuracy: 0.9994
Epoch 64/100
129/129 [==============================] - 1s 7ms/step - loss: 0.0662 - accuracy: 0.9835
Epoch 65/100
129/129 [==============================] - 1s 10ms/step - loss: 0.4968 - accuracy: 0.8656
Epoch 66/100
129/129 [==============================] - 1s 11ms/step - loss: 0.1810 - accuracy: 0.9439
Epoch 67/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0779 - accuracy: 0.9768
Epoch 68/100
129/129 [==============================] - 1s 7ms/step - loss: 0.0292 - accuracy: 0.9956
Epoch 69/100
129/129 [==============================] - 1s 7ms/step - loss: 0.0194 - accuracy: 0.9971
Epoch 70/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0084 - accuracy: 0.9993
Epoch 71/100
129/129 [==============================] - 1s 7ms/step - loss: 0.0053 - accuracy: 0.9998
Epoch 72/100
129/129 [==============================] - 1s 7ms/step - loss: 0.0069 - accuracy: 0.9993
Epoch 73/100
129/129 [==============================] - 1s 7ms/step - loss: 0.0042 - accuracy: 0.9996
Epoch 74/100
129/129 [==============================] - 1s 8ms/step - loss: 0.0065 - accuracy: 0.9993
Epoch 75/100
129/129 [==============================] - 1s 9ms/step - loss: 0.0043 - accuracy: 0.9995
Epoch 76/100
129/129 [==============================] - 1s 7ms/step - loss: 0.0064 - accuracy: 0.9994
Epoch 77/100
129/129 [==============================] - 1s 8ms/step - loss: 0.0055 - accuracy: 0.9994
Epoch 78/100
129/129 [==============================] - 1s 11ms/step - loss: 0.0060 - accuracy: 0.9993
Epoch 79/100
129/129 [==============================] - 1s 11ms/step - loss: 0.0099 - accuracy: 0.9990
Epoch 80/100
129/129 [==============================] - 1s 7ms/step - loss: 0.2034 - accuracy: 0.9411
Epoch 81/100
129/129 [==============================] - 1s 6ms/step - loss: 0.3196 - accuracy: 0.9006
Epoch 82/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0876 - accuracy: 0.9733
Epoch 83/100
129/129 [==============================] - 1s 7ms/step - loss: 0.0283 - accuracy: 0.9936
Epoch 84/100
129/129 [==============================] - 1s 7ms/step - loss: 0.0098 - accuracy: 0.9991
Epoch 85/100
129/129 [==============================] - 1s 7ms/step - loss: 0.0069 - accuracy: 0.9993
Epoch 86/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0043 - accuracy: 0.9995
Epoch 87/100
129/129 [==============================] - 1s 7ms/step - loss: 0.0035 - accuracy: 0.9998
Epoch 88/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0043 - accuracy: 0.9995
Epoch 89/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0042 - accuracy: 0.9994
Epoch 90/100
129/129 [==============================] - 1s 7ms/step - loss: 0.0046 - accuracy: 0.9995
Epoch 91/100
129/129 [==============================] - 1s 8ms/step - loss: 0.0047 - accuracy: 0.9993
Epoch 92/100
129/129 [==============================] - 1s 11ms/step - loss: 0.0038 - accuracy: 0.9995
Epoch 93/100
129/129 [==============================] - 1s 10ms/step - loss: 0.0029 - accuracy: 0.9996
Epoch 94/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0042 - accuracy: 0.9994
Epoch 95/100
129/129 [==============================] - 1s 7ms/step - loss: 0.0033 - accuracy: 0.9994
Epoch 96/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0041 - accuracy: 0.9993
Epoch 97/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0034 - accuracy: 0.9995
Epoch 98/100
129/129 [==============================] - 1s 7ms/step - loss: 0.0038 - accuracy: 0.9994
Epoch 99/100
129/129 [==============================] - 1s 7ms/step - loss: 0.0039 - accuracy: 0.9994
Epoch 100/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0037 - accuracy: 0.9993
Epoch 1/100
129/129 [==============================] - 3s 5ms/step - loss: 3.9363 - accuracy: 0.1803
Epoch 2/100
129/129 [==============================] - 1s 6ms/step - loss: 3.2477 - accuracy: 0.3177
Epoch 3/100
129/129 [==============================] - 1s 6ms/step - loss: 2.8152 - accuracy: 0.3914
Epoch 4/100
129/129 [==============================] - 1s 6ms/step - loss: 2.5211 - accuracy: 0.4323
Epoch 5/100
129/129 [==============================] - 1s 6ms/step - loss: 2.2811 - accuracy: 0.4779
Epoch 6/100
129/129 [==============================] - 1s 6ms/step - loss: 2.0925 - accuracy: 0.5093
Epoch 7/100
129/129 [==============================] - 1s 6ms/step - loss: 1.9417 - accuracy: 0.5376
Epoch 8/100
129/129 [==============================] - 1s 6ms/step - loss: 1.8113 - accuracy: 0.5684
Epoch 9/100
129/129 [==============================] - 1s 6ms/step - loss: 1.6805 - accuracy: 0.5925
Epoch 10/100
129/129 [==============================] - 1s 9ms/step - loss: 1.5848 - accuracy: 0.6132
Epoch 11/100
129/129 [==============================] - 1s 8ms/step - loss: 1.4689 - accuracy: 0.6404
Epoch 12/100
129/129 [==============================] - 1s 8ms/step - loss: 1.3772 - accuracy: 0.6531
Epoch 13/100
129/129 [==============================] - 1s 6ms/step - loss: 1.3000 - accuracy: 0.6727
Epoch 14/100
129/129 [==============================] - 1s 6ms/step - loss: 1.2058 - accuracy: 0.6926
Epoch 15/100
129/129 [==============================] - 1s 7ms/step - loss: 1.1264 - accuracy: 0.7125
Epoch 16/100
129/129 [==============================] - 1s 6ms/step - loss: 1.0608 - accuracy: 0.7274
Epoch 17/100
129/129 [==============================] - 1s 6ms/step - loss: 0.9895 - accuracy: 0.7378
Epoch 18/100
129/129 [==============================] - 1s 6ms/step - loss: 0.9171 - accuracy: 0.7581
Epoch 19/100
129/129 [==============================] - 1s 6ms/step - loss: 0.8545 - accuracy: 0.7746
Epoch 20/100
129/129 [==============================] - 1s 6ms/step - loss: 0.7893 - accuracy: 0.7930
Epoch 21/100
129/129 [==============================] - 1s 6ms/step - loss: 0.7492 - accuracy: 0.7995
Epoch 22/100
129/129 [==============================] - 1s 6ms/step - loss: 0.6780 - accuracy: 0.8169
Epoch 23/100
129/129 [==============================] - 1s 6ms/step - loss: 0.6318 - accuracy: 0.8306
Epoch 24/100
129/129 [==============================] - 1s 6ms/step - loss: 0.5689 - accuracy: 0.8455
Epoch 25/100
129/129 [==============================] - 1s 6ms/step - loss: 0.5151 - accuracy: 0.8617
Epoch 26/100
129/129 [==============================] - 1s 7ms/step - loss: 0.4816 - accuracy: 0.8683
Epoch 27/100
129/129 [==============================] - 1s 9ms/step - loss: 0.4385 - accuracy: 0.8785
Epoch 28/100
129/129 [==============================] - 1s 7ms/step - loss: 0.3846 - accuracy: 0.8994
Epoch 29/100
129/129 [==============================] - 1s 6ms/step - loss: 0.3492 - accuracy: 0.9081
Epoch 30/100
129/129 [==============================] - 1s 6ms/step - loss: 0.3143 - accuracy: 0.9155
Epoch 31/100
129/129 [==============================] - 1s 6ms/step - loss: 0.2809 - accuracy: 0.9262
Epoch 32/100
129/129 [==============================] - 1s 6ms/step - loss: 0.2452 - accuracy: 0.9380
Epoch 33/100
129/129 [==============================] - 1s 6ms/step - loss: 0.2393 - accuracy: 0.9378
Epoch 34/100
129/129 [==============================] - 1s 6ms/step - loss: 0.2088 - accuracy: 0.9443
Epoch 35/100
129/129 [==============================] - 1s 6ms/step - loss: 0.1895 - accuracy: 0.9533
Epoch 36/100
129/129 [==============================] - 1s 6ms/step - loss: 0.1667 - accuracy: 0.9606
Epoch 37/100
129/129 [==============================] - 1s 6ms/step - loss: 0.1537 - accuracy: 0.9624
Epoch 38/100
129/129 [==============================] - 1s 6ms/step - loss: 0.1371 - accuracy: 0.9661
Epoch 39/100
129/129 [==============================] - 1s 6ms/step - loss: 0.1092 - accuracy: 0.9776
Epoch 40/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0754 - accuracy: 0.9897
Epoch 41/100
129/129 [==============================] - 1s 8ms/step - loss: 0.0754 - accuracy: 0.9869
Epoch 42/100
129/129 [==============================] - 1s 10ms/step - loss: 0.1113 - accuracy: 0.9735
Epoch 43/100
129/129 [==============================] - 1s 8ms/step - loss: 0.1650 - accuracy: 0.9505
Epoch 44/100
129/129 [==============================] - 1s 6ms/step - loss: 0.1460 - accuracy: 0.9587
Epoch 45/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0990 - accuracy: 0.9755
Epoch 46/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0621 - accuracy: 0.9888
Epoch 47/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0488 - accuracy: 0.9911
Epoch 48/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0339 - accuracy: 0.9964
Epoch 49/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0323 - accuracy: 0.9955
Epoch 50/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0276 - accuracy: 0.9967
Epoch 51/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0148 - accuracy: 0.9987
Epoch 52/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0147 - accuracy: 0.9989
Epoch 53/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0131 - accuracy: 0.9993
Epoch 54/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0090 - accuracy: 0.9994
Epoch 55/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0106 - accuracy: 0.9994
Epoch 56/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0109 - accuracy: 0.9994
Epoch 57/100
129/129 [==============================] - 1s 8ms/step - loss: 0.0086 - accuracy: 0.9994
Epoch 58/100
129/129 [==============================] - 1s 8ms/step - loss: 0.3495 - accuracy: 0.9039
Epoch 59/100
129/129 [==============================] - 1s 7ms/step - loss: 0.3750 - accuracy: 0.8843
Epoch 60/100
129/129 [==============================] - 1s 6ms/step - loss: 0.1239 - accuracy: 0.9632
Epoch 61/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0550 - accuracy: 0.9864
Epoch 62/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0288 - accuracy: 0.9945
Epoch 63/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0153 - accuracy: 0.9989
Epoch 64/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0088 - accuracy: 0.9995
Epoch 65/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0083 - accuracy: 0.9994
Epoch 66/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0076 - accuracy: 0.9995
Epoch 67/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0071 - accuracy: 0.9994
Epoch 68/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0055 - accuracy: 0.9996
Epoch 69/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0060 - accuracy: 0.9995
Epoch 70/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0049 - accuracy: 0.9995
Epoch 71/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0079 - accuracy: 0.9989
Epoch 72/100
129/129 [==============================] - 1s 7ms/step - loss: 0.0074 - accuracy: 0.9995
Epoch 73/100
129/129 [==============================] - 1s 8ms/step - loss: 0.0063 - accuracy: 0.9995
Epoch 74/100
129/129 [==============================] - 1s 8ms/step - loss: 0.0698 - accuracy: 0.9796
Epoch 75/100
129/129 [==============================] - 1s 6ms/step - loss: 0.4696 - accuracy: 0.8618
Epoch 76/100
129/129 [==============================] - 1s 6ms/step - loss: 0.1280 - accuracy: 0.9605
Epoch 77/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0580 - accuracy: 0.9843
Epoch 78/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0309 - accuracy: 0.9937
Epoch 79/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0124 - accuracy: 0.9988
Epoch 80/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0060 - accuracy: 0.9996
Epoch 81/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0054 - accuracy: 0.9993
Epoch 82/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0041 - accuracy: 0.9998
Epoch 83/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0060 - accuracy: 0.9994
Epoch 84/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0038 - accuracy: 0.9998
Epoch 85/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0051 - accuracy: 0.9995
Epoch 86/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0065 - accuracy: 0.9993
Epoch 87/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0050 - accuracy: 0.9995
Epoch 88/100
129/129 [==============================] - 1s 8ms/step - loss: 0.0029 - accuracy: 0.9996
Epoch 89/100
129/129 [==============================] - 1s 7ms/step - loss: 0.0038 - accuracy: 0.9996
Epoch 90/100
129/129 [==============================] - 1s 8ms/step - loss: 0.0035 - accuracy: 0.9996
Epoch 91/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0044 - accuracy: 0.9994
Epoch 92/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0044 - accuracy: 0.9995
Epoch 93/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0037 - accuracy: 0.9994
Epoch 94/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0048 - accuracy: 0.9991
Epoch 95/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0050 - accuracy: 0.9993
Epoch 96/100
129/129 [==============================] - 1s 6ms/step - loss: 0.0129 - accuracy: 0.9973
Epoch 97/100

### STL-10

In [ ]:
# model.fit(X_train_resized, y_train, batch_size=128, epochs=100, validation_data=(X_test_resized, y_test))
import tensorflow as tf
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras import layers
from sklearn.model_selection import KFold
def create_model():
    model = keras.Sequential([
        keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(96, 96, 3)),  # Update input shape
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(64, activation='relu'),
        keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])

    return model

# Define the number of folds for cross-validation
num_folds = 10
kf = KFold(n_splits=num_folds, shuffle=True)

fold_accuracy = []
for train_index, val_index in kf.split(x):
    # Split the data into training and validation sets
    x_train_fold, x_val_fold = x[train_index], x[val_index]
    y_train_fold, y_val_fold = y[train_index], y[val_index]
    with tf.device('/device:GPU:0'):
      model = create_model()
      model.fit(x_train_fold, y_train_fold, epochs=100, batch_size=64, verbose=1)
    # Evaluate the model on the validation data
      _, accuracy = model.evaluate(x_val_fold, y_val_fold, verbose=0)
      fold_accuracy.append(accuracy)


average_accuracy = np.mean(fold_accuracy)
print('Average accuracy:', average_accuracy)
i = 0
float2 = "{0:.2f}"
for score in fold_accuracy:
    percent = score * 100
    print("Fold-{}: {}%".format(i+1, float2.format(percent)))
    i = i + 1

Epoch 1/100
183/183 [==============================] - 6s 19ms/step - loss: 14.8323 - accuracy: 0.2829
Epoch 2/100
183/183 [==============================] - 3s 16ms/step - loss: 1.4409 - accuracy: 0.4759
Epoch 3/100
183/183 [==============================] - 4s 20ms/step - loss: 1.0856 - accuracy: 0.6109
Epoch 4/100
183/183 [==============================] - 3s 16ms/step - loss: 0.7680 - accuracy: 0.7286
Epoch 5/100
183/183 [==============================] - 3s 16ms/step - loss: 0.5065 - accuracy: 0.8320
Epoch 6/100
183/183 [==============================] - 3s 15ms/step - loss: 0.3249 - accuracy: 0.8956
Epoch 7/100
183/183 [==============================] - 4s 21ms/step - loss: 0.2109 - accuracy: 0.9341
Epoch 8/100
183/183 [==============================] - 3s 18ms/step - loss: 0.1717 - accuracy: 0.9479
Epoch 9/100
183/183 [==============================] - 3s 15ms/step - loss: 0.1399 - accuracy: 0.9602
Epoch 10/100
183/183 [==============================] - 3s 16ms/step - loss: 0.1263 - accuracy: 0.9621
Epoch 11/100
183/183 [==============================] - 3s 17ms/step - loss: 0.1033 - accuracy: 0.9702
Epoch 12/100
183/183 [==============================] - 3s 18ms/step - loss: 0.0697 - accuracy: 0.9794
Epoch 13/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0493 - accuracy: 0.9868
Epoch 14/100
183/183 [==============================] - 3s 16ms/step - loss: 0.1090 - accuracy: 0.9691
Epoch 15/100
183/183 [==============================] - 3s 17ms/step - loss: 0.1306 - accuracy: 0.9599
Epoch 16/100
183/183 [==============================] - 3s 18ms/step - loss: 0.0854 - accuracy: 0.9753
Epoch 17/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0386 - accuracy: 0.9907
Epoch 18/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0521 - accuracy: 0.9859
Epoch 19/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0480 - accuracy: 0.9851
Epoch 20/100
183/183 [==============================] - 4s 20ms/step - loss: 0.0512 - accuracy: 0.9842
Epoch 21/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0553 - accuracy: 0.9844
Epoch 22/100
183/183 [==============================] - 3s 16ms/step - loss: 0.1013 - accuracy: 0.9712
Epoch 23/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0903 - accuracy: 0.9742
Epoch 24/100
183/183 [==============================] - 4s 20ms/step - loss: 0.0588 - accuracy: 0.9836
Epoch 25/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0355 - accuracy: 0.9897
Epoch 26/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0838 - accuracy: 0.9761
Epoch 27/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0883 - accuracy: 0.9775
Epoch 28/100
183/183 [==============================] - 4s 20ms/step - loss: 0.0788 - accuracy: 0.9769
Epoch 29/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0582 - accuracy: 0.9830
Epoch 30/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0527 - accuracy: 0.9872
Epoch 31/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0481 - accuracy: 0.9867
Epoch 32/100
183/183 [==============================] - 4s 20ms/step - loss: 0.0237 - accuracy: 0.9926
Epoch 33/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0254 - accuracy: 0.9929
Epoch 34/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0283 - accuracy: 0.9918
Epoch 35/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0455 - accuracy: 0.9874
Epoch 36/100
183/183 [==============================] - 3s 18ms/step - loss: 0.1658 - accuracy: 0.9613
Epoch 37/100
183/183 [==============================] - 3s 16ms/step - loss: 0.1352 - accuracy: 0.9652
Epoch 38/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0607 - accuracy: 0.9834
Epoch 39/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0309 - accuracy: 0.9915
Epoch 40/100
183/183 [==============================] - 3s 18ms/step - loss: 0.0168 - accuracy: 0.9954
Epoch 41/100
183/183 [==============================] - 3s 17ms/step - loss: 0.0134 - accuracy: 0.9956
Epoch 42/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0215 - accuracy: 0.9948
Epoch 43/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0778 - accuracy: 0.9807
Epoch 44/100
183/183 [==============================] - 3s 16ms/step - loss: 0.1179 - accuracy: 0.9733
Epoch 45/100
183/183 [==============================] - 3s 19ms/step - loss: 0.0576 - accuracy: 0.9835
Epoch 46/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0603 - accuracy: 0.9856
Epoch 47/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0740 - accuracy: 0.9849
Epoch 48/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0673 - accuracy: 0.9832
Epoch 49/100
183/183 [==============================] - 3s 19ms/step - loss: 0.0423 - accuracy: 0.9891
Epoch 50/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0666 - accuracy: 0.9841
Epoch 51/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0560 - accuracy: 0.9871
Epoch 52/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0572 - accuracy: 0.9851
Epoch 53/100
183/183 [==============================] - 4s 20ms/step - loss: 0.0498 - accuracy: 0.9866
Epoch 54/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0675 - accuracy: 0.9828
Epoch 55/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0428 - accuracy: 0.9904
Epoch 56/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0567 - accuracy: 0.9879
Epoch 57/100
183/183 [==============================] - 4s 19ms/step - loss: 0.0326 - accuracy: 0.9918
Epoch 58/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0154 - accuracy: 0.9956
Epoch 59/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0270 - accuracy: 0.9932
Epoch 60/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0079 - accuracy: 0.9975
Epoch 61/100
183/183 [==============================] - 3s 18ms/step - loss: 0.0266 - accuracy: 0.9943
Epoch 62/100
183/183 [==============================] - 3s 17ms/step - loss: 0.0744 - accuracy: 0.9841
Epoch 63/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0807 - accuracy: 0.9836
Epoch 64/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0869 - accuracy: 0.9819
Epoch 65/100
183/183 [==============================] - 3s 17ms/step - loss: 0.0958 - accuracy: 0.9815
Epoch 66/100
183/183 [==============================] - 3s 18ms/step - loss: 0.0641 - accuracy: 0.9883
Epoch 67/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0371 - accuracy: 0.9919
Epoch 68/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0268 - accuracy: 0.9938
Epoch 69/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0431 - accuracy: 0.9912
Epoch 70/100
183/183 [==============================] - 4s 20ms/step - loss: 0.0259 - accuracy: 0.9938
Epoch 71/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0180 - accuracy: 0.9956
Epoch 72/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0360 - accuracy: 0.9904
Epoch 73/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0535 - accuracy: 0.9881
Epoch 74/100
183/183 [==============================] - 4s 19ms/step - loss: 0.0310 - accuracy: 0.9932
Epoch 75/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0823 - accuracy: 0.9850
Epoch 76/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0620 - accuracy: 0.9866
Epoch 77/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0134 - accuracy: 0.9958
Epoch 78/100
183/183 [==============================] - 3s 19ms/step - loss: 0.0166 - accuracy: 0.9962
Epoch 79/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0218 - accuracy: 0.9957
Epoch 80/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0487 - accuracy: 0.9905
Epoch 81/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0353 - accuracy: 0.9918
Epoch 82/100
183/183 [==============================] - 3s 19ms/step - loss: 0.0866 - accuracy: 0.9856
Epoch 83/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0684 - accuracy: 0.9862
Epoch 84/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0821 - accuracy: 0.9862
Epoch 85/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0616 - accuracy: 0.9896
Epoch 86/100
183/183 [==============================] - 3s 17ms/step - loss: 0.0282 - accuracy: 0.9941
Epoch 87/100
183/183 [==============================] - 3s 18ms/step - loss: 0.0399 - accuracy: 0.9931
Epoch 88/100
183/183 [==============================] - 4s 19ms/step - loss: 0.0136 - accuracy: 0.9975
Epoch 89/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0073 - accuracy: 0.9988
Epoch 90/100
183/183 [==============================] - 3s 18ms/step - loss: 0.0121 - accuracy: 0.9973
Epoch 91/100
183/183 [==============================] - 3s 17ms/step - loss: 0.0166 - accuracy: 0.9962
Epoch 92/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0508 - accuracy: 0.9904
Epoch 93/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0781 - accuracy: 0.9882
Epoch 94/100
183/183 [==============================] - 3s 17ms/step - loss: 0.0574 - accuracy: 0.9915
Epoch 95/100
183/183 [==============================] - 3s 19ms/step - loss: 0.0524 - accuracy: 0.9899
Epoch 96/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0544 - accuracy: 0.9906
Epoch 97/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0343 - accuracy: 0.9932
Epoch 98/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0349 - accuracy: 0.9939
Epoch 99/100
183/183 [==============================] - 4s 20ms/step - loss: 0.0156 - accuracy: 0.9967
Epoch 100/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0233 - accuracy: 0.9960
Epoch 1/100
183/183 [==============================] - 6s 19ms/step - loss: 11.2897 - accuracy: 0.2617
Epoch 2/100
183/183 [==============================] - 3s 16ms/step - loss: 1.5176 - accuracy: 0.4338
Epoch 3/100
183/183 [==============================] - 3s 16ms/step - loss: 1.2480 - accuracy: 0.5385
Epoch 4/100
183/183 [==============================] - 3s 16ms/step - loss: 0.9247 - accuracy: 0.6686
Epoch 5/100
183/183 [==============================] - 3s 19ms/step - loss: 0.6614 - accuracy: 0.7658
Epoch 6/100
183/183 [==============================] - 3s 16ms/step - loss: 0.4686 - accuracy: 0.8379
Epoch 7/100
183/183 [==============================] - 3s 16ms/step - loss: 0.3686 - accuracy: 0.8776
Epoch 8/100
183/183 [==============================] - 3s 16ms/step - loss: 0.2593 - accuracy: 0.9154
Epoch 9/100
183/183 [==============================] - 4s 19ms/step - loss: 0.1905 - accuracy: 0.9405
Epoch 10/100
183/183 [==============================] - 3s 16ms/step - loss: 0.1474 - accuracy: 0.9546
Epoch 11/100
183/183 [==============================] - 3s 15ms/step - loss: 0.1196 - accuracy: 0.9649
Epoch 12/100
183/183 [==============================] - 3s 16ms/step - loss: 0.1217 - accuracy: 0.9667
Epoch 13/100
183/183 [==============================] - 4s 19ms/step - loss: 0.1223 - accuracy: 0.9636
Epoch 14/100
183/183 [==============================] - 3s 16ms/step - loss: 0.1085 - accuracy: 0.9682
Epoch 15/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0606 - accuracy: 0.9825
Epoch 16/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0663 - accuracy: 0.9800
Epoch 17/100
183/183 [==============================] - 4s 19ms/step - loss: 0.0917 - accuracy: 0.9711
Epoch 18/100
183/183 [==============================] - 3s 16ms/step - loss: 0.1132 - accuracy: 0.9654
Epoch 19/100
183/183 [==============================] - 3s 16ms/step - loss: 0.1813 - accuracy: 0.9485
Epoch 20/100
183/183 [==============================] - 3s 16ms/step - loss: 0.1329 - accuracy: 0.9625
Epoch 21/100
183/183 [==============================] - 4s 20ms/step - loss: 0.0791 - accuracy: 0.9765
Epoch 22/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0527 - accuracy: 0.9844
Epoch 23/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0674 - accuracy: 0.9820
Epoch 24/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0727 - accuracy: 0.9774
Epoch 25/100
183/183 [==============================] - 3s 19ms/step - loss: 0.0404 - accuracy: 0.9879
Epoch 26/100
183/183 [==============================] - 3s 17ms/step - loss: 0.0757 - accuracy: 0.9785
Epoch 27/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0923 - accuracy: 0.9759
Epoch 28/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0817 - accuracy: 0.9776
Epoch 29/100
183/183 [==============================] - 3s 19ms/step - loss: 0.0903 - accuracy: 0.9740
Epoch 30/100
183/183 [==============================] - 3s 18ms/step - loss: 0.0671 - accuracy: 0.9808
Epoch 31/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0629 - accuracy: 0.9827
Epoch 32/100
183/183 [==============================] - 3s 16ms/step - loss: 0.1725 - accuracy: 0.9576
Epoch 33/100
183/183 [==============================] - 3s 17ms/step - loss: 0.0589 - accuracy: 0.9838
Epoch 34/100
183/183 [==============================] - 3s 18ms/step - loss: 0.0446 - accuracy: 0.9877
Epoch 35/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0398 - accuracy: 0.9894
Epoch 36/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0256 - accuracy: 0.9927
Epoch 37/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0498 - accuracy: 0.9878
Epoch 38/100
183/183 [==============================] - 4s 19ms/step - loss: 0.0654 - accuracy: 0.9838
Epoch 39/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0456 - accuracy: 0.9869
Epoch 40/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0816 - accuracy: 0.9789
Epoch 41/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0514 - accuracy: 0.9851
Epoch 42/100
183/183 [==============================] - 4s 20ms/step - loss: 0.0632 - accuracy: 0.9835
Epoch 43/100
183/183 [==============================] - 3s 16ms/step - loss: 0.1159 - accuracy: 0.9719
Epoch 44/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0681 - accuracy: 0.9829
Epoch 45/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0362 - accuracy: 0.9893
Epoch 46/100
183/183 [==============================] - 4s 20ms/step - loss: 0.0243 - accuracy: 0.9926
Epoch 47/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0361 - accuracy: 0.9909
Epoch 48/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0823 - accuracy: 0.9798
Epoch 49/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0358 - accuracy: 0.9907
Epoch 50/100
183/183 [==============================] - 4s 20ms/step - loss: 0.0889 - accuracy: 0.9793
Epoch 51/100
183/183 [==============================] - 3s 16ms/step - loss: 0.1180 - accuracy: 0.9740
Epoch 52/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0805 - accuracy: 0.9809
Epoch 53/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0306 - accuracy: 0.9936
Epoch 54/100
183/183 [==============================] - 3s 19ms/step - loss: 0.0274 - accuracy: 0.9934
Epoch 55/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0209 - accuracy: 0.9932
Epoch 56/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0046 - accuracy: 0.9985
Epoch 57/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0085 - accuracy: 0.9973
Epoch 58/100
183/183 [==============================] - 3s 18ms/step - loss: 0.0113 - accuracy: 0.9960
Epoch 59/100
183/183 [==============================] - 3s 17ms/step - loss: 0.0581 - accuracy: 0.9879
Epoch 60/100
183/183 [==============================] - 3s 16ms/step - loss: 0.1164 - accuracy: 0.9764
Epoch 61/100
183/183 [==============================] - 3s 17ms/step - loss: 0.0985 - accuracy: 0.9787
Epoch 62/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0853 - accuracy: 0.9810
Epoch 63/100
183/183 [==============================] - 3s 16ms/step - loss: 0.0557 - accuracy: 0.9881
Epoch 64/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0479 - accuracy: 0.9881
Epoch 65/100
183/183 [==============================] - 3s 14ms/step - loss: 0.0761 - accuracy: 0.9837
Epoch 66/100
183/183 [==============================] - 3s 14ms/step - loss: 0.0339 - accuracy: 0.9926
Epoch 67/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0283 - accuracy: 0.9938
Epoch 68/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0339 - accuracy: 0.9923
Epoch 69/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0699 - accuracy: 0.9861
Epoch 70/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0568 - accuracy: 0.9891
Epoch 71/100
183/183 [==============================] - 3s 14ms/step - loss: 0.0416 - accuracy: 0.9898
Epoch 72/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0190 - accuracy: 0.9948
Epoch 73/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0183 - accuracy: 0.9959
Epoch 74/100
183/183 [==============================] - 3s 14ms/step - loss: 0.0342 - accuracy: 0.9944
Epoch 75/100
183/183 [==============================] - 3s 14ms/step - loss: 0.0339 - accuracy: 0.9935
Epoch 76/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0276 - accuracy: 0.9936
Epoch 77/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0648 - accuracy: 0.9875
Epoch 78/100
183/183 [==============================] - 3s 14ms/step - loss: 0.0541 - accuracy: 0.9880
Epoch 79/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0847 - accuracy: 0.9838
Epoch 80/100
183/183 [==============================] - 3s 14ms/step - loss: 0.0426 - accuracy: 0.9907
Epoch 81/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0490 - accuracy: 0.9900
Epoch 82/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0473 - accuracy: 0.9897
Epoch 83/100
183/183 [==============================] - 3s 14ms/step - loss: 0.0349 - accuracy: 0.9926
Epoch 84/100
183/183 [==============================] - 3s 14ms/step - loss: 0.0336 - accuracy: 0.9932
Epoch 85/100
183/183 [==============================] - 3s 14ms/step - loss: 0.0242 - accuracy: 0.9950
Epoch 86/100
183/183 [==============================] - 3s 15ms/step - loss: 0.1155 - accuracy: 0.9797
Epoch 87/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0940 - accuracy: 0.9847
Epoch 88/100
183/183 [==============================] - 3s 14ms/step - loss: 0.0563 - accuracy: 0.9879
Epoch 89/100
183/183 [==============================] - 3s 14ms/step - loss: 0.0412 - accuracy: 0.9916
Epoch 90/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0259 - accuracy: 0.9936
Epoch 91/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0199 - accuracy: 0.9956
Epoch 92/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0766 - accuracy: 0.9881
Epoch 93/100
183/183 [==============================] - 3s 14ms/step - loss: 0.0360 - accuracy: 0.9933
Epoch 94/100
183/183 [==============================] - 3s 15ms/step - loss: 0.0359 - accuracy: 0.9921
Epoch 95/100

### voc2012

In [ ]:
import tensorflow as tf
import tensorflow_datasets as tfds
import numpy as np
from sklearn.model_selection import KFold

# Check if GPU is available
if tf.config.list_physical_devices('GPU'):
    print("GPU is available.")
else:
    print("GPU is not available. Training on CPU.")

# Load VOC 2012 dataset from TFDS
def load_voc_dataset():
    dataset, info = tfds.load('voc/2012', split='train', with_info=True)
    test_data = tfds.load('voc/2012', split='test')
    val_data = tfds.load('voc/2012', split='validation')

    return dataset, test_data, val_data, info


# Define the model architecture
def create_model():
    model = tf.keras.models.Sequential([
        tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(None, None, 3)),
        tf.keras.layers.MaxPooling2D((2, 2)),
        tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
        tf.keras.layers.MaxPooling2D((2, 2)),
        tf.keras.layers.Conv2D(128, (3, 3), activation='relu'),
        tf.keras.layers.MaxPooling2D((2, 2)),
        tf.keras.layers.GlobalAveragePooling2D(),
        tf.keras.layers.Dense(512, activation='relu'),
        tf.keras.layers.Dense(20, activation='softmax')  # 20 classes in VOC 2012 dataset
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model

# Prepare the dataset for training
def preprocess_image(example):
    image = example['image']
    objects = example['objects']

    # Extract the label from the 'objects' key
    # In this case, we'll consider the first object's label as the image's label
    label = objects['label'][0]

    image = tf.image.resize(image, (224, 224))
    image = tf.cast(image, tf.float32) / 255.0

    return image, label


train_data, test_data, val_data, dataset_info = load_voc_dataset()
train_data = train_data.map(preprocess_image).prefetch(tf.data.AUTOTUNE)
test_data = test_data.map(preprocess_image).prefetch(tf.data.AUTOTUNE)
val_data = val_data.map(preprocess_image).prefetch(tf.data.AUTOTUNE)

# Combine train, test, and validation datasets
combined_data = train_data.concatenate(test_data).concatenate(val_data)

# Convert labels to a list for KFold split
labels = [label.numpy() for _, label in combined_data]

# Check for GPU support and set up the strategy
strategy = None
if tf.config.list_physical_devices('GPU'):
    strategy = tf.distribute.MirroredStrategy()
    print(f"Running on {strategy.num_replicas_in_sync} GPUs.")

# K-Fold Cross Validation
k = 10
num_samples = dataset_info.splits['train'].num_examples + dataset_info.splits['test'].num_examples + dataset_info.splits['validation'].num_examples
indices = np.arange(num_samples)

kfold = KFold(n_splits=k, shuffle=True, random_state=42)
fold_index = 0

for train_index, val_index in kfold.split(indices, labels):
    fold_index += 1
    print(f"Fold {fold_index}:")

    # Create TensorFlow datasets for training and validation
    train_dataset = combined_data.skip(val_index[-1] + 1).take(train_index[-1] + 1)
    val_dataset = combined_data.skip(train_index[-1] + 1).take(val_index[-1] - train_index[-1])

    # Create and train the model within the strategy's scope
    with strategy.scope():
        model = create_model()

    model.fit(train_dataset, validation_data=val_dataset, epochs=5)

GPU is available.

InvalidArgumentError: ignored

In [ ]:
# Define the model architecture
def create_model():
    model = tf.keras.models.Sequential([
        tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(None, None, 3)),
        tf.keras.layers.MaxPooling2D((2, 2)),
        tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
        tf.keras.layers.MaxPooling2D((2, 2)),
        tf.keras.layers.Conv2D(128, (3, 3), activation='relu'),
        tf.keras.layers.MaxPooling2D((2, 2)),
        tf.keras.layers.GlobalAveragePooling2D(),
        tf.keras.layers.Dense(512, activation='relu'),
        tf.keras.layers.Dense(20, activation='softmax')  # 20 classes in VOC 2012 dataset
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model

# Prepare the dataset for training
def preprocess_image(example):
    image = example['image']
    label = example['label']

    image = tf.image.resize(image, (224, 224))
    image = tf.cast(image, tf.float32) / 255.0

    return image, label


train_data, test_data, val_data, dataset_info = load_voc_dataset()
train_data = train_data.map(preprocess_image).prefetch(tf.data.AUTOTUNE)
test_data = test_data.map(preprocess_image).prefetch(tf.data.AUTOTUNE)
val_data = val_data.map(preprocess_image).prefetch(tf.data.AUTOTUNE)

# Combine train, test, and validation datasets
combined_data = train_data.concatenate(test_data).concatenate(val_data)

# Convert the combined dataset to numpy arrays
x_combined = np.array([image.numpy() for image, _ in combined_data])
y_combined = np.array([label.numpy() for _, label in combined_data])

# Check for GPU support and set up the strategy
strategy = None
if tf.config.list_physical_devices('GPU'):
    strategy = tf.distribute.MirroredStrategy()
    print(f"Running on {strategy.num_replicas_in_sync} GPUs.")

# K-Fold Cross Validation
k = 10
num_samples = dataset_info.splits['train'].num_examples + dataset_info.splits['test'].num_examples + dataset_info.splits['validation'].num_examples
indices = np.arange(num_samples)

kfold = KFold(n_splits=k, shuffle=True, random_state=42)
fold_index = 0

for train_index, val_index in kfold.split(indices):
    fold_index += 1
    print(f"Fold {fold_index}:")

    # Create numpy arrays for training and validation sets
    x_train_fold, y_train_fold = x_combined[train_index], y_combined[train_index]
    x_val_fold, y_val_fold = x_combined[val_index], y_combined[val_index]

    # Create and train the model within the strategy's scope
    with strategy.scope():
        model = create_model()

    model.fit(x_train_fold, y_train_fold, validation_data=(x_val_fold, y_val_fold), epochs=5)

KeyError: ignored

# OpenML Datasets from KEEL

In [ ]:
pip install openml

Collecting openml
  Downloading openml-0.14.1.tar.gz (131 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.3/131.3 kB 1.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting liac-arff>=2.4.0 (from openml)
  Downloading liac-arff-2.5.0.tar.gz (13 kB)
  Preparing metadata (setup.py) ... done
Collecting xmltodict (from openml)
  Downloading xmltodict-0.13.0-py2.py3-none-any.whl (10.0 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from openml) (2.31.0)
Requirement already satisfied: scikit-learn>=0.18 in /usr/local/lib/python3.10/dist-packages (from openml) (1.2.2)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/dist-packages (from openml) (2.8.2)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from openml) (1.5.3)
Requirement already satisfied: scipy>=0.13.3 in /usr/local/lib/python3.10/dist-packages (from openml) (1.10.1)
Requirement already satisfied: numpy>=1.6.2 in /usr/local/lib/python3.10/dist-packages (from openml) (1.23.5)
Collecting minio (from openml)
  Downloading minio-7.1.15-py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.4/77.4 kB 6.8 MB/s eta 0:00:00
Requirement already satisfied: pyarrow in /usr/local/lib/python3.10/dist-packages (from openml) (9.0.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.0->openml) (2022.7.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil->openml) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.18->openml) (1.3.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.18->openml) (3.2.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from minio->openml) (2023.7.22)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.10/dist-packages (from minio->openml) (1.26.16)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->openml) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->openml) (3.4)
Building wheels for collected packages: openml, liac-arff
  Building wheel for openml (setup.py) ... done
  Created wheel for openml: filename=openml-0.14.1-py3-none-any.whl size=146927 sha256=23993111282f79cf4ae7832076358e3daf7021ad3eed34418030a1889f1913fb
  Stored in directory: /root/.cache/pip/wheels/75/bc/fd/739778254a2881ef96b139d0aaf60c6d4f9130bb1459b48f10
  Building wheel for liac-arff (setup.py) ... done
  Created wheel for liac-arff: filename=liac_arff-2.5.0-py3-none-any.whl size=11716 sha256=a26ee199f7c8f50df284aa18047a23804e764a1cd35a2080301f0e56be4eb3c8
  Stored in directory: /root/.cache/pip/wheels/5d/2a/9c/3895d9617f8f49a0883ba686326d598e78a1c2f54fe3cae86d
Successfully built openml liac-arff
Installing collected packages: xmltodict, minio, liac-arff, openml
Successfully installed liac-arff-2.5.0 minio-7.1.15 openml-0.14.1 xmltodict-0.13.0

# Holdout Cross-Val

## Folds (2)

### Appendicitis

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 1462  # ID of the "appendicitis" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 2
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.9766763848396501
Fold 2: Accuracy = 0.9766763848396501
Mean accuracy: 0.9766763848396501
Standard deviation: 0.0

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Australian

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 40981  # ID of the "australian" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 2
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.8144927536231884
Fold 2: Accuracy = 0.8318840579710145
Mean accuracy: 0.8231884057971015
Standard deviation: 0.008695652173913049

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Banana

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 1460  # ID of the "banana" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 2
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.709811320754717
Fold 2: Accuracy = 0.7588679245283019
Mean accuracy: 0.7343396226415094
Standard deviation: 0.024528301886792447

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Bands

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
import openml

# Load the dataset by ID
dataset_id = 6332  # ID of the "Bands" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# print(X.head(5))

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 2
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.6888888888888889
Fold 2: Accuracy = 0.7111111111111111
Mean accuracy: 0.7
Standard deviation: 0.011111111111111127

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Breast

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
import openml

# Load the dataset by ID
dataset_id = 844  # ID of the "breastTumor" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# print(X.head(5))

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 2
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(

Fold 1: Accuracy = 0.5944055944055944
Fold 2: Accuracy = 0.5734265734265734
Mean accuracy: 0.583916083916084
Standard deviation: 0.010489510489510467

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Bupa

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Buppa.csv to Buppa.csv

In [ ]:
import pandas as pd
df = pd.read_csv("Buppa.csv")

In [ ]:
df.head()

   mcv  alkphos  sgpt  sgot  gammagt  drinks  selector
0   85       92    45    27       31     0.0         1
1   85       64    59    32       23     0.0         2
2   86       54    33    16       54     0.0         2
3   91       78    34    24       36     0.0         2
4   87       70    12    28       10     0.0         2

In [ ]:
# Split the DataFrame into X and y variables
X = df.drop('selector', axis=1)  # Drop the 'selector' column to get features (X)
y = df['selector']  # Get the 'selector' column as the target variable (y)
print(X.head())
print(y.head())

   mcv  alkphos  sgpt  sgot  gammagt  drinks
0   85       92    45    27       31     0.0
1   85       64    59    32       23     0.0
2   86       54    33    16       54     0.0
3   91       78    34    24       36     0.0
4   87       70    12    28       10     0.0
0    1
1    2
2    2
3    2
4    2
Name: selector, dtype: int64

In [ ]:
from tensorflow import keras
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras


# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 2
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

Fold 1: Accuracy = 0.6428571428571429
Fold 2: Accuracy = 0.5185185185185185
Mean accuracy: 0.5806878306878307
Standard deviation: 0.06216931216931221

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Chess

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 3 # ID of the "chess" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 2
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.9336670838548186
Fold 2: Accuracy = 0.9399249061326659
Mean accuracy: 0.9367959949937422
Standard deviation: 0.0031289111389236623

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Crx

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 29 # ID of the "credit card approval" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 2
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.7536231884057971
Fold 2: Accuracy = 0.7304347826086957
Mean accuracy: 0.7420289855072464
Standard deviation: 0.011594202898550732

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### GermanCredit

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving GermanCredit.csv to GermanCredit.csv

In [ ]:
import pandas as pd
df = pd.read_csv("GermanCredit.csv")

In [ ]:
df.head(2)

,status,duration,credit_history,purpose,amount,savings,employment_duration,installment_rate,personal_status_sex,other_debtors,...,property,age,other_installment_plans,housing,number_credits,job,people_liable,telephone,foreign_worker,credit_risk
0,... < 100 DM,6,critical account/other credits existing,domestic appliances,1169,unknown/no savings account,... >= 7 years,4,male : single,none,...,real estate,67,none,own,2,skilled employee/official,1,yes,yes,1
1,0 <= ... < 200 DM,48,existing credits paid back duly till now,domestic appliances,5951,... < 100 DM,1 <= ... < 4 years,2,female : divorced/separated/married,none,...,real estate,22,none,own,1,skilled employee/official,1,no,yes,0

In [ ]:
# Split the DataFrame into X and y variables
X = df.drop('credit_risk', axis=1)  # Drop the 'selector' column to get features (X)
y = df['credit_risk']  # Get the 'selector' column as the target variable (y)
print(X.head())
print(y.head())

                status  duration                            credit_history  \
0         ... < 100 DM         6   critical account/other credits existing
1    0 <= ... < 200 DM        48  existing credits paid back duly till now
2  no checking account        12   critical account/other credits existing
3         ... < 100 DM        42  existing credits paid back duly till now
4         ... < 100 DM        24           delay in paying off in the past

               purpose  amount                     savings  \
0  domestic appliances    1169  unknown/no savings account
1  domestic appliances    5951                ... < 100 DM
2           retraining    2096                ... < 100 DM
3     radio/television    7882                ... < 100 DM
4            car (new)    4870                ... < 100 DM

  employment_duration  installment_rate                  personal_status_sex  \
0      ... >= 7 years                 4                        male : single
1  1 <= ... < 4 years                 2  female : divorced/separated/married
2  4 <= ... < 7 years                 2                        male : single
3  4 <= ... < 7 years                 2                        male : single
4  1 <= ... < 4 years                 3                        male : single

  other_debtors  present_residence  \
0          none                  4
1          none                  2
2          none                  3
3     guarantor                  4
4          none                  4

                                            property  age  \
0                                        real estate   67
1                                        real estate   22
2                                        real estate   49
3  building society savings agreement/life insurance   45
4                                unknown/no property   53

  other_installment_plans   housing  number_credits  \
0                    none       own               2
1                    none       own               1
2                    none       own               1
3                    none  for free               1
4                    none  for free               2

                         job  people_liable telephone foreign_worker
0  skilled employee/official              1       yes            yes
1  skilled employee/official              1        no            yes
2       unskilled - resident              2        no            yes
3  skilled employee/official              2        no            yes
4  skilled employee/official              2        no            yes
0    1
1    0
2    1
3    1
4    0
Name: credit_risk, dtype: int64

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml

# Load the dataset by ID
# dataset_id = 844  # ID of the "GermanCredit" dataset on OpenML
# dataset = openml.datasets.get_dataset(dataset_id)

# # Access the data and target variables
# X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# print(X.head(5))

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 2
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.698
Fold 2: Accuracy = 0.686
Mean accuracy: 0.692
Standard deviation: 0.00599999999999995

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Haberman

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 43  # ID of the "Haberman" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 2
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(

Fold 1: Accuracy = 0.738562091503268
Fold 2: Accuracy = 0.7058823529411765
Mean accuracy: 0.7222222222222223
Standard deviation: 0.01633986928104575

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Statlog (Heart)

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 53  # ID of the "Heart" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 2
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(

Fold 1: Accuracy = 0.5925925925925926
Fold 2: Accuracy = 0.5185185185185185
Mean accuracy: 0.5555555555555556
Standard deviation: 0.037037037037037035

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Hepatitis

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 55  # ID of the "Hepatitis" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 2
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.7307692307692307
Fold 2: Accuracy = 0.7012987012987013
Mean accuracy: 0.7160339660339661
Standard deviation: 0.014735264735264708

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Housevote

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 56  # ID of the "Hepatitis" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 2
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.8853211009174312
Fold 2: Accuracy = 0.8617511520737328
Mean accuracy: 0.873536126495582
Standard deviation: 0.011784974421849226

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Ionosphere

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 59 # ID of the "Hepatitis" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 2
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(

Fold 1: Accuracy = 0.6136363636363636
Fold 2: Accuracy = 0.7085714285714285
Mean accuracy: 0.6611038961038961
Standard deviation: 0.047467532467532436

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Mammographic

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 45557# ID of the "Mammographic" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 2
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
WARNING:openml.datasets.functions:Could not download file from http://openml1.win.tue.nl/dataset45557/dataset_45557.pq: Bucket does not exist or is private.
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.7671517671517671
Fold 2: Accuracy = 0.75
Mean accuracy: 0.7585758835758836
Standard deviation: 0.00857588357588357

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Monk-2

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 333 # ID of the "Monk-2" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 2
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.6546762589928058
Fold 2: Accuracy = 0.7086330935251799
Mean accuracy: 0.6816546762589928
Standard deviation: 0.02697841726618705

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Mushroom

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 24 # ID of the "Mushroom" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 2
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 1.0
Fold 2: Accuracy = 0.9679960610536681
Mean accuracy: 0.9839980305268341
Standard deviation: 0.016001969473165956

### Phoneme

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml
import openml

# Load the dataset by ID
dataset_id = 1489 # ID of the "Phoneme" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 2
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.807179866765359
Fold 2: Accuracy = 0.7886750555144337
Mean accuracy: 0.7979274611398963
Standard deviation: 0.009252405625462645

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Pima Indians Diabetes

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml
import openml

# Load the dataset by ID
dataset_id = 37 # ID of the "Phoneme" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Encoder_X = LabelEncoder()
# for col in X.columns:
#     X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 2
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.7135416666666666
Fold 2: Accuracy = 0.6953125
Mean accuracy: 0.7044270833333333
Standard deviation: 0.009114583333333315

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Saheart

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml
import openml

# Load the dataset by ID
dataset_id = 1498 # ID of the "Saheart" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 2
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.7575757575757576
Fold 2: Accuracy = 0.658008658008658
Mean accuracy: 0.7077922077922079
Standard deviation: 0.04978354978354976

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Sonar

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml
import openml

# Load the dataset by ID
dataset_id = 40 # ID of the "Sonar" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Encoder_X = LabelEncoder()
# for col in X.columns:
#     X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 2
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(

Fold 1: Accuracy = 0.8076923076923077
Fold 2: Accuracy = 0.75
Mean accuracy: 0.7788461538461539
Standard deviation: 0.028846153846153855

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Spambase

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml
import openml

# Load the dataset by ID
dataset_id = 44 # ID of the "Spambase" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Encoder_X = LabelEncoder()
# for col in X.columns:
#     X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 2
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.9230769230769231
Fold 2: Accuracy = 0.9330434782608695
Mean accuracy: 0.9280602006688963
Standard deviation: 0.004983277591973201

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### SPECTFHeart

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml
import openml

# Load the dataset by ID
dataset_id = 1600 # ID of the "SPECTF Heart" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Encoder_X = LabelEncoder()
# for col in X.columns:
#     X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 2
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(

Fold 1: Accuracy = 0.6865671641791045
Fold 2: Accuracy = 0.6541353383458647
Mean accuracy: 0.6703512512624845
Standard deviation: 0.01621591291661989

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Tic-Tac-Toe

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml
import openml

# Load the dataset by ID
dataset_id = 50 # ID of the "Tic-Tac-Toe" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 2
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.5908141962421712
Fold 2: Accuracy = 0.6409185803757829
Mean accuracy: 0.615866388308977
Standard deviation: 0.025052192066805812

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Titanic

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml
import openml

# Load the dataset by ID
dataset_id = 40704 # ID of the "Tic-Tac-Toe" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Encoder_X = LabelEncoder()
# for col in X.columns:
#     X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 2
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.7801998183469573
Fold 2: Accuracy = 0.77
Mean accuracy: 0.7750999091734787
Standard deviation: 0.005099909173478634

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Wdbc

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml
import openml

# Load the dataset by ID
dataset_id = 1510 # ID of the "Tic-Tac-Toe" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Encoder_X = LabelEncoder()
# for col in X.columns:
#     X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 2
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.9614035087719298
Fold 2: Accuracy = 0.9507042253521126
Mean accuracy: 0.9560538670620212
Standard deviation: 0.0053496417099085924

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Wisconsin

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml
import openml

# Load the dataset by ID
dataset_id = 15 # ID of the "Wisconsin" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 2
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.9571428571428572
Fold 2: Accuracy = 0.9512893982808023
Mean accuracy: 0.9542161277118297
Standard deviation: 0.0029267294310274528

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

## Folds (5)

### Appendicitis

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 1462  # ID of the "appendicitis" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.9781818181818182
Fold 2: Accuracy = 0.9890909090909091
Fold 3: Accuracy = 0.9671532846715328
Fold 4: Accuracy = 0.9781021897810219
Fold 5: Accuracy = 0.9854014598540146
Mean accuracy: 0.9795859323158593
Standard deviation: 0.007522083486645915

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Australian

In [ ]:
from tensorflow import keras
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras

# Load the dataset by ID
dataset_id = 40981  # ID of the "australian" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.8405797101449275
Fold 2: Accuracy = 0.8405797101449275
Fold 3: Accuracy = 0.8768115942028986
Fold 4: Accuracy = 0.8478260869565217
Fold 5: Accuracy = 0.8695652173913043
Mean accuracy: 0.855072463768116
Standard deviation: 0.015200128234350038

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Banana

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 1460  # ID of the "banana" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.7141509433962264
Fold 2: Accuracy = 0.7037735849056603
Fold 3: Accuracy = 0.7660377358490567
Fold 4: Accuracy = 0.7245283018867924
Fold 5: Accuracy = 0.7584905660377359
Mean accuracy: 0.7333962264150944
Standard deviation: 0.024583392414946954

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Bands

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
import openml

# Load the dataset by ID
dataset_id = 6332  # ID of the "Bands" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# print(X.head(5))

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.7129629629629629
Fold 2: Accuracy = 0.7037037037037037
Fold 3: Accuracy = 0.7129629629629629
Fold 4: Accuracy = 0.6388888888888888
Fold 5: Accuracy = 0.7407407407407407
Mean accuracy: 0.7018518518518517
Standard deviation: 0.03384382756017975

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Breast

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
import openml

# Load the dataset by ID
dataset_id = 844  # ID of the "breastTumor" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# print(X.head(5))

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.6206896551724138
Fold 2: Accuracy = 0.6140350877192983
Fold 3: Accuracy = 0.5789473684210527
Fold 4: Accuracy = 0.5614035087719298
Fold 5: Accuracy = 0.6666666666666666
Mean accuracy: 0.6083484573502722
Standard deviation: 0.03647988128751804

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Bupa

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Buppa.csv to Buppa.csv

In [ ]:
import pandas as pd
df = pd.read_csv("Buppa.csv")

In [ ]:
df.head()

   mcv  alkphos  sgpt  sgot  gammagt  drinks  selector
0   85       92    45    27       31     0.0         1
1   85       64    59    32       23     0.0         2
2   86       54    33    16       54     0.0         2
3   91       78    34    24       36     0.0         2
4   87       70    12    28       10     0.0         2

In [ ]:
# Split the DataFrame into X and y variables
X = df.drop('selector', axis=1)  # Drop the 'selector' column to get features (X)
y = df['selector']  # Get the 'selector' column as the target variable (y)
print(X.head())
print(y.head())

   mcv  alkphos  sgpt  sgot  gammagt  drinks
0   85       92    45    27       31     0.0
1   85       64    59    32       23     0.0
2   86       54    33    16       54     0.0
3   91       78    34    24       36     0.0
4   87       70    12    28       10     0.0
0    1
1    2
2    2
3    2
4    2
Name: selector, dtype: int64

In [ ]:
from tensorflow import keras
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras


# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.6363636363636364
Fold 2: Accuracy = 0.5454545454545454
Fold 3: Accuracy = 0.8181818181818182
Fold 4: Accuracy = 0.36363636363636365
Fold 5: Accuracy = 0.6363636363636364
Mean accuracy: 0.6
Standard deviation: 0.1477097891751993

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Chess

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 3 # ID of the "chess" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.95
Fold 2: Accuracy = 0.9640062597809077
Fold 3: Accuracy = 0.9780907668231612
Fold 4: Accuracy = 0.9812206572769953
Fold 5: Accuracy = 0.9702660406885759
Mean accuracy: 0.9687167449139279
Standard deviation: 0.011127673960867552

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Crx

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 29 # ID of the "credit card approval" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.7971014492753623
Fold 2: Accuracy = 0.7971014492753623
Fold 3: Accuracy = 0.7391304347826086
Fold 4: Accuracy = 0.8188405797101449
Fold 5: Accuracy = 0.8405797101449275
Mean accuracy: 0.7985507246376811
Standard deviation: 0.033802619680262616

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### GermanCredit

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving GermanCredit.csv to GermanCredit.csv

In [ ]:
import pandas as pd
df = pd.read_csv("GermanCredit.csv")

In [ ]:
df.head(2)

,status,duration,credit_history,purpose,amount,savings,employment_duration,installment_rate,personal_status_sex,other_debtors,...,property,age,other_installment_plans,housing,number_credits,job,people_liable,telephone,foreign_worker,credit_risk
0,... < 100 DM,6,critical account/other credits existing,domestic appliances,1169,unknown/no savings account,... >= 7 years,4,male : single,none,...,real estate,67,none,own,2,skilled employee/official,1,yes,yes,1
1,0 <= ... < 200 DM,48,existing credits paid back duly till now,domestic appliances,5951,... < 100 DM,1 <= ... < 4 years,2,female : divorced/separated/married,none,...,real estate,22,none,own,1,skilled employee/official,1,no,yes,0

In [ ]:
# Split the DataFrame into X and y variables
X = df.drop('credit_risk', axis=1)  # Drop the 'selector' column to get features (X)
y = df['credit_risk']  # Get the 'selector' column as the target variable (y)
print(X.head())
print(y.head())

                status  duration                            credit_history  \
0         ... < 100 DM         6   critical account/other credits existing
1    0 <= ... < 200 DM        48  existing credits paid back duly till now
2  no checking account        12   critical account/other credits existing
3         ... < 100 DM        42  existing credits paid back duly till now
4         ... < 100 DM        24           delay in paying off in the past

               purpose  amount                     savings  \
0  domestic appliances    1169  unknown/no savings account
1  domestic appliances    5951                ... < 100 DM
2           retraining    2096                ... < 100 DM
3     radio/television    7882                ... < 100 DM
4            car (new)    4870                ... < 100 DM

  employment_duration  installment_rate                  personal_status_sex  \
0      ... >= 7 years                 4                        male : single
1  1 <= ... < 4 years                 2  female : divorced/separated/married
2  4 <= ... < 7 years                 2                        male : single
3  4 <= ... < 7 years                 2                        male : single
4  1 <= ... < 4 years                 3                        male : single

  other_debtors  present_residence  \
0          none                  4
1          none                  2
2          none                  3
3     guarantor                  4
4          none                  4

                                            property  age  \
0                                        real estate   67
1                                        real estate   22
2                                        real estate   49
3  building society savings agreement/life insurance   45
4                                unknown/no property   53

  other_installment_plans   housing  number_credits  \
0                    none       own               2
1                    none       own               1
2                    none       own               1
3                    none  for free               1
4                    none  for free               2

                         job  people_liable telephone foreign_worker
0  skilled employee/official              1       yes            yes
1  skilled employee/official              1        no            yes
2       unskilled - resident              2        no            yes
3  skilled employee/official              2        no            yes
4  skilled employee/official              2        no            yes
0    1
1    0
2    1
3    1
4    0
Name: credit_risk, dtype: int64

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml

# Load the dataset by ID
# dataset_id = 844  # ID of the "GermanCredit" dataset on OpenML
# dataset = openml.datasets.get_dataset(dataset_id)

# # Access the data and target variables
# X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# print(X.head(5))

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.755
Fold 2: Accuracy = 0.7
Fold 3: Accuracy = 0.65
Fold 4: Accuracy = 0.735
Fold 5: Accuracy = 0.725
Mean accuracy: 0.713
Standard deviation: 0.03613862199918529

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Haberman

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 43  # ID of the "Haberman" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.7096774193548387
Fold 2: Accuracy = 0.7704918032786885
Fold 3: Accuracy = 0.7377049180327869
Fold 4: Accuracy = 0.7540983606557377
Fold 5: Accuracy = 0.7213114754098361
Mean accuracy: 0.7386567953463776
Standard deviation: 0.0218791229085337

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Statlog (Heart)

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 53  # ID of the "Heart" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.6481481481481481
Fold 2: Accuracy = 0.6481481481481481
Fold 3: Accuracy = 0.6481481481481481
Fold 4: Accuracy = 0.5740740740740741
Fold 5: Accuracy = 0.6296296296296297
Mean accuracy: 0.6296296296296297
Standard deviation: 0.028688765527462346

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Hepatitis

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 55  # ID of the "Hepatitis" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.8064516129032258
Fold 2: Accuracy = 0.7096774193548387
Fold 3: Accuracy = 0.7419354838709677
Fold 4: Accuracy = 0.7419354838709677
Fold 5: Accuracy = 0.7741935483870968
Mean accuracy: 0.7548387096774194
Standard deviation: 0.032896900087695365

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Housevote

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 56  # ID of the "Hepatitis" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.9080459770114943
Fold 2: Accuracy = 0.896551724137931
Fold 3: Accuracy = 0.9195402298850575
Fold 4: Accuracy = 0.8505747126436781
Fold 5: Accuracy = 0.8390804597701149
Mean accuracy: 0.8827586206896552
Standard deviation: 0.032019283395825576

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Ionosphere

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 59 # ID of the "Hepatitis" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.8028169014084507
Fold 2: Accuracy = 0.6428571428571429
Fold 3: Accuracy = 0.8
Fold 4: Accuracy = 0.8
Fold 5: Accuracy = 0.8428571428571429
Mean accuracy: 0.7777062374245474
Standard deviation: 0.06935919251200896

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Mammographic

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 45557# ID of the "Mammographic" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
WARNING:root:Received uncompressed content from OpenML for https://api.openml.org/data/v1/download/22116525/Mammographic-Mass-Data-Set.arff.
WARNING:openml.datasets.functions:Could not download file from http://openml1.win.tue.nl/dataset45557/dataset_45557.pq: Bucket does not exist or is private.
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.7823834196891192
Fold 2: Accuracy = 0.7447916666666666
Fold 3: Accuracy = 0.7604166666666666
Fold 4: Accuracy = 0.7708333333333334
Fold 5: Accuracy = 0.7552083333333334
Mean accuracy: 0.7627266839378238
Standard deviation: 0.012927734874600125

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Monk-2

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 333 # ID of the "Monk-2" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.6517857142857143
Fold 2: Accuracy = 0.7567567567567568
Fold 3: Accuracy = 0.5945945945945946
Fold 4: Accuracy = 0.8378378378378378
Fold 5: Accuracy = 0.7117117117117117
Mean accuracy: 0.710537323037323
Standard deviation: 0.0839493944233383

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Mushroom

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 24 # ID of the "Mushroom" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(

Fold 1: Accuracy = 1.0
Fold 2: Accuracy = 1.0
Fold 3: Accuracy = 1.0
Fold 4: Accuracy = 1.0
Fold 5: Accuracy = 1.0
Mean accuracy: 1.0
Standard deviation: 0.0

### Phoneme

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml
import openml

# Load the dataset by ID
dataset_id = 1489 # ID of the "Phoneme" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.8279370952821462
Fold 2: Accuracy = 0.8057354301572618
Fold 3: Accuracy = 0.8066604995374653
Fold 4: Accuracy = 0.8066604995374653
Fold 5: Accuracy = 0.8027777777777778
Mean accuracy: 0.8099542604584233
Standard deviation: 0.009103631177522125

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Pima Indians Diabetes

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml
import openml

# Load the dataset by ID
dataset_id = 37 # ID of the "Phoneme" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Encoder_X = LabelEncoder()
# for col in X.columns:
#     X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.7207792207792207
Fold 2: Accuracy = 0.7662337662337663
Fold 3: Accuracy = 0.7337662337662337
Fold 4: Accuracy = 0.7843137254901961
Fold 5: Accuracy = 0.7254901960784313
Mean accuracy: 0.7461166284695696
Standard deviation: 0.02483418468002585

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Saheart

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml
import openml

# Load the dataset by ID
dataset_id = 1498 # ID of the "Saheart" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.7741935483870968
Fold 2: Accuracy = 0.7096774193548387
Fold 3: Accuracy = 0.8043478260869565
Fold 4: Accuracy = 0.6847826086956522
Fold 5: Accuracy = 0.6086956521739131
Mean accuracy: 0.7163394109396914
Standard deviation: 0.06887666521760147

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Sonar

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml
import openml

# Load the dataset by ID
dataset_id = 40 # ID of the "Sonar" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Encoder_X = LabelEncoder()
# for col in X.columns:
#     X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.8809523809523809
Fold 2: Accuracy = 0.8571428571428571
Fold 3: Accuracy = 0.8095238095238095
Fold 4: Accuracy = 0.8292682926829268
Fold 5: Accuracy = 0.7317073170731707
Mean accuracy: 0.821718931475029
Standard deviation: 0.05112975773067395

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Spambase

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml
import openml

# Load the dataset by ID
dataset_id = 44 # ID of the "Spambase" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Encoder_X = LabelEncoder()
# for col in X.columns:
#     X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.9359391965255157
Fold 2: Accuracy = 0.9326086956521739
Fold 3: Accuracy = 0.9173913043478261
Fold 4: Accuracy = 0.9326086956521739
Fold 5: Accuracy = 0.9347826086956522
Mean accuracy: 0.9306661001746683
Standard deviation: 0.006760454809425919

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### SPECTFHeart

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml
import openml

# Load the dataset by ID
dataset_id = 1600 # ID of the "SPECTF Heart" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Encoder_X = LabelEncoder()
# for col in X.columns:
#     X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.7037037037037037
Fold 2: Accuracy = 0.7222222222222222
Fold 3: Accuracy = 0.6415094339622641
Fold 4: Accuracy = 0.7547169811320755
Fold 5: Accuracy = 0.5849056603773585
Mean accuracy: 0.6814116002795247
Standard deviation: 0.06073170986160763

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Tic-Tac-Toe

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml
import openml

# Load the dataset by ID
dataset_id = 50 # ID of the "Tic-Tac-Toe" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.6354166666666666
Fold 2: Accuracy = 0.6041666666666666
Fold 3: Accuracy = 0.7291666666666666
Fold 4: Accuracy = 0.6335078534031413
Fold 5: Accuracy = 0.6178010471204188
Mean accuracy: 0.644011780104712
Standard deviation: 0.044068580065640454

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Titanic

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml
import openml

# Load the dataset by ID
dataset_id = 40704 # ID of the "Tic-Tac-Toe" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Encoder_X = LabelEncoder()
# for col in X.columns:
#     X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.7256235827664399
Fold 2: Accuracy = 0.7886363636363637
Fold 3: Accuracy = 0.7886363636363637
Fold 4: Accuracy = 0.7727272727272727
Fold 5: Accuracy = 0.7772727272727272
Mean accuracy: 0.7705792620078334
Standard deviation: 0.02333472674707963

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Wdbc

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml
import openml

# Load the dataset by ID
dataset_id = 1510 # ID of the "Tic-Tac-Toe" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Encoder_X = LabelEncoder()
# for col in X.columns:
#     X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.956140350877193
Fold 2: Accuracy = 0.9824561403508771
Fold 3: Accuracy = 0.9824561403508771
Fold 4: Accuracy = 0.9736842105263158
Fold 5: Accuracy = 0.9292035398230089
Mean accuracy: 0.9647880763856544
Standard deviation: 0.020221298524352973

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Wisconsin

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml
import openml

# Load the dataset by ID
dataset_id = 15 # ID of the "Wisconsin" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /dataset15/dataset_15.pq
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.9571428571428572
Fold 2: Accuracy = 0.9785714285714285
Fold 3: Accuracy = 0.9571428571428572
Fold 4: Accuracy = 0.9571428571428572
Fold 5: Accuracy = 0.935251798561151
Mean accuracy: 0.9570503597122302
Standard deviation: 0.013699338235285031

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

## Fold (10)

### Appendicitis

In [ ]:
from tensorflow import keras
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras

# Load the dataset by ID
dataset_id = 1462  # ID of the "appendicitis" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 10
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.9927536231884058
Fold 2: Accuracy = 0.9637681159420289
Fold 3: Accuracy = 0.9854014598540146
Fold 4: Accuracy = 0.9927007299270073
Fold 5: Accuracy = 0.9708029197080292
Fold 6: Accuracy = 0.9708029197080292
Fold 7: Accuracy = 0.9781021897810219
Fold 8: Accuracy = 0.9781021897810219
Fold 9: Accuracy = 0.9854014598540146
Fold 10: Accuracy = 0.9854014598540146
Mean accuracy: 0.9803237067597588
Standard deviation: 0.009221132735358082

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Australian

In [ ]:
from tensorflow import keras
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras

# Load the dataset by ID
dataset_id = 40981  # ID of the "australian" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 10
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.8405797101449275
Fold 2: Accuracy = 0.855072463768116
Fold 3: Accuracy = 0.8405797101449275
Fold 4: Accuracy = 0.8405797101449275
Fold 5: Accuracy = 0.8405797101449275
Fold 6: Accuracy = 0.8840579710144928
Fold 7: Accuracy = 0.8985507246376812
Fold 8: Accuracy = 0.7971014492753623
Fold 9: Accuracy = 0.8405797101449275
Fold 10: Accuracy = 0.8985507246376812
Mean accuracy: 0.8536231884057971
Standard deviation: 0.03001784808291013

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Banana

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 1460  # ID of the "banana" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 10
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.7132075471698113
Fold 2: Accuracy = 0.7075471698113207
Fold 3: Accuracy = 0.7132075471698113
Fold 4: Accuracy = 0.7
Fold 5: Accuracy = 0.7622641509433963
Fold 6: Accuracy = 0.720754716981132
Fold 7: Accuracy = 0.7283018867924528
Fold 8: Accuracy = 0.730188679245283
Fold 9: Accuracy = 0.6924528301886792
Fold 10: Accuracy = 0.7037735849056603
Mean accuracy: 0.7171698113207545
Standard deviation: 0.01883865654498959

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Bands

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
import openml

# Load the dataset by ID
dataset_id = 6332  # ID of the "Bands" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# print(X.head(5))

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 10
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.7407407407407407
Fold 2: Accuracy = 0.6851851851851852
Fold 3: Accuracy = 0.7407407407407407
Fold 4: Accuracy = 0.6481481481481481
Fold 5: Accuracy = 0.7407407407407407
Fold 6: Accuracy = 0.7037037037037037
Fold 7: Accuracy = 0.6481481481481481
Fold 8: Accuracy = 0.5740740740740741
Fold 9: Accuracy = 0.7222222222222222
Fold 10: Accuracy = 0.7777777777777778
Mean accuracy: 0.6981481481481482
Standard deviation: 0.05740740740740741

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Breast

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
import openml

# Load the dataset by ID
dataset_id = 844  # ID of the "breastTumor" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# print(X.head(5))

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 10
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.6551724137931034
Fold 2: Accuracy = 0.5862068965517241
Fold 3: Accuracy = 0.5517241379310345
Fold 4: Accuracy = 0.6551724137931034
Fold 5: Accuracy = 0.5862068965517241
Fold 6: Accuracy = 0.6206896551724138
Fold 7: Accuracy = 0.5714285714285714
Fold 8: Accuracy = 0.5714285714285714
Fold 9: Accuracy = 0.7142857142857143
Fold 10: Accuracy = 0.6428571428571429
Mean accuracy: 0.6155172413793103
Standard deviation: 0.04832170840036584

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Bupa

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Buppa.csv to Buppa.csv

In [ ]:
import pandas as pd
df = pd.read_csv("Buppa.csv")

In [ ]:
df.head()

   mcv  alkphos  sgpt  sgot  gammagt  drinks  selector
0   85       92    45    27       31     0.0         1
1   85       64    59    32       23     0.0         2
2   86       54    33    16       54     0.0         2
3   91       78    34    24       36     0.0         2
4   87       70    12    28       10     0.0         2

In [ ]:
# Split the DataFrame into X and y variables
X = df.drop('selector', axis=1)  # Drop the 'selector' column to get features (X)
y = df['selector']  # Get the 'selector' column as the target variable (y)
print(X.head())
print(y.head())

   mcv  alkphos  sgpt  sgot  gammagt  drinks
0   85       92    45    27       31     0.0
1   85       64    59    32       23     0.0
2   86       54    33    16       54     0.0
3   91       78    34    24       36     0.0
4   87       70    12    28       10     0.0
0    1
1    2
2    2
3    2
4    2
Name: selector, dtype: int64

In [ ]:
from tensorflow import keras
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras


# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 10
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.8333333333333334
Fold 2: Accuracy = 0.3333333333333333
Fold 3: Accuracy = 0.8333333333333334
Fold 4: Accuracy = 0.3333333333333333
Fold 5: Accuracy = 1.0
Fold 6: Accuracy = 0.8
Fold 7: Accuracy = 0.2
Fold 8: Accuracy = 0.6
Fold 9: Accuracy = 0.8
Fold 10: Accuracy = 0.4
Mean accuracy: 0.6133333333333334
Standard deviation: 0.26255158223353625

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Chess

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 3 # ID of the "chess" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 10
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.953125
Fold 2: Accuracy = 0.965625
Fold 3: Accuracy = 0.984375
Fold 4: Accuracy = 0.9875
Fold 5: Accuracy = 0.978125
Fold 6: Accuracy = 0.9875
Fold 7: Accuracy = 0.9905956112852664
Fold 8: Accuracy = 0.9780564263322884
Fold 9: Accuracy = 0.9843260188087775
Fold 10: Accuracy = 0.9843260188087775
Mean accuracy: 0.9793554075235111
Standard deviation: 0.011015356734897966

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Crx

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 29 # ID of the "credit card approval" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 10
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.8405797101449275
Fold 2: Accuracy = 0.7971014492753623
Fold 3: Accuracy = 0.8695652173913043
Fold 4: Accuracy = 0.7971014492753623
Fold 5: Accuracy = 0.8260869565217391
Fold 6: Accuracy = 0.7681159420289855
Fold 7: Accuracy = 0.8405797101449275
Fold 8: Accuracy = 0.8405797101449275
Fold 9: Accuracy = 0.855072463768116
Fold 10: Accuracy = 0.8115942028985508
Mean accuracy: 0.8246376811594203
Standard deviation: 0.029309780313270552

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### GermanCredit

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving GermanCredit.csv to GermanCredit.csv

In [ ]:
import pandas as pd
df = pd.read_csv("GermanCredit.csv")

In [ ]:
df.head(2)

,status,duration,credit_history,purpose,amount,savings,employment_duration,installment_rate,personal_status_sex,other_debtors,...,property,age,other_installment_plans,housing,number_credits,job,people_liable,telephone,foreign_worker,credit_risk
0,... < 100 DM,6,critical account/other credits existing,domestic appliances,1169,unknown/no savings account,... >= 7 years,4,male : single,none,...,real estate,67,none,own,2,skilled employee/official,1,yes,yes,1
1,0 <= ... < 200 DM,48,existing credits paid back duly till now,domestic appliances,5951,... < 100 DM,1 <= ... < 4 years,2,female : divorced/separated/married,none,...,real estate,22,none,own,1,skilled employee/official,1,no,yes,0

In [ ]:
# Split the DataFrame into X and y variables
X = df.drop('credit_risk', axis=1)  # Drop the 'selector' column to get features (X)
y = df['credit_risk']  # Get the 'selector' column as the target variable (y)
print(X.head())
print(y.head())

                status  duration                            credit_history  \
0         ... < 100 DM         6   critical account/other credits existing
1    0 <= ... < 200 DM        48  existing credits paid back duly till now
2  no checking account        12   critical account/other credits existing
3         ... < 100 DM        42  existing credits paid back duly till now
4         ... < 100 DM        24           delay in paying off in the past

               purpose  amount                     savings  \
0  domestic appliances    1169  unknown/no savings account
1  domestic appliances    5951                ... < 100 DM
2           retraining    2096                ... < 100 DM
3     radio/television    7882                ... < 100 DM
4            car (new)    4870                ... < 100 DM

  employment_duration  installment_rate                  personal_status_sex  \
0      ... >= 7 years                 4                        male : single
1  1 <= ... < 4 years                 2  female : divorced/separated/married
2  4 <= ... < 7 years                 2                        male : single
3  4 <= ... < 7 years                 2                        male : single
4  1 <= ... < 4 years                 3                        male : single

  other_debtors  present_residence  \
0          none                  4
1          none                  2
2          none                  3
3     guarantor                  4
4          none                  4

                                            property  age  \
0                                        real estate   67
1                                        real estate   22
2                                        real estate   49
3  building society savings agreement/life insurance   45
4                                unknown/no property   53

  other_installment_plans   housing  number_credits  \
0                    none       own               2
1                    none       own               1
2                    none       own               1
3                    none  for free               1
4                    none  for free               2

                         job  people_liable telephone foreign_worker
0  skilled employee/official              1       yes            yes
1  skilled employee/official              1        no            yes
2       unskilled - resident              2        no            yes
3  skilled employee/official              2        no            yes
4  skilled employee/official              2        no            yes
0    1
1    0
2    1
3    1
4    0
Name: credit_risk, dtype: int64

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml

# Load the dataset by ID
# dataset_id = 844  # ID of the "GermanCredit" dataset on OpenML
# dataset = openml.datasets.get_dataset(dataset_id)

# # Access the data and target variables
# X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# print(X.head(5))

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 10
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.78
Fold 2: Accuracy = 0.72
Fold 3: Accuracy = 0.64
Fold 4: Accuracy = 0.77
Fold 5: Accuracy = 0.68
Fold 6: Accuracy = 0.65
Fold 7: Accuracy = 0.71
Fold 8: Accuracy = 0.78
Fold 9: Accuracy = 0.74
Fold 10: Accuracy = 0.7
Mean accuracy: 0.7170000000000001
Standard deviation: 0.04838388161361178

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Haberman

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 43  # ID of the "Haberman" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 10
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.6774193548387096
Fold 2: Accuracy = 0.7741935483870968
Fold 3: Accuracy = 0.7741935483870968
Fold 4: Accuracy = 0.7741935483870968
Fold 5: Accuracy = 0.8709677419354839
Fold 6: Accuracy = 0.5806451612903226
Fold 7: Accuracy = 0.8
Fold 8: Accuracy = 0.7333333333333333
Fold 9: Accuracy = 0.6666666666666666
Fold 10: Accuracy = 0.7666666666666667
Mean accuracy: 0.7418279569892473
Standard deviation: 0.07724659637573703

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Statlog (Heart)

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 53  # ID of the "Heart" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 10
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.7407407407407407
Fold 2: Accuracy = 0.6666666666666666
Fold 3: Accuracy = 0.7037037037037037
Fold 4: Accuracy = 0.6296296296296297
Fold 5: Accuracy = 0.6666666666666666
Fold 6: Accuracy = 0.6666666666666666
Fold 7: Accuracy = 0.7037037037037037
Fold 8: Accuracy = 0.5185185185185185
Fold 9: Accuracy = 0.7037037037037037
Fold 10: Accuracy = 0.6666666666666666
Mean accuracy: 0.6666666666666667
Standard deviation: 0.0573775310549247

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Hepatitis

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 55  # ID of the "Hepatitis" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 10
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.875
Fold 2: Accuracy = 0.6875
Fold 3: Accuracy = 0.75
Fold 4: Accuracy = 0.6875
Fold 5: Accuracy = 0.875
Fold 6: Accuracy = 0.8
Fold 7: Accuracy = 0.8
Fold 8: Accuracy = 0.6666666666666666
Fold 9: Accuracy = 0.7333333333333333
Fold 10: Accuracy = 0.8
Mean accuracy: 0.7675
Standard deviation: 0.071219535397405

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Housevote

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 56  # ID of the "Hepatitis" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 10
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.9090909090909091
Fold 2: Accuracy = 0.9090909090909091
Fold 3: Accuracy = 0.8409090909090909
Fold 4: Accuracy = 0.9545454545454546
Fold 5: Accuracy = 0.8863636363636364
Fold 6: Accuracy = 0.9534883720930233
Fold 7: Accuracy = 0.7906976744186046
Fold 8: Accuracy = 0.9069767441860465
Fold 9: Accuracy = 0.8604651162790697
Fold 10: Accuracy = 0.7906976744186046
Mean accuracy: 0.8802325581395347
Standard deviation: 0.0559261557194329

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Ionosphere

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 59 # ID of the "Hepatitis" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 10
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.8055555555555556
Fold 2: Accuracy = 0.8285714285714286
Fold 3: Accuracy = 0.8571428571428571
Fold 4: Accuracy = 0.5714285714285714
Fold 5: Accuracy = 0.8285714285714286
Fold 6: Accuracy = 0.7142857142857143
Fold 7: Accuracy = 0.7142857142857143
Fold 8: Accuracy = 0.9142857142857143
Fold 9: Accuracy = 0.8285714285714286
Fold 10: Accuracy = 0.8285714285714286
Mean accuracy: 0.7891269841269841
Standard deviation: 0.09240089377310172

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Mammographic

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 45557# ID of the "Mammographic" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 10
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
WARNING:root:Received uncompressed content from OpenML for https://api.openml.org/data/v1/download/22116525/Mammographic-Mass-Data-Set.arff.
WARNING:openml.datasets.functions:Could not download file from http://openml1.win.tue.nl/dataset45557/dataset_45557.pq: Bucket does not exist or is private.
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.8041237113402062
Fold 2: Accuracy = 0.7708333333333334
Fold 3: Accuracy = 0.7604166666666666
Fold 4: Accuracy = 0.7708333333333334
Fold 5: Accuracy = 0.75
Fold 6: Accuracy = 0.7916666666666666
Fold 7: Accuracy = 0.75
Fold 8: Accuracy = 0.7916666666666666
Fold 9: Accuracy = 0.6979166666666666
Fold 10: Accuracy = 0.78125
Mean accuracy: 0.766870704467354
Standard deviation: 0.028672618070771524

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Monk-2

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 333 # ID of the "Monk-2" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 10
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.6071428571428571
Fold 2: Accuracy = 0.6964285714285714
Fold 3: Accuracy = 0.7678571428571429
Fold 4: Accuracy = 0.7857142857142857
Fold 5: Accuracy = 0.6607142857142857
Fold 6: Accuracy = 0.5714285714285714
Fold 7: Accuracy = 0.8363636363636363
Fold 8: Accuracy = 0.8909090909090909
Fold 9: Accuracy = 0.7090909090909091
Fold 10: Accuracy = 0.7272727272727273
Mean accuracy: 0.7252922077922077
Standard deviation: 0.09387839215214194

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Mushroom

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 24 # ID of the "Mushroom" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 10
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(

Fold 1: Accuracy = 1.0
Fold 2: Accuracy = 1.0
Fold 3: Accuracy = 1.0
Fold 4: Accuracy = 1.0
Fold 5: Accuracy = 1.0
Fold 6: Accuracy = 1.0
Fold 7: Accuracy = 1.0
Fold 8: Accuracy = 1.0
Fold 9: Accuracy = 1.0
Fold 10: Accuracy = 1.0
Mean accuracy: 1.0
Standard deviation: 0.0

### Phoneme

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml
import openml

# Load the dataset by ID
dataset_id = 1489 # ID of the "Phoneme" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 10
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.8280961182994455
Fold 2: Accuracy = 0.8299445471349353
Fold 3: Accuracy = 0.8243992606284658
Fold 4: Accuracy = 0.7985212569316081
Fold 5: Accuracy = 0.774074074074074
Fold 6: Accuracy = 0.7907407407407407
Fold 7: Accuracy = 0.8
Fold 8: Accuracy = 0.8185185185185185
Fold 9: Accuracy = 0.7870370370370371
Fold 10: Accuracy = 0.8148148148148148
Mean accuracy: 0.806614636817964
Standard deviation: 0.01826029670240646

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Pima Indians Diabetes

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml
import openml

# Load the dataset by ID
dataset_id = 37 # ID of the "Phoneme" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Encoder_X = LabelEncoder()
# for col in X.columns:
#     X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 10
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.6883116883116883
Fold 2: Accuracy = 0.7662337662337663
Fold 3: Accuracy = 0.7012987012987013
Fold 4: Accuracy = 0.8441558441558441
Fold 5: Accuracy = 0.7922077922077922
Fold 6: Accuracy = 0.6883116883116883
Fold 7: Accuracy = 0.8051948051948052
Fold 8: Accuracy = 0.7662337662337663
Fold 9: Accuracy = 0.7368421052631579
Fold 10: Accuracy = 0.7105263157894737
Mean accuracy: 0.7499316473000683
Standard deviation: 0.05092575465887315

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Saheart

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml
import openml

# Load the dataset by ID
dataset_id = 1498 # ID of the "Saheart" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 10
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.7446808510638298
Fold 2: Accuracy = 0.7872340425531915
Fold 3: Accuracy = 0.6739130434782609
Fold 4: Accuracy = 0.6956521739130435
Fold 5: Accuracy = 0.8043478260869565
Fold 6: Accuracy = 0.782608695652174
Fold 7: Accuracy = 0.6739130434782609
Fold 8: Accuracy = 0.6521739130434783
Fold 9: Accuracy = 0.5869565217391305
Fold 10: Accuracy = 0.6521739130434783
Mean accuracy: 0.7053654024051804
Standard deviation: 0.0676493946506324

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Sonar

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml
import openml

# Load the dataset by ID
dataset_id = 40 # ID of the "Sonar" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Encoder_X = LabelEncoder()
# for col in X.columns:
#     X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 10
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.8571428571428571
Fold 2: Accuracy = 0.8095238095238095
Fold 3: Accuracy = 0.8571428571428571
Fold 4: Accuracy = 0.8571428571428571
Fold 5: Accuracy = 0.7619047619047619
Fold 6: Accuracy = 0.8571428571428571
Fold 7: Accuracy = 0.9047619047619048
Fold 8: Accuracy = 0.7619047619047619
Fold 9: Accuracy = 0.85
Fold 10: Accuracy = 0.65
Mean accuracy: 0.8166666666666667
Standard deviation: 0.07017955591215443

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Spambase

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml
import openml

# Load the dataset by ID
dataset_id = 44 # ID of the "Spambase" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Encoder_X = LabelEncoder()
# for col in X.columns:
#     X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 10
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.9392624728850325
Fold 2: Accuracy = 0.9369565217391305
Fold 3: Accuracy = 0.9304347826086956
Fold 4: Accuracy = 0.9326086956521739
Fold 5: Accuracy = 0.8934782608695652
Fold 6: Accuracy = 0.95
Fold 7: Accuracy = 0.9239130434782609
Fold 8: Accuracy = 0.9456521739130435
Fold 9: Accuracy = 0.9304347826086956
Fold 10: Accuracy = 0.9369565217391305
Mean accuracy: 0.9319697255493729
Standard deviation: 0.01472020376154483

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### SPECTFHeart

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml
import openml

# Load the dataset by ID
dataset_id = 1600 # ID of the "SPECTF Heart" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Encoder_X = LabelEncoder()
# for col in X.columns:
#     X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 10
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.7037037037037037
Fold 2: Accuracy = 0.7407407407407407
Fold 3: Accuracy = 0.7407407407407407
Fold 4: Accuracy = 0.7037037037037037
Fold 5: Accuracy = 0.5555555555555556
Fold 6: Accuracy = 0.6666666666666666
Fold 7: Accuracy = 0.7407407407407407
Fold 8: Accuracy = 0.8076923076923077
Fold 9: Accuracy = 0.5769230769230769
Fold 10: Accuracy = 0.5769230769230769
Mean accuracy: 0.6813390313390313
Standard deviation: 0.0808661492610731

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Tic-Tac-Toe

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml
import openml

# Load the dataset by ID
dataset_id = 50 # ID of the "Tic-Tac-Toe" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 10
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.6041666666666666
Fold 2: Accuracy = 0.6875
Fold 3: Accuracy = 0.6041666666666666
Fold 4: Accuracy = 0.65625
Fold 5: Accuracy = 0.6770833333333334
Fold 6: Accuracy = 0.7395833333333334
Fold 7: Accuracy = 0.6875
Fold 8: Accuracy = 0.5520833333333334
Fold 9: Accuracy = 0.6105263157894737
Fold 10: Accuracy = 0.6526315789473685
Mean accuracy: 0.6471491228070175
Standard deviation: 0.051848941648571255

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Titanic

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml
import openml

# Load the dataset by ID
dataset_id = 40704 # ID of the "Tic-Tac-Toe" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Encoder_X = LabelEncoder()
# for col in X.columns:
#     X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 10
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.6742081447963801
Fold 2: Accuracy = 0.7772727272727272
Fold 3: Accuracy = 0.7818181818181819
Fold 4: Accuracy = 0.7863636363636364
Fold 5: Accuracy = 0.8181818181818182
Fold 6: Accuracy = 0.759090909090909
Fold 7: Accuracy = 0.7818181818181819
Fold 8: Accuracy = 0.7636363636363637
Fold 9: Accuracy = 0.7727272727272727
Fold 10: Accuracy = 0.7681818181818182
Mean accuracy: 0.7683299053887289
Standard deviation: 0.03498560118167958

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Wdbc

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml
import openml

# Load the dataset by ID
dataset_id = 1510 # ID of the "Tic-Tac-Toe" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Encoder_X = LabelEncoder()
# for col in X.columns:
#     X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 10
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.9473684210526315
Fold 2: Accuracy = 0.9649122807017544
Fold 3: Accuracy = 0.9824561403508771
Fold 4: Accuracy = 0.9824561403508771
Fold 5: Accuracy = 0.9824561403508771
Fold 6: Accuracy = 0.9824561403508771
Fold 7: Accuracy = 0.9824561403508771
Fold 8: Accuracy = 0.9649122807017544
Fold 9: Accuracy = 0.9649122807017544
Fold 10: Accuracy = 0.8928571428571429
Mean accuracy: 0.9647243107769423
Standard deviation: 0.026529816492407807

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

### Wisconsin

In [ ]:
import numpy as np
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from tensorflow import keras
import pandas as pd
# import openml
import openml

# Load the dataset by ID
dataset_id = 15 # ID of the "Wisconsin" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

Encoder_X = LabelEncoder()
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Create a neural network classifier (or use any other classifier of your choice)
classifier = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', random_state=42)

# Perform k-fold cross-validation
k = 10
kf = KFold(n_splits=k, shuffle=True, random_state=42)
scores = cross_val_score(classifier, X, y, cv=kf)

# Print the accuracy scores for each fold
for fold, score in enumerate(scores):
    print(f"Fold {fold+1}: Accuracy = {score}")

# Print the mean and standard deviation of the scores
print(f"Mean accuracy: {np.mean(scores)}")
print(f"Standard deviation: {np.std(scores)}")

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:437: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Fold 1: Accuracy = 0.9571428571428572
Fold 2: Accuracy = 0.9571428571428572
Fold 3: Accuracy = 0.9714285714285714
Fold 4: Accuracy = 0.9857142857142858
Fold 5: Accuracy = 0.9428571428571428
Fold 6: Accuracy = 0.9714285714285714
Fold 7: Accuracy = 0.9714285714285714
Fold 8: Accuracy = 0.9428571428571428
Fold 9: Accuracy = 0.9285714285714286
Fold 10: Accuracy = 0.9420289855072463
Mean accuracy: 0.9570600414078674
Standard deviation: 0.01697475111996609

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

# C3

### appendicitis

In [ ]:
# import tensorflow as tf
# tf.compat.v1.enable_eager_execution()

In [ ]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
import openml

# Load the dataset by ID
dataset_id = 1462  # ID of the "appendicitis" dataset on OpenML
dataset = openml.datasets.get_dataset(dataset_id)

# Access the data and target variables
X, y, _, _ = dataset.get_data(target=dataset.default_target_attribute)

# Perform data preprocessing (e.g., scaling)
scaler = StandardScaler()
X = scaler.fit_transform(X)

/usr/local/lib/python3.10/dist-packages/openml/datasets/functions.py:438: FutureWarning: Starting from Version 0.15 `download_data`, `download_qualities`, and `download_features_meta_data` will all be ``False`` instead of ``True`` by default to enable lazy loading. To disable this message until version 0.15 explicitly set `download_data`, `download_qualities`, and `download_features_meta_data` to a bool while calling `get_dataset`.
  warnings.warn(

In [ ]:
from sklearn.model_selection import train_test_split
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
print(X_train.shape, y_train.shape, X_test.shape,y_test.shape)

(1097, 4) (1097,) (275, 4) (275,)

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.neural_network import MLPClassifier

# Define a simple neural network model
model = MLPClassifier(hidden_layer_sizes=(4,), activation='relu', solver='adam', max_iter=1000)
model.fit(X_train, y_train)

MLPClassifier(hidden_layer_sizes=(4,), max_iter=1000)

In [ ]:
# Store the original model parameters for CrlB
original_params = model.coefs_
X_new_task, y_new_task = X, y
X_train_new_task, X_test_new_task, y_train_new_task, y_test_new_task = train_test_split(X_new_task, y_new_task, test_size=0.2, random_state=42)
# Train the model on the new task (assuming you have X_new_task and y_new_task)
model.fit(X_train_new_task, y_train_new_task)

# Calculate the Fisher Information for each parameter
fisher_information = []  # Calculate Fisher Information here

# Define the CrlB regularization strength
lambda_ = 0.01

# Calculate the CrlB loss
CrlB_loss = 0.0
for i, (original_param, fisher_info) in enumerate(zip(original_params, fisher_information)):
    CrlB_loss += (fisher_info * np.square(model.coefs_[i] - original_param)).sum()

# Get the original loss from the model (use appropriate loss function here)
original_loss = model.loss_

# Add CrlB loss to the original loss
total_loss = original_loss + lambda_ * CrlB_loss

# Set the loss function of the model to the combined loss
model.loss_ = total_loss

In [ ]:
from sklearn.metrics import accuracy_score
y_pred_new_task = model.predict(X_test_new_task)
accuracy_new_task = accuracy_score(y_test_new_task, y_pred_new_task)
print("Accuracy on the new task's test set:", accuracy_new_task)

Accuracy on the new task's test set: 0.9818181818181818